### ISSUE TITLE
Code signing Certificate

### ISSUE THREAD

**Issue by bliker** [cmderdev/cmder#100]
Windows is having some trust issues with the PS script and the binaries. For security and general usability it would be really nice to have them signed.

**If anyone of you scholars is in possession of code signing certificate and is willing to help. Please contact me.**

If you have other suggestion, apart from the 100$ one, do no hesitate to write here.

**Comment by Jackbennett** [comment]
Consolidating on #136 if there's any progress. Doesn't seem to be a great answer to the execution Policy no matter what.
