### ISSUE TITLE
using touch in cli doesn't work anymore with latest update

### ISSUE THREAD

**Issue by SOSANA** [cmderdev/cmder#1002]
Hi All,

Not sure what happened but I updated to latest version and now when using ```touch``` to create a new file won't work....

anyone else having this issue?

use ```ls``` in cli works still though

![image](https://cloud.githubusercontent.com/assets/2634185/16137215/5f391b9c-33ee-11e6-9d2c-82e87f388a57.png)

![image](https://cloud.githubusercontent.com/assets/2634185/16137277/d2a42d1a-33ee-11e6-8cac-e8b450c29d31.png)

**Comment by SOSANA** [comment]
@Stanzilla my next attempt my be to uninstall and reinstall, I can't remember if I had to add it to windows global variable program path or if this will happen on its own? if not what path am I looking to include if its needed. Also is there a way to keep our settings so I don't have reconfigure it again? or do you have suggestions I could do without uninstalling or reinstalling?

**Comment by Stanzilla** [comment]
It will add itself to the Path on its own, yes. And you can just download this https://ci.appveyor.com/api/buildjobs/h150iq3w7d4fk0or/artifacts/build/cmder.7z and unpack it into a new folder and tell me if it still happens.

**Comment by SOSANA** [comment]
Thanks @Stanzilla worked fine, only thing I notice is when I type ```git``` or ```npm`` it is not highlighted anymore, is there a setting to turn on so I can see color for ```npm i -g example```

**Comment by Stanzilla** [comment]
not sure about that, paging @vladimir-kotikov

**Comment by SOSANA** [comment]
@vladimir-kotikov @Stanzilla ya on command prompt when typing global vars like git, npm, atom, etc you would see highlighted text for these, not sure if its a manual setting now or if something else as of right now all text is grayed out 

![image](https://cloud.githubusercontent.com/assets/2634185/16168722/4c670876-34cf-11e6-9ef1-32ed6684d4b8.png)

**Comment by SOSANA** [comment]
Thanks for your help
