### ISSUE TITLE
after updating cmder

### ISSUE THREAD

**Issue by kwokandy** [cmderdev/cmder#1004]
Cmder is constantly asking me for an update. 

For the 5 times I tried , it is extracting the files and at the end I have this error...

![2016-06-20 15_05_48-bliker_cmder - gitter](https://cloud.githubusercontent.com/assets/4679470/16195202/cb3bb52c-36f8-11e6-9278-b99c14cef71f.png)

After the unsucessful update, cmder cannot be launched again. I have to reinstall everything.

Can anyone tell me how can I do the upgrade successfully or simply bypass it?

**Comment by Stanzilla** [comment]
Try updating manually from https://conemu.github.io/en/Downloads.html

**Comment by kwokandy** [comment]
done that buddy. it does not do anything ... If you have any other ideas, I'm all ears

**Comment by Jackbennett** [comment]
What's D:\? Do you have permission to create .exe files there? make any text file and rename it .exe does it work at the path `d:\cmder\cmder\vendor`?

**Comment by kwokandy** [comment]
`D drive`. I do have writing permission so all the programs that I have

**Comment by Jackbennett** [comment]
Is your anti-virus kicking in about those 3 files?

**Comment by kwokandy** [comment]
nope

**Comment by Jackbennett** [comment]
Can you delete the 3 existing exe's a copy them out manually, perhaps it's having trouble overwriting them.

**Comment by kwokandy** [comment]
done. It just gave me the same error. And I lost my config as well

**Comment by Jackbennett** [comment]
Get a fresh download of [160616](https://github.com/Maximus5/ConEmu/releases/tag/v16.06.19)

The hash should match: 

algo | hash
--- | ---
sha256 | 8F33446E189C1EF18A5EA0E1D33563CC4CBF35276D22187FD9152D8D8E333B93
sha1 | C039C6B7B3FC160738918360B2607BDA92783511

powershell `Get-FileHash ~\downloads\ConEmuPack.160619.7z -Algorithm SHA1` of you need a the command. But I think 7zip sticks that in you context menu.

**Comment by kwokandy** [comment]
I'm losing sanity. cmder looks good but in term of stability, it can gain improvement, much improvement actually... grrrhhh

**Comment by Jackbennett** [comment]
Ok I can't help you with that.

Your operating system it saying your access is denied to 3 exe files. There's nothing I can do. We don't even make those 3 files. or 7zip. Obviously conemu isn't running is it? since you're trying to replace its files. 

You wouldn't have lost your config if you just removed the 3 files I said.

**Comment by kwokandy** [comment]
Bud, I tried but I could not. That's an easy one to say...

**Comment by Mikkolehtimaki** [comment]
I have this same problem. The ideas here do not seem to work..

**Comment by MartiUK** [comment]
7-zip does not have the permissions to write those PEs, you are either running conemu/cmder at the same time or the permissions are broken. Whenever something like this happens, I suggest extracting cmder in a location your user can access, be it your user folder, your documents folder or as I have always done it onto your Desktop, Windows is 100% stupid with permissions, especially on the root of disks.

**Comment by kwokandy** [comment]
Sounds good @MartiUK . I will install winzip.

**Comment by MartiUK** [comment]
@kwokandy That's not what I was suggesting, but give it a try I guess.

**Comment by kwokandy** [comment]
Sorry in the middle of a few things. 

I've installed the cmder software on a separate folder and each time, I had the issue. Let's do that: 7zip, I don't know much about it but thinking about it now, it may not be reliable. 

My workaround for now is to have no upgrade. Since the last time when I almost lost all my hairs, cmder has been working like a treat.

I'll do a backup next week and once done:

1. Install winzip
2. Make the the upgrade
3. Keep you posted, regardless of the results
