### ISSUE TITLE
Lost my cursor in cmder and settings seem correct

### ISSUE THREAD

**Issue by codefoster** [cmderdev/cmder#1005]
I can no longer see my text cursor in cmder. I don't know what changed when I lost it, because it took me a while to notice. I've played with all of the settings under Settings | Features -> Text cursor and none seem to work. Any ideas on how to fix this?

**Comment by seiggy** [comment]
I'm also having the same issue. Windows 10 Pro build 14367. v1.2.9 of cmder, going to try v1.3 pre

**Comment by seiggy** [comment]
If I hit backspace as soon as the console opens, the cursor will appear though.

**Comment by codefoster** [comment]
I'm also on 14367, but have had the issue for a few builds. I am not able to use your backspace workaround.
