### ISSUE TITLE
issue with updating ConEmuPack.160619.7z

### ISSUE THREAD

**Issue by kwokandy** [cmderdev/cmder#1006]
Cmder is constantly asking me for an update. 

For the 5 times I tried , it is extracting the files and at the end I have this error...

![2016-06-20 15_05_48-bliker_cmder - gitter](https://cloud.githubusercontent.com/assets/4679470/16195202/cb3bb52c-36f8-11e6-9278-b99c14cef71f.png)

After the unsucessful update, cmder cannot be launched again. I have to reinstall everything.

Can anyone tell me how can I do the upgrade successfully or simply bypass it?

Edit: Jack Bennett tried to help me but to no avail. 

I've tried to resintall this package manually `ConEmuPack.160619.7Z` but I have the same issue.

The issue has not been sorted and yet my old issue has been closed. If you feel my issue is not important, please do not contribute to/ update / create this software. In customer services, there is a say that goes like that 'you will lose 10 customers because of an angry one'.

I spent times on it and to hear, that the issue is not your business is the least to say, insulting.

**Comment by Stanzilla** [comment]
Get something like LockHunter and inspect the files with it, it will tell you if any process is keeping a handle on them.

**Comment by kwokandy** [comment]
That's an answer. Thank you, Benjamin

**Comment by mrRosset** [comment]
Another possibility: Right click on the cmder folder and look if "read only" is checked. If this is the case uncheck it and press Apply (if it ask you say to apply the change to all subfolders and files).

**Comment by kwokandy** [comment]
Hi @mrRosset it seems it is due to 7zip that cannot update/extract the conemuexe file properly. I tried to reinstall the conemu exe from the portable version but it is still not doing the update... Carrying my investigation
