### ISSUE TITLE
Newbie: What do i have to do to make cmder run from 'Run' or from the default CMD

### ISSUE THREAD

**Issue by renoirfaria** [cmderdev/cmder#1007]
Hello guys,

Sorry for the newbie question, i am learning some windows commands and cmder but i can't configure the cmder to run directly from the cmd by typing just 'cmder' or from the windows run (windows+r) and typing 'cmder'.

Sorry for the bad english.

**Comment by mrRosset** [comment]
Add the cmder folder (where the cmder.exe is) in you path

**Comment by renoirfaria** [comment]
Got it! To open cmder trough the run just copy all the cmder files to the 'bin' folder inside the folder of cmder then insert this folder into the path system variable.

1.open the command prompt with admin privileges

2.setx PATH "%PATH%;<cmderfolder>/bin" /M

3. test it typing cmder trought the run (windows+r)
