### ISSUE TITLE
High-lighting text and copying is broken

### ISSUE THREAD

**Issue by danwellman** [cmderdev/cmder#1008]
Since updating to version 1.2 (via auto-update) copy and pasting seems broken and weird.

In previous versions you would highlight some text and that text would be copied to the clipboard.

Now, you highlight some text and nothing happens. Then you right-click the text and it is automatically copied to the prompt.

This is awful. Sometimes I want to copy text and add something additional to the prompt, then paste in the new text. Other times I might want to copy it to a completely different application (which is still possible, but it means I have to remove the copied text from the Cmder prompt when I come back to it).

It was perfect before, please revert!

**Comment by Jackbennett** [comment]
I'm not sure I follow, these two lines describe the same things;

> In previous versions you would highlight some text and that text would be copied to the clipboard.

> Now, you highlight some text and nothing happens. Then you right-click the text and it is automatically copied to the prompt.

As far as I can recall. Highlighting text IS the copy command and will go on your clipboard. Right-click is paste. I don't think this has ever changed.

Normally windows cmd.exe or powershell.exe hosts, when "quickedit mode" is enabled. you get
1. Highlight
1. right-click copy
1. rightclick paste

In short. Just highlight, that is on your clipboard already at that point.

**Comment by danwellman** [comment]
Something has definitely changed between the last version and the current version. For me in any case, and there were no other changes to my system other than Cmder update.

Previously the process you describe above was like this:

1. Highlight text (that's it, it was copied automatically without right-click, and the highlight disappeared immediately)
2. Right-click to paste

Now it appears to work like this:

1. Highlight (highlight stays and doesn't go away)
2. Right-click to copy the text, remove the highlight and paste to the prompt

It's still a two-step process for me, but the difference now is that on right click the text is copied *and* pasted to the prompt with one click.

I'm on Windows 7 Pro btw, but I also notice the same issue on Windows 10

**Comment by vBm** [comment]
It's just a changed option. I've had the same issue and solution is to check it.

Preferences -> Keys & Macro -> Mark/Copy -> Select text with mouse (LeftClick+Drag) -> 
- [x] Reset selection on Left Button release
