### ISSUE TITLE
Add trailing backslash after tab completing directory name?

### ISSUE THREAD

**Issue by zerodburn** [cmderdev/cmder#1009]
I can't remember if it did this or not before the latest update, but is there a way to add a backslash when you do this? For e.g., say you wanted to cd up a directory and then into a directory called folder

If I do this:

cd ..\fol

then press tab

I'd like it to produce:

cd ..\folder\

but at the moment it does

cd ..\folder

Thanks

**Comment by Adyel** [comment]
Yes, I want this too. Windows 10 build in CMD support similar feature. If you press TAB it'll show Files/Directories

**Comment by zerodburn** [comment]
I've found it works fine if I use the GIT BASH profile

**Comment by daxgames** [comment]
Works as requested in the current version.  Closing.
