### ISSUE TITLE
{lamb} problem again... :-(

### ISSUE THREAD

**Issue by maral** [cmderdev/cmder#1012]
I have the same issue like #223, my prompt now looks like this:
![the console picture](http://image.prntscr.com/image/858d0bd02c35480a8d23d27eb7d7d654.png)
In mentioned issue it was solved by installing a newer version of clink (0.4.3). I have version 0.4.4 installed and the issue persists even when I downgrade clink to 0.4.3... Any ideas?

**Comment by maral** [comment]
Okay so it seems that it is due to the last update, which upgraded the Cmder somewhere, but my launch icon still targets the old version... I'm trying to find the newly installed version...

**Comment by maral** [comment]
So I rather downloaded the newest version from here and it works like a charm.

**Comment by johnkors** [comment]
.. downloading the newest clink helped me.

https://github.com/cmderdev/cmder/issues/223#issuecomment-90946902

**Comment by maxpou** [comment]
I've got the same problem, and update Clink did not work for me.
If your folder/project contain a **package.json** file, add this attributes: `name` and `version`.
