### ISSUE TITLE
Start .vbs to call .bat to run with cmder

### ISSUE THREAD

**Issue by maravento** [cmderdev/cmder#1015]
Hi. Great app, congratulations. 
we have a "test.vbs", to call "test.bat" to run with "cmder" (instead of cmd.exe). What is the procedure (step by step)?... Thanks

test.vbs

> Option Explicit
> On Error Resume next
> mensaje = MSGBOX ("Start Test", vbOKCancel)
> If mensaje = vbOK Then
> SCRIPT = "test.bat"
> Set objShell = CreateObject("Wscript.Shell")
> strPath = Wscript.ScriptFullName
> Set objFSO = CreateObject("Scripting.FileSystemObject")
> Set objFile = objFSO.GetFile(strPath)
> strFolder = objFSO.GetParentFolderName(objFile) 
> NewPath = objFSO.BuildPath(strFolder, SCRIPT)
> set objshell = createobject("wscript.shell")
> objshell.run NewPath, 1, true
> Else
> End If
> On Error GoTo 0

test.bat (with @echo off)

> set /p drive=Choose the drive usb letter:
> if exist %drive%: (goto target)
> :target
> attrib /d /s -r -h -s %drive%:*.*
> :: ext
> call:ext "_.ini_"
> call:ext "_.lnk_"
> exit
> :: funcion ext
> pause
> goto:eof
> :ext
> set ext=%1
> del /f/q/s %drive%:\"%ext%"
> goto:eof

**Comment by daxgames** [comment]
I don't understand the question.  There is no difference between running 
this in cmd and cmder is once cmder uses cmd as it's default shell.

**Comment by maravento** [comment]
The difference is when "test.vbs" call "test.bat", "test.bat" run in cmd (not in cmder), because cmd.exe is the default shell in Windows. The question is how vbs call test.bat to force run with cmder. Thanks
