### ISSUE TITLE
"Access is denied" fresh cmd prompt

### ISSUE THREAD

**Issue by shanff** [cmderdev/cmder#1020]
Latest dev version downloaded and extracted to a folder.

Ran .\build.ps1 in $progdir/scripts to get the vendor programs

Ran .build.ps1 -compile from dev console to build the launcher.

Standard cmder prompt runs through the init.bat initially, drops messages regarding .lua files, then drops an access is denied message.  The next messages relate to user-profile.cmd I believe.  

From then on, the cmder task loads with "Access is Denied." a CR/LF and the appropriate prompt.  Administrator task for cmd does the same.  

Any clues as to what I can look for in the .bat file that is causing the message?  I've tried narrow things down, but it's been a while since I've messed with batch files.

**Comment by Stanzilla** [comment]
In which folder is your cmder installation?

**Comment by shanff** [comment]
In my case, it's currently sitting under c:\users\shawn\binaries\cmder

**Comment by Stanzilla** [comment]
Can you maybe screen record the process?

**Comment by shanff** [comment]
Sorry about the quality and watermark.  I'm coming from linux mainly and haven't found a good video editor as of yet.  https://www.youtube.com/watch?v=evT5a6H0X6o&feature=youtu.be

**Comment by shanff** [comment]
I've commented out all of the "git" checks/tests.  The error went away.  It appears as though the logic is failing at some point.  I'll post back if I get it squared away.

**Comment by shanff** [comment]
I've found that line 82 is where I'm getting the access is denied error.  Not exactly sure what it's doing, but I'm still digging and googling.

**Comment by shanff** [comment]
Not sure what's changed  since my last try at this, but it's working fine on Win10 now.
