### ISSUE TITLE
Global hotkey for "Open Here" with AHK

### ISSUE THREAD

**Issue by dragons4life** [cmderdev/cmder#1022]
Considering that this was base from ConEmu I though this script would work fine
`#NoTrayIcon
;-------- https://autohotkey.com/boards/viewtopic.php?t=5796&p=33858#p33858  user tmplinshi   ---
# t::

```
PID := cmdHere()
WinSet, AlwaysOnTop, On, ahk_id %OutputVarID%
```

return

cmdHere() {
    If WinActive("ahk_class CabinetWClass") || WinActive("ahk_class ExploreWClass") {
        WinHWND := WinActive()
        For win in ComObjCreate("Shell.Application").Windows
            If (win.HWND = WinHWND) {
                dir := SubStr(win.LocationURL, 9) ; remove "file:///"
                dir := RegExReplace(dir, "%20", " ")
                Break
            }
    }
    Run, "C:\Program Files\cmder\cmder.exe", % dir ? dir : A_Desktop, , OutputVarPID
    return OutputVarPID
}`

I know you can right-click > cmder here, but if there is a way to make a global hotkey with
win+t to open the cmder here it would be preferable.

Also if it can be done within cmder itself, than that's fine as well.

**Comment by inwardmovement** [comment]
I am interested too!

**Comment by daxgames** [comment]
cmder %cd%
