### ISSUE TITLE
How to completely clear console output on pressing Ctrl-L?

### ISSUE THREAD

**Issue by basharov** [cmderdev/cmder#1025]
When I press Ctrl-L, the screen clears, but not completely, more like scrolling down to a clear space and keeping all the output above the screen fold, so when I scroll up, I see all the output I had before.

Is it possible to clear the console output completely?

I need it because when I run some program with long log output, it's hard to track where previous output ends and current one begins, so I would like to clear the console completely before running the program.

Thanks!

**Comment by glucas** [comment]
What shell are you using? The cmd.exe built-in `cls` will do what you want.

**Comment by SOSANA** [comment]
@glucas I am having an issue with cls, it leaves spacing issues, you'll also notice that now global env vars aren't highlighted as they use to be example ```git status``` etc
![temp](https://cloud.githubusercontent.com/assets/2634185/16745538/840eb614-4773-11e6-9def-8e77fea5238b.PNG)

**Comment by marcosbozzani** [comment]
Use GuiMacro (Keys & Macro page)

`print("\ecls\n")`

"\e" emulates Esc express, "\n" emulates Enter.

Source: http://superuser.com/a/623833/351521
