### ISSUE TITLE
cmder no longer using path variables

### ISSUE THREAD

**Issue by brianbrennan** [cmderdev/cmder#1029]
I've been using cmder for a bit over a year now. I've never had an issue like this though. After installing after reinstalling, none of my path variables are working properly in cmder.

The command prompt recognizes these commands, but not cmder. I don't have this issue on my work computer, which I installed with cmder a few weeks ago.

Currently using Windows 10 on both

EDIT:

Looks like adding stuff to the path in cmder via @set path sort of does the trick, but it still doesn't allow for using npm package commands

**Comment by Nicholaiii** [comment]
I can confirm this. Came to write an issue about it but found this.

**Comment by Nicholaiii** [comment]
I found out why it didn't work for me. Cause actually it did, but it turned out the NPM folder wasnt in my path.
do `npm config get prefix` and add this to your path the normal way. :)

**Comment by brianbrennan** [comment]
I was able to fix this by reinstalling the mini version. I'm honestly not entirely certain why it works now, but it does. I had reinstalled the mini version several times, but this last time did the trick. Not touching it anymore since its working. NPM was already on the path for me, so @Nicholaiii 's suggestion wasn't what fixed it for me.

**Comment by jdhao** [comment]
I have also met this problem. I installed a new application on my Windows machine and I have added its executable path into the system path variable. But I can only run the command from the system `cmd`, not in `cmder`, which is weird.  After a fresh new install of `cmder`, now I can use that command. I have no idea what is exactly wrong.
