### ISSUE TITLE
Cmder + Git Bash and Unicode symbols

### ISSUE THREAD

**Issue by hex3r** [cmderdev/cmder#1030]
I'm using Cmder with Git Bash task and lately I've run into a problem that whenever I try to send Cyrillic symbols to a server, the terminal isn't able to correctly read them and only sends (and takes) question marks. This has been an issue in older versions of Git for Windows but has been fixed a long time ago.

If I run git BASH it works with Cyrillic symbols just fine. The problem lies somewhere on the Cmder side.

**Comment by mrRosset** [comment]
Try #985 but with ru_RU.UTF-8 (list of locales: https://docs.moodle.org/dev/Table_of_locales)

**Comment by fracz** [comment]
It does not help.
