### ISSUE TITLE
Cmder getting raped by dr.web quarantine system

### ISSUE THREAD

**Issue by dagman** [cmderdev/cmder#1031]
So when i trying to launch `cmder.exe` dr.web treats `ConEmuC.exe` file as **virus** and put it into qarantine.
![false virus](https://cloud.githubusercontent.com/assets/13398931/16715712/a4514848-46f0-11e6-831c-48869d7349ec.png)

And when i recover it and restart `cmder.exe` i get this problem
![problem](https://cloud.githubusercontent.com/assets/13398931/16715720/e47793dc-46f0-11e6-9102-f38972c81d0f.png)

So what should i do to fix this?

**Comment by Stanzilla** [comment]
Report it as a false positive to Dr. Web

**Comment by dagman** [comment]
how can i do it?

**Comment by dagman** [comment]
nevermind i find how to send a report.

**Comment by shakvaal** [comment]
Still raped :(
It's report time...

![2017-10-25 13_27_17-2017-10-25 13_25_50- png - windows photo viewer](https://user-images.githubusercontent.com/4275080/31994125-438ee7fc-b988-11e7-925a-13093bba3d78.png)

**Comment by SindbadSeafarer** [comment]
how did you cope with this problem?

**Comment by SindbadSeafarer** [comment]
I have the same problem

**Comment by Stanzilla** [comment]
Stop using bad AntiVir software? :)
