### ISSUE TITLE
Error opening the cmd. Missing ConEmu.exe

### ISSUE THREAD

**Issue by jellysquider** [cmderdev/cmder#1033]
When unzipped the archive and opened commander the following  error appeared:

_Windows cannot find
' J:...\cmder-master\/vendor/conemu-maximus5/ConEmu.exe'. Make sure you typed the name correctly and, then try again._

Machine: Windows 10 Pro x64.

**Comment by Stanzilla** [comment]
Did you start cmder with cmder.bat or cmder.exe?

**Comment by shanff** [comment]
If you downloaded the zip from github, you'll need to run utils.ps1 from the scripts folder

**Comment by jellysquider** [comment]
Got it, thanks :)
