### ISSUE TITLE
[task?] connect ssh to server after open tab

### ISSUE THREAD

**Issue by krzys1u** [cmderdev/cmder#1034]
Is it possible to configure cmder that when I open new tab (new task) it'll call ssh myserverAddress ?

I try to make one click shortcut to open new tab with ssh connection to my server can I do something like this?

**Comment by shanff** [comment]
I do this.  

In my task Command window:
putty.exe -load "gruvbox" user@server

Runs putty with my preferred profile and specifies user@server.  Pretty easy actually.

**Comment by formatq** [comment]
@shanff but it's run without color theme of the cmder.

**Comment by shanff** [comment]
Do you mean the window color theme, or the terminalcolor theme?  I use putty to control my terminal color theme.  I just name my profiles with my theme name.  It's easier for me to get the use I want that way. The original question didn't have any reference to theme.  I use -load "profile name" user@server to control which server i want to connect to which is a valid answer to OP's question.
