### ISSUE TITLE
Ligature Support

### ISSUE THREAD

**Issue by conor-byrne** [cmderdev/cmder#1036]
Just would like to submit a feature request for supporting fonts with ligatures; Fira Code and Hasklig.

**Comment by Azza292** [comment]
Are there any plans to implement Ligatures in Cmder?

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)

**Comment by DRSDavidSoft** [comment]
For context, this is being tracked at https://github.com/Maximus5/ConEmu/issues/703
