### ISSUE TITLE
Error from clink-completions/vagrant.lua on launch

### ISSUE THREAD

**Issue by mcw0933** [cmderdev/cmder#1038]
I just installed Cmder 1.3.0 overtop of a 1.2.9 install.

I'm getting the following when launching a new instance:

`...CMDER_PATH/vendor/clink-completions/vagrant.lua:66: Additional arguments to new_parser() must be tables or strings`

where `CMDER_PATH`is my path to the 1.3.0 exe.  `vagrant.lua` doesn't seem to have changed between 1.2.9 and 1.3.0, so I'm guessing it's an incompatibility with the new version of clink?

**Comment by Stanzilla** [comment]
https://github.com/vladimir-kotikov/clink-completions/pull/53

**Comment by clijiac** [comment]
delete .lua in config floder solved this issue for me.

**Comment by kohenkatz** [comment]
@Stanzilla's linked issue fixed this for me.
