### ISSUE TITLE
1.3.0 ls output utf code of cjk but dir get right output

### ISSUE THREAD

**Issue by clijiac** [cmderdev/cmder#1041]
use pure new 1.3.0 still get this result. my os is win10-x64

`ls` output
![image](https://cloud.githubusercontent.com/assets/1262789/16896019/b73bef30-4bb9-11e6-942b-1977ec7960de.png)

`dir` output

![image](https://cloud.githubusercontent.com/assets/1262789/16896024/c844da94-4bb9-11e6-991e-e03c8bab9a86.png)

**Comment by mrRosset** [comment]
Try #985

**Comment by clijiac** [comment]
Works for me! Thanks @mrRosset
will close this.

**Comment by osdu** [comment]
下载https://github.com/git-for-windows/git/releases/download/v2.7.4.windows.1/PortableGit-2.7.4-32-bit.7z.exe
直接用7-zip解压PortableGit-2.7.4， 提取`/usr/bin/ls.exe` 替换`/Cmder/vendor/git-for-windows/usr/bin/ls.exe`
