### ISSUE TITLE
How to start cmder from command line with a given task?

### ISSUE THREAD

**Issue by lbaca** [cmderdev/cmder#1043]
With ConEmu, you can run `ConEmu64.exe -Single -run {Shells::cmd}` from command line to start the task called "{Shells::cmd}". I cannot figure out how to do the same thing with cmder. My objective is to integrate this into an AutoHotkey script that does other things, so the task name is not necessarily known beforehand.

(Sorry if this is the wrong forum or manner by which to get the answer for this question.)

**Comment by jakenuts** [comment]
Seems like a really importance piece, not being able to launch "tasks" is a bit off

**Comment by daxgames** [comment]
Cmder wraps conemu, conemu does what you ask.  Doing this with cmder.exe gains you nothing, just use conemu to do it.

**Comment by lbaca** [comment]
Doing this with Cmder gains me, well, doing it with Cmder. By that logic, what's the purpose of Cmder at all? I like its look and feel better, and would prefer to be able to use it as what it is, a Conemu wrapper, wherever I would use Conemu.

**Comment by Jackbennett** [comment]
I think the cmder.exe wrapped has many changes in its future from all the stuff i've pointed back to #420

I can't really touch C++ so hopefully just getting all the related issues together will help those who can.

**Comment by daxgames** [comment]
@lbaca cmder.exe just launches conemu.exe.  The true power of cmder is the init.bat and how it flies together all the products that make up the cmder suite.  If you use conemu.exe to launch init.bat you are doing the same thing cmder.exe does.

**Comment by cyrilchapon** [comment]
> @lbaca cmder.exe just launches conemu.exe with a default task that launches init.bat.

Actually it also displays a nice icon in the taskbar.

Would it be possible for cmder to have an option to select predefined task when starting up ?
The whole point of a wrapper is to **abstract** a thing, isn't it ? So when the abstraction seem to lack a feature, I think (this is my humble opition) this is just a lack of feature, not an out-of-scope unrelated feature oO

Thus, I'd like to launch a cmder terminal (not a ConEmu.exe or some obscure-already-wrapped-stuff-that-I-don't-have-time-to-digg-into-that's-exactly-why-I'm-using-a-wrapper terminal, a real cmder terminal) in administrator mode, from context menu, only when I want to. That seems a reasonable use-case for a terminal program doesn't it ?

I duplicated `[HKCR]/Directory/Shell/Cmder` to `[HKCR]/Directory/Shell/Cmder_admin` (and same for `directory/background/shell`). In "command" reg key, the invocation is in the form

```
"C:\[path of cmder]\cmder_mini\Cmder.exe" "%V"
```

Which, in the current state, doesn't allow one to tweak the terminal launch.

**Comment by ReGrantDev** [comment]
What I would like to do is to have multiple tasks (preferably in external files) to where I could launch Cmder with a variety of configurations. For different projects I have different needs - meaning different split layouts, colors, tab names etc... The most convenient thing would be to launch Cmder and have it start out with this layout. I can use tasks but even after I figure out all the switches, there is still always one extra tab open that I don't need - as Cmder always starts out with something.

Seems like the topic here would be a way to achieve this but perhaps there is another way that I haven't found yet?
