### ISSUE TITLE
Git: fatal: Unable to create '.git/index.lock': File exists.

### ISSUE THREAD

**Issue by Sabrethan** [cmderdev/cmder#1044]
Git is unable to create `.git/index.lock` file because it already exists.  Steps to reproduce using files that are readily available:

- Goto https://wordpress.org/download/ and download WordPress ZIP archive.
- Extract to a directory.
- Open Cmder and change directory where WordPress was extracted.
- Init directory using:

```bat
git init
```

- Configure `user.name` and `user.email`

```bat
git config user.name "test"
git config user.email "test@example.com"
```

- Add all files.

```bat
git add -A
```

- Commit files.

```bat
git commit -m "test"
```

An error like this shows up:

```
fatal: Unable to create 'Z:/a/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
```

- Listing the `.git` directory shows that an `index.lock` file exists.
- Open **Task Manager** and multiple **Git for Windows** processes are still running.

**Comment by phith0n** [comment]
I also have the problem. Why close the issue ?

**Comment by Stanzilla** [comment]
Because it has nothing to do with cmder, it's a git problem.

**Comment by phith0n** [comment]
Can you tell me how to solve the problem ? Just update git ?

**Comment by Stanzilla** [comment]
Yeah that would be the only thing that could help, otherwise create a ticket over at git-for-windows

**Comment by phith0n** [comment]
thx a lot, I'd like to search about it.

**Comment by acrap** [comment]
Do you sure that you don't have another Cmder tab with opened the same git folder? Everything must be ok if you close another.

**Comment by 22u2** [comment]
I have the same issue with, with another command like git mergetool and I think it is a cmder issue because If I do the steps inside a window prompt, there is no problem.

**Comment by ghola** [comment]
The problem is definitely with Cmder or ConEmu. It spawns a git process that never closes each time it displays the prompt line (so if you are in a directory which is also a git repo, on each enter press you get a new process spawned). One of those git processes produce a index.lock file which prevent any other git process to operate on the repo.

**Comment by ghola** [comment]
It seems to be the same issue as here: https://github.com/cmderdev/cmder/issues/1060

**Comment by ghola** [comment]
It seems to be the same issue as here: https://github.com/cmderdev/cmder/issues/1060

**Comment by cringer** [comment]
Same issue here.  Also confirmed that if I run the same commands in a windows command prompt everything is fine.  However in cmder the issue persists.  The index.lock file appears when I do a 'git add .' from then on the lock file is there.  Can't do a commit after that...

**Comment by stefan-wiesner** [comment]
Same for me. It's spawning git processes which do not end leaving you with an index.lock which  you cannot delete since the process is still running.

**Comment by oskarlind** [comment]
Same for me... a new git process spawns every time I enter the directory.

**Comment by nerzid** [comment]
Same problem here. Just installed git for windows and used git bash to add,commit and push things to github. This problem is definetly with Cmder. Its sad to see such an excellent terminal has this problem 😭

**Comment by Demers94** [comment]
I'm also having this problem, and it seems to be caused by cmder. When cmder is open, there's the index.lock file in the .git folder of my project. As soon as I close cmder, it is deleted.

A way to fix this issue for me is to close cmder and use git bash instead to push to my repo or do whatever I want to do. Once that's done, I can re-open cmder and the index.lock file will not be created, I can use cmder again for git operations.

**Comment by MartiUK** [comment]
Fixed in #1101

**Comment by ogrishman** [comment]
@MartiUK , how can I use it? I see the release version is still 1.3.1. Should I build it by myself? Is there a documentation? I'm sorry I'm new to this.

**Comment by MartiUK** [comment]
@ogrishman The latest development builds are always here: https://ci.appveyor.com/project/MartiUK/cmder/build/artifacts

**Comment by ogrishman** [comment]
@MartiUK, Thank you!

**Comment by ClementParis016** [comment]
I'm having the same issue with latest v1.3.1 of Cmder, it is still spawning multiple Git for Windows processes as soons as I cd into a local repository

**Comment by selrond** [comment]
Same problem here

**Comment by daxgames** [comment]
rm .git/index.lock

**Comment by selrond** [comment]
@daxgames it is __not__ a solution, bundled git.exe always create new index.lock and prevents commiting. Solved in the latest build though

**Comment by WillJE** [comment]
it's locked,you can use GUI to unlock it and then everything will be fine, i just tried it

**Comment by cringer** [comment]
@WillJE Why should anyone have to unlock it?  Something within the application keeps causing it to lock.  Manually unlocking it gets you by one time, but this is a recurring issue.  Your saying we should have to manually go in and unlock it every time it glitches out?  That is not a solution, it's called a band-aid fix.

**Comment by twinsec** [comment]
For anyone ran into the same issue with index lock, there's a workaround that disabling
Settings -> Git Extensions -> Performance -> Show number of changed files on commit button
so that Git Extensions won't call git status as soon as any file updates which blocking the current processing git commands and introducing the lock.

Hope this help for you guys.

**Comment by Stanzilla** [comment]
Might get a real fix soon https://github.com/git-for-windows/msys2-runtime/commit/78e2deea8ec1db4aea1e78432ae98dac7198f6a5

**Comment by AnilKumar345** [comment]
The solution is to unhide all the hidden files of local repo,
Open .git folder in that "index.lock" is available, delete that file and continue your git execution

**Comment by AnilKumar345** [comment]
Problem:
========
Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.

Solution:
=========
1. Open local repository
2. By default .git is hidden while initializing local repositort, unhide .git folder.
3. OPen .git folder 
4. Under this "index.lock" file is available, delete that file

**Comment by svchraghava** [comment]
the above solution worked for me thanks

**Comment by brady800526** [comment]
Though there is an alternative above, but that didn't solve my situation.
In my case, I delete the "git" plugin in ./zshrc and reboot the computer then the issue is gone, I guess the plugin had done something conflict the git command.

**Comment by herijaona** [comment]
solution :  rm -Force ./.git/index.lock

**Comment by daxgames** [comment]
@lucas0000miranda how does this have anything to do with cmder if you are on mac osx given cmder is a Windows only app?

**Comment by lucas0000miranda** [comment]
@daxgames hmmm not sure. I just put that in context make sure that this implementation will work for MAC users.

**Comment by MohsinRaz3** [comment]
I am facing same issue saying /index.lock with "another git process seems to be running.. "  on my command line Git Bash terminal

**Comment by Sathri-Mamatha1127** [comment]
> the above solution worked for me thanks

How u done ..........................where i have to open local repositary

**Comment by chandu575** [comment]
@AnilKumar345
this solution work thanks

**Comment by Subham123456789kumar** [comment]
**Use  command  solve problem** 
step1.ls -a
step2.cd .git
step3.ls -a
step4.rm index.lock
