### ISSUE TITLE
About letter overlapping

### ISSUE THREAD

**Issue by matreex** [cmderdev/cmder#1045]
update to v1.3.0, edit ~\cmder\vendo\init.bat, search the keywords: `@prompt`, but don't find it, so... add `@prompt $E[1;32;40m$P$S $S$_$E[1;30;40m$$ $E[0m` to init.bat, but the code is not working, what i do for this?

it's bug? Type cmd, and hit the keyboard of up and down, Just like that...
<a href="http://imgur.com/h3RFKZU"><img style="max-width:100%;" src=http://i.imgur.com/h3RFKZU.png"></a>

**Comment by Jin-Whu** [comment]
cmder V1.2.9 has this problem too!

**Comment by matreex** [comment]
@Jin-Whu 
Yes, i know, but it would not happened the preblem again, when change > @prompt $E[1;32;40m$P$S{git}{hg}$S$_$E[1;30;40m{lamb}$S$E[0m to > @prompt $E[1;32;40m$P$S $S$_$E[1;30;40m$$ $E[0m in init.bat. so... update to v1.3.0, i want to do this, but i can't find the codes and be added > @prompt $E[1;32;40m$P$S $S$_$E[1;30;40m$$ $E[0m that's not working.

**Comment by Jin-Whu** [comment]
@matreex ,Thank you. It's working in V1.2.9! V1.3 has other bug, so I won't swtich to V1.3.

**Comment by Stanzilla** [comment]
@Jin-Whu which other bug are you talking about?

**Comment by Jin-Whu** [comment]
@matreex ,if I replace `@prompt $E[1;32;40m$P$S{git}{hg}$S$_$E[1;30;40m{lamb}$S$E[0m` with `@prompt $E[1;32;40m$P$S $S$_$E[1;30;40m$$ $E[0m`, the **git** branch will disappear in path .How can I resume keep git branch when avoid letter overlap.
@Stanzilla , In V1.3, if I switch ENG to other language,  cmder's top frame will appear some prompt, but V1.2.9 won't.

**Comment by Jin-Whu** [comment]
@matreex , I found solution in V1.2.9. Just replace `@prompt $E[1;32;40m$P$S{git}{hg}$S$_$E[1;30;40m{lamb}$S$E[0m` with `@prompt $E[1;32;40m$P$S{git}{hg}$S$_$E[1;30;40m$$$S$E[0m`. It's working in V1.2.9

**Comment by matreex** [comment]
@Jin-Whu , I had found disable clink, would fix the problem. it's just, add `::` to line 37 of init.bat. of course, who is essential `@prompt $E[1;32;40m$P$S $S$_$E[1;30;40m$$ $E[0m` too.
