### ISSUE TITLE
Why your git version is fast?

### ISSUE THREAD

**Issue by shytikov** [cmderdev/cmder#1048]
Hi,

Stupid question. I need to know the trick. You're shipping `cmder` with most recent version of `git-portable` and it is fast. And by fast I mean no delays when executing commands. for example I can ask for git version and receive control back without any delay, same for status commands, log and so on.

When I download it from official website it is slow. And when I say "slow" I mean noticeable (several milliseconds) delay, when `git` is supposed either release control to command line, or output data.

Both versions yours and official uses same configuration file. Both was checked in different combinations of `bash`es and `cmd`s. Result is always the same — official has this annoying delay which drives me crazy.

To provide some figures, so you'll understand what I mean. I've created small `bat` file to illustrate my problem:

```
@echo off
echo %time% < nul
git > nul
echo %time% < nul
```

It will just show me start and end time of simple call — help for `git` command. `cmd` was used for all cases.
- 64 portable version of `git version 2.9.0.windows.1` shows `10:53:29.73 -10:53:30.71`, so it's almost second delay!
- 32 portable version of `git version 2.9.0.windows.1` shows `10:54:15.10 - 10:54:16.19`, so it's more then second delay!!
- `cmder` with `git version 2.9.0.windows.1` shows `10:54:51.13 — 10:54:51.36` **WAY LESS THAN SECOND**!!!

So what's the trick? Which spell did you cast to do this magic to `git`?

**Comment by Jackbennett** [comment]
If the referenced issue doesn't answer it I don't think we've any clue, sorry. Perhaps a combination of install location, caching and permissions help light its load.
