### ISSUE TITLE
prompt is Garbled

### ISSUE THREAD

**Issue by zydxhs** [cmderdev/cmder#1054]
As shown below：
![prompt](https://cloud.githubusercontent.com/assets/15759657/17278173/ca3ff79a-5788-11e6-82e9-09d44a364954.png)

cmder ver is 1.3 in win7 64bit。

**Comment by janschulz** [comment]
Seems that the replacement code can't handle non-ascii chars?

```
c:\temp
λ mkdir ü

c:\temp
λ cd ü

c:\temp\�
λ
```

**Comment by janschulz** [comment]
We [currently](https://github.com/cmderdev/cmder/blob/master/vendor/clink.lua#L23-L26) do this:

```lua
    cwd = clink.get_cwd()
    prompt = "\x1b[1;32;40m{cwd} {git}{hg} \n\x1b[1;30;40m{lamb} \x1b[0m"
    new_value = string.gsub(prompt, "{cwd}", cwd)
    clink.prompt.value = string.gsub(new_value, "{lamb}", "λ")
```

So my reading is that we can't pass the output of `clink.get_cwd()` to `clink.prompt.value`?

CC: @mridgers (clink maintainer)

**Comment by zydxhs** [comment]
May be the clink does not support non-ascii.

**Comment by janschulz** [comment]
I think it does (letting the cmd set the prompt and then handling it in clink works...), just that the string has to get encoded... No idea how that works :-/

**Comment by janschulz** [comment]
So, a bit of debugging (to a ANSI encoded file) shows this:

```
cwd(string): c:\temp\ü
prompt(string): c:\temp\Ã¼> # before any changes in lua
prompt(string): [1;32;40mc:\temp\ü {git}{hg}  # after changes in lua
```

If I interpete http://stackoverflow.com/a/14981670/1380673 right, then clink needs to translate the prompt between utf (what clink/lua seems to use in `get_cwd()`) and whatever is done with `clink.prompt.value` when it is written back to the prompt.

[Not, I have changed my codepage to utf8: `chcp  65001` but the same debug output happens with `chcp 850` which is the default in a regular cmd window]

**Comment by janschulz** [comment]
I've taken that upstream: https://github.com/mridgers/clink/issues/415

**Comment by zydxhs** [comment]
Directly set value to "clink.prompt.value" is ok:

**Comment by janschulz** [comment]
I can't reproduce: on my system with `clink.prompt.value = clink.get_cwd()` (not the last `()`!) exactly the same happens:

```
c:\temp\�
```

**Comment by janschulz** [comment]
Please try https://github.com/cmderdev/cmder/pull/1070 for a version which parses the original prompt.

**Comment by zydxhs** [comment]
I also do not know why.

tks for your efforts(#1070), and it's ok in my system.

2016-08-10 

johnsmithcry 



发件人：Jan Schulz <notifications@github.com>
发送时间：2016-08-09 18:47
主题：Re: [cmderdev/cmder] prompt is Garbled (#1054)
收件人："cmderdev/cmder"<cmder@noreply.github.com>
抄送："zydxhs"<johnsmithcry@163.com>,"Author"<author@noreply.github.com>

I can't reproduce: on my system with clink.prompt.value = clink.get_cwd() (not the last ()!) exactly the same happens:
c:\temp\�

**Comment by jing2si** [comment]
good job!Thx~
it fixed my same problem!

**Comment by davpaez** [comment]
According to [this](https://github.com/chrisant996/clink/commit/99b2b6566ab59a691ea4b501c4ea0adfedb14f17) commit in clink, this issue appears to have been fixed.

If so, maybe the `clink.lua` script should use the get_cwd() again ?
