### ISSUE TITLE
Lamba prompt and git status scripts not running 

### ISSUE THREAD

**Issue by ambitionly** [cmderdev/cmder#1055]
Lamba prompt and git status scripts not running.(ps os is win 10)

**Comment by cmorgan** [comment]
for me too, is there any fix for this?

**Comment by janschulz** [comment]
What does this mea, you you show a screenshot?

**Comment by fehrm** [comment]
I have the same issue. Clean installation of Cmder (full) on path C:\Cmder
Note: I removed my username and replaced it with a (fully professional photoshopjob) text saying Test, so that part is still working :wink:

![1](https://cloud.githubusercontent.com/assets/8399245/17397738/bb4c545a-5a39-11e6-8ceb-9501c809cfd5.PNG)
![4](https://cloud.githubusercontent.com/assets/8399245/17397741/bfb57756-5a39-11e6-8264-b59f8d94128c.PNG)

**Comment by janschulz** [comment]
> The message at the top of window is posted on every new cmd window I open, the "additional *.lua" etc.

@fehrm Do you have writing rights in c: \cmder?

**Comment by fehrm** [comment]
@janschulz Yes, I am owner of the folder and have full rights. Just to be sure I made a new folder, gave me full modify permissions and extracted cmder again. Still experiencing the same issues.

**Comment by janschulz** [comment]
What I find interesting is that the clink output is above the "generating clink config". That lines are only there to notify the user that the following lines calls clink and does all the real work (if called for the first time)...

-> https://github.com/cmderdev/cmder/blob/master/vendor/init.bat#L27-L34

So my next guess would be that clink is installed to inject itself in all cmd sessions and output comes from the cmder clink not being able to inject itself and so not generating the config files in `<cmder>\config` and therefore showing the message the next time?

@fehrm Do you have clink installed in addition to cmder?

**Comment by fehrm** [comment]
@janschulz I do! Removing clink fixes the issue. 

It would be great though if there was a way to make it work together. I been using Clink and Cmder separate before and it has worked, the version I know where it is working is 1.2.9 which was my previous installation.

Either way, great conclusion, you nailed it :smile:
