### ISSUE TITLE
conda environment not displaying

### ISSUE THREAD

**Issue by cmorgan** [cmderdev/cmder#1056]
the conda env, usually looks like `(dev) c:\dev\code (master)`
is missing from version 1.30 full distribution

**Comment by janschulz** [comment]
As we currently do not use the original prompt, you have to add conda information yourself: 

Add a file called `<cmder dir>\config\<somehing>.lua` with the following content:

```lua
---
 -- Find out current conda env
 -- @return {false|conda env name}
---
function get_conda_env()
    env_path = clink.get_env('CONDA_DEFAULT_ENV')
    if env_path then
        basen = basename(env_path)
        return basen
    end
    return false
end

---
 -- add conda env name 
---
function conda_prompt_filter()
    -- add in conda env name
    local conda_env = get_conda_env()
    if conda_env then
        clink.prompt.value = string.gsub(clink.prompt.value, "{lamb}", "["..conda_env.."] {lamb}")
    end
end

clink.prompt.register_filter(conda_prompt_filter, 20)
```

**Comment by lpinner** [comment]
At the point this runs, the "{lamb}" has already been replaced with "λ".

To get it working, I replaced:
`clink.prompt.value = string.gsub(clink.prompt.value, "{lamb}", "["..conda_env.."] {lamb}")`

with:
`clink.prompt.value = string.gsub(clink.prompt.value, "λ", "["..conda_env.."] λ")`

**Comment by janschulz** [comment]
Please try https://github.com/cmderdev/cmder/pull/1070 for a version which parses the original prompt.
