### ISSUE TITLE
Use within Terminal of PHPStorm

### ISSUE THREAD

**Issue by ktwbc** [cmderdev/cmder#1061]
Is there a command line switch or way to get Cmder to be run inside PHPStorm's Terminal on Windows? You can change PHPStorm to point to the c:\Program Files\cmder\cmder.exe easily, but then when attempting to click on Terminal, it launches its own window instead of remaining inside like the default Windows. Not sure if this is your issue, or theirs, or if your program is always designed to create its own window but would be nice to be more "integrated" in a scenario like this.

**Comment by fredericseiler** [comment]
Cmder 1.3.0 & PhpStorm 2016.2 :

You can't use the "full" Cmder package (with the ConEmu container), but what you can do is to load the Cmder init script inside the PhpStorm terminal :

1. Add a user environment variable `CMDER_ROOT` pointing to your Cmder installation path
2. Restart PhpStorm (to [propagate](https://support.microsoft.com/en-us/kb/104011) the newly created environment variable)
3. In `Settings\Tools\Terminal`, add this shell path: `"cmd" /k "%CMDER_ROOT%\vendor\init.bat"`

![image](https://cloud.githubusercontent.com/assets/954168/17456935/4776a05c-5be8-11e6-8f7e-85bce5b6c4dc.png)

Based on #282 and c769502

**Comment by cyb3rD** [comment]
@fredericseiler Thanks for your solution!
That's worked for me with WebStorm 2016.2.3
Could you, please tell how to run CmdEr in current project directory within WebStrom

**Comment by etarel** [comment]
For someone whose `CMDER_ROOT` path has space in it, the shell path may be `"cmd" /k ""%CMDER_ROOT%\vendor\init.bat""`, it works for my `C:\Program Files (Portable)\cmder`

**Comment by otravers** [comment]
The solution above works for me, however how can you do the same with powershell.exe? I really want Ctrl-R history support.

**Comment by OuPDO** [comment]
Any idea to get this work with Cmder 1.3.2 and PhpStorm 2016.3.3 ? The solution doesn't work. I am only able to set Path Variables in PhpStorm. Where can I set an  environment variable?

**Comment by fredericseiler** [comment]
> You can also view or modify the environment variables by selecting **System** from the **Control Panel**, selecting **Advanced system settings**, and clicking **Environment Variables**.

[msdn](https://msdn.microsoft.com/library/windows/desktop/ms682653(v=vs.85).aspx)
