### ISSUE TITLE
cmder here not working with windows bash

### ISSUE THREAD

**Issue by Ehekatl** [cmderdev/cmder#1063]
my bash task definition:
`
%SYSTEMROOT%\System32\bash.exe -c zsh -new_console:a:s:p:n:d:"%USERPROFILE%"
`
when I using cmder here it always goes same directory, but it's working on powershell and cmd.

**Comment by darsain** [comment]
Have a similar issue when trying to open Cmder in a specific directory, where passing any parameter to `Cmder.exe` has no effect when `{cmd::Cmder as Admin}` is set as a default task. It works fine for non-admin `{cmd::Cmder}` though.

Any possible fix for this?

**Comment by Stanzilla** [comment]
https://github.com/cmderdev/cmder/issues/901#issuecomment-237562623

**Comment by darsain** [comment]
@Stanzilla maybe I'm blind, but I don't see a solution to anything in this thread on that link.

**Comment by Ehekatl** [comment]
@Stanzilla have you tried "open cmd here" ? It's doesn't work on my side

**Comment by Ehekatl** [comment]
k, now I find out why it's not working, in default settings this magic actually control by `CMDER_START` env variable, and the init script where take care of it.

e.g. init.bat for cmd
```
:: This is either a env variable set by the user or the result of
:: cmder.exe setting this variable due to a commandline argument or a "cmder here"
if defined CMDER_START (
    cd /d "%CMDER_START%"
)
```

@darsain for your question, just add the initial script to your admin task should work
but for windows bash, seems it doesn't pass the env variable, I can't find `CMDER_START` in env

**Comment by darsain** [comment]
I'm gonna clarify further. I'm running Cmder 1.3.0.

There are 2 tasks.

`{cmd::Cmder}`:

```
cmd /k "%ConEmuDir%\..\init.bat"  -new_console:d:%USERPROFILE%
```

`{cmd::Cmder as Admin}`:

```
*cmd /k "%ConEmuDir%\..\init.bat"  -new_console:d:%USERPROFILE%
```

The tasks are identical, both including the `init.bat` script as you can see above.

Starting in specified directory (passed to the Cmder.exe as 1st parameter) works for normal task, but  doesn't for Admin.

I want to use Admin task as default, but can't because using Cmder without the configurable starting directory is too painful.

**Comment by pingshunhuangalex** [comment]
Not working with Git Bash either, and it's still not fixed judging from the closed issue [here](https://github.com/cmderdev/cmder/issues/709#issuecomment-158489521)

**Comment by xschen** [comment]
Just found a solution. You can simply replace `%USERPROFILE%` with `%CMDER_START%`.  For example the task for the built-in git bash can be modified as

`cmd /c "%ConEmuDir%\..\git-for-windows\bin\bash --login -i" -new_console:d:%CMDER_START%`

**Comment by pingshunhuangalex** [comment]
@xschen 
Gosh mate, you saved my day. I've been using the `ConEmu Here` temporary fix found on Stackoverflow like forever.

I did see people mention the magic `%CMDER_START%` in a couple of issue threads as well as in the `init` file, but their solutions didn't work so I just moved on...

For people who are looking for similar answers, Git Bash can also be called like this:
`"%ProgramFiles%\Git\bin\sh.exe" --login -i -new_console:d:%CMDER_START%`

**Comment by Shurelia** [comment]
@pingshunhuangalex In your windows shortcut, you can set the `/start` option.
For example, your shortcut's target may look like this: `C:\cmder\Cmder.exe /start "C:\Users\ping"`

Still no fix for 'cmder here' in the root of a drive, though.

**Comment by Messiahhh** [comment]
@xschen  Saved me

**Comment by rodrymbo** [comment]
This is old, but the latest Windows Subsystem for Linux (WSL) seems to do things just slightly differently lately, so I thought I'd document it here for completeness.

This works for me:

```
Icon:
/icon "C:\Program Files\WindowsApps\CanonicalGroupLimited.Ubuntu18.04onWindows_1804.2018.427.0_x64__79rhkp1fndgsc\ubuntu1804.exe"

Commands:
ubuntu1804 run

```

The "run" parameter for ubuntu1804 is documented (in windows store). It says you can use it with a script name as in `ubuntu1804 run myscript.bash`, which is supposed to start bash and execute the script found in the current directory. Just `run` by itself starts the default shell (bash?) in the current directory. With no `run`, it starts it in the user's `~`  home directory. 

I suppose one can use something similar with the init.bat method. 

Not sure how to pass the current directory on the command line -- %V does not seem to work properly.

Also, for "WSL Bash Here", the following command seems to work:

`"D:\apps\Dev\cmder_mini\Cmder.exe" /task "bash::wsl" /start "%1"` when `bash::wsl` is defined as above.
