### ISSUE TITLE
Navigation arrows not working in docker

### ISSUE THREAD

**Issue by syepes** [cmderdev/cmder#1064]
Hello,

I have just upgraded both cmder v1.3.0 and docker to the last versions and now my arrows keys do not work anymore ;-(
Has anyone else noticed this?

**Reproduction**:
# docker run -d --name alpine alpine top
# docker exec -it alpine sh
-- Run some cmds
-- Now user the arrows and they do not work

**Details**:
λ docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:04:48 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      linux/amd64

**Comment by rwilliams** [comment]
It's a weird interaction with ConEmu and Docker, there a bug reports open for it on both respective projects.
