### ISSUE TITLE
Behaviour Moving around / Deleting Korean (possibly all CJK) characters.

### ISSUE THREAD

**Issue by wtkim** [cmderdev/cmder#1066]
I am currently using latest stable release of cmder on Windows 10 machine, with Korean language set. For this configuration of Windows, default cp for cmd.exe is cp949 (EUC-KR). In cp949, using either system cmd.exe or cmder have no problem. 

But what I want to do is use cp65001(utf-8). 
In cmder, if I type Korean characters, call programs to print Korean characters, etc., it will render them perfectly. But, if I try to _Backspace_ those characters, it will delete more spaces than it should be. 

This is what cmder looks like when I begin to use cp65001.
![image](https://cloud.githubusercontent.com/assets/11325881/17465924/c558666c-5d3d-11e6-9aae-a0ae9a220352.png)

Now, if I type a Korean character, 
![image](https://cloud.githubusercontent.com/assets/11325881/17465894/e370ac5a-5d3c-11e6-9824-5f53b82be56b.png)
then move my cursor back a single character, using arrow key, 
![image](https://cloud.githubusercontent.com/assets/11325881/17465900/f603d392-5d3c-11e6-82f4-0f93c6a1caa8.png)
the position is slightly back from original position, perhaps as wide as a half-width character. Compare it with the first image.

Moving forward will return the cursor to proper position, so it seems that the cursor regards a Korean character more wide than it actually is. 

Backspace key also does same, so if I type more than 2 Korean characters then backspace all, it will remove the prompt (the lambda character), as shown below.
![image](https://cloud.githubusercontent.com/assets/11325881/17465929/ddd658f2-5d3d-11e6-8f40-c61eafe16375.png)

For comparison, in system cmd.exe, also powershell and all other cmd-based programs alike, typing non-ASCII characters is impossible when in cp65001, but I can copy-paste some. This is is the result.
![image](https://cloud.githubusercontent.com/assets/11325881/17465908/2656e0e8-5d3d-11e6-96cf-71a8ee80afb7.png)
Full-widths characters are rendered as half-width characters, thus overlapping happens. Could only this behaviour be reproduced, I can set CJK characters narrower in cmder, which could be ugly, but usable.

I am not sure of whether this is a bug or a problem on my settings, but at least checking or un-checking monospace option (which is solution for different CJK widths problems in this repo) did not make any difference.

**Comment by Stanzilla** [comment]
Could be either clink or conemu, can you try filing an issue at https://github.com/Maximus5/ConEmu/ first, please?

**Comment by HojinCho** [comment]
I posted this issue (accidently with someone else's id. sorry for confusion.) and I just tried to reproduce this problem in ConEmu, and it turns out that ConEmu is free of this issue. And I am not currently using clink, unless it is being used by default.

I use mini version of cmder, fresh install save for auto-updating to latest ConEmu.

**Comment by hideaki-t** [comment]
This affects Japanese characters too. CP932(Shift-JIS) works well, but CP65001 does not.
as far as I tried so far, only [Nyagos](https://github.com/zetamatta/nyagos) + Cmder(ConEmu) works fine 

I'm using Windows 10 1607.

**Comment by Stanzilla** [comment]
Probably a clink issue then. It comes with the package and is used by default.

**Comment by Equim-chan** [comment]
Same for Chinese characters. This annoyed me a lot but I can't find a solution yet.
It only occurs in cmd. In bash and powerline it works fine.

**Comment by yangsheng6810** [comment]
I just opened an issue to clink: [Unicode compatibility issue with WSL](https://github.com/mridgers/clink/issues/449).
@Equim-chan I am in a different situation: the problem occurs in cmd and bash, but not in powerline. By bash, I mean all the following: 1. {bash::bash}, 2. {bash::cygwin bash}, 3. calling bash in cmd, 4. calling bash in powerline. Could you provide your config file?

**Comment by Equim-chan** [comment]
@yangsheng6810 For me, it works in {bash::bash}, {bash::mintty}, but fails in calling bash in cmd.
Config: {bash::bash} `cmd /c "%ConEmuDir%\..\MinGW\git\bin\bash --login -i" -new_console:d:%USERPROFILE%`
~/bashrc:
```bash
export PATH=/d/Software/cmder/bin:${PATH}
export LANG=en_US.UTF8
# ...
```

**Comment by Equim-chan** [comment]
Additionally, I just found it seems to be a problem of cmd.exe itself.
After I execute `chcp 65001` in native cmd.exe, CJK characters became "broken" and I am not able to edit them properly.
It occurs no matter I check "use legacy console" or not.

**Comment by yangsheng6810** [comment]
@Equim-chan So your {bash::bash} is actually calling bash provided by MinGW?

**Comment by Equim-chan** [comment]
@yangsheng6810 Yes, I use MinGW and Git standalone.
