### ISSUE TITLE
Garbled utf8 in prompt

### ISSUE THREAD

**Issue by Furgas** [cmderdev/cmder#1068]
Cmder version 1.3.0. ConEmu version 160724 stable.
Applied `set LANG=pl_PL.UTF-8` as per #985.
Using `East Europe` in **Font charset**.

Now `dir` work OK, `ls` works OK, but UTF 8 characters are not properly displayed in prompt:

![cmder_utf8](https://cloud.githubusercontent.com/assets/715407/17475393/1e40d9ea-5d5b-11e6-9b5b-458b51d238ec.png)

**Comment by janschulz** [comment]
This is https://github.com/cmderdev/cmder/issues/1054

**Comment by Furgas** [comment]
Right, sorry. I was searching for "utf". Closing this.
