### ISSUE TITLE
Strange characters in Fish shell with the Linux Subsystem for Windows

### ISSUE THREAD

**Issue by igorkulman** [cmderdev/cmder#1069]
I installed the  Linux Subsystem for Windows, added it to cmder as `%windir%\system32\bash.exe ~ -c fish -cur_console:p`. When it opens, I see some strange characters at the beginning and end of the prompt:

![image](https://cloud.githubusercontent.com/assets/4746070/17512413/f8a48664-5e27-11e6-849a-d11423207df7.png)

Is it because of some wrong unicode settings?

**Comment by JVMartin** [comment]
I had this same issue.  Your font simply doesn't support unicode.  When I changed to a font that does (I chose "Liberation Mono", since that is the font that comes with the Linux Subsystem - it was lovingly crafted by the Ubuntu team), everything works great:

![liberation](https://cloud.githubusercontent.com/assets/4450814/17571344/aab04262-5f04-11e6-8e90-bc834d0d698e.png)

**Comment by JVMartin** [comment]
I have the same issue.  What's weird is that some unicode characters work, and others don't:

![ss](https://cloud.githubusercontent.com/assets/4450814/17572222/2b7bf564-5f08-11e6-882d-9725791c2391.png)

**Comment by rlabrecque** [comment]
What's the output of "echo $LANG"?

**Comment by Hammster** [comment]
I encountered something similiar with zsh + ohmyzsh,

I configured my bash on windows, added zsh but now i've got a good amount of question marks showing up. I tried to mask them with the alternative font options but apparently, they don't work or the ranges are not sufficent. 

As Example:

` /mnt/c/cmder via ⬢ v4.2.0`

⬢ = 0x2B22

![34252362362345248712895617825](https://cloud.githubusercontent.com/assets/1093709/17634181/9d11bc7a-60d1-11e6-8774-73918c9fb573.jpg)

### Temporary solution i had to use
As the __tooltip__ on _Alternative font_ suggests you have to edit the config by hand, and hopefully never press the Apply button.

![52328357982375](https://cloud.githubusercontent.com/assets/1093709/17634979/5d9cb190-60d5-11e6-973e-fc4cc8dc2ce0.jpg)

**Comment by igorkulman** [comment]
`echo $LANG` returns en_US.UTF8 for me

**Comment by iamfreee** [comment]
@Hammster what did you change in the config?

Thanks

**Comment by Hammster** [comment]
@iamfreee you have to edit the value for "FixFarBoardersRanges" in your ConEmu.xml, the path to the file is displayed on the top of the settings window. But be aware you cannot change anything afterward because it overwrites the settings again.

**Comment by iamfreee** [comment]
@Hammster Thanks

**Comment by mackcoding** [comment]
I am seeing this too. 

![image](https://user-images.githubusercontent.com/10917563/58772491-39e68a80-8587-11e9-9c74-5653c36caaa6.png)
