### ISSUE TITLE
Mouse right click copy and paste at same time.

### ISSUE THREAD

**Issue by eromoe** [cmderdev/cmder#1072]
I prefer cmd quick edit mode,  one `right click`  copy,  another `right click` paste .
But I find the mouse setting only has `auto(default copy and paste)`, `copy` and `paste`.
How to walk around?

**Comment by Jackbennett** [comment]
Settings > Keys & Macro > Mark/copy, untick "Copy on Left Button Release"

Seems you have to restart cmder then it only woks the once also. Bit odd.
