### ISSUE TITLE
Does the Conemu autoupdater also update Cmder?

### ISSUE THREAD

**Issue by edgr-sanchez** [cmderdev/cmder#1073]
If not, is there an auto update process to get the latest version of Cmder? Or does it have to be downloaded and replaced with the latest version manually?

**Comment by Stanzilla** [comment]
ConEmu update only updates ConEmu, if you want to get the latest version of the Cmder scripts/launcher you have to download a zip again.

**Comment by UberGruber** [comment]
Hey there, 
simply placing the zip content where Cmder is installed I guess it's going to overwrite also the `bin` and `config` contents loosing settings, aliases and so on right? 

What is the best way to update Cmder keeping the customizations made?

**Comment by Stanzilla** [comment]
Your settings are preserved, no worries

**Comment by mloskot** [comment]
For those confused or lazy ones who still look for instructions

1. Download the latest ConEmu pack (eg. `ConEmuPack.180626.7z`) from https://www.fosshub.com/ConEmu.html

2. Launch `cmd.exe`

3. Remove the current ConEmu but *without* `ConEmu.xml` config file.  For example, if Cmder lives in `c:\apps\cmder_mini`:

```
cd c:\apps\cmder_mini\vendor\conemu-maximus5
c:\apps\cmder_mini\vendor\conemu-maximus5> ls -1
ConEmu
ConEmu.exe
ConEmu.map
ConEmu.xml
ConEmu64.exe
ConEmu64.map
plugins
c:\apps\cmder_mini\vendor\conemu-maximus5> rm -rf ConEmu ConEmu.exe ConEmu.map ConEmu64.exe ConEmu64.map plugins
c:\apps\cmder_mini\vendor\conemu-maximus5>ls -1
ConEmu.xml
```

4. Unpack ConEmu pack into `c:\apps\cmder_mini\vendor\conemu-maximus5`

5. Launch Cmder
