### ISSUE TITLE
Unplugging the battery detaches the Quake console

### ISSUE THREAD

**Issue by Mivexil** [cmderdev/cmder#1074]
Occasionally (apologies, but I don't think I have a good repro for that), unplugging my laptop's battery causes cmder working in Quake console mode to detach itself.

![image](https://cloud.githubusercontent.com/assets/5994816/17623472/7fc62a1a-60a0-11e6-94b1-0f5d5333e25d.png)

The console (or multiple consoles, if more than one is open) become separate windows and lose their styling, requiring me to close all windows and restart cmder. For comparison, that's how cmder looks on my PC when starting:

![image](https://cloud.githubusercontent.com/assets/5994816/17623517/c1a47158-60a0-11e6-84cf-79e77bcedb39.png)

I understand it's kind of a Heisenbug, but perhaps you have some idea as to what could be causing this odd behavior? I'd be happy to provide any relevant config information.

**Comment by Stanzilla** [comment]
Try over at https://github.com/Maximus5/ConEmu/ :)
