### ISSUE TITLE
Using F12 to Open does not work.

### ISSUE THREAD

**Issue by tiredofitdotca** [cmderdev/cmder#1076]
I'm coming from Guake on Linux and looking to emulate my Desktop experience as much as possible - I've noticed that F12 when set does not activate the Console Window, yet does close it. Any way we can force it to take over the F12 key globally?

**Comment by alexlecco** [comment]
Hi dude. Late but sure, in my settings you can do that pressing Ctrl+ñ. Obviously you can change it.
