### ISSUE TITLE
Please add better integration for "Duplicate as admin" & "Cmder Admin here"

### ISSUE THREAD

**Issue by c33s** [cmderdev/cmder#1077]
my question is about to enhance the possibilities to quickly switch to root (=Administrator) user and staying in the current directory.
## Cmder Admin here

it should be easier to configure the context menu, just a command like `setup.bat` where the steps from the manual are done:
https://github.com/cmderdev/cmder/wiki/%5BWindows%5D-%22Open-Cmder-Here%22-in-context-menu
also it would be great to have the option for a 2nd menu item `Cmder Admin here` to directly start as admin
## Duplicate as admin

currently the duplicate as admin is not that helpful because it doesn't keep the current directory. it always start in the default startup dir.
please, if possible, enhance this behavior to let a "duplicate as admin" started at `e:\myfile\myproject\foo.com` keeps that directory.
## my workaround

as workaround i added an alias `su` to handle that for me.  just typing `su` in the current console opens the same directory as root/Administrator.

C:\Program Files\Cmder\config\aliases

```
su=cmd /k "%ConEmuDir%\..\init.bat" -new_console:a:.
```

**Comment by c33s** [comment]
related issues:
https://github.com/cmderdev/cmder/issues/920
https://github.com/cmderdev/cmder/issues/544
https://github.com/cmderdev/cmder/issues/645

**Comment by Oxicode** [comment]
+1

**Comment by Stanzilla** [comment]
So basically https://github.com/cmderdev/cmder/pull/381?

**Comment by eromoe** [comment]
+1

**Comment by r15ch13** [comment]
I currently use these steps to add the context menu: https://github.com/cmderdev/cmder/pull/381#issuecomment-242130103

**Comment by c33s** [comment]
unstale

**Comment by daxgames** [comment]
You can add context menu and specify a task to launch which allows `Cmder Here` to open an admin shell if you want.

Duplicate as admin is a conemu thing you need to ask them.

**Comment by daxgames** [comment]
You could also run `cmder /single / task [task name]` to duplicate a tab as admin.
