### ISSUE TITLE
Programs that work on ConEmu are failing on Cmder

### ISSUE THREAD

**Issue by hugows** [cmderdev/cmder#1083]
See here:
https://github.com/zyedidia/micro/issues/223

Any hint on what could be going on?
Apps based on this Golang terminal package called tcell (https://github.com/gdamore/tcell) fail only for cmder, strangely working on ConEmu.

The error shown is No Suitable Screen (https://github.com/gdamore/tcell/search?utf8=%E2%9C%93&q=ErrNoScreen)

No idea where to start..

**Comment by MartiUK** [comment]
What shell are you running?

**Comment by hugows** [comment]
cmd.exe i think ?

**Comment by MartiUK** [comment]
Any issues when running it in PowerShell or cygwin/bash for windows?

**Comment by hugows** [comment]
Thanks for the reply. I was able to try Powershell easily - and it did
work. I have no idea what this means, though :)

**Comment by zyedidia** [comment]
Ok, I figured out why Cmder breaks with tcell. It's because Cmder sets `TERM=cygwin` and tcell doesn't support Cygwin.

Any ideas why Cmder sets `TERM=cygwin` if it isn't running Cygwin?

**Comment by MartiUK** [comment]
Ah, it's for git-for-windows, see: https://github.com/cmderdev/cmder/blob/master/vendor/init.bat#L40

Set TERM to something else in `%CMDER_ROOT%\config\user-profile.cmd`

**Comment by MartiUK** [comment]
If you _have _ to use cmd.
