### ISSUE TITLE
writing long lines with double quotes doesn't wrap correctly

### ISSUE THREAD

**Issue by Amleto** [cmderdev/cmder#1084]
To reproduce: keep your finger down on any key. The wrapping will skip a line:

```
aaaaaaaaaaaaaa

aaaa...
```

Maybe this is by design but the following is definitely a bug. If you are inserting characters between quotes:

e.g. enter two double quotes, then enter lots of characters between them

```
"aaa"
```

Keep going:

```
"aaaaaaaaaaaaaaaa"
```

Eventually the line wraps poorly:

```
"aaaaaaaaaaaaaaaaaaaaaaaaaa"
a
aaaaa"
```

Note that Only two double quotes were typed, but three are now shown after the line wraps. Further there is a single character on a line of its own.

**Comment by Jackbennett** [comment]
As of 1.3.2 I can't reproduce. Tested a... "aa..." and "a... including resizing the window. Must be newer clinks that fixed it.

**Comment by Amleto** [comment]
I still see it every day and I take the updates.

**Comment by Amleto** [comment]
ok, cmder updates don't update clink, it seems. I downloaded a new cmder mini and this issue is fixed.
