### ISSUE TITLE
Replacing Portable GIT with Babun

### ISSUE THREAD

**Issue by VileTouch** [cmderdev/cmder#1085]
so as you know Babun... (cygwin, should i say) has it's own git...along with a ton of other features, compared to Git for Windows's Mingw.

recently i updated it to latest from git's repo and all commands are available through zsh, cmd and powershell... so that got me thinking, what's the point of keeping the (now outdated) git folder?

am i missing something? does cmder add any special functionality to it that the babun one doesn't have?

**Comment by janschulz** [comment]
What does babun add? Git for win looks pretty "out if upstreams repo" to me (I once build it from source), so I'm a bit surprised that there should be something missing (apart from stuff which depends on a working python, e.g. hg support).

I didn't actually know that there is another distribution of git for windows... :-)

**Comment by VileTouch** [comment]
well, the git commands are similar in both (apart from the ever so useful [git subtree](https://developer.atlassian.com/blog/2015/05/the-power-of-git-subtree/), located [here](https://github.com/git/git/tree/master/contrib)) but the real meat is the full range (almost?) of nix tools as Cygwin's repo is much more complete than MinGW and...[uh, yeah](https://github.com/robbyrussell/oh-my-zsh), the rule of cool.

so it's not really "another git for windows", rather, it's a... "git that works in windows" thanks to Cygwin.

**Comment by janschulz** [comment]
Nothing prevents you from installing babun, adding git to the PATH (and maybe set the right git env variable so that cmder startup files find it) and then use it. I'm pretty happy with the current integration of the git-for-windows package (I've actually installed git-extras and stuff, so that works too...)

**Comment by VileTouch** [comment]
that's what concerns me. even though integration is perfect so far i've been wondering if there's anything more than adjusting the init script to it

**Comment by janschulz** [comment]
The integration (in init.bat -> cmd, but not ps/bash) pretty much just does this:

* figure out where git is installed (influene-able by a ENV var: `%GIT_INSTALL_ROOT%\cmd\git.exe` must exist)
* set PATH to the `cmd\` directory and the git-internal shell commands (`ls`, `grep` and friends -> at the end of PATH to not overwrite windows internal commands like `more`)

Integration is here: https://github.com/cmderdev/cmder/blob/master/vendor/init.bat#L42-L89
