### ISSUE TITLE
Add time to status

### ISSUE THREAD

**Issue by gaborbernat** [cmderdev/cmder#1086]
Hello, 

How can I add the current time inside the PS status? Potentially with the exit code of the last executed command. 

Thanks,

**Comment by Jackbennett** [comment]
Cmder 1.4 will let you customize the prompt in powershell which should offer you a mechanism to get what you're after.

Powershell populates $LASTEXITCODE for you and there's also get-history whose members have `StartExecutionTime`,`EndExecutionTime` properties.

To change this right now have a look at the prompt function in profile.ps1 but any changes there will get clobbered next update.
