### ISSUE TITLE
Cmder running very slow on Windows 10 Anniversary Update

### ISSUE THREAD

**Issue by SulivanDotEu** [cmderdev/cmder#1087]
Hello everyone,

Since one week, cmder is running very slowly on Windows 10. I noticed that on my Surface Pro 3 then today on my working station. This is frustrating and make the soft unusable. I think, obviously, one of the update is responsible for that. Where is the update I have on my working machine : 
- KB3189031
- KB3176938
- KB3176936
- KB3176934

I try to run the soft as an admin, no change.

What I observe : 
- "git status" takes +/- 5 min
- "ls" takes +/- 2 min

First time I'm creating a ticket on Github, sorry if I'm doing wrong.
Thanks in advance and thanks for this amazing soft!

**Comment by ironicnet** [comment]
Same thing is happening to me. It seems to be waiting for the "clink_x64.exe" process to finish before being avail to receive input.

Happening in the version 160828[64] and it happens in the new stable version 160904.

Same thing is happening to two other coworkers

**Comment by jimiche** [comment]
Same problem here as ironicnet!

Cmder since today it's extremely slow on Windows 10.

**Comment by SulivanDotEu** [comment]
I have 2 desktop where it runs fine. On a surface pro 3, I can try anything (reinstall, redownload, move files, whatever) it takes 5/10 min to be ready. Now running a "ls" command is faster but still less faster than 2 weeks before.

**Comment by sasha240100** [comment]
It takes 2-3 seconds to start on my PC with win10.

**Comment by ccoenen** [comment]
no problem here, either. If you'd like me to check anything for comparison, please @-mention me.

```
(Powershell)> get-hotfix

Source        Description      HotFixID      InstalledBy          InstalledOn
------        -----------      --------      -----------          -----------
XXXXXXXXXX    Update           KB3176935     NT-AUTORITÄT\SYSTEM  28.09.2016 00:00:00
XXXXXXXXXX    Update           KB3176937     NT-AUTORITÄT\SYSTEM  28.09.2016 00:00:00
XXXXXXXXXX    Security Update  KB3193494     NT-AUTORITÄT\SYSTEM  28.09.2016 00:00:00
```

`winver.exe` (Opens a GUI Popup) says, I run Windows 10 Version 1607/ Build 14393.187

**Comment by jimiche** [comment]
cmder just working perfect again since a few weeks ago 💃 . Thank you guys!

**Comment by IronSean** [comment]
cmder which is on release 161009a stable seems to be running really slow still for me on Windows 10 Anniversary Update as well. Version 1607 (14393.222).

**Comment by ccoenen** [comment]
I'd vote to close this ticket, there's not enough information to actually do anything about it.
