### ISSUE TITLE
Bad symbols

### ISSUE THREAD

**Issue by LFeh** [cmderdev/cmder#1092]
Hi guys,

I'm trying to use the bash for windows with cmder.

Everything are working perfectly, but I have a problem with bad symbols.

Can you help me?

![image](https://cloud.githubusercontent.com/assets/3603793/18392568/a13aed40-7688-11e6-9635-4d953b00d393.png)

**Comment by thatsIch** [comment]
You per change use an outdated version of clink?

**Comment by LFeh** [comment]
@thatsIch I don't know. How I can confirm?

**Comment by thatsIch** [comment]
type in `clink` and you should see some output with a version. The latest version up to now is `0.4.8`

**Comment by LFeh** [comment]
@thatsIch Sorry again. what is `clink`? Is [this](http://mridgers.github.io/clink/)?

I never use it.  😟

**Comment by LFeh** [comment]
Hey @thatsIch. I understand now.

How can I install the fonts for bash?

**Comment by thatsIch** [comment]
It is installed in your vendor folder. You are using it by default if you are using cmder, but some versions fix stuff for your OS version.

btw how do you even use bash with cmder? I just type in `bash` and it works perfectly

**Comment by LFeh** [comment]
Hey @thatsIch, the problem was the theme on the zsh. I didn't have the fonts installed. 

Thanks!
