### ISSUE TITLE
Shortcut for new tab ??

### ISSUE THREAD

**Issue by bboysathish** [cmderdev/cmder#1093]
Hi

i love cmder, i have started using it for couple days now. 

Is there way to add a shortcut to new tab ??

**Comment by MegamiSyn** [comment]
CTRL+T

**Comment by scottmathews** [comment]
Are you talking about making a new tab, or switching to a new tab? 

CTRL+0...9

You can also use CTRL+TAB (one tab forward), CTRL+SHIFT+TAB (one tab backward), or hold CTRL+TAB, then LEFT, RIGHT.

There are a lot of different answers. Are you able to specify exactly what you're trying to do?

**Comment by bboysathish** [comment]
Both CTRL+TAB (switching between tabs) and CTRL+T (create a new tab) works great. 

Thanks,
Sathish
