### ISSUE TITLE
Create shortcut for specific task

### ISSUE THREAD

**Issue by stanislavromanov** [cmderdev/cmder#1095]
I would like to request a feature to create a shortcut for a specific task.

Scenario:

Nowadays in Windows people tend to use two tasks, one for regular shell and other for Ubuntu shell. Now would it be great if we could create two shortcuts for Cmder in our taskbar when one will launch Windows shell and other will launch Ubuntu shell?

I tried to do it myself and asked question on [superuser](https://superuser.com/questions/1112088/how-to-create-cmder-shortcut-to-start-a-task) and seems that this option does not exists.

**Comment by Stanzilla** [comment]
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

**Comment by Fmstrat** [comment]
For anyone else who runs across this on Google, the command line option for this is:

```
Cmder.exe /task cmd::cmder
```

**Comment by stanislavromanov** [comment]
Thank you @Fmstrat
