### ISSUE TITLE
Ctrl+L rewrites "header"

### ISSUE THREAD

**Issue by math2001** [cmderdev/cmder#1099]
Hi
When I clear the console with `ctrl`+`L`, and scroll up, the header thing is rewritten:

![double](https://cloud.githubusercontent.com/assets/15224242/18811812/83a7a37e-8301-11e6-8fe6-ddaa8407e6a2.png)

It's not a big deal, but it's just a bit annoying, cause I think that the use `ctrl`+`L` is to clear **temporarily** the terminal, so we can still have a look at what happened before. So, this doubled header _kind_ of ruins it.

Matt

**Comment by ogrim** [comment]
This was annoying me as well, but it seems to be fixed in the latest version.

**Comment by Jackbennett** [comment]
Tested 1.3.2 and it's still doing it, But it's not overwriting anything and cls/clear do wipe everything. Hopefully a fix just comes in from conemu or clink updates in time.

powershell doesn't do this so I presume clink is at fault.
