### ISSUE TITLE
The name of the branch (git) & current dir in cyrillic

### ISSUE THREAD

**Issue by alexandr-san4ez** [cmderdev/cmder#1100]
If the path to the folder includes Cyrillic - it does not appear the name of the branch (git).
I tried to change the character (`chcp`) but it did not help.

![image](https://cloud.githubusercontent.com/assets/20110612/18837799/cfe480d8-840d-11e6-886f-78cb5d591fb5.png)

Perhaps you will have the idea of what is the reason?

**Comment by mrRosset** [comment]
Just so that you know at least on v1.29 it doesn't show a branch name in an empty git repository you needed to have added an commited stuff for (master) to appear.
So you example doesn't really prove that it doesn't work
