### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by FrambuHuesa** [cmderdev/cmder#1103]
The download links in the [website](http://cmder.net/) are broken !

`https://github.com/cmderdev/cmder/releases/download/v1.3.1/cmder.zip`

I think since you chaged versioning system and removed the `v`. Now `1.3.1`.

**Comment by MartiUK** [comment]
Fixed: https://github.com/cmderdev/cmderdev.github.io/commit/8391f5de260ddf802758950f3f37b9616ca47e5d
