### ISSUE TITLE
Maximize Active Splitted Console

### ISSUE THREAD

**Issue by madprops** [cmderdev/cmder#1105]
Hi, first of all thanks a lot for cmder, it is my favorite terminal including from all the linux terminals.

I was wondering since I couldn't find it, if there's a way to maximize one console from all of the splits when a terminal is splitted, to for instance have more space when editing files on nano and such.

**Comment by MartiUK** [comment]
I don't think we've changed the hotkeys but you can see the defaults here: http://conemu.github.io/en/SplitScreen.html
