### ISSUE TITLE
Processes dying due to lack of memory?

### ISSUE THREAD

**Issue by mctully** [cmderdev/cmder#1106]
Hi there,

Using cmder (ConEmu 160710 [64]) version 1.3.0 on Windows 10, I often get into a state where I SSH into a remote server, and then whatever command I run on the remote server, for example, vi or less, will cause the SSH session to abruptly drop with the message:

    0 [main] ssh 428204 C:\cmder\vendor\git-for-windows\usr\bin\ssh.exe: *** fatal error - cmalloc would have returned NULL

Once this starts happening, I have to shut down cmder and start a new session, in which SSH will work as normal.

The Windows Task Manager shows Consule Emulator (x64) is taking only 46.5 MB. There is plenty of free memory both on the local Windows box and the remote server.

If there is any more information I can provide I will happily assist.

Thx!

**Comment by MartiUK** [comment]
Have a look at this issue: https://github.com/git-for-windows/git/issues/356#issuecomment-138340001, unfortunately it's closed without an answer but the reporter mentioned reducing the size of the screen buffer.

**Comment by mctully** [comment]
Thanks, I had set it to 32767 and I was wondering if that could be involved somehow. I will lower it and see how I get on.

**Comment by morfien101** [comment]
I can confirm that lowering the screen buffer has also fixed my issue.

I had it set to 32000 and dropped it to 10000.
I must admit that I did not experiment on numbers but this worked for me once I opened a new console.

Build: ConEmu161206 if it helps.

**Comment by sryze** [comment]
I changed the screen buffer size to 10000 lines but still have this issue. Is there another solution?

Where do you change the buffer, is it this setting?

![buffer](https://user-images.githubusercontent.com/4525736/43572222-c0825248-9660-11e8-81e1-2264152285d0.png)

**Comment by viion** [comment]
I have this issue **ALL THE TIME** and it's so frustrating, it happens everytime i use `nano` and it's always random, i have 32gb of memory so I'm defaintly not running out, even on a 200 line screen buffer it happens, i've tried so many values, it's practically a useless option.

Can this be looked into? It happens about 15 times a day. **Only with cmder.**

**Comment by 7dir** [comment]
run As Administrator in new windows works
