### ISSUE TITLE
Up/down key (bash history) not working in Docker on Cmder

### ISSUE THREAD

**Issue by skrysmanski** [cmderdev/cmder#1108]
Cmder does not forward the up and down key to Docker containers running under Docker for Windows. Not sure whether this is actually a ConEmu or CLink issue - but since I'm using Cmder I'm reporting it here.

So, here are the steps to reproduce the problem:
1. Install [Docker for Windows](https://www.docker.com/products/docker#/windows)
2. Run `docker run -ti --rm ubuntu`
3. (Now inside the Docker container) type a command, like `ls`.
4. Hit the _up_ key. This would normally put `ls` back on the prompt but just nothing happens.

I also tried using Cmder with PowerShell - same problem.

Doing the steps above directly in `cmd` or `powershell` works without a problem.

I'm running:
- Windows 10 (not sure about the anniversary update)
- Cmder: 1.3.1
- ConEmu: 160914 stable
- Docker for Windows: 1.12.1

**Comment by otravers** [comment]
It looks like Docker for Windows 1.12.2 will solve this:
https://github.com/docker/docker/issues/13817

**Comment by elijahgagne** [comment]
I agree that Docker 1.12.2 solves this for arrow keys in bash. However, I am seeing that arrow keys are still broken when using vi/nano.

**Comment by AlexanderChou** [comment]
Up/down key didn't work in Ubuntu on Windows 10 either.

**Comment by jlost** [comment]
Any fix to up/down not working in Ubuntu for Win 10?

**Comment by 0anton** [comment]
Any fix for this?

**Comment by alzen8work** [comment]
is this still an issue?
