### ISSUE TITLE
Icon in a new window

### ISSUE THREAD

**Issue by alexandr-san4ez** [cmderdev/cmder#1111]
If you create a new window will not change the icon.
Icon ConEmu.
In version 1.2.9, it was not.
![image](https://cloud.githubusercontent.com/assets/20110612/19044052/5298c506-899b-11e6-9459-6f2771ee56c8.png)

**Comment by cagils** [comment]
So, this was closed without an answer? Any way to change the icon to lambda and not ConEmu icon? I create new window with a keyboard shortcut and ConEmu icon is bothering me a little.

**Comment by alexandr-san4ez** [comment]
Looks like this problem resolved - https://github.com/cmderdev/cmder/pull/2335, https://github.com/cmderdev/cmder/releases/tag/v1.3.15

**Comment by alexandr-san4ez** [comment]
Looks like this problem resolved - https://github.com/cmderdev/cmder/pull/2335, https://github.com/cmderdev/cmder/releases/tag/v1.3.15
