### ISSUE TITLE
Cmder goes blank?

### ISSUE THREAD

**Issue by rgfx** [cmderdev/cmder#1114]
My computer shut down unexpectedly while I had gulp running. Now my console is just blank.. When I move the directory it works, also when load C:\cmder\vendor\conemu-maximus5\ConEmu.exe instead of 64bit.  Each time I move the dir I can't got back to previous one, something weird is stored somewhere.

Weird, must be an explanation. 

Waiting for PSU replacement battery, hopefully it comes before my computer breaks or I run out directories :)

![cmder-issue](https://cloud.githubusercontent.com/assets/2388078/19135587/fad2e21e-8b22-11e6-81ab-ee9e82ca514d.gif)

**Comment by rgfx** [comment]
If I force uninstall the folder with Revo unistaller I can get the cursor back. Think it may be a registry issue.

**Comment by MartiUK** [comment]
I think you should work on getting your installation of windows back in order before saying it's an issue with cmder. Sorry.
