### ISSUE TITLE
Using The Silver Searcher(Ag) Search Chinese fail in Cmder

### ISSUE THREAD

**Issue by HomelandScenery** [cmderdev/cmder#1115]
Hello. I am using ConEmu 160710 Stable version(and default settings), and I've intall latest Cygwin and Ag package.
In Cygwin bash, searching Chinese documents is success. However in Cmder ,the search result is unreadable, can you please help ,thank a lot.
![ag](https://cloud.githubusercontent.com/assets/19407813/19138935/ff73fa2a-8bb2-11e6-9bef-6e533bffddd3.PNG)

ConEmu 160710 [64] Startup Info
 OsVer: 10.0.14393.x64, Product: 1, SP: 0.0, Suite: 0x100, SM_SERVERR2: 0

**Comment by mrRosset** [comment]
Have you tried with the solution proposed in #985 ?

**Comment by HomelandScenery** [comment]
Thanks for reply.
I both try add the text `set LANG=zh_CN.UTF-8` and `LANG=zh_CN.UTF-8` to Environment, but the problem is stile can't fix.
BTW, I use `ls` to listing file named Chinese is totally correct.
