### ISSUE TITLE
RuntimeError: Failed to beep

### ISSUE THREAD

**Issue by yuyang2009** [cmderdev/cmder#1116]
I get a "RuntimeError: Failed to beep" erro when run python script on cmder. while it works on windows cmd.The code is like:

`winsound.Beep(300,2000)`

**Comment by ahmad2smile** [comment]
Same Issue:! I'm using gulp and beeping with gutil.beep() ... Everything works fine on windows CMD but I doesn't BEEP in CMDer nor gives any error. Plz someone fix this. I love CMDer and Need the beep if I get error in code compiled.

**Comment by prahladyeri** [comment]
I'm facing this same issue in ConEmu (not using cmder).

**Comment by yairEO** [comment]
I urge the developers to fix this. Beeping is a basic and much needed in a terminal software

**Comment by xulfir** [comment]
For anyone running across this in the future, it seems to be a ConEmu feature. To disable: Settings > Features > In-console options > uncheck "Suppress bells"
