### ISSUE TITLE
git functions slow on first execution

### ISSUE THREAD

**Issue by pyeguy** [cmderdev/cmder#1117]
I love cmder but the first time I execute a git command (ie ls) it can take **many** seconds for the output to load. after the first time i execute it it pretty speedy but if i open another tab we're back to the slow execution. without understanding how the git functionality gets incorporated into ConEmu, it feels like some git functionality is getting loaded lazily, is there any way to force a "pre-load"?

**Comment by Jackbennett** [comment]
git has not ls command that must be an alias you've created, without knowing what that alias is doing I can't offer anymore advice then it must be some clever history formatting. try running each part that alias is made up off to find if there's a slow piece.

**Comment by lunyx** [comment]
@Jackbennett I suspect he means the ls bundled with git-for-windows, not an alias.  In any case, it sounds very similar to another issue that I ran into and had a workaround for here: https://github.com/cmderdev/cmder/issues/993#issuecomment-257873392

**Comment by pyeguy** [comment]
sorry for the late response. 

but yes @lunyx  is correct. 

However sometimes it feels as though all general execution is very slow compared to the native cmd.exe  terminal. Frequently launching an ipython terminal session can take ~5-10 seconds to load on a fresh cmder instance and then only ~1 second afterwards.
