### ISSUE TITLE
ANOMALY: use of REX.w is meaningless

### ISSUE THREAD

**Issue by bsamadi** [cmderdev/cmder#1118]
I have removed and reinstalled cmder on a 64-bit Windows 10 but still get the following error:

ANOMALY: use of REX.w is meaningless (default operand size is 64)

**Comment by bsamadi** [comment]
It seems that it is created by a TrendMicro OfficeScan update for Windows 10 and it has nothing to do with cmder:

http://www.areresearch.net/2016/09/win10-anomaly-use-of-rexw-is-meaningless.html

**Comment by MartiUK** [comment]
We can't do anything about AV, you need to sort it with your AV vendor.
