### ISSUE TITLE
how to let vim support python?

### ISSUE THREAD

**Issue by axiaoxin** [cmderdev/cmder#1119]
vim not support python now
vim --version show

    -python 
    -python3

how can I let cmder vim support Python?

**Comment by daxgames** [comment]
Syntax hilite?

**Comment by axiaoxin** [comment]
no, I mean the vim compile without python support, it not has("python")

**Comment by MartiUK** [comment]
We use the vim included with git-for-windows, you should probably install your own version with python support.
