### ISSUE TITLE
Startup directory on new tab

### ISSUE THREAD

**Issue by koenmetsu** [cmderdev/cmder#112]
I can't seem to find a way to set the default for "Startup directory for new process:" when creating/opening a new tab (ctrl+t). This always defaults to the location of my cmder folder, while I would like it to be empty.

Is there any way to correct this?

**Comment by vancezhu** [comment]
you can do like this:

**Comment by Artaches** [comment]
Checkout my answer here: http://stackoverflow.com/questions/31933766/start-up-cmder-conemu-console-in-a-specific-folder/43836978#43836978

Basically, create a shortcut for ConEmu and change the "Start in:" attribute in the shortcut's properties.

**Comment by maliavko** [comment]
Hey, guys. But what if I open new shell tab and want this tab to be opened in the working directory from the previous one? I use pure ConEmu + Far3 x64 and open shells using hotkeys, it works well: new shell is opened always in the directory where I was in Far tab. But it doesn't work when I use Cmder + Far3 x64.
