### ISSUE TITLE
Terminal won't remember window size.

### ISSUE THREAD

**Issue by madprops** [cmderdev/cmder#1120]
I'm not sure what I did, maybe play with split view a few, but now the terminal window always starts huge, and resizing it doesn't leave it like that on next startup. 

http://i.imgur.com/WwU2VHw.jpg

**Comment by MartiUK** [comment]
Two Qs:
- What version?
- By default, it should remember the window position and size, did you change the setting?

**Comment by madprops** [comment]
I'm not sure if I changed a setting regarding that. Do you know what can I check to make sure?

**Comment by MartiUK** [comment]
Settings > Main > Size & Pos > Check "Auto save window size and position on exit"

**Comment by madprops** [comment]
That was it :)  I had it disabled for some reason. Sorry to bother you
