### ISSUE TITLE
Haskell repl (ghci) crashes only in cmder works elsewhere

### ISSUE THREAD

**Issue by asunar** [cmderdev/cmder#1125]
Installed haskell platform and tried to run the REPL (ghci.exe). I get 
````gcc.exe' failed in phase `gcc'. (Exit code: -1073741819)```

REPL works in windows command prompt and git bash (on windows). 

OS: Windows 8.1 (64bit)
Haskell platform version: 8.0.1
cmder version: 161009 Stable

Any ideas on how to fix this issue?
Thanks.

![ghci_cmder](https://cloud.githubusercontent.com/assets/204049/19245157/3861ac6c-8ee5-11e6-962d-09146de759f3.png)

**Comment by Stanzilla** [comment]
Try updating ConEmu to 161009a https://github.com/Maximus5/ConEmu/releases/tag/v16.10.09a

**Comment by asunar** [comment]
Fixed thanks @Stanzilla
