### ISSUE TITLE
can't autocomplete file names in the same folder

### ISSUE THREAD

**Issue by luisrudge** [cmderdev/cmder#1128]
Suppose I have a file called "app.txt" in my current directory, typing "ap[TAB]" doesn't autocomplete the file name.

**Comment by luisrudge** [comment]
do you have a thread I can follow about the clink issue?

**Comment by Stanzilla** [comment]
No, sorry. I forgot to send my comment :( I meant to say that you have to file a bug over here: https://github.com/mridgers/clink

**Comment by luisrudge** [comment]
k thanks
