### ISSUE TITLE
python for cmder

### ISSUE THREAD

**Issue by totoroha** [cmderdev/cmder#1129]
Dear Team,

I changed the environment values of my computer and add python 2.7 directories to that. However, i can only access python from cmd, not from cmder. Unless i cd to C:\Python27. Is there anyway that we can propagate the environment values of system to CMDER?

Thank you so much

**Comment by totoroha** [comment]
Nevermind. The solution is right here:
------------------------
Execute .\cmder.exe /REGISTER ALL If you get a message "Access Denied" ensure you are executing the command in an Administrator prompt.

**Comment by davrenschwanner** [comment]
I ran this but still am only able to run python commands when I navigate to where I have python (in my case this is a miniconda folder). Any tips on what I might be missing?

**Comment by xuhuapeng** [comment]
Have the same problem. I can run python in default cmd of win10. However, I can not run python or conda in cmder.  I install anaconda.
