### ISSUE TITLE
Powershell Slow Startup

### ISSUE THREAD

**Issue by BClev** [cmderdev/cmder#1130]
After updating to 1.3.1, a Powershell tab takes a little over 2 minutes to start-up and allow typing. I added a stopwatch to both my profile and the profile.ps1 in cmder. The cmder profile took 2.39493755666667 minutes to finish loading, my user profile loaded in about a second. 
Is this just an isolated issue with me, or are others having similar issues?

**Comment by daxgames** [comment]
I have not seen this.

**Comment by Jackbennett** [comment]
That's strange. Is your startup directory a git repository? Just trying to rule some things out.

**Comment by Jackbennett** [comment]
Hm I replied to this on email I wonder where that's gone.

Your scripts folder isn't in program files is it?

**Comment by Jackbennett** [comment]
Your scripts folder isn't under program files is it?  Uac gets extra
excited about that path.

**Comment by BClev** [comment]
It is not. It is under ~\Desktop\Scripts. 
UAC is disabled on my machine.

**Comment by BClev** [comment]
I readded UAC, rebooted, removed it again, rebooted, and now Powershell loads quickly again. 
I think I'll chalk this up to an anomaly.

**Comment by Jackbennett** [comment]
Super weird. Thanks for the update. What version of powershell was this by the way? Just whatever w8.1 ships, you've not updated it I presume.

Not great to disable UAC FYI but that's up to you.

**Comment by BClev** [comment]
Powershell 5. 
My company disables UAC by default.
