### ISSUE TITLE
Cursor dislocation when using backspace

### ISSUE THREAD

**Issue by dfc643** [cmderdev/cmder#1132]
Cmder is a powerful tool for developing,
but there something wrong when using backspace.

When I typed a cURL command line (over than one row) 
and move cursor to the first row, then using backspace to delete a character
There something wrong happens.

The first time using bksp no any character delete

Exmaple: https://postimg.org/image/r159c2m7b/  ( Image Too Large cannot display in GIthub )

**Comment by dfc643** [comment]
seems solved in windows 10, but still in windows 7 and 8.1

**Comment by wandering007** [comment]
@dfc643 I came across the same issue when using Cmder in Win 10...

**Comment by wandering007** [comment]
@dfc643 After installing Clink, the problem is automatically solved~

**Comment by dfc643** [comment]
@wandering007 the newer cmder works fine with windows 10 ver 1703 :)
but still has problem in older windows or legacy cmd.
