### ISSUE TITLE
'ls' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by sekti92** [cmderdev/cmder#1133]
Sir i just updated cmder then i got an error like this 
![capture](https://cloud.githubusercontent.com/assets/14885417/19447802/554160a4-94c9-11e6-863b-77efc9f27ccb.PNG)

i believe this command worked before, but after i downloaded the latest one still wasn't working.
PS: I'm using cmder mini

**Comment by daxgames** [comment]
cmder mini does not include the 'ls' command so unless you have it installed elsewhere and in the path this is expected behavior.
