### ISSUE TITLE
Task Parameters SSH

### ISSUE THREAD

**Issue by ghost** [cmderdev/cmder#1134]
Oi,

I'm not able to create a task which runs `ssh user@host` after i opened the task. 

```
cmd /k "%ConEmuDir%\..\init.bat"  -new_console:d:%USERPROFILE%\Gitlab\ ssh user@host
```

tbh i did not understand well how the task is working. Where do i put my startup parameters?

**Comment by MartiUK** [comment]
What are you asking for?

Does it work? It sound like it is, do you want to know more about creating tasks? If so [this is the best link.](http://conemu.github.io/en/Tasks.html)

**Comment by geongeorge** [comment]
Can someone please help here? I too cannot figure out how to set this up

**Comment by daxgames** [comment]
Closing - See https://github.com/cmderdev/cmder/issues/2022#issuecomment-473572828
