### ISSUE TITLE
Exclude command from using mingw internal one, use windows exe instead

### ISSUE THREAD

**Issue by dehein** [cmderdev/cmder#1135]
I want to run compile makefiles with windows. While using the full edition of cmder. 
How can i exclude cmder from using the linux (mingw) make command, and instead let it use my windows make.exe ?

**Comment by MartiUK** [comment]
You can either run the exe directly: `C:\<insert dirs here>\make.exe [params]`
or
make sure the directory with your preferred make executable is earlier in your `PATH` environment variable.
