### ISSUE TITLE
Update process is intransparent

### ISSUE THREAD

**Issue by kleinfreund** [cmderdev/cmder#1141]
I'm running Windows 10 and hit _Help_ → _Check for Updates_ which doesn’t do anything. So I go to the website and download the most recent version. Since there is no installer, I go to my _old_ Cmder installation, remove everything but the `config` directory and copy the new content _without_ the `config` directory I don’t want to the location.

Surprise, as I now remember, all my settings are gone besides importing the ConEmu.xml I kept in `config`. This happened to me multiple times and becomes very frustrating.

How is one supposed to update this software? Are there any directiosn? Is there a simple _copy everything to your location_ approach I missed?

**Edit:** All my startup tasks are gone as well. This is really not so great. :(

**Comment by daxgames** [comment]
Download the new version and copy it to you old location.  That's it.

**Comment by Stanzilla** [comment]
it's kinda hard for a compilation/pack to communicate it's own version properly, sadly.

**Comment by daxgames** [comment]
One clarification the only piece of configuration stored outside the config directory is the conemu.xml which is where all of your startup tests are kept kept.

I have an open pull req that resolve this issue it just needs to be merged.
