### ISSUE TITLE
Completely non technical issue

### ISSUE THREAD

**Issue by AaronKaa** [cmderdev/cmder#1142]
Where can I get the desktop background you use behind cmder screenshots - looks awesome :)

**Comment by Jackbennett** [comment]
I had no luck with a reverse image search but it might be like any sky image with noise filter and a sepia filter to my eye. @samvasko as the original author would be the only one who knows. 

Here's the [metadata](http://regex.info/exif.cgi?imgurl=https%3A%2F%2Fraw.githubusercontent.com%2Fcmderdev%2Fcmderdev.github.io%2Ff6518cc02dd2a861376bd016bdf4e3bfd4fe0d61%2Fimg%2Fmain.jpg) from the original commit in case there's a clue

**Comment by samvasko** [comment]
[its your lucky day](http://666a658c624a3c03a6b2-25cda059d975d2f318c03e90bcf17c40.r92.cf1.rackcdn.com/unsplash_5239196e5ae68_1.JPG)

**Comment by AaronKaa** [comment]
You star - thanks you guys :)
