### ISSUE TITLE
Attempt to concatenate local 'package) nil value

### ISSUE THREAD

**Issue by csmithersslc** [cmderdev/cmder#1145]
Hi!  I tried to use the fixes in the lua files int eh past fix and those don't seem to work on this.  My CMDR is up to the latest version. 
This is what it reads out : 
`...iles (x86)\cmder/vendor/clink-completions/npm_prompt.lua:12: attempt to concatenate local 'package_version' (a nil value)
C:\Users\User\Directory\folder\file {git}{hg}`

**Comment by reecebradley** [comment]
I had this problem today and fixed it locally.

I'm not a lua programmer but cracking open the "npm.lua" file at line 209 is pretty clear that the JSON:decode return a nil (null) object.

Looking at the code, the error can be avoided by adding this line
`if not package then return false end`

Below is the full function with the fix. Cofee & Pasta the code into your `npm.lua` file and walla, should work.

```lua
function npm_prompt_filter()
    local package_file = io.open('package.json')
    if not package_file then return false end

    local package_data = package_file:read('*a')
    package_file:close()

    local package = JSON:decode(package_data)
    if not package then return false end
    if not package.name and not package.version then return false end

    local package_name = package.name or "<no name>"
    local package_version = package.version and "@"..package.version or ""
    local package_string = color.color_text("("..package_name..package_version..")", color.YELLOW)
    clink.prompt.value = clink.prompt.value:gsub('{git}', '{git} '..package_string)

    return false
end
```

good luck. 
I'll submit a pull request...eventually.

**Comment by vladimir-kotikov** [comment]
This has been fixed in https://github.com/vladimir-kotikov/clink-completions/pull/64 and released in 0.3.2, so hopefully will be available in next Cmder release.

/cc @Stanzilla

**Comment by Stanzilla** [comment]
I currently can't touch `master` because of some setting @MartiUK changed. Also waiting for a decision on which branch to use going forward.

**Comment by MartiUK** [comment]
@Stanzilla You should be able to make changes to master again.

**Comment by Stanzilla** [comment]
@MartiUK cool, thank you! What branch to use for what going forward then? I remember talks where people suggested going with master for everything vs master/dev. Currently we accept PRs on both branches and it kinda is a mess.
