### ISSUE TITLE
How to remove master tag from path

### ISSUE THREAD

**Issue by MandarSant** [cmderdev/cmder#1147]
In my cmder in path C:\Users\(Username)  **_(master)_**  how do i remove this master  and why it is showing master in it

**Comment by Jackbennett** [comment]
It's your current git branch name. you'll have to customise the prompt function to remove it if you don't want the git status printed there.

**Comment by daxgames** [comment]
is your home folder a git repo?

**Comment by mandar262** [comment]
@Jackbennett @daxgames  how do i remove it i dont know how to use the git i installed because bower requires git can you tell me the steps to remove it

**Comment by mrRosset** [comment]
Is there a folder called ".git" (notice the dot before the name) in C:\Users\<yourname> ?
Yes: Delete it
No: Look in C:\Users\, if there still isn't, it's probably in C:

Note: if you use the "ls" command the folder will not be liste, use "ls -a" or "dir" or the explorer.

**Comment by Jackbennett** [comment]
Careful there @mrRosset just advising deleting files mandar262 might not realise they were using it.

@mandar262 you only need git installed for bower, you don't need to be using `git init` if you're not using git. Any folder you've ran `git init` inside then cmder will show you gits information about it. Bower will use git for it's own purposes you shouldn't need to see.

**Comment by mandar262** [comment]
@Jackbennett i didnt got what ru saying

**Comment by daxgames** [comment]
'git init' makes any folds fit is run in a git repository.  Git supports branches and the default branch is called master.  Cmder is telling you you are in a folder that is a git repository and you are on the master branch.  It is a very useful feature of you use git.  

Did you type 'git init' in 'C:\Users\(Username)'?  There is probably a folder in this location called '.git' if you rename it the 'master' will go away.  Keep in mind if you did not type git init and some other process did this to track changes for you you could break something.

**Comment by mandar262** [comment]
@daxgames git is only installed no use for rather i dont know how to use git me and i have also not typed git init so insted of asking me what i have tried/ have i tried this,that just tell me easy steps to remove it Please..!! A BIG SORRY If this comment is rude for u...

**Comment by daxgames** [comment]
@MandarSant did you get whanted out of this?

**Comment by MandarSant** [comment]
@daxgames i just deleted ` .git`  folder
