### ISSUE TITLE
What is mintty in here?

### ISSUE THREAD

**Issue by fghhfg** [cmderdev/cmder#1149]
<img width="735" alt="2016-11-03 19_55_28-program manager" src="https://cloud.githubusercontent.com/assets/1284845/19964984/ba136e12-a1ff-11e6-9cea-54f448ee7484.png">

cmd/bash/powershell is a script language.

conEmu is a GUI window (terminal), which can show some text to me.

cmder runs on `conEmu`.

Mintty is also a GUI window (terminal).

mintty runs inside conEmu?

**Comment by daxgames** [comment]
You got it, mostly.  

cmd/bash/powershell are shells that you can use to write scripts.

conEmu is a GUI terminal that can run multiple shells in tabs as well as other applications if desired.

ConEmu is a part of Cmder along with Git for Windows, Clink, Clink Completions, and a whole bunch of scripting tying them all together.

Mintty is the native graphical terminal of Git for windows that is integrated into Cmder along with bash.exe - see the Cmder readme.md for differences between Mintty and bash.exe.

**Comment by fghhfg** [comment]
OK, it just show differ color schemes and key bindings, mostly. :open_mouth:

> Cmder, PowerShell, and Bash tabs all run on top of the Windows Console API

> Mintty tabs use a program called 'mintty' as the terminal that is not based on the Windows Console API

> Mintty differs from the other tabs in that it supports xterm/xterm-256color TERM types, and does not work with ConEmu settings like color schemes and key bindings. For more on Mintty and its config click [here](https://github.com/mintty/mintty).

**Comment by zaphod77** [comment]
mintty is also why the xterm emulation actually works. :)

by default conemu's does not. (test with win32 ssh.exe and pico text editor if yo udon't believe me. CMDer works fine. Conemu standalone does NOT.
