### ISSUE TITLE
Launcher start argument only takes directories

### ISSUE THREAD

**Issue by queimadus** [cmderdev/cmder#115]
Launcher start argument only accepts directories paths. 

Enabling it to work with arbitrary paths would enable "Run with" funcionality with the launcher.

if the path isn't a directory, **cd** to the file's directory and run the file in cmder.

**Comment by tomasfejfar** [comment]
@Shoozza that does not work for me - the cmd gets opened in background but the output is not in the Cmder window opened afterwards.

**Comment by tomasfejfar** [comment]
Oh I missed that I was supposed to add stuff to init.bat as well :) Now it works. Nice. :+1:
