### ISSUE TITLE
Cmder after alias，restart report error，maybe cause by chinese in the path

### ISSUE THREAD

**Issue by wenbaofu** [cmderdev/cmder#1151]
set is ok，and alias work fine
![image](https://cloud.githubusercontent.com/assets/20511885/20036073/2aa2714e-a437-11e6-8627-75b58f80afc1.png)

when restart，alias can not work
![image](https://cloud.githubusercontent.com/assets/20511885/20036078/78a1bc88-a437-11e6-86dd-9119c3223c72.png)

**Comment by wenbaofu** [comment]
when I remove the chinese from the command,it work fine.......

**Comment by mrRosset** [comment]
Tried with the solution of #985 ?

**Comment by Stanzilla** [comment]
Yep,
