### ISSUE TITLE
Cygwin?

### ISSUE THREAD

**Issue by Xeryko** [cmderdev/cmder#1155]
It's not an issue but more a feature.
Is it possible to use cygwin DLL with Cmder?
As this, I think we can have a fully powerfull and personnal console emulation on windows!

Anyway, your work is awesome and I can't have a Windows without Cmder now xD Thanks all the team!

**Comment by mrRosset** [comment]
[Like this](https://github.com/cmderdev/cmder/wiki/%5BWindows%5D-Integrating-Cygwin) ?

**Comment by Xeryko** [comment]
Ah... Yeah sorry for the issue created xD
