### ISSUE TITLE
When package.json is present and empty, line colouring stops showing up.

### ISSUE THREAD

**Issue by renatoliveira** [cmderdev/cmder#1159]
`C:\cmder/vendor/clink-completions/npm.lua:209: attempt to index local 'package' (a nil value)`

Using ConEmu 161022 Stable on Windows 10 x64, after creating a directory with `mkdir`, and then using `touch` to create a `main.js` file and a `package.json`, colours stopped appearing (like in this screenshot http://imgur.com/bF7vSp3).

After 'cd'ing to the directory, right after restarting Cmder, the error still shows up.

Edit: just noticed this happens only if the package.json is empty. Maybe it should be ignored in case it is empty, instead of throwing that error.

**Comment by savovs** [comment]
I fixed this by removing trailing commas in package.json

Wrong:
```javascript
dependencies: {
  "react": 15.3.2,
  "react-dom",
}
```

Right:
```javascript
dependencies: {
  "react": 15.3.2,
  "react-dom"
}
```

**Comment by renatoliveira** [comment]
This is fixed by [**this**](https://github.com/vladimir-kotikov/clink-completions/commit/795f6a927df4ef16a3ecdefc99ec839b747a2946) commit on clink-completions' repository. Cmder needs to use a newer version of clink-completions.
