### ISSUE TITLE
"Cmder Here" right-click doesn't pass folder to minTTY

### ISSUE THREAD

**Issue by tomByrer** [cmderdev/cmder#1163]
I prefer bash::mintty, so I changed to it in the ConEmu Settings:Startum.  However, if I right-click in Windows Explorer for the "Cmder Here", it does open minTTY as the default terminal, but the current folder is not adjusted to where I activated Cmder; it is set to the default '~home'.  If I open a new terminal Cmder terminal from inside the (new) current ConEmu, the chosen folder is active there.

The problem may be bash; home folder is default there also.

**Comment by eromoe** [comment]
Remove `%USERPROFILE%` in tasks, done.

**Comment by arvindch** [comment]
I fixed this in a diff way - https://gist.github.com/arvindch/5895d58fabe3cb7678b7c6d3a66a9349

**Comment by tomByrer** [comment]
Thanks, but neither worked.
My Task for minTTY:
`%ConEmuDir%\..\git-for-windows\usr\bin\mintty.exe /bin/bash -l -new_console:d:%userProfile%`

**Comment by arvindch** [comment]
Oh, I thought you meant in the `Open Cmder here` integration. Because substituting `%V%` in place of `%userProfile%` passes the selected path instead.

**Comment by tomByrer** [comment]
Yes, `%V%` doesn't work for me; I get an error.

**Comment by arvindch** [comment]
Oops, my bad. It's just `%V`, as such: `{Powershell::Powershell} -cur_console:n:d:"%V"`

**Comment by stayfools** [comment]
Try to replace %userProfile% with %CMDER_START%, and it works for me.

**Comment by pingshunhuangalex** [comment]
Not just for minTTY, actually bash is the only one that doesn't take current directory at all, including Git Bash and Windows Bash as reported [here](https://github.com/cmderdev/cmder/issues/1063) and [here](https://github.com/cmderdev/cmder/issues/709#issuecomment-158489521)

**Comment by hiddenalpha** [comment]
Worked for me (see CMDER_START at end):
`cmd /c "%ConEmuDir%\..\git-for-windows\bin\bash --login -i" -new_console:d:%CMDER_START%`

Source:
- Followed first link of @pingshunhuangalex (https://github.com/cmderdev/cmder/issues/1063)
- Then found it in @xschen s post from 2017-02-24.

**Comment by borela** [comment]
I tried previous methods but it didn't work on Windows 10. After some hours of praying, got the answer:

**Icon:** `/icon "C:\Program Files\Git\mingw64\share\git\git-for-windows.ico"`

**Task command:** `"C:\Program Files\Git\git-cmd.exe"  --command=usr/bin/bash.exe -li -new_console:d:%CMDER_START%`
