### ISSUE TITLE
Lua files in config aren't being read

### ISSUE THREAD

**Issue by Aetylus** [cmderdev/cmder#1164]
It doesn't seem like custom `lua` files placed in the config directory are being read. The documentation suggestions that a `cmder.lua` file is supposed to read them in, but that file doesn't appear to exist. The end of the `clink.lua` file does read in additional `lua` files, but only from the /vender/clink-completions directory. 

I added a similar snippet of code right after that to read from the config directory, however, and that seemed to work:

    -- Load additional lua scripts from the config directory
    local config_dir = clink.get_env('CMDER_ROOT')..'/config/'
    for _,lua_module in ipairs(clink.find_files(config_dir..'*.lua')) do
        -- Skip files that starts with _. This could be useful if some files should be ignored
        if not string.match(lua_module, '^_.*') then
            local filename = config_dir..lua_module
            -- use dofile instead of require because require caches loaded modules
            -- so config reloading using Alt-Q won't reload updated modules.
            dofile(filename)
        end
    end

**Comment by janschulz** [comment]
[This](https://github.com/cmderdev/cmder/blob/master/vendor/init.bat#L34) lines (the profile part) should get all lua scripts in `config` getting executed.
