### ISSUE TITLE
Multiple git instances running

### ISSUE THREAD

**Issue by natewaldrop** [cmderdev/cmder#1166]
When launching git mergetool (Beyond Compare 4) and merge conflicts occurred, cmder seems to lose control of the git.exe process it spun up. This causes 1 or 2 git.exe to continue spinning up with every additional git call. Once an index.lock file is created from the merging process, nothing can commit any new changes because of the index.lock. Closing cmder doesn't kill the git.exe processes, and requires closing them manually before any tool can finish the commit. (Git Bash, Sourcetree...etc)

This is the error message I am getting:

> Another git process seems to be running in this repository, e.g.
> an editor opened by 'git commit'. Please make sure all processes
> are terminated then try again. If it still fails, a git process
> may have crashed in this repository earlier:
> remove the file manually to continue.

**Comment by drath3000** [comment]
I get the exact same issue where the index.lock file is created when simply running the 'ls' command in the root repo directory. I can see that git processes are created and aren't being destroyed and that the index.lock file is indeed created. If I restart I get the same issue. If I kill of the spawned git processes I can then delete the lock file but it gets created when I enter the directory via CMDR or use CMDR to run a command (even a git status).

The stranger part is this only occurs in 1 of my workspace/repo's, everything appears to work fine in the others...

**Comment by natewaldrop** [comment]
I can not replicate this issue when using Git Bash (understandably), but as darth3000 mentioned, it is creating the index.lock file, and doesn't ever kill off the spawned processes. Manually killing all git processes, and deleting the file temporarily fixes the issues, but my branch is still in the middle of a merge, and it recreates the problem when I launch it again.

**Comment by mariotacke** [comment]
Just ran into the same problem. Cmder just being within the repo directory spawned a git process and created a lock file. From there I was unable to add files or commit. I was able to commit my changes by closing Cmder, removing the lock file through regular cmd.exe and committing through cmd.exe as well.

**Comment by christRescues** [comment]
I have the same exact problem.  Are there any real fixes yet?

**Comment by Stanzilla** [comment]
@christRescues try a dev version and tell me if it still happens, please! https://ci.appveyor.com/project/MartiUK/cmder/build/artifacts

**Comment by christRescues** [comment]
@Stanzilla Same issue.  It seems as though Cmder spawns a new git.exe instance as soon as I cd into a folder that has a git repo with a dirty head (*branch name is in red*) 🔴 .   Then, no matter what command I run, as soon as I press **"enter"** Cmder spawns another git.exe instance.

**Comment by smartpcr** [comment]
reinstalled git on windows, pick option "Checkout-as-is, commit as-is", problems seems gone.

**Comment by christRescues** [comment]
Same for me.  Git instances seem to be exiting properly now 👍

**Comment by drath3000** [comment]
I haven't been able to re-create the issue (it seems to be intermittent). I've updated to git 2.11.0.windows.1 from the previous version and had the issue occur once in the same repo but never again (I have 20+ checked out and it only ever occurred in 1 of them).

Everything seems to be working fine at the moment but if it occurs again I will try and get a test case together and add it in here.
