### ISSUE TITLE
Admin profile not authenticating

### ISSUE THREAD

**Issue by crutchcorn** [cmderdev/cmder#1167]
When I try to use the default CMD or Powershell admin profile, I do not get a UAC asking for authentication anymore, like I used to. Nor do I get admin privileges from the shell.

**Comment by mrRosset** [comment]
I remember on 1.29 (haven't tested since) using ctrl+t or the green plus button caused the same thing to happens, but opening the menu next to the green button and choosing "cmd as admin" worked.

**Comment by crutchcorn** [comment]
I'll be damned. That did it. As you said though, nowhere else works

**Comment by mrRosset** [comment]
So I tried with an old version of 1.29 I had copied somewhere, didn't update conemu when asked, everything worked fine. Did the conemu update and now it doesn't work anymore in the normal way only with the sub-menu.

**Comment by crutchcorn** [comment]
I discovered that it was due to a new button being added (AFAIK, new)
called "Run as admin". It's unchecked by default, no matter your profile.
Check it on any profile and it'll work. I think it should read from the
profile and allow you to check or uncheck after that.

**Comment by mrRosset** [comment]
I'm seeing the button you are talking about in 1.3.1 mini nor in 1.2.9:
http://i.imgur.com/xBJlu4Q.png
Where is it ?

**Comment by mrRosset** [comment]
You are right a new button appeared in the open task window.
I tried conemu on it's own (last version: 161022) and the problem is present there too. If you change the default task "cmd" by adding a * at it's start the same problem occurs (doesn't worked unless checked new button but work in sub-menu). So it's a "bug" on conemu side.

**Comment by NitroBAY** [comment]
Please where is run as admin button ?
