### ISSUE TITLE
Does cmder support the notion of a plugin

### ISSUE THREAD

**Issue by adriatic** [cmderdev/cmder#1173]
If this is a trivial question, the answer is well hidden as I was not able to find anything except a few old questions discussing the use of cmder command line arguments. 

I would like to programmatically launch cmder and specify its screen position and size at a minimum. If I can write a plugin that would listen to a specific address and then use cmder's "internal" commands, that would be a breeze.

Can this be done?

**Comment by Stanzilla** [comment]
https://github.com/cmderdev/cmder/pull/849
