### ISSUE TITLE
some kind of project profile

### ISSUE THREAD

**Issue by luisrudge** [cmderdev/cmder#1175]
Let's say I'm working in project 1 and project 2. I'd like to setup a project profile that sets all my windows in a specific way.
For example:

## Project 1

**2 consoles, split horizontally**
**console 1**: `c:\projects\project1> npm start`
**console 2**: `c:\projects\project1\src> npm run test:ci`

## Project 2

**3 consoles, split vertically**
**console 1**: `c:\projects\project2> npm start`
**console 2**: `c:\projects\project2\src> npm run test:ci`
**console 3**: `c:\projects\project3\src> npm run lint:ci`

So, ideally, I'd setup the terminals the way I want and then "save" this profile.

**Comment by cj525** [comment]
You can accomplish this using the ConEmu Tasks.. Simply create a new task, click "Taskbar jump lists", set an optional Hotkey, and fill in the Commands section.  Here is an example of a vertically-split cmd.exe session, with a 64 bit pane on top and a 32-bit pane on bottom:

```
> "%windir%\system32\cmd.exe" /k ""%ConEmuBaseDir%\CmdInit.cmd" & echo This is Native cmd.exe"

"%windir%\syswow64\cmd.exe" /k ""%ConEmuBaseDir%\CmdInit.cmd" & echo This is 32 bit cmd.exe -new_console:s50V"
```

Access this feature by pressing Win-Alt-T or clicking the green '+' icon on the bottom-right and selecting 'Setup Tasks...'

**Comment by luisrudge** [comment]
Thanks @cj525!
