### ISSUE TITLE
Question: How to hide the left and right borders of a regular mode window?

### ISSUE THREAD

**Issue by Mark-Han** [cmderdev/cmder#1176]
Hi there,
I forgot how to do that. I have tried for hours but in vain.
#324  only applies to a quake style window.
Thanks.

**Comment by Mark-Han** [comment]
@Stanzilla Your reaction to this issue makes no sense.

**Comment by daxgames** [comment]
What reaction, closing It as an upstream issue?  It is an upstream issue.
