### ISSUE TITLE
Disable Auto Scrolling

### ISSUE THREAD

**Issue by nalandial** [cmderdev/cmder#118]
This might be really simple and I've looked around the ConEmu documentation but I can't quite figure out how to get this work with cmder. I simply would like the Scroll Lock feature; that is to say, have scrolling enabled, but when text is printed to the console, don't move the cursor down to the bottom. This is nice if I want to look at some output of a process while it's still running, like how Cygwin does it.

**Comment by ruicovelo** [comment]
Hi!

I got here searching for how to configure this. Apparently I can't yet.

:+1:

**Comment by felixSchl** [comment]
That feature would be great to have!

**Comment by Jackbennett** [comment]
I can't see a conEmu setting so this would be something to request with that project, which we may or may not turn on by default. 

Use @MartiUK suggestion (pipe to more) which is more robust as its not specific to an application setting.

`thiscommandproducesmanylines.exe | more`

**Comment by PeteW** [comment]
Pipe to more is a hacky workaround. More loses console output colors. It comingles [--more--] text into the output as you scroll. The better thing I can find is the pause/break key on the keyboard. But bear in mind many laptop manufacturers actually do not support those keys.
