### ISSUE TITLE
Archive file for download is not available

### ISSUE THREAD

**Issue by Dmdv** [cmderdev/cmder#1188]
See the link published in readme.

**Comment by noformnocontent** [comment]
this link?
https://github.com/cmderdev/cmder#installation >> https://github.com/cmderdev/cmder/releases/

**Comment by abrownwv** [comment]
http://cmder.net/ Download Mini and Download Full buttons do not work. They link to 
https://github.com/cmderdev/cmder/releases/download/1.3.1/cmder_mini.zip
and
https://github.com/cmderdev/cmder/releases/download/1.3.1/cmder.zip
which return githubs 404 page

**Comment by noformnocontent** [comment]
yep, its resolved in cmderdev/cmderdev.github.io#9 now waiting for OP to merge
