### ISSUE TITLE
"chcp 65001" (UTF-8) support for cmd

### ISSUE THREAD

**Issue by pihug12** [cmderdev/cmder#119]
Hello!

What's the proper way to support UTF-8 in cmd with **cmder**?
Executing `chcp 65001` works well. I tried to add it in _/vendor/init.bat_ but is shows up every time I open a new tab.

Here is some links :
- http://stackoverflow.com/a/3473206
- http://superuser.com/a/692230

Thanks

**Comment by promethe42** [comment]
Just ran into the same problem and searched for hours...
Maybe that should be in `/vendor/init.bat` by default? But I don't know...

**Comment by janschulz** [comment]
I have that in my user startup file, but there are sometimes problems, the worst is ` more`:

```
λ more
Nicht genügend Arbeitsspeicher. # Not enough free RAM
λ echo "hello" | more
Nicht genügend Arbeitsspeicher.
```

I had some fun until I found out what it was: https://github.com/tj/git-extras/blob/master/install.cmd#L13

**Comment by david-learner** [comment]
@samvasko Thank you!
I need to set UTF-8 on intellij console using cmder.
So added `@set LANG=ko_KR.UTF-8` in /vendor/init.bat
![177](https://user-images.githubusercontent.com/19724220/39503732-7cf29c78-4e02-11e8-8e47-cc32347d38e1.jpg)

It works good.

**Comment by chabinot** [comment]
Hello,
I do the same, but i replace ko_KR by fr_FR as follows 👍 
`echo :: use  in front of the command to prevent printing the command
    echo.
    echo :: uncomment this to have the ssh agent load when cmder starts
    echo :: call "%%GIT_INSTALL_ROOT%%/cmd/start-ssh-agent.cmd"
    echo.
    echo :: uncomment this next two lines to use pageant as the ssh authentication agent
    echo :: SET SSH_AUTH_SOCK=/tmp/.ssh-pageant-auth-sock
    echo :: call "%%GIT_INSTALL_ROOT%%/cmd/start-ssh-pageant.cmd"
    echo.
    echo :: you can add your plugins to the cmder path like so
    echo :: set "PATH=%%CMDER_ROOT%%\vendor\whatever;%%PATH%%"
    echo.
    ) > "%CMDER_ROOT%\config\user-profile.cmd"
)
@set LANG=fr_FR.UTF-8
exit /b'
It seems not working, the character "é" becomes |-&reg;
