### ISSUE TITLE
The first letter may be stuck....

### ISSUE THREAD

**Issue by zhangchen915** [cmderdev/cmder#1190]
When I press ↑, the first letter may be stuck, and will not be deleted, just like the following GIF.
![gif](https://cloud.githubusercontent.com/assets/14519018/20960253/7e92fb04-bc9a-11e6-9d56-a671b4a29ad0.gif)

**Comment by x9t9** [comment]
I can confirm this behavior . Although not consistent ...

**Comment by Stanzilla** [comment]
Continue here please https://github.com/mridgers/clink/issues/409
