### ISSUE TITLE
git-for-windows can't support Chinese characters in v1.3.2

### ISSUE THREAD

**Issue by codesboy** [cmderdev/cmder#1193]
After my testting ,the new version v2.11.0 of GIT will be garbled.But I  switched to the previous version 2.9.3 it works fine.
![1](https://cloud.githubusercontent.com/assets/9047357/21001844/9922562c-bd5d-11e6-8fc5-253b61b2a4d5.png)
![2](https://cloud.githubusercontent.com/assets/9047357/21001854/9dda84dc-bd5d-11e6-8262-ddc7efe90c04.png)
![3](https://cloud.githubusercontent.com/assets/9047357/21001900/e8c0c3c6-bd5d-11e6-9ba8-791ecbd12826.png)

**Comment by Stanzilla** [comment]
Please report over at https://github.com/git-for-windows/
