### ISSUE TITLE
1.3.1 release rename breaks chocolatey package

### ISSUE THREAD

**Issue by steveire** [cmderdev/cmder#1194]
The package

 https://chocolatey.org/packages/Cmder

is no longer installable.

	Attempt to get headers for https://github.com/cmderdev/cmder/releases/download/1.3.1/cmder.7z failed.
	  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://github.com/cmderdev/cmder/releases/download/1.3.1/cmder.7z'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
	Downloading cmder
	  from 'https://github.com/cmderdev/cmder/releases/download/1.3.1/cmder.7z'
	ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://github.com/cmderdev/cmder/releases/download/1.3.1/cmder.7z'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."

The issue seems to be the addition of a 'v' before the version numbers.

**Comment by Stanzilla** [comment]
Please report that to the chocolatey package maintainers.
