### ISSUE TITLE
Using the λ character as prompt when in cygwin

### ISSUE THREAD

**Issue by born2net** [cmderdev/cmder#1195]
I am using cygwin but would love to have the same λ prompt character, is it possible?

see image
![prompt](https://cloud.githubusercontent.com/assets/5090936/21081838/b8e266d2-bf83-11e6-9c15-c456b4103d78.PNG)

regards

Sean

**Comment by daxgames** [comment]
Yes.  Look at the readme.md about using cygwin with cmder and cmder_xinit in the cmder/vendor folder.

**Comment by born2net** [comment]
ya I configured cygwin and all working, but still has old prompt.. not λ
regards

**Comment by daxgames** [comment]
From cygwin type 'ls /etc/profile.d/cmder*' and post the output here?  Also what shell are you using with cygwin?  Bash?  Type 'echo $SHELL' to find out.

**Comment by born2net** [comment]
I guess I dont have that file as this is my output
```
root@DESKTOP-VEUHFOL /cygdrive/c/msweb/ng2Boilerplate
$ ls /etc/profile.d/cmder*
ls: cannot access '/etc/profile.d/cmder*': No such file or directory

root@DESKTOP-VEUHFOL /cygdrive/c/msweb/ng2Boilerplate
$ echo $SHELL
/bin/bash

root@DESKTOP-VEUHFOL /cygdrive/c/msweb/ng2Boilerplate
$
``` 
tx for the support,

Sean

**Comment by born2net** [comment]
I think I may be missing the file since I am running the lite version of cmder

**Comment by born2net** [comment]
so I copied that file:
```
root@DESKTOP-VEUHFOL /cygdrive/c/msweb/ng2Boilerplate
$ ls /etc/profile.d/cmder*
/etc/profile.d/cmder_exinit.sh
```
what's the next step?

regards

**Comment by daxgames** [comment]
Actually * am wrong. That file has nothing to do with the prompt.  I will see if I can find it and let you know.

**Comment by born2net** [comment]
thanks...

**Comment by daxgames** [comment]
Save this file to /etc/profile.d 

https://github.com/cmderdev/cmder/blob/master/vendor/git-prompt.sh

And start a cygwin session.

**Comment by born2net** [comment]
sweeet.... tx, I appreciate it, that did it!!!
tx again,
Sean
