### ISSUE TITLE
Download links on http://cmder.net/ are broken 

### ISSUE THREAD

**Issue by lanzkron** [cmderdev/cmder#1196]
The download links on http://cmder.net are currently broken:
Full: https://github.com/cmderdev/cmder/releases/download/1.3.1/cmder.zip
Mini: https://github.com/cmderdev/cmder/releases/download/1.3.1/cmder_mini.zip

The `v` is missing in the version number (also shouldn't it be 1.3.2?)

**Comment by ogrim** [comment]
I'm currently seeing the correct link (https://github.com/cmderdev/cmder/releases/download/v1.3.2/cmder_mini.zip)

**Comment by lanzkron** [comment]
@ogrim I see it too now. (I'm pretty sure I'm not insane and it wasn't like this an hour ago...)
