### ISSUE TITLE
The last version is not work with webpack & babel

### ISSUE THREAD

**Issue by Cacivy** [cmderdev/cmder#1197]
OS: Windows 10
version 161206
![webpackfail](https://cloud.githubusercontent.com/assets/8381177/21093137/3821e80c-c08b-11e6-88e9-07d620838bb4.png)
it's error

version 161022 or git bash
![webpackok](https://cloud.githubusercontent.com/assets/8381177/21093150/49696338-c08b-11e6-873a-5e6de831f7b8.png)
It's right

And the ConEmu is ok

**Comment by Stanzilla** [comment]
Please report that on the ConEmu issue tracker
