### ISSUE TITLE
Multiple instances of git (each created by single activity in local git repository)

### ISSUE THREAD

**Issue by quasarea** [cmderdev/cmder#1198]
Versions

ConEmu build: 161206 x64
OS version: Windows 7 x64
Used shell version: cmd::Cmder

Problem description

Multiple instances of git processes are invoked by any command after accessing local git repository.
Each is locking repository so committing is no blocked.
Got fresh update of cmder and fresh install of git (git version 2.11.0.windows.1)

Steps to reproduce

enter local git repository (notice tab name will change to git.exe)
type any command, i.e. echo "a" multiple times
each command opens new git sub process
Actual results

multiple git processes running

Expected results

one git process handling all the activity in the repository

![2016-12-08 17_43_33-cmd](https://cloud.githubusercontent.com/assets/10334982/21099590/e7827bba-c066-11e6-9eef-d3ffa4791a9a.png)

![2016-12-08 17_44_18-cmd](https://cloud.githubusercontent.com/assets/10334982/21099594/ec927fe2-c066-11e6-85aa-f086434a5f6a.png)

**Comment by jamesjrg** [comment]
I too have this issue, have you found a way to disable git support? I'm fine using cmder without the git-aware prompt, but this behaviour makes it unusable as is.

**Comment by quasarea** [comment]
Nope, nothing new from my side. I'm running git in separated consoles and avoiding git folders in cmder.

Tired to reinstall both in different order, did not help at all.

**Comment by glucas** [comment]
I've seen this problem before, but haven't had it in a while. I think this is related to git processes not terminating properly, see https://github.com/cmderdev/cmder/issues/1060 for related discussion.

**Comment by DeezCashews** [comment]
Just adding my observations, same problem.  Didn't happen until I updated to Windows 10 last night but that's not to say Cmder didn't upgrade as well.  Tried a fresh install of Cmder + Git for windows after uninstalling my own Git for Windows.  Still getting same error.  Even doing

git status -> creates lock file
git add --all -> Failed because lock file still exists and there are handing git processes

This only happens in cmd, not in Powershell or bash through Cmder.

**Comment by quasarea** [comment]
@Stanzilla - was it fixed?

**Comment by Stanzilla** [comment]
Yeah should be

**Comment by DeezCashews** [comment]
Use Powershell if you can.

**Comment by hassan-kassim** [comment]
use this for remove the git running process.

`rm -f .git/index.lock`
