### ISSUE TITLE
Issue on Dual Monitors Buffer can been seen and doesn't scroll.

### ISSUE THREAD

**Issue by bgallagh3r** [cmderdev/cmder#120]
I recently installed Cmder on my Win 8,1 laptop.  It works great until I plug in my second monitor then all hell breaks loose.  I have Cmder set to 100%x40% with Quake mode turned on, every time I close and re-open Cmder I am able to see a black bar at the bottom, which grows each time I open close it.  I also noticed once the black part reaches the bottom of my screen I am unable to scroll inside Cmder's buffer.

**Comment by Festum** [comment]
@Zolli didn't fixed problem on my Windows TP b9888

**Comment by Festum** [comment]
Fixed in my TP 9888. Thank you @Zolli.
