### ISSUE TITLE
How do I change the color of the split screen divider ( border ) line.

### ISSUE THREAD

**Issue by NicolaSansom** [cmderdev/cmder#1202]
I cannot seem to find this in the settings any ideas?

![screenshot](https://cloud.githubusercontent.com/assets/17367104/21262156/a1a9711a-c387-11e6-95ee-ec433b4faccb.jpg)

Thanks Nicola

**Comment by Jackbennett** [comment]
Sorry I can't see a way, ask over in https://github.com/Maximus5/ConEmu that's the program doing the console UI. If you find out please do comment back.

**Comment by airstrike** [comment]
For future readers looking into this, this can be changed by altering the RGB for the background color of the status bar, located under Features > Status bar in the settings menu, even if your status bar is hidden
