### ISSUE TITLE
keyboard shortcuts

### ISSUE THREAD

**Issue by kcris** [cmderdev/cmder#1203]
Hello,

I assigned Ctrl-Shift-9 for Split right and it works
I assigned Ctrl-Shift-0 for Split bottom and it does not work

no other shortcuts are customized, no overlapping
I am using version 161206 stable
Thanks

**Comment by copdips** [comment]
@kcris  could you explain where and how you assigned these shortcuts ? Thx.

**Comment by copdips** [comment]
I got it
