### ISSUE TITLE
Launching cmder from explorer context menu

### ISSUE THREAD

**Issue by Ribice** [cmderdev/cmder#1204]
Is there a way to launch Cmder instead of CMD when using following shortcut:

Shift + Right click -> Open command window here

Love the tool.

**Comment by mrRosset** [comment]
Wiki :[Open Cmder Here" in context menu](https://github.com/cmderdev/cmder/wiki/%5BWindows%5D-%22Open-Cmder-Here%22-in-context-menu)

**Comment by Ribice** [comment]
Thanks!

Although on Windows 8.1, after clicking on 'Open Cmder here' I get the following warning:

![image](https://cloud.githubusercontent.com/assets/5403700/21284982/0fc25b0e-c42c-11e6-8ef8-544559be0b0b.png)

Only Windows Defender installed (no other AV), permissions seem to be fine.

**Comment by mrRosset** [comment]
Can you verify that you put the correct path in n the environment variable. Also try restarting your computer.

**Comment by Ribice** [comment]
Restart solved it. Perhaps you can add it to Wiki?

**Comment by mrRosset** [comment]
I'm just a user of cmder,  I don't know the rules for changing the wiki. But it's also a pretty standard thing on both Linux and windows that any modifications to an env variable require to restart the processes that use it. (Restarting the OS being the simplest option)

**Comment by Stanzilla** [comment]
Will at to the wiki, thank you!

**Comment by yairEO** [comment]
I made it open but the path is wrong. it is not starting the shell in the path where it was opened :/
