### ISSUE TITLE
How to make CMDER my default console?

### ISSUE THREAD

**Issue by Droyk** [cmderdev/cmder#1206]
hey guys I want to make cmder my default console but there is no setting in cmder that can let me do it.
the only setting I found in cmder is make CONEMU default but I don't want to do that I want to make cmder my default application 

What I mean to say is when I rightclick on start and hit cmd it should open cmder instead of cmd or conemu
everytime I search for cmd in run it should open cmder

**Is there is any way I can do it**
thanx

**Comment by ShadowRylander** [comment]
Since Cmder is simply a wrapper, and your version of ConEmu is most likely wrapped in it, when you set ConEmu as your default console, it will call up Cmder instead. It worked in my instance. I think.

**Comment by Jackbennett** [comment]
Check https://github.com/cmderdev/cmder/issues/307#issuecomment-158373090 and the next comment on how to do that, it's a bit tricky.

If you just put the folder the cmder.exe is in on your users' path you can simply do `win + r` and type `cmder` to run it. there's also `cmder.exe /register user` to put it in the right-click menu on folders.
