### ISSUE TITLE
Trouble using StackExchange's blackbox with cmder

### ISSUE THREAD

**Issue by jrappen** [cmderdev/cmder#1209]
How do I use [`blackbox`](https://github.com/StackExchange/blackbox) with [cmder](https://github.com/cmderdev/cmder) (consule emulator for Windows)?

---

### What I tried...

* Copied files from this repo to `%CMDER_ROOT%/vendor/blackbox` subfolder.
* Added line `set PATH=%CMDER_ROOT%\vendor\blackbox\bin;%PATH%` to file `%CMDER_ROOT%/config/user-profile.cmd`

#### `cmd`

```text
λ sh blackbox_initialize
%CMDER_ROOT%/vendor/blackbox/bin/blackbox_initialize: line 12: blackbox_initialize/_blackbox_common.sh: No such file or directory
```

#### `bash`

```text
$ blackbox_initialize
bash: blackbox_initialize: command not found
```

#### `mintty`

```text
$ blackbox_initialize
bash: blackbox_initialize: command not found
```

**Comment by jrappen** [comment]
StackExchange/blackbox#176

**Comment by jrappen** [comment]
@Maximus5 Do you have a solution for this issue?

**Comment by Maximus5** [comment]
Why do you ask **here** how to install blackbox, if you know [the proper tracker](https://github.com/StackExchange/blackbox/issues)?

**Comment by Maximus5** [comment]
Your blackbox doesn't work even in mintty. Which is "standard" for cygwin/msys. You know the [proper issue tracker](https://github.com/StackExchange/blackbox/issues/176).

Suggest to close this as it's not related to cmder or ConEmu.
