### ISSUE TITLE
Very slow; clink_x64.exe seems to be to blame

### ISSUE THREAD

**Issue by Jenuma** [cmderdev/cmder#1211]
Came into work today to find my commands were taking ages to execute, even those as simple as `git status`. Restarted my PC to no avail. Downloaded the latest release and tried a fresh install to no avail. Nothing has changed on this computer.

It takes anywhere from 30 seconds to 3 minutes to execute any git task. Native commands like `dir` seem to work instantly, but it still takes about 60 seconds for the prompt to show up again to enter a new command.

I found a few tickets with similar issues: #188 and #763. Neither really seem to have answers other than a suggestion to have `get_git_dir()` in clink.lua return false and comment the rest of the code out. That didn't work for me. #447 suggests the problem is with git itself, but this is not the case either as the same command in any other shell runs instantly and the prompt for a new command comes back up instantly.

My computer is running 64-bit Windows 10 Enterprise, has an i7 @ 3.40 GHz and 16 GB of RAM. No other programs are behaving slowly.

**Comment by Jackbennett** [comment]
As a workaround, if you use the powershell task it doesn't need clink so it should remain speedy for you. If you don't use arguments to the usual windows commands(dir, cd, etc...) you shouldn't notice much different.

**Comment by JSamir** [comment]
I just discovered cmder today and had this issue right away...

**Comment by JSamir** [comment]
As of today i tried cmder again, downloaded latest version, but got the same problem.
Cmder_mini:
- Very slow start ( ~30 seconds)

Cmder_full:
- Very slow start ( ~30 seconds)
- Any unix command takes very long to execute (~30 seconds), even ls, doesnt matter in which directory i am

All Windows commands are executed immediately on either version.

**Comment by MarcusCaepio** [comment]
can confirm this: happened suddenly.....
[(https://github.com/cmderdev/cmder/issues/1426)]

**Comment by JSamir** [comment]
So i tried the latest dev build and the problem still persists. It really ruins the experience...

Any ideas how we can troubleshoot this issue?

**Comment by dmbarreiro** [comment]
I am suffering from this issue on version 171025. I've installed the same version on other computers with the same operating system (Windows 7) and there I didn't see the problem. @Jackbennett workaround helps.

**Comment by bigeast** [comment]
Same problem here, any command in a git repo directory will block the command prompt for about 30 second or so.

Drive me crazy. I found the similar issue https://github.com/cmderdev/cmder/issues/763 two years ago and now it‘s still a problem, I don't know what to say.

git version 2.14.1.windows.1
windows 10.0.16299.0
ConEmu 171025[64] Alpha

I HATE this shit.

**Comment by JSamir** [comment]
This really ruins the otherwise very nice cmder experience for me... also tried it on my colleagues laptop, they had the issue too. Note that we all use our company laptops, so we got similar setup.

**Comment by nhova** [comment]
Seems like it may be IPV6 related.

If possible try to disable IPV6 in your network settings.

**Comment by JSamir** [comment]
@nhova Thanks, but that did not help in my case.

Starting cmder still takes around 30 seconds. I dont use cmder for git so I can't comment on that, although after its started the windows native commands are executed immediately, but linux commands like ls take around 1 second to execute.

**Comment by SaltyCatFish** [comment]
Same issue as reported by others.  Over 30 seconds to start, very slow to operate.  What info can we submit?

**Comment by mark-walle** [comment]
I'm having this too. Seems to be open a new tab or window and sometimes when I terminate a running process. The tab at the bottom of the window reads "clink_x64.exe" hangs for roughly 20 or 30 seconds, then finally the expected lambda prompt appears and it works fine. using cmd::Cmder, haven't tried other tasks,, cmndermini 1.3.5 was choco installed on Windows 10 ee v1709 b16299.192.

**Comment by Jebble** [comment]
@Stanzilla can you please explain why the issue is marked closed as this issue is still active?
None of the advices here worked.

**Comment by Stanzilla** [comment]
Because it's probably an upstream issue in clink

**Comment by Jebble** [comment]
Interesting. I never had this issue on the previous version I was running (Don't know what version number this was, but it was from sept 2017 - august 2018). It's only now that my laptop was reinstalled that CMDer became really slow.

**Comment by mmenschig** [comment]
This is still an issue in March 2020 running the latest version. Can we get an update on this?

**Comment by JiveyGuy** [comment]
Still ongoing, windows 10, 2024

**Comment by daxgames** [comment]
Usually slowness is a side effect of something on the users own machine.  Overzealous/misbehaving Anti-Virus or DLP software.

That being said we have worked to mitigate these issues by optimizing startup times as much as possible in un-released versions.

**Comment by chrisant996** [comment]
> Still ongoing, windows 10, 2024

@JiveyGuy This issue 1211 is about a specific kind of slowness, and is definitely not related to the slowness you're experiencing (for one thing, Clink has been literally almost completely rewritten since this issue was first opened).

Can you describe specifically what is the nature of the slowness?
Specifically what steps do you do?
Specifically when does slowness occur?
Specifically how long is the slowness?

If you believe you're tracked down that the slowness coming specifically from clink_x64.exe, can you share the troubleshooting that led to that conclusion?  As the maintainer of Clink, I'm willing to investigate any issues in Clink, but there isn't any information available yet to enable me to investigate anything.

I wonder if you might be experiencing general slowness, as in #2816, and not anything related to Clink?
