### ISSUE TITLE
Problems when working with Git

### ISSUE THREAD

**Issue by thefunnyfunyan** [cmderdev/cmder#1212]
When working with git, if I perform a `git merge` and there are merge conflicts, git creates an `index.lock` file. This is preventing me from abort the merge or even delete the repository. If I close cmder, and open up cmd.exe no `index.lock` file is create and i am able to abort the merge.

**Comment by Stanzilla** [comment]
Are you sure you are on the latest version? Because we actively prevent that https://github.com/cmderdev/cmder/blob/master/vendor/clink.lua#L228

**Comment by thefunnyfunyan** [comment]
Yes I do have the most recent version.

**Comment by glucas** [comment]
See related https://github.com/cmderdev/cmder/issues/1060.
