### ISSUE TITLE
'findstr' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by emmanuelnk** [cmderdev/cmder#1213]
On version 161206 and get the error 'findstr' is not recognized as an internal or external command when the command console opens up.
I fixed it by getting findstr.exe from C:\Windows\System32 and copying it to cmder\bin. I'm not sure this is a good fix for this issue though so I'm reporting it.

**Comment by Jackbennett** [comment]
`echo %path%` will list all the folders (separated by semicolon ';') in the order it will search for `<program>.exe` so if you look through those can you find the command where it's supposed to be?

use this from the powershell task if you want; `$env:path.split(';') | gci -Filter 'findstr.exe'`

It must be in that folder in the path, it will not look inside subfolders.

**Comment by glucas** [comment]
If you don't have C:\Wndows\System32 (and the other windows defaults) on your PATH then you will probably have lots of issues. By default cmder does not remove these entries, any chance you are modifying your PATH variable somewhere in your cmder configuration? You can try starting a cmd.exe shell directly and seeing what the PATH is there (`set PATH`), or check the Windows environment variables via the system properties dialog.

**Comment by Jackbennett** [comment]
I suspect you've used assign `=` where it should be append `+=` when adding something to your path. Check your profile for a line like that with `$env:Path`

**Comment by ankitakalgut** [comment]
Solution :- Set the Path to C:\Windows\System32  and restart Anypoint Studio.

**Comment by daxgames** [comment]
@ankitakalgut I edited your response to be more appropriate.  Simply setting the path as you originally recommended woumd break a lot.  Also what is Anypoint Studio and whay does it have to do with this issue?

**Comment by Jackbennett** [comment]
Profile full of single commit repos? Looks like an astroturfing bot. I've edited the comment to remove the product placement and reported.

**Comment by GOKULPRAVI** [comment]
C:\Users\Gokul P\Desktop\tekhno\logstash-7.5.0\bin>logstash
'findstr' is not recognized as an internal or external command,
operable program or batch file.
Error: Could not find or load main class P\Desktop\tekhno\logstash-7.5.0\logstash-core\lib\jars\animal-sniffer-annotations-1.14.jar;C:\Users\Gokul

**Comment by GOKULPRAVI** [comment]
plse help me

**Comment by daxgames** [comment]
@GOKULPRAVI Cmder Version?

**Comment by daxgames** [comment]
@GOKULPRAVI out put of `set path`?

**Comment by Vaderv** [comment]
still not working. Same error.

**Comment by Jackbennett** [comment]
What's in your PATH, what cmder version, what's `where findstr` produce in cmder, what about in just cmd.exe and another profile of single commit repos, are you a robot? If none of the above works out can you make a new issue, this one has no content.
