### ISSUE TITLE
Group and broadcast feature

### ISSUE THREAD

**Issue by noldona** [cmderdev/cmder#1215]
I use [terminator](https://gnometerminator.blogspot.com/p/introduction.html) for work all the time and love the ability to group the consoles together and broadcast the commands to all the consoles in the group. It makes it easier to run the same commands on different nodes all at once. Would it be possible to have this feature added to cmder?

**Comment by Stanzilla** [comment]
That's a feature request for ConEmu: https://github.com/Maximus5/ConEmu
