### ISSUE TITLE
Change Shell Via Command

### ISSUE THREAD

**Issue by ShadowRylander** [cmderdev/cmder#1216]
Hello!
Just wondering: Is there any way or command to change the current shell from, say, `CMD` to `Powershell`, or `CMD` to `Cygwin Bash`, via the primary terminal itself? Maybe a
```
change shell {bash::cygwin}
```
or
```
change shell {bash::git}
```
for example?
Thanks!
P.S. I apologize if this has been addressed before already; I tried my best to find an issue similar to it, both here and outside, but was unable to find it. If the question already exists somewhere else, a link to it would be greatly appreciated.

**Comment by Jackbennett** [comment]
No you'd have to start a new task, there's keyboard hot-keys to launch those. There's also some conemu way to do that but typing it won't be faster than the hot-keys.

You can quickly hop into those programs if you want just by running them but you won't get all the initialization stuff cmder does that way.
