### ISSUE TITLE
Change directory (dir at another local disk)

### ISSUE THREAD

**Issue by isnullxbh** [cmderdev/cmder#1220]
It is possible to change local disk with 'cd' command without usage '/d' flag?
It's so annoying to write /d everytime.

**Comment by daxgames** [comment]
This is not related to cmder.  This is Microsoft cmd.exe syntax.

**Comment by daxgames** [comment]
You could do an alias.  Something like:

```
alias cdd=cd /d $*
```

Then:

```
cdd e:\test
```
Would change to 'e:\test'

Do not do the below because it could bread some stuff:

```
alias cd=cd /d $*
```

**Comment by isnullxbh** [comment]
Thank you!
