### ISSUE TITLE
Login with ssh on start

### ISSUE THREAD

**Issue by romainhe** [cmderdev/cmder#1221]
Hi, I try to create a "task" to automaticaly login the new tab through ssh server

I try something like 

`
cmd /k "%ConEmuDir%\..\init.bat" -new_console:t:
%ConEmuDir%\..\init.bat -c "ssh"
`

Any idea ? 

Thx a lot !

**Comment by denis-adobe** [comment]
i did it like this 
`cmd.exe /k "%ConEmuBaseDir%\CmdInit.cmd" && ssh user@ip`
in in the commands textarea

**Comment by romainhe** [comment]
Do you have special parameters ? It doesn't work for me :/

"'ssh' not reconized command"

![image](https://cloud.githubusercontent.com/assets/1837829/21924506/cfdd4a22-d979-11e6-9ceb-c8d5fb273d20.png)

**Comment by ladislavsulc** [comment]
@romainhe do you have ssh installed? Try chocolatey https://chocolatey.org/packages/openssh. If you type ssh on your cmd, you should see the help.

**Comment by measdot** [comment]
```""%ConEmuDir%\..\init.bat" && ssh vagrant@127.0.0.1 -p 2222"```
works for me. 

I am using the same feature in PhpStorm IDE to open cmder and ssh into a vm every time I open embedded terminal. For that I had to go to settings>tools>terminal and set application setings Shell path to "cmd" /k "C:\cmder\vendor\init.bat && ssh vagrant@127.0.0.1 -p 2222" .

Hope this helps to readers.
![cmder_default_ssh](https://user-images.githubusercontent.com/5073326/41643916-46725630-748a-11e8-8862-4e002489f522.png)
