### ISSUE TITLE
Features from other terminals

### ISSUE THREAD

**Issue by cmrdt** [cmderdev/cmder#1223]
https://github.com/robbyrussell/oh-my-zsh/#selecting-a-theme
https://fishshell.com/
https://github.com/vshatskyi/black-screen
  ? https://github.com/powerline/powerline

e.g. fish's syntax highlighting 
https://github.com/oh-my-fish/oh-my-fish/blob/master/docs/Themes.md

**Comment by Jackbennett** [comment]
You could try to add in another colour scheme to conemu in "settings > features > colours" but I've no idea how you work out what colour goes where.

As for the others you'd have to be more specific than linking to entire projects. Of which don't even support windows. You could have a look at using [powerline](https://github.com/Jaykul/PowerLine) as your linked one has no windows instructions and requires python, another dependency we'll avoid adding if possible.
