### ISSUE TITLE
start cmder with given directory when single instance mode should fix

### ISSUE THREAD

**Issue by the1900** [cmderdev/cmder#1224]
My Enviroment
OS: Winodws 10 x64
cmder version: 1.3.2

When I disable single instance mode then `/path/cmder.exe /START <path>` works perfect with always show new windows. But If I use the single mode then `/path/cmder.exe /START <path>` doesn't show windows or tab and If I use `/path/cmder.exe /SINGLE <path>` then It makes new tab on first path not the current path. _cmder here_ function only works when It start at first If Single mode has been on.

It would be pleasure to fix this situation.

**Comment by Jackbennett** [comment]
Sorry this appears to be an ongoing bit of odd behaviour, latest work seems to be #420
