### ISSUE TITLE
How to uninstall cmder or clear the related things in regedit?

### ISSUE THREAD

**Issue by GabrielDrapor** [cmderdev/cmder#1226]
Well, I download it, install it, register it in regedit.msc, and now I want to undo it and move the exe to another place, restall it again. Should I clear regedit.msc myself or is there anyway to solve it?

**Comment by Jackbennett** [comment]
You can see options with `cmder.exe /?` but if you registered it with `cmder.exe /REGISTER ALL` then you want `cmder.exe /UNREGISTER ALL` to then re-register.

If you've done it by hand then I'm not certain it will remove the correct settings.

**Comment by overheat** [comment]
`cmder.exe /UNREGISTER ALL` is not work properly under version 1.3.5. you need to edit Reg and remove cmder items manually.

**Comment by oshihirii** [comment]
> cmder.exe /UNREGISTER ALL is not work properly under version 1.3.5. you need to edit Reg and remove cmder items manually.

How can I learn how to do this?  

How to edit Reg and remove items manually (and what items)?

**Comment by daxgames** [comment]
Use a nightly build it works from unreleased versions.

**Comment by oshihirii** [comment]
How do I find and install nightly build on Windows?  

Is it the latest one here?  

https://github.com/cmderdev/cmder/releases

    v1.3.6-pre1.zip

Thank you.

**Comment by daxgames** [comment]
There is a link to nightly builds at the bottom if the main README.md file. 
 https://ci.appveyor.com/project/MartiUK/cmder/branch/master/artifacts
