### ISSUE TITLE
Aliases no longer working

### ISSUE THREAD

**Issue by tkrause** [cmderdev/cmder#1227]
Seems that with one of the newer updates Aliases are no longer working as expected. See output below

C:\Users\TJ
λ alias
Use /? for help

~=cd /d C:\Users\TJ
clear=cls
clink="C:\PROGRA~1\cmder\vendor\clink/clink_x64.exe" --cfgdir "C:\PROGRA~1\cmder\config" $*
cmderr=cd /d "%CMDER_ROOT%"
dev=cd \Users\TJ\Development
e.=explorer .
gl=git log --oneline --all --graph --decorate  $*
history=cat %CMDER_ROOT%\config\.history
hosts=elevate notepad C:\Windows\System32\Drivers\etc\hosts
l=ls --show-control-chars --color $*
ll=ls -la --show-control-chars --color $*
ls=ls --show-control-chars --color $*
pwd=cd
sudo=elevate $*
unalias=alias /d $1
vi=vim $*

C:\Users\TJ
λ dev
'dev' is not recognized as an internal or external command,
operable program or batch file.

**Comment by daxgames** [comment]
Do you have any errors when starting a cmder session?

**Comment by AlexMasterov** [comment]
Same problem after upgrading Windows 10 to build version 15002-15007 (pre release).

There's still a lot of things stopped working normally;
for example, now you cannot close a running process, `<C-c>` does not work. Very fun.

**Comment by tkrause** [comment]
No errors with starting cmder. As Alex mentioned, on Insider release 15014 many things no longer work. Aliases and Ctrl + C being the two major ones.

**Comment by KayLeung** [comment]
I could confirm this is Windows 10 Insider Build problem as well. Simply execute `doskey ` in command line also doesn't work

**Comment by mattcfox** [comment]
This is still broken on Insider build 15019.

**Comment by Stanzilla** [comment]
Not our problem, sorry. Go to the ConEmu or clink bugtracker, they have a few issues open with Insider builds, https://github.com/mridgers/clink/issues/431 for ex

**Comment by thenitai** [comment]
For the afterworld, also broken in 15031 build. Though, doskey executes and "some" of my aliases still work. Very weird.

**Comment by Koi7** [comment]
Fuck Win 10 updates
