### ISSUE TITLE
How to close the cmder by command ? 

### ISSUE THREAD

**Issue by woshichuanqilz** [cmderdev/cmder#1228]
I use this bat file(named startCmder) to make cmder to exec a cmd. 

I want the new cmder window closed when the command has been execuated, so I add `&& exit` at the end of the command. But the cmder window won't closed, instead of show this: 

![0115173454.png](http://7xpvdr.com1.z0.glb.clouddn.com/0115173454.png)

but the window never closed(instead of what it shows `it will close less than 10s`)

So how to close this windows after the command exec? 

```
@echo off
set CMDER_ROOT=%~dp0
start %CMDER_ROOT%\vendor\conemu-maximus5\ConEmu.exe /icon "%CMDER_ROOT%\cmder.exe" /title Cmder /loadcfgfile "%CMDER_ROOT%\vendor\conemu-maximus5\ConEmu.xml" /cmd cmd /c "%CMDER_ROOT%\vendor\init.bat cd %CD% && %~1 && exit"
```

**Comment by Jackbennett** [comment]
This script literally just seems to open then close cmder immediately, ConEmu which hosts the cmder session is warning you of that. If you just want to run a single command and close again then just call the command, you don't need an interactive session like cmder to what amounts to a shortcut.

The screenshot posted warns you;

> process **was** alive less than 10 seconds

Not that it will close in 10 seconds.
