### ISSUE TITLE
Is there any way to use mouse in vim ?

### ISSUE THREAD

**Issue by sapeyes** [cmderdev/cmder#1229]
Is there any way to activate mouse in vim in cmder terminal?  
(I am using gvim80 64bit)

Even though I wrote ' set mouse = a' in _vimrc, vim in cmder doesn't accept mouse click to move cursor(prompt) in vim editor. (+ mouse scroll)

**Comment by sapeyes** [comment]
I found Mouse setting, but that is not working well..

Settings 
 - Mouse
 -- [O] change prompt (cmd, powershell) text cursor position with Left Click.

Above setting helps to move cursor in Vim but after split windows, Vim just stopped to accept any input (keyboard, mouse). 

There are more options in Settings-Key & Macro-Mouse. But these options are not compatible with vim.

**Comment by schlichtanders** [comment]
why was this closed? is there a solution to this?

**Comment by Stanzilla** [comment]
Upstream issue

**Comment by schlichtanders** [comment]
thanks

**Comment by schlichtanders** [comment]
so I updated conemu to latest dev version "ConEmu 171205 Alpha"
and further adapted ``.vimrc`` with
```
set term=xterm
set mouse=a
```
and checked "Send mouse events to console" in "ConEmu Settings / Keys & macro / Mouse"

however while mouse click events seem to work, neither of the following works:
- mouse wheel to scroll vim
- mouse drag to enter visual select
- mouse drag to drag split screen borders in vim
- standard arrow keys are no longer recognized

any help is highly appreciated

**Comment by schlichtanders** [comment]
found this duplicate issue #1185, which indeed is still open

**Comment by schlichtanders** [comment]
The duplicate was just closed.
I again made a clean cmder install v1.3.4 (last release)

vim does not work by setting the above configs

please, if this is already solved as suggested by @Stanzilla closing all these issues, provide default vim configurations which work with full mouse support.

**Comment by ryankhart** [comment]
Is there any way to resolve this issue then? If not, what "upstream issue" is causing the bug?

I'm really liking this console emulator. It's one of the best I've tried on Windows 10, and mouse support is the only missing feature I'm looking for (or rather, bug, because it was clearly an intended feature in the settings).

**Comment by jdhao** [comment]
I am using Neovim inside Cmder. The above settings by @ryankhart  does not work. After setting the 'Mouse' options in Key&Macro, I still can not change windows with left click.

**Comment by daxgames** [comment]
@jdhao there are probably also settings required in your vim config file to allow this.  If this works in a standard cmd.exe prompt the I suggest asking the question in the conemu forum.  Conemu is the cmder terminal app and is not maintained by us.

**Comment by sapeyes** [comment]
I found a very curios thing, a tricky temporal solution. After reading a file in vim, just try 'ctrl+z' to command console and return by typing 'exit' to previous file buffer in vim. Then.. mouse scrolling is perfectly working unless new file is buffered. 

1) Load a file
2) Ctrl + Z
3) exit
4) Now can move the prompt with mouse scroll temporarily.

I am using console vim of Gvim 8.1.

**Comment by kuna** [comment]
Passing by. I solve this problem by unchecking 'Quickedit mode' of ConEmu properties, so it may not be problem of cmder.
you may check this out: https://imgur.com/a/HQ4dA
