### ISSUE TITLE
how to open specail directory? in sublime Terminal plugin?

### ISSUE THREAD

**Issue by atian25** [cmderdev/cmder#123]
I'm using sublime text 3 with `Terminal`, 

```
{
    // The command to execute for the terminal, leave blank for the OS default
    // On OS X the terminal can be set to iTerm.sh to execute iTerm
    //"terminal": "",
    "terminal": "D:\\Tool\\cmder\\Cmder.exe",

    // A list of default parameters to pass to the terminal, this can be
    // overridden by passing the "parameters" key with a list value to the args
    // dict when calling the "open_terminal" or "open_terminal_project_folder"
    // commands
    "parameters": []
}
```

but, it always open `c:\Users\TZ`

**Comment by vishnuaniyan** [comment]
Thanks @pwiesner , It worked for me. 
The best part is that we can also use Ctrl+Shift+t also :)

**Comment by babhishek21** [comment]
Thank you so much. I was nearing my wit's end.

**Comment by xnathanh** [comment]
@pwiesner  how to set "parameters": ["/START","xxxxx"] in mac?

**Comment by StephenKingg** [comment]
@xnathanh https://packagecontrol.io/packages/Terminal

iTerm on OS X
{
  "terminal": "iTerm.sh"
}

iTerm on OS X with tabs
{
  "terminal": "iTerm.sh",
  "parameters": ["--open-in-tab"]
}
