### ISSUE TITLE
Sth wrong with show Chinese char how to fix it? 

### ISSUE THREAD

**Issue by woshichuanqilz** [cmderdev/cmder#1230]
The chn char in the `cmder` shows inappropriatly how to fix it ? 
![0116093135](https://cloud.githubusercontent.com/assets/11295355/21968520/7005f4b0-dbd0-11e6-8298-5b67be471c9c.png)

**Comment by Jackbennett** [comment]
Have a look at https://github.com/cmderdev/cmder/issues/985#issuecomment-227387888
