### ISSUE TITLE
.bashrc loaded twice with the bash task?

### ISSUE THREAD

**Issue by YAmikep** [cmderdev/cmder#1231]
I have a `.bashrc` file at `C:\Users\Michael`.
When I use the `bash` task, the `.bashrc` file is loaded twice (I can tell based on the output).

Task definition:
`cmd /c "%ConEmuDir%\..\git-for-windows\bin\bash --login -i" -new_console:d:%USERPROFILE%`

Thanks

**Comment by glucas** [comment]
Any chance you have a .bash_profile as well? Looks like git bash generates a .bash_profile that explicitly sources ~/.bashrc if found.
