### ISSUE TITLE
CTRL + C not working to stop current process

### ISSUE THREAD

**Issue by jojobyte** [cmderdev/cmder#1234]
So, I'm not sure what is causing this new issue for me, especially as I haven't updated Cmder in a while, it might be Cmder + Windows 10 Update issue, or at least that is the only thing I can think of.

The gist is, `CTRL+C` no longer works to close the running program. Specifically Node.js servers won't close. Tested `npm start` and `node app.js` and neither will recognize CTRL+C, however the `node` REPL will quit properly.

I just updated (as in less than 3 hours ago) Windows 10 to Build 15007.rs_prerelease.170107-1846, however this was also not working on whatever version it was before that.

When opening CMD or PowerShell and running the same `npm start` or `node app.js` the keyboard shortcut works fine and correctly quits the program.

Any ideas?

**Comment by Stanzilla** [comment]
are you on some windows 10 insider build?

**Comment by jojobyte** [comment]
Yup, I'm running a windows 10 insider build.

**Comment by Stanzilla** [comment]
They broke that recently, you will have to wait for them to fix it.

**Comment by DamageLimiter** [comment]
I am using Windows 10 but not on an insider build. Still though, CTRL+C isn't working for me either. Is there an update required? Iam actually running on Version 161206

**Comment by dadvir** [comment]
It's probably how you start the cmd. Try running as admin or starting the cmd manually and not using a 3rd party tool (like VS Code).

**Comment by BrainCrumbz** [comment]
#1258 seems related, actually this could be a dupe
