### ISSUE TITLE
Drag and drop folders/files into the console window from windows explorer

### ISSUE THREAD

**Issue by jaskiratr** [cmderdev/cmder#1235]
I've been using cmder on Windows 10 Home edition for a while now. Love it.
Though, I am not able drag and drop folders/files into the console window, to generate a path. However, I do remember some of the previous releases allowed that. ConEmu it allows this feature. Not sure if I need to mess with any specific settings.

Any suggestions are welcome.
Thanks!

**Comment by Jackbennett** [comment]
I've just tried this in 1.3.2 and it works, could you try this in both the cmd and powershell tasks just to help rule anything out, those two things work slightly differently. And if it doesn't work in both it's possibly a conemu setting.

**Comment by jaskiratr** [comment]
Thanks @Jackbennett 
Just figured it out. I had to right-click on Cmder.exe -> Properties -> Check 'Unblock' (If it is there)
Windows need a proper UX around blocking/unblocking content.

**Comment by sk29110** [comment]
I started the cmder with run as administrator it will block me to drag&drop to cmder.

version v1.3,4

**Comment by Jackbennett** [comment]
Even notepad will block that, I think by design since the explorer process you're dragging the file from doesn't have the administrator token on your user account it can't talk to the cmder instance that does have the administrator token to tell it to go open a file.

**Comment by Radhika-Lele** [comment]
I am using Cmder on Windows 11. When I did right click on cmder.exe file and choose run as administrator, Then it doesn't allow me to drag and drop file. On contrary when I double clicked on (instead of right click) Cmder.exe and open terminal it allows me drag and drop files. How can I fix this?

**Comment by daxgames** [comment]
@Radhika-Lele you can't it is not Cmder or ConEmu it is Windows blocking this.
