### ISSUE TITLE
Shift + Up doesn't function

### ISSUE THREAD

**Issue by rparolin** [cmderdev/cmder#124]
Stock installation from both the 7z and Zip files 'Shift + Up' (navigate up a directory) is either disabled or doesn't function.

**Comment by Twelve-60** [comment]
@rparolin That also worked for me! Thanks
@bliker Any reason this hasn't been fixed?

**Comment by Blasz** [comment]
Bump

**Comment by babhishek21** [comment]
Given that this feature is "well advertised" everywhere (on the companion site, README), this should probably be on high priority. @MartiUK

**Comment by willifordjn** [comment]
FYI. The[ http://cmder.net/]( http://cmder.net/) page still shows **Shift + Up** in the Keyboard Shortcuts section.
