### ISSUE TITLE
Slow startup (noce.exe)

### ISSUE THREAD

**Issue by N-Molham** [cmderdev/cmder#1240]
Hello Guys,

I am having a problem when starting new `cmd` tab .... When starting one, it takes 3-5 seconds to load ... I noticed it while waiting the tab title is `node.exe` > ![cmder-node-slow-startup](https://cloud.githubusercontent.com/assets/3770036/22397103/a8a1ff66-e572-11e6-87ca-7943339c71bb.png)

I am using `window 10 home x64`, `nodejs v4.4.7`, last version of `cmder`

**Comment by stewartadam** [comment]
Are you using a domain-joined machine? If so, that's why - edit your nsswitch.conf e.g. https://github.com/cmderdev/cmder/issues/993#issuecomment-257873392

**Comment by fztfztfztfzt** [comment]
@N-Molham 
Hi，I have the same problem with you. After I install the Node.js, cmder start slowly. I have tried to edit my nsswitch.conf, but it doesn't work. Does it work for you?

**Comment by N-Molham** [comment]
@stewartadam @fztfztfztfzt I tried editing the `nsswitch.conf` file as in the [#993 (comment)](https://github.com/cmderdev/cmder/issues/993#issuecomment-257873392) with the same problem ... I am not using a domain-joined machine ... any other idea ?!

Note: I am using `nodejs v7.8.0` now

**Comment by reecebradley** [comment]
Same here.

**Comment by fztfztfztfzt** [comment]
@N-Molham @reecebradley 
hi, I edited my `Enhance Path` in `init.bat` from `@set PATH=%CMDER_ROOT%\bin;%CMDER_ROOT%;%PATH%` to `@set PATH=%CMDER_ROOT%\bin;%CMDER_ROOT%;%PATH:C:\Program Files\nodejs\;=%` which means that I remove path of nodejs temporary when I start the `cmder`.
Then `cmder` can start normally. And at the same time, as I remove the nodejs' path, I cannot use `npm` in `cmder`. I can only use `npm` in `cmd` or `powershell`.
I hope it can help you.

**Comment by thomthom** [comment]
Tweaking `nsswitch.conf` did not affect the performance lag for me.

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)
