### ISSUE TITLE
Style Active Tab

### ISSUE THREAD

**Issue by BananaHemic** [cmderdev/cmder#1241]
Hey,

I use, and love, Cmder on a monitor with unusual color, as a result it's difficult to determine which tab is currently active because the difference between active and non-active tabs is hard to see.

Is it possible to change the styling for the current active tab? If it's not possible from the settings window (I have looked there) where in the code would be a good place to change that?

**Comment by catamphetamine** [comment]
@Stanzilla Why did you silently close this issue?
The current tab colors are really inconvenient and there's no way one can differentiate between an active tab and all others.

**Comment by catamphetamine** [comment]
So, the real answer is https://github.com/Maximus5/ConEmu/issues/1603
