### ISSUE TITLE
Cygwin Warning "Couldn't compute FAST_CWD pointer" on latest Windows 10 build

### ISSUE THREAD

**Issue by chriswatt** [cmderdev/cmder#1242]
![image](https://cloud.githubusercontent.com/assets/488912/22419474/942dbe9e-e6d5-11e6-93f9-52e5c13343ba.png)

Possibly related to this - https://cygwin.com/git/gitweb.cgi?p=newlib-cygwin.git;a=commitdiff;h=e5cadbfdcdd8b06932a9503b3c72511b68f03a60

**Comment by edukinara** [comment]
Same issue here

**Comment by DRSDavidSoft** [comment]
@anburocky3 Please post a screenshot to see if this issue can be solved
