### ISSUE TITLE
Something (like git submodule) cannot function properly without cygwin

### ISSUE THREAD

**Issue by xdujiang** [cmderdev/cmder#1244]
I tried to pull some project today, but after I type "git submodule init", some errors come, saying that wrong version of cygwin is used, while I have not installed cygwin.
Is it a bug? Or may I have to install cygwin to make it run properly?
Thanks

Cmder: 1.3.2
System: Win10 10240 x64

$ git submodule
      0 [main] sh (19628) D:\program\cmder\vendor\git-for-windows\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0xF96408/0xE46408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
      0 [main] sh 3032 fork: child -1 - forked process 19628 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
D:\program\cmder\vendor\git-for-windows\mingw32/libexec/git-core\git-submodule: fork: retry: No child processes
      2 [main] sh (4788) D:\program\cmder\vendor\git-for-windows\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0xF96408/0xF36408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
1080042 [main] sh 3032 fork: child -1 - forked process 4788 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
D:\program\cmder\vendor\git-for-windows\mingw32/libexec/git-core\git-submodule: fork: retry: No child processes
      1 [main] sh (2464) D:\program\cmder\vendor\git-for-windows\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0xF96408/0xE96408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
3169469 [main] sh 3032 fork: child -1 - forked process 2464 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
D:\program\cmder\vendor\git-for-windows\mingw32/libexec/git-core\git-submodule: fork: retry: No child processes
      2 [main] sh (18468) D:\program\cmder\vendor\git-for-windows\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0xF96408/0xE56408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
7229485 [main] sh 3032 fork: child -1 - forked process 18468 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
D:\program\cmder\vendor\git-for-windows\mingw32/libexec/git-core\git-submodule: fork: retry: No child processes
      0 [main] sh (5604) D:\program\cmder\vendor\git-for-windows\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0xF96408/0xED6408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
15304373 [main] sh 3032 fork: child -1 - forked process 5604 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
D:\program\cmder\vendor\git-for-windows\mingw32/libexec/git-core\git-submodule: fork: Resource temporarily unavailable

**Comment by Jackbennett** [comment]
Did you copy cmder 1.3.2 into an older install of cmder? I'm wondering if maybe the mini version has been put over a full version, then it wouldn't have the newer git-for-windows which has something to do with cygwin. 

If you have git installed normally then remove cmder and use our mini version. Otherwise check you extracted the full version to that `d:\program` path.

**Comment by xdujiang** [comment]
@Jackbennett  
After delete everything in D:\program\cmder and extract new one there, "git submodule" works well, thanks very much.
I updated cmder from 1.3.0 to 1.3.2 by extract the new version to the old folder and choose overwrite for all files, and I'm sure both are the full version.
May I know the appropriate way to update old cmder to a new one? Thanks.

**Comment by Jackbennett** [comment]
Sounds like when you copied in the new files, it's added to come things in cygwin they're removed in new versions. You could have probably just gotten away with replacing that vendor/ folder.

The proper upgrade method in that case should be to remove the existing `vendor/` folder then you can copy in the new cmder over the top.

Not ideal I know. Checking with @cmderdev/trusted-contributors Is that really the best upgrade method?

**Comment by daxgames** [comment]
@Jackbennet - Thats what I would do with two additional stepc depending on current version of Cmder.  Backup the ConEmu.xml before deleting the vendor folder and restore it after copying in the new Cmder stuff.  The extra two steps are not required if upgrading from version 1.3.2, the current version.

**Comment by gutierrezps** [comment]
Hi. I've been using cmder for a long time, almost on a daily basis. Suddenly today, when trying to `git push`, I've got a similar error:

```
λ git push
      1 [main] bash (9048) D:\Data\Apps\cmder\vendor\git-for-windows\usr\bin\bash.exe: *** fatal error - cygheap base mismatch detected - 0x1626408/0x1396408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
      0 [main] bash 3692 fork: child -1 - forked process 9048 died unexpectedly, retry 0, exit code 0xC0000142, errno 11

bash: fork: retry: No child processes
^C
      1 [main] bash (2268) D:\Data\Apps\cmder\vendor\git-for-windows\usr\bin\bash.exe: *** fatal error - cygheap base mismatch detected - 0x1626408/0x11B6408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
```

I've reinstalled cmder (the git version), but I've got the same error. I ran this command yesterday, and it worked fine. I didn't do anything different in the meantime (no updates, no other programs installed/removed).

I solved it by updating Git - downloaded latest [PortableGit version](https://github.com/git-for-windows/git/releases), 2.13.2 as today, and replaced the `vendor\git-for-windows` folder.
