### ISSUE TITLE
Create alias with equal sign gets truncated in cmder cli

### ISSUE THREAD

**Issue by GlassGruber** [cmderdev/cmder#1245]
Hey there as per title, when I try in cmder prompt to create an alias with an equal sign, what comes with the `=` gets truncated and not correctly stored in the `user-aliases.cmd` file.

For ex:
`λ alias wifi=netsh wlan show profile $1 key=clear`
will be stored as:
`wifi=netsh wlan show profile $1 ke`

I guess for `$reasons` cmder reads `y=clear` as `$something` worthy evaluating and so it's cut off from the actual alias storing process. Manually editing the file quickly overcome this issue.

Am I blatantly missing something on the ever growing *Effin' Manual* that I haven't accurately read? 😛

**Comment by glucas** [comment]
It looks like the doskey command (which alias wraps) handles your example, so this may be a bug in the alias.bat script.

**Comment by GlassGruber** [comment]
I can confirm your correction fixed the problem, thank you! Should I do a PR?

**Comment by glucas** [comment]
I can create a pull request with the fix.
