### ISSUE TITLE
Question : Sound

### ISSUE THREAD

**Issue by paallaire** [cmderdev/cmder#1248]
Is it possible to have sound in Cmder like "beep" ?

I use "command line window" and I have a "beep" sound when I make a error in Gulp but no sound in Cmder.

**Comment by yairEO** [comment]
yes, in windows `CMD` you get to hear those lovely "beeps" (try <kbd>CTRL</kbd> + <kbd>G</kbd>) but Cmder is silent..

**Comment by xulfir** [comment]
Seems like it's a ConEmu feature. To disable: Settings > Features > In-console options > uncheck "Suppress bells"

**Comment by yairEO** [comment]
it works! now I have internal speaker sound! Thanks @xulfir

**Comment by willsoares** [comment]
The sound could be customized.
I mean, the sound ideia isn't bad, but the sound that is played is too long and loud. It's irritating. Could be just a beep. A tiny, smooth beep
