### ISSUE TITLE
about linux on windows

### ISSUE THREAD

**Issue by aak1247** [cmderdev/cmder#1249]
### Question
&nbsp;&nbsp;&nbsp;&nbsp;The appearence is not lovely at all when using linux on windows in cmder, and what's more important is that I can't recall the last command by press key ":arrow_up:", which means when I am using bash(linux on windows) in cmder, nothing would happen as I press ⬆️.
### Suggestion
&nbsp;&nbsp;&nbsp;&nbsp;As you could see the linux on windows is pretty useful, so it's important to make it easy to use it. Thanks for seeing this.

**Comment by paal85** [comment]
I solved it by creating a new task and call bash.exe directly, then it should work.
![cmder_bash_for_windows](https://cloud.githubusercontent.com/assets/12137432/22783201/02aa06c8-eecb-11e6-9f67-bb5e7a2f9e9a.png)

**Comment by aak1247** [comment]
@paal85 Thanks! This works well!
