### ISSUE TITLE
Ctrl+C not passed to console

### ISSUE THREAD

**Issue by talz** [cmderdev/cmder#1258]
I'm working with {cmd} on cmder.
It appears that the key combination of Ctrl+C is not passed to the actual shell.
Other special escape keys are passed properly (Ctrl+D, Ctrl+Z, etc.)
It appears as though Ctrl+C is captured by the Conemu wrapper and not passed down to the shell

**Comment by andre-f-paggi** [comment]
I am having the same issue for days. 

When I press Ctrl-C, the Cmder shows the normal console input with the lambda sign on the beginning but as soon as I start typing, the rest of the last command output starts showing on screen and messing everything up.

Example: git hist
![image](https://cloud.githubusercontent.com/assets/8538938/23130644/05bb39ce-f766-11e6-9723-b9c386fab911.png)

**Comment by talz** [comment]
Not the same here.
As far as I know, what @andre-f-paggi is showing is a git bug, and not a cmder (i'm familiar with issue with git commands and various cygwin commands for agest)

What I'm experiencing is ctrl+c not being passed to the console at all, doesn't terminate batch jobs, doesn't stop any other long running commands, etc.

E.g. when opening python interperter, pressing Ctrl+D (or any other letter for that matter) will result with a ^D - Ctrl+C won't show anything.

**Comment by andre-f-paggi** [comment]
Oh, I am sorry that I got it wrong. 😅

**Comment by talz** [comment]
Ok guys, found what the issue was.
I am using Windows 10 Insider build 15025 - the problem was with modification that were made by Microsoft to standard cmd.exe

To solve this I had to "Use legacy console" option in standard cmd - which solved this issue.

**Comment by BrainCrumbz** [comment]
@talz where do you set that option (when starting cmder)?

**Comment by tomskip123** [comment]
1. Open Command Prompt (probably as admin)
2. right click on window (top bar)
3. Click properties
4. Options Tab
5. check 'Use Legacy Console'
6. Ok

**Comment by BrainCrumbz** [comment]
@tomskip123 thanks for those steps. Regarding force exit the console and restart, have you checked the *Kill active process* command?

![image](https://user-images.githubusercontent.com/3185573/36427203-bd2d14c8-164c-11e8-84f7-fce70bb5e547.png)

**Comment by BrainCrumbz** [comment]
Just checked now, and I think there's also a "less invasive" option to workaround this. The same steps as @tomskip123 but using another check:

1. Open Windows Command Prompt as admin
1. Right click on top bar
1. Properties menu command
1. Options tab
1. **Uncheck** *Enable Ctrl key shortcuts*
1. Ok

![image](https://user-images.githubusercontent.com/3185573/36427568-de439690-164d-11e8-8d7b-1a6dbe0a7c62.png)

The difference being that instead of loosing modern features altogether, you just give up on one single feature. And BTW Ctrl-C Ctrl-V seems to still work.

HTH

**Comment by tomskip123** [comment]
Unfortunately, that didn't work for me. When using angular2 CLI (ng serve) and Ctrl+c/ Ctrl+v it looks like it's exited the watching process but when I make changes it continues recompiling the code.

**Comment by BrainCrumbz** [comment]
Uhm ... have you tried hitting that twice? For us it worked (with just one hit) both with `dotnet run` and `ng build -w`.

**Comment by tomskip123** [comment]
Aha! You're right. Whilst Ctrl+c and y (answering the Terminate batch Job  (y/n)) doesn't actually kill the process... double Ctrl+c works. Also after checking out this article, you can bypass this stupid prompt by creating a bash script and running the commands! yay 

[https://www.triplet.fi/blog/getting_rid_of_terminate_batch_job_while_developing_node_application_on_windows/](url)

**Comment by BrainCrumbz** [comment]
Please note link is somehow broken, had to manually select text and copy it

**Comment by tomskip123** [comment]
Ok Fixed

**Comment by khmelev77** [comment]
I can not use the recommendations above, they are all out of date. And in "cmd" (as administrator) I don’t have at all "enable ctrl key shortcuts" windows 7. 
What needs to be done in the latest stable version of cmder to kill the running python process? CTRL + C does not work!

**Comment by miltoncandelero** [comment]
Having the same problem trying to end node running on bash running on conemu.

(cmd on conemu works fine)

**Comment by moataz9** [comment]
hey guys, i use cemder cmd and i solve it by 
1) setting (win + alt + p)
2) keys & macro
3) write "active process" in Filter Hotkeys (Alt + F)
4) choose Terminate (kill) active process in the current console and click on it
5) choose hotkey: is enabled make it c
6) and ctrl from second list
7) don't forget to save setting
:) enjoy

**Comment by amrak44** [comment]
create a macro.  in the line put 

break Event==0

per documentation.
Break([<Event>[,<ProcessGroupId>]])
  - Event==0: Generates a CTRL+C signal
    Event==1: Generates a CTRL+BREAK signal
    More info in GenerateConsoleCtrlEvent WinAPI function

**Comment by timofeydanshin** [comment]
I have a similar but not identical problem: I am using tmux in ComEmu, and the Ctrl-B prefix key is not passed to it. Is there a way to allow all ctrl key combinations to be passed to the shell?

**Comment by thedelk** [comment]
For anyone who might need this in the future, here's a screenshot to go with @moataz9's solution.

![image](https://user-images.githubusercontent.com/26914643/153253185-88749eff-ee4e-4249-be8d-edeb731b6b9e.png)
