### ISSUE TITLE
prevent output beeing cleared afer batch script is done executing

### ISSUE THREAD

**Issue by bitbonk** [cmderdev/cmder#1260]
When I run a .bat or .cmd script and the script prints some output to the cmder console, when this script is done executing that output is automatically cleard leaving me with an empty cmder window. Is there a way to prevent this? If not, please add this feature, so I do not have to put `pause` at the end of all scripts I want to run.

**Comment by daxgames** [comment]
This is not anything we are doing.  Do you have a sample script?

**Comment by bitbonk** [comment]
Ok, I found it. It always happens when I start the scripts from TotalCommander instead of Windows Explorer. Any idea what could cause this and what I could do against this?
