### ISSUE TITLE
Customising Lambda

### ISSUE THREAD

**Issue by justskymarshall** [cmderdev/cmder#1261]
Is the only non-customisable component of cmder, the lambda itself? I'd like it to be a different character.

**Comment by daxgames** [comment]
You could customize it but you would need to redo the customization after each upgrade.  It is not designs to be user configurable.

**Comment by gustavoalfaro** [comment]
I have my own customized theme for cmder you can find it here:
https://github.com/gustavoalfaro/power-monokai

**Comment by Jackbennett** [comment]
We'll work out a solution to #1280 and you'll be able to change everything.
