### ISSUE TITLE
cmd history (cursor-up/cursor-down) not working

### ISSUE THREAD

**Issue by jenisys** [cmderdev/cmder#1262]
VERSION: cmder-1.3.2

When I open a "cmd.exe" window with ``cmder`` , the cursor-up/cursor-down semantics (command history) no longer works on one of my PCs. I only see the cryptic ``ASCII-ESC H`` or ``ASCII-ESC M`` sequences instead of the expected behaviour.

For whatever reason, it is working on another PC. 
In addition, the command history is working when I use the bash (with cursor-up/cursor-down).

MAYBE RELATED: Has the fix for the following issue related to bash caused this ?
* https://github.com/Maximus5/ConEmu/issues/629
* https://github.com/Microsoft/BashOnWindows/issues/111

**Comment by Stanzilla** [comment]
Yup, nothing we can do here.

**Comment by jordwalke** [comment]
Is there a way to take advantage of the underlying ConEmu workaround?
`ConEmu.exe -basic -run {bash}` ?

**Comment by jenisys** [comment]
**PROBLEM-CAUSE:** ``%HOME%/.inputrc`` file (orginally for Cygwin) in my  Windows ``HOME``  directory.
After I removed/renamed the file, everything works fine again.
NOTE: Problem w/ CURSOR-UP/-DOWN keys was in the cmd-shell (and not the bash; bash was working fine).
