### ISSUE TITLE
real-time as-you-type syntax highlighting

### ISSUE THREAD

**Issue by cmrdt** [cmderdev/cmder#1263]
perhaps similar to https://github.com/zsh-users/zsh-syntax-highlighting#zsh-syntax-highlighting
(because of  ease of typo errors from complex commands)

whether to include

- "quoted strings"
- programs
- arguments
- operators
- **red for errors/typo's**
- gray for auto-complete

**Comment by Jackbennett** [comment]
Ditch cmd for powershell and you'll get something like this. Otherwise if clink haven't added that by now maybe they can't?
