### ISSUE TITLE
Error when entering a git repo directory

### ISSUE THREAD

**Issue by thany** [cmderdev/cmder#1264]
When I enter a git repo directory on the lambda console (let's call it that, since the console prompt isn't always a lambda...) I get this:
![capture](https://cloud.githubusercontent.com/assets/152227/23126054/41b69310-f775-11e6-89d0-e45c6f66fc1a.PNG)

To make this findable through searching:
```
C:\Cmder/vendor/clink-completions/npm_prompt.lua:11: attempt to concatenate local 'package_version' (a nil value)
```

What can I do to fix this? Or is this a bug somewhere I can't reach?

**Comment by Stanzilla** [comment]
Please update to the latest version

**Comment by thany** [comment]
I always let it update when it asks for it. Is auto-updating broken, you say?

**Comment by daxgames** [comment]
Auto update is a component of and only updates conemu which is only part of cmder.  The rest remains at an older version.

**Comment by thany** [comment]
I've updated to the latest version, but the problem remains.
