### ISSUE TITLE
Small issue with syntax highlighting in directories with "%20" in their name

### ISSUE THREAD

**Issue by alexbance** [cmderdev/cmder#1265]
Any folder with %20 in the name gives the following error `D:\cmder\vendor/clink.lua:42: invalid capture index` and the syntax highlighting is broken.
![image](https://cloud.githubusercontent.com/assets/23360105/23127247/35ac8a32-f772-11e6-864d-54730bb97dcf.png)

**Comment by janschulz** [comment]
Seems to be this:
http://stackoverflow.com/questions/11008520/putting-in-string-gsub-in-lua

I tried a few ways to escape it, but I wasn't successfull :-/

**Comment by alexbance** [comment]
Ahh that would also explain an issue I'm having with ^. If you try to apply a stash like so `git stash apply stash^{/ExampleStash}` you get a fatal error. I assume it's a similar issue being that ^ is an operator in lua?

**Comment by janschulz** [comment]
I added the following functions and replaces all `string.gsub` by `replace`:

```
function explode(separator, str, withpattern)
	if ( withpattern == nil ) then withpattern = false end
	local ret = {}
	local current_pos = 1
	for i = 1, string.len( str ) do
		local start_pos, end_pos = string.find( str, separator, current_pos, not withpattern )
		if ( not start_pos ) then break end
		ret[ i ] = string.sub( str, current_pos, start_pos - 1 )
		current_pos = end_pos + 1
	end
	ret[ #ret + 1 ] = string.sub( str, current_pos )
	return ret
end

function replace( str, tofind, toreplace )
	local tbl = explode( tofind, str )
	if ( tbl[ 1 ] ) then return table.concat( tbl, toreplace ) end
	return str
end
```

the functions are form https://github.com/garrynewman/garrysmod/blob/master/garrysmod/lua/includes/extensions/string.lua, which have no license attached :-(

**Comment by Stanzilla** [comment]
want to make a PR?

**Comment by janschulz** [comment]
Do you want the functions which are upstream without a license?

**Comment by Stanzilla** [comment]
I think it's ok, it's pretty generic.. cc @MartiUK though

**Comment by MartiUK** [comment]
I'd give a cautious yes to go ahead, a simple attribution in a comment would be enough I feel.

**Comment by jankatins** [comment]
I'm not anymore using windows, and so also do not use cmder, so I cannot do this PR anymore :-(

**Comment by jkesselring** [comment]
Has there been any movement on this issue?

**Comment by Stanzilla** [comment]
![conemu64_2018-05-17_15-09-39](https://user-images.githubusercontent.com/75278/40179358-7164d324-59e4-11e8-9510-92526e62397b.png)
Can't repo :(

**Comment by jkesselring** [comment]
I see this is closed, but I want to throw this into the ring. In my case I'm using an SVN(I know) repo, perhaps that's the trick? Running CMDER v1.3.5

![image](https://user-images.githubusercontent.com/366279/41102275-77a18240-6a34-11e8-915a-6bfae5adf7fb.png)

**Comment by Stanzilla** [comment]
Yup, can repro with SVN, thank you!

**Comment by jkesselring** [comment]
When downloading from https://ci.appveyor.com/project/MartiUK/cmder/branch/master/artifacts the problem persists. Error reported drops down 5 lines - vendor/clink.lua:335

**Comment by Stanzilla** [comment]
What is your folder name? You blanked it out in your screenshot.

**Comment by jkesselring** [comment]
Tested cmder from previous link on the dirs for both: 

- C:\dev\K188CA163TestDirectory\source
- C:\dev\test dir\source

**Comment by Stanzilla** [comment]
So you don't even have % in your path, so it's a different issue. I can't repro with your paths.

![conemu64_2018-06-07_16-45-19](https://user-images.githubusercontent.com/75278/41107222-32bd178c-6a72-11e8-8221-7014b5174f15.png)

**Comment by Stanzilla** [comment]
I will take a proper look at both issues later.

**Comment by Stanzilla** [comment]
@jkesselring can you test with https://github.com/cmderdev/cmder/commit/e3cdf43afc88b514045e80e30689b6f35cbdc925 please?

**Comment by jkesselring** [comment]
@Stanzilla Problem persists through on v1.0.698-master. (Apologies for the delay in getting back)

> vendor/clink.lua:334: invalid capture index

The SVN repos I'm working with do have %20 in them. Several in fact. 

IE: Something like 

> URL: https://svn.foo.net:2222/svn/projects/clients/foo%20/bar/51487/Project%20Name
Relative URL: ^/projects/clients/foo%20/bar/51487/Project%20Name

**Comment by Stanzilla** [comment]
![conemu64_2018-06-21_16-45-30](https://user-images.githubusercontent.com/75278/41726494-966ecb80-7572-11e8-9c45-e47b07d4a8f0.png)
🤔🤔
