### ISSUE TITLE
Can't use as terminal in Android studio

### ISSUE THREAD

**Issue by cclover** [cmderdev/cmder#1267]
Hi: 

I want to set the cmder as terminal in AndroidStudio on Windows10 to instead the cmd or powershell .

But when i set and  click the [terminal] tab in Android Studio, it will open an new cmder windows.

I want the cmder window can embed into the Android Stuido terminal

Thanks!

**Comment by radzio** [comment]
👍

**Comment by bezmian** [comment]
:+1:

**Comment by mzielu** [comment]
👍

**Comment by DRSDavidSoft** [comment]
@cclover - related #282

Here are the full steps to work Cmder perfectly with Android Studio:
1. Assuming you have the latest version of Cmder, go to the installation directory and create a new file named `cmder_shell.bat`, with the following content:
`@cmd.exe /k %0\..\vendor\init.bat`
1. Open settings in Android Studio (<kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>S</kbd>) and type `terminal` in the search box
2. In the __Shell path__, change _cmd.exe_ to the following:
`C:\path\to\cmder\cmder_shell.bat` (make sure to replace _C:\path\to\cmder_ to **your** installation directory)

At any time, press ALT-F12 to run Android Studio's terminal with Cmder.
<img width="762" alt="android_studio_terminal" src="https://user-images.githubusercontent.com/4673812/36968495-ebb6a068-2077-11e8-88cb-904bdcc0af0e.png">

<img width="573" alt="android_studio_terminal_cmder" src="https://user-images.githubusercontent.com/4673812/36968583-2d3d4596-2078-11e8-8d3d-7f4e82f95421.png">

**Comment by DRSDavidSoft** [comment]
@Stanzilla Please add label:Guide, thanks.

**Comment by daggerok** [comment]
Did like so and terminal opens using cmder, but how can I fix encoding?

![image](https://user-images.githubusercontent.com/2445604/48505348-27a13b00-e847-11e8-845d-0bf24c314995.png)
