### ISSUE TITLE
Bash on Ubuntu for Windows versus Cmnder version discrepancy

### ISSUE THREAD

**Issue by mark-walle** [cmderdev/cmder#1269]
I am using Cmnder to run Bash on Ubuntu for Windows 10 as a task. In the Bash for Ubuntu I've installed ZSh and am using a Powerline theme. The reason I switched to Cmnder was to allow this theme setup.

There are version discrepancies in the software between these two for node and npm. Possibly others, but this is the first of my concerns:

in Cmnder (running Ubuntu for Windows as a task):
```
╭─ mwalle@DESKTOP-LO101K6   ~ 
╰─ node -v                       
v0.10.25                         
╭─ mwalle@DESKTOP-LO101K6   ~ 
╰─ npm -v                        
4.2.0                            
╭─ mwalle@DESKTOP-LO101K6   ~ 
╰─              
```                 

in Ubuntu for Windows:
```
╭─ mwalle@DESKTOP-LO101K6   ~ 
╰─ node -v
v7.5.0
╭─ mwalle@DESKTOP-LO101K6   ~ 
╰─ npm -v
1.3.10
╭─ mwalle@DESKTOP-LO101K6   ~ 
╰─
```

the task defined in Cmnder is:
`%windir%\system32\bash.exe ~ -cur_console:p`

![version problem](https://cloud.githubusercontent.com/assets/3486204/23191507/e1d9cd66-f852-11e6-92cf-de53407ee6bc.PNG)

**Comment by BClev** [comment]
In Ubuntu for Windows and in cmder bash, type `which node` and `which npm`. If those both show the same location, open up a cmder cmd.exe and type `for %i in (npm.exe) do @echo.   %~$PATH:i` and `for %i in (node.exe) do @echo.   %~$PATH:i` . 
Please post the results.

**Comment by BClev** [comment]
@mark-walle ?

**Comment by mark-walle** [comment]
Sorry @BClev, I lost track of this:

Both Ubuntu for Win10 and Cmndr showed the same location:
```
>which node
node: aliased to nodejs
> which npm
/usr/local/bin/npm
```
The results of your directions:
```
Mark@DESKTOP-LO101K6 C:\Users\Mark\Desktop
> for %i in (npm.exe) do @echo. %~$PATH:i


Mark@DESKTOP-LO101K6 C:\Users\Mark\Desktop
> for %i in (node.exe) do @echo. %~$PATH:i
 C:\Program Files\nodejs\node.exe

Mark@DESKTOP-LO101K6 C:\Users\Mark\Desktop
> where npm
C:\Users\Mark\AppData\Roaming\npm\npm
C:\Users\Mark\AppData\Roaming\npm\npm.cmd
C:\Program Files\nodejs\npm
C:\Program Files\nodejs\npm.cmd

Mark@DESKTOP-LO101K6 C:\Users\Mark\Desktop
> where node
C:\Program Files\nodejs\node.exe
```

My goal was to get node v7.5.0 in Cmndr, but now it seems I have v0.10.25 in _both_ Ubuntu for Windows _and_ Cmndr. Following your procedure above, I tried updating node according to http://askubuntu.com/questions/426750/how-can-i-update-my-nodejs-to-the-latest-version#480642, but the version number is still reading v0.10.25.

cmd.exe gives:
```
C:\Users\Mark>node --version
v4.6.1
C:\Users\Mark>where node
C:\Program Files\nodejs\node.exe
```

**Comment by BClev** [comment]
This looks like an issue with node in general. Found this stackflow with a potential solution: http://stackoverflow.com/questions/33383349/updating-to-node-4-x-in-linuxubuntu-fails-with-no-error-and-stays-with-v0-10

**Comment by mark-walle** [comment]
Thanks. Didn't quite work for me, but I googled some more and found a guide that helped:
https://aigeec.com/installing-node-js-on-windows-10-bash/
replacing the line
`curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -`
with 
`curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -`
to get the latest version... Perhaps there is a more generic url to always pull the latest, but this worked for me, and `node --version` returns `v7.7.3` across both Cmnder and Ubuntu for Window 10.
