### ISSUE TITLE
Cmder not receiving %V when being launched from Right Click menu

### ISSUE THREAD

**Issue by bsquidwrd** [cmderdev/cmder#1271]
When right clicking a directory and clicking "Cmder here", the program does not seem to receive "%V".

If I change the binary it's launching to PowerShell, it launches just fine, with it's `-command "Set-Location -LiteralPath %V"`.

But, if I run manually `C:\cmder\Cmder.exe C:\some\path\` it starts in that path perfectly fine.

The value for the `command` key in the registry is `"C:\cmder\Cmder.exe" "%V"`

**Comment by freemagee** [comment]
Try

"LOCAL_PATH_TO_CMDER" /START "%V"

Where LOCAL_PATH_TO_CMDER is your path ;) Using this as my right click command opens Cmder in my current folder in Win Explorer.

**Some notes:**

Opens Cmder in a new window. There is some discussion here about how to open it in a tab:

https://github.com/cmderdev/cmder/issues/91

**Comment by bsquidwrd** [comment]
I forgot this was an issue I submitted. It seems to be working now, not sure what changed or how it was fixed but it works now.
