### ISSUE TITLE
Always-on-top, but click-through to underlying applications, rather than taking back focus

### ISSUE THREAD

**Issue by timkrins** [cmderdev/cmder#1273]
Love the always-on-top, but often, I just want to monitor my console, and not interact with it.

It would be great if we could set the out-of-focus-but-always-on-top console window to pass through clicks to underlying applications, so that clicks will only be accepted in the console when it **_already_** has focus.

I would then expect to re-focus the application by clicking the task-bar or tray.

**Comment by timkrins** [comment]
There is already a Windows application called "Peek Through" which allows this sort of click-through functionality, but it would be sweet to have it as an option here.

**Comment by Jackbennett** [comment]
That would be a good question for the conemu devs
