### ISSUE TITLE
Update GPG 

### ISSUE THREAD

**Issue by Keyhaku** [cmderdev/cmder#1276]
Hello,

It seems the version of GnuPG that you are embedding in cmder is very old (1.4.20 - 2015).
Yet Google proved recently that SHA-1 collision is possible, and old version of gpg use sha1 as the primary signature fonction.

For security sake, please update gpg to the latest modern version (2.1).

Thanks

**Comment by Jackbennett** [comment]
This will be from tools in Git-For-Windows so it'll get updated as a dependency when they do.
