### ISSUE TITLE
Odd SSH Behavior?

### ISSUE THREAD

**Issue by audioeptesicus** [cmderdev/cmder#1277]
I'm new to using Cmder, and figured I'd try it at work to replace SecureCRT (7.3.0 if that matters). SSHing to one of my Ubuntu servers at home, I have no issues. SSHing to a Ubuntu jump box at work, I have no issues (after configuring ServerAliveInterval in the ssh_config). However, there's one Ubuntu jump box that I have issues with (in the image below). I use this server strictly to ssh to other servers in our environment and in customer's environments. Connecting to this server via SSH in SecureCRT, I can't use backspace (shows up as ^H), but delete works like backspace. However, using cmder, backspace shows a block (below), and delete doesn't do anything. Using the up arrow, it actually moves the cursor up to the line above, as it should. Using the picture below, if I were to hit the up arrow, the cursor would be on top of the "h". If I were to hit the up arrow in SecureCRT, it'd show up as "^[[A".

Really, the biggest issue is not being able to use backspace/delete. If I mistype, my only options are to disconnect the session or execute the command, which I don't like the idea of doing.

Thoughts?

Thanks,
Mike

![cmder1](https://cloud.githubusercontent.com/assets/25988545/23363923/fb5108d2-fcca-11e6-91b9-8113db5eb61d.JPG)

**Comment by waulkrie** [comment]
I just went through something similar, it has to do with being logged into /bin/sh (bourne shell),
exec bash (/bin/bash or bourne again shell) or zsh or an other shell. Don't think this is inherent of Cmder.
