### ISSUE TITLE
How to get old 1.2 behavior on 1.3 ?

### ISSUE THREAD

**Issue by oskari** [cmderdev/cmder#1279]
I just reinstalled cmder and immediately noticed that it just doesn't work like it used to. There's no lambda and tab completing dirs doesn't work the same. It completes the directory but doesn't prepend  '/' and autocomplete next path. 

Also all the old default hotkeys seem to be gone now.

**Comment by glucas** [comment]
This seems like an installation or configuration issue. --  there are not changes in 1.3 to remove the lambda or change the default hotkeys.
