### ISSUE TITLE
ctrl+space doesn't set mark in Emacs through bash on Windows

### ISSUE THREAD

**Issue by sanchom** [cmderdev/cmder#1281]
When I run bash on Windows through cmder, and then try to use Emacs from within bash, ctrl+space doesn't set the Emacs mark. Instead, it simply inserts a space.

**Comment by psidhu** [comment]
Still an issue with 161206.

**Comment by gaspar09** [comment]
Is there any known fix for this?

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)
