### ISSUE TITLE
Alt+Space

### ISSUE THREAD

**Issue by kasajian** [cmderdev/cmder#1288]
installing the mini version, looks like a very common windows shortcut, that's been there since Windows 1.0, Alt+Space to bring up the windows system menu, is not working.

it doesn't look like it's a missed setting 'cause I looked at all of the configuration.

**Comment by DRSDavidSoft** [comment]
@Stanzilla This is a real issue. Tested it out, not a problem of ConEmu or Clink. Any idea what causes it in Cmder?

**Comment by Stanzilla** [comment]
it's Win+Alt+Space and non configurable: https://conemu.github.io/en/KeyboardShortcuts.html
