### ISSUE TITLE
Cmder current path loses lambda and path colors with global clink install

### ISSUE THREAD

**Issue by ihorzenich** [cmderdev/cmder#1291]
**Steps to reproduce**
1. Install cmder wih Chocolatey: `choco install cmder -y`
2. Run cmder, you will see colored current path and lambda. Close cmder.
![2017-03-21 2](https://cloud.githubusercontent.com/assets/1684521/24142199/8c098966-0e2e-11e7-8002-cdb8fbc925fd.png)
3. Install *clink* wih Chocolatey after cmder install: `choco install clink -y`.
4. Run cmder, you **will not see colored current path and lambda**.
![2017-03-21 1](https://cloud.githubusercontent.com/assets/1684521/24142150/65582d40-0e2e-11e7-99d3-570947d11be1.png)

Windows 10 Anniversary Update, 10.0.14393.726

No matter when you install *clink* — before or after cmder. Also no matter there is ConEmu installed or not into system.  
Clink uninstall (`choco uninstall clink -y`) fix the problem.

**Comment by YLiLarry** [comment]
Might be helpful to add an option to change the lambda's color or hide it?

**Comment by Oxicode** [comment]
+1

**Comment by e-pc** [comment]
I am not really sure how the command prompt customisation is done in cmder but if you want to have the custom prompt in cmder (by custom I mean with lambda and colourised) and still have clink installed globally then just remove clink's autoinjection:
`clink autorun uninstall`

For more details check the Usage section [here](https://github.com/mridgers/clink).
