### ISSUE TITLE
New completions for clink

### ISSUE THREAD

**Issue by hervehobbes** [cmderdev/cmder#1293]
Hello,

Could you consider to add those completions for clink?
https://github.com/hervethouzard/clink-completions

There is one for ionic and another one for composer.

Bye

**Comment by glucas** [comment]
You can those or your own custom clink completions by dropping the .lua files in your cmder/config directory.

**Comment by hervethouzard** [comment]
Yes I know, I was just suggesting that you include them in cmder.
