### ISSUE TITLE
Chinese folder error

### ISSUE THREAD

**Issue by ywyt738** [cmderdev/cmder#1294]
my envirionment: cmder 1.3.0, windows7 x64. Version status:161206 stable

I place the whole program in Chinese folder.
When I open cmd in cmder, it wil show "cannot open E:\鎴戠殑鍧氭灉浜慭cmder\vendor\clink\clink.lua: No such file or directory"

![1](https://cloud.githubusercontent.com/assets/19743532/23687177/3f8802de-03e8-11e7-9a4d-a0dbccc79b1a.png)

**Comment by benjaminach** [comment]
Same error with french accents ;)

cannot open G:\T├®l├®chargements\cmder\vendor\clink\clink.lua: No such file or directory

**Comment by Lin-Buo-Ren** [comment]
And Chinese(Taiwan) locale(CP950) as well
![default](https://user-images.githubusercontent.com/13408130/31112322-a0bceedc-a845-11e7-93e7-808ed5ef2173.png)

**Comment by xianyukang** [comment]
![image](https://user-images.githubusercontent.com/24707226/44314699-4792af80-a44e-11e8-986e-b48af3c51202.png)

**Comment by bashkos** [comment]
Same error
