### ISSUE TITLE
Environnement Path doesn't refresh after restart

### ISSUE THREAD

**Issue by maxime4000** [cmderdev/cmder#1298]
Hi 
I just install node and npm from Chocolatey.
Normally I expect them to work just after the choco install or maybe after a restart of the shell.
But it wasn't. So I try to update cmder with the preview version and it wasn't working too. I can't affort the reboot now (mid work and can't stop the app) So I just decide to use normal cmd to work with, but I really don't understand why the Environnement Path wasn't refreshing and I verified with RapidEE and those were there. (And Working in cmd.exe...)

Just let me know if you need something to check why it's happening 

Here what I don't understand (maybe it's an useless gif but anyway)
![cmder](https://cloud.githubusercontent.com/assets/4070713/23728947/692a7ea6-042d-11e7-9d26-6590e372f841.gif)

**Comment by Jackbennett** [comment]
You'll need to check the path those process' are under is mentioning in the PATH env variable that cmder has in it.

I think cmd is `echo %PATH%` but i know powershell is `$env:Path.split(';')` The path needs to be the folder with the executables in it, windows doesn't check those paths recursively. Only the first one found will get used too. (I'm sure you knew that just to narrow things down)

Withpowershell you can check the path scopes too if you are finding cmder doesn't have the same paths as cmd.exe or powershell.exe

Scope | command
--|--
process | `$env:Path.split(';')`
User | `[Environment]::GetEnvironmentVariable('Path','user').split(';')`
Computer | `[Environment]::GetEnvironmentVariable('Path','machine').split(';')`

sidenode: How did you make the gif it's really nice?

**Comment by maxime4000** [comment]
In fact, I just write path in cmder and it was like if the application wasn't able to get path from the systems and in cmd.exe was showing all path so I guess something when wrong in the refresh of environnement path and it wasn't able to get whatever from the systems. 

By the way, the reboot fix my thing but I just want to let you know that happen and I don't know why.

For the gif : Screentogif. Lightweight project on github (On phone so I let you google that)

**Comment by Jackbennett** [comment]
Thanks, it must have overwritten PATH somehow like you said.

**Comment by maxime4000** [comment]
Version : 170305 preview and the Stable release

So I don't know why but it's appear again when I use Chocolatey
I install Mercurial
Try using hg after the install and it's doesn't work.
Restart CMDer and it not working again...
This is the screen shot of cmder after the restart of CMDer (BTW: hg work on cmd.exe)
![cmdererrorpath](https://cloud.githubusercontent.com/assets/4070713/24019850/1b54e4e8-0a70-11e7-8951-2810865770e1.png)

__NOTE : The next thing I should do is installing from the installer and try after on CMDer (Any idea of good tools to try with?) (Restart Require so I will update this issues in the next day)__

**Comment by joeflack4** [comment]
+1 Why is this closed? Issue still exists.

**Comment by daxgames** [comment]
The following is how it works.  I have not tested the exact circumstances since I am not quite sure what those are.

Cmder shell env is inherited from the cmder.exe that launched it.  If running a new cmd.exe works then running a new cmder.exe should also work.  Simply starting a new shell from an already running cmder.exe session will not work because it still has the env that was available prior to installing the new apps.

**Comment by Jackbennett** [comment]
Lol why is it closed? Have you seen the post dates for someone to bring this up again?

Doesn't conemu keep running in the system tray unless you exit everything from there? That's my guess I can't test from my phone and Chromebook.

**Comment by malvarco** [comment]
I can confirm the problem is still there. I could run sass on cmd, but even when restarting Cmder, it wouldn't run. I had to add the path manually in Cmder. Very annoying, considering you want it to work right away to replace cmd.

**Comment by daxgames** [comment]
What if you run Cmder from CMD.exe?

**Comment by MrEduar** [comment]
I was having the same problem. Following the recommendation of @daxgames the problem seems to be solved....
