### ISSUE TITLE
Git Branch Autocomplete

### ISSUE THREAD

**Issue by adamjford** [cmderdev/cmder#130]
Before switching to cmder, I was using ComEmu + Git Bash, and it had a feature where if you were typing a git command that expected a branch name, like `git checkout <branch>`, you could start typing the name of the branch and then hit Tab to autocomplete the name. (Or at least I believe it included that; I might have added that myself a long time ago but I don't recall doing so.)

It doesn't appear that cmder supports that out of the box. Is there a way to enable that or would that have to be a new feature?

Note: I'm using the MSYSGIT version of cmder.

**Comment by espiriki** [comment]
I'm using the 191012 [64] version and looks like it doesn't work when you use aliases.
If I do "git checkout branch-name" that works for me. But I have an alias "co" for checkout
If I do "git co branch-name" that doesn't work

**Comment by bachbach** [comment]
@espiriki here you can find a workaround: https://github.com/cmderdev/cmder/issues/1495
