### ISSUE TITLE
`cd/d D:' always goes to `D:\Programs\Cmder\config\profile.d'

### ISSUE THREAD

**Issue by hyrious** [cmderdev/cmder#1301]
As I put Cmder at `D:\Programs\Cmder`, every time when I change directory by:
~~~ shell
D:
cd/d D:
cmder /single "D:"
~~~
It will goes to `D:\Programs\Cmder\config\profile.d` actually.
![default](https://cloud.githubusercontent.com/assets/8097890/23820513/e57db9f4-0654-11e7-8e69-babb7c5e9241.png)
And I've noticed something like below (the `C:` goes to `%HOME%` is the same as Windows's Cmd):
![default](https://cloud.githubusercontent.com/assets/8097890/23820518/2fbbd44c-0655-11e7-9290-0378b84d85d3.png)
- Given path with `/` means the absolute path, it's obvious.
- Without `/`, it seems like it will goes to the `HOME` folder but I'm not sure.

Any explanation?

**Comment by manizm** [comment]
Getting same issue. Fairly new to using cli so I am not sure what to do

**Comment by hyrious** [comment]
More details I've found these days.
- **Windows' Cmd will remember the last directory** of the disk you've worked at, and when you `cd` back to the same disk (without `/`), it will be there.  
![image](https://cloud.githubusercontent.com/assets/8097890/24034022/871eb1d0-0b2a-11e7-98fe-f38824d7874d.png)
- Same behavior will be seen on Cmder, so we could conclude this:  
  **Cmder's last working directory is `%CMDER_ROOT%/config/profile.d`**, which means Cmder runs cmd.exe at this path, and then goes to the real destination, e.g. %HOME%.  
  If the target path's disk is the same as %CMDER_ROOT%'s, it's no problem.

So, if you want to make a change, go set some init scripts to `cd` to the root of this disk. ;-)
~~~ cmd
:: %CMDER_ROOT%\config\user-profile.cmd
set "init_current_path=%cd%"
cd /d D:/
cd /d %init_current_path%
set init_current_path=
~~~
But it will not change `cmder /single "D:"`'s behavior.
- - -
`*.{bat|cmd}`s at `%CMDER_ROOT%/config/profile.d` are going to be init scripts, where we may know the reason for it becomes the last path Cmder worked at before program getting ready.

**Comment by DongZhe93** [comment]
new a file "user.bat" in "...cmder\config\profile.d" , It's ok!
```
cd /
```

**Comment by DongZhe93** [comment]
file **user_aliases.cmd**, add new line:
`
D:=cd /d D:/
`
