### ISSUE TITLE
text cursor can'nt align to the console's beginning 

### ISSUE THREAD

**Issue by dzb** [cmderdev/cmder#1305]
and there is no settings fix this. take a look.

<img width="592" alt="2017-03-14 5" src="https://cloud.githubusercontent.com/assets/148160/23904208/fbd78234-0901-11e7-87af-7b21ce6e316b.png">
<img width="592" alt="2017-03-14 6" src="https://cloud.githubusercontent.com/assets/148160/23904209/fbd88756-0901-11e7-8c8f-2b15eea86593.png">

**Comment by dzb** [comment]
Run the last cmder on windows 10 build 15055.

**Comment by dev-seahouse** [comment]
same problem here
![image](https://cloud.githubusercontent.com/assets/4751342/24068869/90a42d5c-0bd4-11e7-918d-3bd4aadd7ea1.png)

**Comment by dev-seahouse** [comment]
seem to have something to do with clink,
if i remove this from init.bat  
```bash
:: Run clink
"%CMDER_ROOT%\vendor\clink\clink_x%architecture%.exe" inject --quiet --profile "%CMDER_ROOT%\config" --scripts "%CMDER_ROOT%\vendor"
```
cursor goes to beginning

**Comment by lizy14** [comment]
Even more wired with wide characters.

Let's key-in four wide characters, with IME:

![image](https://cloud.githubusercontent.com/assets/9985286/24078638/dabbfabc-0cad-11e7-9f4d-a04153b8eb7f.png)

Now press Left Arrow three times:

![image](https://cloud.githubusercontent.com/assets/9985286/24078641/f9ecc2b8-0cad-11e7-9427-ceef03e7353b.png)

Now disable IME and press 'a':

![image](https://cloud.githubusercontent.com/assets/9985286/24078642/07a5ef88-0cae-11e7-9416-2fe231c936fc.png)

p.s. Disabling clink won't help.

**Comment by wikilike7** [comment]
same error in windows 10.15063 , Fast Ring

**Comment by SongRb** [comment]
same error in Windows 10.15063, Slow Ring

**Comment by dupu222** [comment]
powershell:
![image](https://cloud.githubusercontent.com/assets/13982466/24642520/645376a4-193a-11e7-813c-03a19e46eb83.png)

cmd:
![image](https://cloud.githubusercontent.com/assets/13982466/24642541/7d89f72e-193a-11e7-8232-b7f91833512c.png)

wsl zsh:
![image](https://cloud.githubusercontent.com/assets/13982466/24642555/a704f6f8-193a-11e7-8dbd-735a57bf064d.png)

wsl zsh  agnoster theme:
![image](https://cloud.githubusercontent.com/assets/13982466/24642588/e2c3c052-193a-11e7-967f-bc74c06ed945.png)
