### ISSUE TITLE
Aliases + Coloring Path don't work Win10 15052

### ISSUE THREAD

**Issue by gustavorlopez** [cmderdev/cmder#1306]
Windows 10 Insider Pro 15042.0 | cmder version 1.3.2
I copy my cmder folder from machine with Win10 Pro 14393 to laptop with win10 Insider 15042
* Aliases don't work
* Coloring path don't work

I download cmder again, but same problem.
![alias command](https://cloud.githubusercontent.com/assets/1809845/23904661/ab3ab3c0-0896-11e7-82da-43669e4e77b7.png)
![ls command](https://cloud.githubusercontent.com/assets/1809845/23904767/159eef06-0897-11e7-9225-c82c44889ab1.png)

**Comment by ihorzenich** [comment]
Do you have Clink installed globally?
Maybe it something similar to https://github.com/cmderdev/cmder/issues/1291

**Comment by gustavorlopez** [comment]
No. I don't have external Clink

**Comment by luantu** [comment]
I also met this problem too

**Comment by jerkovicl** [comment]
Getting the same error aswell

**Comment by archer0001** [comment]
This was fixed for me in 1.3.4 running on the fall creators update of win10.
