### ISSUE TITLE
How to pass DOSKEY alias to Cmder

### ISSUE THREAD

**Issue by insurgencymodscum** [cmderdev/cmder#1307]
Hello

I'm trying to do the following:

Pass a DOSKEY alias to Cmder.

In this case, in Total Commander's command line I run:

`do.cmder.cmd.bat smartgit`

I get the following error:

```
'smartgit' is not recognized as an internal or external command,
operable program or batch file.
```

If I pass "echo test", there's no error.

`do.cmder.cmd.bat echo test`

If I run "smartgit" in Cmder, the alias works.

---

My setup:

```
do.cmder.cmd.bat

...
start  %conemu% /loadcfgfile "%CMDER_ROOT%\config\ConEmu.xml" /cmd cmd /k "%CMDER_ROOT%\vendor\cmdercfg-init-clink-no.bat & %*"
...
```

---

So is there any way to make this work?

**Comment by glucas** [comment]
The short answer is no: doskey macros are limited in how they can be invoked. You probably want to change `smartgit` from an doskey alias to a bat file on your PATH.
