### ISSUE TITLE
Add WLS bash task

### ISSUE THREAD

**Issue by yveslange** [cmderdev/cmder#1312]
Hi, thanks for the beautiful work.

I spend few hours trying to make the cmder working with the new WLS (_Windows Linux Subsystem aka: Bash for Ubuntu for Windows -  windows 10_).

It seems that ConEmu automatically detects if WLS is installed and then creates a default `{bash}` task. But for cmder (and the default ConEmu.xml configuration) it uses the `../git-for-windows/bin/bash.exe`.

You should add a new task called: {bash:wls} or {bash:ubuntu} with the following content:

`%windir%\system32\bash.exe ~ -cur_console:pm:/mnt`

Best regards

**Comment by jwoglom** [comment]
Note: Running bash through cmder with these options breaks arrow keys handling in vim and other programs, and also causes odd issues while using screen and ssh.

**Comment by yveslange** [comment]
For an un-understood reason, if you don't use the following argument `-cur_console:pm:/mnt` you will have the mentioned problems.

After putting the argument `-cur_console:pm:/mnt`, the arrow problem (known to be in VIM) will disappear.

**Comment by jwoglom** [comment]
That's not working for me -- I still get the issue with arrow keys using your exact arguments.

**Comment by yveslange** [comment]
Did you use the tild `~` ? A lot of people were forgetting the tild and this is why it didn't worked.

**Comment by gmarian** [comment]
There was a bug filed for it. There's probably some gory details in that discussion:

https://github.com/Maximus5/ConEmu/issues/629

**Comment by ATL-Flaneur** [comment]
I'm on Windows 10 Pro, build 1703. Arrow keys are non-functional in vi after starting bash with $%windir%\system32\bash.exe ~ -cur_console:pm:/mnt$ but work fine with Emacs.

**Comment by BeanBagKing** [comment]
Here's what I discovered:
like @ATL-Flaneur, when I launched bash from a console (1703, ConEmu 170402, tilda and everything) arrow keys are non-functional in vim. However, when I opened a new bash console (Green plus dropdown-> bash -> bash), arrow keys work just fine. 

I've noticed in a lot of other threads there's a variety of reports, and I think this is the fundamental problem.  People are opening bash in different ways, and opening bash from a command window doesn't necessarily work.

Anyone found a way to type bash in a Cmder CMD window and have it work correctly?

**Comment by ATL-Flaneur** [comment]
The "green plus dropdown -> bash -> bash" route does give me functional arrow keys in vi. Didn't realize that was an option until @BeanBagKing post.

**Comment by Stanzilla** [comment]
Fixed in https://github.com/cmderdev/cmder/commit/91f5c5379a5cf20fcadd2d90456818cc3b245b74

**Comment by dustintheweb** [comment]
nano works fine, so at least we've go that

**Comment by PhlpMaxence** [comment]
I've managed to correct that bug by using {WSL:bash} task when opening new tab.
