### ISSUE TITLE
%ProgramFiles% in the Environment Path doesn't resolved for Shells in Cmder

### ISSUE THREAD

**Issue by osya** [cmderdev/cmder#1313]
When using %ProgramFiles% variable in the environment variable "Path" values. Then for regular PowerShell (without Cmder) this %ProgramFiles% correctly resolved to "C:\Program Files". But for PowerShell started from Cmder %ProgramFiles% doesn't resolved. To check environment variables values I used the following: `(Get-Childitem env:Path | Select-Object -Expand Value).Split(';')`

**Comment by Jackbennett** [comment]
%VARIABLE% Doesn't exist in powershell or the host program. 

For env variables you want;

type | example | value
-|-|-
process | $env:tmp | C:\Users\Jack\AppData\Local\Temp
process | [environment]::GetEnvironmentVariable('tmp', 'process') | C:\Users\Jack\AppData\Local\Temp
User | [environment]::GetEnvironmentVariable('tmp', 'user') | C:\Users\Jack\AppData\Local\Temp
machine | [environment]::GetEnvironmentVariable('tmp', 'machine') | C:\WINDOWS\TEMP
