### ISSUE TITLE
UNC paths are not supported

### ISSUE THREAD

**Issue by malashin** [cmderdev/cmder#1315]
As of v.1.3.2 starting **cmder** in or changing directory to UNC path is not supported with the default settings.

```bash
'\\RACKNODE\racknode'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.

C:\Windows
λ cd \\RAKCNODE\racknode
'\\RAKCNODE\racknode'
CMD does not support UNC paths as current directories.
```

This can be changed in ConEmu settings:
**Settings > Integration > ComSpec > Support UNC paths in cmd.exe (\\server\share\folder)**

But does not really work:
```bash
C:\Windows
λ cd \\RACKNODE\racknode\
'\\RACKNODE\racknode\'
CMD does not support UNC paths as current directories.
```

If you start **cmder** from UNC path directory after changing this setting, error message is gone and you are moved to profile.d directory for some reason:
```bash
D:\Documents\Tools\cmder\config\profile.d
λ
```

I'm not really familiar with **cmder** and not sure what causes this behavior.
**ConEmu** does not have any of those problems if UNC path are enabled in Windows.

**ConEmu** has this setting enabled by default unlike **cmder**.
**Settings > Integration > ComSpec > Support UNC paths in cmd.exe (\\server\share\folder)**

**Comment by gliptak** [comment]
I checked ```Support UNC paths in cmd.exe (\server\share\folder)```, but it shows ```CMD does not support UNC paths as current directories.``` when trying to ```cd`` or open UNC location from Explorer.

I found workaround using ```pushd``` described at https://mypkb.wordpress.com/2007/02/01/how-to-deal-with-cmd-does-not-support-unc-paths-as-current-directories/

**Comment by izimbra** [comment]
I'm also experiencing the same issue on Windows 7 with the setting enabled.

@Stanzilla please re-open.

**Comment by daxgames** [comment]
This is not a Cmder issue.  Cmd.exe does not support unc paths as current directories.  You can't `cd \\server\path`.  You need to use `pushed \\server\path` that will temporarily map a drive to that path then change to it.

This is not something that can be fixed by us.

**Comment by izimbra** [comment]
@daxgames @Stanzilla ok, got it, I also found this workaround. By the way, it is `pushd`, not `pushed`. I guess the **Support UNC paths** setting should then be removed, it is misleading.

**Comment by izimbra** [comment]
@daxgames, thanks for the detailed explanation!
