### ISSUE TITLE
Environmental variables are not reloaded on new console

### ISSUE THREAD

**Issue by gsbabil** [cmderdev/cmder#132]
> Cmder version: 1.1.3
> Windows version: 8.1 (64bit)

**To reproduce:**
- Run Cmder (it creates the first console). Add a user environmental variable (e.g. TEST=1234)
- Create a new console inside the same Cmder session and run `echo %TEST%`. It will print `%TEST%` meaning the variable doesn't exist
- Restart the whole Cmder session (kill and start over). Now run `echo %TEST%`. It will print `1234` meaning that the `%TEST%` variable exists for the session this time.

**Comment by Chigogo** [comment]
@samvasko I use setx both in CMD and Cmder, I get that whether I start a new console in current session or I restart Cmder session, the result is the same that Cmder wont refreash user-level's variable.

**Comment by joeflack4** [comment]
Restarting Windows10 fixed for me.
