### ISSUE TITLE
[Q] How to add function to user-profile.cmd

### ISSUE THREAD

**Issue by szachara** [cmderdev/cmder#1321]
Hi, first I want thx, I have discovered cmder few days ago and 🔥 

I'm using this in `.bashrc`:
```
# Laravel Ide Helper Regenerate
ihr() {
    php artisan cache:clear
    php artisan ide-helper:generate
    php artisan ide-helper:meta
    php artisan optimize
}
```

How can I rewrite this and use it in cmder? with cmd.exe shell

**Comment by glucas** [comment]
If you want to run custom commands in a cmd.exe shell, you'll need to write a batch (.bat or .cmd) file and put it somewhere on your PATH.

**Comment by szachara** [comment]
Ok, thx, can be closed.
