### ISSUE TITLE
"Unable to create the ConEmu Process!" when running cmder.exe

### ISSUE THREAD

**Issue by jonofan** [cmderdev/cmder#1322]
Running vendor\conemu-maximus5\ConEmu.exe is working correctly, though with the ConEmu icon rather than the cmder icon, as you would expect.

Windows 10 Enterprise. 

![image](https://cloud.githubusercontent.com/assets/13552974/24470551/17e21f20-1474-11e7-89ed-5697cc1e2882.png)

**Comment by codebymikey** [comment]
+1

**Comment by antivitla** [comment]
I had the same when accidentally tried to start conemu as admin through explorer menu settings->compatibility>start as admin. Reinstall did not help.

So i go to regedit and by F3 find all conemu and cmder entries and remove them. Then cmder works again.

Actually i think critical thing was to remove in regedit key that relates to starting conemu as admin. 

Try to wipe in regedit everything that relates to cmder and conemu (few entries).

**Comment by frtru** [comment]
I am using the zipped version from the cmder site. I had this issue and did what @antivitla suggested, but I was still having the issue afterwards. I had to delete the whole cmder folder and unzip again and start from scratch my setup. Hope it helps.

**Comment by onebit0fme** [comment]
Having the same issue.

**Comment by pyrsmk** [comment]
+1

**Comment by pyrsmk** [comment]
Solved the problem by removing a key related to running ConEmu as admin (not Cmder) in `HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers`. Also, I've created a key to properly run Cmder as admin (useful when run from explorer right-click context), with the Cmder executable path as key, and `~ RUNASADMIN` as value.

**Comment by MrkGrgsn** [comment]
I had this problem on Win 10 Enterprise immediately after installing 1.3.2 but only after doing the auto update for ConEmu. During the update 7zip gave an error: "Can not open output file : Access is denied. : C:\...\CMDer\vendor\conemu-maximus5\ConEmu64.exe"

I resolved it by downloading the portable stable zip of ConEmu and unzipping to `vendor\conemu-maximus5`, replacing the existing version entirely. I note that when it was broken `ConEmu64.exe` was missing from this folder but in re-installing ConEmu it was created.

**Comment by iulo** [comment]
@MrkGrgsn thanks for your comment. It save my day.
