### ISSUE TITLE
still have an incomplete operations confirmation dialog

### ISSUE THREAD

**Issue by giuem** [cmderdev/cmder#1323]
```
cmder version: v1.3.2
using {bash::bash}

$ git --version
git version 2.11.0.windows.1

```
![gif](https://cloud.githubusercontent.com/assets/8272989/24503798/2fd00800-1586-11e7-9829-b84687499715.gif)

**Comment by Brandon-Huang** [comment]
I have this similar issue. I use mini and with windows git

ConEmu 161022[64]

$ git --version
git version 2.12.2.windows.1

**Comment by daxgames** [comment]
This us not a cmder issue.  Report it to conemu devs.

**Comment by eliveikis** [comment]
I searched conemu issues and did not find anything similar. I'm happy to enter a new bug there but I was unable to reproduce in conemu.

I downloaded conemu windows latest, opened git bash - referencing the same windows git installation that my cmder bash is using, closed the app and there was no warning popup about incomplete operations.

**Comment by uzabila** [comment]
Still have the same issue

**Comment by daxgames** [comment]
As stated by @Brandon-Huang Using Cmder mini and Git for Windows has the same issue.

The ONLY files in Git for Windows that are added/customized by Cmder are:

```
vendor/git-for-windows/etc/profile.d/cmder.sh
vendor/git-for-windows/etc/profile.d/git-prompt.sh
```

If I remove `vendor/git-for-windows/etc/profile.d/git-prompt.sh` and replace Cmders `vendor/git-for-windows/etc/profile.d/git-prompt.sh` with `vendor/git-for-windows/etc/profile.d/git-prompt.sh.bak` from Cmders embedded Git for Windows Portable install the same warning exists.

This is basically ConEmu and Git for Windows.

This is not a Cmder issue.
