### ISSUE TITLE
Aliases don't work in batch files

### ISSUE THREAD

**Issue by Razor-13** [cmderdev/cmder#1326]
Is there any way to make aliases work in batch files?

**Comment by Razor-13** [comment]
Using separators like & also doesn't work to execute commands in order, it recognizes the first alias then the second either doesn't work or isn't recognized. E.g.:
`ytquality=youtube-dl -F $*`
Tried also $1, "$1 $T", "$* $T" with no luck.

**Comment by jrappen** [comment]
@Razor-13 Perhaps your issue is a duplicate of #1325?

**Comment by Razor-13** [comment]
@jrappen 
I'm on Windows 7 x64 SP1 and the aliases do work, I'm talking about them working in batch files or after operators (&, &&, ||, etc)

**Comment by glucas** [comment]
Assuming your shell is cmd.exe, then aliases are a wrapper around the [doskey](http://www.microsoft.com/resources/documentation/windows/xp/all/proddocs/en-us/doskey.mspx) command  and you are limited to how doskey macros work -- what you are trying to do is not supported.

From the doskey documentation: 
> To run a macro, type the macro name starting at the first position on the command line ... 
> You cannot run a doskey macro from a batch program.

You may want to move those aliased commands to their own bat files on your PATH -- that way you can still use them from the shell, but also have more flexibility in how they can be called.
