### ISSUE TITLE
Remove item from Create new Console

### ISSUE THREAD

**Issue by szachara** [cmderdev/cmder#1329]
How to remove item from select's popup in Create new Console modal dialog?

I tried right click on title and clear history... but didn't help.

![2017-04-01](https://cloud.githubusercontent.com/assets/86900/24578441/b9905a44-16e0-11e7-8410-57fe3fa94a29.png)

**Comment by cowai5** [comment]
How did you solve this problem?

**Comment by silverqx** [comment]
This is normal behavior, I think the author answered me, that it's last opened session? I don't remember exactly.

**Comment by cowai5** [comment]
I see. thank you!
