### ISSUE TITLE
Possible problem with Arrows in VIM

### ISSUE THREAD

**Issue by xnosx** [cmderdev/cmder#1330]
![e388](https://cloud.githubusercontent.com/assets/3417231/24588654/b7e83cce-17cc-11e7-92dc-14cae86da49d.JPG)

The arrows of the cursor position do not work correctly, I am still doing more tests, but editing with a VIM text file when selecting the arrows gives me error, if I find that the problem is another I confirm immediately.

Regards!

**Comment by xnosx** [comment]
Confirmed! in PowerShell everything work fine!

The problem is in Cmder!

![powershell](https://cloud.githubusercontent.com/assets/3417231/24588690/abb39e48-17cd-11e7-9bcb-797fce73899a.JPG)

**Comment by daxgames** [comment]
I use vim daily in cmder using cmd, powershell, and git-bash shells daily with zero issues.  I don't think the issue is in cmder.

What shell are you using when you have an issue?

**Comment by xnosx** [comment]
Hello @daxgames 

I use the bash console {bash::bash as Admin} but I have tried all versions!

I use version of ConEmy 161206[64]{Stable}

What exact version are you using?

Can you compress it and send it to me? So I can compare it to the one I'm using!

Thanx!

**Comment by fztfztfztfzt** [comment]
Hello @xnosx 
I can use arrows in vim in windows using cmder, but I have the same situation with yours when I use arrows in vim in bash on ubuntu on windows. 
I have found the solution online, I hope it can help you too.
I use this command to start the bash on ubuntu on windows
`%windir%\system32\bash.exe ~ -cur_console:p:n`
![image](https://cloud.githubusercontent.com/assets/9301116/24706907/23f56878-1a44-11e7-8d3c-be2c3a149872.png)

**Comment by xnosx** [comment]
Hello @fztfztfztfzt 

Ups! I think that I havent the bash.exe file on my system32 directory!, What version of Windows do you have? Did you install any additional packages besides Cmder?

Thanks!

**Comment by mrRosset** [comment]
@xnosx https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/

**Comment by xnosx** [comment]
@fztfztfztfzt  and @mrRosset thank you! merge of both answers fix my problem!

Cheers!

**Comment by iromise** [comment]
@fztfztfztfzt , this really work. But how can I open the cmder in the dir I am just in and show the path just I am in?(the default works fine, but when modified, it just jumps to the ~). Is there any parameter to set this?
