### ISSUE TITLE
Cmder start slowly after Node.js installed

### ISSUE THREAD

**Issue by fztfztfztfzt** [cmderdev/cmder#1332]
I can start cmder quickly before, but after I installed Node.js, cmder start slowly.
When I click the cmder.exe, the tab name will first become node.exe. And after about 5 seconds, it start successfully.
![image](https://cloud.githubusercontent.com/assets/9301116/24707020/9f6e3f98-1a44-11e7-9863-f76bb02dba7f.png)
We can see in the picture that the tab name become node.exe

**Comment by affanshahid** [comment]
Similar issue

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)
