### ISSUE TITLE
Cannot use Ctrl+Backspace to delete a word in Bash on Ubuntu on Windows

### ISSUE THREAD

**Issue by Gelio** [cmderdev/cmder#1336]
I've recently added Bash on Ubuntu on Windows as a task for Cmder:
```
%windir%\system32\bash.exe ~ -cur_console:p
```
Everything works fine except for the fact, that pressing Ctrl+Backspace results in a small lag in the console and nothing being deleted, whereas in other consoles (regular cmdPowershell or bash, all ran under Cmder) it works fine and deletes the last word behind the cursor.

Is there an option to enable Ctrl+Backspace for Bash on Ubuntu on Windows? I'd be satisfied with this command just removing a single character instead of lagging the window.

**Comment by JordanRobinson** [comment]
I've noticed if you turn this setting 

![image](https://cloud.githubusercontent.com/assets/1202911/25073944/5910d63e-22e9-11e7-8881-e683ec3cd35e.png)

It seems to fix the problem, for bash, at least.

**Comment by Gelio** [comment]
@JordanRobinson Thanks for responding!

Turning it off does work, but not in the way I would expect it to. It seems to delete a bunch of words at a time, sometimes even restores letters and appears to be unpredictable overall, at least to my mind. Not only that but then Ctrl + Backspace doesn't work in regular Cmder shell.

**Comment by JordanRobinson** [comment]
Ah you're right, it looks like I was a little too hasty to celebrate. After checking I'm also getting the issue in base ConEmu (170402).

**Comment by rlabrecque** [comment]
This worked for me before updating to Win10 1703 (Creators Update) and the latest ConEmu, I'm not sure which one broke it, but yeah :(

**Comment by masaeedu** [comment]
I'm seeing this issue in regular ConEmu as well, I don't think this is cmder specific.

**Comment by Gelio** [comment]
@masaeedu For me the regular ConEmu is working just fine. The only consoles that have this issue are Bash on Ubuntu on Windows and mintty.

**Comment by Gelio** [comment]
@masaeedu Sure, it is probable, yet I didn't know where to post this issue. Thanks for clarifying.

**Comment by rlabrecque** [comment]
Does this still happen with the latest preview build of ConEmu?

**Comment by FooBarrior** [comment]
i found that alt+backspace starts working instead

**Comment by Brunni132** [comment]
FYI a terrible hack that works is remap Ctrl+Backspace to Alt+Backspace. Still this should be fixed, but in the meantime if your fingers really hate that Alt+Backspace thing (which doesn't exist on the standard cmd or any shell) you can go this way.

![image](https://user-images.githubusercontent.com/9025750/33974118-0a5f4120-e0ca-11e7-9a7a-0b68e5f36bec.png)

**Comment by alexandr-san4ez** [comment]
@Brunni132 nice fix!

**Comment by natewaldrop** [comment]
I have found that leaving the cmder defaults - I will open to cmd.exe {cmd::Cmder}. After initialization, I am unable to use CTRL+Backspace. 
It is annoying, but using ALT+Backspace does the trick.
I stumbled on a work-around tonight - if you type
`cmd`
and then immediately
`exit`
CTRL+Backspace functionality works.

**Comment by cyberguest** [comment]
thanks,
updated Tasks->{cmd:Cmder} to: cmd /k "%ConEmuDir%\..\init.bat" & cmd & exit

**Comment by icharge** [comment]
> I have found that leaving the cmder defaults - I will open to cmd.exe {cmd::Cmder}. After initialization, I am unable to use CTRL+Backspace.
> It is annoying, but using ALT+Backspace does the trick.
> I stumbled on a work-around tonight - if you type
> `cmd`
> and then immediately
> `exit`
> CTRL+Backspace functionality works.

Not worked for me  :(

**Comment by marklauyq** [comment]
> FYI a terrible hack that works is remap Ctrl+Backspace to Alt+Backspace. Still this should be fixed, but in the meantime if your fingers really hate that Alt+Backspace thing (which doesn't exist on the standard cmd or any shell) you can go this way.
> 
> ![image](https://user-images.githubusercontent.com/9025750/33974118-0a5f4120-e0ca-11e7-9a7a-0b68e5f36bec.png)

Works like a charm

**Comment by JohnnyFun** [comment]
I just installed on new machine and it took me a bit to figure out that in the "Keys & Macro" section, you need to scroll down to the Macro types and select an un-set macro and mod that. There's doesn't appear to be an add macro button or anything like that.

**Comment by flatline-studios** [comment]
Why was this closed? It's still broken?

**Comment by stroj943** [comment]
> > FYI a terrible hack that works is remap Ctrl+Backspace to Alt+Backspace. Still this should be fixed, but in the meantime if your fingers really hate that Alt+Backspace thing (which doesn't exist on the standard cmd or any shell) you can go this way.
> > ![image](https://user-images.githubusercontent.com/9025750/33974118-0a5f4120-e0ca-11e7-9a7a-0b68e5f36bec.png)
> 
> Works like a charm
Thank you! The only solution that worked for me.

**Comment by Anvesh965** [comment]
1. Create .inputrc in ~/ directory
2. add this to the file `"\C-h": backward-kill-word`
3. save and reopen git bash

**Comment by chrisant996** [comment]
> 1. Create .inputrc in ~/ directory
> 2. add this to the file `"\C-h": backward-kill-word`
> 3. save and reopen git bash

@Anvesh965 no, that changes the binding for <kbd>Backspace</kbd>, which will be unexpected and probably very frustrating.

The request was to make a binding for <kbd>Ctrl</kbd>-<kbd>Backspace</kbd>.
