### ISSUE TITLE
Any IntelliJ IDE cursor bug 

### ISSUE THREAD

**Issue by DavidArutiunian** [cmderdev/cmder#1337]
After upgrading to Windows 10 Creators Update threre is extra space in left side of cursor, when using cmder inside IDE, but only under certain circumstances. I'll try to show you it with a gif. 

[Click to see a gif (imgur)](https://i.imgur.com/f8J6CI6.gif)

I also checked previous versions of IDEs(current 2017.1) and still bug exists, so I think thats not porblem of IDEs, but Windows.

On the other hand, cmder console itself doesnt have this bug in all window sizes. Is threre any solution of how to fix that?

P.S. cmd.exe doesn't have this bug too.

**Comment by mu-yu** [comment]
Cmder have the same bug in Windows 10 Creators Update, cmd.exe is OK

**Comment by mayiwei** [comment]
The same,how to fix it?

**Comment by DavidArutiunian** [comment]
@mu-yu @mayiwei the only way I found rolling back to previous version of Windows

**Comment by iainheng** [comment]
Can confirm the same problem after upgraded to Windows 10 Creators Update. An extra space before the text cursor. Very annoying.

**Comment by rillomas** [comment]
Starting bash in cmder and exiting immediately somehow fixes this issue temporarily

**Comment by IceDong** [comment]
same bug..

**Comment by IceDong** [comment]
@DavidArutiunian I found way to fix it,In Settings->Environment insert 'chcp 65001';

**Comment by iainheng** [comment]
@IceDong Thanks. Just tried your fix and it works. Thank you. 

`chcp 65001`

**Comment by DavidArutiunian** [comment]
@IceDong just to make clear for other people, this command `chcp 65001` changes the encoding of bash to `UTF-8`, right?
