### ISSUE TITLE
tree -L 3: too many parameters

### ISSUE THREAD

**Issue by waldens** [cmderdev/cmder#1338]
```bash
d:\Downloads
λ tree -L 3
too many parameters - 3
```
Seems still using windows commond `tree`. How to use `tree` like in Linux?

**Comment by daxgames** [comment]
@waldens not sure if tree is included in cmder.  But if it is you would need to use a fully qualified path to the tree command as cmder prefers windows binaries by default in the path.  You could modify the task that starts cmder sessions to prefer *nix binaries.  See the `/nix_tools` argument in the [readme.md](https://github.com/cmderdev/cmder#command-line-arguments-for-initbat)
