### ISSUE TITLE
display error with non-ASCII characters on windows 1703

### ISSUE THREAD

**Issue by Himyth** [cmderdev/cmder#1339]
after upgrade to windows creator update which is version 1703, the display is no longer right.

when i trying to ls the directory, it output `?` instead of the non-ASCII characters, which is behave the same for both Chinese and Japanese. but `dir` command work fine.
![image](https://cloud.githubusercontent.com/assets/7251473/24833652/6a9a4102-1d02-11e7-8826-c5b0ea084f63.png)

here is the output byte sequence of both command. I test this in another laptop with windows 10 version 1607, the output byte sequences are identical, and display is right:
![image](https://cloud.githubusercontent.com/assets/7251473/24833682/835f1be4-1d03-11e7-9d5a-a50e7d646c6a.png)

and if i type Chinese directly to the cmder, every character i type, the cursor will go right a little bit more than character's width, like they are getting fatter, which is not. in the following screenshots, the white-space between Chinese characters and cursor is not manually added. it just come out of nowhere.
![image](https://cloud.githubusercontent.com/assets/7251473/24833697/e27c2e46-1d03-11e7-94a2-b840a6ea7361.png)
![image](https://cloud.githubusercontent.com/assets/7251473/24833703/10a7f7e6-1d04-11e7-8f06-41e44ff03213.png)
![image](https://cloud.githubusercontent.com/assets/7251473/24833706/425ddae4-1d04-11e7-9bbb-9a5dd3e9ad87.png)

it seems these has something to do with the display, because if i vim some file and type Chinese, despite the display all goes wrong, the content stays correct.

the problem seems to be ConEmu.exe, i got the same result if i run ConEmu.exe directly. any ideas?

**Comment by tszyjie** [comment]
u need  
`chcp 65001`

**Comment by Himyth** [comment]
no luck with that... @tszyjie

**Comment by tszyjie** [comment]
![snipaste20170413_112320](https://cloud.githubusercontent.com/assets/11535520/24988936/a2042112-203b-11e7-89c8-bfbd8bf1e4c8.png)

**Comment by tszyjie** [comment]
![default](https://cloud.githubusercontent.com/assets/11535520/24989036/41d8c7f6-203c-11e7-9aa3-e8d7a6a1ae13.png)

**Comment by tszyjie** [comment]
![snipaste20170413_112832](https://cloud.githubusercontent.com/assets/11535520/24989055/5ddeb1ea-203c-11e7-8935-b6c713d0aa5e.png)
@Himyth

**Comment by Himyth** [comment]
thx! that works with the display. but type Chinese still looks fatter than it should be
![image](https://cloud.githubusercontent.com/assets/7251473/24989088/bc6e3dfc-203c-11e7-9dc7-a78ddcd8bd2b.png)

i think maybe it has something to do with the new render mechanism in 1703?

**Comment by tszyjie** [comment]
default:
![snipaste20170413_114426](https://cloud.githubusercontent.com/assets/11535520/24989387/e64f7eb8-203e-11e7-999b-b75881b4415d.png)
but 
after execute `chcp 65001`
![snipaste20170413_114455](https://cloud.githubusercontent.com/assets/11535520/24989388/e651a6b6-203e-11e7-91fe-e0aa2eeb1954.png)

By the way:
![18](https://cloud.githubusercontent.com/assets/11535520/24989469/6be59fda-203f-11e7-9c03-80389cf207c4.png)

**Comment by tszyjie** [comment]
or  try to change 'Main console font'
![09](https://cloud.githubusercontent.com/assets/11535520/24989561/1706d97e-2040-11e7-9987-cedc69d158d1.png)

https://1drv.ms/u/s!AhgDJ1s9sY7dgbpplOA4ZVuCBorlDA 
@Himyth

**Comment by Himyth** [comment]
switching to powershell, and every thing work now! thx~

**Comment by jrappen** [comment]
Free CJK fonts:

* <https://www.google.com/get/noto/>
  * Noto Sans CJK (Adobe calls it "Source Han Sans")
  * Noto Serif CJK (Adobe calls it "Source Han Serif")

**Comment by 40huo** [comment]
Same problem and changing font doesn't work.

![](http://i2.muimg.com/567571/a7bef7b014b3ed45.png)

**Comment by victor97** [comment]
Same problem in ConEmu. 
I solved it by using the old version console.
![image](https://cloud.githubusercontent.com/assets/9767416/25323014/8bb2ec7a-28ee-11e7-873a-f8f9989fa849.png)

**Comment by Himyth** [comment]
@victor97 perfect solution! thx

**Comment by kevinzfjiang** [comment]
@victor97 
that would make not working on bash on ubuntu feature:

`Unsupported console settings. In order to use this feature the legacy console must be disabled.`

**Comment by amazecc** [comment]
- When i open it with powershell, it shows that this is what i do not like
![Uploading QQ截图20170531105644.jpg…]()
- can it show with this and solve the problem?
![qq 20170531105600](https://cloud.githubusercontent.com/assets/19689743/26614058/9257678a-45f0-11e7-9704-83359be2ebb2.jpg)

**Comment by amazecc** [comment]
- When i open it with powershell, it shows that this is what i do not like
![qq 20170531105644](https://cloud.githubusercontent.com/assets/19689743/26614122/0181f468-45f1-11e7-80d0-3233118419be.jpg)
- can it show with this and solve the problem?
![qq 20170531105600](https://cloud.githubusercontent.com/assets/19689743/26614104/e0eb600e-45f0-11e7-92c8-bf8ee51821d1.jpg)

**Comment by amazecc** [comment]
- It can enter the Chinese, but can also delete the "$", enter the Chinese double quotation marks, delete the text will be a problem
![qq 20170531110648](https://cloud.githubusercontent.com/assets/19689743/26614254/c0d050bc-45f1-11e7-893f-4be15a7cd133.jpg)
![Uploading QQ截图20170531110706.jpg…]()

**Comment by amazecc** [comment]
- It can enter the Chinese, but can also delete the "$", enter the Chinese double quotation marks, delete the text will be a problem
![Uploading QQ截图20170531110706.jpg…]()

**Comment by hijkzzz** [comment]
mark

**Comment by tiakia** [comment]
mark

**Comment by lsh6372** [comment]
mark

**Comment by jdhao** [comment]
Do not produce noise by using mark @hijkzzz , @tiakia , @lsh6372

**Comment by tiakia** [comment]
> Do not produce noise by using mark @hijkzzz , @tiakia , @lsh6372

I am sorry, I have deleted it.

**Comment by windicold** [comment]
> * It can enter the Chinese, but can also delete the "$", enter the Chinese double quotation marks, delete the text will be a problem
>   ![qq 20170531110706](https://cloud.githubusercontent.com/assets/19689743/26614399/bd363e0c-45f2-11e7-8ec3-2da3418a70c9.jpg)
>   ![qq 20170531110648](https://cloud.githubusercontent.com/assets/19689743/26614400/c222a69e-45f2-11e7-9566-51c6967c1c19.jpg)

try to excecute `chcp 936`, and then seems to solve the problem you mentioned in deleting text mixed with non-ASCII chars.
so just edit the cmder startup config: _**user-profile.cmd**_, add `chcp 936>nul` 
if not use cmd and bash or anyelse, modify the custom task startup command:
- `cmd /c [task_command]` -> `cmd /c "chcp 936>nul & [task_command]"`

![task startup command](https://i.postimg.cc/V68Szk7t/snipaste-20230921-054229.png)
