### ISSUE TITLE
Extra space before cursor

### ISSUE THREAD

**Issue by fztfztfztfzt** [cmderdev/cmder#1342]
![bug](https://cloud.githubusercontent.com/assets/9301116/25003326/77c82a7e-2081-11e7-8eff-d864358a65e2.png)
There is an extra space before the cursor, how to fix this bug?
This problem only occur when I open cmd.exe, but there is no extra space when I open powershell with cmder.

**Comment by Jeff-sjtu** [comment]
Startup -> Environment
Then add <code>chcp 65001</code>

**Comment by Jeff-sjtu** [comment]
Startup -> Environment
Then add <code>chcp 65001</code>
![image](https://cloud.githubusercontent.com/assets/15179660/25006126/3f551be0-208e-11e7-94f9-e565621445d7.png)

**Comment by fztfztfztfzt** [comment]
@Jeff-sjtu Thank you. Your answer fix my problem

**Comment by phpcyy** [comment]
@Jeff-sjtu I have take your method. But When I use `ssh` command, this problem will reappear. How can I fix it ? 
![_20170419105729](https://cloud.githubusercontent.com/assets/13944592/25161539/2659174e-24ef-11e7-8f0c-270732994894.png)

**Comment by ZetaoYang** [comment]
@fztfztfztfzt hi, this is Windows 10 bug, please upgrade to OS version 15063.332 .

**Comment by GeeKidult** [comment]
OS: Windows 10
Change the original command prompt λ to other characters in file cmder/vendor/clink.lua line 51

// before fixing
local lambda = "λ"

// after modification
local lambda = ">>"

**Comment by daxgames** [comment]
Don't edit clink.lua.  There are other BETTER ways.  search for prompt.lua
