### ISSUE TITLE
is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by copdips** [cmderdev/cmder#1343]
Hello,

I tried to launch zip version of cmder from an company 2012R2 server.
The sysadmin changed to original cmd.exe in order to have a custom CMD banner and prompt. The sysadmin also change the UI of the windows to red, which means every window even the system bar of the server is shown in red.

When I opened cmder.exe, I got following messages, and at last I got the cmder prompt, and it works.

There're 5 errors on " is not recognized as an internal or external command,
operable program or batch file.", are they important ? 

There's also a message about : "The filename, directory name, or volume label syntax is incorrect.", that I've no idea at all.

Please find below what I see when I start cmder.exe : 

Thx.

=====================================================
WARNING :
- You are connected to a Production environnement
- All changes must be declared before any actions
- Change management rules should be strictly followed
- You must have a formal request and operational procedures.
=====================================================
Found old git version in "C:\Users", but not using...
Found old git version in "C:\Users", but not using...
Found old git version in "C:\Users", but not using...
Found old git version in "C:\Users", but not using...
Found old git version in "C:\Users", but not using...
Found old git version in "C:\Users", but not using...

Found old git version in "C:\Users", but not using...
The filename, directory name, or volume label syntax is incorrect.
'"D:\Tools\cmder\config\profile.d\WARNING"' is not recognized as an internal or external command,
operable program or batch file.
'"D:\Tools\cmder\config\profile.d\-"' is not recognized as an internal or external command,
operable program or batch file.
'"D:\Tools\cmder\config\profile.d\-"' is not recognized as an internal or external command,
operable program or batch file.
'"D:\Tools\cmder\config\profile.d\-"' is not recognized as an internal or external command,
operable program or batch file.
'"D:\Tools\cmder\config\profile.d\-"' is not recognized as an internal or external command,
operable program or batch file.
'"D:\Tools\cmder\config\profile.d\====================================================="' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\me
(servername) λ

**Comment by sekti92** [comment]
i got the same issue, it's detected npm but did not recognizing sublime text
![capture](https://cloud.githubusercontent.com/assets/14885417/25083854/9f002e48-2383-11e7-89ae-8fdc9216deff.PNG)

**Comment by mollman** [comment]
Aliases defined via doskey appear to be broken under cmder if you're running Windows version 1703 (Creators update) that's rolling out now. See https://github.com/cmderdev/cmder/issues/1348. 

Doesn't look like the issue @copdips is experiencing, but does look like what @sekti92 is seeing.

**Comment by Alzy** [comment]
Has this been resolved in any way? I am running windows version 1809 and this issue is still present.

**Comment by daxgames** [comment]
There is nothing to fix.  This is not a cmder issue.  If you have an issue open one with as much detailas possible and we will look at it.
