### ISSUE TITLE
Once again about posh-git module.

### ISSUE THREAD

**Issue by illusive-man** [cmderdev/cmder#1345]
Until the last update everything was working perfectly, but after the update cmder's Power Shell (both admin and non-admin consoles) keep telling me to install posh-git, despite the fact it's already installed. I install it again but cmder still says "WARNING: Missing git support, install posh-git with 'Install-Module posh-git' and restart cmder" yet it shows changed files count string. Alas, after restart it shows posh-git no more and displays above mentioned warning text all over again. 

I saw couple closed tickets on the same matter, but there was no solution at all.

**Comment by illusive-man** [comment]
Self service)).
For those experiencing the same issue I was describing above, just type "Update-Module posh-git" and hit Enter. Voila, posh-git is working again! (This method is for already installed but not working module).

P.S. If it doesn't work, try execute "Import-Module YourHomeDir\Documents\WindowsPowerShell\Modules\posh-git\0.6.1.20160330\posh-git.psd1" before updating. This will work if you installed posh-git with old PSGet.

**Comment by Bigpet** [comment]
None of the solutions worked for me.

I had to open a powershell admin prompt outside of cmder and use `Install-Module posh-git` there.
Opening a powershell admin prompt inside cmder did not work for me.

**Comment by dahlbyk** [comment]
You should be able to `Install-Module posh-git -Scope CurrentUser` without an admin prompt.

**Comment by aaronmorgan** [comment]
If you want to use it without `posh-git`, but still using cmder's profile.ps1, edit the `''%ConEmuDir%\..\profile.ps1'''` file and remove/comment the `checkGit($pwd.ProviderPath)` instruction from line 105; and associated `checkGit()` and `Import-Git()` methods for completeness.

**Comment by orhanmaden** [comment]
> If you want to use it without `posh-git`, but still using cmder's profile.ps1, edit the `''%ConEmuDir%\..\profile.ps1'''` file and remove/comment the `checkGit($pwd.ProviderPath)` instruction from line 105; and associated `checkGit()` and `Import-Git()` methods for completeness.

Link to SO answer: https://stackoverflow.com/a/47188927/1912609
