### ISSUE TITLE
Emoji in Cmder - what am I missing?

### ISSUE THREAD

**Issue by arieljannai** [cmderdev/cmder#1347]
Hi,

I'm trying to use unicode and emoji's in Cmder, but I just get question marks. What should I set to make it work? any `chcp` code? some other setting?
Specifically on the default cmd that opens with Cmder.

Thanks!

**Comment by asternaut** [comment]
As far as I can tell, Cmder doesn't support emojis yet. See: https://github.com/cmderdev/cmder/issues/642

**Comment by arieljannai** [comment]
Cmder is based on ConEmu, and ConEmu support emojis with simple glyphs (black & white, not the colorful ones).
https://github.com/Maximus5/ConEmu/issues/988#issuecomment-285858633

**Comment by JohnChan1017** [comment]
You can use 【Windows Terminal】 https://apps.microsoft.com/detail/9n0dx20hk701?hl=en-us&gl=CN

**Comment by daxgames** [comment]
Or just sownload the unreleased wt builds that have Windows terminal already.

https://github.com/cmderdev/cmder/actions/runs/10471496494#artifacts
