### ISSUE TITLE
Alias not working 

### ISSUE THREAD

**Issue by sekti92** [cmderdev/cmder#1348]
I tried to run sublime text using cmder; however did not work. 
What wrong on my aliases sir?
![capture](https://cloud.githubusercontent.com/assets/14885417/25116047/8052305c-2434-11e7-8799-935b2800d3d8.PNG)

**Comment by maxshlain** [comment]
Happens for me too. All aliases stopped working on 161206 latest stable

**Comment by archer0001** [comment]
doskey /macros shows all aliases exist for me, they're just not usable.
![image](https://cloud.githubusercontent.com/assets/8215860/25130595/b7fa65a2-2410-11e7-9dd9-ab07b450b548.png)

**Comment by Tomcat9** [comment]
Did you guys recently get the new Windows 10 Creators Update (Version 1703)? Maybe that's the issue.

**Comment by archer0001** [comment]
Yes, and this failure happened after that.  I tested using doskey in a standard cmd.exe window and it appears to work there.

**Comment by maxshlain** [comment]
@Tomcat9 Yep, installed this morning

**Comment by mollman** [comment]
This repros for me after update to Windows 1703 as well. Worked fine yesterday with the same cmder install under Windows 1607. I'm able to use doskey to define the same macros in a regular cmd shell and they work; manually defining them using doskey in cmder as did @archer0001 they do not work. 

I also tried calling doskey in user-profile.cmd with no luck either.

**Comment by archer0001** [comment]
@mollman Thank you!  Am now following #1325 as well.

**Comment by sekti92** [comment]
@Tomcat9 yes, i installed 2 days ago

**Comment by Beej126** [comment]
[linking to the Clink fix for this](https://github.com/mridgers/clink/pull/464)
