### ISSUE TITLE
Cmder slow when used over Remote Desktop?

### ISSUE THREAD

**Issue by needfulthing** [cmderdev/cmder#1349]
I noticed that cmder reacts unusually slow when used in a Windows remote desktop connection. Does anyone know why?

**Comment by DRSDavidSoft** [comment]
Tested on several RDP instances, it doesn't look slow at all to me. If you use a VPS, it could have lower resources than expected, or have more CPU consumption.

If it's still slow for you, please disable some ticks at *Experience* tab of RDP, see if that helps.
<img width="305" alt="rdp_disable" src="https://user-images.githubusercontent.com/4673812/36928988-7b9bbf1c-1ea0-11e8-8e67-31ef04e5b28c.png">

**Comment by needfulthing** [comment]
Thank you for the answer. I couldn't reproduce a performance problem anymore in the last months. Still there is this weird problem with the red GIT font being scrambled when displayed via RDP. But this is another ticket. Cheers.

**Comment by DRSDavidSoft** [comment]
@Stanzilla could you close this issue?
