### ISSUE TITLE
Extra space before cursor when ZSH_THEME enabled

### ISSUE THREAD

**Issue by hungys** [cmderdev/cmder#1350]
OS: Windows 10 Creators Update (1703)
Shell: zsh in Ubuntu on Windows
Font: Ubuntu Mono derivative Powerline

When themes enabled for zsh (using oh-my-zsh), there is an annoying extra space before the cursor.

theme disabled:
![](https://i.imgur.com/L6nAMX9.png)

theme enabled:
![](https://i.imgur.com/SFQC9WM.png)

I have tried the workaround in #1342 by adding `chcp 65001` into the settings, but still no luck :(

The above screenshots are captured on a desktop PC.

A fun fact is that it's not an issue on a freshly installed VM. (Parallels Desktop on macOS, with 2560x1440 screen resolution and 200% scaling)

But when I set the display scaling to 100% temporarily, the extra space would appear :/

**Comment by hungys** [comment]
The above screenshots are captured on a desktop PC.

A fun fact is that it's not an issue on a freshly installed VM. (Parallels Desktop on macOS, with 2560x1440 screen resolution and 200% scaling)

But when I set the display scaling to 100% temporarily, the extra space would appear :/

**Comment by anjingcuc** [comment]
The same issue.

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)
