### ISSUE TITLE
weird Ghost character for CJK User

### ISSUE THREAD

**Issue by ihipop** [cmderdev/cmder#1351]
I'm a CJK user.
Note that there is nothing before “git” when I press “↑” on keyboard
I keep press “↑” on keyboard to to get out another history command
 “vagrant ssh”，then I press “↓” on keyboard to get“git” back.
You will see that there is a additional “v” fom “vagrant” before “git”
But it's actually a “git” there ,not “vgit”. the "v" character  is just like a ghost

here is a screen record,I'm Using windows 10  (64 bit), with chinese language  enabled, same issue on windows 7 (64 bit),with a clean install of cmder 1.3.2

![22223](https://cloud.githubusercontent.com/assets/423077/25168086/cbe2c0f0-2514-11e7-9d35-5bd6f3e37e91.gif)

**Comment by Kisesy** [comment]
**Open:** `Cmder\vendor\clink.lua`
https://github.com/cmderdev/cmder/blob/master/vendor/clink.lua#L44
**Change:**

    if env == nil then
        lambda = "$"
    else
        lambda = "("..env..") $"
    end

**Comment by ihipop** [comment]
@Kisesy It works..
Why don't provide any settings to change this prompt ....

**Comment by clijiac** [comment]
add chcp utf-8 

see https://github.com/cmderdev/cmder/issues/1339#issuecomment-293768557

**Comment by ihipop** [comment]
@clijiac it‘s not a utf-8 issue
I‘ve tried
run `chcp 65001` won't work. and some programs such as `vagrant` won't work in utf-8 code page in Chinese env
change the prompt  from  `λ` to `$`  [here ](https://github.com/cmderdev/cmder/blob/399999d7f728c74fe3b4712ae511bcc36f299a85/vendor/clink.lua#L43-L47) work the best and cost the least.

**Comment by jdhao** [comment]
I have met exactly the same issue. Following @Kisesy 's advice, it works. Go to where cmder is installed, e.g., `D:Program Files`, the `clink.lua` file is in `vendor` sub-directory.

**Comment by KB5201314** [comment]
I have facing the same issue, I test it on my Windows10 laptop, and

**Comment by jdhao** [comment]
This issue still persists. Solution for the latest release of cmder (version 1.3.8) can be found [here](https://github.com/cmderdev/cmder/issues/506#issuecomment-438977819).
