### ISSUE TITLE
Text editor?

### ISSUE THREAD

**Issue by weaverbel** [cmderdev/cmder#1354]
Can I install nano on cmder?

**Comment by mrRosset** [comment]
Sure
![Example of nano in cmder](http://i.imgur.com/xCVkdAZ.png)
You just need to have the folder where the nano executable is in the PATH environment variable.

As for where to obtain nano, you can either use the executable from the [official website](https://www.nano-editor.org/dist/win32-support/) which probably use cygwin or look at other projets that try to properly port nano for windows. [One example](https://github.com/lhmouse/nano-win) of such projects.

**Comment by weaverbel** [comment]
Pinging @naupaka

**Comment by naupaka** [comment]
Thanks @mrRosset - this question (from @weaverbel) is in relation to a challenge we're having getting a terminal environment with nano pre-installed. We are both involved in teaching [Software Carpentry](https://software-carpentry.org/) workshops and many of the attendees have never used a command line before, so even something like adding to the PATH variable is prohibitive. If we forked the project and put the nano executable in the `bin/` directory, and then rebuild the application, is it correct that this would then automatically put nano in the PATH? Cmder looks almost perfect, but we're trying to figure out how tricky it would be to have a version that had nano installed off the bat.

**Comment by weaverbel** [comment]
Thanks for this @naupaka !

**Comment by mrRosset** [comment]
I don't know @MartiUK or @Stanzilla will probably be able to answer this.

**Comment by weaverbel** [comment]
Thanks for your efforts @mrRosset. It would be great if CMDER could solve the problem we have when trying to teach with specific tools across a range of operating systems.

**Comment by elnuno** [comment]
Maybe cmder could (optionally) depend on the [Git for Windows SDK](https://github.com/git-for-windows/build-extra/releases) and get [MSYS2](http://www.msys2.org/) support for free, allowing to install packages with ease? Or add (a simple way to also install) a real MSYS2 environment for the same effect without having to build git.
