### ISSUE TITLE
Cmder does not run if username has spaces between it

### ISSUE THREAD

**Issue by kas** [cmderdev/cmder#1355]
Same as #658, which was closed.

I get the following when using the `{bash::bash}` specified named task in cmder (Alt+Win+T > Startup).

`'C:\Users\Kenneth' is not recognized as an internal or external command,
operable program or batch file.`

My Windows user directory is `Kenneth Schnall`.

**Comment by nithinmohan** [comment]
I am facing the same issue. Can someone please update on this?

**Comment by oliversalzburg** [comment]
In the task definitions, you need to replace
```shell
cmd /k ""%ConEmuDir%\..\init.bat" "
```
with 
```shell
cmd /k ""%ConEmuDir%\..\init.bat""
```

Notice the extra space in the original command line. That is not properly escaping the path and results in the observed failure.
