### ISSUE TITLE
date issue

### ISSUE THREAD

**Issue by hackhowtofaq** [cmderdev/cmder#1357]
On Windows Command Prompt
```
echo %date:~10,4%-%date:~7,2%-%date:~4,2%
>  2017-04-26
```

On Cmder
```
echo %date:~10,4%-%date:~7,2%-%date:~4,2%
>  --2--0
```

**Comment by DRSDavidSoft** [comment]
@hackhowtofaq Is issue still relevant? I get `-/0-/0` on **both** Command Prompt _and_ cmder on my machine.

Try this instead:
`echo %date:~0,4%-%date:~5,2%-%date:~8,2%`

**Comment by Stanzilla** [comment]
That probably depends on your system locale? For me 

`echo %date:~10,4%-%date:~7,2%-%date:~4,2%` 

gives `-01-4.` in both cmd and cmder.
