### ISSUE TITLE
PowerShell init scrip

### ISSUE THREAD

**Issue by Jackbennett** [cmderdev/cmder#136]
I want to have a look at getting powershell to the same usable state CMD+clink is because I think it's just better but anyway;

If you download Cmder, run a build/install script I'm thinking it could generate its own  certificate, sign itself as the host user account, then sign the Cmder scripts it needs to run.

That way;
1. We aren't using some global cert we can execute any code through for all time
1. There isn't 1 cert to steal to run any code on all the users machines
1. We keep the user execution policy of `remoteSigned` which is [the best state][1] for a developer. Maybe even `allsigned` as anyone whose a powershell dev will set it anyway.

Some Cons;
1. Almost certainly won't be portable.*
2. It's an extra step between download -> run. but it wouldn't have to hinder
3. I guess Cmder might have to include openSSL to make the cert? The git build already comes with it and could use that. 

Pros:
1. Doesn't have to effect users who stick to cmd + clink land
2. Fire and forget powershell setup

*Maybe it's ok to sign scripts for Cmder itself the one time it's run. You have to add this cert to the host computer is that acceptable for any computer you can walk up to with a pendrive "run as admin" ?

I would love to wrap the ISE in Conemu but the ISE won't do interactive consoles so that's using git out. It would be sweet if someone could just rip the ISE engine with intellisense and syntax highlighting to use in a console window.

[1]: http://technet.microsoft.com/en-us/library/hh847748.aspx - search for "2012 R2"

**Comment by Jackbennett** [comment]
This still needs a solid answer but referencing #100 for future work.

**Comment by Izzmo** [comment]
There is a circular loop on #100 to #136 and back to #100 (this one).

Should one of these tickets still be opened?

**Comment by Jackbennett** [comment]
Looks like it was more to have the related discussion included as it's not directly a follow on.

Basically I just don't have a good answer for signing. It's kind of a misfeature.

**Comment by Izzmo** [comment]
Ah, gotchya. Yeah.. seems like someone just needs to inject some money in this project 😃
