### ISSUE TITLE
Aliases not working

### ISSUE THREAD

**Issue by ROODAY** [cmderdev/cmder#1361]
I have my aliases set inside my user-aliases.cmd file inside the config folder for cmder. They used to work in the past, yet starting sometime in the last few days the aliases are no longer working. Not even the basic ones included with cmder, like `e.` 

I'm running version 161206 stable.

**Comment by luk355** [comment]
This is a known issue if you are running Win10 1703. See #1325 for more details.

**Comment by nonsocode** [comment]
I was having this issue. But today it started working. I don't know why. When i opened cmder, i got this output
```
Clink v0.4.8 [git:d565ad] Copyright (c) 2012-2016 Martin Ridgers
http://mridgers.github.io/clink
```
Now aliases are working fine. I think there was a background update.
