### ISSUE TITLE
Direction doesnt work on Bash for Windows

### ISSUE THREAD

**Issue by MrJaxK** [cmderdev/cmder#1362]
When using cmd or powershell by Cmder, the direction keys work fine. Nevertheless, when having started bash for Win (type 'bash' command in cmd/powershell) in Cmder, the direction keys doesn't work.
Is it a bug or just I didn't set configurations correctly?

**Comment by jls5177** [comment]
This is a known issue with ConEmu (see the following page for details, [Ger arrows working in ConEmu](http://conemu.github.io/en/BashOnWindows.html#arrows)). 

You can update to the latest development build of cmder that includes a newer version of ConEmu at the following link, [AppVeyor](https://ci.appveyor.com/project/MartiUK/cmder/branch/development/artifacts).

**Comment by MiniDigger** [comment]
setting preferred release type to latest in the update settings also fixed this issue
