### ISSUE TITLE
Problem with displaying chinese characters

### ISSUE THREAD

**Issue by secsilm** [cmderdev/cmder#1363]
HI, I have a problem with displaying chinese characters. The position of cursor is wrong and not close to the characters when I input chinese characters.

![](http://i.imgur.com/e1pTdjv.png)

**My Cmder Version**

161206 stable

![](http://i.imgur.com/7xcYi3N.png)

**Comment by FirstJavaMaster** [comment]
I have the same problem.My computer runs win7 is normal but not runs win10.

**Comment by wloli** [comment]
[https://github.com/cmderdev/cmder/issues/1339](url)

**Comment by wloli** [comment]
#1339

**Comment by FirstJavaMaster** [comment]
I get a solution from issues.  You can view https://github.com/cmderdev/cmder/issues/1339 . @victor97`s answer is very good.

**Comment by secsilm** [comment]
@wloli @FirstJavaMaster thank you, the solution is pretty good.
