### ISSUE TITLE
Default Cmder install is very slow inside a large Git repo

### ISSUE THREAD

**Issue by seanofw** [cmderdev/cmder#1364]
I just downloaded and installed Cmder for the first time.  I opened it, typed `ls` a few times, and then cd'ed into one of my repositories at work, and...  nothing.  I thought it had broken, but after a little poking, I discovered that in fact it was merely _extremely_ slow.

It appears that whatever trick the prompt uses to display the current Git branch takes quite some time to load on a large repository, and it just so happened that my first tests were inside a large repository:  More than a gigabyte of source code, scattered across ~50,000 files and ~10,000 directories.

I'm used to `git status` taking a few seconds in this repo when I run it, but I'm not used to _every_ command, even simple things like `ls` and `cd`, taking an extra four seconds (literally) after it completes. I'm pretty sure it's the prompt's Git integration, since it only seems to happen in this (admittedly huge) repository; anywhere else in the filesystem, it's fine and runs at full speed.

A possible reasonable workaround might be changing the prompt so it just shows the current branch name (fast), rather than trying to determine the current code's commit status (slow).

But for me, the default configuration of Cmder out-of-the-box is nearly unusable, with no obvious way to fix it.  There are a few older pages online that describe how to change the prompt (which I'd hoped to do to simply remove the Git status outright), but they seem to only apply to older versions of Cmder:  I have 161206 stable, and the configuration files they talk about don't seem to exist, much less be editable.

**So how can I make Cmder usable when working inside a large Git repository?**

**Comment by centur** [comment]
Check file vendor/profile.ps1 if you're using powershell as your main console.
The function of interest is around line 63 (Cmder mini)  - `function checkGit($Path)`
and then it's invoked in line 113 in CmderPrompt script block like `checkGit($pwd.ProviderPath)`

You can override script blocks in your user profile file, which gets included into main profile so you will preserve your customizations between upgrades.


Or for Cmd promp you need to look into `clink.lua`, but it's up to you to figure out how to fix it in lua, I don't use classic cmd prompt

**Comment by mloskot** [comment]
@seanofw For the `clink.lua`, I've just posted another workaround here https://github.com/cmderdev/cmder/issues/447#issuecomment-379992066

**Comment by maybeec** [comment]
The coloring most probably should be an opt-out to not work in the lua code anymore. But it definitely saved my day already! Thanks @mloskot for the pointer

**Comment by ta32** [comment]
its also happening inside and SVN directory, cd is extremely slow and ls hangs as well
