### ISSUE TITLE
Bug: Aliases doesn't work

### ISSUE THREAD

**Issue by arieljannai** [cmderdev/cmder#1366]
As seen in the image below - what can be the problem?

Thanks!

![image](https://cloud.githubusercontent.com/assets/3811594/25768756/2e44876e-3213-11e7-81ee-76dc8e38d6f5.png)

**Comment by MichaelSims** [comment]
https://github.com/cmderdev/cmder/issues/1325

**Comment by arieljannai** [comment]
Thanks! will follow there.
