### ISSUE TITLE
emacs key not work in win10 bash 

### ISSUE THREAD

**Issue by fuzihaofzh** [cmderdev/cmder#1368]
I use win10 bash in cmder and I want to use emacs in it. I found `C-@`(selection) and 'C-/'(undo) cannot work here. Is there any method to solve this?

**Comment by binbinfrog** [comment]
I cannot even use arrow key and backspace key...

**Comment by bingxiao** [comment]
win10 bash+cmder, no `C+/`. I've searched around but found no document to reassign undo.
