### ISSUE TITLE
Traverse up in directory structure

### ISSUE THREAD

**Issue by fr3sh** [cmderdev/cmder#1369]
When I wand to traverse up in directory structure with Ctrl+Alt+u i have   "€" sign nothing happend. 
Is it possible to change shortcut? My system is Windows 7 keyborad in windows caled polish(developer).

**Comment by fr3sh** [comment]
Is there a way to change the shoutcut Ctrl+Alt+u to something else?

**Comment by livarion** [comment]
I am experiencing the same issue, also on polish(developer) keyboard layout.

**Comment by fr3sh** [comment]
nothing? really?

**Comment by Jooraz** [comment]
@fr3sh @filipwkania: The problem which you are facing is actually related to clink, not to the cmder itself.
You could change `up-directory` located in `vendor/clink/clink_inputrc_base` for your needs, for example to previous way to traverse up directories. So from ``M-C-u`` (ctrl+alt+u) to ``"\033`b"`` (shift+up)

**Comment by mywebstuff** [comment]
@michalsznajder Thanks, that worked for me!
