### ISSUE TITLE
Move .history file to custom location?

### ISSUE THREAD

**Issue by dimitertodorov** [cmderdev/cmder#1370]
Hi,

I store my portable conemu on a shared folder (a-la Google Drive).
Noticed that the .history file is stored with the binaries, is there any way to customize the location of the file.
I sometimes use clear-text password in my commands, and would prefer if these don't get persisted to shared storage.

D

**Comment by glucas** [comment]
The history file is created by clink. From the clink [documentation ](https://github.com/mridgers/clink/blob/master/docs/clink.md) you can specify an alternate profile directory via `--profile`. 

In cmder this option is already being used, take a look at `cmder\vendor\init.bat` -- it's being set as follows:

    --profile "%CMDER_ROOT%\config"

So you should be able to modify this bat file to specify some other directory, but note that clink looks for its settings files in the same place. You would need to move your `settings` and various `.lua` files as well.
