### ISSUE TITLE
Strange font comportment

### ISSUE THREAD

**Issue by clemjlt** [cmderdev/cmder#1371]
Hi,

I'm using Cmder but I noticed Something Strange when doing a 
`ConEmuC -CheckUnicode` :

![image](https://cloud.githubusercontent.com/assets/10855219/25962893/b1e87768-367f-11e7-9e1a-f132d63679ba.png)

I also have the problem when I use git lg (I'm French, so I haven't the problem of chinese font some people had here), :

![image](https://cloud.githubusercontent.com/assets/10855219/25973455/6b66a600-36a4-11e7-8783-6ab618793704.png)

 I changed the begin of the line from lambda to $, and I have chcp utf-8 in my environment ...

Please help !
Regards

**Comment by FtheGFW** [comment]
got the same issue with displaying Chinese

**Comment by marcadler** [comment]
Ditto. Using the default, straight-out-of-the-box settings I get this: 

![2017-05-25 23_35_50-cmder](https://cloud.githubusercontent.com/assets/8760663/26480917/0383ac40-41a3-11e7-8563-41ffafd2c3f6.png)
