### ISSUE TITLE
Quake style not hiding with lost  focus

### ISSUE THREAD

**Issue by F0rt1s** [cmderdev/cmder#1373]
Steps to reproduce behaviour:
* Have cmder in quake style mode with always on top on and autohide on focus lost out
* press show/hide toggle hotkey: cmder slides in
* loose cmder focus by clicking outside
* pres toggle hotkey again: cmder slides in again, although it is still visible (because of always on top)

Expected behaviour:
the second press on the toggle button should allways slide out cmder

**Comment by dennis-f** [comment]
Works right now as expected. But I disabled animations, maybe that helps.
