### ISSUE TITLE
Is it possible to insert a line break?

### ISSUE THREAD

**Issue by MichaelManhire** [cmderdev/cmder#1379]
In Git Bash, I was able to type a commit message, then insert a line break in the middle of it by pressing <kbd>Shift</kbd> <kbd>Enter</kbd>

However, when I tried to do that in cmder, it treated it as though I had only pressed <kbd>Enter</kbd> and submitted my commit message. Is there a key combination or some setting that makes it possible to insert a line break in cmder?

**Comment by eissasoubhi** [comment]
Use the ^ character as an escape:

```
command -option:text^

whatever
```

source : https://superuser.com/questions/150116/how-can-i-insert-a-new-line-in-a-cmd-exe-command#answer-150120

**Comment by haramjan** [comment]
git commit -m "
>
>text"

**Comment by rkyoku** [comment]
Please reopen, as this does not seem to work. Cmder treated my new line as a separate command.

Simply opening a double quote and hitting "return" does not work either (it does work in GitBash though)

This is really annoying when trying to enter a multiline text, e.g. for a commit comment

**Comment by daxgames** [comment]
This was a not a Cmder issue.  There is nothing we can do to enable this.  It is how cmd.exe works.

**Comment by rafbravo** [comment]
type this.......

sh yourShellFileName.sh

obviously you have to go to the directory or type the full route if you're not in that directory
