### ISSUE TITLE
Turn every cmd to cmder

### ISSUE THREAD

**Issue by tomasfejfar** [cmderdev/cmder#138]
I was not able to make this work. I managed to autoattach every CMD to cmder (i.e. start > run > "cmd" results in new tab). But the new tab does not look like cmder - it's normal CMD. Also "Open ConEmu Here" context menu item opens plain conemu and not cmder (ugly colors, fonts, etc.)

Is there a way to turn all of those to cmder tabs?

**Comment by ArmorDarks** [comment]
Author probably means `Integration` -> `Defatult term` -> `Force ConEmu as default terminal for console applications`

Currently that checkbox will set as Default term ConEmu itself (from `cmder\vendor\conemu-maximus5`) which will launch with it's own settings, while it should set as Default term `Cmder.exe` from `cmder\`

**Comment by tomasfejfar** [comment]
Exactly. Thanks for the clarification. @ArmorDarks

**Comment by marcoscssno** [comment]
@tomasfejfar You can launch cmder from "Run" by setting it up like this:
1. In run, type sysdm.cpl ,3
2. Click on "Environment Variables"
3. In "User Variables", edit your "PATH" variable
4. In the end of your "PATH"'s value, add a `;` + the path of the cmder's folder. Ex.: %PROGRAMFILES%\nodejs\\**;C:\cmder_mini**

You're now set up, just type cmder in run.

**Comment by tomasfejfar** [comment]
@marcoscssno not exactly - this won't open "new" cmder tab. 

* run -> cmder
* cmder window opens
* run -> cmd
* cd c:\temp
* cmder
* expected: new cmder tab opened in c:\temp
* actual: existing cmder window brought to foreground

**Comment by luscas** [comment]
@ArmorDarks thanks bro!

**Comment by BrenBarn** [comment]
Isn't it kind of absurd that opening Cmder and using it to register its own context menu actually registers a different program (ConEmu)?  Why doesn't Cmder override the ConEmu settings so it registers itself and not ConEmu?

**Comment by mrx23dot** [comment]
How do I override "open command window here" context menu to open in cmder instead of cmd in 2021?
