### ISSUE TITLE
UnicodeEncodeError: 'gbk' codec can't encode character  u'\ufeff' in position 10: illegal multibyte sequence

### ISSUE THREAD

**Issue by woshichuanqilz** [cmderdev/cmder#1381]
![0521172644](https://cloud.githubusercontent.com/assets/11295355/26282768/78c2e3ba-3e4a-11e7-8c36-d7be673c5277.png)
HOw to solve this question ?

**Comment by frankruizhi** [comment]
Maybe you could have a refrence to 
this discussion:https://stackoverflow.com/questions/3218014/unicodeencodeerror-gbk-codec-cant-encode-character-illegal-multibyte-sequen
