### ISSUE TITLE
"Opening" in already open terminal

### ISSUE THREAD

**Issue by Falkgaard** [cmderdev/cmder#1382]
Hi, I've integrated Sublime Text 3 into Cmder like this: 
http://i.imgur.com/hBCdnXO.png
And I've got a ST3 plugin called "Terminal" that let's me open an external terminal (Cmder, in this case) at the folder the current document is in simply by pressing a hotkey.
What I want to do is something along the lines of: CTRL+B to build the current source file, CTRL+SHIFT+T to switch focus to the already open upper split panel (the Cmder one) and have it navigate to the folder of the source file, then just write "foo" to run the freshly built "foo.exe" there. But instead, when press CTRL+SHIFT+T a new tab gets opened in Cmder that covers all of the previous two splits... is there a way to make it re-use the currently open Cmder panel instead..?
Best regards,
-V

**Comment by GufNZ** [comment]
In a similar vein, is there a way in general to open say a cygwin bash on one side of a split and a cmd on the other, other than splitting cmd and running cygwin manually under one of them?  Or are splits limited to being only the same Task?
