### ISSUE TITLE
Non-default path for .ssh keys 

### ISSUE THREAD

**Issue by luntungle** [cmderdev/cmder#1384]
if I generate ssh keys in cmder and save them at a path other than default, the ssh-agent will work with them just fine for the current session, but then in the next session it would only start looking for the keys at the default path.  How do I tell it where to look? Win 7, cmder mini

**Comment by janschulz** [comment]
IMO the easiest way to handle keys is putting `AddKeysToAgent yes` into ~/.ssh/config and then specifying key locations there:

```
AddKeysToAgent yes

Host github.com-js
    HostName github.com
    User git
    IdentityFile ~/.ssh/id_rsa_janschulz

# [more hosts with different keys]

# default at the last position
IdentityFile ~/.ssh/id_rsa_janschulz
```

This results in a password question when you first use that key and then you are done for that key for this session.
