### ISSUE TITLE
Some suggested features

### ISSUE THREAD

**Issue by ducminhgd** [cmderdev/cmder#1386]
~1. Open terminal panels in the same windows like terminator on Linux or MPutty on Windows.~
2. Color of tabs. For example, I can make color of live environment tabs red to warning myself to be careful when run any command, color of test environment tabs are blue and color of development tabs are default.

**Comment by DRSDavidSoft** [comment]
@Maximus5 does ConEmu have a feature to color the tabs?

**Comment by Maximus5** [comment]
Tabs? What do mean? 

![2018-03-08_19-14-21](https://user-images.githubusercontent.com/1222388/37161923-090d8a84-2305-11e8-9afc-6cf8aec67f10.png)

**Comment by DRSDavidSoft** [comment]
@Maximis5, I mean setting the background color  of the tab buttons (where you have marked as "Tab")

iTerm2 has a similar featue as stated [here](https://superuser.com/q/403650/320611):
![iTerm2 tabs](https://i.stack.imgur.com/cjsQf.png)

Can you implement a similar featue for ConEmu?

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)

**Comment by DRSDavidSoft** [comment]
@Maximus5 should I recreate this issue at ConEmu repo?
