### ISSUE TITLE
SSH extremely slow

### ISSUE THREAD

**Issue by izay4kun** [cmderdev/cmder#1390]
Hi guys, until 2 weeks ago i was using **CMDER**, like my new lover, forever together, we were inseparable. But then a terrible thing happened, the SSH becomes slow in a way that is impossible to even tip "**HTOP**", the console is fine with normal usage outside **SSH**, but when i connect everything goes to turtles. (i know what you're thinking, 

> dude its your server provider!

, and yeah i was thinking that too, but **NO!** it isn't i entered in contact with them and they said that the server was okay, without errors and etc.) then i tried to connect in SSH with PUTTY and tadãaa **WORKED NORMALLY!** So i can only suppose that the problem is **CMDER**, tried to find something here on the issues but didn't. So now i'm here sadly asking you folks if you know something about this and if you do, please save me because i'm already addicted with **CMDER**. 

- I'm using CMDER full version in WINDOWS.

- I'm sorry for any typos, english isn't my native language.

- Thanks in advance!

**Comment by rvhelden** [comment]
Recently i have issues to with ssh. After logging in U must type every character twice before it shows on screen. Maybe it has something to do with the combination of windows 10 version 1703 build 16199.1000

**Comment by rvhelden** [comment]
I maybe have found the cause of the issue and it seems to be in windows 10 insider preview builds, check this link https://github.com/git-for-windows/git/issues/1172

**Comment by izay4kun** [comment]
Hi @rvhelden i'm using windows 10 insider preview, version 1703, build 16199.1000! I will try to get the new builds and see if it solves, thank you (when i see some results i write again here).

**Comment by rvhelden** [comment]
I can confirm that the latest windows preview version fixed it. The latest version is currently Microsoft Windows [Version 10.0.16226.1000]
