### ISSUE TITLE
terminal prompt not wrapping correctly while emulating bash on windows    

### ISSUE THREAD

**Issue by ssehayek** [cmderdev/cmder#1392]
To reproduce, open Cmder, and maximize the window: 

1. While emulating a bash console (Bash on Ubuntu on Windows), shrink window size so that the command line (i.e. `PS1` environment variable), wraps to the next line. 
2. Run the command (can be a simple <kbd>Enter</kbd> keystroke, as long as 1. is respected).
3. Maximize window size, and type a command which is longer than the previous shrunken window. Line should wrap over itself.

Can anyone reproduce this behavior? (Running Microsoft Windows [Version 10.0.15063])

I did not observe the same behavior while emulating cmd.exe.

**Comment by bdeonovic** [comment]
I also have this problem

**Comment by imdaveho** [comment]
I'm also experiencing this issue.

**Comment by daxgames** [comment]
If you are running WSL you are not using Cmder.  You are running WSL in Conemu.

If you have issues you nwed to report it to the Conemu Developer.

**Comment by imdaveho** [comment]
@daxgames I'm running mintty in cmder and no, it is not an issue with mintty / msys2, see my new issue #2165
