### ISSUE TITLE
change directory very slow inside a git repo

### ISSUE THREAD

**Issue by vinoth1303** [cmderdev/cmder#1394]
I see lot of questions surrounding this but no solution. A simple empty enter key on a git repo working directory takes a huge delay. I guess it's due to the git checks for any repo changes. Any solution to improve this?

**Comment by rsirefelt** [comment]
I have this problem myself with the 1.3.4 release. What I see on my computer is that cmder responds pretty well at first inside a git repo. But after some time it gets really really slow and unusable while inside the a git repo but it responds fine outside of it. Restarting cmder does not help. The only solution I have is to restart my computer then cmder in the git repo works fine until the same situation arises again. 

Anyone else seeing this or have a solution?

**Comment by overheat** [comment]
I face almost the same issue. Win10 64-bit and latest Git and Cmder 1.3.5
