### ISSUE TITLE
"DC initialization failed!"

### ISSUE THREAD

**Issue by helmesjo** [cmderdev/cmder#1398]
Returning from turned off display (displayport, which does a lot of funky stuff [causing a sea of issues](https://goo.gl/6YZLFi) with windows & scaling) gives me this error:

<img width="143" alt="cmder_fail" src="https://user-images.githubusercontent.com/2501070/26913781-7294ca36-4c1d-11e7-9cd3-ae8df600f437.PNG">

Force-quitting cmder is the only resolution.

#windows10

**Comment by moritzgloeckl** [comment]
This still happens.

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)
