### ISSUE TITLE
Set a name for the Tab on a task

### ISSUE THREAD

**Issue by ghost** [cmderdev/cmder#14]
Is there a way to open a tab and have if use a default Tab Name rather than having to rename the tab each time? eg when creating a tab using a task is it possible to set the name of the tab ?

**Comment by szkrd** [comment]
Can I combine this with the `:d` (directory) param?

**Comment by mpes** [comment]
You can:
`cmd /c "%ConEmuDir%\..\git-for-windows\bin\bash --login -i" -new_console:d:%USERPROFILE%  -new_console:t:Hallo`
