### ISSUE TITLE
Auto-create fast new tab shortcuts for additional tasks

### ISSUE THREAD

**Issue by nevik** [cmderdev/cmder#140]
The *fast new tab* shortcuts `Shift+Alt+{1,2}` for *New {cmd,ps} tab* seem to be hard-coded. I would have expected that these numbers are related to the number of the task in the settings dialog, and that when I create new tasks, these get assigned shortcuts as well -- but that does not seem to be the case (I created a new task, now number 3, and `Shift+Alt+3` does nothing).

If you could make it so that the first 10 tasks get auto-assigned the shortcuts `Shift+Alt+[1-9,0]`, that would be awesome :D

**Comment by Jackbennett** [comment]
Yes.

see: https://github.com/cmderdev/cmder/commit/5e07567a724e39c7d827c14d4b2d2a731afb9fba
