### ISSUE TITLE
docs: Can I add a command to run when I cd somewhere? how?

### ISSUE THREAD

**Issue by cfv1984** [cmderdev/cmder#1402]
In bash, this involves adding an alias to cd using the builtin inside, looking for a script, and running it. Can I do this in cmder? If it does, can this be added to the docs?

**Comment by glucas** [comment]
Something like this?

    cd=cd $* $T echo Doing something else here

The cmd.exe alias support (via doskey) doesn't allow recursive aliases so this seems to work fine. 

Depending on your use case, you may also want to look at hooking into clink. For example I am using https://github.com/wting/autojump with cmder. I believe the way it works is it registers a custom prompt filter via clink that lets it run a script to update the autojump database after every command.

**Comment by glucas** [comment]
If you want to conditionally run some command based on the current directory you can still use a cd alias, such as:

    cd=cd $* $T if exist foo.cmd foo.cmd
