### ISSUE TITLE
Strange behavior on Windows 7

### ISSUE THREAD

**Issue by ghost** [cmderdev/cmder#1404]
Hello. 

I've noticed some strange behavior with cmder on Windows 7.
Whenever I run a command, create a directory or whatever I need to do it doesn't have any ("visual") effect.

Now, let me explain this better.. to be frank, I don't even know how to explain this.

If I run `vagrant init` to generate a Vagrantfile, it will do that just fine and I can see the file being there if I type in the `ls` command, but if I open my text editor in the same directory (or if I simply search for the file from the UI) it's not there. Same thing can be said about directories. 

It's a bit strange to me because yesterday it was working fine and now it seems to have this problem.

I believe it might be something related to my user profile being corrupted (?) as some other Windows commands (such as CTRL + A) do not work.

Note that I am running cmder with administrator privileges.
Any help would be more than welcome.

Thanks.
- Paul

**Comment by daxgames** [comment]
works fine for me on windows 10 and I don't have windows 7 so I can't troubleshoot it.
