### ISSUE TITLE
With certain applications, Right click does not work

### ISSUE THREAD

**Issue by catch878** [cmderdev/cmder#141]
Alright, so just to warn you, this problem seems to be limited to only one application and is fairly obscure. I use ModelSim to do simulation of hardware for one of my classes and in my development flow I use cmder to start the simulation with the vsim command. 

However, if ModelSim is started from cmder, any right click within the application causes the window to lose focus. If I right click fast enough I can see the context menu flash briefly before disappearing and the window loses focus. I have tried this with other applications, but none of them exhibit this behavior. Starting ModelSim any other way, either from the Windows Command Prompt or by clicking the program icon does not cause this behavior.

Using the debug tool, I was able to capture the events that were occurring on right click within the application, but I'm not sure how to debug this and identify the issue. I've included screenshots of the commands being sent below:
![screenshot 12](https://f.cloud.github.com/assets/4050301/2155492/e738ff0c-9446-11e3-9342-6aa08d130ebf.png)

I've boxed the commands that are related to the right click action, but just for reference command 23 is being sent in on the ComEmuGui pipe from the ModelSim GUI process (vish in the second screenshot below) when I right click within the ModelSim window.

List of processes currently running:
![screenshot 13](https://f.cloud.github.com/assets/4050301/2155528/5ea46e96-9447-11e3-94f7-1e132d22c5af.png)

Of course, the easiest and simplest fix is to just use the Windows command line, and I will probably end up doing that if there is no fix. But for the sake of my sanity, can anyone pinpoint why the right click is being rerouted to ConEmu?

**Comment by Jackbennett** [comment]
This is an awesome bug report but I don't think we can help with it. Might be a symptom of another problem that ConEmu want to investigate.
