### ISSUE TITLE
Bash commands like ls and cat not working.

### ISSUE THREAD

**Issue by bipindr123** [cmderdev/cmder#1410]
I have downloaded the full version (with git for windows) but the bash commands are not working
![capture](https://user-images.githubusercontent.com/12273287/27330214-1fea35a6-55d6-11e7-807f-2930c74bb0c0.PNG)

**Comment by helmesjo** [comment]
Hi! You are running cmd.exe (Windows Command Prompt), which doesn't support those commands.

Press the + in the bottom-right corner and open a new terminal with Powershell (or bash if [unix-like environment is available](https://superuser.com/questions/608106/how-can-i-use-a-bash-like-shell-on-windows)). Powershell supports [**a few**](https://msdn.microsoft.com/en-us/powershell/scripting/getting-started/fundamental/using-familiar-command-names) of the Unix commands disguised as [aliases](https://en.wikipedia.org/wiki/Alias_(command)).

**Comment by bipindr123** [comment]
OH thanks got it!

**Comment by marcosAJS** [comment]
@helmesjo Thanks man

**Comment by abdelilahberk** [comment]
thank you

**Comment by daxgames** [comment]
@bipindr123 @marcosAJS @abdelilahberk If you downloaded Cmder full and bash commands shown in the screenshot ar not working something is wrong.  These commands should work in Cmder full in all session types.

Open a `cmd::cmder` session and type `cmder_diag.cmd` and post the output here.

**Comment by mfaccin** [comment]
thank you :)

**Comment by Ahmed-Ibork** [comment]
**Thanks Man ! That's Great**
