### ISSUE TITLE
How to install Vim plugins through pathogen or vim-plug? 

### ISSUE THREAD

**Issue by DevotionGeo** [cmderdev/cmder#1411]
I actually want to install [vim-go](https://github.com/fatih/vim-go) on Vim which comes bundled with full download of Cmder.

**Comment by vegangaro** [comment]
same way than on linux

Just copy all yours linux vimrc into C:\Users\<current user>\Vim\_vimrc

Then run:

`PlugInstall`

**Comment by DevotionGeo** [comment]
Did you mean "Just copy all your Linux ~/.vim contents into C:\Users\<current user>\Vim_vimrc" ?

**Comment by DevotionGeo** [comment]
@Stanzilla

**Comment by vegangaro** [comment]
You can use Gvim through Cmder.

I installed Gvim and Cmder. Then I copied my vimrc to _vimrc, installed all plugins through vim-plug(PlugInstall).

To open Gvim through Cmder just type: `vim`
