### ISSUE TITLE
mv command fails with / or \

### ISSUE THREAD

**Issue by DrakeXiang** [cmderdev/cmder#1412]
I'm relatively new to terminal command, so I tried to move a file to a folder that hasn't been created yet in current path with this command: ```mv abc.txt /book``` and I found the abc.txt file was gone, I then got told that this command actually means 'move abc.txt to /book directory at root', however, I could not find the ```/book``` folder or the ```abc.txt``` anywhere. I then tried with ``` mv abc.txt ./book``` and ```mv abc.txt .\book```, still not work as I expected, so is cmder buggy?

**Comment by hyrious** [comment]
Firstly, lets find your first abc.txt,
```cmd
cd /
explorer .
```
should find book here.

Then, look into some shell commands when you run
with cmd.exe (as cmder's default shell),
```cmd
mkdir book
move abc.txt book
```
(more details see `move /?`)

with bash,
```bash
mkdir book
mv abc.txt book/abc.txt
```
(more details see `man mv`)

**Comment by DrakeXiang** [comment]
@hyrious Thanks for your reply, but I still can't find my abc.txt or /book like that, maybe it's just me?

**Comment by DrakeXiang** [comment]
Finally, I found those files in cmder folder, not  sure why..
