### ISSUE TITLE
Compiling g++/clang files takes longer than on Gvim/cmd

### ISSUE THREAD

**Issue by ghost** [cmderdev/cmder#1413]
Hi, 

Most probably its my fault, but why its talkes longer to compile a single g++ file on cmder/vim than on gvim/cmd?

Commands used to compile:

`g++ -std=c++14 -Wall -Wextra -pedantic chapter.4.6.3.cpp -o chapter.4.6.3.exe`

and 
`
clang++ -std=c++14 -Wall -Wextra -pedantic chapter.4.6.3.cpp -o chapter.4.6.3.exe`

Source file 
```

#include "std_lib_facilities.h"

//------------------------------------------------------------------------------

// simple dictionary: list of sorted words:
int main()
{
    vector<string> words; 
    string temp;
    while (cin>>temp)                // read whitespace separated words
        words.push_back(temp);       // put into vector

    cout << "Number of words: " << words.size() << endl;

    sort(words.begin(),words.end()); // sort "from beginning to end"

    for (int i = 0; i< words.size(); ++i) 
        if (i==0 || words[i-1]!=words[i]) // is this a new word?
            cout << words[i] << "\n"
```

[github source](https://github.com/vegangaro/dotfiles/blob/master/devel/ppp/Chapter04/chapter.4.6.3.cpp)

Thanks!

**Comment by vegangaro** [comment]
Fixed by removing git checking on clink.lua as said here:

https://github.com/cmderdev/cmder/issues/447#issuecomment-244149494
