### ISSUE TITLE
How to remove cmderr and "Unrecognized parameter" messages?

### ISSUE THREAD

**Issue by AlexAkulov** [cmderdev/cmder#1415]
I get two messages "Unrecognized parameter" on logon in Windows and everytimes when I launch VSCode I get three messages "Unrecognized parameter".

https://gyazo.com/a807f78b3d48019ce2a41eb9043e15f6

It make me crazy!!! 

I ran `cmder /UNREGISTER ALL`,  
I pressed all buttons "Unregister" in settings,
I finded and delete all items "cmder" in windows registry.
BUT IT DOES NOT HELP! 

How I can fully remove cmder from my system?

**Comment by daxgames** [comment]
Is this still an issue using current nightly builds?

**Comment by liklev** [comment]
a little old, but today i met the same misery under windows 7.
i solved it deleting the environmental variable "comspec" in computer/advanced properties.

**Comment by daxgames** [comment]
Closing due to lack of response from OP.

**Comment by rorar** [comment]
If you found your way here, this might be your solution.
You might followed other (outdated) instructions with changing things in regedit and messed things a bit up

make sure you've correctly set up all variables correctly:
https://github.com/cmderdev/cmder/wiki/Setting-up-Environment-Variables
_Little Helper:_
Install cmder with...
System variables = cmder installed locally on your computer
User variables = Carry around cmder as portable app (for you usb flash drive)

run
**regedit.exe**
navigate to
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\cmd.exe

if the 
(Standard) key value is different from
C:\Windows\System32\cmd.exe
right click->Edit
copy and paste the above folder structure

Path key value is different from
C:\Windows\System32
right click->Edit
copy and paste the above folder structure

Fully reboot your PC with
run
shutdown /s /f /t 0

Turn on you PC...
Everythings should work as intended now.
