### ISSUE TITLE
Font display broken when using cmder via Remote Desktop

### ISSUE THREAD

**Issue by needfulthing** [cmderdev/cmder#1418]
When I use cmder on a server via Remote Desktop red text is partially rendered blurred.

![image](https://user-images.githubusercontent.com/2411992/27480117-fcd12bea-5816-11e7-8ea0-2afae196ed1d.png)

**Comment by needfulthing** [comment]
I still have this problem on all RD connections. Can anyone confirm this? It seems to be limited to the red color used in the git status output.

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)

**Comment by needfulthing** [comment]
Did so, thanks for the feedback :)
