### ISSUE TITLE
Create windows installer

### ISSUE THREAD

**Issue by iljau** [cmderdev/cmder#142]
#### The easy way

1. Download and install [`nsis-2.46.5-Unicode-setup.exe`](https://unsis.googlecode.com/files/nsis-2.46.5-Unicode-setup.exe) from https://code.google.com/p/unsis/.
2. Download: https://github.com/bliker/cmder/releases/download/v1.1.3/cmder.zip 

3. Select: "Installer based on ZIP file"
![screenshot-1](https://f.cloud.github.com/assets/43159/2179169/2cbe1f54-9694-11e3-96ae-623cd706edcc.png)

4. Set meaningful default extraction path:
![screenshot 2014-02-16 00 58 11](https://f.cloud.github.com/assets/43159/2179175/c52759fe-9694-11e3-99ff-918f7aa9c6bc.png)

5. _(optional)_ Sign the resulting installer.

   Follow guide: http://blog.assarbad.net/20110513/startssl-code-signing-certificate/

   Then sign using:
   `signtool.exe sign /v /f cert.pfx /ph /t http://timestamp.verisign.com/scripts/timstamp.dll cmder-setup.exe`

<br />

#### Expected result
Something similar to [`cmder-setup.exe`](https://github.com/iljau/cmder/releases/download/v1.1.3-installer/cmder-setup.exe) from https://github.com/iljau/cmder/releases/tag/v1.1.3-installer

**Comment by felixfbecker** [comment]
As much as a portable version is cool to have, I would prefer to have an installer also - that creates start menu shortcuts, registers the context menu extension (if the user chooses so) and also uninstalls everything again. It can't be that hard to wrap up a little .msi?
