### ISSUE TITLE
When in Quake mode, the context menu has odd behaviour.

### ISSUE THREAD

**Issue by Jezza** [cmderdev/cmder#1423]
Simply put, using the context menu with quake mode doesn't work as you'd expect.
Currently, it just opens a tab to the default location.

I'd expect it to either open a tab at the location, or change the current tab.

**Comment by smokebacon** [comment]
This is the same issue as in [This thread](https://github.com/cmderdev/cmder/issues/356)

**Comment by Stanzilla** [comment]
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu
