### ISSUE TITLE
Latest cmder is listed as malicious according to Virustotal

### ISSUE THREAD

**Issue by JonasStenmarck** [cmderdev/cmder#1427]
The cmder binary is probably including a Trojan. https://www.virustotal.com/en/file/834af17ac69ee62c8748b00cd54859b4f2e179677397cfde276cf48d30b0594a/analysis/

Its also detected as malicious by Carbon Black.

**Comment by jgstew** [comment]
It seems to be misidentified as an actual trojan, `Trojan.Diple`, not just a warning about a potential hacktool, which would be less concerning.
