### ISSUE TITLE
Is that any way I can run some commands when I launch Cmder?

### ISSUE THREAD

**Issue by thehackercat** [cmderdev/cmder#1428]
I need to run some commands as administator(root) to set up network config.

Like 
``` bash
set http_proxy=http://10.196.0.84:3128
set https_proxy=http://10.196.0.84:3128  
```

But I can't find any place that I can add those commands in Cmder setting.

Is that any way I can run some commands when I launch Cmder?

**Comment by goutkannan** [comment]
You can do that in Settings --> Environment menu. 
![image](https://user-images.githubusercontent.com/13937868/28026181-ed0c96b2-655a-11e7-8298-b67fa0596923.png)

**Comment by thehackercat** [comment]
@goutkannan thanks, it works!

**Comment by DRSDavidSoft** [comment]
@Stanzilla Add to the docs and close?

**Comment by daxgames** [comment]
Put scripts in `%cmder_root%\config\profile.d`

**Comment by thehackercat** [comment]
@daxgames Actually, I put these scripts in `%cmder_root%\config\profile.d`, but somehow it didn't work.

**Comment by daxgames** [comment]
@thehackercat what scripts, filenames?  If you are referring to `%cmder_root%\config\user-profile.cmd`, `%cmder_root%\config\user-profile.sh`, or `%cmder_root%\config\user-profile.ps1`.  They should be in the exact paths shown. 

It depends entirely on the version of cmder you are running as to whether it has `profile.d` support.
