### ISSUE TITLE
REGISTER ALL Without admin?

### ISSUE THREAD

**Issue by buddythumbs** [cmderdev/cmder#1429]
Hi,

I really really like this CMD replacement, real good job!!

One thing I need to be able to do though is be able to right click from a folder and open cmder there. 

I see this is accounted for in the readme but I don't have admin privileges.

Is it possible to have this functionality WITHOUT admin privileges ? I currently use git bash and was able to set this up without admin privileges. If this is not possible that's ok too but I would like to move away from using multiple systems.

Great job on the whole project!!

**Comment by Mindavi** [comment]
There is a link here explaining how to do this by editing the registry. You probably still can't do this with admin rights, but this is the only other (good) way. https://github.com/cmderdev/cmder/wiki/%5BWindows%5D-%22Open-Cmder-Here%22-in-context-menu

If this is not possible with your rights, you probably can't do this.
