### ISSUE TITLE
handle could not be opened / terminal is not fully functional

### ISSUE THREAD

**Issue by corsen2000** [cmderdev/cmder#143]
Hello,

When I move into a directory containing and git repository and run `git log`, I recieve the following messages:

```
WARNING: terminal is not fully functional
-  (press RETURN)
```

And

```
The handle could not be opened
during redirection of handle 0.
The handle could not be opened
during redirection of handle 0.
```

I receive these messages in other scenarios as well, this is just one example.

This is a clean installation of Cmder v1.1.3.  I do not get these issues when using git-bash.

I am running git `1.7.9.msysgit.0`.

Any suggestions on what I can try to fix this?

Thank you.

**Comment by fernandoPalaciosGit** [comment]
thank you @corsen2000 , in Windows easy take control of that environment variable by console typing:
```bash
 setx TERM msys
```
