### ISSUE TITLE
problem with last command

### ISSUE THREAD

**Issue by zcdll** [cmderdev/cmder#1431]
I use Cmder.exe in Windows 10 and the version of Cmder is 161206 stable.

The problem is that when I try to run last command many times, that is to say I press down the  UP button many times, the first few times I get the right command, but after 3 times, I get one more letter before the right command.
It's just like the photo below.

![more g](http://osrxoas5t.bkt.clouddn.com/snipaste20170708_213600.png)

First I type git push and I press down the UP button 3 times then I get the  'gls' command. The letter g is redundant.

**Comment by gotounix** [comment]
I have the same problem with 161206 and 170730 ConEmu.

**Comment by gotounix** [comment]
@zcdll You can change the prompt in 'Cmder\vendor\clink.lua', and everything will be OK.

```
local cmder_prompt = "\x1b[1;32;40m{cwd} {git}{hg} \n\x1b[1;30;40m{lamb} \x1b[0m"
```

Replace '{lamb}' to other characters.

```
local cmder_prompt = "\x1b[1;32;40m{cwd} {git}{hg} \n\x1b[1;30;40m$ \x1b[0m"
```

**Comment by zcdll** [comment]
@gotounix THX
