### ISSUE TITLE
Ctrl+C closes my text editor

### ISSUE THREAD

**Issue by TheRealPhoneCall** [cmderdev/cmder#1433]
Hi,

I'm having this problem that whenever I terminate running programs, Ctrl+C or Ctrl+Break, it also closes my text editor Visual Studio Code. 

Cheers

**Comment by tdunsford** [comment]
FYI, this is not a cmder issue. Its related to how VS code starts up. Simple fix is to make sure your the code.exe is not in your path and/or that it runs the code.cmd command instead. 

See this issue: https://github.com/Microsoft/vscode/issues/20769
