### ISSUE TITLE
messy Chinese characters

### ISSUE THREAD

**Issue by Whisht** [cmderdev/cmder#1436]
when I use the alisas "ls" in 'cmd.exe' console ,this characters are shown as "\"+digitals.
Just like this.
![image](https://user-images.githubusercontent.com/16497652/28110126-f61446d6-6723-11e7-88ac-2ebfb38287b0.png)

**Comment by mrRosset** [comment]
Have you tried the solution from #985 ?

**Comment by Whisht** [comment]
Yes,I have tried this method before.But it is just effective when I use ls rather than "ls |more".Meanwhile ,if I input "help",it is also messy code .

**Comment by BruceChen2017** [comment]
open `~\cmder_mini\config\user-profile.cmd` ,then write `set LANG=zh_CN.UTF-8`

**Comment by rosuH** [comment]
@Whisht Did you try to restart your cmder ?

**Comment by Whisht** [comment]
@rosuH Absolutely yes！I got no idea about this problem.So Confused.Maybe I should reinstall and reconfigure my cmder .Anyway,thanks you guys.

**Comment by wakedautumn** [comment]
I've suffering the same issue!
What's more, it's not able to insert Chinese characters in emacs editor, launching by cmder.
I've tried #985, which doesn't help.

OS: Windows 10  
Language: English
