### ISSUE TITLE
git bash is not available

### ISSUE THREAD

**Issue by Whisht** [cmderdev/cmder#1437]
well.My installation path include space。It's E:\Program Files\Cmder。And because of this ,every time I launch bash console ,it will show me that "'E:\Program' is not an internal or external command, nor is it a program to run"
![image](https://user-images.githubusercontent.com/16497652/28110365-be1d36ba-6724-11e7-839b-ff729039ac85.png)

**Comment by rwenz3l** [comment]
Same issue for me. Is fixed by moving it to a path without spaces. I created a "Applications" directory under C:\ and placed it in there. No issues after that. It would be great if that common place (Program Files) was possible.

**Comment by toto-jy** [comment]
Yes, spaces in path names have been a thing since Windows 95. Software should be able to cope with them in 2018 without falling over. Consider the user who only has write access to their user directory `C:\Users\Bob Jones` on a locked-down system — they will not be able to use this *at all*.

**Comment by Stanzilla** [comment]
Try with v1.3.5

**Comment by rwenz3l** [comment]
Works for me on Windows 10 Pro and Cmder 1.3.5

**Comment by toto-jy** [comment]
I only downloaded it four hours ago, though, and it claims to be version 1.3.5. I re-downloaded and it does the same thing. This is the mini version — I don't really want to download the full version as I already have Git for Windows installed.
