### ISSUE TITLE
git clone templates not found / Unable to find remote helper for 'https'

### ISSUE THREAD

**Issue by welovewebdesign** [cmderdev/cmder#144]
After installing cmder I'm getting the following messages while trying to clone a github repo:

```
git clone https://github.com/twbs/bootstrap.git
Cloning into 'test'...
warning: templates not found /share/git-core/templates
fatal: Unable to find remote helper for 'https'
```

Some infos:
- windows 8.1
- git version 1.8.5.2.msysgit.0 (installed prior to cmder)
- http://windows.github.com/ is also installed on my system (cloning with it is still working)

Removing cmder fixed the issue, but well, no more cmder ...

update: after investigation, I was using the msysgit version which probably was in conflict with the already in place msysgit.

**Comment by JazzCousins** [comment]
I am having this problem, what is the "mini" version, where can I download it?

**Comment by Stanzilla** [comment]
It's no longer available, it was the version without Git.

**Comment by JazzCousins** [comment]
ok, I think I may have found a work around anyway

**Comment by Studiman** [comment]
@JazzCousins  what is the workaround. Got the same problem?

**Comment by JazzCousins** [comment]
@Studiman My work around was to download the project as a zip file and locate that with sourcetree after it  had downloaded, I later got other problems though so switched to using Git desktop instead of Sourcetree. being a noob to git it was far simpler to use and didnt malfunction on me. Hope that answers your question but not sure im knowledgeable enough to help beyond that anyway... Sorry.

**Comment by Studiman** [comment]
Hm okay thanks anyway.

Still got this problem:

warning: templates not found /mingw64/share/git-core/templates
fatal: Unable to find remote helper for 'https'

I don't have a clou where that is comming from.

**Comment by Pycomet** [comment]
Same here. Why is the coming up?

**Comment by Hsgngr** [comment]
Same Problem here any solution ?

**Comment by daxgames** [comment]
Looks like there is a solution above in this issue.  Does the situation match Nd have you tried the fix?
