### ISSUE TITLE
choco install miniconda for python2

### ISSUE THREAD

**Issue by l0o0** [cmderdev/cmder#1440]
```
λ choco install Miniconda
Chocolatey v0.10.7
[Pending] Removing incomplete install for 'anaconda2'
Installing the following packages:
Miniconda
By installing you accept licenses for the packages.
Progress: Downloading Miniconda 4.3.21... 100%

Miniconda v4.3.21 [Approved]
miniconda package files install completed. Performing other installation steps.
The package Miniconda wants to run 'chocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[N]o/[P]rint): Y

File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
Error - hashes do not match. Actual value was '5B0B6B699E70A1018057160C4831DAC0'.
Downloading miniconda 64 bit
  from 'https://repo.continuum.io/miniconda/Miniconda2-4.3.21-Windows-x86_64.exe'
Progress: 100% - Completed download of C:\Users\0o0\AppData\Local\Temp\chocolatey\Miniconda\4.3.21\Miniconda2-4.3.21-Windows-x86_64.exe (51.41 MB).
Download of Miniconda2-4.3.21-Windows-x86_64.exe (51.41 MB) completed.
Hashes match.
Installing miniconda...
miniconda has been installed.
  miniconda can be automatically uninstalled.
 The install of miniconda was successful.
  Software installed as 'EXE', install location is likely default.

Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

C:\Users\0o0
λ conda
'conda' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Users\0o0
λ C:\Users\0o0\AppData\Local\Temp\chocolatey\Miniconda\4.3.21\Miniconda2-4.3.21-Windows-x86_64.exe
C:\Users\0o0
λ miniconda
'miniconda' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
```

I installed Miniconda for python2 by choco and instaslled successfully as the message shown above.  
But I can not find `conda` or `miniconda` command after this installation.
I found a conda.exe in `C:\ProgramData\Miniconda2/Scripts`
Do I need to double click the miniconda exe file downloaded to install it manually? or add `C:\ProgramData\Miniconda2/Scripts` to my PATH?

**Comment by l0o0** [comment]
After I add `C:\ProgramData\Miniconda2/Scripts` to windows Path, it works fine. Please close this issue.

**Comment by Thamster** [comment]
The path should have been updated for you by the installer.

**Comment by l0o0** [comment]
@Thamster Sorry for the delayed replay.  The PATH in win10 has not changed before I install miniconda. Maybe this is a bug

**Comment by MartiUK** [comment]
@l0o0 That would be a bug with miniconda, not cmder. Please create an issue with them.

**Comment by jan-glx** [comment]
Sorry for the noise @cmder-devs, but since I came here through google for someone to tell me to use:

```choco install miniconda3 --params="'/AddToPath:1'"``` 

to have miniconda added to `PATH` when installing it with `choco` I though to be this one myself and leave this message in this totally inappropriate place. Sorry again for the noise.
