### ISSUE TITLE
git-for-windows somehow blocks vagrant use in cmder

### ISSUE THREAD

**Issue by realsby** [cmderdev/cmder#1444]
After I read this I manage to use vagrant in cmder.. 

https://superuser.com/questions/1228436/vagrant-under-cmder-on-windows-10-does-nothing-works-under-cmd-exe/1230618

**Comment by ihipop** [comment]
same issue

**Comment by ihipop** [comment]
maybe it‘s a vagrant issue
I down grade to vagrant 1.9.6 it works.
the problem is appear on vagrant 1.9.7
