### ISSUE TITLE
Windows 10: "stopped working" flood

### ISSUE THREAD

**Issue by simberaj** [cmderdev/cmder#1446]
When using Cmder on Windows 10, it seems some of its subprocesses are terminated in an unusual way that displays the "<program> has stopped working" prompt every time. Due to this, the console is almost unusable as the user is flooded with these prompts.

The following errors pop up during startup:
* Where - Lists location of files has stopped working
* Windows Command Processor has stopped working (three times)
* Find String (QGREP) Utility has stopped working
* Keyboard History Utility has stopped working

When I traverse into a directory that contains a Git repository:
* Git for Windows has stopped working
* Windows Command Processor has stopped working

When I run "git status" in such a directory:
* Git for Windows has stopped working (twice)
* Windows Command Processor has stopped working
This also does not produce any output when it should.

I'm running Windows 10 with Avecto Defendpoint and CylancePROTECT. It might be that some of this interferes but I haven't found any evidence of that. No other programs have similar symptoms.

**Comment by mwhitis** [comment]
+1 for me... seeing the same thing.  We run McAfee AV and Verdasys Digital Guardian.  Not sure if this is a cmder issue or a conemu issue, but it's become unusable over the past 3-4 months.

**Comment by Hubert-Rybak** [comment]
Same here... 2 corporate PCs, on one with Win 7 works, on one with Win 10 not, so may be Win 10 related

**Comment by yehanghanGE** [comment]
same issues here. Win10 PC. Any updates?

**Comment by ikhot** [comment]
still have same problem in 1.3.4

**Comment by nledenyi** [comment]
thought of using cmder for a change but was immediately greeted with this issue - exact same popups as in the first post. Windows 10 Pro, corporate PC (domain controlled group policy settings), McAfee AV. Issue is also present if executed as admin.

**Comment by nathanaelhuffman** [comment]
I had the same issue on Windows 10, but I did find a possible work-around.  Not sure what side effects this causes but if you go to cmder settings and uncheck "Inject ConEmuHk" from the Features screen, this seemed to stop the crashing applications.

**Comment by simberaj** [comment]
Confirming @nathanaelhuffman 's workaround is effective. In my setup, it reduces the "stopped working" messages to a single one issued at cmder exit.

**Comment by tonytronics** [comment]
I am also experiencing this issue with git and Avecto Defendpoint. Any traction on this?

**Comment by daxgames** [comment]
Is this still an issue?

**Comment by scorpioniz** [comment]
yes

**Comment by ravituvar** [comment]
yes, there is still an issue.

**Comment by daxgames** [comment]
This is not a cmder issue.  It is most probably an issue with some antivirus/dlp software integration.
