### ISSUE TITLE
init.bat disappears upon crash (Windows)

### ISSUE THREAD

**Issue by mkalam-alami** [cmderdev/cmder#1447]
When cmder crashes (the latest I got was while duplicating a console), it has a chance of making the `vendor/init.bat` file disappear from the cmder directory. Restoring it afterwards is pretty tricky due to access rights which are somehow restricted (I'm on Windows 7).

My workaround is as following:

- Make sure cmder is stopped
- Create a `tmp/` folder under the cmder root path
- Grab a fresh `init.bat` file from the cmder setup archive, and put it in `tmp/`
- Rename the old `vendor/` folder to `vendor2/`
- Renamde `tmp/` to `vendor/`
- Move all files from `vendor2/` to `vendor/`

This looks unnecessarily convoluted, but anything simpler than that actually fails due to permission errors, even when using an administrator account.

**Comment by MartiUK** [comment]
Are you extracting cmder into "Program Files" or other System protected directories?

**Comment by mkalam-alami** [comment]
Nope the setup folder has no particular permissions. The path is `D:\Apps\cmder`, so no spaces or special chars either.
