### ISSUE TITLE
Firefox tags the latest download as malicious

### ISSUE THREAD

**Issue by CB-Giepa** [cmderdev/cmder#1449]
Hey there,

I just wanted to download the latest version of cmder (v 1.3.2). Unfortunately my Firefox gives me a warning of malware. Hopefully its nothing like that. So I am a little bit confused if there is anything malware like in the latest download. 

Can someone please confirm that there is everthing alright with the download?

**Comment by purefan** [comment]
Its actually the entire domain that is being reported as malicious, so older releases are also marked as dangerous

**Comment by CB-Giepa** [comment]
I also get the error when trying to download files from other github repos. Noticeable is that it happens when the files are hostest on amazonaws.com. So my guess is that is something on this end and has nothing to do with this repo at all.

Firefox and Chrome give me both the same warning. Only IE did nothing and let me download it. I just let my Antivirus Software (ESET) check the .7z file. Nothing found there. So for me everything is alright.

So I am closing the issue because I think the problem is not the repo by itself but rather than the host on amazonaws.com.
