### ISSUE TITLE
CMDER connecting SSH with ppk file

### ISSUE THREAD

**Issue by trenyture** [cmderdev/cmder#1451]
Hi everyone,

In my work they're all using _Putty_ to connect to **SSH into a VPN**, with an Auth File : `auth_key.ppk`

I've worked with **CMDER** for a lot of time now, and I tried to connect with **CMDER** because it's better than _Putty_. Well I made this command : 

`ssh user@127.127.127.127 -p 110 -i "C:\Users\Me\Documents\SSH\auth_key.ppk"`

and then it's asking me the passphrase for key "C:\Users\Me\Documents\SSH\auth_key.ppk" but when I put it, it just asking me again and again... Is there a way to bypass this?

**Comment by daxgames** [comment]
Maybe its the fact that ppk and open-ssh keys use different formats. See: https://unix.stackexchange.com/questions/74545/what-difference-between-openssh-key-and-putty-key

**Comment by jaysassyinfotech** [comment]
Hello,

When i try to run this command in CMDR. Invalid ppk format error display but that ppk file i already used in putty and successfully login.
**ssh root@192.192.192.192 -p 22 -i "C:\Users\HP\Documents\asd.ppk"**
**Load key "C:\Users\HP\Documents\asd.ppk": invalid format
root@192.192.192.192: Permission denied (publickey).**

If there any solution ?

**Comment by daxgames** [comment]
@jaysassyinfotech see my last comment on this thread.  You need to use ssh-keygen to create an ssh key.  ppk is for use with puTTY.

**Comment by mpuri14** [comment]
@daxgames @trenyture did you find away to do this on cmder?

**Comment by trenyture** [comment]
As @daxgames said two years ago, .ppk is for Putty, not CMDER ... I don't think they changed anything ... Sorry

**Comment by ChristophKubik** [comment]
The putty-keygen has an option to convert your .ppk key to a openssh key. Convert your private key and then use the openssh one instead of your .ppk key and it will work!
