### ISSUE TITLE
Hope cmder could support rz/sz to translate files

### ISSUE THREAD

**Issue by onewesong** [cmderdev/cmder#1452]
![image](https://user-images.githubusercontent.com/17920822/28658404-c68b44e4-72dd-11e7-87de-91820ba54efa.png)

![image](https://user-images.githubusercontent.com/17920822/28658414-cd5f4680-72dd-11e7-9d13-a9dca6e9fc99.png)

it all just jamming here

**Comment by daxgames** [comment]
If you can find standalone 'rz.exe' and 'sz.exe' that do what you want and add them to '%cmder_root%/bin' then you could do this yourself.

**Comment by NewCoderQ** [comment]
@onewesong Did you solve the problem, I also encountered the problem.

**Comment by NewCoderQ** [comment]
@onewesong  Did you solve the problem, I also encountered the problem.

**Comment by mizyanlu** [comment]
1. install `ubuntu `subsystem on you windows.
2. install `zssh `on your ubuntu
3. play `rz`/`sz `with `zssh`. (cmder does not support ^@ as hotkey,plz use   `zssh -z ^X`  as hotkey)

by the way,
if you are interested in "ssh session clone" as a replacement of SecureCRT feature, 
add blow to you ` /etc/ssh_config`
```
   ControlMaster auto
   ControlPath ~/.ssh/%r@%h:%p
```

**Comment by leyafo** [comment]
same problem still.

**Comment by leyafo** [comment]
@daxgames How can i fix this problem? I have copied 'rz.exe' and 'sz.exe' into '%cmder_root%/bin'. It has nothing changed.

**Comment by daxgames** [comment]
@leyafo error messages?

`%cmder_root%/bin` is added to the path.  If you put the files in the path they should run. That's the best we can do with a foreign exe file.
