### ISSUE TITLE
"Reset..." option in Settings LOSES "{cmd::Cmder}" startup task option!

### ISSUE THREAD

**Issue by peternann** [cmderdev/cmder#1462]
Yes, pretty fatal...

All I did was this:
1) Extracted 'full' package, on Windows 7
2) Ran Cmder first time - All fine
3) Went into settings to mess with font options. I messed up settings, forgot original...
4) Clicked on 'Reset...' option
5) A window "ConEmu 161022..." comes up. The second pull-down on that screen DOES NOT list Cmder. Forced to pick something else.
5) After this, I can no longer start CMDER shells!!!

Looking in Settings->Startup, there is no {cmd::Cmder} option in 'Specified named task'!

It seems the 'Reset' function does not actually reset to 'as-installed' settings. In fact, it has a rather fatal outcome. I had to delete and re-extract from zip...

**Comment by james-robson** [comment]
@peternann same here, thought I was going crazy but no, ConEmu is back to some pre-Cmder default state. Very annoying, looks like I'll have to bite the bullet and reinstall when I have time.

**Comment by daxgames** [comment]
Sorry for the inconvenience but this is not unexpected since conemu is a self contained product that is used by cmder.  We have no control over what it does.  It does not know it is being used with the other components as a part of cmder.  Reset does exactly that, reset to conemu default that knows nothing about cmder

**Comment by peternann** [comment]
Eh. Fair enough. Wasn't aware how all the separate bits hang together.

You've got to admit - It's a pretty nasty trap for the uninitiated. Leads to a re-install pretty much! (Which I know is very light-weight... But still...)

I presume you can't 'alter the defaults' that ConEmu assigns when that button is hit...

**Comment by daxgames** [comment]
I know but when you loosely integrate disparate products it's unavoidable.  This is not the only situation.

**Comment by GHW2014** [comment]
Try to delete user-ConEmu.xml in config folder.

**Comment by daxgames** [comment]
@GHW2014 to truly resest to cmder default you need to delete 2 files with Cmder shut down:

```
%cmder_root%\config\user_ConEmu.xml
%cmder_root%\vendor\conemu-maximus5\conemu.xml
```
