### ISSUE TITLE
Tab doesn't autocomplete System directories

### ISSUE THREAD

**Issue by holycrepe** [cmderdev/cmder#1464]
If a folder has the SYSTEM attribute, tab auto-completion does not work.  Is this intentional, and if so, is there a setting to modify this behavior?

**Comment by daxgames** [comment]
Explain?  Works for me.

```
C:\Users\dgames.DTG>attrib ntuser[tab][tab] --> C:\Users\dgames.DTG>attrib ntuser.dat.LOG1[enter]
A  SH              C:\Users\dgames.DTG\ntuser.dat.LOG1
```

**Comment by holycrepe** [comment]
Hmm your first entry seems to show it working, here is what happens for me:
```
C:\Users\Avi
λ attrib Vide[tab] → attrib Videos[enter]
     R             C:\Users\Avi\Videos

C:\Users\Avi
λ attrib Vide[tab] → attrib +S Videos[enter]
```

The following does not work now that the folder is +S:
```
C:\Users\Avi
λ attrib Vide[tab] → no autocomplete
```

Once I remove the SYSTEM attribute it works:
```
C:\Users\Avi 
λ attrib -S Videos[enter] 

C:\Users\Avi
λ attrib Vide[tab] → attrib Videos[enter]
     R             C:\Users\Avi\Videos
```

Autocomplete works fine when invoking cmd.exe directly, without cmder.

**Comment by holycrepe** [comment]
I've done some more investigation. The problem remains on a virtual machine, and another computer so the issue is not related to my computer's configuration. 

Can you confirm that you had clink enabled during your tests?

**Comment by daxgames** [comment]
I did yes.

**Comment by shrivatsahosabettu** [comment]
When I type the folder in the directory it doesn't auto complete 

 Example:
```
F:\
λ ls
'!qhlogs.doc'    'Lux photos'/  'My Lockbox'/  'System Volume Information'/   obj/
'$RECYCLE.BIN'/   Movies/        My-Lockbox/    default.gpr                   src/

F:\
λ cd "My
My Lockbox\  My-Lockbox\
F:\
```

But in comemu it is like as below, on 2nd time the tab press the, next matched folder name is coming.

![webp net-gifmaker](https://user-images.githubusercontent.com/12061573/36348263-f4e5cdcc-1491-11e8-92ec-7149ca7115e5.gif)
