### ISSUE TITLE
Citrix and UNC path support

### ISSUE THREAD

**Issue by mikeychan** [cmderdev/cmder#1465]
Wanting to use Cmder in my Citrix Xen Desktop environment. My Documents is usually mapped to a fully qualified UNC pathname. Cmder appears to be having a lot of problems...
![image](https://user-images.githubusercontent.com/30942369/29236620-4c73d1ce-7f50-11e7-92ba-80a0d0aa78a2.png)

There also appears to be lots of problems updating...this update appears specific to ConEmu.
![image](https://user-images.githubusercontent.com/30942369/29236589-e064e766-7f4f-11e7-9abd-377c486b8328.png)
![image](https://user-images.githubusercontent.com/30942369/29236596-fe996842-7f4f-11e7-920d-6e540f515422.png)
![image](https://user-images.githubusercontent.com/30942369/29236605-247f274a-7f50-11e7-898c-c81b6030a3a7.png)

I've tried running under the Administrative account privileges but this doesn't appear to improve the situation.

**Comment by daxgames** [comment]
The unc path issue is not a cmder issue.  It is a cms.exe issue.  May be able to work around this using pushd and popd to dynamically map a drive letter to the required unc path in %cmder_root%\vendor\iniit.bat.  I am not somewhere in can test it right now.

The update is indeed for conemu and not the whole cmder package.  I personally do not take conemu updates via this dialog and would recommend disabling it as I have had mixed results after completing the process.

**Comment by daxgames** [comment]
PR #1456 may address this.  Asked the submitter to make a couple of changes.

@mikeychan can you confirm if this would fix your issue?

**Comment by mikeychan** [comment]
@daxgames that has resolved the error. I'm now getting [module matchers not found error](https://github.com/cmderdev/cmder/issues/949).

**Comment by mikeychan** [comment]
Just FYI, I was also able to resolve the error if I first mapped a drive letter to the location where cmder is located. For example, net use x: \\server\directory.

If cmder folder is placed under x:\, it all works fine as well.

**Comment by mikeychan** [comment]
Have closed this issue as there is an existing module matchers not found error issue logged.
