### ISSUE TITLE
ls not working

### ISSUE THREAD

**Issue by kasperbisgaard** [cmderdev/cmder#1468]
Hi.
When i try to run "ls" command, i get a popup error saying "The code execution cannot proceed because cygintl-2.dll was not found."
I have tried re-downloading cmder, but it doesn't fix the problem.
![skaermbillede 2017-08-17 08 51 39](https://user-images.githubusercontent.com/9379915/29399431-81da85ba-8329-11e7-9e94-f5ecc70a61a3.png)

**Comment by daxgames** [comment]
Probably not a cmder issue.  My guess is you are not running cmder's `ls.exe` but another from your path.  I do not think the file it is complaining about is part of cmder.

`echo %path%` or `echo $PATH` output?
