### ISSUE TITLE
Control key not behaving as expected when SSH-ed

### ISSUE THREAD

**Issue by FredDeschenes** [cmderdev/cmder#147]
When in the "Windows command prompt" mode, holding the control key and using the left and right arrow keys jumps between words and pushing z reverts the last keystroke/command.

![workingbefore](https://f.cloud.github.com/assets/313707/2236471/913355c4-9b5f-11e3-9411-09fc737ec5d3.PNG)

After SSH-ing into another machine though, holding the control key as no effect when using either the arrow keys or z.
![sshednotworking](https://f.cloud.github.com/assets/313707/2236480/e0852508-9b5f-11e3-82ac-c1c24bfa76ca.PNG)

The keystroke is still being recorded though since I can still control-c to stop a running process.
![140221202407](https://f.cloud.github.com/assets/313707/2236488/1ab14e32-9b60-11e3-847f-bcf0997d26d4.png)

This happens on both computers that I have tried it on (Windows 8.1 and Windows 7).

**Comment by ilyaigpetrov** [comment]
In my case `Ctrl-C` didn't work in `Node.js/gulp`.  
I've unchecked `Inject ComEmuHk` option in settings and it helped.

**Comment by songzhiyong** [comment]
why closed? I have same problem on windows 10
