### ISSUE TITLE
Change .ssh directory folder

### ISSUE THREAD

**Issue by TautFlorian** [cmderdev/cmder#1472]
Hey,

is it possible to Change the Folder of the ssh keys?

Im running cmder on a usb drive and want to save the ssh keys on it too.

Thank you guys

**Comment by lukescammell** [comment]
I'd also like to know how to do this easily. If I find a way I'll add it, but if someone already knows...

**Comment by lukescammell** [comment]
I have a workaround using `%CMDER_ROOT%\config\user-profile.cmd`

Try using this gist and saving your SSH key to `%CMDER_ROOT%\config\.ssh`

You will need to `mkdir .ssh` in cmder to create that directory, Windows Explorer won't let you create a directory with a leading full stop.

https://gist.github.com/lukescammell/743bd91cf2da0ed1d2cd699a2fdc3698
