### ISSUE TITLE
Git Blame Stuck After (Click Ctrl+C)

### ISSUE THREAD

**Issue by elit69** [cmderdev/cmder#1473]
Step to reproduce:
1. Go to some repo 
2. git blame sourcecode.xx (which longer than current window screen)
3. Ctrl+C

![capture](https://user-images.githubusercontent.com/4709476/29572068-5681fe9c-8785-11e7-81e8-e097e5339058.PNG)

Now you are stuck in git blame while trying to blame other dev.

**Comment by ogrim** [comment]
I sometimes get stuck into this `log file:` stuff, usually I get out of this by deleting whatever got typed into the prompt, and pressing ctrl-c. If it seems stuck, I kill `less.exe` in the Windows Task Manager.

Anyways, the proper way to exit less is to press `q`.

**Comment by elit69** [comment]
Never mind. I am using Hyper with Git Bash now.
