### ISSUE TITLE
Add to the Windows Store

### ISSUE THREAD

**Issue by Odonno** [cmderdev/cmder#1477]
Is it planned to publish cmder in the Windows 10 Store?

**Comment by lukescammell** [comment]
Given the UWP and Windows 10+ requirement, I very much doubt it.

**Comment by Odonno** [comment]
@lukescammell Even with the Desktop Bridge? https://developer.microsoft.com/en-us/windows/bridges/desktop

**Comment by lukescammell** [comment]
Interesting link, thanks :)

That does seem to get rid of the UWP requirement. But I don't believe it does anything to resolve the Windows 10 requirement from the Windows Store. Or am I reading that wrong?

**Comment by Odonno** [comment]
@lukescammell Of course, you can only target Microsoft supported platforms using UWP (or UWP-like solution). If you use the Desktop Bridge, you will only target Windows 10 users on tablets or desktop.
