### ISSUE TITLE
The system cannot find the path specified.

### ISSUE THREAD

**Issue by moazam1** [cmderdev/cmder#148]
I am using Windows 7 64 bit. Whatever command I run I see an error at bottom: "The system cannot find the path specified."

Here is an example:

C:\Users\Moazam
λ d:
The system cannot find the path specified.
C:\Users\Moazam
D:\

**Comment by moamenmct** [comment]
The system cannot find the path specified.

**Comment by asma1588** [comment]
i am having the same issue. old solution doesnt fix the problem. i get this The system cannot find the drive specified. error for all commands or when try to change the drives
