### ISSUE TITLE
stdout issue

### ISSUE THREAD

**Issue by dimyG** [cmderdev/cmder#1484]
![image](https://user-images.githubusercontent.com/12560596/30315020-436d1c3e-97ab-11e7-9a1e-83081592eb05.png)

I just downloaded release 1.3.2 and it seems that there is an issue with stdout or something.
For example when I run `heroku redis:info` only one line is returned and the rest of the response is blank as you can see in the picture. But if I redirect the output to a file the whole response is written. 

Am I missing something?

**Comment by ReGrantDev** [comment]
I am having a similar same issue using 1.3.2 and 1.3.0. 

Normally I use a bash prompt but the same thing happens with a normal cmd prompt or Powershell. For me it only happens with grunt output but I've never seen it happen anywhere else.

Here is some sample output:

![image](https://user-images.githubusercontent.com/1722510/30504037-a483b47e-9a3a-11e7-8ff5-5cc0e1f82ddb.png)

However if I select the area with the mouse, now I see the text 'eslintTest1 task' is there but it just being rendered black perhaps?

![image](https://user-images.githubusercontent.com/1722510/30504071-c5e0d16a-9a3a-11e7-8655-3890b21109fe.png)

**Comment by dimyG** [comment]
Actually the same applies to my case too. If I highlight the response I can see that the missing characters are there.

**Comment by ReGrantDev** [comment]
Another piece of info I discovered - if I select Debug / Real Console, in the console that opens the text does not show up even if I highlight it - not sure what this would mean (if anything).

**Comment by stingray21** [comment]
Same here, I cannot see any output from grunt unless I highlight it. Might be a coincidence, but seemed to start after I upgraded from node 6 to 8

**Comment by ReGrantDev** [comment]
Can't say for certain but I think that is the case for me as well.

**Comment by bonesoul** [comment]
same here.

**Comment by nestorneto** [comment]
same here
