### ISSUE TITLE
issue with vagrant command

### ISSUE THREAD

**Issue by dimyG** [cmderdev/cmder#1485]
v.1.3.2

It seems that vagrant there is an issue with vagrant command. For example when I run `vagrant up` nothing happens. There is no return message and the command has no effect. 

![image](https://user-images.githubusercontent.com/12560596/30315333-3bbfc7ce-97ac-11e7-9b47-400db288dec4.png)

**Comment by goutkannan** [comment]
Do you have the Vagrant file in "zakanda01"folder?

**Comment by dimyG** [comment]
Yes the vagrant file is there. The command runs just fine from the Windows Command Prompt or Console2

**Comment by dimyG** [comment]
No vagrant command runs with cmder. For example when I bring up a virtual machine with vagrant up (using command prompt) and trying to connect to it from cmder with vagrant ssh, nothing happens.

**Comment by goutkannan** [comment]
It looks like cmder is not reading your "PATH" environment variable, Can you provide the screen shot of your "Settings" -> "Startup" -> "Environment". It must be ideally "set PATH=%ConEmuBaseDir%\Scripts;%PATH%"

**Comment by dimyG** [comment]
It seems to be fine

![capture](https://user-images.githubusercontent.com/12560596/31219827-2fc24618-a9c7-11e7-922f-fb120de8a62e.PNG)

**Comment by Katario** [comment]
Hello,
I had the same issue few days before, and I solved it by adding a "[provider](https://www.vagrantup.com/docs/cli/up.html)" parameter : 
"vagrant up --provider=virtualbox"

**Comment by heroselohim** [comment]
You require Git installed [Git for Windows](https://gitforwindows.org)

Change this setting:
Settings / Startup / Specified named task / **bash::bash**
(close and reopen)

Solved both for me:  vagrant up & vagrant ssh
