### ISSUE TITLE
Double ctrl-c to terminate batch job

### ISSUE THREAD

**Issue by grokky1** [cmderdev/cmder#1488]
When a batch file is running, and I press `ctrl-c` it shows
> Terminate batch job {Y/N)?

In many Node apps it's common to press ctrl-c then ctrl-c and that "answers" the question as yes.

And clink [supports this feature](https://github.com/mridgers/clink/issues/307#issuecomment-91145742) using the command `clink set terminate_autoanswer 1`.

But this doesn't work for me. When I run `clink set` it shows that the settings path is `C:\PROGRA~2\cmder\config/settings` instead of the `%APPDATA%` path. There is [a workaround](https://github.com/mridgers/clink/issues/405#issuecomment-236512392), but I'm not sure how to configure it with cmder.

Regardless, what do I need to do to enable this feature with cmder?

**Comment by grokky1** [comment]
Can you give me an idea instead of just closing?

**Comment by Stanzilla** [comment]
Try making a report on the ConEmu project please

**Comment by eriegz** [comment]
@grokky1 I realize I'm 3 years late to answering your question, but did you know you can literally just type:

```clink set terminate_autoanswer 1```

...into your cmder terminal and hit "Enter" and it will set this behaviour for you? This change will persist in any new tabs that you create, and persist after you close + relaunch the application! I found the answer from [this page](https://github.com/cmderdev/cmder/wiki/Customization#terminate-batch-job-yn).

Say goodbye to hitting `Ctrl + C` twice!
