### ISSUE TITLE
Why does my cmder console cannot use basic cd (directory_name) 

### ISSUE THREAD

**Issue by abrhambas01** [cmderdev/cmder#1492]
I used cmder with laragon before and when i used it, it instantly integrated with git so i get those unix and git commands but now I've reformatted my pc and just used only cmder not that laragon, and how can i integrate it with git bash so that i can use unix commands.? Can you assist me in this matter please ?

**Comment by DRSDavidSoft** [comment]
Personally, I use Cygwin with Cmder, which provides a near-_real_ implementation of Gnu's tools (unix commands) and an amazing Bash.

You can also use the vendored Git bash with Cmder, but it's less powerful.

### Running Nano in Cygwin with Cmder:
<img width="565" alt="cygwin_nano_cmder" src="https://user-images.githubusercontent.com/4673812/36929255-758a22fa-1ea3-11e8-811e-16ca40506d45.png">


### Running VSCode with Cygwin on Cmder:
<img width="565" alt="cygwin_nano_cmder" src="https://i.imgur.com/RKN3Avl.gif">
