### ISSUE TITLE
How to use msys2 ? 

### ISSUE THREAD

**Issue by dridk** [cmderdev/cmder#1493]
Could you explain how to configure cmder with msys2 ?

**Comment by phizaz** [comment]
I found this, create a new task and use:
"set MSYSTEM=MINGW64 & "C:\msys64\usr\bin\bash.exe" --login -i" for Mingw64 shells
and "set MSYSTEM=MSYS" for MSYS shells.

**Comment by essethon** [comment]
I found this: [Integrate MSYS2 into Cmder](https://zyzyz.github.io/en/2017/10/Integrate-MSYS2-into-Cmder/) from @zyzyz 's blog.
