### ISSUE TITLE
Clink Autocompletions should work for git aliased commands

### ISSUE THREAD

**Issue by youfeis** [cmderdev/cmder#1495]
It is somewhat mentioned here:  https://github.com/vladimir-kotikov/clink-completions/issues/24
But it didn't go any further except for adding alias itself to auto-completion, which is not really useful.

The problem description:

Checking if I'm having alias 
`> git config --get-regexp alias 2>nul`
shows all the alias:
~~~~
alias.co checkout
alias.cm commit
alias.st status
alias.br branch
alias.mg merge
alias.lg log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit`
~~~~

Now type `> git checkout f` then tab, it autocompletes to `> git checkout feature/1/header-slide`
However typing `> git co f` then tab won't show anything for auto-completion, which is appeared to be malfunctioning to me.

My workaround solution looks like this: Edit `cmder\vendor\clink-completions\git.lua` file, find the line starting with `local git_parser`, then edit the parameter of the parser function, ensure that for all the aliased command, I create an copy of entry identical to what real command is, and replace the command to my alias:

~~~~
...
        "check-mailmap",
        "check-ref-format",
        "checkout" .. parser({checkout_spec_generator},
            "-q", "--quiet",
            "-b",
            "-B",
            "-l",
            "--detach",
            "-t", "--track",
            "--orphan",
            "-2", "--ours",
            "-3", "--theirs",
            "-f", "--force",
            "-m", "--merge",
            "--overwrite-ignore",
            "--conflict",
            "-p", "--patch",
            "--ignore-skip-worktree-bits"
        ),
        "co" .. parser({checkout_spec_generator},
            "-q", "--quiet",
            "-b",
            "-B",
            "-l",
            "--detach",
            "-t", "--track",
            "--orphan",
            "-2", "--ours",
            "-3", "--theirs",
            "-f", "--force",
            "-m", "--merge",
            "--overwrite-ignore",
            "--conflict",
            "-p", "--patch",
            "--ignore-skip-worktree-bits"
        ),
        "checkout-index",
        "cherry",
...
~~~~

it would be nice if something handles the git alias auto completion out of the box...

**Comment by mattdkerr** [comment]
You should really file this issue over at the clink GitHub though https://github.com/mridgers/clink/

**Comment by crunchy234** [comment]
Just wondering if there is a link to the issue created on [clinks issue board](https://github.com/mridgers/clink/issues)?
