### ISSUE TITLE
Win10 cmder does not create alias in configs folder

### ISSUE THREAD

**Issue by ScottYang36** [cmderdev/cmder#1496]
It shows error "\Microsoft was unexpected at this time."

![capture](https://user-images.githubusercontent.com/25097121/30679074-586f07e4-9ec9-11e7-83e5-b6f4baab5e4b.PNG)

**Comment by daxgames** [comment]
Don't know about the \Microsoft but 'ls' is not part of cmder mini.

**Comment by ScottYang36** [comment]
Actually， I use full version at first，it did not work also, so I tried the mini one, they have the same issue.

**Comment by mattdkerr** [comment]
No repro for me on two machines

**Comment by jsturtevant** [comment]
I had this issue and was able to fix it by removing the quotes in my path as mentioned in #1222.
