### ISSUE TITLE
Jest: "Test run was interrupted." Happens when run in cmder

### ISSUE THREAD

**Issue by thekip** [cmderdev/cmder#1499]
related issue in jest repo: 

https://github.com/facebookincubator/create-react-app/issues/2649

For me seems it happens all the time when jest in interactive watch mode. It not depends on tapping enter, even after file change it stops with this error. 

In cmd.exe works perfect. 

So I can provide all additional info if needed.

**Comment by michaelklopf** [comment]
Somewhere between the last two days, something makes that problem occur with my project too.

I've read somewhere that it could be related to enter key actions that come from nowhere.

Or it could be related to anti-virus updates. We have Sophos on our company notebooks, could be stemming from a recent update this week.

**Comment by ArmorDarks** [comment]
Same issue here :(

I have a feeling that it is more related to ConEmu itself, not cmder.

**Comment by nogenem** [comment]
No news about this? I'm having the same problem... ;(

**Comment by cdtinney** [comment]
I'm also having this issue.
