### ISSUE TITLE
"Duplicate root" crashes cmder and deletes init.bat

### ISSUE THREAD

**Issue by 0ctothorp** [cmderdev/cmder#1503]
So my problem is that when I click right mouse button on active tab -> Restart or duplicate -> Duplicate root, a new tab opens correctly with the same path as in the tab that I wanted to duplicate, but as soon as I try to type something, cmder window disappears without any information about what happened. So I assume it crashed. 
![bez nazwy](https://user-images.githubusercontent.com/5238816/31012217-46ff76da-a511-11e7-9f43-57d42c2e61f4.png)

Then when I open up cmder again it shows this:
![przechwytywanie](https://user-images.githubusercontent.com/5238816/31012274-7cd0a57c-a511-11e7-9ff4-d5357c6635ef.PNG)
and the init.bat script is indeed not there, like it has been deleted.

The only way I can get around this is just making a fresh install of cmder and not using the duplicate feature.

Might be also helpful: after the crash system won't let me copy anything into "vendor" directory. It says it requires admin privileges although I have them. The system restart works for this one.

I'm on a Windows 10 64-bit.

**Comment by DRSDavidSoft** [comment]
@0ctothorp Is this issue fixed? I just tested on my machine and it duplicated without any issue.
<img width="565" alt="fixed_or_not" src="https://user-images.githubusercontent.com/4673812/36929319-27e3b6aa-1ea4-11e8-8c1d-def80a04feeb.png">

**Comment by 0ctothorp** [comment]
@DRSDavidSoft I just checked it and indeed it works. I think the issue can be closed.

**Comment by DRSDavidSoft** [comment]
@Stanzilla could you close the issue?
