### ISSUE TITLE
Win+Left & Win+Right don't work when caption (window title bar) is hidden

### ISSUE THREAD

**Issue by rococode** [cmderdev/cmder#1506]
![](https://i.imgur.com/nlZeq7d.png)

When the caption is hidden, hitting Win+Left does not snap the window to occupy half of the screen space (horizontally). When the caption is visible, Win+Left works as expected (same behavior as other programs).

This is a bug, right?

**Comment by rococode** [comment]
Given that Win+Down works with its expected behavior in the same situation, I suspect this is still a bug. Bumping for activity.

**Comment by daxgames** [comment]
This has to be a conemu setting or other conemu issue.  Ask the conemu devs.
