### ISSUE TITLE
React-native build comments not showing up

### ISSUE THREAD

**Issue by JatinYadav1307** [cmderdev/cmder#1507]
![](https://vgy.me/QluFed.png)

Nothing is showing up.

How do I fix this?

**Comment by Kevin-Chung** [comment]
Same issue. Not sure what is causing it

**Comment by nilkesede** [comment]
Maybe the text color is the same as the background color?!

**Comment by Kevin-Chung** [comment]
@nilkesede Yes that is what's happening, you can highlight the text and it will show up. The issue is that for some reason react-native cli is causing the text color to match the background

**Comment by miluokesiji** [comment]
Feature->Colors->Extended foreground colors with background 
Set to "#0".
when i use the  <Ubuntu> scheme，maybe it's unnecessary.

**Comment by fisherwise** [comment]
Same problem. Any fix?
