### ISSUE TITLE
Cmder not rendering ctrl characters

### ISSUE THREAD

**Issue by dankell** [cmderdev/cmder#1513]
We've just updated to the latest version of the **PM2** monitoring  tool for NodeJS

One of the more obvious changes is to the `pm2 monit` command which presents the details as 4 panes separated by `x(B` and `xx(0xx(B` command strings.

The first image on [this ](http://pm2.keymetrics.io/docs/usage/monitoring/)page illustrates what _should_ be seen

The command codes do not render in a standard cmder terminal. cmd.exe properly renders and a cmder Powershell terminal also renders correctly.

Thoughts?

**Comment by namanyayg** [comment]
I have the exact same issue, it also breaks a lot of things when I'm in `ssh`. 

`pm2 monit` is a very obvious example.

My `locale` seems okay:

```
LANG=
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_ALL=
```

Anything that worked for you?
