### ISSUE TITLE
Right click open current file

### ISSUE THREAD

**Issue by th3nate** [cmderdev/cmder#1515]
i want to right click a .bat file and to have a context menu that will run the current file in Cmder.
anyone have a solution for this implementation? 
i can only find how to open directories with right click but not a file.

**Comment by nmgwddj** [comment]
I have the same problems.
How to start cmder.exe with a .bat file?

**Comment by daxgames** [comment]
It's not possible, today.

Can I get some clarification on this?

Why?  Explain the use case, how would this be used, be spexific.

Is this *.bat file supposed to run to completion and exit or remain open as an interactive shell?

Can you do this with cmd.exe, if so why do you need cmder to do it?

**Comment by nmgwddj** [comment]
@daxgames Thank you, I have solved this problem: https://conemu.github.io/en/DefaultTerminal.html
For your questions, there are the following reasons:
  - Cmder color, background, fonts are more comfortable
  - I often use some bat files to compile the program, so the interface is basically a long stay.
