### ISSUE TITLE
Open SSHLegacy Options

### ISSUE THREAD

**Issue by abiwifi** [cmderdev/cmder#1516]
Hi 

I am trying to ssh into brocade switch, using cmder, as it still uses Legacy algorithms I get this below error.

"Unable to negotiate with 10.19.32.7 port 22: no matching key exchange method found. Their offer: diffie-hellman-group1-sha1"

I can still use "ssh -o KexAlgorithms=+diffie-hellman-group1-sha1 -oHostKeyAlgorithms=+ssh-dss est@10.19.32.7" and ssh into the device, but I need to use when logging into every switch every time.

I also found a solution to overcome this, I need to add  "Host 192.168.8.*  HostKeyAlgorithms=+ssh-dss" in the ~/.ssh/config file.

I do not find the config file inside .ssh folder instead I find known_hosts. I was not able to find a way to add this in cmder.

Could anyone help me in adding the above in file .ssh/config in cmder?

Thank you in advance.

Regards,
Abilash PR

**Comment by daxgames** [comment]
Just add the %userprofile%/.ssh/config file and it will be used.
