### ISSUE TITLE
cmder.net gives certificate error with https

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [cmderdev/cmder#1519]
Expected: defaults to https.

Actual: https://cmder.net and https://www.cmder.net give a certificate error.

![image](https://user-images.githubusercontent.com/3335181/31782537-120011fc-b4b0-11e7-9ece-fab88e4dcb6c.png)

**Comment by MartiUK** [comment]
cmder.net is hosted through github pages and it does not support https with custom domains.

**Comment by Stanzilla** [comment]
@MartiUK could use CloudFlare though? https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/

**Comment by rossinimartins** [comment]
Another option would be Netlify: https://www.netlify.com/docs/ssl/

**Comment by Stanzilla** [comment]
Wrong repo though. Go here https://github.com/cmderdev/cmderdev.github.io
