### ISSUE TITLE
Ctrl + Tab not working on windows7 x64，disabled

### ISSUE THREAD

**Issue by F5F5** [cmderdev/cmder#1520]
![image](https://user-images.githubusercontent.com/15978277/31808435-aef60d04-b5a5-11e7-84c0-b996aa28ae69.png)

How to switch next tab use hot-key?

Please help me,thank you!

**Comment by angly-cat** [comment]
Do you have `Internal CtrlTab` option enabled? If yes, why not trying set hotkey to that `User`/`Switch next console`?

![image](https://user-images.githubusercontent.com/5000549/33193323-f996c3be-d0f1-11e7-9b25-f19567be381f.png)

**Comment by F5F5** [comment]
## Thank your answer.

### It was checked, but don't work.

![image](https://user-images.githubusercontent.com/15978277/33195407-1c477af0-d112-11e7-91db-b5345c66cbba.png)

### And the hotkey setting can't work too.

![image](https://user-images.githubusercontent.com/15978277/33195460-b9d7fae2-d112-11e7-9008-b6a85e8d6ba0.png)
