### ISSUE TITLE
cmder removed by Windows Defender as Win32/Rundas.B

### ISSUE THREAD

**Issue by dschoeni** [cmderdev/cmder#1524]
Today, Windows Defender removed my Cmder.exe + Cmder.Ink, identified as "Win32/Rundas.B"
I did not update it or anything - Might this be a misidentification due to updated definitions?

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Trojan:Win32/Rundas.B

**Comment by e-morency** [comment]
I concur, just had it removed by Windows Defenders as well.

Virus definition version: 1.253.1093.0
Malware definition version: 1.253.1093.0

**Comment by dschoeni** [comment]
Well, either it is real and spreads through the cmder update (what I don't believe, as you have to confirm every update) or we simply have a very agg

**Comment by outdooricon** [comment]
I'm seeing this as well @Stanzilla , why is it closed?

**Comment by Stanzilla** [comment]
Because it still is a false positive
