### ISSUE TITLE
Rightclick paste (Questionen)

### ISSUE THREAD

**Issue by sinnlosername** [cmderdev/cmder#1526]
Is it possibke to disable paste on rightclick? I already searched for rightclick in settings but I couldn't find it.

**Comment by lukescammell** [comment]
Yes, this is built in to the settings and you can change it by following these steps:

1. Win+Alt+P (to open settings).
2. Select "Mouse" in the left tree.
3. Under the "Mouse button actions", in the middle, change the value of "Right:" to "<None>"
4. Save settings.

Screenshot attached.
![conemu64_2017-10-25_15-38-46](https://user-images.githubusercontent.com/108340/32004950-f196bed0-b99a-11e7-835b-d88369afe8ac.png)
