### ISSUE TITLE
non-functional arrow keys in Windows Store versions of Ubuntu and OpenSUSE

### ISSUE THREAD

**Issue by JeffMelton** [cmderdev/cmder#1528]
I just reinstalled WSL on Fall Creators Update and installed Ubuntu and OpenSUSE from the Store and found that arrow key navigation is broken. Updated Cmder to latest from stable; same story there.

**Comment by jcaudle** [comment]
I just tried [this solution](https://github.com/Maximus5/ConEmu/issues/629#issuecomment-334050682). Does it work for you?

**Comment by JeffMelton** [comment]
Yes, with some tweaks it does. Thanks. I didn't think to look upstream. >.<

**Comment by nilskp** [comment]
@JeffMelton Doesn't work for me. What tweaks did you do?

**Comment by JeffMelton** [comment]
@nilskp Here's what I have for that task:

`ubuntu -cur_console:p`

**Comment by nilskp** [comment]
@JeffMelton That's what I'm doing, but arrow keys remain unresponsive.

**Comment by JeffMelton** [comment]
Sorry, @nilskp. I'd recommend opening another issue in hopes the developers can give you a little more input. Mine's working as expected, so there's likely to be some difference between our installs, or some other problem behind your trouble.
