### ISSUE TITLE
Cmder lambda and info virtualenv not appearing or the color is wrong

### ISSUE THREAD

**Issue by adautoserpa** [cmderdev/cmder#1529]
Lambda character, not appearing. I believe the color is the same background, but I could not change.
cmder version 1.3.3
OS: Windows 10 Fall Creators Version 1709 build 16299.19

![1](https://user-images.githubusercontent.com/1083945/32140186-7903205c-bc3e-11e7-8336-964fbf0d2ed6.jpg)
![2](https://user-images.githubusercontent.com/1083945/32140187-7b6ffcf2-bc3e-11e7-89f6-3caed628adf8.jpg)
![3](https://user-images.githubusercontent.com/1083945/32140189-7d224082-bc3e-11e7-8fdd-5cbbd451e0c6.jpg)
![4](https://user-images.githubusercontent.com/1083945/32140190-7f213758-bc3e-11e7-9030-9aa05df17d53.jpg)

Thanks in advance
Sorry for my English

**Comment by Stanzilla** [comment]
Hey there, can you check out if https://github.com/cmderdev/cmder/commit/a8d32611a9b93cfb58f0318ae4b8041bc8a86c68 fixes it? Thanks!

**Comment by adautoserpa** [comment]
It worked !!! Thanks.

In Contingency, I had downloaded the conemu portable and replaces the original conemu of the version 1.3.3, but is now solved. ;-)

Just need to update the builds.

Closed

**Comment by adautoserpa** [comment]
@Stanzilla 

I preferred to replace ConEmu portable, **the color of the text λ and venv are in gray**. I think this is the cmder default.

I'm practically out of time so I could not pinpoint what the problem was. I did some testing here and when I replaced the files
conemu-maximus5 \ ConEmu \ ConEmuHk64.dll
conemu-maximus5 \ ConEmu64.exe

ConEmu updated and fixed the problem.

I am not familiar with the project, but perhaps re-packaging with the current version of ConEmu could solve the problem.

Follow the print with powerline installed ;-)

![1](https://user-images.githubusercontent.com/1083945/32147366-55a6098c-bccd-11e7-8dd0-0387dbca798b.png)

**Comment by Stanzilla** [comment]
@adautoserpa So which version of ConEmu did you download and install? Because 1.3.3 actually comes with the latest alpha version. So if you downloaded the latest release version, you actually downgraded ConEmu and only delayed running into the problem

**Comment by adautoserpa** [comment]
@Stanzilla I am using the stable version 161 206.
I downloaded alpha version 171025 and did the same procedure. The bug appears.
This leads to believe that it is some bug in the conemu or some incompatibility with the alpha version.

**Comment by Stanzilla** [comment]
Yup makes sense, thank you for checking!

@maximus5 Intended change or regression?

**Comment by Maximus5** [comment]
To set highlighted foreground colors it's recommended to use `ESC [ 90..97 m` instead of ambiguous BrightOrBold.
Intended change.

**Comment by adautoserpa** [comment]
@Stanzilla  and @Maximus5 
We could use the code below to have the same result as the previous version of cmder, dark gray.

`local cmder_prompt = "\x1b[1;32;40m{cwd} {git}{hg}{svn} \n\x1b[1;30;90m{lamb} \x1b[0m"`
or
`local cmder_prompt = "\x1b[1;32;40m{cwd} {git}{hg}{svn} \n\x1b[30;90m{lamb} \x1b[0m"`

**Comment by Stanzilla** [comment]
@vbm suggested using `39m` because that's the default color of foreground at startup -> https://github.com/shiena/ansicolor/blob/master/README.md
I'm inclined to leave it like that.

**Comment by 0123guoxiao** [comment]
I use this：
local cmder_prompt = "\x1b[1;32;40m{cwd} {git}{hg}{svn} \n\x1b[1;37;40m{lamb} \x1b[0m"
then the color is the same as code，i like it. nice.

**Comment by rhpijnacker** [comment]
Just to let you know: Just downloaded the minimal version from the cmder home page (v1.3.3/cmder_mini.zip) and ran into the same issue.

**Comment by xiaolei16fan** [comment]
@rhpijnacker  I resolved this problem just open `C:\cmder\vendor\clink.lua` file with my editor, then located to 41 line and replace 30 with 39. Just like:
```
Old: local cmder_prompt = "\x1b[1;32;40m{cwd} {git}{hg}{svn} \n\x1b[1;30;40m{lamb} \x1b[0m"
New: local cmder_prompt = "\x1b[1;32;40m{cwd} {git}{hg}{svn} \n\x1b[1;39;40m{lamb} \x1b[0m"
```

refer to :  [a8d3261](https://github.com/cmderdev/cmder/commit/a8d32611a9b93cfb58f0318ae4b8041bc8a86c68)

**Comment by adautoserpa** [comment]
@Stanzilla Can I close the issue?
Then tell us when to leave the build with the fix. Thank you!

**Comment by Stanzilla** [comment]
I think so, yeah. 1.3.4 is out now

**Comment by freiro** [comment]
@Stanzilla the official cmder download link leads to version 1.3.3.

**Comment by Stanzilla** [comment]
@freiro I know, the PR updating the links has not been merged yet.

**Comment by vrufine** [comment]
@Stanzilla #worked like a charm 👍 👍 👍
