### ISSUE TITLE
A neat way to add sublime text seamlessly.

### ISSUE THREAD

**Issue by expositor** [cmderdev/cmder#153]
![untitled](https://f.cloud.github.com/assets/6570916/2250370/3365eb5a-9d8f-11e3-9454-728c80a287d6.png)

For all you Windows developer using cmder, here is a neat way to integrate cmder and sublime text to work seamlessly. 

**Step 1:** Create a new folder called 'Sublime Text 3' in the '/cmder/vendor/' location. You should also see the folders /clink, /conemu-maximus5, and /mysgit.

**Step 2:** Download a portable version of Sublime Text 3 from [their website](http://www.sublimetext.com/3) and unzip the content into the newly created Sublime Text 3 folder.

**Step 3:** Then, in the aliases file under /cmder/config/aliases, add:

~~~
subl="%CMDER_ROOT%\vendor\Sublime Text 3\sublime_text.exe" $1 -new_console:s75V
~~~

You can change 'subl' with any alias you want, hopefully one that doesn't conflict with an existing command. 

Like the view above, the -new_console:s75V will split the console horizontally where sublime will take up 75% of the view. You can also change the split behavior. Here are some other examples:

~~~
-new_console:s or -new_console:s50H
~~~
Split will be created to the right, both splits becomes 50%.
![untitled4](https://f.cloud.github.com/assets/6570916/2250361/28287e06-9d8f-11e3-8579-b094a19b750f.png)

~~~
-new_console:s50V
~~~
Split will be created horizontally, both splits becomes 50%.
![untitledg](https://f.cloud.github.com/assets/6570916/2250507/eadae35c-9d90-11e3-981d-397f3531d768.png)

**Step 4:** Start or restart cmder and type 'subl' and a file name. For example:
~~~
C:\Users\Foo
λ subl foo.txt
~~~
Foo.txt should open in sublime text 3 and split your screen. If 'foo.txt' exists, it should open that file, otherwise, it will create a new 'foo.txt' file in your directory. Here, I didn't have a foo.txt file in my directory when I typed that command. After pressing Ctrl S, it created a new foo.txt and saved it in the current working directory. Check out the status on the bottom.

![untitledhj](https://f.cloud.github.com/assets/6570916/2250571/acf856cc-9d91-11e3-85da-6a5018f374af.png)

Of course, to make it look extra integrated, I removed the tabs in sublime. For the minimalists, you can even remove the menu bar and the status bar, so it looks like a complete extension of the cmder. Honestly, I prefer the menu bar.

![untitled2](https://f.cloud.github.com/assets/6570916/2250301/462fd24c-9d8e-11e3-80c9-21ad44e0d816.png)

Remember, you can you can always open the menu again by pressing 'Alt'. Also, in the conemu setting, I changed the tab group in the Features-->settings and checked 'one tab per group'. Again, for the minimalists, you can even remove the tabs completely. Just be sure to remember all your shortcuts!

Minimalist setup right here:

Horizontal Split.
![untitledd](https://f.cloud.github.com/assets/6570916/2250457/46005ae2-9d90-11e3-9edb-952ff46a7e16.png)

Vertical Split
![untitledf](https://f.cloud.github.com/assets/6570916/2250459/48cf4792-9d90-11e3-8635-f5d0a5d8a0a4.png)

Another neat timesaving tip is that you can autocomplete queries by pressing TAB. So if the filename is called Vagrantfile, then all you have to do is type subl vag and press TAB, and it should auto-complete.

**Step 5:** To quickly exit sublime, you just press Alt F X. And you're back to your cmd. Pretty sweet!

**Bonus Step 6:**To make sublime text not remember your previously opened files, in Sublime, under Preferences-->Settings - User, put:

~~~
// Settings in here override those in "Default/Preferences.sublime-settings",
// and are overridden in turn by file type specific settings.
{
	"hot_exit": false,
	"remember_open_files": false
}

~~~
So now, when you just type 'subl', see that it creates a blank document.

~~~
C:\Users\Foo
λ subl
~~~

![untitled1](https://f.cloud.github.com/assets/6570916/2250306/567e1190-9d8e-11e3-806c-694314aada6b.png)

**Comment by Jackbennett** [comment]
Made it to the wiki ages ago: https://github.com/cmderdev/cmder/wiki/Seamless-Sublime-Text-3-Integration

**Comment by TheRealBluebird** [comment]
An added tweak:

I didn't want to install a second instance of Sublime, since I already have the default install, so I did the following (in Windows 7):

1. In cmder or a dos shell, navigate to "%CMDER_ROOT%\vendor\"

2. Create a symbolic link:

> mklink /J sublime "C:\Program Files\Sublime Text 3\"

3. In the alias file, add the line:

> subl="%CMDER_ROOT%\vendor\sublime\sublime_text.exe" $1 -new_console:s75V

Seems to be working alright so far.

**Comment by DRSDavidSoft** [comment]
@expositor This is really Neat, indeed!

**Comment by nihildeb** [comment]
ctrl-tab is to change tabs in both cmder and sublime. anyone have a solution to that?

thanks btw!

**Comment by gubrus50** [comment]
There is now a stable and portable release of **Sublime text 4**. On this new release, the Sublime window pops out of the Cmder. Interestingly, when opening a new Sublime window, for example, "settings" (found in the Preferences drop-down tab), that newly opened Sublime window is then integrated back into Cmder. **Is there a way to integrate Sublime text 4 editor into Cmder terminal?**
