### ISSUE TITLE
IDP.ALEXA.51 treath

### ISSUE THREAD

**Issue by lordmax** [cmderdev/cmder#1532]
I've downloaded today the mini version
Started on a windows10 system

After 1 minute antivirus find a strange file init.bat from the vendor directory and it seems that contain an idp.alexa.51 menace

Anyone alse find it?

I'm for sure that's not in my pc (tested with 3 antivirus, 2 local and one enterprise at office)

![cmder_mini_alexa](https://user-images.githubusercontent.com/349971/32193463-a875d59e-bdb7-11e7-9596-f50ddc1ec781.png)

**Comment by Stanzilla** [comment]
Report it as a false positive please

**Comment by lordmax** [comment]
NO

It's not a false positive

Also AVG and McAfee signals a menace

**Comment by Stanzilla** [comment]
It is a false positive.

**Comment by vBm** [comment]
Only mediocre AV's find problems with it.
https://www.virustotal.com/#/file/6ab9edda66f2f4766a896df8a52c8b2be977e251b74d4a36304edb22734aae80/detection

**Comment by felipevr** [comment]
The same thing happend to me with the latest cmder full today.

**Comment by VitaliiHudukhin** [comment]
Damn, the same thing happend to me with the latest cmder full today (2019-09-22).

**Comment by eccker** [comment]
I got this warning from Avast, is it a false positive or do i got a virus? how to proceed?
![image](https://user-images.githubusercontent.com/5886200/65548438-0edec880-dee1-11e9-9b6b-ea7cc6aa74ff.png)

**Comment by Stanzilla** [comment]
report als false positive please

**Comment by jpruiz114** [comment]
The same is happening to me as of 2019.10.16.

What is this error?

What is IDP.ALEXA.51?

![image](https://user-images.githubusercontent.com/4614970/66976309-7ebf1980-f06f-11e9-8a34-ccfca6cd9d6f.png)

**Comment by ccoenen** [comment]
I know it's a a false positive, but it still happens. Does anyone know what triggers this?

**Comment by kthy** [comment]
> Does anyone know what triggers this?

Crappy antivirus software.

I've reported the file as a false positive to AVG. Doubtful it helps.

**Comment by Malkom** [comment]
I've reported too (Avast).

Virustotal show it "Undetected" by all AV : [Virustotal test](https://www.virustotal.com/gui/file/e50fdaa261e8b888c3ffe0c18baac20ede9b92b61aa3b5450942071c1178134d/detection)

**Comment by gjh71** [comment]
Last week no issue, now Avast reports the exact same thing on W10.

**Comment by robertrypula** [comment]
![image](https://user-images.githubusercontent.com/6407731/71824647-6244e300-309a-11ea-8366-bd54539e8c2d.png)
Same on my side - windows 10 Home and ConEmu 191012

**Comment by daxgames** [comment]
Report it as a false positive.
