### ISSUE TITLE
The latest version's `vendor\conemu-maximus5` lost .exe file

### ISSUE THREAD

**Issue by iulo** [cmderdev/cmder#1533]
file tree:
```
.
|-- ConEmu
|-- ConEmu.map
|-- ConEmu.xml
|-- ConEmu64.map
`-- plugins

```

**Comment by Stanzilla** [comment]
Do you mean the 1.3.3 release and if so, which zip?

**Comment by iulo** [comment]
yes. both `cmder_mini.zip` and `cmder.zip`

**Comment by vBm** [comment]
@iulo There are both `ConEmu.exe` and `ConEmu64.exe` in [v1.3.3 cmder_mini.zip, cmder.zip and in cmder.7z](https://github.com/cmderdev/cmder/releases/tag/v1.3.3). Just checked all 3.
