### ISSUE TITLE
Virus found in release v1.3.3

### ISSUE THREAD

**Issue by arthurwdev** [cmderdev/cmder#1534]
When I download the release v1.3.3 (cmder_mini.zip) my antivirus has the following infection:
- Trojan:Win32/Fuerboos.C!cl on file: Downloads\cmder_mini.zip->vendor/conemu-maximus5/ConEmu.exe

System Info:
Windows 10 Version 1709 (OS Build 16299.19)
Windows Defender Security Center - Definition Update Out-31-2017.

**Comment by Stanzilla** [comment]
Please report as a false positive
