### ISSUE TITLE
Git For Windows 64-bit

### ISSUE THREAD

**Issue by MartiUK** [cmderdev/cmder#1536]
Would it be a good idea to switch to 64-bit Git For Windows?

**Comment by Stanzilla** [comment]
I think so. There will be people complaining and I thought about doing two editions but I don't think we should do that.

**Comment by MartiUK** [comment]
Roughly 95% of Windows Steam users use a 64 bit version of Windows, obviously this isn't 1-1 with cmder users; but I could see it being representative of advanced users.

**Comment by daxgames** [comment]
I think it's a good idea.  I'm gong out on a limb here and guessing anyone wanting to use cmder is not running 32bit windows.

**Comment by Stanzilla** [comment]
Let's try it: https://github.com/cmderdev/cmder/commit/124565f36aa091cdbf96d6140e9033f3a6e9a144
