### ISSUE TITLE
'C:\Program' is not recognized as an internal or external command, When Launching with bash

### ISSUE THREAD

**Issue by markolo25** [cmderdev/cmder#1537]
```
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.


Current` directory:
C:\Users\mark

Command to be executed:
"C:\Windows\SYSTEM32\cmd.exe"  /c "C:\Program Files (x86)\Cmder\vendor\conemu-maximus5\..\git-for-windows\bin\bash --login -i"


ConEmuC: Root process was alive less than 10 sec, ExitCode=1.
Press Enter or Esc to close console... 
```

I get this error when I launching Cmder with bash shell, it is currently stored in 
C:\Program Files (x86)\Cmder 

The setting used by the {bash::bash} is

```
cmd /c "%ConEmuDir%\..\git-for-windows\bin\bash --login -i" -new_console:d:%USERPROFILE%
```

**Comment by MartiUK** [comment]
Don't store cmder in Program files, not only will you have this problem but you may end up with some issues with permissions, try again with it in your home directory or on your desktop.

**Comment by markolo25** [comment]
Thanks that works.

**Comment by mkczyk** [comment]
#1200

**Comment by mkczyk** [comment]
There are more problems when cmder store in `C:/Program Files` https://github.com/cmderdev/cmder/issues/1200

**Comment by HBenzaoui** [comment]
> Don't store cmder in Program files, not only will you have this problem but you may end up with some issues with permissions, try again with it in your home directory or on your desktop.

Im storing cmder in my home derectory "C:\Users\me\cmder and i got the same problem
