### ISSUE TITLE
Cmder tries to create clink initial settings every time if clink is already installed

### ISSUE THREAD

**Issue by Mystiflow** [cmderdev/cmder#1538]
Cmder v.1.3.3, Microsoft Windows [Version 10.0.16299.19]

I have cmder_mini extracted to C:/Cmder with CMDER_INSTALL_DIR as an environmental variable set.
I also have [clink 0.4.8](https://mridgers.github.io/clink/) installed system wide on my PC as I like to use it in cmd prompt.

When I open Cmder.exe, I get the following printed in the window *every* time:
```
Generating clink initial settings in "C:\Cmder\cmder_mini\config\settings"
Additional *.lua files in "C:\Cmder\cmder_mini\config" are loaded on startup.
```

I looked and it appears the settings file isn't being created which I think is why the log is being shown.

--

After uninstalling system wide clink, the log only shows on the first run and the **settings** file is being created therefore the issue is solved.

Can the tool be modified to be respectful for any external clink installations?

Thanks

**Comment by MartiUK** [comment]
@Stanzilla something for you to look at?

**Comment by Stanzilla** [comment]
Hrmm I will take a look but no promises.

**Comment by hAirypAulsAck** [comment]
@Mystiflow Thanks, that was bugging me. So if I reinstall clink will the repeating message come back or now that I have the proper settings file can I control this?

**Comment by Mystiflow** [comment]
@hAirypAulsAck At the top of my head, I think now that your settings are generated - it's fine to reinstall. Why not try?

**Comment by hruzeda** [comment]
If you look at the config folder, you'll see that the settings sub-folder doesn't exist (at least in my setup), neither the clink.lua file.
Create the folder and copy the clink.lua file from *\cmder_mini\vendor" into it and the warning will disappear.
