### ISSUE TITLE
"Cmder Here" menu context item doesn't work for git bash.

### ISSUE THREAD

**Issue by donperi** [cmderdev/cmder#1539]
When opening Cmder at current folder using the context menu, if the startup task is Git Bash, the new console will open at Home dir.

Default bash task:

`cmd /c "%ConEmuDir%\..\git-for-windows\bin\bash" --login -i -new_console:d:%USERPROFILE%` 

Expected behavior:
Bash is open in current folder.

**Comment by erlangp** [comment]
+1

**Comment by relzhong** [comment]
Just add  `if [ -n "$CMDER_START" ]; then cd ${CMDER_START} ; fi` in your bashrc.
This code check the CMDER_START env, and go to the directory cmder opened.

For example, I use git bash, so I add it  at the end of  `C:\Program Files\Git\etc\bash.bashrc`

**Comment by erlangp** [comment]
works! thanks @relzhong :+1:

**Comment by donperi** [comment]
Thanks @relzhong.
Could be nice to add a documentation for that in the Readme.

**Comment by gpakosz** [comment]
This should work out of the box without fiddling with `C:\Program Files\Git\etc\bash.bashrc`. The shell extension is registered with `"C:\cmder\Cmder.exe" "%V"` and this should be honored
