### ISSUE TITLE
Lambda sign not visible

### ISSUE THREAD

**Issue by gozdal** [cmderdev/cmder#1541]
I'm not sure if it belongs here or in ConEmu.
After fresh install of Cmder the lambda char in prompt is not visible.
It's there - if you select the text you see it's there, it's just the same color as background.
Changing color scheme does not work - i.e. lambda is still drawn using background color. All other texts are displayed properly.
Any idea what is wrong?

**Comment by Mystiflow** [comment]
What version are you using? I think https://github.com/cmderdev/cmder/commit/a8d32611a9b93cfb58f0318ae4b8041bc8a86c68 (v1.3.4) fixed it

**Comment by gozdal** [comment]
1.3.3 - downloaded from main page which links to https://github.com/cmderdev/cmder/releases/download/v1.3.3/cmder_mini.zip

**Comment by gozdal** [comment]
@Mystiflow thx, that fixes the problem
