### ISSUE TITLE
attempt to call a nil value

### ISSUE THREAD

**Issue by miluokesiji** [cmderdev/cmder#1544]
Why each time a command is executed, it's presented that  "attempt to call a nil value"?

**Comment by ifoundu** [comment]
question the same..... // want to ask the same question.

**Comment by HaoLiuHust** [comment]
may be you used  a Chinese directory name

**Comment by Axl2017** [comment]
I found this a lua error, but I know nothing of lua, is there anyone can solve it?
PS: I use cmder in Chinese env

**Comment by imwillhayes** [comment]
do not use a  directory name that include chinese

**Comment by yangsheng20080808** [comment]
oh，that is

**Comment by equaliser0** [comment]
> do not use a directory name that include chinese

What does that mean? I have no chinese in my directory (lol - sounds weird). What else could it? I have this after every command. realy annoying.

**Comment by SergeMaikere** [comment]
Is there a fix ? It's a pain in the **** for each and every commands to end like this

**Comment by HaoLiuHust** [comment]
do not put cmder in a Chinese directory name

**Comment by yichen8** [comment]
Cmder 的**安装目录**中不要带中文。这样应该就可以解决了。

**Comment by youssiyouss** [comment]
help me plz since i tried to pull the updates of the remote GIT directory this crap bin showin and it wont let me use the git instractions 
C:\laragon\bin\cmder\vendor/clink.lua:219: attempt to index local 'HEAD' (a nil value)
pllllz someone help me i neve used any chineese words

**Comment by dev-oswld** [comment]
> may be you used a Chinese directory name

Great tip!!!

**Comment by ymyguang** [comment]
Dot use Chinese directory !

**Comment by DevSairus** [comment]
That's appear when you have special character in some part of directory or path... try to delete this...

**Comment by rhamdif** [comment]
cd laragon
