### ISSUE TITLE
Scripted start of MINGW64 through cmder

### ISSUE THREAD

**Issue by blackfyre** [cmderdev/cmder#1545]
Hi!

Since I have to start up multiple long running console tasks & I use git bash to do things, I was wondering if cmder allows to start up with a script?

Like: open 3 tabs & run specific commands in them automatically?

**Comment by angly-cat** [comment]
One way to achieve that is to create a task that would launch different scripts in different tabs.

For example, it's able to create a task that just launches 3 `cmd`s.
![image](https://user-images.githubusercontent.com/5000549/33193099-83fa3132-d0f0-11e7-8577-5e22c9c0344e.png)

So with a bit of trial and error you can get what you want.
