### ISSUE TITLE
Using a smicolon triggers an error

### ISSUE THREAD

**Issue by trichetriche** [cmderdev/cmder#1548]
Everything is in the picture : 

![image](https://user-images.githubusercontent.com/7789922/32670177-4a09ea7e-c643-11e7-8744-492a7eb6fd45.png)

I'm on a surface pro 4, brand new, have only configured Cmder to load in a specific folder, and using 161206 stable version (shown in Help/About)

If you need more information, feel free to ask, I don't really know what to put more.

**Comment by angly-cat** [comment]
Isn't it how it should be? In your case `git` thinks that the rest of string including semicolon is parameters, which triggers an error. One normally run several commands with `&&`, no? Like `git add -A && git commit --amend -no-edit && git push -f`.

**Comment by trichetriche** [comment]
I don't think so, I've always used semicolons in Linux to chain my commands, I also did it with cmder on my old computer, and I never have faced this issue before.

**Comment by angly-cat** [comment]
> I also did it with cmder on my old computer

You know, I kinda struggle to find any info about semicolon ever worked as commands delimiter in Windows's console. However, it works perfectly fine in powershell. Did you by any chance use powershell before?
![image](https://user-images.githubusercontent.com/5000549/33206401-499dfb10-d134-11e7-826a-66d25af4930a.png)

**Comment by trichetriche** [comment]
Maybe you struggle to find it because I said it was a Linux computer ;)

Well I don't know, at work on a windows computer, I can use them, but I didn't use powershell. Maybe it was set in this way ? the opposite thing happens with the surface : I bought it with windows 10 on it and I instantly downloaded cmder, and this issue happened.

**Comment by angly-cat** [comment]
> Well I don't know, at work on a windows computer, I can use them

Wow. Could you provide some details? Windows version, 32/64, the console you use (is it regular `cmd`? Or `cmd` or other console emulator just by itself or within Cmder?

**Comment by trichetriche** [comment]
Me too, but I can't at home with my surface, that's my point !

64 bits, windows 10 (I'm not at home I can't provide the exact version sorry), and I use cmder without any custom settings, I don't know if it emulates a windows console, I'm not very experienced in that, I just use it !

**Comment by daxgames** [comment]
; works as a command separator in bash and power when but not in cmd.exe.  the default cmder shell is cmd.exe.  you can use & or && in cmd.exe shells.

& = always execute the next command
&& = only execute the next command if previous command exits with errorlevel 0

**Comment by trichetriche** [comment]
That's helpful, thank you !

Do you know if there's a way to set power shell as the cmder's shell ?

**Comment by daxgames** [comment]
You can set cmder to launch the powershell task as the default in the setup tasks menu.

**Comment by trichetriche** [comment]
Thank you !
