### ISSUE TITLE
Command line is corrupted after exiting less.exe with ctrl+c

### ISSUE THREAD

**Issue by folmert** [cmderdev/cmder#1553]
Steps to reproduce

1.  Go to directory with git repository.
2.  git log
3.  Ctrl+C
4.  For unknown reason name of active tab will change to "less.exe" - what the heck is that?
5.  Typing other commands will summon back shattered parts of previous git log output or less.exe shortcuts.

**Edit**
Ok, I know now that less is a text editor and a correct way to close it is by ":q", but while exiting by "ctrl+c" is also possible (which will make a mess in the command line), it's still a bug.

**Comment by seaSide974** [comment]
Same issue there

**Comment by i-love-code** [comment]
Same here, it's super annoying. Any potential for a fix?

**Comment by vinayluzrao** [comment]
Mine works completely fine, on cmder with ConEmu 180626 [64] {Preview}. . Exiting less.exe with ctrl+c just does nothing (also doesn't exit less). "git log" will run less and change the tab name to less.exe, but upon exiting with ":q" the tab name goes back to cmd.exe. No mess, no shattered parts.

**Comment by YamidDev** [comment]
press Q
