### ISSUE TITLE
Prompt (λ) is same color as background

### ISSUE THREAD

**Issue by Nick-Hope** [cmderdev/cmder#1554]
On a vanilla installation of version 1.3.4, the λ prompt is the same color as the background:

![cmder-invisible-prompt1](https://user-images.githubusercontent.com/33649175/32765884-09c0b58e-c93f-11e7-9722-ab73d462621c.png)

This prompt is there, as can be seen when I select that area:

![cmder-invisible-prompt2](https://user-images.githubusercontent.com/33649175/32765898-1df2ee96-c93f-11e7-8df4-340ea3d0586e.png)

The prompt stays the same color as the background even if I change the color scheme.
Quite possibly user error, as I'm a cmder newbie, but I can't find an obvious way to make that prompt a different color.

**Comment by Stanzilla** [comment]
The color is defined here https://github.com/cmderdev/cmder/blob/a8d32611a9b93cfb58f0318ae4b8041bc8a86c68/vendor/clink.lua#L41

**Comment by Nick-Hope** [comment]
@Stanzilla Thank you. I should have downloaded version 1.3.4 from Github, rather than the version from the front page of http://cmder.net/, which is still 1.3.3 and has this issue.

**Comment by beansrowning** [comment]
I have this same issue, is the color value in the lua script now correct as of 1.3.4?

**Comment by Stanzilla** [comment]
yes
