### ISSUE TITLE
Task Startup Directory not working in 1.3.4

### ISSUE THREAD

**Issue by Tadimsky** [cmderdev/cmder#1555]
I have the following task that I want to start in a certain folder:
`*cmd /k "%ConEmuDir%\..\init.bat"  -new_console:d:C:\Users\joschm\Intentional`
This used it work fine on 1.3.2. I just moved to 1.3.4 and now all of my Tasks start in my standard User Profile folder (C:\Users\joschm).

Did something change with the `d` option?

**Comment by Stanzilla** [comment]
Can you test with the latest master build, please? https://ci.appveyor.com/project/MartiUK/cmder/build/1.0.494-master/artifacts

**Comment by Tadimsky** [comment]
That works! Thank you 😄 #1547
