### ISSUE TITLE
echo $? does not print exit status of last command

### ISSUE THREAD

**Issue by fracz** [cmderdev/cmder#1558]
Why echoing of `$?` does not print the last command status? Is it possible to configure it somehow?

```
λ echo $? 
$?
```

**Comment by rohitkrishna094** [comment]
What is the answer for this?

**Comment by daxgames** [comment]
`echo $?` Is a bash shell command.  The default cmder shell is cmd.exe.

**Comment by rohitkrishna094** [comment]
Thank you so much.
