### ISSUE TITLE
Add auto-update to cmder

### ISSUE THREAD

**Issue by kyan001** [cmderdev/cmder#1559]
I know ConEmu can be auto-updated, but cmder is not. Update manually by download .zip and replace exist files feels so unsafe for my configs and binaries.

At the first few days, I thought ConEmu Auto-update is the Cmder Auto-update, until I did some research on this topic. It's kinda confusing. 

At least, cmder should be able to auto-check new versions.

**Comment by Stanzilla** [comment]
Since Cmder is only a tools collection this is kinda hard to do.

**Comment by EnshaednHiker** [comment]
Hard to do but ultimately worth it? I want to second this request.  If technically not feasible, could we get some documentation to help us install newer versions? A checklist  or something? I love using cmder but it's not clear to me where cmder stops and clink/conemu begins.
