### ISSUE TITLE
Transparent image. A Detail but I would like to get it to work

### ISSUE THREAD

**Issue by buckleyGI** [cmderdev/cmder#156]
Hi,

I'm trying replace the white border from the logo below so that you can see through it.
However, I'm quit a beginner when it comes to graphics. Can you give me a pointer so that I can get started. I made some progress when I used the png format. The radiobutton next to transparent always seems to be greyed out.

Thanks!

![image](https://f.cloud.github.com/assets/2102864/2271424/f2271cd8-9ef9-11e3-8452-c9f7412a1c8c.png)

![image](https://f.cloud.github.com/assets/2102864/2271439/0cf75f8c-9efa-11e3-9d5c-e8f9d79d8c15.png)

**Comment by lnfel** [comment]
@samvasko  thank you very much my good sir!
