### ISSUE TITLE
Request: working with command history 

### ISSUE THREAD

**Issue by niradler** [cmderdev/cmder#1560]
List history + pagination
Crud on the list
Sync over gdrive?

**Comment by glucas** [comment]
What shell do you use? The history mechanisms are different. If you are using cmd.exe then when running cmder the history is managed by clink. History is saved in a text file that you can sync (or grep, cat, edit,  etc) if you like. See "%CMDER_ROOT%\config\.history".

Also note that clink has various configuration options for history - how often it is persisted, whether to keep duplicate entries, etc. 

If you are using powershell then you may want to look in to configure PsReadLine.

**Comment by imbible** [comment]
The history file is at %CMDER_ROOT%\config\\.history. You missed a **\\** .
