### ISSUE TITLE
init.bat – Invalid method used for determining a recent `git` version

### ISSUE THREAD

**Issue by DRSDavidSoft** [cmderdev/cmder#1564]
### Found old git version in "C:\path\to\git", but not using...

Sounds familiar? Upon inspecting the [`init.bat`](https://github.com/cmderdev/cmder/blob/master/vendor/init.bat#L46) file, I found out that the mechanism for checking a recent version of git is as follows:

> also check that we have a recent enough version of git (e.g. test for GIT\cmd\git.exe)

Which means that a possible installation of `git.exe` in a directory such as `GIT\bin\git.exe` is **considered NOT recent to cmder.**

This seems like a really, _rellay_ bad idea to me. I'll explain why:

Consider this for example:

<img width="427" alt="cmder_git" src="https://user-images.githubusercontent.com/4673812/33296063-966253da-d3ee-11e7-84e5-08bd11ea1de7.png">

As you can see, I have a perfectly recent `git.exe` installation within Cygwin, which happens to be located in a `/bin` directory rather than a `/cmd` directory.

However, although **`git version 2.13.2`** is obviously more recent than **`git version 2.9.0.windows.1`**, since it is not installed in a `/cmd` directory, `init.bat` thinks that it is **NOT** a recent version of git, while it obviously **is**.

While `init.bat` is a great part of cmder, I think the implementation of this part is really horrible. IMO, instead of checking for the `/cmd` path, it should compare `git.exe --version` values to detect which git is more recent.

If my proposal seems reasonable to you, I'll be glad to PR a solution, based on [this](https://stackoverflow.com/a/4025065/1454514).

Thank you :)

**Comment by MartiUK** [comment]
Please go ahead

**Comment by DRSDavidSoft** [comment]
@MartiUK done, #1658

**Comment by DRSDavidSoft** [comment]
An issue with the space in directory path has been fixed in #1696

**Comment by DRSDavidSoft** [comment]
@MartiUK & @Stanzilla Could you please add this issue to the `v1.4` release project (marked as ready)?

I'd like to see this patch in the next major release
