### ISSUE TITLE
How to configure the Git Prompt

### ISSUE THREAD

**Issue by c33s** [cmderdev/cmder#1565]
today i updated from cmder 1.2 to 1.3 and prompt in git repos totally changed.
the real path containing a git repo of 
```
c:\home\projects\puppet\control-repo
```
gets to the, for me, unreadable:
```
c:\home\projects -> origin\puppet\control-repo -> origin (development -> origin)
```
before it was the simple and clear
```
c:\home\projects\puppet\control-repo (development)
```

is this cmder specific or is this clink specific? is this a bug or a feature? how can i get the old behavior back? shouldn't we document this in the wiki?

**Comment by igortg** [comment]
Try this: https://github.com/AmrEldib/cmder-powerline-prompt

Need some minor config, but it's a nice customization and keep the Cmder old style prompt

**Comment by c33s** [comment]
@igortg thank you, i found `cmder-powerline-prompt already` i was looking for the official way and hoped there is an easy boolean flag for that.

**Comment by maeriens** [comment]
Hey there, I just updated to `cmder@1.3.5` and I too find that ` -> origin` line awful (Also not sure what it meant, local branches did show it too when they were not yet pushed to the remote or anything, and I felt it was misleading).

 So I went for a caveman's solution. Did a `grep` for ` \-> ` in the `vendors` folder and found the culprit: `clink-completions > git_prompt.lua`. Inside, in line 80, you have to change 
```clink.prompt.value = clink.prompt.value:gsub(escape(branch), '%1 -> '...text)``` (Or similar, don't exactly recall the line) by removing the `-> '...text)`. (The space after the `>` too, but remember to leave the single quotation mark).

![image](https://user-images.githubusercontent.com/5074186/36310824-f8d897ba-1307-11e8-8bf3-b26e7d90ec43.png)

**Comment by daxgames** [comment]
To get rid of the `-> origin` from a cmder session:

1. Type `del  "%cmder_root%\vendor\clink-completions\git_prompt.lua"`
2. Start a new session.

To make it permanent so it does not come back after a cmder update add the following to `"%cmder_root%\config\user-profile.cmd"`:

```
if exists  "%cmder_root%\vendor\clink-completions\git_prompt.lua" del  "%cmder_root%\vendor\clink-completions\git_prompt.lua"
```
