### ISSUE TITLE
cmder really slow in hg repo

### ISSUE THREAD

**Issue by jeffwitthuhn** [cmderdev/cmder#1566]
Hello, I really like cmder but it's really slow in my repo. Each command, or even pressing enter requires like 2 seconds. How can I disable the source control stuff in cmder? I tried deleting checkGit in the profile.ps1 but no luck 

*edit* using mercurial (hg). The process hangs after each command running an hg executable. I assume to do like hg status.  It's probably more of a problem with hg being slow, but I'd like to just turn off the source control info to avoid this.

**Comment by glucas** [comment]
You'll want to look at get_hg_status in vendor/clink.lua. One quick fix might be to have that function just return true all the time.

I've done something similar in my own get_svn_status function in that same file -- I updated the svn options to avoid recursing into subdirectories as that is painfully slow on a large repository I work on.

**Comment by Stanzilla** [comment]
@jeffwitthuhn please test with https://ci.appveyor.com/project/MartiUK/cmder/build/1.0.522-master/artifacts

**Comment by bickel** [comment]
I still have this problem with the latest version. I tried to comment the get_hg_status() function as suggested previously but this method does not exist in my vendor/clink,lua file, nor any reference to "hg status". Commands are executing at normal (expected) speed, but it takes ages to get the prompt back.

**Comment by qwoodmansee** [comment]
the answer of @glucas led me to my solution, which was to comment out the hg function as well as the SVN function under it. Thanks!
