### ISSUE TITLE
Console doesn't show typed letters after quitting `git log` on Git Bash

### ISSUE THREAD

**Issue by pbelzek** [cmderdev/cmder#1567]
I'm using Git Bash via Cmder. I've run `git log`, scrolled trough some commits and then pressed CTRL+C to exit. It turns out that console doesnt show letters that I'm typing but console still works and executes commands normally, I won't see letters appearing on the screen but they still are "there" and after pressing Enter the command executes and I get response. It occurs only on Git Bash (default cmder and powershell works normally)

**Comment by spone379** [comment]
I have the same problem!

**Comment by prakash-ism** [comment]
Is there a solution to this problem apart from restarting git bash?

**Comment by Naresh22255** [comment]
:q

**Comment by goczbela** [comment]
>     2. To fix a broken console where typing is gone, type **reset** and press enter. This resets the bash console, and fixes the issue where the echo doesn't show what you type. Found that hint elsewhere on the internet. It does clear the windows though, so you may lose your log output.

thx, its worked!
