### ISSUE TITLE
it`s something wrong with colors in my computer

### ISSUE THREAD

**Issue by peiyc** [cmderdev/cmder#1568]
windows10 64bit
cmder version 1.3.4
When I use cmder run react-native, only can see a  part of logs.
![3mphyfpqqn 6rw0t_g4gy8](https://user-images.githubusercontent.com/15152562/33361791-9d56fa20-d514-11e7-8233-88d820611933.png)

 I changed the color of text, I can see the words.
![r 8 zv67 c0 btcw hhr pl](https://user-images.githubusercontent.com/15152562/33362069-a59fe150-d515-11e7-8941-138440f88161.png)

I run it again, I can`t see the logs after I changed the color.
![4734w 9 sydckgs9wstzs6](https://user-images.githubusercontent.com/15152562/33362070-a7ab9e80-d515-11e7-9943-00954a5d44b4.png)
![wye q3m a iffnpww3 rx f](https://user-images.githubusercontent.com/15152562/33362106-c1c45280-d515-11e7-860e-8da5052937a1.png)

I think it has something wrong with colors on windows10

**Comment by PolaEdward** [comment]
I have the same Issue

**Comment by PolaEdward** [comment]
Update, I think it's related to the styling library used by React native which is Chalk
