### ISSUE TITLE
blank space can 't be showed normally while using cmder as a ssh client

### ISSUE THREAD

**Issue by squallud** [cmderdev/cmder#1569]
After ssh to the server, using vim to open a text file, i found that the blank space showed like the picture bellow:

![image](https://user-images.githubusercontent.com/34089154/33365495-65a4427c-d523-11e7-99c4-c19e42b861e5.png)

But while i using vim to open a local text file, it works well:
![image](https://user-images.githubusercontent.com/34089154/33365904-b0a4d894-d524-11e7-980d-3a8d69a22a97.png)

Did i missing any configuration?

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)
