### ISSUE TITLE
how to upgrade git 

### ISSUE THREAD

**Issue by PrasanthiUma** [cmderdev/cmder#1570]

**Comment by ryanmcdonnell** [comment]
1. Install the latest version of [Git for Windows](https://git-scm.com/downloads/win)
2. Create a new environment variable `GIT_INSTALL_ROOT` pointed at the installation folder of Git for Windows e.g. `C:\Program Files\Git` for the 64-bit flavor.
3. Open cmder and run `git --version` to confirm the latest version is installed.

**Comment by lgwebdev** [comment]
If you want to keep it in cmder folder:

1. Rename `C:\path\to\cmder\vendor\git-for-windows` into `C:\path\to\cmder\vendor\git-for-windows.old`
2. Download the last portable version of Git for Windows with the last link on [this page](https://git-scm.com/download/win) **Git for Windows Portable ("thumbdrive edition")**
3. Extract it in `C:\path\to\cmder\vendor\git-for-windows`

**Comment by kalvn** [comment]
If you want to keep it in cmder folder:

1. Rename `C:\path\to\cmder\vendor\git-for-windows` into `C:\path\to\cmder\vendor\git-for-windows.old`
2. Download the last portable version of Git for Windows with the last link on [this page](https://git-scm.com/download/win) **Git for Windows Portable ("thumbdrive edition")**
3. Extract it in `C:\path\to\cmder\vendor\git-for-windows`

**Comment by daxgames** [comment]
Kind of but not really.  Cmder adds some configuration to the /etc/profile.d folder inside git-for-windows.  To upgrade and maintain all functionality you need to add that configuration back to that location

**Comment by kalvn** [comment]
Good point @daxgames thanks :)

**Comment by Stanzilla** [comment]
Type `git update-git-for-windows`

**Comment by GlassGruber** [comment]
Hi sorry for bumping again, is there anything like `git update-git-for-windows` but for **portable** version? AFAICT this install the full version of Git on the system, not in the `cmder/vendor` folder.

**Comment by daxgames** [comment]
Download the portable version and expand it to vendor/git-for-windows.

**Comment by GlassGruber** [comment]
@daxgames Thank you for your answer, I thought so, but I'am _very lazy_ and hoped for a nice little command as this one ;)

**Comment by daxgames** [comment]
There is another way but it's more effort.
