### ISSUE TITLE
Scroll in applications

### ISSUE THREAD

**Issue by sinnlosername** [cmderdev/cmder#1572]
I'm unable to scroll in applications like "less", "htop" or "screen" when using the git-bash or the ubuntu subsystem in cmder. It works fine when I'm only using the git-bash.

Seems like cmder doesn't send such scroll-events. I'm using the latest cmder version from your webpage.

**Comment by toloveru** [comment]
Same issue here.

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)
