### ISSUE TITLE
can not input single or double quotation marks in cmder

### ISSUE THREAD

**Issue by yorua007** [cmderdev/cmder#1573]
I just update to the latest version(171025[64] {Alpha}), but the problem is still there, I just cannot input the single or double quotation marks in cmder.
My OS is WIN7_X68-64

**Comment by rangercyh** [comment]
the same question

**Comment by daxgames** [comment]
Can you please  this in a little more detail?

**Comment by rangercyh** [comment]
thx for attention! I just can't input quotations in cmder console, I mean when I press the quotation key in my keyboard, nothing happened. I am sure my keyboard is normal, I can input quotations in a notepad and anywhere else. I try every key in my keyboard, only quotation key can't input.
![1](https://user-images.githubusercontent.com/1217541/43712517-0b4744dc-99a9-11e8-92d3-b3227b4eee33.png)

as you can see, I can input the other keys but the quotation

**Comment by rangercyh** [comment]
also I tried installed the conemu only, and guess what, I can't input quotation in conemu either

**Comment by daxgames** [comment]
I have never seen anything like this.

Dax
