### ISSUE TITLE
Windows shell instaed of bash shell

### ISSUE THREAD

**Issue by Remiol** [cmderdev/cmder#1575]
Is it possible to open cmder.exe in dos shell instead of bash.exe.

What I do now is in bash shell launch the command "cmd.exe" to go to dos shell.

ps: Is it also possible to use the windows Ctrl-A to select all text and to have the windows right click menu when I right click in cmder.exe?

**Comment by daxgames** [comment]
The default cmder shell is cmd.exe

**Comment by Remiol** [comment]
Not in my case I downloaded cmder_mini.zip - I had the full version before where I had the shell cmd.
However my full version didn't work with total commander. The mini does. 
I emptied my cmder.exe directory before to use the mini version.

**Comment by daxgames** [comment]
Mini does not even include bash.

**Comment by Remiol** [comment]
![cmder_prompt](https://user-images.githubusercontent.com/7782450/33525457-30900156-d830-11e7-848c-cf4c7c834c90.png)

**Comment by daxgames** [comment]
That is cmd.exe.

**Comment by Remiol** [comment]
Isn't this the bash prompt? What I do is to insert "cmd.exe" in order to obtain this:
![cmder_prompt2](https://user-images.githubusercontent.com/7782450/33525754-7183d3f8-d836-11e7-9454-88a23a74f40b.png)

**Comment by daxgames** [comment]
Type `ver` in both you will get the same output that is the version of Windows.  You can also type `set` and it will show you the eng variables.

**Comment by Remiol** [comment]
ver --> yes correct. 

This is my windows shell prompt:
![windows_prompt](https://user-images.githubusercontent.com/7782450/33525896-2712b1e8-d838-11e7-9269-d100b4845d46.png)

How can I change the bash like prompt "labda" to the windows prompt "\>"

**Comment by daxgames** [comment]
I don't know.  Why are you using cmder and all its benefits if all you want is cmd.exe?  You could create a task that just launched cmd.exe but you would lose all the other benefits cmder provides.

**Comment by daxgames** [comment]
The lamda is part of clink config.  I am not a clink expert.  I could probably figure it out but don't have the time.
