### ISSUE TITLE
Vi Key Bindings?

### ISSUE THREAD

**Issue by x-ji** [cmderdev/cmder#1577]
Not sure if this question has been asked before. A quick search didn't turn up any related issues. In Bash or Zsh you can use Vi-style key bindings with either 

`set -o vi`

or

`bindkey -v`.

I'm wondering whether there is currently a possibility/plan to have such a functionality in Cmder as well.

**Comment by timetimetimetime** [comment]
That bot is annoying. An issue is an issue. People still want this.
https://superuser.com/questions/1439240/how-to-enable-vi-key-binding-in-cmder/1439494

**Comment by daxgames** [comment]
You talking about Git bash Cmder sessions or the default cmd.exe based cmder session?  I would think it would work in Git bash but I have not tried it.  It is not possible in cmd.exe

**Comment by daxgames** [comment]
@x-ji @timetimetimetime You talking about Git bash Cmder sessions or the default cmd.exe based cmder session? I would think it would work in Git bash but I have not tried it. It is not possible in cmd.exe

**Comment by daxgames** [comment]
@timetimetimetime annoying or not we all have full time jobs and maintain Cmder for fun in our very limited spare time.  The bot just helps us notice issues that have fallen off the radar or been missed completely as this one WAS.  We try to respond to every issue as time permits.

**Comment by MartiUK** [comment]
This is not possible with cmd.exe, see https://serverfault.com/a/779653 for Powershell and do what you usually do for git bash etc.
