### ISSUE TITLE
Why is php command not found

### ISSUE THREAD

**Issue by kennblvnp** [cmderdev/cmder#1578]
> C:\xampp\htdocs\webapps\native_adwords (master -> origin)
> λ php -v
> 'php' is not recognized as an internal or external command,
> operable program or batch file.

**Comment by Stanzilla** [comment]
Not on your path?

**Comment by kennblvnp** [comment]
After restart, works perfectly fine!

**Comment by daxgames** [comment]
Same problem as before.  Not in your path.

**Comment by kennblvnp** [comment]
Yeah I got it fix by adding new variable path
