### ISSUE TITLE
Why does composer doesn't work but in git bash it works fine

### ISSUE THREAD

**Issue by kennblvnp** [cmderdev/cmder#1579]
C:\xampp\htdocs\webapps\native_adwords (master -> origin)
λ composer
'composer' is not recognized as an internal or external command,
operable program or batch file.

**Comment by kennblvnp** [comment]
okay why closed it?

**Comment by Stanzilla** [comment]
Sounds like composer is not on your path. Does it work in a normal cmd?

**Comment by kennblvnp** [comment]
Its working after I restart my computer.
