### ISSUE TITLE
Can't change into "shared dropbox" directory. Running cmder on Mac Parallels 13 Pro using WIN 10 Pro  

### ISSUE THREAD

**Issue by mtin79** [cmderdev/cmder#1581]
Hi there,
I got a dropbox folder (business) that is hosted on my Mac OS X (High Sierra). 
I can see it in File Explorer (Windows 10 Pro) running via Parallels 13 on the Mac.
It's the V: - Drive there.
But I can't cd into this folder like this: "v:" 
With powershell its working somehow.

Thanks for any help!

**Comment by mtin79** [comment]
Any reason why this was closed without further info?

**Comment by Stanzilla** [comment]
Yes, it is not really Cmder issue. Issues like that should be filed over at ConEmu https://github.com/Maximus5/ConEmu

Cmder is just a compilation of parts, most if not 99% of all issues reported on Cmder are actually because of bugs in one of those parts.

**Comment by mtin79** [comment]
Thanks for the info!
