### ISSUE TITLE
Git stash no longer seems to work

### ISSUE THREAD

**Issue by danwellman** [cmderdev/cmder#1582]
Whenever I run `git stash` in Cmder, I get a message:

> git: 'stash' is not a git command. See 'git --help'

And git stash is not listed in the help. But in other apps, like Sourcetree, stashing works fine, like it always did.

**Comment by DRSDavidSoft** [comment]
If this issue is still reproducible, please run the following:
* `git --version`
* `where git`

and post the results here.

**Comment by danwellman** [comment]
I was only seeing this issue on my work machine, but today it seems to be working as expected.
