### ISSUE TITLE
Setting up Ubuntu from the Win10 store (NOT WSL)

### ISSUE THREAD

**Issue by Taubin** [cmderdev/cmder#1584]
I can't seem to figure out a way to set up cmder to work with the Ubuntu downloaded form the windows store. I've read setting it up on WSL however, that does not work with the Windows Store version of Ubuntu. 

The error I get when attempting to open the WSL version is this: 
The system cannot find the path specified.

```
Current directory:
C:\Users\taubi

Command to be executed:
"C:\WINDOWS\SYSTEM32\cmd.exe"  /c "D:\cmder\vendor\conemu-maximus5\..\git-for-windows\bin\bash" --login -i


ConEmuC: Root process was alive less than 10 sec, ExitCode=1.
Press Enter or Esc to close console...
```
I have looked for a support forum or similar to post this to, however, I cannot find one. I apologize if this is not the correct place to ask this, and if it's not please direct me to the correct place. Thank you.

**Comment by jodli** [comment]
I also had this problem and I fixed it by modifying the Task in the settings.

When you are in the Settings dialog, navigate to Startup->Tasks and change the path to the bash.exe from `"D:\cmder\vendor\conemu-maximus5\..\git-for-windows\bin\bash"` to `"%systemroot%\system32\bash"` everything works just fine.

**Comment by garretmh** [comment]
Just to be clear, the Ubuntu app in the Microsoft Store is still WSL: https://docs.microsoft.com/en-us/windows/wsl/about

You can check you setup against the ConEmu's current info: https://conemu.github.io/en/BashOnWindows.html

**Comment by Stanzilla** [comment]
https://github.com/cmderdev/cmder/commit/91f5c5379a5cf20fcadd2d90456818cc3b245b74

**Comment by Brain2000** [comment]
I was trying to install with the same issue. Everywhere kept referencing this "lxrun" command, but after an hour of searching, I finally found that it is now wslconfig.exe. I had to run this to remove the reference to some "ghost" ubuntu that didn't exist, then I could reinstall.
