### ISSUE TITLE
'curl' is not an internal or external command nor is it a runnable program Or batch file.

### ISSUE THREAD

**Issue by wangming-0215** [cmderdev/cmder#1585]
I update the latest version of cmder. And the 'curl' command is not working.
OS: window10 16299.19
cmder version: v1.3.4
![qq 20171208122123](https://user-images.githubusercontent.com/21071580/33751030-e1ece76c-dc12-11e7-9922-03123a2981c8.png)
When I use Git Bash, the command is working as usual.

**Comment by daxgames** [comment]
Curl is not a part of cmder

**Comment by wangming-0215** [comment]
@daxgames Thanks

**Comment by gucong3000** [comment]
Curl is exist in `Git Bash`
![image](https://user-images.githubusercontent.com/1171691/37017003-cb680cb6-2149-11e8-86eb-bde069a66212.png)

Maybe we should fix it.

**Comment by gucong3000** [comment]
Related PR: #1690

**Comment by harryizquierdo** [comment]
I have taken curl of bit bash, and then paste it on the path: **cmder\bin\**
![imagen](https://user-images.githubusercontent.com/3268758/38286521-72eab018-378b-11e8-8f0c-081ab38de2d2.png)

![imagen](https://user-images.githubusercontent.com/3268758/38286611-e4066bfc-378b-11e8-8321-c7969862b6d0.png)

**Comment by prianto** [comment]
E.g. if you install cmder in `C:\cmder`, then just add `C:\cmder\vendor\git-for-windows\mingw64\bin` to `Path` Environment Variables.

**Comment by daxgames** [comment]
This is a part of the daily builds already just not released in binary form.

**Comment by brendonco** [comment]
when will curl be bundled with cmder?

**Comment by fabiosantoscode** [comment]
Would be good for older versions of windows

**Comment by daxgames** [comment]
@fabiosantoscode Curl is included with the latest cmder full but since windows has it the windows version is used by default.

```
where curl

C:\windows\system32.exe
%cmder_root%\vendor\git-for-windows\mingw64\bin\curl.exe
```
