### ISSUE TITLE
Windows 10 Ubuntu Pasting Issues

### ISSUE THREAD

**Issue by marct83** [cmderdev/cmder#1588]
When I try and copy and paste something like this into the bash shell in cmder :

 go get github.com/golang/dep/cmd/dep

All that gets pasted is:

m/golang/dep/cmd/dep

Why? Driving me nuts.

**Comment by zoober-linden** [comment]
I have the same problems.  Pasting large commands or using the up arrow seems to cause some text wrapping issues.

**Comment by zoober** [comment]
I have the same problems. Pasting large commands or using the up arrow seems to cause some text wrapping issues.

**Comment by jhaagmans** [comment]
Same issue, running Inside Build 17025. Doesn't happen when running `bash.exe`.

**Comment by RobertKozak** [comment]
I am seeing the same issue for over a month. I can't find a version where this is not happening now.

**Comment by deadalnix** [comment]
I'm affected by this problem too. It seems to be a ConEmu issue. I reported it here: https://github.com/Maximus5/ConEmu/issues/1387

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)

**Comment by mindplay-dk** [comment]
@Stanzilla looks like this was [resolved](https://github.com/Maximus5/ConEmu/issues/1314) so maybe Cmder distro needs an update?

**Comment by mindplay-dk** [comment]
And just to confirm, the issue does appear to have been resolved.

**To others stuck with this issue**: I'm using the portable release, so I downloaded the portable latest release of ConEmu [here](https://www.fosshub.com/ConEmu.html) and unpacked into `cmder\vendor\conemu-maximus5` - it works :-)

**Comment by Stanzilla** [comment]
Yeah we need to cut a new release, I was just waiting for the new git version to come out but that seems to take longer than I anticipated. Any day now though.

**Comment by deadalnix** [comment]
Eagerly waiting for the new release. Thanks everybody.

**Comment by mindplay-dk** [comment]
@Stanzilla everyone who accepts (or is forced to install 🙄) the latest Win 10 update is affected by this - the paste function simply stops working. I think it would be nice to get a release out soon, so everyone doesn't have to find this issue on github and fix it by hand?

**Comment by reijin90** [comment]
@mindplay-dk : I just replaced the contents now, but now Home (Pos1) and End keys don't seem to work. Also the command completion with the cursor keys doesn't work anymore. Did you only replace the executables?

**Comment by mindplay-dk** [comment]
> now Home (Pos1) and End keys don't seem to work

odd! works fine here.

> Also the command completion with the cursor keys doesn't work anymore

with the cursor keys? not sure how that works.

auto-completion with TAB works fine, and cursor up/down iterates through history as usual.

> Did you only replace the executables and does this work for you?

That's all I did, yeah - unzip the entire folder on top of the files already there.

Did you install the latest OS update? I'm on Win 10 Pro build 17134.48

**Comment by reijin90** [comment]
Up and down go through history, but before doing this, when I wrote "ssh" it would only cycle through my previous ssh commands. Pos1 and End still don't seem to do anything... It's odd... 
I'm on Win 10 Pro 1803 17134.81

**Comment by mindplay-dk** [comment]
Upgraded to 17134.81 and everything still works fine here.

**Comment by zaszlo** [comment]
after I replaced the conemu with a newer version the pasting is fixed but vi isn't working... up/down arrows are non-responsive, can't edit a file :-(

**Comment by deadalnix** [comment]
+1 , the copying and pasting behavior now works, but arrows are now broken in various contexts like vim and most.

**Comment by deadalnix** [comment]
@zaszlo any progress on that front ?

**Comment by zaszlo** [comment]
I reverted my conemu to the original as I'm more often editing files in terminal (ex. commit messages) then pasting in commands. Or I try to do the pasting from cmd and not from Windows' linux shell. So it is not resolved for me. Did I miss the solution or why is this issue closed?

**Comment by reijin90** [comment]
I will make a new issue and update here. Dunno why this is still closed as it should not be.

**Comment by zaszlo** [comment]
@deadalnix please help me finding that template file, or tab/section where to set p5 for that cur_console. I tried seearching for it in all conemu and inside the settings with cur_console but hasn't seen any `p` there. Thanks.

**Comment by reijin90** [comment]
@zaszlo If you had read this issue, you would see my comment stating that I created a new issue. I posted a detailed fix there.
