### ISSUE TITLE
executable program is not recognized even though I have added its directory to system PATH

### ISSUE THREAD

**Issue by jdhao** [cmderdev/cmder#1589]
Recently I installed Pandoc and add its install directory to my system PATH. But I found that I can execute the program in the system `cmd`, not in `cmder`. 

I reinstalled the cmder program and the `pandoc` command can be executed in `cmder` miraculously. Today, I can not execute the command again, which is weird. 

I have read the issue #443 and #792, which are related to mysql. In my case, there is no `&` character in the Pandoc path, the full path is `C:\Users\east\AppData\Local\Pandoc`.

## version info
+ cmder:  v1.3.4
+ System: Windows 8.1

**Comment by f-zand** [comment]
check which type of command {Task} you are using when you are creating a new tab. If you use, {bash::bash} it will pick up stuff from paths mentioned in your PATH var and execute them if they are bash scripts (which was the case for me, getting the same error)

**Comment by jdhao** [comment]
Sorry, but I can not understand what you are saying. Can you be more specific.

**Comment by Otiel** [comment]
Having the same issue.

**Comment by daxgames** [comment]
@otiel I hate to ask this but did you relaunch cmder after adding to your user path.  New adds/ changes are not available unroll a relaunch.

**Comment by Otiel** [comment]
@daxgames Yes, of course, I restarted cmder after modifying the PATH.

**Comment by Otiel** [comment]
My program is now recognized in cmder. Looks like a Windows restart solved this.
