### ISSUE TITLE
document update / upgrade

### ISSUE THREAD

**Issue by schlichtanders** [cmderdev/cmder#1590]
it would be great to have a short section in the README on how to upgrade CMDER to another more recent version

I just tried it by copying the bin and config folder to a newly extracted zip, however a startup dialog opened  where I again have to set settings, which should be there from my older cmder install

**Comment by daxgames** [comment]
@schlichtanders Working on it.

**Comment by daxgames** [comment]
Done #1591

**Comment by schlichtanders** [comment]
Thanks a lot
