### ISSUE TITLE
Invalid Bold text

### ISSUE THREAD

**Issue by alexandr-san4ez** [cmderdev/cmder#1595]
Updated from v1.3.2 to v1.3.4 and noticed an incorrect display of bold text.
![default](https://user-images.githubusercontent.com/20110612/34119356-e40f0746-e432-11e7-9f0f-1632585c94f2.png)

For tests use this file: https://gist.github.com/mlocati/fdabcaeb8071d5c75a2d51712db24011#file-win10colors-cmd

How can I fix it?

**Comment by Stanzilla** [comment]
Please report over at ConEmu https://github.com/Maximus5/ConEmu

**Comment by alexandr-san4ez** [comment]
I am sorry, i had to check it out right away.

In version 17.12.17 this is fixed.
https://github.com/Maximus5/ConEmu/commit/dd36455b2d826caa1786eb3bfe4ea381c1add0d9
