### ISSUE TITLE
invalid use of '%' in replacement string

### ISSUE THREAD

**Issue by cdswyda** [cmderdev/cmder#1597]
When I use `cd` command enter into some path, the cmder maybe out of work.

such as:

```
D:\workspace
λ cd epoint-web

D:\cmder\vendor/clink.lua:310: invalid use of '%' in replacement string
D:\workspace\epoint-web>cd /d e:

E:\
λ cd Code\2017\住房城乡建设部信息系统资源整合项目\

E:\Code\2017\住房城乡建设部信息系统资源整合项目
λ cd 前端页面\

D:\cmder\vendor/clink.lua:310: invalid use of '%' in replacement string
E:\Code\2017\住房城乡建设部信息系统资源整合项目\前端页面>
```

![image](https://user-images.githubusercontent.com/13060680/34285487-f13a3582-e714-11e7-8c27-28f2b4059b3c.png)

the command is also works well , but always show `D:\cmder\vendor/clink.lua:310: invalid use of '%' in replacement string`.

The cmder version is 1.3.4

**Comment by angrilove** [comment]
Can anyone solve it?

**Comment by GZ-ted** [comment]
应该是中文路径问题

**Comment by zuoliang0** [comment]
同问

**Comment by Stanzilla** [comment]
Should be fixed in the latest master builds

**Comment by leemoncn** [comment]
I have the same problem. My cmder version 1.3.6 (ConEmu 180528 preview).
![a d43ebg9svw h 4rji w9](https://user-images.githubusercontent.com/16697876/43619464-91d72446-9700-11e8-98e9-1a025fe7a5b8.png)
