### ISSUE TITLE
Please add a way to split panes without duplicating the background image

### ISSUE THREAD

**Issue by DavidTheProgrammer** [cmderdev/cmder#1598]
The title says it all. 

**Reproduction steps:**
+ Add a background image
+ Add macro to split panes vertically or horizontally
+ Split panes.

**Expected Result:**
The panes split while leaving the background image intact.

**Actual result:**
The background image gets duplicated with every new pane created.

**Comment by daxgames** [comment]
Upstream feature request. Request this from conemu.
