### ISSUE TITLE
Duplicate the tab's current directory maybe won't work in new version.

### ISSUE THREAD

**Issue by abrhambas01** [cmderdev/cmder#1600]
How can I duplicate the specific tab's current directory and do it in the second tab. Maybe it won't work in the new version? I tried right clicking on the tab and then chose duplicate root but it would only redirect me to this directory: 
C:\Users\PC_NAME

**Comment by tyler36** [comment]
Same problem with v1.3.3 & v1.3.4.
Worked fine in v1.3.2

Tried overriding the vendor directories with v1.3.2 versions but didn't work

**Comment by tyler36** [comment]
Seems to be fixed here with #1416

Try this:  https://ci.appveyor.com/project/MartiUK/cmder/build/1.0.521-master/artifacts
