### ISSUE TITLE
prompt sometimes becomes bold after command

### ISSUE THREAD

**Issue by philiparvidsson** [cmderdev/cmder#1602]
I'm using the default prompt (nothing in the config is changed except window startup position, which is automatically saved).
sometimes (seems random) after entering a command (can be any command) the prompt turns bold and stays bold. only solution is to close the tab and open a new terminal.

**Comment by Stanzilla** [comment]
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu
