### ISSUE TITLE
How to start cmd with folder in context menu ? WIN 10 [FlXED]

### ISSUE THREAD

**Issue by 001123** [cmderdev/cmder#1606]
![a](https://user-images.githubusercontent.com/32441266/34467970-1328da6c-ef31-11e7-8e99-f372cc08506d.png)
When i open d:/ and click Open with Cmder it always go to "C:\Users\Administrator" Frist ...?
How to fix this ? Thanks you

**Comment by remcoros** [comment]
Read through the comments of this issue: https://github.com/cmderdev/cmder/issues/91

a lot of workarounds there, hopefully, @Stanzilla can choose/make a definitive fix

**Comment by 001123** [comment]
@remcoros Thanks u 👍
