### ISSUE TITLE
[WSL] bash.exe causes Error: 0x80070005

### ISSUE THREAD

**Issue by rparolin** [cmderdev/cmder#1607]
![image](https://user-images.githubusercontent.com/1320845/34539974-a6801ce2-f087-11e7-97ff-1979eab1aa1c.png)

![image](https://user-images.githubusercontent.com/1320845/34540051-ec858452-f087-11e7-8d19-e3cb7f44b9d0.png)

This error only seems to have happen under cmder.  In a regular console bash.exe runs correctly.

**Comment by rparolin** [comment]
Was this issue fixed?

**Comment by Stanzilla** [comment]
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu
