### ISSUE TITLE
Incorrect path in Visual Studio after update

### ISSUE THREAD

**Issue by tyler36** [cmderdev/cmder#1610]
This was working for in Visual Studio yesterday.
```
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
    "terminal.integrated.shellArgs.windows": [
        "/k",
        "%CMDER_ROOT%\\vendor\\init.bat"
    ],
```

Updated to latest CMDER v1.3.4 and now terminal always opens @ %userprofile%

OS: Win10

**Comment by misox-git** [comment]
I have the same problem in Jetbrains IDEA. 
Shell path in terminal settings:
`"cmd" /k ""%CMDER_ROOT%\vendor\init.bat""`

It doesn't work in v1.3.3+ (So I keep using v1.3.2. until this is fixed)

**Comment by Stanzilla** [comment]
@tyler36 @misox-git can you get with latest `master`? Should have been fixed by https://github.com/cmderdev/cmder/pull/1416

Links are here https://ci.appveyor.com/project/MartiUK/cmder/build/1.0.521-master/artifacts

**Comment by misox-git** [comment]
@Stanzilla latest master works. Thank you.

**Comment by tyler36** [comment]
@Stanzilla, works with the #1416 fix as advertised.

Thanks!
