### ISSUE TITLE
ConEmuHK64 fault!!!Can't use the cmder....

### ISSUE THREAD

**Issue by miluokesiji** [cmderdev/cmder#1616]
When i open the cmder ,it‘s always  prompt "Injecting hooks into PID=XXXX FAILED,code=XXXXX".And then it's black .How to solve it~~~

**Comment by phobson** [comment]
I'm seeing this same behavior.

I'm on Windows 10 Enterprise 64-bit, build #1709.

Launching the extracted cmder.exe (downloaded today) pulls up the window, then this:
![image](https://user-images.githubusercontent.com/1163939/34964164-1461645a-fa01-11e7-9ba3-972b8be7a656.png)

Clicking "OK" let's you focus on the terminal window, but you cannot interact with it. Instead it just displays:

```
Generating clink initial settings in "C:\Users\phobson\Downloads\cmder\config\settings"
Additional *.lua files in "C:\Users\phobson\Downloads\cmder\config" are loaded on startup.
```
With no prompt before or after. The window does not seem to respond to keyboard input.

**Comment by Stanzilla** [comment]
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

**Comment by miluokesiji** [comment]
ok，thanks!
