### ISSUE TITLE
ssh agent is running but it's STILL asking for my password, why?

### ISSUE THREAD

**Issue by Boscop** [cmderdev/cmder#1620]
Following [this](https://github.com/cmderdev/cmder/wiki/%5BWindows%5D-Integrate-SSH-Agent-or-PuTTY-Agent) I put this in my user-profile.cmd (after a fresh install of Cmder):
```cmd
call "%GIT_INSTALL_ROOT%/cmd/start-ssh-agent.cmd"
ssh-add "C:\Users\me\.ssh\github_rsa"
```
This key works in my Git Shell, spawned from GitHub Desktop.
When I start Cmder, it says:
```
Found ssh-agent at 7596
Found ssh-agent socket at /tmp/ssh-YPk8hYjdtrea/agent.7108
Starting ssh-agent:  done

Identity added: C:\Users\me\.ssh\github_rsa (C:\Users\me\.ssh\github_rsa)
```
But when I then try to use it, it STILL asks for my password, so the key is not being used apparently, why?
(It doesn't ask for a password in Git Shell btw.)

I'd be very happy if you can help me get this working :)

**Comment by xelra** [comment]
This doesn't really have anything to do with Cmder, but ssh uses socket files based on the `SSH_AUTH_SOCK` environment variable. You need to point that to your socket file.

**Comment by Boscop** [comment]
Thanks :)
So which command should I run, to get it to work?
Shouldn't running `%GIT_INSTALL_ROOT%/cmd/start-ssh-agent.cmd` set the `SSH_AUTH_SOCK` var correctly?
