### ISSUE TITLE
Appended logs disapear when hit enter few times

### ISSUE THREAD

**Issue by Bazylot** [cmderdev/cmder#1621]
I am facing a nasty behaviour. I use maven to start Tomcat together with my web application. Maven is executing a certain goal wihich is responsible of starting Tomcat, deploy the application and wait until shutdown signal appears. Web application inside Tomcat logs many information which i can see in cmder console. 
Here comes the problem:
Sometimes for testing/debuging purposes i want to make console to have a gap between logs, so when i start some code snippet i will see only logs from this snippet. To do so i just hit enter multiple times to push some new line characters into cmder console. Many times when i do it the whole logs above just disappear and i can't browse it anymore until Tomcat send next log to the console, and cmder append it and print for me all logs back again.

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)
