### ISSUE TITLE
Problem getting cmder tab to open directory on startup

### ISSUE THREAD

**Issue by mattiasaronsson** [cmderdev/cmder#1622]
I have a problem to get cmder to open up a specific directory on startup.
(If I use git bash it works fine.)

First I tried to use cmd::Cmder task as a base and just change:
cmd /k "%ConEmuDir%\..\init.bat"  -new_console
to
cmd /k "%ConEmuDir%\..\init.bat"  -new_console:d:C:\test
But it did not change anything. Still opened to C:\Users\myuser

Next I tried to do it via saving current tabs into a task and open them up that way but same result.

I am running ConEmu version 171025 according to Help->Check for updates

//Mattias

**Comment by copper-ctl** [comment]
same issue here - running 171025 [64] {alpha} on windows 10

**Comment by nilfric** [comment]
Same for me. Also did not work with the latest ConEmu preview version 171109 on Windows 10.

**Comment by JohnCampionJr** [comment]
Same issue here.  My last copy of cmder at 1.3.2 does not have this problem.

**Comment by XTpeeps** [comment]
the same here...
