### ISSUE TITLE
Please add subdirectories of cmder_mini/bin to %PATH% automatically

### ISSUE THREAD

**Issue by DmitriyK-CPKIO** [cmderdev/cmder#1624]
It seems more convinient to sort command line tools in subdirectories in /cmder_mini/bin, but files in those subdirectories are not added to path and so are not accessible via autocomplete and run.

Please add those subdirectories to path recursively.

**Comment by DRSDavidSoft** [comment]
@Stanzilla Do you approve this feature to be implemented? I already made a PR to @daxgames's branch (assuming my method is accepted.)

**Comment by Stanzilla** [comment]
Yeah that's cool with me!

**Comment by DRSDavidSoft** [comment]
Alright, now we have to see if the method I used is okay with @daxgames.

**Comment by DRSDavidSoft** [comment]
@DmitriyK-CPKIO This feature has been implemented into cmder (nightly builds for now, it will be released once tested and verified to work correctly.)

We're also working on limiting the path depth (if it get's too long, it could possibly get truncated on Windows.) Could you specify usually how many directories you keep in the `/bin` directory?

**Comment by DmitriyK-CPKIO** [comment]
Three-four directory steps is OK I think.

**Comment by daxgames** [comment]
It will be configurable 1-5 levels with a default of 1 which means no subdirectories.
