### ISSUE TITLE
Multi line paste prompt - no way to disable?

### ISSUE THREAD

**Issue by andyd0** [cmderdev/cmder#1627]
Sorry if this is the wrong place for this question but I'm trying to disable the prompt that pops up whenever I go to paste in multiple lines into the window.  This is usually when I'm doing something related to programming.

**Comment by Stanzilla** [comment]
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

**Comment by zaphod77** [comment]
You are looking for "Confirm Critical Actions" In Keys & macro/Paste

There are two options. one for large pastes, and one for multi line paste.
