### ISSUE TITLE
Replacing icons

### ISSUE THREAD

**Issue by aplocher** [cmderdev/cmder#1628]
Is it possible for me (the end user) to replace these ugly ol' icons? 

![image](https://user-images.githubusercontent.com/1132447/35210125-ca542cbc-ff05-11e7-891a-9ad4a264a8f7.png)

Thanks!

**Comment by Stanzilla** [comment]
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu
