### ISSUE TITLE
Can't select and copy text

### ISSUE THREAD

**Issue by amercier** [cmderdev/cmder#163]
That would be a useful feature

**Comment by arunkumarselvaraj** [comment]
How an I change it to, click+drag for selection and ctrl+c for copy?

**Comment by MartiUK** [comment]
Settings > Keys & Macro > Mark/Copy > Text selection (Change Left Shift to <Always>)

**Comment by arunkumarselvaraj** [comment]
Thank you. I have few doubts as well..
1. I want VI editor, how do I bring it up?
2. Want to assign ctrl+z for undo, how to do it?

**Comment by MartiUK** [comment]
Instead of telling you how to do it, here is the documentation: https://conemu.github.io/en/TableOfContents.html
