### ISSUE TITLE
problem with kotlinc 

### ISSUE THREAD

**Issue by msdmirz** [cmderdev/cmder#1630]
when I hit enter cmder print input and output at output
`>>><enter>`
`>>> >>>`
or 
`>>> 2+2 <enter>`
`2+24`
`>>> >>>`

**Comment by Stanzilla** [comment]
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

**Comment by msdmirz** [comment]
thank you and sorry for my mistake
