### ISSUE TITLE
Vim is too slow to move cursor with my vimrc when editing file with lots content

### ISSUE THREAD

**Issue by tooyangtoonavie** [cmderdev/cmder#1631]
set cursorcolumn
set cursorline

highlight CursorLine   cterm=NONE ctermbg=DarkRed ctermfg=green guibg=NONE guifg=NONE
highlight CursorColumn cterm=NONE ctermbg=DarkRed ctermfg=green guibg=NONE guifg=NONE

My cmder version is v1.3.2

**Comment by Stanzilla** [comment]
remove the background color, should be fine then.

**Comment by tooyangtoonavie** [comment]
@Stanzilla 
I think is not a good idea.

**Comment by Stanzilla** [comment]
@tooyangtoonavie did you test it?

**Comment by tooyangtoonavie** [comment]
@Stanzilla 
I had tested , it does work, but I think it's a useful feature. Could the developer improve cmder's preformance? thx

**Comment by Stanzilla** [comment]
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)
