### ISSUE TITLE
using my Python from within cmder?

### ISSUE THREAD

**Issue by EMCP** [cmderdev/cmder#1632]
I tried running as administrator, which didn't change anything.

I'd attempted to add the `/REGISTER ALL` somewhere, but when I added it to the shortcut it seems to break Cmder from starting properly..  Any ideas?

**Comment by Stanzilla** [comment]
Please provide more information on what exactly you are trying to do

**Comment by EMCP** [comment]
Closing, python wasn't even in my CMD path.. I added it and it started to work without the need for `/REGISTER ALL` or anything fancy

**Comment by Noor-Shaik-Bose** [comment]
Is there a way to change my default python launcher to lambda cmder. When I double my test.py , it opens up in a windows cmd black terminal by default . How can i change this to launch in cmder. Should I write some .bat file?
