### ISSUE TITLE
Is it possible to run MATLAB in cmder?

### ISSUE THREAD

**Issue by pvonmoradi** [cmderdev/cmder#1633]
If I execute `matlab -nodesktop` in cmder, MATLAB opens in its own command window. I can run codes like 'x = 4', 'whos' or even 'plot'. But I want to do so in the original cmder window.  
I can do so with Python. After running `python` I can code in python right in cmder. I want to do the same thing with MATLAB. Here is a picture of MATLAB command window and a [doc link](https://www.mathworks.com/help/matlab/ref/matlabwindows.html).  
[https://imgur.com/a/Gi9C5](https://imgur.com/a/Gi9C5)

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)
