### ISSUE TITLE
what's the difference between 'cmd' and 'bash' when starting a new console ?

### ISSUE THREAD

**Issue by dingrui37** [cmderdev/cmder#1637]
Hi,all, I run cmder on windows, I want to know  what's the differences between 'cmd' and 'bash' when starting a new console ?

**Comment by glucas** [comment]
They will run two totally different shells. Use 'cmd' if you want to run a Windows cmd.exe shell; or use bash if you want to run a bash shell (using git-for-windows\bin\bash). 

You can go to Settings -> Startup -> Tasks to review the details of the different tasks that are defined.
