### ISSUE TITLE
Can't find VIM TagList and NERDTree commands in 'Cmder'

### ISSUE THREAD

**Issue by shreyansvm** [cmderdev/cmder#1638]
I can't move to the VIM TagList window when I'm using vim in 'Cmder'. 

I'm able to use :TlistToggle, :TlistAddFiles , etc commands.. but cannot move to the taglist window using (most common) way such 'Ctrl + w' 

same is with NERDTree. I'm able to start it using ':NERDTree', but how to access the NERDTree browser from 'Cmder' ?

I would really appreciate if someone can help me with this.

**Comment by shreyansvm** [comment]
Ctrl+W+W , Ctrl+W+P --> works.

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)
