### ISSUE TITLE
Unknown character

### ISSUE THREAD

**Issue by sansroman** [cmderdev/cmder#1639]
when I use ctrl+` show console ,Unknown characters appear like this:
![kc c vcekusph5y799 8yr](https://user-images.githubusercontent.com/17476682/35673006-2da64430-077b-11e8-8821-2db85fd6499d.png)

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)
