### ISSUE TITLE
Can't trust new host key

### ISSUE THREAD

**Issue by jursetti** [cmderdev/cmder#1640]
I am trying to ssh to a new server within Cmder. Since it's a new server I get this prompt:

Do you want to trust this new host key and continue connecting?
Please type 'no','once' or 'always':

I try to type always, but every letter  just causes the prompt to redisplay. Pretty soon it looks like this:

Do you want to trust this new host key and continue connecting?
Please type 'no','once' or 'always':

Please type 'no','once' or 'always':

Please type 'no','once' or 'always':

Please type 'no','once' or 'always':

What could be causing this problem? Is this a know issue? 

Thanks.

Jerry

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)
