### ISSUE TITLE
ConEmu being launched with fixed Title

### ISSUE THREAD

**Issue by pjc42** [cmderdev/cmder#1642]
This may be intended behaviour but by launching ConEmu with "/Title Cmder" argument ConEmu fixes the window title and so ignores any update to $host.UI.RawUI.WindowTitle.  

```c++
// CmderLauncher.cpp  176, 180
swprintf_s(args, L"/single /Icon \"%s\" /Title Cmder", icoPath);
swprintf_s(args, L"/single /Icon \"%s\" /Title Cmder", icoPath);
```

As a consequence the $Prompt call to update the WindowTitle is ignored.

```powershell
# profile.ps1 118
$host.UI.RawUI.WindowTitle = Microsoft.PowerShell.Management\Split-Path $pwd.ProviderPath -Leaf
```

**Comment by pjc42** [comment]
I set the Tab template Console to `$f`, the current dir, expecting this to result in the tab name changing to the current dir. 

Interestingly while this works in cmd shell it is not sufficient for powershell shell. ConEmu does not appear to be updating its value of the current working dir in powershell (and doesn't appear to update with a bash shell either).

You can manually update ConEmu's value for working dir in powershell by:
```powershell
#  config/user-profile.ps1 
# add to [ScriptBlock]$PostPrompt = {} to manually update ConEmu cwd
& "$ENV:CMDER_ROOT\vendor\conemu-maximus5\ConEmu\ConEmuC64" -StoreCWD $pwd
```

This is obviously a ConEmu issue not a Cmder one.


For the sake of completeness here is the ConEmu setting for tab template:
![conemu](https://user-images.githubusercontent.com/1176935/35759024-faa6ecd6-082b-11e8-9893-bd91453541e2.PNG)

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)

**Comment by keremispirli** [comment]
@Stanzilla I think you misunderstood this one. How can ConEmu being launched with "/Title Cmder" argument be a ConEmu bug? See: https://github.com/cmderdev/cmder/blob/master/launcher/src/CmderLauncher.cpp#L373
