### ISSUE TITLE
linux' s make menuconfig

### ISSUE THREAD

**Issue by SynneK1337** [cmderdev/cmder#1643]
I have been installing gentoo via ssh using cmder terminal emulator, and when I wanted to configure my kernel, i runned menuconfig and I' ve got something like this one in attachment
![gentoocmder](https://user-images.githubusercontent.com/26191968/35777751-85b63b82-09b3-11e8-98bf-46c337acae23.png)

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)
