### ISSUE TITLE
Trying to pipe command output to less on ssh terminates the ssh.exe process

### ISSUE THREAD

**Issue by mkierc** [cmderdev/cmder#1644]
Trying to pipe command output to `less` on `ssh` terminates the `ssh.exe` process:

```
P:\ ()
λ ssh service@192.168.61.201
...
/home/service#: history | less

0 [main] ssh 7620 C:\cmder\vendor\git-for-windows\usr\bin\ssh.exe: *** fatal error - cmalloc would have returned NULL
1288 [main] ssh 7620 cygwin_exception::open_stackdumpfile: Dumping stack trace to ssh.exe.stackdump

P:\ ()
λ 
```

The problem appears in the newest version (`171025`), it does not appear in previous version I had (`161022`).

If the dumpfile is necessary, I can add it - the error happened on a machine at work, and I don't have any server at home to test the ssh with.

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)
