### ISSUE TITLE
Colors in Visual Code

### ISSUE THREAD

**Issue by tyler36** [cmderdev/cmder#1646]
Cmder works fine for me except colors are off in Visual Studio Code.

The prompt shows in color (green path with red git branch). 
If I run, say PHP Code Sniffer, it out fine in the terminal window
```
W......W...........................W.... 40 / 40 (100%)
```

but displays the control codes(?) in VSCode 
```
?[33mW?[0m......?[33mW?[0m...........................?[33mW?[0m.... 40 / 40 (100%)
```

My VSCode settings are:
```
    "terminal.integrated.cursorBlinking": false,
    "terminal.integrated.cursorStyle": "line",
    "terminal.integrated.fontFamily": "Consolas, 'Courier New', monospace",
    "terminal.integrated.fontSize": 12,
    "terminal.integrated.lineHeight": 1.4,
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
    "terminal.integrated.shellArgs.windows": [
        "/k",
        "%CMDER_ROOT%\\vendor\\init.bat"
    ],
```

Any ideas?

OS: Win10
VSCode: 1.19.1 & 1.20.0

**Comment by AdsonCicilioti** [comment]
Use this:
```
"terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
    "terminal.integrated.shellArgs.windows": [
        "/K",
        "B:\\Apps\\Cmder\\vscode.bat"
    ]
```

Create a vscode.bat file on your Cmder directory with this hack:
```
@echo off
SET CurrentWorkingDirectory=%CD%
SET CMDER_ROOT=B:\Apps\Cmder
CALL "%CMDER_ROOT%\vendor\init.bat"
CD /D %CurrentWorkingDirectory%
```
... And be Happy!

**Comment by tyler36** [comment]
@AdsonCicilioti  Thanks for the the suggesting. But it didn't work.

I tried upgrading to 1.35 this morning but no go there either :(

**Comment by tyler36** [comment]
I get color in the prompt path, and I get color from yarn in VSCode

I just dont get color with PHP Code Sniffer or PHPunit when I run the terminal through VSCode. The commands show color in a normal Cmder terminal session though which is the frustrating thing.

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)

**Comment by DRSDavidSoft** [comment]
For future visitors, with the commits in #1665, there seems to be no need for the batch file mentioned [in the above answer](https://github.com/cmderdev/cmder/issues/1646#issuecomment-364687993). This has been also stated [here](/daxgames/cmder/pull/2).

<img width="679" alt="vscode_cmder" src="https://user-images.githubusercontent.com/4673812/36644451-f2509234-1a6f-11e8-8c84-889f800acc86.png">

**Comment by DRSDavidSoft** [comment]
@tyler36 As discussed in #1861, I think this is due to a problem in PHP binaries for Windows. I don't think that the same issue will happen by using something like [chalk](https://github.com/chalk/chalk) for example.

As I can see in your screenshot, the Clink part of Cmder has color, but `phpcs` which calls PHP binaries don't have color output correctly.

**Comment by tyler36** [comment]
@DRSDavidSoft  - thanks for an update ... I started down that rabbit hole before I made the original post but there didn't seem to be anything to try. As you said, PHP binary issue.

BUT ... came across https://github.com/php/php-src/pull/2103
Seems they were able to get some new code in PHP 7.2 for windows. 

Download [PHP 7.2.9 ( NTS x64)](https://windows.php.net/download/) and it works!

**Comment by tyler36** [comment]
PHP7.1
![php7 1](https://user-images.githubusercontent.com/7234392/44758306-a4891680-ab6e-11e8-85f4-49b6880f1bb4.png)

PHP7.2
![php7 2](https://user-images.githubusercontent.com/7234392/44758309-a5ba4380-ab6e-11e8-9825-76e02dea7403.png)

**Comment by DRSDavidSoft** [comment]
@tyler36 Thanks for the follow-up! Another reason to update to the `7.2.x` branch of PHP on Windows.

**Comment by joshpeng** [comment]
I am running into the same issue, but rather with Python instead of PHP. Anyone figure out how to solve this on Python CLIs?

The `| cat` suggestion works, but that's kind of annoying to type every time.
