### ISSUE TITLE
Incorrect display of characters

### ISSUE THREAD

**Issue by sqqqs** [cmderdev/cmder#1649]
This is [gtop](https://github.com/aksakalli/gtop) running in cmder:
`cmd /k "%ConEmuDir%\..\init.bat"  -new_console:`
https://lithi.io/file/6cKt.png

This is [gtop](https://github.com/aksakalli/gtop) running in cmd:
`gtop -new_console`
https://lithi.io/file/7Yz3.png

The lines in the cmder are not displayed. What should be fixed in init.bat?

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)
