### ISSUE TITLE
Unix commands not working on jupyter notebook for python 

### ISSUE THREAD

**Issue by SrihariGunji** [cmderdev/cmder#1651]
![image](https://user-images.githubusercontent.com/29956850/36071112-2eb833d6-0f2f-11e8-99b8-1bcc54e76eb4.png)

I am using git bash on windows 10.
All Unix commands working properly on Git Bash

Can anybody help me here.

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)

**Comment by SrihariGunji** [comment]
Hey, 

Thanks, @Stanzilla , for introducing good option ConEmu

anyway issue resolved when I opened jupyter from power shell, but not from cmd
