### ISSUE TITLE
can't save the environment settings

### ISSUE THREAD

**Issue by PromiseChan** [cmderdev/cmder#1652]
when I clicked the 'Save settings' and then closed the window,the code in line 869
![1](https://user-images.githubusercontent.com/28709322/36111578-8b909480-1061-11e8-9b2c-d7ceec4415b4.PNG)

did't save new changes in the file ConEmu.xml

**Comment by LucasZeng99** [comment]
@PromiseChan I had the same problem, had to hard code <line data="set LANG=zh_CN.UTF-8"/> in that file.

**Comment by PromiseChan** [comment]
@LucasZeng99 me too,directly coded in the file
