### ISSUE TITLE
Cmder/ConEmu enables menu key after idling for a few minutes

### ISSUE THREAD

**Issue by Frankusky** [cmderdev/cmder#1653]
Similar: https://github.com/cmderdev/cmder/issues/109
Hi, I has been facing a strange issue. After idling some minutes and focusing cmder again, the [menu key](https://fasteratexcel.com/wp-content/uploads/2015/11/menu-key-keyboard-excel.png) seems like its activated (I know that its that key since if I only type L key, it enables the highlighting feature that [ConEmu has](https://conemu.github.io/en/KeyboardShortcuts.html) {search at Apps+L combination}), I didnt find in settings something that causes this strange behavior. I think its not a keyboard issue since in other software my keyboard works as expected.

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)

**Comment by Frankusky** [comment]
Thanks, im not sure from where comes the issue so I opened here. Im openning an issue at ConEmu too. In case they make a fix how can I add it into my cmder?

**Comment by Stanzilla** [comment]
You can update ConEmu indepently from Cmder and we will package an eventual fix with the next release.
