### ISSUE TITLE
1.3.5 Regression: can't start in current directory anymore

### ISSUE THREAD

**Issue by jods4** [cmderdev/cmder#1654]
Up to 1.3.4, I had my tasks set up to start cmder in current directory, like so:
`cmd /k "%ConEmuDir%\..\init.bat" -new_console:d:"%__CD__%"`

After upgrading to 1.3.5 this doesn't work anymore and I suspect it might be related to changes for #921.

No matter what I tried, I can't make cmder start in the current directory in 1.3.5. :(

**Comment by Stanzilla** [comment]
@david-driscoll

**Comment by kaanid** [comment]
it is.

**Comment by jods4** [comment]
@kaanid what do you mean? "It is" possible to start in current dir? 
If so I would appreciate a description of how to do it, thanks!

**Comment by kaanid** [comment]
@jods4 sorry,
My situation is the same as yours

**Comment by kaanid** [comment]
I can't make cmder start in the current directory in 1.3.5！ too

**Comment by gpakosz** [comment]
Commit badb027c24c5a7d1152466f467f93f9f2e1579f6 got rid of `CMDER_START` environment variable and `vendor/profile.ps1` and `vendor/init.bat` just got stripped from the code that changed directory...

**Comment by daxgames** [comment]
@gpakosz are you suggesting the missing code should be added back?  What do your tasks look like in the conemu config?

**Comment by gpakosz** [comment]
@daxgames Your question gave me the idea to not port my configuration over when upgrading to 1.3.5 and now things more or less work again.

**Comment by gpakosz** [comment]
I say more or less because "Cmd Here" doesn't work for a drive root directory

**Comment by daxgames** [comment]
@gpakosz That's where I was heading.  I will look at the root drive complaint.

**Comment by gpakosz** [comment]
So yeah the tasks migrated from < 1.3.5 refer to `%USERPROFILE%` which likely explains why we always end up in the profile directory

**Comment by jods4** [comment]
So are you guys saying it is possible to open cmder in the current folder? 
Can you show me how to do that? 
I've tried using `-new_console:d:` in the task but I found no usable env. variable that represented the current folder... or it didn't work, somehow.

**Comment by daxgames** [comment]
@jods4 Yeah remove that and it should work, I think.  @gpakosz can you post your task config for @jods4?

**Comment by jods4** [comment]
@daxgames Remove what exactly?

If I remove `-new_console:d:...` completely from my task, it starts in `%USERPROFILE%` by default.

With Cmder 1.3.4 I had `-new_console:d:%__CD__%`. `%__CD__%` is supposed to be my current directory and it worked. Now with 1.3.5 this always resolves to `%CMDER%\vendor\conemu-maximus5`.

I think the real difference between 1.3.5 and 1.3.4 is the environment used when starting. Stuff like `%CD%` has changed meaning when used in task configurations.

**Comment by Stanzilla** [comment]
Yeah it's fixed, read the changelog for more info

**Comment by verglor** [comment]
@Stanzilla so when will be v1.3.6 released ? Also there is no changelog beyond v1.3.5 in [releases](https://github.com/cmderdev/cmder/releases).

**Comment by Stanzilla** [comment]
Not sure yet. Could probably do one soon with the next Git for Windows release.
