### ISSUE TITLE
Can't compile with g++ through cmd::cmder

### ISSUE THREAD

**Issue by Ekwy** [cmderdev/cmder#1655]
I installed g++ in mingw and msys, you can see them installed in the pictures below:
![image](https://user-images.githubusercontent.com/32315407/36261283-e131e6a6-1231-11e8-8dd9-0e70df9aae96.png)
![image](https://user-images.githubusercontent.com/32315407/36261329-ff5697bc-1231-11e8-9287-43e78f9dcb7d.png)

I also included both of those bin paths in my environment variable PATH (see last ones):
![image](https://user-images.githubusercontent.com/32315407/36261471-7e02868e-1232-11e8-9ed0-97fd0165b4b2.png)

This was done with the file user-profile.cmd in /config, see below:
![image](https://user-images.githubusercontent.com/32315407/36261547-b081f2a2-1232-11e8-8e28-0259a1c9884f.png)

I am able to compile with g++ using msys2 and mingw through cmder, see below:
![image](https://user-images.githubusercontent.com/32315407/36261725-56f4b7b4-1233-11e8-8f96-8997ef3a0fc0.png)

The problem happens when I try to compile using the cmd through cmder, see below:
![image](https://user-images.githubusercontent.com/32315407/36261772-778666a8-1233-11e8-9dfe-d4b246f560a1.png)

Nothing happens, I purposely didn't include stdio to have an error when compiling... no object files are made either...
I am kind of lost and I really don't know what's my mistake here... please help

**Comment by DRSDavidSoft** [comment]
Thanks for posting the details and including screen shots. Please also issue `where g++` and post the result here to see if any path in the `%PATH%` variable is interfering with the msys installation.

**Comment by Ekwy** [comment]
Sorry for the last response, not used to using those forums, I'm now subscribed to the post!
![image](https://user-images.githubusercontent.com/32315407/38007668-7d048af6-3218-11e8-9fee-fefba9503a7a.png)

**Comment by Ekwy** [comment]
As you can see above, the content of main.cpp should, at the time of compilation, display the following: 
![image](https://user-images.githubusercontent.com/32315407/38335732-5ee95928-382d-11e8-9d0e-0e0eae6ced90.png)
It's exactly the same main.cpp compiled in two different consoles.

The problem here is that g++ just doesn't seem to compile at all...

**Comment by S-NA** [comment]
Mixing different binaries breaks binary compatibility.* So in a sense your `PATH` is mangled in a way that breaks the expectation of some programs. The fix should be as simple as removing anything referencing, "git-for-windows" in your `PATH`.

*By different binaries, I mean binaries compiled under MSYS versus other environments like git-for-windows.

**Comment by daxgames** [comment]
Probably the easiest thing to do is to download the [Git for Windows SDK](https://github.com/git-for-windows/build-extra/releases) and add it to Cmder/Conemu:

Install Path: `c:\tools\git-sdk-64`

Task Name:  `Git SDK 64::bash`

Task:
`cmd /c ""c:\tools\git-sdk-64\usr\bin\bash" --login -i"`

or
`"c:\tools\git-sdk-64\usr\bin\mintty.exe" /bin/bash -l`

Task Parameters: ` /icon "c:\tools\git-sdk-64\msys2.ico"`
