### ISSUE TITLE
Trying to get cmder in vscode working perfectly

### ISSUE THREAD

**Issue by JimmyByte** [cmderdev/cmder#1656]
I've been trying to get cmder in my vscode environment as the terminal, and everything is working, minus the issue that when i press ctrl + ` and cmder is open, it switches to the open cmder instance.
This is very contrary to the expected behavior of vscode, which is that the terminal will open with a new instance of the terminal.

Dear developers, how do I make my current setup, which launches \vendor\init.bat with cmd /K, launch a new session of cmder in vscode? This would be a nice thing to get polished so that people can enjoy their cmder + vscode

**Comment by joekaiser** [comment]
You have a key-shortcut conflict I just changed the key-mapping for cmder. Instead of hiding/showing on ctrl+` I changed it to win+` Or, you can change it for VSCode.

**Comment by aindriu80** [comment]
I'm having this same problem, very confusing when you press CTRL and ' to see a new ConEmu screen popup outside VSCode.  You can't even type on it.   How do you get focus to the terminal instead ?

![image](https://user-images.githubusercontent.com/8885837/50741870-51e5f800-11fb-11e9-9ec6-b5185136031f.png)

I know you can press CTRL SHIFT ' to get a new terminal.

![image](https://user-images.githubusercontent.com/8885837/50741908-e94b4b00-11fb-11e9-9515-9c926a9bdaf0.png)

**Comment by zdog234** [comment]
@joekaiser asking for posterity, how did you change the cmder keymapping? (Is this a windows-level thing, or is it something I can find in the cmder settings?)

**Comment by joekaiser** [comment]
> @joekaiser asking for posterity, how did you change the cmder keymapping? (Is this a windows-level thing, or is it something I can find in the cmder settings?)

Open your cmder preferences and change the keybinding there.

**Comment by zdog234** [comment]
Thanks! I feel stupid now. I was clicking through all of the sub-menus under "Keys & Macro".
