### ISSUE TITLE
cmder.exe launch says git-bash.exe not compatible with the version of Windows

### ISSUE THREAD

**Issue by shrivatsahosabettu** [cmderdev/cmder#1657]
When I run the file I got the below message and now whenever I run the cmder.exe it says as `"This version of C:\Users\adm\Downloads\cmder\vendor\git-for-windows\git-bash.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher."`

```
Initial Message first time after install:
Generating clink initial settings in "C:\Users\adm\Downloads\cmder\config\settings"
Additional *.lua files in "C:\Users\adm\Downloads\cmder\config" are loaded on startup.
Creating initial user-aliases store in "C:\Users\adm\Downloads\cmder\config\user-aliases.cmd"...
        1 file(s) copied.
This version of C:\Users\adm\Downloads\cmder\vendor\git-for-windows\git-bash.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
Creating user startup file: "C:\Users\adm\Downloads\cmder\config\user-profile.cmd"
```

How to solve this?

**Comment by shrivatsahosabettu** [comment]
I have windows 8.1 and git version 2.15.1.windows.2.

**Comment by daxgames** [comment]
32 or 64 bit? Cmder uses 64 bit git-bash

**Comment by daxgames** [comment]
You could download and install 32bit git-bash and cmder or cmder mini with it.

**Comment by shrivatsahosabettu** [comment]
I am using 32 bit.. I will try with 32 bit gitbash..thank you

**Comment by shrivatsahosabettu** [comment]
I have installed the 32bit git bash, but still the error is same. Is there something wrong with my installation?

**Comment by daxgames** [comment]
Did you install git to  the default location?  You could try deleting. The cmder_root\vendor\git-for-windows folder

**Comment by shrivatsahosabettu** [comment]
Superb solution... Now the error is gone. Thanks for helping me out..
