### ISSUE TITLE
Cmder conEmu in Vim's Problem about charactor's width especially Chinese

### ISSUE THREAD

**Issue by humingkk** [cmderdev/cmder#1661]
![img_20180220_005109](https://user-images.githubusercontent.com/25192909/36391042-cf75d10a-15df-11e8-9128-f45ec6e31fed.jpg)
![img_20180219_012325](https://user-images.githubusercontent.com/25192909/36391047-d2640aa8-15df-11e8-8097-7ee7d3a2018a.jpg)

When I type :set vsplit in vim ,I want to create a new vertical window ,but someting happened, the demarcation line of two windows is irregular,I guess it's because of the unsure width of the chatactors, the chinese charactor's width is different from the English's charactor.
best wish,humingkk

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)
