### ISSUE TITLE
"clink.lua:44: invalid capture index" on folder with "%" character in the name.

### ISSUE THREAD

**Issue by luisfernandomoraes** [cmderdev/cmder#1663]

**Comment by jafin** [comment]
Experienced this issue.
Repro:
Open Shell, navigate to folder with %20 in it. ie (C:\Data\Dev\Foo%20\)
Then on the shell continue to receive message.
C:\PROGRA~1\cmder\vendor/clink.lua:44: invalid capture index

![2018-11-07 09_16_15-cmder](https://user-images.githubusercontent.com/127927/48100153-d94fd300-e26d-11e8-97eb-cce849305898.png)

Currently using ConEmu 171025

**Comment by jafin** [comment]
Apologies, updated to 1.3.6 of Cmder and problem does not reappear.
