### ISSUE TITLE
`LS` not showing color

### ISSUE THREAD

**Issue by sigmap** [cmderdev/cmder#1664]
the alias of `ls`, `ls --show-control-chars -F --color` outputs only white text. I tested older versions of cmder and found that `ls` from `msysgit` was able to produce color output but new versions with `git-for-windows` did not. I don't think this is a Window 7 issue but I'm not certain. I also tested this and reproduced this with a fresh install of the latest release of cmder.

**Comment by xelra** [comment]
I'm also on the latest version, albeit on Windows 10.

I have the following lines as aliases
```
ll=ls --show-control-chars -F --color $* -al
ls=ls --show-control-chars -F --color $*
```
I have no issues with color output.

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)

**Comment by sigmap** [comment]
It wasn't conemu.

**Comment by daxgames** [comment]
`ls --show-control-chars -F --color` - Works for me.  Running cmder 1.3.5+

**Comment by ryanjmartin** [comment]
> ```
> ll=ls --show-control-chars -F --color $* -al
> ls=ls --show-control-chars -F --color $*
> ```


This works for me as well. Thanks for sharing!
