### ISSUE TITLE
Ctrl+C - Disable terminate batch job question

### ISSUE THREAD

**Issue by xelra** [cmderdev/cmder#1666]
One of the most annoying things when working with the Command Prompt on Windows is the `Terminate batch job (Y/N)?` question that has to be answered after pressing `ctrl+c`.
Some people are ok with pressing `ctrl+c` twice, but this doesn't always work.

Cmder brings the Unix workflow to Windows and a great feature would be to suppress this question.

There's a little project called [CmdEx](https://github.com/sgraham/cmdEx/), which has exactly done that. Maybe the code could be mostly copied from that?

Thank you very much for considering.

**Comment by DRSDavidSoft** [comment]
@xelra Vote up for merging `CmdEx` into Cmder, alongside Clink!

**Comment by edmundo096** [comment]
This was somewhat previously commented on #1488

**Comment by edmundo096** [comment]
Also discussed here: #108 
Probably what samvasko pointed to on that issue, there is a setting inside `\cmder\config\settings` file:

```
# name: Auto-answer terminate prompt
# type: enum
#  0 = Disabled
#  1 = Answer 'Y'
#  2 = Answer 'N'
# Automatically answers cmd.exe's 'Terminate batch job (Y/N)?' prompts. 0 =
# disabled, 1 = answer 'Y', 2 = answer 'N'.
terminate_autoanswer = 1
```

That should do the trick.

**Comment by DRSDavidSoft** [comment]
Thanks @edmundo096! I added your solution to our wiki:
- https://github.com/cmderdev/cmder/wiki/Customization

**Comment by daxgames** [comment]
just run:

```
C:\Users\user\Documents$ clink set terminate_autoanswer 1
Settings 'terminate_autoanswer' set to '1'
```

**Comment by seezmash** [comment]
Using 'clink set terminate_autoanswer 1'
Returns 'ERROR: Setting 'terminate_autoanswer' not found.' in my case

I used 'clink set cmd.auto_answer 1' which adds 'cmd.auto_answer = answer_yes' to clink_settings
Problem solved 🙂

**Comment by chrisant996** [comment]
> Using 'clink set terminate_autoanswer 1'
> Returns 'ERROR: Setting 'terminate_autoanswer' not found.' in my case

That suggestion was given when Clink 0.4.9 was being used.
Clink overhauled its settings and renamed that one (all of them, actually).

> I used 'clink set cmd.auto_answer 1' which adds 'cmd.auto_answer = answer_yes' to clink_settings
> Problem solved 🙂

Yes, that's the new name.
Great to hear confirmation it's working as desired!

**Comment by chrisant996** [comment]
For the record:  I've also added backward compatibility with old setting names (except for a couple that have been removed).  That should make it so old posts that e.g. mention `clink set terminate_autoanswer` will still work, and will just get redirected to the corresponding new setting(s).

**Comment by DRSDavidSoft** [comment]
@chrisant996 Good idea, could you please also link the commit you made that enables this?

**Comment by chrisant996** [comment]
> @chrisant996 Good idea, could you please also link the commit you made that enables this?

I've linked it in the Clink repo and in the Clink documentation. Please feel free to link it here yourself if that seems desirable. That would be a nice way to help me out, so that I'm not single handedly doing all the things that are requested. I only have so much time.

(Yes it took me longer to write that than it would have to find the change and link it. But I'm setting boundaries, so it's worth it.)

**Comment by DRSDavidSoft** [comment]
@chrisant996 No worries, and thanks for all the wonderful work you're doing on Clink!  I'm afraid I wasn't able to find the commit that made this change at that time either in the [Clink.md documentation](https://github.com/chrisant996/clink/blob/master/docs/clink.md), or in [Commits history](https://github.com/chrisant996/clink/commits/master), hence the request.

However, upon further search, I found it at https://github.com/chrisant996/clink/commit/b7ccf598d9c3d2d559b72212a018a675d8fc9181, so I'd like to apologize for my request, and thank you for the time.
