### ISSUE TITLE
MSI-based installation should be an option

### ISSUE THREAD

**Issue by dneelyep** [cmderdev/cmder#1667]
It would be great if I could download an installer and have it show up in my list of programs, rather than having to locate and run an exe every time I want to run cmder.

**Comment by daxgames** [comment]
Create a shortcut.  Its a portable app.

**Comment by DRSDavidSoft** [comment]
There is a fork of Cmder called [shark](/kenijo/shark) which appears to have an installer (untested by us).

However, the beauty of Cmder is that it's _completely_ portable. It doesn't _really_ need an installer. :)
