### ISSUE TITLE
HttpRequestException with git push as of Feb 22, 2018

### ISSUE THREAD

**Issue by caleywoods** [cmderdev/cmder#1668]
I was running into an exception when trying to do a `git push` to any of my repos since yesterday when using cmder on Windows 10. I was able to find my way to [this issue](https://github.com/Microsoft/Git-Credential-Manager-for-Windows/issues/488) on the Git Credential Manager for Windows (GCM). 

Following the steps from @whoisj of:

1.) Run SET GIT_TRACE=1
2.) Run SET GCM_TRACE=1
3.) Reproduce your issue.

I was able to figure out exactly what was going on. It seems as though around Feb 22, 2018 (yesterday as of this writing) Github finally requires TLS 1.2 based on [this article](https://githubengineering.com/crypto-deprecation-notice/). Following the suggestion of upgrading my GCM to 1.14.0 by @dsyme fixed the error and username prompt for me in cmder. There are some other comments after that suggest this did not work for all users but instead they had to upgrade their git version.

Just opening this issue up for visibility for other cmder users who may come here first.

**Comment by kyle-west** [comment]
I am getting the same issue too. `git pull` works just fine, but `git push` makes me authenticate every time.

**Comment by caleywoods** [comment]
@kyle-west You may try the steps listed in that issue I linked to Git Credential Mgr for windows and update its version to [1.14.0](https://github.com/Microsoft/Git-Credential-Manager-for-Windows/releases/tag/v1.14.0) or the other suggestion from @massimonewsuk in that same issue of upgrading the Git version.

I'm not part of cmderdev though, I would be interested to  hear their official suggestions. You can either try the suggestions or wait for cmder to be updated, they may release a new version that bundles 1.14.0 of GCM.

**Comment by whoisj** [comment]
@kyle-west fetch/pull with GitHub is often unauthenticated so seeing the issue only during push makes sense. You likely need an updated GCM which can be had by updating just the GCM or updating Git for Windows.

Thanks @caleywoods, this is a very helpful thing you've done here. 😊

**Comment by Laoujin** [comment]
Same problem here. I updated Git Credential Manager for Windows and the problem went away:

https://github.com/Microsoft/Git-Credential-Manager-for-Windows/releases/tag/v1.14.0

**Comment by adelriosantiago** [comment]
Confirmed, @Laoujin solution works.
