### ISSUE TITLE
quick right docked tab key binding

### ISSUE THREAD

**Issue by AsadNoman** [cmderdev/cmder#1670]
I would prefer having a way to create another tab docked to right or left rather than the dialog being showed up.

**Comment by daxgames** [comment]
You can add this manually to your own config by creating a new task and using `-cur_console:s50H`.  The number is a percentage

Right Split:

![cmder_right_split](https://user-images.githubusercontent.com/7318053/36632155-4d798f68-1948-11e8-8fa6-25fdf0f825dc.png)

Bottom Split:

![cmder_bottom_split](https://user-images.githubusercontent.com/7318053/36632127-e52af1c2-1947-11e8-9f33-6b826dd7e524.png)
