### ISSUE TITLE
Vim is too slow to move cursor with my vimrc when editing file with lots content

### ISSUE THREAD

**Issue by tooyangtoonaive** [cmderdev/cmder#1672]
#1631 told about this bug. ConEmu'author has fixd it with new ConEmu version included 180206. It's very fast if I set config below at starting ConEmu 
![default](https://user-images.githubusercontent.com/19810827/36715133-d89fcb3c-1bcf-11e8-8d14-d5ac16448943.PNG)

**Comment by daxgames** [comment]
Outdated - Reopen if it is still an issue.
