### ISSUE TITLE
Aliases are not persisted between sessions

### ISSUE THREAD

**Issue by Demers94** [cmderdev/cmder#1674]
When I create an alias in `Settings` > `Startup/Environment` like this :

    alias code=cd Documents/code

It is not persisted when I close down Cmder and re-open again. I downloaded the full version (with Git) and unzipped it in the Downloads folder.

This is my Cmder/ConEmu version : 

![](https://i.imgur.com/Ckom57C.png)

And here is my OS info : 

![](https://i.imgur.com/nHoc70B.png)

I tried running it as Administrator. This is the storage page it's using for the config file : 

    C:\Users\<Username>\Downloads\cmder\vendor\conemu-maximus5\ConEmu.xml

**Comment by daxgames** [comment]
You are showing the conemu version which is a component of cnder.   The cmder version is in a file in the root dir, the current version is 1.3.5.  The only way to get the most recent version of cmder is to download the zip file and following the upgrade procedure in the [README.MD](https://github.com/cmderdev/cmder/blob/master/README.md)

Read the [README.MD](https://github.com/cmderdev/cmder/blob/master/README.md) and search for 'aliases' on how to set them.

**Comment by Demers94** [comment]
Hi dax, thank you for the fast reply.

I re-downloaded the newest `cmder.zip` from the releases page and extracted the zip. I'm now running version 1.3.5.

However, when I go to the Settings section, it's still using the same XML file in the `vendor/` directory for storage and my aliases are still not persisted. 

Are there any configuration files that are stored anywhere on the OS (ex: AppData or something) other than in the directory that I just extracted?

**Comment by daxgames** [comment]
I see you went back and looked at the Readme.md.  

Conemu and cmder are not the same thing.  Conemu is a component of cmder and it's config is stored in the conemu.xml file.

Cmder config is stored in `%cmder_root%\config` folder and it can include conemu config in various forms.  Again see the Readme.md

When cmder.exe starts and `%cmder_root%\vendor\conemu-maximus5\conemu.xml` does not exist and   `%cmder_root%\config\user-conemu.xml` does not exist `%cmder_root%\config\conemu.xml`, the default cmder specific conemu.xml file, is copied to `%cmder_root%\vendor\conemu-maximus5\conemu.xml`.

If cmder.exe starts and `%cmder_root%\vendor\conemu-maximus5\conemu.xml` does exist it is copied to `%cmder_root%\config\user-conemu.xml`.  This is done to preserve any conemu config changes your previous cmder session may have saved for future use.

When cmder.exe starts and `%cmder_root%\config\user-conemu.xml` exists and  `%cmder_root%\vendor\conemu-maximus5\conemu.xml` does not `%cmder_root%\config\user-conemu.xml` is copied to `%cmder_root%\vendor\conemu-maximus5\conemu.xml`.  
This is done to reapply any conemu config saved from a previous run.

This decision process happens each time cmder.exe is run.

**Comment by daxgames** [comment]
@Demers94 Is this still an issue with the current unreleased [version](https://ci.appveyor.com/project/MartiUK/cmder/builds/24321752/artifacts)?
