### ISSUE TITLE
%user-aliases% should be %user_aliases%

### ISSUE THREAD

**Issue by step-** [cmderdev/cmder#1675]
I think all instances of `%user-aliases%` and `user-aliases=` in vendor\init.bat (and possibly other files) should be `%user_aliases%` and `user_aliases` respectively. The dash isn't a valid character for batch script identifiers.

Running mini version 1.3.5 Win10 x64.

**Comment by step-** [comment]
Yes, I get a syntax error message, recalling from memory, something like "-aliases is an invalid identifier". Possibly my %CmdSpec% (TCC) is fussier than CMD about identifiers, I'm not sure.

**Comment by CollinChaffin** [comment]
Yes, the entire thing blows up with TCC due to the dash.  I agree why not keep it consistent all the conemu vars use underscores.  

Otherwise, you wind up with stuff like this in cmder (running the init.bat with TCC):
````
TCC: Unknown command "/c" echo "D:\Data\My"
TCC: Unknown command "/c" echo "D:\Data\My"
TCC: Unknown command "/c" echo "D:\Data\My"
TCC: Unknown command "/c" echo "D:\Data\My"
TCC: Unknown command "/c" echo "D:\Data\My"
TCC: Unknown command "/c" echo "D:\Data\My"
TCC: Unknown command "/c" echo "D:\Data\My"
TCC: Unknown command "/c" echo "D:\Data\My"
TCC: Unknown command "/c" echo "D:\Data\My"
TCC: Unknown command "/c" echo "D:\Data\My"
TCC: Unknown command "/c" type "D:\Data\My"
````

**Comment by daxgames** [comment]
not fixed - probably can't fix TCC/LE that I have access to appears to be incompatible with cmd.exe despite their docs saying it is.
