### ISSUE TITLE
Wrong HOME directory - SSH on WIN10 (latest official release)

### ISSUE THREAD

**Issue by ladislavsulc** [cmderdev/cmder#1677]
Hi,

I have the latest portable version of CMDER. When I try to create SSH key or use SSH, it always refers to the directory:

`\home\username\` instead of `c:\Users\username\`

Screen: https://i.imgur.com/9Snt431.png
![conemu64_2018-03-01_02-16-02](https://user-images.githubusercontent.com/3188341/36822218-261c66ae-1cf7-11e8-8c43-6307e55e53ba.png)

Even though my HOME directory variable is fine, CMDER still looks in the home folder as it would on Linux.

Any idea what could help me solve this?

Thank you.

**Comment by DRSDavidSoft** [comment]
Could you do `echo %HOME%` and `echo %USERPROFILE%`? I see a `"` (quotation mark) at the end of your HOME variable.

**Comment by ladislavsulc** [comment]
@DRSDavidSoft thank you, fixed that, but still it looks for a home directory:

https://i.imgur.com/foukYyq.png

![conemu64_2018-03-01_14-02-55](https://user-images.githubusercontent.com/3188341/36846034-5190f888-1d59-11e8-9bca-ef0c00ec6c12.png)

Tried that also with `ssh-keygen -t rsa` -> Enter file in which to save the key (/home/ladis/.ssh/id_rsa).

**Comment by DRSDavidSoft** [comment]
Make sure `C:\Users\ladis\.ssh` exists (`mkdir .ssh`) - from past experience, that's sometimes the problem.

Just to be sure, please also issue `where ssh`. It could be another ssh installation interfering.

**Comment by ladislavsulc** [comment]
It exists (existed), despite that path "bug" it wrote the server to known_hosts. Don't get it. There is no other .ssh folder.

**Comment by daxgames** [comment]
`which ssh` and post output?  You have multiple this will tell us which one is running.

**Comment by DRSDavidSoft** [comment]
@ladislavsulc Hm this seems to be an `chocolatey` issue rather than cmder – you can confirm this if you get the same results by running the same command in `cmd.exe` rather than Cmder.

In addition to `which ssh`, please post `ssh -V`. You might have an outdated version of OpenSSH installed. The best practice is using Cmder with either Cygwin (which has ssh built in), or easier to use vendored Git with cmder.

**Comment by ladislavsulc** [comment]
@daxgames `which ssh` > `/c/ProgramData/chocolatey/bin/ssh`.

@DRSDavidSoft cmd.exe shows the same except the GIT ssh. Same problem (but that is obvious since it is also linked with Chocolatey.

`which ssh` as stated above. `ssh -v` doesn't work. I have the latest version of OpenSSH, always keep my packages up to date.

Do you think I should try to uninstall OpenSSH so it would work with just the GIT (Bash) one?

Thank you for your help.

**Comment by ladislavsulc** [comment]
@DRSDavidSoft sorry, used -v instead of -V for `ssh -V` :( This is the output:

`OpenSSH_7.1p1, OpenSSL 1.0.2e 3 Dec 2015`

Thank you.

**Comment by DRSDavidSoft** [comment]
@ladislavsulc `OpenSSH_7.1p1` (the one that `chocolatey` uses) is obviously not the latest version, I have `OpenSSH_7.6p1` on my machine at the moment.

Try this:
`"C:\Program Files\OpenSSH-Win64\ssh.exe" csred_cz@csred.cz -p 22`

and report back if it works.

**Comment by ladislavsulc** [comment]
@DRSDavidSoft this works also with ssh-keygen, finally the right folder (`C:\Users\ladis`). What should I do now, please?

Thank you.

**Comment by DRSDavidSoft** [comment]
In my opinion:

1. Update the `%PATH%` priorities to use the OpenSSH installation first and _before_ any other SSH installations.
2. For Chocolatey, go to the installation directory and manually _remove_ or better, _update_ the `ssh.exe`.
   Personally, I would symlink it to a recent `ssh.exe` binary.

Change the PATH from:
<kbd>Windows</kbd> + <kbd>Pause/Break</kbd> → Advanced system settings → **Environment Variables...** (button at the bottom) → From **System variables**, choose **PATH** and then **Edit**.
Select the path with **OpenSSH** and move it **above** Chocolatey's path.

For example, here's an screenshot ofwhat my PATH are:

<img width="376" alt="path_list" src="https://user-images.githubusercontent.com/4673812/36871748-73af2d90-1db8-11e8-994e-0046ecbef012.png">

**Comment by ladislavsulc** [comment]
@DRSDavidSoft Thanks for all your help. Moving the variable for OpenSSH before the Chocolatey one now WORKS!

**Comment by ladislavsulc** [comment]
Let me just add that now it also uses the latest version `OpenSSH_7.6p1, LibreSSL 2.5.3`. 👍

**Comment by DRSDavidSoft** [comment]
@ladislavsulc Glad it works now for you. So, it wasn't really a Cmder issue!
If everything's fine now, please close the issue.

**Comment by FrankFang** [comment]
https://stackoverflow.com/a/2840909/1262580
Try set the variable HOME for Windows
