### ISSUE TITLE
Clarify Git branches

### ISSUE THREAD

**Issue by Jackbennett** [cmderdev/cmder#1679]
Hello, We should agree something acceptable here and then;

- [ ] Update README Current development builds a callout to contributing
- [ ] Update CONTRIBUTING.md with the clarifications from this issue
- [ ] Add a callout to CONTRIBUTING.md on cmder.net too (something small).

I'm sure there's various git flows with names we could subscribe to if you want but initially I thought to propose what my understanding was of how things seem to be done lately.

# Proposal

Pretty much what we already have it's just not completely clear. 

1. Master holds the latest acceptable changes
1. Keep master passing successful builds
1. Releases are tested and then tagged by a human
1. Any other branch can be for major changes somebody might want. But mainly work stays on master.

## Concerns
- As I understand our tests pretty much consist of only cmder compiling so that could use some work.

# In the Past
Initially we always had work and PR's on the development branch. As releases were packaged from master. Since then we've started using git and githubs tags to publish releases. There was always some ambiguity when a change was worth waiting to go through development or just apply onto master.

I pretty much focus on powershell and try to help where I can, I don't think I've ever cut a release so let's hear from @cmderdev/trusted-contributors as well as the community going forward. Related to the stalled #1372.

**Comment by MartiUK** [comment]
The majority of outside contributors never followed the "fork and make changes in the development branch" so I'm fine with dropping it.

I'd like to find some time into looking into automated GUI testing since I would think it would be more appropriate than just running the included scripts for consistency.

**Comment by Stanzilla** [comment]
@MartiUK I think you are the only person with enough permissions to delete it btw
