### ISSUE TITLE
bash task can not work when creating a new console if the cmder install path has space in it

### ISSUE THREAD

**Issue by jdhao** [cmderdev/cmder#1681]
I have find that when I want to create a new console with the predefined `bash::bash` task, an error occurred:

> 'D:\Program' is not recognized as an internal or external command,
> operable program or batch file.
> 
> 
> Current directory:
> C:\Users\jdhao
> 
> Command to be executed:
> "C:\Windows\SYSTEM32\cmd.exe"  /c "D:\Program Files\cmder\vendor\conemu-maximus5\..\git-for-windows\bin\bash --login -i"

it is because that the cmder is installed on `D:\Program Files\`. I have also found that if we simply use 
```
"C:\Windows\SYSTEM32\cmd.exe"  /c "D:\Program Files\cmder\vendor\conemu-maximus5\..\git-for-windows\bin\bash"
```
After some search and test, the correct way to use the command in case of a space in path is that:

```
"C:\Windows\SYSTEM32\cmd.exe"  /c ""D:\Program Files\cmder\vendor\conemu-maximus5\..\git-for-windows\bin\bash" --login -i"
```

**Comment by phcamargo23** [comment]
I Have the same problem.
