### ISSUE TITLE
Help needed - "Duplicate tab" in PowerShell

### ISSUE THREAD

**Issue by dallonf** [cmderdev/cmder#1684]
I would like to use the "Duplicate tab" shortcut to open a new tab in the same directory with PowerShell (this seems to work with cmd.exe). But when I use that shortcut, it opens in my home directory (or wherever I opened the instance of Cmder) instead of the current directory of the tab I duplicated.

I did try to follow the instructions in the [ConEmu docs](https://conemu.github.io/en/ShellWorkDir.html) - this was a little bit tricky as Cmder seems to override the prompt function differently, but ultimately I wound up tweaking the script in `config/user-profile.ps1` to look like this:

```
[ScriptBlock]$PostPrompt = {
    $dir = $(get-location).ProviderPath
    # You may use ANSI or direct ConEmuC call
    if ($env:ConEmuBaseDir -ne $null) {
        Write-Host -NoNewline (([char]27) + "]9;9;`"" + $dir + "`"" + ([char]27) + "\")
        & ConEmuC.exe -StoreCWD "$dir"
    }
}
```

But that doesn't seem to have much of an effect - even after restarting the console, the "Duplicate tab" shortcut still ignores the current directory I'm trying to set.

I must be missing something; I'm three levels deep in tech that's unfamiliar to me (Cmder, ConEmu, and PowerShell), so any enlightenment would be appreciated!

I don't necessarily need the full power of the "duplicate tab" feature, I just want a new tab in the same directory, so if you know of any other workarounds, that would be great too. It would be really cool if the dialog window for the "Create new console" keyboard shortcut automatically filled the directory of the current console tab for the "Startup directory for new process:" field, and that would fix my workflow too.

(This is probably related to https://github.com/cmderdev/cmder/issues/582, but that issue doesn't have a whole lot of information in it, so I figured I'd have more luck creating a new one)

**Comment by daxgames** [comment]
Right clicking a tab and choosing `Restart or Duplicate` is a feature of ConEmu and you are right it does not appear to work the same for Powershell.exe as it does with Cmd.exe.

You can however run `cmder /task powershel::powershell` and it will open a new tab in the same dir.
