### ISSUE TITLE
many powershell commands do not work in cmder powershell task

### ISSUE THREAD

**Issue by bitbonk** [cmderdev/cmder#1685]
There are a lot of things that work in the regular powershell command line (also with cmder attached) but that don't work when I start powershell cmder task. Here are some examples:

`λ $PROFILE`
>$PROFILE' is not recognized as an internal or external command, operable program or batch file.

`λ Install-Module -Name PowerShellGet -Force`
> Install-Module : A parameter cannot be found that matches parameter name 'Name'.

`λ Install-Module posh-git -Scope AllUsers`
> Install-Module : A parameter cannot be found that matches parameter name 'Scope'.

Both use the same version of powershell:

`λ  $PSVersionTable.PSVersion`
> Major  Minor  Build    Revision
> 5         1          15063  909

This is how my powershell task is configured:

`PowerShell -ExecutionPolicy Bypass -NoLogo -NoProfile -NoExit -Command "Invoke-Expression '. ''%ConEmuDir%\..\profile.ps1'''" -new_console:d:"%USERPROFILE%"`

What do I need to do that everything that works in the regular powershell also works with the cmder task?

**Comment by daxgames** [comment]
I just tested all of these and the work for me.  My task:

```
PowerShell -ExecutionPolicy Bypass -NoLogo -NoProfile -NoExit -Command "Invoke-Expression '. ''%ConEmuDir%\..\profile.ps1'''"
```

$PSVersionTable

```
PSVersion                      5.1.16299.248
```
