### ISSUE TITLE
UI Flickering in Coherence under Parallels 

### ISSUE THREAD

**Issue by fenneh** [cmderdev/cmder#169]
Bit of a unique one, but the UI appears to flicker quite a lot and the skin appears to be a Windows 7 non aero variant when running cmder under Coherence mod via Parallels on OSX. 

Windows Version = 8.1
OSX Version = 10.9.2
Parallels Version = 9

Screenshot attached (Minus the flickering ofc!)

![i78mi](https://f.cloud.github.com/assets/1257820/2467126/7f55e48e-afb9-11e3-948d-0d0efcd15c3c.png)

**Comment by alecgorge** [comment]
I solved this by disabling "Active window transparency" and "Use separate transparency value for inactive window" in "Features > Transparency"
