### ISSUE TITLE
Delete word leftward to the cursor (ignored in Far) Not working with Ctrl+Backspace

### ISSUE THREAD

**Issue by johanstenberg92** [cmderdev/cmder#1691]
Hi, recently switched from ConEmu to Cmder and deleting leftward word is not working with Ctrl + Backspace, oddly enough Alt + Backspace does it instead but it is not mentioned in the shortcuts.

How can I rebind to Ctrl + Backspace?

Thanks,

Johan

**Comment by johanstenberg92** [comment]
cmder version 1.3.5

**Comment by sqqqs** [comment]
In version 1.3.2, everything worked fine.

**Comment by DianaNites** [comment]
Have the same issue, and alt+backspace works as well.

I think clink is what causes this, as i've had the same issue when using just clink before.

This only occurs in CMDer windows, and powershell ignores the shortcut completely, ctrl+backspace works fine there.

ctrl+backspace also works if cmder autoattaches to a new cmd window, but then that window doesnt respect any of your settings like colors.

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)
