### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by chagensi** [cmderdev/cmder#1697]
After downloading and extracting the application to my desktop, I then ran cmder.exe as admin and got the following error message
```
Generating clink initial settings in "\support2.us.agas.group\users\PCDesktops\Chelsie.HagenSwiecic\Desktop\cmder\config\settings"
Additional *.lua files in "\support2.us.agas.group\users\PCDesktops\Chelsie.HagenSwiecic\Desktop\cmder\config" are loaded on startup.

The command prompt has been disabled by your administrator.

Press any key to continue . . .
```

![image](https://user-images.githubusercontent.com/37189373/37166425-9e090852-22c4-11e8-9f72-72da3c33601c.png)

**Comment by MartiUK** [comment]
Are you 100% positive that the command prompt has not been disabled in group policy?
