### ISSUE TITLE
Cmder navigation stopped working with forward bars

### ISSUE THREAD

**Issue by julioocamargoo** [cmderdev/cmder#1698]
I use the cmd terminal with Cmder and I'm having a problem with the navigation through folders. It works fine in the bash terminal, but I need to use the cmd.

Before:
Could navigate throught folders/files using only "/", "cd /c/dev/projects" for example. The autocomplete was also funcional this way.

After the last update:
I need to use reverse bars to navigate. "cd C:\dev\projects", for example.

**Comment by MartiUK** [comment]
Were you using cmd before when using forward slashes? Did you do this tweak? https://github.com/mridgers/clink/issues/395

**Comment by julioocamargoo** [comment]
I tried to do this tweak but the problem persists.

Yes, I always used cmd terminal. Actually, I use the default terminal when cmder open, that is cmd.

If it's possible to open bash terminal by default, it's ok for me. I use cmder integrated with VSCode and when that feature has stopped, it cost me a lot of productivity.

PS: The use of forward bar work neither cmder directly, nor with VSCode integration.

**Comment by daxgames** [comment]
@julioocamargoo `cd /c/dev/projects` is a git bash syntax and should not have ever worked properly in `cmd.exe` sessions.  Cmd.exe path syntax is `[drive]:\[folder]\[folder].

Clink supports using `c:\` or `c:/` in `cmd.exe` paths but the path to a specific drive will always need to begin with the drive letter and not a `/`.  This is just the way `cmd.exe` works.

You can configure `bash::bash` as the default `Cmder.exe` session in `Conemu->Setup tasks...->Startup->Specified named task`
