### ISSUE TITLE
git-for-windows is only 64 bit.

### ISSUE THREAD

**Issue by sptndc** [cmderdev/cmder#1699]
Cmder on the latest version is only get git-for-windows for 64 bit. How to get git-for-windows 32 bit in cmder latest version ?

**Comment by sptndc** [comment]
@lowtolerance Okay, thanks :+1:

**Comment by sptndc** [comment]
I replaced git-for-windows version 2.16.1.windows.4 64 bit to 2.16.2.windows.1 32 bit in the latest version of Cmder and this works perfectly for me. :100:

**Comment by Shinyhero36** [comment]
I can confirm that all you have to is to download git 32 and replace it with the one installed within CMDER.

**Comment by daxgames** [comment]
@Shinyhero36 there's more to it than that. We add a `%cmder_root%\vendor\git-for-windows\etc\profile.d\cmder.sh` and a modified `%cmder_root%\vendor\git-for-windows\etc\profile.d\git-prompt.sh`.  So if you want full Cmder functionality you could backup and restore these files after replacing git with the 32 bit package.
