### ISSUE TITLE
weird tabbar drawing problems

### ISSUE THREAD

**Issue by luca76** [cmderdev/cmder#1700]
Hi, when I maximize then restore window, the tabbar is drawing with problems, as you can see in this image. I'm using cmder on a windows 7 PC, connected via remote desktop.

![cmder](https://user-images.githubusercontent.com/5095918/37200283-97182206-2384-11e8-9cbd-7bc8f2c14e43.png)

**Comment by MartiUK** [comment]
Does this happen on a non-remote desktop session?

**Comment by daxgames** [comment]
Closing due to lack of response.
