### ISSUE TITLE
Found old git but not using...

### ISSUE THREAD

**Issue by cra0zy** [cmderdev/cmder#1703]
So testing out few shells for windows, and I noticed I get this message from cmder even tho I have the newest git installed:

```
Clink v0.4.9 [git:2fd2c2] Copyright (c) 2012-2016 Martin Ridgers
http://mridgers.github.io/clink

Generating clink initial settings in "C:\Program Files\cmder\config\settings"
Additional *.lua files in "C:\Program Files\cmder\config" are loaded on startup.
Found old git version in "C:\msys64\usr", but not using...

C:\Users\Harry>git --version
git version 2.16.2

C:\Users\Harry>
```

**Comment by daxgames** [comment]
Cmder version?

**Comment by cra0zy** [comment]
Newest one from the website, not sure where I can check it.

**Comment by cra0zy** [comment]
1.3.5

**Comment by daxgames** [comment]
Try saving this [init.bat](https://raw.githubusercontent.com/daxgames/cmder/init_args_rebased/vendor/init.bat) to `%cmder_root%\vendor\init.bat`

**Comment by cra0zy** [comment]
The system cannot find the batch label specified - enhance_path

**Comment by daxgames** [comment]
@cra0zy -  UGH....Sorry about that.  Try this build of [cmder mini](https://ci.appveyor.com/api/buildjobs/ihawfb7w6pet2gp6/artifacts/build%2Fcmder_mini.zip) it is from #1696

**Comment by cra0zy** [comment]
Yup, that solves the error.

**Comment by daxgames** [comment]
Cool thanks.

**Comment by DRSDavidSoft** [comment]
Related issue - #1564
