### ISSUE TITLE
Run Cmder inside VScode

### ISSUE THREAD

**Issue by ifyour** [cmderdev/cmder#1704]
### VSCode settings

```
"terminal.integrated.env.windows": {"CMDER_ROOT": "D:\\soft\\cmder"},
"terminal.integrated.shellArgs.windows": ["/k D:\\soft\\cmder\\vendor\\init.bat"],
```

### It's work!! :+1:  

![image](https://user-images.githubusercontent.com/15377484/37265334-af52bc12-25ed-11e8-9ed3-f9d2df2fbe9a.png)

**Comment by codesboy** [comment]
@ifyour 为什么我按照你上面的的配置配置好之后，重启vscode，然后打开终端就报错， 
![_20180316213242](https://user-images.githubusercontent.com/9047357/37523478-0c4f8716-2962-11e8-8cdb-3b8891d8edbe.png)

**Comment by ifyour** [comment]
@codesboy 你这个是 powershell ？你的 Comder 确定是以 `cmd` 启动的

**Comment by codesboy** [comment]
@ifyour 每错 是以cmd启动的，win10+cmder1.3.5+vscode1.12.1
![_20180316224638](https://user-images.githubusercontent.com/9047357/37527008-e7ee4240-296b-11e8-9272-6aed47c1f3e0.png)

**Comment by ifyour** [comment]
@codesboy 参考下这里 http://www.igakki.com/?p=329

**Comment by codesboy** [comment]
@ifyour 我在vscode里添加了一项配置`"terminal.integrated.shell.windows": "cmd.exe",` 然后就可以了

**Comment by DRSDavidSoft** [comment]
## Running VS Code with Cygwin on Cmder
![Running VS Code with Cygwin on Cmder](https://i.imgur.com/RKN3Avl.gif)

**Comment by DRSDavidSoft** [comment]
More info: https://github.com/Microsoft/vscode/issues/12006

**Comment by etiennejcharles** [comment]
Doesn't work if path cotains spaces, this would be a better example
```
 "terminal.integrated.shellArgs.windows": [
    "/k C:\\Program^ Files\\cmder\\vendor\\init.bat"
  ]
```

**Comment by upupming** [comment]
Also, remember to replace the `λ` in `cmder/vendor/clink.lua`, otherwise there will be an invisible extra whitespace when you use left/right arrow keys:

```
// Before
local lambda = "λ"

// After
local lambda = "$"
```

**Comment by HoneyHunter** [comment]
" Terminal.integrated.shell.windows " : " cmd.exe " ,
    "terminal.integrated.env.windows": {"CMDER_ROOT": "C:\\apps\\cmder"},
    "terminal.integrated.shellArgs.windows": ["/k C:\\apps\\cmder\\vendor\\init.bat"],

It's only working when you use the cmder into VS Code.
If you try to change the VS Code terminal to Bash or powershell, you will get an error.
I don't know how to fix it. 
![vsCode](https://user-images.githubusercontent.com/46455799/64914675-8d5b9d80-d75e-11e9-83fb-9d785e54c174.png)

**Comment by cooper1x** [comment]
```
"terminal.integrated.shell.windows": "cmd.exe",

  "terminal.integrated.env.windows": {
    "CMDER_ROOT": "C:\\sx\\cmder_mini\\Cmder.exe"
  },
  "terminal.integrated.shellArgs.windows": [
    "/k",
    "C:\\sx\\cmder_mini\\vendor\\bin\\vscode_init.cmd"
  ]
```
为什么我的不行呢？
![image](https://user-images.githubusercontent.com/9080789/66696080-4af49480-ecfb-11e9-9053-56e627141295.png)
按照文档写的
![image](https://user-images.githubusercontent.com/9080789/66696088-55af2980-ecfb-11e9-9f66-f0d606544b27.png)
[Seamless VS Code Integration · cmderdev/cmder Wiki](https://github.com/cmderdev/cmder/wiki/Seamless-VS-Code-Integration)

**Comment by cooper1x** [comment]
上个问题解决了，是我写错了路径，把Cmder.exe去掉就好。
另外想问下，如果想关联为git bash版本的cmder怎么配置呢？

**Comment by kabirsumn** [comment]
> ## Running VS Code with Cygwin on Cmder
> ![Running VS Code with Cygwin on Cmder](https://camo.githubusercontent.com/a7489811aeb64a7cb9d33b390515c1bdf57e117a/68747470733a2f2f692e696d6775722e636f6d2f524b4e3341766c2e676966)

how did you do that?
