### ISSUE TITLE
Incorrect behavior of quake-mode console

### ISSUE THREAD

**Issue by Xeizzen** [cmderdev/cmder#1705]
If you set it to hide when it lose focus, when you bring it, it won't get focus and it causes it to infinitely show up again.
In other words: you try to bring the console, it shows up, but it doesn't get focus, and after that if you try to hide it again, it starts to infinitely hiding and showing up again.
Only if you click on it, to make it focused, only after that it starts to work normally.

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)
