### ISSUE TITLE
ssh-add.exe loading slowly

### ISSUE THREAD

**Issue by popey456963** [cmderdev/cmder#1708]
New commander terminals have recently been taking longer and longer to start up.  It seems to get frozen on:

    get-add.exe

With the terminal logging:

    Found ssh-agent at 3744
    Found ssh-agent socket at /tmp/ssh-NLlEGSBUxZsq/agent.9508

At the moment it's taking 10 seconds, last month it was taking 5.  To my knowledge my computer has not changed at all, definitely not slowing down 50%.

**Comment by MartiUK** [comment]
Do you have an aggressive AV? It scanning ssh-add.exe every time it runs would cause an issue like this.

**Comment by popey456963** [comment]
Woah, excellent catch @MartiUK, that hadn't even passed my mind.

Disabling Norton (my AV) made cmder start up almost immediately, as did (for a more long term solution), white listing half a dozen cmder executables.

**Comment by MartiUK** [comment]
Glad to have helped
