### ISSUE TITLE
start in current directory

### ISSUE THREAD

**Issue by alex-jitbit** [cmderdev/cmder#1709]
If a program is started in a dir - it should **work in that dir.** It's been a standard for years in almost every operating system. Like, when you type `git` - it looks at the current directory (!), not some home user profile folder or whatever.

When you type "cmder" in the command prompt or in a file manager (Total Commander, Far, etc) or wherever - you want it to start in the current dir, just like any other program would do.

`cmder` always starts in my home folder. Wasn't expecting that from a tool that claims "it gets console"

Thanks for considering

**Comment by alex-jitbit** [comment]
I'm not a C++ dev, but it seem a pretty easy fix. In `CmderLauncher.cpp` [line 214](https://github.com/cmderdev/cmder/blob/17247f2065f48ad99385abb519b196981e054825/launcher/src/CmderLauncher.cpp#L214) just change it from `GetEnvironmentVariable(L"USERPROFILE", buff, MAX_PATH);` to some `GetCurrentDir` 

https://stackoverflow.com/a/145309/56621

**Comment by SuperSandro2000** [comment]
Use cmder minimal and external git

**Comment by alex-jitbit** [comment]
what? I mentioned git as an EXAMPLE. A program started in a dir should be working in that dir.

**Comment by SuperSandro2000** [comment]
Probably missunderstud you. Your right

**Comment by daxgames** [comment]
Fixed see #1725

**Comment by jods4** [comment]
@daxgames So that will fix #1654 as well, right? Just starting cmder without any parameter will be in the current directory? Nice 👍

**Comment by alex-jitbit** [comment]
thanks @daxgames just tested - everything's fine
