### ISSUE TITLE
Problem with CTRL + W and Nano

### ISSUE THREAD

**Issue by osuwariboy** [cmderdev/cmder#1711]
I use cmder to connect to my Linux servers and my preferred editor happens to be Nano. However, to make a search in Nano, you have to type CTRL + W... which is instantly caught by cmder which asks me if I want to close the window. Couldn't there be a way to tell cmder to forward the keys to the terminal and not do anything with them? As it is, if I want to search a file, I have to use another terminal software, which is kind of irritating.

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)

**Comment by jozsefsallai** [comment]
Just a little follow-up on this - you can remap the key combination in the Cmder settings: 

![Cmder settings](https://i.imgur.com/GY2uul3.png)

I personally prefer to use `Ctrl+Alt+W` 😄

**Comment by tigercosmos** [comment]
@jozsefsallai  thanks. I just think about how to use ctrl+w in vim.
