### ISSUE TITLE
[Bug] Double Ctrl+C is glitch Console 

### ISSUE THREAD

**Issue by goodrank** [cmderdev/cmder#1712]
If the shortcut ctrl + c is pressed 3-4 times quickly in the active window, the active window freezes. It helps only reboot.
The screenshot shows how the bug occurs, the cursor hovers below the line of code entry.
what to do?

 
[image-1](https://image.ibb.co/nRf3hx/15_03_2018_15_09_56.jpg)
[image-2](https://image.ibb.co/cdN5vH/15_03_2018_15_10_34.jpg)

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)
