### ISSUE TITLE
alias doesn't seem to work...

### ISSUE THREAD

**Issue by andyd0** [cmderdev/cmder#1713]
I read that previous versions had issues with newer builds of Windows 10 and that it should have been corrected in 1.3.5.  I've downloaded and now don't get an error when trying to use an alias but it doesn't do anything either.  For example, I have this in environment...

alias mc=cd D:\Documents\OneDrive\Documents\MC

It could be that I have the format incorrectly as well but when I type "mc" at prompt nothing happens.  I tried quotes around the path and that didn't work.

**Comment by gtalarico** [comment]
@andyd0 I also could not get aliases to work properly on newer windows, even with the latest release.
My current workaround is to enable legacy mode on the cmd prompt, as described here:
https://github.com/cmderdev/cmder/issues/1509#issuecomment-338423681

**Comment by daxgames** [comment]
Aliases work fine on newer Windows if it's not there is something not right with your config folder most likely.  What shell are you using?

**Comment by gtalarico** [comment]
You are correct. I did a fresh install and it seems to be working. Thanks

**Comment by andyd0** [comment]
Is this the proper command?

```alias mc=cd D:\Documents\OneDrive\Documents\MC```

Because I tried a fresh install and the setting isn't sticking

**Comment by daxgames** [comment]
@andyd0 What she'll?

**Comment by andyd0** [comment]
Just the cmd shell.
