### ISSUE TITLE
Text garbled: Unable to use vi with cmder or bash as cygwin or xterm

### ISSUE THREAD

**Issue by slayerfat** [cmderdev/cmder#1714]
Greetings!

There's an issue with Cmder, the terminal is not working properly within vi in different servers and versions even with different shells and terminals, i tried bash and cmder and both fail with cygwin and xterm, however inside mintty vi works fine.

i did a quick search in the issues and found no answers there, im sorry if this issue already exists.

inside a random server with vim version 7.2.108
![image](https://user-images.githubusercontent.com/7544518/37561532-e04fe4ba-2a26-11e8-8cb9-17165712a67d.png)

The issue persist even in the vim version 8.0.606 provided with the default installation.

![image](https://user-images.githubusercontent.com/7544518/37561546-541f8404-2a27-11e8-878c-b7196d609f88.png)

i'm thinking this could be related to some $TERM variable somewhere or something similar, im hope any of you guys could help me with this, thx!

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)

**Comment by slayerfat** [comment]
@Stanzilla oh! ic, sorry!
