### ISSUE TITLE
Uninstalled cmder (still present when right-clicking)

### ISSUE THREAD

**Issue by Sebastian-Nielsen** [cmderdev/cmder#1715]
I uninstalled cmder and deleted the folder it was located in. (`C:/Program files (86x)/cmder`) 
But for some reason, whenever I right click in the file explorer. 

If I click on the cmder in the "right-click" popup, I get the following error: https://cl.ly/243R4621272z

"This file does not have a program associated with it for performing this action. Please install a program or, if one is already installed, create an association in the Default Programs control panel."

**Comment by daxgames** [comment]
That's because you deleted the files.  The easiest thing to tell you is out the files back where you had them and unregister the shell extension by running cmder.exe with the `/UNREGISTER ALL` and `/UNREGISTER USER`.  Confirm the shell extension is gone then delete the files if you want to.

**Comment by Sebastian-Nielsen** [comment]
Before I deleted the directory in which cmder was located. I did run the commands you stated. I don't remember exactly the output when running those commands, but I know for sure that they didn't raise any errors.

**Comment by joannesalfa** [comment]
When i did `/UNREGISTER ALL`  then I got:

https://i.imgur.com/xwsm5s4.png

**Comment by AmirthaRajan** [comment]
I have the same Problem and yet unable to uninstall even with the provided commands
![image](https://user-images.githubusercontent.com/13075625/108303816-acb8ee80-71cc-11eb-8e4c-8265943c297f.png)

I would like to reopen this ticket!!!
