### ISSUE TITLE
powerline + zsh + win bash, right section shows on second line

### ISSUE THREAD

**Issue by yanjingzhaisun** [cmderdev/cmder#1716]
Hi,

Here is my problem: the powerline status shows on the secondline. Same setting works fine in mac system.

Screen shot:
![image](https://user-images.githubusercontent.com/6327230/37569581-fc6947f6-2aba-11e8-8eba-7ec6786a027c.png)

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)
