### ISSUE TITLE
cmder display error after using vim

### ISSUE THREAD

**Issue by GavinLi369** [cmderdev/cmder#1717]
Does anyone have this problem?
This is screenshot after I quit from vim.
![default](https://user-images.githubusercontent.com/15731822/37574694-b6e9c838-2b5d-11e8-91dc-8e6f47817456.PNG)

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)

**Comment by DRSDavidSoft** [comment]
@GavinLi369 Please do a `where vi.exe` and post the screen shot here.

**Comment by GavinLi369** [comment]
![default](https://user-images.githubusercontent.com/15731822/37833752-19ddab44-2ee7-11e8-89c5-2890a9e529dc.PNG)
@DRSDavidSoft This means unable to find file with provided mode.

**Comment by DRSDavidSoft** [comment]
@GavinLi369 Thanks for the translation, please do this instead:
`where vim.exe`

**Comment by DRSDavidSoft** [comment]
@GavinLi369 Okay, could you do this please?
`vim.exe --version`

**Comment by GavinLi369** [comment]
@DRSDavidSoft 
![1](https://user-images.githubusercontent.com/15731822/37834991-13cb74fe-2eea-11e8-9a47-916e5b1e7fdd.PNG)
![2](https://user-images.githubusercontent.com/15731822/37835022-23c72998-2eea-11e8-82ea-8da82979356f.PNG)

**Comment by DRSDavidSoft** [comment]
@GavinLi369, ok, so I can confirm that you are using the latest version from the Cmder's vendored Git.

Some things to consider:
- Does running `E:\Program Files\cmder\vendor\git-for-windows\usr\bin\vim.exe` from Windows `CMD.EXE` result the same way?
- Did you resize your Cmder window when you were in VIM?

**Comment by GavinLi369** [comment]
![default](https://user-images.githubusercontent.com/15731822/37835711-bf159ac8-2eeb-11e8-9a17-f26fce747bb0.PNG)
@DRSDavidSoft This is the result of my running in Windows `cmd.exe`. Its looks the same as Cmder. And I don't resize Cmder window when I'm in Vim.

**Comment by DRSDavidSoft** [comment]
@GavinLi369 Thanks for the result, I'm afraid to say that this is not an issue of Cmder, though we appreciate you reporting it.

This is most probably an issue related to the msys32's Git for windows installation of VIM, with which each of them may lay the problem.

Personally, I use the slightly less useful Nano editor on both Linux an windows, but I recommend opening an issue here to report this misbehavior of VIM on windows:
https://github.com/vim/vim/issues
This would fix the problem for **others** as well, if the authors of VIM find it reproducible.
(As always, it's recommended to look for closed issues first.)

Another option is to ignore this, and use an `alias` to clear screen after you exit VIM, which is personally my favorite. Like so: `vi=vim $* ^& clear`

I hope this helps you. :)

**Comment by GavinLi369** [comment]
@DRSDavidSoft Thank you for your patience to help me solve this problem.
