### ISSUE TITLE
'Cmder Here' context menu entry no longer opens 'here'

### ISSUE THREAD

**Issue by PeteAndersen** [cmderdev/cmder#1718]
Occurring since upgrading to 1.3.5. The context menu option added with `.\cmder.exe /REGISTER ALL` no longer seems to have any effect. Cmder window opens with the prompt wherever it happened to be last.

**Comment by daxgames** [comment]
Working on this....

**Comment by daxgames** [comment]
Fixed [here](https://ci.appveyor.com/project/MartiUK/cmder/branch/master/artifacts)

Remove `/newconsole:d:*` arguments from your default cmder task.
