### ISSUE TITLE
Problem with using vim in cmder

### ISSUE THREAD

**Issue by pvonmoradi** [cmderdev/cmder#1719]
I'm using cmder:bash with the vim which comes with cmder (full-version). I'm also using vim-plug for plugin management.  
Problem is, `colorscheme` plugin does not work as expected. It seems it is conflicting with cmder colors. 
**1-** How can I solve this issue?   
**2-** Where is `.vimrc` located? In `cmder\vendor\git-for-windows\etc` ?  
**3-** Why `echo $MYVIMRC` prints nothing in bash?  
**4-** Why `echo $TERM` prints `cygwin` in bash? Shouldn't it print `xterm`?   
  
Thanks in advance

**Comment by Stanzilla** [comment]
https://github.com/cmderdev/cmder/issues/468

**Comment by pvonmoradi** [comment]
But it's not duplicate. #468 has syntax highlighting issue but my syntax highlighting is fine. I have issues with themes and colors.

**Comment by daxgames** [comment]
@pvonmoradi the color issues you are asking about is simply a limitation of the Windows console subsystem which cmder uses.  I don't think your going to find a fix, I tried for months.

**Comment by pvonmoradi** [comment]
@daxgames But I'm using bash (not cmd). Does that limitation still apply? Do you have any idea about my other questions? (2, 3 & 4)

**Comment by daxgames** [comment]
@pvonmoradi 

Yes it does.  I use come every day and love it.  I experimented and found a color scheme I can live with but am not completely happy with.

`bash->mintty` does not use the Windows console subsystem but introduces a whole bunch of other issues.

2.  `%userprofile%\.vimrc` just like always
3.  What do you expect it to print?  I would say nothing.
4.  $TERM is set to `cygwin` by one of the init scripts, I don't know which one.  If you don't like it change it by setting it to whtever you think it should be in `$CMDER_ROOT/config/user-profile.sh`

**Comment by pvonmoradi** [comment]
@daxgames Thanks. So I just need to change cmder's colorscheme using the menu configs then in this way, vim would accept that setting?
About .vimrc, when I enter `:scriptnames` in vim, it is showing me that it is loading something from this `/etc/vimrc` which I gather is the .vimrc file. No .vimrc file resides in my $home directory. Are you sure about this? Can you check which scripts are loaded at vim startup by `:scriptnames` command?

**Comment by daxgames** [comment]
I don't know what setting you are trying to set.  I think I run the default cmder color scheme and played with setting a color scheme in .vimrc.

If you put .vimrc in your home dir it will load from there.  I believe the one in /etc loads first then the one in home loads second.

**Comment by grufffta** [comment]
For the solarized theme you need to add and select the Solarized (Luck Maciack) colour scheme, if you don't want to change the cmder theme switch out solarized for the Molokai theme it works perfectly as well
```    
if (&term == "pcterm" || &term == "win32")
        set term=xterm t_Co=256
        let &t_AB="\e[48;5;%dm"
        let &t_AF="\e[38;5;%dm"
        set termencoding=utf8
        set nocompatible
        inoremap <Char-0x07F> <BS>
        nnoremap <Char-0x07F> <BS>
endif
set background=dark
colorscheme solarized
```

**Comment by cutejs** [comment]
In case it's useful for anyone else, after I added the settings suggested by @grufffta I was getting crazy random colored boxes drawn all over the screen, and struggled for a long time before I stumbled upon the answer: my theme didn't have a background color set for terminals. Once I added one to the theme, everything became normal. Thank you so much for your suggestion!

```
hi Normal                 cterm=NONE             ctermbg=234  ctermfg=145
```

**Comment by OutbackMan** [comment]
@grufffta Could you please explain how this works and how to apply it for Solarized light in cmder and vim respectively? Thanks

**Comment by grufffta** [comment]
> @grufffta Could you please explain how your `.vimrc` config works and how to apply it for the Solarized Light colourscheme in Cmder and Vim respectively? Thanks

You should just be able to change `set background=dark` to `set background=light` you can also select the normal solarized theme in cmder - but they don't have to be the same, you'll just get whatever the cmder theme background colour as the margin around the vim app.
