### ISSUE TITLE
Misaligned cursor in wsl zsh

### ISSUE THREAD

**Issue by specter119** [cmderdev/cmder#1720]
I use the new wsl download from app store, the distribution is debian.
The cursor is aligned with input in bash & zsh with native wsl app and bash with cmder. But it is not misaligned in zsh with cmder.

Zsh and bash in cmder
![zsh and bash in cmder](https://user-images.githubusercontent.com/8768524/37693020-c4c3b7a2-2cf7-11e8-95aa-ef7813f6138b.png)

My task setting
![tim 20180321111020](https://user-images.githubusercontent.com/8768524/37693109-7cb5d660-2cf8-11e8-93e9-c5f1455f4415.png)

In vscode integrated cmder, it seems more werid.
Cursor is misaligned only when it coming after a space, it seems like four spaces in front of the cursor but only one.

my vscode settings

```json
    "terminal.integrated.fontFamily": "Meslo LG S for Powerline",
    "terminal.integrated.fontSize": 12,
    "terminal.integrated.shell.windows":"C:\\Windows\\sysnative\\cmd.exe",
    "terminal.integrated.shellArgs.windows" : ["/K","C:\\Users\\Specter119\\scoop\\apps\\cmder\\current\\vendor\\init.bat"],
    "terminal.integrated.env.windows": {
        "CMDER_ROOT": "C:\\Users\\Specter119\\scoop\\apps\\cmder\\current"
    },
```

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as term...
