### ISSUE TITLE
Cmder.exe should have a version number

### ISSUE THREAD

**Issue by lennybacon** [cmderdev/cmder#1729]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 
To distinguish versions of the file it would be helpful if the file property for version would be set.

![image](https://user-images.githubusercontent.com/272164/37960829-ec881e72-31b6-11e8-9555-2d55e11d7d1b.png)

**Comment by DRSDavidSoft** [comment]
## fix in #1730 preview:
<img width="296" alt="cmder_version" src="https://user-images.githubusercontent.com/4673812/38048217-febdfbd8-32d9-11e8-9524-5e7ad286852b.png">
