### ISSUE TITLE
How to use pacman as cmder's msys2 package manager?

### ISSUE THREAD

**Issue by pvonmoradi** [cmderdev/cmder#1731]
cmder-full comes with its own internal `git`, and msys2 tools like `curl` and `ssh`. I need `gcc `so I installed msys2 **externally**. 
Now, I have two directories in my C drive: C:/cmder and C:/msys64
However, msys2's console has `pacman` which is a nice package manager if I want to install something.

**1-** How can I force cmder use my own external msys2 files so I can use `pacman`? I already need `gcc `so I must have the external msys2 install.
**2-** If I want to keep the internal msys2, how can I use `pacman `to extend and update its tools?
**3-** If I want to only use my external msys2, would there be any remaining reasons for me to have the full version of cmder? In that case I can have cmder-light and just use `pacman `to install `git `and `vim `alongside `ssh`, `gcc `and `curl`, right? 

Sorry for these n00b questions and thanks

**Comment by SuperSandro2000** [comment]
Start msys trough cmder

**Comment by SuperSandro2000** [comment]
Search for the msys.exe and run it. Don't know if it works but it could.

**Comment by S-NA** [comment]
I recently required the need of other *nix tools on Windows and found that MSYS2 would be the most painless way to go about getting them. The quickest way I have gotten everything to set up is doing the following:

Visit the official MSYS2 website: http://www.msys2.org/
Download the relevant executable to install MSYS2: `msys2-x86_64-20161025.exe` is the one of question, at the time I am writing this.
Download cmder-full, and extract it to a directory, we can call it `cmder\`.
Run the MSYS2 executable, and set the install path to `<location-to>\cmder\vendor\msys64\`
Click `Setup tasks...` (<kbd>Win</kbd>+<kbd>Alt</kbd>+<kbd>T</kbd>).
Create a predefined task named `{bash::msys2}`.
Task parameters: `/icon ...` (set whatever icon you want).
In the larger box now type: `cmd /c "%ConEmuDir%\..\msys64\usr\bin\bash.exe" --login -i`

You should now be able to create a new-console that is `{bash:msys2}`. This console should now contain bash that has `pacman`. 

You may want to modify `cmder\vendor\init.bat` specifically around the line that says: `:: Prepare for git-for-windows` to set `PATH`.

Do not forget to copy in your `.ssh` and the like into `<location-to>\cmder\vendor\msys64\home\<username>`

Note, there are more permanent methods which involve installing MSYS2 into the host but this method works for putting `cmder` on a removable disk.

**Comment by pvonmoradi** [comment]
@S-NA Based on your guides, I just selected "Add/Refresh Default Tasks" and somehow cmder detected many shells on my system (MSYS2-64, putty, ...). Now I just use CTRL+T and msys2 and I can use PACMAN there.
So I assume using this solution, packages are saved to the default MSYS2 dir.
But your solution seems better since it is portable AND used PACMAN as package manager. Wouldn't installing unix utilities and particularly GCC require installing on host? I can just install msys2 and pacman packages inside cmder and most utilities just run off that path?
Thanks
