### ISSUE TITLE
Is It Possible to recover the files removed by `rm -rf` 

### ISSUE THREAD

**Issue by Xsmael** [cmderdev/cmder#1733]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [- ] Question

### Description of the issue 
Is It Possible to recover the files removed by `rm -rf` 

Where do those files go ? or are they erased permanently ?

**Comment by daxgames** [comment]
You could try Google and search 'undelete files rm -rf windows git bash' without the quotes but I do believe they are indeed gone.
