### ISSUE TITLE
Change Background Path to same location as Cmder.exe

### ISSUE THREAD

**Issue by arenacheck** [cmderdev/cmder#1734]
Hello first of all thanks to cmder for this awesome terminal tool <3 So many awesome functions!

Not really a problem but I can´t find a way to use pathes like:
.\sample.jpg
./sample.jpg
Also I do not test it but I think homepath variables like from cmd are also not supported.

The only paths that work are full paths like:
C:\testfolder\sample.jpg

Is there a way to hardcore a background image with changing internal codes lines or is there another way to change the background path to the same location as the Cmder.exe or the bin folder?

The problem is if I want to universal store my image as example to C:\user\AppData\\.sampleProject\bg.jpg

Then I can´t copy & paste my cmder folder to a new machine with new username without that the bg.jpg from above gets lost because the username change. Of course I could change the path to a path without username inside but I must use this folder from above.

Any ideads?

**Comment by daxgames** [comment]
@arenacheck Ask over at [ConEmu](https://conemu.github.io/) if you can add a path to a background image using an environment variable in the path like "%cmder_root%\config\bg.jpg".  If not ask for the feature to be added there.
