### ISSUE TITLE
Unable to override powershell prompt from user-profile.ps1

### ISSUE THREAD

**Issue by scott-wi** [cmderdev/cmder#1736]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 

You're currently unable to customize the powershell prompt from "$env:CMDER_ROOT\config\user-profile.ps1" as the "$env:CMDER_ROOT\vendor\profile.ps1" overrides the prompt *after* running the user profile script.  

The issue appears to be how the prompt is being overridden in the profile.ps1 script:
```
# Once Created these code blocks cannot be overwritten
Set-Item -Path function:\PrePrompt   -Value $PrePrompt   -Options Constant
Set-Item -Path function:\CmderPrompt -Value $CmderPrompt -Options Constant
Set-Item -Path function:\PostPrompt  -Value $PostPrompt  -Options Constant

# Functions can be made constant only at creation time
# ReadOnly at least requires `-force` to be overwritten
Set-Item -Path function:\prompt  -Value $Prompt  -Options ReadOnly
```

If you move the above lines of code *above* execution of the user-profile.ps1, the prompt is properly customized when opening a new cmder/ConEmu tab. 

This appears to be a common problem as shown by the below gist post where people are bypassing cmder's profile.ps1 altogether: 
https://gist.github.com/jchandra74/5b0c94385175c7a8d1cb39bc5157365e 

It feels like Cmder should always honor customizations that are being performed in user-profile.ps1 so that workarounds like editing profile.ps1 or switching back to Powershell's default profile.ps1 won't be required.

**Comment by pezcode** [comment]
I'm running into the same problem using virtualenv for Python. It tries to customize the PS shell:

```powershell
    # Set the prompt to include the env name
    # Make sure _OLD_VIRTUAL_PROMPT is global
    function global:_OLD_VIRTUAL_PROMPT {""}
    copy-item function:prompt function:_OLD_VIRTUAL_PROMPT
    function global:prompt {
        Write-Host -NoNewline -ForegroundColor Green '(env) '
        _OLD_VIRTUAL_PROMPT
    }
```

which gives me an error: *Cannot write to function prompt because it is read-only or constant.*.

**Comment by daxgames** [comment]
Look at the latest unreleased [version](https://ci.appveyor.com/project/MartiUK/cmder/builds/24321752/artifacts) for a fix.
