### ISSUE TITLE
window+D command not working properly from cmder 

### ISSUE THREAD

**Issue by gpatel93** [cmderdev/cmder#1737]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 
when cmder is open and I press windows+D to go to desktop, and on desktop if I search for let say "application" - cmder will take it as input text and desktop search wont work

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)
