### ISSUE TITLE
Environment setting in Startup do not support multiline command

### ISSUE THREAD

**Issue by xycui** [cmderdev/cmder#1738]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 
When the user try to set the variable in the envrionment setting. Only the first line is saved into the **ConEmu.xml**
#### Repro steps:
1. Open the settings of the Cmder
2. Insert/Append a line in the text box of Startup/Environment setting section.
3. 'Save settings' and close the cmder instance
4. Open the cmder instance again and check the Startup/Environment section. 
 
*Expected:* Multiline in the text box
*Actual:* Only the first line of the setting

Version Info: 180206 preview

![image](https://user-images.githubusercontent.com/2989428/38238209-c506aab2-375b-11e8-89e3-86995c9c214c.png)

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)
