### ISSUE TITLE
Window position and size is wrong and changes itself

### ISSUE THREAD

**Issue by kleinfreund** [cmderdev/cmder#1740]
### Purpose of the issue

- [x] Bug report (encountered problems/errors)

### Description of the issue 

I just downloaded cmder and started configuring it. I struggle with setting up the window position and size. There are several issues with that. I’m running Windows 10.

First of all, let me clarify the following options are turned on:

- Show & store current window size and position
- Auto save window size and position on exit

Unfortunately, these settings do not work as expected.

**Issue 1:** Setting a fixed window position of `x: 0` and `y: 0`.

- Expected: The window will be positioned in the top left corner of the screen and its position will be remembered.
- Actual: See attached screenshot. For some reason, cmder’s settings will show `x: 7` as the configured value now. I have not set that. The position was not remembered.

![2018-04-06-09-47-38 microsoft store](https://user-images.githubusercontent.com/5774638/38408882-94f5b450-397f-11e8-9f33-f1b0514293f1.png)

**Issue 2:** Setting a fixed window size of `width: 104` and `height: 1047px`.

- Expected: The dimensions of the window adjust and are remembered.
- Actual: First of all, for some reason, the previously wrong value for the screen position changes from `x: 7` to `x: 14`. After closing and starting the application again, the value for the window height is now `height: 1033px`. The value was not remembered as well.

---

So far, nothing that I set under Size & Pos works as expected. I can’t control the window size and position and have cmder start in that configuration again.

**Comment by daxgames** [comment]
All use cases work for me, I can't duplicate.

**Comment by kleinfreund** [comment]
I experience this on multiple systems. This issue is not resolved.

**Comment by daxgames** [comment]
Cmder version? Have you tried a nightly build?

**Comment by daxgames** [comment]
@kleinfreund 

Reopened at user request

**Comment by kleinfreund** [comment]
Steps to reproduce:

1. Download cmder mini and extract.
2. Start cmder and press <kbd>WIN+Right Arrow</kbd> to position the window in the right screen half. Close cmder.
3. Start cmder. The window is not positioned as before. There are gaps to the right and the bottom.

**Positioning before closing**:

![photo5343975279971903832](https://user-images.githubusercontent.com/5774638/47003696-2ab5e800-d130-11e8-8d52-7fa0e64eda35.jpg)

**Positioning after re-opening**:

![photo5343975279971903831](https://user-images.githubusercontent.com/5774638/47003712-330e2300-d130-11e8-9be2-ef1af50d5e55.jpg)

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)

**Comment by kleinfreund** [comment]
I see. As this is most likely an upstream issue, I’m closing this.

**Comment by MrEduar** [comment]
@kleinfreund I am having the exact same problem, did you find a solution to this?
