### ISSUE TITLE
Againe CMDER environment problem.

### ISSUE THREAD

**Issue by mrG0bliN** [cmderdev/cmder#1742]
windows x64 10 
cmd environment work,
in cmder not work =\
i twice restard pc, in classic cmd all work, but in cmder not undertand my new params 
![](https://image.ibb.co/mpFknH/image.png)
![](https://image.ibb.co/gCjs1c/10_04_2018_13_40_24.jpg)
![](https://image.ibb.co/kCh1ux/10_04_2018_13_39_51.jpg)
![](https://image.ibb.co/fgguEx/10_04_2018_13_39_40.jpg)
What should I do now???

**Comment by Stanzilla** [comment]
Why do you add environment variables in the task? Also you did not add yarn to PATH, you made a new Yarn variable

**Comment by mrG0bliN** [comment]
@Stanzilla 
i found solution: new path -> %APPDATA%\npm\node_modules\yarn\bin\
and cmder now works correctly
