### ISSUE TITLE
Getting error using setx to set environment variables.

### ISSUE THREAD

**Issue by Chigogo** [cmderdev/cmder#1746]
### Purpose of the issue
- [x ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x ] Question

### Description of the issue 
I use SetX to set user-level environment variables. 
I do this in cmd: `setx test1 1`;
I do this in cmder: `setx test2 2`:(the pic says success)
![](https://i.loli.net/2018/04/16/5ad4ad59f1c77.png)

I restart cmd, and do this: `echo %test1%`
![](https://i.loli.net/2018/04/16/5ad4ad2392bc1.png)

I restart cmder, and do this: `echo %test2%`
![](https://i.loli.net/2018/04/16/5ad4ad8a8f722.png)

**Comment by daxgames** [comment]
You need to completely close cmder and restart it for setx vars to be available.  I tested this and it works.

**Comment by daxgames** [comment]
The only solution would be to close and relaunch both cheer and wox.  It is not a big in either app

**Comment by Chigogo** [comment]
@daxgames Solution is so simple that relaunch is no-need. Just use set and setx at same time.

**Comment by daxgames** [comment]
Yeah that would work too.
