### ISSUE TITLE
[Documentat] History of the project?

### ISSUE THREAD

**Issue by ghost** [cmderdev/cmder#1747]
Hello,

Could the history be expanded a little?

E. g. when cmder was started (the year) in particular is what I am interested in.

On a side note, https://en.wikipedia.org/wiki/ConEmu has a wikipedia entry
whereas cmder does not; yet I feel that cmder is more active (I may be wrong
given that I use Linux a lot more than WIndows, but perhaps this also explains
my curiosity a little.)

Feel free to close this issue at any moment in time, if the topic is considered
unnecessary.

**Comment by DRSDavidSoft** [comment]
I'm also interested in the history of Cmder!

Some notes I'd like to mention: Cmder's very [first commit](https://github.com/cmderdev/cmder/commit/ef9bbdab6ae03bd3109ab26f633e68cd5729dc27) was made on Jul 9, 2013, by @samvasko.

He started Cmder as a collection of configurations for ConEmu, and until a few later versions, Cmder did not have its own launcher.

The website (cmder.net) hasn't changed much from the creation of the project, as you can see the website's history at web.archive.org.

Also, don't be mistaken. ConEmu has much active development, in fact, our maintainers update Cmder's ConEmu to the latest version a couple of times each month:
https://github.com/cmderdev/cmder/commits?author=Stanzilla

Maximus, the ConEmu author patches bugs and adds new features to ConEmu each day. Cmder is built with the latest version of ConEmu each time it's released, and even new versions of Cmder are released when the underlying ConEmu is updated.

Also, there are key differences between Cmder and ConEmu. ConEmu is designed to work _just_ as a terminal emulator, and it isn't expected to perform anything else than emulating the Console API of windows. Cmder, on the other hand, is designed as a powerful, beautiful and unified complete package consisting of Git, Clink and its own profile configuration (color schemes, tasty lambada prompt symbol, etc.) So, Cmder _uses_ ConEmu (or any other Terminal emulators) to form the complete terminal.

Although the original author meant Cmder to be used only with ConEmu, [Cmder on VS Code](https://imgur.com/RKN3Avl) and [Cmder on on Hyper](https://imgur.com/RKN3Avl) are still Cmder, even if those don't use ConEmu. There's even a fork of Cmder called [Shark](https://github.com/kenijo/shark) which provides Cmder with both ConEmu and [Console2](https://github.com/cbucher/console) as an alternative (though in my opinion ConEmu is superior to Console2 and ConsoleZ).

I'd like to see a Cmder wikipedia page, though!

**Comment by samvasko** [comment]
Got mixed reviews on hacker news for the first time. https://news.ycombinator.com/item?id=6802777

**Comment by DRSDavidSoft** [comment]
@DRSDavidSoft This should be added to the Wiki.
