### ISSUE TITLE
Repeated errors about non-existent pipe when in git repo folders

### ISSUE THREAD

**Issue by FieldMarshallVague** [cmderdev/cmder#1748]
I'm using v1.3.5 full (having tried Mini) on Win 10 64.

When I change directory into a folder with a Git project in it, I get the following error:

![image](https://user-images.githubusercontent.com/2116744/38831480-71cc25aa-41b7-11e8-8b74-6ba918be1942.png)

Every time I hit enter (even when not inputting a command), I get the same 14 lines of error.  I've looked all over the settings and the only files running are the one auto-generated when CMDer updates (says so in the files themselves).

Any idea what might be causing this?  I can't find anything online and it just doesn't make much sense that it is running anything in a Git repo folder.

**Comment by Stanzilla** [comment]
Hey there! Can you do me a favor and try a dev build and tell me if it happens there as well? Thanks!

Dev builds: https://ci.appveyor.com/project/MartiUK/cmder/build/1.0.646-master/artifacts

**Comment by FieldMarshallVague** [comment]
@Stanzilla Hi, thanks for responding.  I tried the full dev build and am getting the same error (also 'ls' doesn't work and isn't recognised, for some reason?).

When the cmd.exe tab loads, I am getting 
Error: git --version
Press any key to continue...

But 'git --version' works fine when the prompt appears.

I had a hunch that it might be something to do with my aliases.cmd file (auto-running via command processor registry entry), so I removed them and that seems to solve the problem.  But I can't see why it does?  This is the whole file:

![image](https://user-images.githubusercontent.com/2116744/38861619-e96bfcfc-422a-11e8-96e5-36b692c01238.png)

And this is the registry entry used to load them:

[HKEY_CURRENT_USER\Software\Microsoft\Command Processor]
"AutoRun"="%USERPROFILE%\\aliases.cmd"

This appears correctly in regedit, btw.

I guess, right now, CMDer just isn't compatible with auto-running scripts via the command processor registry entries and this should be done via CMDer's own interface?

**Comment by FieldMarshallVague** [comment]
I can confirm that I was ballsing up CMDer's own alias system by using the windows cmd approach.  It's far easier just to edit the user-aliases.cmd file in the %CMDER_ROOT%/config folder.  I just applied the same alises used above, but without the 'DOSKEY' prefix (i.e. follow the examples in the user-aliases.cmd file).
