### ISSUE TITLE
"Open Cmder Here" context menu option doesn't work with "Quake style slide down" enabled

### ISSUE THREAD

**Issue by emzero** [cmderdev/cmder#1749]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 
With the "Quake style slide down" option, using "Open Cmder Here" context menu option with Cmder already opened doesn't open a new tab in the corresponding directory, instead it opens a new tab in the same directory as the already opened tab.

If Cmder is not opened, then the option works as expected.

**Comment by daxgames** [comment]
@emzero Try the latest release, it works for me.
