### ISSUE TITLE
你好,我遇到问题

### ISSUE THREAD

**Issue by zjbdiy** [cmderdev/cmder#1752]
ls 无法显示中文文件名  请问要怎么设置才行

**Comment by zjbdiy** [comment]
而且 在Settings>Startup>Environment中 添加配置无法保存

**Comment by zjbdiy** [comment]
I'm sorry to bother you. I really like this software, but I have a problem. I can't display the Chinese directory correctly in cmder. Try setting the encoding in Settings>Startup>Environment, but I cannot save the second line. I can only delete the previous line. The configuration, leaving only set LANG=zh_CN.UTF8, solved my problem. Is this a bug?

**Comment by kumamiko** [comment]
@zjbdiy 我也遇到这个问题了，不管是不是用管理员权限打开cmder，在Environment里的设置无法保存。
然后我直接打开  ....\vendor\conemu-maximus5\ConEmu.xml 
手动添加“<line data="set LANG=zh_CN.UTF-8"/>”这一行，不知道这是不是某种蜜汁bug

<value name="EnvironmentSet" type="multi">
	<line data="set PATH=%ConEmuBaseDir%\Scripts;%PATH%"/>
	<line data="set LANG=zh_CN.UTF-8"/>
</value>

**Comment by YinAoXiong** [comment]
@kumamiko  thank you ，I  also meet this problem.
And it work for me.
