### ISSUE TITLE
Startup directory doesn't work if cmder is launched with a path

### ISSUE THREAD

**Issue by johntk** [cmderdev/cmder#1755]
If I launch cmder using "C:\cmderDir\cmder\Cmder.exe" /START "%passedPath%", the "Start directory for new process" will always open the new tab using the path stored in passedPath, rather than the path I have entered in the control.

The result is the same if I use Open Cmder Here.

**Comment by daxgames** [comment]
This should be fixed in latest builds [here](https://ci.appveyor.com/project/MartiUK/cmder/branch/master/artifacts)
