### ISSUE TITLE
cmder can not Tab-complete S attribution file or dir

### ISSUE THREAD

**Issue by Justsoos** [cmderdev/cmder#1756]
which been set by attrib.exe +s, native cmd of Windows10 can tab-complete, but cmder can not.

**Comment by daxgames** [comment]
Cmd.exe will autocomplete anything Clink does not.  Clink provides:

* Context sensitive completion;
  * Executables (and aliases).
  * Directory commands.
  * Environment variables
  * Thirdparty tools; Git, Mercurial, SVN, Go, and P4.

If you would prefer it does something different it is also scriptable using Lua.  In any case if you think this is an issue report it to the [Clink developer](https://github.com/mridgers/clink)

Thanks.
