### ISSUE TITLE
Cmder doesn't preserve window position after snapping it, minimizing it, and restoring it

### ISSUE THREAD

**Issue by kodos84** [cmderdev/cmder#1757]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Question
- [ ] Feature request (request for new functionality)

### Description of the issue 
I tried reproducing this issue in ConEmu but I couldn't so it seems like this problem is specific to cmder.

Steps to reproduce:

1. Open a new instance of Cmder (if already open, close it and open again)
2. Open another window (i.e. Windows Explorer)
3. Snap Cmder to the right side
4. Snap the other window to the left side
5. Resize the Cmder window so that it takes up about 75% of the screen (doing this should also automatically resize the window on the left side).
6. Minimize the Cmder window then restore it.

Expected result:
Cmder should return to the size and position it was before it was minimized.

Actual result:
Cmder is moved to extreme right side of the screen with a portion of it off-screen.

**Comment by Stanzilla** [comment]
Can you open the ConEmu settings inside of Cmder and take a screenshot please?

![conemu64_2018-04-29_23-13-41](https://user-images.githubusercontent.com/75278/39411070-0e907ba2-4c03-11e8-9270-95b04bfb5e0c.png)

**Comment by kodos84** [comment]
![conemu-settings](https://user-images.githubusercontent.com/2031121/39420258-8fdcbb20-4c18-11e8-838b-c54875661b0f.png)

**Comment by Stanzilla** [comment]
Okay, so can you try updating ConEmu, go to update, set "preferred release type" to "latest" and then copy the settings I have and see if this fixes anything?

**Comment by kodos84** [comment]
No dice, it's still showing the same behavior after updating to the latest ConEmu.

**Comment by kodos84** [comment]
Any idea about this issue?

I recorded my screen so you can see what I am seeing and doing.

![tes3t4](https://user-images.githubusercontent.com/2031121/40163754-819d6454-596c-11e8-85d9-271ab94b8c49.gif)

Sorry for the large file size. I had to record my whole screen so you can see.

Thanks again.

**Comment by daxgames** [comment]
This is probably not anything cmder related but you might get some traction opening and issue here: 
https://conemu.github.io/

**Comment by v3rticale** [comment]
similar issue, on win 10, after years i tried this, out of the blue, on window size, using percentages instead of pixels, that made it work for me, w 50% h 100% for me, position 0, 0 for me is better, to the right, it's easy for to regulate that position on x axis and i personally keep it fixed
