### ISSUE TITLE
Auto-updating functionality?

### ISSUE THREAD

**Issue by shevegen** [cmderdev/cmder#1759]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [X] Feature request (request for new functionality)
- [ ] Question

### Description

Would it be possible to add an "auto-update" functionality? Ideally in the context menu on the menu bar or something; or in several places. That way users could click on it, and cmder would auto-update itself.

What I mean with "auto-update" is to either install the latest releases, if it is of a HIGHER version than the current one; or, perhaps even better, the latest git-checkout (the same you'd get if you click on the "zip" button).

My aim here with this is to simplify updating to the latest, when we already have installed cmder. I am writing this on a university machine where I have win10, I think. I am mostly using Linux myself, so I am a bit unfamiliar with win-environment and cmder, but I have plenty of shell-code and ruby-code that should work cross-platform. Since I will use this machine for a longer time, and thus also cmder (cmd.exe is too awful for me to use), I'd ideally love to be able to easily auto-update.

Not sure if this functionality is worth to have in cmder, but if you think it is not worth it or too difficult, feel free to close this issue request at any moment in time.

**Comment by Stanzilla** [comment]
no, sorry.
