### ISSUE TITLE
Open folder in Explorer by `ctrl_click` or `click` a folder path in cmder?

### ISSUE THREAD

**Issue by vikyd** [cmderdev/cmder#1762]
### Purpose of the issue
- [√ ] Feature request (request for new functionality)

### Description of the issue 
How can I open folder in Explorer by `ctrl_click` or `click` a folder path in cmder?

**Comment by daxgames** [comment]
@vikyd `cmder /register all` or `cmder /register user` will give you a right click context menu on folder to open `Cmder here`.

If in a folder in Explorer you can type `cmder` in the navigation bar to open cmder in that folder.

Both require the latest release `1.3.6`
