### ISSUE TITLE
Bad owner or permissions on C:\\Users\\USER/.ssh/config

### ISSUE THREAD

**Issue by vdonchev** [cmderdev/cmder#1763]
Since yesterday's windows update (1810), I got this error when trying to connect to any of my servers through ssh:

```
λ ssh myserver
Bad owner or permissions on C:\\Users\\MY_USER/.ssh/config
```
I am using cmder 1.3.4 (i have also tried with 1.3.5).

![problem](https://user-images.githubusercontent.com/12625450/39507170-6b5d4c1e-4de5-11e8-98a1-8a083615a6fe.PNG)

**Comment by vdonchev** [comment]
Ok, here's the solution that worked for me:

Right button on file:
`Properties` -> `Security` -> `Advanced` -> `Disable Inheritance` -> `Remove all inherited permissions from this object`

**Comment by Stanzilla** [comment]
I fail to see how that is Cmder's fault?

**Comment by vdonchev** [comment]
It's working ok with gitbash for example. I have this problem with cmder only.

**Comment by Jiwangreal** [comment]
It does not work.....OMG

**Comment by marsggbo** [comment]
> Ok, here's the solution that worked for me:
> 
> Right click on file:
> `Properties` -> `Security` -> `Advanced` -> `Disable Inheritance` -> `Remove all inherited permissions from this object`

Thanks for your solution. It indeed solved my problem but raise another problem that I can't write `config` file now. How can I solve this problem?

**Comment by qy527145** [comment]
> > Ok, here's the solution that worked for me:
> > Right click on file:
> > `Properties` -> `Security` -> `Advanced` -> `Disable Inheritance` -> `Remove all inherited permissions from this object`
> 
> Thanks for your solution. It indeed solved my problem but raise another problem that I can't write `config` file now. How can I solve this problem?
你可以添加一个用户权限
![Snipaste_2019-11-25_16-18-19](https://user-images.githubusercontent.com/39358262/69523591-3adcff80-0f9f-11ea-9979-dfb5de39fef7.png)
![Snipaste_2019-11-25_16-19-00](https://user-images.githubusercontent.com/39358262/69523625-51835680-0f9f-11ea-9ab1-8a173667ddd9.png)

**Comment by Jiwangreal** [comment]
Thanks, eveyone!I have solved, but setting a content in my vs codes solves the issue !

![image](https://user-images.githubusercontent.com/48763621/69642846-59c1bb80-109d-11ea-897e-124df7895b5e.png)

**Comment by RizhaoCai** [comment]
> Ok, here's the solution that worked for me:
> 
> Right click on file:
> `Properties` -> `Security` -> `Advanced` -> `Disable Inheritance` -> `Remove all inherited permissions from this object`

Thanks. It works for me.

**Comment by djhmateer** [comment]
Remember to leave permissions for yourself (Full control was fine)
![81](https://user-images.githubusercontent.com/111231/75975597-b6204c80-5ed0-11ea-8e07-ad1662a085cf.jpg)

**Comment by beginnerJq** [comment]
> Ok, here's the solution that worked for me:
> 
> Right click on file:
> `Properties` -> `Security` -> `Advanced` -> `Disable Inheritance` -> `Remove all inherited permissions from this object`

this works for me,thanks

**Comment by Guchshenskaya** [comment]
> Thanks, eveyone!I have solved, but setting a content in my vs codes solves the issue !
> 
> ![image](https://user-images.githubusercontent.com/48763621/69642846-59c1bb80-109d-11ea-897e-124df7895b5e.png)

Это помогло!!! Спасибо!!! Прописан путь  C:\\Users\\admin\\ssh\\config как на скрине. И все заработало!

**Comment by mrdcn** [comment]
> Thanks, eveyone!I have solved, but setting a content in my vs codes solves the issue !
> 
> ![image](https://user-images.githubusercontent.com/48763621/69642846-59c1bb80-109d-11ea-897e-124df7895b5e.png)

It helps for me!!!!!!!!!!!!!!!   Thanks

**Comment by prairiewolf-by** [comment]
> 
> 
> Ok, here's the solution that worked for me:
> 
> Right click on file:
> `Properties` -> `Security` -> `Advanced` -> `Disable Inheritance` -> `Remove all inherited permissions from this object`

For me helped ONLY setting permissions Like owner - full control (and disabling permissions inheritance, for sure!!) for two more files - 'config' file itself and both of my PRIVATE and PUBLIC keys. Only after that Remote-SSH plugin started working as it has to.

It seems that such permissions for VS Code are good enough like 0600 for ".ssh" folder in Linux OS'es.

**Comment by jethas-bennettjones** [comment]
You can also fix this from the command line. Here are the commands I used:
`
icacls c:\users\<username>\.ssh\config /inheritance:r
icacls c:\users\<username>\.ssh\config /grant <username>:f

icacls c:\users\<username>\.ssh\id_rsa /inheritance:r
icacls c:\users\<username>\.ssh\id_rsa /grant <username>:f
`

**Comment by isquicha** [comment]
> Thanks, eveyone!I have solved, but setting a content in my vs codes solves the issue !
> 
> ![image](https://user-images.githubusercontent.com/48763621/69642846-59c1bb80-109d-11ea-897e-124df7895b5e.png)

Worked for me, thaks!

**Comment by AllanOricil** [comment]
> Ok, here's the solution that worked for me:
> 
> Right click on file:
> `Properties` -> `Security` -> `Advanced` -> `Disable Inheritance` -> `Remove all inherited permissions from this object`

I had to do this change after I changed the disk where Vagrant is installed.

**Comment by CoolCat64** [comment]
> Ok, here's the solution that worked for me:
> 
> Right click on file: `Properties` -> `Security` -> `Advanced` -> `Disable Inheritance` -> `Remove all inherited permissions from this object`

If you followed this without thinking, like I did, it will solve the problem but leave you with no permissions on the file.
I resolved this by opening a PowerShell with Administrator privileges, and then ran the following command on the file:
`takeown /F C:\Users\<user-name>\.ssh\config`
Where <user-name> is your user name on the system. Then, you can set yourself as the owner and reassign permissions properly through the right-click menu as you normally would.
Hope this helps someone.

**Comment by Cheny5863** [comment]
> Thanks, eveyone!I have solved, but setting a content in my vs codes solves the issue !
> 
> ![image](https://user-images.githubusercontent.com/48763621/69642846-59c1bb80-109d-11ea-897e-124df7895b5e.png)

best answer!!! thank u

**Comment by KaiChen1998** [comment]
> Thanks, eveyone!I have solved, but setting a content in my vs codes solves the issue !
> 
> ![image](https://user-images.githubusercontent.com/48763621/69642846-59c1bb80-109d-11ea-897e-124df7895b5e.png)

Thank you! This works for me.

**Comment by nduka4real** [comment]
This is not an Ubuntu problem and not a Python/.venv problem. Windows OpenSSH is refusing to use your SSH configuration because the file:

C:\Users\NDUKS_TECH\.ssh\config

has an invalid/stale Windows security permission:

UNKNOWN\UNKNOWN
S-1-5-21-...

Let's fix the SSH permissions first. You don't need to change your Ubuntu configuration.

1. Back up your SSH config

Run PowerShell as Administrator and execute:

Copy-Item "$env:USERPROFILE\.ssh\config" "$env:USERPROFILE\.ssh\config.backup" -Force
2. Take ownership of the config file
takeown /F "$env:USERPROFILE\.ssh\config"

You should get a message indicating that ownership was successfully changed.

3. Remove the broken UNKNOWN permission

Run:

icacls "$env:USERPROFILE\.ssh\config" /remove "*S-1-5-21-1258662184-272400643-100602640-1023"

If Windows says the SID wasn't found, that's okay.

4. Reset the config permissions

For your current Windows account:

icacls "$env:USERPROFILE\.ssh\config" /inheritance:r

Then:

icacls "$env:USERPROFILE\.ssh\config" /grant:r "$env:USERNAME:F"

And:

icacls "$env:USERPROFILE\.ssh\config" /grant:r "SYSTEM:F"
5. Check the permissions

Run:

icacls "$env:USERPROFILE\.ssh\config"

You should see permissions for your Windows account and SYSTEM, rather than the stale UNKNOWN\UNKNOWN SID.

6. Test SSH again

Now try:
