### ISSUE TITLE
CMD does not support UNC paths as current directories

### ISSUE THREAD

**Issue by WSQi** [cmderdev/cmder#1764]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)

### Description of the issue 
**Settings** > **Integration** > **ComSpec** > **Support UNC paths in cmd.exe (\\server\share\folder)** was already checked

OS: **Windows 7 SP1 Build 7601**
cmder version: **1.3.5 mini**

```sh
λ cd \\servername\path
'\\servername\path'
CMD does not support UNC paths as current directories.
```
![image](https://user-images.githubusercontent.com/5621964/39566606-bea975aa-4eee-11e8-8528-ef640b41a46f.png)

**Context Menu** > **ConEmu Here** with command "{cmd::Cmder} -cur_console:n", pwd will be in ***path_to_cmder*\config\profile.d**

Maximus5/ConEmu release 180429 **does not** have the issue mentioned.
![image](https://user-images.githubusercontent.com/5621964/39566811-666d9c58-4eef-11e8-8f3f-688126b52d3a.png)

**Comment by daxgames** [comment]
Supporting unc paths and using them as current directories is two different things.  We cannot fix what cmd.exe does not support

**Comment by WSQi** [comment]
This is what the option originally do in ConEmu, and some of the core function does not work after adding a wrapper (cmder), does it not count as a bug or regression?

![image](https://user-images.githubusercontent.com/5621964/39610606-281cb124-4f84-11e8-962c-cc06e596ae0c.png)

![image](https://user-images.githubusercontent.com/5621964/39610618-3bd1bfc0-4f84-11e8-8151-bd6e1d1c8b0d.png)
