### ISSUE TITLE
open multiple tabs in one console window when run the cmder.exe

### ISSUE THREAD

**Issue by yaoyonstudio** [cmderdev/cmder#1765]
I need couple tabs, I need run cmder.exe, and add each tabs manually. can I get multiple tabs in one console window when run the cmder.exe? ?

just one line command, get the result like this.

![tim 20180504090429](https://user-images.githubusercontent.com/13121726/39609304-8b6cc80e-4f7a-11e8-992e-640ec26bea1d.png)

**Comment by oshihirii** [comment]
Cmder > Startup > 'Auto save/restore opened tabs'?

**Comment by yaoyonstudio** [comment]
It worked as what I expected,thanks.
