### ISSUE TITLE
Why do console tabs have different icons?

### ISSUE THREAD

**Issue by oshihirii** [cmderdev/cmder#1766]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Description of the issue 

Hello,

I am very new to using a terminal other than Windows cmd.exe.  

I have set up a Cmder terminal to use multiple tabs (and save them on closing, which is great).  

To create a tab, I do:

    Cmder > New console...

For some reasons, the tabs have different icons, as shown below:

![cmder_tabs](https://user-images.githubusercontent.com/5090307/39739305-91ce8384-52d3-11e8-9913-1af8afbf6bfa.PNG)

Can anyone tell me why this is happening and how to remedy it?  

Thank You.  

Edit:  I just saw this issue seems to mentioned in these issues:

- https://github.com/cmderdev/cmder/issues/1522
- https://github.com/cmderdev/cmder/issues/255

**Comment by daxgames** [comment]
@oshihirii It a feature.  The green tabs are cmder enhanced launched using the `cmder` tasks inside `win+ctrl+t`.

The black tabs are are probably vanilla Windows cmd.exe.  Maybe you have a vanilla Windows Cmd.exe task defined that you are launching?

I am sorry I do not understand `Cmder > New console...`, what does that mean?  Is that a command you are typing?

What does the dialog look like when you hit `ctrl+t`.  Mine looks like:

![image](https://user-images.githubusercontent.com/7318053/40886346-acac873c-66fb-11e8-8494-247af3c8b00b.png)

If I hit start here I always get the green icon tab.

If this is no longer an issue please close.

**Comment by catamphetamine** [comment]
@Stanzilla Hi. Is there a way to disable tab icons? And is there a way to customize the active tab background color (or label color) to be more in contrast with the other tabs (which are not selected)?

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)
