### ISSUE TITLE
Quake Mode + Fullscreen lets Cmder grow bigger than viewport

### ISSUE THREAD

**Issue by dennis-f** [cmderdev/cmder#1768]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 

1. Open in Quakemode via shortcut
2. Fullscreen (`alt + enter`)
3. Hide via shortcut
4. Show via shortcut

The result is a window that is bigger than the screen with parts unreadable. If you keep hiding and showing it grows a little each time.

My config: [conemu.xml](https://gist.github.com/dennis-f/c30d6c0710741ab8e828d25767d8bba7)

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)
