### ISSUE TITLE
Can't start cmder.exe with /c option (tried to set a custom folder for cmder_config)

### ISSUE THREAD

**Issue by psicomante** [cmderdev/cmder#1769]
### Purpose of the issue
- [x] Question

### Version Used
1.3.5 full package

### Description of the issue 
Sorry for posting here, but i followed the guide on readme.md about how to set a custom config folder for cmder with the "/c" command line argument but cmder gives the following error:

Cmder Launcher
Unrecognized parameter
<list of all parameter except /c>

I tried also to read the CmderLauncher.cpp src, the option is there, maybe should i recompile all the source? Or are there any way to set a config folder in other place?

thank you.

**Comment by daxgames** [comment]
`/c` is an unreleased feature.  You would need to use a nightly build.  A 
link to nightly builds is at the bottom of the readme.22nd file.

Dax

**Comment by psicomante** [comment]
Thank you!
