### ISSUE TITLE
Can't Pipe history to grep

### ISSUE THREAD

**Issue by melvyniandrag** [cmderdev/cmder#1770]
history | grep pattern

just dumps the whole history for me. I'm on windows 7 and under "Settings" I see ConEmu161022 [64] which I guess is the version number I'm using. Not sure if this issue is my own or if others have it and if it is even a Cmder issue, might be ConEmu.

**Comment by xmarklar** [comment]
Yep.  Same for me.  Need to fix that.. need my "history | grep blah" functionality...

**Comment by daxgames** [comment]
In `Cmder::Cmder` sessions `history` is a doskey macro.  The output of a macro cannot be passed using the pipe `|` but you could use the command that is the content of the doskey macro as shown below:

```
C:\Users\user\cmder
λ cat %CMDER_ROOT%\config\.history | grep cmder
cd cmder
git clone https://github.com/cmderdev/cmder
git clone https://github.com/cmderdev/cmder cmderdev
cd cmderdev
cmder
cd cmder
git clone https://github.com/cmderdev/cmder
git clone https://github.com/cmderdev/cmder cmderdev
cd cmderdev
cmder
cmderr
cmderr
cd  cmderdev\
cd cmder
cd "..\..\..\Program Files (x86)\cmder_mini\
cmderr
cd ..\cmderdev\
cmder
cmder /h
cmder /task "PowerShell::PowerShell"
cd cmderdev
cmder /task Powershell::Powershell
```

**Comment by daxgames** [comment]
or use `bash::bash` session where history is an actual command and it works as expected.

**Comment by melvyniandrag** [comment]
Thanks for the info Dax. I'm not sure what you mean by bash::bash session?

**Comment by daxgames** [comment]
Cmder supports 3 shells, cmd(default), bash, and PowerShell.  You choose the shell from the menu when you start a session.  Choose bash then choose bash.  It is labled bash::bash in the Tasks dialog.

**Comment by samgermain** [comment]
@daxgames What exactly are you showing? Is there a way to `grep` the results of the history command?

**Comment by daxgames** [comment]
@samgermain `cat %CMDER_ROOT%\config\.history | grep cmder`

**Comment by eriegz** [comment]
@daxgames Thanks for the suggestion of changing Cmder's startup task from `{cmd::Cmder}` to `{bash::bash}` (I think that's what you were suggesting anyways?).

After changing my session to bash, I then re-ran `history | grep -i "something"` and it works like you said it would, only now the program no longer recognizes my `alias grep=grep --color=always $*` alias, which worked fine when I was using `{cmd::Cmder}`.

Are aliases supported in `{bash::bash}`?
