### ISSUE TITLE
More Unix like behavior

### ISSUE THREAD

**Issue by half-potato** [cmderdev/cmder#1771]
Is there a way to easily bind all keyboard shortcuts to be the same as Unix and flip the direction of the slash? If the answer is manually I'm finding a different emulator.

**Comment by daxgames** [comment]
Cmder is a compilation of tools to enhance the users shell environment.  It defaults to using the Window Cmd.exe shell to try and make it more functional and make unix tools and some functionality available but some things cannot be changed like the direction of the '\'.  Use bash in cmder it is even more unix like and uses the forward '/'
