### ISSUE TITLE
ConEmuC: Root process was alive less than 10 sec, ExitCode=0.

### ISSUE THREAD

**Issue by adautoserpa** [cmderdev/cmder#1773]
I was using the cmder with bash and closed with using control + D after about 3 seconds, then the following displayed the following message:

ConEmuC: Root process was alive less than 10 sec, ExitCode = 0.

Would you like to know if this is a bug or just a message ?
Can you corrupt something in the cmder or ConEmu?

Thanks.

**Comment by jschneidereit** [comment]
I get the same error on windows 10 when trying to start any shell to do with powershell (bash works fine for me)

```
ConEmuC: Root process was alive less than 10 sec, ExitCode=0.
```

**Comment by Stanzilla** [comment]
Can you post the content of the task you are running?

**Comment by Stanzilla** [comment]
try PowerShell.exe. Also my default task is `powershell.exe -new_console:d:%USERPROFILE%`

**Comment by Stanzilla** [comment]
well is powershell on your path?

**Comment by jschneidereit** [comment]
from vanilla command prompt:
```
C:\Users\jschneidereit>echo %PATH%
C:\Program Files\Docker\Docker\Resources\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;
```

from bash in cmder:
```
jschneidereit@compy ~
λ which powershell
/c/WINDOWS/System32/WindowsPowerShell/v1.0/powershell
```

**Comment by Stanzilla** [comment]
Really no idea then, can you try a nightly build? https://ci.appveyor.com/project/MartiUK/cmder/build/1.0.667-master/artifacts

**Comment by jschneidereit** [comment]
Nightly does the same thing 😂 at this point I'd point the blame at my laptop - but it's been freshly imaged. 

I'll go back to older builds and try that now 😞

**Comment by adautoserpa** [comment]
I asked in the ConEmu project and they informed me this:

@TeamSpen210
"This is a convenience feature. If you run a process and it quits before 10 seconds are up, ConEmum keeps the tab open until you press a key. That ensures if you run some program that ends quickly, you can still see the messages it produces. You can change this to be always/never/10 seconds only in the settings."


https://github.com/Maximus5/ConEmu/issues/1556#issuecomment-388686378

**Comment by ittayd** [comment]
not sure why you closed this. powershell crashes...

**Comment by daxgames** [comment]
Probably because this is not a cmder issue.

**Comment by adautoserpa** [comment]
According to TeamSpen210 this is a feature of convenience. I tried to reproduce the same error using the powershell and it did not occur.


@ittayd  Can you tell me how to reproduce ?

**Comment by ittayd** [comment]
Well, obviously something in my environment that causes it. But I have no idea how to debug it.

**Comment by ittayd** [comment]
1. yes
2. yes
3. no such file in cmder and I can't share the ps1 file. it starts ssh
agent which seems to cause the crash
4. no

it turns out the culprit is the conemuhk injection. once i disabled this,
everything seems fine.

attached the diag file

**Comment by daxgames** [comment]
@ittayd Glad you found the issue.

If you do not have `%cmder_root%\config\user_profile.ps1` you are running an older version OR Powershell never got far enough in Cmder to actually create one for you.  Now that you say it is working it should exist now.

**Comment by ittayd** [comment]
no, nothing. iirc, i update cmder a month ago.

**Comment by daxgames** [comment]
@ittayd then something is still broken because it should self create.  The diag file did not come through.  I assume you attached it to an email.

**Comment by ittayd** [comment]
[cmder_diag.zip](https://github.com/cmderdev/cmder/files/2674953/cmder_diag.zip)
