### ISSUE TITLE
View is broken on narrow windows.

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [cmderdev/cmder#1774]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 
So, I always keep a window of ping open, but I am only interested in the number of ms that is required, so I run this command:
`ping -t www.bbc.com | awk '{ split($5, a, "="); split(a[2],b,"ms"); print b[1];}' `

Now, that's a window of 2 or 3 digits per line, so trying to keep it as narrow as possible to take the least possible space, but when I do that, the view is broken.

Correct view (wide):
![screenshot_671](https://user-images.githubusercontent.com/19984935/40266326-8aeab91a-5b49-11e8-9d77-1037a76e569b.jpg)

Bad view (narrowed down to the minimum): 
![screenshot_672](https://user-images.githubusercontent.com/19984935/40266347-ec588c18-5b49-11e8-93b8-e9be21bb9633.jpg)

Windows 10 Version 1803 Build 17134.48
Cmder Version 161206 stable
1920x1080 monitor

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)
