### ISSUE TITLE
bash : Not recognized as a command | Root process was alive

### ISSUE THREAD

**Issue by AnmSaiful** [cmderdev/cmder#1776]
### Versions

Cmder: [1.3.5](https://github.com/cmderdev/cmder/releases/download/v1.3.5/cmder.7z) 
Operating System: Windows 10 Pro 1803 (17134.48) x64 - *April 2018 update*

### Problem description

**This is what I see once I start a new bash console**

![cmder_bash_console](https://user-images.githubusercontent.com/204376/40267897-6a70285e-5b86-11e8-8f87-320004d1616f.png)

**This is my ConEmu version**

![conemu_version](https://user-images.githubusercontent.com/204376/40267911-8bd23186-5b86-11e8-8387-c25a65097c1e.png)

**And this is my Windows version**

![windows_version](https://user-images.githubusercontent.com/204376/40267972-4fb720a2-5b87-11e8-872a-82f45ec7e891.png)

**Comment by AnmSaiful** [comment]
Cmder 1.3.4 works fine.

**Comment by Stanzilla** [comment]
refresh your tasks

**Comment by daxgames** [comment]
Try the latest release 1.3.6

**Comment by daxgames** [comment]
Try the latest release 1.3.6

**Comment by AnmSaiful** [comment]
It works! Thank you @daxgames and @Stanzilla for your response.
