### ISSUE TITLE
get-content pipe to docker exec in Cmder

### ISSUE THREAD

**Issue by johnsivertsen** [cmderdev/cmder#1777]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 
Using the following command in PowerShell works:
`get-content <file> | docker exec -i <container name> psql -U username`
Output to console is whatever psql (postgresql command line utility) echoes out to std/errout
Example:
![image](https://user-images.githubusercontent.com/16814294/40270888-e0f67892-5b8c-11e8-8304-5d0ba36d0cd0.png)
Database objects are also created as expected.

Executing the same command in cmder outputs nothing and no database modifications are made.
![image](https://user-images.githubusercontent.com/16814294/40279089-9d99fc60-5c34-11e8-988d-a7b38ddd672b.png)

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)

**Comment by johnsivertsen** [comment]
Found a solution in the issues-forum there. Thanks.
