### ISSUE TITLE
Support Windows 10 Fluent design (Acrylic effect)

### ISSUE THREAD

**Issue by Abbyjeet** [cmderdev/cmder#1778]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 

As the title says...

![image](https://user-images.githubusercontent.com/1262108/40292472-e34e6400-5d0e-11e8-9108-e5057e1b6279.png)

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)

**Comment by DRSDavidSoft** [comment]
@Abbyjeet Please follow this [guide](https://github.com/cmderdev/cmder/wiki/Seamless-FluentTerminal-Integration) for a new way to have Acrylic effect on Cmder.

#### Demo
[![Cmder on FluentTerminal UWP, a transparent terminal for Windows with acryclic effect](https://user-images.githubusercontent.com/4673812/51953290-1385d680-2451-11e9-9b06-46978cf738da.jpg)](https://user-images.githubusercontent.com/4673812/51953308-213b5c00-2451-11e9-9820-30760d786b2f.png)
