### ISSUE TITLE
Child shells yields broken prompt

### ISSUE THREAD

**Issue by NuSkooler** [cmderdev/cmder#178]
I have a Python script that sets a bunch of variables, etc., then in turn executes cmd.exe at the end so that I am dropped into a child or "sub" shell with the prepared environment.

When running this cmder, I'm left with a prompt that looks like this:
```
C:\SomePath {git} 
{lamb}
```
Any idea on how to fix this? If required, I can change the command in the Python script to be more than just "cmd.exe".

**Comment by janschulz** [comment]
See https://github.com/cmderdev/cmder/pull/961
