### ISSUE TITLE
how to set PS1 for bash

### ISSUE THREAD

**Issue by wjx0912** [cmderdev/cmder#1780]
i set bash::bash as the default env,  where is the .bashrc or .bash_profile?

i want set export PS1="\u@\h:\w \$ "
where to add this code?

**Comment by wjx0912** [comment]
modify this file cmder\vendor\git-for-windows\etc\profile, 

please close the issue.

**Comment by daxgames** [comment]
You should not edit that file because it is replaced on updates.

You should instead edit `~/.bashrc` or `~/.bash_profile` if not worked about portability.  If you want it portable then edit `$CMDER_ROOT/config/user-profile.sh`
