### ISSUE TITLE
Create a function

### ISSUE THREAD

**Issue by chabinot** [cmderdev/cmder#1782]
Hi,
I want to know if is it possible to create a function as linux zsh terminal ?
The function in zsh is 
`function createdb {
	DB NAME=$1
	echo "CREATING $DB NAME..."
	mysql -u root --password="" -e "CREATE DATABASE $DB NAME;"
	echo "DATABASE $DB NAME CREATED."
}`
Thanks for your help
Regards

**Comment by Stanzilla** [comment]
Not sure what you are asking but this seems hardly cmder related?

**Comment by daxgames** [comment]
if you are using bash in cmder then yes you can create a function the same way you would in zsh.  this is not a cmder issue so closint .
