### ISSUE TITLE
Charset UTF-8

### ISSUE THREAD

**Issue by chabinot** [cmderdev/cmder#1784]
Hi,
How can i change charset to utf-8
Thanks for your help
Regards

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)

**Comment by yuxing1994** [comment]
settings  ----> environment ---> add  
```
set LANG=zh_CN.UTF-8
chcp 65001
```
ok
