### ISSUE TITLE
bug, move window will cancel search

### ISSUE THREAD

**Issue by Justsoos** [cmderdev/cmder#1787]
ver: ConEmu 180309 [64]
can not to move window to have a look of context when searching key word, or u will lose the search state.
suggest to have a way like vim search, like pushing "n" & "N" to move the windows to focus the key word and certainly could move the window to see context first.

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)
