### ISSUE TITLE
CMDER fails to load git aliases defined in .gitconfig in %userprofile% home directory

### ISSUE THREAD

**Issue by kunalegendo** [cmderdev/cmder#1788]
### Purpose of the issue
- [ ] Question

### Description of the issue 
I have played around CMDER and tried to set the default starting directory for my newly opened tabs and in the process somehow misconfigured CMDER and now cannot load my custom git aliases defined in the 

> .gitconfig 

in my windows10 home directory.

I have deinstalled and reinstalled my CMDER console to the latest version.

But still CMDER doesn't load them.

What should I do, to make CMDER read my defined git aliases again.

Working without them really slows down my workflow.

Ivan

**Comment by Stanzilla** [comment]
type `which git` to see which version of Git cmder is using and check if the config file is in the correct place for it.

**Comment by kunalegendo** [comment]
thank you, it works now.
Albeit all commands run extremly slow. i.e. git status, git branch etc.
