### ISSUE TITLE
The position of mouse cursor offseted.

### ISSUE THREAD

**Issue by seanmars** [cmderdev/cmder#1789]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 
When using MSYS2 + fish the position of mouse cursor is not correct.
![mouse cursor](https://i.imgur.com/M9TMe6O.png)

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)
