### ISSUE TITLE
\cmder_mini\vendor\lib\lib_base"" was unexpected at this time.

### ISSUE THREAD

**Issue by Qrzysio** [cmderdev/cmder#1791]
I have updated today ConEmu and Cmder.
When I launch Cmder I get this error:
`\cmder_mini\vendor\lib\lib_base"" was unexpected at this time.`

I have just overwritten all the files in the `c:\Program Files (x86)\cmder_mini\`.
I've tried to copy files from both versions of Cmder: mini and full, but still getting the same issue.
What might went wrong?

**Comment by daxgames** [comment]
Move the folder to a path with no `()`

**Comment by Qrzysio** [comment]
Moving to `C:\Program files\` solved the problem. Thank you.

**Comment by daxgames** [comment]
The newest builds also fixes the issue

**Comment by Bakaji** [comment]
thnx my freiind

**Comment by cristoferfb** [comment]
I Still having the error in v180528, solved moving to Program files folder

**Comment by CharlesStover** [comment]
Nightly build does not fix this, but confirming that moving it from `Program Files (x86)` to `Program Files` did fix it.

**Comment by wreeecks** [comment]
I've fixed this issue by moving the `\cmder_mini` dir to `c:\cmder_mini`. Hope this helps someone. 

`\cmdr` - is an absolute path. Cmdr assumes that its dir is located at the root level. In windows case,  `\` is equivalent to `c:\`

**Comment by Iriyos** [comment]
I think that if any of __*`(`*__ and __*`)`*__ characters appears in the path name, it is happening. No matter the depth of the __`cmder`__ path or what characters are used in the path name except the two.

**Comment by daxgames** [comment]
See https://github.com/cmderdev/cmder/issues/1791#issuecomment-395911443

**Comment by SilentGene** [comment]
> Nightly build does not fix this, but confirming that moving it from `Program Files (x86)` to `Program Files` did fix it.

Yes, this problem is still there in the latest version (v1.3.14), and I fixed it by moving it from `Program Files (x86)` to `Program Files`.

**Comment by everaldoferreira** [comment]
Em 28/05/2020, **Version: v1.3.14** o problema persiste apenas em `Program Files (x86)`

Solução:

- mover os arquivos do `Program Files (x86)` para `Program Files`.
