### ISSUE TITLE
How to hide size and buffer notification

### ISSUE THREAD

**Issue by ibnuh** [cmderdev/cmder#1792]
I'd like to remove/hide this size & buffer info. I already search on the settings but can't find one.

![screenshot_1](https://user-images.githubusercontent.com/18393879/40726113-3e3a4018-644f-11e8-84e3-dbb1ebb1bd24.png)

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)
