### ISSUE TITLE
user-profile.ps1 is read twice

### ISSUE THREAD

**Issue by ooxif** [cmderdev/cmder#1795]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 

`vendor/profile.ps1` reads `config/user-profile.ps1` twice.

1. https://github.com/cmderdev/cmder/blob/v1.3.6/vendor/profile.ps1#L157
2. https://github.com/cmderdev/cmder/blob/v1.3.6/vendor/profile.ps1#L166

Is this intentional?

**Comment by daxgames** [comment]
Fixed in #1796
