### ISSUE TITLE
ssh glitch when installing program

### ISSUE THREAD

**Issue by luukonetap** [cmderdev/cmder#1797]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 
When installing programs on Ubuntu Server (for example MySQL server or PHPMyAdmin) you will get prompted with a full screen window to enter a root password. First time that shows up fine, but with the confirmation window it gets all glitchy.
The BufferHeight mode goes on and off really fast and the screen glitches.

I'm using the newest version available at the time of writing, v1.3.6 (clean files downloaded from the website)

https://gyazo.com/6d289bee03aa616cf2000cec27897281

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)
