### ISSUE TITLE
TASK switch not recognized

### ISSUE THREAD

**Issue by DamnedScholar** [cmderdev/cmder#1799]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 
I'm trying to execute Cmder with a starting task as described in [the documentation](https://github.com/cmderdev/cmder/blob/master/README.md#cmderexe-command-line-arguments), but it throws an error message.

#### Steps to reproduce:
```
> "C:/cmder_mini/Cmder.exe" /TASK ls
```

#### Output:
![image](https://user-images.githubusercontent.com/4084322/40995003-79d9283c-68c3-11e8-8f59-e3c7d4b97054.png)

**Comment by daxgames** [comment]
Try the 1.3.6 release
