### ISSUE TITLE
I let the antivirus deleted that init.bat file. Now It's already deleted how can I get it back?

### ISSUE THREAD

**Issue by abrhambas01** [cmderdev/cmder#1800]
The antivirus removed the file. that i didn't know is important

 now I get this error : 
> C:\users\Computer\Desktop\cmder\vendor\conemu-maximus5\..\init.bat' is not recognized as an internal or external command,
> operable program or batch file.

how can i fix this?

**Comment by ghid** [comment]
@abrhambas01 I think, you can take it from here:
[https://github.com/cmderdev/cmder/blob/master/vendor/init.bat](https://github.com/cmderdev/cmder/blob/master/vendor/init.bat)

**Comment by abrhambas01** [comment]
@ghid, that file didn't work things out. I just deleted the old cmder and downloaded the cmder file
