### ISSUE TITLE
Unable to open directory on another disk

### ISSUE THREAD

**Issue by drop-db** [cmderdev/cmder#1801]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 

I've integrated Cmder with the Windows context menu as you can see [here](https://github.com/drop-db/CmderHere). But when trying to invoke the Cmder on a disk other than the main (C:\\) it closes without reporting error.

**Comment by mzhboy** [comment]
In fact, it can't open any root directory (c:/d:/e:...etc) by context menu (1.3.2 does).

**Comment by daxgames** [comment]
I went back and looked at the code for 1.3.2 and it is identical to the code in 1.3.6 for setting up the context menu.  Something has changed in windows top break it.
