### ISSUE TITLE
global keyboard shortcut to activate cmder started working differently

### ISSUE THREAD

**Issue by philiparvidsson** [cmderdev/cmder#1802]
## steps to reproduce
1. start cmder
2. switch to another window (do not minimize cmder, just leave it and switch focus)
3. press global keyboard shortcut to activate cmder

## expected result:
cmder window is activated

## actual result:
cmder window is minimized

## workaround:
press global keyboard shortcut again and cmder will restore it self and become focused

## found in version:
1.3.6 (was not present in 1.3.5)

**Comment by philiparvidsson** [comment]
@Stanzilla

**Comment by daxgames** [comment]
1.3.6 is very old, please update.

This is a configurable setting in ConEmu. There are multiple choices:

1. Minimize/Restore (Quake-style hotkey also) - The behavior you describe that you don't want.
2. Restore (bring to front) - The behavior you describe that you most likely want.
