### ISSUE TITLE
Without %CMDER_START%, I have to find another way to make "Cmder Here" apply for msys2's bash

### ISSUE THREAD

**Issue by zyzyz** [cmderdev/cmder#1803]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Description of the issue 

Hello. 
As far as I have investigated, since 1.3.5 Cmder removes %CMDER_START% environment variable and use /dir to switch the startup directory when using context menu, previously I relied on %CMDER_START% to do the `cd` when MSYS2 sourcing my customized profile, but now it's gone! 

I studied MSYS2_shell.cmd and found there's a %CHERE_INVOKING% variable, according to this [link](https://conemu.github.io/en/CygwinStartDir.html) if %CHERE_INVOKING% is set to 1 the shell will be started in proper working directory and I tested the directory does change, I don't know why it also works on MSYS2 (originally it's a **workaround** for Cygwin) but I just want to get confirmed is it the correct way to validate "Cmder Here" for external stuffs after version 1.3.5? Or should I use %ConEmuWorkDir% to do the `cd`? (Maybe %CMDER_START% is redundant with %ConEmuWorkDir% so it is deleted?)

Also hope this issue may help other guys.

**Comment by daxgames** [comment]
Yes use could use `conemuworkdir`.  I guess there would be no harm in adding back CMDER_START OR CMDER_WORKDIR as an env var that could be used by user init scripts.  @cmderdev/trusted-contributors?

**Comment by daxgames** [comment]
@zyzyz Also this works just fine for me:

cmder_here_bash.reg

```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\Directory\shell\Cmder - Bash]
@="Cmder Here - Bash"
"NoWorkingDirectory"=""
"Icon"="C:\\Users\\user\\cmder dev\\icons\\cmder.ico"

[HKEY_CLASSES_ROOT\Directory\shell\Cmder - Bash\command]
@="\"C:\\Users\\user\\cmder dev\\Cmder.exe\" /single /task bash::bash \"%V\""

```
