### ISSUE TITLE
Enable SSO for SSH sessions using Cmder

### ISSUE THREAD

**Issue by sayantandas** [cmderdev/cmder#1808]
### Purpose of the issue

- [* ] Question

### Description of the issue 

In most large organisations, laptops/desktops for all users are connected via Active Directory. It binds all systems to a single domain. And so are the Linux machines. 
While connecting to the Linux boxes from Windows laptop using Putty, we can login to these Linux machines via SSO, using a single user ID without having to enter our password over and over again. 
Is there something similar available in Cmder?

**Comment by daxgames** [comment]
SSO for linux machines using AD is configured on the Linux machine and Cmder would use it.  This is beyond the scope of Cmder.
