### ISSUE TITLE
some directives don`t support window10x32

### ISSUE THREAD

**Issue by steavengong** [cmderdev/cmder#1809]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ x ] Question

### Description of the issue 

I use Cmder in windows 10 x32 ,but more not support like ls.exe、bash.exe...
In windows 10 x64 ,there are no problem
is this not support x32 system?

**Comment by Stanzilla** [comment]
Nope, 64bit Git only. You can replace the git-for-windows folder with a portable 32bit version if you want.
