### ISSUE TITLE
The command 'screen'  fatal error

### ISSUE THREAD

**Issue by shvets-alex** [cmderdev/cmder#1810]
Hello,

Every time when I try to run command 'screen' I get fatal error:
# screen -rd
    256 [main] ssh 8976 C:\tools\cmder\vendor\git-for-windows\usr\bin\ssh.exe: *** fatal error - cmalloc would have returned NULL

and bash terminal was closed.

I run the cmder on Windows 10 (1803) x64

**Comment by Stanzilla** [comment]
https://github.com/cmderdev/cmder/issues/1781
