### ISSUE TITLE
Output problem (Ping)

### ISSUE THREAD

**Issue by ozgurbuz7** [cmderdev/cmder#1811]
Hello,

When i was run ping command, few minutes later output turns to this. I usually use cmder's "Split Screen" feature. I think problem is related with this feature but i come across this problem on normal window (Less than Split Screen).

![image](https://user-images.githubusercontent.com/7359577/41333552-e2856c42-6eea-11e8-883f-2bcd77c43ee4.png)

I run the cmder on Windows 10 Pro (1803) x64

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)
