### ISSUE TITLE
Cmder in hyper theme issues

### ISSUE THREAD

**Issue by jghielmi** [cmderdev/cmder#1812]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Description of the issue 

This is using hyper with cmder and I have small issues : 
In the tab on top it puts the path from the shell args, how could I replace that by a simple name plus icon ?
Secondly no matter what theme I put on hyper the colors on my cmder don't change (see the green on the screenshot), background changes but what is cmder doesn't change, how can I apply a theme to that ?
![image](https://user-images.githubusercontent.com/14925932/41345356-a9366540-6f03-11e8-9f8a-6970c4c495bb.png)

**Comment by DRSDavidSoft** [comment]
@jghielmi Hi, sorry for late response

I updated the wiki to address your issue.

1. **Display icon + name:**
   1. For icon, use this plugin: ([wiki](https://github.com/cmderdev/cmder/wiki/Seamless-Hyper-integration#recommended-optional-steps))
      ```
      'hyper-tab-icons'
      ```
   2. For title, insert this command: ([wiki](https://github.com/cmderdev/cmder/wiki/Seamless-Hyper-integration#additional-configuration))
      ```
      shellArgs: ['/k', 'title Cmder & %CMDER_ROOT%\\vendor\\init.bat'],
      ```

2. **Change shell color:**
   Open this file: ([wiki](https://github.com/cmderdev/cmder/wiki/Customization#prompt))
   ```shell
   \cmder\vendor\clink.lua
   ```

   Find these lines:
   ```lua
       local cmder_prompt = "\x1b[1;32;40m{cwd} {git}{hg}{svn} \n\x1b[2;37;40m{lamb} \x1b[0m"
       local lambda = "λ"
   ```

   Read [this](https://github.com/cmderdev/cmder/wiki/Customization#prompt-color) to change the color.

   Here are some examples:

   If you change **`32`** to **`36`**, you'll get cyan path:  
   <img width="130" alt="cmder-cyan" src="https://user-images.githubusercontent.com/4673812/54070755-5cfbe980-4279-11e9-865d-cd5d2e41bfc1.png">

   If you change **`32`** to **`33`**, you'll get yellow path:  
   <img width="130" alt="cmder-yellow" src="https://user-images.githubusercontent.com/4673812/54070752-579e9f00-4279-11e9-920e-45d96ab1993b.png">

I hope this helps.
