### ISSUE TITLE
We need a Chinese mirror download address

### ISSUE THREAD

**Issue by muyu66** [cmderdev/cmder#1815]
amazon s3 download speeds in China unbearable. I generally use the download service in the cloud download abroad, and then return to China. I think such excellent software should be more widely disseminated in China. So I suggest to provide China download address, if not convenient, I at an appropriate time to provide a download mirror to help you

**Comment by DRSDavidSoft** [comment]
Hi @muyu66, thanks for your suggestion, but I don't think it'll be easy for the website to provide per-location mirrors.

Where do you propose the chinese mirror to be located? Are you able to set-up a mechanism to automatically fetch the latest releases from GitHub and provide checksum-perfect binaries?

Maybe the links to per-country mirrors can be added to the Wiki, if the Cmder team agree.
