### ISSUE TITLE
How to hide some particular files when I use ls command?

### ISSUE THREAD

**Issue by loliMay** [cmderdev/cmder#1816]
![1](https://user-images.githubusercontent.com/32427260/41472243-6cd1d800-70e8-11e8-9e40-f90d0138a00d.png)
When I use `ls` command to list files and folders under current path, I find **cmder** show some protected operating system files and folders that I don't want to see. Can I hide them through some configrations?

**Comment by Stanzilla** [comment]
Not a cmder issue.
