### ISSUE TITLE
cmder installer/updater? we have a solution!

### ISSUE THREAD

**Issue by mouuff** [cmderdev/cmder#1818]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [x] Question

### Description of the issue 
Hello, we are a team of students (3rd year in master computer engineering school in France)
We are currently working on a easy to setup installer/updater, which could be used for cmder.
The project is named Quail, it is hosted here: https://github.com/QuailTeam/Quail
Currently the project is in development stage, and we are looking for projects like yours, to use our solution, and get feedbacks from your community and your team.
We are going to work on that project for at least the next 2 years. (part time)
We started this project months ago. Today we believe we have came to a point where it could be released in alpha version.
The configuration required to build an installer is that easy:

```
import quail

quail.run(
    solution=quail.SolutionGitHub("cmder_mini.zip", "https://github.com/cmderdev/cmder"),
    installer=quail.Installer(
        name='Cmder',
        icon='Cmder.exe',
        binary='Cmder.exe',
        console=False
    ),
    builder=quail.builder.Builder(
        quail.builder.CmdIcon('icon.ico'),
        quail.builder.CmdNoconsole()
    ),
    controller=quail.ControllerTkinter()
)
```
This is already working with cmdr, just click on the generated binary and cmder will be installed, registered on windows control panel, and with a desktop icon.
You can test it here:
https://drive.google.com/open?id=1h2NlKftvb5apdDcLmqt_ywQxmDDD_EPU

This is much easier than asking users to download a zip, unzip to a folder, create shortcut themselves, and do the process over and over again each update.
And on your side the setup is quite easy, and we have a one-liner to generate the installer binary.

Today it quail can already retrieve solutions on github, but not update yet, (update system should come in the next 3 months, probably less)
Also we are currently working a Ui (which should also come in the next months), but we believe cmder users wont be scared to see a terminal for the installation process.

Understand that we are not asking you to use quail tomorrow.
We have opened this issue to talk with you and see if you are open to such projects.
And if you are ready to use quail, we will always be ready to help you with it as fast as possible, even implement new features.

**Comment by mouuff** [comment]
I have updated the demo binary with our current user interface. (WIP)
The auto-update system already works but as it slows down the launch time by 3 seconds we have disabled it for this demo.
(We will probably check for updates in background in the future)

**Comment by xaoseric** [comment]
@mouuff I have an nsis solution that downloads the latest release from github, you build it using the build.js file if you want to take a look at that. Perhaps using the nsis installer might work better?

https://github.com/XAOS-Interactive/cmder_inst

**Comment by mouuff** [comment]
The project is now in beta, you can get the release on PIP and I have made a iquail config for cmder:
```
#!/usr/bin/python3

import iquail

if not iquail.helper.OS_WINDOWS:
    raise AssertionError("This test solution is windows only")


class FrameSelectMiniOrFull(iquail.controller_tkinter.FrameBaseConfigure):
    def __init__(self, parent, controller):
        super().__init__(parent, controller)
        self.version_selected = self.add_combobox("Which version would you like to install?",
                                                  ('Full', 'Mini'))

    def next_pressed(self):
        print(self.version_selected.get())
        version = self.version_selected.get().lower()
        zip = "cmder_mini.zip" if version == "mini" else "cmder.zip"
        self.manager.config.set("zip_url", zip)
        self.controller.switch_to_install_frame()


iquail.run(
    solution=iquail.SolutionGitHub(iquail.ConfVar("zip_url"), "https://github.com/cmderdev/cmder"),
    installer=iquail.Installer(
        publisher='cmderdev',
        name='Cmder',
        icon='Cmder.exe',
        binary='Cmder.exe',
        console=False,
        launch_with_quail=True
    ),
    builder=iquail.builder.Builder(
        iquail.builder.CmdIcon('icon.ico'),
        iquail.builder.CmdNoconsole()
    ),
    controller=iquail.ControllerTkinter(install_custom_frame=FrameSelectMiniOrFull)
)
```

**Comment by DRSDavidSoft** [comment]
For future visitors: installer/updater work is related to package-manager distribution, but it is no longer the only path for WinGet.

WinGet can use ZIP archive manifests with portable nested installers, so Cmder can attempt an initial WinGet package using official release archives while installer/MSI work continues separately if the core team wants it.

Master package-manager tracker: https://github.com/cmderdev/cmder/issues/3094
Wiki status page: https://github.com/cmderdev/cmder/wiki/Package-Manager-Status
