### ISSUE TITLE
Windows 8.1 High-DPI Scaling

### ISSUE THREAD

**Issue by cgarst** [cmderdev/cmder#182]
Cmder is pretty awesome on a 10" Win 8.1 1080p tablet (150% dpi) after enlarging the text, but the UI buttons at the bottom of the window do not scale. It would be great if they did.

**Comment by CumpsD** [comment]
I can confirm replacing the conemu which comes with cmder by ConEmu 141221 fixes this issue.

**Comment by PWKad** [comment]
The link is dead to what's new - @CumpsD any insight in to how you upgraded to newer conemu?

**Comment by Stanzilla** [comment]
@PWKad there you go https://conemu.github.io/

**Comment by PWKad** [comment]
I guess I meant how to upgrade cmder to use new conemu since the docs don't mention dpi and I am too dumb to find the upgrade path

**Comment by CumpsD** [comment]
Download conemu and overwrite the one you have in the subfolder right now. Nothing special for upgrade path besides that

**Comment by Stanzilla** [comment]
Yup, what he said. Should work!

**Comment by PWKad** [comment]
Cool I'll try that out the `conemu` in the subdir looked to be a fork or something `conemu-maximus` but I'll review again and see if I can get it thanks again.

**Comment by Stanzilla** [comment]
nah, conemu-maximus is the correct name
