### ISSUE TITLE
Cmder + Tablets w/ On-Screen Keyboard

### ISSUE THREAD

**Issue by hayesjo33** [cmderdev/cmder#1822]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 

When using Cmder on a SP3 running Windows 10, I have a few issues. They may be Con-Emu issues but I don't really know, feel free to close this if they are not Cmder's issues.

First, touching the screen does not bring up the on-screen keyboard like it would touching any other text field.

Secondly, if I bring up the on-screen keyboard using the icon in the task bar, the arrow keys do not work to cycle through command history or move the cursor left and right through a command I've already typed.

My current workaround is to carry a pocket sized bluetooth keyboard but it would be nice if the OSK just worked.

**Comment by daxgames** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem or a question, please open an issue over at https://github.com/Maximus5/ConEmu

Thank you! :-)
