### ISSUE TITLE
how to uninstall anything of the cmder 

### ISSUE THREAD

**Issue by s1204** [cmderdev/cmder#1824]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 

system: windows10 1803 17134.81
version:v1.3.6
ssh to my vps......
arrow key 【← hide and → display】
i del the folder of cmder,find "cmder" from regedit ,and del it,and download again,the problem still exists
in virtualbox, the same version;vps;windows , It operate normally
so that, i want to uninstall all the cmder
maybe it's the wrong way to del it
help me,thanks

![cmder](https://user-images.githubusercontent.com/19360425/41762557-bda5a096-762d-11e8-8fdf-ce8d1a6085a4.gif)

**Comment by daxgames** [comment]
I dont understand the issue.  Deleting the folder should be sufficient assuming you did not run 'cmder /register'
