### ISSUE TITLE
Language settings save failed

### ISSUE THREAD

**Issue by LuckyRabbitFeet** [cmderdev/cmder#1825]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 
system: windows10 1803 17134.112

version:v1.3.6 

In the settings, the language is switched to Chinese, the settings are saved and the cmder is closed, and after the restart, the cmder is restored to English.

After checking, the Language in the `.\vendor\conemu-maximus5\ConEmu.xml` file was not rewritten.

Is there a problem with my operation or is it a bug?

help me,thanks .

**Comment by scalpelx** [comment]
I also encountered the same problem.
