### ISSUE TITLE
Cmder Window stuck on invisible Screen

### ISSUE THREAD

**Issue by pluess** [cmderdev/cmder#1828]
### Purpose of the issue
- [x ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 
I'm working with two different screen setups:
1. Two screens in the office, laptop built in screen swichted off.
2. Only the built in laptop screen.

When I close the Cmder Mainwindow on the second screen and later on start Cmder again while working with the laptop screen only, the Cmder Windows isn't visisble.
Usually this can be resolved by activating the application via the task bar and hiting Windows+Cursor right until the window appears on the screen. But for Cmder this doesnt work. 
I didn't find a way to get the Cmder window back in this situation.

**Comment by daxgames** [comment]
Hey there,

To clarify, there is no such thing as a 'Cmder Mainwindow'.  Cmder uses ConEmu as terminal emulator and any window is ConEmu.  If you are experiencing a problem or a question, please open an issue over at https://github.com/Maximus5/ConEmu

Thank you! :-)
