### ISSUE TITLE
New Task: Anaconda prompt

### ISSUE THREAD

**Issue by gabriellima** [cmderdev/cmder#1829]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [X] Question

### Description of the issue 

How may I add another `.bat` script to execute after cmder `init.bat` during task initialization?

Specifically for Anaconda python, their script add an environment name next to the prompt. 

If, after cmder initialize, I just execute their script, I end up with this (which is correct):

![image](https://user-images.githubusercontent.com/487779/42104683-ec44d748-7ba3-11e8-9af2-462bb207c78f.png)

At ConEmu, I can create a task to acomplish this using the following command:

`cmd.exe /k "%ConEmuBaseDir%\CmdInit.cmd" %localappdata%\Continuum\anaconda3\Scripts\activate.bat`

Where the first part, I just copied/paste from default {shell::cmd} task.

However, trying to reproduce this with cmder, I ended up with this command task, which DOESN'T work as expected:

`cmd /k ""%ConEmuDir%\..\init.bat" " %localappdata%\Continuum\anaconda3\Scripts\activate.bat`

I tried many variations, excluding some quotes ("), adding more, but none of those worked as expected.

As I explained, if I just open a cmder default task {cmd::Cmder} and then execute the `activate.bat` Anaconda's script, the prompt work as expected. 

Comparing both initialization scripts, I think the part that is not contained in `cmder` version is this one:

```
rem Support additional batch execution as `{cmd} "path\to\batch.cmd" <arguments>`
rem Due to parsing rules of cmd.exe last argument must NOT ends with "
if "%~1" == "" goto clean
rem We can't call here %* unfortunately
call %1 %2 %3 %4 %5 %6 %7 %8 %9
```

But I tried adding it to cmder `init.bat` without success. 

Thank you for all work, and nice project.

**Comment by gabriellima** [comment]
I could make it work by addint a `&` after initial parameter of the Task (i.e., making script execute after cmder prompt is opened)

`cmd /k  ""%ConEmuDir%\..\init.bat"" & %localappdata%\Continuum\anaconda3\Scripts\activate.bat C:\Users\bg7g\AppData\Local\Continuum\anaconda3`

**Comment by daxgames** [comment]
If that works I' close the issue if I were you.

**Comment by arisliang** [comment]
What worked for me is additionally adding:
`& %userprofile%\anaconda3\Scripts\activate.bat %userprofile%\anaconda3`

**Comment by nmaynes** [comment]
In case you are like me and use miniconda, this will look a little different. The structure of the setup task is the following:
`cmd /k "%ConEmuBaseDir%\CmdInit.cmd" " & "{path\to\miniconda}\Scripts\activate.bat" "path\to\miniconda\}"`

Just make sure to replace the {path\to} blocks with your own path. This will vary depending on where miniconda is on your system. I believe the default behavior is to place it in: C:\Users\%user_profile%\AppData\Local\Continuum\miniconda3\Scripts
