### ISSUE TITLE
how to config installed msysgit 

### ISSUE THREAD

**Issue by Awezome** [cmderdev/cmder#183]
hello , i installed your cmder, it is very awesome. i know you have included the msysgit into cmder.zip , but i have installed another msysgit , is there any way to using my msysgit with the cmder-mini version ? thank you .

**Comment by justsayno** [comment]
How does this work now that msygit has been superceeded by Git for windows? I've tried doing this:

```
@set git_install_root=C:\Program Files\Git
```

But looking at the file structure in there compared to mysygit its quite different... If I do the above then I loose my bash comands.. like `ls rm` etc
