### ISSUE TITLE
Flickering screen while installing postfix

### ISSUE THREAD

**Issue by cedrictailly** [cmderdev/cmder#1831]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 

I have problem installing Postfix on a new Linux server through SSH, there drawing problems at the configuration form wich switch repeatedly with the black screen, nothing can be done and I have to restart session.

To reproduce you have to start a new install of Postfix, so to clean up :

`apt purge postfix`

...and to install :

`apt install postfix`

...and you might encounter the problem.

Thanks in advance for your support.

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)
