### ISSUE TITLE
how to split the screen with two tabs

### ISSUE THREAD

**Issue by demetrioin** [cmderdev/cmder#1833]
It is in fact a question instead of an issue. I just downlowaded cmder and I already like it. But I didn't some resource I was looking for: how to split one screen in two tabs in the same moment so I can see both in exact same moment?

### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [x] Question

**Comment by lucasrabiec** [comment]
@demetrioin See this link: [https://conemu.github.io/en/SplitScreen.html](https://conemu.github.io/en/SplitScreen.html)
Cmder uses conemu. So you can look at conemu's documentation if you want to do some with conemu's features
I hope it will help.

**Comment by demetrioin** [comment]
thanks. I didn't note there is an option to split when opening a new screen [+].
