### ISSUE TITLE
is it possible to pin/fix several paths, one for each tab amongst multiple tabs?

### ISSUE THREAD

**Issue by demetrioin** [cmderdev/cmder#1835]
I am using 4 different paths (eg. c:/mypath1, c:/mypath2, c:/mypath3 and c:/mypath4). Is it possible to fix them so when I reopen cmder it will automatically reopen with 4 tabs, each one in one of these 4 paths?

### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

**Comment by daxgames** [comment]
Yes, There are two ways.
1. Set Conemu to `Auto Save/Open Tabs` on the `Startup` page in the settings dialog.
 
2. Create a new task with the below contents and set it as the `Specified Named Task` on the `Startup` page:

```
cmd.exe /k ""%ConEmuDir%\..\init.bat" " -new_console:d:C:\Users\user\dir1

cmd.exe /k ""%ConEmuDir%\..\init.bat" " -new_console:d:C:\Users\user\dir2

cmd.exe /k ""%ConEmuDir%\..\init.bat" " -new_console:d:C:\Users\user\dir3

cmd.exe /k ""%ConEmuDir%\..\init.bat" " -new_console:d:C:\Users\user\dir4
```
