### ISSUE TITLE
trailing backslash in start path causes an error on windows

### ISSUE THREAD

**Issue by themike10452** [cmderdev/cmder#1836]
The following commands work:
`cmder /start "c:\\"`
`cmder /start "c:"`

The following command doesn't work:
`cmder /start "c:\"`

It seems the last '\\' is processed as an escape character instead of a regular character in the path.

I discovered the issue when adding cmder to visual studio 2017: `cmder /start "%folder%"`
Visual Studio adds a trailing backslash to the path, so cmder does not launch, it says folder not found.

![image](https://user-images.githubusercontent.com/7006763/42453769-6e7b4842-8396-11e8-85a0-92dd795aeb88.png)

**Comment by daxgames** [comment]
fixed #1871
