### ISSUE TITLE
Setting alias with parenthesis char ")" returns "was unexpected at this time"

### ISSUE THREAD

**Issue by natenho** [cmderdev/cmder#1837]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 

The command `alias npp=C:\Program Files (x86)\Notepad++\notepad++.exe $*` doesn't work, apparently because of the parenthesis ")" inside the path.

### With ")":

![image](https://user-images.githubusercontent.com/4236481/42668934-8a84017e-8629-11e8-9872-376ab708d1f2.png)

### Without ")"

![image](https://user-images.githubusercontent.com/4236481/42669028-ecf673b4-8629-11e8-82f0-59ee3006b053.png)

Is there any other way to set an alias with cmder?

**Comment by ghid** [comment]
Hi @natenho. Please try `alias npp="C:\Program Files ^(x86^)\Notepad++\notepad++.exe $*"`

**Comment by natenho** [comment]
Thanks, it worked. An alternataive way to achieve that is to set the alias through Settings -> Startup -> Environment. There you don't need to escape with ^.

It is good to mention that to get it fully working I had to enable legacy console as described in #1257
