### ISSUE TITLE
CMDER doesn't forward piped stdin to docker

### ISSUE THREAD

**Issue by moerwald** [cmderdev/cmder#1838]
I'm using the docker image located under https://hub.docker.com/r/think/plantuml/. The docu says that input shall be piped to the container like: 

`cat test.uml | docker run --rm -i think/plantuml > test.svg`

I run above command in cmder (PowerShell) nothing happens. If I run the same command in a standard Windows PowerShell terminal everything is fine.

Is there a workaround/fix to use stdin piping via CMDER?

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)
