### ISSUE TITLE
What is the best way to start Cmder on Windows 10 startup?

### ISSUE THREAD

**Issue by natenho** [cmderdev/cmder#1839]
### Purpose of the issue
- [X] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [X] Question

### Description of the issue 

Where should I correctly define Cmder to open at windows 10 startup (after logon)?

Here is what happens when I create a shortcut to Cmder under C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp

At windows startup, Cmder opens like this:
![image](https://user-images.githubusercontent.com/4236481/42735073-aa731f68-8824-11e8-9ce2-e2f8f8a4c201.png)

It seems like an intermitent bug, at most times the styled command line simply does not appear at startup. It just pops the Clink header message and the prompt doesn't come with that lambda icon.

Then closing and starting again:
![image](https://user-images.githubusercontent.com/4236481/42735079-c9565256-8824-11e8-898c-d7c93aa6e9bc.png)

Thanks

**Comment by daxgames** [comment]
@natenho Do you also have clink installed globally?

**Comment by natenho** [comment]
Hello @daxgames, what exactly do you mean with "globally"? Actually, I'm using the portable version (not installed)

**Comment by daxgames** [comment]
Clink is also a part of cmder.  I am wondering if you have clink auto starting if it might be interfering with cmder.

**Comment by daxgames** [comment]
Creating a shortcut where you are works for me.

**Comment by daxgames** [comment]
@natenho Creating a shortcut where you are works for me.
