### ISSUE TITLE
I cannot alias when I'm using cmder

### ISSUE THREAD

**Issue by abrhambas01** [cmderdev/cmder#1840]
### Purpose of the issue
- [ x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 

I am using laragon specifically version : 

![image](https://user-images.githubusercontent.com/12043306/42984190-eb7bcd32-8c1d-11e8-9eb7-da322a84475d.png)
But I cannot alias the command art as an alias , I tried using
``` alias art=php artisan $*  => ```

**Comment by ghid** [comment]
Hello @abrhambas01 , please try to add your alias in ConEmu-Settings (can normaly be activated with Win+Alt+p) under `Startup > Environment`.

**Comment by daxgames** [comment]
@abrhambas01 What is the error or failure you are seeing?  Setting an alias differs depending on the shell you are in.

**Comment by daxgames** [comment]
closing due to lack of response.
