### ISSUE TITLE
No tab completion on pipe

### ISSUE THREAD

**Issue by raggnic** [cmderdev/cmder#1842]
Thx for this amazing software that brings at least cmd console closer of unix standard.

I noticed a minor issue. If you type `le and  "tab"` you get 
` λ le
LegacyNetUXHost.exe  less.exe             lessecho.exe         lesskey.exe`

But if you type` λ set | le and "tab"` it doesn't show anything. 
It may be not an issue, currently I'm trying stuff.

**Comment by daxgames** [comment]
works for me using [latest](https://ci.appveyor.com/project/MartiUK/cmder/build/1.0.743-master/artifacts)
