### ISSUE TITLE
Taking over clink-completions maintenance 

### ISSUE THREAD

**Issue by vladimir-kotikov** [cmderdev/cmder#1843]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Description of the issue 

Hello, Cmder maintainers. As you might know one of my pet projects, https://github.com/vladimir-kotikov/clink-completions is included into Cmder distribution and I hope helps users a lot in their daily Cmder usage.

However I basically abandoned the completions repo since I've completely migrated to a Mac ecosystem about a couple years ago and don't really have an ability and, mainly, desire to maintain at anymore. Although I thought that it's pretty stable (at least it was for my purposes), people still contribute [fixes](https://github.com/vladimir-kotikov/clink-completions/pull/100) and [new features](https://github.com/vladimir-kotikov/clink-completions/pull/98) which I can't validate and don't want to merge before someone has signed off on.

So I was wondering if someone of you might want to take over maintenance work on clink completions. I'd really appreciate this.

--
Best regards, Vladimir

**Comment by Stanzilla** [comment]
uh, I guess it would make sense to move it into the cmderdev org?

**Comment by daxgames** [comment]
@stanzilla and @vladimir-kotikov makes sense to me.

**Comment by vladimir-kotikov** [comment]
👍 Feel free to do so. Let me know if you need anything from my side

**Comment by Stanzilla** [comment]
@vladimir-kotikov you'd have to go to the repo settings and hit "transfer ownership"

**Comment by vladimir-kotikov** [comment]
![image](https://user-images.githubusercontent.com/3857604/44973757-47260880-af66-11e8-880f-aeccad69bd7b.png)

**Comment by vladimir-kotikov** [comment]
Not sure if it would work but I can add you guys as a maintainers so you can then transfer it to cmderdev yourself

**Comment by daxgames** [comment]
I think we will need to elevate your permissions long enough to do the transfer.

https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/

**Comment by daxgames** [comment]
@cmderdev/core Bump

**Comment by daxgames** [comment]
@cmder/core Or what is the possibility of adding @stanzilla or me to cmder/core team so one or both of us has the appropriate permissions to fully manage the org?
