### ISSUE TITLE
Pressing backspace while typing command clears the whole terminal 

### ISSUE THREAD

**Issue by hecerinc** [cmderdev/cmder#1844]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 

Pressing backspace (or Ctrl+Backspace) when typing a command will delete characters up to the cursor point for the whole terminal.

Repro: 

1. Print to the terminal some large amount of text

![image](https://user-images.githubusercontent.com/7988472/43231976-7cb62a6e-9023-11e8-8a39-0edce26bffc2.png)

2. Type a new command of any length

3. Press backspace

![image](https://user-images.githubusercontent.com/7988472/43231987-8d0f956c-9023-11e8-9070-ef0b679c75c4.png)

This doesn't happen when I run the ConEmu64 executable, so I assume it must be a cmder bug.

Running on Windows 10 the latest build.

Let me know if you need any more info

**Comment by lgaborini** [comment]
Confirmed! 

- ConEmu 180528 preview
- Cmder 1.3.6.678
- Windows 10 Insider Preview 10.0.17692.1004

**Comment by lgaborini** [comment]
Updated ConEmu to 180626 preview, bug is fixed.
