### ISSUE TITLE
Fails to parse path in PATH system variable with '&'

### ISSUE THREAD

**Issue by Lopson** [cmderdev/cmder#185]
I have a path in my PATH system variable that contains the character '&' in it. For some reason, whenever cmder starts up, he throws a "The system cannot find the path specified" error when it tries to handle that path.

Here's the content of the PATH variable (output of cmd.exe):
PATH=C:\Program Files (x86)\AMD APP\bin\x86_64;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\Toshiba\Bluetooth Toshiba Stack\sys\;C:\Program Files (x86)\Toshiba\Bluetooth Toshiba Stack\sys\x64\;C:\WinDDK\7600.16385.1\Tools\devcon\amd64;C:\Yap64\bin;c:\go\bin;C:\Program Files (x86)\ECLiPSe 6.0\lib\i386_nt;C:\Program Files (x86)\MiKTeX 2.9\miktex\bin;C:\Program Files (x86)\Video & Audio\MKVtoolnix;C:\Python27;C:\Program Files (x86)\Android\android-sdk\platform-tools;C:\Program Files (x86)\GnuPG\pub;C:\Program Files (x86)\Dig;C:\Program Files (x86)\Video & Audio\Quicktime\QTSystem;C:\Program Files (x86)\GTK2-Runtime\bin;C:\Program Files (
x86)\Nmap

And here's what cmder is printing out:
PATH=C:\cmder\vendor\conemu-maximus5\ConEmu;C:\cmder\vendor\conemu-maximus5;C:\Program Files (x86)\AMD APP\bin\x86_64;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\Toshiba\Bluetooth Toshiba Stack\sys\;C:\Program Files (x86)\Toshiba\Bluetooth Toshiba Stack\sys\x64\;C:\WinDDK\7600.16385.1\Tools\devcon\amd64;C:\Yap64\bin;c:\go\bin;C:\Program Files (x86)\ECLiPSe 6.0\lib\i386_nt;C:\Program Files (x86)\MiKTeX 2.9\miktex\bin;C:\Program Files (x86)\Video 

Notice how the last one stops at the '&' character.

**Comment by Ramouch0** [comment]
I know this issue is closed. But I managed to work around this by changing init.bat file to this :
```
:: Enhance Path
@setlocal
@for %%G in ("%path:;=" "%") do @call set "TMPPATH=%%TMPPATH%%;%%G"
@set PATH=%CMDER_ROOT%\bin%TMPPATH%;%CMDER_ROOT%
@endlocal
``` 
I had the problem with "MySQL Fabric 1.5.4 & MySQL Utilities" in my path.

**Comment by kfrederix** [comment]
I had the exact same problem with "MySQL Fabric 1.5.4 & MySQL Utilities 1.5.4 1.5" in PATH.
For me, this simple fix did the trick:
(just put double quotes around the whole thing in `init.bat`)
```
:: Enhance Path
@set "PATH=%CMDER_ROOT%\bin;%PATH%;%CMDER_ROOT%"
```

**Comment by jarst** [comment]
How about third party batch files that manipulate PATH?
Unless I patch them, one by one, I will see the same warning whenever I execute them.
