### ISSUE TITLE
Customize/reset prompt for single task

### ISSUE THREAD

**Issue by bllngr** [cmderdev/cmder#1851]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Description of the issue 

I have a task that calls cmd.exe with a custom init script. This script changes background and text colors, so the default prompt looks weird in it. I'd like to reset the prompt for this single task to the default (resp. change it to a prompt without defined colors).

In ConEmu, that's possible by [setting the ``prompt`` variable in the task:](https://conemu.github.io/en/CmdPrompt.html)

    set PROMPT=$P$_$G & cmd.exe /k ...

However, this doesn't work in cmder, which seems to overwrite the prompt globally.

Is there any way to change/reset the prompt for a single task only in cmder?

**Comment by daxgames** [comment]
The latest build ov cmder [here](https://ci.appveyor.com/project/MartiUK/cmder/build/1.0.743-master/artifacts) allows you to change the prompt. The or catch is you need to know lua.

Not sure it's possible to do it for one specificsession though.

**Comment by Tb0b** [comment]
I'm searching almost the same trick.
I'd like to bring different prompt when I use cmder or cmder(Admin) like in a linux shell with Green $ or Red # in bashrc . I've already tuned my prompt with the help of a clink_prompt.lua but I dont find how to differentiate cmder and cmder(Admin) and bring to everyone a specific prompt.
thank you by advance for your help.

**Comment by daxgames** [comment]
@Tb0b not sure I can help but can you share your `clink_prompt.lua`.  I assume you are putting this in `%cmder_root%/config`?

**Comment by Tb0b** [comment]
sure I can (I found it here in GitHub and it's goo for me) :
[https://github.com/Tb0b/lua/blob/master/clink_prompt.lua](url)

**Comment by Tb0b** [comment]
with conemu installed out of cmder it does the job , i'd like to do the same with cmder

**Comment by daxgames** [comment]
@tbob the below works for me:

```
function my_prompt_filter()
    cwd = clink.get_cwd()
    if clink.get_env('ConEmuIsAdmin') == 'ADMIN' then
      prompt = "\x1b[1;32;40m{cwd}{git}{hg}\x1b[1;30;40m{lamb} \x1b[0m"
      new_value = string.gsub(prompt, "{cwd}", cwd)
      clink.prompt.value = string.gsub(new_value, "{lamb}", "#")
    else
      prompt = "\x1b[1;32;40m{cwd}{git}{hg}\x1b[1;30;40m{lamb} \x1b[0m"
      new_value = string.gsub(prompt, "{cwd}", cwd)
      clink.prompt.value = string.gsub(new_value, "{lamb}", "$")
    end
end

clink.prompt.register_filter(my_prompt_filter, 1)
```

@bllngr You could do something similar only look at this env variable to match the task name:

```
ConEmuTask={cmd::Cmder as Admin}
```
