### ISSUE TITLE
ssh-agent doesn't work even after uncommenting call "%GIT_INSTALL_ROOT%/cmd/start-ssh-pageant.cmd"

### ISSUE THREAD

**Issue by Ciwan1859** [cmderdev/cmder#1852]
Hello all

I have uncommented this line `call "%GIT_INSTALL_ROOT%/cmd/start-ssh-pageant.cmd"`  in the file:

`C:\cmder_mini\config\user-profile.cmd`

This was suggested on a similar issue on SSH-Agent in this repo, but I still cannot get Cmder to work with SSH.

I have PuTTY installed, and Git Bash works fine with SSH. Only Cmder seems to have issues for me. After uncommenting that line, when I open Cmder, I get this:

![image](https://user-images.githubusercontent.com/932975/43994334-1e8d412a-9d93-11e8-99a2-46a4fb3a3022.png)

What can I do to get SSH working in Cmder?

**Comment by daxgames** [comment]
Please elaborate, I've never had any issues with ssh in cmder.  BTW Cmder bash shell is git bash.

**Comment by Ciwan1859** [comment]
@daxgames perhaps I'm going about this the wrong way. What do you do to get SSH Agent working on Cmder?

PS. [This is the thread](https://gist.github.com/Shoozza/8fe8b0c85fa89cd3b1c4) (towards the bottom) that suggested uncommenting the line.

**Comment by daxgames** [comment]
@ciwan1859 sorry I did not read the subject I just saw that you could not get ssh working.  I do not use ssh-agent so I can't answer that.

**Comment by daxgames** [comment]
@Ciwan1859 I uncommented these two lines for `%cmder_root%/config/user-profile.cmd`:

```
SET SSH_AUTH_SOCK=/tmp/.ssh-pageant-auth-sock
call "%GIT_INSTALL_ROOT%/cmd/start-ssh-pageant.cmd"
```

Now when I start a session I get:

```
Starting ssh-pageant...
SSH_AUTH_SOCK='/tmp/.ssh-pageant-auth-sock'
SSH_PAGEANT_PID=8808
```

So seems to work for me without getting the error you reported.

**Comment by Ciwan1859** [comment]
Thank you, that was it! I had to uncomment two lines instead of one. I was uncommenting only one before.

Much appreciated.
