### ISSUE TITLE
How to launch new console tab with the same default dir for the task

### ISSUE THREAD

**Issue by heihachi88** [cmderdev/cmder#1853]
In Tasks section i've set: `-new_console:d:C:\Users\Alexander\Sites` (WSL::BASH)

When i open cmder at start, it uses my custom path.

However when i Ctrl+T new tab, it suggests me directory where the cmder.exe initially launched.

**Comment by daxgames** [comment]
* Remove '-new_console:d:C:\Users' from the task
* Create a shortcut with a target of '"[path to cmder root dir]\cmder.exe" /start "C:\Users\Alexander\Sites"'

**Comment by gaia** [comment]
I set my shortcut to

`/start "C:\Users\myname\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc\LocalState\rootfs\home\bashuser"`

but it starts in the `/` of the bash environment, not `~` (`/home/bashuser`)

minor annoyance, but how do I start on `/home/bashuser`
