### ISSUE TITLE
Shift-arrow Shift-arrow doesn't work to extend selection; can't place cursor with mouse

### ISSUE THREAD

**Issue by BobRay** [cmderdev/cmder#1854]
### Purpose of the issue
- [x ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 
On Windows 10, you can normally place the cursor, then use shift-right-arrow or shift-left-arrow to select text in either direction.  This works when selecting text in previous commands in Cmder, but it doesn't work with the current command you're typing (where you need it most). You should be able to create a selection from the current cursor position in either direction using shift-arrow. 

You also can't place or move the cursor in a line you're typing by clicking with the mouse. You can only move the cursor with the arrow keys.

I'm almost certain that both of these worked in earlier versions but they don't work for me now.

**Comment by daxgames** [comment]
Probably by design in conemu.  Cmder uses ConEmu as terminal emulator, if you are experiencing a problem or a question, please open an issue over at https://github.com/Maximus5/ConEmu

Thank you! :-)
