### ISSUE TITLE
[Question] Do not freeze console when text selected

### ISSUE THREAD

**Issue by Raoul555** [cmderdev/cmder#1855]
Hi all,

When selecting a text in Cmder via the mouse, the console is freezed: can't type any char with the keyboard until the selection is removed.

Is it possible to change this behavior? I'd like that the selection stay active until a new element is inserted in the clipboard, and I can keep working with the console.

Is that possible?

Thanks,
Raoul

Cmder v. 180528 preview

**Comment by ogrim** [comment]
I usually enable this, so the selection doesn't hang around after I have made it:

- Go to `Keys & Macro` -> `Mark/Copy`
- Select `Reset selection on Left Button release`


Now the selection is copied straight to the clipboard, and then it is reset so you can continue typing.

Is this what you need?

**Comment by AlBannaTechno** [comment]
[ConEmu]:https://github.com/Maximus5/ConEmu
you aim to extendable selection! why?
there are two types of selection used overall 
emulators 
* ignore selection if user press any non-special key
* don't ignore selection except when user press some special keys

But non-restricted selection used usually with text editors like `vim/nvim`

yes it's possible: but it's relative to  [ConEmu] core
I'm not read the source code of ConEmu but I think this very easy to implement
I will take a flash look at the source code and see if I can implement this feature

but for logical steps, this can be done by
* Stop Prevent Inputs when user select text-area
* Allow select highlight to be at the same place if the selected area not-writable
* Make select highlight extendable if the currently selected area reach the end-cursor 
    > so it's will extend when user type other characters 
    * But now we will on a cross-roads Because when user press enter `/n` we can do one of next
        * stop dynamic selection but not remove it and allow the user to complete typing
        *  remove selection `with copy it` and allow the user to complete typing
        * keep the selection and make it continue with the user
            * select the result `if command return result` and `cmder` auto-generated lines ` path, lambda `
                > this will cause a very big problem if the result is dynamic like `vim` 
            * ignore the result and keep select the previous selection and then select the new selection
                > this will make a separate selection `hard to implement`

**Comment by Raoul555** [comment]
Thanks for your response ogrim and AlBannaTechno.

I will got for the `Reset selection on Left Button release` options.

It's not 100% what I wanted, I more expected a putty like behavior or terminator like, but at least my console get not blocked anymore randomly. I understand what is the default behavior aims to achieve, but for me it was really anyoing, and was a reason to drop Cmder.

**Comment by daxgames** [comment]
This is a feature of Conemu which is a component of Cmder.  I would suggest asking your question in the Conemu Issues tracker at https://github.com/Maximus5/ConEmu/issues
