### ISSUE TITLE
[Feature request] Remove file extension for auto-completed executable file name

### ISSUE THREAD

**Issue by AlBannaTechno** [cmderdev/cmder#1856]
## HI 
When autocomplete work with general windows`os` path cmder show the extension of the file

#### for example when typing `gif2` and press `tap` key `cmder` will generate `gif2h5.exe`
    > /c/Program Files/Anaconda3/Library/bin/gif2h5.exe
it's very **ugly** to show `.exe` or any other auto-executed types
we need to not produce it or at least give a user the ability to choice

**Comment by DRSDavidSoft** [comment]
Hi @AlBannaTechno,

This behaviour is related to the **Clink** binary. Please re-submit your issue here:
https://github.com/mridgers/clink/issues/new

Thank you for understanding.
