### ISSUE TITLE
[FeatureRequest] commands on close

### ISSUE THREAD

**Issue by matthieu-blin** [cmderdev/cmder#1858]
Cmder Task can execute some commands at start. Should be great to execute some commands on close too !
ex :
on Start 
vim --servername "%1"
on Close 
vim --servername "%1" --remote-expr 'execute("wqa")'
(maybe i'll try to do it myself btw)

**Comment by xiazeyu** [comment]
Need this feature too.

**Comment by daxgames** [comment]
Not likely in Cmder.  Maybe ask in Conemu the terminal program used by Cmder. https://github.com/Maximus5/ConEmu/issues
