### ISSUE TITLE
Missing colors on VSCode

### ISSUE THREAD

**Issue by furtivesock** [cmderdev/cmder#1861]
Hello,
I've already read an issue about my problem ( https://github.com/cmderdev/cmder/issues/1646 ), but there was not a concrete solution. I follow instructions from VSCode website. It works, but colors are missing (i'm using Symfony for my project) : 
![image](https://user-images.githubusercontent.com/38814441/44629989-6665da00-a957-11e8-8e56-4e08fefde35d.png) 
I would like something like that : 
![image](https://user-images.githubusercontent.com/38814441/44630074-8fd33580-a958-11e8-9959-1a177c1da948.png)

Instead, I'm using cmder.exe to have colors but this solution is a little bit frustrating because I would like to benefit from the included terminal of VSCode.

I hope someone will help me.
Thanks for your reading.

**Comment by DRSDavidSoft** [comment]
@furtivesock I think this issue is related to the way that PHP binaries on windows work; they don't usually return colors.
Can you see if the colors work without integrating Cmder in VS Code?

**Comment by tyler36** [comment]
I got it working by updating my PHP to 7.2 flavor. #1646
