### ISSUE TITLE
Can not open any root directory of disk

### ISSUE THREAD

**Issue by tjuyy** [cmderdev/cmder#1863]
##Can not open any root directory of disk
Version 1.3.6.678

![image](https://user-images.githubusercontent.com/10655032/44712357-27648f80-aae3-11e8-99e0-1ad4ae2cd8f3.png)

**Comment by DRSDavidSoft** [comment]
@tjuyy Please elaborate.

**Comment by taichushouwang** [comment]
I also has this problem. When I click "cmder here", 
![image](https://user-images.githubusercontent.com/6072834/44890081-52c9c300-ad0b-11e8-9814-acec485b048f.png)

**Comment by DRSDavidSoft** [comment]
Can you send the config file from here:

1- Go to the Registry (<kbd>Win</kbd> + <kbd>R</kbd> → Enter `RegEdit` and click `OK`)
2- Open the following: `HKEY_CLASSES_ROOT\Directory\Background\shell`
3- Find `Cmder` or `cmder_shell`, right-click → **Export** and save the file
4- Attach the file with your next comment.

**Comment by taichushouwang** [comment]
@DRSDavidSoft here the file is.

[cmder.txt](https://github.com/cmderdev/cmder/files/2339036/cmder.txt)

And the setting of the cmder

![image](https://user-images.githubusercontent.com/6072834/44896901-591c6700-ad2c-11e8-8a86-bfd548be2c70.png)

**Comment by tjuyy** [comment]
Here is my reg file



```ini
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\directory\shell\Cmder]
@="Cmder Here"
"NoWorkingDirectory"=""
"Icon"="D:\\Program\\cmder\\icons\\cmder.ico"

[HKEY_CLASSES_ROOT\directory\shell\Cmder\command]
@="\"D:\\Program\\cmder\\Cmder.exe\" \"%V\""
```

**Comment by KavenWork** [comment]
change `[HKEY_CLASSES_ROOT\directory\shell\Cmder\command]`
from
```
"C:\MyProgram\cmder\Cmder.exe" "%V"
```
to
```
"C:\MyProgram\cmder\Cmder.exe" /START %V
```

**Comment by tjuyy** [comment]
> change `HKEY_CLASSES_ROOT\Directory\Background\shell\Cmder\command`
> from
> 
> ```
> "C:\MyProgram\cmder\Cmder.exe" "%V"
> ```
> to
> 
> ```
> "C:\MyProgram\cmder\Cmder.exe" /START %V
> ```

It worked. Thanks!
