### ISSUE TITLE
Command 'jar' is not working

### ISSUE THREAD

**Issue by lynnchin** [cmderdev/cmder#1867]
Hi,

I am having some issue on running the jar command in cmder.
I have checked that in my environment variables I have the following code snippet:

`C:/Program Files/Java/jre1.8.0_172/bin:`

found in the PATH environment variable. 

I even tried run it with java -jar XXXX.war and I am getting error message` Error: Unable to access jarfile xf`

Any ideas or tips on what is going on and how to fix this?

**Comment by daxgames** [comment]
Does the exact same command work in other cmd.exe based shells?  The default windows command prompt?

**Comment by lynnchin** [comment]
Yes. It works fine on my powershell. Not sure what is going on wrong here!
