### ISSUE TITLE
Register on OS startup option is not working

### ISSUE THREAD

**Issue by heihachi88** [cmderdev/cmder#1868]
### Purpose of the issue
- [x ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 
Win 10 (1803)

If i check "register on OS startup" it creates an entry in registry. However it doesn't start on windows boot/restart because of arguments it adds to launch the program.

If i add just a shortcut to `shell:startup` location, then it automatically loads on boot/restart.

**Comment by daxgames** [comment]
This is a feature of Conemu which is a component of Cmder.  I am unfamiliar with this feature and your issue does not have enough detail of the expected outcome and the failure.  I woul suggest aking your question in the Conemu Issues tracker at https://github.com/Maximus5/ConEmu/issues
