### ISSUE TITLE
Tabbar for vertical monitor

### ISSUE THREAD

**Issue by mljli** [cmderdev/cmder#1872]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 
Hi, I'm using a vertical monitor. With over 10 tabs opened, the monitor is too narrow to show all tab names clearly. Is it possible to put the tabbar on right?

**Comment by daxgames** [comment]
Cmder uses conemu for it's terminal window you should ask over there.
