### ISSUE TITLE
Using OpenSSH from Windows 10 bundle causes screen to flash 

### ISSUE THREAD

**Issue by onkami** [cmderdev/cmder#1875]
As explained in https://github.com/Maximus5/ConEmu/issues/1625,
cmder with ConEmu is experiencing problems with OpenSSH from windows 10.

Suggestion is to prefer cmder's own SSH to avoid the issue or at least warn users that OpenSSH can cause problems explained it the tread above.

**Comment by ihorzenich** [comment]
Adding `c:\tools\Cmder\vendor\git-for-windows\usr\bin;` to cmder Settings->Startup->Environment did the trick for me.

![cmder-ssh-flashing-fix](https://user-images.githubusercontent.com/1684521/52853719-1822de00-3125-11e9-8ad2-927aaebb72d6.png)

**Comment by Sebi11** [comment]
@onkami How do you define which SSH client to use by default please?

**Comment by daxgames** [comment]
you can do that or edit your cmder task and add `/nix_tools 2` 

![image](https://user-images.githubusercontent.com/7318053/54469331-17558a00-476d-11e9-8ab6-142ec5028a79.png)

Note: This will prefer even more *nix like tools that exist in other paths that are a part of Git for Windows.
