### ISSUE TITLE
`CreateFile() Error: 5` with Cmder Here

### ISSUE THREAD

**Issue by MuyePeikon** [cmderdev/cmder#1879]
I use {Powershell::Powershell} by default. And when open cmder with Cmder Here, it always show `CreateFile() Error: 5`. But if open another tab with alt+shift+3, it's OK.
I wonder why and how to fix it, thx.

**Comment by daxgames** [comment]
Don't know never seen that.

**Comment by daxgames** [comment]
Seems to work fine for me with latest cmder.
