### ISSUE TITLE
Output is very slow

### ISSUE THREAD

**Issue by patricksnape** [cmderdev/cmder#188]
Couldn't find an appropriate issue for this, but output in cmder seems to be very slow. This is particularly evident when there is a lot of output produced. For example, if I'm using Python and I run a large suite of tests, a lot of output is printed. If I run this in Powershell, it flies through the output and is finished in a couple of seconds. In cmder, however, it takes many seconds and although I can tell the tests are finished, it just seems to be taking a long time to clear the output.

Any clues as to what settings might effect this/if this seems to be a bug?

**Comment by aruizca** [comment]
+1

**Comment by mmagnuski** [comment]
I have the same problem - all commands are significantly slower than normal cmd (sometimes take a few seconds). :cry:

**Comment by netinept** [comment]
+1 the output is noticeably slow, even from a fresh download and just running the `ls` or `ls -lh` commands straight out of the box. Native commands seem to be reasonably fast (compare `dir` with `ls`).

**Comment by mirkos** [comment]
I can verify this as well. I have downloaded cmder yesterday and ```ls``` is noticeably slower than when I execute it from cmd. Also, native commands like ```dir``` run much faster than say ```ls```.

**Comment by igorng** [comment]
+1. I noticed that after re-installig cmder, everything went back to the normal, but after a few days of use it becomes slow again!

**Comment by vrajanap** [comment]
+1. Right after starting cmder with a fresh install, running "ls" took around 10-14 seconds. dir in the same console took less than few milliseconds.

**Comment by LordNoteworthy** [comment]
The same here, just ls output  is significantly slow !

**Comment by duckie** [comment]
+1 Same here. On Windows 10 Pro 64bits.

**Comment by MrWharfsnort** [comment]
I seem to be having the same problem, but it seems to be only when working within a git repo

**Comment by tribet84** [comment]
+1

**Comment by sekai92id** [comment]
+1

**Comment by delscorcho** [comment]
I followed the advice on another thread and changed cmder.lua to return false in get_git_dir.

local function get_git_dir(path)
    return false
    --return get_dir_contains(path, '.git')
end

Native commands are still far faster (dir vs. ls), but at least it isn't slow just to type characters in cmder.

**Comment by gabrielbiga** [comment]
+1

**Comment by kinder112** [comment]
+1 the trick with get_git_dir fixed it for me.
