### ISSUE TITLE
How to open Gitbash and make it run some commands automatically

### ISSUE THREAD

**Issue by charlie3620** [cmderdev/cmder#1880]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

**Comment by charlie3620** [comment]
actually i was doing some commands manually like opening the files and opening the folders using the git bash every time as those files and folders are necessary for me.

But is there any process that the git bash should open automatically and run those commands automatically in the terminal

**Comment by daxgames** [comment]
@charlie3620 Do you want to run the same commands at the start of every git bash session?

If so do you want those commands to be portable and follow cmder wherever you download and run it?  If so and you need portable add the commands to `$CMDER_ROOT/config/user_profile.sh` if not portable edit `$HOME/.bashrc`.

There is not currently a way to make git bash do what you are asking for a single session.

**Comment by daxgames** [comment]
1. Create a task for what you want to do, See: https://github.com/cmderdev/cmder/issues/2022#issuecomment-473572828
2. Run: `cmder /task [taskname]`
