### ISSUE TITLE
Add Tabname to Window Title

### ISSUE THREAD

**Issue by dampfklon** [cmderdev/cmder#1881]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [X] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 
Add an option to add the name of the tab which has focus to window title. similar to the apperance -> always show numbers option.

reason: i use keepass with auto-type and it matches the window titles to select relevant entries.

**Comment by daxgames** [comment]
This is a question for the conemu developer.
