### ISSUE TITLE
Startup task cmd::Cmder mess with open ssh-agent

### ISSUE THREAD

**Issue by sdaclin** [cmderdev/cmder#1885]
### Purpose of the issue
- [x ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 
When trying to load the ssh agent by uncommenting the line in user-profile.cmd : 
* call "%GIT_INSTALL_ROOT%/cmd/start-ssh-pageant.cmd"

The agent load in a sub ms-dos context and I'm not able to use ssh-add to add my keys.
Typing exit makes the sub context to be closed and then I get my keys loaded.

## Investigation : 
Below is the difference between previous and current default configuration
![image](https://user-images.githubusercontent.com/706379/45632418-922f3800-ba9d-11e8-8543-1a273296a699.png)

If I use the previous configuration, everything works as expected

**Comment by ToniPeratalo** [comment]
Same kind of behavior is also when using start-ssh-agent.cmd
- call "%GIT_INSTALL_ROOT%/cmd/start-ssh-agent.cmd"
Keys are initialised but on that "ms-dos console" there is no color in prompt and git branch is not shown at all. When exiting this console, branch is shown.
![image](https://user-images.githubusercontent.com/25682299/46018021-91bc2000-c0e1-11e8-99ff-ec6d041e2304.png)

Adding that -new_console parameter does not help.

**Comment by dw72** [comment]
I have the same, bad behaviour.

**Comment by bastelflp** [comment]
Have a look at #1807 and #1781

**Comment by daxgames** [comment]
`call "%GIT_INSTALL_ROOT%/cmd/start-ssh-agent.cmd" /k exit` is what current versions of cmder has in `user_profile.cmd`
