### ISSUE TITLE
Cmder running jest and react commands

### ISSUE THREAD

**Issue by FG28** [cmderdev/cmder#1890]
### Purpose of the issue
- [X] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 

Using react and jest, when trying to run **npm run test** I get the following error :
![image](https://user-images.githubusercontent.com/43477278/45891754-48f12800-bdbe-11e8-9835-42172d6339ed.png)

However when that same command is runned on **Git Bash** for instance, the error doesn't occur and I'm able to run all the tests without problems.

Did anybody had the same issue, or know how to fix this?

Thanks

**Comment by daxgames** [comment]
@FG28 What shell `cmd.exe` or `bash.exe` in cmder?
