### ISSUE TITLE
Sometimes no window preview when using Aero Peek

### ISSUE THREAD

**Issue by himhimlo** [cmderdev/cmder#1892]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 

Sometimes, i.e. sometimes it works but other times not, the Aero Peek of cmder window is not showing, instead it shows a loading ring.
I am running Cmder Version 1.3.6.678 on Windows 10 Pro Version 1803.
![image](https://user-images.githubusercontent.com/3815971/46193808-fb326d80-c331-11e8-9327-dcffe42b5f2c.png)

**Comment by daxgames** [comment]
Report this to conemu maintainer
