### ISSUE TITLE
ConPTY API support

### ISSUE THREAD

**Issue by lars18th** [cmderdev/cmder#1896]
Hi,

Thank you for this great piece of software! :wink: 

Will be support for the new Windows Pseudo Console (ConPTY API)?
https://blogs.msdn.microsoft.com/commandline/2018/08/02/windows-command-line-introducing-the-windows-pseudo-console-conpty/

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)
