### ISSUE TITLE
Issue with text "Overtyping" in the command line.

### ISSUE THREAD

**Issue by jakub530** [cmderdev/cmder#1897]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 
 
I have a problem, which occurs when I try to edit the command in the command line, after I ssh into server. 

As an example when I enter command 54321 into command line and try to input a between "2" and "1", my command line looks like expected - 5432a1. Similar with placing it between "3" and "2", as well as "3" and "4". However when I put it between "5" and "4" my command line is 5a321. 

However it is not the case that "a" was "inserted" over "4" it is only visual problem. When I press enter I get command 5a4321 and before pressing enter I can also hold right arrow to "reveal" subsequent letters of the command, i.e. when the cursor returns to the end of the line the command that is displayed before running is 5a4321. 

It seems to be the case that I can only add characters up to three places from the end of command line, otherwise it exhibits this weird behavior.

While it is possible to work around it by regular refreshing of command line using arrow keys, it makes it much more difficult to work. I would greatly appreciate any help with solving this issue.

**Comment by aniketmeshram** [comment]
I think when you ssh into the server the prompt mode is changed to something else (maybe vi mode or something else). try running 'bash' as soon as you login into the server.
