### ISSUE TITLE
Java programs after version 8 does not run

### ISSUE THREAD

**Issue by e2-fo** [cmderdev/cmder#1898]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

**Comment by daxgames** [comment]
Steps to replicate?

**Comment by e2-fo** [comment]
Me and my colleague have this problem on our work stations. We are using Chocolatey. I have not seen the problem on other machines.

Trying to run Tomcat web app with Java 8:

[error occurred during error reporting (printing fatal error message), id 0xc0000005]                    
                                                                                                         
#                                                                                                        
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007e1100026ffc, pid=20440, tid=0x0000000000005d44   
#                                                                                                        
# JRE version: OpenJDK Runtime Environment (8.0_181-b02) (build 1.8.0_181-b02)                           
# Java VM: OpenJDK 64-Bit Server VM (25.181-b02 mixed mode windows-amd64 compressed oops)                
# Problematic frame:                                                                                     
# C  [ConEmuHk64.dll+0x26ffc]                

When using Java version higher than 8, there is no output.
Running java -version has normal output with Java 8 and no output with versions higher than 8.

**Comment by reseto** [comment]
just tried this
![image](https://user-images.githubusercontent.com/6586857/49874604-361b4c00-fe1f-11e8-9925-f220001b1634.png)
