### ISSUE TITLE
Getting Old command popup 

### ISSUE THREAD

**Issue by osamakhanedu** [cmderdev/cmder#1900]
I am getting old command popping up on console,  

for example: 
i run the command ls to list  the directory content.  then i run the command cls the clear the console, but when again the run any command for example cd, then it show all the previous command along the content, which fill my console screen.

**Comment by daxgames** [comment]
Not sure I understand.  Please provide more detail.

**Comment by aniketmeshram** [comment]
@osamakhanedu a screenshot perhaps
