### ISSUE TITLE
windows10 using cmder unrecoginized paramter error 

### ISSUE THREAD

**Issue by lonecloud** [cmderdev/cmder#1902]
### Purpose of the issue
- [√ ] Bug report (encountered problems/errors)

### Description of the issue 
open in c:/demo directory is ok!**but open C:/ ** while tell me this error ：
![](https://github.com/lonecloud/issuesImages/blob/master/cmder/unregister.png?raw=true)
please help me thanks

**Comment by daxgames** [comment]
@lonecloud steps to reproduce?  Have you tried latest unreleased [builds](https://ci.appveyor.com/project/MartiUK/cmder/build/artifacts)?

**Comment by daxgames** [comment]
This is a bug currently I don't know how to fix it.

**Comment by daxgames** [comment]
This is now fixed in Cmder 1.3.11

**Comment by daxgames** [comment]
The shell context menu `/register||/unregister` on drives will be in the next release.
