### ISSUE TITLE
nano stop working

### ISSUE THREAD

**Issue by karthikeyanangler** [cmderdev/cmder#1903]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 

The nano suddenly stop working from yesterday on my windows 10 PC.

i am getting bellow error
```
'nano' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by daxgames** [comment]
It must not be in your path.  What changes?

**Comment by daxgames** [comment]
closing inactivity

**Comment by daxgames** [comment]
Asked and answered.  See above.

**Comment by RGPhD** [comment]
That did not work for me so I am using Git Bash and all of the commands are working there.
Thank you,
Robelyn

**Comment by daxgames** [comment]
Can you explain a little more?  Cmder includes git bash.  Are you using bash inside cmder or separate git bash?  Nano is a part of git bash in cmder and works for me in cmder.

What is the output of `where nano`

```
where nano
C:\\users\\dtgam\\cmder\\vendor\\git-for-windows\\usr\\bin\\nano.exe
```
If you get nothing then your path is not right and you need to fix it.

What is the output of `echo %path%`

**Comment by daxgames** [comment]
Are you using cmder or cmder mini?

**Comment by daxgames** [comment]
@RGPhD I even tried with cmder mini and external Git for windows installed and it still worked as long as `C:\Program Files\Git\bin` was in the path before launching `Cmder.exe` so it could find it and update its path.
