### ISSUE TITLE
Problem on starting cmder

### ISSUE THREAD

**Issue by stnlylee** [cmderdev/cmder#1904]
### Purpose of the issue
- [ x] Bug report (encountered problems/errors)

### Description of the issue 
I was able to use Cmder without any issue until I installed bash on my Windows 10 but not sure they are related

After I reinstalled the package, first start it will freeze immediately:
![image](https://user-images.githubusercontent.com/8663190/46678539-9d0a6200-cc30-11e8-84d2-08c6d362bca4.png)

Second start it resumes but seems missing something (still usable)
![image](https://user-images.githubusercontent.com/8663190/46678849-43eefe00-cc31-11e8-9cc6-651a9642c76c.png)

**Comment by tonybengue** [comment]
I have a problem too when I start my new fresh Cmder downloaded. 
There is any path written here, so I can't type commands.

I tried a lot of things, especially in Cmder setting.

![image](https://user-images.githubusercontent.com/25368989/46910317-ec0f0a80-cf42-11e8-8c0c-53f434b4de60.png)

Thanks

**Comment by daxgames** [comment]
@stnlylee and @tonybengue When you say 'installed bash on my Windows 10' I assume you mean 'wsl'? I have wsl and do not see this issue.  Have you tried the latest unreleased [builds](https://ci.appveyor.com/project/MartiUK/cmder/build/artifacts)

**Comment by tonybengue** [comment]
I tried it but there is nothing. When I open cmder in admin or not, I can see that current path is missing.
I don't know what to do.

When i search cmd in cortana, i can't open it, however I can use it from System32 and anywhere in the system.

**Comment by daxgames** [comment]
@tonybengue I don't understand your Response.  Can you clarify?

**Comment by tonybengue** [comment]
I said that there is no path in my cmder. I can't access Windows console by Cortano but I can use it anywhere else in the system by typing cmd in explorer.

![image](https://user-images.githubusercontent.com/25368989/46966125-18df3100-d0ad-11e8-83d3-57ba140ed161.png)

**Comment by daxgames** [comment]
'I can't access Windows console by Cortano' I don't see how this is related to cmder.  

Can you provide the contents of your `%cmder_root%\config\user-profile.cmd`?

**Comment by stnlylee** [comment]
@daxgames yes it's wsl on windows 10 - windows subsystem for linux

I have tried the link provide it's actually the same
![image](https://user-images.githubusercontent.com/8663190/46989947-eab02e80-d14a-11e8-9e77-25e239c6c5ca.png)
![image](https://user-images.githubusercontent.com/8663190/46989985-116e6500-d14b-11e8-9309-125c4ddec0cd.png)

**Comment by daxgames** [comment]
@stnlylee Thanks.

@tonybengue Could you have the same issue?  I can't reproduce the problem.

**Comment by daxgames** [comment]
Closing, inactivity.
