### ISSUE TITLE
Portableapps

### ISSUE THREAD

**Issue by BlackGad** [cmderdev/cmder#1906]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Description of the issue 
Any chance to see cmder in this [list](https://portableapps.com/apps)? 

Manual how to create installer
https://portableapps.com/apps/development/portableapps.com_installer

Forum topic
https://portableapps.com/node/43597

**Comment by daxgames** [comment]
Pull requests are welcome.

**Comment by RoyiAvital** [comment]
That would be great to have it.

By the way, reading the thread I can see `Cmder` isn't fully portable as it leaves configuration at `LOCALAPPDATA\clink` and `HCKU\Console\ConEmu`.

**Comment by daxgames** [comment]
@royiavital Cmder does not rely on any setting in the locations you specified.  Components of cmder may put stuff there but that is outside our control.

We are not going to do a portable installer version of cmder.  There is no need since it's a simple zip extraction.

**Comment by RoyiAvital** [comment]
@daxgames ,
I think you can handle the issue of component by changing the system variables.

Regarding @PortableApps, I don;t think looking at it as Portable Installer is the right way.
You can think of it as the package / application manager of Windows.

It will expose `Cmder` to many users who will enjoy it greatly in my opinion.

**Comment by RoyiAvital** [comment]
I created my own Portable Launcher with a file named `Cmder.cmd` with the following content:

```
@echo off
if not exist "%CD%\Config\AppData\Roaming" mkdir "%CD%\Config\AppData\Roaming"
if not exist "%CD%\Config\AppData\Local\Temp" mkdir "%CD%\Config\AppData\Local\Temp"
set USERPROFILE=%CD%\Config
set APPDATA=%CD%\Config\AppData
set TEMP=%CD%\Config\AppData\Local\Temp
set TMP=%CD%\Config\AppData\Local\Temp

start Cmder.exe /start D:\
```

It is not a perfect solution but at least it doesn't leave a mess after each run.

**Comment by daxgames** [comment]
@royiavital sorry but I dont understand ' but at least it doesn't leave a mess after each run.'  What mess and how does this prevent anything being left each run?

**Comment by RoyiAvital** [comment]
@daxgames , Have a look at [my post above](https://github.com/cmderdev/cmder/issues/1906#issuecomment-478576867).

When one run `Cmder` it leaves traces behind.
If someone wants a portable application one must make sure all data generated by the application is saved to the application folder.
This is what @PortableApps does (More elegantly and they can take care of Registry as well). My script above set System Environment variables so things are kept within `Cmder` folder.

**Comment by daxgames** [comment]
Yeah, I still dont get why the completely benign data you are trying to prevent matters enough to change things like `%temp%`, ` %appdata%`, `%userprofile%` to a folder that is not the user profile folder.

OR Why you care wht gets put in in `%temp%`, cmder does not put anything here.

OR that clink drops a meaningless log file in  `appdata\local\clink`

Seams like overkill for nothing.

Sorry, just my opinion.

**Comment by RoyiAvital** [comment]
It is a general script template I use. I didn't look into anything `Cmder` does (Or its components).

The rationale is simple the way I see it:
1. I want my Windows to behave like it is its first day after Installation even after 5 years of use.
2. I want to be able to wipe clean my OS drive, reinstall Windows and be able to start working within 5 minutes.

The way to achieve both is use only Portable Applications.
I use PortableApps and for applications which are not part of PortableApps I create some kind of a script to limit them.
I try to avoid applications that use registry.

**Comment by daxgames** [comment]
I see, we have all fought the battle of Windows performance degradation.  It is truly an admirable goal. :+1:
