### ISSUE TITLE
Quake style suggestions

### ISSUE THREAD

**Issue by HerelAdrastel** [cmderdev/cmder#1912]
Hi everyone,

I've just discovered the quake style and it's awesome !

I've however 2 suggestions to add:

Is it possible to add a shortcut to switch between quake style and windowed style ?
I've attached a background to Cmder and when I minimize/restore Cmder, the background blink to white for a fraction of seconds. It's really annoying :/

Otherwise, that's a wonderful project ;)

**Comment by daxgames** [comment]
This is a conemu question.  Best to report it to the conemu developer
