### ISSUE TITLE
Cmder issue in Windows 10

### ISSUE THREAD

**Issue by vpa24** [cmderdev/cmder#1913]
"C:\Users\Admin\Downloads\cmder\vendor\conemu-maximus5\ConEmu\Scripts;C:\Users\Admin\Downloads\cmder\vendor\conemu-maximus5;C:\Users\Admin\Downloads\cmder\vendor\conemu-maximus5\ConEmu;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Windows\System32;C:\Program Files (x86)\Yarn\bin;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs\;C:\Users\Admin\AppData\Local\Microsoft\WindowsApps;C:\Users\Admin\AppData\Local\atom\bin;C:\Program Files\Microsoft VS Code\bin;C:\Users\Admin\AppData\Roaming\Composer\vendor\bin;C:\Users\Admin\AppData\Local\GitHubDesktop\bin;C:\Users\Admin\AppData\Local\Yarn\bin;C:\Users\Admin\AppData\Roaming\npm;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\HashiCorp\Vagrant\bin;C:\composer;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Calibre2\;C:\wamp64\bin\php\php5.6.35;C:\Program Files\Git\cmd;C:\ProgramData\ComposerSetup\bin;"C:\wamp64\bin\php\php5.6.35;C:\ProgramData\ComposerSetup\bin";C:\Users\Admin\AppData\Local\Microsoft\WindowsApps;C:\Users\Admin\AppData\Local\atom\bin;C:\Program Files\Microsoft VS Code\bin;C:\Users\Admin\AppData\Roaming\Composer\vendor\bin;C:\Windows\System32;C:\Users\Admin\AppData\Local\GitHubDesktop\bin;C:\Users\Admin\AppData\Local\Yarn\bin;C:\Users\Admin\AppData\Roaming\npm;C:\Users\Admin\AppData\Local\Microsoft\WindowsApps;C:\wamp64\bin\php;"C:\ProgramData\Drush\;C:\Program Files (x86)\Drush\Php";C:\Users\Admin\AppData\Roaming\Composer\vendor\drush\drush;C:\wamp64\bin\mysql\mysql5.7.21\bin;"C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem";C:\WINDOWS\System32\Wbem;C:\wamp\bin\mysql\mysql5.5.24\bin";"|findstr >nul /I /R ";C:\\Program\ Files\\Git\\cmd\"$"
\Drush\Php";C:\Users\Admin\AppData\Roaming\Composer\vendor\drush\drush;C:\wamp64\bin\mysql\mysql5.7.21\bin;"C:\WINDOWS\system32 was unexpected at this time.

![cmder](https://user-images.githubusercontent.com/24423668/46918319-23d98900-cffb-11e8-8e15-99485591cc21.png)

**Comment by daxgames** [comment]
@vpa24 have you tried the latest unreleased [builds](https://ci.appveyor.com/project/MartiUK/cmder/build/artifacts)

**Comment by daxgames** [comment]
@vpa24 looks like your path variable has mismatched double quotes.  Look for `\Drush\Php"`

**Comment by daxgames** [comment]
closing, inactivity.
