### ISSUE TITLE
Question (Why does cmder not automatically exit when I execute some git commands?)

### ISSUE THREAD

**Issue by wqk317** [cmderdev/cmder#1915]
![image](https://user-images.githubusercontent.com/13175615/46924430-1b16a080-d057-11e8-908e-8f12ee1ea75a.png)

### Description of the issue 
As shown, when I execute some git commands (for example: git pull), I can't exit automatically. The cursor keeps flashing on the last line. I am sure the command has been executed.

**Comment by wqk317** [comment]
Even `Ctrl+c` doesn't work either, I can only force close this tab.

**Comment by wqk317** [comment]
![image](https://user-images.githubusercontent.com/13175615/46924601-0804d000-d059-11e8-94ac-3e64765bd82a.png)
Some other commands are the same

**Comment by daxgames** [comment]
@wqk317 use the commands you posted daily and have never seen this issue on several different systems.

**Comment by wqk317** [comment]
> @wqk317 I use the commands you posted daily and have never seen this issue on several different systems.

That may be the reason for my system, but what valid log can I provide?

**Comment by daxgames** [comment]
Closing due to lack of response from OP
