### ISSUE TITLE
W10 - problem on starting \conemu-maximus5\..\init.bat is not recognized

### ISSUE THREAD

**Issue by lamapidu** [cmderdev/cmder#1916]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 

Hi

I have seen some similar issues but not exactly the same.

So I have the version mini cmder Version 1.3.6.678
When I launch it (as Administrator), I got the following error:
```
\cmder_mini\vendor\conemu-maximus5\..\init.bat"' is not recognized as an internal or external command,
operable program or batch file.
```
![image](https://user-images.githubusercontent.com/28307637/46960435-7320c780-d096-11e8-933c-337b6c297c37.png)

This is usable but it doesn't load the ssh agent for example.

**What I have tried:**
I have also tried to download the full version and mini version from the official website.
Then I tried to download from the latest unreleased builds, and I got always the same problem

I am a very basic user of Cmder - just download and launch it but today it stopped working.

Please can you advice?

Many thanks

**Comment by daxgames** [comment]
@lamapidu Fresh install of upgrade?

**Comment by lamapidu** [comment]
@daxgames : on my mini-cmder I did an upgrade, and then I downloaded fresh installs from the official website and from the latest unreleased builds and launched it from the download folder.

Would it be better to try to remove/clean everything and download again?

Thanks

**Comment by daxgames** [comment]
I am not where I can look at it now but will look when I can and respond then.

**Comment by daxgames** [comment]
I am not where I can look at it now but will look when I can and respond then.

**Comment by lamapidu** [comment]
@daxgames many thanks for your time and help, let me know if you need more information or screenshots

**Comment by cosmicmarkup** [comment]
The same thing is happening to me. Been using Cmder for 2 years, but I'm encountering the same status message since yesterday.

**Comment by lamapidu** [comment]
It seems to be because of a windows 10 update, I tried on a computer without the last updates and it worked, then it did the updates and cmder gave me the error again.

**Comment by daxgames** [comment]
@lamapidu @cosmicmarkup Check that your antivirus is not quarantining `init.bat` when you extract the archive or run `cmder.exe`.  Does `%cmder_root%\vendor\init.bat` file exist after extraction or `cmder.exe` execution?

**Comment by lamapidu** [comment]
@daxgames You are totally right! I checked the extracted folder and the init.bat wasn't here but it was well into the archive.
This is really odd that I didn't have any notification that the antivirus removed it.
I use avast on this laptop and it seems that it removed it yes.
It works back to normal now!
Many thanks

**Comment by lamapidu** [comment]
@daxgames You are right!
It seems that my antivirus (avast on this laptop) removed the init.bat on the extracted archive,
It works back to normal now!
Many thanks

**Comment by lamapidu** [comment]
@daxgames You are right!
It seems that my antivirus (avast on this laptop) removed the init.bat on the extracted archive,
It works back to normal now!
Many thanks

**Comment by lamapidu** [comment]
@daxgames You are right!
It seems that my antivirus (avast on this laptop) removed the init.bat on the extracted archive,
It works back to normal now!
Many thanks

**Comment by fandyramadhan** [comment]
Many thanks

**Comment by hbweb** [comment]
> 
> 
> @lamapidu @cosmicmarkup Check that your antivirus is not quarantining `init.bat` when you extract the archive or run `cmder.exe`. Does `%cmder_root%\vendor\init.bat` file exist after extraction or `cmder.exe` execution?

I use AVG and it also quanrantined the init.bat file.. It works again after restoring the file. Many thanks

**Comment by tiago-84** [comment]
Pessoal boa noite, não possuo antivírus no sistema mas mesmo assim quando faço a extração dos arquivos e percebi que o init.bat não extrai. Será que o próprio windows não está permitindo?
por favor me ajudem!

**Comment by xax-git** [comment]
Still useful, quarantined init.bat caused the same symptoms. Avast was the source of the issue in my case as well.
