### ISSUE TITLE
Any roadmap?

### ISSUE THREAD

**Issue by SongRb** [cmderdev/cmder#1917]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Description of the issue 
Loving cmder, and looking forward to use and/or contribute to its next release. Is there a roadmap for features to implement and date to release new version?

**Comment by daxgames** [comment]
@SongRb Not sure we are that organized.  @Stanzilla Might disagree and be able to point you at something.

**Comment by Stanzilla** [comment]
We are pretty much not organized at all, most releases I did where based on if there was any cool change in git for windows or conemu

**Comment by SongRb** [comment]
Well, any useful resources if I would like to contribute to this repo?

**Comment by Stanzilla** [comment]
Pretty much https://github.com/cmderdev/cmder/blob/master/CONTRIBUTING.md and feel free to tackle any issue you want :)

**Comment by MartiUK** [comment]
cmder is quite mature, there could be more work to be done, perhaps moving away from conemu?

**Comment by Stanzilla** [comment]
I'd advise against that, also considering that @Maximus5 is working on porting it to use the new ConPTY api in Win10
