### ISSUE TITLE
Git Not working

### ISSUE THREAD

**Issue by moazam1** [cmderdev/cmder#192]
I have latest version cmder. When i try to ssh git it says permission denied (publickey). Here are the commands I am using:

> ssh-agent - s
SSH_AUTH_SOCK=/tmp/ssh-CCWsJB1728/agent.1728; export SSH_AUTH_SOCK;
SSH_AGENT_PID=8796; export SSH_AGENT_PID;
echo Agent pid 8796;

> ssh -T git@github.com  
Permission denied (publickey).  

I copied my .ssh folder into config folder and also put shortcut of .ssh folder but still not recognizing git ssh keys. Any help would be greatly appreciated.

Thanks

**Comment by kputtur** [comment]
Folks is this fixed ? I am facing exact same error as described above, any resolution?

**Comment by daxgames** [comment]
@trevorberman It works as expected for me.

In my `%cmder_root%\config\user_profile.cmd`:

```
:: uncomment this to have the ssh agent load when cmder starts
call "%GIT_INSTALL_ROOT%/cmd/start-ssh-agent.cmd" /k exit
ssh-add.exe ~/.ssh/ci-cd-testing.pem
```

Running `ssh-add -l` displays both identities as expected and `ssh -T git@github.com` works as expected also.
