### ISSUE TITLE
user-profile.ps1 is always executed twice

### ISSUE THREAD

**Issue by glucas** [cmderdev/cmder#1921]
I'm running cmder 1.3.6. 

While debugging an unrelated issue I added some logging to my user-profile.ps1 and found that it is being called twice any time I open a PowerShell tab in cmder. This looks fairly straightforward in profile.ps1 so not sure if it is intentional for some reason?

Here's the snippet from vendor/profile.ps1 which is sourcing $CmderUserProfilePath twice: 

    if (Test-Path $CmderUserProfilePath) {
        # Create this file and place your own command in there.
        . "$CmderUserProfilePath"
    }

    if ($ENV:CMDER_USER_CONFIG) {
        $CmderUserProfilePath = Join-Path $ENV:CMDER_USER_CONFIG "user-profile.ps1"
    }

    if (Test-Path $CmderUserProfilePath) {
        . "$CmderUserProfilePath"
    } else {

**Comment by daxgames** [comment]
This is fixed in latest unreleased [builds](https://ci.appveyor.com/project/MartiUK/cmder/build/artifacts).
