### ISSUE TITLE
Ctrl+C issue

### ISSUE THREAD

**Issue by gekap** [cmderdev/cmder#1923]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)

### Description of the issue 
when I do ssh username@server I connect normally on the server, then I do tailf /var/log/messages and when I press Ctrl+C it stop tailf but it show a heart (♥)

[user@server ~]# tailf /var/log/messages
Oct 23 09:37:55 cbsmtjfuuat2 audispd: node=server type=CRED_REFR msg=audit(1540276675.571:13827): pid=7014 uid=0 auid=0 ses=1248 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:setcred grantors=pam_faillock,pam_unix acct="user" exe="/usr/sbin/sshd" hostname=10.116.30.137 addr=ip_addr terminal=ssh res=success'
♥
[user@server ~]#

**Comment by daxgames** [comment]
See: https://github.com/cmderdev/cmder/issues/2034#issuecomment-473491038

**Comment by daxgames** [comment]
My previous comment was invalid.  I am not sure this is a cmder issue.  Have you tried the same with conemu portable edition.
