### ISSUE TITLE
Cmder input hangs or not accepted by console

### ISSUE THREAD

**Issue by ramlaxman** [cmderdev/cmder#1926]
### Purpose of the issue
- [X] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 

I haven't changed any settings of cmder. Still suddenly I started facing following issues.

Usign cmder version 1.3.6, facing issues:
1. After sometime of starting cmder, automatically it does not accept any input.
2. After one or two chars it started printing in search bar
3. Every time after pressing A it shows Affinity Processor option which is quite annoying.
4. Also, there is by default uncheck on 'change line prompt'.

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)

**Comment by ramlaxman** [comment]
I found new problem. No sooner I uninstalled Far Manager than cmder started working.
Quite strange but it worked.
