### ISSUE TITLE
The widths of lines are only half of the full window width

### ISSUE THREAD

**Issue by andys0975** [cmderdev/cmder#1927]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 

![image](https://user-images.githubusercontent.com/21152737/47567397-01336280-d961-11e8-8e31-d51fc12b59f5.png)

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)
