### ISSUE TITLE
Environment settings not persisted when blank line present

### ISSUE THREAD

**Issue by ostrolucky** [cmderdev/cmder#1929]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue

Settings -> Startup -> Environment:
Use following, hit save, reopen cmder and check if settings are persisted.

Following works:
``` 
set PATH=%ConEmuBaseDir%\Scripts;%PATH%
set LANG=en_EN.utf8
```

Does not work:
```
set PATH=%ConEmuBaseDir%\Scripts;%PATH%

set LANG=en_EN.utf8

```

Cannot reproduce in standalone ConEmu

**Comment by daxgames** [comment]
Report this to conemu dwveloper
