### ISSUE TITLE
How to enable ssh-agent?

### ISSUE THREAD

**Issue by CaseyLabs** [cmderdev/cmder#193]
I'm trying to setup Cmder to use ssh-agent forwarding:

λ ssh-agent
SSH_AUTH_SOCK=/tmp/ssh-JqBCMa6092/agent.6092; export SSH_AUTH_SOCK;
SSH_AGENT_PID=7840; export SSH_AGENT_PID;
echo Agent pid 7840;

λ ssh-add my-public-key.pub
Could not open a connection to your authentication agent

Any ideas what I'm doing wrong here?

Thank!

**Comment by cdelgehier** [comment]
It is working for me but the agent forwarding is not good
How to export SOCK and  PID variable?

**Comment by cdelgehier** [comment]
With your script @teleivo and http://niki.hammler.net/wiki/PuttyAgent_now_supports_openssh/cygwin/msys 
I am a satisfied man

**Comment by IrNoThnk** [comment]
has anyone successfully had confirmation with ssh-add working?

ssh-add -c /path/to/key

Adding is no problem, but you'll get a failure when connecting because there is no /usr/libexec/ssh-askpass. At least that's the issue that I've had in Ubuntu before.

**Comment by isdsc** [comment]
I am currently using `start-ssh-agent` script [provided by msysgit](https://github.com/msysgit/msysgit/blob/master/cmd/start-ssh-agent.cmd) to set up my ssh-agent in cmder (it is in the default cmder search path: %git_install_root%\cmd\). Is there any reason to switch to the one added to the [development branch](https://github.com/bliker/cmder/blob/development/bin/agent.cmd)?

**Comment by markwint** [comment]
@isdsc any idea how to make it enable agent forwarding?

**Comment by isdsc** [comment]
@markwint if the question is how `start-ssh-agent` works with agent forwarding, the answer is (AFAIK):
> It just starts `ssh-agent` properly in your session [in Windows console] and adds the default identity, it doesn't deal with agent forwarding.

Here is my ssh configuration:

```
λ head ~/.ssh/config
# Shortcut to connect to my server
Host mysvc
 User MyName
 IdentityFile ~/.ssh/id_rsa
 HostName myservice.example.com

# GitHub account: isdsc
Host github.com
 IdentityFile ~/.ssh/isdsc
 HostName github.com
```

Here is how I use agent forwarding with a second identity to connect to GitHub. See [GitHub](https://developer.github.com/guides/using-ssh-agent-forwarding/) for details.

```
λ start-ssh-agent
Removing old ssh-agent sockets
Starting ssh-agent: done
Enter passphrase for /c/Users/MyName/.ssh/id_rsa:
Identity added: /c/Users/MyName/.ssh/id_rsa (/c/Users/MyName/.ssh/id_rsa)

λ ssh-add ~/.ssh/isdsc
Enter passphrase for /c/Users/MyName/.ssh/isdsc:
Identity added: /c/Users/MyName/.ssh/isdsc (/c/Users/MyName/.ssh/isdsc)

λ ssh -T git@github.com
Hi isdsc! You've successfully authenticated, but GitHub does not provide shell access.
```

However, just to make sure I understood what agent forwarding means, I googled it and found another explanation: http://www.unixwiz.net/techtips/ssh-agent-forwarding.html#fwd

If your question is about this second interpretation, I don't know how to respond to your question because:

1. I don't know the specifics of your situation.
2. I don't think I have used ssh in that way (unless that's what's going on behind the scenes when I connect to GitHub).

**Comment by airtonix** [comment]
@isdsc regarding 2. no. it is not. if you've never chained ssh tunnels together then you've never used agent-forwarding.

**Comment by SpacemanPete** [comment]
@teleivo, your option seems to be the one that would fit my eneeds best, but I get an error that >'pageant' is not recognized as an internal or external command, operable program or batch file.<

even though the %PATH% has my "C:\Users\<Myusername>\.ssh" location listed in there...

I edited the pageant_autostart.cmd file to list the full explicit path to pageant.exe and it works but i'm puzzled why cmder can't find pageant...

**Comment by kud** [comment]
I'm using `@call "%CMDER_ROOT%/bin/agent.cmd"` but it doesn't work here.

```
  0 [main] ssh-agent xxxx open_stackdumpfile: Dumping stack trace to ssh-agent.exe.stackdump
Could not open a connection to your authentication agent.
Could not open a connection to your authentication agent.
```

Any idea?

**Comment by OleksiiShevchenko** [comment]
Thanks, works great!

**Comment by NitroBAY** [comment]
For futur people the equivalent to linux's eval seems to be call so to call ssh-agent it would be `call %GIT_INSTALL_ROOT%/cmd/start-ssh-agent.cmd`

**Comment by jocafi** [comment]
I noticed that I had to start the Windows service "OpenSSH Authentication Agent". I think this advice may help some solution here to work, specially the solution from @bojanrajkovic .
In my case, after putting his Gist in the CMder settings, I had only to execute the command "ssh-add.exe" in the CLI. If I add optional arguments like "ssh-add.exe %HOME%\.ssh\id_ed25519" , it does not work.

**Comment by Mooninaut** [comment]
The latest version of `start-ssh-agent.cmd` seems to open a `cmd` shell with the arguments provided to it on the command line, which was giving me a shell with no Cmder magic. I changed my default `{cmd::Cmder}` task to run `"C:\Program Files\Git\cmd\start-ssh-agent.cmd" /k ""%ConEmuDir%\..\init.bat" "` and that worked for me.

**Comment by renandecarlo** [comment]
For some reason either ssh-agent or ssh-pageant is working for me. It asks for password on startup, but then it asks again when I ssh to a server.
