### ISSUE TITLE
How to turn off the "Create New Console" dialog ?

### ISSUE THREAD

**Issue by mithuns** [cmderdev/cmder#1941]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Description of the issue 

Each time when I do Ctrl + T, to open a new tab, I am wondering if there is any setting to turn off that new tab dialog. I fixed my preferences the first time and there should be a check-box that remembers those settings and just apply the next time I open a new tab. 
Any suggestions ? Or Am I missing something ?

**Comment by daxgames** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)
