### ISSUE TITLE
'C:\Program' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by garthmountain** [cmderdev/cmder#1943]
My installed Cmder has been working perfectly for over a year on my machine, I use it every day, all day to run my Angular apps, however, this morning when opening it I get the above error message.

I did see a previous ticket that says that you should install it on the desktop iso Program Files... but why would it suddenly start giving this error after a year of operating perfectly?

**Comment by daxgames** [comment]
@garthmountain I don't know.  What version are you using?  

Did you make any changes?

What folder is it installed in?

**Comment by Happin3ss** [comment]
@daxgames : I face the same issue and cannot open my ssh task. My cmder folder was put inside "C\...\Google Drive\" - This one have space in path and I think It's problem.
Is there any  workaround available for this one ?
Thank you for help

**Comment by garthmountain** [comment]
@daxgames v1.3.2
What I did to resolve this...
- Deleted the version I had in c:/program files
- Re-extracted my original download zip to c:/cmder (it started working at this point)
- Ran the update to the latest version

All good now.
MAny thanks for the help.
