### ISSUE TITLE
Error when entering an SVN repo directory with [ ] characters

### ISSUE THREAD

**Issue by pizza2code** [cmderdev/cmder#1944]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)

### Description of the issue 
When entering an SVN repo directory that contains the square bracket characters [ ], I see an "invalid capture index" error:

![cmder - invalid capture index bug](https://user-images.githubusercontent.com/15824044/48221791-fdd8a780-e360-11e8-8866-922508a24989.png)

The clink.lua file appears to be a Cmder script that interfaces with clink, rather than source belonging to clink itself.  The file is hosted in this GitHub repo.

This issue is similar to, but not the same as, https://github.com/cmderdev/cmder/issues/1629

Cmder version 1.3.6

**Comment by Stanzilla** [comment]
So did you try with a recent nightly build as well?

**Comment by pizza2code** [comment]
Where would I find the nightly builds?  After scouring the site and reading all the way through the readme, the only thing I could find to download is AppVeyor logs.

**Comment by pizza2code** [comment]
I also tried to look for build instructions, but could find none.  And Cmder.bat -- which I suspect is supposed to build -- returns an error `The system cannot find the file C:\My.`

**Comment by Stanzilla** [comment]
On the artifacts tab on appveyor, https://ci.appveyor.com/project/MartiUK/cmder/builds/20031234/artifacts for example

**Comment by daxgames** [comment]
@Stanzilla I'm thinking it might be time for 1.3.7 release.  We've fixed a lit since 1.3.6

**Comment by Stanzilla** [comment]
Yeah we really should

**Comment by daxgames** [comment]
I have done some testing with it.  The main thing I tested was detailing with the `.gitignore` and is it right.

No other real changes other than koving the default conemu.xml file.  I have not tested that but it was a simple path change.  I'll do some testing I the morning and comment on the pr.

**Comment by daxgames** [comment]
@pizza2code have you tried a nightly build or the latest release?  Please update this issue with your findings.

**Comment by daxgames** [comment]
@pizza2code Still an issue?  If not please close else we will close after one more attempt to get status.

**Comment by pizza2code** [comment]
@daxgames Unfortunately, this still appears to be an issue.  The error is silenced, but the prompt still loses its Cmder features:

![image](https://user-images.githubusercontent.com/15824044/49409353-47cd6700-f72e-11e8-92a0-ef7ef2e53ac2.png)

Tried both the latest release and the most recent build ( from https://ci.appveyor.com/api/buildjobs/do3c27axgymov335/artifacts/build%2Fcmder.7z ).
