### ISSUE TITLE
PC use utf-8 code and  chinese language show with differnt 

### ISSUE THREAD

**Issue by TinaAlreadyLose** [cmderdev/cmder#1950]
## problem
when i input chinese laguage, there is some problems in  font-spacing ,it's to large and i don't know how to solve it. You konw it's hard for a programer to describe a question clearly.And I;;; show you this problems in by pothos ,can you give me some suggestion. thank you very much
##     picture

the ping of github 100% time out ,oh my god , I'm ....................

**Comment by daxgames** [comment]
@TinaAreadyLose does @Malcn suggestion help you?  if so please close this issue.
