### ISSUE TITLE
Glob with backslashes in emulated commands does not work

### ISSUE THREAD

**Issue by baflo** [cmderdev/cmder#1952]
Unix commands currently don't work when using backslashes:

```
λ cp config\locales\en\*.json config\locales\de
cp: cannot stat 'configlocalesen*.json': No such file or directory
λ ls config\locales\*
ls: cannot access 'configlocales*': No such file or directory
```

With slashes it works, however:

```
λ cp config/locales/en/*.json config/locales/de
λ ls config/locales/*
config/locales/de:
translation.json

config/locales/en:
translation.json
```

**Comment by daxgames** [comment]
Then use '/'.  This is not a `Cmder` issue.  The `*nix` commands are a part of `Git for Windows`.  `\` in `*nix` is an escape character so this is expected behavior.

**Comment by andypillip** [comment]
Then autocomplete should be considered broken. It's suggesting \, which then leads to an error.
