### ISSUE TITLE
The input command's first word not clear by console

### ISSUE THREAD

**Issue by magicdmer** [cmderdev/cmder#1953]
### Versions
cmder ：1.3.2
ConEmu build: 161206 stable x64
OS version: Windows 7 x64 chinese
mode：cmder default cmd

### Problem description
1. because problem is strange, so i put gif picture to explain it. the first word can't be deleted by backspace.but the first word has no impact on other command
2. other console is ok, like windows cmd, powershell , msys2 ...
[screenshot](https://i.imgur.com/2qnGSiI.gif)

### Steps to reproduce
1. input any command 
2. press up to view history command
3. the first word not clear by console and can't be deleted

**Comment by daxgames** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)

**Comment by magicdmer** [comment]
No, I open a bug over at Conemu, but i test ConEmu without cmder, all is ok, and the maintainer said ,it's cmder's question

**Comment by magicdmer** [comment]
I upload a gif to compare to ConEmu
[screenshot](https://imgur.com/a/v2Hq3g9)

**Comment by kicoliu** [comment]
Try to change prompt "λ" to "$" or other character.
see https://gist.github.com/vamdt/6f7a83a68334504b2f2bef07e6b7936f

**Comment by daxgames** [comment]
A better approach to fixing this would be to add a file called `dollar_prompt.lua` to `cmder_root%\config\`

```
function my_prompt_filter()
    cwd = clink.get_cwd()
    prompt = "\x1b[1;32;40m{cwd}{git}{hg}\x1b[1;30;40m{lamb} \x1b[0m"
    new_value = string.gsub(prompt, "{cwd}", cwd)
    clink.prompt.value = string.gsub(new_value, "{lamb}", "$")
end

clink.prompt.register_filter(my_prompt_filter, 1)
```

This will survive upgrades where other suggested solutions will not.

**Comment by magicdmer** [comment]
> Try to change prompt "λ" to "$" or other character.
> see https://gist.github.com/vamdt/6f7a83a68334504b2f2bef07e6b7936f

thank you , daxgmaes's lua script is more convenient, it solves my question,  you can try it too.
