### ISSUE TITLE
SSH DietPi menu infinite refresh

### ISSUE THREAD

**Issue by Sk1pp3r** [cmderdev/cmder#1954]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 
I've searched through issues, and it seems noone has stumbled upon it. Moreover, I'm not sure if it's `cmder` issue, or `ComEmu`'s which is used by it.

Whenever I connect to a machine through `SSH` to a macine that has **DietPi** on it, and enter one of the DietPi menu's (which have options to select and a blue background), `cmder` starts to "infinitely refresh", so that the only thing you see in it is a blue screen (without the text or or anything being seen).
This kind of issue is **not** present in Windows' `CMD` or Linux `terminal`, however in Windows' `CMD` the background might change from black to blue when entering DietPi menu's and exitting back to simple CMD view.

Steps to reproduce:
1. have a machine (virtual will do) with DietPi installed (latest version or any other)
2. SSH into the machine
3. enter any `dietpi-*` command (for example `dietpi-config`)
4. navigate through that menu; the unreadable `cmder` refresh will trigger at some point (not from the very beginning)

Help is appreciated :slightly_smiling_face:

**Comment by Technetium1** [comment]
This caused me to have to reinstall from a failed upgrade. I'm completely done using cmder until this is fixed. This has been one of the most rage-inducing bugs I've _**ever**_ run into.

**Comment by daxgames** [comment]
@Technetium1 Cmder is the terminal emulator Cmder uses and it is responsible for rendering any text/graphics in a session.  Does this happen when using ConEmu outside Cmder?

I don't see how this could be a Cmder issue.

**Comment by Technetium1** [comment]
@daxgames Thanks for the reminder. I just checked the latest conemu alpha and it's still broken there. Not an issue with cmder specifically.

**Comment by daxgames** [comment]
@technetium1

**Comment by Sk1pp3r** [comment]
@Technetium1 There is a workaround... Something related to deleting OpenSSH from Windows Apps, and that seemed to have worked...

**Comment by daxgames** [comment]
That may be a little heavy handed.  You can tell the cmder task to prefer the *nix tools by modifying the task that launches cmder.  See: [/nix_tools] in the readme.(https://github.com/cmderdev/cmder#command-line-arguments-for-initbat)

**Comment by Technetium1** [comment]
That is not a valid workaround. I removed the Windows version as soon as I reinstalled the OS last, and I constantly use the newest OpenSSH via Chocolatey; this can't be the right way to solve this.

**Comment by daxgames** [comment]
@Technetium1 so you are installing cmder(full or mini)?  I ask because full includes Git Bash that includes ssh client that is probably openssl. And you are installing open ssh via chocolaty and windows includes ssh.  Hopefully you are running the one you think you are running based on your path setup.

What is the output of `where ssh`  if the suggestion to delete the ssh included in windows does indeed fix the problem then you may be using it and not the one you are installing via chocolaty and not the one in cmder full.

**Comment by Technetium1** [comment]
@daxgames I was using mini. I installed OpenSSH from Chocolatey, and I removed the SSH feature from Windows. I am certain it was the correct executable being run.
