### ISSUE TITLE
Cmder opens after a program is closed in guake style mode

### ISSUE THREAD

**Issue by ghaffarinia** [cmderdev/cmder#1955]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 

I am using cmder in windows 10 in guake style mode. Most of the time when I open a window and close it then cmder terminal drop down while I did not use the hotkey. Please kindly let me know how should I get the log so that I can report it here if you want.

**Comment by daxgames** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)
