### ISSUE TITLE
Numpad writes ' Î ' in vim

### ISSUE THREAD

**Issue by Tx0n** [cmderdev/cmder#1957]
### Purpose of the issue
- [ x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 
Hello, I'm using vim in cmder, and I have a problem with the numpad. When I type a number (anyone), it writes ' Î ' and i'm not able to write numbers with the numpad. I tried a lot of different things, but none worked. What could I do to solve that ?

Thank you

**Comment by cognivore** [comment]
Same issue
