### ISSUE TITLE
The git code hint is not comprehensive enough

### ISSUE THREAD

**Issue by linjialiang** [cmderdev/cmder#1958]
> The git code hint is not comprehensive enough

**Comment by daxgames** [comment]
What dies that mean?  What is the issue?

**Comment by linjialiang** [comment]
> Could you fill in some !
> Your cmder is better than git bash, and I'm using cmder pretty much all the time now, but the gti command isn't enough
> I think cmder is great, it's just one of my functional requirements, and I'll continue to use cmder even if you don't add more git commands

**Comment by linjialiang** [comment]
![default](https://user-images.githubusercontent.com/8848263/48680723-c5df2900-ebd8-11e8-941c-98b2c41a8382.png)

> This name cannot be completed automatically on cmder
