### ISSUE TITLE
Start cmder "find" errors

### ISSUE THREAD

**Issue by EnzoAkira** [cmderdev/cmder#1959]
Hello guys!!
I am using cmder for a couple of days and I'm having this weird errors every time I start cmder:
![cmder_error](https://user-images.githubusercontent.com/39481527/48709609-f1283f00-ebfd-11e8-99e1-0c856c3451ff.png)

FYI I unzip it into my C:\Users\user\cmder and I'm using Win 10

**Comment by cokelly** [comment]
Same issue here on Win 10. The message is:

```
find: '/i': No such file or directory  
find: ' ': No such file or directory  
find: '/i': No such file or directory  
find: '\\cmd.exe': No such file or directory  
find: '/i': No such file or directory  
find: '\\tcc.exe': No such file or directory  
find: '/i': No such file or directory  
find: '\\tccle': No such file or directory
```

The issue persists in the current development version (`7f534290`) on Appveyer.

**Comment by EnzoAkira** [comment]
Hi @cokelly!
Do you have any clues what might be?
I searched in init.bat and nothing. but on file cmder\vendor\lib\lib_base.cmd in lines 64-66 are related with the messages we received, so the cmder it's using "find" from Windows\System32 instead of "find" from built-in because 'find' on windows doesn't recognize "/i" parameters. This is my opinion, please devs if I am wrong correct me :)

**Comment by cokelly** [comment]
You've done a better diagnosis job than me @EnzoAkira! I had got as far as lib_base.cmd being new compared to version 1.3.6, but no further.

**Comment by EnzoAkira** [comment]
Hello @daxgames!

> Don't use tcc.exe as %comspec%

I was analyzing lib_base.cmd file and I found this workaround:
Comment this lines:
`echo %comspec%| find /i "\tcc.exe" > nul && set "CMDER_SHELL=tcc"`
`echo %comspec%| find /i "\tccle" > nul && set "CMDER_SHELL=tccle"`

I even made the change to this line:
`echo %comspec%| find /i "\cmd.exe" > nul && set "CMDER_SHELL=cmd"`
to 
`set "CMDER_SHELL=cmd"`

@daxgames 
**Is there another way to specify not to use tcc.exe as %comspec%?**

For now cmder it's working.

Thank you for your input 

BTW, It's been very pleasant to work with cmder on Windows!!! Great work!

**Comment by DanielChesters** [comment]
I have the same problem (on Windows 7) and I think I have a solution : 

Replace all 
`echo %comspec%| find /i "\tcc.exe" > nul && set "CMDER_SHELL=tcc"`
`echo %comspec%| find /i "\tccle" > nul && set "CMDER_SHELL=tccle"`
`echo %comspec%| find /i "\cmd.exe" > nul && set "CMDER_SHELL=cmd"`
by
`echo %comspec%| %WINDIR%\System32\find /i "\tcc.exe" > nul && set "CMDER_SHELL=tcc"`
`echo %comspec%| %WINDIR%\System32\find /i "\tccle" > nul && set "CMDER_SHELL=tccle"`
`echo %comspec%| %WINDIR%\System32\find /i "\cmd.exe" > nul && set "CMDER_SHELL=cmd"`

If I have time tonight, I will do a PR to fix the error.

**Comment by DanielChesters** [comment]
> `echo %CMDER_USER_FLAGS% | find /i "%feFlagName%">nul`

You can replace this by `echo %CMDER_USER_FLAGS% | %WINDIR%\System32\find /i "%feFlagName%">nul`

The main issue here is in some case you use a "Unix" find (from a Unix tools installation in your system) instead of the windows find command so I think the best solution is to force use the system find instead the find command from path.

**Comment by daxgames** [comment]
@DanielChesters Nice catch! Looking forward to the PR.

**Comment by EnzoAkira** [comment]
Hello guys!
Nice tip @DanielChesters! 
I would add in changing all `findstr` to `%WINDIR%\System32\findstr` , I also get this error.

**Comment by cokelly** [comment]
Thanks all: adding `%WINDIR%\System32\` before find and findstr across all `*.cmd` in the vendor folder worked perfectly.

**Comment by DanielChesters** [comment]
@EnzoAkira : I have to create the PR to send the fix, I think it is better to have the issue open until I have sent the PR.
