### ISSUE TITLE
Git syntax highlighting similar to iTerm2 + Solarized

### ISSUE THREAD

**Issue by arunpkqt** [cmderdev/cmder#1962]
Is there already a theme of configuration available to make cmder show Git related changes similar to iTerm2 + Solarized as shown below.

![image](https://user-images.githubusercontent.com/4667704/49099276-55d44100-f271-11e8-8136-e75a8df82411.png)

**Comment by daxgames** [comment]
There is a powerline lua that works with cmder.   [cmder-powerline-prompt](https://github.com/AmrEldib/cmder-powerline-prompt)

Not sure it does exactly what you want but it does support git repo status.

**Comment by daxgames** [comment]
I am also a heavy mac user and use item2 and polarized.  I have not been able to successfully duplicate solarized color scheme in cmder that I am happy with.

**Comment by arunpkqt** [comment]
@daxgames Thanks for the info. It worked as expected with cmder..
