### ISSUE TITLE
Running .cmd for SSH agent and putty integration

### ISSUE THREAD

**Issue by tomasorti** [cmderdev/cmder#1963]
Hi.
I am trying to integrate what is described here:
https://github.com/cmderdev/cmder/wiki/Integrate-SSH-Agent-or-PuTTY-Agent

But when I do that (uncommenting the lines in current `config/user-profile.cmd`), when cmder starts, it misses colors and it is like it goes back to traditional CMD prompt.
Same as executing manually the first .cmd like this:

![capture](https://user-images.githubusercontent.com/2485147/49154511-d26e2a80-f318-11e8-8ca1-9d4872550c79.PNG)
![capture2](https://user-images.githubusercontent.com/2485147/49154516-d4d08480-f318-11e8-9de7-423cee73203b.PNG)

I expected it would _source_ the .cmd script without breaking the cmder prompt, etc...
Is this supposed to go back to CMD? Is this the way it is supposed to run?
How can I run those without changing it?

Regards.

### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [X] Question

**Comment by tomasorti** [comment]
Shouldn´t `call` execute the .cmd file seamlessly?

**Comment by daxgames** [comment]
I just uncommented:

```
:: uncomment this next two lines to use pageant as the ssh authentication agent
SET SSH_AUTH_SOCK=/tmp/.ssh-pageant-auth-sock
call "%GIT_INSTALL_ROOT%/cmd/start-ssh-pageant.cmd"
```
and got the below in my next session:

```
Starting ssh-pageant...
SSH_AUTH_SOCK='/tmp/.ssh-pageant-auth-sock'
SSH_PAGEANT_PID=18156

C:\Users\user\cmderdev(master -> origin)$
```

All is working as expected.

**Comment by daxgames** [comment]
@tomasorti maybe your user-profile is from an older version of Cmder.  The commands I uncommented ore different than yours.

**Comment by tomasorti** [comment]
This is the content of current `user_profile.cmd` on cmder version 1.3.8 is:

```
:: use this file to run your own startup commands
:: use in front of the command to prevent printing the command

:: uncomment this to have the ssh agent load when cmder starts
:: call "%GIT_INSTALL_ROOT%/cmd/start-ssh-agent.cmd"

:: uncomment the next two lines to use pageant as the ssh authentication agent
:: SET SSH_AUTH_SOCK=/tmp/.ssh-pageant-auth-sock
:: call "%GIT_INSTALL_ROOT%/cmd/start-ssh-pageant.cmd"

:: you can add your plugins to the cmder path like so
:: set "PATH=%CMDER_ROOT%\vendor\whatever;%PATH%"

:: arguments in this batch are passed from init.bat, you can quickly parse them like so:
:: more useage can be seen by typing "cexec /?"

:: %ccall% "/customOption" "command/program"

@echo off
```
The command that gets executed first is the `ssh-agent` cmd file:
`call "%GIT_INSTALL_ROOT%/cmd/start-ssh-agent.cmd"`
That is the one that makes the colors gone and shows the traditional CMD prompt.

**Comment by daxgames** [comment]
@tomasorti Have a look at #1807 and #1781.  From what I saw #1781 was best.

**Comment by daxgames** [comment]
@tomasorti - Just a little more info.

`%GIT_INSTALL_ROOT%/cmd/start-ssh-agent.cmd` is provided by the Git for Windows Package that Cmder uses.  It is not maintained by us and thus can't be fixed by us.
