### ISSUE TITLE
/START command line argument does not work

### ISSUE THREAD

**Issue by gwarnants** [cmderdev/cmder#1964]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue
I'm using version 1.3.8.793

When I try to open Cmder.exe with the /START command line argument to open in a specific folder, Cmder always open in the default folder (%USERPROFILE%).

No error message, just the command line argument seems to be ignored.

On the other hand, if I try to open to a non-existing folder, I get a window dialog saying "_Folder does not exist!_", which is correct.

**Comment by daxgames** [comment]
Did you upgrade from a previous version?  Press <kbd>Win</kbd>+<kbd>Alt</kbd>+<kbd>t</kbd> and change the command line in the `{cmd::Cmder}` task to:

```
cmd /k ""%ConEmuDir%\..\init.bat" "
```

**Comment by daxgames** [comment]
@gwarnants the `/start [path]` switch works for me.

**Comment by gwarnants** [comment]
Hello, yes I upgraded from 1.3.1
I changed the task and it's working now.
Don't know why, but my command was :

`cmd /k "%ConEmuDir%\..\init.bat"  -new_console:d:%USERPROFILE%`

Thanks

**Comment by daxgames** [comment]
Cmder used to force `%userprofile%`.  We don't do that any more .  That piece of config is written by us exactly one time, when you install/run cmder the first time.  Then we never touch it again.  You had the cmder 1.3.1 default task list.

Glad it's working now.
