### ISSUE TITLE
Second line of Powershell prompt incorrectly placed

### ISSUE THREAD

**Issue by sql-sith** [cmderdev/cmder#1965]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 

I am using ConEmu 180626 on Windows 10 Enterprise Edition 1709 (I can't upgrade Windows to a newer build per IT policy). 

I love ConEmu - thank you to everyone who works on it! I have one issue that I think has been discussed before but I can't find any resolution that makes sense to me. Basically, sometimes when returning to ConEmu from another app, my prompt is not displayed properly. I use a two-line prompt, and sometimes the second line is displayed far to the right. The blinking cursor is at the lower-left, where I would expect it, but the characters I type show up right after the second line of the prompt. It's hard to explain but easy to see, so here's a sample. It has the end of the output of the previous command, which was `dir` (for the very observant: this is using an alias that invokes the `cmd` version of `dir`, not `Get-ChildItem`). Then it shows the two-line prompt, and then the next command I executed (`sqlcmd`). Finally, it shows the first thing `sqlcmd` displayed. 

You actually have to scroll to the right to see where the prompt was and where I typed the `sqlcmd` command. Notice that it is on the same line as the first part of the prompt, so it looks like a newline is getting lost somewhere. And again, this only seems to be an issue when I come back to `cmder`. It could possibly be related to resizing the window, but I haven't been able to verify or disprove that.

```
 Directory of C:\Users\cleonard\Dropbox\jdbc\Microsoft JDBC Driver 6.0 for SQL Server\sqljdbc_6.0\enu\xa\x86

01/17/2017  10:44 AM           169,800 sqljdbc_xa.dll
               1 File(s)        169,800 bytes

     Total Files Listed:
              16 File(s)     10,458,104 bytes
               2 Dir(s)  516,450,955,264 bytes free
C:\Users\cleonard\Documents\GitHub\
C:\Users\cleonard\Documents\GitHub\                                                                                                    λ  sqlcmd -S .\SQL2017

1>
```

Does anyone know why this happens or how to prevent it? I don't know if this is an issue with my `cmder` config or with something in `ConEmu` so I am just stuck at this point and any advice is appreciated.

**Comment by daxgames** [comment]
@sql-sith I have not seen this behavior.

**Comment by sql-sith** [comment]
I believe you! But I have seen it on multiple laptops. I can't be the only person - in fact, as I mentioned before, I once found other discussions about this but they were not resolved. It seems like something we should be able to track down and get fixed. Do you have any suggestions that would help us do that, @daxgames (or anyone else)?

**Comment by daxgames** [comment]
@sql-sith So you are running a Powershell session in `Cmder` and have created a Powershell alias/function called `dir` to run the `cmd.exe` internal command `dir`?

1. How did you do that?  `function dir() {cmd /c dir $args}`

This is what I get:

```
C:\Users\user\cmder dev [ps1_prompt]
λ  del alias:dir
C:\Users\user\cmder dev [ps1_prompt]
λ  function dir() {cmd /c dir $args}
C:\Users\user
λ  dir ".\Dropbox\jdbc\Microsoft JDBC Driver 6.0 for SQL Server\sqljdbc_6.0\enu\xa\x86"
 Volume in drive C is Windows
 Volume Serial Number is BE6A-E4D2

 Directory of C:\Users\user\Dropbox\jdbc\Microsoft JDBC Driver 6.0 for SQL Server\sqljdbc_6.0\enu\xa\x86

03/16/2019  06:06 PM    <DIR>          .
03/16/2019  06:06 PM    <DIR>          ..
09/16/2018  04:36 PM             3,117 git_prompt.lua
               1 File(s)          3,117 bytes
               2 Dir(s)  362,287,190,016 bytes free
C:\Users\user
λ   cat .\test.ps1
param (
     [string]
     $Config = $null
)
"Config = $Config"
C:\Users\user
λ
```

Seems to work for me.

**Comment by sql-sith** [comment]
Hey @daxgames. This doesn't seem to have anything to do with what commands I'm using. What happens is that after I've switched to other apps and later give focus back to cmder, the prompt will be way over to the right, as you can see from my un-edited copy/paste in the OP. (Of course, you have to scroll to the right to see the mis-placed prompt). When this happens, the cursor actually displays (blinks) where it should, so some portion of cmder/conemu knows where it should be. But what I type appears after the mis-placed prompt.

I will try to see if I can get a repro for this. It happens to me almost every day, so it's either a bug or something in my config that's just not right. It also happens on 2 different laptops.

**Comment by daxgames** [comment]
It is a very unique problem and it did try the switch away and back and had no issues like you reported.

**Comment by sql-sith** [comment]
I can reproduce the issue now but I'm on call this week. I'll try to
remember to post back next week when life is a little more sane.

**Comment by sql-sith** [comment]
OK, this is what I've been able to reproduce. I have one laptop running ConEmu 180626 (preview) that displays this problem and another running ConEmu 180206 (stable) that does not. 

It's actually easy to repro the problem on the 180626 machine. Read the following like keyboard pseudocode.

**Scenario 1**
- start with maximized ConEmu running Powershell
- double-click the title bar to toggle (restore) to a smaller Window size
- type something (I chose to type "ls")

This is what happens:
```
C:\Users\cleonard
λ
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 1 Keys:
 l

Exception:
System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Array destinationArray, Int32 length)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)

   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
C:\Users\cleonard
λ  ls
```
(My prompt begins with 'C:' and ends with 'λ '.)

**Scenario 2**
- start with non-maximized ConEmu running Powershell
- double-click the title bar to toggle (maximize) to a full-screen Window
- type something (I again chose to type "ls")

This is what happens:
```
C:\Users\cleonard                                                                  λ  ls
```
In case it wraps, that last one is all on one line.

So it looks like this is a possible regression between 180206 and 180626. I am going to install a newer preview release and see if the problem is still there. If not, problem solved. If it is, that's a problem, and in that case I will install 180206 (stable) and see if that fixes the issue. If it does, there is a problem in the preview builds that was not in 180206. If it does not, then it's something specific to my environment. I'll keep you posted.

**Comment by sql-sith** [comment]
OK, so I installed 190331 preview. Things are better, but not perfect. This is with all the default settings using the "small" installer (without the git tools).

Now, this is what happens:

If I repeat the test in **Scenario 1** above, when I toggle/restore the window, the prompt jumps up some number of lines on the screen, often with previous output displayed beneath the prompt. Here is an example (notice that the prompt is in the middle of the previous `ls` output).
```
-a----       11/20/2017   5:37 PM          19070 dbo.raa_ContactVerificationAdd_sp.prc
-a----       11/20/2017   5:37 PM           8166 dbo.raa_contactVerificationEmailQueueGetProcessAttempt_sp.prc
-a----       11/20/2017   5:37 PM           6796 dbo.raa_contactVerificationEmailQueueGetUnprocessed_sp.prc
-a----       11/20/2017   5:37 PM           8139 dbo.raa_contactVerificationEmailQueueInsert_sp.prc
-a----       11/20/2017   5:37 PM           9812 dbo.raa_contactVerificationEventScan_sp.prc
-a----       11/20/2017   5:37 PM           4616 dbo.raa_contactVerificationShopperMergeUpdate_sp.prc
-a----       11/20/2017   5:38 PM           7967 dbo.raa_shopperMergeFix_sp.prc > ls

-a----        1/22/2009   1:13 PM           7296 OneNote Table Of Contents.onetoc2
-a----         3/6/2019   5:32 PM             13 readme.txt
-a----        12/7/2017   7:57 PM              8 text.txt
-a----         2/7/2008   7:13 PM            137 vssver2.scc



[LTTC-3QN8RF2] code:\daily\2019\04\03\css
>
```

**Scenario 2** above seems to be fixed for me.

I will test with 180206 and see if any of this behavior was present there.

**Comment by sql-sith** [comment]
I've just realized that I've been referring to 180626 as "stable." It is in fact an older preview build.

I installed 180626 and found similar behavior. The problems morph a little bit, and seem to depend on whether cmder/conemu was launched directly or via an init.bat file that ships with conemu.

Repro is still simple for me. Can someone else try this please? Make sure you do this with a fresh copy of cmder. By the way, start each scenario with a screen full of text (run `dir C:\Windows` or something) - it will make it easier to see what is happening.
- Download cmder
- Unzip it to wherever
- Run conemu64.exe
- Do **Scenario 1** and **Scenario 2** above
- Scratch head and wonder why
