### ISSUE TITLE
Command git submodule update does not show password check

### ISSUE THREAD

**Issue by camohub** [cmderdev/cmder#1966]
Hi, I have a project which uses Git submodules. So i need to call `git submodule init` which works well in CMDER and then call `git submodule update`. This command should ask me for password to repository but CMDER does not ask me for password. Then it throws me an error. 
I am on Windows 10 and have one of the latests version of CMDER.

**Comment by camohub** [comment]
In this case I use Gitbash console and it has no problem with it.

**Comment by daxgames** [comment]
Are you using git bash inside cmder or outside cmder when it works?

**Comment by hosaka** [comment]
Hi @daxgames 

Having the same issue with cmder. Git Bash, installed from git-for-windows works okay (the separate cygwin app). User has access to both repositories and registered SSH key. Recursively cloning or doing submodule update --init produces this:
```
C:\Users\user\work\git  $ git clone --recursive git@gitlab.com:path/repo.git -b develop
Cloning into 'neif-revit'...
Enter passphrase for key '/c/Users/user/.ssh/id_ed25519':
remote: Enumerating objects: 933, done.
remote: Counting objects: 100% (933/933), done.
remote: Compressing objects: 100% (457/457), done.
Receiving otal 933 (delta 648), reused 684 (delta 451), pack-reused 0
Receiving objects: 100% (933/933), 1.06 MiB | 732.00 KiB/s, done.
Resolving deltas: 100% (648/648), done.
Submodule 'Submodule' (git@gitlab.com:path/submodule.git) registered for path 'Submodule'
Cloning into 'C:/Users/user/work/git/repo/Submoddule'...
git@gitlab.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```

**Comment by malcolmdavey** [comment]
Seems it's just an issue with git on windows. Some tools may be able to work around it.

**Comment by btara1** [comment]
https://github.com/gitextensions/gitextensions/issues/5073#issuecomment-933985371
use git bash. works for me
