### ISSUE TITLE
it took me about 10's to start

### ISSUE THREAD

**Issue by hellobbq** [cmderdev/cmder#1972]
```
DEBUG(init.bat): Env Var - CMDER_ROOT=<path>

DEBUG(init.bat): Env Var - debug_output=1

Injecting Clink!
DEBUG(init.bat): Looking for Git install root...

DEBUG(:read_version): Env Var - git_executable=<path>\vendor\git-for-windows\cmd\git.exe

DEBUG(:read_version): Env Var - GIT_VERSION_VENDORED=2.19.0.windows.1

DEBUG(:validate_version): ARGV[1]=VENDORED, ARGV[2]=2.19.0.windows.1

DEBUG(:parse_version): ARGV[1]=VENDORED, ARGV[2]=2.19.0.windows.1

DEBUG(:validate_version): Found Git Version for VENDORED: ...

DEBUG(Using vendored Git from '<path>\vendor\git-for-windows...):

DEBUG(:enhance_path): Env Var 1 - found=0

DEBUG(:enhance_path): Env Var 2 - found=0

DEBUG(:enhance_path): BEFORE Env Var ....

DEBUG(:enhance_path): Appending '<path>\vendor\git-for-windows\cmd'

DEBUG(:enhance_path): AFTER Env Var ...

DEBUG(:enhance_path): Env Var 1 - found=0

DEBUG(:enhance_path): Env Var 2 - found=0

DEBUG(:enhance_path): Appending '<path>\vendor\git-for-windows\mingw64\bin'

DEBUG(:enhance_path): AFTER Env Var ...

DEBUG(:enhance_path): Env Var 1 - found=0

DEBUG(:enhance_path): Env Var 2 - found=0

/////////////////and so on....

DEBUG(:enhance_path_recursive): Env Var - add_path=<path>\bin

DEBUG(:enhance_path_recursive): Env Var - position=

DEBUG(:enhance_path_recursive): Env Var - max_depth=1

DEBUG(:enhance_path_recursive): Adding parent directory - '<path>\bin'

DEBUG(:enhance_path): Env Var 1 - found=0

DEBUG(:enhance_path): Env Var 2 - found=0

///////////////////until

Running Git for Windows one time Post Install....

DEBUG(init.bat): Env Var - HOME=C:\Users\<User>

Elapsed Time: 0:0:10.88 (10.88s total)
```
```
env set: CMDER_ROOT and append  '%CMDER_ROOT%\bin' to PATH

windows10, cmd:cmder, but bash:bash faster,

i had installed java/node/vmware/vbox...
```

**Comment by hellobbq** [comment]
it took me 1's more or less until i reinstalled windows10 version 1089, and changed new 256G SSD, old cpu is e3-1230, memory is 16G.
now eveytime i start cmder cost so long time.
my heart broken, test env PATH and try hard for this...
could it be that difference between 'cmd' and 'powershell'

**Comment by daxgames** [comment]
@hellobbq `4s` is still a long time with `/f`, e3-1230, 16GB, and ssd hdd. I would think you'd be on par or better than me given your CPU is for a server and of similar age as mine.

**Comment by lonelykid** [comment]
> 
> 
> @hellobbq `4s` is still a long time with `/f`, e3-1230, 16GB, and ssd hdd. I would think you'd be on par or better than me given your CPU is for a server and of similar age as mine.

Is there a introduction to the init.bat file? I don't know what it's doing and what arguments I could pass to it. without /f, I got like 4s, with /f, I got 1.6s. Still rather slow.

Instead, I tried reset completely. then it falls back to use CmdInit.cmd. And I just add the git-for-windows path manually. I didn't feel any difference but it's much faster
Thanks!

**Comment by daxgames** [comment]
@lonelykid 1.6s is about right for `/f`.

Basically `init.bat` sets up the path, injects clink, conflgures user aliases, and runs user init scripts.  All the things that make cmder.  

If you reset you are running straight conemu and have lost all the Cder enhancments.
