### ISSUE TITLE
Error execuing vi in ssh session.

### ISSUE THREAD

**Issue by Txema30** [cmderdev/cmder#1976]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

**Comment by Txema30** [comment]
Hi,

When I try to create/edit files usin vi inside a ssh session, I get the next error:

cygwin: Unknown terminal type
I don't know what kind of terminal you are on - all I have is 'cygwin'.

I solve this error change the next enviroment value 'export TERM=vt100' (I am not know if this value is the best, but this solve my problem) in the destination machine, but I want to know if may be possible configure my local cmder to connect automatically with this value or another similar by default.

My OS is Windows 10 and the destinations machines are SOLARIS10 and 11.

Could you help me please? 

### **Thank you very much and great job for this software, is very useful for my.**

Thanks.

**Comment by daxgames** [comment]
@Txema30 you can set 'export TERM=vt100' in `%cmder_root%\config\user_profile.cmd` and it will override the default.
