### ISSUE TITLE
User path

### ISSUE THREAD

**Issue by dunnodun** [cmderdev/cmder#1977]
There is this [thread](https://superuser.com/questions/911799/why-cmder-does-not-import-the-user-path-variables) but it doesn't really help me since the init.bat changed and I have no clue what the problem is. I just would like to use the user path variable in cmder and I was wondering why it isn't available by default.

How could I add the user path to the current version?

**Comment by daxgames** [comment]
In my testting not even cmd.exe shells outside cmder have the user path configured.  Cmder inherits the path from explorer as does cmd.exe.  This is not a cmder issue.

**Comment by dunnodun** [comment]
I probably did a mistake. I think it's related to my usage of cmder from another partition. 
I tested it now and I could execute the programs from my user path even from the other partition, so it's kinda weird. But I don't know exactly what I did 9 days ago and in the meantime I switched to Linux for work because currently I'm not bound to Windows applications. 
Thanks for trying to help anyways and sorry for opening the issue.
