### ISSUE TITLE
hg_prompt_filter @ clink.lua is broken

### ISSUE THREAD

**Issue by Sairony** [cmderdev/cmder#1978]
It seems to operate under the assumption that hg id will return at the very least 2 lines. However in a repo on default with no tags or bookmarks with uncommitted changes it will return only a single line, items will then contain only 1 item, and hence <code> result = color .. items[2] -- string.sub(items[2], 1, string.len(items[2]) - 1)</code> on line 339 will index out of bounds & try to concat with a nil value. Or at the very least that's my understanding with poor lua skills. The consequence is <code>cmder\vendor/clink.lua:339: attempt to concatenate field '?' (a nil value)</code> after every command while inside the repo.

**Comment by Shingyx** [comment]
This should be fixed by https://github.com/cmderdev/cmder/pull/2002
