### ISSUE TITLE
Path in certain branch of git displays out of order.

### ISSUE THREAD

**Issue by paintballduke22** [cmderdev/cmder#1979]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Description of the issue 

I haven't been able to find others with a similar issue (part of the problem is I don't know exactly what to search for beyond "path display messed up in git branch".

When I am in the directory of one of my branches on git, the path has been aliased or something causing a strange appearance in my terminal window.

`rigin;40mC:\Projects\<my path> (2 -> origin) rigin2 -> origin;49m(<my tag>)rigin2 -> origin;49m`

When I change branches, it looks completely normal:
`C:\Projects\<my path> (master -> origin) (<my tag>)`

![image](https://user-images.githubusercontent.com/5873323/49535405-609a6180-f881-11e8-9112-2ce65f8380d9.png)

Is there a way that anyone knows of to remedy this? It's not breaking in any way but it is super annoying. This branch is one that I frequently use.

**Comment by daxgames** [comment]
What is the branch name that has this behavior and have yo modified the `%cmder_root%/vendor/clink.lua` in any way?

**Comment by k7sleeper** [comment]
I have the same problem!

My git repo is located under `C:\development\vcs\git\repos\gr0`. If I check-out branch `master`, `cmder`displays the prompt correctly: `C:\development\vcs\git\repos\gr0 (master -> origin/current)`.
When I check-out branch `develop`, then `cmder` incorrectly displays `C:\develop -> origin/currentment\vcs\git\repos\gr0 (develop -> origin/current)`.

**Comment by daxgames** [comment]
PR open with ckink-completins that fixes this. https://github.com/vladimir-kotikov/clink-completions/pull/114
