### ISSUE TITLE
Feature Request: Autocomplete non-executables

### ISSUE THREAD

**Issue by CIPop** [cmderdev/cmder#1980]
There are many issues like #508 pointing out that non-executables don't autocomplete.
A current workaround exists: set exec_match_style to -1

```
# name: Executable match style
# type: enum
#  0 = PATH only
#  1 = PATH and CWD
#  2 = PATH, CWD, and directories
# Changes how Clink will match executables when there is no path separator on
# the line. 0 = PATH only, 1 = PATH and CWD, 2 = PATH, CWD, and directories. In
# all cases both executables and directories are matched when there is a path
# separator present. A value of -1 will disable executable matching completely.
exec_match_style = 2
```

This is a feature request to allow autocompletion for local files either:
1. All local files could auto-complete.
2. Allow us to define executables (*.exe, *.cmd, etc)

**Comment by CIPop** [comment]
#2 is explained here: https://github.com/cmderdev/cmder/issues/826#issuecomment-443714333

> On Windows in cmd.exe sessions executeable file extensions are configured by the PATHEXT environment variable. Mine is currently set to:
> PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC

I'll leave this item opened - can we have this automatically populated by cmder instead of all of us adding to this environment? Maybe another config such as `exec_extensions = ...`?

**Comment by daxgames** [comment]
You can auto-populate it by editing your `user_profile.cmd`.  Something like:

```
set PATHEXT=%PATH_EXT%,.PY,.PL
```
The above will make `*.pl` and `*.py` files autocomplete.

If you want to do the `-1` thing and that does what you want then that is also an option.

This will not be added as a feature of Cmder.  That is why you have user init scripts.

**Comment by bumbaras** [comment]
Cmd has no problem to expand any file name, executable or not. What a crap, need to look for some other replacement of cmd.
