### ISSUE TITLE
cmder vscode intergration fails

### ISSUE THREAD

**Issue by TonyLancer** [cmderdev/cmder#1984]
I have [Shell launcher] installed on VS Code. I've been trying to run cmder through the VS Code integrated terminal, but everytime I run it, this error pops up.

![error message](https://user-images.githubusercontent.com/20476593/49818388-3feb7380-fd7b-11e8-8896-dd5051f1ce41.png)

The configuration of cmder is:

    "shellLauncher.shells.windows": [
        {
            "shell": "D:\\cmder\\Cmder.exe",
            "label": "Cmder",
            "args": ["/k D:\\cmder\\vendor\\init.bat"]
        },
    ],

I do have a `vscode.bat` file as instructed [here](https://code.visualstudio.com/docs/editor/integrated-terminal#_can-i-use-cmders-shell-with-the-terminal-on-windows), and did try the configuration presented there and this did not help.

Is there something I am missing here?

    OS: Windows 10 x64
    Cmder: ConEmu 161206 [64]
    VS Code: 1.29.1

  [Shell launcher]: https://marketplace.visualstudio.com/items?itemName=Tyriar.shell-launcher

**Comment by TonyLancer** [comment]
Turns out I did not read the [documentation](https://github.com/cmderdev/cmder/wiki/Seamless-VS-Code-Integration#vs-code-terminal) properly 😞 . The `shell` property should be of the Windows Command Prompt, that is, `C:\\Windows\\system32\\cmd.exe` (not the `cmder.exe`) and the args can be the same (or updated with the [`%CMDER_ROOT%`](https://github.com/cmderdev/cmder/wiki/Setting-up-Environment-Variables#1-how-to-properly-set-up-the-cmder_root-variable).

So the resulting configuration is:
```
"shellLauncher.shells.windows": [
    {
        "shell": "C:\\Windows\\system32\\cmd.exe",
        "label": "Cmder",
        "args": ["/k D:\\cmder\\vendor\\init.bat"]
    },
],
```

**Comment by Tecayehuatl** [comment]
For those who shows the console in a new window, I share my setup, I installed `shellLauncher` plugin if you want to.

My code:

```

{
    "editor.mouseWheelZoom": true,
    "terminal.integrated.shell.windows": "C:\\windows\\System32\\cmd.exe",
    "terminal.integrated.shellArgs.windows": [
        "/k",
        "C:\\Users\\enrique.delgado\\Downloads\\cmder_mini\\vendor\\init.bat"
    ],
    /* 
        The next setup is because shellLauncher plugin, if you don't have it installed you only will need the above code.
    */
    "shellLauncher.shells.windows": [
        {
            "shell": "C:\\windows\\System32\\cmd.exe",
            "label": "cmd",
            "args": [
                "/k C:\\Users\\enrique.delgado\\Downloads\\cmder_mini\\vendor\\init.bat"
            ]
        },
        {
            "shell": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
            "label": "PowerShell"
        }
    ],

    "editor.formatOnPaste": true
}

```
