### ISSUE TITLE
Something wrong with Windows 10 UTF-8 support.

### ISSUE THREAD

**Issue by PMExtra** [cmderdev/cmder#1986]
## Start command

Just cmd.

```
cmd /k ""%ConEmuDir%\..\init.bat""
```

## Recurrent

Enter something that more than 4 character. (without enter key)

```Shell
λ some-command
```

Then press [CTRL] + [U] to clear the line.

Excepted:

```Shell
λ 
```

Actual:

```Shell
λ s
```

And I cannot using the backspace key to remove the `s`.

**Comment by PMExtra** [comment]
This character only show on the screen but it doesn't effect when execute.

**Comment by PMExtra** [comment]
I think it's because of the "System Locale Settings".
![image](https://user-images.githubusercontent.com/11289158/50410866-b6d24300-0836-11e9-8207-3c225cb6f44b.png)

Please check the compatibility with enable the new feature in Windows 10: `Beta: Use Unicode UTF-8 for world wide language support`

**Comment by darklonely** [comment]
got the same issue.
system: windows 7 64bit
cmder: lastest 1.3.11.

**Comment by Citizen-icon** [comment]
Same issue

![image](https://user-images.githubusercontent.com/11224565/51012018-f4a0cc80-1595-11e9-9859-6b77abd12b3b.png)
Input '中文’，I just delete one word,but can't display '中'.

Enabled Windows UTF-8 support.
![image](https://user-images.githubusercontent.com/11224565/51012066-3e89b280-1596-11e9-9009-d855947736b6.png)

Cmder Env:
![image](https://user-images.githubusercontent.com/11224565/51012101-6ed15100-1596-11e9-80d8-dfeebe1f0543.png)

**Comment by Jiffies-Duke** [comment]
same issue:
1. When inputing Chinese, the cursor moves right correctly. But if I press backspace once, the cursor moves left 3-space-width, 2 Chinese words are removed, and 1 extra space is added at the line end.  It is supposed to move cursor 2-space-width left, remove 1 Chinese word, and add no space.
2. After Cmder started, the cursor is 2 spaces away from the "λ" prompt, which used to be 1 space away.
My windows region setup is same as @PMExtra and @drrrMikado .

**Comment by jdhao** [comment]
This is related to https://github.com/cmderdev/cmder/issues/506#.

**Comment by mattmilten** [comment]
A workaround is to change the default prompt and replace the lambda character `λ` with something else, like `>`. This can be done in `Cmder\vendor\clink.lua`:

```
 local lambda = ">"
```

**Comment by dorkbox** [comment]
An update on this issue, since I'm having it as well...
I think it's absolutely a rendering issue... since you cannot have arbitrary characters as the "lambda". For example -  the default is `λ` and if you *replace* it with 𝝺 (which is a different lambda) - the prompt is completely screwed up

![image](https://user-images.githubusercontent.com/5301521/77831348-da1d2980-712e-11ea-8bc3-5edfd3ea45ce.png)

For reference, I got that lambda from https://en.wikipedia.org/wiki/Lambda, and it is the `U+1D77A` lambda. I have UTF support enabled in windows.Only the first two lambda's work from that page.

**Comment by PMExtra** [comment]
@dorkbox I think it's not a bug, it's because your file encoding is not UTF-8. Please check.

**Comment by dorkbox** [comment]
@PMExtra 

Windows was already set to use UFT-8, is there another setting I should change as well?

![image](https://user-images.githubusercontent.com/5301521/78029886-92caaf00-7361-11ea-8d53-ac1040c7278d.png)

**Comment by PMExtra** [comment]
@dorkbox How did you replace the `λ`? Did you modify `clink.lua` or `profile.ps1`? Please check the file encoding.

**Comment by daxgames** [comment]
@PMExtra You can write a `%cmder_root%\config\prompt.lua` to replace the `λ`.  You could even search Cmder issues and find one I wrote and use it.

**Comment by daxgames** [comment]
@PMExtra see #2208

**Comment by dorkbox** [comment]
I edited the `clink.lua` file. The file is UTF-8. Of note, the file *displayed* the different lambda correctly. The *prompt* is what was screwed up.

![image](https://user-images.githubusercontent.com/5301521/78155896-54ef8880-743e-11ea-9db3-ccfd1b46788a.png)

**Comment by daxgames** [comment]
@dorkbox don't edit the clink.lua.  use the method I suggested.

**Comment by dorkbox** [comment]
@daxgames I made the change -- that's a lot easier for customization than manually editing `clink.lua` ... I had no idea, thanks! 

However, it exhibits the same problem. An actual **unicode** lambda,  `U+1D77A`, which is not in the DOS lookup table, does not work. The `file` is UTF-8 and the `OS` is set to UTF-8.  This is super easy to reproduce.

`%cmder_root%\config\prompt.lua`
```
function my_prompt_filter()
    cwd = clink.get_cwd()
    prompt = "\x1b[1;32;40m{cwd}{git}{hg}{svn}\x1b[1;30;40m{lamb} \x1b[0m"
    new_value = string.gsub(prompt, "{cwd}", cwd)
    clink.prompt.value = string.gsub(new_value, "{lamb}", "𝝺")
end

clink.prompt.register_filter(my_prompt_filter, 1)
```


![image](https://user-images.githubusercontent.com/5301521/78229410-3e920d00-74d0-11ea-99c2-43ab28cd4c6f.png)

**Comment by daxgames** [comment]
The lambda is not going away.  You can change it to something else using the method I referenced.  Does the same thing happen in straight cmd.exe outside conemu?

`cmd /k ""%cmder_root%\vendor\init.bat""`

**Comment by dorkbox** [comment]
@daxgames I love the lamba, please don't get rid of it - i just don't want to have problems when navigating history *which I do a lot*, so I'm forced to change it (or be stuck with a corrupted prompt, as shown by OP)

I think the problem that exists (where on windows, if you navigate "up" through history for short commands, the first letter of a previous command "corrupts" the prompt) is a real problem, needs fixing, and is related to the underlying byte arrays (ie: utf-8 requires more space than ascii, but less than utf-16, and someone, I think at MS, didn't test UTF-8 chars that are not in the DOS lookup table. Of note, there are other UTF-8 chars in this lookup table, which is what windows uses).

This problem also happens via `cmd /k ""%cmder_root%\vendor\init.bat""` The windows command prompt does not like to accept `𝝺`, even *typing it* or *copy/paste* into the window...

**This is spectacularly easy to reproduce**  
1) Paste `λ` in the command prompt window. 
2) Notice that it works. 
3) Now paste `𝝺` in the window. 
4) Notice it does not work.

Step 2 for showing the byte alignment issues.
1) Type "hello" in the command prompt window. DO NOT PRESS ENTER
2) Paste `λ` in the command prompt window (this is the cmder lambda, which is different than `𝝺`).
3) Move the cursor to the left one position.
```
  -> helloλ|
  ->       ^ cursor
  -> hello|λ
  ->      ^ cursor
```
4) Notice that the cursor will "jump" two characters, to the left of the 'o', and it is not possible to move the cursor between the 'o' in "hello" and the λ
```
  -> hell|oλ
  ->     ^ cursor

#This is not possible
  -> hello|λ
  ->      ^ cursor
```

**Comment by daxgames** [comment]
@dorkbox 

> This is spectacularly easy to reproduce
> Paste λ in the command prompt window.
> Notice that it works.
> Now paste 𝝺 in the window.
> Notice it does not work.

Yes

> Step 2 for showing the byte alignment issues.
> 
> Type "hello" in the command prompt window. DO NOT PRESS ENTER
> Paste λ in the command prompt window (this is the cmder lambda, which is different than 𝝺).
> Move the cursor to the left one position.
>  ```
>   -> helloλ|
>   ->       ^ cursor
>   -> hello|λ
>   ->      ^ cursor
>  ```

This worked fine for me.  I was able to move the cursor between the 'o' in "hello" and the λ.

I suggest you change the `λ` to a `$` using the method I suggested and see if the issue persists.

**Comment by daxgames** [comment]
@dorkbox If you still have issues after changing the `λ` to a `$` report it to the conemu developer at https://github.com/Maximus5/ConEmu/issues

**Comment by daxgames** [comment]
@dorkbox it could also just be a font issue and you may be able to resolve it using a different font.

**Comment by dorkbox** [comment]
Oh interesting. 

Using your method, I changed it to a `~`, and it works. I don't have a problem with history navigation with the `~` like I do with the `λ`, however I would prefer the labda... (of note, changing it the way you specified has the same result as changing it in `clink.lua` 

I'm curious though, what version of the terminal you're using? Maybe that has something to do with it? Mine is:
```
Microsoft Windows [Version 10.0.17763.1131]
(c) 2018 Microsoft Corporation. All rights reserved.
```

**Comment by dorkbox** [comment]
> 
> 
> @dorkbox it could also just be a font issue and you may be able to resolve it using a different font.

I tried `Source Code Pro` and it screwed up. What font are you using?

**Comment by dorkbox** [comment]
> 
> 
> @dorkbox it could also just be a font issue and you may be able to resolve it using a different font.

I also tried the same font but with a different font charset, it didn't work.

![image](https://user-images.githubusercontent.com/5301521/78585884-e2661a80-783a-11ea-899c-3d2772754957.png)
