### ISSUE TITLE
Make history-search-backward (PgUp) the default (Up)

### ISSUE THREAD

**Issue by crstnbr** [cmderdev/cmder#1993]
Thanks to https://github.com/cmderdev/cmder/issues/103 we have `PgUp` and `PgDown` to jump through old commands. It seems to be a powerful generalization of what happens on `Up` and reduces to the simple `Up`-behavior if nothing has been typed.

1) Why isn't the `PgUp` behavior the default? In my opinion it should be on `Up` as is the case in most linux distributions.
2) If we don't make it the default, is it possible to reassign `Up` to `PgUp` functionality locally?

I know that the feature itself is implemented in clink. However, other shortcuts are defined in ConEmu.

**Comment by daxgames** [comment]
@crstnbr I do not understand what you are asking.
