### ISSUE TITLE
Error  run in read-only filesystem

### ISSUE THREAD

**Issue by qokelate** [cmderdev/cmder#1994]
I copy cmder to vhd and mount for read-only, where run cmder.exe it say this:

---------------------------
Cmder Launcher
---------------------------
Failed to copy ConEmu.xml file to backup location!
---------------------------
确定   
---------------------------

**Comment by daxgames** [comment]
Cmder as it is today can't run from a read only file system.

**Comment by qokelate** [comment]
okay, thanks
