### ISSUE TITLE
Problem occurs after quit vim

### ISSUE THREAD

**Issue by ylkky** [cmderdev/cmder#2000]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 

Every time I quit from vim, cmder becomes:
![image](https://user-images.githubusercontent.com/19553921/50392106-3b18bd80-0786-11e9-9c5c-b6e99099f17e.png)
I have tried in cmd of windows 10, it works well.
my vim version is Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)

**Comment by ylkky** [comment]
There is no script to start my vim. I just use 'vim FILENAME' to start vim, and ':wq' or ':quit' to quit vim. What's more, I tried the same commands in windows cmd.exe, it works well.

> Does this happen whe Cmder Full embedded vim? My guess this is an issue with your Vim. Are you running a script to start your vim? What happens when you type `exit`>

**Comment by daxgames** [comment]
And if you type `exit` at the resulting prompt after exiting vim?

Attach the output of `where vim`?

**Comment by ylkky** [comment]
> And if you type `exit` at the resulting prompt after exiting vim?
> 
> Attach the output of `where vim`?


I am using the vim on my remote server, so when I type `exit` at the resulting prompt after exiting vim, the ssh connection to my server was closed normally.
My system is Ubuntu 16.04, and it shows 'No command 'where' found'. I tried `which vim`, and get output as `/usr/bin/vim'

**Comment by ylkky** [comment]
> I don't understand the problem then. All is working as expected. `Escenter11pc` is the remote host?

Yes, Escenter11pc is the remote host.
The problem is,before I use vim, cmder works well
![image](https://user-images.githubusercontent.com/19553921/50448608-2c383380-095d-11e9-93e7-d54d5a28fe38.png)
But, after I type `vim FILENAME`, and edit my file, and quit vim, cmder becomes:
![image](https://user-images.githubusercontent.com/19553921/50448684-82a57200-095d-11e9-834b-14c5e8fe2e34.png)

All the context disappeared!! It seems to be a display problem.
If I am using a windows cmd.exe, it works well:
![image](https://user-images.githubusercontent.com/19553921/50448732-cc8e5800-095d-11e9-8318-f9a571e3bced.png)

**Comment by daxgames** [comment]
Cmder is not running on your remote host.  It is not responsible for the color of the remote host prompt.

Cmder uses conemu as its terminal emulator.  You should try doing a similar action with default conemu that is not cmder enhanced.

My guess is the problem is with conemu or one of its settings.  Issues should be reported to conemu team.

**Comment by daxgames** [comment]
Can this be closed?
