### ISSUE TITLE
Aliases 'used' on start, then they are unavailable

### ISSUE THREAD

**Issue by Grupa-Leonardo** [cmderdev/cmder#2003]
Few days ago my Cmder was started with 'use' all aliases:
https://prnt.sc/m2zg85
and after start, they are unavailable:
http://prntscr.com/m2zivw
**BUT**
when I add any alias, e.g. `alias .=.` ...
http://prntscr.com/m2zk04

Why? I don't have any changes/updates or anything else.

**Comment by daxgames** [comment]
I don't understand the screenshots.

What version of cmder?

Did you update cmder recently?  If so what was the old version?

If running the latest you can type `cmder_diag.cmd` and post the output to give us some insight into your config.

**Comment by Grupa-Leonardo** [comment]
> I don't understand the screenshots.

Sorry, I didn't have better idea how to describe a problem.



> What version of cmder?

Latest


> Did you update cmder recently? If so what was the old version?

I was downloaded yesterday latest version from website



> If running the latest you can type `cmder_diag.cmd` and post the output to give us some insight into your config.

Here you are: https://pastebin.com/igvWwn4v

**Comment by daxgames** [comment]
I still do not understand the issue based on your description.  What does 'Cmder was started with 'use' all aliases and after start, they are unavailable' mean?

I don't see any obvious issues in the cmder_diag output.

The latest cmder uses a different file format to store aliases than what your previous version used.  I believe it was 1.3.2?  When an old version is seen it is converted to the new version. Maybe something went wrong in this conversion?

**Comment by Grupa-Leonardo** [comment]
Here is video clip from this (bug?)
https://drive.google.com/file/d/18RXyF-RDJ5fDa6WGutTapgVUfp9pINwa/view

**Comment by Grupa-Leonardo** [comment]
Any ideas?

**Comment by daxgames** [comment]
Nope.  Can you share the contents of '%cmder_root%\config\user_aliases.cmd`?

**Comment by daxgames** [comment]
@Grupa-Leonardo you have not responded.  Do you still need help with this or can I close it.

**Comment by daxgames** [comment]
Closing due to lack of response from OP.
