### ISSUE TITLE
Directory or user issue

### ISSUE THREAD

**Issue by PrinceArthas13** [cmderdev/cmder#2006]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Description of the issue 

I'm new to cmder so I'm not even really sure what I'm doing wrong or what's going wrong, but I either can't figure out how to set up a user profile or other issues that I don't know what it could be. Looking through the issues. I couldn't even pinpoint a name for my issue so looking through everything trying to figure out what it could be and nothing really popping up with my exact issue. So if anyone could help I would really appreciate it, and sorry ahead of time if this is an easy fix and I just seem dumb. I've tried changing file locations, I've tried downloading atleast 20 times. I've been trying to figure this out for a few days now.
![20190109_093622](https://user-images.githubusercontent.com/26804477/50929074-5a704580-142a-11e9-9b11-f996528dfafc.jpg)
![20190109_155359](https://user-images.githubusercontent.com/26804477/50929088-60febd00-142a-11e9-9e5a-d1af5a476796.jpg)

**Comment by daxgames** [comment]
I don't see any issue.  This is normal behavior for a first time launch.  All user configuration is in `%cmder_root%\config`.  There is a separate `user_profile.[cmd|ps1|sh]` for each shell type that gets created at initial launch of the shell.

Hope this helps and welcome!

**Comment by daxgames** [comment]
Don't know what to tell you other than what I just said.  `ls` lists what is in the current folder and that is what is in the cmder folder after you unzip it.

**Comment by PrinceArthas13** [comment]
I'm trying to get it connected to all my files so I can connect my anaconda 3 to it when I try it just says path isn't there

**Comment by daxgames** [comment]
I'm afraid I can't help you with that.  You would do it the same way you would with any other terminal.

**Comment by PrinceArthas13** [comment]
Thank you so much I figure it out.  I never went to startup directory and chose a file to start at.
