### ISSUE TITLE
Alias is not working if 2nd in a pipe command

### ISSUE THREAD

**Issue by cdiac** [cmderdev/cmder#2007]
![1](https://user-images.githubusercontent.com/23461852/51028020-fb7e0e00-159a-11e9-88df-38f55d3b580b.png)
![2](https://user-images.githubusercontent.com/23461852/51028021-fb7e0e00-159a-11e9-95ca-363fc8302493.png)

### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 
Alias is not working if 2nd in a pipe command. Please view attached images. Even if „ll„ command does not make sense in a pipe, will show that aliases are not recognized in pipes.

**Comment by daxgames** [comment]
This is a limitation of doskey macros which is how cmder cmd shell aliases work.  If you want true alias functionality use the bash shell.

**Comment by ILyaCyclone** [comment]
Hi. No progress here?

**Comment by daxgames** [comment]
There is no progress to be made see my last comment.

**Comment by chrisant996** [comment]
Clink v1.0 and higher support expanding doskey macros after the pipe character.

**Comment by daxgames** [comment]
Ok so maybe that is progress I did not know about.
