### ISSUE TITLE
Cmder terminal window doesn't close if background process still running

### ISSUE THREAD

**Issue by realuser** [cmderdev/cmder#2008]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Description of the issue 

I'm not sure if this is ConEmu or Cmder issue but I'm using Cmder with WSL (windows subsystem for linux), if I start a background process and then type `exit` , the message `logout` is printed and then the terminal hangs (I can however still hit the "X" in the GUI which does close the terminal window).  If I open another terminal window and kill the background process then the original terminal window closes.

This is different to how the WSL Ubuntu terminal works which if I start a background process and then type `exit` it will close the terminal window and the background process will remain running.

Why is there a difference between the way these two things work? Is there some setting to get the same behavior as the native WSL terminal?

**Comment by daxgames** [comment]
Hey there,

Cmder uses ConEmu as terminal emulator, if you are experiencing a problem or have a question with that, please open a issue over at https://github.com/Maximus5/ConEmu

Thank you! :)

**Comment by realuser** [comment]
@daxgames  How would I know if it's a problem with Cmder or ConEmu?

**Comment by daxgames** [comment]
Cmder is a package of various products and config for cmd, git bash, and powershell. 
WSL is none of these.  Cmder.exe is a launcher for Conemu that is the beginning of this custom integration that together with other components is Cmder.  Conemu is the terminal emulator Cmder uses.  If you are using WSL you are not using Cmder, you are using WSL in Conemu that was launched by Cmder.exe.

If you want you could confirm 100%  if you download conemu portable and try the same in there.
