### ISSUE TITLE
start up directory on cmder does not appear

### ISSUE THREAD

**Issue by Jesuisdesole** [cmderdev/cmder#2010]
Hi guyz,

After I run cmder the cursor just keeps blinking and I can not write a single line of code! Moreover, sometimes the dialog window does not open the way I want. The system open instead of cmd.exe something like where.exe??

Once the directory appears, it does not allowed me to write...

![image](https://user-images.githubusercontent.com/46635759/51079139-3b8be080-16c2-11e9-9326-11da332b1e94.png)

This all happend, after I tried to install lavarel. Yes, I have already installed composer.

Thanks verrry much

**Comment by daxgames** [comment]
Add `-d -v` to the cmder task that you are launching to see where it hangs and post the output.

**Comment by daxgames** [comment]
Closing due to lack of response from OP.
