### ISSUE TITLE
vendor\conemu-maximus5\..\init.bat"' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by Jesuisdesole** [cmderdev/cmder#2011]
Hi guys,

see what appears me, when I run cmder.exe  . Does someone of you had a similar problem?

![image](https://user-images.githubusercontent.com/46635759/51083880-8a1c9780-1721-11e9-8834-c9e7f5f41f31.png)

Thankz

**Comment by daxgames** [comment]
Check your antivirus quarantine.

**Comment by daxgames** [comment]
Closing due to lack of response

**Comment by mary-C21** [comment]
Hi,
Could you please advise how to check that ? 

Do you know what else can cause this as it looks like this computer doesn't have antivirus ?

Many thanks,

**Comment by daxgames** [comment]
How to check:  Is there a file called init.bat in the mentioned location?

Why this happens: Usually an antivirus/malware false positive.  Sometimes older versions of Cmder or Cmder conemu.xml config didn't handle paths with spaces correctly.  It's not recommended to put Cmder in `c:\program files`

**Comment by mary-C21** [comment]
Well not in the file where I extract all the file but in the downloaded one it is . I tried to copy and paste from one folder to another but it doesn’t like it either.

So if I will save it elsewhere not in the C drive that should help ? 

Maria Croitor

**Comment by daxgames** [comment]
Unknown.  Something is removing it after you copy it to that location and it will probably do it wherever you copy it.

You need to figure out what is doing it and make it stop.
