### ISSUE TITLE
User profile with spaces

### ISSUE THREAD

**Issue by auirarrazaval** [cmderdev/cmder#2012]
Hi! 
So im getting started on Cmder and ConEmu, by following [this tutorial](https://gist.github.com/jchandra74/5b0c94385175c7a8d1cb39bc5157365e) and i have an issue as im doing this:

![image](https://user-images.githubusercontent.com/31079536/51230576-3be4df80-193f-11e9-9b8d-7f4ecc8eb8b1.png)

The problem is that my user folder is 'Alfonso Irarrázaval', and then i get the following error:

![image](https://user-images.githubusercontent.com/31079536/51230631-7484b900-193f-11e9-8c8e-7621436a3b17.png)

Im guessing it is because there is a space on the folders name, so is there a way to go around it?

**Comment by daxgames** [comment]
Cmder version?  The screenshot appears to be an old version.

**Comment by auirarrazaval** [comment]
I have just installed it using Chocolatey and cinst cmder -y
The version file says 1.3.11.843

**Comment by auirarrazaval** [comment]
@daxgames i uninstalled and installes from github the latest release, and still have the same problem

**Comment by daxgames** [comment]
@auirarrazaval I just tested and did not see this issue.  The file that is executing and erroring in your screenshot is not a part of Cmder.  It looks like your Powershell profile might be being dot sourced from this file.  Make sure the path to the sourced profile is wrapped in quotes.

Also I still contend your screenshot does not match the current version powershell task settings of cmder.  Below is how my Powershell task is configured:

```
PowerShell -ExecutionPolicy Bypass -NoLogo -NoProfile -NoExit -Command "Invoke-Expression '. ''%ConEmuDir%\..\profile.ps1'''"
```

**Comment by daxgames** [comment]
@auirarrazaval  I just looked again at your screenshot and the task is the problem.  It is sourcing the profile and is unquoted.

**Comment by auirarrazaval** [comment]
@daxgames I was using the other one because i knew its location, but now it works perfect;y, thanks!
