### ISSUE TITLE
Weird graphical glitch when running NERDTree

### ISSUE THREAD

**Issue by samuelbodin** [cmderdev/cmder#2016]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 
Sorry if this is the wrong place for this post...

So I ran into this weird graphics bug with NERDTree...
When editing a file with Vim in Cmder I get this
![1](https://user-images.githubusercontent.com/19345463/51432853-04c44600-1c3f-11e9-8d0b-c94570bc99e7.png)

Whereas with the standard bash terminal I get it correct...
![2](https://user-images.githubusercontent.com/19345463/51432855-173e7f80-1c3f-11e9-9f66-04309d3aa78f.PNG)

This was a fresh install of Ubuntu18.04 on WSL. 
Any ideas?

**Comment by daxgames** [comment]
I use Nerdtree all the time in vim in cmd and bash sessions with cmder.  I think I have also used it with wsl in cmder and not had any issues but I need to verify that.

**Comment by daxgames** [comment]
I'm betting it's a font issue

**Comment by samuelbodin** [comment]
Yes, confirmed it's a font issue. I switched from "Segoe UI Symbol" into Lucida Console and now it works :) Thanks daxgames!
