### ISSUE TITLE
Set-PSReadlineOption throws an exception when I open new PowerShell console

### ISSUE THREAD

**Issue by thomaslevesque** [cmderdev/cmder#2019]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 

When I open a new Powershell console, I get the following message:

```
Set-PSReadlineOption : The type initializer for 'Microsoft.PowerShell.PSConsoleReadLine' threw an exception.
At C:\tools\Cmder\vendor\profile.ps1:88 char:5
+     Set-PSReadlineOption -ExtraPromptLineCount 1
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-PSReadLineOption], TypeInitializationException
    + FullyQualifiedErrorId : System.TypeInitializationException,Microsoft.PowerShell.SetPSReadLineOption
```

If I catch the error and print the inner exception, I get this message:

```
An item with the same key has already been added
```

Note: it's a fresh install of cmder on a new machine, installed with Chocolatey

**Comment by lbonvarl** [comment]
Same here

**Comment by Cosolord** [comment]
I get the same error. Did you find a solution? If i comment the block of code that throw the exception, i don't get any errors but I suspect that this is not the right way to solve the problem...

**Comment by thomaslevesque** [comment]
I found a workaround, but I don't remember exactly what it was... I *think* I just installed the latest version of PSReadLine (from source)

**Comment by Cosolord** [comment]
Thanks for the reply. After the upgrade I get the same error message. I followed the guide found on github:

[https://github.com/lzybkr/PSReadLine](url)

**Comment by JanPokorny** [comment]
I was able to workaround this issue by running these two commands:

```powershell
Install-Module PowershellGet -Force
Install-Module PSReadLine -AllowPrerelease -RequiredVersion 2.0.0-beta3
```

**Comment by EffiOvadia** [comment]
I get that error only when the language input is set the anything else other English.
it seems that while windows input is set to non English  input the module does not work at all
