### ISSUE TITLE
Bug report(?) native install-module cmdlet not recognized in vendor/profile.ps1

### ISSUE THREAD

**Issue by Banchio** [cmderdev/cmder#2021]
in vendor/profile.ps1 the following line always return false, thus enabling the embedded install-module of cmder:
$moduleInstallerAvailable = [bool](Get-Command -Name 'Install-Module' -ErrorAction SilentlyContinue | Out-Null)

I believe it should be converted to $moduleInstallerAvailable = [bool](Get-Command -Name 'Install-Module' -ErrorAction SilentlyContinue)

**Comment by daxgames** [comment]
Thanks, fix coming soon.
