### ISSUE TITLE
Cannot setup tasks for ssh

### ISSUE THREAD

**Issue by geongeorge** [cmderdev/cmder#2022]
### Purpose of the issue
- [x ] Question

### Description of the issue 

I cannot figure out how to setup `ssh user@host` as a task in cmder.
whatever I do it ends up as an error. The docs didn't help much.
````
cmd /k ""%ConEmuDir%\..\init.bat" "  -exec "ssh 'root@111.1.1.1'"
```

**Comment by daxgames** [comment]
Why would you want to?  Have you thought about [using your SSH config file to create aliases for hosts](https://www.howtogeek.com/75007/stupid-geek-tricks-use-your-ssh-config-file-to-create-aliases-for-hosts/)

**Comment by geongeorge** [comment]
I figured out how to do this:
In Cmder Tasks:
`
cmd /c ""%ConEmuDir%\..\git-for-windows\bin\bash" --login -i -c "ssh root@111.2.3.444""
`

**Comment by daxgames** [comment]
Oh it's definitely possible there are just better ways to do it

**Comment by Nilpo** [comment]
Wouldn't it be better to add your custom commands to `~/.bashrc`?

**Comment by Nilpo** [comment]
Sorry. You are using the --login option, you would need to use `~/bash_profile`.
