### ISSUE TITLE
Extremely slow startup

### ISSUE THREAD

**Issue by eparizzi** [cmderdev/cmder#2023]
I've upgraded from version `1.3.6.678` to latest `1.3.11.843` and the startup is painfully slow. More than 5s.

I've even tried downloading a fresh copy of the mini release and put it into my C: drive (which is a Samsung 960 EVO) and it's the same.

Previous version loaded almost instantly.

**Comment by daxgames** [comment]
they are virtually the same for me:

![image](https://user-images.githubusercontent.com/7318053/52180921-c344a680-27b9-11e9-95a4-06daa5bbaedc.png)

**Comment by daxgames** [comment]
If I add `/f` to `cmd::Cmder task `1.3.11` is actually 1 second faster than `1.3.6`

**Comment by SpeedySparrow** [comment]
@daxgames  Could you provide a little more info on where exactly you put /f. I have tried several scenarios but all fail.

**Comment by daxgames** [comment]
@speedyspareow it's all In the [README.md](https://github.com/cmderdev/cmder/blob/master/README.md#changing-cmder-default-cmdexe-shell-startup-behaviour-using-task-arguments)

**Comment by SpeedySparrow** [comment]
Thanks. It did improve my startup, not quite with your impressive results but still better.

**Comment by daxgames** [comment]
You can also do a `/t` and it will give you an exact time it takes to start.  How long does it take?

**Comment by SpeedySparrow** [comment]
Aah, that's where you got that timer from:-). Well, my readings doesn't make much sense to me. 3 times with and without /f. Using Launchy but directly from C:\cmder seems to yield the same weird measures.

Without /f
Elapsed Time: 39:30:34.00 (142234.00s total)
Elapsed Time: 15:28:34.00 (55714.00s total)
Elapsed Time: 69:27:42.00 (250062.00s total)

With /f
Elapsed Time: 17:22:32.00 (62552.00s total)
Elapsed Time: 65:22:7.00 (235327.00s total)
Elapsed Time: 22:21:45.00 (80505.00s total)

**Comment by daxgames** [comment]
That is still crazy slow even with /f

**Comment by daxgames** [comment]
@speedysparrow do you have an antivirus/antimalware you can disable and try again.  These could be slowing it down.  If they are you might be able to exclude cmder from scans and get it back to full speed.

Just curious what hardware you running this on, processor, hdd type, and memory?

**Comment by daxgames** [comment]
Those times can't be right the fastest says it took 15+ minutes to start

**Comment by SpeedySparrow** [comment]
True, something must be wrong with the timings. In real time:-) it's more like 5-6 seconds. I am on a Lenovo T460s with:
Win10 - ver. 1511
i5-6300U @ 2.4 GHz
20 GB RAM
But is a corporate computer with all sorts of anti-virus and what have we that I can't disable. Guess I just have to live with it. 

Still weird with the timings:-)

**Comment by daxgames** [comment]
@speedysparrow I personally know others with corporate laptops that have the similar complaints.  Sorry not anything we can do about that.

**Comment by p1va** [comment]
I also noticed slowness on my corporate laptop but after disconnecting the network drives i saw a huge improvement in startup time when opening new bash consoles.
Hope it helps.

**Comment by GF-Huang** [comment]
Is this startup speed normal? I think it is very slow.

![mI30vdKAs0](https://user-images.githubusercontent.com/4510984/79343888-96655500-7f61-11ea-852f-0251002e3201.gif)

**Comment by daxgames** [comment]
@GF-Huang yes.  If you want it to be faster but sacrifice some rarely used functionality you can add `/f` to the task launching your session.

**Comment by keyiflerolsun** [comment]
> Is this startup speed normal? I think it is very slow.
> 
> ![mI30vdKAs0](https://user-images.githubusercontent.com/4510984/79343888-96655500-7f61-11ea-852f-0251002e3201.gif)

![image](https://user-images.githubusercontent.com/57468649/79371324-dd048080-7f5c-11ea-896e-858345f48c1a.png)

startup > tasks > cmd > add arg /f

![image](https://user-images.githubusercontent.com/57468649/79371198-a464a700-7f5c-11ea-8f62-97c303d37e7c.png)

**Comment by GF-Huang** [comment]
Got it, thank you all.

**Comment by mvanwaaijen** [comment]
for me it was the GIT_INSTALL_ROOT environment setting that was missing. therefore the init.bat was taking a long time to discover where git.exe was installed. After setting GIT_INSTALL_ROOT in my environment settings, cmder starts a whole lot faster.

**Comment by AliF50** [comment]
![image](https://user-images.githubusercontent.com/22825890/94345348-333d1b80-fff3-11ea-9c73-078160cc0094.png)

For me, it takes almost 9 seconds to launch. I added the /f argument variable. Is there anything I can do to make it faster? Before I remember it was almost instantaneous.

**Comment by fakaki** [comment]
> for me it was the GIT_INSTALL_ROOT environment setting that was missing. therefore the init.bat was taking a long time to discover where git.exe was installed. After setting GIT_INSTALL_ROOT in my environment settings, cmder starts a whole lot faster.

The hint from  mvanwaaijen really helped!
Before: Cmder Startup time used to be 9 seconds on a modern Windows 10 Notebook, i5, 16 GB, SSD,...
After adding GIT_INSTALL_ROOT environment variable (system): < 3 seconds!

**Comment by AliF50** [comment]
Thanks fakaki, I got similar results as well by doing that recommendation.

For anyone wondering how to do it, add the line underlined in red here.

![image](https://user-images.githubusercontent.com/22825890/103049102-bde3d700-455e-11eb-96ca-32819703169a.png)

**Comment by doglex** [comment]
just remove those function calls , and hard code all env, since you know the very git_install location.
My demo, https://github.com/doglex/Light_Weapon/blob/master/cmder/vendor/init.bat

which is fast
0.5s in HDD
0.1s in SSD

**Comment by daxgames** [comment]
@doglex

**Comment by alextenev** [comment]
> 
> 
> @doglex that works great for a single person with a single set of settings if that person wants to maintain his own `init.bat`. I wish we could bw that lean it just will not work for the masses.

Is it possible to store these values after first run? and then change them if the need arises?

**Comment by DerDemystifier** [comment]
If you don't use Git Bash that often, you can skip the whole thing after you run CMDer for the first time.
Note: You can always just comment this line when you're using bash regularily.

![image](https://user-images.githubusercontent.com/124774256/230798028-fe9a78eb-0b8b-41ca-af44-c21a50974161.png)

**Comment by daxgames** [comment]
@DerDemystifier I don't think that means what you think it means. 😀

I do not believe that variable is used by Git bash at all.

What it is used for is to skip re-running parts of `init.bat` if you MANAUALLY rerun it and it was previously run for the current shell session.

Released  Cmder versions MUST run the `init.bat` EVERY new shell else you do not get enhancements Cmder provides.

Unreleased Cmder mentioned in a PR #2825 makes `init.bat` a run once action, after that Cmder launches Cmd.exe sessions in less than a second.

**Comment by kartikpodugu** [comment]
> just remove those function calls , and hard code all env, since you know the very git_install location. My demo, https://github.com/doglex/Light_Weapon/blob/master/cmder/vendor/init.bat
> 
> which is fast 0.5s in HDD 0.1s in SSD

GitHub link not found anymore. 
Please update it

**Comment by daxgames** [comment]
Just use t=e unreleased dev builds of cmder that does that for you without editing the cmder source.

**Comment by DRSDavidSoft** [comment]
@kartikpodugu Here are the instructions to download the latest unreleased dev builds:

1. Please open this link:  
   https://github.com/cmderdev/cmder/actions/workflows/build.yml?query=branch:development+event:pull_request+is:success
2. Open the the first **workflow run** item you see in the list
3. Navigate to the bottom of the page, under **Artifacts**, select the edition you want to use

We have some new editions of Cmder now, including **wt** or Windows Terminal builds, as well as the classic build as well. These unreleased development builds at the moment incorporate the https://github.com/cmderdev/cmder/pull/2825 speed optimizations, but aren't thoroughly tested. We are waiting for some other changes to be completed and will release these new exciting improvements in the future.
