### ISSUE TITLE
Cmder breaks Windows Snap Assist (Win+Left, Win+Right)

### ISSUE THREAD

**Issue by tomasorti** [cmderdev/cmder#2025]
Ok, I have downloaded [ConEmu versions](https://github.com/Maximus5/ConEmu/releases):

- [190108](https://github.com/Maximus5/ConEmu/releases/tag/v19.01.08) (latest)
- [180626](https://github.com/Maximus5/ConEmu/releases/tag/v18.06.26) (the one shipped with Cmder Version 1.3.11.843)

and I can confirm this problem does **NOT** appear in ConEmu.
Snap with `Win+LeftArrow` & `Win+RighArrow` works fine in ConEmu.

But it does not in Cmder. So it must be **a issue of Cmder**.

_Originally posted by @tomasorti in https://github.com/cmderdev/cmder/issues/799#issuecomment-455738784_

**Comment by tomasorti** [comment]
I have tested in many different computers and it behaves wrongly in exactly the same manner.  
Cmder gets confused with `Win+LeftArrow` & `Win+RighArrow`, and switches them.  

Start Cmder and then use `Win+LeftArrow`, which puts the windows on the left side.   
Hit `Alt+Tab` since Windows 10 losses focus on Cmder (switches to other app if you have more).  
Then try to use `Win+RightArrow`, which does not do anything...
Using `Win+LeftArrow` again will move it to the right side, which is just the opposite.

That does not happen with other apps like `FileExplorer`, `notepad` or... `ConEmu`, which works fine.  
Check it (you should show the pressed keys with something like [Carnac](http://code52.org/carnac/)):

![cmderfailstosnap](https://user-images.githubusercontent.com/2485147/52184912-bd7ead80-2819-11e9-8ca9-fb3f2577aa63.gif)

**Comment by pawelkuras** [comment]
Same thing here.  Cmder 1.3.11.843 misbehaves, but Conemu works fine.  Installed Conemu 180626, and that works fine as well.

**Comment by daxgames** [comment]
I think it's a difference between the default conemu settings and the default cmder settings.   I spent hours the other night trying to find the magic combination.  Never did find it.  If I use Cmder with default conemu settings all seems well.

**Comment by tomasorti** [comment]
> I think it's a difference between the default conemu settings and the default cmder settings. I spent hours the other night trying to find the magic combination. Never did find it. If I use Cmder with default conemu settings all seems well.

Well, I do not know what it is... but it is enough for me to stop using Cmder and stick to ConEmu.  
ConEmu author also warns about the problems that Cmder may bring:

> However, because cmder changes things, you may observe some problems which do not exist in the official ConEmu distro.

Check `Summary` on https://conemu.github.io/en/cmder.html

**Comment by daxgames** [comment]
@tomasorti That is certainly an option.  There are others as well.  

You could reset the config in the conemu gui to conemu default.  You may need to then re-add the cmder tasks.  Restart the entire session an verify if behaviour is what you'd expect.

I am not able to test this at the moment or I would.

**Comment by daxgames** [comment]
I just confirmed the approach I suggested above works to restore snap behavior seen in default ConEmu.  It is not Cmder init scripts or other components.  It is just some 'magical' combination of ConEmu settings that are defined as a part of Cmders default `ConEmu.xml`

**Comment by daxgames** [comment]
See [Cmder 1.3.11 vs. ConEmu Default Settings](https://github.com/cmderdev/cmder/wiki/Cmder-1.3.11-vs.-ConEmu---Default-Settings)
