### ISSUE TITLE
Cmder with FluentTerminal (Acrylic Effect)

### ISSUE THREAD

**Issue by DRSDavidSoft** [cmderdev/cmder#2026]
### Cmder with the Acrylic Terminal Effect
[![Cmder on FluentTerminal UWP, a transparent terminal for Windows with acryclic effect](https://user-images.githubusercontent.com/4673812/51953290-1385d680-2451-11e9-9b06-46978cf738da.jpg)](https://user-images.githubusercontent.com/4673812/51953308-213b5c00-2451-11e9-9820-30760d786b2f.png)

This is made possible by running Cmder inside [FluentTerminal](https://github.com/felixse/FluentTerminal) instead of ConEmu.

### Guide
- https://github.com/cmderdev/cmder/wiki/Seamless-FluentTerminal-Integration

### Related
- #1778
- #267

### Help & Issues
Please comment possible problems on this issue.

**Comment by DRSDavidSoft** [comment]
@Stanzilla Could you please add the "Guide" label?

**Comment by DRSDavidSoft** [comment]
👌 Thank you for the observation @ericcornelissen, I updated the wiki!
(The wiki is open to editing for anyone, so you can go ahead and edit it in the future if you see fit!)

**Comment by ThatOneCalculator** [comment]
Cool! Personally, I'll take  my default CMD in Fluent over CMDER, but CMDER will always have it s uses 😄

**Comment by SayidHosseini** [comment]
@DRSDavidSoft, I wanna install agnoster on zsh. Do I need CMDER or should I start somewhere else?

**Comment by DRSDavidSoft** [comment]
@SayidHosseini

Generally speaking, `zsh` binaries on Windows work without needing Cmder.

The Cmder package just contains [ConEmu](https://conemu.github.io/) terminal emulator, plus [Clink](https://mridgers.github.io/clink/) shell and some additional batch scripts. `zsh` _doesn't_ require nor interact with Clink and/or any batch scripts at all, so you won't need those to run `zsh`.

The ConEmu terminal within Cmder _can_ be used to run `zsh` -- but seeing that you have commented on this issue, I'd say that you are looking to run `zsh` on FluentTerminal, not ConEmu. If that's the case, you will not need Cmder _at all_ to run `zsh`.

In any case, `zsh` will require an installation of either [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10), [git-for-windows/msys2](https://gitforwindows.org/), or [Cygwin](https://www.cygwin.com/) to run. Do you have any of those?

You can also contact me on [Telegram](http://t.me/DRSDavidSoft) (same username), if you'd like to do so, so I can help you directly over there.

Cheers! ✌️

**Comment by ntamas9503** [comment]
Hi! 

I followed the instructions point by point, but I keep getting this launching Fluent Terminal in cmd: 'The system cannot find the path specified.'

Launching in Powershell:  : 
'The module '[CMDER_ROOT]' could not be loaded. For more information, run 'Import-Module [CMDER_ROOT]'.
At line:1 char:3
+ . '[CMDER_ROOT]\vendor\profile.ps1'
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: ([CMDER_ROOT]\vendor\profile.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoLoadModule'

I setup the environment variable as the instructions told:
![Capture](https://user-images.githubusercontent.com/30979609/83055262-ea308700-a053-11ea-856d-00f76adf1afc.JPG)

Can you help me out with this?
Thanks!

**Comment by DRSDavidSoft** [comment]
@ntamas9503 Hey there, the `[CMDER_ROOT]` is actually the place holder for the Cmder path.

### Please replace it like this:
`[CMDER_ROOT]` → `%CMDER_ROOT%`

and it should work!

**Comment by ntamas9503** [comment]
Yeah, it worked with specifying the full path. Thanks for your help!

**Comment by Bilibili-toast** [comment]
Hello author, I have set everything up in FluentTerminal, but the acrylic effect is not achieved.

**Comment by DRSDavidSoft** [comment]
@Bilibili-toast Hi there, please check if other fluent/metro UI/store apps have the same issue.

If the problem only exists in FluentTerminal, please create a new issue here:
https://github.com/felixse/FluentTerminal/issues

Also, please checkout our guide to use WindowsTerminal with Cmder, which also has the acrylic effect (blurred behind):
https://github.com/cmderdev/cmder/wiki/Seamless-Windows-Terminal-Integration
