### ISSUE TITLE
Workarounds for very slow I/O

### ISSUE THREAD

**Issue by teknopaul** [cmderdev/cmder#2028]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [* ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 

Given that cmder is slow https://github.com/cmderdev/cmder/issues/188

And probably that is an upstream issue.

Could we have some work-arounds, if you know a command is going to output a lot you can >:NUL  or 2>:NUL  but if you only find out the command is verbose when running it, you have to sit and wait, or force it to crash.
e.g. running mvn versions:set in my machine takes >10 mins in cmder and a matter of seconds in cmd.exe depending on the size of the repo and the warnings it prints.

Workarounds could be keyboard shortcuts to swallow output after its started until the command ends.

Perhaps Ctrl - O to stop outputting stdout  and Ctrl - E to stop outputting error.
Perhaps some way to freeze all output, until the command finishes.
Perhaps some way to redirect to a file instead of screen after the command has started.
Perhaps some way to shrink the screen to size 0 and then printing output would be a noop.

Clearly this would be hard/impossible for console apps but for command line apps it should be feasible.

**Comment by daxgames** [comment]
Do you have this issue running straight cmd.exe in conemu?  Have you tried other shells in cmder like Bash or Powershell?  They might be faster, if they are it might be an issue with, [Clink](https://mridgers.github.io/clink/), the cmd.exe shell enhancement package we use.

I'm afraid what you are asking is beyond the scope of the Cmder team.  Cmder is a curated set of packages tied together with some scripts and configuration to provide an enhanced shell env for Windows users wanting a more Linux like experience.  Perhaps the macros you ask for could be added to, [Conemu](https://conemu.github.io/), the terminal emulator we use.

**Comment by AminLA** [comment]
@teknopaul 

you can try these settings

![cmder-setting-feat-ansi_exec](https://user-images.githubusercontent.com/7601951/58408566-a56cbb80-80a0-11e9-89a3-6fe4c0948c46.png)
![cmder-setting-feat-comspec](https://user-images.githubusercontent.com/7601951/58408567-a56cbb80-80a0-11e9-9b5a-06744d909682.png)
![cmder-setting-feat-transparency](https://user-images.githubusercontent.com/7601951/58408568-a6055200-80a0-11e9-8543-015f1aa3e71b.png)
![cmder-setting-main](https://user-images.githubusercontent.com/7601951/58408571-a69de880-80a0-11e9-8852-d3661f7b95f8.png)
![cmder-setting-main-appearance](https://user-images.githubusercontent.com/7601951/58408572-a69de880-80a0-11e9-9890-43ea8af459f4.png)
![cmder-setting-main-size_pos](https://user-images.githubusercontent.com/7601951/58408573-a69de880-80a0-11e9-9e45-ce64e974a88c.png)

**Comment by rjo67** [comment]
I know this issue has been closed, but maybe my experience will be useful for somebody. 

I had a similar problem running a maven build (with console output) in git-bash in cmder 1.34 (win-7). In native git-bash the build finished in 2:41, in cmder it was one minute slower.

Switching off transparency and the enhanced progress bars (as suggested in the screenshots above) worked for me. Now the build finishes in 2:29, which is the same if not better then git-bash. :-)
