### ISSUE TITLE
"Create new tab" create more than one tab

### ISSUE THREAD

**Issue by zonky2** [cmderdev/cmder#2029]
Version: 161206

"Create new tab" create the same number of opend tabs instead of one - eg: I have 4 tabs open and click "Create new tab" - I get 4 more tabs (sum 8) ...

**Comment by daxgames** [comment]
@zonky2 Can you clarify?  Is this an issue you are having or a feaqture request?

**Comment by zonky2** [comment]
@daxgames this is a bug - adding should only create one tab at a time and not several

**Comment by daxgames** [comment]
@zonky2 when I click `Create New Console`, I assume that is what you meant.

I get exactly that, one tab with one new console.
