### ISSUE TITLE
Add an option to have cmder start in the current directory

### ISSUE THREAD

**Issue by pimterry** [cmderdev/cmder#203]
I typically want a command line in the current folder I'm viewing in windows explorer. With cmd, I just type `cmd` into the address bar, and it opens in the current folder.

If I type `cmder` however, it opens in my home directory. I'm currently getting around this by renaming the cmder executable to cmder-raw, and creating a cmder.bat like:

``` bat
cmder-raw %CD%
```

(open 'cmder-raw', with the current directory as an argument, which apparently opens cmder there)

This does exactly what I want, but it's a bit hacky, and it results in a very very brief flash on non-cmder console window appearing, before cmder opens. It'd be great if cmder could add an option to act like this natively.

**Comment by futurechan** [comment]
:+1: I would love the ability to type ```cmder``` into the address bar of file explorer and have it open in that directory!

**Comment by mrgrain** [comment]
":+1: I would love the ability to type cmder into the address bar of file explorer and have it open in that directory!"

me too!

**Comment by vitr** [comment]
:+1:

**Comment by dvlsg** [comment]
:+1: Agreed, I really miss this ability when working with cmder.

**Comment by hstarorg** [comment]
Me too.

**Comment by kjeske** [comment]
Just go to cmder settings, then Tasks tab and set {cmd} task full command to:

````
cmd /k "%ConEmuDir%\..\init.bat" -new_console:%__CD__%
````

**Comment by JanSchulz** [comment]
If you register cmder, then `right click -> Cmder here` works that way. 

For a solution which works as you currently work: add a startup batch file (`c.bat`) in a directory which is in the normal path (not the enhanced one in cmder!), which calls cmder with `cmder %CD%` (or `C:\Users\jschulz\Dropbox\Programme\cmder\cmder.exe %CD%` in my case). Its a little flickery, as the batch file opens ina window, but cmder comes up right in the right dir.

[Note that both solutions need a recent development build as there was for some time a bug which prevented the "start with a path"-scenario; not sure if the last release had this bug or not]

**Comment by hstarorg** [comment]
@kjeske Thank you, it's available.

**Comment by onewhaleid** [comment]
This is not working for me. cmder just opens in my home directory. What am I doing wrong?

![cmder](https://user-images.githubusercontent.com/11261876/36889750-6f53e50a-1e4f-11e8-9a39-5fdcac4121ce.png)

**Comment by daxgames** [comment]
Hardcoding the task is not the right answer.  Most of you want to be able to open a cmder session in a folder from explorer.  This should work using `cmder /REGISTER [USER|ALL]`.  This adds the `Cmder Here` context menu you can get to by a right click on the folder.

In all situations I would recommend downloading the latest version of cmder and make sure your tasks do not use the `-new-console` argument at all.

What exactly are the rest of you trying to do here, and I do mean 'exactly'.  Give me the process step by step from the very beginning.  Are you in explorer and want to open cmder in a right clicked folder?  Are you in a Windows `cmd.exe` or a `cmder` session and want to open cmder in the current folder by typing `cmder [something]`? Or clicking a shortcut icon?  I believe cmder can indeed work in all these sutuations, just need to know what you,are trying to do.

In all situations I would recommend downloading the latest version of cmder and make sure your tasks do not use the `-new_console` argument at all.

**Comment by onewhaleid** [comment]
I wanted to navigate to a folder in explorer, then type `cmder` into the explorer address bar, and have cmder open up a new console in that folder.

**Comment by daxgames** [comment]
@onewhaleid did you try my suggestions?  I have not with your use case.

**Comment by onewhaleid** [comment]
@daxgames the address bar method did not work. I am using the context menu instead.

**Comment by daxgames** [comment]
@onewhaleid I tried various things also and could not make that option work.  The context menu is your best option for explorer.

**Comment by alex-jitbit** [comment]
Why is this closed?

I want to type "cmder" in my file namager (Totl Commander, Far, etc) and I want it to start in current dir, **just like `cmd` does**

**Comment by Stanzilla** [comment]
@alex-jitbit PRs welcome!

**Comment by thewingit** [comment]
@daxgames As said, we want to be able to type `cmder` in the Windows explorer's address bar and the console opens up in that directory. I used fix from @pimterry and that seems to work, but as he sais, its a bit hacky and that quick flash of the standard cmd window is a little annoying...

**Comment by daxgames** [comment]
This is fixed try a nightly build.  See the readme.md

**Comment by NicolasZapata** [comment]
Hi there!!
The only i do y add the file location in enviromente varables, but only copy and paste all cmder's folder, not the bin, and that work!!! (for me).
