### ISSUE TITLE
Command history

### ISSUE THREAD

**Issue by BDein** [cmderdev/cmder#2030]
Hi great Folks,

A couple of technical questions:

1. Current history is missing in history file, but arrow-up and down works fine, but I can't search the history, which is a big problem. I know exit and restart puts history to the file, but that's not a smart way. What is the smart way?
2. How does the history work? 
   2.1 ie. which role does doskey play?
3. How do I force the keyboard buffer history to be saved to the history file (on demand)?
  3.1. Is the a connection to doskey macro: "**save=DOSKEY /history $g$g "<path>\cmd_history.log**"
    3.1.1. If so, how do I use this, as it doesn't work out of the box?

**Comment by daxgames** [comment]
My answer to you remains the same but I will try to clarify.  History is maintained by clink which we did not write nor do we maintain it.  If you have questions about clink and how it works with history please ask the clink developer.

**Comment by daxgames** [comment]
## Cmder 1.3.11 with Clink v0.4.9

`clink set history_io 1`  changes this behaviour to update the history file after every command.
