### ISSUE TITLE
cmder.net window crashes leading comemu hanging headless.

### ISSUE THREAD

**Issue by cbuteau** [cmderdev/cmder#2032]
### Purpose of the issue
- [ x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 

Hello,

I have noticed an odd bug.
It seems cmder.net crashes the window leaving all your running ConEmu processes running.

I thought the whole thing was crashing and I was just starting a new instance until I had a port in use error 
and I checked my ProcessExplorer and found a whole process tree hanging out.

I had recently switched my settings so it does not prompt me for each new tab and it always starts cmd processes in admin mode.

But I do open a lot of tabs and sleep and awaken my windows 10 work system a lot.

![image](https://user-images.githubusercontent.com/1906839/52210042-cab88e00-2853-11e9-9c72-de792762eedd.png)

**Comment by cbuteau** [comment]
I don't know.
Is the window s separate process I can get a crash dump of.

**Comment by daxgames** [comment]
Did you find a solution?

**Comment by cbuteau** [comment]
It has not occurred lately ...
It occurred two or three times 
and I discovered it because a program I usually run reported a port in use...and I thought are those processes out there....and they were....

No idea how to reproduce.
Any idea on how to gather information after the fact?

I closed it by accident.
I was commenting from my phone and I think I hit the wrong button.

**Comment by cbuteau** [comment]
Hello,
I noticed it did not happen at home and I checked the differences.
Both systems I was launching console windows with admin privileges.

The home system I was launching the Cmder.net shell with admin privileges also.

I switched it to the same at work and I have not seen the problem.

I am going to close this for now.
If the problem occurs again I will reopen.

**Comment by cbuteau** [comment]
Reopening ...this problem is annoying me today...
It may be tied to minimize on the main window...

Is there way I can turn on logging or something or do I have to fetch the source and compile to gather more information?

**Comment by daxgames** [comment]
There is no such thing as a cmder.net window.  It is all conemu, if there is an issue with the window crashing and you can provide reproduction steps I suggest you report it to the conemu devs.
