### ISSUE TITLE
Could not load library msys-python2.7.dll

### ISSUE THREAD

**Issue by abdelhalim** [cmderdev/cmder#2033]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [x] Question

### Description of the issue 
I'm trying to run vim with a plugin for autocomplete, when I do that it keeps giving me error for not finding python although I have it in my path, tracing this further seems vim cannot find the file msys-python2.7.dll (or corresponding one for python 3 msys-python3.6m.dll) in the Cmdr path

I'm not sure if I'm supposed to add this myself or what? If this was stripped out for size is it possible to add it now for this need? or may be create Mega distribution with python and this file?

**Comment by daxgames** [comment]
Python is not a part of Git for Windows, a component of Cmder.  you might be able to make it work if you add a folder that contains it to the path.
