### ISSUE TITLE
Best fix for Ctrl + C not working as expected?

### ISSUE THREAD

**Issue by Manish-Giri** [cmderdev/cmder#2034]
So, today I came across the issue where Ctrl + C doesn't work (at least for node.js). I've come across these related issues - #1234 #1258 #671 

From what I can see, the two possible fixes are - use legacy console, or right click the process and terminate/kill.

Is there another better way?

PS - I'm not on an Insider build.

**Comment by crutchcorn** [comment]
I'm running into the same problems on stable and am wondering the same

**Comment by daxgames** [comment]
Make sure `Ctrl+c` is not set to copy text in:

![image](https://user-images.githubusercontent.com/7318053/54469669-7ddca700-4771-11e9-8a19-69a6e40e8f95.png)
