### ISSUE TITLE
Run notepad after run Cmder.exe?

### ISSUE THREAD

**Issue by goodandrewsoft** [cmderdev/cmder#2036]
How run notepad after run Cmder.exe?

For example "c:\MyProgarms\cmder\Cmder.exe /START c:\windows\notepad.exe"

Does't work....

**Comment by daxgames** [comment]
A batch file that runs one then the other:

Cmder_notepad.bat

```
Cmder.exe
Notepad.exe
```

**Comment by goodandrewsoft** [comment]
Ok , i see, you very smart 🥇 :)

How run "ping exe" in cmder window

like cmd.exe /k "ping.exe"
but 
cmder.exe /k "ping.exe" or something...

**Comment by daxgames** [comment]
Was not trying to be 'smart'.  What you ask is not possible, cmder is not a shell cmd.exe is.  I simply answered your question with less detail than you wanted.

**Comment by goodandrewsoft** [comment]
> is not possible
I'm doubt

**Comment by daxgames** [comment]
You may be able to create a task in cmder that does this and then point to that task via a cmder command line arg, but you cannot do this with cmder.exe alone.  If anyone knows this I do, I am one of the maintainers of this repo.

I am however on a phone at the moment trying to answer your questions.

**Comment by goodandrewsoft** [comment]
I'm done with it.
**Hardcoded** info (don't have much time).
The command:
```
ConEmu.exe /Icon F:\Run\Utilties\System\cmder\icons\cmder.ico /Title Cmder /LoadCfgFile F:\Run\Utilties\System\cmder\config\ConEmu.xml -Single -run {run} ping
```

The new task `run`:
`cmd /k "%ConEmuDir%\..\init_run.bat"  -new_console:d:%USERPROFILE%`

The batch file `init_run.bat`:
just make copy `init.ru` to `init_run.bat` and add this lines to the end of copied file:
```
@if [%1]==[] goto end
@echo starting %1
@call %1
:end
```

**Comment by daxgames** [comment]
Cool, Now that you have a task you can:

```
Cmder /task [task_name]
```

**Comment by goodandrewsoft** [comment]
![image](https://user-images.githubusercontent.com/2471892/52494005-858ab800-2bd5-11e9-98ae-5c5fafe7d99c.png)
My Cmder  - Version v1.2 - i think

**Comment by daxgames** [comment]
Time to upgrade.  Also you may want to put your script in '%cmder_root%\config`

**Comment by daxgames** [comment]
@goodandrewsoft Make sure you follow the instructions in the readme.md file before upgrading.  To ensure you don't lose any config.
