### ISSUE TITLE
Quoted PowerShell script parameters with space characters trimmed after first space

### ISSUE THREAD

**Issue by alekdavis** [cmderdev/cmder#2038]
### Purpose of the issue
[X] Bug report (encountered problems/errors)
[ ] Feature request (request for new functionality)
[X] Question

### Description of the issue 
If I pass a command-line parameter value containing a space character enclosed inside of double quotes (e.g. `-Config "A B C"`) to a PowerShell script, the value gets trimmed after the first space character. If I pass the same value enclosed in single quotes, it works as expected. In PowerShell, either double or single quotes produce the same correct result.

### How to duplicate

Save the following code as a PowerShell script with the name `TestQuotes.ps1`:

```PowerShell
param
(
    [string]
    $Config = $null
)

"Config = $Config"
```
Run it in cmder as:

```PowerShell
PowerShell .\TestQuotes.ps1 -Config 'A B C'
PowerShell .\TestQuotes.ps1 -Config "A B C"
```
Here are the results from cmder:

![cmder](https://user-images.githubusercontent.com/2113681/52597546-1648da00-2e08-11e9-9ace-350d44fbb734.png)

Here are the results from PowerShell (it works the same in PowerShell ISE):

![powershell](https://user-images.githubusercontent.com/2113681/52597613-43958800-2e08-11e9-935c-45c5825a3bb6.png)

It gets even more weird. If you have a set-based string parameter with a default value that you do not pass via command line, such as:

```PowerShell
param
(
    [ValidateSet("X", "Y", "Z")]
    [string]
    $Mode = "X",
    [string]
    $Config = $null
)

"Config = $Config"
```
executing

```PowerShell
PowerShell .\TestQuotes.ps1 -Config "A B C"
```
will result in error:

![cmder2](https://user-images.githubusercontent.com/2113681/52597940-33ca7380-2e09-11e9-8a78-87189965a71d.png)

It works as expected (i.e. fine), in PowerShell and PowerShell ISE. 

Could someone explain what is going on here? Thanks.

P.S. I'm using the most recent version of cmder with `ConEmu 180626 [64} {Preview}`.

**Comment by daxgames** [comment]
Your first example works the same for me in both Cmder and Powershell:

![image](https://user-images.githubusercontent.com/7318053/54476750-515b7600-47d7-11e9-9126-65ad04c17b4f.png)

and so does the second:

![image](https://user-images.githubusercontent.com/7318053/54476806-cfb81800-47d7-11e9-9c5e-70d2578838c1.png)

What is the content of the `$profile` file?  I do not have a `$profile`  maybe something in yours is making Powershell outside Cmder behave differently?

**Comment by alekdavis** [comment]
Hmmmm... The `$profile` variable on my system points to a non-existent file. I can still duplicate the same problem. And it looks like I'm not the only one (this was originally reported to me by a user who had the same issue and thought there was something wrong in my script). Is there any global settings in `cmder` that could've caused cause this (I did not make any changes to `cmder`)?

**Comment by daxgames** [comment]
We are the same.  No `$PROFILE` default cmder settings. I will verify that by downloading a fresh copy and trying again.

**Comment by daxgames** [comment]
Confirmed my exact same results with fresh default Cmder 1.3.11 version. Both Cmder Powershell and Powershell work and fail in exactly the same ways.

**Comment by daxgames** [comment]
I was able to duplicate your failed results launching `powershell .\test.ps1 -Config "A B C"` from both `Cmd::Cmder` the default Cmder session type and `Windows Cmd.exe Prompt` so this is not a Cmder issue.

**Comment by alekdavis** [comment]
It looks like the problem occurs when you call the script by referencing PowerShell. If this is how `cmder` executes PowerShell scripts, how are you supposed to pass quoted parameters to it (say, a parameter value contains a space character)? I posted a question at StackOverflow for this: https://stackoverflow.com/questions/55201798/why-does-powershell-not-recognize-quoted-parameters

**Comment by daxgames** [comment]
As you can see in my last it's not just cmder but also cmd.exe so it's not a cmder issue.

**Comment by alekdavis** [comment]
There is a couple of responses on StackOverflow that explain why it is behaving this way.

**Comment by daxgames** [comment]
Cool will look when I get home.
