### ISSUE TITLE
Wrong cursor position when using cmder with vscode

### ISSUE THREAD

**Issue by lonelykid** [cmderdev/cmder#2039]
### Purpose of the issue
- [x ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 

The cursor position is not right when using with vscode. 
![d](https://user-images.githubusercontent.com/2936633/52658700-af8bf500-2ec9-11e9-98c8-e23ff1693524.gif)
There's a mismatch when moving the cursor to the left and back.
I understand this might not be the issue of cmder itself. But I wish to get some information about how to fix this.
My setting for the shell:
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe",
    "terminal.integrated.env.windows": {"CMDER_ROOT": "C:\\Users\\xxx\\apps\\cmder"},
    "terminal.integrated.shellArgs.windows": [
        "/k",
        "C:\\Users\\xxx\\apps\\cmder\\vendor\\init.bat /f"
    ],

**Comment by TylorShin** [comment]
👍

**Comment by lonelykid** [comment]
It turns out replacing the lambda λ prompt with dollar $ solves the problem.

**Comment by daxgames** [comment]
@lonelykid and did you do that by editing the `%cmder_root%\vendor\clink.lua`?

If so a better way is [here](https://github.com/cmderdev/cmder/issues/2042)

**Comment by lonelykid** [comment]
@daxgames Thank you! that seems a better solution. The problem appears to be quite common. Do you also have a script for bash/powershell?
