### ISSUE TITLE
Document necessary config changes

### ISSUE THREAD

**Issue by sqrt** [cmderdev/cmder#2040]
I find it very hard to keep track of what changed between releases, and what I need to do to migrate my configuration. It regularly happens that some config location changes, or the name of options, or something like that, and we have to find the respective PR to see what actually changed.

The release notes/Changelog is not exactly helping, case in point for 1.3.7:

> *    Revert "replace user-aliases with user_aliases"
> *    replace user-aliases with user_aliases
> *    better fix for #1265
> *    Revert "sanitize dir before assigning to prompt"
> *    sanitize dir before assigning to prompt
>
> [...]
> 
> Dax T Games (8):
> 
> *    Revert "Ignore %cmder_root%\config (#1945)"
> *    Ignore %cmder_root%\config (#1945)
> *    Add /f for fast init. (#1942)
> *    add diag helper scripts and adds to the path (#1918)
> *    Fix #1806 #1675 (#1870)
> *    Profile.ps1 (#1796)
>
> [...]
> 
> Dax T. Games (42):
> 
> *    Fixed move of default conemu.xml to the vendor folder

How am I supposed to understand what is necessary from user perspective to migrate configuration? Am I supposed to check all PRs and see what exactly has changed?

It would be great to get a "Changes Required" chapter in the release notes, with easy-to-grasp required actions such as "Rename you ``user-aliases`` file to ``user_aliases``", "Move your ``conemu.xml`` to the vendor folder", "Add the following line to ``Profile.ps1 ``" or whatever.

**Comment by daxgames** [comment]
@sqrt Sorry but I am unaware of whet config changes you are referring to.  We have not in any recent changes required any user changes to update.

There should be no need for a user to manually migrate configuration assuming you follow some simple rules:

1.  NEVER change anything in the `%cmder_root%\vendor` folder.
2.  Keep all user config stored in `%cmder_root%\config` and `%cmder_root%\bin`
3.  Upgrade using these [instructions](https://github.com/cmderdev/cmder#upgrading). _Note: These need to be updated to say "`[cmder_root]/config/user[-|_]conemu.xml`"_

Any time we have changed a config file name/location/format/content we have written in automation to handle that change for the user.  Cmder should see that changes are required and do all required changes for you on first run after upgrading.  If this is not the case can you please provide a detailed example of where this did not work for you.

**Comment by daxgames** [comment]
README.md updated #2041

**Comment by daxgames** [comment]
@sqrt was the above helpful?

**Comment by daxgames** [comment]
Closing due to lack of response from OP.
