### ISSUE TITLE
Cannot delete Chinese characters.

### ISSUE THREAD

**Issue by SCLeoX** [cmderdev/cmder#2042]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 

I freshly downloaded Cmder Mini version from cmder.net. I pasted in some Chinese characters "大家好啊", and tried to delete them with backspace. It appears that Cmder only deletes half a character a time. However, it actually, deletes the character but it is displayed incorrectly.

![2019-02-19_18-35-41](https://user-images.githubusercontent.com/13428807/53055308-31a18e00-3475-11e9-8314-9767ee1a85e2.gif)

I am sure this is an issue with Cmder because if I go to cmd, it works perfectly.

![2019-02-19_18-36-51](https://user-images.githubusercontent.com/13428807/53055351-5f86d280-3475-11e9-8ef9-d13b1615b7c1.gif)

I am using the default configuration of Cmder. The region of my computer is United States.

![applicationframehost_2019-02-19_18-38-07](https://user-images.githubusercontent.com/13428807/53055407-90670780-3475-11e9-96d0-5cac1accddff.png)

It should be reproducible by simply copying those characters (大家好啊) into the window. The issue is, however, **not** specific to those characters. Any other Chinese character has the same issue, too.

**EDIT:** The version of Cmder is 1.3.11.843.

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)

**Comment by SCLeoX** [comment]
@Stanzilla No, it is not a problem with ConEmu. As demonstrated by the second gif. As soon as I type enter cmd mode in the very same ConEmu window, it works. The issue only occurs with cmder.

**Comment by Stanzilla** [comment]
Oh probably clink then?

**Comment by SCLeoX** [comment]
It does seem an issue with clink: https://github.com/mridgers/clink/issues/514.

**Comment by Stanzilla** [comment]
that's unfortunate, clink dev is pretty dead. he only commits random stuff once a year or so and does not respond to tickets etc.

**Comment by daxgames** [comment]
@SCLeoX have you tried:

Create `%cmder_root%\config\my_prompt.lua`:

```
function my_prompt_filter()
    cwd = clink.get_cwd()
    prompt = "\x1b[1;32;40m{cwd}{git}{hg}{svn}\x1b[1;30;40m{lamb} \x1b[0m"
    new_value = string.gsub(prompt, "{cwd}", cwd)
    clink.prompt.value = string.gsub(new_value, "{lamb}", "$")
end

clink.prompt.register_filter(my_prompt_filter, 1)
```

Restart cmder.

**Comment by SCLeoX** [comment]
@daxgames I just tried it. Sadly, the issue still exists.

**Comment by daxgames** [comment]
Did the prompt change to a `$`?

**Comment by SCLeoX** [comment]
@daxgames Yes, the prompt did change to $, but I still cannot delete the content properly.

By the way, is this reproducible in your computer?

**Comment by lonelykid** [comment]
Unable to reproduce your problem. I'm using a portable full version of cmder

**Comment by SCLeoX** [comment]
Ahhh this is so painful. I just reset Windows and the issue persists. I rarely use Chinese in my console and I can still use it as it is only a visual glitch, but this is so painful.

I really hope one day this can be fixed. T_T

**Comment by daxgames** [comment]
It is definitely clink.  I can not reproduce the issue with Cmder - clink(Left) but can reproduce it with Cmder with Clink(Right): 

![2019-02-28_17-11-42](https://user-images.githubusercontent.com/7318053/53602436-cb0b2700-3b7c-11e9-9a31-0549d3bcf4a9.gif)
