### ISSUE TITLE
after updating vendor git-for-windows it no longer uses the user-profile.sh file in config

### ISSUE THREAD

**Issue by Rab815** [cmderdev/cmder#2043]
Hello,

So I updated the vendor version of git-for-windows with the latest 2.20.1 with the portable version...  I renamed the old version directory git-for-windows.old and extracted the newer version into a git-for-windows directory in cmder/vendor....  the previous version I was using somehow always loaded the C:\cmder\config\user-profile.sh file for user definied aliases.  Luanching the old version via 

cmd /c "%ConEmuDir%\..\git-for-windows.old\bin\bash --login -i" -- uses the user-profile.sh file listed above

cmd /c "%ConEmuDir%\..\git-for-windows\bin\bash --login -i"  -- however launching the newer version doesn't seem to use the user-profile.sh file... nothing else has changed.  

Is this a bug or something else I'm missing?

Doug

**Comment by daxgames** [comment]
@RAB815 updating the way you did requires an additional step.

```
Copy "%cmder_root%/vendor/cmder.sh" "%cmder_root%/vendor/git-for-windows/etc/profile.d/cmder.sh"
```

If `%cmder_root%/vendor/cmder.sh` does not exist, and it probably doesn't, download it [here](https://raw.githubusercontent.com/cmderdev/cmder/master/vendor/cmder.sh)

**Comment by Rab815** [comment]
I did this and it's still not using the sh file in the config.... my goal
here was actually not to use the vendor version of git as I install the
windows version in the Program Files/Git directory, however when I do that
it seems it wants to use the bash.bashrc file in C:\Program
Files\Git\etc\bash.bashrc instead of the sh file in the config of cmder,
this way my commander configuration is portable, and... all my aliases
carry with me from machine to machine but I have one centralized location,
namely the windows location for the git install that can be updated on it's
own.

Is this scenario possible?

**Comment by daxgames** [comment]
If you installed that it is what is being used.  Verify feom inside cmder cmd session with:

```
where git
echo %git_install_root%%
```

Copy the file I suggested to the same folder in the Windows installed path.
