### ISSUE TITLE
Console buffer is empty after running "top" - command (WLS)

### ISSUE THREAD

**Issue by maksiik** [cmderdev/cmder#2044]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

**Comment by maksiik** [comment]
Console buffer is empty after running "top" - command (WLS).

This happening on WLS localhost and on remote machines over SSH for example.

**Comment by daxgames** [comment]
Does the same thing happen running wsl outside cmder?  What about running wsl in native conemu?

**Comment by maksiik** [comment]
> Does the same thing happen running wsl outside cmder? What about running wsl in native conemu?

Yeap same thing happen.

**Comment by daxgames** [comment]
@maksiik Then it's not cmder.
