### ISSUE TITLE
Aliased commands don't work with &&

### ISSUE THREAD

**Issue by hurani** [cmderdev/cmder#2046]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 

I aliased del=trash so whenever I run del it actually calls the [trash command](https://github.com/sindresorhus/trash-cli).

If I try running something like javac *.java && del *.class, the del being called here is the actual del command and not the trash command.

**Comment by daxgames** [comment]
I assume the alias works on it's own?

Cmder uses `doskey` to provide basic macro/alias functionality to cmd.exe shells.  The issue you describe is a limitation of `doskey` and is not something that can be fixed.

**Comment by hurani** [comment]
yes it does work on its own. thanks.

**Comment by daxgames** [comment]
@hurani If you want true alias support the use a bash shell with cmder.
