### ISSUE TITLE
.msg files within git-for-windows\mingw64

### ISSUE THREAD

**Issue by ThreepE0** [cmderdev/cmder#2047]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 

.msg files are being scanned and flagged by my corporate policy;  Not a "Cmder" problem really I understand, but .msg files are emails as far as Windows is concerned... is there any way to use a different file extension for these files?

**Comment by Stanzilla** [comment]
Not a Cmder issue

**Comment by ThreepE0** [comment]
I understand this isn't a Cmder issue, but in some enterprise environments, it causes a large issue that makes Cmder basically unusable;  If it were possible to have the package that relies on these .msg files look for .msgs files instead, the problem would be resolved.  Can someone at least point me in the right direction, or give me an opinion as to whether this may be possible, as opposed to the off-hand 'not a Cmder issue' reply?

**Comment by Stanzilla** [comment]
Well can't your company whitelist those files in that dir? They are coming from tcl and tk libraries used by mingw64
