### ISSUE TITLE
Cmd.exe takes >30 seconds to load when opening Cmder

### ISSUE THREAD

**Issue by shane-moore** [cmderdev/cmder#2048]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

**Comment by daxgames** [comment]
@shane-moore Details?  Mine opens in 1-4 seconds max, something else on your machine is probably causing this. 

Corporate PC or home?  Anti-Virus/Malware can be an issue.

Have you tried all cmder shell types cmd, bash, and powershell?

**Comment by daxgames** [comment]
Closing to lack of response.

**Comment by daxgames** [comment]
Closing to lack of response.
