### ISSUE TITLE
Multiple errors when running init.bat

### ISSUE THREAD

**Issue by happy-sadan** [cmderdev/cmder#2049]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue 

I was trying to make Visual Studio Code use Cmder as its terminal, which requires running `vendor\init.bat`.

At first I wasn't having any issues, but soon enough, every time I tried running `vendor\init.bat`, whether in VS Code or in Command Prompt, I got the following errors :

    The system cannot find the path specified.
    The system cannot find the path specified.
    The system cannot find the path specified.
    The system cannot find the path specified.
    The system cannot find the path specified.
    'debug-output' is not recognized as an internal or external command,
    operable program or batch file.
    'debug-output' is not recognized as an internal or external command,
    operable program or batch file.
    The system cannot find the path specified.
    'debug-output' is not recognized as an internal or external command,
    operable program or batch file.
    'read_version' is not recognized as an internal or external command,
    operable program or batch file.
    'validate_version' is not recognized as an internal or external command,
    operable program or batch file.
    'enhance_path_recursive' is not recognized as an internal or external command,
    operable program or batch file.
    'enhance_path' is not recognized as an internal or external command,
    operable program or batch file.
    'run_profile_d' is not recognized as an internal or external command,
    operable program or batch file.
    Creating initial user-aliases store in "C:\Users\trist\Google^ Drive\Software\cmder\config\user-aliases.cmd"...
    The system cannot find the path specified.
    The system cannot find the path specified.
    'debug-output' is not recognized as an internal or external command,
    operable program or batch file.
    Creating user startup file: "C:\Users\trist\Google^ Drive\Software\cmder\config\user-profile.cmd"
    The system cannot find the path specified.

**Comment by daxgames** [comment]
Did you follow our [VSCode Wiki](https://github.com/cmderdev/cmder/wiki/Seamless-VS-Code-Integration)

**Comment by happy-sadan** [comment]
Yes, but it doesn't matter, as I said I get the same error whether I use VS Code or a terminal

**Comment by daxgames** [comment]
What version of Cmder.  I just opened `cmd.exe` changed to the Cmder folder and ran `vendor\init.bat`.  All works as expected.

**Comment by happy-sadan** [comment]
I'm running version 1.3.6.678 on Windows 10

**Comment by daxgames** [comment]
@happy-sadan have you tried the latest release?

**Comment by happy-sadan** [comment]
I have now, same problem. But the last error message, i.e. "Creating user startup file", seems to be pointing to where I first installed Cmder, not it's current directory.

**Comment by daxgames** [comment]
I don't see how that's possible its portable software it should work on any windows system the same way for everyone.

Do you have an environment variable called `cmder_root` set outside Cmder in Windows?

Open `cmd.exe` and type `set cmder` if anything comes back set each to nothing like:

```
set cmder_root=
set cmder[whatever]=
```

Then change to path you expanded Cmder to and type `vendor\init.bat`.

If the above works delete the environment variables from Windows.  If you don't know how Google `setting environment variables windows 10`.

**Comment by happy-sadan** [comment]
I kept trying to find a fix without success, until Windows forced an update on me, which apparently made it work. The only difference I could notice from before was that the `CMDER_ROOT` user variable was finally pointing to the current Cmder directory, as opposed to the old one (which I forgot to mention before, sorry about that), which was seemingly causing the error.

The reason I couldn't fix this earlier was that when I tried to edit the `CMDER_ROOT` user variable, then restarted my system, it would reset to the old path where I installed Cmder, **which contained a space**.

**Comment by daxgames** [comment]
Glad its working FWIW the space in the path shouldn't matter I use it that way every day.

**Comment by RoyLarson** [comment]
Another program overwrote a setting for me that took a little while to find and I am hoping this helps someone else.
In the Settings->Integration->ComSpec
at the bottom section there was a value in 
![image](https://user-images.githubusercontent.com/30960043/56064846-d4b9aa00-5d38-11e9-9ddb-8b1e8dd6ab3a.png)
when I cleared that value all of the "The system cannot find the path specified" error disappeared.
