### ISSUE TITLE
Cmder console 'hijacked' after running 'start-ssh-agent'

### ISSUE THREAD

**Issue by pixelbrad** [cmderdev/cmder#2050]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Description of the issue 
Hello, not quite sure where to post my concerns, so I'm sorry if this is the wrong place. Just need a little guidance.

Whenever I execute `start-ssh-agent` in Cmder, it seems like the console gets 'hijacked' by another console. Here's an example of my situation:

```
C:\Users\Brad
λ start-ssh-agent
Found ssh-agent at 6752
Found ssh-agent socket at /tmp/ssh-GYaVEG9e6nDE/agent.18340
Microsoft Windows [Version 10.0.17134.556]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\Brad>
```

Prior to executing `start-ssh-agent`, I'd be entering commands beside the lambda symbol (one line under my CWD), and my CWD is a nice green colour. After executing `start-ssh-agent`, all of my commands are entered after `C:\Users\Brad>` on the same line, and all my console text is the same colour. 

I can get out of this by simply executing `exit`, and them I'm brought back to the standard Cmder console, complete with colours. I can add my SSH keys in either situation, but I much prefer using the default Cmder console. Example of coming back to the standard Cmder console:

```
C:\Users\Brad
λ start-ssh-agent
Found ssh-agent at 6752
Found ssh-agent socket at /tmp/ssh-GYaVEG9e6nDE/agent.18340
Microsoft Windows [Version 10.0.17134.556]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\Brad>exit

C:\Users\Brad
λ
```

Ultimately this isn't a game-breaking issue or anything like that. Just a matter of preference I guess? Can someone help me determine what exactly is going on here?

To answer some questions I'm confident I'll be asked:
- I'm using Windows 10 Enterprise, build 1809.
- I do not have Microsoft's OpenSSH client installed (Settings app -> Apps & Features -> Manage optional features)

Please let me know if any additional information is required. I appreciate any help with this concern!

**Comment by daxgames** [comment]
Have a look at #1807 and #1781

**Comment by pixelbrad** [comment]
Thank you

**Comment by daxgames** [comment]
or `call "%GIT_INSTALL_ROOT%/cmd/start-ssh-agent.cmd" /k exit`
