### ISSUE TITLE
git commit error: pathspec 'commit' did not match any file(s) known to git

### ISSUE THREAD

**Issue by boi87** [cmderdev/cmder#2052]
Possible dupe of #847 ?
Thanks for cmder, I've been trying it for about a week and I came across an issue while committing.

`git add .` works, then
`git commit -m 'header works'`
returns this: 
`git commit error: pathspec 'header' did not match any file(s) known to git`
`git commit error: pathspec 'works' did not match any file(s) known to git`

if I then try 
`git push origin header`
returns
`already up-to-date`
which is not true :sob:

with git bash the commit goes through without issues and so does the push attempt. 
Is there any fix for this?

thanks very much guys!

**Comment by daxgames** [comment]
Single quotes cannot be used in cmd.exe sessions.

**Comment by boi87** [comment]
> Single quotes cannot be used in cmd.exe sessions.

Thanks.
So what can I use when committing? Double quotes? Brackets and single quotes? No quotes?

**Comment by daxgames** [comment]
git commit -m "Double quotes"

**Comment by boi87** [comment]
Thanks pal, very useful!

**Comment by Mauroquil-bit** [comment]
Me aparece el mismo error, ya probé comillas simples y dobles y nada,  

`$ git commit -m index.html "mensaje"
error: pathspec 'mensaje' did not match any file(s) known to git
`

**Comment by daxgames** [comment]
Try `git add index.html && git commit -m  "mensaje"`

**Comment by doubleogadoga** [comment]
Wow it worked, i used double quotes and it committed. Thanks.

> Single quotes cannot be used in cmd.exe sessions.

**Comment by isaacton** [comment]
i used double quotes it did not work.

**Comment by chrisant996** [comment]
> i used double quotes it did not work.

@isaacton What was the full command line that was used?
What was the expected behavior?
What was the actual behavior that happened instead?
