### ISSUE TITLE
git clone doesn't show correct options

### ISSUE THREAD

**Issue by gayanper** [cmderdev/cmder#2053]
with cmder cmd emulator, for git clone the options that are shown is wrong. Seems like the cmder\vendor\clink-completions\git.lua file doesn't implement auto completion for all git options.

**Comment by gayanper** [comment]
Following content is expected to clone to work properly

`
"clone" .. parser("--template","-l","-s",
                "--no-hardlinks","-q","-n","--bare","--mirror",
                "-o","-b","--branch=","-u","--reference","--dissociate",
                "--separate-git-dir","--depth", "--single-branch",
                "--no-single-branch","--no-tags","--recurse-submodules=",
                "--shallow-submodules","--no-shallow-submodules","--jobs"),
`

**Comment by daxgames** [comment]
Open a pr with clink completions on github.  This is not a cmder issue.
