### ISSUE TITLE
Hyper.js integration startup dir

### ISSUE THREAD

**Issue by Eldair** [cmderdev/cmder#2054]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Description of the issue 
How to set startup dir for cmder when started via hyper.js?

**Comment by daxgames** [comment]
`cmdef [path]

**Comment by Eldair** [comment]
Where does that go following the instructions from here https://github.com/cmderdev/cmder/wiki/Seamless-Hyper-integration ?

**Comment by daxgames** [comment]
I guess my post is irrelevant.  Was not aware of what hyper.js was but this is how to open cmder in a path.

**Comment by daxgames** [comment]
@Eldair I installed Hyper and can't find a way to do what you ask.  This is not really a Cmder issue, probably best to ask the Hyper developers.  If you get a solution please let us know here.

**Comment by DRSDavidSoft** [comment]
@Eldair Sorry for the late response, I have now _updated_ the wiki to address your question.  You'll find the solution here: https://github.com/cmderdev/cmder/wiki/Seamless-Hyper-integration#additional-configuration

In addition to that, an answer to your issue has been already published over Hyper's official repo:
- https://github.com/zeit/hyper/issues/2794#issuecomment-378840982

**Comment by Eldair** [comment]
Thank you very much @DRSDavidSoft
