### ISSUE TITLE
不能保存已设置的语言

### ISSUE THREAD

**Issue by chenfd99** [cmderdev/cmder#2057]
设置语言后  下次打开又会变成默认的英文

**Comment by chenfd99** [comment]
![image](https://user-images.githubusercontent.com/16187185/54018712-5d867880-41c4-11e9-814e-368b56791221.png)

**Comment by daxgames** [comment]
@chenfd99 I am sorry we need you to use English here as none of the Cmder team can read your post.

**Comment by chenfd99** [comment]
After setting the language to Chinese, the next time you open it, it will become the default English.

**Comment by chenfd99** [comment]
@daxgames

**Comment by daxgames** [comment]
@chenfd99 Did you see my post and question?

**Comment by yumenaka** [comment]
编辑"cmder\vendor\conemu-maximus5\ConEmu.xml"这一行即可:
edit "cmder\vendor\conemu-maximus5\ConEmu.xml\ConEmu.xml",like this":

<value name="Language" type="string" data="zh"/>

**Comment by daxgames** [comment]
This is not a cmder issue see ny post above.
