### ISSUE TITLE
Add autocompletion for csudo

### ISSUE THREAD

**Issue by NieLeben** [cmderdev/cmder#2058]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [ ] Question

### Version Information
Cmder version: 180626
Windows version: Windows 10 Pro 1809
### Description of the issue 
I just found out about csudo and really like it but after I type "csudo" I don't get completions for other commands like "choco".

**Comment by daxgames** [comment]
We do not maintain the code that does our autocompletion.  You could add this by contributing to [clink-completions](https://github.com/vladimir-kotikov/clink-completions)
