### ISSUE TITLE
start proces in background

### ISSUE THREAD

**Issue by wolacinio** [cmderdev/cmder#2059]
How execute command in background and how come back to terminal without closing process?
For example adding ampersand not work:
`kubectl port-forward pod/nginx-test1-7b48ddf7b6-gqg6m 80:80 &`

**Comment by daxgames** [comment]
The default cmder shell is cmd.exe and ther is no direct equivalent to using `&` in linux.  You could lookat [this](https://superuser.com/questions/198525/how-can-i-execute-a-windows-command-line-in-background).

You can launch a cmder bash shell and you use the `&` character to background a process
