### ISSUE TITLE
WSL + vim + -cur_console:p does not work out-of-the-box

### ISSUE THREAD

**Issue by NBardelot** [cmderdev/cmder#2061]
Context:

  * Dell XPS laptop with Windows 10 up-to-date
  * fresh cmder installation
  * default `{WSL:bash}` task with `-cur_console:p` included
  * WSL & Ubuntu up-to-date

To be clear, here is the task (I did not modify it):

```
set "PATH=%ConEmuBaseDirShort%\wsl;%PATH%" & %ConEmuBaseDirShort%\conemu-cyg-64.exe --wsl -cur_console:pm:/mnt
```

Issue: the arrow keys do not work in vim.

I know this is a issue that comes again and again, but here I think I've followed the documentation and current "best practices", and it still does not work properly... Any advice/workaround?

Thanks.

**Comment by NBardelot** [comment]
Finally found help here : 
https://github.com/cmderdev/cmder/issues/1832

> Ok so as it turns out, the p flag used to default to value 5 for cur_console, but doesn't anymore. This is what was causing the issue in vim and alike for me. Replacing p to p5 in my templates solved it.

And it works now for me with: 

```
set "PATH=%ConEmuBaseDirShort%\wsl;%PATH%" & %ConEmuBaseDirShort%\conemu-cyg-64.exe --wsl -cur_console:p5m:/mnt
```

**Comment by daxgames** [comment]
@NBardelot I assume this can be closed then?

**Comment by NBardelot** [comment]
Unfortunately while the issue seems to be fixed for some times after patching the task and reopening a new console, when I use said console for several hours the issue comes back. It appears to be an underlying bug of `cmder` or `conemu`.

**Comment by daxgames** [comment]
If you are using WSL then you are not using Cmder.  Cmder is a set of Tasks defined in ConEmu that runs scripts, software and config defined by the Cmder Team.

You are using WSL in ConEmu that happens to be launched by the `Cmder.exe` launcher.

I suggest you follow the docs [here](https://github.com/cmderdev/cmder/issues/2022#issuecomment-473572828)
