### ISSUE TITLE
Ctrl+L doesn't work in R

### ISSUE THREAD

**Issue by 229668880** [cmderdev/cmder#2064]
Hi, I am using R with cmder. But Ctrl+L cannot clear screen in R. How to solve it? In R, cat("\033[2J") can be used to clear screen, but cmder cannot deal with this command.

**Comment by daxgames** [comment]
Check the `Keys and Macros` config in `Setup Tasks` and make sure `Ctrl+L` is not configured for something else.  If it is disable it.

**Comment by 229668880** [comment]
I think it is the problem of R. Ctrl+L can be used from Python, Juila and Cygwin in cmder, but not for R.  Is it because R user different code to clear screen?

**Comment by daxgames** [comment]
Unknown.  I don't know what R is.  Does the same issue exist in strain Conemu using R?  if so report the issue there.

**Comment by 229668880** [comment]
Thanks. I am going to leave this issue behind.
