### ISSUE TITLE
Command group {cmd} not found!

### ISSUE THREAD

**Issue by zsedcbm** [cmderdev/cmder#2065]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

Cmder Version 1.3.11.843
ConEmu 180626 preview

win10 Pro 1709
### Description of the issue 

1. Integration -> ConEmu Here -> Register
2. open folder
3. right mouse -> ConEmu Here

the windows pops up a dialog box

ConEmu 180626 [64]

Command group {cmd} not found!
Choose your shell?

是(Y)   否(N)

**Comment by daxgames** [comment]
Undo that, then:

```
Cmder.exe /register
```

**Comment by zsedcbm** [comment]
> Undo that, then:
> 
> ```
> Cmder.exe /register
> ```

thanks , it's worked.

So, I can't use the settings interface to Register a Windows Shell Menu, this will mislead the user.

**Comment by daxgames** [comment]
This is a side effect of what Cmder actually is.

A currated set of software that is tied together with scripts and configuration to provide a better console env on windows.

The GUI interface would work just fine to do this if you were using 'Conemu', the terminal emulator Cmder uses, by itself.
