### ISSUE TITLE
Cmder changes font to italic by itself.

### ISSUE THREAD

**Issue by In5ert** [cmderdev/cmder#2067]
I'm using monofur font in console and everytime I'm launching it font is italic. 
Monofur isn't italic by default, and I haven't set it italic in settings.

Edit:
I had two fonts installed at once - monofur and monofur italic.
Cmder used this one which is italic, but idk why.

**Comment by daxgames** [comment]
Cmder is a colection of separate software tied together by scripts and configuration.  These scripts and configuration have nothing to do with your font of choice.  ConEmu is the terminal emulator and is what is responsible for using the font you choose in the ConEmu GUI.
