### ISSUE TITLE
Paste selected text without copying to clipboard

### ISSUE THREAD

**Issue by jtechpro** [cmderdev/cmder#2069]
### Purpose of the issue
- [x] Feature request (request for new functionality)

### Version Information
180626 [64]

Windows 10 Enterprise Edition

### Description of the issue 
I would like to see a feature where we can paste the selected text without copying it to clipboard. Because the clipboard may contain other useful content which doesn't want to be overriden.
This functionality is seen in XShell with (Alt+Insert) which inserts the selected text on the console without actually copying it to the clipboard.

It can be implemented like this..
Add an event listener on the shortcut (for ex, Alt+Insert or any custom shortcut), getSelectedText() and paste it when the shortcut is pressed.

It would be very handy.

**Comment by daxgames** [comment]
This is a request for conemu.  If this is a feature you want then the developers over there would be the ones to add it.
