### ISSUE TITLE
Cmder does not want to change directory

### ISSUE THREAD

**Issue by SirTwsted** [cmderdev/cmder#2070]
I downloaded the the full .zip file thats around 108-mb in size.
I extracted the zip file on the desktop and was left with a folder named cmder with lots of content files inside.
I then moved the enter folder to C:\
In the same directory where my (2) Program Folders reside in Windows 7- x64-bit.
I then opened cmder and typed the following. 
cd Desktop

This is the result I got back.
.
![Screenshot_19](https://user-images.githubusercontent.com/15247713/55323997-c624e600-544e-11e9-9b52-e1061bdfebda.png)

I am using v 1.3.11.843
I then proceeded to download the alpha version (v 1.3.11.872) 
and did the same steps I mentioned above.
and got the same result as the first.

.

**Comment by daxgames** [comment]
You need to specify a valid path:

```
cd /d "%userprofile%\Desktop"
```
