### ISSUE TITLE
Is there any option to open cmder via context menu

### ISSUE THREAD

**Issue by niyas-ali** [cmderdev/cmder#2073]
### Purpose of the issue
- [ ] Question

### Version Information

ConEmu 180626 [64] Startup Info
  OsVer: 10.0.17134.x64, Product: workstation, SP: 0.0, Suite: 0x100
  Build: 1803, UBR: 648, ReactOS: 0, Rsrv: 0, WINE: 0, PE: 0, R2: 0

### Description of the issue 

Is there any way to open current working directory from the context menu in windows
Example : Git bash provide an option like "Open Git Bash here" in context menu
I have seen some issues already raised but if the feature available its not working or Am i missed something?

**Comment by daxgames** [comment]
Cmder /register /single

**Comment by niyas-ali** [comment]
Thanks, @daxgames  that worked for me
