### ISSUE TITLE
cd - not working

### ISSUE THREAD

**Issue by mallikarjunece** [cmderdev/cmder#2074]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

**Comment by koliapp2019** [comment]
Is there any plan to make cd ~ works?

**Comment by daxgames** [comment]
#1051

**Comment by DRSDavidSoft** [comment]
For anyone in the future looking for a method to make `cd ~` work, without using <kbd>Tab</kbd>, I wrote a solution here: https://github.com/cmderdev/cmder/issues/1051#issuecomment-702983948

Give it a test, and let me know!
