### ISSUE TITLE
Fluent terminal + cmder space display incorrect

### ISSUE THREAD

**Issue by silencial** [cmderdev/cmder#2075]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)

### Version Information

Cmder - 1.3.11.843
Window - win10 1803

### Description of the issue 
run cmder under FluentTerminal exactly as this [post](https://github.com/cmderdev/cmder/wiki/Seamless-FluentTerminal-Integration).

when a space is typed, there seems to be two spaces displayed like this:
![20190406013528](https://user-images.githubusercontent.com/26143109/55667059-4dd27200-580c-11e9-8270-24863550a99e.png)
**There is only one spaced typed between 'b' and the cursor.**

But if you type another character, the display is normal like this:
![20190406013732](https://user-images.githubusercontent.com/26143109/55667076-90944a00-580c-11e9-838f-b29adc5fdd20.png)
**Which means it is only display problem.**

After deleting the last character 'c' and one space:
![20190406013855](https://user-images.githubusercontent.com/26143109/55667086-c20d1580-580c-11e9-9dd2-43bd0626f760.png)
**There seems to be one space between 'b' and the cursor but it is not! If you delete again it will delete 'b'!**

**Comment by DRSDavidSoft** [comment]
@silencial That's odd, may I ask does this issue happen *only* with the Cmder profile? Or does it happen with other FluentTerminal profiles too?

Additionally, which version of FluentTerminal have you installed?

Can you see whether your FluentTerminal uses WinPTY or ConPTY?

**Comment by silencial** [comment]
@DRSDavidSoft This happens only with the Cmder profile. But this problem is gone after changing the Cmder "\lambda" sign to "$".

**Comment by DRSDavidSoft** [comment]
@silencial Then this issue is with the default font that is used in FluentTerminal.

Personally, I use either Source Code Pro or Hasklig that does not exhibit this issue.

Thanks for your feedback I'll update the wiki accordingly.
