### ISSUE TITLE
'/usr/bin/env' not found when running flutter on windows 10

### ISSUE THREAD

**Issue by mchenx** [cmderdev/cmder#2077]
### Purpose of the issue
- [ x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information
1.3.6.678 
180528[64]preview

Windows 10 Pro 1809

### Description of the issue 
added google flutter bin folder and run flutter says "/usr/bin/env: bad interpreter: No such file or directory". It seems the flutter tool tries to execute /usr/bin/env however it doesn't exist in /usr/bin folder

**Comment by daxgames** [comment]
Please try the latest release

**Comment by mchenx** [comment]
thanks, I updated to 1.3.11 and it works
