### ISSUE TITLE
open cmder with bash command line options

### ISSUE THREAD

**Issue by Catsquotl** [cmderdev/cmder#2078]
Hi I want to open cmder from a texteditor, Geany in this case and have it run a file with some python or ruby interpreter.

I can get it to open up cmder and start bash, but I can't work out how to open bash with a commandline switch which will tell it to start python and run a file

**Comment by daxgames** [comment]
Not possible without a very lengthy explanation of multiple required steps.  Cmder buys you nothing when using it for automated tasks.  Just use cmd.exe and use its command line switches to run whatever you need.
