### ISSUE TITLE
When I use ssh to connect to the remote host, after using and exiting the vim editor, the previous cmder output disappears.

### ISSUE THREAD

**Issue by marsvet** [cmderdev/cmder#2085]
When I use ssh to connect to the remote host, after using and exiting the vim editor, the previous cmder output disappears.
Version: v1.3.11

**Comment by daxgames** [comment]
@marsvet You mean what was in the scroll back buffer before you started vim?

**Comment by marsvet** [comment]
![GIF](https://user-images.githubusercontent.com/36563356/57572600-357af600-744f-11e9-95a4-be91cad90364.gif)

Like this, the previous output disappeared. My system is Windows10.

In addition, opening the remote vim will automatically start the "REPLACE" mode.

**Comment by daxgames** [comment]
I tested with ConEmu Portable and got similar results.  Cmder uses ConEmu as terminal emulator please open an issue over at https://github.com/Maximus5/ConEmu

Thank you! :-)
