### ISSUE TITLE
Bash on cmder doesn't properly convert paths containing square brackets ([]).

### ISSUE THREAD

**Issue by MoHKale** [cmderdev/cmder#2086]
### Purpose of the issue
- [X] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information
CMder version 190331 preview running on windows 10 Education (version 1809) installed on a Macintosh desktop system (through bootcamp).

#### Introduction
*This section is my just justifying this issue, you can skip it if you wish*

This issue may be related to [this issue](https://github.com/cmderdev/cmder/issues/1944) but that was running on cmd prompt on cmder (and thus paths in that environment are automatically windows compatible, whereas in bash they need to be converted). My issue relates exclusively to bash. I should also note this has been an issue for quite a while, I updated a pretty long time ago and have been encountering this bug pretty frequently. I always assumed you were aware and didn't give it a second thought (as I just jumped back and replaced /c/ with C:/) but I can only surmise you aren't aware.

#### Problem
As per what the title says, any path which contains either a forward or backward square bracket isn't converted to a windows like path when passed to an executable. To display this I wrote a simple python script.

```python
from sys import argv

for X, arg in enumerate(argv, 1):
    print('%03d: %s' % (X, arg))
```

and passed numerous path values to it to see if their converted properly. I've attached a screenshot showing the output from a few different path types.

![Capture](https://user-images.githubusercontent.com/23294780/56697953-27f00d00-66e8-11e9-891c-6416a1602683.PNG)

The path is converted only when it doesn't contain either square bracket type. This appears to only happen with square brackets. If I use regular parentheses , it works fine, if I use curly braces, it works fine. It only fails with square brackets. This wasn't a problem in older versions of CMder and I haven't read any mention of desiring such behaviour in change logs so I can only surmise its a bug.

**Comment by MoHKale** [comment]
should also mention I'm running on python 3.7.1

**Comment by daxgames** [comment]
@mohkale I am guessing this is a Git for Windows, the component of cmder that provides the bash shell, issue and not a Cmder issue.  Git bash is included I Cmder pretty much unmodified other than the Cmder prompt.

The question I would have is does this happen in git bash outside Cmder?

**Comment by MoHKale** [comment]
@daxgames You're right, do you know where the git bash repo is?

**Comment by daxgames** [comment]
https://github.com/git-for-windows/git
