### ISSUE TITLE
How to run a command in a new tab

### ISSUE THREAD

**Issue by distante** [cmderdev/cmder#2089]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Version Information
Cmder 180626
Windows 10 Pro

### Description of the issue 
I have two aliases that run two REPL (`runAT`, and `testAT`) tasks that I always need to run together and each one also open a side program. What I do now is run one and then go back to cmdr, there I press `ctrl-t` and run the other one. After that I go back to cmdr and rename each tab to the corresponding REPL script name.

Is there a way to instruct cmdr to "open a new tab with this name and run this script"? I have found some info about do this in ConEmu but when I run those in cmdr I always get an error like this:
` cmder -Here -title Test -run dir -new_console:s50H:t:LINT`
![image](https://user-images.githubusercontent.com/5490201/57182408-e9541280-6e9e-11e9-94c4-2c06d24a8b1e.png)

ConEmu new console info https://conemu.github.io/en/NewConsole.html

My end goal is to have one script to starts `runAT` and `testAT` each in their own tab.

**Comment by daxgames** [comment]
Cmder is not conemu and thus the command line args for conemu cannot be used with cmder.exe.  the beast advice I can give you is to craft a Conemu task called `runAt` and one called `testAt` that does what you want and call them with `cmder /task runAt` and `cmder /task testAt`
