### ISSUE TITLE
Discord or Slack Server for Cmder ? 

### ISSUE THREAD

**Issue by abrhambas01** [cmderdev/cmder#2090]
Is there a IRC for Cmder community so that we might find solutions quick ather than waiting for a week or days

**Comment by doudouClem** [comment]
still no discord ? I'd like to look up the code but I'm not understanding who / where to contact, I validate the above suggestion to get a discord, lots of programming community are there like powershell, bash, ubuntu, windows and other open source programs, would be nice IMO

**Comment by chrisant996** [comment]
@abrhambas01 How would moving to Discord change responsiveness of volunteers and community members to questions?

@doudouClem Do you have specific questions?  Post them as issues.  You've found who/where to contact.  The code is in this git repo.

**Comment by MartiUK** [comment]
You are welcome to discuss the project in the discussions section of the repo and open issues as you wish.
