### ISSUE TITLE
How to recover aliases and terminal preferences such as its appearance

### ISSUE THREAD

**Issue by abrhambas01** [cmderdev/cmder#2091]
I don't remember what I've done but I've remembered that I wanted to change the startup directory in Cmder, since it's in C:\Users 
and I've tried to follow the instructions here in this link :
https://stackoverflow.com/a/43986501/6813433
And then I restarted and I lose all my aliases like I can't even do the commands that I can do before

**Comment by daxgames** [comment]
@abrhambas01 Did you figure it out?

**Comment by abrhambas01** [comment]
Yep, just reinstalled cmder and copied all my aliases
