### ISSUE TITLE
ssh adds my company domain name to my username 

### ISSUE THREAD

**Issue by s0j0urn** [cmderdev/cmder#2093]
### Purpose of the issue
- [X] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

cmder version: 1.3.11.843
conemu version: 180626

Windows 10
Was working correctly on windows 7
### Description of the issue

Hi,
I recently switched to Windows 10 from a Windows 7 PC.
On the windows 10, now whenever I try to ssh to any server it automatically adds the domain name of my organization to my username.
For example:

~ssh SERVER_A
hit enter, it automatically becomes
**~ssh my_ldap_id@domainname.com@SERVER_A**

earlier when I was on windows 7, the behavior was
 
~ssh SERVER_A
hit enter, it automatically becomes
**~ssh my_ldap_id@SERVER_A**

**Comment by daxgames** [comment]
I doubt this is a cmder issue.  `ssh` is prepending your username.  In addition you are probably using Windows 10 built in `ssh.exe` and not the one from `Cmder`.

What is the output of  `where ssh`?

What is the output of `set user`

**Comment by s0j0urn** [comment]
> I doubt this is a cmder issue. `ssh` is prepending your username. In addition you are probably using Windows 10 built in `ssh.exe` and not the one from `Cmder`.
> 
> What is the output of `where ssh`?
> 
> What is the output of `set user`

@daxgames Thank you. Yes, you are right. I was using openssh. I uninstalled that and now started using ssh(git-for-widows)(cmder\vendor\git-for-windows\usr\bin\ssh.exe) that comes with cmder full package.
