### ISSUE TITLE
How to start Cmder hidden in TaskBar

### ISSUE THREAD

**Issue by eziosella** [cmderdev/cmder#2094]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [X] Question

### Version Information

Cmder Version 1.3.6.678
ConEmu 180528 [32

Windows 7 Professional
OsVer: 6.1.7601.x64, Product: workstation, SP: 1.0, Suite: 0x100
Build: Service Pack 1, ReactOS: 0, Rsrv: 0, WINE: 0, PE: 0, R2: 0

### Description of the issue

Is it possible to run Cmder hidden in TaskBar?
I 'm able to do it directly on ConEmu, but no way to pass the "-MinTSA" parameter from Cmder.

**Comment by daxgames** [comment]
@eziosella Cmder.exe does not support conemu command line switches.  I am however looking at POSSIBLY passing unknown cmder.exe switches directly to conemu when we start it.

**Comment by eziosella** [comment]
Thanks for the prompt reply, in the meanwhile i was just looking the source code and i am try to modifiy it in that way. I also was thinking could be very usefull a tunnel for pass parameters directly to ConEmu.

**Comment by daxgames** [comment]
PRs are very welcome and I am not a C++ guy so I struggle with getting stuff done.

**Comment by eziosella** [comment]
Ok then, this is my first pull request. I 've tried to follow all the instructions. I hope will be ok.
Since i was able to do what i ask in my first request, this question can be closed by my side.
Thanks @daxgames
