### ISSUE TITLE
Bold in Console

### ISSUE THREAD

**Issue by rpartha** [cmderdev/cmder#2095]
Using chalk library in Node, I noticed that the text does NOT actually bold in the console, as evidenced by the below (the text 'Bold!' should be bolded). 

![image](https://user-images.githubusercontent.com/3248921/57574943-8408a000-740f-11e9-876d-376d5cbabdf4.png)

**Comment by daxgames** [comment]
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem or a question, please open an issue over at https://github.com/Maximus5/ConEmu

Thank you! :-)
