### ISSUE TITLE
cmder with oh-my-zsh agnoster theme

### ISSUE THREAD

**Issue by congx961** [cmderdev/cmder#2098]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Version Information

Windows 10 pro 1809
comder 1.3.11.843
zsh 5.4.2 (x86_64-ubuntu-linux-gnu)

### Description of the issue

I'm just try cmder today on windows10.
I open a WSL(ubuntu18.04) tab with zsh, when i use the default theme 'robyrussell' everything going fine, but after i change to theme 'agnoster' and run 'git log' under a git repository or edit a script via vim, after run such commands, i get an results like this 

[before]
![before](https://user-images.githubusercontent.com/30112011/57778432-a32c6800-7756-11e9-994e-58f332b4d1cd.png)

[after]all the directory of the former line are gone
![after](https://user-images.githubusercontent.com/30112011/57778437-a4f62b80-7756-11e9-8ecd-4df3c9bffadb.png)

How can i fix this?
Please help me.

**Comment by daxgames** [comment]
If you are using WSL you are not using Cmder.  You are running WSL in Conemu if you are having issues you should report those to the conemu developer.

**Comment by congx961** [comment]
OK, thanks

**Comment by congx961** [comment]
> If you are using WSL you are not using Cmder. You are running WSL in Conemu if you are having issues you should report those to the conemu developer.

OK thanks
