### ISSUE TITLE
Unable to open batch file after updating Cmder

### ISSUE THREAD

**Issue by reaktorblue** [cmderdev/cmder#2100]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [X] Question

### Version Information
Working - Cmder version 1.3.6.678, ConEmu version 180528
Not Working - Cmder version 1.3.11.843, ConEmu version 190331
Windows version - Windows 7

### Description of the issue
**Desired Result** - I'm trying to open a batch file (runpsql.bat) with Cmder, without having to make Cmder my default Windows terminal.

I've created two batch files which used to work. I since updated Cmder by downloading the full version from the website and extracting it to C:\ and renaming the old C:\Cmder to C:\Cmder_old. Illustrated below in the _actual result_, it seems to no longer work and opens ConEmu instead of Cmder.

I think a setting or configuration is missing but cannot figure out how to get the _expected result_ with the updated Cmder.

**Expected Result**
![Cmder - Expected Result](https://user-images.githubusercontent.com/20385393/57967064-5ac4a400-7928-11e9-81a8-31c4185cd2fd.jpg)

**Actual Result**
![Cmder - Actual Result](https://user-images.githubusercontent.com/20385393/57967067-6912c000-7928-11e9-8843-f8c6ffe7eeaf.jpg)

**runpsqlcmder.bat**
`"cmder.bat" "runpsql.bat"`

**cmder.bat**
```
@echo off
set CMDER_ROOT=C:\Cmder
set CMDER_ICONS=%CMDER_ROOT%\icons
start %CMDER_ROOT%\vendor\conemu-maximus5\ConEmu.exe -Icon %CMDER_ROOT%\Cmder.exe -Title PostgreSQL -LoadCfgFile %CMDER_ROOT%\config\ConEmu.xml -run cmd /k "%CMDER_ROOT%\vendor\init.bat cd %CD% && %~1" -run {cmd::Cmder} -cur_console:n:C:"%CMDER_ICONS%\cmder_blue.ico"
```

**Comment by daxgames** [comment]
Technically they are both Coemu since it is a component of Cmder 

My guess is you forgot to copy your config folder from your old installation to your new installation before you run the batch file.  This would result in a default  conemu.xml to be and used because the xonemu.xml file you pointed to does not exist.

**Comment by daxgames** [comment]
@reaktorblue ???

**Comment by reaktorblue** [comment]
That looks like it resolved the issue. Thanks!
