### ISSUE TITLE
Strange error message at startup

### ISSUE THREAD

**Issue by ninjubohra** [cmderdev/cmder#2101]
### Purpose of the issue
- [ X] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information
Version 1.3.11.843

Windows 10 Enterprise ver. 1809

### Description of the issue
When I startup Cmder I get the following message at the top

**'env' is not recognized as an internal or external command,
operable program or batch file.**

C:\tools\cmder-1.3.11
λ

Snooping around I found the **init.bat** file and I set the `verbose_output` and `debug_output` to non-zero values and generated the following output

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
DEBUG(init.bat): Env Var - CMDER_ROOT=C:\tools\cmder-1.3.11

DEBUG(init.bat): Env Var - debug_output=1

Injecting Clink!
DEBUG(init.bat): Looking for Git install root...

DEBUG(:read_version): Env Var - git_executable=C:\tools\cmder-1.3.11\vendor\git-for-windows\cmd\git.exe

DEBUG(:read_version): Env Var - GIT_VERSION_VENDORED=2.19.0.windows.1

DEBUG(:validate_version): ARGV[1]=VENDORED, ARGV[2]=2.19.0.windows.1

DEBUG(:parse_version): ARGV[1]=VENDORED, ARGV[2]=2.19.0.windows.1

DEBUG(:validate_version): Found Git Version for VENDORED: ...

DEBUG(:read_version): Env Var - git_executable=C:\tools\cmder-1.3.11\vendor\git-for-windows\mingw64\bin\git.exe

DEBUG(:read_version): Env Var - GIT_VERSION_USER=2.19.0.windows.1

DEBUG(:validate_version): ARGV[1]=USER, ARGV[2]=2.19.0.windows.1

DEBUG(:parse_version): ARGV[1]=USER, ARGV[2]=2.19.0.windows.1

DEBUG(:validate_version): Found Git Version for USER: ...

DEBUG(Comparing:):

DEBUG(USER:): ...

DEBUG(VENDORED:): ...

DEBUG(Using found Git from 'C:\tools\cmder-1.3.11\vendor\git-for-windows\mingw64\bin...):

DEBUG(init.bat): Preferring Windows commands

DEBUG(:enhance_path): Env Var 1 - found=0

DEBUG(:enhance_path): Env Var 2 - found=0

DEBUG(:enhance_path): BEFORE Env Var - PATH=C:\tools\cmder-1.3.11\vendor\conemu-maximus5\ConEmu\Scripts;C:\tools\cmder-1.3.11\vendor\conemu-maximus5;C:\tools\cmder-1.3.11\vendor\conemu-maximus5\ConEmu;C:\oracle\product\11.2.0\client_1\bin;C:\Program Files (x86)\RSA SecurID Token Common;C:\Program Files\RSA SecurID Token Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Plantronics\Spokes3G\;C:\tools\jdk1.8.0_162\bin;C:\tools\cmder-1.3.11\vendor\git-for-windows\mingw64\bin;C:\tools\apache-maven-3.2.5\bin;C:\tools\gradle-4.1\bin;C:\Users\e047379\AppData\Local\Microsoft\WindowsApps

DEBUG(:enhance_path): Appending 'C:\tools\cmder-1.3.11\vendor\git-for-windows\mingw64\bin\usr\bin'

DEBUG(:enhance_path): AFTER Env Var - PATH=C:\tools\cmder-1.3.11\vendor\conemu-maximus5\ConEmu\Scripts;C:\tools\cmder-1.3.11\vendor\conemu-maximus5;C:\tools\cmder-1.3.11\vendor\conemu-maximus5\ConEmu;C:\oracle\product\11.2.0\client_1\bin;C:\Program Files (x86)\RSA SecurID Token Common;C:\Program Files\RSA SecurID Token Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Plantronics\Spokes3G\;C:\tools\jdk1.8.0_162\bin;C:\tools\cmder-1.3.11\vendor\git-for-windows\mingw64\bin;C:\tools\apache-maven-3.2.5\bin;C:\tools\gradle-4.1\bin;C:\Users\e047379\AppData\Local\Microsoft\WindowsApps;C:\tools\cmder-1.3.11\vendor\git-for-windows\mingw64\bin\usr\bin

'env' is not recognized as an internal or external command,
operable program or batch file.
DEBUG(init.bat): Env Var - GIT_INSTALL_ROOT=C:\tools\cmder-1.3.11\vendor\git-for-windows\mingw64\bin

DEBUG(init.bat): Found Git in: 'C:\tools\cmder-1.3.11\vendor\git-for-windows\mingw64\bin'

DEBUG(:enhance_path): Env Var 1 - found=0

DEBUG(:enhance_path): Env Var 2 - found=0

DEBUG(:enhance_path): BEFORE Env Var - PATH=C:\tools\cmder-1.3.11\vendor\conemu-maximus5\ConEmu\Scripts;C:\tools\cmder-1.3.11\vendor\conemu-maximus5;C:\tools\cmder-1.3.11\vendor\conemu-maximus5\ConEmu;C:\oracle\product\11.2.0\client_1\bin;C:\Program Files (x86)\RSA SecurID Token Common;C:\Program Files\RSA SecurID Token Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Plantronics\Spokes3G\;C:\tools\jdk1.8.0_162\bin;C:\tools\cmder-1.3.11\vendor\git-for-windows\mingw64\bin;C:\tools\apache-maven-3.2.5\bin;C:\tools\gradle-4.1\bin;C:\Users\e047379\AppData\Local\Microsoft\WindowsApps;C:\tools\cmder-1.3.11\vendor\git-for-windows\mingw64\bin\usr\bin

DEBUG(:enhance_path): Prepending 'C:\tools\cmder-1.3.11\vendor\bin'

DEBUG(:enhance_path): AFTER Env Var - PATH=C:\tools\cmder-1.3.11\vendor\bin;C:\tools\cmder-1.3.11\vendor\conemu-maximus5\ConEmu\Scripts;C:\tools\cmder-1.3.11\vendor\conemu-maximus5;C:\tools\cmder-1.3.11\vendor\conemu-maximus5\ConEmu;C:\oracle\product\11.2.0\client_1\bin;C:\Program Files (x86)\RSA SecurID Token Common;C:\Program Files\RSA SecurID Token Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Plantronics\Spokes3G\;C:\tools\jdk1.8.0_162\bin;C:\tools\cmder-1.3.11\vendor\git-for-windows\mingw64\bin;C:\tools\apache-maven-3.2.5\bin;C:\tools\gradle-4.1\bin;C:\Users\e047379\AppData\Local\Microsoft\WindowsApps;C:\tools\cmder-1.3.11\vendor\git-for-windows\mingw64\bin\usr\bin

DEBUG(:enhance_path_recursive): Env Var - add_path=C:\tools\cmder-1.3.11\bin

DEBUG(:enhance_path_recursive): Env Var - position=

DEBUG(:enhance_path_recursive): Env Var - max_depth=1

DEBUG(:enhance_path_recursive): Adding parent directory - 'C:\tools\cmder-1.3.11\bin'

DEBUG(:enhance_path): Env Var 1 - found=0

DEBUG(:enhance_path): Env Var 2 - found=0

DEBUG(:enhance_path): BEFORE Env Var - PATH=C:\tools\cmder-1.3.11\vendor\bin;C:\tools\cmder-1.3.11\vendor\conemu-maximus5\ConEmu\Scripts;C:\tools\cmder-1.3.11\vendor\conemu-maximus5;C:\tools\cmder-1.3.11\vendor\conemu-maximus5\ConEmu;C:\oracle\product\11.2.0\client_1\bin;C:\Program Files (x86)\RSA SecurID Token Common;C:\Program Files\RSA SecurID Token Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Plantronics\Spokes3G\;C:\tools\jdk1.8.0_162\bin;C:\tools\cmder-1.3.11\vendor\git-for-windows\mingw64\bin;C:\tools\apache-maven-3.2.5\bin;C:\tools\gradle-4.1\bin;C:\Users\e047379\AppData\Local\Microsoft\WindowsApps;C:\tools\cmder-1.3.11\vendor\git-for-windows\mingw64\bin\usr\bin

DEBUG(:enhance_path): Prepending 'C:\tools\cmder-1.3.11\bin'

DEBUG(:enhance_path): AFTER Env Var - PATH=C:\tools\cmder-1.3.11\bin;C:\tools\cmder-1.3.11\vendor\bin;C:\tools\cmder-1.3.11\vendor\conemu-maximus5\ConEmu\Scripts;C:\tools\cmder-1.3.11\vendor\conemu-maximus5;C:\tools\cmder-1.3.11\vendor\conemu-maximus5\ConEmu;C:\oracle\product\11.2.0\client_1\bin;C:\Program Files (x86)\RSA SecurID Token Common;C:\Program Files\RSA SecurID Token Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Plantronics\Spokes3G\;C:\tools\jdk1.8.0_162\bin;C:\tools\cmder-1.3.11\vendor\git-for-windows\mingw64\bin;C:\tools\apache-maven-3.2.5\bin;C:\tools\gradle-4.1\bin;C:\Users\e047379\AppData\Local\Microsoft\WindowsApps;C:\tools\cmder-1.3.11\vendor\git-for-windows\mingw64\bin\usr\bin

DEBUG(:enhance_path): Env Var 1 - found=0

DEBUG(:enhance_path): Env Var 2 - found=0

DEBUG(:enhance_path): BEFORE Env Var - PATH=C:\tools\cmder-1.3.11\bin;C:\tools\cmder-1.3.11\vendor\bin;C:\tools\cmder-1.3.11\vendor\conemu-maximus5\ConEmu\Scripts;C:\tools\cmder-1.3.11\vendor\conemu-maximus5;C:\tools\cmder-1.3.11\vendor\conemu-maximus5\ConEmu;C:\oracle\product\11.2.0\client_1\bin;C:\Program Files (x86)\RSA SecurID Token Common;C:\Program Files\RSA SecurID Token Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Plantronics\Spokes3G\;C:\tools\jdk1.8.0_162\bin;C:\tools\cmder-1.3.11\vendor\git-for-windows\mingw64\bin;C:\tools\apache-maven-3.2.5\bin;C:\tools\gradle-4.1\bin;C:\Users\e047379\AppData\Local\Microsoft\WindowsApps;C:\tools\cmder-1.3.11\vendor\git-for-windows\mingw64\bin\usr\bin

DEBUG(:enhance_path): Appending 'C:\tools\cmder-1.3.11'

DEBUG(:enhance_path): AFTER Env Var - PATH=C:\tools\cmder-1.3.11\bin;C:\tools\cmder-1.3.11\vendor\bin;C:\tools\cmder-1.3.11\vendor\conemu-maximus5\ConEmu\Scripts;C:\tools\cmder-1.3.11\vendor\conemu-maximus5;C:\tools\cmder-1.3.11\vendor\conemu-maximus5\ConEmu;C:\oracle\product\11.2.0\client_1\bin;C:\Program Files (x86)\RSA SecurID Token Common;C:\Program Files\RSA SecurID Token Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Plantronics\Spokes3G\;C:\tools\jdk1.8.0_162\bin;C:\tools\cmder-1.3.11\vendor\git-for-windows\mingw64\bin;C:\tools\apache-maven-3.2.5\bin;C:\tools\gradle-4.1\bin;C:\Users\e047379\AppData\Local\Microsoft\WindowsApps;C:\tools\cmder-1.3.11\vendor\git-for-windows\mingw64\bin\usr\bin;C:\tools\cmder-1.3.11

DEBUG(init.bat): Env Var - HOME=C:\Users\e047379

DEBUG(init.bat): Calling - C:\tools\cmder-1.3.11\config\user_profile.cmd

C:\tools\cmder-1.3.11
λ

**Comment by ninjubohra** [comment]
Doing some further evaluation and it appears the issue is self-inflicted.  

I was unnecessarily was adding `;%CMDER_HOME%\vendor\git-for-windows\mingw64\bin; `to my SYSTEM path variable before invoking the **cmder.exe** and that confused the init.bat logic such that the attempt to enhance the PATH for adding the UNIX commands (line 268 of init.bat) added an invalid path.

After removing the extra entry the startup was successful

**Comment by DexterAntonio** [comment]
Did you ever find a way to add git to the SYSTEM path variable without breaking cmder? I would like to add git so that I have git to the SYSTEM path so I have git support in some other programs, but I do not want to break cmder.

**Comment by daxgames** [comment]
@DexterAntonio You talking about adding Cmder's embedded Git or user installed Git?  Never tried adding Cmder's embedded Git but user installed Git should be fine.  

Let us know what you find.

**Comment by DexterAntonio** [comment]
Yeah, I tried adding cmder's native git to my PATH, which broke some things. I installed git through another installer and that fixed things.
