### ISSUE TITLE
Use "export" command on CMDER

### ISSUE THREAD

**Issue by cam-bdt** [cmderdev/cmder#2104]
Hi,

I am trying to export http_proxy and https_proxy to my cmder environment. To do that, I need to use the "export" command. But, here is the output :

 
![image](https://user-images.githubusercontent.com/43960194/58406322-a2a2a400-8069-11e9-9d07-d24696373e7c.png)

(export' is not recognized as an internal command or external, an executable program or a command file.)

Can anyone help me ??

Thanks

**Comment by daxgames** [comment]
Export is not a valid command in a cmd.exe shell.  Use set instead.
