### ISSUE TITLE
post-install.bat impacts cmd on every startup

### ISSUE THREAD

**Issue by newmankyle** [cmderdev/cmder#2105]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Version Information

Cmder Version 1.3.11.843
ConEmu Build 190526 (preview)

### Additional Relevant Infromation
I'm using Cmder Mini since I have Git and Git Bash loaded on Windows already.
Git and Git Bash are provided by Source Tree.

GIT_INSTALL_ROOT=C:\Users\<my-home-dir>\AppData\Local\Atlassian\SourceTree\git_local\
### Description of the issue

I'm not sure if this is Cmder's area of concern, but I'd like to make the ticket here for reference.

init.bat has always been slow for me, clocking in at ~12 seconds every time. I investigated by timing its segments, and found that ~7 seconds of that time was spent in here:
```
if exist "%GIT_INSTALL_ROOT%\post-install.bat" (
    %lib_console% verbose_output "Running Git for Windows one time Post Install...."
    pushd "%GIT_INSTALL_ROOT%\"
    "%GIT_INSTALL_ROOT%\git-bash.exe" --no-needs-console --hide --no-cd --command=post-install.bat
    popd
)
```
I checked SourceTree's git_local, and it does, in fact have a post-install.bat. I tried renaming it and my startup was reduced to < 3 seconds.

Is post-install.bat needed to run everytime? 'verbose_output' implies that it should be a one-time deal.

**Comment by daxgames** [comment]
@newmankyle at one time post_install.bat deleted itself and may still if using git portable that is included with Cmder.  I am not really sure if it does or not and I can't check right now.  It only really needs to run once for portable git.
