### ISSUE TITLE
1.3.12 Release

### ISSUE THREAD

**Issue by daxgames** [cmderdev/cmder#2107]
I am thinking of removing the new `alias create ...` syntax for `alias.cmd`.  A user expressed a desire to have it in an incomplete PR that sat forever.  I finished it and it was merged but I have found it does not work in all cases and is difficult to manually test all cases with no real benefit.

The feature has not yet been included in any released version so I think it would be best to remove it and cut a new release once that is done.

@cmderdev/trusted-contributors do you have issues with removing this functionality?

**Comment by Stanzilla** [comment]
If you think it causes more issues than it helps, go for it

**Comment by MartiUK** [comment]
I'm happy with that @daxgames

**Comment by Jackbennett** [comment]
I haven't used cmd.exe for years so I stay out of decisions going on in that area. Just commenting in case you were waiting for the last trusted-contrib in the group to chime in.

**Comment by daxgames** [comment]
@Jackbennett yeah me too for the vast majority of what I do is MacOS and zsh.
