### ISSUE TITLE
'findstr' is not recognized as an internal or external command - again

### ISSUE THREAD

**Issue by brandstaetter** [cmderdev/cmder#2108]
Seems to be the same issue as #1213 - but this was closed without resolution...

`λ init.bat`
`'findstr' is not recognized as an internal or external command,
operable program or batch file.`

`λ echo %PATH%`
`C:\Users\hbrandstaetter\cmder_mini\vendor\conemu-maximus5\ConEmu\Scripts;C:\Users\hbrandstaetter\cmder_mini\vendor\conemu-maximus5;C:\Users\hbrandstaetter\cmder_mini\vendor\conemu-maximus5\ConEmu;C:\Users\hbrandstaetter\AppData\Local\Microsoft\WindowsApps;C:\Users\hbrandstaetter\go\bin;C:\Users\hbrandstaetter\AppData\Local\GitHubDesktop\bin;C:\Users\hbrandstaetter\AppData\Local\Programs\Microsoft VS Code\bin;;C:\Program Files\Docker\Docker\Resources\bin;C:\Python27;C:\Python27\Scripts;C:\Program Files (x86)\Python36-32\Scripts\;C:\Program Files (x86)\Python36-32\;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Gpg4win\..\GnuPG\bin;C:\Program Files\PuTTY\;C:\Program Files\TortoiseSVN\bin;%MAVEN_HOME%\bin;%JAVA_HOME%\bin;%SYSTEMROOT%\System32\OpenSSH\;%GOROOT%\bin;C:\Program Files\TortoiseGit\bin;C:\Users\hbrandstaetter\oc;C:\Users\hbrandstaetter\adb-fastboot\platform-tools;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\GitExtensions\;`

so:

C:\Users\hbrandstaetter\cmder_mini\vendor                         
λ echo %SystemRoot%\system32                                      
C:\WINDOWS\system32                                               
                                                                  
C:\Users\hbrandstaetter\cmder_mini\vendor                         
λ %SystemRoot%\system32\findstr                                   
FINDSTR: Bad command line                                         
                                                                  
C:\Users\hbrandstaetter\cmder_mini\vendor                         
λ findstr                                                         
'findstr' is not recognized as an internal or external command,   
operable program or batch file.

**Comment by daxgames** [comment]
What is the output of `where findstr`.  My guess is there is a problem with your path env var.

**Comment by brandstaetter** [comment]
λ where findstr
'where' is not recognized as an internal or external command,
operable program or batch file.

%SystemRoot%\system32; appears in my %PATH% but it looks like it's not used?

I use it from ConEmu, this is my task to starrt the console:
![image](https://user-images.githubusercontent.com/644820/58878096-c0f44980-86d2-11e9-91a9-54b2800900a2.png)

**Comment by MartiUK** [comment]
@brandstaetter I think `%SystemRoot%\system32` in your PATH should be `%SystemRoot%\System32`, but I could be wrong...

**Comment by brandstaetter** [comment]
@MartiUK Windows is case insensitve here, see:

C:\Users\hbrandstaetter\cmder_mini\vendor
λ %SystemRoot%\**system32**\findstr
FINDSTR: Bad command line

**Comment by markschuh** [comment]
The

> `λ echo %PATH%`

on your system returns the PATH environment variable - but without expanding other variables used for its definition - like %SystemRoot%. That is unusual.

What type has the registry value with the definition of your PATH?
Check with help of
 `%SystemRoot%\system32\reg query "HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Environment" /v Path`
It should output the type as REG_EXPAND_SZ. 

If it were REG_SZ instead that could explain why findstr can't be found within your PATH, Workaround in such a case: Either change the value of the PATH registry value so all other variables are manually resolved or better recreate the registry value PATH as type REG_EXPAND_SZ with same value.
Nevertheless chances are, that whatever program has changed the type of this value may do it again.

**Comment by brandstaetter** [comment]
@MartiUK I decided to change my PATH entries and - unbelievably - it works now. Thanks. What a weird problem.

@markschuh 

`λ reg query "HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Environment" /v Path                                                                                                                   
                                                                                                                                                                                                          
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment                                                                                                                           
    Path    REG_EXPAND_SZ    C:\Program Files\Docker\Docker\Resources\bin;C:\Python27;C:\Python27\Scripts;C:\Program Files (x86)\Python36-32\Scripts\;C:\Program Files (x86)\Python36-32\;%SYSTEMROOT%\Sys
tem32;%SYSTEMROOT%;%SYSTEMROOT%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Gpg4win\..\GnuPG\bin;C:\Program Files\PuTTY\;C:\Program Files\TortoiseSVN\bin;%MAVEN_HO
ME%\bin;%JAVA_HOME%\bin;%SYSTEMROOT%\System32\OpenSSH\;%GOROOT%\bin;C:\Program Files\TortoiseGit\bin;C:\Users\hbrandstaetter\oc;C:\Users\hbrandstaetter\adb-fastboot\platform-tools;C:\ProgramData\chocola
tey\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\GitExtensions\;                                                                                                                                   `

I don't know why the values are not expanded on the command line, but it works now, so I won't touch anything there 😁

**Comment by Vaderv** [comment]
I have the same issue.

**Comment by chrisant996** [comment]
Maybe some program accidentally changed the PATH registry key to be REG_SZ instead of REG_EXPAND_SZ.  That would cause environment variables in the registry key to not be expanded, and thus some programs would not be findable.

Or maybe a config script is setting PATH, instead of appending to PATH, thus removing many search paths.
