### ISSUE TITLE
Different Font for the Lambda

### ISSUE THREAD

**Issue by schodge** [cmderdev/cmder#211]
Is it possible to specify a different font for the lambda?  Source Code Pro doesn't seem to have the character, so I was wondering if it was possible to use Consolas only for that.  There's a pseudographics font option in the settings, but it doesn't seem to have an impact there.

Also, going to tag on one other question because I think it's silly user error.  I find that shift-home, even with the appropriate settings on, often winds up selecting the prompt and sticks me in a mode where I can't seem to do anything.  Is there a better way to select text back to the start of the prompt?  Thanks.

**Comment by fgilio** [comment]
Neither on mines

**Comment by ryanwmarsh** [comment]
This issue should be reopened. It still exists. I'm trying to use Hoefler Operator Mono and it is not falling back to consoles for the lambda char.

**Comment by scheMeZa** [comment]
I'm also using Operator Mono that doesn't have a lambda character.

**Comment by safinea** [comment]
Ran into this as well. Downloaded and installed the latest version of Source Code Pro font [download here](https://github.com/adobe-fonts/source-code-pro) and that solved the issue.

**Comment by MrGrigri** [comment]
Please reopen this issue and fix this. You cannot expect everyone to create/modify a font to add a Lambda character.
