### ISSUE TITLE
Command to run .bat file in Cmder?

### ISSUE THREAD

**Issue by NSExceptional** [cmderdev/cmder#2110]
I'm trying to set up a context menu command to run a .bat file with Cmder. Google tells me ConEmu supports this with something like `C:/.../ConEmu.exe /cmd %1`, is there any equivalent launch argument for Cmder?

**Comment by daxgames** [comment]
Unreleased [Cmder](https://ci.appveyor.com/project/MartiUK/cmder/builds/25804070/artifacts) supports passing conemu arguments to `conemu` using the following:

```
cmder /x "/cmd test.bat"
```

If the path to the script contains spaces then use:

```
cmder /single /x "/cmd \"c:\folder one\test.bat\""
```

**Comment by NSExceptional** [comment]
Thank you!

**Comment by NSExceptional** [comment]
Unreleased... does that mean it's an upcoming release or was it an old version that was scrapped? That page says 1.0.9, but the version I have is 1.3.5.

**Comment by daxgames** [comment]
This will be in a future releslase.

**Comment by homayoonahmadi** [comment]
You can use this registry config:
```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\batfile\shell\open\command]
@="\"D:\\dev\\cmder\\Cmder.exe\" /single /x \"/cmd %1\" %*"
```

Save it as .reg file and run it!
