### ISSUE TITLE
How to install dependencies

### ISSUE THREAD

**Issue by FernandoAguilarR** [cmderdev/cmder#2115]
Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ X ] Question

Version Information
1.3.11.843

Can I add packages with this console?.. I tried to execute this command:
pv opensuse.vdi > /tmp/opensuse.vdi

but I get this result:
'pv' is not recognized as an internal or external command,
operable program or batch file.

I want to insall pv but I don't know if this is possible

**Comment by daxgames** [comment]
There is no package manager, this is not Linux.  You can use Chocolatey to insatll 'packages' on windows but this results in a non portable config.  You can also put portable apps in the `%cmder_root%/bin` folder and run them from there.
