### ISSUE TITLE
Path displays incorrectly if string "master" is in directory name

### ISSUE THREAD

**Issue by generic11** [cmderdev/cmder#2116]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

I am running Conemu version 180626 on Windows 10 Enterprise vers. 1709.

### Description of the issue

I have an issue where the prompt displays incorrectly when I have the string "master" as a portion of a directory name.

My case:
aiScript is a subdirectory of this folder: C:\dev\ifpMisc\archmasterScript.
If I cd into aiScript, the prompt looks like:
C:\dev\ifpMisc\archmaster -> originScript\aiScript (master -> origin)

When I change the folder "archmasterScript" to "archmastScript" everything works fine.

This might be related to #1979 - "Path in certain branch of git displays out of order."
as the last commenter also had an issue where a keyword appears to be replaced by the git branch information.

Thanks so much!

**Comment by generic11** [comment]
Hello, I love cmder! Great tool.

I am running Conemu version 180626 on Windows 10 Enterprise vers. 1709.

I have an issues where the prompt displays incorrectly when I have the string "master" as a portion of a directory name.

My case:
aiScript is a subdirectory of this folder: C:\dev\ifpMisc\archmasterScript. 
If I cd into aiScript, the prompt looks like:
C:\dev\ifpMisc\archmaster -> originScript\aiScript (master -> origin)

When I change the folder "archmasterScript" to "archmastScript" everything works fine.

This might be related to #1979 - "Path in certain branch of git displays out of order."
as the last commenter also had an issue where "a keyword appears to be replaced by the git branch information."

Thanks so much!

**Comment by lucas-gonzalez** [comment]
I ran into this same issue. I have been able to isolate it to [issue #104](https://github.com/vladimir-kotikov/clink-completions/issues/104) in [clink-completions](https://github.com/vladimir-kotikov/clink-completions).
