### ISSUE TITLE
[question] unsure how to debug launch errors

### ISSUE THREAD

**Issue by JasonCostanza** [cmderdev/cmder#2118]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Version Information
version=161206

Windows 10 build 1903 (18362.175)

### Description of the issue
I've put a new installation of cmder on a new laptop I received from work. I may have done something unique in the setup process but I'm not sure how to backtrack what is causing my issue.

The issue is when I launch cmder I get a whole bunch of unrecognized commands before landing at a directory. See below:

> The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
'cmder_shell' is not recognized as an internal or external command,
operable program or batch file.
'debug_output' is not recognized as an internal or external command,
operable program or batch file.
'debug_output' is not recognized as an internal or external command,
operable program or batch file.
'verbose_output' is not recognized as an internal or external command,
operable program or batch file.
'debug_output' is not recognized as an internal or external command,
operable program or batch file.
'read_version' is not recognized as an internal or external command,
operable program or batch file.
'validate_version' is not recognized as an internal or external command,
operable program or batch file.
'read_version' is not recognized as an internal or external command,
operable program or batch file.
'validate_version' is not recognized as an internal or external command,
operable program or batch file.
'compare_versions' is not recognized as an internal or external command,
operable program or batch file.
'debug_output' is not recognized as an internal or external command,
operable program or batch file.
'debug_output' is not recognized as an internal or external command,
operable program or batch file.
'enhance_path' is not recognized as an internal or external command,
operable program or batch file.
'enhance_path' is not recognized as an internal or external command,
operable program or batch file.
'enhance_path' is not recognized as an internal or external command,
operable program or batch file.
'debug_output' is not recognized as an internal or external command,
operable program or batch file.
'debug_output' is not recognized as an internal or external command,
operable program or batch file.
'enhance_path' is not recognized as an internal or external command,
operable program or batch file.
'enhance_path_recursive' is not recognized as an internal or external command,
operable program or batch file.
'enhance_path' is not recognized as an internal or external command,
operable program or batch file.
'run_profile_d' is not recognized as an internal or external command,
operable program or batch file.
'"C:\Dev\cmder\config\user_aliases.cmd"' is not recognized as an internal or external command,
operable program or batch file.
'debug_output' is not recognized as an internal or external command,
operable program or batch file.
'debug_output' is not recognized as an internal or external command,
operable program or batch file.

The errors are not very descriptive of where these are trying to be run from so backtracking what's causing these is a little over my head. The only thing I did before adding cmder was install VSCode and a few extensions for it. But I don't think those should have any bearing on this.

In my cmder settings, I modified the default launch directory. The task for {cmd::Cmder} shows the following:
`-new_console:d:C:\Dev cmd /k ""%ConEmuDir%\..\init.bat" "`

Anyone have information on what this spam is I'm seeing? I exported my settings file from my desktop computer which works perfectly and loaded it into my laptop and updated the file path for the launch directory accordingly. Any ideas how to track down what is triggering this slew of commands?

Cheers!

**Comment by daxgames** [comment]
The `-new_console:d:C:\Dev` is might be the culprit.  Have you tried removing that?

The newest cmder will open in the current working directory by default or any directory passed to cmder.exe on the command line making your change unnecessary.

Are you by any chance using cmder as the console and/or tasks runner for vscode and are seeing this only when running vscode tasks.  If so this could also be the issue.

If neither of these are the cause Iould need more info.

**Comment by JasonCostanza** [comment]
> The `-new_console:d:C:\Dev` is might be the culprit. Have you tried removing that?
> 
> The newest cmder will open in the current working directory by default or any directory passed to cmder.exe on the command line making your change unnecessary.
> 
> Are you by any chance using cmder as the console and/or tasks runner for vscode and are seeing this only when running vscode tasks. If so this could also be the issue.
> 
> If neither of these are the cause Iould need more info.

I tried removing the chunk from the launch task, it now shows: `cmd /k ""%ConEmuDir%\..\init.bat" "` from the launch task, but I'm still seeing it.

I have the launch task set because I'm booting it from a shortcut on my taskbar or start menu and not from windows explorer. I pretty much only work out of a single directory and then `cd [folder]` through the children as needed depending what i'm working on.

I have not used cmder in any direct relation to VScode Tasks yet that I know of. I mean, I haven't done anything in VSCode yet except install some extension and pick a color theme. Is there a way to confirm if I am or am not doing what you mentioned? I'll look into that and then dig into more info for you if I'm you still need more info, happy to get anything you need.

**Comment by JasonCostanza** [comment]
OH, wow. That was stupid of me. I just solved it...

I didn't notice right below there is a "startup dir" button. I just wiped the entire thing above and set the startup dir through the folder picker and now it's good to go.

**Comment by daxgames** [comment]
You dont even need to do that you could just st the start in directory on the shortcut on the task bar

**Comment by JasonCostanza** [comment]
True, two ways to achieve the same. Right?

Just need to figure out how to make the current line show the Git branch i'm in, but that's a different topic. I can close this thread I think we're good to go on this one. Thanks!

**Comment by daxgames** [comment]
It should already show you what git branch you are on.

**Comment by JasonCostanza** [comment]
Yeah I thought it was supposed to as well. I'm not sure what happened, it felt like something just got really messed up so I reinstalled it and it seemed better. 🤷‍♂ 

Turn it off and back on again, IT-101.
