### ISSUE TITLE
Issue while running ls and vagrant commands

### ISSUE THREAD

**Issue by jpruiz114** [cmderdev/cmder#2119]
Hello, I'm getting some issues with the cmder console

![image](https://user-images.githubusercontent.com/4614970/60529810-647e4d00-9cc5-11e9-85e9-978c09b3c3ed.png)

Sometimes other commands fail, this is the most recent example of a failed command.

Also, the slowness is really annoying even when the console is open with admin rights.

Here is another example:

![image](https://user-images.githubusercontent.com/4614970/60529882-91cafb00-9cc5-11e9-9433-5fb3b971e182.png)

It says that the error is related to git but I have tried upgrading it and removing and installing again but the issue comes and goes a lot.

**Comment by daxgames** [comment]
@jpruiz114 Never seen this.
