### ISSUE TITLE
lambda bug when i install clink

### ISSUE THREAD

**Issue by melck** [cmderdev/cmder#212]
When I install CLINK globally and locally, I have a display problem of lambda and git. 
I use clink 0.4.1 and the last full cmder.

How can I fix it? 

Thank you in advance.

![2014-06-25 12_04_15-cmder](https://cloud.githubusercontent.com/assets/813889/3383995/ae83ca06-fc52-11e3-9511-a3a159bb23fa.png)

**Comment by Wicked0ne** [comment]
Any further updates on this? I've since done a few clean installs of windows 8.1 and I still have this issue. I have never manually installed clink. On a clean install of windows 8.1 x64 I download cmder and unpack it and start it and I get the same thing as in melck's picture.

**Comment by MartiUK** [comment]
It may be an anti virus program preventing clink from running, check and
make sure cmder is on a whitelist

**Comment by Wicked0ne** [comment]
I'm using BitDefender free edition and I just completely disabled it tried to open cmder. It did not fix the issue.
