### ISSUE TITLE
Support new windows 10 1903 Terminal

### ISSUE THREAD

**Issue by santagada** [cmderdev/cmder#2121]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [ ] Question

### Description of the issue
The new windows terminal https://github.com/microsoft/terminal is much much faster and has a ton of nice features that conemu has. Maybe supporting it, even if just by pointing to a page saying how to run cmder inside it would be cool.

**Comment by daxgames** [comment]
Run `%cmder_root%/vendor/init.bat` insidet the new terminal running a cmd.exe session.

**Comment by ladislavsulc** [comment]
Doesn't work, any other idea, please?

**Comment by D3473R** [comment]
To add cmder as a new terminal add this profile in the `json` settings

```json
{
    "name": "Cmder",
    "commandline": "cmd.exe /k %cmder_root%/vendor/init.bat",
    "icon" : " %cmder_root%/icons/cmder.ico",
    "hidden": false
},
```
<img width="361" alt="2019-11-22 23_30_08-Windows PowerShell" src="https://user-images.githubusercontent.com/10356892/69464960-25d65580-0d80-11ea-831e-2428db774da5.png">

**Comment by ladislavsulc** [comment]
@D3473R Perfect. Thank you! Any idea how to have the same syntax highlighting as in Cmder? Would be much appreciated.

**Comment by D3473R** [comment]
I don't think syntax highlighting is possible within cmd, maybe a cmder developer can answer that.

**Comment by ShadyAlfred** [comment]
Is it possible to start Windows Terminal in the last directory I was working on? Is it a command line option or is it not related to cmder but Windows Terminal itself?

**Comment by simonpeterdebbarma** [comment]
@D3473R My cmder is not installed in sys32, which is where I think the `commandline` and `icon` keys are checking.

How should I modify my config file to account for my file dir structure?

![image](https://user-images.githubusercontent.com/31207418/75599254-a20bc380-5a68-11ea-9a40-756e84df9b49.png)

**Comment by hectormz** [comment]
@simonpeterdebbarma Do you have `%cmder_root%` environment variable set? If you run `echo %cmder_root%`, it should return `C:\Programming\cmder_mini\`. If it doesn't you should set the variable to that path.

**Comment by daxgames** [comment]
Instead of using `%cmder_root%` you can also just point directly ro `[drive]:\[folder-path]\cmder\cmder.exe` in whatever path it is in and Cmder will set `%cmder_root%` for you when it starts.

**Comment by simonpeterdebbarma** [comment]
Oh nice! Awesome tip @daxgames . I'll give it a shot as well.

**Comment by hectormz** [comment]
@simonpeterdebbarma I think you have to exit all cmd windows etc to load the new env variables. There may be a simpler fix.

**Comment by aliahmadcse** [comment]
I have integrated cmder using the profile below:
{
        "guid": "{00000000-0000-0000-ba54-000000000132}",
        "name": "Cmder",
        "commandline": "cmd.exe /k C:/cmder/vendor/init.bat",
        "icon": " C:/cmder/icons/cmder_red.ico",
        "hidden": false,
        "closeOnExit": true,
        "cursorColor": "#FFFFFF",
        "cursorShape": "bar",
        "historySize": 9001,
        "padding": "8, 8, 8, 8",
        "snapOnInput": true,
        "startingDirectory": "%USERPROFILE%"
      }

I Hope, this may help someone.

**Comment by santagada** [comment]
I've tried cmder in hyper and fluent terminal, I'm now using it in fluentterminal, conemu performance is really bad when theres a lot of text to print. Will try the new terminal as well.

**Comment by ShadyAlfred** [comment]
My opinion isn't a real solution, but if you use cmder for the Linux commands like: ls, touch, etc... Those commands come with git if you have it installed, you can add the path of these commands to your environment paths, and you'll have ls, touch, grep, etc... working in cmd and even PowerShell. I think PowerShell with the new terminal can be a nice experience, specially with some extensions like oh-my-posh.

**Comment by Acid-Crash** [comment]
Hi here.
I have some issues with setting up Cmder to work properly.
For some reason Terminal fails to recognize `%cmder_root%` environment variable despite it is set up correctly.
Cmder is installed for me in c:\Program Files\Cmder\
Environment variables are set up per this guide
https://github.com/cmderdev/cmder/wiki/Setting-up-Environment-Variables

Try 1:
`"commandline": "cmd.exe /k %cmder_root%/vendor/init.bat",`
"%cmder_root%" - is not an internal or external...

Try2:
`"commandline": "cmd.exe /k c:/Program Files/Cmder/vendor/init.bat"`
It gives error "c:/Program" is not an internal or external...


Try3:
Moved Cmder to the root of C drive
`"commandline": "cmd.exe /k c:/Cmder/vendor/init.bat",`
Now it works

Still, I would like to set up via proper div (c:/Program Files/Cmder/) or via %cmder_root%
Any hints how this can be acheived?

**Comment by jack1142** [comment]
@Acid-Crash that's just how arguments in shell usually work - if you want to use a space in argument (or use environment variable that contains space), you need to use quotes.
In this case, it would be:
```
"commandline": "cmd.exe /k \"C:\Program Files\Cmder\vendor\init.bat\""
```
or if you have `%cmder_root%` environment variable available:
```
"commandline": "cmd.exe /k \"%cmder_root%\vendor\init.bat\""
```

**Comment by daxgames** [comment]
@Acid-Crash also we do not recommend putting Cmder in `c:\program files` just not a good idea for other reasons.  The recommended place is in you `%userprofile%`

**Comment by Bartunek** [comment]
Setting it as @D3473R suggested in https://github.com/cmderdev/cmder/issues/2121#issuecomment-557718618 works great, but for some reason aliases don't work there. I'm running Cmder with the same command inside VSCode and aliases work there fine. I have my aliases as usual in `%cmder_root%/config/user-aliases.cmd`

Does anyone have an idea if it's some limitation of the new Windows Terminal or it's necessary to add some more specific configuration? Or am I missing something?
