### ISSUE TITLE
characters of commands got splitted and look  ugly connected to openssh 

### ISSUE THREAD

**Issue by mchenx** [cmderdev/cmder#2125]
### Purpose of the issue
- [x ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information
cmder 1.3.11
openssh 8.0.1
server : windows server 2016 core
client: windows 10 1903

### Description of the issue
after connected to openssh server on windows server 2016 core successfully

run commands like "help", "find", "docker"

then the command line interface becomes like this 

![image](https://user-images.githubusercontent.com/1550186/60854585-6602c480-a233-11e9-8e6d-313b73ec459b.png)

the cursor goes to the middle (a bit right) of the screen
![image](https://user-images.githubusercontent.com/1550186/60854805-1670c880-a234-11e9-8924-db29b271c846.png)

commands like "ls", "dir" are fine

**Comment by mchenx** [comment]
this problem remains in v1.3.12

**Comment by daxgames** [comment]
@mchenx from cmder type `where ssh`  what is the output?  If it is in the Windows directory you are not using ssh from cmder.  Does this happen if you ssh to the same server outside cmder?  If so contact the conemu devwlopers about this since it is likely a conemu issue and not cmder.

**Comment by mchenx** [comment]
this is what "where ssh" output

on remote win server 2016
![image](https://user-images.githubusercontent.com/1550186/66371870-2b95f880-e9d7-11e9-8e96-cf22c7d4dbfe.png)

local (client)
![image](https://user-images.githubusercontent.com/1550186/66371958-5aac6a00-e9d7-11e9-995a-c17a692889b1.png)
