### ISSUE TITLE
Cmder ignores start location if "Auto save/restore opened tabs" is turned on

### ISSUE THREAD

**Issue by NSExceptional** [cmderdev/cmder#2127]
### Purpose of the issue
- [x] Bug report
- [ ] Feature request
- [ ] Question

### Version Information
Cmder 1.3.2, Windows 10

### Description of the issue
I followed [these instructions](https://github.com/cmderdev/cmder/wiki/Context-menu-integration) to get a "Shell here" context menu working. It works, except when the _"Auto save/restore opened tabs"_ feature is turned on. I would expect that if I have it turned on and start Cmder by using _Shell here_ then I would get all of my saved tabs _plus_ a new tab in this location.

**Comment by daxgames** [comment]
1.  Its time to upgrade, the current released version is 1.3.11. :-)
2.  The behavior you expect is not how it works.

**Comment by NSExceptional** [comment]
> The behavior you expect is not how it works.

If what I expected was how it worked, I would not have posted... do you mean to say what I expect is not what is intended?

If so, why is that the case? My idea seems like expected behavior to me.

**Comment by daxgames** [comment]
Sorry for my abrupt answer earlier.  Cmder is a collection of softwarewith some opinionated configuration.

The various pieces of software are maintained by different groups of people.

The intended behavior of the context menu is to open a shell in the specific folder.  If you have questions about the Auto/Save Restore feature should work you should ask the Conemu dev team.  Its not a feature i use so i cant answer that question.
