### ISSUE TITLE
Launch Cmder and run a command in it with a Bash script

### ISSUE THREAD

**Issue by TheHaricover** [cmderdev/cmder#2128]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Version Information
Cmder : Version 1.3.11.843
Conemu : Couldn't find it

Windows 10 Family 1809

### Description of the issue
I would like to start a new Cmder console and put a command in it, all of this with a bash script. I hope I'm not in the wrong place ! If so I'm sorry 🙏

**Comment by daxgames** [comment]
Looking at it.
