### ISSUE TITLE
Cmder not starting in user home but in cmder_root instead

### ISSUE THREAD

**Issue by cristovaov** [cmderdev/cmder#2129]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Version Information

Cmder V1.3.11.843
ConEmu 180626

Win8.1
### Description of the issue

Hi there, I've just upgraded from 1.3.5 to 1.3.11.843. When I now launch Cmder the startup directory is no longer my home profile (`C:\User\<username>`) directory (`but the `[cmder_root]` path instead -- {bash::bash} set to default startup task.  

Is this a change that's been made with Cmder or its vendors ?
What do you suggest is best to get back to startup in my home directory?

Thx in advance.

**Comment by daxgames** [comment]
The latest Cmder opens in the current working directory as most all windows apps do by standard.  This is working as expected and was done by MULTIPLE user requests.  You can create a shortcut and set the start in folder to be `"%userprofile%"`.

**Comment by cristovaov** [comment]
Thanks for the clarification. I was just surprised/confused. Cheers!

>
