### ISSUE TITLE
Cmder wiki has the wrong instructions for VSCode integration

### ISSUE THREAD

**Issue by kerabyte** [cmderdev/cmder#2130]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

Cmder v1.3.11
Visual Studio Code v1.36.1

### Description of the issue

The Cmder wiki states:

> Append or modify the following variables into your configuration file:

```json
"terminal.integrated.shell.windows": "cmd.exe",

"terminal.integrated.env.windows": {
"CMDER_ROOT": "[cmder_root]"
},
"terminal.integrated.shellArgs.windows": [
    "/k [cmder_root]\\vendor\\init.bat"
],
```

However, this does not work. When [cmder_root] is replaced with the path to my Cmder installation directory, the VSCode integrated terminal just opens up to normal cmd.exe.
When CMDER_ROOT is added as an environment variable, which then substitutes [cmder_root] as `%CMDER_ROOT%`, the same thing occurs.

To get it working, I used these options instead:
```json
"terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe",
"terminal.integrated.shellArgs.windows": [
    "/K",
    "[cmder_root]\\vendor\\init.bat"
]
```
replacing [cmder_root] with the path to my Cmder installation directory.

**Comment by daxgames** [comment]
Updated Wiki. @kerabyte you should go look as it has updated info to fix some issues with using VS Code with cmder.
