### ISSUE TITLE
Cmder's shell in other terminals-I need some help Please

### ISSUE THREAD

**Issue by Toby69Sheba59** [cmderdev/cmder#2132]
First I have to say that Cmder is very cool and thanks to those who created it..

So i am tring to get the Cmder's shell in other terminals to work and I just cannot so I must be doing something wrong...

- I have a folder C:\CMDER with CMDER installed in it..........

- I have C:\CMDER added to the PATH in the SYSTEM VARIABLES

- I created the cmder_shell.bat and it is in the C:\CMDER folder

@if "%cmder_init%" == "1" (goto :eof) else (set cmder_init=1)
@pushd %CMDER_ROOT%
@call "%CMDER_ROOT%\vendor\init.bat" /f
@popd

- When I run cmder_shell here is what I get

C:\>cmder_shell
The system cannot find the path specified.

- I checked the following

C:\>where cmder
C:\CMDER\Cmder.exe

C:\>where cmder_shell
C:\CMDER\cmder_shell.bat

I am kinda new to some of the programming stuff, but I just don't know where i went wrong....

So please help if you can.....

Thanks

**Comment by daxgames** [comment]
How did you add Cmder to the path? If using the GUI did you open a new shell after adding it?  Changes the the environment using the GUI do not affect current shells.

Check the current shell path: `echo %path%`.

**Comment by Toby69Sheba59** [comment]
I checked it and it using the echo %path% and c:\cmder is there

 

 

 

 

David A. Richwalski

 <mailto:d_richwalski@hotmail.com> d_richwalski@hotmail.com

**Comment by daxgames** [comment]
I did the following:

1. Expand `cmder.zip` to `c:\cmder`
2. Create `c:\cmder\cmder-shell.cmd` with the below content:

   ```
   @echo off

   pushd %CMDER_ROOT%
   call "%CMDER_ROOT%\vendor\init.bat" /f
   popd
   ```
3. Open a windows command prompt and type `setx path %path%;c:\cmder` to add `c:\cmder` to the users path permanently.  This requires a new windows console to take effect.
4. Close the current windows command prompt.
5. Open a new windows command prompt and type `cmder-shell`

This worked for me.
