### ISSUE TITLE
Is it possible to generate a script that will open multiple windows or tabs of cmder and a few instructions in each?

### ISSUE THREAD

**Issue by gtludwig** [cmderdev/cmder#2135]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Version Information

1.3.11.843

Windows 10 Pro

### Description of the issue

I would like a script that would do the following steps:

0. loop through a list of directories
1. create a new cmder window or tab
2. rename the window or tab title bar
3. cd into a specific directory
4. execute a series of commands
5. if the directory is the last of the list, end script

Is this possible? Does anyone have an example I can get ideas from?

**Comment by colderleo** [comment]
I have the same need. Could anyone help?

**Comment by daxgames** [comment]
This is more a question about capabilities of Conemu the terminal emulator Cmder uses.  It may already be asked over [here](https://github.com/Maximus5/ConEmu/issues)

**Comment by daxgames** [comment]
Or [here](https://conemu.github.io/)
