### ISSUE TITLE
Chinese display is not normal

### ISSUE THREAD

**Issue by sonwnja** [cmderdev/cmder#2138]
![image](https://user-images.githubusercontent.com/15842446/62751776-8b375c80-ba97-11e9-8168-73792dfd2c8c.png)
display no normal

**Comment by Stanzilla** [comment]
what would be normal in this case?

**Comment by benzBrake** [comment]
Uncheck `Compress long strings to fit space` to fix it.
<img width="572" alt="fix chinese" src="https://user-images.githubusercontent.com/11323774/62945050-8b758600-be10-11e9-979c-b235cbf341d7.png">
