### ISSUE TITLE
Cmder doesn't launch a task anymore

### ISSUE THREAD

**Issue by lesktimo** [cmderdev/cmder#2139]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

Cmder v. 1.3.11.843
ConEmuC v. 18.6.26.0

Windows 10 Enterprise 10.0.17763 Build 17763
### Description of the issue

I've had cmder running WSL debian for several months now without a problem. Suddenly today that (default) task stopped working. I've not changed any setting or anything prior the error. The error message I get is as follows:

> 'C:\Program' is not recognized as an internal or external command, operable program or batch file.
> 
> Current directory:
> C:\Users\{myUsername}
> 
> Command to be executed:
> "C:\windows\SYSTEM32\cmd.exe /C C:\Program Files\WindowsApps\TheDebianProject.DebianGNULinux_1.1.6.0_x64__76v4gfsz19hv4\debian.exe
>
> ConEmuC: Root process was alive less than 10 sec, ExitCode=1.
> Press Enter or Esc to close console...

Cmder itself is installed to C:\cmder and debian WSL is installed to that directory in the error since it's from the Microsoft Store. I have no rights to operate in WindowsApps in this system.

I've already tried to include the path in the task inside both single ('') and double ("") quotes, quote only 'Program Files' with both quotes. I've also tried to escape the space using '^' (Program^ Files), 'progra~1' and '%ProgramFiles%' and none of the above work.

**Comment by daxgames** [comment]
@lesktimo Can you launch it outside Cmder?

**Comment by lesktimo** [comment]
@daxgames Yes, I can.

**Comment by daxgames** [comment]
If you are running WSL in Cmder technically you are not using Cmder, you are in fact running WSL on ConEmu.

According to [ConEmu - Bash on Windows](https://conemu.github.io/en/BashOnWindows.html)

WSL Task should look like:
```
set "PATH=%ConEmuBaseDirShort%\wsl;%PATH%" & %ConEmuBaseDirShort%\conemu-cyg-64.exe --wsl -cur_console:pm:/mnt
```

This works for me.

**Comment by lesktimo** [comment]
Thanks for response. My configuration used to work. I will check tomorrow if I can get it to work with your settings.

**Comment by daxgames** [comment]
@lesktimo You all set?
