### ISSUE TITLE
"Your alias cannot contain a space"

### ISSUE THREAD

**Issue by metude** [cmderdev/cmder#214]
I would like to assign `php artisan` alias with `art`. But when run `alias art='php artisan'` gives me "Your alias cannot contain a space"

**Comment by Jackbennett** [comment]
Now is fixed tested as of 1.3-pre. the bat PR fix could have landed sooner I'm not sure specifically what it was.

`alias art=php artisan` works fine.

**Comment by GhislainMitahi** [comment]
en voulant changer le port de mon serveur avec "php artisan --port:5090" il m'affiche "The "--port:5090" option does not exist."

que faire ?

**Comment by Jackbennett** [comment]
I think you need `php artisan serve --port=8080` / `php artisan serve --port 8080` or maybe `SERVER_PORT="8080" php artisan serve` should work.

Args are always `<space>` or `=`. The colon is something just for artisan.

**Comment by GhislainMitahi** [comment]
Thanks more dear 🙏🙏
