### ISSUE TITLE
clipping

### ISSUE THREAD

**Issue by herbthecoder** [cmderdev/cmder#2140]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

**Comment by herbthecoder** [comment]
After I installed cmder on Windows 10 Pro, some of my program windows are being clipped.
When I try to resize some programs, I get white of black space in the areas which were resized.
This started happening after I installed cmder and Docker for Windows.

**Comment by Stanzilla** [comment]
Not a cmder issue
