### ISSUE TITLE
remove mactype warning

### ISSUE THREAD

**Issue by dfc643** [cmderdev/cmder#2141]
i tried to modify ConEmu file to remove MacType warning,
and it works.

### Usage
* remove old conemu in cmder ```vendor/conemu-maximus5```
* download patch and unzip new conemu to ```vendor/conemu-maximus5```
* restart your cmder

### What Modified
* vendor/conemu-maximus5/ConEmu/ConEmuCD.dll
* vendor/conemu-maximus5/ConEmu/ConEmuCD64.dll

### Download
https://mega.nz/#!dwo0BA4Q!M3NU6yJ6MA1Qs5atfpt0NNzFonvENos3KPZZrUkCQoU

**Comment by Stanzilla** [comment]
Do not distribute modified binaries here, please.
