### ISSUE TITLE
Messed up it's own dimensions when moving between 2 monitors 

### ISSUE THREAD

**Issue by zb-z** [cmderdev/cmder#2142]
### Purpose of the issue
- [x ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information
Version 1.3.11.843

ConEmu 180626 [64] Startup Info
  OsVer: 10.0.14393.x64, Product: workstation, SP: 0.0, Suite: 0x100
  Build: 1607, UBR: 3115, ReactOS: 0, Rsrv: 0, WINE: 0, PE: 0, R2: 0
  DBCS: 0, IMM: 1, Remote: 0, ACP: 1252, OEMCP: 437, Admin: 1
  Desktop: `Winsta0\Default`, SessionId: 1, ConsoleSessionId: 1, Theming: 1, DWM: 1
  Size: {0,0},{0,0}
  Flags: 0x00001000, ShowWindow: 0, ConHWnd: 0x00000000
  Handles: 0x00000000, 0x00000000, 0x00000000
  Active HKL: 0x0000000004090409
  GetKeyboardLayoutList: 0x00000000040904 0xFFFFFFFFE09904
ExecMod: C:\utils\cmder\vendor\conemu-maximus5\ConEmu64.exe

Proc tree:
ConEmu64        
  ConEmuC64   
    cmd             
    conhost        

Proc cmd lines:
ConEmu64.exe: /Icon "C:\utils\cmder\icons\cmder.ico" /Title Cmder

ConEmuC64.exe: "C:\utils\cmder\vendor\conemu-maximus5\ConEmu\ConEmuC64.exe"  /CINMODE=600020 /AID=10548 /GID=7948 /GHWND=00E70084 /BW=89 /BH=30 /BZ=1000 "/FN=Lucida Console" /FW=3 /FH=5 /TA=10100007 /HIDE /ROOT cmd /k ""%ConEmuDir%\..\init.bat" "

conhost.exe: \??\C:\Windows\system32\conhost.exe 0x4
cmd.exe: "C:\Windows\SYSTEM32\cmd.exe"  /k ""C:\utils\cmder\vendor\conemu-maximus5\..\init.bat" "

### Description of the issue

When I drag the console from screen with higher dpi to the one with lover it changes width/height at it's own volition. On this setup from 120x30 (which is set up as default for cmd.exe) to  157x39. Of I leave Options dialog open the change is reflected there - live :-) If I change it back to 120x30 on lower dpi screen then it shrinks it to 91x22 when I drag it back to higher dpi screen.

Both screens are 4K, higher dpi is 15.6in, lower dpi is 27in.

"Console properties" (R-click in status bar > Debug > Properties) remain at 120x30 but info in that dialog is insanely off in all other aspects (doesn't reflect actual colors and shows font size as 5pt - default is set to 16 and is used in both plain and cmdr process). 

Cmder.exe was started by a plain D-click in explorer window open to the folder where it was placed (no install took place,l - folder was virgin unpack of cmder_mini.zip).

**Comment by gazialankus** [comment]
I have the same issue. I think this should be reopened. This is between a 4K and a 1080P monitor.
1080P:
![2020-02-22 22_31_50-Cmder](https://user-images.githubusercontent.com/412997/75098096-2a025100-55c3-11ea-8150-e7dbc7bfc03d.png)
Moved the window to 4K (much smaller window):
![2020-02-22 22_32_00-Cmder](https://user-images.githubusercontent.com/412997/75098098-2c64ab00-55c3-11ea-95bc-79546de4d816.png)
I think this issue should be reopened.

**Comment by daxgames** [comment]
@gazialankus Its not a cmder problem. Its the terminal emulator cmder uses and that is conemu.  If you think its an issue open one there.

**Comment by zb-z** [comment]
Stubbornly and arrogantly deflecting the problem and telling people "go to another site, waste countless hours and maybe report there" is counterproductive. It is **YOU RESPONSIBILITY** to propagate/escalate problems with whatever you took as a dependency. It's a slap in a face and the sole result is that people are going to walk away - I did.

We are not going to "research" your dependencies, we don;t know where what you consider "your area" stops and "their area" starts and we are certainly not going to serve as ping-pong balls between two "teams"  in whatever feud you have. If someone would would put in disproportionate effort go "go there", wherever it might be, he'd be faced with "you have to 'try' and report with 'just our code', without whatever someone else piled up on top of it". 

You can say "we don't care" or "we are not going to fix anything" or "this project is defunct" but don't go repeatedly insulting everyone who makes an effort to report a problem.

Why did you take a dependency if you don't know how to handle it and don't want to put any effort into it? If you don;t want or don;t know how to take care of things then please just close the project and remove binaries to that people don't waste time on it.

**Comment by daxgames** [comment]
@zb-z Sorry you take offense and feel that we are insulting our users by redirecting issues to another project that we use as a default component but the fact remains this issue occurs whether Conemu is used with or without cmder invlovement.

Our issue template clearly states we do not handle Conemu issues and directs users to open terminal emulator issues with the Conemu team

```
  • Please understand that Cmder uses ConEmu as the default underlying Terminal Emulator.  If your issue is regarding the **Terminal Emulator**, please visit the ConEmu issues page:

    https://github.com/Maximus5/ConEmu/issues?q=is:issue

    If there isn't an existing issue, you may open a new one there.
```

This project is not 'defunct', there is no 'feud' with Conemu, and we do care about users issuesand requests.  We simply do not have the resources or the experience with the Conemu codebase to assist in issues with Conemu.

This is a volunteer effort and I spend much of my weekend looking at issues and feature requests from users like you that I can help with so redirecting users to where they can get help when I cannot is the best use of my limited free time.

If you don't like how Cmder works with Conemu then you can use it with pretty much any other terminal emulator.  Look at the [wiki](https://github.com/cmderdev/cmder/wiki#integrate-cmder-with-other-terminalides) for others that have been tried.
