### ISSUE TITLE
How does bin work?

### ISSUE THREAD

**Issue by Mega-Volt** [cmderdev/cmder#2145]
I'm looking to use a portable console such as Cmder to run commands such as 'ffmpeg', 'code', 'python' or 'node' from computer to computer. I have downloaded all of them ([screenshot](https://i.imgur.com/2oQBeRm.png)) but none of the commands work. I read the wiki, couldn't find anything and the issues page didn't help any.

My question is can I run 'node' or do I have to write 'bin/node-v10.16.3/node.exe' every time?

**Comment by daxgames** [comment]
Anything in `%cmder_root%/bin/[filename]` will execute simply by typing the executeable filename.  If the executeable dike is in a subdirectory of bin you have tqo options.

1.  Write a shim cmd file, `%cmder_root%/bin/node.cmd` that points at the real `node.exe`
2.  Telling `%cmder_root%\vendor\init.bat` to add sub-directories of `%cmder_root%/bin` to the path in addition to `%cmder_root%/bin`.  Note: This slows down startup and could have other side effects.

I recommwnd the first option.

**Comment by Mega-Volt** [comment]
So after lots of trial and error, I ended up using `vscode="%CMDER_ROOT%\bin\vscode\bin\code.cmd" $*` in the config folder. I figured out that I had to remove the %cmder_root% from my path because that was redirecting everything to use the local config files and not my usb stick.
