### ISSUE TITLE
Replace Lambda in Powershell Durably

### ISSUE THREAD

**Issue by TheAjItator** [cmderdev/cmder#2146]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [x] Question

### Version Information

cmder v1.3.12.915

Windows 10 Pro 1803
### Description of the issue

It looks like there isn't a "hook" in thep config\user_profile.ps1 to replace the lambda symbol in the Powershell.  The CmderPrompt override in user_profile.ps1 doesn't do so.  It looks like one needs to modify vendor\profile.ps1 in order to change the prompt character, but this is susceptible to overwrite on upgrade.
Maybe I'm missing something?  If I'm not, this would be a nice feature to bring parity with the functionality supported in cmd side of things.

**Comment by CollinChaffin** [comment]
No @TheAjItator the config/userconfig folders never contain anything in the install, hence will never be overwritten. However, I absolutely do agree it might be a nice thing to have for plug-ability at some point.

Also just to mention if you aren't aware (most I talk to don't realize this feature was even added) I put in the suggestion and @daxgames did an awesome job implementing it at lighting speed:  The ability to separate cmder to multi-user/multi-profile (think almost anything).  In that case, all users and run profiles I have set up have their own totally separate `config` folder, which then contain totally different configs/tasks/prompts/lua/etc.

More info here if interested:  https://github.com/cmderdev/cmder/pull/1949

**Comment by TheAjItator** [comment]
Thanks for the reply.

Are you saying you are "voting" for a way to override the prompt symbol for PowerShell, i.e. that it's a feature that isn't there but would be good to have?

Additionally, to further clarify my initial post, I realize that I mistyped above.  The CMD side of cmder does have the ability to update the symbol at the prompt (the lambda symbol) by updating config\my_prompt.lua.
For PowerShell there are hooks in config\user_profile.ps1 to customize things _surrounding_ the prompt symbol ($PrePrompt, $CmderPrompt, $PostPrompt) however it seems one cannot change the actual symbol short of editing the vendor\profile.ps1 file.  The symbol is "hardcoded" into the line after the CmderPrompt line. (See below)

`PrePrompt | Microsoft.PowerShell.Utility\Write-Host -NoNewline`
`CmderPrompt`
``Microsoft.PowerShell.Utility\Write-Host "`nλ " -NoNewLine -ForegroundColor "DarkGray"``
`PostPrompt | Microsoft.PowerShell.Utility\Write-Host -NoNewline`

I'm asking if this issue can be treated as an enhancement request, or if the functionality exists, can one guide me how to do so?

**Comment by daxgames** [comment]
@TheAjItator you can override the promp using `user_profile.ps1` and if the `profile.ps1` sees it was modified from the Windows Powershell default prompt it will not attempt to set it to the Cmder default pompt.  See line 171 in `profile.ps1`

**Comment by daxgames** [comment]
@TheAjItator  SUPER simple example add the below to `$env:cmder_root\config\user_profile.ps1` changes lambda to `$`

```
[ScriptBlock]$Prompt = {
    $realLASTEXITCODE = $LASTEXITCODE
    $host.UI.RawUI.WindowTitle = Microsoft.PowerShell.Management\Split-Path $pwd.ProviderPath -Leaf
    PrePrompt | Microsoft.PowerShell.Utility\Write-Host -NoNewline
    CmderPrompt
    Microsoft.PowerShell.Utility\Write-Host "`n$ " -NoNewLine -ForegroundColor "DarkGray"
    PostPrompt | Microsoft.PowerShell.Utility\Write-Host -NoNewline
    $global:LASTEXITCODE = $realLASTEXITCODE
    return " "
}

```

**Comment by TheAjItator** [comment]
@daxgames I was thinking that function in `vendor\profile.ps1` wasn't to be overridden, particularly with the comment above the `config\user_profile.ps1` method `[ScriptBlock]$CmderPrompt` ("Replace the cmder prompt entirely with this.").  I tried modifying that and it **did not** replace the prompt entirely.  One could argue the terminology is a bit ambiguous, but that's minor.

Thanks for the info.

One question: Any thought that having to override the whole thing could lead to issues with updates later on?

Appreciate it.

**Comment by TheAjItator** [comment]
So I tried it after posting the above comment....and it did not replace the prompt.

**Comment by daxgames** [comment]
`user-profile.ps1` is your file, put whatever you want in it.  As it says in the `profile ps1` if the prompt is changed in the `user-profile.ps1` from the default the cmder prompt is ignored so no issues on upgrades.  To be sure you could grab all prompt methods from `profile.ps1` and put them in your `user-profile.ps1`

It works for me on cmder 1.3.11 and should work on 1.3.12.  I will post my entire `user-profile.ps1` in a few minutes.

**Comment by daxgames** [comment]
this is what I did to make it work for Cmder 1.3.12:

```
# You need everything below here to change the prompt 

# Pre assign the hooks so the first run of cmder gets a working prompt.
[ScriptBlock]$PrePrompt = {}
[ScriptBlock]$PostPrompt = {}
[ScriptBlock]$CmderPrompt = {
    $Host.UI.RawUI.ForegroundColor = "White"
    Write-Host -NoNewline "$([char]0x200B)"
    Microsoft.PowerShell.Utility\Write-Host $pwd.ProviderPath -NoNewLine -ForegroundColor Green
    if (get-command git -erroraction silentlycontinue) {
        checkGit($pwd.ProviderPath)
    }
}

<#
This scriptblock runs every time the prompt is returned.
Explicitly use functions from MS namespace to protect from being overridden in the user session.
Custom prompt functions are loaded in as constants to get the same behaviour
#>

[ScriptBlock]$Prompt = {
    $realLASTEXITCODE = $LASTEXITCODE
    $host.UI.RawUI.WindowTitle = Microsoft.PowerShell.Management\Split-Path $pwd.ProviderPath -Leaf
    PrePrompt | Microsoft.PowerShell.Utility\Write-Host -NoNewline
    CmderPrompt
    Microsoft.PowerShell.Utility\Write-Host "`n$ " -NoNewLine -ForegroundColor "DarkGray"
    PostPrompt | Microsoft.PowerShell.Utility\Write-Host -NoNewline
    $global:LASTEXITCODE = $realLASTEXITCODE
    return " "
}

Set-Item -Path function:\PrePrompt   -Value $PrePrompt   -Options Constant
Set-Item -Path function:\CmderPrompt -Value $CmderPrompt -Options Constant
Set-Item -Path function:\PostPrompt  -Value $PostPrompt  -Options Constant

Set-Item -Path function:\prompt  -Value $Prompt  -Options ReadOnly
```

**Comment by daxgames** [comment]
You can do less  but this does what you asked and keeps all existing functionality

**Comment by daxgames** [comment]
If you like powerline follow this instead of the above:

https://github.com/JanDeDobbeleer/oh-my-posh

**Comment by daxgames** [comment]
A better screenshot with fonts:

![image](https://user-images.githubusercontent.com/7318053/65804558-4e5f1c00-e150-11e9-8013-2cbe4ae703cf.png)

**Comment by TheAjItator** [comment]
After replicating all the code suggested (from `profile.ps1` to `user-profile.ps1`), I was able to change the symbol without modifying the `profile.ps1` file.
