### ISSUE TITLE
Unicode characters not working properly

### ISSUE THREAD

**Issue by sebolio** [cmderdev/cmder#2150]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

1.3.11.843

Windows 10 1903 Home

### Description of the issue

I'm using "vue" CLI to create VueJS projects, and it uses a character string (❯) to highlight the current choice on a menu. It shows perfectly on Webstorm's terminal, **even here on github!!!**, but Cmder shows a question mark symbol instead. I've tried different font types and the problem persists. Webstorm uses Fira Code Retina. 

Looks like this:
![image](https://user-images.githubusercontent.com/197329/63875722-11a5d680-c992-11e9-995a-26d8b936a087.png)

Should look like this:
![image](https://user-images.githubusercontent.com/197329/63875757-2aae8780-c992-11e9-90f9-55456580c08a.png)

**Comment by Stanzilla** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem with that, please open a bug over at https://github.com/Maximus5/ConEmu

Thank you! :)
