### ISSUE TITLE
Cmder Update

### ISSUE THREAD

**Issue by rlsalgueiro** [cmderdev/cmder#2152]
- # Feature request (request for new functionality)
- Cmder update, not update only ConEmu, everu time i update Cmder i lost all my config.

- [ ] Question
Why cmder don't have update option?

### Version Information
cmder 1.3.10.811 ConEmu 190526 Windows 10 1903 18362.267
CMder doesn't have its own update, it only updates ConEmu, when I update manually I lose all the configurations of the version I have.

**Comment by daxgames** [comment]
Cmder updates nothing. Conemu updates conemu.  Cmder update procedure is in the readme.md.
