### ISSUE TITLE
First run error

### ISSUE THREAD

**Issue by Lazar-as** [cmderdev/cmder#2154]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

Cmder v1.3.12
Windows 10 1903

### Description of the issue
When I'm running Cmder for the first time (fresh install) I get some permission errors.

> Generating clink initial settings in "C:\Cmder\config\settings"
        1 file(s) copied.
Additional *.lua files in "C:\Cmder\config" are loaded on startup.
Creating initial user_aliases store in "C:\Cmder\config\user_aliases.cmd"...
        1 file(s) copied.
Running Git for Windows one time Post Install....
"running post-install"
mkdir: cannot change permissions of ‘/dev/shm’: Permission denied
mkdir: cannot change permissions of ‘/dev/mqueue’: Permission denied
'C:\Windows\system32\drivers\etc\hosts' -> '/etc/hosts'
'C:\Windows\system32\drivers\etc\protocol' -> '/etc/protocols'
'C:\Windows\system32\drivers\etc\services' -> '/etc/services'
'C:\Windows\system32\drivers\etc\networks' -> '/etc/networks'
The batch file cannot be found.
Creating user startup file: "C:\Cmder\config\user_profile.cmd"
        1 file(s) copied.

**Comment by erikjasiak** [comment]
I'm new-ish to cmder, but finding that my git tools / unix links in general are hosed up unless I adjust my path in cmder.  Looking for more documentation, and may write up a separate bug - this messes with ssh as well and looks to overlap with 2-3 different things I'm seeing in issues.  It's unclear if the "permission denied" is because it's finding the target and they are locked down from a previous admin run, or because the targets are not found at all.  (Yes, it says "Permission denied" but ssh errors are similarly ambiguous sometimes.)

_In general_, unless I do a `set PATH={put git for windows binaries in front of path};{rest of path}`, then things like `ls /tmp` or `ssh-add -l` fail.  Not sure what interferes enough to throw that off yet though.

I'll dig in a little more when I can.  Windows 10 ver 1903 x64

**Comment by erikjasiak** [comment]
Add'l clarification - "fail" before I change my %PATH% are things like:
`λ ls /tmp
ls: /tmp: No such file or directory`

Starting `ssh-agent` and running `ssh-add` seems to be fixed when I use the cmder with built in git tooling.

**Comment by daxgames** [comment]
@Lazar-as completely normal.  That is cmder running  git for windows one time startup script per the git for windows portable documenration.

**Comment by daxgames** [comment]
@Lazar-as I did not see the comment on the manual path mod being required to use Cmder built in git for windows.  That is definitely not normal.

Can you provide what your pTh looks like from a normal cmd.exe prompt and what it looks like after starting cmder?

**Comment by Lazar-as** [comment]
cmd

> C:\MSYS64\mingw64\bin
C:\Windows
C:\Windows\System32
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
C:\Windows\System32\OpenSSH\
C:\Program Files\dotnet\
C:\Program Files\Microsoft SQL Server\130\Tools\Binn\
C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\
C:\Cmder
C:\Users\Lazar\AppData\Local\Microsoft\WindowsApps
C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.1\bin
C:\Users\Lazar\AppData\Local\Programs\Microsoft VS Code\bin

Cmder

> C:\Cmder\bin
C:\Cmder\vendor\bin
C:\Cmder\vendor\conemu-maximus5\ConEmu\Scripts
C:\Cmder\vendor\conemu-maximus5
C:\Cmder\vendor\conemu-maximus5\ConEmu
C:\MSYS64\mingw64\bin
C:\Windows
C:\Windows\System32
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
C:\Windows\System32\OpenSSH\
C:\Program Files\dotnet\
C:\Program Files\Microsoft SQL Server\130\Tools\Binn\
C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\
C:\Cmder
C:\Users\Lazar\AppData\Local\Microsoft\WindowsApps
C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.1\bin
C:\Users\Lazar\AppData\Local\Programs\Microsoft VS Code\bin
C:\Cmder\vendor\git-for-windows\cmd
C:\Cmder\vendor\git-for-windows\mingw64\bin
C:\Cmder\vendor\git-for-windows\usr\bin
C:\Cmder

**Comment by daxgames** [comment]
Just type `set path` in each and send the unmodified output please.

**Comment by Lazar-as** [comment]
@daxgames Sorry for that.

cmd
>Path=C:\MSYS64\mingw64\bin;C:\Windows;C:\Windows\System32;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Users\Lazar\AppData\Local\Microsoft\WindowsApps;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.1\bin;;C:\Users\Lazar\AppData\Local\Programs\Microsoft VS Code\bin;
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC

Cmder
Path=C:\Cmder\bin;C:\Cmder\vendor\bin;C:\MSYS64\mingw64\bin;C:\Windows;C:\Windows\System32;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Users\Lazar\AppData\Local\Microsoft\WindowsApps;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.1\bin;C:\Users\Lazar\AppData\Local\Programs\Microsoft VS Code\bin;C:\Cmder\vendor\git-for-windows\cmd;C:\Cmder\vendor\git-for-windows\mingw64\bin;C:\Cmder\vendor\git-for-windows\usr\bin;C:\Cmder
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC

**Comment by daxgames** [comment]
@Lazar-as I don't see any issues with your path.

`ls /tmp` will fail because `cmder` is not bash.  Try:

```
c:
λ ls /windows
λ ls /windows ls: /windows: No such file or directory
λ ls \windows
[This will display the contents of the c:\windows folder]
```

**Comment by daxgames** [comment]
@Lazar-as you OK with the above explanation or is it still an issue?

**Comment by Lazar-as** [comment]
@daxgames Yeah, everything works fine. Thank you for explanation.

**Comment by ChipClark** [comment]
Set the following path variable %CMDER_ROOT% - and the message no longer appears.

CMDER runs .\vendor\init.bat - and it is looking for this variable.
