### ISSUE TITLE
Cmder Git tags show up twice

### ISSUE THREAD

**Issue by doubleUTF** [cmderdev/cmder#2155]
### Purpose of the issue
- [X ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

ConEmu 180626
Cmder 1.3.10.811

Win 10 Pro 1903
### Description of the issue

The tag displayed in folders with git repositories are duplicated. Please see the screenshots.
![duplace2](https://user-images.githubusercontent.com/17230520/64133132-02a39780-cd89-11e9-850e-818dd6a95ced.png)
![duplicate1](https://user-images.githubusercontent.com/17230520/64133133-02a39780-cd89-11e9-9626-98fcad6e3101.png)

**Comment by andytruett** [comment]
Do you have a `git.lua` in your config folder?
Could be related to https://github.com/cmderdev/cmder/issues/494

**Comment by doubleUTF** [comment]
Yea there is, but I don't know what to do with it. So I just installed a fresh copy of cmder to remove this  graphical bug. Thanks.
