### ISSUE TITLE
Theme not applied on Run command prompt here

### ISSUE THREAD

**Issue by c4d3r** [cmderdev/cmder#216]
When i richt click for the first time and i use the action: Open Command window here. It opens ConEmu but without the skin from cmder

Using Windows 8.1 64-bit pro

**Comment by Jackbennett** [comment]
`Shift + R-click` offers "Open Command Window Here" That's from windows itself. If you configure conEmu to be the default terminal I believe that should open in a fresh conemu instance as you describe.

Register the cmder hook with `cmder.exe /REGISTER ALL` to see "Cmder Here" in the nomral `R-click` context menu.

I believe that was your problem.
