### ISSUE TITLE
How to find source of double entry of cmder-related paths in %PATH%

### ISSUE THREAD

**Issue by epogrebnyak** [cmderdev/cmder#2160]
In `%PATH%` variable some cmder-related paths are found at the start of string and some at the end:

```
PATH=D:\Programs\Cmder\bin
D:\Programs\Cmder\vendor\conemu-maximus5\ConEmu\Scripts
D:\Programs\Cmder\vendor\conemu-maximus5
D:\Programs\Cmder\vendor\conemu-maximus5\ConEmu

C:\tools\ruby26\bin
C:\Program Files\Haskell\bin
C:\Program Files\Haskell Platform\8.4.3\lib\extralibs\bin
C:\Program Files\Haskell Platform\8.4.3\bin
C:\Program Files (x86)\Common Files\Oracle\Java\javapath
C:\ProgramData\Oracle\Java\javapath
C:\Program Files (x86)\Intel\iCLS Client\
C:\Program Files\Intel\iCLS Client\
C:\Windows\system32
C:\Windows
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
# ...

C:\Program Files\Git\usr\bin
C:\Program Files\Git\usr\share\vim\vim74
D:\Programs\Cmder\
```
In my other installation on a notebook `c:\...\cmder\vendor\git-for-windows\cmd` is at the start and `c:\...\cmder\vendor\git-for-windows\usr\bin` is at the end of the path.

My question what are the sources of path injections at the start and at the end of path? Which functionality controls the head part and which an end part?

Many thanks for clarification.

**Comment by daxgames** [comment]
As for cmder path elements its all in the i%cmder_root%\vendor\init.bat`.

You have called out git for windows paths that cmder did not add. 

* C:\Program Files\Git\usr\bin
* C:\Program Files\Git\usr\share\vim\vim74

'In my other installation on a notebook c:\...\cmder\vendor\git-for-windows\cmd is at the start and c:\...\cmder\vendor\git-for-windows\usr\bin is at the end of the path.', is the default behavior for current cmder releases.

**Comment by epogrebnyak** [comment]
@daxgames, thank you for pointing out to `%cmder_root%\vendor\init.bat`, it is now my idea of autoexec.bat, which I miss from DOS and early days of Windows as it provided clear way to compose path.

Closing the issue, may post some follow up on disection of path, still a bit unclear about the intent of git for windows inserting some dir to head and other to tail of PATH, maybe some precedence issue.

**Comment by daxgames** [comment]
Git for windows decides how to modify the path based on questions it asks during the install.  It asks something about what shells or tools would you like to use by default.

**Comment by daxgames** [comment]
@epogrebnyak You can add *.bat or *.cmd files to `%cmder_root%\config\profile.d` and they will be executed by the init.bat in alphabetical order.
