### ISSUE TITLE
cmder hangs on `git` command

### ISSUE THREAD

**Issue by hzhu212** [cmderdev/cmder#2161]
### Purpose of the issue
- [X] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

- Cmder: 1.3.12.915
- ConEmu: 180626
- Windows: Windows 10 1903

### Description of the issue

I just downloaded `cmder_mini.zip` from `https://cmder.net/`, and unzipped it into a folder under non-system disk (`D:\Protable\cmder\`). Then I opened `Cmder.exe` without any user-configuration, the command line always get stuck when using `git` commands (like `git --version`, `git --help`, `git status`, `git add`, etc). But other commands work well.

![2019-09-10_185541](https://user-images.githubusercontent.com/19285447/64608216-c0b7c880-d3fc-11e9-8cf9-cfbbc48ca1e4.jpg)

The following observations might help:

- Except `git`, all other commands work fine, like `ls`, `pwd`, `ssh`, `python`, `node`, etc.
- ~Only the following tasks stuck: `cmd::Cmder`, `Powershell::Powershell`, `bash::bash`. But `WSL::bash` never stuck, ether I call git of WSL (`/usr/bin/git`) or git-for-windows(`/mnt/c/Program Files/Git/bin/git.exe`).~
- Only happens in Windows Shells, including `cmd::Cmder` and `Powershell::Powershell`; but does not happen in Bashs, including `bash::bash`(git bash) and `WSL::bash`. Importantly, also does not happen in native `cmd.exe` and `powershell.exe`.
- When the tab is stuck, the only way to interrupt it is to close the tab, `Ctrl+C` doesn't work.
- When the tab is stuck, I can still create other tabs of any tasks, and they work correctly.
- When the tab is stuck, the command is indeed succeeded. For example, after one tab hanging on `git add .`, I can see from another tab that the files have already been added.

~To locate the problem, I also tried the underlying ConEmu and found the following clues:~

- ~Open `[CMDER_ROOT]/vendor/ConEmu.exe`, all tasks work well, and no stuck happened.~
- ~But open `[CMDER_ROOT]/vendor/ConEmu64.exe`, the problem appears like when using cmder.~

~It seems like a bug of `ConEmu64.exe`?~

~So, before this bug getting fixed, is there any hacking to make cmder call `ConEmu.exe`, instead of `ConEmu64.exe`?~

To locate the problem, I tried `ConEmu.exe` and `ConEmu64.exe` under the `[CMDER_ROOT]/vendor/conemu-maximus5/` directory, they all have the same problem. 

So it's probably a bug of ConEmu, not Cmder. I'm going to create an issue under ConEmu's repo.

**Comment by CollinChaffin** [comment]
What is your %PATH%?

**Comment by hzhu212** [comment]
> 
> 
> What is your %PATH%?

I copied this from `{cmd::Cmder}` console:

```
λ echo %PATH%
```

`D:\Portable\Cmder\bin;D:\Portable\Cmder\vendor\bin;D:\Portable\Cmder\vendor\conemu-maximus5\ConEmu\Scripts;D:\Portable\Cmder\vendor\conemu-maximus5;D:\Portable\Cmder\vendor\conemu-maximus5\ConEmu;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\libnvvp;C:\Program Files (x86)\Common Files\Intel\Shared Files\cpp\bin\Intel64;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;D:\Program Files\MATLAB\R2017a\runtime\win64;D:\Program Files\MATLAB\R2017a\bin;C:\Program Files\Java\jdk1.8.0_151\bin;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;D:\GreenTools\gradle-4.4\bin;C:\Program Files\mingw-w64\mingw64\bin;C:\WINDOWS\System32\OpenSSH\;D:\Program Files\mysql-5.6.41-winx64\bin;D:\Portable\Scripts;D:\ProgramFiles\nvm;C:\Program Files\nodejs;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\GnuWin32\bin;D:\Archive\Research\rayinvr\rayinvr-source\build;C:\Program Files (x86)\Simply Fortran 2\mingw-w64\bin;C:\Program Files (x86)\Simply Fortran 2\mingw-w64\x86_64-w64-mingw32\lib32;C:\Program Files (x86)\Simply Fortran 2\mingw-w64\x86_64-w64-mingw32\lib64;C:\Users\haley\AppData\Local\Programs\Python\Python36\Scripts;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;D:\ProgramFiles\cudnn\bin;C:\Users\haley\AppData\Roaming\Python\Python36\Scripts;C:\Program Files\NVIDIA Corporation\Nsight Compute 2019.1\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Users\haley\AppData\Local\Microsoft\WindowsApps;D:\ProgramFiles\nvm;C:\Program Files\Fiddler;C:\Users\haley\AppData\Local\Microsoft\WindowsApps;C:\Users\haley\AppData\Local\hyper\app-2.0.0\resources\bin;D:\ProgramFiles\nvm;C:\Program Files\nodejs;C:\Users\haley\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;D:\Portable\Cmder`

**Comment by daxgames** [comment]
@hzhu212 did you install 32bit or 64bit git for windows?  Just a guess but could you try uninstalling git and reinstalling git for windows 64bit.

Cmder.exe would need to be recoded to launch `conemu.exe`.  I am not quite sure why it distinguishes between the two but currently it does.  Its an easy thing and I may try it because I see no reason for what it is doing now.  I just don't have the cycles to do it right now.

**Comment by daxgames** [comment]
@hzhu212 before you do that type `where git` inside cmder and post the output.

**Comment by hzhu212** [comment]
@daxgames I just updated my Git-for-Windows from v2.22.0 to the newest v2.23.0. But unfortunately, it has no effect.

Besides, typing `where git` giving the following output:

```
λ where git
C:\Program Files\Git\cmd\git.exe
```

I'm sure it's the directory where I installed the newest Git-for-Windows.

**Comment by hzhu212** [comment]
@daxgames Sorry for my mistakes. I just found that it's not a problem of 32bits vs. 64bits, but the problem of ConEmu's supporting for Windows shells (Cmd and Powershell).

I have updated the issue, and I'm going to create a new issue under ConEmu's repo.

**Comment by daxgames** [comment]
What makes you say its a conemu issue?  Be specific.

**Comment by hzhu212** [comment]
@daxgames I tried both Cmder's underlying ConEmu and the newest standalone ConEmu(v190714), they all stuck in `cmd` and `powershell` tasks, but not stuck in `git-bash` and `WSL-bash` tasks, whether 32bits ConEmu or 64bits ConEmu I use.

So I think it's a problem of ConEmu, not Cmder.

There are mistakes in my previous description of the issue, which is misleading. I have updated it.

**Comment by jfustier-it** [comment]
Hey @hzhu212 can you link the issue posted on ConEmu repo?

**Comment by fv-leo** [comment]
> 

I had same problem too.

when i type git command ,like `git status` , cmder stuck.

I integrate cmder to Windows Terminal. the problem  still exist.
`cmd.exe /k "d:\cmder\vendor\init.bat"`

### Version Information
Cmder: 1.3.19.1181
ConEmu: 22.4.18.0
Windows: Windows 10 21H2 19044.1766

**Comment by baiyujianyi** [comment]
i also met this problem, try to set git.exe to compatibility mode. it works in mine

**Comment by mapfel** [comment]
I face this issue since a longer time. What do you mean by "set git.exe to compatibility mode", @baiyujianyi? Thanks
