### ISSUE TITLE
git tag at the wrong position with pwsh

### ISSUE THREAD

**Issue by Geobert** [cmderdev/cmder#2163]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information
ConEmu 190526 (issue shows on stable 161206 as well)

### Description of the issue
Using Windows' 10 Powershell it's working fine:
![image](https://user-images.githubusercontent.com/72570/64851206-d4d31400-d60e-11e9-943c-f3818e08662f.png)

Using pwsh:
![image](https://user-images.githubusercontent.com/72570/64851237-e3b9c680-d60e-11e9-8a62-00df9ef8c899.png)

EDIT: it's both pwsh 6 and 7preview3

Moreover, with pwsh 6, I got many errors on startup of the shell:
```
Set-PSReadlineOption : The type initializer for 'Microsoft.PowerShell.PSConsoleReadLine' threw an exception.
At C:\Users\Geob\AppData\Roaming\Cmder\vendor\profile.ps1:92 char:5
+     Set-PSReadlineOption -ExtraPromptLineCount 1
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Set-PSReadLineOption], TypeInitializationException
+ FullyQualifiedErrorId : System.TypeInitializationException,Microsoft.PowerShell.SetPSReadLineOption

Set-PSReadlineOption : The type initializer for 'Microsoft.PowerShell.PSConsoleReadLine' threw an exception.
At J:\Docs\WindowsPowerShell\Microsoft.PowerShell_profile.ps1:1 char:1
+ Set-PSReadlineOption -BellStyle None
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Set-PSReadLineOption], TypeInitializationException
+ FullyQualifiedErrorId : System.TypeInitializationException,Microsoft.PowerShell.SetPSReadLineOption
```

That I don't get with 7preview

**Comment by Geobert** [comment]
Still relevant today

**Comment by daxgames** [comment]
Looks fine to me:

![image](https://user-images.githubusercontent.com/7318053/68092041-0de07580-fe55-11e9-86c3-0566f02bae3a.png)

Running:

![image](https://user-images.githubusercontent.com/7318053/68092063-4718e580-fe55-11e9-80d1-fba66075fa98.png)

This is the latest Cmder pre-release [code](https://ci.appveyor.com/project/MartiUK/cmder/builds/28582111/artifacts) running with the latest Conemu 191012.

**Comment by daxgames** [comment]
Also tested with cmder 1.3.11 and posh-git 0.7.3.

I doubt this is a cmder issue.

**Comment by ViceIce** [comment]
looks strange here:

![image](https://user-images.githubusercontent.com/1798109/69722265-feccaa80-1116-11ea-946d-5ed3c8741173.png)

**Comment by daxgames** [comment]
@ViceIce yeah that looks strange but that is not what I get.

**Comment by ViceIce** [comment]
it's related to https://github.com/dahlbyk/posh-git/issues/592

**Comment by ViceIce** [comment]
`$GitPromptSettings.AnsiConsole = 0;` has to be set for posh-git >= 1.0.0

**Comment by spooky** [comment]
> 
> 
> `$GitPromptSettings.AnsiConsole = 0;` has to be set for posh-git >= 1.0.0

that fix doesn't work with beta 4 :(

**Comment by feafarot** [comment]
I was also not able to get this working on posh-git 1.0-beta4
Best thing I've managed to achieve is this:
```ps1
[ScriptBlock]$PostPrompt = {
    $GitPromptSettings.AnsiConsole = $false;
}
```
Which only works for the second command entry
![Screenshot_1](https://user-images.githubusercontent.com/2183846/103838725-7305ab80-5096-11eb-9b45-a0de41416490.png)

**Comment by dothar** [comment]
> I was also not able to get this working on posh-git 1.0-beta4
> Best thing I've managed to achieve is this:
> 
> ```powershell
> [ScriptBlock]$PostPrompt = {
>     $GitPromptSettings.AnsiConsole = $false;
> }
> ```
> 
> Which only works for the second command entry

Im having the exact same issue here

**Comment by Aaronontheweb** [comment]
Same, just started having this issue myself
