### ISSUE TITLE
terminal prompt not wrapping correctly while emulating mintty

### ISSUE THREAD

**Issue by imdaveho** [cmderdev/cmder#2165]
### Referencing #1392 (that were auto-closed but not resolved)

printing this: (86 chars):

`---------1---------2---------3---------4---------5----------6---------7---------8------` 

### Observed: 83rd - 86th are wrapped

----------------------------------------------------

## mintty settings:

<img src="https://user-images.githubusercontent.com/13990019/64912141-04f6e180-d6f9-11e9-823e-ff4ccd26e3a8.png" width=400 />

## window settings: `86w x 30h`:

<img src="https://user-images.githubusercontent.com/13990019/64912179-96665380-d6f9-11e9-84d2-af85d2cd2a6a.png" width=500 />

## result on mintty in cmder:

<img src="https://user-images.githubusercontent.com/13990019/64912202-ddecdf80-d6f9-11e9-8b69-f3e9b155156a.png" width=400 />

## result on mintty (standalone app):

<img src="https://user-images.githubusercontent.com/13990019/64912210-1987a980-d6fa-11e9-8c9b-f523a80e0870.png" width=400 />

## result on cmd:

<img src="https://user-images.githubusercontent.com/13990019/64912319-818abf80-d6fb-11e9-80f0-842d6afed523.png" width=500 />

**Comment by daxgames** [comment]
@imdaveho you are still setting a fixed window size in Conemu.  It could be font related it could be Conemu.  Either way its not a Cmder issue.
