### ISSUE TITLE
Latest addition of "--nolog" clink breaks cmd prompts

### ISSUE THREAD

**Issue by CollinChaffin** [cmderdev/cmder#2166]
If I simply remove the new "--nolog" from 2 lines in the new init.bat, my powerline/git prompts return to normal.  Otherwise, for some reason it breaks them I have not done any debugging yet but since it's reproducible on mult machines I wanted to report it right away.

**Comment by daxgames** [comment]
@CollinChaffin I just tried [this](https://github.com/AmrEldib/cmder-powerline-prompt),  no issues.  Is it intermittent?

**Comment by CollinChaffin** [comment]
No, with powerline prompt set up, Powershell remains unaffected and anything loading clink (only with the new `--nolog` renders a default prompt and I'll have to retest but now that I think about it, I wonder if clink even injects properly in those cases.  I'll update here as soon as I can I apologize I totally meant to provide more debug info but again - making only that change in init.bat removing only the new `--nolog` and restarting cmder, returned clink-based startup tabs to normal behavior.

**Comment by daxgames** [comment]
@CollinChaffin I must be missing something.

The link I posted was powerline for cmder clink.  Works fine with --nolog

**Comment by daxgames** [comment]
@CollinChaffin 

![image](https://user-images.githubusercontent.com/7318053/65804473-0a6c1700-e150-11e9-9f7f-2564c8e13bca.png)

**Comment by daxgames** [comment]
@CollinChaffin Unable to reproduce this.

**Comment by Zorgodon** [comment]
I also have this issue. I only get a lambda, colors and Ctrl+L if I remove --nolog from 2 lines. The lambda is white however, not grey like it should be. I have none of these issues in 161206/1.3.2

**Comment by daxgames** [comment]
@Zorgodon @CollinChaffin Try [this](https://ci.appveyor.com/project/MartiUK/cmder/builds/29908645/artifacts)

Apparently only Windows 7 is affected by the --no-log issue.

**Comment by CollinChaffin** [comment]
@daxgames Good to see this was finally able to be reproduced and fixed with latest PRs but this issue# should have also probably been listed on the changelog along with the later duplicate issue #s.  I try to report this stuff quick when I test new builds but for some reason this one was closed as not reproducible, and then months later others opened the exact same issue and only those are listed on the changelog.
 
I knew it was the issue since I've simply been hand-editing the init bat myself but still run WIN7 on most systems. :)

**Comment by daxgames** [comment]
@CollinChaffin the Windows 7 was the missing detail as it is only Windows 7 that has the problem.  Thanks.

**Comment by daxgames** [comment]
As for the changelog it will be updated.  I just wanted to get the fix out and tested.
