### ISSUE TITLE
start cmder with log4cxx error

### ISSUE THREAD

**Issue by tornadoyi** [cmderdev/cmder#2168]
Hi:
     Each time, there is log4xx error apperas when I launch cmder with default dialog arguments: {cmd::Cmder}. The detail errors as below:

log4cxx: No appender could be found for logger (SGEPLog.LogConfigControler).
log4cxx: Please initialize the log4cxx system properly.

**Comment by daxgames** [comment]
This is not coming from cmder.

**Comment by tornadoyi** [comment]
> This is not coming from cmder.
This error appears when I launch Cmder and ConEmu lanuching is ok.

**Comment by tornadoyi** [comment]
> This is not coming from cmder.
I found that this error appears when I install git on my machine and I use Cmder mini version.
