### ISSUE TITLE
Set cursor to middle of the screen

### ISSUE THREAD

**Issue by meetjaydeep** [cmderdev/cmder#2169]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [x] Question

### Version Information
Version 1.3.8.793
Windows 10 Enterprise

### Description of the issue

Is there any setting to set the cursor always in the middle of the screen.
(Padding between cursor and the bottom)

![image](https://user-images.githubusercontent.com/1770120/65042205-ff59ff80-d975-11e9-89c1-7885b3750950.png)

**Comment by daxgames** [comment]
Can you clarify? I don't understand the question.

**Comment by meetjaydeep** [comment]
Something similar to 'Scroll-Forward' feature present in Command Prompt / Terminal

![image](https://user-images.githubusercontent.com/1770120/68575272-b31cce80-0491-11ea-949f-bdc1fb8e9824.png)

**Comment by daxgames** [comment]
Cmder uses ConEmu as terminal emulator, if you have feature request, are experiencing a problem or have a question, please open an issue over at https://github.com/Maximus5/ConEmu

Thank you! :-)

**Comment by PlaceofYichen** [comment]
Hi there,

Is there a similar "scroll-forward" feature (in cmd) for Cmder? 

Thank you so much.
