### ISSUE TITLE
Launcher opens new window separately

### ISSUE THREAD

**Issue by ghost** [cmderdev/cmder#217]
Hi there, I have an issue with Cmder v1.1.3, when i pin the launcher to the task bar instead of stacking new windows on top of the launcher it creates a new window. See below.

![cmder](https://cloud.githubusercontent.com/assets/8067713/3481355/a5dd82e2-036f-11e4-83f5-95510636bb17.png)

This is the full msysgit download, and i've tried re-downloading a few times.

Thanks!

**Comment by prust** [comment]
FWIW, I was able to work around this by installing Cmder to `AppData\Local` instead of `Program Files`.

**Comment by wadewegner** [comment]
I confirm that @prust's fix resolves this issue.

**Comment by Jackbennett** [comment]
In that case I'm willing to bet putting cmder anywhere but `Program Files` would fix this. Vista and onwards treats program files and bit more strictly.

**Comment by MartiUK** [comment]
@Jackbennett Correct, cmder needs to be extracted to somewhere where the current user can access without needing to escalate permissions. i.e. Program Files
