### ISSUE TITLE
A Few Product Questions

### ISSUE THREAD

**Issue by lastercaleb** [cmderdev/cmder#2171]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

**Comment by lastercaleb** [comment]
Why is it so hard to get these questions answered? The VA has a user who wants to use this product and we to vet it before he can install it.

**Comment by Stanzilla** [comment]
You did not ask a question?

**Comment by daxgames** [comment]
What question exactly as i don't see one being asked.

**Comment by Stanzilla** [comment]
Oh he put his questions into the comments, so it's not visible, hit edit to see them
