### ISSUE TITLE
Cannot make Cmder.exe as Default shell for remote ssh connections

### ISSUE THREAD

**Issue by sureshkotapydev** [cmderdev/cmder#2172]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

1.3.12.915

Windows server 2016

### Description of the issue

I cannot make Cmder.exe as Default shell for remote ssh connections. ssh connection is getting closed automatically.

**Comment by daxgames** [comment]
I am afraid I don't understand the issue.  Can you explain exactly what you are trying to do.?
