### ISSUE TITLE
Unable to create hotkey/macro to output perdefined text

### ISSUE THREAD

**Issue by 3cks82** [cmderdev/cmder#2175]
Hello, I am hoping someone could point me in the right direction. I am new to cmder and so far I really like the layout and everything. The one thing I am still having issues with is creating a shortcut or macro that will output certain text. Example: create a shortcut/macro to type the following "copy run scp://username@serverip//directory". This is something I use throughout the day along with a few similar ones. Is there a way to get this type of function out of cmder?

Thank you.

 

### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

**Comment by daxgames** [comment]
cmder uses `doskey` to provide alias like functionality in `cmd.exe` terminals.  you could look at [doskey documentation](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/doskey)

Try:

```
C:\Users\user\cmder_1.3.11
λ  alias s1=copy run scp:/username@serverip/directory
​C:\Users\user\cmder_1.3.11
λ  alias s1
s1=copy run scp:/username@serverip/directory
```

**Comment by 3cks82** [comment]
Thank you for getting back with me. I have setup aliases in cmder, which are working flawlessly. However, this doesn't seem to work as an alias. When I am ssh'd into a device and try to type the alias it doesn't work, it tries to resolve the name. Is there anyway to get this with a hotkey or a macro?

**Comment by daxgames** [comment]
Sorry i misunderstood your use case.

Aliases are to run in cmder.  If you need an alias on a remote device you need to create the alias there using proper syntax for that os.

Sounds like you are looking for a macro type functionality.

There are some great windows tools that will do this i just need to remember what they are.

**Comment by daxgames** [comment]
@3cks82 I have used this in the past.http://www.joejoesoft.com/vcms/97/

It is a clipboard/macro manager
