### ISSUE TITLE
The issues template has issues.  

### ISSUE THREAD

**Issue by daxgames** [cmderdev/cmder#2176]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

* Cmder Version:
* ConEmu Version:
* Windows Version(e.g. Windows 10 Pro 1809):

### Description of the issue

It is not clear  where a user should enter the description.  It says:

\<\!\-\- Provide a clear, simple description of your issue here \-\-\>

and users do exactly that.  they edit the comment so the question never shows in the Github interface.  The same is true for other areas of the template.  I can fix it if someone gives me access to do so OR I have edited it here and hopefully make it clearer for future users.

**Comment by daxgames** [comment]
Whoever has access can get the fixed template by editing my above comment  and copying down to and including:

\<\!\-\- Provide a clear, simple description of your issue here \-\-\>

**Comment by Stanzilla** [comment]
I can already tell you that it's too long and nobody is going to read it :( tried longer templates with a few projects before and it never worked out

**Comment by daxgames** [comment]
Agree.  That is the CURRENT template.  I changed only 5 lines

**Comment by daxgames** [comment]
Did not know that is where it was.

**Comment by Stanzilla** [comment]
oh. lol.

**Comment by DRSDavidSoft** [comment]
Apparently the current issue template format is also considered legacy now.
If you do a re-write, you could use [the new format](https://help.github.com/en/articles/about-issue-and-pull-request-templates) and split it into separate files.
