### ISSUE TITLE
How to show different commend history in different tab

### ISSUE THREAD

**Issue by AkenoSyuRi** [cmderdev/cmder#2179]
After i execute a commend in A tab,
i can find it via UP/DOWN key in B tab.

How can i disable this feature?

**Comment by daxgames** [comment]
There is one command history.  The difference is when it is written.  The cmder default on the katest versions is to write command history after each issued command.

You can change this to write at session exit using the command `clink history_io 0`

**Comment by SamuelC54** [comment]
Yes we have the same problem, before we had an history per tab not the command history is share for all tabs. How can I change this behavior back

**Comment by phanirithvij** [comment]
https://github.com/cmderdev/cmder/issues/2480#issuecomment-792664473
