### ISSUE TITLE
alias register issue

### ISSUE THREAD

**Issue by szabizs** [cmderdev/cmder#2180]
### Purpose of the issue
- [X] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information
180626

Windows 10 Pro - 1809

### Description of the issue

`for /r %i in (*.log) do (break > %i)`

This command runs without problems in cmder, but when I try to add an alias to it, it gives me this error.
The command finds all *.log files in the folder and clears them with > break.
I've tried with quotes, without, with double % , without.... nothing seems to work for this alias.
```
λ alias clear_logs=for /r %%i in (*.log) do (break > %%i)
do was unexpected at this time.
```

**Comment by daxgames** [comment]
@szabizs At first glance Your alias syntax is incirrect.  Search for doskey in google and look at the microsoft docs

**Comment by szabizs** [comment]
> @szabizs At first glance Your alias syntax is incirrect. Search for doskey in google and look at the microsoft docs

It is correct, this script does run.

`for /r %i in (*.log) do (break > %i)`

**Comment by daxgames** [comment]
No its not.  It might be correct dos batch but it is not correct doskey because of the special characters like '>'.  Look at the doskey docs as Irecommended and  [cmder aliases wiki](https://github.com/cmderdev/cmder/wiki/Cmder-Aliases)

**Comment by daxgames** [comment]
Pay attention to the cmder aloas command lin syntax on escaping  '%' also.
