### ISSUE TITLE
Win7, Powershell no lambda prompt

### ISSUE THREAD

**Issue by Geobert** [cmderdev/cmder#2182]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information
Stable and Preview 180626

Windows 7

### Description of the issue
Using powershell, I don't get the prompt with lambda, I got the powershell default (with `PS`)

Tried a clean install to be sure.

**Comment by Geobert** [comment]
still relevant

**Comment by daxgames** [comment]
I don't have windows 7.  cant fix what I can't troubleshoot.

**Comment by daxgames** [comment]
PR's are welcome.
