### ISSUE TITLE
Vim rendering issue in tmux with WSL

### ISSUE THREAD

**Issue by DuckDuckWhale** [cmderdev/cmder#2183]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information
Cmder: mini, v1.3.12 from <https://cmder.net/>
ConEmu: 2018.6.26

### Description of the issue
Exactly the same as <https://github.com/Maximus5/ConEmu/issues/1786>.
It seems that the issue is fixed on the ConEmu side, but it is still reproducible in Cmder because the version of ConEmu it ships with is too old.
It seems that updating the vendored ConEmu would resolve it by following the guide on <https://github.com/cmderdev/cmder/issues/1073>.

**Comment by daxgames** [comment]
Looking at updating conemu in cmder.

**Comment by daxgames** [comment]
@DuckDuckWhale Try [this](https://ci.appveyor.com/project/MartiUK/cmder/builds/28742167/artifacts)

**Comment by DuckDuckWhale** [comment]
It works for me.
