### ISSUE TITLE
Is there a way to complete commands from history?

### ISSUE THREAD

**Issue by endolith** [cmderdev/cmder#2184]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Version Information

ConEmu 161206

Windows 7 Pro

### Description of the issue

For example, on Ubuntu with [fish shell](https://fishshell.com/), if I had previously entered

```
cd /some/long/folder/path/
make
cd /a/different/long/folder/path/
ls
```

and then I type `cd ` and then press Up, it will suggest the `cd /a/different/long/folder/path/` command.  If I press Up again, it will then suggest the `cd /some/long/folder/path/` command, going back through history and finding commands that match what I've already typed.  

[IPython](https://ipython.org/ )also has this kind of completion from history, matching parts I've already typed.

In Cmder, if I type `cd `, and press Up, it will suggest `ls`, and then `cd /a/different/long/folder/path/`, and then `make`, and then `cd /some/long/folder/path/`.  It ignores what I've already typed.  Is there a way to get fish's completion feature instead of just blindly going back through all of history?

(I use Cmder with the λ prompt, not Clink.)

**Comment by hasham7861** [comment]
Have you tried typing ctrl + r command which suggests the commands you have typed previously

**Comment by endolith** [comment]
That seems to just show the most recent history entry that matches what is typed?

**Comment by daxgames** [comment]
That is the correct answer at this time.  It may be possible with some lua code.

**Comment by hasham7861** [comment]
But endolith you do want to check the previous commands you typed with ls so it does answer question.

**Comment by daxgames** [comment]
@endolith after ctrl+r you can use page up/down to see all commands in history that match the partially typed command

**Comment by v1kku** [comment]
> 
> 
> @endolith after ctrl+r you can use page up/down to see all commands in history that match the partially typed command

Was this feature changed? That doesn't seem to be what's happening. Say you have the following command history

```cmd
cd repos
pip install --upgrade pip
choco install git
git clone https://github.com/cmderdev/cmder.git
cd cmder
```

If you `ctrl+r` then search `choco` and press up, the `reverse-i-search` will exit and `pip install ...` will be the command you get, if you press down it'll be `git clone ...`. Basically up/down exits the search and shows the prev/next command that was entered after the search result that was shown.

**Comment by daxgames** [comment]
@v1kku to search command history is <kbd>Ctrl</kbd>+<kbd>r</kbd>[<kbd>page up</kbd>|<kbd>page down</kbd>].  Don't use arrow keys.

**Comment by v1kku** [comment]
@daxgames aah of course, I misread that. Thanks

**Comment by greasedonkey** [comment]
To come back to the original question is there a way to have the way @endolith was asking?

I love cmder and having this would make it even better.

**Comment by endolith** [comment]
Now if I start typing, and then press PgUp or PgDn, it finds matching commands without me having to press Ctrl+R.

**Comment by Harsharma2308** [comment]
is there a way to get this via just pressing up arrow key?

**Comment by chrisant996** [comment]
> is there a way to get this via just pressing up arrow key?

Yes, as linked above.  [mridgers/clink#164 (comment)](https://github.com/mridgers/clink/issues/164#issuecomment-499876172)

**Comment by daxgames** [comment]
@chrisant996 tried that just for fun and it did not work.  Unless I messed it up somehow.

**Comment by endolith** [comment]
You saw that you can just use PgUp and PgDn right?

**Comment by daxgames** [comment]
@endolith Who, me?  Yes I already know about pgup/pgdown.  That is why I said 'just for fun'.

**Comment by chrisant996** [comment]
> @chrisant996 tried that just for fun and it did not work. Unless I messed it up somehow.

Sorry, I didn't read it closely enough. The linked comment said it was for up/down, but it was not actually.

This is the key bindings to use:
```
"\e[A":    history-search-backward
"\e[B":    history-search-forward
```

`"\e[A"` is up.
`"\e[B"` is down.
`history-search-backward` and `history-search-forward` are the history search commands that use what's been typed so far as a prefix.

Also, using `set history-point-at-end-of-anchored-search on` in the .inputrc file puts the cursor at the _end_ of the found history line when using the `history-search-forward` or `history-search-backward` (like history search in 4Dos/4NT/TCC does).

To find key binding sequences, use `clink echo` and also see [Key Bindings](https://chrisant996.github.io/clink/clink.html#key-bindings) in the Clink documentation.

To find commands, refer to [Bindable Readline Commands](https://tiswww.cwru.edu/php/chet/readline/readline.html#SEC13) in the Readline manual, and to [New Commands](https://chrisant996.github.io/clink/clink.html#new-commands) in the Clink documentation.

**Comment by raveren** [comment]
So to actually emulate the wonderful substring history completion from Fish shell I did these steps:

1. in my portable cmder directory `cmder\config` I added a new file called `.inputrc`:
```
"\e[A": history-substring-search-backward            # arrow up
"\e[B": history-substring-search-forward             # arrow down
```
2. in the same dir there was already a `clink_settings` file so I added this line to it:
```
set history-point-at-end-of-anchored-search on
```

**Comment by chrisant996** [comment]
> 2. in the same dir there was already a `clink_settings` file so I added this line to it:
> ```
> set history-point-at-end-of-anchored-search on
> ```

That will have no effect. That belongs in the `.inputrc` file.

**Comment by raveren** [comment]
it was for sure working and now it doesn't work in neither of the config files..

**Comment by chrisant996** [comment]
> it was for sure working and now it doesn't work in neither of the config files..

It is impossible for putting it in `clink_settings` to take effect.  If it was working at some point, then it was because of something else.
