### ISSUE TITLE
Latest release triggering anti-virus

### ISSUE THREAD

**Issue by d-cs** [cmderdev/cmder#2186]
### Purpose of the issue
- [X] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information
v1.3.12 - ZIP Artefact

### Description of the issue
Downloading the zipped release triggers antivirus warnings. 

Vendor scan: https://www.virustotal.com/gui/file/5b03f694ce24d125591252787ccb67b3efa850db6a9321a48aa44bae4e8911ad/detection

**Comment by MartiUK** [comment]
Report the false positive to your AV provider, thanks.

**Comment by lumagm** [comment]
download zip file Latest Version: v1.3.12 - **no problem**
unzipped and put the folder in program files - **no problem**
scanned with avg zipped and unzipped folder - **no problem**

**Description of the issue**

but when i run the executable files I get an unpleasant warning that there is something named **IDP.ALEXA.51**

bellow a snapshot photo of the warning:
![cmder avg warning](https://user-images.githubusercontent.com/7574835/68422144-48754580-01a8-11ea-8625-662bb1eda815.PNG)
