### ISSUE TITLE
using Cmder instead of Putty

### ISSUE THREAD

**Issue by mpuri14** [cmderdev/cmder#2190]
I'm currently using Putty to logon to a linux server with a .ppk file for credentials. I'm trying to do this within the cmder window but have not had success. What are the steps to do this?

**Comment by daxgames** [comment]
You found my other post.  You need to generate an ssh key and use it instead.  Google is your friend. :-)

**Comment by daxgames** [comment]
https://www.ssh.com/ssh/keygen/
