### ISSUE TITLE
Modifying ConEmu config in Cmder requires help of a Zen Master

### ISSUE THREAD

**Issue by fira** [cmderdev/cmder#2195]
Version: Cmder 1.3.12.915, shipped with ConEmu 180626
Platform: Win 10 x64, Winver 1903 (May 2019 Update)
Install Method: Chocolatey

... to stay calm enough to figure out that **config**/user-ConEmu.xml is _actually pretty much some useless internal backup_, despite:
 * The folder being named config suggesting Cmder settings
 * README in that folder specifically saying they are configuration file, although ConEmu.xml is "_overwritten on update_"
 * Any common sense suggesting that Cmder manages ConEmu configuration

... but rather that **vendor**/conemu-maximus5/ConEmu.xml is where you're supposed to edit it at, despite:
 * Top folder being named vendor suggesting internal dependencies
 * The fact that this file is usually stored in ConEmu @ %APPDATA% so you can't know it exists at all unless ending up looking at obscure GitHub issues (thanks #1930) or the source
 * Any common sense suggesting that Cmder manages ConEmu configuration

Also the official README says quite literally (though i found out after-the-fact) 
```
Editing files under [cmder_root]/vendor is not recommended since you will need to re-apply these changes after any upgrade. All user customizations should go in [cmder_root]/config folder.
```

So in effect, if you for some reason think that you can modify config/user-ConEmu.xml, you're dead wrong, Cmder will simply overwrite it with the old file from vendor/conemu-maximus5 instead, [as evidenced down from CmderLauncher.cpp:212](https://github.com/cmderdev/cmder/blob/e4651/launcher/src/CmderLauncher.cpp#L212).

After two hours of pure madness trying to figure this out to change a single setting, I've been trying to figure out what the above snippet was _actually_ trying to accomplish. I spent a few more hours breaking down the process to understand, and frankly it's not helping that much.

In that source part there are basically 9 file operation cases. Quick summary, in order.

 * Init/Overwrite machine-specific configs with vendor file, when no /C, vendor file exists, and using /M or there is a machine-specific file (the one overwritten..)
 * Init missing vendor file with (potentially also missing) machine-specific file, when no /C, and using either /M or there is a machine-specific file
 * Init missing machine config from vendor, when using /M, /C, vendor config exists but not machine's
 * Overwrite user config with vendor config if both exist and not using /C
 * Init vendor config with user config if it's missing and not using /C
 * Init user config with vendor config + overwrite vendor config with defaults, if vendor config exists and not using /C
 * Init vendor config from defaults if missing and not using /C
 * Init user config from vendor config if existing
 * Init user config from default config with custom root when using /C

Why so much nonsense ? 
I'm not sure what more I can say about this issue - I was going to propose a patch but hour after hour on this I'm starting to realize I can't actually figure out what it's supposed to be doing at all in the first place.
Is the Vendor config considered a static file distributed by ConEmu ? If so, why is it written to so much ? Why so much logic to separate usage of custom user roots ? Ugh...

**Comment by daxgames** [comment]
@fira Sorry you are having difficulty in inderstanding how Cmder manages and uses the Conemu config file.  I will try to explain.

## History

Cmder used to directly use the conemu.xml in the config folder directly but the Conemu dev recommended  we leave the `comemu.xml` in the conemu folder so the settings conemu uses are in `vendor/conemu-maximus5/ConEmu.xml`.

## The Problem

The problem with this is that the file could be overwritten on upgrade of `Cmder`.  If that happens users lose all config that is done in the Conemu GUI.

## How cmder.exe manages the conemu config.

1. On initial run Cmder.exe places the Cmder default conemu.xml in `vendor/conemu-maximus5/ConEmu.xml` when  none exists.
2. Each launch of `cmder.exe` looks for `vendor/conemu-maximus5/ConEmu.xml` 
 * If it exists it is copied to `config\user-conemu.xml` so changes made via the Conemu GUI  can be reapplied after upgrading.
  * If it does not exist `config\user-conemu.xml` is copied to `vendor/conemu-maximus5/ConEmu.xml`

The recommended upgrade process is to delete the vendor folder and copy a new one in.  When this happens the next time cmder.exe runs it checks for `config/user-conemu.xml` and if it exists it copies `config/user-conemu.xml` file to `vendor/conemu-maximus5/ConEmu.xml` so all previous user config is re-applied to the upgraded install.

Modifying the conemu config in cmder is done by changing any setting in the comemu gui.  Its pretty simple actually but if you must edit the file then edit `vendor/conemu-maximus5/ConEmu.xml`. 

The vendor folder is subject to overwrite at any time but it does contain actively used and edited config files as stated above.  It is not recommended to edit anything in vendor folder other that the `vendor/conemu-maximus5/ConEmu.xml` sine it is the ONLY file the default Cmder install edits and protects against overwrite on upgrade.

Custom user roots were requested by users that wanted to use a single copy of cmder and have a way to separate individual user config so multiple users on a single system(windows terminal server/citrix) could have a shared config with additional user config.


Its pretty simple really.  If you have any other questions please let us know.

**Comment by fira** [comment]
Well I suppose if ConEmu.xml really absolutely has to be in vendor (except when using custom user roots where it works outside anyway), has to be backed up in a "config" folder (whose Readme says it's modifiable), and has to be blindly demolished during update (which then defer damage control to startup logic instead), then it's all fine and does make sense yeah...

Ugh.... Is it possible to at least add a note in config/Readme.md ?
Thanks...

**Comment by daxgames** [comment]
@fira what readme says its modifiable?  If it says that, its a mistake.

If you think a readme edit is necessary pull requests are welcome.
