### ISSUE TITLE
Cmder context menu selection causes windows path error - path and env are set correctly.

### ISSUE THREAD

**Issue by nichalko** [cmderdev/cmder#2196]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

Version 1.3.12.915 - Cmder

Windows 10 Version 10.0.18362 Build 18362

### Description of the issue

Having clean Windows 10 install, I decided to install Cmder, so I extracted it to c: drive path following the wiki.

I added env variables and path values.

Checked with where command - all look good.

After adding registry keys, context menu is not working. The icon is not showing anyway, so my guess is, there must be something wrong with the path ? 

Error says:
[Window Title]
Explorer.EXE

[Content]
Windows cannot access the specified device, path or file. You may not have the appropriate permissions to access the item.

[OK]

I cannot track it down... please help.

![windows_error](https://user-images.githubusercontent.com/22373203/67625951-e0843e00-f83c-11e9-8e14-079841996743.PNG)
![context_menu](https://user-images.githubusercontent.com/22373203/67625952-e0843e00-f83c-11e9-8fea-cc554efbf860.PNG)
![env_variables](https://user-images.githubusercontent.com/22373203/67625953-e0843e00-f83c-11e9-9f97-73fb6c84e068.PNG)
![path_check](https://user-images.githubusercontent.com/22373203/67625954-e11cd480-f83c-11e9-8f4e-a5accf4acf0b.PNG)
![registry_entry](https://user-images.githubusercontent.com/22373203/67625955-e11cd480-f83c-11e9-98b1-bb147bbe4ce9.PNG)

**Comment by daxgames** [comment]
Context menu works for me.  How did you add it?

```
cmder /register user
```

**Comment by nichalko** [comment]
> Context menu works for me. How did you add it?
> 
> ```
> cmder /register user
> ```

That command fixed it. Thanks.

Wish it was in the wiki though ?

**Comment by daxgames** [comment]
Its not in the wiki because its in the main readme.md
