### ISSUE TITLE
Option to disable git support

### ISSUE THREAD

**Issue by santagada** [cmderdev/cmder#2197]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [ ] Question

### Description of the issue
I have some big repositories (LLVM is one of them) that make cmd take a long time to print the prompt because git status is slow. Would be cool if there were a way to disable it.

**Comment by daxgames** [comment]
@santagada disable it globally per shell session or per git repo?

**Comment by daxgames** [comment]
@santagada cmd, powershell or bash?

**Comment by daxgames** [comment]
I have written this but it is not committwd publicly yet.  What I have done so far is to modify `vendor\clink.lua`  to look for a setting in the `.git\config` file of a repo and disable git status if the setting is set to `false`.  

The setting is added to the file by editing the file and looks like:

```
[cmder]
    status = false
```
