### ISSUE TITLE
Custom shading/text colors based on connection status

### ISSUE THREAD

**Issue by DuCFb1xU1CYEICVIaQHt** [cmderdev/cmder#2198]
Whenever I run Connect-VIServer I want the text and shading to automatically adjust based on what user credentials were entered. If I'm connected as an admin I want it to be distinct. Below is some basic code that I wrote for this, but powershell doesn't have an easy way to refresh the UI automatically based on events or different connection scenarios. I'm hoping that this software provides that functionality.

Function nCreate-CVCAlias {

    Param(
    	[Parameter(Mandatory=$false, Position = 0)][string]$targetVC,
		[Parameter(Mandatory=$false, Position = 1)][switch]$alllinked
    )

	If($targetVC) {
		
		If($PSBoundParameters.ContainsKey('alllinked')) {
		
			Connect-VIServer $targetVC -AllLinked
		
		}
		Else {
			
			Connect-VIServer $targetVC
		
		}
	
		
		
		ForEach($user in $Global:defaultviservers.User) {
			
			If($user -like "*domainadminuser") {
			
				$Host.UI.RawUI.WindowTitle = 'Running as domainadminuser'
				
				$host.UI.RawUI.BackgroundColor = "DarkRed"; $Host.UI.RawUI.ForegroundColor = "White"
				
			}
			
		}
		
	}
	ElseIf($Global:CVCAliasInit -ne 1) {
		
		$Global:CVCAliasInit = 1
		
		Set-Alias -Name "cvc" nCreate-CVCAlias
		
	}
	Else {
	
		# The initial function load completed and looped back. Do nothing
	
	}
	
} # End "nCreate-CVCAlias"

**Comment by daxgames** [comment]
@DuCFb1xU1CYEICVIaQHt You might be able to do this by adding your required code the the `PostPrompt` script block in `$env:cmder_root\config\user_profile.ps1`

```
[ScriptBlock]$PostPrompt = {

}
```

This will cause the code to execute each time the prompt is written to screen.
