### ISSUE TITLE
PS session warning missing Git support although exists

### ISSUE THREAD

**Issue by blindzero** [cmderdev/cmder#2205]
### Purpose of the issue
- [X] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information
cmder v1.3.12 (mini)
Windows 10 ProN 1903
git version 2.18.0.windows.1 manually installed

### Description of the issue
When starting a new cmd session Git Support works fine, GIT_INSTALL_ROOT is found and set correctly, directory status is working fine.
When starting a PS session Git Support is not detected, although git command is in $env:PATH.
Each line prints warning about missing Git support and reminds to setup posh-git (which shouldn't be necessary as git is available. As far as I understand the issue is in Import-Git function, invoked by checkGit. Import-Git only checks for Posh-Git module and not for git cmd availability (as it is done for Configure-Git which is only invoked if Get-Command git fails.

**Comment by daxgames** [comment]
Cmde powershell git integration depends on posh-git.  Install it.
