### ISSUE TITLE
As admin task only works for first session not in new tabs

### ISSUE THREAD

**Issue by blindzero** [cmderdev/cmder#2206]
### Purpose of the issue
- [X] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information
cmder v1.3.12 (mini)
Windows 10 ProN 1903

### Description of the issue
The "...as Admin" tasks are not working when a new tab session is started.
The "*" task prefix is only working for the first default session opened. So e.g. if I configure "Powershell as Admin" as default task this tab is started as Admin.
Further tabs opened with "Powershell as Admin" are not started as admin if I don't manually check "Run as administrator".

**Comment by daxgames** [comment]
@blindzero  I can't reproduce this.  I can open as many tabs as admin as I want.

**Comment by andyc56-mso** [comment]
I am seeing this problem as well.

OS: Win10 x64 (both 1809 and 1903)
cmder: Both 1.3.12 and also after upgrade to 1.3.13 (both mini).
Other: Standalone git from git SCM (not from cmder) with PATH set to allow execution of Git for Windows' unix utilities.

When choosing "{cmd::Cmder as Admin}", a new tab and session are created just fine, but there is no UAC system dialog asking me to allow the app to make changes, and the resulting session doesn't have Admin privileges, as can be verified by typing e.g.
powercfg -waketimers
As per the original poster, checking the "Run as administrator" checkbox in the "Create new console" dialog works as expected.
