### ISSUE TITLE
cmder Mini - Don't Echo Path

### ISSUE THREAD

**Issue by DuCFb1xU1CYEICVIaQHt** [cmderdev/cmder#2208]
![image](https://user-images.githubusercontent.com/57237284/69178790-e681dd80-0acf-11ea-8157-07d54ce982c8.png)
How do you remove the echo every time you press enter within cmder?

**Comment by daxgames** [comment]
I don't understand the question.  You sent a screenshot of the cmder prompt hitting enter several times.

**Comment by DuCFb1xU1CYEICVIaQHt** [comment]
How do I remove the "C:\MyData\Software\cmder_mini" echo every time I press enter?

**Comment by daxgames** [comment]
That IS the prompt for Cmder telling you tour current working directory.  The prompt is customizable using the lua language that us used by Clink to write the prompt.

You would need to write a custom `%cmder_root%\config\prompt.lua` to change the way the prompt is written.

**Comment by daxgames** [comment]
You have everything on one line:

```
function my_prompt_filter()
    cwd = clink.get_cwd()
    prompt = "\x1b[1;32;40m{cwd}{git}{hg}{svn}\x1b[1;30;40m{lamb} \x1b[0m"
    new_value = string.gsub(prompt, "{cwd}", cwd)
    clink.prompt.value = string.gsub(new_value, "{lamb}", "λ")
end

clink.prompt.register_filter(my_prompt_filter, 1)
```

![image](https://user-images.githubusercontent.com/7318053/69191227-193bce00-0af0-11ea-8e01-a73215325487.png)

Or remove the path entirely:

```
function my_prompt_filter()
    cwd = clink.get_cwd()
    prompt = "\x1b[1;32;40m{git}{hg}{svn}\x1b[1;30;40m{lamb} \x1b[0m"
    clink.prompt.value = string.gsub(prompt, "{lamb}", "λ")
end

clink.prompt.register_filter(my_prompt_filter, 1)
```

![image](https://user-images.githubusercontent.com/7318053/69191273-2ce73480-0af0-11ea-9fbc-ce3efe742257.png)
