### ISSUE TITLE
Open Cmder here in context menu not working with WSL and other drives then C:\

### ISSUE THREAD

**Issue by kwint** [cmderdev/cmder#2209]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Version Information
Cmder: 1.3.12.915
ConEmu: 180626
Win 10 Pro

### Description of the issue
I use the right click context menu in explorer a lot to open cmder in a specific folder, this works like a charm, except for when I do this in other drives than the C:\ drive.  When I click "Cmder here" while in another drive it goes to my home folder. This is only happening in WSL, in cmd this works like intended. When I open a folder in the C drive (with WSL) it does go to the right folder (ie `/mnt/c/path`). Using cd to go the right folder on another drive works (ie `cd /mnt/q/path`)

How do I get this to work?

**Comment by daxgames** [comment]
If you are using 'WSL' you are not using Cmder.  You are using 'WSL' in 'Conemu'.  You should ask the Conemu developer if you have questions about this.
