### ISSUE TITLE
fast_init breaks debug_output and verbose_output

### ISSUE THREAD

**Issue by tednich** [cmderdev/cmder#2210]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

cmder version 1.3.11.843
ConEmu build: 180626 x64
WIndows 10 Pro 10.0.17134.x64

### Description of the issue

fast_init configuration causes problems with verbose and debug

### Steps to reproduce

1. set fast_init=1 in init.bat
2. start cmder.exe
3. 

### Actual results
Many messages like this:
'debug_output' is not recognized as an internal or external command,
operable program or batch file.
'verbose_output' is not recognized as an internal or external command,
operable program or batch file.

### Additional files

My workaround to the problem: edit lib_console.cmd and 
remove line 3 "if "%fast_init%" == "1" exit /b"

Problem seems to be fast_init in lib_console doesn't allow %lib_console% to be set properly.

**Comment by daxgames** [comment]
This is working as designed.  One of the main purposes is to disable debug and verbose output so things are faster by skipping all the logic involved with those two functions.
