### ISSUE TITLE
ConEmu can't run because blocking or access denied errors maybe.

### ISSUE THREAD

**Issue by goldWave** [cmderdev/cmder#2211]
### ConEmu can't run succeed because blocking or access denied errors maybe.

win 64 professional.

![image](https://user-images.githubusercontent.com/15025129/69301922-cb8ba680-0c52-11ea-9203-a060b17a87b7.png)

**Comment by daxgames** [comment]
Click unlock and continue.

**Comment by xinshoushangdao** [comment]
第一次进入有可以理解，但每次打开都有这样提示就不应该了

**Comment by daxgames** [comment]
@xinshoushangdao Translation: 'It’s understandable the first time you enter, but every time you open it, there should be such a prompt. It shouldn’t be.'

You should get this prompt once if you click 'Unblock and Continue'.  If you click anything else you will ger this every time.

If you are still getting it after clicking 'Unblock and Continue' you need to report it to the Conemu developer.
