### ISSUE TITLE
Fresh install of Cmder Mini 1.3.13 `git` error

### ISSUE THREAD

**Issue by ryanpcmcquen** [cmderdev/cmder#2213]
```'git' is not recognized as an internal or external command, operable program or batch file.```

I am running `vcvarsall.bat x86_amd64` inside of `user-startup.cmd`, but otherwise everything is vanilla.

**Comment by daxgames** [comment]
Building new 1.3.13 release packages now.

**Comment by daxgames** [comment]
New packages available.  Please confirm issue is resolved.

**Comment by ryanpcmcquen** [comment]
@daxgames, thank you! Will it auto update?

**Comment by daxgames** [comment]
@ryanpcmcquen no it wont and i may have to do another build to fix powershell sessions for the same issue.

**Comment by ryanpcmcquen** [comment]
@daxgames, that fixed it, but an auto update would be nice since this is a stable release.

**Comment by daxgames** [comment]
Thanks.  There us no auto update and there will be no auto update.  Update process is described in the `README.md` file.

**Comment by ryanpcmcquen** [comment]
@daxgames, what does this do?
![Annotation 2019-11-23 202022](https://user-images.githubusercontent.com/772937/69489558-c71be500-0e2e-11ea-85c2-a87c7971a96a.jpg)

**Comment by daxgames** [comment]
Cmder is configuration plus a combination of several different open source products:

- conemu
- clink
- clink-completions
- git-for-windows

The screenshot is the check for updates screen for the conemu component of Cmder.

**Comment by ryanpcmcquen** [comment]
Ah, thank you @daxgames! I appreciate the quick turnaround on the fix too. 🍻
