### ISSUE TITLE
`/nix_tools 0` should prevent adding !GIT_INSTALL_ROOT!\mingw64\bin to PATH

### ISSUE THREAD

**Issue by mloskot** [cmderdev/cmder#2214]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

- Cmder 1.3.12
- ConEmu 191012 preview
- Windows 10 Pro 1903 (18362.476)

### Description of the issue

The PR #1975 added `/nix_tools` option to control order or prevent adding `!GIT_INSTALL_ROOT!\usr\bin` to `PATH` and this works.

The `/nix_tools 0` should also prevent adding `!GIT_INSTALL_ROOT!\mingw64\bin` to `PATH`.

The current handling of `/nix_tools 0` seems incomplete and overlooking the `ming64` directory.

**Comment by daxgames** [comment]
Is this what setting 'use from git bash only' does when installing git for windows?

**Comment by mloskot** [comment]
bump

**Comment by daxgames** [comment]
@mloskot this is already done in Cmder 1.3.14

**Comment by mloskot** [comment]
@daxgames Sorry, I assumed merged fix commit will include `Fixes #2214` to automatically close the issue. So, I missed the fix. Thanks.
