### ISSUE TITLE
Pass escaped string to cmder

### ISSUE THREAD

**Issue by AndiLeni** [cmderdev/cmder#2215]
### Purpose of the issue
- [x] Question

### Version Information
newest
Win 10 home 1909

Hello,

I have a question about a task I currently face.
I have created a shell menu entry to open text files with the nano editor inside cmder.
The batch file which is called contains the following code:

````
echo %1
PAUSE
cmder /x "/cmd nano %1"
````

where ``$1`` is the complete path of the file on my system. 
Unfortunately my home folder contains a whitesapce, which means the path must be put in quotes.
But cmder cant handle this currently, or I dont know how to do it correctly.

The output in the cmd is 
````
C:\Users\Andreas L\Desktop>echo "C:\Users\Andreas L\Desktop\Zu erledigen.md"
"C:\Users\Andreas L\Desktop\Zu erledigen.md"

C:\Users\Andreas L\Desktop>PAUSE
Drücken Sie eine beliebige Taste . . .

C:\Users\Andreas L\Desktop>cmder /x "/cmd nano "C:\Users\Andreas L\Desktop\Zu erledigen.md""
````

How can I pass the path without problems?

Kind regards
Andreas

**Comment by daxgames** [comment]
Look at the `--` arg in [this](https://github.com/cmderdev/cmder/pull/2174)

**Comment by daxgames** [comment]
> Look at the `--` arg in [this](https://github.com/cmderdev/cmder/pull/2174) instead of using `/x` which will not work with paths with spaces.

**Comment by AndiLeni** [comment]
Thanks for pointing this out!

I managed to achieve what I wanted using this code:
````
cmder -- -cmd -new_console:"nano" %1
````
