### ISSUE TITLE
Cmder extremely slow on Shared Disk Volume (Windows 10) 

### ISSUE THREAD

**Issue by ForrestSu** [cmderdev/cmder#2216]
cmder version: 1.3.13
OS version: Windows 10 Enterprise Edition 1903 

I divided two disk volumes (D disk volume and E disk volume) on one SSD, and the entire `D disk volume` was opened for disk sharing by docker.
I put Cmder on the `D disk volume` and executed Unix commands very slowly; however, when I copied the entire folder of cmder to the `E disk volume`, cmder executed any command very quickly.

**Comment by daxgames** [comment]
Cmder does not care which drive letter it runs from.
