### ISSUE TITLE
Can't restore the layout of split tabs after reopen Cmder

### ISSUE THREAD

**Issue by pansila** [cmderdev/cmder#2217]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information
Cmder: 1.3.13.967
ConEmu: IDK, it comes with cmder
Windows 7 64bit

### Description of the issue
1. After a new fresh installation (extraction) of cmder 1.3.13.967, I enabled "Auto save/restore opened tabs" in the settings/startup, then I split the tabs and made a 2x2 layout, then I closed and opened Cmder, the layout changed to 3x1 + 1 layout, please see the attached pictures for actual layouts. It seems that the auto save/restore feature doesn't work properly.

![image](https://user-images.githubusercontent.com/5125601/69612349-785a8f00-106a-11ea-9049-df87cefe0577.png)
=>
![image](https://user-images.githubusercontent.com/5125601/69612310-67118280-106a-11ea-94f8-b8e86ad0a3fc.png)

**Comment by daxgames** [comment]
Cmder is configuration plus a combination of several different open source products:

- conemu
- clink
- clink-completions
- git-for-windows

Conemu is responsible for the feature you are trying to use.  You should teport the issue to the Conemu developer.
