### ISSUE TITLE
get previous command with array up key

### ISSUE THREAD

**Issue by Reshad-Hasan** [cmderdev/cmder#2219]
I can't find any option in the settings for getting previous executed commands with the arrow up key.
Is it not supported yet?

**Comment by daxgames** [comment]
Ctrl+r then use page up/down

**Comment by daxgames** [comment]
Correction previous executed commands should just work with up/down error.  To fikter them based on something typed use my precuous.

**Comment by daxgames** [comment]
@Reshad-Hasan did my answers help you? Can I close this?
