### ISSUE TITLE
CJK problem

### ISSUE THREAD

**Issue by noisia04** [cmderdev/cmder#222]
Hello. I am korean and when I use cmder, it has a problem. CJK characters are too close to each other.
(Windows 7 64bit korean version, cmder 1.1.3)

Look at this. [오후], [파일], [디렉터리], [바이트], [남음] are overlapped.
![cjk problem](http://i.imgur.com/c4iR6Lw.png)

**Comment by Jackbennett** [comment]
commit [997bd5c24...](https://github.com/cmderdev/cmder/commit/997bd5c24ef79394c0451ff0165f43149910aaa8) has pulled in `ls=ls --show-control-chars -F --color $*` so I'm closing this fixed.
