### ISSUE TITLE
Error running CMD

### ISSUE THREAD

**Issue by Tukali** [cmderdev/cmder#2221]
when i first use it ,cmd and cmd as admin have a error :

'"D:\software\cmder\vendor\conemu-maximus5\..\init.bat"'  is not recognized as an internal or external command,
operable program or batch file.
Or batch files.

Only these two reported this error，what should i do 

and there's one more small problem,I want to change that sign to $,how do i do that

**Comment by Tukali** [comment]
ok，i know ,360 safe delete my init.bat ,think of it as a virus

**Comment by daxgames** [comment]
Report it as a false positive and create an exception in your anti-virus
