### ISSUE TITLE
Adds new line on each char when using fish

### ISSUE THREAD

**Issue by lordlycastle** [cmderdev/cmder#2224]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Version Information

Cmder: Version 1.3.13.967

### Description of the issue

A new line is added when you type for each character when using fish. I believe this has something to do with the auto-complete in fish. I'm running this in a remove linux VM and ssh-ing in to access this terminal with fish.

![See this.](https://i.imgur.com/0MW4lSS.gif)

Is there a way to fix this?

**Comment by daxgames** [comment]
Hey there,

I doubt this id a Cmder issue or anything we could fix.

Cmder uses ConEmu as terminal emulator, if you are experiencing a problem or have a question, please open an issue over at https://github.com/Maximus5/ConEmu

Thank you! :-)

**Comment by lordlycastle** [comment]
Are you sure it's not just a setting? Where the auto-complete feature is using new line and the terminal rather than use the same line, goes to new one. E.g. when you have progress bars that are meant to print/update on the same line.

**Comment by daxgames** [comment]
I don't know.  Even if it is a setting its a conemu setting so my original response still applies.
