### ISSUE TITLE
`attempt to call a nil value` after every command

### ISSUE THREAD

**Issue by VeryTastyTomato** [cmderdev/cmder#2225]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

Cmder: 1.3.13.967
ConEmu: 191012

Windows 10 Family 1909 (18363.476)

### Description of the issue

I downloaded the mini package of Cmder. When I launch the application, in the console I get the following error message:
`cannot open D:\├ëfrit\T├®l├®chargements\cmder_mini\vendor\clink\clink.lua: No such file or directory`
`attempt to call a nil value`
The real path mentioned in the error message is `D:\Éfrit\Téléchargements\cmder_mini\vendor\clink\clink.lua`.
Afterwards, everytime I launch a command, the output result has a new line and the message `attempt to call a nil value` added after the genuine part.

I guess it is related to a Lua application (Clink?) but I am not sure. It seems to not support non-ASCII characters in paths, which would be unfortunate if that’s actually the cause of this error.

**Comment by daxgames** [comment]
You are correct.  Probably clink and clink is pretty much unsupported right now.  You could open an issue at https://github.com/mridgers/clink
