### ISSUE TITLE
git ssh may have some cache, which use deleted rsa key to connect github.

### ISSUE THREAD

**Issue by goldWave** [cmderdev/cmder#2226]
### Version Information
win:10
ConEmu: 180626[64] preview

### Detail Information

`Cmder` can't pull or push to github but use `Git Bash` can even restart computer.

when I delete all files in `.ssh` folder, and delete the public key in github setting, the `Cmder` also can connect to github use this commd `ssh -T git@github.com` , but can't `clone or push or pull`.
Why the `Cmder` can connect the git use `ssh -T git@github.com`, even I deleted all ssh files.

The blew image is the I add new rsa files, the `Cmder` can't pull or push , but `Git Bash` can, I used this commd before, such as `ssh-agent bash` and `ssh-add C:\Users\jimbo\.ssh\id_rsa_naver`

![image](https://user-images.githubusercontent.com/15025129/70596799-bb4b6380-1c21-11ea-9e50-14470a7fd53b.png)
![image](https://user-images.githubusercontent.com/15025129/70788849-cabae000-1dcc-11ea-9f1a-0e670ba5d4ee.png)

Thanks.

**Comment by goldWave** [comment]
not anyone can help me?

**Comment by daxgames** [comment]
Bump
