### ISSUE TITLE
chinese input can not show compete.

### ISSUE THREAD

**Issue by endingman** [cmderdev/cmder#2227]
vagrant ssh to homestead，in homestead
when I input chinese like this: '测试测试'
it only show '测'.
![62025871-ee113400-b20b-11e9-8cce-eb25fed414d9](https://user-images.githubusercontent.com/16915802/70602147-b3de8700-1c2e-11ea-8104-eceb79eeb3aa.png)

**Comment by linqh1** [comment]
try set `set LANG=zh_CN.UTF-8` at "Settings-Startup-Environment"
![image](https://user-images.githubusercontent.com/42435177/71387676-e4132600-262f-11ea-97c5-fe1d6b1ae21b.png)

**Comment by endingman** [comment]
It does not work! 
It happen when input chinese in  single quotes:''.
![image](https://user-images.githubusercontent.com/16915802/71388224-6866a880-2632-11ea-8d49-2c3d21568387.png)
@linqh1

**Comment by linqh1** [comment]
What version and input method are you using?

My version is 191012 and I am using Sogou to type Chinese characters, it works fine. 

I'm not sure if it's caused by version/input method, maybe be you could try another input method to see what happen.

**Comment by endingman** [comment]
![image](https://user-images.githubusercontent.com/16915802/71388882-2d19a900-2635-11ea-889f-92adf6974519.png)

I will try other  input method.
@linqh1

**Comment by endingman** [comment]
I try another input method by system. It also has the same problem.
@linqh1
