### ISSUE TITLE
Cannot daisy chain alias 

### ISSUE THREAD

**Issue by christopherpickering** [cmderdev/cmder#2228]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

Version 1.3.13.967, Windows 10 Pro 10.0.18362.356

### Description of the issue

Hi, I am unable to run daisy chained alias with or without variables. I can run ordinary commands daisy chained.

**Alias example**
gs=git status
myecho=echo $1
gco=git checkout $1

**Running Commands**
```sh
git status && git status
```
this will output 2 results

```sh
gs && gs
```
this will only run first command.

```sh
echo 1 && echo 2
```
this will output
1
2

```sh
myecho 1 && myecho 2
```
this will output
1

```sh
git checkout branch1 && git checkout branch2
```
will checkout branch1 and then checkout branch2

```sh
gco branch1 && gco branch2
```
this will only checkout branch one and ignore the second command.

![image](https://user-images.githubusercontent.com/17788706/70618123-63593080-1c12-11ea-907e-c70c6a7eec7b.png)

Am I missing something simple, or is there a way to make this work?
Thanks!
Christopher

**Comment by daxgames** [comment]
Cmd::Cmder sessions alias functionality is provided by Microsoft Doskey.  This is a limitation of Doskey and not a Cmder issue.

**Comment by daxgames** [comment]
If you want to be able to do this is bash::bash sessions.

**Comment by christopherpickering** [comment]
Thanks for the reply!
