### ISSUE TITLE
Timing Problem with oh-my-posh theming (Powershell Core)

### ISSUE THREAD

**Issue by Ergamon** [cmderdev/cmder#2230]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Version Information

Cmder v1.3.13 (unmodified ConEmu, using the one from the zip file)

Windows 10 Enterprise 1909

### Description of the issue

I am mainly using Cmder with Powershell Core (pwsh) and there seems to be a timing problem when setting it up with oh-my-posh 

What I am trying to do is activating the oh-my-posh theme in my user_profile.ps1

So what I added is this:

## <Continue to add your own>

$DefaultUser = "XXX"
Import-Module posh-git
Import-Module oh-my-posh
# Set-Theme Paradox

As you can see the command to set the theme is currently commented out, cause there is the issue.

If I wait until everything is up and running and type this command manually everything works as expected.

If I try to make the command in the user profile the coloring gets messed up.

Of course it is a little annyoing to do the last step everytime manually. It would be nice if someone could fix this or anyone has a hint how to execute the command at a later moment.

Thx for any help

PS:
In the screenshots you can see a) when I type the command manually everything looks correct and b) when the command is executed during the profile the output is messed up

![Set-Theme-Manually](https://user-images.githubusercontent.com/48294299/70861586-57ca7a00-1f30-11ea-859b-5f1be2e37cd0.jpg)
![Set-Theme-ByUserProfile](https://user-images.githubusercontent.com/48294299/70861593-5e58f180-1f30-11ea-8c59-54e4cb4f3bfc.jpg)

**Comment by Ergamon** [comment]
Is there noone who can reproduce this or has any clue how to fix it?

**Comment by JanDeDobbeleer** [comment]
Folluw-up in https://github.com/JanDeDobbeleer/oh-my-posh/issues/201 for those interested.

**Comment by daxgames** [comment]
@Ergamon I just ran youe exact replication steps and do not see the issue.:

![image](https://user-images.githubusercontent.com/7318053/74597397-dfb22a80-502c-11ea-990f-8fd009f47913.png)

**Comment by daxgames** [comment]
@Ergamon I am running newer Cmder though.

**Comment by daxgames** [comment]
@Ergamon we will close this issue if you don't respond.  Is this still an issue?
