### ISSUE TITLE
Add extra actions after $* in alias

### ISSUE THREAD

**Issue by reypm** [cmderdev/cmder#2231]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Version Information
 - ConEmu 191012 x64 [Preview]
 - Cmder 1.3.11.843

### Description of the issue

Is it possible to add extra actions after `$*` in alias? I have the following alias:

```bash
some_alias=pushd c:\somedir\docker && docker-compose exec container vendor/bin/codecept $*
```

and I would like to go back to the original directory where the alias was executed after perform the operations, IE

```bash
some_alias=pushd c:\somedir\docker && docker-compose exec container vendor/bin/codecept $* && popd
```

But `popd` is not recognized in the command and I never go back to the previous directory. In order to understand this here is an example:

```
λ pwd
c:\somedir\someproject
λ some_alias # this will change the dir to c:\somedir\docker
λ pwd
c:\somedir\docker
```

By using `popd` at the end I should have:
```
λ pwd
c:\somedir\someproject
λ some_alias # this will change the dir to c:\somedir\docker
λ pwd
c:\somedir\someproject
```

is this possible somehow?

**Comment by daxgames** [comment]
@reypm Not sure about your exact use case but you could look at [Complex Alias Examples](https://github.com/cmderdev/cmder/wiki/Cmder-Aliases#complex-alias-examples)

**Comment by daxgames** [comment]
@reypm Also I am surprised your alias works at all.  Are you using a `cmd::cmder` session or `bash::bash`

**Comment by reypm** [comment]
@daxgames I am using `cmd::cmder` session and as  for the exact use case is just I want to execute a different thing that goes after `$*` definition and separated by `&&`

**Comment by daxgames** [comment]
I understand your use case the problem is that `&&` is not valid in an `cmd::cmder` alias.  It should instead be `$t$t`

**Comment by reypm** [comment]
@daxgames  thank you, it worked. Closing this as "fixed".
