### ISSUE TITLE
cmder flickers madly while using ssh

### ISSUE THREAD

**Issue by libphy** [cmderdev/cmder#2232]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue

It happens often that while using a ssh session, the cmder window flickers crazy and no key works to stop it and I have to close the window. What causes this?

**Comment by daxgames** [comment]
Don't know never seen this happen.

**Comment by Sparh4wk** [comment]
have the same problem...

**Comment by floviolleau** [comment]
Same for me

**Comment by cdol** [comment]
I experience the same behaviour SSHing from Win10 to Ubuntu when using gpg. Specifically when prompted to re-enter the password.
