### ISSUE TITLE
need help for run bat 

### ISSUE THREAD

**Issue by lilixiong2018** [cmderdev/cmder#2233]
I write a bat file named test.bat which its conten is:

```
@echo off
if "%1"=="np+" (
	"c:\Program Files\Notepad++\notepad++.exe"
	GOTO completed
)
:completed
```

Now I run test.bat with param np+ in cmder prompt line ("test np+"), it open notepad++ sucess, but I notice that test.bat will not return until I close the notepad++ window.

In order to run test.bat with non blcok, I change test.bat to 
```
@echo off
if "%1"=="np+" (
	start "c:\Program Files\Notepad++\notepad++.exe"
	GOTO completed
)
:completed
```

then I run "test np+" and find it can not open notepad++ at all, instead, a new cmd.exe tab created:
![image](https://user-images.githubusercontent.com/40269098/71321515-37348e00-24f5-11ea-97fb-7c759e57ec1b.png)

Help! What's suggestions? 
Thanks.

**Comment by daxgames** [comment]
```
start /d "c:\Program Files\Notepad++" notepad++.exe
```

**Comment by lilixiong2018** [comment]
Well, it work! Thanks you very much.
