### ISSUE TITLE
question

### ISSUE THREAD

**Issue by shikulja** [cmderdev/cmder#2235]
1. where to add far manadger
2. is it possible to somehow add the choice of x86 x64 for dosbox and far is convenient for portability.

now far added in
C:\cmder\vendor\conemu-maximus5
But it didn’t turn out beautifully, and far does not start automatically

**Comment by daxgames** [comment]
I don't use far manager, actually I have never used it so I can't answer your question.  I assume you would install it as any app and run it from wherever it is installed.

**Comment by daxgames** [comment]
You should not put anything in `%cmder_root%\vendor` as it is subject to overwrite when you update cmder.

**Comment by shikulja** [comment]
@daxgames 
I found the information here
[https://conemu.github.io/en/Installation.html](url)

> If you install ConEmu in the same folder where far.exe is located, C:\Tools\Far for example, there will be no problem at all, ConEmu plugin will be (most probably) installed into C:\Tools\Far\plugins\ConEmu folder and will be loaded by far.exe automatically.

but it’s not clear whether Far autorun works and how to do it.
(far settings are also not saved, for example, the program language is returned)

**Comment by daxgames** [comment]
@shikulja I am sorry I am not sure what else I can do for you.  I know NOTHING about Far.
