### ISSUE TITLE
ls (-lah) is not working properly with split consoles

### ISSUE THREAD

**Issue by xbelanch** [cmderdev/cmder#2236]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information
cmder version 1.3.13.967
Windows 10 Pro 1903 18362.535

### Description of the issue

See what happens when I execute the ls command on split consoles (but also with single ones):

![2020-01-04_12-33-10](https://user-images.githubusercontent.com/23429/71764918-8237a380-2eee-11ea-803f-ab7b1c671827.gif)

**Comment by daxgames** [comment]
@xbelanch Works fine for me.

**Comment by xbelanch** [comment]
@daxgames just recorded a video showing the issue with a fresh cmder installation

https://youtu.be/qgP-ncVpYV4

**Comment by daxgames** [comment]
I just fresh installed the last 3 versions of cmder and they all work flawlesly with `ls -lah`.

Does the same happen in cmd.exe outside Cmder?  You will probably need to change to `%cmder_root%\vendor\git-for-windows\usr\bin`

**Comment by xbelanch** [comment]
You're lucky man :)
cmder.exe outside its directory raises this error:
![Cmder_2020-01-06_16-03-20](https://user-images.githubusercontent.com/23429/71826403-1eec7380-309e-11ea-8e42-9d0adf9e035f.png)

My bad, but I don't figure out how and where I change that path :-/

**Comment by daxgames** [comment]
I didnt say use cmder.  

- launch `start->cmd.exe`
- change to the referenced directory `cd /d "[cmder folder]\vendor\git-for-windows\usr\bin`
- run `ls -lah`

**Comment by xbelanch** [comment]
Oh! Sorry for my dumb way of reading.
Okay, I followed your steps but if I'm not wrong once again, the cmder "mini" version has no "git-for-windows" directory:

```
C:\Users\Rotter\Desktop\cmder\vendor>ls -lah
total 147K
drwxrwx---+ 1 Rotter Ninguno    0 Jan  6 09:12 .
drwxrwx---+ 1 Rotter Ninguno    0 Jan  6 16:16 ..
-rwxrwx---+ 1 Rotter Ninguno  54K Jan  6 09:12 ConEmu.xml.default
-rwxrwx---+ 1 Rotter Ninguno   49 Jan  6 09:12 Readme.md
drwxrwx---+ 1 Rotter Ninguno    0 Jan  6 09:12 bin
drwxrwx---+ 1 Rotter Ninguno    0 Jan  6 09:12 clink
drwxrwx---+ 1 Rotter Ninguno    0 Jan  6 09:12 clink-completions
-rwxrwx---+ 1 Rotter Ninguno  14K Jan  6 09:12 clink.lua
-rwxrwx---+ 1 Rotter Ninguno 4.0K Jan  6 09:12 clink_settings.default
-rwxrwx---+ 1 Rotter Ninguno 3.9K Jan  6 09:12 cmder_exinit
drwxrwx---+ 1 Rotter Ninguno    0 Jan  6 15:53 conemu-maximus5
-rwxrwx---+ 1 Rotter Ninguno  15K Jan  6 09:12 init.bat
drwxrwx---+ 1 Rotter Ninguno    0 Jan  6 09:12 lib
-rwxrwx---+ 1 Rotter Ninguno 7.0K Jan  6 09:12 profile.ps1
drwxrwx---+ 1 Rotter Ninguno    0 Jan  6 09:12 psmodules
-rwxrwx---+ 1 Rotter Ninguno  718 Jan  6 09:12 sources.json
-rwxrwx---+ 1 Rotter Ninguno  443 Jan  6 09:12 user_aliases.cmd.default
-rwxrwx---+ 1 Rotter Ninguno  722 Jan  6 09:12 user_profile.cmd.default
-rwxrwx---+ 1 Rotter Ninguno  861 Jan  6 09:12 user_profile.ps1.default
-rwxrwx---+ 1 Rotter Ninguno  295 Jan  6 09:12 user_profile.sh.default
```

**Comment by i-s-o** [comment]
So, your `ls` didn't come with Cmder: maybe it is too old or just incompatible with ConEmu? Does it work properly in cmd.exe? What happens if you try the full Cmder that comes with `ls` provided by git-for-windows?

Here is what I see in Cmder:
```
C:\tools\cmder
λ ls -lah
total 164K
drwxr-xr-x 1 ismail 197121    0 Dec 17 07:24  ./
drwxr-xr-x 1 ismail 197121    0 Jan  1 19:59  ../
drwxr-xr-x 1 ismail 197121    0 Dec 17 08:37  bin/
-rwxr-xr-x 1 ismail 197121 139K Dec  2 19:18  Cmder.exe*
drwxr-xr-x 1 ismail 197121    0 Dec 29 18:51  config/
drwxr-xr-x 1 ismail 197121    0 Dec  2 19:17  icons/
-rw-r--r-- 1 ismail 197121 1.1K Dec  2 19:17  LICENSE
drwxr-xr-x 1 ismail 197121    0 Dec  2 19:18  vendor/
-rw-r--r-- 1 ismail 197121    0 Dec  2 19:18 'Version 1.3.13.968'

C:\tools\cmder
λ where ls
C:\tools\cmder\vendor\git-for-windows\usr\bin\ls.exe

C:\tools\cmder
λ ls --version
ls (GNU coreutils) 8.31
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Richard M. Stallman and David MacKenzie.
```

**Comment by xbelanch** [comment]
Thanks @i-s-o! I checked where ``ls`` is installed and I found that:

````
λ where ls
C:\cygwin64\bin\ls.exe
C:\Program Files\Git\usr\bin\ls.exe
```` 
So the ls.exe from cygwin (older than the git version) was the problem! I fixed this and now it works perfectly.
