### ISSUE TITLE
when i try to click the icon this pops up

### ISSUE THREAD

**Issue by littlekidsasa** [cmderdev/cmder#2239]
![Capture](https://user-images.githubusercontent.com/59585000/71855085-16039e00-30ae-11ea-878c-0ab1350376d9.PNG)

### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

**Comment by daxgames** [comment]
@littlekidsasa where is the cmder folder.  We recommend in your user directory.

**Comment by daxgames** [comment]
@littlekidsasa Did my suggestion help?  If so please close the issue.
