### ISSUE TITLE
cmder shortcut bug feedback

### ISSUE THREAD

**Issue by dajiiu** [cmderdev/cmder#2242]
> Cmder uses shortcut(Ctrl + U) command to remove unclean  

![cmder_bug](https://user-images.githubusercontent.com/52339367/72127698-8448a900-33ab-11ea-94a5-d82260a570c2.gif)

**Comment by daxgames** [comment]
@dajiiu Works for me.  

Look at #918.  Possibly one of these setting as required to make it work right.

**Comment by dajiiu** [comment]
![cmder_bug2](https://user-images.githubusercontent.com/52339367/72202109-ae2aca00-3496-11ea-8d92-5a030737862c.gif)

**Comment by daxgames** [comment]
@dajiiu 

I like the videos but a few words to explain would be helpful also.

So before the change it worked and after it didn't?  Undo the change.
The settings I recommended were a possible nudge in the right direction not a guarantee of a fix.  In fact the settings I recommended can have different settings themselves based on your workstation setup.

My point is this is not an issue we can fix it is probably a configuration issue you will need to figure out and let users here know what you found.

**Comment by dajiiu** [comment]
According to issue provided above, make the same configuration. Using shortcut keys to remove an entire line of input commands will leave a letter, which has no effect but only appears to have.  For example, if the letter left behind is 'g', the input git will display 'ggit' on the interface.  

The content of the configuration is 
```bash
set LC_ALL=zh_CN.UTF-8
set LANG=zh_CN.UTF-8
chcp utf8
set ConEmuDefaultCp=65001
```

**Comment by daxgames** [comment]
What language settings are you using by default?  This is probably not a Cmder issue rather it is probably a language/locale issue.  I do not see this problem using my default English language/locale settings.  You will probably have to do a lot of research and experimentation to get it fixed.  Please report back here if you find a solution.

**Comment by dajiiu** [comment]
Currently using Chinese environment
