### ISSUE TITLE
Cmder taskbar icon not stacking when open

### ISSUE THREAD

**Issue by wardinh0** [cmderdev/cmder#2243]
Sorry if this is a super lame issue, I went through some similar Issues, e.g., issue #758.

(I think) it's not a bug, I just can't set it so that the taskbar icon stacks as I open Cmder. I made a simple demo [GIF](https://i.imgur.com/PrjI35Z.gif).

It's probably something super simple but I've trying for hours and can't solve this, so I came here for help.

**Comment by daxgames** [comment]
@wardinh0 I am sorry I don't understand the issue.
