### ISSUE TITLE
Error code 267 when trying to open new powershell tab.

### ISSUE THREAD

**Issue by guerra08** [cmderdev/cmder#2244]
Windows 10 Insider

Cmder version 191012 preview

**Issue:** When trying to launch a new tab with powershell, I'm greeted with the error code 267.

**Steps:** Start Cmder and try to open a new tab with powershel (without admin privileges).

![image](https://user-images.githubusercontent.com/29544679/72303895-8af64b00-364d-11ea-9f27-8675aeb31879.png)

The name of the user in the working folder does not match my user.

**Comment by MartiUK** [comment]
Try installing cmder in your user directory

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by guerra08** [comment]
Problem solved, tweaked some of the settings and it worked!

**Comment by guerra08** [comment]
Solved by changing some settings.
