### ISSUE TITLE
Include default WindowsPowerShell/Profile.ps1

### ISSUE THREAD

**Issue by darkretailer** [cmderdev/cmder#2245]
I suggest to load the default Profile.ps1 which is used by PowerShell by default.
Example:
%userprofile%/documents/WindowsPowerShell/Profile.ps1
Currently this scripts will be ignored in Cmder/PowerShell.

I have a solution for myself by adding this paths to the Cmder/Profile.ps1, but i think this should be loaded by default.

Source: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7

**Comment by daxgames** [comment]
@darkretailer thanks fir the suggestion bu the point of `Cmder` is to be a portable package to configure the shell that results in a known config, as much as possible, on any system.  Including the default Powershell profile may not be desired by all users.

If a user wants to load the default Powershell user profile its easy enough to add by editing `%CMDER_ROOT%\config\user_profile.ps1` and adding `source $profile`.

**Comment by darkretailer** [comment]
you are right...
it is not that hard ;-)

thank you anyway!
