### ISSUE TITLE
"Shortcut mode?" - having to restart regularly

### ISSUE THREAD

**Issue by woottonn** [cmderdev/cmder#2246]
I'm not sure if this is a bug or something I'm pressing. Every hour or so CMDER seems to go into a weird shortcut mode. Half the keys I press no longer type the character, they start opening windows. 

e.g. the A key opens up a "Set active processes affinity and priority" window like below..

![image](https://user-images.githubusercontent.com/6769984/72444244-96f62000-37a7-11ea-96a8-42895eb71f52.png)

Is this something I'm doing wrong?

**Comment by daxgames** [comment]
Don't know never had this issue.

Probably a better question to ask of the conemu devs.  Conemu is the terminal emulator for cmder.

**Comment by MartiUK** [comment]
Are you sure you're not enabling sticky keys or something? It sounds like you're pressing ctrl + a or alt + a to get these windows up

**Comment by woottonn** [comment]
Hmmmm... no sticky keys, just checked and its off. How would I go about asking the devs?

**Comment by daxgames** [comment]
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem or have a question, please open an issue over at https://github.com/Maximus5/ConEmu
