### ISSUE TITLE
init.bat throws "The input line is too long" error

### ISSUE THREAD

**Issue by guoliang** [cmderdev/cmder#2247]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information
1.3.14

Windows 10 Pro 1803
### Description of the issue
When I start cmder using the provided `init.bat` I get following error
![image](https://user-images.githubusercontent.com/542598/72507501-4d0f4780-3844-11ea-8c47-1917c6c5bdc0.png)

I have traced it down to the following line where it starts to throw errors i.e "The input line is too long"
https://github.com/cmderdev/cmder/blob/638d82e9897864935480a81b6c0b20b0e883b3ff/vendor/init.bat#L221

I tried to fix it somehow, but I'm not a batch script expert. Right now I have reverted it to the original init.bat.

**Comment by daxgames** [comment]
What do you mean 'Right now I have reverted it to the original init.bat.'?  What version works?

That code has been in place for several versions of cmder.

**Comment by guoliang** [comment]
> 
> 
> What do you mean 'Right now I have reverted it to the original init.bat.'? What version works?
> 
> That code has been in place for several versions of cmder.

I meant I reverted my changes, that is I removed all my debugging traces, so the `init.bat` file is in its initial state before anything was done to it.

**Comment by daxgames** [comment]
Do previous versions of cmder have the same issue?

**Comment by daxgames** [comment]
Chances are the path is already too long and when we try to add to it there is an error.  This is probably not something we can fix as it is a limitation of cmd.exe

**Comment by guoliang** [comment]
> 
> 
> Chances are the path is already near its max length and when we try to add to it there is an error. This is probably not something we can fix as it is a limitation of cmd.exe.
> 
> Just a theory given what I know.

I don't think the path is the issue though. If it's the path to git it looks as following for me
![image](https://user-images.githubusercontent.com/542598/72529105-dcc8ec00-386c-11ea-9056-8480e047401b.png)

Is there's a way I can get the logs to further look into it?

**Comment by daxgames** [comment]
Not the path to Git the overall system path.  You could add `/d /v` to the task launching the `cmd::cmder` task and it will give you a lot more output on starting cmder.  In the bin folder ther are also diag scripts that will provide a 'picture' of your env.  You can post the output of both.

**Comment by guoliang** [comment]
I got the following log when I started a cmder tab with `/d /v`
![image](https://user-images.githubusercontent.com/542598/72544527-ddbb4700-3887-11ea-809f-a391ab0cec2c.png)

I could not find the mentioned `diag scripts` in the bin folder though. It was just a `README.md` in there.

**Comment by daxgames** [comment]
@guoliang Diag scripts:

![image](https://user-images.githubusercontent.com/7318053/74597265-42ee8d80-502a-11ea-9c76-e0b9cf5e5927.png)

**Comment by guoliang** [comment]
λ bash bin\cmder_diag.sh
------------------------------------
ls -la C:\tools\cmder
------------------------------------
total 256
drwxr-xr-x 1 lwong1 1049089      0 Jan 10 09:54  .
drwxr-xr-x 1 lwong1 1049089      0 Jan  6 21:52  ..
-rw-r--r-- 1 lwong1 1049089  73491 Feb 11  2018  CHANGELOG.md
-rw-r--r-- 1 lwong1 1049089   1784 Feb 11  2018  CONTRIBUTING.md
-rwxr-xr-x 1 lwong1 1049089 141824 Jan  9 03:47  Cmder.exe
-rw-r--r-- 1 lwong1 1049089   1069 Jan  9 03:47  LICENSE
-rw-r--r-- 1 lwong1 1049089  13140 Feb 11  2018  README.md
-rw-r--r-- 1 lwong1 1049089      0 Nov 30  2018 'Version 1.3.10.811'
-rw-r--r-- 1 lwong1 1049089      0 Dec 22  2018 'Version 1.3.11.843'
-rw-r--r-- 1 lwong1 1049089      0 Aug 19  2019 'Version 1.3.12.915'
-rw-r--r-- 1 lwong1 1049089      0 Nov 24 00:14 'Version 1.3.13.967'
-rw-r--r-- 1 lwong1 1049089      0 Jan  9 03:47 'Version 1.3.14.982'
-rw-r--r-- 1 lwong1 1049089      0 May 30  2018 'Version 1.3.6.678'
-rw-r--r-- 1 lwong1 1049089      0 Nov 10  2018 'Version 1.3.8.793'
-rw-r--r-- 1 lwong1 1049089      0 Feb 11  2018 'Version v1.3.5'
drwxr-xr-x 1 lwong1 1049089      0 Jan  9 03:47  bin
drwxr-xr-x 1 lwong1 1049089      0 Jan 15 10:31  config
drwxr-xr-x 1 lwong1 1049089      0 Jan  9 03:47  icons
drwxr-xr-x 1 lwong1 1049089      0 Feb 19 10:08  vendor

------------------------------------
ls -la C:\tools\cmder/vendor
------------------------------------
total 150
drwxr-xr-x 1 lwong1 1049089     0 Feb 19 10:08 .
drwxr-xr-x 1 lwong1 1049089     0 Jan 10 09:54 ..
-rw-r--r-- 1 lwong1 1049089 54990 Jan  9 03:47 ConEmu.xml.default
-rw-r--r-- 1 lwong1 1049089    49 Jan  9 03:47 Readme.md
drwxr-xr-x 1 lwong1 1049089     0 Jan  9 03:47 bin
drwxr-xr-x 1 lwong1 1049089     0 Dec 20  2017 clink
drwxr-xr-x 1 lwong1 1049089     0 Dec  5 08:47 clink-completions
-rw-r--r-- 1 lwong1 1049089 13686 Jan  9 03:47 clink.lua
-rw-r--r-- 1 lwong1 1049089  4015 Jan  9 03:47 clink_settings.default
-rw-r--r-- 1 lwong1 1049089     0 Feb 19 10:08 cmder_diag.txt
-rw-r--r-- 1 lwong1 1049089  3903 Jan  9 03:47 cmder_exinit
drwxr-xr-x 1 lwong1 1049089     0 Feb 19 10:01 conemu-maximus5
drwxr-xr-x 1 lwong1 1049089     0 Jan 10 10:17 git-for-windows
-rw-r--r-- 1 lwong1 1049089 15119 Jan 16 11:52 init.bat
drwxr-xr-x 1 lwong1 1049089     0 Jan  9 03:47 lib
-rw-r--r-- 1 lwong1 1049089  7153 Jan  9 03:47 profile.ps1
drwxr-xr-x 1 lwong1 1049089     0 Jan  9 03:47 psmodules
-rw-r--r-- 1 lwong1 1049089   720 Jan  9 03:47 sources.json
-rw-r--r-- 1 lwong1 1049089   440 May 30  2018 user-aliases.cmd.example
-rw-r--r-- 1 lwong1 1049089   443 Jan  9 03:47 user_aliases.cmd.default
-rw-r--r-- 1 lwong1 1049089   440 Nov 30  2018 user_aliases.cmd.example
-rw-r--r-- 1 lwong1 1049089   722 Jan  9 03:47 user_profile.cmd.default
-rw-r--r-- 1 lwong1 1049089   861 Jan  9 03:47 user_profile.ps1.default
-rw-r--r-- 1 lwong1 1049089   295 Jan  9 03:47 user_profile.sh.default

------------------------------------
ls -la /s C:\tools\cmder/bin
------------------------------------
ls: cannot access '/s': No such file or directory
'C:\tools\cmder/bin':
total 5
drwxr-xr-x 1 lwong1 1049089  0 Jan  9 03:47 .
drwxr-xr-x 1 lwong1 1049089  0 Jan 10 09:54 ..
-rw-r--r-- 1 lwong1 1049089 84 Jan  9 03:47 Readme.md

------------------------------------
ls -la /s C:\tools\cmder/config
------------------------------------
ls: cannot access '/s': No such file or directory
'C:\tools\cmder/config':
total 413
drwxr-xr-x 1 lwong1 1049089      0 Jan 15 10:31 .
drwxr-xr-x 1 lwong1 1049089      0 Jan 10 09:54 ..
-rw-r--r-- 1 lwong1 1049089 267095 Feb 19 09:38 .history
-rw-r--r-- 1 lwong1 1049089  54966 May 30  2018 ConEmu.xml
-rw-r--r-- 1 lwong1 1049089    887 Jan  9 03:47 Readme.md
drwxr-xr-x 1 lwong1 1049089      0 Aug  3  2018 profile.d
-rw-r--r-- 1 lwong1 1049089   4131 Aug  3  2018 settings
-rw-r--r-- 1 lwong1 1049089  58496 Jan 14 13:44 user-ConEmu.xml
-rw-r--r-- 1 lwong1 1049089    535 Aug  3  2018 user-profile.cmd
-rw-r--r-- 1 lwong1 1049089   1348 Jan 14 13:45 user_aliases.cmd
-rw-r--r-- 1 lwong1 1049089    733 Nov 14  2018 user_profile.cmd
-rw-r--r-- 1 lwong1 1049089    861 Jan  9 03:47 user_profile.ps1

'C:\tools\cmder/config/profile.d':
total 4
drwxr-xr-x 1 lwong1 1049089 0 Aug  3  2018 .
drwxr-xr-x 1 lwong1 1049089 0 Jan 15 10:31 ..

------------------------------------
env
------------------------------------
feFlagName=
USERDOMAIN=INFOR
ChocolateyToolsLocation=C:\tools
OS=Windows_NT
fast_init=0
COMMONPROGRAMFILES=C:\Program Files\Common Files
PROCESSOR_LEVEL=6
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\windows\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\PowerShell\Modules\
ConEmuDrawHWND=0x00020B26
CommonProgramW6432=C:\Program Files\Common Files
nix_tools=1
M2_HOME=C:\ProgramData\chocolatey\lib\maven\apache-maven-3.6.3
ConEmuDrive=C:
!ExitCode=00000000
lib_git=call "C:\tools\cmder\vendor\lib\lib_git.cmd"
debug_output=0
CMDER_ROOT=C:\tools\cmder
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
position=append
lib_console=call "C:\tools\cmder\vendor\lib\lib_console.cmd"
found=1
PUBLIC=C:\Users\Public
ConEmuArgs2=
VENDORED_MAJOR=2
ccall=call C:\tools\cmder\vendor\bin\cexec.cmd
GITHUB_ACCESS_TOKEN=6552185788985f21b3071fe842b96d53b2781bf5
USER_MINOR=25
GIT_INSTALL_ROOT=C:\Program Files\Git
USERNAME=lwong1
find_query=C:\\Program\ Files\\Git\\cmd
ChocolateyInstall=C:\ProgramData\chocolatey
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_211
USER_PATCH=0
LOGONSERVER=\\NLBAVWDC1
PROCESSOR_ARCHITECTURE=AMD64
lib_profile=call "C:\tools\cmder\vendor\lib\lib_profile.cmd"
COMMANDER_PATH=C:\Program Files\totalcmd
git_executable=C:\Program Files\Git\cmd\git.exe
ConEmuPalette=Monokai
LOCALAPPDATA=C:\Users\lwong1\AppData\Local
ConEmuHooks=Enabled
CLASSPATH=.;
COMPUTERNAME=SELINLWONG02
USER_BUILD=windows.1
lib_path=call "C:\tools\cmder\vendor\lib\lib_path.cmd"
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
!::=::\
SYSTEMDRIVE=C:
USERPROFILE=C:\Users\lwong1
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW;.RB;.RBW
SYSTEMROOT=C:\windows
USERDOMAIN_ROAMINGPROFILE=INFOR
OneDriveCommercial=C:\Users\lwong1\OneDrive - Infor
ConEmuDir=C:\tools\cmder\vendor\conemu-maximus5
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
ANSICON_DEF=7
lib_base=call "C:\tools\cmder\vendor\lib\lib_base.cmd"
ConEmuArgs=
OneDriveConsumer=C:\Users\lwong1\OneDrive
PWD=/c/tools/cmder/vendor
VCTargetsPath=C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets
HOME=/c/Users/lwong1
TMP=/tmp
ConEmuWorkDir=C:\Users\lwong1\Development\gitrepos\infor\mashups\server\server-gar
VENDORED_BUILD=windows.2
ConEmuANSI=ON
path_position=append
cexec=C:\tools\cmder\vendor\bin\cexec.cmd
CMDER_INIT_START=10:04:08,90
verbose_output=0
OneDrive=C:\Users\lwong1\OneDrive - Infor
OLD_PATH=C:\tools\cmder\vendor\conemu-maximus5\ConEmu\Scripts;C:\tools\ruby27\bin;C:\Python27\;C:\Python27\Scripts;C:\Python38\Scripts\;C:\Python38\;C:\tools\ruby26\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\tools\ruby25\bin;C:\Python37\Scripts\;C:\Python37\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\ProgramData\chocolatey\bin;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Java\jdk1.8.0_181\bin;C:\Users\lwong1\.npm-packages;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files\Java\jdk1.8.0_191\bin;C:\Program Files\Java\jdk1.8.0_201\bin;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Java\jdk1.8.0_211\bin;C:\Program Files\Gource\cmd;C:\ProgramData\chocolatey\lib\maven\apache-maven-3.6.1\bin;C:\ProgramData\chocolatey\lib\maven\apache-maven-3.6.1\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\ProgramData\chocolatey\lib\maven\apache-maven-3.6.3\bin;C:\Program Files\Calibre2\;C:\tools\BCURRAN3;C:\Program Files\Git\cmd;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\GitExtensions\;C:\Program Files\nodejs\;C:\Users\lwong1\.windows-build-tools\python27\;C:\Users\lwong1\.npm-packages\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;c:\users\lwong1\.npm-packages\node_modules\windows-build-tools\node_modules\.bin;c:\users\lwong1\.npm-packages\node_modules\.bin;C:\tools\cmder\bin;C:\tools\cmder\vendor\bin;C:\tools\cmder\vendor\conemu-maximus5\ConEmu\Scripts;C:\tools\cmder\vendor\conemu-maximus5;C:\tools\cmder\vendor\conemu-maximus5\ConEmu;C:\tools\ruby26\bin;C:\tools\ruby25\bin;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Python37\Scripts\;C:\Python37\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\ProgramData\chocolatey\bin;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Java\jdk1.8.0_181\bin;C:\Users\lwong1\.npm-packages;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files\Java\jdk1.8.0_191\bin;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Java\jdk1.8.0_201\bin;C:\Program Files (x86)\GitExtensions\;C:\Program Files\Git\cmd;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Java\jdk1.8.0_211\bin;C:\Program Files\nodejs\;C:\tools\Sencha\Cmd\6.1.2.15/..;C:\Users\lwong1\AppData\Local\Microsoft\WindowsApps;C:\tools\cmder;C:\Program Files (x86)\LinqPad5;C:\tools\neovim\Neovim\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\tools\cmder;C:\Users\lwong1\AppData\Roaming\npm
ConEmuAnsiLog=
architecture_bits=64
!C:=C:\tools\cmder\vendor
PROCESSOR_REVISION=9e09
FPS_BROWSER_USER_PROFILE_STRING=Default
add_path=C:\Program Files\Git\cmd
USERDNSDOMAIN=INFOR.COM
PROMPT=$P$G
NUMBER_OF_PROCESSORS=8
GIT_VERSION_VENDORED=2.24.1.windows.2
ProgramW6432=C:\Program Files
ConEmuCfgDir=C:\tools\cmder\vendor\conemu-maximus5
USER_MAJOR=2
ConEmuWorkDrive=C:
VENDORED_PATCH=1
ConEmuBackHWND=0x0004091A
COMSPEC=C:\windows\system32\cmd.exe
ConEmuConfig=
ConEmuHWND=0x0032073C
APPDATA=C:\Users\lwong1\AppData\Roaming
TERM=cygwin
CMDER_USER_FLAGS=
CMDER_CLINK=1
WINDIR=C:\windows
GIT_VERSION_USER=2.25.0.windows.1
time_init=0
ProgramData=C:\ProgramData
SHLVL=1
PLINK_PROTOCOL=ssh
PROGRAMFILES=C:\Program Files
ConEmuBaseDir=C:\tools\cmder\vendor\conemu-maximus5\ConEmu
max_depth=1
ALLUSERSPROFILE=C:\ProgramData
TEMP=/tmp
DriverData=C:\Windows\System32\Drivers\DriverData
SESSIONNAME=Console
ConEmuBuild=191012
VENDORED_MINOR=24
ProgramFiles(x86)=C:\Program Files (x86)
PATH=/c/tools/cmder/vendor/conemu-maximus5/ConEmu/Scripts:/c/tools/ruby27/bin:/c/Python27:/c/Python27/Scripts:/c/Python38/Scripts:/c/Python38:/c/tools/ruby26/bin:/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/c/tools/ruby25/bin:/c/Python37/Scripts:/c/Python37:/c/windows/system32:/c/windows:/c/windows/System32/Wbem:/c/windows/System32/WindowsPowerShell/v1.0:/c/windows/System32/OpenSSH:/c/Program Files/Microsoft SQL Server/130/Tools/Binn:/c/Program Files/dotnet:/c/ProgramData/chocolatey/bin:/c/Program Files/Microsoft VS Code/bin:/c/Program Files/Java/jdk1.8.0_181/bin:/c/Users/lwong1/.npm-packages:/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/130/Tools/Binn:/c/Program Files (x86)/Microsoft SQL Server/140/Tools/Binn:/c/Program Files/Microsoft SQL Server/140/Tools/Binn:/c/Program Files/Microsoft SQL Server/140/DTS/Binn:/c/Program Files (x86)/Microsoft SQL Server/Client SDK/ODBC/130/Tools/Binn:/c/Program Files (x86)/Microsoft SQL Server/140/DTS/Binn:/c/Program Files (x86)/Microsoft SQL Server/140/Tools/Binn/ManagementStudio:/c/Program Files/Java/jdk1.8.0_191/bin:/c/Program Files/Java/jdk1.8.0_201/bin:/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn:/c/Program Files/Java/jdk1.8.0_211/bin:/c/Program Files/Gource/cmd:/c/ProgramData/chocolatey/lib/maven/apache-maven-3.6.1/bin:/c/ProgramData/chocolatey/lib/maven/apache-maven-3.6.1/bin:/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/c/Program Files/Intel/WiFi/bin:/c/Program Files/Common Files/Intel/WirelessCommon:/c/ProgramData/chocolatey/lib/maven/apache-maven-3.6.3/bin:/c/Program Files/Calibre2:/c/tools/BCURRAN3:/cmd:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files (x86)/GitExtensions:/c/Program Files/nodejs:/c/Users/lwong1/.windows-build-tools/python27:/c/Users/lwong1/.npm-packages/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/c/users/lwong1/.npm-packages/node_modules/windows-build-tools/node_modules/.bin:/c/users/lwong1/.npm-packages/node_modules/.bin:/c/tools/cmder/bin:/c/tools/cmder/vendor/bin:/c/tools/cmder/vendor/conemu-maximus5/ConEmu/Scripts:/c/tools/cmder/vendor/conemu-maximus5:/c/tools/cmder/vendor/conemu-maximus5/ConEmu:/c/tools/ruby26/bin:/c/tools/ruby25/bin:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/iCLS:/c/Program Files/Intel/Intel(R) Management Engine Components/iCLS:/c/Python37/Scripts:/c/Python37:/c/windows/system32:/c/windows:/c/windows/System32/Wbem:/c/windows/System32/WindowsPowerShell/v1.0:/c/windows/System32/OpenSSH:/c/Program Files/Microsoft SQL Server/130/Tools/Binn:/c/Program Files/dotnet:/c/ProgramData/chocolatey/bin:/c/Program Files/Microsoft VS Code/bin:/c/Program Files/Java/jdk1.8.0_181/bin:/c/Users/lwong1/.npm-packages:/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/130/Tools/Binn:/c/Program Files (x86)/Microsoft SQL Server/140/Tools/Binn:/c/Program Files/Microsoft SQL Server/140/Tools/Binn:/c/Program Files/Microsoft SQL Server/140/DTS/Binn:/c/Program Files (x86)/Microsoft SQL Server/Client SDK/ODBC/130/Tools/Binn:/c/Program Files (x86)/Microsoft SQL Server/140/DTS/Binn:/c/Program Files (x86)/Microsoft SQL Server/140/Tools/Binn/ManagementStudio:/c/Program Files/Java/jdk1.8.0_191/bin:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/c/Program Files/Java/jdk1.8.0_201/bin:/c/Program Files (x86)/GitExtensions:/cmd:/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn:/c/Program Files/Java/jdk1.8.0_211/bin:/c/Program Files/nodejs:/c/tools/Sencha/Cmd/:/c/Users/lwong1/AppData/Local/Microsoft/WindowsApps:/c/tools/cmder:/c/Program Files (x86)/LinqPad5:/c/tools/neovim/Neovim/bin:/cmd:/mingw64/bin:/usr/bin:/c/tools/cmder:/c/Users/lwong1/AppData/Roaming/npm
ConEmuPID=14732
HOMEDRIVE=C:
ConEmuBaseDirShort=C:\tools\cmder\vendor\conemu-maximus5\ConEmu
ChocolateyLastPathUpdate=132265739411193559
CMDER_ALIASES=1
architecture=64
HOMEPATH=\Users\lwong1
ConEmuServerPID=20624
CMDER_SHELL=cmd
RUBYOPT=-Eutf-8
ANSICON=305x1000 (305x86)
_=/usr/bin/env

------------------------------------
which git
------------------------------------
/cmd/git
