### ISSUE TITLE
Tab dont work well when I use linux screen in ConEmu?

### ISSUE THREAD

**Issue by lyg4795** [cmderdev/cmder#2248]
ConEmu version preview-191012. Screen version 4.00.03 (FAU) 23-Oct-06.

I connect to remote machine and attach to screen in ConEmu.

If I press 'tab' to autocomplete filename, the cursor will move half of screen.

If I do above action in powershell, the 'tab' work well.

**Comment by daxgames** [comment]
My guess this is a ConEmu issue.  does it happen in ConEmu outside Cmder?

**Comment by lyg4795** [comment]
> My guess this is a ConEmu issue. does it happen in ConEmu outside Cmder?

Yes,it is

**Comment by daxgames** [comment]
@lyg4795 Can we close this issue then?
