### ISSUE TITLE
How to obtain branch name in cmder

### ISSUE THREAD

**Issue by OldShaterhan** [cmderdev/cmder#2249]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [X] Question

### Version Information
1.3.14.982

Windows 10.

### Description of the issue
Hi guys,
I just downloaded cmder for my personal computer - I'm using it on other machine and it works really great. However, I have a problem with the git. On my second machine it works with providing git branch name after the path, e.g.:
`c:\dev\project (my-branch -> origin)`
or (for worktrees)
`c:\dev\project\develop (my-branch -> origin)`

Unfortunately I can't get it on my main machine at this moment and I don't remember what I did to achieve such solution. Additionally I cannot find it somewhere in the internet. I hope you could help me.

And my other question:
Is it possible in the worktrees to show branches and status (e.g. dirty code) aside the main directory?

**Comment by daxgames** [comment]
Try `git branch -u [branch_name]` minus the `[]`

**Comment by OldShaterhan** [comment]
This doesn't seem to be working. Additionally - I could see that without setting upstream branch. Maybe I was not precise, but for now I don't see any information about branch at the path level.

**Comment by daxgames** [comment]
I undersrood the prompt issue you were explaining  Have you pushed yet to the upstream I may have been incorrect on my other command.  `git push -u origin master`

**Comment by OldShaterhan** [comment]
Yes,, I have connected branches to the upstream.

**Comment by daxgames** [comment]
@OldShaterhan Output of `where git`?

**Comment by daxgames** [comment]
@OldShaterhan we will close this issue if you don't respond.  We can't help without additional info.

**Comment by OldShaterhan** [comment]
`
λ where git
E:\Program Files\Git\cmd\git.exe
E:\Program Files\Git\mingw64\bin\git.exe
D:\dev\cmder\vendor\git-for-windows\cmd\git.exe
D:\dev\cmder\vendor\git-for-windows\mingw64\bin\git.exe`

**Comment by daxgames** [comment]
@OldShaterhan have you tried [this](https://ci.appveyor.com/project/MartiUK/cmder/build/artifacts)

**Comment by daxgames** [comment]
@OldShaterhan Can you provide the output of `cat .git\config`.

I currently have different branches setup to track different remotes and it all works.

See below:

```
C:\Users\dtgam\cmder - development (master -> upstream)
λ gco 1.3.15
Switched to branch '1.3.15'
Your branch is up to date with 'origin/1.3.15'.

C:\Users\dtgam\cmder - development (1.3.15 -> origin)
λ cat .git\config
[core]
        repositoryformatversion = 0
        filemode = false
        bare = false
        logallrefupdates = true
        symlinks = false
        ignorecase = true
[remote "origin"]
        url = https://github.com/daxgames/cmder
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = upstream
        merge = refs/heads/master
[remote "upstream"]
        url = git@github.com:cmderdev/cmder.git
        fetch = +refs/heads/*:refs/remotes/upstream/*
[prompt]
        showinfo = true
[branch "user_lua"]
        remote = origin
        merge = refs/heads/user_lua
[branch "userlua"]
        remote = origin
        merge = refs/heads/userlua
[gui]
        wmstate = normal
        geometry = 893x435+234+234 175 196
[branch "1.3.15"]
        remote = origin
        merge = refs/heads/1.3.15
```

**Comment by daxgames** [comment]
And I can change the  remotes a branch tracks using:

```
C:\Users\dtgam\cmder - development (master -> upstream)
λ git branch -u origin master
Branch 'master' set up to track remote branch 'master' from 'origin'.

C:\Users\dtgam\cmder - development (master -> origin)
λ
```

**Comment by daxgames** [comment]
@OldShaterhan have you tried this [build](https://ci.appveyor.com/project/MartiUK/cmder/build/artifacts)

**Comment by OldShaterhan** [comment]
`cat .git\config.`:


`[core]
        repositoryformatversion = 0
        filemode = false
        bare = false
        logallrefupdates = true
        symlinks = false
        ignorecase = true
[remote "origin"]
        url = ***
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master
[branch "data-obtaining"]
        remote = origin
        merge = refs/heads/data-obtaining
[user]
        email = ***
        name = ***
[branch "MIB3RD-1-sources-update-Python3"]
        remote = origin
        merge = refs/heads/MIB3RD-1-sources-update-Python3
[branch "python2-test"]
        remote = origin
        merge = refs/heads/python2-test`

`git branch -u origin master` doesn't change anything.

What I see now, is that for simple-icons repository it works properly, but not for this repo I try to use. Other steps I will check soon.

**Comment by JohnnyFun** [comment]
This happened to me when I upgraded from win10 to win11. Not sure which of these did the trick, but:

- be sure you have 7-zip installed on your system
  - I was getting prompted about it not being installed and then seeing a big output of failures when I opened up cmder
  - but when I installed 7-zip, I got prompted for an update to cmder on startup, it ran, and then cmder looked good again with branch name
- other things to check:
  - download the zip, right click it, check "unblock", and save those settings before extracting it

**Comment by bariod** [comment]
I'm having a similar issue where the branch name isn't visible in worktree directories. It works for "normal" repos.

**Comment by daxgames** [comment]
@bariod can you explain 'worktree directories'?

**Comment by bariod** [comment]
A [git worktree](https://git-scm.com/docs/git-worktree) directory.

**Comment by chrisant996** [comment]
Most likely the lua script is directly peeking inside git internal files, because it's faster than invoking `git` commands to get the branch name.  And the script probably doesn't include support for peeking inside the alternate file structures used for tracking the .git dir for a worktree.

**Comment by daxgames** [comment]
Just looked at the code.  That is indeed wht the lua is doing.

**Comment by daxgames** [comment]
Just did a little playing and if we switched to `git rev-parse --abbrev-ref HEAD` it would fix the issue.

**Comment by chrisant996** [comment]
The lua is trying to handle exactly this case.

But [this line](https://github.com/cmderdev/cmder/blob/0616ff0a828595d8dfe379f0c6ed195af24ef28e/vendor/clink.lua#L259) only handles a relative path.
But the path can be relative or absolute.

So it should be possible to fix by just inserting a check for absolute path immediately before the line linked above:
```lua
        -- INSERT THIS...
        if os.isdir then -- only available in Clink v1.0.0 and higher
            if git_dir and os.isdir(git_dir) then
                return git_dir
            end
        end
        -- IMMEDIATELY BEFORE THIS...
        return git_dir and dir..'/'..git_dir
```

This would be much higher performance than spawning `git rev-parse`.

**Comment by daxgames** [comment]
@chrisant996 tried the fix above.  It does indeed fix the issue.

**Comment by bariod** [comment]
Do you intend to apply the proposed fix?

**Comment by daxgames** [comment]
Just merged the fix.  Archives shod be available soon as an unreleased build.
