### ISSUE TITLE
Cant find a way to persist history when using BASH shell

### ISSUE THREAD

**Issue by kksharma1618** [cmderdev/cmder#2251]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Version Information

Version 1.3.14.982

### Description of the issue

When using bash shell, history is not persisted when window is closed. I saw some existing closed issues for the same history issue, but they are for cmd/powershell.
Any ideas how I can make this work in bash?

**Comment by daxgames** [comment]
The same way you would for any bash shell, add it to an `sh` script that is sourced during startup.  `~/.bashrc` would work but not be portable.  A portable option would be `$CMDER_ROOT/config/user-profile.sh` or any code in `$CMDER_ROOT/config/profile.d/*.sh`

**Comment by kksharma1618** [comment]
Thank you. Didnt know that bash needed specific command for that :)
If anyone else need it, this helped https://superuser.com/questions/584480/how-to-persist-bash-history

```
# Make Bash append rather than overwrite the history on disk:
shopt -s histappend
# A new shell gets the history lines from all previous shells
PROMPT_COMMAND='history -a'
# Don't put duplicate lines in the history.
export HISTCONTROL=ignoredups
```
