### ISSUE TITLE
Is there any way to prevent the ConEmuTask to go into the ENV vars?

### ISSUE THREAD

**Issue by reypm** [cmderdev/cmder#2252]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Version Information
 - ConEmu 191012 preview
 -  OsVer: 10.0.18363.x64, Product: workstation, SP: 0.0, Suite: 0x100
 - Build: 1909, UBR: 592, ReactOS: 0, Rsrv: 0, WINE: 0, PE: 0, R2: 0

### Description of the issue
I am using Cmder and Docker Desktop and so far I didn't have any issues. I have updated Docker Desktop to it's latest version and now I am unable to run `docker-compose` commands. See below:

```bash
λ docker-compose exec service-name php bin/console
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 72, in main
  File "compose\cli\main.py", line 128, in perform_command
  File "compose\cli\main.py", line 491, in exec_command
  File "compose\cli\main.py", line 1469, in call_docker
  File "subprocess.py", line 172, in call
  File "subprocess.py", line 394, in __init__
  File "subprocess.py", line 644, in _execute_child
TypeError: environment can only contain strings
[16508] Failed to execute script docker-compose
```

If I run `printenv` everything seems to be fine except for a var being added as:

```
ConEmuTask={bash::bash}
```
or 
```
ConEmuTask={cmd::Cmder}
```
Is there any way to prevent Cmder for doing this?

**Comment by daxgames** [comment]
Cmder is not doing it conemu is.  Only option might be to rename the task without `::`

**Comment by daxgames** [comment]
Is your docker-compose file importing the whole env somehow?

**Comment by reypm** [comment]
@daxgames no, it is not it only use environment variables defined within `docker-compose.yml` and all of them are strings

**Comment by daxgames** [comment]
Did renaming the task help?

**Comment by reypm** [comment]
@daxgames I don't know how to achieve such thing and I will have to try tomorrow since I am out of office for today and have Mac at house not Windows sorry about that

**Comment by daxgames** [comment]
You will need to rename the task in the conemu setup tasks dialog and update the startup task to the new name in a different area of the same dialog.

**Comment by reypm** [comment]
@daxgames ok, cool I will give this a try first time tomorrow and mention you if it works or not thanks

**Comment by reypm** [comment]
@daxgames I haven't tried your solution but I am closing this since there seems to be some issues with Docker (see here https://github.com/docker/compose/issues/7171) so is not ConEmu nor Cmder issu, thank you so much for your help, appreciate it.
