### ISSUE TITLE
Setting for "paste-long-text-warning" gets disabled while editing

### ISSUE THREAD

**Issue by axxelG** [cmderdev/cmder#2253]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

Cmder version 191012

Windows 10 Enterprise 17763

### Description of the issue

The text field for the setting "Long text paste: avoid non-responsive console until paste finishes" is acting weird. If I remove all non-zero numbers, the field instantly gets disabled.

I wanted to change the value from 200 to 500. After removing the 2 the textbox was instantly deactivated. With first typing the 5 and after that removing the 2 it works.

![image](https://user-images.githubusercontent.com/10010543/72875850-7709b380-3cf5-11ea-9cff-8968d08d689d.png)

![CmderSetting](https://user-images.githubusercontent.com/10010543/72876511-f9df3e00-3cf6-11ea-9935-3a3945c30558.gif)

**Comment by daxgames** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem or have a question, please open an issue over at https://github.com/Maximus5/ConEmu

Thank you! :-)

**Comment by axxelG** [comment]
Sorry for bothering you. I just assumed that you are doing the UI for all settings.
In case somebody else is interested in this: https://github.com/Maximus5/ConEmu/issues/2058

**Comment by daxgames** [comment]
@axxelG No bother at all.
