### ISSUE TITLE
Minimize/Restore hotkey button not working

### ISSUE THREAD

**Issue by jamesfpate** [cmderdev/cmder#2255]
### Purpose of the issue
- [ x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

1.3.14

Windows 10 pro
### Description of the issue

I set minimize/restore hotkey to just shift+ctrl (with no keys) and now nothing happens when i click the button with three dots to change the binding, and it won't let me type in the empty box
![cmder issue](https://user-images.githubusercontent.com/6530936/73811671-158f1d80-47a8-11ea-90a1-b2caa128b1c9.gif)

.

**Comment by daxgames** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem or have a question, please open an issue over at https://github.com/Maximus5/ConEmu

Thank you! :-)
