### ISSUE TITLE
Start Minimized

### ISSUE THREAD

**Issue by q00u** [cmderdev/cmder#2256]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [X ] Feature request (request for new functionality)
- [ ] Question

### Version Information
1.3.14.982
Windows 10 Enterprise 1903

### Description of the issue
Trying to find a way to launch this minimized. I saw [this previous issue](https://github.com/cmderdev/cmder/issues/532#issuecomment-209477427) but the accepted solution seems to be .... **don't use Cmdr? Skip straight to ConEmu and just use that?** That can't be correct, can it?

ConEmu _does_ support launching minimized, which is what I want.
Cmdr does not, nor does it support calling ConEmu with /min

Another suggestion, Minimize on focus loss, won't work either, because I **don't want it to minimize on focus lost.** That is a completely separate thing. I only want it to _launch_ minimized, so I can have it silently launch on startup. I still want to be able to see the window while working in a different window.

Running it through `start /min ...` doesn't appear to work either. Well, a process _does_ launch, but it's not accessible. It's just running in the background and can't be seen or used. So that's out too.

It's not a dealbreaker. It's just a little frustrating.

**Comment by sidian123** [comment]
maybe, you can use my workaround , which work well, can silently launch on startup

see https://github.com/cmderdev/cmder/issues/532#issuecomment-584161122

**Comment by ArnaudKunzi** [comment]
I confirm that the workaround does work. Thanks to @sidian123 for making it more explicit:

https://github.com/cmderdev/cmder/issues/532#issuecomment-584161122

That said, it does feel more like a workaround rather than a feature...

**Comment by daxgames** [comment]
@q00u Run `cmder -- -min`.  Any arg on the other siode of `--` is passed directly to `conemu`

**Comment by brunomolteni** [comment]
I just found out you can also just edit the shortcut and add `/x -MinTSA` at the end
