### ISSUE TITLE
How to open current directory in vscode

### ISSUE THREAD

**Issue by geochronology** [cmderdev/cmder#2257]
I'm wondering whether it's possible to create an alias within Cmder that would allow me to open my active directory within vscode (or another IDE).

For example:
`C:\Users\me\projects\my-app`
`λ vscode`

would open a new vscode window with my-app as the root

### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

**Comment by ilya-edrets** [comment]
VS Code adds own installation directory to a PATH variable. So, you can just type:
`λ code .`
And the VS Code will appear with current folder as a root.
If you need an alias, you should add a new line into %CMDER_ROOT%\config\user_aliases.cmd
`vscode=code .`

**Comment by geochronology** [comment]
Brilliant! Thank you so much.
