### ISSUE TITLE
Missing output issue

### ISSUE THREAD

**Issue by tanruixiang** [cmderdev/cmder#2258]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

1.3.14

win10
### Description of the issue

When I open the cpp file in cmder using vim and compile and run, the output part of the io stream is missing, and only the input part is left. But when I run the just generated exe file directly in cmder, it can output normally.(vim is downloaded directly from the vim official website)

**Comment by daxgames** [comment]
I am not sure how this is a Cmder issue.  You are using vim from vim and even if you were using Cmder Vim it is a part of git for windows that Cmder repackages.  The terminal emulator is ConEmu.  Cmder is simply configuiration that ties all these components and more together.

My question is does the same happen outside Cmder using your Vim in a normal cmd.exe oin your chosen shell in ConEmu.?

**Comment by tanruixiang** [comment]
> I am not sure how this is a Cmder issue. You are using vim from vim and even if you were using Cmder Vim it is a part of git for windows that Cmder repackages. The terminal emulator is ConEmu. Cmder is simply configuiration that ties all these components and more together.
> 
> My question is does the same happen outside Cmder using your Vim in a normal cmd.exe oin your chosen shell in ConEmu.?

I'm sorry I haven't replied to you for so long. Because of some problems, I have been unable to access GitHub for nearly three weeks. My problem is that when I use vim test.cpp to open and run it in cmder, I can only input and cannot see the output, even cout<<"Hello world";

About your question,using vim in a normal cmd.exe is fine.

**Comment by daxgames** [comment]
My question had two parts: Does the same happen outside Cmder using your Vim in a normal cmd.exe or in your chosen shell in ConEmu?

**Comment by tanruixiang** [comment]
> My question had two parts: Does the same happen outside Cmder using your Vim in a normal cmd.exe or in your chosen shell in ConEmu?


Just using cmder ,this will  happen.Using vim hello.cpp both in cmd.exe and cmder and then run it in vim .The image shows what happen between cmd.exe and cmder.The cout<<"hello\n"; is missing.（Chinese means press any key to return）
![1](https://user-images.githubusercontent.com/34568378/76144740-3657d500-60be-11ea-98b7-ce4aeac32407.png)

**Comment by daxgames** [comment]
I am not asking about Cmder.  If download [Conemu](https://conemu.github.io/en/Downloads.html), expand and run it.  Does the same happen?

**Comment by tanruixiang** [comment]
> I am not asking about Cmder. If download [Conemu](https://conemu.github.io/en/Downloads.html), expand and run it. Does the same happen?


Conemu happens the same. Thank you for your patience.How can I solve this problem？

**Comment by daxgames** [comment]
See if a similar issue us reported at https://github.com/Maximus5/ConEmu/issues and if not report it there.
