### ISSUE TITLE
Arrow keys not working in python shell

### ISSUE THREAD

**Issue by XinliYu** [cmderdev/cmder#2260]
I use cmder + cygwin + python 3.7.5, all latest version.

The cygwin task is 

>set CHERE_INVOKING=1 & set "PATH=C:\cygwin64\bin;%PATH%" & %ConEmuBaseDirShort%\conemu-cyg-64.exe -new_console:p C:\cygwin64\bin\bash.exe --login -i -new_console:C:"C:\cygwin64\Cygwin.ico"

The arrow keys works in the terminal and vim, but not the Python or IPYTHON shell,

![image](https://user-images.githubusercontent.com/47457513/74621601-87058f00-510b-11ea-928e-8c4fbdcd6ec2.png)

The left key is mapped to 'OD', the right key is mapped to 'OC', up key mapped to 'OA', down key mapped to 'OB'.

The python shell in Cygwin's buildin terminal is OK.

**Comment by XinliYu** [comment]
Tried replacing `-new_console:p` by ` -new_console:p5` as suggested here https://github.com/cmderdev/cmder/issues/1832

Not working.

**Comment by daxgames** [comment]
If you use cmder + cygwin you are not using cmder.  You are using cygwin with conemu.

You should look at conemu issues and if nothing fits open an issue there.
