### ISSUE TITLE
Cmder hangs on git.exe

### ISSUE THREAD

**Issue by jfustier-it** [cmderdev/cmder#2261]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

ConEmu : 191012[64]{Preview}
Cmder: Latest Version: v1.3.14

Windows 10 Entreprise LTSC 1809

### Description of the issue

When I launch the application, the terminal hangs on git.exe (as administrator or not).
Sometimes when I reload the window, the terminal works but when I launch a git command it stays blocked.

![cmder_git_2](https://user-images.githubusercontent.com/56533201/74657724-23be4000-5191-11ea-9b0d-885ee5db3ea8.png)

![cmder_git_3](https://user-images.githubusercontent.com/56533201/74657745-2ae54e00-5191-11ea-9198-6acde5cd22e9.png)

**Comment by daxgames** [comment]
Output of `where git`?

**Comment by jfustier-it** [comment]
`C:\Program Files\Git\cmd\git.exe`
`C:\Program Files\Git\mingw64\bin\git.exe`

On my second screenshot.

**Comment by daxgames** [comment]
Is it possibly related to #2161

**Comment by jfustier-it** [comment]
Thanks!

Yes, This also happens with PowerShell but not using Git bash

**Comment by daxgames** [comment]
So can we close this issue?

**Comment by baiyujianyi** [comment]
i also met this problem, try to set git.exe to compatibility mode. it works in mine

**Comment by mapfel** [comment]
I face this issue since a longer time. What do you mean by "set git.exe to compatibility mode", @baiyujianyi? Thanks
