### ISSUE TITLE
Open new Tab "Run as administrator" default

### ISSUE THREAD

**Issue by StevenTCramer** [cmderdev/cmder#2262]
![image](https://user-images.githubusercontent.com/357219/74719018-d52ea580-5265-11ea-8d25-46a864a8a5e4.png)

Can we get the new tab dialog to have "Run as administrator"  checked by default?

My Task uses the "*" but it does NOT run as administrator unless I check the above, which I would like to just be default checked.

![image](https://user-images.githubusercontent.com/357219/74719128-0909cb00-5266-11ea-9045-0afa7d81668f.png)

**Comment by daxgames** [comment]
Any changes to the UI need to asked of the ConEmu developer.
