### ISSUE TITLE
Is it possible to custom external editor  to Notepad++ ?

### ISSUE THREAD

**Issue by lilixiong2018** [cmderdev/cmder#2264]
When I move mouse to text of file path , for example, I move  mouse to text " g:\workspace\cmd\mylist.txt" then hit ctrl-click, by default, it will use far.exe to open the linker(far.exe /e0:1 "G:\workspace\cmd\mylist.txt") .

Is it posssible to custom far.exe to Notepad++, and let it  jump to line 100, column 30 ?
Thank you. 

```
$cat g:\test\foo.txt  
g:\workspace\cmd\mylist.txt:100:30 
```

**Comment by daxgames** [comment]
I looked at the settings as I am sure you did and found nothing obvious.

This is more of a question for the developers of [Conemu](https://github.com/Maximus5/ConEmu/issues) since it is completely related to that project

**Comment by lilixiong2018** [comment]
Thank you.

I got the answer from https://conemu.github.io/en/Settings.html. 

![image](https://user-images.githubusercontent.com/40269098/78464110-ff55fd00-7717-11ea-99cf-3056da7e13e7.png)
