### ISSUE TITLE
VS Code stalls with cmder integrated 

### ISSUE THREAD

**Issue by JalinWang** [cmderdev/cmder#2266]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

Cmder version: 1.3.14.982
VSCode version: 1.42.1

Windows 10 Pro 1909
### Description of the issue

I met the same one as #2147 which is closed without solution. So I open a new issue here.
The integration with VSCode was done by following cmder's wiki [Seamless VS Code Integration](https://github.com/cmderdev/cmder/wiki/Seamless-VS-Code-Integration#vs-code-terminal) and I can provide two ways to reproduce:

--- 
**Approach One**
1. Start VSCode, which should come with an opened terminal(integrated cmder)
![image](https://user-images.githubusercontent.com/20621784/75442507-994cbc00-599a-11ea-94ab-f39983e3c580.png)
2. Open a new terminal:
![image](https://user-images.githubusercontent.com/20621784/75442622-db75fd80-599a-11ea-8cbb-508692a0413e.png)
3. ... then kill it
![image](https://user-images.githubusercontent.com/20621784/75442662-eb8ddd00-599a-11ea-9eee-fa32bf8d3254.png)
--- 
**Approach Two**
1. Same as the first step above.
2. Kill the existed terminal.
3. ... then open a new one by the menu or 'ctrl + shift + `'
![image](https://user-images.githubusercontent.com/20621784/75442844-39a2e080-599b-11ea-8b2c-22fa4386c01f.png)
--- 
Either of the two leads to a freezed VSCode and later VSCode will prompt:
![image](https://user-images.githubusercontent.com/20621784/75442937-6656f800-599b-11ea-9075-3a5550c3c610.png)

I tried  to find logs but failed, which makes me adrift.

**Comment by daxgames** [comment]
Don't kill the terminal type exit in the terminal.

**Comment by daxgames** [comment]
Visual Studio Code with Cmder is achieved by code.exe running the Cmder init script with its default settings that is normally run by a task in Conemu.  Integration is really a misnomer, it is actually a very loose coupling and the described side effect is a result of this.

If this happens when you kill the Cmder terminal in vscode as stated above there is nothing we can do to fix that. Something is going wrong with the way vscode is doing that.

Don't kill the terminal type `exit` in the terminal.

**Comment by PyGamer0** [comment]
Even for me it hangs.
Earlier I was using WSL in VSCode, and then I killed thee terminal; it always hanged no matter what i did.

I believe its a problem of VScode or the terminals i'm using.

Also before i used cmder, it did not hangs (unless a process was running)
