### ISSUE TITLE
`LANG` environment variable improperly set

### ISSUE THREAD

**Issue by lucatrv** [cmderdev/cmder#2268]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information
Cmder 1.3.14.982
ConEmu 19.10.12.0

Windows 7 64-bit

### Description of the issue
I use Italian language. If I start `cmd` the `LANG` environment variable is unset. If I start `Cmder`, the `LANG` environment variable is set to `IT`, which is not a valid locale. I was not able to find where it is set to `IT`, but I verified that it is before `init.bat` is run, so at line 245 it is not redefined.
If I comment lines 243 and 247 of `init.bat`, then `LANG` is properly set to `it_IT.UTF-8`. I would open a PR if I was able to find where `LANG` is set originally.

```batch
if defined git_locale (
  %lib_console% debug_output init.bat "Env Var - git_locale=%git_locale%"
REM  if not defined LANG (
      for /F "delims=" %%F in ('%git_locale% -uU 2') do (
          set "LANG=%%F"
      )
REM  )
)
```

**Comment by daxgames** [comment]
@lucatrv 

If you run `cmd.exe` what is the output of `set LANG`.

Maybe it is set improperly in your env because Cmder `init.bat` sees it is set to SOMETHING because your commented lines, that prevent resetting a preset value, bypass that protection and allow `init.bat` to set it properly.

**Comment by lucatrv** [comment]
Wow, this is really weird. That was the first thing that I checked, and it was unset. I checked again about 1 hour ago, and it was unset... but now it is set to `IT`. The only think I did was to upgrade Total Commander, because I noticed that `LANG` was unset if I run `cmd.exe` from the start menu, but it was set to `IT` if I run it from Total Commander (and I always run Cmder from Total Commander). But what drives me crazy is that now `LANG` is always set to `IT` even if I run `cmd.exe` from the start menu... As I said, I just updated Total Commander, but I also verified under Control Panel and `LANG` is not defined under System / Advanced Settings / Environment Variables, so I do not see how it could have set the `LANG` variable system-wide (if that was the case, I would open an issue on their forum).

Well, maybe it's only my issue? In this case I will fix it myself adding `set LANG=` in the `init.bat` script.

**Comment by daxgames** [comment]
@lucatrv It is best not to edit the init.bat.  you cN edd env settings in conemu gui.  That is a better place to do it so it will survive cmder upgrades.

**Comment by daxgames** [comment]
Add `LANG=it_IT.UTF-8` to the conemu gui.

**Comment by lucatrv** [comment]
OK, thanks.
