### ISSUE TITLE
Error taking screenshots

### ISSUE THREAD

**Issue by world33** [cmderdev/cmder#2269]
### Purpose of the issue
Error taking screenshots

### Version Information
1.3.14 (2020-01-08)
Windows 7

### Description of the issue
I am trying to use cmder to take screenshots in bulk of many urls.
I use the following command but no matter what url I try I get an error (in bold below):
-------------------------------------------------
λ ss  --sleep 3000 --path 'D:\screenshots2\' --name '18163-Corporacion-Universitaria-Autonoma-de-Narino' http://www.aunar.edu.co
• Launching chrome...
✔ Done.

• Loading http://www.aunar.edu.co...
• Sleeping for 3000ms...
• Taking screenshot of http://www.aunar.edu.co...
• **Error taking screenshot of http://www.aunar.edu.co. Skipping...**

✔ Done. Have a great day!
-------------------------------------------------

I used to be able to get screenshots in the past. Am I doing something wrong?
BTW I open cmder.exe as an Administrator.

**Comment by daxgames** [comment]
@world33 Was there a solution?

**Comment by world33** [comment]
I realised that probably it was not the right place a post for an issue that is more related to the script site-scan (used for screenshots) rather than cmder. The solution was to remove the option “location” in the script command string. So when I removed D://screenshots2/ it worked. Not sure why. Apologies for the inconvenience.
