### ISSUE TITLE
color scheme lost after CTRL+C on git status

### ISSUE THREAD

**Issue by Ortix92** [cmderdev/cmder#227]
I opened up a powershell, ran a `git status` with an immense amount of deleted files (red font). Then when CTRL+C is pressed, that red font color is used for everything and can't be reset unless the application is restarted. In other words, do a git status on a huge list of deleted files and press CTRL+C. The font color will be stuck

**Comment by Jackbennett** [comment]
I can't reproduce this anymore. Please open again if it persists.
