### ISSUE TITLE
how to really disable updates?

### ISSUE THREAD

**Issue by fireheart2008** [cmderdev/cmder#2270]
i keep unchecking the update option but i keep getting update notice!
and my 'color scheme' customizations are discarded and resetted to the blue background and asks for that start command

i have given cmder all integration options 

now i updated to the latest version but i am asking for instructions to disable update notice once and for all and prevent the change in color scheme. 

my usage of the app is simple and all those updates are useless to me. i only use it because it looks nice, better than microsoft's app

**Comment by daxgames** [comment]
If un-configuring auto uodates in conemu does not work I dont know what to tell you.  The update notifications come from conemu and are not for cmder itself.  Conemu is the terminal emulator and is a completely separate project from cmder.
