### ISSUE TITLE
Failed to load configuration file Cmder using Terminal in Laragon

### ISSUE THREAD

**Issue by abrhambas01** [cmderdev/cmder#2272]
When I click on terminal button in `Cmder`
---------------------------
ConEmu 161206 [64]
---------------------------
Failed to load configuration file!
F:\laragon_2\bin\cmder\vendor\conemu-maximus5\ConEmu.xml
Line=1, Pos=1, XmlCode=0xC00CE556, HR=0x00000000
Invalid at the top level of the document.
---------------------------
OK   
---------------------------

![image](https://user-images.githubusercontent.com/12043306/76163622-a6c82a00-6182-11ea-8119-a4593e5c4bcb.png)

**Comment by daxgames** [comment]
Looks like an error for an invalid conemu.xml file.  Was it edited directly?

**Comment by abrhambas01** [comment]
nope fr

**Comment by daxgames** [comment]
@abrhambas01 what was the process you followed to reinstall?

What version of cmder did you have before?

What version did you try to reinstall?

**Comment by abrhambas01** [comment]
it just worked. THanks

**Comment by daxgames** [comment]
Cool thanks.  Closing
