### ISSUE TITLE
Error when run cmder in Windows 7 32bits

### ISSUE THREAD

**Issue by lemquy** [cmderdev/cmder#2273]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Description of the issue

When i had ran cmder i saw this error
![image](https://user-images.githubusercontent.com/50269397/76193004-aaf15780-6215-11ea-9f63-c5eb983b9b15.png)
How to fix it???

**Comment by daxgames** [comment]
For a portable option:

1.  Download [32Bit Git for windows portable](https://github.com/git-for-windows/git/releases/download/v2.25.1.windows.1/PortableGit-2.25.1-32-bit.7z.exe).
2.  Backup `%cmder_root%\vendor\git-for-windows\etc\profile.d\cmder.sh`
3. Replace the `%cmder_root%\vendor\git-for-windows` folder contents with the 32Bit git for windows files.
4.  Restore `%cmder_root%\vendor\git-for-windows\etc\profile.d\cmder.sh` you backed up earlier.
5.  Run `cmder.exe`

For a non-portable version:

1.  Download and install [32Bit Git for windows](https://github.com/git-for-windows/git/releases/download/v2.25.1.windows.1/Git-2.25.1-32-bit.exe).
2.  Backup `%cmder_root%\vendor\git-for-windows\etc\profile.d\cmder.sh`
3. Download [Cmder Mini](https://github.com/cmderdev/cmder/releases/download/v1.3.14/cmder_mini.zip)
4. Expand it to your desired location.
5.  Copy the file you backed up earlier to `c:\program files\git\etc\profile.d\cmder.sh`
6.  Run `cmder.exe`
