### ISSUE TITLE
About the close button

### ISSUE THREAD

**Issue by juzi214032** [cmderdev/cmder#2275]
When I click the close button, cmder closes all the tabs in the TAB bar. I want to hit the close button and just minimize the window, not close the TAB. How should I set it?

**Comment by daxgames** [comment]
The GUI for Cmder is a separate project called Conemu.

I'm pretty sure you should expect the close button to do exactly what it is doing and instead use the minimize button to do what you want.

If you disagree and feel there are other options you could ask the Conemu [developer](https://github.com/conemu).
