### ISSUE TITLE
user_profile.cmd is loaded twice when starting cmder

### ISSUE THREAD

**Issue by thesobercoder** [cmderdev/cmder#2277]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information
Cmder: 1.3.14
ConEmu: 191012 preview [64]
OS: Windows 10 Enterprise 1809 (OS Build 17763.1039

### Description of the issue
`user_profile.cmd` is called twice when cmder is starting.

To prove this I included the `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\VsDevCmd.bat` in the `user_profile.cmd` file.

![image](https://user-images.githubusercontent.com/1915249/76217800-1993dc80-6239-11ea-959d-4906ca927e22.png)

Since the `VsDevCmd.bat` print a message when its called, as can be seen that printed the message twice.

![image](https://user-images.githubusercontent.com/1915249/76218073-8dce8000-6239-11ea-90b0-fe1962c53259.png)

**Comment by daxgames** [comment]
@thesobercoder this should be fixed in the latest master [build](https://ci.appveyor.com/project/MartiUK/cmder/build/artifacts).  Please respond here and let us know.

**Comment by thesobercoder** [comment]
@daxgames Yep it seems to be fixed in the latest master build. Thanks!
