### ISSUE TITLE
Open at folder vs Default Directory

### ISSUE THREAD

**Issue by chiming93** [cmderdev/cmder#2279]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [X] Question

### Version Information

![image](https://user-images.githubusercontent.com/54393280/76384951-5ed01f80-639b-11ea-9b87-f44267596814.png)

### Description of the issue

I setup the context menu to open cmder at the current folder according to 
https://github.com/cmderdev/cmder/wiki/Context-menu-integration

But I also have setup up the cmder startup default directory. 
![image](https://user-images.githubusercontent.com/54393280/76385080-bc646c00-639b-11ea-8ef5-299621ab6d0a.png)

The default directory causing the "open here" context menu to open cmder at the default directory.

What is the configuration needed for it to work as intended ?

**Comment by daxgames** [comment]
@chiming93 remove the default sirectory in the task.

If you want to have both you can create a shortcut to cmder.exe with a working directory set to your default directory.
