### ISSUE TITLE
libiconv-2.dll is missing

### ISSUE THREAD

**Issue by gabbsmo** [cmderdev/cmder#228]
Installed cmder.portable from Chocolatey which installs libiconv-2.dll to /vendor/msysgit/bin/. I get the following error when running cmder.bat:

> git.exe - System Error. 
> The Program can't start because libiconv-2.dll is missing from your computer. Try reinstalling the program to fix this problem.

I've tried reinstalling using `cinst cmder.portable -force` to no avail.

**Comment by Apetrail** [comment]
C:\Users\*username*\AppData\Local\GitHub\PortableGit_015aa71ef18c047ce8509ffb2f9e4bb0e3e73f13\cmd
