### ISSUE TITLE
Name tab on creation

### ISSUE THREAD

**Issue by gilles-crealp** [cmderdev/cmder#2280]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [ ] Question

It would be great to have a third text input in the "new console" window to be able to directly set the name of the new tab. So you don't have to create the new tab then right click on it and select "rename tab".

### Example
![Create new console](https://user-images.githubusercontent.com/29562925/76496647-c6d54300-6439-11ea-87b2-7d26a5c8e851.png)

**Comment by daxgames** [comment]
@gilles-crealp thanks for the feature request but you are asking for a feature in a component of Cmder that is a separate project that do kot maintain.  Checkout https://github.com/conemu and make the same request there.

**Comment by gilles-crealp** [comment]
Ho, OK, sorry. Didn't know that tabs was handled by ConEmu.
