### ISSUE TITLE
Unsupported 16 Bit Application Error

### ISSUE THREAD

**Issue by WarenGonzaga** [cmderdev/cmder#2282]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

CMDer 1.3.14 on Windows 10 Pro Build OS 18363.720

### Description of the issue

The issue is CMDer not able to run in my system it shows an error...

![image](https://user-images.githubusercontent.com/15052701/76857816-2f388000-6891-11ea-8a53-141caf521a8e.png)

**Comment by daxgames** [comment]
@WarenGonzaga 64Bit windows cannot run 16Bit apps.  This is not a cmder issue.

Why is there a 16Bit version of `Cmd.exe` in your path from the user folder? Malware?  This is not normal and highly suspect.

I suggest renaming and probably removing this file and trying again.

Cmder runs `cmd.exe` and it will use the first one it finds as defined by your `%path%` env variable.

**Comment by WarenGonzaga** [comment]
@daxgames good point will check it...

**Comment by WarenGonzaga** [comment]
@daxgames it works well now... thanks for the information...
