### ISSUE TITLE
Is there a way when opening a tab to fill a command?

### ISSUE THREAD

**Issue by Mioni** [cmderdev/cmder#2284]
Example when I open a new console it automatically fills in "youtube.com/" and then I just fill in the username and then press ENTER and he executes the command.

**Comment by daxgames** [comment]
I think [this](https://github.com/cmderdev/cmder#customizing-user-sessions-using-initbat-custom-arguments) will do what you want.

Add a Task called `Cmder - Youtube` with the below in `Commands` field:

```
cmd /k ""%ConEmuDir%\..\init.bat" /youtube"
```

Add the below to `%cmder_root%\config\user_profile.cmd`:

```
%ccall% "/youtube" "start" "https://youtube.com"
```

When you start the `Cmder - Youtube` Cmder will start a terminal and launch `https://youtube.com` in your default browser.

**Comment by daxgames** [comment]
@Mioni Sorry for the late response ^^^^

**Comment by Mioni** [comment]
Okay, thanks for helping me. o/
I have another question I use this program https://github.com/streamlink/streamlink is there a possibility to automatically fill a command in the program without being executed?

**Comment by daxgames** [comment]
@Mioni I don't understand the question about https://github.com/streamlink/streamlink.

You want the command on screen without being executed waiting for input and an [enter] key press?

If so nothing exists but could be written in a script file like:

Save the below as `%cmder_root%\bin\streamlnk.cmd`

```
@ECHO OFF

set URL=%~1

ECHO.
ECHO Type in any string and close by pressing Enter, F6 (or Ctrl+Z), Enter.
ECHO Only the last non-empty line will be remembered, leading spaces are ignored.
ECHO.
 
:: Only one single command line is needed to receive user input
FOR /F "tokens=*" %%A IN ('TYPE CON') DO SET INPUT=%%A
:: Use quotes if you want to display redirection characters as well

ECHO streamlink %URL% best %INPUT%
```

Add a Task called `Cmder - Streamlink Youtube` with the below in `Commands` field:

```
cmd /k ""%ConEmuDir%\..\init.bat" /slyt"
```

Add the below to `%cmder_root%\config\user_profile.cmd`:

```
%ccall% "/slyt" "streamlink.cmd" "https://youtube.com"
```

When you start the `Cmder - Streamlink Youtube` Cmder will start a terminal and launch `%cmder_root%\bin\streamlnk.cmd https://youtube.com` and wait for input.  You can then type input and pres `Ctrl+z`.

The script will then echo `streamlink %URL% best %INPUT%` to the screen.

To launch Streamlink instead change `echo` to `start` in the script.

hope this helps

**Comment by Mioni** [comment]
Thank you! 👍
