### ISSUE TITLE
Slow startup time

### ISSUE THREAD

**Issue by allenjzhang** [cmderdev/cmder#2285]
Downloaded the latest 1.3.14 mini version of Cmder. Unzip into a folder and ran first time to initialize. No other customization. 

After that, starting Cmder to cursor shows ready always takes ~9.5 seconds which is VERY long time. Do you know what could be the problem and how can that be speeded up? Thanks.

OS: Windows 10
Machine:  2020 Surface laptop 15

**Comment by daxgames** [comment]
I hate to sat this but if it is that slow it is something on your system.  We see this a lot on corporate systems with AV/Malware/DLP software installed.  you can try adding a `/f` after init.bat in the task you are launching with.  This disables parts of the initialization that you may never miss and can speed things up some.

My personal system starts Cmder with `/f` in under 2 seconds, without its `4.5` seconds.  On my corporate laptop the exact same version is double sometimes even triple those times to start.

**Comment by anthofo** [comment]
I have the same issue after updating to the latest version, startup is now very slow. I tried adding the /f and it works very well, almost back to initial fast startup time !

**Comment by daxgames** [comment]
@anthofo 1.3.14 init does a lot, based on user requests, that 1.3.2 did not hence it is slower.  `/f` strips most of that away and get you baxk closer to 1.3.2 so your results make sense.
