### ISSUE TITLE
Display error when typing commands with a long suggestion

### ISSUE THREAD

**Issue by GrayXu** [cmderdev/cmder#2286]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

Cmder v1.3.14, ConEmu 191012, Windows Subsystem Linux Ubuntu 16, zsh-autosuggestions

### Description of the issue

Display error when typing commands with a long suggestion.

A right display like this (Windows Terminal):
Type `wget`
![1](https://user-images.githubusercontent.com/20384421/77397810-40c5de80-6de1-11ea-9d68-a6f09fd8ffe6.jpg)

But on cmder, it shows like that with **character occlusion and cursor misplaced:**   
Type `wge` 
![2](https://user-images.githubusercontent.com/20384421/77397813-41f70b80-6de1-11ea-8eb1-ec55c90d3cf4.jpg)
Type `wged` 
![3](https://user-images.githubusercontent.com/20384421/77397801-3d325780-6de1-11ea-83a5-e3b201b06c51.jpg)
And even like this:
![TIM截图20200324151511](https://user-images.githubusercontent.com/20384421/77398334-47088a80-6de2-11ea-9797-cae6c575610c.jpg)

**Comment by daxgames** [comment]
@GrayXu Does this happen in Cmd running straight Conemu not Cmder?

**Comment by GrayXu** [comment]
> @GrayXu Does this happen in Cmd running straight Conemu not Cmder?

I just found this error only occured when using **wslbridge**. If I use powershell in cmder and use `wsl` command to get in WSL, everything works fine.
