### ISSUE TITLE
How to create alias for functions?

### ISSUE THREAD

**Issue by reypm** [cmderdev/cmder#2287]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Version Information
- Conemu 191012 preview x64

### Description of the issue
I have created a function that I would like to use from within cmder. The function looks like:
```bash
eol() {
  EOL="${1}"
  if [[ "${@}" =~ " --global " ]]; then
    GLOBAL="--global"
  fi
  if [[ "${EOL}" == "lf" ]]; then
    git config "${GLOBAL}" core.autocrlf false
    git config "${GLOBAL}" core.eol lf
    # Normalize Files In Repository
    git rm --cached -rf .
    git diff --cached --name-only -z | xargs -n 50 -0 git add -f
    # Normalize Files In Working Directory
    git ls-files -z | xargs -0 rm
    git checkout .
  fi
  if [[ "${EOL}" == "crlf" ]]; then
    git config "${GLOBAL}" core.autocrlf true
    git config "${GLOBAL}" core.eol crlf
    # Normalize Files In Repository
    git rm --cached -rf .
    git diff --cached --name-only -z | xargs -n 50 -0 git add -f
    # Normalize Files In Working Directory
    git ls-files -z | xargs -0 rm
    git checkout .
  fi
  if [[ "${EOL}" == "" ]] || [[ "${EOL}" == "--help" ]] || [[ "${EOL}" == "-h" ]]; then
    echo "Available Options Are As Follows: lf,crlf"
    echo "You May Also Define An Optional Flag: --global"
    echo "Specifying --global Will Make Changes Across All Repositories vs Just Working Directory"
  fi
}
```
The usage is simple as `eol lf --global`. I know how to create basic alias but I am not sure how to write something for the function to be usable from cmder. I could add the function to `.bash_profile` or `.bashrc` but not sure how to achieve this either, can I get some help?

**Comment by daxgames** [comment]
You can add it to any `*.sh` file in the `$CMDER_ROOT/config /profile.d` folder.  This will work for `bash` sessions in cmder but not `Cmder` sessions in Cmder.

`Cmder` sessions just do jot support complex function aliases like `bash` sessions do.
