### ISSUE TITLE
Fullscreen window sits behind Windows Taskbar.

### ISSUE THREAD

**Issue by asandhu3** [cmderdev/cmder#2288]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

Cmder: 1.3.14.982
ConEmu: 191012

Windows 10 Pro - 2004 19041.153

### Description of the issue

A fullscreen window of cmder sits behind the Windows taskbar. Clicking the Windows taskbar then clicking into Cmder brings cmder above the taskbar, however using the restore hotkey places it behind again. "Always on top" is enabled.

![image](https://user-images.githubusercontent.com/14942829/77680098-17c85980-6f59-11ea-8f5a-2cdedc400d08.png)

**Comment by daxgames** [comment]
Hey there,

Cmder uses ConEmu as terminal emulator and GUI, if you are experiencing a problem or have a question, please open an issue over at https://github.com/Maximus5/ConEmu

Thank you! :-)
