### ISSUE TITLE
Exiting from vim clears screen in cmder.

### ISSUE THREAD

**Issue by kodlekereanup** [cmderdev/cmder#2289]
So I'm running a Windows 10 system. 
Say I'm on the cmder screen. And I have a bunch of commands above me. 
I open a file, vim <filename>.cpp and enter vim and do my business as usual.
After saving the file and quitting, one would expect to get back to the screen having all those command histories. However, I am not able to get that. Somehow it clears the screen everytime I leave vim.

Although I can cycle though the commands using ArrowUp and ArrowDown keys, I'd like to see the whole history. 

I've researched quite a bit, and came across many people with the same issue. However many of them are either on Mac or Linux.

**Comment by daxgames** [comment]
Sounds like a vim thing then sinc cmder does not run on mac or linux.

**Comment by kodlekereanup** [comment]
Well it works fine when I use it with cmd. Only cmder(possibly the error is somwhere in ConEmu) gives me this. So I don't think it's vim.

**Comment by daxgames** [comment]
You could try it from conemu running pure cmd.exe.

**Comment by daxgames** [comment]
@kodlekereanup Exiting vim does not clear my screen as you have stated.  I am not seeing the issue,

**Comment by dseals3** [comment]
I have the same problem and just posted an issue on it like 2 minutes ago. It's very annoying

**Comment by kodlekereanup** [comment]
Yea it's not fixed. cmd works fine as mentioned before.

**Comment by daxgames** [comment]
@dseals3 @kodlekereanup I just did the following:

1. Start `Cmder`.
2. Run several shell commands.
3. Run `vim` and edited a file.
4. Exited `vim`.
5. All screen history remained on the screen.
6. Run `ssh [host]` and login
7. Run several shell commands.
8. Run `vim` and edited a file.
9. Exited `vim`.
10. All screen history from local and ssh session remained on the screen.
11. Exited `ssh`.
12. All screen history from local and ssh session remained on the screen.

As I said I can't reproduce it.

**Comment by daxgames** [comment]
Duplicate #2297

**Comment by daxgames** [comment]
@dseals3 @kodlekereanup Did either of you try running it from pure Comemu as asked?

**Comment by daxgames** [comment]
Did either of you try this: https://vi.stackexchange.com/questions/432/prevent-vim-from-clearing-the-terminal-after-exit

**Comment by daxgames** [comment]
you could add `set t_te=` to your `~/.vimrc` and it will be set each time you run vim.

**Comment by rakib-hasan** [comment]
Hi. I have the same issue as well. Happens during ssh session to Ubuntu 16.04 from Windows 10. Doesn't happen with either cmd.exe or the powershell, only cmder. 
As for "set t_te=", I tried it and it leaves the last view (the content) of the file on the console, which is not really what I want. I just want to go back the terminal texts that were shown before opening the file.
@daxgames what did you mean by "You could try it from conemu running pure cmd.exe."? Sorry, I am new to cmder and not familiar with conemu.

**Comment by waynezhangw** [comment]
Add ```export TERM=xterm-256color``` to your .zshrc and source it might solve the problem.
This inspired me [https://stackoverflow.com/questions/56502261/keep-conemu-screen-buffer-after-exiting-vim](url)

**Comment by phnsh** [comment]
I am having the same issue on Windows 10. I connect to my VM, edit a file in Vim, then after I quit Vim, it clears the screen and I lose context.

**Comment by chrisant996** [comment]
This normal vim behavior, as described in the linked articles. Consider reading the articles and applying one of the solutions from them. This is a vim issue, not a Cmder issue.
