### ISSUE TITLE
Hyperlinks don't wrap

### ISSUE THREAD

**Issue by sc0tt** [cmderdev/cmder#229]
Holding control and hovering over a URL makes it clickable, but for URLS that span more than one row, the hyperlink doesn't wrap.

![image](https://cloud.githubusercontent.com/assets/915870/3935657/f62c9406-2497-11e4-9f32-0d9bb095c2a7.png)
You can see the underline on the URL doesn't continue to the next line.

I just pasted it into a shell as an example, so ignore the errors about unknown commands.

**Comment by Jackbennett** [comment]
Just tested with a 1.3.2 release and even though the underline doesn't show up the correct link does wrap and does click correctly if only from the top line.

**Comment by nemo-nullius** [comment]
But the problem still exists in my case with the 1.3.2 release. 

![cmder_went_wrong](https://cloud.githubusercontent.com/assets/17632396/24850126/5e8f9240-1e01-11e7-8bcc-1a6dae00b444.png)

You can see that the browser (Chrome) just opens the URL in the first line from "https" to "is" without "sues" in the second line, and thus gives a 404 page.
