### ISSUE TITLE
Use canonical names like `x86`, `x64` for `architecture`

### ISSUE THREAD

**Issue by vatsan-madhavan** [cmderdev/cmder#2290]
I'm a long time Cmder user and for idiosyncratic reasons I've historically run the 32-bit version of cmd.exe, so I didn't encounter this problem until just now. 

I was building [dotnet/wpf](https://github.com/dotnet/wpf) just now and noticed that it had trouble building correctly. 

I debugged it down to [these lines](https://github.com/dotnet/wpf/blob/878a6b748b66c6dc464dd50753fff5e5a2e6acdb/eng/WpfArcadeSdk/tools/Wpf.Cpp.props#L19-L21) that fail to initialize the MSBuild property `$(Architecture)` correctly (it's initialized to `64` instead of `x64`), which in turn lead to my (dev) build failures in **dotnet/wpf**.

```xml
    <Architecture Condition="'$(Platform)'=='x64' or '$(Platform)'=='x86' or '$(Platform)'=='arm' or '$(Platform)'=='arm64'">$(Platform)</Architecture>
    <Architecture Condition="'$(Platform)'=='Win32'">x86</Architecture>
    <Architecture Condition="'$(Architecture)'==''">x64</Architecture>
```

Ultimately, this seems to the what caused my troubles, where `%architecture%` is (seemingly) set for _script-local_ use, but the environment-variable ultimately leaks out of the script: 

https://github.com/cmderdev/cmder/blob/1071221468f2f75f2b63e482deab69c9ca986219/vendor/init.bat#L125-L132

I have two suggestions: 

- Use `setlocal` at the top of the batch file wherever it makes sense. I realize that the 'fix' may not be as simple as adding a one-line change, since some env-vars might be exported deliberately, whereas others might be leaking merely as a side-effect. 
- Consider using (more) canonical names like `x86`, `x64`, `arm`, `arm64` etc. for `architecture` (instead of `86`, `64` etc. ).

**Comment by daxgames** [comment]
@vatsan-madhavan  try this https://ci.appveyor.com/project/MartiUK/cmder/build/artifacts

**Comment by vatsan-madhavan** [comment]
Thanks for handling this quickly!

**Comment by vatsan-madhavan** [comment]
Tested - works well. 

Feel free to close - I'll look for this in the next alpha update. 

![image](https://user-images.githubusercontent.com/20246435/78589076-7e206800-77f4-11ea-9a65-acaa4b35455d.png)
