### ISSUE TITLE
ABD Push Failure in Bash Script

### ISSUE THREAD

**Issue by sethurv** [cmderdev/cmder#2292]
### Description of the issue

I have a similar problem as reported in [#1121](https://github.com/cmderdev/cmder/issues/1121). However the suggestion of converting the bash script to bat will not work, as there are dependencies in the script which can't be converted to bat file.

Please share the reason for `adb push` failure in bash script whereas the same can be achieved through `Cmder` terminal.

The `/sdcard/` reference seems attached to `Git for Windows`. Does this can be changed?

### Version Information

1.3.12.915

**Comment by daxgames** [comment]
@sethurv Can you paste the bash script here?

**Comment by sethurv** [comment]
When the same command is executed in `Cmder` terminal. I don't see an issue.

    adb push --sync -p "$FILE" '/sdcard/' 2>&1

**Comment by daxgames** [comment]
This works: 

```
dtgam@DTG-WS ~/cmder - development (1.3.15)
λ bin/adb/adb push --sync -p "C:\\Users\\dtgam\\working_issues.txt" "//sdcard" 2>&1
C:\Users\dtgam\working_issues.txt: 1 file pushed, 0 skipped. 0.2 MB/s (1803 bytes in 0.011s)
```

**Comment by daxgames** [comment]
and it even works from a shell script.
