### ISSUE TITLE
Init.bat fails

### ISSUE THREAD

**Issue by KeltarHelviett** [cmderdev/cmder#2295]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information
1.13.4

### Description of the issue
Decided to upgrade cmder to a newer version and get this:

`\\cmder\\vendor\\git-for-windows\\cmd was unexpected at this time`

Added git to path and GIT_INSTALL_ROOT in order to continue working but clink doesn't autocomplete branches after git verbs (e.g. `git push origin blabla<tab>` do nothing)

**Comment by KeltarHelviett** [comment]
Works on 1.13.2 btw.

**Comment by daxgames** [comment]
@KeltarHelviett Try the latest master branch build.

**Comment by daxgames** [comment]
@KeltarHelviett ???

**Comment by daxgames** [comment]
Should be fixed in [this](https://ci.appveyor.com/project/MartiUK/cmder/build/artifacts)
