### ISSUE TITLE
Feature: Same as zsh-autosuggestions

### ISSUE THREAD

**Issue by Daniel-Mendes** [cmderdev/cmder#2298]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [x] Question

### Version Information

- Cmder 1.3.14.982

- Windows 10 Home 2004

### Description of the issue

Is there a plugin to add auto-suggestions like [zsh-autosuggestions](https://github.com/zsh-users/zsh-autosuggestions). I know there is a tab-completion but I really want the auto-suggestion to be displayed.

**Screenshot** (Ubuntu WSL with Oh my ZSH with plugin zsh-autosuggestions) :
![image](https://user-images.githubusercontent.com/28825568/79635255-37295f80-8170-11ea-9aba-496cce9fab53.png)

**Comment by garbinmarcelo** [comment]
any news?

**Comment by daxgames** [comment]
Zsh running on ubuntu/wsl is a MUCH more capable shell than Cmd.exe.  Probably not going to change much to get you there.

**Comment by garbinmarcelo** [comment]
> Zsh running on ubuntu/wsl is a MUCH more capable shell than Cmd.exe. Probably not going to change much to get you there.

Yes, I used it and found it really fantastic.

However I tried to use docker with WSL2 (I thought it would be wonderful), but the slowness made me retreat strongly to the Hyper-v.

Example: A request that takes 200ms in Hyper-v in WSL2 ended up passing 6500ms. In short, it is impossible to work that way.

So I'm back to Cmder which always served me well, but these features (plugins) that zsh has are fantastic.

**Comment by kamenminkov** [comment]
For anyone coming here late, this has been possible for some time already; it's not a feature of cmder but a feature of clink. To enable it, execute `clink set autosuggest.enable true`, and you'll have similar functionality everywhere you're using clink-injected cmd.

**Comment by HeyItsJono** [comment]
@kamenminkov That's giving me `ERROR: Setting 'autosuggest.enable' not found.`  in the version of clink bundled with the latest Cmder (Clink v1.2.46.69fc92 chrisant996 fork).

**Comment by chrisant996** [comment]
Use the pre-release Cmder, or update Clink by extracting the latest Clink .zip release into the `vendor\clink` directory under Cmder.

**Comment by HeyItsJono** [comment]
Oh hey thank you for the reply and for the excellent software. I can't seem to find a pre-release of Cmder, I've looked on the site and on the GH releases page, I might be missing something though. Would manually updating the vendored clink break anything out of the box between 1.2.4 and 1.3.17?

**Comment by chrisant996** [comment]
> Oh hey thank you for the reply and for the excellent software. I can't seem to find a pre-release of Cmder, I've looked on the site and on the GH releases page, I might be missing something though. 

I don't know if pre-release builds are easily findable.  But for example, right now if you click Issues and then click the first issue (2700), about halfway down the page is a link to a pre-release build.  Several other issues have links to pre-release builds as well.  But I would recommend updating Clink.

> Would manually updating the vendored clink break anything out of the box between 1.2.4 and 1.3.17?

It shouldn't break anything.  (I'm the author of Clink.)

**Comment by HeyItsJono** [comment]
Amazing, thanks for your help. Updating definitely worked, and nothing is obviously broken out of the box.

**Comment by daxgames** [comment]
Pre-release builds are found by clicking the `Buils Passing ` button on the Cmder main Github Repo page below:

<img width="243" alt="image" src="https://user-images.githubusercontent.com/7318053/170048945-f4ba853c-34e7-4b5e-8c21-cbf3a9a83544.png">

Then `Artifacts` in `AppVeyor`:

<img width="353" alt="image" src="https://user-images.githubusercontent.com/7318053/170049277-fc53c9dd-1626-4698-a9cd-73c3266e3f72.png">

**Comment by kamenminkov** [comment]
> @kamenminkov That's giving me ERROR: Setting 'autosuggest.enable' not found. in the version of clink bundled with the latest Cmder (Clink v1.2.46.69fc92 chrisant996 fork).

I'm using `1.3.17.0a95d0` installed through Scoop (that's my preferred method for getting Clink and a lot of other stuff).
