### ISSUE TITLE
how to set the interval between files' path i dragged in.

### ISSUE THREAD

**Issue by alexzms** [cmderdev/cmder#2300]
how to set the interval between files' path i drag in, like i draged test1.txt and test2.txt now it shows "C:\test1.txt C:\test2.txt", but i want it to be "C:\test1.txt?C:\test2.txt". is there a way to do so?

**Comment by daxgames** [comment]
This is not a cmder issue.  I doubt what you ask is possible but you could ask the Conemu developer.  Conemu is the GUI/terminal emulator Cmder uses.
