### ISSUE TITLE
IntelliJ integration

### ISSUE THREAD

**Issue by entuzjasci** [cmderdev/cmder#2301]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Version Information
ConEmu 191012 [64]
Cmder 1.3.14.982
Windows 10.0.18362

### Description of the issue
I may be stupid, but there's something I'm not able to have working and am unable to find a solution in the web and among this repo's issues...
I've got Cmder configured with ZSH started as 'startup task' with this command (in the task):
`C:\soft\cygwin64\bin\mintty.exe /usr/bin/zsh --login -i -new_console:d:%USERPROFILE%`.

If I start `cmder.exe` it works as expected.
But when I try to use this configuration in IntelliJ by pointing 'Terminal' setting to `C:\soft\cmder\cmder_shell.bat` it does not load the startup task, and so I only see a lambda symbol, without any configuration made for ZSH.
The contents of `cmder_shell.bat` are:
```
@echo off

set CMDER_ROOT=c:\soft\cmder\
set USERPROFILE=c:\soft\cygwin64\home\Piotr\
@cmd.exe /k %CMDER_ROOT%\vendor\init.bat
```

I would greatly appreciate someone's help.
And of course I'd like to thank you for your awesome work on this project!

Piotr

**Comment by daxgames** [comment]
@entuzjasci if you are using zsh you are not using cmder.  You are using Conemu to launch zsh.

`Init.bat` is `Cmder`.  It is a shell init script that ties several products together along with some config that provides the cmder shell.  It is what `Conemu` launches to run `Cmder`.

I guess you could try to replace the contents of `cmder_shell.bat` with `[drive]:\\[folder_path]\\zsh --login -i`.  Maybe it will get you what you want.

This is not a cmder issue so I am closing.

**Comment by stephenasamoah** [comment]
@strugman, did you find a fix for this? I faced this exact same issue today after I noticed WSL was too slow when running files out of its VM.
