### ISSUE TITLE
Cmder ends up in a weird place after changing drive letter

### ISSUE THREAD

**Issue by JasonCostanza** [cmderdev/cmder#2302]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Version Information

191012
Win10 1909 18363.778

### Description of the issue
I have figured out how to set the default directory for Cmder when it launches, but when I change drive letter it goes into some random directory and i'm not sure how to fix that.
Default: D:\
when I changed to E:\ by entering "E:" into Cmder, it changes to E:\Program Files\Git\cmd. I have no idea where it's gotten this directory from, I don't see it anywhere in the settings but might be looking in the wrong place.

I would like it to change to just E:\ when I change drive.

Thanks!
![image](https://user-images.githubusercontent.com/30665880/80023166-fdb76380-8491-11ea-9e20-3dfb1365bc1c.png)

**Comment by daxgames** [comment]
Not sure why that happens.  Cmder does search for externally installed git versions and this could be an artifact of where that search ended on the `c:`.   Maybe a bug to be fixed.

I assume you are expecting `c:` to take you to `c:\`

You could do `cd /d c:\` as a work around.

**Comment by JasonCostanza** [comment]
Yeah i think that is my expectation. It seems to store the location on each drive letter correct so if I back up to E:\program files, then switch back to D and again to E, it will resume at E:\Program Files

I will try that workaround
