### ISSUE TITLE
Cannot enable 256 colors, vim behaving strangely with termguicolors

### ISSUE THREAD

**Issue by r-janik** [cmderdev/cmder#2303]
Hi all,

I cannot for the life of me figure out how to turn on the 256 color support in cmder. I have all the settings correct according to the links and documentation I found (trust me I dug a lot), and the in-terminal vim changes the background colours when moving the cursor in any direction. I have dug through everything I could lay my eyes / hands on and cannot figure it out. Any output of anything you require to help me diagnose it - just say the words.
Any assistance?

Thanks

**Comment by daxgames** [comment]
@r-janik I assume you are talking about the Conemu documentation [here](https://conemu.github.io/en/Xterm256Colors.html)

I've never been able to make it work either.  I gave up.

**Comment by r-janik** [comment]
@daxgames exactly, so simple yet so hard for no apparent reason

**Comment by r-janik** [comment]
Is the project dead, or just no answer to this particular question?

**Comment by daxgames** [comment]
What project?  Cmder is alive, so is Conemu.  What you are asking for is a feature of Conemu so this is not the place to really ask the question.
