### ISSUE TITLE
keep focus on prompt

### ISSUE THREAD

**Issue by zsbolyoczki** [cmderdev/cmder#2304]
Hi,

I don't know if this is a bug or a feature but when I use left mouse button to select some text on the screen, the prompt loses focus and I have to press any key to return to the prompt before I can start typing again. (It's like the cursor moves to the selection from the prompt.)

Expected behaviour is like in wsltty (text is selected, focus returns immediately to the prompt)

Also other hotkeys don't work right after text selection, like "switch next/previous console". In this case the size of the selected area is changed.

This is very uncomfortable and an obstacle for doing productive terminal work.

**Comment by daxgames** [comment]
Check `Setup Tasks -> keys & Macros -> Mark/Copy -> reset Selection on Left Button Release`.  I think that will do what you want.

**Comment by daxgames** [comment]
@zsbolyoczki  ^^^^^
