### ISSUE TITLE
Setting the WSL home directory as default when using Cmder through Hyper.js

### ISSUE THREAD

**Issue by epitone** [cmderdev/cmder#2305]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Version Information
Cmdr Version `1.3.14.982`
ConEmu Version `191012`

### Description of the issue
I've been following [this guide](https://github.com/cmderdev/cmder/wiki/Seamless-Hyper-integration) and everything works just fine _except_ I'd like to start my Hyperjs terminal at the WSL home folder instead of my regular old `Users/<name>` folder - I'm not sure if this is the place I should be asking about this but I figured since the guide was here, it'd be as good a spot as any. I imagine there's something I'd need to change in my hyperjs shellArgs config (which I've included [here](https://gist.github.com/epitone/f709a81acab05fa05087bc3035b908ee)) but I'm not too versed on bash and the shell arguments and couldn't figure it out after an hour or so of searching.

**Comment by daxgames** [comment]
@epitone you are not using WSL and the bash you are launching uses `%userprofile%` as `%HOME%`.

**Comment by epitone** [comment]
@daxgames I see - so aside from changing the shell to use `wsl.exe` is the only solution? Or is there something else I'm missing?

**Comment by daxgames** [comment]
@epitone I don't know.  I have never used Hyper.  Playing with it now to see if I can get it to do what you ask.  FWIW I tried to use your `hyper.js` and hyper failed to launch.

**Comment by daxgames** [comment]
@epitone I set the below in `.hyper.js`:

 ```
shell: 'wsl.exe',
```

Add at the end of `~/.bashrc`.

```
if [ -t 1 ]; then
  cd $HOME
fi
```

Now when I launch Hyper I am in the `$HOME` Folder for `WSL`.
