### ISSUE TITLE
Starting ssh-agent done but still asking for password

### ISSUE THREAD

**Issue by grodriguez88** [cmderdev/cmder#2306]
Hi, I've a problem when I start a cmder console I've this message:
```
Starting ssh-agent:  done
Enter passphrase for /c/Users/XXXX/.ssh/id_rsa:
Identity added: /c/Users/XXXX/.ssh/id_rsa (/c/Users/XXXX/.ssh/id_rsa)
```
But after when I tried to ssh XXXX it ask me for the password.

I've this line on user_profile.cmd:
` call "%GIT_INSTALL_ROOT%/cmd/start-ssh-agent.cmd" /k exit`

Thanks in advance

**Comment by daxgames** [comment]
@grodriguez88 Your ssh key was built requiring a passphrase.  Rebuild it without one and the problem will go away.

**Comment by kkthxbye-code** [comment]
@daxgames  - ssh-agent works fine with passphrases, it's pretty much the entire point of ssh-agent.

@grodriguez88 - Check if the windows optional feature "OpenSSH Client" is installed. Go to apps and features -> optional features and check for it. If it is installed the folder "C:\Windows\System32\OpenSSH" is added to the system path and takes precedence over the included git-for-windows ssh-agent, which breaks the feature. Removing the path from the system environment solved the issue for me.

I realize you probably solved it or moved on, but others might find the issue.
