### ISSUE TITLE
how can I use z inside cmder

### ISSUE THREAD

**Issue by AbhimanyuAryan** [cmderdev/cmder#2307]
`cd` command is very time consuming so I use https://github.com/rupa/z to jump directories based on history. How can I use this in Cmder? 

I'm using this in mac as well as powershell(windows). I'm new to Cmder

**Comment by daxgames** [comment]
`z.sh` is a shell script so it will not work in the default cmder shell but you could use it in cmder with the Cmder `bash::bash` shell.

**Comment by daxgames** [comment]
How are you using this in powershell?

**Comment by AbhimanyuAryan** [comment]
@daxgames this version is written for powershell https://github.com/vincpa/z

**Comment by daxgames** [comment]
@AbhimanyuAryan you download these and put them in `%cmder_root%\bin` and you could use the in `bash` and `powershell` sessions.  If you could find a version for `cmd.exe` the same would work.

**Comment by AbhimanyuAryan** [comment]
I didn't get you. You mean just clone https://github.com/vincpa/z inside `%cmder_root%\bin` and it would work magically in cmder after new session? Or I'll need some configuration?
