### ISSUE TITLE
New to cmder. Would like to create Windows shortcut that run a few commands on startup.

### ISSUE THREAD

**Issue by JayGameHive** [cmderdev/cmder#2309]
I would like to be able to double click a windows shortcut and bring up cmder but with two commands already run. This is what I did so far.

- I created a windows shortcut and right-clicked it and went to **properties > Target** and added **"C:\cmder\Cmder.exe /TASK mytask"**

- I opened cmder and went to **Settings > StartUp > Tasks**. Made a new task myTask with the following commands

```
cd C:\Users\userName\DirectoryIWantToStartIn
C:\Users\Janimator0\Anaconda3\Scripts\activate.bat C:\Users\Janimator0\Anaconda3\envs\myEnv
```
unfortunately this did not work is there another solution?

The error i get is
`ConEmuC: Root process was alive less than 10 sec, ExitCode=0.`

**Comment by daxgames** [comment]
@Janimator0_twitter you are not using Cmder. You are using Cmder.exe to launch Conemu.exe to run a custom Task.

Is this setup something you want to run on every start of cmder or just sometimes based on launching with a specific shortcut?

See #2284 and look at how `%ccall%` is used

**Comment by JayGameHive** [comment]
Just sometimes I would like these commands to run. If I'm working using Anaconda I would love to avoid typing those commands every time I open the terminal. When I'm not using Anaconda I'm good with just the default terminal opening up without any commands.

**Comment by JayGameHive** [comment]
So I just learned about Macros. My solution is to just make a macro that does my desired function and assign it to a hotkey. 

**Settings** > **Keys & Macro** > **Macros** (DropDown) > Select a **Not Set Macro** > in **GUI Macro** 
`print("cd C:\\Users\\userName\\DirectoryIWantToStartIn \nC:\\Users\\Janimator0\\Anaconda3\\Scripts\\activate.bat C:\\Users\\Janimator0\\Anaconda3\\envs\\myEnv")
`

**Comment by JayGameHive** [comment]
Going to close this issue since this is a viable solution for me
