### ISSUE TITLE
Version for Windows ARM or 32bit

### ISSUE THREAD

**Issue by Ivan8R** [cmderdev/cmder#2312]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Version Information

my current version 1.3.4

Windows 10 on ARM SQ1
### Description of the issue

Do you have plans to make another version of cmder?  Because the last version in 32bit was 1.3.4.
Thank you.

**Comment by daxgames** [comment]
No and but if you need 32 bit it is easy to do if you want to do it yourself.  

See: https://github.com/cmderdev/cmder/issues/1699#issuecomment-623407002

**Comment by DRSDavidSoft** [comment]
@jesseleite Pinging you to check, do you still use Windows 11 on ARM? We're tracking ARM support on #2633 for the next major release
