### ISSUE TITLE
How can I create a PowerShell console with conda base environment activated?

### ISSUE THREAD

**Issue by BiggerHao** [cmderdev/cmder#2313]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [X] Question

### Version Information

Cmder: 1.3.13.967
ConEmu: 191012 preview
Windows 10

### Description of the issue

I want to create a task to open a new PowerShell console with the base conda environment activated. I am not familiar with PowerShell script syntax and I couldn't find relevant issues. I tried some; for example, I added the following commands to the end of `user_profile.ps1`
```
C:\ProgramData\Anaconda3\shell\condabin\conda-hook.ps1
conda activate C:\ProgramData\Anaconda3
```
but this would make the prompt become "(base) PS D:\Software\cmder>" and it's colorless. Other part of the console is fine and correctly colored. I want the color of the prompt back and I want to remove the redundant "PS". What should I do?

Also, in this way, all newly-created PowerShell consoles will have conda activated since I modified `user_profile.ps1`. How can I let only one task to activate conda while other tasks remain intact. Thank you!

**Comment by daxgames** [comment]
I don't use this, haven't even looked at what it is but I would write a small script that contains the bits to activate 'conda' and just call it from '$env:cmder_root\bin\activate_conda.ps1' when I wanted to use it from a Cmder Powershell session.
