### ISSUE TITLE
Feature request: support custom delimiters for mouse text selection

### ISSUE THREAD

**Issue by m4rkw** [cmderdev/cmder#2316]
When I click on text to select it in cmder it selects more than I would like. I'd therefore like to be able to configure either custom word boundaries or characters to be considered part of a word, in the latter case it should then only select a word.

iTerm has this feature, the default is that these characters are considered part of a word: /-+\~_.

**Comment by daxgames** [comment]
Cmder uses Conemu as it's terminal emulator.  This is a feature request better asked for there.
