### ISSUE TITLE
Program takes a good 5 seconds to load

### ISSUE THREAD

**Issue by dhsdshdhk** [cmderdev/cmder#2317]
When I either open cmder or a new console dialog, it will pop up instantly, but will take about 5 seconds for the cursor to show up, allowing me to type.

Am I the only one?
Running on Windows 10, on an SSD.

**Comment by daxgames** [comment]
4-5 secs is normal.  You can speed it up with `init.bat -f` note this reduces functionality slightly.

**Comment by dhsdshdhk** [comment]
That's insane. Linux terminals are instant.

**Comment by daxgames** [comment]
It's not a Linux terminal.  It's an MS Cmd.exe plus additional tools and configuration trying to mimic a Linux terminal in addition to being a portable env and that takes time.

If you want faster try the `-f` as recommended or try `bash::bash` for an even more Linux like env or even run WSL which is a Linux env on Windows.
