### ISSUE TITLE
Open from keyboard

### ISSUE THREAD

**Issue by ahmadmustafaanis** [cmderdev/cmder#2322]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [x] Question

### Description of the issue

Just like we open terminal in ubuntu by `win + alt + t`, is there any shortcut key to open cmder?

**Comment by daxgames** [comment]
This is not a feature of cmder or Ubuntu on Windows.  It is a feature of windows.  A hotkey can be added to any app shortcut.  First create a shortcut to Cmder.exe then access the properties ansd add a hotkey
