### ISSUE TITLE
Graphical issue with powerline + cmder

### ISSUE THREAD

**Issue by BothymanRoyne** [cmderdev/cmder#2324]
Firstly, I'll admit that I don't know if this issue pertains to cmder, conemu, powerline, or a combination of the 3. I hope somebody can point me in the right direction because this is some amazing software and I'd like to continue using it.

Currently, I use cmder to ssh into my webserver, and I have powerline installed on that box. If I ssh using cygwin, powerline displays perfectly: 

![image](https://user-images.githubusercontent.com/17679795/83378387-d065ab80-a395-11ea-9ef3-d9e6ee9af068.png)

but if I ssh in through cmder, my prompt looks like this:

![image](https://user-images.githubusercontent.com/17679795/83378430-ea9f8980-a395-11ea-8d3d-916c0dc1fcf0.png)

Note the arrow glyph's background being uncolored. Can anyone provide guidance as to what might cause this?

**Comment by daxgames** [comment]
Cmder uses Conemu as it's terminal emulator so Conemu is responsible for all things display.

What happens if you add [Cygwin to Cmder/Conemu](https://github.com/cmderdev/cmder/wiki/Integrating-Cygwin) tasks and launch it from there?  I am guessing the same will happen because it's the font being used by Conemu.

**Comment by Dumbassahedratron** [comment]
I've tried what you suggested and the effect remains the same. Should I open an issue on Conemu? Thanks for the guidance.

**Comment by daxgames** [comment]
Did you try different fonts?

**Comment by Dumbassahedratron** [comment]
Yep, that was the first thing I tried. Have tried every font in the list,
all results in the same.
