### ISSUE TITLE
coc.nvim drop down menu is invisible in Cmder

### ISSUE THREAD

**Issue by wardinh0** [cmderdev/cmder#2325]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ X] Question

### Version Information

Cmder: 1.3.14
ConEmu: 200604 alpha

Windows 10 Enterprise 2004 build 19640.1

### Description of the issue

I'm using coc to extend the functionality of Neovim inside Cmder. I don't why, but the drop down menus (suggestions, completions) of coc.nvim are invisible in Cmder. I tested Neovim's standalone application, and the suggestions appear, the problem is with Cmder apparently. I also tested ConEmu (without Cmder), and it also works, the problem is with Cmder indeed.

![0](https://user-images.githubusercontent.com/39901954/83829371-12099580-a6b9-11ea-811e-fd77c3b09eb0.png)

**Comment by daxgames** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem or have a question, please open an issue over at https://github.com/Maximus5/ConEmu

Thank you! :-)
