### ISSUE TITLE
vscode weird git path look

### ISSUE THREAD

**Issue by MaciejWiatr** [cmderdev/cmder#2326]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information
latest, v1.3.14

Windows Home 

### Description of the issue

When using vscode i get this weird issue with git path, how can i fix or disable it?

![Image](https://user-images.githubusercontent.com/44440856/83941971-e50bce80-a7ef-11ea-8ce9-dbc0106b4417.png)

**Comment by MaciejWiatr** [comment]
it is worth mentioning that the issue doesn't occur outside vscode

**Comment by daxgames** [comment]
@MaciejWiatr looks normal to me.  Could you be more specific, do you have a screenshot of the same repo outside vscode The only thing I see that might be odd is the `!` in the prompt status.  

Even if you can describe the issue better I doubt there is anything we can do to fix the behaviour inside vscode.

**Comment by MaciejWiatr** [comment]
Oh, i didn't know that was i feature, but is there by any chance way to hide this red text?

**Comment by daxgames** [comment]
You can if you really want to but it tells you the status of your Git repo.  As a developer I don't know why you would want to.  See the [README.md](https://github.com/cmderdev/cmder#git-status-opt-out)

It should happen on normal Cmder Powershell sessions as well.  If it is not then something is not right.
