### ISSUE TITLE
[request] [switch] Run as Administrator if the User in Group Admin

### ISSUE THREAD

**Issue by blackcrack** [cmderdev/cmder#2330]
cmder.exe /administrator to let open a Administration Window
or, if there a user "blackcrack" as case, open a window as user "blackcrack"

cmder.exe /user blackcrack
or 
cmder.exe /user %0  #open account $USER and ask for passwort

cmder.exe /administrator #open account $Administrator and ask for passwort if the user not in the group.

best regards
Blacky

**Comment by daxgames** [comment]
Have you tried a Windows shortcut set to run as administrator.

**Comment by blackcrack** [comment]
the link/shortcut works not on a usb-stick by different Computers as Administrator
if you have disable to call cmd.exe as administrator for the whole Clients ;)
Therefore is your Program perfect if you be a admin, should it be possible for give with administrator ;)

**Comment by daxgames** [comment]
The capability already exists to open an administrative tab after the terminal emulator app is open.  I doubt this will get added to the launcher.
