### ISSUE TITLE
Large git-lfs repository very slow

### ISSUE THREAD

**Issue by fjulia** [cmderdev/cmder#2333]
Hi,

I've a quite large git repository with git-lfs support enabled. As is has increased the size and number of files tracked by git-lfs cmder is slower in that folder.

At this moment it is very slow, every time I try to execute "cd" or any other command it keeps stucked for quite a large time (10~15 secs).

I know that this issue is also caused by git-lfs but I do not understand why/which command is executed each time I try to do "cd", it seems that cmder is executing some git and git-lfs command after every command executed.

Is there a way to change/remove that command? other way cmder it is almost unusable in that folder.

Thanks

### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

**Comment by daxgames** [comment]
See the readme.md for git status opt out.

**Comment by fjulia** [comment]
Thanks for your quick response @daxgames. 

The README solution does not works. I've set it in both global and local configs, started new tab, etc... 
It seems that now it does not execute the git,exe but it keeps executing git-lfs.exe which takes so long.

thanks
