### ISSUE TITLE
ctrl-] not working inside WSL/bash and Vim

### ISSUE THREAD

**Issue by sim590** [cmderdev/cmder#2337]
How to reproduce:

1. `:help`
2. Put your cursor on some link.
3. Try to jump from the link with `CTRL-]`
4. Notice how nothing happens.

However, it is possible to do `g<CTRL-]>` and this variant of the mapping works. However, it is not the same and I really would appreciate being able to use `CTRL-]`.

Also on bash, when pressing `CTRL-]`, the character `^]` should appear. However, in Cmder, I get a plain `]` which indicates that something is eaten up by Cmder.

I tried removing all of the `CTRL-` mappings in the configs, but it didn't help.

Let me also point out that `wsltty` doesn't have this issue, i.e. `CTRL-]` works as expected.

**Comment by daxgames** [comment]
If you have an issue with WSL bash you are not using Cmder.  You are using WSL in Conemu so if things are not working you should report the issue to the Conemu developer.
