### ISSUE TITLE
Accented characters

### ISSUE THREAD

**Issue by OverSpeed301** [cmderdev/cmder#234]
Hello,

When i type 'ls' command, I see '?' instead of the accented char. See below : 
![image](https://cloud.githubusercontent.com/assets/741798/4023168/310f9198-2b7a-11e4-819e-03495368ded9.png)

Is there a way to display accented characters ?

Thanks,

**Comment by kud** [comment]
Indeed. I did that:

```
ls=ls --show-control-chars -F --color $*
lsa=ls -lah --show-control-chars -F --color $*
l=ls -la --show-control-chars -F --color $*
ll=ls -l --show-control-chars -F --color $*
la=ls -lap --show-control-chars -F --color $*
```

(quite boring, even if you defined ls like that, you have to specify it for other aliases too.)

**Comment by Jackbennett** [comment]
commit [997bd5c24...](https://github.com/cmderdev/cmder/commit/997bd5c24ef79394c0451ff0165f43149910aaa8) has pulled in `ls=ls --show-control-chars -F --color $*` so I'm closing this fixed.
