### ISSUE TITLE
(question) how to save this layout & working directory by default ?

### ISSUE THREAD

**Issue by 3xploiton3** [cmderdev/cmder#2342]
(question) how to save this layout & working directory by default ?

![image](https://user-images.githubusercontent.com/19517680/86201008-73256b80-bb88-11ea-8aca-6420022f8747.png)

**Comment by daxgames** [comment]
I don't know.  If I use the feature in Conemu feature to save current tabs it does not produce desired results:

![image](https://user-images.githubusercontent.com/7318053/87221482-5fbd9180-c33a-11ea-9701-3462a570bced.png)

Maybe ask the Conemu Dev.
