### ISSUE TITLE
Too much scrolling without contents too scroll on

### ISSUE THREAD

**Issue by petmakris** [cmderdev/cmder#2344]
There is some bug in cmder that make the scrollbar scroll
for vertical space that is not occupied by text inside the terminal

![https://media1.tenor.com/images/35e456a6519d3ff0e8f800de7063cd4e/tenor.gif](https://media1.tenor.com/images/35e456a6519d3ff0e8f800de7063cd4e/tenor.gif)

How can this be fixed? Is it a matter of configuration? 

This is a huge usability issue, if you grab the scrollbar in the right and try to move upwards/downwards it's impossible. A tiny mouse movement will get you thousands of lines away for the point of interest. 

I don't understand how nobody else has this problem.

**Comment by daxgames** [comment]
This is not a Cmder issue.  Cmder uses Conemu as it's terminal emulator.  Problems with Conemu need to be reported to that project.
