### ISSUE TITLE
Use ~ for User's Home directory

### ISSUE THREAD

**Issue by Lunchb0ne** [cmderdev/cmder#2348]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [ ] Question

### Version Information

Cmder : 1.3.15.1010
ConEmu : 19.10.12.0

Windows 10 Pro 2004
### Description of the issue

It would be nice to have `%USERPROFILE%` directory in the prompt to be replaced by a `~` as it does on linux.
[Owl-Cmder-Tools](https://github.com/tadashi-aikawa/owl-cmder-tools) does it, but adds the powerline prompt to it.
It would be nice to have it in base cmder too.

**Comment by daxgames** [comment]
Create this file `%cmder_root%\config\prompt.lua`:

```
-- Much of the below was 'borrowed' from https://github.com/AmrEldib/cmder-powerline-prompt
-- Symbol displayed for the home dir in the prompt.
if not prompt_homeSymbol then 
	prompt_homeSymbol = "~"
end

-- Symbol displayed in the new line below the prompt.
if not prompt_lambSymbol then
	prompt_lambSymbol = "λ"
end

-- Extracts only the folder name from the input Path
-- Ex: Input C:\Windows\System32 returns System32
---
local function get_folder_name(path)
	local reversePath = string.reverse(path)
	local slashIndex = string.find(reversePath, "\\")
	return string.sub(path, string.len(path) - slashIndex + 2)
end

function prompt_filter()
    cwd = clink.get_cwd()

    if prompt_useHomeSymbol and string.find(cwd, clink.get_env("HOME")) then 
        cwd = string.gsub(cwd, clink.get_env("HOME"), prompt_homeSymbol)
    end
    prompt = "\x1b[1;32;40m{cwd}{git}{hg}{svn}\x1b[1;30;40m {lamb} \x1b[0m"
    new_value = string.gsub(prompt, "{cwd}", cwd)
    clink.prompt.value = string.gsub(new_value, "{lamb}", prompt_lambSymbol)
end

clink.prompt.register_filter(prompt_filter, 1)
```

![image](https://user-images.githubusercontent.com/7318053/87251154-8a414480-c437-11ea-99d6-76b2a1a65fd7.png)

You can stop here but you can configure it by creating `%cmder_root%\config\prompt_config.lua`:

```
-- MOST of the below was 'borrowed' from https://github.com/AmrEldib/cmder-powerline-prompt

--- REQUIRED. config_prompt_type is whether the displayed prompt is the full path or only the folder name
 -- Use:
 -- "full" for full path like C:\Windows\System32
 -- "folder" for folder name only like System32
 -- "smart" to switch in git repo to folder name instead of full path 
 -- default is full
prompt_type = "smart"
--- REQUIRED. config_prompt_useHomeSymbol is whether to show ~ instead of the full path to the user's home folder
 -- Use true or false
 -- default is true
prompt_useHomeSymbol = true  

-- Symbols
-- REQUIRED. Prompt displayed instead of user's home folder e.g. C:\Users\username
prompt_homeSymbol = "~"

-- REQUIRED. Symbol displayed in the new line below the prompt.
prompt_lambSymbol = "$"
```

![image](https://user-images.githubusercontent.com/7318053/87251184-b9f04c80-c437-11ea-8862-d22a14960d63.png)

**Comment by Lunchb0ne** [comment]
Sorry, but the replacement part is not working for me.
![image](https://user-images.githubusercontent.com/22198661/87302709-87297f80-c52f-11ea-9230-f684a9b6e649.png)

**Comment by daxgames** [comment]
Maybe it is cas sensitive? Output of `set home`?

**Comment by daxgames** [comment]
I added a section to the initial script make sure you have it in yours.

**Comment by Lunchb0ne** [comment]
Thanks, it works now!
