### ISSUE TITLE
Updated cmder to take over cmd.exe, unix commands not working?

### ISSUE THREAD

**Issue by Labarr** [cmderdev/cmder#2350]
![](https://i.gyazo.com/71618560af0d17c1138a1a629ef09596.png)

So I was hoping to get all the functionality of cmder to overtake cmd.exe, is this something I messed up? or is this not something that can be achieved? Above is an example, I do have git installed on my pc

**Comment by daxgames** [comment]
What exactly did you do?

**Comment by daxgames** [comment]
@Labarr ???

**Comment by i-s-o** [comment]
Sounds like ConEmu's setting to take over as the default terminal (i.e. launching cmd.exe runs ConEmu instead of Command Prompt), which, obviously, doesn't bring in the functionality of Cmder:
![image](https://user-images.githubusercontent.com/1661549/88095287-de98a280-cb62-11ea-898b-1087e2b8cf3a.png)

**Comment by i-s-o** [comment]
@Labarr My previous comment was a bit cryptic. To clarify: Cmder brings together ConEmu, Clink, and its own enhancements/configuration to those tools. As such, you have to run Cmder.exe to get all its functionality. If, indeed, you are referring to the option I showed above, when you run cmd.exe, you will be launching ConEmu without the Cmder & Clink enhancements. I don't think you can have Cmder overtake cmd.exe with that option unless you directly run Cmder. In a way, that option in ConEmu is irrelevant/useless if you want to use Cmder.

**Comment by daxgames** [comment]
@iso Thanks for trying to help.

@Labarr is the above what you tried?  I do not know exactly what that option in Conemu does to force itself to replace cmd.exe but @i-s-o is probably correct in the assessment provided.

Please respond or the issue will be closed for lack of response.

**Comment by Labarr** [comment]
Hey guys! My apologize for the lack of response. Thank you for the tips! I've been swamped with testing stuff for work, and have been unable to follow up as of yet (Reinstalled windows a few times since my initial comment, but I think @i-s-o made it clear what I was doing wrong. I'll test it out as soon as I get a chance, hopefully by this weekend.

Cheers!
