### ISSUE TITLE
cmder initialization is too slow

### ISSUE THREAD

**Issue by lzb-libra** [cmderdev/cmder#2352]
Hello developer, I recently used the cmder and found that there is a problem that I can't stand. That is, after opening the software, I can input the command for operation. The initialization in the middle is too slow. I feel that the initialization speed is the same as that of the sloth. I want to ask if there is an optimization method. thank you

**Comment by daxgames** [comment]
Example?

**Comment by cobolcowboy** [comment]
👍

**Comment by lzb-libra** [comment]
每次我在打开cmder时，界面处于黑屏状态，到可以输入命令着中间的过程有点长。你可以试着打开win10电脑的cmd，打开就可以立马输入命令。我就想是否有什么办法可以优化一下像cmd一样，打开能立马输入命令一样。我安装的cmder从打开软件到能输入命令之间最长的一次我等了20多秒。

**Comment by lzb-libra** [comment]
Every time I open the cmder, the interface is in a black screen state, and the process from being able to enter commands is a bit long. You can try to open the windows 10 computer's CMD, open can immediately input commands. I just want to know if there is any way to optimize it, like CMD, which can input commands immediately. I waited more than 20 seconds for the longest time between opening the software and being able to enter commands.

**Comment by daxgames** [comment]
20 seconds is really long.  Usually this is caused by some software on your system.  Launch time on my systems is 2-4 seconds.  Most people that report long launch times are on corporate managed systems with malware prevention or data loss protection agents installed.

You can modify the task that Conemu uses to run Cmder and add `/f` that can give you some speed at the expense of done functionality.

**Comment by lzb-libra** [comment]
Should not be this reason, I found that the lower left corner of the initialization will not stop the cycle cmd.exe , local.exe , find.exe , findstr.ext , git.exe Wait, this is to initialize these plug-ins.

**Comment by lzb-libra** [comment]
Should not be this reason, I found that the lower left corner of the initialization will not stop the cycle cmd.exe , local.exe , find.exe , findstr.ext , git.exe Wait, this is to initialize these plug-ins.

**Comment by lzb-libra** [comment]
My idea is whether it can be initialized only when it is initialized cmd.exe This one. Others are initialized asynchronously. At least I can use it after I open it for about 1 second

**Comment by daxgames** [comment]
@lzb-libra I have given you the only suggestions I have. `/f` should help some but it will never be as fast as a vanilla `cmd.exe` shell.

**Comment by Krysenlo** [comment]
@daxgames

Just change the following code 
https://github.com/cmderdev/cmder/blob/44f5095047c2e5056884eca90082e13ebcf73061/vendor/lib/lib_console.cmd#L4
to below will reduce the time from 4.18s to 2.82s on my computer. 
```
if %debug_output% gtr 0 (
    set lib_console=call "%~dp0lib_console.cmd"
) else if %verbose_output% gtr 0 (
    set lib_console=call "%~dp0lib_console.cmd"
) else (
    set lib_console=rem
)
```

There should be a lot of places can be optimized.

**Comment by Ali-Nategh** [comment]
I am facing the same issue, was there any solution? I tried both "/f" and the "lib_console.cmd" code replacement none of which worked.

**Comment by chrisant996** [comment]
This is an old issue. Use #2816 to discuss. Try the pre-release build there as well.
