### ISSUE TITLE
[Request] Create pipeline to publish on WinGet

### ISSUE THREAD

**Issue by Echarnus** [cmderdev/cmder#2355]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [X] Feature request (request for new functionality)
- [ ] Question

### Version Information
N/A

### Description of the issue

Would you mind creating a pipeline to publish releases onto WinGet (Windows Package manager, successor of AppGet)? It requires you to make a pull request with a yaml file for each version, which contains information such as version, url of the download, file type, etc. For more information you can look at https://github.com/microsoft/winget-pkgs/tree/master/manifests .

Will be much easier to use Cmder via WinGet as it makes me able to keep my software more up to date.

**Comment by daxgames** [comment]
Cmder does not have an installer.  This is not reqired.

**Comment by Arecsu** [comment]
This should be considered in a future once WinGet supports no-installer, zipped apps like this one though.

For now, Chocolatey works just fine. https://chocolatey.org/packages/Cmder

**Comment by daxgames** [comment]
We do not maintain the Chocolatey repo either.  If someone wants to provide a WinGet package when/if they ever support no installer zip packages then they should.

**Comment by DRSDavidSoft** [comment]
Support for WinGet can be tracked over: #2552

**Comment by DRSDavidSoft** [comment]
For future visitors: this can remain closed as a duplicate of #2552, while the broader WinGet and package-manager work is tracked in the master issue and wiki.

Cmder is not available in WinGet's default source yet, but the old ZIP-support blocker has changed. The next step is to prepare and submit archive/portable WinGet manifests from official Cmder release assets.

Master package-manager tracker: https://github.com/cmderdev/cmder/issues/3094
Wiki status page: https://github.com/cmderdev/cmder/wiki/Package-Manager-Status
