### ISSUE TITLE
Open 

### ISSUE THREAD

**Issue by mrmmg** [cmderdev/cmder#2360]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Description of the issue

Hi, I want to make a task that opens a certain folder in the current tab, not in new console. how can I do this?

An example: I want a task to run this command: `cd d:\projects\laravel` **in current active tab**

**Comment by daxgames** [comment]
Do you want to create an alias?

```
C:\ > alias projects=cd /d d:\projects\laravel
C:\ > projects

D:\projects\laravel
```

**Comment by mrmmg** [comment]
@daxgames thanks to you, it's working
