### ISSUE TITLE
Trouble with downloader

### ISSUE THREAD

**Issue by MacelinCane** [cmderdev/cmder#2361]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)

### Version Information

Cmder only v1.3.16 2020/07/29

Win10 Pro 10.0.108362

### Description of the issue
Upon attempting to unzip (I've tried 7-zip and the built in windows extractor) Windows defender warns of a Trojan in the .exe file and quarantines it. 
![cmderTrojan](https://user-images.githubusercontent.com/57817530/89071307-6d1bd980-d344-11ea-94ae-81243d34875c.jpg)

**Comment by daxgames** [comment]
It's a false positive.  The file is clean.
