### ISSUE TITLE
bash shell does not include 'stdbuf' anymore

### ISSUE THREAD

**Issue by caecilius7** [cmderdev/cmder#2362]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Version Information

cmder 1.3.12.915

Windows 10 Pro 1903
### Description of the issue

Hi, I'm currently running Cmder 1.3.12.915, using a bash shell but this version does not include the 'stdbuf' command anymore.
I even downloaded and tested cmder-1.3.15 and cmder-1.3.16 (latest), but still nothing.
However, older versions - such as cmder-1.3.4-32bit or cmder-1.3.6-64bit - did include it (<cmder>\vendor\git-for-windows\usr\bin)!

Why this change? Isn't 'stdbuf' a core bash command?
Anyway, is this a cmder or git-for-windows change\limitation?
More important, preferably without the need of an external installation of bash, can you help me solve this issue?
Thank you!

**Comment by daxgames** [comment]
We rely on and use Git for Windows Portable so whatever that package includes you get in Cmder.  If they removed this file we have no control over that.
