### ISSUE TITLE
Terminal do nothing when going in some folder

### ISSUE THREAD

**Issue by azralth** [cmderdev/cmder#2363]
Hi,
I don't know why but when i go in some folder, cmder is doing nothing and i have no choice to close it. I don't understand why.
![index](https://user-images.githubusercontent.com/552339/89304732-16790d00-d66e-11ea-8942-a08743163fb5.png)
In this folder i have a prestashop CMS folder, some git folder : 
![index2](https://user-images.githubusercontent.com/552339/89304873-432d2480-d66e-11ea-86b9-712e2b5e4b2d.png)

I try to find what cause this break but get no idea. I i use the windows default terminal i can navigate to this folder. Can you help me with this ?

**Comment by daxgames** [comment]
Try renaming the .git folder.  Don't delete it, just rename it.

**Comment by daxgames** [comment]
@azralth ???

Is this still an issue.

Git can be slow on a large repo or a git lfs repo which is why I made the suggestion I did.

you could also try [this](https://github.com/cmderdev/cmder#git-status-opt-out)

**Comment by azralth** [comment]
Hi. You've right. I have to ne more patient. It's work better on SSD. Thanks for your help.
