### ISSUE TITLE
"cat" and "ls" commands are not working , this massage appears " 'cat' is not recognized as an internal or external command, operable program or batch file."

### ISSUE THREAD

**Issue by deebonit** [cmderdev/cmder#2364]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

**Comment by daxgames** [comment]
@deebonit More info.

I assure you `cat` and `ls` work as expected unless you downloaded mini and don't have Git installed locally or there is something wrong with your environment.

**Comment by daxgames** [comment]
@deebonit ???
