### ISSUE TITLE
tweak cmder inside IntelliJ

### ISSUE THREAD

**Issue by Drprincerajput** [cmderdev/cmder#2367]
when i run 
CTRL + L
only lamda remain in terminal other part gone outside terminal window 
is there any solution for that
![one](https://user-images.githubusercontent.com/55732506/89753124-ad254e00-daf4-11ea-89b2-062f6c2d9baf.png)
![two](https://user-images.githubusercontent.com/55732506/89753133-b31b2f00-daf4-11ea-961b-72ebee330cbd.png)

problem when i will be playing with github.
can i tweak it like bash shell so everything will be in lamda line not above ?

_Originally posted by @Drprincerajput in https://github.com/cmderdev/cmder/issues/282#issuecomment-671161803_

**Comment by daxgames** [comment]
See: #2348, #338

Both do what you ask #2348 additionally uses `~` for the home folder.
