### ISSUE TITLE
'λ' symbol in powershell is not showing correctly

### ISSUE THREAD

**Issue by WilliamZY** [cmderdev/cmder#2368]
### Purpose of the issue
- [X] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

cmder 1.3.16.1035
ConEmu 191012 preview and ConEmu 200713 preview 

Windows 10 Ent 2004
Windows 10 Pro 1909

### Description of the issue
In the latest version(1.3.16.1035) downloaded from release, the "λ" symbol is not displaying correctly when using the powershell.
![image](https://user-images.githubusercontent.com/12370751/89990791-777b9300-dcb5-11ea-8f06-e4eec269e979.png)
I thought it was a ConEmu issue and downgrade and upgrade the ConEmu from the setting but doesn't resolve the problem. 
I have also tried to set everything to default and I get the same result. 

But in the last version(1.3.15.1010) of the cmder, there is no such issue.
![image](https://user-images.githubusercontent.com/12370751/89991354-510a2780-dcb6-11ea-8eaa-95a91fb0e637.png) 

All screenshots are taken from the same computer with same system with same language setting.

**Comment by mcnubblet** [comment]
I am also experiencing this issue.

I replaced the vendor\profile.ps1 file with the file from 1.3.15 and the issue went away.

Comparing the file using WinMerge reveals that the text content is identical, however the 1.3.16 version of the file does not have the utf-8 BOM at the start of the file (first 3 bytes in the 1.3.15 version are hex 0xEF 0xBB 0xBF).

**Comment by WilliamZY** [comment]
Nice. That solves the problem. 
Just had a quick look of the commit history, can't spot why that would happen in the lattest version. But since the problem have been identified just hope the dev could fix that in the next release.

**Comment by mentofa123** [comment]
Hey had the same problem but i [fixed ](https://github.com/cmderdev/cmder/issues/2341#issuecomment-670490681) it replacing the lambda with the unicode character in the vendor\profile.ps1 file. 
Interesting that you were able to fix it with a profile.ps1 file from a previous version, this didn't work for me.

**Comment by Rohaq** [comment]
> I am also experiencing this issue.
> 
> I replaced the vendor\profile.ps1 file with the file from 1.3.15 and the issue went away.
> 
> Comparing the file using WinMerge reveals that the text content is identical, however the 1.3.16 version of the file does not have the utf-8 BOM at the start of the file (first 3 bytes in the 1.3.15 version are hex 0xEF 0xBB 0xBF).

Thanks - Converting the file to UTF-8 BOM fixed it for me.

**Comment by daxgames** [comment]
This is fixed in latest master branch and will be in the next release.
