### ISSUE TITLE
Console will be pending after gvim

### ISSUE THREAD

**Issue by lauxinw** [cmderdev/cmder#2375]
The console of cmder will be pending after opening file with gvim,
is there any setting can run gvim asynchronously?

**Comment by daxgames** [comment]
`start gvim` maybe.

**Comment by daxgames** [comment]
I installed gvim and when I execute `"c:\Program Files (x86)\Vim\vim82\gvim"` all works as expected.  `gvim` launches and I have immediate access to the prompt.

I did not have the `gvim` installer create bat files in `c:\windows` so I could launch it from the path.  This may change the behavior to what you are seeing.

You could delete the gvim batch files from `c:\windows` and add `set path=%path%;"c:\Program Files (x86)\Vim\vim82"` to `%cmder_root%\config\user_profile.cmd` to allow launching `gvim` without the fully qualified path.  This also works as expected and returns to the prompt immediately.

**Comment by lauxinw** [comment]
Thanks for your response. 
I would access console by "start gvim".
