### ISSUE TITLE
\Cmder\vendor\bin\cexec.cmd"" was unexpected at this time.

### ISSUE THREAD

**Issue by FirassBarakat** [cmderdev/cmder#2377]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

**Comment by FirassBarakat** [comment]
Please Solve it

**Comment by daxgames** [comment]
@FirassBarakat details?

**Comment by daxgames** [comment]
@FirassBarakat can you try: https://ci.appveyor.com/project/MartiUK/cmder/builds/34805231/artifacts

**Comment by briansrls** [comment]
I get this error when the name of my folder contains a parenthesis, i.e. "cmder (1)".  I was able to solve it by renaming the folder to "cmder"

**Comment by daxgames** [comment]
@briansrls did you try the version in the link above.  This is a fix for this issue.

**Comment by briansrls** [comment]
@daxgames, I don't think that worked for me.

I downloaded the build, extracted, and this is what I see:

![image](https://user-images.githubusercontent.com/11205878/91664693-b9724a80-eaa5-11ea-9c38-5261b4623446.png)

**Comment by briansrls** [comment]
Here is the testing I've done:

- "cmder" ✅
- "cmder (1)" ❌
- "cmder (2)" ❌
- "cmder ()" ❌
- "cmder (" ✅

I was surprised that the last one worked.

**Comment by daxgames** [comment]
https://ci.appveyor.com/project/MartiUK/cmder/builds/34844421/artifacts

**Comment by briansrls** [comment]
@daxgames that build worked for me.

**Comment by daxgames** [comment]
Merged PR to master that fixes this.  Artifacts here: https://ci.appveyor.com/project/MartiUK/cmder/build/artifacts

**Comment by locdhthtb** [comment]
i think it has prolem from path with round brackets 

E:\Program Files (x86)\cmder -> 

\cmder\vendor\bin\cexec.cmd"" was unexpected at this time.
