### ISSUE TITLE
Problem with Text based displayed

### ISSUE THREAD

**Issue by matze2090** [cmderdev/cmder#2378]
i have the problem that text based images are not displayed. the image only flickers.
the problem was already in the older version.

![Capture1](https://user-images.githubusercontent.com/57045956/90391200-00ffdc00-e08d-11ea-9a4a-9638033fadaa.PNG)

for example: than after choose "change user password"
![Capture](https://user-images.githubusercontent.com/57045956/90391196-ffceaf00-e08c-11ea-8849-a44633b8c042.PNG)

**Comment by daxgames** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem or have a question, please open an issue over at https://github.com/Maximus5/ConEmu

Thank you! :-)
