### ISSUE TITLE
wslbridge error: failed to start backend process

### ISSUE THREAD

**Issue by gabimladin** [cmderdev/cmder#2382]
When I open a tab for WSL, WSL-> BASH, an error occurs.
![wsl](https://user-images.githubusercontent.com/17005664/91634376-9f2e6300-e9f8-11ea-8292-66fef7d9ea67.png)

**Comment by Ergamon** [comment]
It is a ConEmu thing. The whole WSL part is for WSL version 1, I guess you are running WSL version 2?

1. You need a new version of cygwin1.dll
Grab one here: https://cygwin.com/snapshots/
Go to vendor\conemu-maximus5\ConEmu\wsl and replace the dll.

2. You need wslbridge 2:
Grab it here: https://github.com/Biswa96/wslbridge2/releases (the cygwin version)

3. Now edit your WSL bash task:
Replace the part "conemu-cyg-64.exe --wsl" with "conemu-cyg-64.exe %ConEmuBaseDirShort%\wsl\wslbridge2.exe"

Done.

**Comment by gabimladin** [comment]
I have Windows 10 Build 19041 and Cmder v1.3.16. It's not a path problem because if I run Cmder\vendor\conemu-maximus5\ConEmu\wsl\wslbridge.exe, the same error occurs. The problem is with wslbridge.exe.

**Comment by Tiaonmmn** [comment]
When you use WSL2,do not use original wslbridge.exe,it's designed for WSL1.You can create a new task,and set the task command as: `set PATH="%ConEmuBaseDirShort%\wsl";%PATH% & wsl -d kali-linux`,which kali-linux is the distro name you have installed.You can get the name by seeing `wsl -l` output.

**Comment by gabimladin** [comment]
Yes, I can run wsl.exe but will no longer use colors 256colors, looking like windows cmd.

**Comment by elisim** [comment]
Hey, 
any progress?

**Comment by IP-Developer** [comment]
https://conemu.github.io/en/wsl.html#wsl2
