### ISSUE TITLE
Issues with Vim in vanilla Cmder

### ISSUE THREAD

**Issue by briansrls** [cmderdev/cmder#2383]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information
Latest downloaded off https://cmder.net/ - Latest Version: v1.3.16 2020/07/29

Windows 10 Pro 2004

### Description of the issue
After downloading cmder and trying to use vim, I'm met with a lot of strange issues.  For example, Home and End do not work.  When I enter them, I see a lot of ```^[[H``` and ```^[[F``` in the bottom right of vim.  Another issue I see is that when simply hitting up/down arrow keys, it sometimes switches to insert mode and inserts seemingly random keys.

Here is a video demonstrating.  Keep an eye on the bottom right and top left.  I never once enter a character other than "fdsa" initially, after that I'm repeatedly hitting arrow keys and home/end keys.

https://streamable.com/rg6wfk

I was not able to reproduce this issue in other programs, such as git bash.  Seems exclusive to cmder so far.  I have not tried standalone conemu yet.

**Comment by daxgames** [comment]
I have seen this too.  It is very annoying.

Try setting this in `%cmder_root%\config\user_profile.cmd`

```
set TERM=xterm-256color
```

Start a new session and run `vim`

Cmder sets `TERM=cygwin` in `%cmder_root%\vendor\init.bat`.  This used to work fine but I think a newer ConEmu changed the behavior.  There are similar issues reported there.

**Comment by briansrls** [comment]
Thanks, it works well now.

**Comment by briansrls** [comment]
Is there anyway to mitigate this for new users?  Maybe cmder should come prepopulated with this command if it's safe @daxgames

**Comment by daxgames** [comment]
We could change from `TERM=cygwin` to `TERM=xterm-256color` but I want to test it for a while before we do.

I literally just tried this 5 minutes before I sent it to you .

**Comment by daxgames** [comment]
@briansrls I had MANY issues with `TERM=xterm-256color`  I went back to Cmder default.  I can't recommend it even though it solve this particular issue.  What's your experience?

**Comment by briansrls** [comment]
@daxgames Honestly it has solved all my issues, but my use case is very narrow.  Maybe it's best to open an issue on ConEmu and hope its solved?  Or has this project diverged from conemu completely?

**Comment by daxgames** [comment]
We use Conemu binaries unmodified.  There are some default settings differences.  THere already is an issue at Conemu that I am commenting on:  https://github.com/Maximus5/ConEmu/issues/1691

**Comment by daxgames** [comment]
This used to work fine.  I don't know what changed or when probably something in underlying Windows console API.

**Comment by daxgames** [comment]
We use Conemu unmodified other than some settings differences.

There already is an issue at conemu

**Comment by ecator** [comment]
I have encountered the same problem when typing CJK characters in command line. So I rollbacked to 1.3.15 :cry:

**Comment by daxgames** [comment]
@ecator CJK in command line???

What does that mean?

**Comment by briansrls** [comment]
> @ecator CJK in command line???
> 
> 
> 
> What does that mean?

It stands for Chinese, Japanese, and Korean characters.
