### ISSUE TITLE
File Explorer context menu opens Cmder in a new window

### ISSUE THREAD

**Issue by nlivaic** [cmderdev/cmder#2384]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [x ] Feature request (request for new functionality)
- [ ] Question

### Version Information

191012 preview

Windows Version	10.0.17763 Build 17763

### Description of the issue

When opening cmder via File Explorer context menu, it gets opened in a new window. It disregards any already open instances of cmder. It would be great if it first checked if a cmder was already running and opening the location in a new tab, as opposed to creating a whole new instance/window.

**Comment by daxgames** [comment]
```
cmder /single /register user
```

Will do what you ask.
