### ISSUE TITLE
When using cmder with windows terminal or fluent terminal, ctrl+u can not clear all characters before the cursor

### ISSUE THREAD

**Issue by myy1966** [cmderdev/cmder#2385]
### Purpose of the issue
Bug report (encountered problems/errors)

### Version Information
cmder v1.3.16 2020/07/29
windows terminal 1.1.2233.0
fluent terminal 0.7.2.0

### Description of the issue
When using cmder with windows terminal or fluent terminal, ctrl+u can not clear all characters before the cursor, it will leave the first character of the line.

In windows terminal
![cmder-wt](https://user-images.githubusercontent.com/10590090/91787017-79dd6700-ec3b-11ea-8a33-c02956496221.gif)

In fluent terminal
![cmder-ft](https://user-images.githubusercontent.com/10590090/91787031-83ff6580-ec3b-11ea-82f4-ed00ec1399e5.gif)

In conemu, ctrl+u can clear all characters before the cursor
![cmder-cm](https://user-images.githubusercontent.com/10590090/91787079-a0030700-ec3b-11ea-936a-041a20823a1e.gif)

**Comment by daxgames** [comment]
Usually this is a font thing and not liking the 'lambda'.  Try a different font, or you could change the 'lambda' to '$' using a custom `prompt.lua` in the `config` folder.
