### ISSUE TITLE
ConEmuHk64 crashes, injecting hooks [into], code=-710:0x00000005

### ISSUE THREAD

**Issue by rslemos** [cmderdev/cmder#2386]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information
Version 1.3.16.1035
Windows 7 Pro SP1

### Description of the issue
Cmder randomly crashes with a message (title ConEmuHk64, PID=xxxxx):

bash.exe: PID=xxxxx
Injecting hooks into PID=yyyyy
FAILED, code=-710:0x00000005

The crash occurs with sh.exe, perl.exe, git.exe, and many others. I use Cmdr mainly for development (git, yarn, npm, angular, java, maven, bash, many unix utilities).

It happens randomly, though the distribution is not uniform. I can work for entire days without a glitch. But some days (like today) it can become so bothersome, when each new tab lives only for a single or a pair of commands (then it dies "injecting hooks").

If the crash happens in bash.exe then usually Cmder recovers (after Ctrl+C) and shows the command prompt. Otherwise it is nearly impossible to recover the problematic tab.

PS: I tried to file this issue with ConEmu (https://github.com/Maximus5/ConEmu/issues/2124) to no avail.

**Comment by daxgames** [comment]
@rslemos what session/task are you using?  Reading the Conemu issue thread I assume it is `bash::bash`.

Some background on what Cmder is.

Cmder is a specialized package of various tools and configuration scripts that delivers a an 'opinionated' and hopefully better terminal experience than the Windows default terminal.

If you are using `bash::bash` you are essentially using Git for Windows Portable inside Conemu.  Both packages are downloaded in archive form from their respective release pages and are included unmodified except as follows.

The Cmder package adds:

### Conemu

- A default `Conemu.xml` file.
  - Configuration differences from the stock Conemu.  These are documented [here](https://github.com/cmderdev/cmder/wiki/Cmder-vs.-ConEmu)
  - Task list for launching Cmder sessions.

### `bash::bash` Session

- Scripts to the Git for Windows `/etc/profile.d` folder:
  - `cmder.sh`: Cmder bash init script.
    - Provides Cmder portable init script execution from the `%cmder_root%\config`.
    - Path additions for easy access to user portable binaries in `%cmder_root%\bin;`
    - Path additions for easy access to Cmder scripts in `%cmder_root%\vendor\bin;` 
  - `git-prompt.sh`: From Git for Windows modified to provide the Cmder prompt look.

### `cmd::cmder` Session
- `init.bat` - Cmder init script 
  - `clink` is injected to provide bash Readline like support, Cmder prompt look that includes Git repo awareness.
  - `clink completions` for command completion.
  - Path additions for easy access to user portable binaries in `%cmder_root%\bin;`
  - Path additions for easy access to Cmder scripts in `%cmder_root%\vendor\bin;` and Git for Windows provided Git and *nix tools.
  - Ability to easily create and use `doskey` macros.
  - Provides Cmder portable init script execution from the `%cmder_root%\config`

### `powershell::powershell` Sessions

- `profile.ps1` - Cmder Powershell profile script.
  - Path additions for easy access to user portable binaries in `%cmder_root%\bin;`
  - Path additions for easy access to Cmder scripts in `%cmder_root%\vendor\bin;` and Git for Windows provided Git and *nix tools.
  - Use `posh-git` Powershell module to create git aware prompt.
  - Configures Cmder prompt look.
  - Provides Cmder portable init script execution from the `%cmder_root%\config`

I hope this helps.

**Comment by rslemos** [comment]
Yes, it is `bash::bash`.

I like to work with git-for-windows and ConEmu together, and Cmder is a perfect merge of them. I like it very much.

But these crashes have become so frequent, to the point of being unbearable.

I'm looking for something I can do to remedy the situation.

ConEmu people ask to upgrade to the lastest version of their package. But Cmder uses an older one. Do you know if I can safely install a newer ConEmu inside my current Cmder installation?

**Comment by daxgames** [comment]
Download the newer Conemu and replace the `cmder_root\vendor\conemu-maximus5` folder>
