### ISSUE TITLE
Cmder warns despite git support is disabled

### ISSUE THREAD

**Issue by takase1121** [cmderdev/cmder#2387]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

Version 1.3.16.1035

Windows 10 Pro 2004
### Description of the issue

The git integration is incredibly slow so I disabled it. However, whenever I start cmder and go to a git repo, I got a warning saying 
```
WARNING: Missing git support, install posh-git with 'Install-Module posh-git' and restart cmder.
```

It'll be better if the warning is not displayed if the user chose to opt out.

**Comment by daxgames** [comment]
Git opt out is both global and local to a single repo. Your request might be possible if Git opt out is global but is not possible if Git opt out is local to a repo so you are just better off installing the module and opting out.

**Comment by takase1121** [comment]
Yes I know that, but I did opt-out globally. How about making it a feature only for global opt-outs?

**Comment by daxgames** [comment]
I will look at it.
