### ISSUE TITLE
Strange behaviour between installations

### ISSUE THREAD

**Issue by webmasterpf** [cmderdev/cmder#2388]
Hello

I use cmder on different windows 10 machines and behaviour change on between.
On machine 1, cmder icon is the grenn one, instead of on the other machine it's a black with E.
When I start it, the git bash tabs prompt for ssh passphrase on the 1, not on the 2nd.
The machine 1 keep command history on git bash or cmd tab, the 2nd, only for git bash.

The 2nd machine have this installation: C:\app\cmder_mini

Task on start are both well executed . The only similar point in fact.

Thanks for tips

**Comment by daxgames** [comment]
@webmasterpf thanks for the question unfortunately I have more questions.

Can you provide the windows versions of each machine:

```
Winver
```

Is the same Cmder release(1.3.16) and package(cmder|cmder_mini) installed on both?

How are you launching both?  Clicking a shortcut or clicking on `Cmder.exe`?

You might also want to provide the output of `cmder_diag.cmd` from each.

What is the default startup task in each?  You find this in the `Setup Tasks` dialog.  I am sorry I don't know the exact tree node from the left.

**Comment by webmasterpf** [comment]
Hello,
Machine1 Dell: 
ConEmu 191012 [64] Startup Info
  OsVer: 10.0.16299.x64, Product: workstation, SP: 0.0, Suite: 0x100
  Build: 1709, UBR: 1087, ReactOS: 0, Rsrv: 0, WINE: 0, PE: 0, R2: 0
  Title: `C:\app\cmder_mini\Cmder.exe`

On machine 1 I launch Cmder by clicking the green icon on task bar. This launch start task ( git bash and cmder)
For cmder_diag, what do I sanitize before joining it here ?

I will provide infos about machine 2 later.

**Comment by daxgames** [comment]
Just look at the output.  If it contains data you do not want to share publicly remove it.  I don't know what is in your environment.  Some people might have credentials set as env variables.

**Comment by daxgames** [comment]
Screenshots from both might be helpful also.

**Comment by webmasterpf** [comment]
2nd machine HP:
ConEmu 191012 [64] Startup Info
  OsVer: 10.0.17763.x64, Product: workstation, SP: 0.0, Suite: 0x100
 Build: 1809, UBR: 973, ReactOS: 0, Rsrv: 0, WINE: 0, PE: 0, R2: 0
  Title: `C:\Users\xxxx\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\Console Emulator (x64).lnk`
  
This is a gist for output of cmder_diag.cmd : https://gist.github.com/webmasterpf/2318c43fdd78ec2b06830ac77c9a9a52

**Comment by webmasterpf** [comment]
Closed but not fixed :/
