### ISSUE TITLE
Split tabs shift to the right on restart

### ISSUE THREAD

**Issue by waptik** [cmderdev/cmder#2389]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

1.3.16.1035, 1.3.15.1010, 1.3.2

### Description of the issue

Hi,

I have been using laragon(v4+) for a while now, which includes a version of cmder(v1.3.2). So recently i decided to update the version of cmder because of some few issues such as alias etc. After updating it like mentioned  in the readme file, i noticed that all split tabs shift to the right after i restart cmder. I split them into 4 equally(left top+down, right top+down), when i close cmder and restart it, i see 3 tabs on the right and 1 tab on my left. as well this message(`The process cannot access the file because it is being used by another process.`) at the beginning of all tabs.
I thought maybe it was because i was using the latest version so i installed the previous version which is v1.3.15.1010 but i faced the same issues. Below are the screenshot(2 for each version) for v1.3.2 and 1.3.16 respectively, i know how to make go away message about **alias** for v1.3.16.
![conEmu v161209 - before](https://user-images.githubusercontent.com/1687551/92835079-57c9ae80-f3ca-11ea-8aa6-e345f0366bb9.jpg)
![conEmu v161209 - restart](https://user-images.githubusercontent.com/1687551/92835084-59937200-f3ca-11ea-95ba-e83e398a596d.jpg)
![conEmu v191012 - before](https://user-images.githubusercontent.com/1687551/92835086-5a2c0880-f3ca-11ea-9c08-eeaab9b1d3c6.jpg)
![conEmu v191012 - restart](https://user-images.githubusercontent.com/1687551/92835089-5ac49f00-f3ca-11ea-8dd7-6395b1f24b72.jpg)

**Comment by daxgames** [comment]
Some background on what Cmder is.

Cmder is a specialized package of various tools and configuration scripts that delivers a an 'opinionated' and hopefully better terminal experience than the Windows default terminal.

You are running multiple splits of Cmder inside Conemu.  Conemu is the gui  and it is downloaded in archive form from it's release page and is included unmodified except as follows.

The Cmder package adds:

### Conemu

- A default `Conemu.xml` file.
  - Configuration differences from the stock Conemu.  These are documented [here](https://github.com/cmderdev/cmder/wiki/Cmder-vs.-ConEmu)
  - Task list for launching Cmder sessions.

### `bash::bash` Session

- Scripts to the Git for Windows `/etc/profile.d` folder:
  - `cmder.sh`: Cmder bash init script.
    - Provides Cmder portable init script execution from the `%cmder_root%\config`.
    - Path additions for easy access to user portable binaries in `%cmder_root%\bin;`
    - Path additions for easy access to Cmder scripts in `%cmder_root%\vendor\bin;` 
  - `git-prompt.sh`: From Git for Windows modified to provide the Cmder prompt look.

### `cmd::cmder` Session
- `init.bat` - Cmder init script 
  - `clink` is injected to provide bash Readline like support, Cmder prompt look that includes Git repo awareness.
  - `clink completions` for command completion.
  - Path additions for easy access to user portable binaries in `%cmder_root%\bin;`
  - Path additions for easy access to Cmder scripts in `%cmder_root%\vendor\bin;` and Git for Windows provided Git and *nix tools.
  - Ability to easily create and use `doskey` macros.
  - Provides Cmder portable init script execution from the `%cmder_root%\config`

### `powershell::powershell` Sessions

- `profile.ps1` - Cmder Powershell profile script.
  - Path additions for easy access to user portable binaries in `%cmder_root%\bin;`
  - Path additions for easy access to Cmder scripts in `%cmder_root%\vendor\bin;` and Git for Windows provided Git and *nix tools.
  - Use `posh-git` Powershell module to create git aware prompt.
  - Configures Cmder prompt look.
  - Provides Cmder portable init script execution from the `%cmder_root%\config`

There is not really anything we can do to change the way Conemu handles split panes in Conemu.

I hope this helps.

**Comment by waptik** [comment]
Thanks for the explanation, it really helped. I managed to fixed it by updating conemu from the GUI.
Is there a way to get rid of this annoying message `The process cannot access the file because it is being used by another process` that displays at the top of each tab at start up?

**Comment by daxgames** [comment]
I have never seen that message.

If you are running Cmder 1.3.16 you can add a `/d` to the task starting Cmder in Conemu tasks after `init.bat` but before the last `"`.  It might give me a clue as to what file it is complaining about.

**Comment by waptik** [comment]
I added /d as suggested and here's the debug output:
```sh
DEBUG(init.bat): Env Var - CMDER_ROOT=C:\laragon\bin\cmder                                                                        
                                                                                                                                  
DEBUG(init.bat): Env Var - debug_output=1                                                                                         
                                                                                                                                  
DEBUG(init.bat): Looking for Git install root...                                                                                  
                                                                                                                                  
DEBUG(:read_version): Env Var - git_executable=C:\laragon\bin\cmder\vendor\git-for-windows\cmd\git.exe                            
                                                                                                                                  
DEBUG(:read_version): Env Var - GIT_VERSION_VENDORED=2.28.0.windows.1                                                             
                                                                                                                                  
DEBUG(:validate_version): ARGV[1]=VENDORED, ARGV[2]=2.28.0.windows.1                                                              
                                                                                                                                  
DEBUG(:parse_version): ARGV[1]=VENDORED, ARGV[2]=2.28.0.windows.1                                                                 
                                                                                                                                  
DEBUG(:validate_version): Found Git Version for VENDORED: 2.28.0.windows.1                                                        
                                                                                                                                  
DEBUG(:read_version): Env Var - git_executable=C:\laragon\bin\git\cmd\git.exe                                                     
                                                                                                                                  
DEBUG(:read_version): Env Var - GIT_VERSION_USER=2.28.0.windows.1                                                                 
                                                                                                                                  
DEBUG(:validate_version): ARGV[1]=USER, ARGV[2]=2.28.0.windows.1                                                                  
                                                                                                                                  
DEBUG(:parse_version): ARGV[1]=USER, ARGV[2]=2.28.0.windows.1                                                                     
                                                                                                                                  
DEBUG(:validate_version): Found Git Version for USER: 2.28.0.windows.1                                                            
                                                                                                                                  
DEBUG(Comparing:):                                                                                                                
                                                                                                                                  
DEBUG(USER:): 2.28.0.windows.1                                                                                                    
                                                                                                                                  
DEBUG(VENDORED:): 2.28.0.windows.1                                                                                                
                                                                                                                                  
DEBUG(Using found Git '2.28.0.windows.1' from 'C:\laragon\bin\git...):                                                            
                                                                                                                                  
DEBUG(Using Git from 'C:\laragon\bin\git...):                                                                                     
                                                                                                                                  
DEBUG(:enhance_path): Env Var INSIDE PATH C:\\laragon\\bin\\git\\cmd - found=1                                                    
                                                                                                                                  
DEBUG(:enhance_path): Env Var BEGIN PATH C:\\laragon\\bin\\git\\cmd - found=1                                                     
                                                                                                                                  
DEBUG(:enhance_path): Env Var INSIDE PATH C:\\laragon\\bin\\git\\mingw64\\bin - found=1                                           
                                                                                                                                  
DEBUG(:enhance_path): Env Var END PATH C:\\laragon\\bin\\git\\mingw64\\bin - found=1                                              
                                                                                                                                  
DEBUG(:enhance_path): Env Var INSIDE PATH C:\\laragon\\bin\\git\\usr\\bin - found=1                                               
                                                                                                                                  
DEBUG(:enhance_path): Env Var END PATH C:\\laragon\\bin\\git\\usr\\bin - found=1                                                  
                                                                                                                                  
DEBUG(init.bat): Env Var - git_locale="C:\laragon\bin\git\usr\bin\locale.exe"                                                     
                                                                                                                                  
DEBUG(init.bat): Env Var - GIT_INSTALL_ROOT=C:\laragon\bin\git                                                                    
                                                                                                                                  
DEBUG(init.bat): Found Git in: 'C:\laragon\bin\git'                                                                               
                                                                                                                                  
DEBUG(:enhance_path): Env Var INSIDE PATH C:\\laragon\\bin\\cmder\\vendor\\bin - found=0                                          
                                                                                                                                  
DEBUG(:enhance_path): Env Var BEGIN PATH C:\\laragon\\bin\\cmder\\vendor\\bin - found=0                                           
                                                                                                                                  
DEBUG(:enhance_path): Prepending 'C:\laragon\bin\cmder\vendor\bin'                                                                
                                                                                                                                  
DEBUG(:enhance_path): END Env Var - PATH=C:\laragon\bin\cmder\vendor\bin;C:\laragon\bin\cmder\vendor\conemu-maximus5\ConEmu\Script;C:\laragon\bin\cmder\vendor\conemu-maximus5\ConEmu;                                                      
                                                                                                                                  
DEBUG(:enhance_path): Env Var C:\\laragon\\bin\\cmder\\vendor\\bin - found=1                                                      
                                                                                                                                  
DEBUG(:enhance_path_recursive): Env Var - add_path=                                                                               
                                                                                                                                  
DEBUG(:enhance_path_recursive): Env Var - position=                                                                               
                                                                                                                                  
DEBUG(:enhance_path_recursive): Env Var - depth=0                                                                                 
                                                                                                                                  
DEBUG(:enhance_path_recursive): Env Var - max_depth=1                                                                             
                                                                                                                                  
DEBUG(:enhance_path): Env Var INSIDE PATH C:\\laragon\\bin\\cmder - found=0                                                       
                                                                                                                                  
DEBUG(:enhance_path): Env Var END PATH C:\\laragon\\bin\\cmder - found=0                                                          
                                                                                                                                  
DEBUG(:enhance_path): Appending 'C:\laragon\bin\cmder'                                                                            
                                                                                                                                  
DEBUG(:enhance_path): END Env Var - PATH=C:\laragon\bin\cmder\vendor\bin;C:\laragon\bin\cmder\vendor\conemu-maximus5\ConEmu\Script;C:\laragon\bin\cmder\vendor\conemu-maximus5\ConEmu;                             
                                                                                                                                  
DEBUG(:enhance_path): Env Var C:\\laragon\\bin\\cmder - found=1                                                                   
                                                                                                                                  
DEBUG(init.bat): Env Var - HOME=C:\Users\GiJoe
                                                                                                                                  
DEBUG(init.bat): Calling - C:\laragon\bin\cmder\config\user_profile.cmd                                                           
                                                                                                                                  
                                                                                                                                  
E:\ λ                                                                                                                             
```

The init.bat is the unmodified version from cmder(Version 1.3.16.1035)

**Comment by daxgames** [comment]
I do not see the `The process cannot access the file because it is being used by another` error in this output?  Is it popping up in a separate window?

Are you using `Cmder.exe` to launch this?

Can I get a screenshot of the error that includes the entire terminal window with debug turned on?

**Comment by daxgames** [comment]
I was interested in Laragon as I had never heard of it.  I downloaded and installed.  I then did the following from an external cmder install running  `cmder::Cmder as Admin`:

```
rename c:\laragon\bin\cmder cmder-1.3.2
mklink /d c:\laragon\bin\cmder %CMDER_ROOT%
```

This creates a symbolic link from Laragon pointing to my external Cmder install basically replacing Laragon's Cmder version.

Launch `Terminal` from Laragon.  I saw no error like you mentioned.

**Comment by daxgames** [comment]
The mklink fix is not a good way to fix the issue.  See: [Laragon Issue: #126](https://github.com/leokhoa/laragon/issues/126#issuecomment-691469768)

**Comment by waptik** [comment]
> I do not see the `The process cannot access the file because it is being used by another` error in this output? Is it popping up in a separate window?
> 
> Are you using `Cmder.exe` to launch this?
> 
> Can I get a screenshot of the error that includes the entire terminal window with debug turned on?

Yes, it is popping on separate window(s). I have opened 4 of them and most of the time it pops up in either 3 of them or both 4.
Yes, i use `Cmder.exe` which i pinned on my taskbar to launch this.
![cmder - process opened msg](https://user-images.githubusercontent.com/1687551/92994683-f7329280-f4eb-11ea-8a25-7c0ebabab963.jpg)

**Comment by waptik** [comment]
> The mklink fix is not a good way to fix the issue. See: [Laragon Issue: #126](https://github.com/leokhoa/laragon/issues/126#issuecomment-691469768)

I don't know he replaced his version of cmder but i did mine by completely deleting  `cmder` found in `c:\laragon\bin\` and installed the current version of `cmder` in it.

**Comment by daxgames** [comment]
The way you upgraded breaks Laragon extra tools paths.

Look at the pull request I added at Laragon github today for a better way to integrate Cmder into Laragon that allows upgrading Cmder using Cmders update instructions.  Also I responded to an open Laragon issue on github on updating Cmder.

**Comment by daxgames** [comment]
Just creat the laragon.cmd mentioned in the https://github.com/leokhoa/laragon/issues/126#issuecomment-691469768 to fix what you broke.

**Comment by daxgames** [comment]
You could add `2>&1` to yout `init.bat` command so they are like `"%conemudir%\..\init.bat" 2>&1 /d`.  This will redirect the STDERR to STDOUT so it mixes in with the debug output giving me some hints.

Alternatively you could also do `"%conemudir%\..\init.bat" 2>nul` but this might just mask an issue that might need to be fixed.

**Comment by waptik** [comment]
> The way you upgraded breaks Laragon extra tools paths.
> 
> Look at the [pull request](https://github.com/leokhoa/laragon/pull/199/files) I added at Laragon github today for a better way to integrate Cmder into Laragon that allows upgrading Cmder using Cmders update instructions. Also I responded to an open Laragon issue on github on updating Cmder. [leokhoa/laragon#126 (comment)](https://github.com/leokhoa/laragon/issues/126#issuecomment-691469768)

I followed your suggestion by creating a `%cmder_root%/config/profile.d.laragon.cmd` file and moved laragon's cmd code in it but didn't solve the issue with `process cannot access...` issue.


> You could add `2>&1` to yout `init.bat` command so they are like `"%conemudir%\..\init.bat" 2>&1 /d`. This will redirect the STDERR to STDOUT so it mixes in with the debug output giving me some hints.
> 
> Alternatively you could also do `"%conemudir%\..\init.bat" 2>nul` but this might just mask an issue that might need to be fixed.

I did the first one and here is the output
```sh
DEBUG(init.bat): Env Var - CMDER_ROOT=C:\laragon\bin\cmder

DEBUG(init.bat): Env Var - debug_output=1

DEBUG(init.bat): Looking for Git install root...

DEBUG(:read_version): Env Var - git_executable=C:\laragon\bin\cmder\vendor\git-for-windows\cmd\git.exe

DEBUG(:read_version): Env Var - GIT_VERSION_VENDORED=2.28.0.windows.1

DEBUG(:validate_version): ARGV[1]=VENDORED, ARGV[2]=2.28.0.windows.1

DEBUG(:parse_version): ARGV[1]=VENDORED, ARGV[2]=2.28.0.windows.1

DEBUG(:validate_version): Found Git Version for VENDORED: 2.28.0.windows.1

DEBUG(:read_version): Env Var - git_executable=C:\laragon\bin\git\cmd\git.exe

DEBUG(:read_version): Env Var - GIT_VERSION_USER=2.28.0.windows.1

DEBUG(:validate_version): ARGV[1]=USER, ARGV[2]=2.28.0.windows.1

DEBUG(:parse_version): ARGV[1]=USER, ARGV[2]=2.28.0.windows.1

DEBUG(:validate_version): Found Git Version for USER: 2.28.0.windows.1

DEBUG(Comparing:):

DEBUG(USER:): 2.28.0.windows.1

DEBUG(VENDORED:): 2.28.0.windows.1

DEBUG(Using found Git '2.28.0.windows.1' from 'C:\laragon\bin\git...):

DEBUG(Using Git from 'C:\laragon\bin\git...):

DEBUG(:enhance_path): Env Var INSIDE PATH C:\\laragon\\bin\\git\\cmd - found=1

DEBUG(:enhance_path): Env Var BEGIN PATH C:\\laragon\\bin\\git\\cmd - found=1

DEBUG(:enhance_path): Env Var INSIDE PATH C:\\laragon\\bin\\git\\mingw64\\bin - found=1

DEBUG(:enhance_path): Env Var END PATH C:\\laragon\\bin\\git\\mingw64\\bin - found=1

DEBUG(:enhance_path): Env Var INSIDE PATH C:\\laragon\\bin\\git\\usr\\bin - found=1


DEBUG(:enhance_path): Env Var END PATH C:\\laragon\\bin\\git\\usr\\bin - found=1

DEBUG(init.bat): Env Var - git_locale="C:\laragon\bin\git\usr\bin\locale.exe"

DEBUG(init.bat): Env Var - GIT_INSTALL_ROOT=C:\laragon\bin\git

DEBUG(init.bat): Found Git in: 'C:\laragon\bin\git'

DEBUG(:enhance_path): Env Var INSIDE PATH C:\\laragon\\bin\\cmder\\vendor\\bin - found=0

DEBUG(:enhance_path): Env Var BEGIN PATH C:\\laragon\\bin\\cmder\\vendor\\bin - found=0

DEBUG(:enhance_path): Prepending 'C:\laragon\bin\cmder\vendor\bin'

DEBUG(:enhance_path): END Env Var - PATH=C:\laragon\bin\cmder\vendor\bin;C:\laragon\bin\cmder\vendor\conemu-maximus5\ConEmu\Scripts;C:\laragon\bin\cmder\vendor\conemu-maximus5;C:\laragon\bin\cmder;(....)


DEBUG(:enhance_path): Env Var C:\\laragon\\bin\\cmder\\vendor\\bin - found=1

DEBUG(:enhance_path_recursive): Env Var - add_path=

DEBUG(:enhance_path_recursive): Env Var - position=

DEBUG(:enhance_path_recursive): Env Var - depth=0

DEBUG(:enhance_path_recursive): Env Var - max_depth=1

DEBUG(:enhance_path): Env Var INSIDE PATH C:\\laragon\\bin\\cmder - found=0

DEBUG(:enhance_path): Env Var END PATH C:\\laragon\\bin\\cmder - found=0

DEBUG(:enhance_path): Appending 'C:\laragon\bin\cmder'

DEBUG(:enhance_path): END Env Var - PATH=C:\laragon\bin\cmder\vendor\bin;C:\laragon\bin\cmder\vendor\conemu-maximus5\ConEmu\Scripts;C:\laragon\bin\cmder\vendor\conemu-maximus5;C:\laragon\bin\cmder;(....)

DEBUG(:enhance_path): Env Var C:\\laragon\\bin\\cmder - found=1

C:\laragon\bin\cmder
DEBUG(init.bat): Env Var - HOME=C:\Users\user

DEBUG(init.bat): Calling - C:\laragon\bin\cmder\config\user_profile.cmd
```

**Comment by daxgames** [comment]
`%cmder_root%/config/profile.d.laragon.cmd` or `%cmder_root%/config/profile.d/laragon.cmd`

It should be the second path.

This fix is not to fix the error message you are complaining about it is to allow Cmder embedded in Laragon to be updated and still retain Laragon features.

**Comment by daxgames** [comment]
I still don't have any idea what is causing the message.  Could you paste in the text of the script you have in Conemu to start your split panes into here?

**Comment by waptik** [comment]
So using this `"%conemudir%\..\init.bat" 2>nul"` command in my task command, displays the current path at the top as seen in the screenshot below
![cmder - with 2nul](https://user-images.githubusercontent.com/1687551/92999357-b8aecf00-f50f-11ea-82c7-feffb90cf7b3.jpg)

**Comment by waptik** [comment]
> %cmder_root%/config/profile.d/laragon.cmd

Sorry, i meant `%cmder_root%/config/profile.d/laragon.cmd`

> I still don't have any idea what is causing the message. Could you paste in the text of the script you have in Conemu to start your split panes into here?

This is found in Settings >Startup > auto saved/reoponed tabs

```sh
-cur_console:d:C:\laragon\bin\cmder -cur_console:C:C:\laragon\bin\cmder\icons\cmder.ico cmd /k ""%ConEmuDir%\..\init.bat" 2>nul"

-cur_console:ns1T50H -cur_console:d:C:\laragon\bin\cmder -cur_console:C:C:\laragon\bin\cmder\icons\cmder.ico "C:\WINDOWS\SYSTEM32\cmd.exe"  /k ""%ConEmuDir%\..\init.bat" 2>nul"

-cur_console:bns1T50V -cur_console:d:C:\laragon\bin\cmder -cur_console:C:C:\laragon\bin\cmder\icons\cmder.ico "C:\WINDOWS\SYSTEM32\cmd.exe"  /k ""%ConEmuDir%\..\init.bat" 2>nul"

> -cur_console:ns2T50V -cur_console:d:C:\laragon\bin\cmder -cur_console:C:C:\laragon\bin\cmder\icons\cmder.ico "C:\WINDOWS\SYSTEM32\cmd.exe"   /k ""%ConEmuDir%\..\init.bat" 2>nul"
```

And this in Settings > Startup > Tasks > Cmd:Cmder
`cmd /k ""%ConEmuDir%\..\init.bat" 2>nul"`

**Comment by daxgames** [comment]
> So using this `"%conemudir%\..\init.bat" 2>nul"` command in my task command, displays the current path at the top as seen in the screenshot below
> ![cmder - with 2nul](https://user-images.githubusercontent.com/1687551/92999357-b8aecf00-f50f-11ea-82c7-feffb90cf7b3.jpg)

So that is caused by `Laragon.cmd` the `findstr` command should have. ` >nul` at the end.  I'll fix that in my PR.

**Comment by waptik** [comment]
> > So using this `"%conemudir%\..\init.bat" 2>nul"` command in my task command, displays the current path at the top as seen in the screenshot below
> > ![cmder - with 2nul](https://user-images.githubusercontent.com/1687551/92999357-b8aecf00-f50f-11ea-82c7-feffb90cf7b3.jpg)
> 
> So that is caused by `Laragon.cmd` the `findstr` command should have. ` >nul` at the end. I'll fix that in my PR.

Alright! I'm okay with how it is for now until a permanent solution is found. It's way better than having `the process cannot ....` message popping up.
Whether i am the only who is facing this issue or not, but i'm i asked for help and finding a temporary  fix!
Thankd so far for your help @daxgames

**Comment by daxgames** [comment]
@waptik can you do me a favor and comment on the pr at https://github.com/leokhoa/laragon/pull/199 to let the Laragon dev know it works for you and allowed you to update Cmder to current.

**Comment by waptik** [comment]
> @waptik can you do me a favor and comment on the pr at [leokhoa/laragon#199](https://github.com/leokhoa/laragon/pull/199) to let the Laragon dev know it works for you and allowed you to update Cmder to current.

Okay, i'll do that right away. Have you fixed the PR?

**Comment by daxgames** [comment]
I did fix the pr.  It does not fix the split tabs issue.

**Comment by waptik** [comment]
Ok. I'll mention an upgrade of conEmu from the GUI would fix that.

**Comment by daxgames** [comment]
@Waptik I modified the PR once again that puts the laragon cmder config mainly in `[laragon]/etc/cmder/laragon.cmd` this is better for the Laragon dev in the long run.  Please take a look.

Cmder has a policy to never touch anything in the users `%cmder_root%\config` folder and this change allows the laragon dev to change the cmder laragon init without touching files in this folder.

**Comment by daxgames** [comment]
@waptik I found the code causing the message you are complaining about.

```
DEBUG(:validate_version): Found Git Version for VENDORED: 2.28.0.windows.1

DEBUG(:read_version): Env Var - git_executable=C:\Program Files (x86)\git\cmd\git.exe

The process cannot access the file because it is being used by another process.
DEBUG(:read_version): Env Var - GIT_VERSION_USER=2.27.0.windows.1

DEBUG(:validate_version): ARGV[1]=USER, ARGV[2]=2.27.0.windows.1
```

It is fixed and will be available in the next release of Cmder.

**Comment by waptik** [comment]
> @waptik I found the code causing the message you are complaining about.
> 
> ```
> DEBUG(:validate_version): Found Git Version for VENDORED: 2.28.0.windows.1
> 
> DEBUG(:read_version): Env Var - git_executable=C:\Program Files (x86)\git\cmd\git.exe
> 
> The process cannot access the file because it is being used by another process.
> DEBUG(:read_version): Env Var - GIT_VERSION_USER=2.27.0.windows.1
> 
> DEBUG(:validate_version): ARGV[1]=USER, ARGV[2]=2.27.0.windows.1
> ```
> 
> It is fixed and will be available in the next release of Cmder.

Thanks!
