### ISSUE TITLE
CMDER_ROOT environment variable is not set when launching Powershell as admin console

### ISSUE THREAD

**Issue by fireph** [cmderdev/cmder#2392]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

Cmder Version: 1.3.16
ConEmu Version: 200713

### Description of the issue

When launching Powershell as an admin console (ex: `-new_console:a:d:C:\Users\username PowerShell ...`), the environment variable CMDER_ROOT is not set. It is set correctly when launching a console not as admin (ex: `-new_console:d:C:\Users\username PowerShell ...`)

**Comment by daxgames** [comment]
@fireph Works for me

![image](https://user-images.githubusercontent.com/7318053/98372066-2e648200-200b-11eb-988c-d86064adba2a.png)
