### ISSUE TITLE
[bug] Running `alias ..=cd ..` removes other aliases

### ISSUE THREAD

**Issue by xy2z** [cmderdev/cmder#2394]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information
- **Cmder:** Version 1.3.16.1035
- **OS:** Windows 10 Pro (version 1909)

### Description of the issue

**⚠ Warning: This may remove your custom aliases.**
1. Run `alias ..=cd ..`
2. Restart cmder
3. Open cmder and run `alias` - some of your aliases have been removed.

### Screenshots
![before](https://user-images.githubusercontent.com/4496997/94363161-a52f6680-00c0-11eb-91c0-53026dc61e0d.PNG)
(restart cmder)

![after](https://user-images.githubusercontent.com/4496997/94363162-a6f92a00-00c0-11eb-8f22-046c574e5744.PNG)

**Comment by xy2z** [comment]
pls fix

**Comment by daxgames** [comment]
@xy2z Works for me.

![image](https://user-images.githubusercontent.com/7318053/98371677-91a1e480-200a-11eb-94da-6726cb61ac63.png)

**Comment by xy2z** [comment]
@daxgames did you restart cmder?

**Comment by daxgames** [comment]
In the screenshot above , no.  I have since restarted though and it works fine. All aliases are there..

**Comment by daxgames** [comment]
or maybe not.

**Comment by daxgames** [comment]
Looks like it removes all 2 character aliases from the file.

**Comment by chrisant996** [comment]
> Looks like it removes all 2 character aliases from the file.

Oh, probably something is using the alias name in a regular expression to remove it, but neglected to escape the alias name.  And then the `.` characters are interpreted as "match any character" by the regular expression.

For example, probably `alias .d=abc` will remove all two character aliases where the second character is `d`.

**Comment by daxgames** [comment]
Fixed in #2449

**Comment by chrisant996** [comment]
Oh, it's using `findstr`. FWIW then, an even easier and more thorough fix could be to use the `/l` flag (and the `/b` flag) to disable regex evaluation, since it's trying to do a literal search.

**Comment by daxgames** [comment]
@chrisant996 My fix works, yours is better and may go in a future change.

Did you see the bug report on 1.3.17 release 1ith Clink 1.1.10 reg clink settings and history?  Not really a bug but if you have suggestions on how to best handle from Cmder side it would be helpful.
