### ISSUE TITLE
λ prompt not displayed correctly for PowerShell

### ISSUE THREAD

**Issue by satorp** [cmderdev/cmder#2395]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

Cmder 1.3.16.1035

Windows 10 Pro 1909

### Description of the issue

On PowerShell task the λ prompt is not displayed correctly.
![cmder-lambda](https://user-images.githubusercontent.com/10983684/94363841-fd398d80-00ff-11eb-9d0e-438a84b8ae99.png)

This seems to be caused by the encoding of profile.ps1 has been changed to UTF8 without BOM, which causes PowerShell to assume the encoding to be the system encoding. This issue does exist in version 1.3.14.982 where the file encoding was UTF8 with BOM.

**Comment by erdnuesse** [comment]
Hi, had a similar encoding issue in the terminal window. 
However, resaving as UTF-8-BOM in NP++ didn't do anything for me. 

My Workaround:
Took the hint, and changed line breaks from unix in user_profile.ps1 to windows instead - did the trick for me. 

To anyone new to the matter: 

- open user_profile.ps1 in notepad++ (open source, portable/no installation needed if that's an issue)
- check in the bottom for this: 
![image](https://user-images.githubusercontent.com/4510296/96237804-051d7c80-0f9e-11eb-94d7-6f64f49ea99a.png)
- Right-Click on Unix, select Windows (if running on windows (no emulation), obviously) and save the file. 
- On next Powershell start, it should be fixed. 
However, the file should be created with right encodings nonetheless. 

Regards, K

**Comment by BClev** [comment]
@satorp  's fix worked for me.

**Comment by orazdow** [comment]
Is it possible to get a custom prompt using cmd.exe, or is that only possible with a tab using powershell? (the cmd tab is noticeably faster, but without the customization).

**Comment by daxgames** [comment]
@orazdow The `cmd::Cmder` prompt is a custom prompt in cmd.exe.  Cmder uses clink to define custom prompts in `cmd::Cmder` sessions.  you can customixe it further by creating your own custom `%cmder_root%\cmder\prompt.lua`.  Search for it you will find others that have.
