### ISSUE TITLE
cmder ssh auto disconnect, please help me. 

### ISSUE THREAD

**Issue by hhniao** [cmderdev/cmder#2396]
i have two computer, all of it is runing on window 10.
ssh connect to my server. i have only one server.
computer one, ssh connect to my server, dont disconnect ssh forever.
computer two, ssh connect to my server. it will be auto disconnect, when i have no any action.

i have try to resolve it.

    cp computer_one/cmder computer_two/cmder

this method is not work.

please help me how to resolve it, make connect always live.
if you have any suggest/good idea for resolve it, please tell me.

im sorry for bad english.
because my bad english, so i cant search any result from stackoverflow and google(in fact, i cant access google, because it is ban by china gov.).

**Comment by hhniao** [comment]
btw, if you know what my question and have a free time to update my question.
please edit my question.

**Comment by daxgames** [comment]
`cp computer_one/cmder computer_two/cmder` is an invalid command are you sure it did what you thought?

What type of session are you using `cmd::Cmder`, `bash::bash`, or `powershell::powershell`?

Does either computer have an `%userprofile%\.ssh\config` file and do the contents match?

**Comment by hhniao** [comment]
@daxgames 
`cp computer_one/cmder computer_two/cmder` 
this is a fake command, it mean copy file from a computer to another computer.

shell: 

    {cmd::Cmder}

![image](http://www.lipin200.com/cmder_setting.png)


    cd /c/Users/Administrator/.ssh
    ls -a
    ./  ../  id_rsa  id_rsa.pub  known_hosts

![image](http://www.lipin200.com/ssh_dir.png)

**Comment by daxgames** [comment]
@hhniao Can you provide a screenshot of the output to `where ssh` from each session.

**Comment by hhniao** [comment]
@daxgames thanks for your reply. 
i give up to fix it already
