### ISSUE TITLE
No efficient way to search existing tickets (filtering out resolved issues)

### ISSUE THREAD

**Issue by Chealer** [cmderdev/cmder#2400]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [X] Feature request (request for new functionality)
- [ ] Question

### Version Information
N/A

### Description of the issue
The issue reporting template requests reporters to search "for existing issues (including the **closed** ones) for the similar problems". At this time, this searches nearly 2000 tickets, whether or not these are about problems affecting the reporter's Cmder version. Given that the search filtering is very basic, this can be highly time-consuming.

Please use an ITS which allows searching only issues affecting a certain version, by filtering out tickets about issues marked as resolved in an earlier version.

**Comment by Chealer** [comment]
Is there a reason this ticket is closed?

**Comment by daxgames** [comment]
Because we are not Github and we use the issue tracking system Github provides, it is an invalid request as noted by the label.

**Comment by Chealer** [comment]
@daxgames a ticket's validity is determined by the existence or absence of the issue it reports. Validity has nothing to do with difficulty.

Thanks for unsetting the "Is Invalid" label

**Comment by Chealer** [comment]
@daxgames, thank you for reopening this ticket and unsetting the "Is Invalid" label.

**Comment by chrisant996** [comment]
@Chealer is there an example of such an ITS that you can share, which is free and can import from github's ITS and integrate with github?

**Comment by Chealer** [comment]
I am very sorry but I unfortunately do not know any such ITS engine which supports version tracking @chrisant996 
In fact, the only free ITS engine with version tracking that I know is Debbugs... which would be a horrible choice :-(

However, there are multiple free ITS engines which would fulfill this request in its basic sense (as formulated in the title). Redmine is one, and is also one of the most interesting ITS engines. That being said, Redmine is more than an ITS engine (which may be as good as bad, but possibly bad for Cmder), and I know nothing about its GitHub integration capabilities (I will only point to [this page](https://zapier.com/apps/github/integrations/redmine), which _suggests_ that may be possible).

**Comment by chrisant996** [comment]
Great, thanks, @Chealer . I imagine that Cmder will probably not want to change out the ITS unless something imports and integrates with github -- i.e. is seamlessly hosted within the github web pages.

If something can't be suggested that fits the team's criteria, then I hope it will be understandable if the Cmder team chooses to close the issue as "won't fix". I'm not saying they will; I'm only suggesting that it's usually desirable to close an issue if no action will be taken, so it's a possibility.

**Comment by daxgames** [comment]
I am confused.  This issue is already closed and has been since 9/30/2020.

There is nothing we can do to accomadate this request.

**Comment by chrisant996** [comment]
> I am confused.  This issue is already closed and has been since 9/30/2020.
> 
> There is nothing we can do to accomadate this request.

Oh I misread, sorry - I thought you had reopened it. You only removed the Invalid tag.
