### ISSUE TITLE
Selecting more than a window of text (for copying) is sluggish (scrolls slowly)

### ISSUE THREAD

**Issue by Chealer** [cmderdev/cmder#2401]
### Purpose of the issue
- [X] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information
Cmder 1.3.16.1035
ConEmu 191012 [64]

OsVer: 10.0.18363.x64

### Description of the issue
Trying to select text which spans many lines with the mouse (as one would do with other terminals) takes a lot of time in Cmder, as the visible area only moves up or down 1 line at a time, and each line takes significant time. This is best described in the ticket reporting the corresponding issue in ConEmu, Maximus5/ConEmu#1413.

An efficient workaround exists:
1. Press the mouse's primary (left) button
2. Move the cursor a bit (until some text is selected)
3. Hold down _Ctrl_ and _Shift_
4. Press Up or Down, until the end of the selection is visible
5. Release _Ctrl_ and _Shift_
6. Move the cursor to the end of the selection
7. Release the mouse's primary (left) button

Based on the fact that the underlying ConEmu issue seems to be a bug (it is a regression), I am marking this as a bug report. Please mark this issue as important.

**Comment by Chealer** [comment]
@daxgames: why was this ticket closed?

**Comment by daxgames** [comment]
@Chealer Because we maintain Cmder not Conemu and we do not fix issues in Conemu.

**Comment by Chealer** [comment]
@daxgames this ITS is not "your" issue tracker, it is Cmder's. It tracks Cmder issues, no matter if "you" fix them or not. No matter if _anyone_ fixes them or not.

**Comment by daxgames** [comment]
This ITS IS for Cmder issues, I am a one of the maintainers of Cmder.  It IS NOT a Cmder issue, it cannot be fixed bu us, that IS why it is closed.

**Comment by Chealer** [comment]
@daxgames: Of course it's a Cmder issue, why would it be reported against it if it was not? Of course it can be fixed by "you" (given the necessary skill).

Since you're a Cmder maintainer, thanks for marking this issue as important once the ticket is reopened, so it shows prominently.

**Comment by chrisant996** [comment]
The issues list in the ConEmu repo is for tracking work in the ConEmu code.

The issues list in the Cmder repo is for tracking work in the Cmder code.

The issue in question is in ConEmu code, not in Cmder code. Therefore it belongs in the ConEmu repo, not here.

This is a standard convention, and it's about keeping track of work in the place where the work needs to be done. It has nothing to do with who does the work. It is purely about tracking work in an organized manner.

**Comment by daxgames** [comment]
@Chealer I am locking this issue to prevent further comment as it is off topic as stated by myself and much more eloquently by @chrisant996.

The issue has been reported where it should and if and when it is addressed by the Conemu developers we will include those fixes in a newer release of Cmder.

Thanks for your interest.
