### ISSUE TITLE
Cmder does not work on current Windows Insider builds due to Clink injection failing

### ISSUE THREAD

**Issue by nikitalita** [cmderdev/cmder#2403]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

Cmder: 1.3.16
ConEmu: 191012

Windows 10 Pro Insider Build 20226
### Description of the issue

This is mostly an issue to keep track of the insider build issue since all the other ones are closed.

Cmder does not work on current Windows Insider builds due to Clink injection failing.

Upstream issue: https://github.com/mridgers/clink/issues/543#issuecomment-703037833

The problem is that Kernelbase.dll has changed significantly in the current Insider builds (since at least 20150), so clink is failing to inject due to being unable to patch Kernelbase.dll for ReadConsoleW.

I have created a PR that fixes this here on your clink fork: https://github.com/cmderdev/clink/pull/2

**Comment by nikitalita** [comment]
See also: #2341 #2347

**Comment by nikitalita** [comment]
Broke again on build 20246, here's a PR with an updated patch: https://github.com/cmderdev/clink/pull/3

**Comment by nikitalita** [comment]
it's still active!

**Comment by nikitalita** [comment]
This is fixed by #2441, but I'll wait until a release to close it.

**Comment by daxgames** [comment]
1.3.17 released
