### ISSUE TITLE
powerline fonts can't effect in cmder setting 'Main console font' option

### ISSUE THREAD

**Issue by lovelyJason** [cmderdev/cmder#2406]
this is some amazing software and I'd like to continue using it,but I don't know why this problem happened?

when I use 'sudo apt-get install fonts-powerline' or 'git clone https://github.com/powerline/fonts.git --depth=1' and then the fonts installed successfully.like this

![Snipaste_2020-10-13_13-28-39](https://user-images.githubusercontent.com/50656459/95819218-107f6680-0d58-11eb-991d-5768ffbb5b51.png)()

but when I open the setting option 'General --> Fonts --> Main console font', it's like this

![Snipaste_2020-10-13_13-31-43](https://user-images.githubusercontent.com/50656459/95819386-7835b180-0d58-11eb-90c7-4e0427070439.png)()

there is no powerline fonts installed.please tell me why that happed.Thanks!

**Comment by daxgames** [comment]
It happened because you are not installing fonts the way windows expects you to install them.  Lookup installing fonts on Windows.
