### ISSUE TITLE
use custom autocomplete configs

### ISSUE THREAD

**Issue by maximousblk** [cmderdev/cmder#2407]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [x] Question

### Version Information

**Cmder:** Version 1.3.16.1035

### Description of the issue

Is there a way to use bash autocomplete files or any custom autocomplete configuration other that those already in clink? If so, how to do it?

**Comment by daxgames** [comment]
Bash is a shell clink is a cmd.exe shell enhancement.  Bash and clink are not used together.  I am not aware of any use of bash completion in Git for Windows Bash shells which is what Cmder uses for Bash shell.

**Comment by daxgames** [comment]
@maximousblk you can write clink completions.  See: https://github.com/vladimir-kotikov/clink-completions
