### ISSUE TITLE
Error messages when starting cmder

### ISSUE THREAD

**Issue by maplegate** [cmderdev/cmder#2408]
When I start cmder on Windows 10 Pro, I see 20 of the following lines:

    'MySQL' is not recognized as an internal or external command, operable program or batch file.

There are no other warnings, and cmder seems to be working fine.  I cannot locate the script or whatever which cmder is trying to execute which is throwing these warnings.

**Comment by daxgames** [comment]
My guess is you have a path with spaces in it that are unquoted in your `%path%` environment variable and Cmder is not handling it well.

Output of `set path`?

**Comment by daxgames** [comment]
@maplegate ???

**Comment by daxgames** [comment]
Closing for lack of reaponse from @maplegate
