### ISSUE TITLE
Error when compiling g++ in VSCode ( integrate )

### ISSUE THREAD

**Issue by harris1111** [cmderdev/cmder#2411]
Firstly, I want to thank all of you guys for making this beautiful terminal for Windows <3 

Im using VSCode for compiling C++ ( file ) in Windows, in which settings. json and tasks.json is as below.
but when I compile using Ctrl+shift+B, it shows error "The syntax of the command is incorrect." (image below), but when I compile manually using g++ *.cpp, it compile succesfully as usual. ( and if I delete cmder and use default cmd, it's also success).

Any help appreciate.
Thanks.
![image](https://user-images.githubusercontent.com/52365112/97662559-04124200-1aaa-11eb-9a7f-39a8acd3cfae.png)

![image](https://user-images.githubusercontent.com/52365112/97662536-f492f900-1aa9-11eb-8572-4fbe642ba79f.png)
![image](https://user-images.githubusercontent.com/52365112/97662725-68350600-1aaa-11eb-92f6-2c25375514e7.png)

**Comment by daxgames** [comment]
Have you looked at: https://github.com/cmderdev/cmder/wiki/Seamless-VS-Code-Integration

I don't know if it will help but it is is the recommended way to integrate with VS Code.

Also does the behavior change if not integrating Cmder?

**Comment by harris1111** [comment]
Yes, I follow all the guide written in there, you will see if you see the second picture. Everything work just fine, Git, or build cpp file manually by using g++ name.cpp, but when I run build tool using ctrl shift B or ctrl f5 in vscode, it say like the third picture.

**Comment by harris1111** [comment]
and if not integrating Cmderm, eveything works fine.

**Comment by daxgames** [comment]
I asked about the wiki because your vscode shell settings are different than those in the wiki.

**Comment by daxgames** [comment]
The settings should be:

```
"terminal.integrated.shell.windows": "cmd.exe",
    "terminal.integrated.shellArgs.windows": [
      "/K",
      "%CMDER_ROOT%\\vendor\\bin\\vscode_init.cmd"
    ],
```

**Comment by harris1111** [comment]
OMG it really works. I misunderstand vscode_init vs init, so that it runs into problem. Thank you for your support.
Have a nice day.

**Comment by daxgames** [comment]
No problem.  Glad to help.
