### ISSUE TITLE
[question] how to return to the previous directory

### ISSUE THREAD

**Issue by taseikyo** [cmderdev/cmder#2413]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Description of the issue

```
F:\test
λ cd foo1\sub-foo1\

F:\test\foo1\sub-foo1
λ cd -
The system cannot find the path specified.
```

When I type `cd -` in the `F:\test\foo1\sub-foo1` directory, I want to return to the previous directory `F:\test` (just like in Linux Bash). Is it possible?
#2074 solves the problem of `cd ~`, which is not what I want.

**Comment by daxgames** [comment]
![image](https://user-images.githubusercontent.com/7318053/98370234-44247800-2008-11eb-870b-5431384f7ecd.png)
