### ISSUE TITLE
Log info shows up every time VS Code terminal is opened.

### ISSUE THREAD

**Issue by atiyar** [cmderdev/cmder#2415]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [x] Question

### Version Information
Cmder - 1.3.16
VS Code - 1.50.1
Windows 10 Pro - 20H2

### Description of the issue
I was using Cmder v1.3.14 integrated in VS Code. When I opened the terminal this is what it looked like -

![cmder_1 3 14](https://user-images.githubusercontent.com/20378536/98041292-e2b7aa00-1e4b-11eb-9976-c771520ad080.png)

Now I'm using Cmder v1.3.16 and whenever I run VS Code and open the terminal, it shows some log info every time -

![cmder_1 3 16](https://user-images.githubusercontent.com/20378536/98041731-9f117000-1e4c-11eb-9de5-f70fbcbcb19f.png)

If I kill the terminal and reopen it, those lines would show up again, and it is annoying those lines cluttering the terminal. How can I stop those lines showing up?

My settings.json contains -
```
"terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
"terminal.integrated.shellArgs.windows": [
	"/k",
	"C:\\Programs\\Cmder\\vendor\\bin\\vscode_init.cmd"
],
```

**Comment by daxgames** [comment]
You can 'fix' this by editing "C:\\Programs\\Cmder\\bin\\vscode_init_args.cmd" and change `set verbose_output=1` to `set verbose_output=`0`.

**Comment by daxgames** [comment]
and if you want comment `Applying Cmder VSCode settings from '%~0'...`.

It is just verbose output to educate users thay have a way to control how Cmder is configured in vscode.  Something new to version 1.3.16.
