### ISSUE TITLE
About window10 paste folder path

### ISSUE THREAD

**Issue by uphg** [cmderdev/cmder#2416]
I installed cmder on windows 10 and started it with bash. I found that it always carries `/mnt` every time I paste the directory of the file manager, such as when I copy the `/c/documents/` path under the file manager, when I paste It will become `/mnt/c/documents/`. But I don’t need `/mnt` because adding `/mnt` jump under window10 will cause jump command error, although I can delete it manually, but I still hope to find the prohibition The method of carrying the `/mnt` path when pasting.

**Comment by jspffms** [comment]
Would you mind telling me how to solve this problem?

**Comment by daxgames** [comment]
No, as far as I know it is a function of the bash shell on  windows and is not a resukt of anything in Cmder

**Comment by uphg** [comment]
> 你介意告诉我如何解决这个问题吗？

我还没有解决，不过我一般用 [z](https://github.com/rupa/z) 命令跳转目录

**Comment by uphg** [comment]
> Would you mind telling me how to solve this problem?

我还没有解决，不过我一般用 [z](https://github.com/rupa/z) 命令跳转目录
