### ISSUE TITLE
cmder 1.3.14.982

### ISSUE THREAD

**Issue by Phantom0410** [cmderdev/cmder#2418]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

**Comment by Phantom0410** [comment]
the lastest version is getting detected as a hacktool, malicious exe over detection engine but the older version was not getting detected.

**Comment by MartiUK** [comment]
You need to report to your virus vendor that it is a false positive, we can't do anything from here unfortunately.
