### ISSUE TITLE
cmder timeout cmnd is overlapping windows timeout

### ISSUE THREAD

**Issue by ctf0** [cmderdev/cmder#2419]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

cmder v1.3.2
ConEmu v161206

Windows 10 Pro 1909

### Description of the issue

cmder `timeout` is overlapping windows internal `timeout` ex.

- cmder
```
timeout --help
Usage: timeout [OPTION] DURATION COMMAND [ARG]...
  or:  timeout [OPTION]
Start COMMAND, and kill it if still running after DURATION.
```

- windows
```
timeout /?

TIMEOUT [/T] timeout [/NOBREAK]

Description:
    This utility accepts a timeout parameter to wait for the specified
    time period (in seconds) or until any key is pressed. It also
    accepts a parameter to ignore the key press.
```

so how to disable this in cmder or tell cmder to use the windows version instead ?

**Comment by MartiUK** [comment]
You can override your aliases in the config folder, alias `timeout` to windows' timeout and maybe `gtimeout` to gnu timeout

**Comment by ctf0** [comment]
@MartiUK could u plz give me an example of what to be added ?

**Comment by daxgames** [comment]
```
alias timeout=[path to windows timeout]
alias gtimeout=[path to gnu timeout]
```

**Comment by ctf0** [comment]
@daxgames thank you so much
