### ISSUE TITLE
Blue screen everywhere

### ISSUE THREAD

**Issue by Ruan29** [cmderdev/cmder#2420]
Just need help with it. When first installed cmder i just got some firmware update message. Now everytime i restart my computer i get firmware update for the same version. I cant delete cmder folder, it gives me blue screen. I cant change cmder folder to another directory, it gives me blue screen. I searched on all places, tried to delete folder from regedit, but there's no folder over there. Please, help
Update: after restarting i cant initiate windows. Stuck on automatic repair. Can't restore, cant rewind to recover point, cant system restore...

**Comment by MartiUK** [comment]
cmder does not request you to update any firmware, unless you didn't download it from github? Either way I can't help you any more than this sorry.

**Comment by Ruan29** [comment]
I didn't download it from github. I get it from cmder.net. Unless this don't belong to you guys?

**Comment by daxgames** [comment]
That is us but Cmder does not do what you detailed in your issue.  Cmder has nothing to do with firmware.

**Comment by Ruan29** [comment]
I only got this problem after dealing with cmder. I have no doubt that it does not have anything to do with firmware, but that was what happened, and probably other people could have it too. Anyway, I lost everything stored, it corrupted many system files and I couldn't even restore or backup any file. I appreciate you guys answers but the way the cmder folder behaved was something to look at, perhaps other people could face this too.
