### ISSUE TITLE
change or disable keyboard shortcuts?

### ISSUE THREAD

**Issue by llaenowyd** [cmderdev/cmder#2421]
I have ctrl-` bound already in my IDE, but now when I try it, cmder steals the window focus and comes to the front.

Is there a way to change or disable this setting?

**Comment by akospasztor** [comment]
I had the same issue. You can easily remap it in the settings, under the Keys & Macro menu. The shortcut that you need to remap is the Global-type Minimize/Restore.

![2020_11_27_16_02_59-Cmder ](https://user-images.githubusercontent.com/6011126/100462207-34a9c380-30ca-11eb-9e92-0dc090a89861.jpg)

**Comment by llaenowyd** [comment]
Thank you! I should have noticed this, I was looking at the "Keyboard" child, but didn't click into this one.
