### ISSUE TITLE
Assertion error on copy

### ISSUE THREAD

**Issue by cdalexndr** [cmderdev/cmder#2422]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information
Cmder Version 1.3.16.1035
ConEmu 191012

### Description of the issue

1. place cursor on some line above prompt
2. CTRL+SHIFT+DOWN until reaching end of terminal
3. CTRL+C to copy text
4. assertion error
![cdmer_assert](https://user-images.githubusercontent.com/22418250/99916664-192e6980-2d14-11eb-9d21-ea7fac6c7e6a.png)

**Comment by daxgames** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem or have a question, please open an issue over at https://github.com/Maximus5/ConEmu

Thank you! :-)
