### ISSUE TITLE
How sed works on Windows

### ISSUE THREAD

**Issue by moniuch** [cmderdev/cmder#2423]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Version Information

Windows 8.1

### Description of the issue

I am not asking for support here. I am asking maybe for better docs to help me understanding whether there is any difference in `sed` implementation, compared to bash/unix, as I am getting the following usage comments: https://superuser.com/questions/1605948/cannot-get-result-of-sed-pipe-as-argument-for-cd/1605958

Unfortunately, with my limited knowledge about the inner side of things, I cannot really understand how `sed` should work on Windows/cmder

**Comment by daxgames** [comment]
'sed' is provided by Git for Windows via mingw  the only thing I can refer you to is the command line help and any dics provided by the Git for Windows or mingw teams.
