### ISSUE TITLE
wslbridge error: failed to start backend process

### ISSUE THREAD

**Issue by thapaliyad** [cmderdev/cmder#2424]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

Version 1.3.14.982

Windows 10 Enterprise
1909
18363.1198
### Description of the issue

After the latest windows patch update, cmder {wsl::bash} stopped working on my system.

I downloaded the latest version and tried running the {wsl::bash}; that's also not working

======================================
Error message:
-----------------
wslbridge error: failed to start backend process
note: backend error output: -v: -c: line 0: unexpected EOF while looking for matching `''
-v: -c: line 1: syntax error: unexpected end of file

ConEmuC: Root process was alive less than 10 sec, ExitCode=0.
Press Enter or Esc to close console...

==========================================================

However, {shells::cmd} is working from where I still can navigate to wsl ((open cmd, type bash, and get the wsl)).
Does this mean wslbridge became incompatible after the update? 

Is there any fix for this "wslbridge error"

**Comment by daxgames** [comment]
`Wsl::bash` has nothing to do with cmder other than being a  session that is presented in the menu.  If there is an issue it needs to be brouggt to the conemu developers attention.

**Comment by IP-Developer** [comment]
https://conemu.github.io/en/wsl.html#wsl2
