### ISSUE TITLE
Cannot make Cmder.exe as Default shell for remote ssh connections

### ISSUE THREAD

**Issue by PeterKarlster** [cmderdev/cmder#2425]
Hi,

On my Windows 10 nodes, I am trying to use cmder.exe as the default Openssh Server shell but it is not working, the connection is instantly closed by the server when I try to login to a node from my linux machine.

If I change Computer\HKEY_LOCAL_MACHINE\SOFTWARE\OpenSSH\DefaultShell to cmd.exe or powershell.exe it works.

But as soon as I put cmder.exe it doesn't work.

I can put cmd.exe as the default shell and once I'm logged in I can go and run C:\tools\cmder\vendor\init.bat and it works, but idealy I'd like it out of the box.

**Comment by daxgames** [comment]
Cmder.exe is not a shell.  Cmder is `cmd.exe` initialized by running `init.bat`.

Your only option would be to figure out how to set the shell as `cmd.exe` and pass parameters `/k "[cmder_root]\vendor\init.bat"` to that shell.  Is there a registry key that allows passing parameters to the shell defined in `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\OpenSSH\DefaultShell`?

Not sure it is even possible.

**Comment by PeterKarlster** [comment]
I have managed to be able to do it by passing the following CMD script to the registry key that you mentioned above:

HKLM/.../DefaultShell:
C:\ProgramData\cmder.cmd

cmder.cmd:
cmd /k C:\tools\cmder\vendor\init.bat

One last note, it really has to be a .CDM file extension, I first tried with a .BAT file extension and it did not work without giving any clue why.

Thank you for your advice, managing windows nodes with cmder remotely via Ubuntu is a bliss!!

**Comment by daxgames** [comment]
Glad you got it working.

**Comment by chhex** [comment]
@PeterKarlster  Very cool
