### ISSUE TITLE
SSH fails when password has special characters

### ISSUE THREAD

**Issue by D4n1984** [cmderdev/cmder#2426]
### Purpose of the issue
- [X ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information
CmdEr 1.3.16.1035
ConEmu 191012

### Description of the issue

I tried to connect to a regular ssh connection (ssh user@host ) but password is like **Cmd¡-Er0012** and fails.
I tried with another ssh connections without **¡** , and it's running fine. I tried with plink (plink user@host -pw Cmd¡-Er0012 ) and same problem.

For that, I suppose that the problem is the special characters in cmder because I can connect with another apps like putty.

**Comment by daxgames** [comment]
Did you try it in a Conemu `cmd.exe` session that was not initialized by `init.bat`?  Cmder is `init.bat` so you could also open a `cmd.exe` and run `init.bat` in it outside Conemu to see if it truly is Cmder.

Output of `which ssh`?  Windows embedded ssh is used by default over any ssh included with cmder.

**Comment by daxgames** [comment]
@D4n1984 ^^^^^

**Comment by D4n1984** [comment]
Same error, I suppose that is not a problem with Cmder or Conemu ... It must be something related to my system

This can be closed.

Thanks!

**Comment by daxgames** [comment]
It could depend on the ssh.exe you are uaing that is why I asked foe the path  provided by `where ssh`
