### ISSUE TITLE
Incorrect operation when scrolling through commands with vertical arrows

### ISSUE THREAD

**Issue by gskoczylas** [cmderdev/cmder#2427]
To illustrate the problem, let's assume that I executed the following commands in sequence:
1. `dir`
2. `pushd c:\temp`
3. `cd ..\Tools\`
4. `dir /w`
5. `popd`

Now I want to execute one of the previous commands again. To do this, I press the up arrow key (on the keyboard).
- After first pressing the button I see the `popd` command. For now everything is fine.
- After second pressing the button I see the `dir /w` command. Still all right.
- After third pressing the button I see the `dcd ..\Tools\` command. **Wrong!** The first letter of the previous command (letter "d") is displayed before the actual command.
- From now on, each subsequent command is preceded by this additional letter (`d`), for example: `dpushd c:\temp`, `ddir`, etc.
- If I press _Esc_, the whole command is deleted, except for this additional letter `d`.

This additional letter at the beginning is only _virtual_. For example, if I see a `ddir` and execute this command, then I will execute the `dir` command - as if this additional letter was not there at the beginning.

You can live with it, but it's annoying and it interferes with your working comfort.

At first I did not have such problems. It happened at some point. I did not change any settings in the program. I didn't notice anything special that could change this behavior.

Environment:
- Cmder ver. 1.3.16.1035
- Windows 10 Enterprise ver. 1909

**Comment by daxgames** [comment]
I don't see this issue in my Cmder 1.3.16.1035.

**Comment by daxgames** [comment]
Usually this is a font thing and not liking the 'lambda'. Try a different font, or you could change the 'lambda' to '$' using a custom prompt.lua in the config folder.

See:#2348 (comment)
