### ISSUE TITLE
Display problem when using up arrow for histroy commands

### ISSUE THREAD

**Issue by playgithub** [cmderdev/cmder#2429]
### Env
Window 10
Cmder 1.3.16.1035 (191012 preview in Help/About)

### Problem
```
D:\test
λ find . -name "aaa"
...

λ whoami
desktop-safa34r\aaa

# press up arrow

D:\test
λ wfind . -name "aaa"
Access denied - .
File not found - -NAME

# press up arrow

D:\test
λ find . -name "aaa"
```

It doesn't alwyas occur, I can't find the condition when it will occur.
However the problem often occurs.

**Comment by daxgames** [comment]
Usually this is a font thing and not liking the 'lambda'. Try a different font, or you could change the 'lambda' to '$' using a custom `prompt.lua` in the config folder.

See:https://github.com/cmderdev/cmder/issues/2348#issuecomment-657242055

**Comment by playgithub** [comment]
OK, still hope it can be fixed anyway
Thanks

**Comment by playgithub** [comment]
I'm using the quite common font **consolas**, I think the problem should be fixed.

**Comment by daxgames** [comment]
The only fix we have identified is changing the lambda and that is possible in user config as stated.  Other maintainers have stated quite clearly the lambda will not be changed ans I cannot reverse that decision.

**Comment by playgithub** [comment]
> Other maintainers have stated quite clearly the lambda will not be changed and I cannot reverse that decision.

If they insist on using lambda, they should see the bug and fix it.
