### ISSUE TITLE
ANSI/Terminal Color issue?

### ISSUE THREAD

**Issue by klodoma** [cmderdev/cmder#2434]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)

### Version Information

Cmder Version 1.3.16.1035

Windows 10 PRO

### Description of the issue
ANSI Colors are not displayed 

I just switched from conemu to cmder, but I have this issue that "some"(not all) application do not display the colors well. See attached screenshot. 

I use this app to reproduce the issue:
https://github.com/symfony/cli

In the portable version of conemu, it works. 

Any thoughts?

![Screenshot_2](https://user-images.githubusercontent.com/944350/101980247-6f802f80-3c64-11eb-96d9-3f07ba509a1f.png)

**Comment by daxgames** [comment]
Good question, I'll have to look into that.

What happens if you create a new task that just runs cmd.exe like conemu does and not yun yhe init.bat from cmder?

**Comment by daxgames** [comment]
I get colors in `git log` output:

![image](https://user-images.githubusercontent.com/7318053/102833460-2e53f200-43bf-11eb-9458-3b12082bf909.png)

I even downloaded `symfony` and it works there too:

![image](https://user-images.githubusercontent.com/7318053/102833615-94407980-43bf-11eb-876f-bfd94acf265e.png)

**Comment by daxgames** [comment]
Try this build: https://ci.appveyor.com/project/MartiUK/cmder/build/artifacts
