### ISSUE TITLE
Q. Commands like 'less filename' or 'man ls' doesnt print organized text ?

### ISSUE THREAD

**Issue by Shahbazakhter** [cmderdev/cmder#2442]
[sample.txt](https://github.com/cmderdev/cmder/files/5718973/sample.txt)

### Purpose of the issue
- [x] Question

### Description of the issue

![image](https://user-images.githubusercontent.com/3104428/102682423-542a9c80-41ef-11eb-97c7-4f4d9d57980e.png)

**Comment by daxgames** [comment]
Downloaded your file typed `less sample.txt`

![image](https://user-images.githubusercontent.com/7318053/102890567-a86d9080-442a-11eb-97f1-d5a3fab297f9.png)

**Comment by naahiv** [comment]
If you are still having a problem with this, it could be a problem fixed in the latest update of ConEmu (I had a similar issue with vim commands). I have created a pull request to upgrade to the latest version.

**Comment by Chealer** [comment]
@naahiv must have referred to [this change](https://github.com/cmderdev/cmder/pull/2454), which has yet to be integrated.

The description is too vague to tell, but I may be experiencing the same issue. I get corrupted display after scrolling up in man ls; or man netstat.
