### ISSUE TITLE
Warning ! ConEmu binaries were marked as `Downloaded from Internet` 

### ISSUE THREAD

**Issue by ralphvirtucio** [cmderdev/cmder#2443]
When I'm opening my cmder I'm getting a prompt warning that my ConEmu binaries were marked as `Downloaded from Internet ` 
![ConEmu warning](https://user-images.githubusercontent.com/67408420/102694410-d51f7d80-425b-11eb-861f-722cc7ad0391.PNG)
? When I click X I'm being direct to the cmder prompt. I'm just curious why I'm having this type of warning ?

**Comment by daxgames** [comment]
UAC is a feature of Windows that allows a user to approve things before taking action.  One of those things is approving use of fikes downloaded feom the internet.  Apparently ConEmu has a feature to disable some UAC protections.

If you want morw than that you will have to ask the developwr of ConEmu for more detail.
