### ISSUE TITLE
Preset does not restore layout properly

### ISSUE THREAD

**Issue by moniuch** [cmderdev/cmder#2445]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

191012 preview

Win 10

### Description of the issue

I wanted to save a group of 4 console tabs under a name that corresponds with my project ID. I clicked Ative Tabs in the preset editor and then tried to reopen the preset.

Even though I had a typical 2x2 layout with all cells even,

50% 50%
50% 50%

the layout didn't get recreated properly. Instead I got something like

50% 25% 25%
100%

Tried several times, seems to be reproducible 100%.
Also when I looked into what got generated by clicking Ative Tabs, it did not seem to contain any size/layout information.

**Comment by daxgames** [comment]
Cmder GUI is ConEmu you should open an issue there for this.
