### ISSUE TITLE
Better control over how presets open

### ISSUE THREAD

**Issue by moniuch** [cmderdev/cmder#2446]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [ ] Question

### Version Information

191012 preview

Win 10

### Description of the issue

(Not sure this pertains to cmder or conemu project.)

When working on a complex project which involves several repos/consoles at the same time, I would want to be able to open such a group in a totally separate window, and not merge all my consoles into existing tabs, because then it kind of defies the comfort that I am using cmder mostly for.

Currently I am trying out the following flow:

- I have Single instance mode turned off
- I have my preset for Ticket1 saved, involving 4 consoles
- I have my consoles A and B open.
- I need to jump to Ticket1.
- I ctrl-T - where I select to open Ticket1 preset in a Layered window.

Actual: I end up with consoles A, B and C through F merged all in one frame. One big mess, hardly navigatable or controllable.

Desired: a new instance/frame is opened with consoles C through F. Consoles A and B remain intact.

Same sort of control should be available when opening a preset from the jump list.

**Comment by daxgames** [comment]
ConEmu is the GUI for Cmder.  Cmder has no control of session pane layout so you should open an issue/request over there.

I might also suggest something like tmux and the tmux-resurrect plugin if you are developing in WSL to do what yoU want.
