### ISSUE TITLE
Cmder-1.3.17 is missing cmder.exe

### ISSUE THREAD

**Issue by plaxamana** [cmderdev/cmder#2450]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

v.1.3.17

### Description of the issue

The most recent version is missing the .exe file.  I thought I was going crazy but it isn't there

**Comment by plaxamana** [comment]
![missing cmder-exe](https://user-images.githubusercontent.com/24259127/103011212-8d248300-4507-11eb-8eb2-f8e30af32d58.png)

**Comment by deanpienaar** [comment]
The assets are missing from the release on GitHub, too.

**Comment by daxgames** [comment]
Built assets are avalable I just have not linked them yet to the release.  I will be doing that today.

**Comment by deanpienaar** [comment]
Ah! Thanks @daxgames

**Comment by daxgames** [comment]
Binaries linked
