### ISSUE TITLE
Black Boxes issue

### ISSUE THREAD

**Issue by sadam3322** [cmderdev/cmder#2453]
how to remove these black boxes right now i am using "iceland" font and i am facing this problem how can i remove these black boxes if i use **cmder default font** "Consoals" then i am not facing this problem but i don't want to use that font if i change Consoals to any other font i am facing this issue is there any way to fix this?

here is screenshot;
https://i.ibb.co/kD3Mcgc/pro.png

**Comment by daxgames** [comment]
@sadam3322 bad screenshot link?

**Comment by sadam3322** [comment]
> @sadam3322 bad screenshot link?

https://i.ibb.co/kD3Mcgc/pro.png

**Comment by daxgames** [comment]
I don't know.  I have never seen that.  Can you provide your `%cmder_root%\config\user-conemu.xml` file?

**Comment by sadam3322** [comment]
> I don't know. I have never seen that. I doubt this is a Cmder issue, most likely Conemu not liking something in the config.
> 
> Can you provide your `%cmder_root%\config\user-conemu.xml` file?
> 
> And any details of how to duplicate your config. I see an image. You said you used a cusrom font. Where did you get it ans what is it called, how did you install it.

please check:
install font : https://www.1001freefonts.com/iceland.font
now go to **settings** > background > set .jpg background (Stretch-Fill)  > General > Fonts > "**Main Console Font**" >  Iceland > **Save Settings**
now go back and type command like "**systeminfo**"
screenshot : https://i.ibb.co/DCMnrrF/op.png

**Comment by daxgames** [comment]
Have you tried the same oitside cmder with ConEmu? I am pretty sure you would get s8milar results.
