### ISSUE TITLE
Cmder cmd.exe without init.bat lags on start (Windows 7 x64 SP1)

### ISSUE THREAD

**Issue by andry81** [cmderdev/cmder#2455]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)

### Version Information

Cmder: 1.3.17
Cmder->ConEmu: 191012

Additionally, I've installed the standalone version of the `ConEmu` 201114 separately. That is might be important.

Windows 7 x64 SP1

### Description of the issue

I've created `{cmd::Cmder clean}` variant to start as `cmd.exe /k` (without init.bat, as fast as possible) and set as default on `Cmder.exe` run.
But Cmder still lags time to time when run from the Desktop shortcut.
To repro, just continuely click on the shortcut and run instance after instance (non stop), time to time the random next instance would freeze to start about 1 or 2 seconds.

**Comment by daxgames** [comment]
If you sre not using init.bat you ate nit using Cmder shell.  You are using Cmder.exe to launch Conemu to run a cmd.exe shell.

**Comment by andry81** [comment]
> If you sre not using init.bat you ate nit using Cmder shell. You are using Cmder.exe to launch Conemu to run a cmd.exe shell.

Why Cmder linked to the ConEmu through the bat file? Is that a bad design?

**Comment by daxgames** [comment]
Cmder is the combination of several different packages through configuration to provide a better shell experience than vanilla `cmd.exe`

That configuration is `init.bat°` and other scripts.  `Cmder.exe` is just a launcher, Conemu is the GUI/Terminal Emulator that runs Cmd.exe shells configured by `init.bat` and other scripts.

You could run `cmd.exe` and then execute `init.bat` and you essentailly have a `Cmder` session in `cmd.exe`.  You could run init.bat in any cmd.exe shell in other terminal emulators and have a Cmder shell so it is not 'linked' to ConEmu other than by the choice of terminal emulator by the Cmder team.

Cmder.exe is a launcher that manages some config files used to initialize Cmder shells enableing use of ConEmu, Clink, Clink Completions, and Git for Windows to be used together  as a portable app.

**Comment by andry81** [comment]
Why not to use external configuration file instead of init.bat?
