### ISSUE TITLE
Powershell Prompt on Windows 10

### ISSUE THREAD

**Issue by joaquimds** [cmderdev/cmder#2456]
Hi,

First of all thank you so much for creating this beautiful terminal emulator ❤️ 

This issue boils down to fixing the Powershell prompt, but it's a bit of a long story...

I recently installed Cmder on a new Windows PC. When opening a Powershell tab, I received the following error:

```
Import-Module : File C:\Users\...\Applications\cmder\vendor\profile.ps1 cannot be loaded. The file
C:\Users\...\Applications\cmder\vendor\profile.ps1 is not digitally signed.
```

I don't have permission to modify the Execution Policy of this machine, but I am able to get around this issue by creating a new file, copying the contents of profile.ps1 into this new file, and then overwriting the original file.

Unfortunately this seems to break the character encoding of the file, converting it from UTF-8 with BOM to simply UTF-8. I believe this breaks the lambda character in the prompt, as instead of a `λ` I get an `Î`.

I have fixed this issue by modifying `profile.ps1` line 70:

```
    Microsoft.PowerShell.Utility\Write-Host "`n$([char]0x03BB)" -NoNewLine -ForegroundColor "DarkGray"
```

My question is: is it worth my putting in a Pull Request for this issue, or is there some way for me to maintain the encoding when I copy the `profile.ps1` contents into a new file?

**Comment by daxgames** [comment]
@joaquimds  Sorry for the late response.

Pull requests are always welcome.

**Comment by Jackbennett** [comment]
Is the execution policy just set to RemoteSigned?

![image](https://user-images.githubusercontent.com/791134/110154284-ffed8c80-7ddb-11eb-8171-0ab166f9d5ee.png)

right-click profile.ps1 and unblock should take off the NTFS file descriptor that says it's a remote file. There's also `unblock-file` if you're already in a console.

That little lambda is responsible for an outrageous amount of issues lol.

**Comment by joaquimds** [comment]
I'll try that next time I'm on my work computer, thanks!
