### ISSUE TITLE
Update missing Lambda

### ISSUE THREAD

**Issue by RyanPrentiss** [cmderdev/cmder#2457]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

ConEmu 201011 [64] Preview

OsVer: 10.0.19042.x64

### Description of the issue

Following update, my prompt now shows "$" instead of "λ".

**Comment by daxgames** [comment]
What did tou update?

What version of cmder?

Can you provide the link where you downloaded?

**Comment by RyanPrentiss** [comment]
> 
> 
> What did tou update?
> _I updated through the application. In settings, I hit reset, saved, then closed. When reopening, cmder asked if I wanted to update. I clicked the "Preview" option. Following the update, I no longer have the lambda._
> What version of cmder?
> _Looks like I'm running 1.3.14.982_
> Can you provide the link where you downloaded?
_Updated through application._

**Comment by RyanPrentiss** [comment]
I've figured it out. Seems the ConEmu update broke the older Cmder update. I've updated Cmder and now everything's works.
