### ISSUE TITLE
CMDER- "runing post install"

### ISSUE THREAD

**Issue by asma1588** [cmderdev/cmder#2459]
hello guys,

I am new to cmder. i just installed following instructions from O'reilly. well... step one.. its not working. if I open the zip file, i get the error msg" failed to copy vendor".  so I  ran it as an administrator account . a window opens but it says " Running Git for Windows one time Post Install....
"running post-install".

i cant type anything on the screen (ex LS, pwd/ node -v) it is stuck on this page.
pls help me unstuck.
thanks

**Comment by daxgames** [comment]
Install is simple expand the content of the zip to `%USERPROFILE%\CMDER`.

**Comment by asma1588** [comment]
thnx. i think it worked :)  it looks like it is working half way but now it wouldnt let me change diroctory/drives.
The system cannot find the drive specified. error for everything.

**Comment by daxgames** [comment]
What are you typing to change directory/drives and what is your current working dir?  Type `cd` to get current working directory.

**Comment by asma1588** [comment]
I am trying to switch to Desktop ( my folders are saved there) like the pic below
![image](https://user-images.githubusercontent.com/29110445/104325356-8cec2780-54b6-11eb-95a1-d0701b12f019.png)

istead I am getting error for everything "path not found".

![image](https://user-images.githubusercontent.com/29110445/104325568-c58c0100-54b6-11eb-92b5-40b5e44a1bbb.png)
 I need to access my VScode from Cmder ( got to follow instructor).  
( vs code doesnt work on its own but that another issue. host808 error)

**Comment by daxgames** [comment]
`cd /d "%userprofile%\Desktop"`

**Comment by daxgames** [comment]
@asma1588 Did my last help?

You could also start a `bash::bash` session and it may be more like what the instructor is showing on his Mac.
