### ISSUE TITLE
Move Window without top/bottom bars

### ISSUE THREAD

**Issue by zuka1337** [cmderdev/cmder#2462]
Hello Guys,

Am I doing something wrong or moving the window x or y direction does not work without bars?
Also windows default shurtcut win+left and win+right where can I set it up?

![test gif](https://user-images.githubusercontent.com/57998098/104659495-a1017600-56bc-11eb-9fd1-b6895aef7809.gif)

**Comment by zuka1337** [comment]
Well Find the the solution:
ctrl+alt.. (sorry about that)

Not closing because the resize window borders still a little hard to get it plus the win+left/right shurtcut.

**Comment by daxgames** [comment]
Not a cmder issue.  Need to report it tonthe conemu dev.
