### ISSUE TITLE
Dose not work with Docker

### ISSUE THREAD

**Issue by DevWL** [cmderdev/cmder#2463]
```
C:\WEB APPS\app\app
λ docker run -dp 3000:3000 -w /app -v "$(pwd):/app" node:12-alpine sh -c "yarn install && yarn run dev"
docker: Error response from daemon: create $(pwd): "$(pwd)" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.
```

### Purpose of the issue
- [ x ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

191012

Windows 10 Pro
### Description of the issue

Hey I am trying to fallow docker getting started tutorial using your terminal https://docs.docker.com/get-started/06_bind_mounts/ 
Unfortunately there is a problem with a path translation. I was able to make it work in GitBash but not in Cmder. 
More about this issue here https://stackoverflow.com/questions/65656378/docker-using-gitbash-cmder-path-issue. 
If you have any solution that would be great. I love cmder terminal but think that will need to use something else for docker.

**Comment by daxgames** [comment]
$(pwd) is invalod in cmd.exe.  Try %cd%

**Comment by daxgames** [comment]
@DevWL ???

**Comment by daxgames** [comment]
Closing no response.
