### ISSUE TITLE
It does nothing when I first run it

### ISSUE THREAD

**Issue by alavaros** [cmderdev/cmder#2465]
### Purpose of the issue
- [X] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

#### Cmder:
Cmder version: 1.3.17 (2020-12-23)
ConEmu version: 191012 preview

![image](https://user-images.githubusercontent.com/4333677/104909520-4603a380-5988-11eb-875a-a20869b1b181.png)

#### Windows:
Edition: Windows 10 Pro
Version: 20H2
Operating system version: 19042.746
### Description of the issue

After downloading the Mini version of Cmder, I unzip the package and run Cmder.exe, but it gets stuck on the next screen:

![image](https://user-images.githubusercontent.com/4333677/104909467-2ec4b600-5988-11eb-8f17-5f1fc7610257.png)

I left it open for a while to see if it took too long, but it seems that it never ends. Then if I open another tab, nothing appears.

![image](https://user-images.githubusercontent.com/4333677/104909732-95e26a80-5988-11eb-85a8-1ca199a9f470.png)

**Comment by daxgames** [comment]
I just downloaded it and tested the same thing.  No Issues:

![image](https://user-images.githubusercontent.com/7318053/105647250-444b4b80-5e72-11eb-9200-6fd4c46c327e.png)

**Comment by daxgames** [comment]
Go here and make the below modifications:

![image](https://user-images.githubusercontent.com/7318053/105647290-95f3d600-5e72-11eb-8b12-9bfe8baf3ddb.png)

Save settings and restart Cmder and post output.

**Comment by alavaros** [comment]
> Go here and make the below modifications:
> 
> ![image](https://user-images.githubusercontent.com/7318053/105647290-95f3d600-5e72-11eb-8b12-9bfe8baf3ddb.png)
> 
> Save settings and restart Cmder and post output.

It doesn't work for me.

I had to download the previous version, [v1.3.16](https://github.com/cmderdev/cmder/releases/tag/v1.3.16), which works correctly.
I also tried to replace all the files in the "config" folder in the v1.3.17 version with those of the v1.3.16 version, but that didn't help either.

**Comment by daxgames** [comment]
I did not expect it to fix the problem.  I expected more output to the screen to give me a clue as to where it was hanging.  If anything then problematic fime is `%cmder_root%\vendor\init.bat`.

**Comment by daxgames** [comment]
Another option is to rename the `%cmder_root%\vendor\clink` folder and copy Clink folder from 1.3.16 to `%cmder_root%\vendor\clink`.  This may actually be the issue since the Clink version changed in 1.3.17.

**Comment by alavaros** [comment]
> I did not expect it to fix the problem. I expected more output to the screen to give me a clue as to where it was hanging. If anything then problematic fime is `%cmder_root%\vendor\init.bat`.

Sorry, I didn't see you asked for the output. Anyway, it doesn't show anything, just like the second screenshot in the post.

**Comment by alavaros** [comment]
> Another option is to rename the `%cmder_root%\vendor\clink` folder in 1.3.17 and copy Clink folder from 1.3.16 to `%cmder_root%\vendor\clink`. This may actually be the issue since the Clink version changed in 1.3.17.

I will test it and get back with the result.

**Comment by alavaros** [comment]
> > Another option is to rename the `%cmder_root%\vendor\clink` folder in 1.3.17 and copy Clink folder from 1.3.16 to `%cmder_root%\vendor\clink`. This may actually be the issue since the Clink version changed in 1.3.17.
> 
> I will test it and get back with the result.

That's it, it worked by copying the `%cmder_root%\vendor\clink` folder from the older version to the latest:

![image](https://user-images.githubusercontent.com/4333677/105717282-39e78b00-5f20-11eb-8778-1c31a07db108.png)

**Comment by mike1130694** [comment]
Would it be possible to rename this issue or add additional tags. I had the same problem when I downloaded the latest version this week. However it took me hours to come across this solution because google didn't related the content to "clink" being the problem. 

Thanks for your help I can finally continue my setup

**Comment by chrisant996** [comment]
This has been fixed, right?  (Asking because it sounds like a Clink issue, and I'm the Clink maintainer.)

**Comment by alavaros** [comment]
> This has been fixed, right? (Asking because it sounds like a Clink issue, and I'm the Clink maintainer.)

I had to do what @daxgames said in this comment:

> Another option is to rename the `%cmder_root%\vendor\clink` folder in 1.3.17 and copy Clink folder from 1.3.16 to `%cmder_root%\vendor\clink`. This may actually be the issue since the Clink version changed in 1.3.17.

Since then I haven't needed to try it again, but the same thing happened to a co-worker. This is what should be displayed on the screen:

> > > Another option is to rename the `%cmder_root%\vendor\clink` folder in 1.3.17 and copy Clink folder from 1.3.16 to `%cmder_root%\vendor\clink`. This may actually be the issue since the Clink version changed in 1.3.17.
> > 
> > 
> > I will test it and get back with the result.
> 
> That's it, it worked by copying the `%cmder_root%\vendor\clink` folder from the older version to the latest:
> 
> ![image](https://user-images.githubusercontent.com/4333677/105717282-39e78b00-5f20-11eb-8778-1c31a07db108.png)

**Comment by chrisant996** [comment]
I believe that was fixed in mid or late January, in Clink v1.1.20.

**Comment by mike1130694** [comment]
I am not sure about the timeline but I was having problems with the configuration at the beginning of February. So it the fix was implemented, it was not included in the version that cmder had as latest at the beginning of february.

**Comment by chrisant996** [comment]
> I am not sure about the timeline but I was having problems with the configuration at the beginning of February. So it the fix was implemented, it was not included in the version that cmder had as latest at the beginning of february.

What Clink version is being used?
`clink info` should say.

**Comment by mike1130694** [comment]
At the moment I am using 
Clink v0.4.9 [git:2fd2c2] Copyright (c) 2012-2016 Martin Ridgers
http://mridgers.github.io/clink
But then again I took the clink version from cmder release 1.3.16 to overwrite the one included in 1.3.17

According to [https://github.com/cmderdev/cmder/releases/](url) the release 1.3.17 is using clink v1.1.10:
"Switch to @chrisant996 Clink v1.1.10 to fix Clink newer Windows 10 releases."

**Comment by chrisant996** [comment]
Ah, ok, thanks.  Probably Cmder hasn't been updated to use a newer version of Clink yet.  Probably it downgraded to v1.1.10 to work around a bug while waiting for the fix that became available in v1.1.20.

Clink is on the edge of releasing an Official Release, and I imagine Cmder will update at that time.

(By the way @daxgames the latest Clink is now able to make the `clink inject --s` flag take effect even if Clink is already injected.  That enables Cmder to be compatible with Clink even when Clink is installed for AutoRun!)

**Comment by daxgames** [comment]
Please confirm if this build works: https://ci.appveyor.com/project/MartiUK/cmder/builds/37955932/artifacts

**Comment by daxgames** [comment]
@mike1130694  Can you confirm the build above fixes your issue?

**Comment by mike1130694** [comment]
At the moment I am not able to remove the current version that I have installed since I am on a deadline for a project. I might be able to try it out in a couple of weeks. Sorry about that.

**Comment by daxgames** [comment]
@mike1130694 you could download the zip grom github and expand it to a different folder.  This would not affect yoyr current install.

**Comment by mike1130694** [comment]
That was my first idea, but when I ran it without adding to the path variables and other installation procedures that I've done. I got next output

`The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
'cmder_shell' is not recognized as an internal or external command,
operable program or batch file.
'init.bat' is not recognized as an internal or external command,
operable program or batch file.
'init.bat' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
'init.bat' is not recognized as an internal or external command,
operable program or batch file.
'validate_version' is not recognized as an internal or external command,
operable program or batch file.
'is_git_shim' is not recognized as an internal or external command,
operable program or batch file.
'get_user_git_version' is not recognized as an internal or external command,
operable program or batch file.
'compare_git_versions' is not recognized as an internal or external command,
operable program or batch file.
'is_git_shim' is not recognized as an internal or external command,
operable program or batch file.
'get_user_git_version' is not recognized as an internal or external command,
operable program or batch file.
'compare_git_versions' is not recognized as an internal or external command,
operable program or batch file.
'enhance_path' is not recognized as an internal or external command,
operable program or batch file.
'enhance_path_recursive' is not recognized as an internal or external command,
operable program or batch file.
'enhance_path' is not recognized as an internal or external command,
operable program or batch file.
'run_profile_d' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the file specified.
'"C:\Users\XXXX\Downloads\cmder\config\user_aliases.cmd"' is not recognized as an internal or external command,
operable program or batch file.
'init.bat' is not recognized as an internal or external command,
operable program or batch file.
'init.bat' is not recognized as an internal or external command,
operable program or batch file.`

I thought that I might need to perform a full configuration to really give it a try. 
Does this help?

Cmder doesn't seem to boot up as with my current installation.

**Comment by chrisant996** [comment]
How are you installing Cmder?
How are you launching Cmder?

- I install it by unzipping the entire "mini" zip file into a `c:\tools\cmder` directory.
- I do not have Cmder on my `PATH`.
- I launch Cmder by launching `c:\tools\cmder\cmder`.

Some observations:

The errors appear to be happening because environment variables somehow are not set or are getting cleared mid-script:
- The `cmder_shell` error can only be happening inside init.bat itself, e.g. here: https://github.com/cmderdev/cmder/blob/a66b8b30355230b51c383765376869623521bcc9/vendor/init.bat#L127
- The `init.bat` errors can only be happening from inside init.bat itself, from lines such as: https://github.com/cmderdev/cmder/blob/a66b8b30355230b51c383765376869623521bcc9/vendor/init.bat#L128

**Comment by chrisant996** [comment]
@mike1130694 a couple possible diagnostic questions:
- Did you not unzip the `vendor/lib` directory?
- Is there a `call` script or program or alias on your computer?
- Inside the Cmder prompt after all those errors, what happens when you type `where call`?

**Comment by mike1130694** [comment]
I don't know if there was an error either on the download or the unzip of the file.

I've repeated the steps and now it seems to be working.

This was shown the first time cmder was run
`Generating clink initial settings in "C:\tools\config\clink_settings"
        1 file(s) copied.
Additional *.lua files in "C:\tools\config" are loaded on startup.
Creating initial user_aliases store in "C:\tools\config\user_aliases.cmd"...
        1 file(s) copied.
Creating user startup file: "C:\tools\config\user_profile.cmd"
        1 file(s) copied.`


Here is the information regarding which version of clink it is used

`C:\tools
λ clink info
version  : 1.1.34.d161e9
session  : 34776
binaries : C:\tools\vendor\clink
state    : C:\tools\config
log      : C:\tools\config\clink.log
settings : C:\tools\config\clink_settings
history  : C:\tools\config\clink_history
scripts  : C:\tools\vendor ; C:\tools\vendor\clink ; C:\tools\config
inputrc  : %clink_inputrc%
             (unset)
         : %userprofile%
             C:\Users\XXXXX\.inputrc
             C:\Users\XXXXX\_inputrc
         : %localappdata%
             C:\Users\XXXXX\AppData\Local\.inputrc
             C:\Users\XXXXX\AppData\Local\_inputrc
         : %appdata%
             C:\Users\XXXXX\AppData\Roaming\.inputrc
             C:\Users\XXXXX\AppData\Roaming\_inputrc
         : %home%
             C:\Users\XXXXX\.inputrc
             C:\Users\XXXXX\_inputrc`

Finally I wasn't able to run "where call".

`C:\tools
λ where call
INFO: Could not find files for the given pattern(s).`

Let me know if you need more information

**Comment by daxgames** [comment]
@mike1130694 looks good now.  Can we xlose this?

**Comment by mike1130694** [comment]
I agree to closing the issue.
