### ISSUE TITLE
failed to copy vendor/conemu.xml.default file to vendor/conemu-maximus5/conemu.xml

### ISSUE THREAD

**Issue by leoniloris** [cmderdev/cmder#2466]
I'm receiving this error `failed to copy vendor/conemu.xml.default file to vendor/conemu-maximus5/conemu.xml` 
Just downloaded the Version 1.3.17.1082 from the website.
Besides, the file `vendor/conemu.xml.default` doesn't exist

![image](https://user-images.githubusercontent.com/22769167/104930416-c0252f80-596a-11eb-9a7e-0142e9cce411.png)

**Comment by daxgames** [comment]
Don't put the cmder folder on `c:\program files`.

**Comment by leoniloris** [comment]
I didn't, as it is said in the website. I'm putting it on C:/users/{MY USER}/.

As a reminder, the file `vendor/conemu.xml.default` doesn't exist

**Comment by daxgames** [comment]
I just downloaded and expanded it:

![image](https://user-images.githubusercontent.com/7318053/104968713-9c86d700-59b4-11eb-9b08-e6ad60e85d51.png)

and ran Cmder.exe, see below:

![image](https://user-images.githubusercontent.com/7318053/104968837-ef608e80-59b4-11eb-8523-a00a51480c03.png)

**Comment by AlongTheDeveloper** [comment]
I had to fix this by running it as admin

**Comment by daxgames** [comment]
@AlongTheDeveloper that is possible depending on where you extract the archive to.

**Comment by daxgames** [comment]
@leoniloris did you find a solution?

**Comment by leoniloris** [comment]
no. not trying anymore.

**Comment by DoopSky** [comment]
You can set `%Somewhere%\cmder\config` folder group Users permissions.

Add Changeable and Writeable.

![微信图片_20210519163242](https://user-images.githubusercontent.com/8330408/118781633-dc58bf00-b8bf-11eb-9591-485a388293e5.png)

**Comment by dommpaulo** [comment]
> Don't put the cmder folder on `c:\program files`. The best place is `%userprofile%\cmder`

Tanks alot bud. It's works! \o/

**Comment by StoneCode5** [comment]
> You can set `%Somewhere%\cmder\config` or `%Somewhere%\cmder\vendor` folder group Users permissions.
> 
> Add **Changeable** and **Writeable**.
> 
> ![微信图片_20210519163242](https://user-images.githubusercontent.com/8330408/118781633-dc58bf00-b8bf-11eb-9591-485a388293e5.png)

this works for me

**Comment by ahmedseada** [comment]
> > Don't put the cmder folder on `c:\program files`. The best place is `%userprofile%\cmder`
That Worked For Me Thanks
