### ISSUE TITLE
Getting Cmder to work with KeeAgent

### ISSUE THREAD

**Issue by xelra** [cmderdev/cmder#2467]
I've been trying to get Cmder to work with KeeAgent, a SSH agent that works with KeePass.

Initially I thought this should be easy peasy. Just add the environment variable `SSH_AUTH_SOCK` and that's it.

I went to `Settings > Startup > Environment` and entered the line
```
set "SSH_AUTH_SOCK=C:\\Users\\User\\.ssh\\KeeAgent.socket"
```

I've tried lots of different variations with escape characters and without them. Moving quotes around and not using them at all. But SSH just won't use my agent.

I know it's not the agent itself, because in Cygwin and MSYS2 it works.

**Comment by daxgames** [comment]
@xerla Which Cmder session are you using?  Is the env variable set in the resulting session?

**Comment by xelra** [comment]
I'm using everything in its default state after a fresh install of Cmder. Yes, when I print the environment variables, `SSH_AUTH_SOCK` is there and properly set.
My personal guess is that somehow SSH cannot access or find the socket file. I thought that maybe it cannot handle the path that is set with the variable. But I've tried pretty much every way of escaping and quoting that I can think of.

In MSYS2 I can simply point to the socket file with the Unix emulated path and it works.
```
# Environment variable I use in MSYS2 and Cygwin
SSH_AUTH_SOCK=/c/Users/User/.ssh/KeeAgent.socket
```

**Comment by daxgames** [comment]
@xerla have you tried Cmder session `bash::bash` it should behave more like MSYS2 and you should be able to set `SSH_AUTH_SOCK=/c/Users/User/.ssh/KeeAgent.socket` in `$CMDER_ROOT/config/user_profile.sh`.

**Comment by daxgames** [comment]
@xelra I have not seen any documentation that KeeAgent can work with cmd.exe based sessions.  Are you sure this is even supported?
