### ISSUE TITLE
Wrong icons when running Cmder via the context menu entry

### ISSUE THREAD

**Issue by DigiOhhh** [cmderdev/cmder#2471]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

Cmder v1.3.17
ConEmu 191012

Windows 7 Ultimate

### Description of the issue

if I run Cmder using the context menu entry, i.e. this one,

![Temp-2](https://user-images.githubusercontent.com/37815914/106362995-21171500-6326-11eb-9a52-885267e2c845.png)

the ConEmu icon pops up in the system tray instead of the Cmder one.

![Temp-1](https://user-images.githubusercontent.com/37815914/106363027-486de200-6326-11eb-9b2c-b15df48c85e0.png)

This is how I've configured the context menu entry:

![Temp-4](https://user-images.githubusercontent.com/37815914/106363088-ab5f7900-6326-11eb-9b45-099f0f23d552.png)

This is how I've configured the `{PowerShell::Open Cmder here}` task:

![Temp-3](https://user-images.githubusercontent.com/37815914/106363102-c8944780-6326-11eb-9906-68c4a92ad5cf.png)

PS: I also just noticed how the icon in the upper left corner of the last two screenshots is ConEmu's instead of Cmder's.
Anything I can do to fix this?
Oh, and more thing. This doesn't happen if I run Cmder normally, i.e. from the Desktop shortcut (which points to `%CMDER_ROOT%\Cmder.exe`). After opening Cmder like this, I can also use the context menu entry and all the icons (both the one in the system tray, and the one in the upper left corner of the window border) are Cmder's and not ConEmu's.
Thank you

**Comment by daxgames** [comment]
Undo the context menu config you have applied and run `cmder.exe /REGISTER USER /SINGLE`.

**Comment by DigiOhhh** [comment]
icons are working correctly now, but Cmder isn't opened in the correct directory:

https://user-images.githubusercontent.com/37815914/106365658-3ea0aa80-6337-11eb-96b2-203c3d7cbc0e.mp4

**Comment by daxgames** [comment]
Which task is starting when cmder is launched and what is the content of that task.

**Comment by DigiOhhh** [comment]
```
title Cmder & PwSh -ExecutionPolicy Bypass -NoLogo -NoProfile -NoExit -Command "Invoke-Expression '. "%USERPROFILE%\Documents\PowerShell\Microsoft.PowerShell_profile.ps1"'" -new_console:d:"%USERPROFILE%"
```
I know I could easily replace `%USERPROFILE%` with `!ConEmuWorkDir!`, but I only want Cmder to start in a specific directory when running it from the context menu. Otherwise (for instance, when I run it from the desktop shortcut) it should always start in `%USERPROFILE%`
is this possible?

**Comment by daxgames** [comment]
1.  You are not running Cmder.  You are using Cmder.exe to launch Conemu to start a custom task that contains no cmder config.  Cmder Powershell config is in `%cmder_root%\vendor\profile.ps1`. 
2. `-new_console:d:"%USERPROFILE%"` tells the task to open in your user profile which overrides the folder set in the shell extension.  You can only do one or the other with a single task unless you remove this setting and use a shortcut to start Cmder that specifies to start in `userprofile`.  This is what I do.
   - Look at `README.md` and the conemu documentation for for command line options.  
   - Cmder.exe can do anything possible with conemu command line by using `Cmder.exe -- [CONEMU COMMAND LINE SETTING]`
3.  You are simultaneously telling powershell to run `-NoProfile` then forcing it to source the profile `. "%USERPROFILE%\Documents\PowerShell\Microsoft.PowerShell_profile.ps1`
    - Cmder `powershell::powershell` by default sources `%cmder_root%\vendor\profile.ps1` wich sources `%USERPROFILE%\Documents\PowerShell\Microsoft.PowerShell_profile.ps1`

**Comment by DigiOhhh** [comment]
I've installed Cmder again, and everything seems to be working correctly now. I'm not completely satisfied with the current setup, but hopefully I'll find what I need in the Wiki.
Thank you c:
