### ISSUE TITLE
Add a privacy policy page to the wiki

### ISSUE THREAD

**Issue by pedrosousa** [cmderdev/cmder#2472]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Version Information
(N/A, or latest version)

### Description of the issue

Some company policies prevent employees from using tools (even open source tools) that are not clear about the data they collect, the purpose of the data, and where that data is stored.

I'd like to request a new wiki page stating what is Cmder's privacy policy, where you would address questions like:

* Do you collect any kind of data? What data exactly, with what purpose, and in which servers do you store it?
* Does the tool collect any telemetry info? Is it anonymized? Where is it stored, and what's the data retention policy?

Note: I also checked the ConEmu repository for this kind of info, but couldn't find it.

Thanks!

**Comment by daxgames** [comment]
Cmder is just configuration that glues together several components and thus collects no data in normal operation.  

Cmder does contain some diag scripts that can be run by the end user that will collect some info for the user to sanitize and post to an issue if required.  See the scrips in `%cmder_root%\vendor\bin\*diag.cmd` for the types of data collected.

**Comment by chrisant996** [comment]
@pedrosousa one of the products in the Cmder package is [Clink](https://github.com/chrisant996/clink). I'll add a line in its documentation attesting that it does not collect any data.  It does have a local log file, but it only writes to the log file, and does not transmit it off of the local computer (it is for diagnostic self-help purposes).
