### ISSUE TITLE
Cannot cd up multiple directories normally

### ISSUE THREAD

**Issue by LucasMonastirsky** [cmderdev/cmder#2473]
running `cd ../` works normally, going up one directory, but `cd ../../` does nothing, remaining in the same directory. `cd ../../../` goes up a single directory, and `cd ../../../../` goes up two directories.

This happens on my desktop pc but not on my laptop. Both are running Windows 10 x64. I've reinstalled Cmder several times in different drives, with no success. This does not happen when emulating a powershell from Cmder though.

**Comment by ovasquez** [comment]
I was going to report this exact same issue.
I tested versions `1.3.15` and `1.3.16` and in both it works as expected, so the bug must have been introduced (or revealed) in `1.3.17`.

### Current behavior
#### 1.3.17
```bash
cd ../..     # goes up 2 directories [Correct]
cd ../../    # stays in the same directory [Incorrect]
```

### Expected behavior
#### 1.3.16 and 1.3.15 (and probably a lot more before)
```bash
cd ../..     # goes up 2 directories [Correct]
cd ../../    # goes up 2 directories [Correct]
```

**Comment by chrisant996** [comment]
This is about Clink.  I can reproduce it, and opened [chrisant996/clink #76](https://github.com/chrisant996/clink/issues/76).

**Comment by chrisant996** [comment]
Thanks for reporting this!  I've fixed the issue in Clink, but haven't published a new version yet.  (Clink v1.1.33 will be published sometime this week.)

**Comment by chrisant996** [comment]
P.S. Clink with fix has been published.

**Comment by daxgames** [comment]
Please confirm if this build works: https://ci.appveyor.com/project/MartiUK/cmder/builds/37955932/artifacts

**Comment by daxgames** [comment]
Fixed in the build https://ci.appveyor.com/project/MartiUK/cmder/builds/37955932/artifacts
