### ISSUE TITLE
The configuration of vscode_init_args.cmd in the document cannot understand the meaning?

### ISSUE THREAD

**Issue by ouweiya** [cmderdev/cmder#2474]
I read [Seamless VS Code Integration] repeatedly, but I still can't figure out step 6.

How do these codes work? Why is it going wrong? Path failed?

https://github.com/cmderdev/cmder/wiki/Seamless-VS-Code-Integration#vs-code-terminal

![chrome_nO1H0wYHel](https://user-images.githubusercontent.com/28357731/107149840-ee0ff980-6995-11eb-8532-2162c5faa215.png)

**How should I configure vscode_init_args.cmd?**

This is the configuration of my CMDER_ROOT.
![SystemPropertiesAdvanced_ZjrHZuLTUo](https://user-images.githubusercontent.com/28357731/107149932-4d6e0980-6996-11eb-8dbd-d84ffae10730.png)

My initial configuration
```cmd
@echo off
if defined CMDER_CONFIGURED (
    :: Set Cmder settings here for when VSCode is launched inside Cmder.
    set verbose_output=1
) else (
    :: Set Cmder settings here for when VSCode is launched from outside Cmder.
    set verbose_output=1
)

set verbose_output=0
```

**Comment by daxgames** [comment]
Because the edited example is wrong.  Just use the default file.
