### ISSUE TITLE
New user - How can i remove the Lambda sign (λ) on Windows? 

### ISSUE THREAD

**Issue by fosam** [cmderdev/cmder#2478]
Hello 

I just installed cmder but i couldn't find how to remove the Lambda sign, i just use cmder to replacce cmd and i want it to look like cmd.

Can someone please help?

Here you can see the Labda sign i want to remove, i just want it to look like C:\Users\etc...

![Capture 15_02_2021_02_08_49](https://user-images.githubusercontent.com/52612348/107895211-da830680-6f32-11eb-8c66-dfaf081ee2c2.png)

Version 1.3.17

**Comment by fosam** [comment]
Found it under "tasks"

**Comment by daxgames** [comment]
Not sure what you mean.  There is nothing under tasks that allows you to remove the lambda and maintain cmdsr functionality.

**Comment by fosam** [comment]
@daxgames No need to add any custom script.

As the screenshot shows, i removed everything after `cmd` and as a result i don't have any Lambda sign when i start up cmder. Am i doing something not correct here?

You can try it and see.

![Capture 15_02_2021_19_52_06](https://user-images.githubusercontent.com/52612348/107984150-968e1100-6fc7-11eb-9638-56d8d1a2ae88.png)

**Comment by daxgames** [comment]
Cmder is the init.bat if yoy rwmove it you are running cmd.exe in conemu.

**Comment by fosam** [comment]
I think that's what happened, where can i learn and know more about `init.bat` ?

**Comment by daxgames** [comment]
The init.bat is just the cmder init script that ties together cmdees components and provides portability.  Everything you beed to know is in the readme.md the wiki and rhw cmder website.
