### ISSUE TITLE
Showing "warning: replacing arglink for *" on all commands

### ISSUE THREAD

**Issue by williamjamir** [cmderdev/cmder#2479]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information
(installed with latest cmdermini)
Cmder: Version 1.3.17.1082
ConEmu: 191012

Windows 10 Home 10.0.18363

### Description of the issue
Opening the Cmnder results on the following output:
```
warning: replacing arglink for 'cherry-pick'; merging is not supported yet.
warning: replacing arglink for 'checkout'; merging is not supported yet.
warning: replacing arglink for 'rebase'; merging is not supported yet.
warning: replacing arglink for 'commit'; merging is not supported yet.
warning: replacing arglink for 'diff'; merging is not supported yet.
warning: replacing arglink for 'annotate'; merging is not supported yet.
warning: replacing arglink for 'apply'; merging is not supported yet.
warning: replacing arglink for 'svn'; merging is not supported yet.
warning: replacing arglink for 'submodule'; merging is not supported yet.
warning: replacing arglink for 'difftool'; merging is not supported yet.
warning: replacing arglink for 'remote'; merging is not supported yet.
warning: replacing arglink for 'reset'; merging is not supported yet.
warning: replacing arglink for 'merge'; merging is not supported yet.
warning: replacing arglink for 'config'; merging is not supported yet.
warning: replacing arglink for 'push'; merging is not supported yet.
warning: replacing arglink for 'branch'; merging is not supported yet.
warning: replacing arglink for 'pull'; merging is not supported yet.
warning: replacing arglink for 'fetch'; merging is not supported yet.
warning: replacing arglink for 'stash'; merging is not supported yet.
warning: replacing arglink for 'add'; merging is not supported yet.
C:\Users\william
λ
```

Executing any command also outputs all this warning again and Unix commands don't work.

```
C:\Users\william
λ tail
'tail' is not recognized as an internal or external command,
operable program or batch file.

warning: replacing arglink for 'cherry-pick'; merging is not supported yet.
warning: replacing arglink for 'checkout'; merging is not supported yet.
warning: replacing arglink for 'rebase'; merging is not supported yet.
warning: replacing arglink for 'commit'; merging is not supported yet.
warning: replacing arglink for 'diff'; merging is not supported yet.
warning: replacing arglink for 'annotate'; merging is not supported yet.
warning: replacing arglink for 'apply'; merging is not supported yet.
warning: replacing arglink for 'svn'; merging is not supported yet.
warning: replacing arglink for 'submodule'; merging is not supported yet.
warning: replacing arglink for 'difftool'; merging is not supported yet.
warning: replacing arglink for 'remote'; merging is not supported yet.
warning: replacing arglink for 'reset'; merging is not supported yet.
warning: replacing arglink for 'merge'; merging is not supported yet.
warning: replacing arglink for 'config'; merging is not supported yet.
warning: replacing arglink for 'push'; merging is not supported yet.
warning: replacing arglink for 'branch'; merging is not supported yet.
warning: replacing arglink for 'pull'; merging is not supported yet.
warning: replacing arglink for 'fetch'; merging is not supported yet.
warning: replacing arglink for 'stash'; merging is not supported yet.
warning: replacing arglink for 'add'; merging is not supported yet.
C:\Users\william
λ ls
'ls' is not recognized as an internal or external command,
operable program or batch file.

warning: replacing arglink for 'cherry-pick'; merging is not supported yet.
warning: replacing arglink for 'checkout'; merging is not supported yet.
warning: replacing arglink for 'rebase'; merging is not supported yet.
warning: replacing arglink for 'commit'; merging is not supported yet.
warning: replacing arglink for 'diff'; merging is not supported yet.
warning: replacing arglink for 'annotate'; merging is not supported yet.
warning: replacing arglink for 'apply'; merging is not supported yet.
warning: replacing arglink for 'svn'; merging is not supported yet.
warning: replacing arglink for 'submodule'; merging is not supported yet.
warning: replacing arglink for 'difftool'; merging is not supported yet.
warning: replacing arglink for 'remote'; merging is not supported yet.
warning: replacing arglink for 'reset'; merging is not supported yet.
warning: replacing arglink for 'merge'; merging is not supported yet.
warning: replacing arglink for 'config'; merging is not supported yet.
warning: replacing arglink for 'push'; merging is not supported yet.
warning: replacing arglink for 'branch'; merging is not supported yet.
warning: replacing arglink for 'pull'; merging is not supported yet.
warning: replacing arglink for 'fetch'; merging is not supported yet.
warning: replacing arglink for 'stash'; merging is not supported yet.
warning: replacing arglink for 'add'; merging is not supported yet.
```

After a reboot, the error stops occurring but it returns after some time. I could not identify any command or action that could be triggering this behavior.

**Comment by daxgames** [comment]
Chances are there is somethong wrong with your env possibky the path

**Comment by chrisant996** [comment]
The message is coming from Clink.

Can you share the output from `clink info`?

I wonder if some script directory is listed twice.  Or maybe the same (or similar) scripts exist in two different directories, and are "fighting" with each other about who gets to supply the argmatchers for certain commands.

If it's feasible to make a .zip file containing all the .lua files from the scripts paths reported by `clink info`, then I could take a look and identify specifically what's happening.  It might be a configuration problem, or it might be scripts fighting with each other, or something else.  It could also potentially help me design a way for Clink to handle the situation -- if there are specific examples that are safe to accommodate, then it might be possible to handle the simple common scenarios, and only warn about weird/rare/complex scenarios (but I suspect that probably in this case there are two different `git` argmatchers that are stomping on each other, and I wonder/hope that it's actually two copies of the same one, in two different directories).

The reason Clink is reporting a warning when one arglink overwrites another is that in v0.4.9 Clink would try to sort of merge things together and it could silently work or silently break things.  Newer versions of Clink are being vocal when arglinks overwrite each other.  An arglink is when a particular argument (such as "stash" in "git stash") is linked to a custom parser for what comes next.  So the warnings are saying "uh oh something said how to handle `git cherry-pick` and now something else wants to say how to handle it...".

Annnd this also led to me noticing `git cherry-pick `<kbd>Alt</kbd>+<kbd>=</kbd> gets confused by the `-` and thinks it needs to complete flags.  I'll open an issue at [chrisant996/clink](https://github.com/chrisant996/clink/issues) for that soon.

**Comment by daxgames** [comment]
Please confirm if this build works: https://ci.appveyor.com/project/MartiUK/cmder/builds/37955932/artifacts

**Comment by williamjamir** [comment]
Issue solved 🎉 

Thanks, @chrisant996 for mentioning the Clink, your explanation about the arglink error was really insightful.
Following your suggestion about duplicate scripts/folders, I found that I had two `git.lua` in two different folders

```
cmder_mini\vendor\clink\git.lua
cmder_mini\vendor\clink-completions\git.lua 
```
I don't know why I had two files in different folders, most probably it was a mistake while editing some custom clink-completions script.

After deleting the `git.lua` file from the clink folder, everything went back to work again =)

Also, @daxgames in this last build the error message raised from Clink is way easier to understand.
``
warning: replacing arglink for 'add' in C: \ tools \ cmder_mini \ vendor \ clink \ git.lua: 940 (see log file for details).
``

**Comment by chrisant996** [comment]
> Issue solved 🎉

Yay!  Excellent news.

> I don't know why I had two files in different folders, most probably it was a mistake while editing some custom clink-completions script.
> 
> After deleting the `git.lua` file from the clink folder, everything went back to work again =)

Ah, makes perfect sense.  😁  Nice work tracking it down.

> Also, @daxgames in this last build the error message raised from Clink is way easier to understand.
> 
> ```
> warning: replacing arglink for 'add' in C:\tools\cmder_mini\vendor\clink\git.lua:940 (see log file for details).
> ```

Yay!  I'm glad the new error message is indeed more helpful, and thank you for confirming it.  (The Clink log file now also contains a full Lua callstack, to help in more complicated cases where the cited file:line might not be quite the real root cause location.)
