### ISSUE TITLE
Cmder still not using the "working directory"

### ISSUE THREAD

**Issue by elsassph** [cmderdev/cmder#248]
In a command prompt, I can open cmder in the current directory by typing `cmder "%CD%"` but it should really be opening in the current directory when only typing `cmder`.

**Comment by rbirkby** [comment]
Not starting in the designated 'working directory' prevents the [Open Command Line](https://visualstudiogallery.msdn.microsoft.com/4e84e2cf-2d6b-472a-b1e2-b84932511379) Visual Studio extension from being configured to work with Cmder.

A hack would be to launch an intermediate batch script which contains:

```batch
%~dp0/cmder %cd%
```

However, you get a flash of a dos window before cmder opens.

**Comment by borekb** [comment]
Came to this issue exactly because of the *Open Command Line* VS extension.

If you think the change in behavior would upset some of the users maybe a setting could be created for this - "Open cmder at working directory" vs. "Open cmder at home directory".

**Comment by ckesc** [comment]
Hey!
I`ve integrated cmder and Double Commander (it works for Total Commader too)

- Download [this](https://gist.github.com/ckesc/2af49ff40798685f1c53) script (Taken from [here](http://stackoverflow.com/questions/298562/windows-xp-or-vista-how-can-i-run-a-batch-file-in-the-background-no-windows-di))
- Make small file cmder_runner.bat :
```batch
cmder.exe /start %1
```
- Config your *commander to run 
```cmd
invis.vbs cmder_runner.bat %CD%
```
ofcourse provide full path to `invis.vbs`, `cmder.exe` and `cmder_runner.bat`

**Comment by kuncevich** [comment]
@ckesc the thing is failing when path contained blank spaces.

**Comment by ckesc** [comment]
Try add quotes to `%cd%`

пн, 1 февр. 2016 г., 10:32, Aliaksei <notifications@github.com>:

**Comment by kuncevich** [comment]
Actually I just realized that cmder just working fine without that scripts magic

**Comment by Mikescher** [comment]
I had the same problem (with the current version).
Creating a new task task with the command `cmd /k "%ConEmuDir%\..\init.bat"  -new_console:d:%CD%` and setting it as the startup task fixed it for me.

I think cmder will now start always in the working directory, but for me thats preferable over always being in the home dir.

**Comment by yangbull** [comment]
Anyone can fix it? ConEmu can work with right configeration, but cmder can not ?!

**Comment by erlangp** [comment]
https://github.com/cmderdev/cmder/issues/203
