### ISSUE TITLE
Command history per tab

### ISSUE THREAD

**Issue by SamuelC54** [cmderdev/cmder#2480]
Like mentioned here https://github.com/cmderdev/cmder/issues/2179

Before we had a unique command history per tab (a few months ago) but now the command history is shared for all tabs. How can I change this behavior back

**Comment by daxgames** [comment]
See: https://chrisant996.github.io/clink/clink.html#configuring-clink

**Comment by phanirithvij** [comment]
`history.shared = False` in clink_settings in `cmder_root\config`

**Comment by ryuukk** [comment]
whoever decided to share history for all tabs has a serious problem

i suggest making that option the default

**Comment by chrisant996** [comment]
> whoever decided to share history for all tabs has a serious problem
> 
> i suggest making that option the default

It _**is**_ off by default.

If you're seeing it enabled, then how is that happening?
Something must be explicitly setting it to True.

**Comment by daxgames** [comment]
It is a Cmder default and has been for a long time.

**Comment by chrisant996** [comment]
> It is a Cmder default and has been for a long time. Turn it off in `%cmder_root%\config\clink_settings`

Just to make sure we're on the same page:  shared history enabled in Clink means all open instances share one view of history, and shared history disabled means all open instances update the master history when they close -- like bash and Powershell and fish and zsh all do.

Out of curiosity, why does Cmder override Clink's default to force shared history on, when none of the other shells behave that way?
