### ISSUE TITLE
Update clink as antivirus detects it as a threat.

### ISSUE THREAD

**Issue by quasarea** [cmderdev/cmder#2482]
You are using old and unsupported version of clink https://github.com/mridgers/clink/issues/555

Please update to https://github.com/chrisant996/clink/releases so our antiviruses will not try to fight it.

**Comment by daxgames** [comment]
We are busing https://github.com/chrisant996/clink/releases in the latest releases.

**Comment by quasarea** [comment]
@daxgames I downloaded cmder.zip from https://cmder.net/ few days ago -16/02/2021
In root folder there is Version 1.3.17.1082 file
In vendor\clink binary details show 1.1.10 as a version, https://github.com/chrisant996/clink/releases/tag/v1.1.10
Its over year behind current version.

I updated manually and waiting from my security team feedback, will take a day I guess

**Comment by daxgames** [comment]
Clink 1.1.10 was releaaed on Dec 14 2020.  It is just over 2 months old.

**Comment by quasarea** [comment]
Ok, sorry, I can't count ;(
