### ISSUE TITLE
When I exit my text editor, all commands clear

### ISSUE THREAD

**Issue by Aleksit0** [cmderdev/cmder#2483]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Version Information

191012[64]

Windows 10 Pro
### Description of the issue

When I exit my editor, all commands and output dissapears (ls, cd, pwd...). Pls help

**Comment by chrisant996** [comment]
Can you share more details?

**Comment by Aleksit0** [comment]
> 
> 
> Can you share more details?

So, I'm typing normal cmd commands like cd, ls, pwd, touch... Then I enter my text editor, and when I exit the editor, the screen clears, like someone typed clear.

**Comment by chrisant996** [comment]
What text editor are you using?

Is it a GUI text editor that opens in a separate window?
Or is it a console based text editor that takes over the console screen temporarily?

Does the same problem happen when launching your text editor from a plain normal standalone CMD console window?

**Comment by Aleksit0** [comment]
> What shell are you using?
> What text editor are you using?
> 
> Is it a GUI text editor that opens in a separate window?
> Or is it a console based text editor that takes over the console screen temporarily?
> 
> If the shell you're using is CMD with Clink (the default Cmder shell), does the same problem happen when launching your text editor from a plain normal standalone CMD console window?

Im using ConEmu.
The editor is Micro.

Its console based, and it tajes over the screen.

**Comment by chrisant996** [comment]
> Im using ConEmu.

What command shell are you using inside ConEmu -- cmd, bash, fish, powershell, something else...?

> The editor is Micro.
> 
> Its console based, and it tajes over the screen.

What happens if you do the same thing, with the same command shell, but running the command shell separately, i.e. not inside ConEmu?

**Comment by chrisant996** [comment]
I downloaded micro and tried using it.

Micro is designed to clear the screen when it exits; that's just how micro works (i.e. it isn't an issue in Cmder or ConEmu or Clink).

**Comment by Aleksit0** [comment]
> I downloaded micro and tried using it.
> 
> Micro is designed to clear the screen when it exits; that's just how micro works (i.e. it isn't an issue in Cmder or ConEmu or Clink).

ou ok, thank you :)
