### ISSUE TITLE
How to make my input look like this?

### ISSUE THREAD

**Issue by Aleksit0** [cmderdev/cmder#2486]
[

### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Description of the issue

How can I make my input look like this?
![asd](https://user-images.githubusercontent.com/50078646/109430344-289f0c00-7a01-11eb-817d-327c65916432.PNG)

**Comment by chrisant996** [comment]
Start with the Clink documentation, especially the section on Customising the Prompt.
And/or use ConEmu ANSI escape codes.

**Comment by Aleksit0** [comment]
> Start with the Clink documentation, especially the section on Customising the Prompt.
> And/or use ConEmu ANSI escape codes.

Thank you :)

**Comment by daxgames** [comment]
@Aleksit0 Look at [this](https://github.com/cmderdev/cmder/issues/2348#issuecomment-657242055)

Might be exactly what you want if not it will get you close.

**Comment by Aleksit0** [comment]
> 
> 
> @Aleksit0 Look at [this](https://github.com/cmderdev/cmder/issues/2348#issuecomment-657242055)
> 
> Might be exactly what you want if not it will get you close.
> 
> P.S. If you figure it out post what you did here so other can learn.

I created this file, but I don't see any changes.

**Comment by Aleksit0** [comment]
> 
> 
> @Aleksit0 Look at [this](https://github.com/cmderdev/cmder/issues/2348#issuecomment-657242055)
> 
> Might be exactly what you want if not it will get you close.
> 
> P.S. If you figure it out post what you did here so other can learn.

1. Open cmder location, and open config folder.
2. Edit 'promt.lua' (delete previous code, and paste this one):

https://github.com/cmderdev/cmder/issues/2348#issuecomment-657242055

3. Save your changes and reload cmder.

**Comment by daxgames** [comment]
@Aleksit0 did you get the result you want.

**Comment by Aleksit0** [comment]
> @Aleksit0 did you get the result you want.

Yes
