### ISSUE TITLE
Issue with United States - International keyboard layout

### ISSUE THREAD

**Issue by vinleclair** [cmderdev/cmder#2487]
When using United States - International keyboard layout on Windows 10, Cmder doesn't treat single quotes and double quotes properly. In all other applications, I can press the single quote or double quote key once followed by space to input one single (') or one double (") quote. In Cmder, it inputs me a blank space instead and the only way I can input one single or one double quote is by pressing the corresponding key twice which then inputs two single ('') or two double ("") quotes followed by a backspace to remove the extra quote.

I tried searching online and in this forum but to no avail. Apologies if there is something I'm missing and this is not an actual issue.

**Comment by chrisant996** [comment]
That's how the United States - International keyboard is supposed to operate.

The <kbd>'</kbd> <kbd>"</kbd> <kbd>~</kbd> <kbd>^</kbd> <kbd>`</kbd> keys let you input accented characters.

<kbd>"</kbd><kbd>a</kbd> => ä
<kbd>`</kbd><kbd>a</kbd> => à
<kbd>~</kbd><kbd>a</kbd> => ã
<kbd>^</kbd><kbd>a</kbd> => â
<kbd>'</kbd><kbd>a</kbd> => à

You can enter the various accent keys by themselves like this:

<kbd>"</kbd><kbd>Space</kbd> => "

And so on.

Here is [some documentation](https://support.microsoft.com/en-us/topic/how-to-use-the-united-states-international-keyboard-layout-in-windows-7-in-windows-vista-and-in-windows-xp-e05ce3ed-11f0-8fc2-498e-a214fa6b898f) on how the keyboard works.

**Comment by chrisant996** [comment]
Ah, I see what you're saying.  This is a Clink issue, not a Cmder issue.  I'm opening an issue in the Clink repo to track it.

**Comment by chrisant996** [comment]
I found and fixed the issue in Clink.  Thank you for reporting this!  I'll publish a new version later today (it's just after midnight in my local time).

**Comment by vinleclair** [comment]
Thanks for the quick fix Chris!

How can I update my Clink version in Cmder?

**Comment by chrisant996** [comment]
v1.1.36 is published at [Clink](https://github.com/chrisant996/clink); click Releases on the right side.  You can extract the files from the .zip into the `cmder\vendor\clink` directory (can ignore the *.pdb.zip file and the *setup.exe file).

**Comment by vinleclair** [comment]
@chrisant996 Works like a charm! Thanks again it was driving me nuts! Cheers!

**Comment by daxgames** [comment]
Released Cmder 1.3.18
