### ISSUE TITLE
Bug when using directional button

### ISSUE THREAD

**Issue by bucherpudge** [cmderdev/cmder#2488]
When I open to read the contents of a certain file such as **_nano <file name>_** or **_visudo_**

And when I use the scroll button to go to a certain line or row.

The page down button, cmder automatically adds letter "B" to that line
The page up button, cmder automatically adds letter "A" to that line
The page left button, cmder automatically adds letter "D" to that line
The page righ button, cmder automatically adds letter "C" to that line

If I press repeatedly 3 - 4 times, the buttons add the above characters on their own. But if I press slowly about 1 second after pressing the next button, cmder will not input the above characters

How to fix this error?

**Comment by chrisant996** [comment]
Do you mean that you're using the nano text editor to open a text file, and while using nano the arrow keys are inserting text?  The text is part of the escape codes for terminal input for arrow keys.

That sounds like an issue with nano itself.  The terminal configuration in nano might be incorrect, causing nano to misinterpret the keys that are pressed.

What version of nano are you using, and from where did you get it?  The most recent version of nano for Windows that I can find is v2.5.3 from 2016.  The arrow keys works fine for me with it in CMD and in Cmder.

**Comment by bucherpudge** [comment]
**Dear Sir,**

"_Do you mean that you're using the nano text editor to open a text file, and while using nano the arrow keys are inserting text? The text is part of the escape codes for terminal input for arrow keys._"
==> Yes

"_That sounds like an issue with nano itself. The terminal configuration in nano might be incorrect, causing nano to misinterpret the keys that are pressed_."
==> I don't think so, not only **nano** but also **vim** also got effected by that

"_What version of nano are you using, and from where did you get it? The most recent version of nano for Windows that I can find is v2.5.3 from 2016. The arrow keys works fine for me with it in CMD and in Cmder._"
==> I am using Cmder to connect my vps server. The server is using Ubuntu 20.04 and nano version 4.8. When I edit any files in my vps server, i got these errors

**Comment by chrisant996** [comment]
Oh, are you using Cmder as a remote terminal?  Then it may be a ConEmu issue.

Anyway, at this point it's very clear it is not a Clink issue.  I tried to help because at first it sounded like it might have been related to Clink, but that's definitely not the case, so there's not much I can do to help.  (I'm the maintainer of Clink.)

**Comment by daxgames** [comment]
There is an issue like this reported against conemu.

https://github.com/Maximus5/ConEmu/issues/1691

**Comment by chrisant996** [comment]
Ah, yes, I see.

@bucherpudge you may want to try in a plain default CMD.EXE window, and then launch nano or etc.  It sounds like the problem will likely occur there as well, in which case it's an issue in the cygwin/msys stuff and can only be address in those tools.  And it also sounds like those tools might not be very interested in working outside of mintty and cygwin's own tools.

**Comment by daxgames** [comment]
I believe I tested in plain cmd.exe and found it to work fine poinging back to conemu.  Notes are in thw referenced issue.

**Comment by bucherpudge** [comment]
I tested in cmd/powershell/xshell. There is no errors with directional key

I believe this error belongs to your software

**Comment by chrisant996** [comment]
> I tested in cmd/powershell/xshell. There is no errors with directional key

Thanks for confirming!


> I believe this error belongs to your software

Does the problem occur when using ConEmu and nano?
If so, then the problem is clearly not a Cmder problem, it is a ConEmu problem.

Cmder is not a program.  Cmder is an installation package that contains 4 other products, plus it has a few command scripts that a essentially typing savers.  The error here can't be an error in Cmder, just like if a garage contains 4 cars and one of the cars won't start, it's a problem with the car not with the garage.

**Comment by bucherpudge** [comment]
Dear chrisant996,

Yes this problem occur when using ConEmu. For more specific, the only problem occur when I use {bash::bash}, if I change into {bash::mintty} or others, it works well

**Comment by daxgames** [comment]
@bucherpudge the question @chrisant996 is asking is does it happen when using Conemu that was not provided as part of a Cmder package.

`bash::bash` is running bash in Conemu with a Cmder enhanced prompt.  This Cmder enhanced prompt has no effect on directional key functionality.

`bash::mintty` is running `bash` in the `mintty` terminal emulator embedded in `conemu` so you are essentially `mintty` as the terminal emulator and Conemu is just displaying its output so the problem does not happen.

**Comment by daxgames** [comment]
@bucherpudge also I just tested `nano` editing a file and saw no issues like you describe while using directional keys in the following Cmder session types:

`bash::bash`
`cmd::Cmder` 

I do not normally use nano so the config is completely Git for Windows default.  Have you made config changes the editor?

**Comment by daxgames** [comment]
@bucherpudge try creating a new task in Conemu called `:bash::bash connector` with the following config:

```
set "PATH=%ConEmuDir%\..\git-for-windows\usr\bin;%PATH%" & "%ConEmuDir%\..\git-for-windows\git-cmd.exe" --no-cd --command="%ConEmuBaseDirShort%\conemu-msys2-64.exe" /usr/bin/bash.exe -l -i
```

**Comment by daxgames** [comment]
@bucherpudge did you try the above?
