### ISSUE TITLE
What is the reason that gitui only works inside cmder but not the standalone ConEmu?

### ISSUE THREAD

**Issue by asmwarrior** [cmderdev/cmder#2498]
Hi, this is normally a question.

I try to run a git command line tool [gitui](https://github.com/extrawurst/gitui) inside the standalone ConEmu, but it failed with a blank screen, the main gitui window only shows when I exit the gitui by press the CTRL+C.

While, if I run the same gitui inside the cmder's shell, it shows correctly.

I try to export the settings of ConEmu inside cmder, then import the setting to the standalone ConEmu, but still the same issue happens.

So, here comes a question, why gitui works inside cmder and not the standalone ConEmu? Any setting difference?

I have post the screen cast of this issue and reported in ConEmu's issue, see here:
[ConEmu can't shown the gitui's main window, but Cmder can · Issue #2297 · Maximus5/ConEmu](https://github.com/Maximus5/ConEmu/issues/2297)

So, I hope the cmder's developer can help, thanks!

**Comment by daxgames** [comment]
Setting differences between ConEmu and Cmer are documented [here](https://github.com/cmderdev/cmder/wiki/Cmder-vs.-ConEmu)

Closing as this is not a Cmder issue.
