### ISSUE TITLE
Not autofocus

### ISSUE THREAD

**Issue by J2TeamNNL** [cmderdev/cmder#2499]
I have update cmder (today) to the lastest version 1.3.17 and have this issues (but not in the old version 1.3.2)
When I turn on the Single instance mode (use existing window instead of running new instance), the window instead of not focus, it minimize
![image](https://user-images.githubusercontent.com/26674308/111576721-990ca200-87e3-11eb-8205-485c5a1d668a.png)

**Comment by daxgames** [comment]
Can you please explain `the window instead of not focus, it minimize`.

The setting you are configuring is a Conemu setting.  We do not develop or control how conemu settings affect behavior.

**Comment by J2TeamNNL** [comment]
Sorry, my bad grammar 

I am trying to say that the window is not auto focus like the old version when I open open program 

I am using Windows 10

**Comment by daxgames** [comment]
I am sorry as I said earlier Conwmu is a part of Cmder but we do not develop it we include it unmodified from its binaty release.

I use the current version and I can enable this setting and when I launch Cmder The window pops up like normal and does not launce to the system tray unless i minimize it.

**Comment by J2TeamNNL** [comment]
I have reinstall and even in another computer but it didn't work
But thank you for the response
