### ISSUE TITLE
the scroll branch appear in cmder like this (scroll) not like this (scroll -> origin) why is this happening???

### ISSUE THREAD

**Issue by noamangg** [cmderdev/cmder#2504]
what is the solution ???

**Comment by daxgames** [comment]
Output of `git remote show`?

**Comment by chrisant996** [comment]
What version of Cmder?
What version of Clink?

**Comment by noamangg** [comment]
> What version of Cmder?
> What version of Clink?

Latest Version: 1.3.17 (2020-12-23)

**Comment by noamangg** [comment]
> Output of `git remote show`?

it doesn't show anything

**Comment by daxgames** [comment]
If you have no remotes there is no origin to show

**Comment by daxgames** [comment]
If you have no remotes there is no origin to show

**Comment by noamangg** [comment]
> If you have no remotes there is no origin to show

No, I have a remote, and when I push the project  it's working and add to github
I don't know what is the problem maybe in my PC.

thank you

**Comment by daxgames** [comment]
See below:

![image](https://user-images.githubusercontent.com/7318053/112617725-b7822700-8dfb-11eb-8f9b-7c4a0fe79353.png)
