### ISSUE TITLE
Context Menu Error

### ISSUE THREAD

**Issue by WickedWizard3588** [cmderdev/cmder#2506]
Hey,

I added Cmder to my ENV Variables (as given in the wiki) and I followed [this wiki](https://github.com/cmderdev/cmder/wiki/Context-menu-integration) to add the `Open Cmder Here` to my context menu. But, whenever I click on `Open Cmder Here` in the Windows Explorer, it opens in the default `%USERPROFILE%` and not in the current directory, or otherwise, throws this error 

![image](https://user-images.githubusercontent.com/67627239/111864427-d8bfbf00-8986-11eb-92cd-f477030aea78.png)

Registry Picture
![image](https://user-images.githubusercontent.com/67627239/111864355-5f27d100-8986-11eb-8c56-c8aef5fc2515.png)

Env Vars 
![image](https://user-images.githubusercontent.com/67627239/111864369-723aa100-8986-11eb-9bb3-ef0a411d194a.png)
![image](https://user-images.githubusercontent.com/67627239/111864377-7a92dc00-8986-11eb-8316-d1015bddd057.png)
![image](https://user-images.githubusercontent.com/67627239/111864390-939b8d00-8986-11eb-9071-2d8fc057ea0a.png)
 

I also did the `./Cmder.exe /REGISTER ALL` Command in my Cmder Folder.

Thank you

**Comment by daxgames** [comment]
What are the contents of the Cmder startup task?

**Comment by WickedWizard3588** [comment]
![image](https://user-images.githubusercontent.com/67627239/111877117-bbf7ab80-89c7-11eb-956a-4fb7b18f03cd.png)
These are the contents of my Cmder Startup Task. The ConEmu.xml file given in the picture is also linked [here](https://pastebin.com/dcY1htx9)

**Comment by daxgames** [comment]
That is the tasks page not the startup task.

Click `Startup` in the menu on the left then come back here and click the named task in the `Predefined Tasks (Command Groups)` pane.

All you really need to do to setup context menu integration is `cmder register /USER`.  I believe the wiki predates this functionality existing.  Mine looks like this:

![image](https://user-images.githubusercontent.com/7318053/112616613-527a0180-8dfa-11eb-82b0-c138792bbcf4.png)


I just verified all works fine with Cmder 1.3.18 for both Drives and Folders in Windows Explorer after doing a `cmder register /USER` with the above task config.

**Comment by WickedWizard3588** [comment]
Hey there,

I undid everything as per said, and ensured that I was back to square A. Then, I ran the command given in the README, (for one user) and it worked!!

Thanks.

Also, why didn't the instructions in the Wiki work? Are they faulty :/

**Comment by DRSDavidSoft** [comment]
If you're on Windows 11 (and using Windows Terminal instead of ConEmu), the best method is this:
https://github.com/cmderdev/cmder/issues/2650#issuecomment-1215045313

Here are more information in order to set it up:
https://github.com/cmderdev/cmder/wiki/Seamless-Windows-Terminal-Integration
