### ISSUE TITLE
the easy way for changing the default "λ"?

### ISSUE THREAD

**Issue by noword** [cmderdev/cmder#2507]
I have to write a `prompt.lua` in CMDER/config, like this:
```
function prompt_filter()
    clink.prompt.value = string.gsub(clink.prompt.value, "λ", "$")
end

clink.prompt.register_filter(prompt_filter, 1)
```
Is there any easy/elegance way to do this? Maybe put it in CMDER/config/settings？

**Comment by daxgames** [comment]
If that works for you that is the way.  You could also look at [this](https://github.com/cmderdev/cmder/issues/2348#issuecomment-657242055).  The link provides a more functional/configurable prompt.

**Comment by DRSDavidSoft** [comment]
For future reference, there's now this:
https://github.com/cmderdev/cmder/wiki/Customization#prompt-symbol
