### ISSUE TITLE
Cmder icon reverts to ConEmu icon when "Startup options" option is changed

### ISSUE THREAD

**Issue by JordanRobinson** [cmderdev/cmder#251]
When the menu option for startup options is changed from specific named task after restarting, the icon shown in both the taskbar and the window is that of ConEmu and not the lovely lambda.

Steps to replicate:

Download version 1.1.4.1 of Cmder
Open up the exe
Open the settings menu
Go to the "Startup" option
Change the startup options to non-default (for example auto save)
Restart the application.

Before and after:
![before](https://cloud.githubusercontent.com/assets/1202911/4103277/55bc7986-3154-11e4-9fad-6337d08fd09d.JPG)

![after](https://cloud.githubusercontent.com/assets/1202911/4103278/5a78a134-3154-11e4-8860-2f4c843dbf82.jpg)

I've tested this so far on two machines both running Windows 7 Pro x64.

Please let me know if I can provide any more details or information.

Thanks.

**Comment by darkpenn** [comment]
Workaround to this issue is right-click Cmder.exe and under "send-to" click "Desktop". From the desktop, just drag the newly created Cmder icon onto the taskbar.

**Comment by RDugan23** [comment]
I having the same issue with the taskbar icon not working properly. The above "workaround" works fine as long as I keep cmder in my downloads directory, or on my desktop, or in a folder on my desktop. As soon as a move it to a directory other than my downloads folder or a folder located on my desktop (like my Program Files or Applications directory) then the workaround stops working. I don't know enough about Windows to know why this is happening an what the difference is between the different folders but it's very confusing. I'm running Windows 8.1. Any help or explanations would be much appreciated.

**Comment by yildizmy** [comment]
If some of the workarounds may cause displaying of multiple icons on the taskbar after starting cmder, try the following approach: 

1.  Extract cmder to **C:\cmder** instead of Program Files, AppData, etc.
2. Right click on Cmder.exe then click "Pin to Start" and "Pin to taskbar" options.
