### ISSUE TITLE
Auto close window input `exit` on cmd.exe

### ISSUE THREAD

**Issue by ChangshengYan** [cmderdev/cmder#2510]
repro steps:
1. open cmder.
2. run `start cmd.exe` to start a new cmd window.
3. run `exit` to exit the cmd process.
4. It shows "Press Enter or Esc to exit..." and I have to key in Enter or Esc to exit this window.
![image](https://user-images.githubusercontent.com/37908328/112705500-59396080-8e5c-11eb-92d6-b13a05cb1ddc.png)

The desired behavior would be this window automatically close after input "exit" (which is the behavior of command prompt). Is there any setting for such behavior?

**Comment by daxgames** [comment]
This is not a feature of Cmder and cannot be addressed by this team.

**Comment by chrisant996** [comment]
That prompt comes from ConEmu.  Check ConEmu documentation and/or settings and/or post an inquiry in the ConEmu repo.

https://github.com/Maximus5/ConEmu/blob/8cc8f95bfe40ea1ec9c4a55ce158cca7a875d7b5/src/ConEmuCD/ConsoleMain.cpp#L1799
