### ISSUE TITLE
Can't get powershell version

### ISSUE THREAD

**Issue by chan15** [cmderdev/cmder#2511]
I user cmder to operate vagrant, it's work perfectly before 1.3.18, when I run vagrant up under 1.3.18 shows error:

```
Vagrant failed to initialize at a very early stage:

The version of powershell currently installed on this host is less than
the required minimum version. Please upgrade the installed version of
powershell to the minimum required version and run the command again.

  Installed version: N/A
  Minimum required version: 3
```

**Comment by daxgames** [comment]
I don't see how this could be related to Cmder 1.3.18.

Can you.provide the output of `$PSVERSIONTABLE`

**Comment by chan15** [comment]
I tried two ways

* echo $PSVERSIONTABLE // get echo $PSVERSIONTABLE
* echo %PSVERSIONTABLE% // get %PSVERSIONTABLE%

1.3.18 and  1.3.17 both the same result

**Comment by daxgames** [comment]
So you are not using a powershell session.  This only works in a powershell session.

From Cmder session type `where powershell` to see if powershell is in the path.

Start a powershell session and type `$psversiontable`  this will give you the version of powershell installed.

Are you sure you did not upgrade Vagrant to a version that requires a newer version of Powershell?  `vagrant --version`

**Comment by chan15** [comment]
if in PowerShell mode I got

```
λ  echo $psversiontable

Name                           Value
----                           -----
PSVersion                      5.1.19041.610
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.610
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

my vagrant version is 2.2.14, and I type `vagrant global-status` in 1.318 I got:

```
λ  vagrant global-status
5
Vagrant failed to initialize at a very early stage:

The version of powershell currently installed on this host is less than
the required minimum version. Please upgrade the installed version of
powershell to the minimum required version and run the command again.

  Installed version: N/A
  Minimum required version: 3
```

again I type `vagrant global-status` in _1.3.17_ **cmder mode** I got:

```
λ vagrant global-status
id       name      provider   state    directory
---------------------------------------------------------------------------
c9815f2  default   virtualbox poweroff D:/vagrant/ubuntu20
4f49b801  homestead virtualbox running  D:/vagrant/homestead
```

**Comment by daxgames** [comment]
`where powershell` output from Cmder session?

**Comment by chan15** [comment]
1.3.18

```
λ where powershell
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
```

1.3.17
```
λ where powershell
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
```

**Comment by chrisant996** [comment]
Does vagrant have a .lua script that somehow integrates with Clink?
If so then maybe there is some issue there, though that seems unlikely.

**Comment by daxgames** [comment]
@chrisant996 Seems unlikely.

@chan15 you could test his theory by replacing the `%cmder_root%\vendor/clink` folder in 1.3.18 with the one from 1.3.17 and restarting cmder.

**Comment by chan15** [comment]
> @daxgames 
> 
> @chan15 you could test his theory by replacing the `%cmder_root%\vendor/clink` folder in 1.3.18 with the one from 1.3.17 and restarting cmder.

would you please tell me how to do that specifically, thaks

**Comment by daxgames** [comment]
Use windows explorer to rename `%cmder_root%\vendor\clink` in 1.3.18 and copy `%cmder_root%\vendor\clink` from 1.3.17 into the same location in 1.3.18

**Comment by chan15** [comment]
> Use windows explorer to rename `%cmder_root%\vendor\clink` in 1.3.18 and copy `%cmder_root%\vendor\clink` from 1.3.17 into the same location in 1.3.18

```
λ vagrant global-status
5
Vagrant failed to initialize at a very early stage:

The version of powershell currently installed on this host is less than
the required minimum version. Please upgrade the installed version of
powershell to the minimum required version and run the command again.

  Installed version: N/A
  Minimum required version: 3
```

the same.

**Comment by chrisant996** [comment]
That means it isn't related to Clink.  That at least helps narrow down the possibilities.

**Comment by daxgames** [comment]
This actually appears to be ConEmu related.  I can open cmd.exe and execute `%cmder_root%\vendor\init.bat` from Cmder 1.3.18 and vagrant functions properly.

I can start a `cmd.exe` session in ConEmu that is bundled with Cmder without running `%cmder_root%\vendor\init.bat` and Vagrant fails with the reported issue.

As a temporary fix you could use windows explorer to rename `%cmder_root%\vendor\conemu-maximus5` in 1.3.18 and copy `%cmder_root%\vendor\conemu-maximus5` from 1.3.17 into the same location in 1.3.18.

Closing with upstream label.
