### ISSUE TITLE
Cannot Run File windows blocks it

### ISSUE THREAD

**Issue by Dexterz167** [cmderdev/cmder#2515]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [x] Question

**Comment by Dexterz167** [comment]
PLS FIX THIS

**Comment by chrisant996** [comment]
To fix it requires a special kind of code signing certificate, which is only issued to companies.  Open source projects by volunteers do not qualify for that kind of code signing certificate.

Click the "more info" link, then click "run anyway".  Once enough people around the world do that, then Windows will automatically stop blocking the file.  It's part of the SmartScreen protection.

There is nothing else that can be done about it.
