### ISSUE TITLE
Errors in using vagrant in the latest version of cmder

### ISSUE THREAD

**Issue by water6000-zhu** [cmderdev/cmder#2521]
When using the latest version of cmder to run vagrant, you will be prompted that the version of PowerShell is too low. But in fact, the version of PowerShell that comes with win10 is 5.1. I don't know why you will be prompted this error. However, there is no error when running under the version of cmder 1.3.17. Please tell me how to solve it. Thank you

**Comment by daxgames** [comment]
This is not a cmder issue.  The same issue has been reported using the latest Conemu.  You could copy an older conemu release into the `%cmder_root%\vendor` folder to resolve it until a newer conemu fixes the issue.

**Comment by water6000-zhu** [comment]
Sorry, the wrong place. Thank you
