### ISSUE TITLE
'ssh' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by litechang** [cmderdev/cmder#2524]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Description of the issue

Hi, 

I would like to use Cmder for ssh connection. Once type 'ssh' in console, it showed following error message, 

'ssh' is not recognized as an internal or external command, operable program or batch file. 

Could you help suggest the solution? 

Thanks,
LC 

![error](https://user-images.githubusercontent.com/61524998/114474866-f958ee80-9bab-11eb-956d-5ca166a6a06e.JPG)

**Comment by chrisant996** [comment]
Ssh is not installed by default on Windows. Has it been specifically manually installed?

This sounds unrelated to Cmder.

**Comment by daxgames** [comment]
Did you download Cmder full or mini

**Comment by litechang** [comment]
> Did you download Cmder full or mini

I downloaded full version and double checked the size as 116MB.

**Comment by daxgames** [comment]
Output of `set g`?

**Comment by litechang** [comment]
![image](https://user-images.githubusercontent.com/61524998/114636957-15789080-9c7d-11eb-98e2-77198e9114a5.png)

**Comment by daxgames** [comment]
Output of `set path`

**Comment by litechang** [comment]
![image](https://user-images.githubusercontent.com/61524998/114649929-3b5e5f00-9c96-11eb-843f-e637afb8a4c9.png)

**Comment by daxgames** [comment]
You have some duplication in your path and this `;";c:\litechang...git\cmd"` is invalid and COULD be the cause of all the issues by breaking Cmders path parsing. Where is that coming from?

It looks like the folder for Git for Windows that contains ssh.exe embedded in Cmder is not in the path and this is odd because it should be.  Other paths Cmder adds are missing also.

Fix the path and see if that helps.  If not send the output of  `%cmder_root%\vendor\bin\cmder_diag.cmd`

**Comment by daxgames** [comment]
BTW, text copy and paste of requested output is preferred than screenshots.

**Comment by daxgames** [comment]
@litechang Did you find a solution?

**Comment by litechang** [comment]
After path fixing, issue is remained. 

Thanks for all the help. I have setup Putty for ssh connection.

**Comment by daxgames** [comment]
Your path had a lot of problems.  Did you fix them all.  Looks like you had a couple of cmder installs in different places, at least one git install other than cmder.

The cmder diag output might help us help you fix it.
