### ISSUE TITLE
VSCode integration - File not found

### ISSUE THREAD

**Issue by boris-remo** [cmderdev/cmder#2526]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

Cmder Version 1.3.18.1106
Conemu Version 210304

Windows 10 Pro 10.0.19042 Build 19042

### Description of the issue
The same exact issues as described here - https://github.com/cmderdev/cmder/issues/2489
But none of the proposed solutions helped me.

This is my current `vscode_init_args.cmd` file
![image](https://user-images.githubusercontent.com/81965134/114730547-e0ca0f00-9d38-11eb-8347-02dcdabef657.png)

I was trying to follow [the instructions in the docs](https://github.com/cmderdev/cmder/wiki/Seamless-VS-Code-Integration) to integrate VSCode with Cmder. Everything works well except for this error. 

Based on the conversation between @chrisant996 and @WickedWizard3588 in https://github.com/cmderdev/cmder/issues/2489 I'm led to believe that the documentation has incorrect instructions.

**Comment by WickedWizard3588** [comment]
Hello @boris-remo,
Yes, in the conversation, I was myself forced to conclude that the documentation IS wrong, and the `vscode_init_args.cmd` is, created by default, the first time when the integrate Cmder terminal is launched. The file is copied from `%CMDER_ROOT%\vendor\bin\vscode_init_args.cmd.default`.

**Comment by daxgames** [comment]
I fixed the Docs

**Comment by boris-remo** [comment]
@daxgames I think something is still off.

The docs mention the `vscode_init` files should be in `%cmder_root%\bin`, but when I look at the repo (and my local dirs), the default files are located in `%cmder_root%\vendors\bin` - https://github.com/cmderdev/cmder/tree/master/vendor/bin

So when the docs say:

> Edit either the%cmder_root%\bin\vscode_init_args.cmd or the %cmder_user_bin%\vscode_init_args.cmd script

Those files don't exist 😕 

If I don't change any script files and just open the terminal I see
![image](https://user-images.githubusercontent.com/81965134/114906732-40481d80-9e12-11eb-89de-2ea74f75ae36.png)

**Comment by daxgames** [comment]
I will look

**Comment by daxgames** [comment]
I opened code.exe.  edited the settings.json and added:

```
    "terminal.integrated.shell.windows": "cmd.exe",
    "terminal.integrated.shellArgs.windows": [
      "/K",
      "C:\\users\\dgames\\cmder - dev\\vendor\\bin\\vscode_init.cmd"
    ],
```

and started a terminal.

![image](https://user-images.githubusercontent.com/7318053/114959089-536ae580-9e32-11eb-940a-4b2c5516ead4.png)

No issues

**Comment by chrisant996** [comment]
> ```
>     "terminal.integrated.shell.windows": "cmd.exe",
>     "terminal.integrated.shellArgs.windows": [
>       "/K",
>       "C:\\users\\dgames\\cmder - dev\\vendor\\bin\\vscode_init.cmd"
>     ],
> ```

I think the observation was that the docs are missing the `vendor\\` part.

So if followed literally, they don't quite work yet.

**Comment by daxgames** [comment]
@boris-remo are you launching code.exe from Cmder?

If you added the following from the wiki to `sources.json`:

```
"terminal.integrated.shell.windows": "cmd.exe",
    "terminal.integrated.shellArgs.windows": [
      "/K",
      "%cmder_root%\\vendor\\bin\\vscode_init.cmd"
    ],
```

Then it only works if launched from Cmder where `%cmder_root%` is set.  You can, as it says in the wiki, 'define an environment variable' sonit works launching outside Cmder OR you can use the real path as I did and not use `%cmder_root%`.

**Comment by chrisant996** [comment]
@daxgames In this specific spot under step 6, the documentation appears to be missing the `vendor\\` part of the path:

> - Edit either the`%cmder_root%\bin\vscode_init_args.cmd` or the `%cmder_user_bin%\vscode_init_args.cmd` script to set appropriate Cmder settings for vscode according the scripts internal documentation.

My understanding is that's what @boris-remo is referring to as a spot in the documentation that isn't possible to follow literally -- it refers to files that (if interpreted literally) seem to not exist.

**Comment by daxgames** [comment]
And what I am saying is if the vscode setup has either the real path or an env variable that is set that points to the real path then the file will be created automatically EXACTLY where the wiki says it is supposed to be as in my example above.

`%cmder_root%\bin\vscode_init_args.cmd` in the screenshot did not exist before I ran a terminal in vscode that was properly configured to run cmder.

You can see in the screenshot where it gets created successfully by copying it to the location specified in the wiki the first time a terminal is run from vscode.

That file is user config.  ALL user config lives in `%cmder_root%\config`

**Comment by daxgames** [comment]
![image](https://user-images.githubusercontent.com/7318053/115066737-f0bf2b80-9ebd-11eb-98a8-5c3d9c030d79.png)

**Comment by boris-remo** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/7318053/115066737-f0bf2b80-9ebd-11eb-98a8-5c3d9c030d79.png)

I spotted something interesting. When you run `ls bin` I see a `code.cmd` and a `vscode` directory. [I don't see them in the repo](https://github.com/cmderdev/cmder/tree/master/bin) or in my local env. Where did they come from?

![image](https://user-images.githubusercontent.com/81965134/115070106-65a95a00-9eec-11eb-9f1c-81d32fff3555.png)

I have already set up env vars according to the docs.

![image](https://user-images.githubusercontent.com/81965134/115070664-262f3d80-9eed-11eb-9fa2-f8a3d233e98b.png)

Also `ls` is not working inside vscode. What am I doing wrong?
![image](https://user-images.githubusercontent.com/81965134/115071466-34318e00-9eee-11eb-9085-6542e00a4136.png)

**Comment by daxgames** [comment]
@boris-remo I download VS Code and set it up as a [portable](https://code.visualstudio.com/docs/editor/portable) install in `%cmder_root%\bin\vscode` folder.  I created the `%cmder_root%\bin\code.cmd` file to make it easy for me to launch VS Code by simply running `code`.  Cmder is portable so I try to stick with portable apps where possible.  It is just how I did the install of VS Code vs. installing using an installer package from Microsoft and is not really relevant to this issue.

Regarding `ls` not working inside vscode did you download Cmder Full or Mini.  `ls` is not included in mini.

If you downloaded Full and the init script is not running cleanly and exiting prematurely because the vscode `settings.json` cannot find the source file to create the `%cmder_root%\bin\vscode_init_args.cmd` that could also be causing `ls` to fail if Cmder is not initializing fully.

FWIW This is what I see on subsequent launches of VSCode terminals when all is properly configured using the DEFAULT `%cmder_root%\bin\vscode_init_args.cmd`.

![image](https://user-images.githubusercontent.com/7318053/115088781-f842fc80-9ede-11eb-870c-bcb5fb0c7351.png)

**Comment by chrisant996** [comment]
@daxgames @boris-remo I just tried a fresh portable install of cmder-mini, and following the steps in [Seamless VS Code Integration](https://github.com/cmderdev/cmder/wiki/Seamless-VS-Code-Integration) precisely and literally.

It worked easily and perfectly for me:

![image](https://user-images.githubusercontent.com/17440311/115120801-39c9bb00-9f64-11eb-942c-d0b7597890b5.png)

So as far as I can see from empirical experimentation, the documentation seems to be accurate.  So if it's not working on a computer, I think there must be something misconfigured somewhere.

**Comment by boris-remo** [comment]
I deleted cmder and un-archived it in a new dir. I follow the same steps just like I did last time and now it works. FML 🤷 

I did find that [these docs](https://github.com/cmderdev/cmder/wiki/Setting-up-Environment-Variables#examples) still refer to the old way of using cmder in vscode
