### ISSUE TITLE
[Error] Get strange color background thing when integrate Cmder to Windows 10 terminal

### ISSUE THREAD

**Issue by buinguyenhoangtho** [cmderdev/cmder#2527]
I use default settings when intergrate Cmder to Windows 10 Terminal. Both are  latest version
Proof
[x]![proof](https://i.imgur.com/QKI5mb0.png)

**Comment by chrisant996** [comment]
It looks as if a background image may have been configured, as in the [background image](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-appearance#background-image-path) section of the Windows Terminal documentation.

What happens if a long line of text is typed?  Does it extend past the black rectangle into the dimmed image?  Is the custom proportional spaced font also affecting the rendering?

**Comment by buinguyenhoangtho** [comment]
Thanks for the reply. I changed every font i got ( even default windows it keeps getting the bug like that). Settings is default. 
![proof2](https://i.imgur.com/dKYxKSS.png) . My background is fill

**Comment by buinguyenhoangtho** [comment]
If i print long text, it keep this ![Proof3](https://i.imgur.com/dGHzTpq.png)

**Comment by chrisant996** [comment]
Can you clarify what you're reporting as the issue?
- That a background image is showing up?
- Or that the black background of some lines of text is obscuring the background image?

If the latter, then it sounds like the same as issue #2516. The information there may be helpful to configure the Cmder prompt to avoid the black bars.

**Comment by buinguyenhoangtho** [comment]
Hey there . The method with #2516  you mention is working. Thanks for your help. I will close this comment at fixed :D

**Comment by daxgames** [comment]
@buinguyenhoangtho did you download the new build and use the new configurable prompt to fix this or did uou edit

https://github.com/cmderdev/cmder/blob/c34eb735556d5f2ccf59b042d17d5f2880414356/vendor/clink.lua#L50

**Comment by buinguyenhoangtho** [comment]
@daxgames  I'm download the latest and follow the comment :D.

**Comment by chrisant996** [comment]
> @daxgames I'm download the latest and follow the comment :D.

Which comment?  :)
- The comment about how to modify clink.lua? (Which will get overwritten next time you install an upgrade for Cmder.)
- Or the comment about how to use the latest _pre-release_ build linked in #2516 and use the brand-new configurable settings? (Which can survive across upgrades of Cmder.)

**Comment by buinguyenhoangtho** [comment]
@chrisant996  This one 
```
function my_prompt_filter()
    cwd = clink.get_cwd()
    prompt = "\x1b[1;32;49m{cwd} {git}{hg}{svn} \n\x1b[2;37;49m{lamb} \x1b[0m"
    new_value = string.gsub(prompt, "{cwd}", cwd)
    clink.prompt.value = string.gsub(new_value, "{lamb}", "★")
end

clink.prompt.register_filter(my_prompt_filter, 1)
```

**Comment by buinguyenhoangtho** [comment]
> > @daxgames I'm download the latest and follow the comment :D.
> 
> @buinguyenhoangtho Which comment? :)
> 
> * The comment about how to modify clink.lua? (Which will get overwritten next time you install an upgrade for Cmder.)
```
@chrisant996  This one 
```
function my_prompt_filter()
    cwd = clink.get_cwd()
    prompt = "\x1b[1;32;49m{cwd} {git}{hg}{svn} \n\x1b[2;37;49m{lamb} \x1b[0m"
    new_value = string.gsub(prompt, "{cwd}", cwd)
    clink.prompt.value = string.gsub(new_value, "{lamb}", "★")
end

clink.prompt.register_filter(my_prompt_filter, 1)
```

> * Or the comment about how to use the latest _pre-release_ build linked in #2516 and use the brand-new configurable settings? (Which can survive across upgrades of Cmder.)
 Where can i find the latest_pre-release btw? Can you show me the way?

**Comment by daxgames** [comment]
@buinguyenhoangtho the new code includes a configurable prompt with a settings file in `%cmder_root%/config`  you should be able to set all colors in that and not use a custom prompt filter at all.

**Comment by buinguyenhoangtho** [comment]
> @buinguyenhoangtho the new code includes a configurable prompt with a settings file in `%cmder_root%/config` you should be able to set all colors in that and not use a custom prompt filter at all.

oh ok i get it.

**Comment by daxgames** [comment]
Latest pre release.  https://ci.appveyor.com/project/MartiUK/cmder/build/artifacts

**Comment by daxgames** [comment]
Please let me know if it works for you.

**Comment by buinguyenhoangtho** [comment]
Ok let me try. I'm usually download it from main website so it old build i afraid? 
![Old?](https://i.imgur.com/iNHjpjm.png)

**Comment by buinguyenhoangtho** [comment]
@daxgames This is prebuild-release and still get the black board
![still](https://i.imgur.com/eS6j6u1.png)

**Comment by chrisant996** [comment]
> @daxgames This is prebuild-release and still get the black board

Did you configure it to use 49? Try that.

**Comment by daxgames** [comment]
@buinguyenhoangtho there should be a `%cmder_root%\config\cmder_prompt_config.lua` file you can edit colors in and restart Cmder.  The new build does not xhange default settings, it just allows the user to configure them to work with alternate terminals

**Comment by buinguyenhoangtho** [comment]
> @buinguyenhoangtho there should be a `%cmder_root%\config\cmder_prompt_config.lua` file you can edit colors in and restart Cmder. The new build does not xhange default settings, it just allows the user to configure them to work with alternate terminals

so this the result i guess
![result](https://i.imgur.com/LJKtA00.png)

**Comment by daxgames** [comment]
I am suprised the entire prompt is green.

**Comment by buinguyenhoangtho** [comment]
> I am suprised the entire prompt is green but at least there are no black bars.

yes me too. But one more thing, i can't find anyway to make my VScode terminal after intergrated with Cmder support Emoji. Although Vscode is support emoji itself.

**Comment by buinguyenhoangtho** [comment]
![Emoji](https://i.imgur.com/2EHSlBh.png)

**Comment by chrisant996** [comment]
> I am suprised the entire prompt is green but at least there are no black bars.

The `lamb_color` in the screen shot has `30;32m`.

32 = green.

It's green because that's what it's been explicitly set to.

**Comment by hectormz** [comment]
Changing from:

```
uah_color = "\x1b[1;33;40m" -- Green = uah = [user]@[hostname]
cwd_color = "\x1b[1;32;40m" -- Yellow cwd = Current Working Directory
lamb_color = "\x1b[1;30;40m" -- Light Grey = Lambda Color
```

to 
```
uah_color = "\x1b[1;33;49m" -- Green = uah = [user]@[hostname]
cwd_color = "\x1b[1;32;49m" -- Yellow cwd = Current Working Directory
lamb_color = "\x1b[1;30;49m" -- Light Grey = Lambda Color
```

got rid of black band and prompt background follows Windows terminal appearance
