### ISSUE TITLE
I cannot type a single word in Cmder Laragon

### ISSUE THREAD

**Issue by eduardonwa** [cmderdev/cmder#2528]
I can't type anything in the Cmder terminal when I launch "Terminal" from Laragon, why is that? 

This is what I see and as you probably tell I can't even see the current directory: https://imgur.com/qm5cvuw

I am using:

Apache httpd-2.435-win64-VC15 port 80
MySQL mysql-5.7.24-windx64 s port 3306
PHP version is 8
NodeJS version is 15.14.0

If I open up a new console I see the current directory path but I still can't type.

I checked to see if I had Windows updates and it is not the case.

I also cannot type in cmd which I think is what powers Cmder. I can type however on my other terminals such as Gitbash and Powershell.

Restarting the console allows me to type 1 letter after it's been restarted.
Restarting as admin does nothing.

**Comment by daxgames** [comment]
Last time I looked the version of Cmder included with Laragon was very old an not easy to upgrade.  I offered a PR to the Laragon developer along with some suggestions to better decouple Cmder from Laragon amd make it easier for users to upgrade Cmder as Cmder upgrades are released.

See: https://github.com/leokhoa/laragon/pull/199
