### ISSUE TITLE
Settings not saving

### ISSUE THREAD

**Issue by crowaaron** [cmderdev/cmder#2529]
I keep making changes to my settings file and it is not saving. I am running cmder and admin on Windows 10.

**Comment by daxgames** [comment]
How are you.making changes

**Comment by crowaaron** [comment]
I am making the changes through the settings editor.

**Comment by daxgames** [comment]
New sessions and/or closing and restarting is losing these changes?  Can you provide an example?

**Comment by daxgames** [comment]
How are you determining changes are not saved?

**Comment by crowaaron** [comment]
When I make my changes, close cmder and reopen it and check the settings,
the previous info I put in there is gone.

**Comment by daxgames** [comment]
And can tou peovide an example of what you are changing?

**Comment by daxgames** [comment]
If what you are saying is what is happening it is most likely a Conemu issue but I want to test it forst on my end.

I have never had this issue and I use Cmder nearly every day.

**Comment by crowaaron** [comment]
Great thanks. Do you change settings frequently?

**Comment by daxgames** [comment]
I do can you give me an example of a change you are making?

**Comment by daxgames** [comment]
@crowaaron ???

**Comment by crowaaron** [comment]
I gave up and moved on bro. Good luck.
