### ISSUE TITLE
Passing command output as argument?

### ISSUE THREAD

**Issue by Lunchb0ne** [cmderdev/cmder#2530]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Version Information

Cmder : 1.3.18.1114
Conemu : 210304
Clink : 1.1.45.1c3985

Windows 10 Pro 21H1

### Description of the issue

I was trying to open up a directory in something like Visual Studio Code, based on the output from another command so something like `spicetify -c` (Which gives me the path to some config file).

Right now the current best way I found out was using the backtick substitution in the `for /F` loop to pass in the command and set up a macro in the aliases as such:
```
codee=for /F "usebackq delims=" %A in (`$*`) do code %A
```

I was wondering if there is a better way to achieve this, just not for code but for any other command too, something akin to using `$(commandhere)` from Unix.

**Comment by daxgames** [comment]
You have run into a limitation of `cmd.exe`.   You could use a `bash::bash` session to get more of what you want.
