### ISSUE TITLE
Feature Request: Add a hotkey for renaming the current tab

### ISSUE THREAD

**Issue by ThePiGuy** [cmderdev/cmder#2531]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [ ] Question

### Description of the issue
It would be very helpful if there was a hotkey or command to quickly rename the current tab. Thanks!

**Comment by daxgames** [comment]
This would be a request for the conemu team.

**Comment by DRSDavidSoft** [comment]
Sorry to revive the issue, but the open issue https://github.com/Maximus5/ConEmu/issues/1521 and https://github.com/Maximus5/ConEmu/issues/1472 are required for this to work.

Then, using the simple command `title <tab_name>` it would be possible to rename tabs!
