### ISSUE TITLE
How do I make cmder run a .py from a .bat/command?

### ISSUE THREAD

**Issue by SpaceNerden** [cmderdev/cmder#2534]
I want to make cmder run `python main.py` from a command line
Sublime Build -> Trigger Command -> Open cmder _and_ run main.py
The reason for this is that Sublime just does not have support for color on the default terminals. That's about it. I just want to replace the default terminal with cmder.

I looked into the [Seamless Sublime Text 3 Integration](https://github.com/cmderdev/cmder/wiki/Seamless-Sublime-Text-3-Integration) part of the wiki but I want it _seperate_ from the editor, so I don't have half my screen taken up by the console. I want it to open when running the script, and the ability to close it and free some more screenspace without having to close the whole editor.

(If my english is really screwed up, apologies. I need sleep.) 
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Version Information
Latest, Just installed it.

**Comment by chrisant996** [comment]
According to [Cmder docs](https://github.com/cmderdev/cmder/blob/master/README.md) the `/x` flag passes arguments to ConEmu.

According to [ConEmu docs](https://conemu.github.io/en/ConEmuArgs.html) the `-run` flag lets you specify a comment to run.

So `cmder.exe /x "-run main.py"`.

Have you tried that already?

**Comment by daxgames** [comment]
You can also do `cmder.exe -- -run main.py` and is probably better than `-x "-run main.py"`

**Comment by SpaceNerden** [comment]
Yup. it works! Thanks!
