### ISSUE TITLE
bash autocompletion cdable_vars

### ISSUE THREAD

**Issue by leonardopsantos** [cmderdev/cmder#2543]
Hi there! I've set up a variable to shorten a much-used folder path, and I'd like to know if the autocompletion should work. Let's say that I have the following folder structure:

```
base
  |- A
  |- B
```

And on my `.bashrc` I have:

```
shopt -s cdable_vars
export projs=/c/base
```

What I would like to happen is to type `cd ba` and have the autocomplete fill in the rest of the path, like if I had typed `cd /c/bas`. Should this work?

**Comment by daxgames** [comment]
Probably in `zsh` but not `bash` and cmder does not include `zsh`
