### ISSUE TITLE
Showing "warning: replacing arglink for *" on all commands

### ISSUE THREAD

**Issue by HeyItsJono** [cmderdev/cmder#2544]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

Cmder 1.3.18
ConEmu 210422 preview

Windows 10 Enterprise 18363.1256

### Description of the issue

Opening Cmder results in the following output:

> warning: replacing arglink for 'b' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'd' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'g' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'h' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'help' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for '--help' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'asset-sizes' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'new' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for '-v' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'build' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'destroy' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'set' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 's' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'init' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'addon' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'generate' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 't' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'v' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'serve' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for '--version' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'version' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'server' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'test' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for '-h' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'github-pages:deploy' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'get' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'source' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'apikey' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'uninstall' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'setapikey' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'feature' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'outdated' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'search' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'list' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'upgrade' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'pin' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'sources' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'install' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'source' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'apikey' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'uninstall' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'setapikey' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'feature' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'outdated' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'search' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'list' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'upgrade' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'pin' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'sources' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'install' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'repo-reset' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'repo-status' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'create-archive' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'repo-update' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'repo-clone' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'merge-pr' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'print-tags' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'plugin' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'platform' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'run' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'emulate' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'compile' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'prepare' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'create' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'build' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'plugin' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'platform' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'run' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'emulate' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'compile' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'prepare' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'create' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'build' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'run' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'build' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'new' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'remove' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'ef' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'list' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'publish' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'sln' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'clean' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'add' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'cherry-pick' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'checkout' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'rebase' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'commit' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'worktree' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'diff' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'switch' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'annotate' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'restore' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'apply' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'svn' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'submodule' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'difftool' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'reset' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'remote' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'branch' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'push' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'config' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'clone' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'merge' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'pull' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'fetch' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'stash' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'add' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'logs' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'config' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'scale' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'describe' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'exec' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'port-forward' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'get' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'view' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'config' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'time' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'accounts' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'statistics' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'computer' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'session' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'use' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'help' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'cache' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'update' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'install' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'remove' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'list' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'rm' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'link' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'audit' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'up' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'find' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'uninstall' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'publish' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'outdated' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'search' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'ln' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'ls' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'run-script' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'run' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'll' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'proxy' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'ls' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'arch' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'use' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'uninstall' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'list' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'install' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'hash' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'download' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'help' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'install' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'show' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'config' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'search' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'list' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'completion' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'uninstall' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'wheel' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'freeze' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'graph' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'open' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'install' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'update' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'shell' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'sync' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'lock' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'check' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'uninstall' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'run' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'clean' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'virustotal' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'cache' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'update' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'install' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'home' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'alias' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'cleanup' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'depends' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'hold' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'unhold' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'config' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'info' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'bucket' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'prefix' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'uninstall' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'help' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'reset' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'provision' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'init' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'package' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'snapshot' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'box' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'plugin' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'up' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'ssh' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'destroy' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'reload' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'halt' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'help' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'cache' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'ls' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'publish' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'team' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'unlink' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'why' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'pack' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'global' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'link' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'licenses' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'owner' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'run' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'tag' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'upgrade' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'outdated' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'version' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'init' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'check' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'remove' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'config' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).
> warning: replacing arglink for 'add' in C:\Program Files\Cmder\config\cmder.lua:182 (see log file for details).

Running `clink info` shows the following:

    λ clink info
    version  : 1.1.45.1c3985
    session  : 164972
    binaries : C:\Program Files\Cmder\vendor\clink
    state    : C:\Program Files\Cmder\config
    log      : C:\Program Files\Cmder\config\clink.log
    settings : C:\Program Files\Cmder\config\clink_settings
    history  : C:\Program Files\Cmder\config\clink_history
    scripts  : C:\Program Files\Cmder\vendor ; C:\Program Files\Cmder\vendor\clink ; C:\Program Files\Cmder\config
    inputrc  : %clink_inputrc%
                 (unset)
             : %userprofile%
                 C:\Users\Jono\.inputrc
                 C:\Users\Jono\_inputrc
             : %localappdata%
                 C:\Users\Jono\AppData\Local\.inputrc
                 C:\Users\Jono\AppData\Local\_inputrc
             : %appdata%
                 C:\Users\Jono\AppData\Roaming\.inputrc
                 C:\Users\Jono\AppData\Roaming\_inputrc
             : %home%
                 C:\Users\Jono\.inputrc
                 C:\Users\Jono\_inputrc

**Comment by daxgames** [comment]
I can't reproduce this issue.

**Comment by chrisant996** [comment]
Where did the `config\cmder.lua` script come from?

The script is trying to redefine/merge a bunch of linked argmatchers that were already defined by something else.  That never worked completely properly even with Clink 0.4.9, and Clink 1.0.0 rewrote how argmatchers work such that redefining/merging linked argmatchers works even less than before.  Therefore Clink reports an error.

My guess is that the config\cmder.lua file is some kind of manually produced file that duplicates a lot of stuff from other scripts, and Cmder has been upgraded on that computer for the first time since Cmder picked up the newer Clink v1.x fork.

The best way to fix the errors is to either update the config\cmder.lua file so it isn't duplicating things, or to remove the other scripts that it's duplicating.  In other words, for some command "foo", there should be only one script that registers arguments for that command's argmatcher.  Right now there are multiple scripts registering argmatchers for the same command, and Clink v1.0 and higher have stopped even trying to guess how to merge them together without breaking things.

Sorry for the inconvenience!

**Comment by daxgames** [comment]
I not even notice that.  That file is not a part of cmder.

**Comment by HeyItsJono** [comment]
> Where did the `config\cmder.lua` script come from?
> 
> The script is trying to redefine/merge a bunch of linked argmatchers that were already defined by something else. That never worked completely properly even with Clink 0.4.9, and Clink 1.0.0 rewrote how argmatchers work such that redefining/merging linked argmatchers works even less than before. Therefore Clink reports an error.
> 
> My guess is that the config\cmder.lua file is some kind of manually produced file that duplicates a lot of stuff from other scripts, and Cmder has been upgraded on that computer for the first time since Cmder picked up the newer Clink v1.x fork.
> 
> The best way to fix the errors is to either update the config\cmder.lua file so it isn't duplicating things, or to remove the other corresponding Lua scripts that it's duplicating. In other words, for some command "foo", there should be only one script that registers arguments for that command's argmatcher. Right now there are multiple scripts registering argmatchers for the same command, and Clink v1.0 and higher have stopped even trying to guess how to merge them together without breaking things.
> 
> Sorry for the inconvenience!

I have no idea! I did not add it personally, and it's been there forever (looking at when I migrated from my old computer ~1.5yrs ago it was there too). It hasn't caused issues before but you're right, removing it as solved the problem. Here's the contents of `cmder.lua`, I assume just straight-up removing it shouldn't cause any problems or loss of features in Cmder?

    function lambda_prompt_filter()
        clink.prompt.value = string.gsub(clink.prompt.value, "{lamb}", "λ")
    end

    ---
     -- Resolves closest directory location for specified directory.
     -- Navigates subsequently up one level and tries to find specified directory
     -- @param  {string} path    Path to directory will be checked. If not provided
     --                          current directory will be used
     -- @param  {string} dirname Directory name to search for
     -- @return {string} Path to specified directory or nil if such dir not found
    local function get_dir_contains(path, dirname)

        -- return parent path for specified entry (either file or directory)
        local function pathname(path)
            local prefix = ""
            local i = path:find("[\\/:][^\\/:]*$")
            if i then
                prefix = path:sub(1, i-1)
            end
            return prefix
        end

        -- Navigates up one level
        local function up_one_level(path)
            if path == nil then path = '.' end
            if path == '.' then path = clink.get_cwd() end
            return pathname(path)
        end

        -- Checks if provided directory contains git directory
        local function has_specified_dir(path, specified_dir)
            if path == nil then path = '.' end
            local found_dirs = clink.find_dirs(path..'/'..specified_dir)
            if #found_dirs > 0 then return true end
            return false
        end

        -- Set default path to current directory
        if path == nil then path = '.' end

        -- If we're already have .git directory here, then return current path
        if has_specified_dir(path, dirname) then
            return path..'/'..dirname
        else
            -- Otherwise go up one level and make a recursive call
            local parent_path = up_one_level(path)
            if parent_path == path then
                return nil
            else
                return get_dir_contains(parent_path, dirname)
            end
        end
    end

    local function get_hg_dir(path)
        return get_dir_contains(path, '.hg')
    end

    local function get_git_dir(path)
        return get_dir_contains(path, '.git')
    end

    ---
     -- Find out current branch
     -- @return {false|mercurial branch name}
    ---
    function get_hg_branch()
        for line in io.popen("hg branch 2>nul"):lines() do
            local m = line:match("(.+)$")
            if m then
                return m
            end
        end

        return false
    end

    ---
     -- Get the status of working dir
     -- @return {bool}
    ---
    function get_hg_status()
        for line in io.popen("hg status"):lines() do
            return false
        end
        return true
    end

    function hg_prompt_filter()

        -- Colors for mercurial status
        local colors = {
            clean = "\x1b[1;37;40m",
            dirty = "\x1b[31;1m",
        }

        if get_hg_dir() then
            -- if we're inside of mercurial repo then try to detect current branch
            local branch = get_hg_branch()
            if branch then
                -- Has branch => therefore it is a mercurial folder, now figure out status
                if get_hg_status() then
                    color = colors.clean
                else
                    color = colors.dirty
                end

                clink.prompt.value = string.gsub(clink.prompt.value, "{hg}", color.."("..branch..")")
                return false
            end
        end

        -- No mercurial present or not in mercurial file
        clink.prompt.value = string.gsub(clink.prompt.value, "{hg}", "")
        return false
    end

    ---
     -- Find out current branch
     -- @return {false|git branch name}
    ---
    function get_git_branch()
        for line in io.popen("git branch 2>nul"):lines() do
            local m = line:match("%* (.+)$")
            if m then
                return m
            end
        end

        return false
    end

    ---
     -- Get the status of working dir
     -- @return {bool}
    ---
    function get_git_status()
        return os.execute("git diff --quiet --ignore-submodules HEAD 2>nul")
    end

    function git_prompt_filter()

        -- Colors for git status
        local colors = {
            clean = "\x1b[1;37;40m",
            dirty = "\x1b[31;1m",
        }

        if get_git_dir() then
            -- if we're inside of git repo then try to detect current branch
            local branch = get_git_branch()
            if branch then
                -- Has branch => therefore it is a git folder, now figure out status
                if get_git_status() then
                    color = colors.clean
                else
                    color = colors.dirty
                end

                clink.prompt.value = string.gsub(clink.prompt.value, "{git}", color.."("..branch..")")
                return false
            end
        end

        -- No git present or not in git file
        clink.prompt.value = string.gsub(clink.prompt.value, "{git}", "")
        return false
    end

    clink.prompt.register_filter(lambda_prompt_filter, 40)
    clink.prompt.register_filter(hg_prompt_filter, 50)
    clink.prompt.register_filter(git_prompt_filter, 50)

    local completions_dir = clink.get_env('CMDER_ROOT')..'/vendor/clink-completions/'
    for _,lua_module in ipairs(clink.find_files(completions_dir..'*.lua')) do
        -- Skip files that starts with _. This could be useful if some files should be ignored
        if not string.match(lua_module, '^_.*') then
            local filename = completions_dir..lua_module
            -- use dofile instead of require because require caches loaded modules
            -- so config reloading using Alt-Q won't reload updated modules.
            dofile(filename)
        end
    end

**Comment by chrisant996** [comment]
I would recommend deleting it:

- It appears to be some kind of manually edited partial copy of an older version of Cmder's `vendor\clink.lua` script.  But it doesn't exactly match any historical version.
- It duplicates a bunch of things, and it might be trying to override some of the prompt text.  It's hard to tell.
- The reason for all the error messages is because at the bottom it has a loop that loads all of the `vendor\clink-completions` scripts a second time.  Since it was literally just re-loading them, they would have worked ok, aside from taking twice as long to load them.

Deleting it might undo some kind of intentional effect, though.
So if you want to be more conservative, then you could just remove from `local completions_dir` to the end of the file.

But the script is competing with Cmder's built in prompt filtering scripts, and those have had some enhancements and fixes in the past couple of years.  And also, I think they'll end up having no effect anyway, since they all run _after_ Cmder's built in scripts, so by the time they run the "{git}" and etc substrings have all been replaced and there's nothing left for these functions to do.

So I think the file may be leftover from some experiment that either didn't work or was unnecessary, and never got deleted, and wasn't noticed until now.

So I do think deleting it should be safe.  And deleting it definitely will not lose any built in Cmder functionality -- because the script isn't part of Cmder.

**Comment by HeyItsJono** [comment]
Thanks! I deleted it and now no longer have the issue :)
