### ISSUE TITLE
Cmder steals Win+<number> keyboard shortcuts

### ISSUE THREAD

**Issue by StFS** [cmderdev/cmder#2545]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Version Information

ConEmu 210304
Cmder v1.3.18

Windows 10 Pro

### Description of the issue
I just started using Windows again after a looong hiatus (coming from Mac and Linux/KDE). I've set up zVirtualDesktop to get keyboard shortcuts for virtual desktops (switching directly and sending windows to vdesktops). However, Cmder is causing problems here. Whenever I focus a Cmder window, my `Win+<number>` shortcuts (to switch virtual desktops) stop working. It's as if Cmder "eats them". Nothing happens.

I tried opening up the settings to look for defined keyboard shortcuts that use Win+1, Win+2, Win+3 and Win+4 but I didn't find anything.

Is there anything that I can try doing to prevent Cmder from grabbing my `Win+<number>` shortcuts?

**Comment by chrisant996** [comment]
Does it work with ConEmu?  If not, then it's either a ConEmu issue or a zVirtualDesktop issue, and one of those forums would be better able to help or comment.  (Also, the zVirtualDesktop repo has similar issues reported with some other software.)

**Comment by daxgames** [comment]
I just installed zVirtualDesktop and it seems to work for me.  <kbd>Ctrl</kbd>+<kbd>Win</kbd>+<kbd>1</kbd> or <kbd>Ctrl</kbd>+<kbd>Win</kbd>+<kbd>2</kbd> switches desktops without issue.

**Comment by daxgames** [comment]
Changing the hotkeys to <kbd>Win</kbd>+<kbd>1</kbd> or <kbd>Win</kbd>+<kbd>2</kbd> also works.

**Comment by daxgames** [comment]
Thats a pretty cool add to WIndows.

**Comment by StFS** [comment]
@daxgames if you ask me it's mind boggling that this isn't a part of the standard virtual desktop experience. But thanks for trying this out... I guess I'm going to have to snoop around for what would be causing this on my machine. I actually also noticed that Visual Studio is behaving the same way... which is very bad since vdesktop 1 is my "work desktop" in which I'd usually only have VS and Cmder running... so that means that every time I switch to vdesktop 1 I'll get completely "stuck" there.

@chrisant996 sorry, I haven't tried with ConEmu (Windows n00b here as I mentioned) and I didn't even realise that ConEmu was an application that I can install and run (and get a window). I thought it was just the terminal component... my bad. I'll check and see whether I can test that out tomorrow.

I doubt that it's a zVirtualDesktop bug as it works fine when other applications have focus (except Visual Studio as I mentioned) and also when no application windows have focus. But maybe... there's also a major booboo with Windows that by default the Win+<number> shortcuts are assigned to selecting the <number>th item from the task list. I managed to turn that off by fiddling with the registry editor but maybe that's contributing to this issue.

At any rate, thanks for taking the time.

**Comment by chrisant996** [comment]
> @chrisant996 sorry, I haven't tried with ConEmu (Windows n00b here as I mentioned) and I didn't even realise that ConEmu was an application that I can install and run (and get a window).

Cmder is actually ConEmu + some scripts that supply some enhancements. So it's very unlikely that Cmder is involved, per se. Most likely either something on that computer is interfering, or it's an issue in zVirtualDesktop, or an issue in ConEmu (the actual terminal program used by Cmder).

> I doubt that it's a zVirtualDesktop bug as it works fine when other applications have focus (except Visual Studio as I mentioned) and also when no application windows have focus.

Maybe. But zVirtualDesktop has the same symptom with VMWare and VirtualBox -- and yet AutoHotkey does not. So there is some data suggesting there may be an issue in how zVirtualDesktop hooks the hotkeys.

> But maybe... there's also a major booboo with Windows that by default the `Win+<number>` shortcuts are assigned to selecting the `<number>`th item from the task list.

A bug to one is a feature to another. I won't try to speak for others, but I love that Windows defaults to Win+digit as taskbar shortcuts. 🤷

> I managed to turn that off by fiddling with the registry editor but maybe that's contributing to this issue.

Interesting that @daxgames didn't need to do registry edits. Maybe the registry edits are indeed part of the problem.

Good luck! Mysterious incompatibilities are frustrating.

**Comment by StFS** [comment]
> A bug to one is a feature to another. I won't try to speak for others, but I love that Windows defaults to Win+digit as taskbar shortcuts. 🤷

True... I forgot to mention that the booboo is that there is no way to unassign this in Windows. In fact, keyboard shortcut management in Windows seems to be a complete mess. Configs are scattered here and there and no central place to view/edit/disable all OS keyboard shortcuts. And as I said, some even can't be configured or disabled at all using "normal channels".

> Good luck! Mysterious incompatibilities are frustrating.

Thanks.

And on that note (@daxgames this might interest you too), I figured out what the common thread is that is causing Windows to grab focus like VS and Cmder are doing. I'm running both of these windows/processes as Administrator. I just tried starting PowerShell up as a normal user and things work as expected like that... but if I run PowerShell as Administrator, the window starts grabbing all my `Win+<number>` keyboard shortcuts.

So you're absolutely right... not a Cmder issue, neither ConEmu nor zVirtualDesktop... it's a Windows thing!

Thanks for your help, at least I'm a step closer to a solution (or the inevitable doom of realizing that there is none).

**Comment by chrisant996** [comment]
If zVirtualDesktop isn't run as Administrator then it cannot hook shortcut keys in programs that are run as Administrator. Otherwise it would be a (pretty bad) security vulnerability.

**Comment by StFS** [comment]
Very good point. I'm not used to this weirdness of having the whole UI application run as an Administrator rather than just escalating privileges for the processes running within the UI (as per running sudo in a terminal in Linux/Mac). But this absolutely explains the issue that I'm having. Thanks.
