### ISSUE TITLE
Question: Run As Admin

### ISSUE THREAD

**Issue by WickedWizard3588** [cmderdev/cmder#2547]
Hey,

### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Version Information

Cmder Version: 1.3.18.1106
![image](https://user-images.githubusercontent.com/67627239/118984297-fc10e580-b99a-11eb-9083-6106f8ba1746.png)

ConEmu Version: 210304 Preview
![image](https://user-images.githubusercontent.com/67627239/118983891-8dcc2300-b99a-11eb-9e75-f7fc479e3140.png)

Windows Version: Windows 10 20H2

I have all my Cmder environment variables (`Path`, `%ConEmuDir%`, `CMDER_ROOT`)  set up properly. I use the `Run` Method (Windows Key + R) to open Cmder. When I try to open Cmder as admin, using Ctrl + Shift + Enter (instead of just Enter), it never opens in admin mode. It just opens without admin privileges. I have to use the New Tab option in Cmder to create a new Tab and elevate it. Is there any way, I can make Cmder Run as Admin from the Run Method itself?

EDIT: Forgot to mention, in README, I tried the startup task, it didn't work

EDIT2: I reinstalled Cmder, which fixed the first problem, Cmder now opens the "first" tab as admin. When I open a new tab, it does not open as admin by default. How can I fix it?

**Comment by daxgames** [comment]
If you always want cmder to start in admin console set the startup task as you already mentioned.  I don't know why it would not work.

**Comment by WickedWizard3588** [comment]
No, I have already set that. The first tab opened in a Cmder session runs as admin. But when I open the second tab, it does not run as admin.

**Comment by daxgames** [comment]
How are you opening the new tab?

**Comment by WickedWizard3588** [comment]
Hotkey: Ctrl + T

**Comment by daxgames** [comment]
Have you looked at:

![image](https://user-images.githubusercontent.com/7318053/126854659-21975475-4fe9-4459-b1ef-b15156ee4084.png)

Pressing <kbd>alt</kbd>+<kbd>shift</kbd>+<kbd>1</kbd> launches `cmd::Cmder as Admin Task`

When tasks are numbers as shown below:

![image](https://user-images.githubusercontent.com/7318053/126854699-09dd5d7b-4c92-4c5d-a77b-9ece1a34707d.png)

**Comment by daxgames** [comment]
Closing as resolved - No response from OP
