### ISSUE TITLE
Git status slows down prompt in large repos

### ISSUE THREAD

**Issue by ian-craig** [cmderdev/cmder#2548]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [ ] Question

### Version Information

191012 [x64] {Preview}

Windows 10 Enterprise 21H1

### Description of the issue

Running `git status` and `git diff` in large repos can take over 1-2 seconds each. By default, cmder runs both in series when generating the prompt text after every command.

So, running fast commands like `cd ..` in large repos can easily take 3-4 seconds for the prompt to come back.

Cmder already has a feature to disable the git status in the prompt to fix this by adding the following to your `.git/config`
```
[cmder]
    status = false
```

This is obviously faster, but I would really like to see the branch name still, and that doesn't require running either `git status` or `git diff` so doesn't slow down in large repos.

### Proposal
Support an additional config option
```
[cmder]
    status = branchonly
```

Update `get_git_status_setting` to return `true | false | 'branchonly'`, and in `git_prompt_filter` check for `'branchonly'` before running `get_git_status` and `get_git_conflict` to decide on the color.

This change is backward compatible, and pretty small. I am happy to submit a PR to contribute this.

**Comment by daxgames** [comment]
I loke the idea but I am pretty sure this change is bigger than you think and could possibly extend to clink completions.

It has been determined that clink completions also adds to prompt slowness in large repos and was recently enhanced to respect Cmders git status opt out settings.

PRs are always welcome.

Cmder's `clink.lua` sets a global variable that clink completions `git-prompt.lua` recognizes and skips git prompt actions it normally does.  You will need to set this variable also to gain all the performance you seek.

**Comment by ian-craig** [comment]
Either I'm not hitting the clink completion slowness you mentioned, or it's just not slow enough (or on a hot enough path) to bother me. Anyway, I sent a PR for `branchonly` mode to skip status and diff on generating the prompt text and that seems way faster in my large repo.

**Comment by chrisant996** [comment]
Just sharing an upcoming Clink feature that's in progress:

Clink is going to gain the ability to filter the prompt asynchronously.

For example, the git prompt filter will be able to:
1. Fill in the branch name immediately.
2. Start a task to asynchronously get the git status.
3. The prompt will show up immediately, but without status info.
4. The user can type and etc.
5. When the async task completes, the prompt will be updated and re-displayed.

A prompt filter must specifically support this, but it's pretty easy to use.  The behavior will be optional, in case people prefer a delay + complete prompt.

Of course, the more text in a prompt is updated on a delay, the more potential for it to be disorienting.  So the behavior will be optional (and a prompt filter doesn't need to do anything different when async prompt filtering is disabled).

**Comment by chrisant996** [comment]
Clink v1.2.10 will include support for async prompt filtering -- imagine showing git status, even in large repos, without having to wait for it!

Will probably release the Clink update around June 9, give or take a couple days.

I've also updated vendor\clink.lua to make use of async prompt filtering for git (see http://github.com/chrisant996/cmder).  Seems to be working great.  Will send a PR closer to June 9.

More info at https://github.com/chrisant996/clink/issues/121.

_(P.S.  I'm excited!  The allure -- and challenge! -- of async prompt filtering was actually the primary motivating factor for me to step up and revive/maintain Clink.)_

**Comment by chrisant996** [comment]
Clink v1.2.10 is released, and I submitted PR https://github.com/cmderdev/cmder/pull/2556 (based off https://github.com/cmderdev/cmder/pull/2549) to update Cmder to include support for the new async prompt filtering.
