### ISSUE TITLE
joining two scripts

### ISSUE THREAD

**Issue by Aadhithyan993** [cmderdev/cmder#2550]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

**Comment by chrisant996** [comment]
There is no description or information here.

What does "joining two scripts" mean?

**Comment by Aadhithyan993** [comment]
Hi I am trying to join two scripts together. the folder creation mkdir along with the csr file creating script. I have tried all to get it into one script but i am not able to. Is there anyway to do this in cmder? might sound childish but it would be helpful if someone could give me an solution

**Comment by Aadhithyan993** [comment]
> There is no description or information here.
> 
> What does "joining two scripts" mean?

Hi I am trying to join two scripts together. the folder creation mkdir along with the csr file creating script. I have tried all to get it into one script but i am not able to. Is there anyway to do this in cmder? might sound childish but it would be helpful if someone could give me an solution

**Comment by daxgames** [comment]
Still do not understand the problem.  Can you provide reproduction steps or an example.

**Comment by Aadhithyan993** [comment]
Hi Daxgames and chrisant996. Sorry was doing the mistake from my end. found out the issue. Thanks for trying to help me out.
