### ISSUE TITLE
PowerShell Preview warning when using the default `profile.ps1`

### ISSUE THREAD

**Issue by DigiOhhh** [cmderdev/cmder#2551]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

`Cmder v1.3.18`
`ConEmu 210422 [64] {Preview}`

```
Edition	        Windows 10 Pro
Version	        Dev
Installed on	‎5/‎23/‎2021
OS build	21387.1
Experience	Windows 10 Feature Experience Pack 321.13101.0.3
```

### Description of the issue

I'm getting the following warning when running PowerShell Preview on Cmder:
`Suggestion [4,General]: The most similar commands are: dir, gcm, gi, gm, ii, mi, ni, ri, si, irm.`
it probably means there's a typo somewhere in `%ConEmuDir%\..\profile.ps1`
This is the task I'm using:
```
PwSh -ExecutionPolicy Bypass -NoLogo -NoProfile -NoExit -Command "Invoke-Expression 'Import-Module ''%ConEmuDir%\..\profile.ps1'''"
```
(it's basically `{PowerShell::PowerShell}`, I only replaced `PowerShell` with `PwSh`)

**Comment by leifniem** [comment]
I encountered the same issue when using pwsh-preview.

**Comment by chrisant996** [comment]
Kind of sounds like it can't find git.

Or what happens when using PowerShell instead of PwSh?  Maybe it's an issue in PwSh, rather than an issue in the PowerShell script.

**Comment by leifniem** [comment]
@chrisant996 info in the prefix and git command are working, i'll test the Powershell / pwsh thingy later.

**Comment by DigiOhhh** [comment]
> Or what happens when using PowerShell instead of PwSh? Maybe it's an issue in PwSh, rather than an issue in the PowerShell script.

Looks like there's no issue when using PowerShell. My guess is, older versions of PowerShell simply suppress (or don't show) these so-called 'suggestions'
