### ISSUE TITLE
Apps-Key Hotkey not functional when Cmder not run as Admin

### ISSUE THREAD

**Issue by HeyItsJono** [cmderdev/cmder#2554]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

Cmder 1.3.18
ConEmu 210422 preview

Windows 10 Enterprise 18363.1256

### Description of the issue

Unless Cmder is run as Admin via its [Properties window](https://i.imgur.com/3ySkTTU.png), Apps-Key does not properly work as an assignable hotkey. If this option is unchecked and you try to assign anything (e.g. a Task or other keyboard shortcut) to activate where the AppsKey is involved in the shortcut, it won't activate. Once ticking this admin box it works again.

**Comment by daxgames** [comment]
The UI for Cmder is ConEmu.  The Cmder team cannot fix issues with ConEmu  so they should be reported to that team.
