### ISSUE TITLE
Setting HOME in ../vendor/init.bat

### ISSUE THREAD

**Issue by zbyna** [cmderdev/cmder#2555]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Version Information

cmder 1.3.18
ConEmu 210304 [64] Startup Info
Clink v1.1.45.1c3985

OsVer: 6.1.7601.x64, Product: workstation, SP: 1.0, Suite: 0x100
Build: Service Pack 1, ReactOS: 0, Rsrv: 0, WINE: 0, PE: 0, R2: 0
### Description of the issue

In order to use [buku](https://github.com/jarun/buku#introduction) I had to [disable setting `HOME`  in  `init.bat`](https://github.com/cmderdev/cmder/blob/36f4ce0e3c664b23c3652f180b29e9238860b203/vendor/init.bat#L401-L403) .

Buku is multiplatform python application and sets its database path according to existence of **HOME variable**, which **is not default defined in Windows**. For using related projects [bukubrow](https://github.com/samhh/bukubrow-webext#bukubrow), [bukubrow-host](https://github.com/SamHH/bukubrow-host#bukubrow-host) is needed to have bookmark database in standard path, which rely on [nonpresence of HOME variable in windows](https://github.com/jarun/buku/blob/5b171fc9b33d14f575ac427c6674bc2f3cc4df93/buku#L401-L427).

Here are my questions:
      - What features are broken by non defining HOME var ?
      - Is there any chance that my  "adjustments" will landed master branch ?

Thanks for reply and patience during reading my long issue :slightly_smiling_face:  .
           zbyna

**Comment by daxgames** [comment]
Nothing is broken that I know of other than editing `init.bat `is not a good thnig to do.  I would `set HOME=` in `%cmder_root%/config/user_profile.cmd`.

No we will not remove the setring of `HOME=%USERPROFILE%` from `init.bat`.

**Comment by zbyna** [comment]
Thanks for suggestion. It works.
