### ISSUE TITLE
Recommendations for detecting installation

### ISSUE THREAD

**Issue by Tyriar** [cmderdev/cmder#2557]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Version Information
N/A

### Description of the issue
I was trying to implement auto detection of the cmder shell for VS Code (https://github.com/microsoft/vscode/issues/125387) so we can expose Cmder as a detected profile in this list:

![image](https://user-images.githubusercontent.com/2193314/121017656-61fabc80-c752-11eb-88a5-8ed0598a5c43.png)

It seems that you don't have an installer so cmder could be anywhere. We can't do a global search on disk for this so are there any recommendations for detecting the cmder installation path so we can find `vscode_init.cmd`? Does cmder modify anything in app data that points to the install dir for example?

**Comment by daxgames** [comment]
The user could set `cmder_root` env var to the folder path wheere cmder is installed and if vscode finds this set ...

**Comment by Tyriar** [comment]
@daxgames is this a common thing users do during setup or does it happen automatically at the global/user level?

**Comment by daxgames** [comment]
This is an optional step a user could do along with adding the `cmder_root` folder path to the `path` env var.  This allows other things, vscode, to know Cmder is on the system.  Therefore, if vscode is launched from outside Cmder vscode should be able to use this manually set  `%cmder_root%` env var to locate cmder.

Cmder does both of these things during its init process so if vscode is launched from inside inside Cmder vscode should be able to use `%cmder_root%` to locate cmder automatically.

Make sense?

**Comment by Tyriar** [comment]
Yep that makes sense, I mainly want to target the case where it's not launched via cmder. Can you link to the `%cmder_root%` being set docs? I see a lot of references to the variable on https://github.com/cmderdev/cmder/blob/master/README.md but not where the user is told to set it up manually?

**Comment by daxgames** [comment]
It is not in the docs as it is not required for Cmder to function.  It is just a piece of extra config that a user can choose to do if they require it.

**Comment by Tyriar** [comment]
@daxgames how does a user find out how to do it if you don't mention it in the documentation?

**Comment by daxgames** [comment]
Sorry to sound flip but, Windows OS knowledge?  Why does one set env variables?

We do not hide the fact that `%cmder_root%` is an important env var set by cmder init scripts.  If someone needs it available outside the cmder shell and they have knowledge of Windows and env variables they set it using normal Windows methods.

I think it might be mentioned in the wiki for integrating with vscode.

I suppose we could add a bit of documentation something like.

### Working with External Apps

If other Windows apps need to know where Cmder is on the filesystem you can set the `%CMDER_ROOT%` environment variable in Windows.  See Windows documentation for details.

No one has ever thought it was necessary, i guess.

**Comment by daxgames** [comment]
One thing to note.  You can run Git Bash in Cmder and the env var there is all upper case so you might be best looking for `%CMDER_ROOT%` instead of `%cmder_root%`.

**Comment by Tyriar** [comment]
> Windows OS knowledge?

That's the problem I was trying to weed out. I'm trying to make things as simple as possible to help out the most users, unfortunately I think the main users we want to cover probably wouldn't go out of their way to configure the environment variable especially if they're not explicitly being told to. A zero config approach that just works would be best, but doesn't look like that's possible here since you don't have an installer.

> Cmder does both of these things during its init process so if vscode is launched from inside inside Cmder vscode should be able to use %cmder_root% to locate cmder automatically.

This is probably a pretty small amount of users who would launch code though here

> You can run Git Bash in Cmder and the env var there is all upper case so you might be best looking for %CMDER_ROOT% instead of %cmder_root%.

Environment variables on Windows are case insensitive so it shouldn't be an issue, node handles this for us.

---

Actually found it, it's linked from the [setting up vscode docs](https://github.com/cmderdev/cmder/wiki/Seamless-VS-Code-Integration):

https://github.com/cmderdev/cmder/wiki/Setting-up-Environment-Variables#setting-up-environment-variables

I'll have another look, maybe it's not worth adding auto detection since it would need additional setup outside of the product anyway. Also I see you're using `shell`/`shellArgs` which are deprecated. In the next version the recommendation instead of:

```json
"terminal.integrated.shell.windows": "cmd.exe",
"terminal.integrated.shellArgs.windows": [
      "/K",
      "%CMDER_ROOT%\\vendor\\bin\\vscode_init.cmd"
],
```

Is:


```json
"terminal.integrated.defaultProfile.windows": "Cmder",
"terminal.integrated.profiles.windows": {
  "Cmder": {
    "path": "cmd.exe",
    "args": [
      "/K",
      "%CMDER_ROOT%\\vendor\\bin\\vscode_init.cmd"
    ]
  }
}
```

This enables convenient switching between shells and also having cmder as the non-default profile available here:

<img width="305" alt="Screen Shot 2021-06-08 at 6 38 42 AM" src="https://user-images.githubusercontent.com/2193314/121195094-2b8d7200-c824-11eb-81b1-f82533757d51.png">

Thanks for all the info!

**Comment by daxgames** [comment]
Thanks for the info on thr new way.  Is that available now?

If so I can update the Wiki.

**Comment by Tyriar** [comment]
@daxgames it is, there were some nasty bugs with defaultProfile that only get fixed in the upcoming version though. So I'd recommend making that change after v1.57 goes out (should be this Friday at the latest)
