### ISSUE TITLE
Whats the problem with it?

### ISSUE THREAD

**Issue by Farshad123123** [cmderdev/cmder#2558]
Whats the problem?why I cant use git?

https://i.postimg.cc/tRLdg4zF/image.jpg

**Comment by daxgames** [comment]
Cmder does not support 32bit windows.  Git for Windows embedded in Cmder is 64 bit.

**Comment by daxgames** [comment]
See: https://github.com/cmderdev/cmder/issues/2273#issuecomment-599224555

**Comment by Farshad123123** [comment]
Aha tnx Ive downloaded git 32bit and install it on git-for-windows seems now git is working but Ive got another question too whats with WSL?

https://i.postimg.cc/zD0fTSKn/1623254894323.png

**Comment by chrisant996** [comment]
That looks like it might be a bug in ConEmu: it looks like it checks whether the hardware is 64, rather than checking whether the OS is 64 bit.
