### ISSUE TITLE
Does cmder support character like: ❱❱❱ and 🔥

### ISSUE THREAD

**Issue by waynezhangw** [cmderdev/cmder#2561]
ConEmu has Unicode Support[https://conemu.github.io/en/UnicodeSupport.html](url)
Since cmder is based on ConEmu , how can I make cmder to recognize character like: ❱❱❱ and 🔥?

**Comment by daxgames** [comment]
If Conemu supports it Cmder should support it.  I assume that is not your experience.

I would start with the Conemu page you referrenced and go through any troubleshooting it recommends.

If you have done that then I don't have a definitive Nswer for you.

Cmder default session uses Clink, Maybe this loss of functionality is a side effect.  @chrissant996?

**Comment by daxgames** [comment]
Looks like it is a limitation of the Windows Console.  I attempted to use `minikube` to test this and there are no emojis.  Found this:

https://github.com/kubernetes/minikube/issues/7981

**Comment by daxgames** [comment]
Followed [this](https://github.com/cmderdev/cmder/wiki/Seamless-Windows-Terminal-Integration):

Now I have Cmder in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?rtc=1#activetab=pivot:overviewtab):

![image](https://user-images.githubusercontent.com/7318053/121807693-3c265980-cc23-11eb-8526-2e65644a1ef3.png)

**Comment by waynezhangw** [comment]
Mine works too if Cmder was integrated into Windows Terminal. 
But if it has to be integrated with other terminal, why would I bother using Cmder?

**Comment by daxgames** [comment]
Because cmder is just Cmder configs running in ConEmu.  Cmder is config that ties together redistributed binaries of Conemu, Clink, Clink Completions, and Git for Windows.

The fact that emojis do not work in Cmder with Comemu is because Conemu uses the Legacy Windows terminal that does not support emojis.  It is not a problem with Cmder.

**Comment by waynezhangw** [comment]
Oh, it's good to know that, so will Conemu use the newer version of Windows terminal that support emojis in the future?

**Comment by daxgames** [comment]
I don't know.  That is a question for the ConEmu team.
