### ISSUE TITLE
[Questions] Hi. How can I making my cmder prompt show only folder name like Zash theme of oh-my-posh ?

### ISSUE THREAD

**Issue by buinguyenhoangtho** [cmderdev/cmder#2562]
Like title. Here the concept. 
zash-theme
![image](https://user-images.githubusercontent.com/76900905/121838500-30f62b00-cd02-11eb-9127-6a2f2f6706fc.png)

![image](https://user-images.githubusercontent.com/76900905/121838548-4c613600-cd02-11eb-86af-ffe02d1b2a8e.png)

**Comment by daxgames** [comment]
If running 1.3.18 see `%cmder_root%\config\cmder_prompt_config.lua` for prompt configuration options.

If it is not there copy `%cmder_root%\vendor\cmder_prompt_config.lua.default` to `%cmder_root%\config\cmder_prompt_config.lua`

Otherwise you can write your own `%cmder_root%\config\custom_prompt.lua`

**Comment by morpheuslord** [comment]
How can we change the default lambda symbol and the input theme in cmder

**Comment by daxgames** [comment]
Download [this](https://ci.appveyor.com/project/MartiUK/cmder/build/artifacts) and it is configurable using the info from posts above.

**Comment by morpheuslord** [comment]
I didn't get you there is nothing mentioned in the post regarding how I can add zsh to cmder

**Comment by daxgames** [comment]
@morpheuslord You dodnt ask about adding zsh to Cmder.  You asked about changing the Lambda

**Comment by buinguyenhoangtho** [comment]
Hey sorry for long time reponses. But i'm switching to linux permanently so i think i will close this issue (or already?).
About the lambda icon. You can try in `vendor\clink.lua`
watch for the line `local lambda = "λ"` .(maybe? don't know if latest version that they changed anything)
