### ISSUE TITLE
Cmder/ConEmu rendering issues

### ISSUE THREAD

**Issue by MegaBor** [cmderdev/cmder#2563]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information
Version: https://github.com/cmderdev/cmder/releases/tag/v1.3.18
OS: Windows 10 Pro 1903

### Description of the issue

It appears when I SSH to my server and executing some commands, there are **very** noticeable rendering issues:
![cmder_bug_rendering](https://user-images.githubusercontent.com/52722806/121926851-ada6fa80-cd3e-11eb-90f6-d087e54b0078.gif)

When I move the cursor from left to right, it clears up the rendering issues.

These issues were noticed in different context as well, but I can't remember now where.

**Comment by jimmyc802** [comment]
I am experiencing similar behavior. I am able to reproduce the issue you show in mysql. I first noticed it with NCDU (vertical shifting) and htop (horizontal shifting). I've tried using SSH outside of cmder and these issues are not present. Please fix!
![cmder-rendering-funny](https://user-images.githubusercontent.com/1918286/143913545-a46e62da-60bc-4ec6-8536-171c2d286802.gif)

**Comment by rcmonitor** [comment]
Are there any plans on integrating this [build of ConEmy](https://conemu.github.io/blog/2022/03/08/Build-220308.html) ?
It seemed to be addressing this bug as well...

**Comment by daxgames** [comment]
@MegaBor See latest unreleased [build](https://ci.appveyor.com/project/MartiUK/cmder/build/artifacts)

**Comment by DRSDavidSoft** [comment]
There will be a [release](https://github.com/cmderdev/cmder/releases) soon in order to fix the bug (https://github.com/Maximus5/ConEmu/issues/2404)
