### ISSUE TITLE
bug in path auto-complete

### ISSUE THREAD

**Issue by carlodri** [cmderdev/cmder#2564]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

I am using cmder-mini version 1.3.18

Windows 10 Pro 19041

### Description of the issue

This is very likely an issue with clink-completions, but I am not sure. I think there is a bug in the autocompletion of folder names. If I have a folder structure like this:
```
D:.
├───a-1
└───a_1
```
and I type this:
```
λ cd a_<TAB>
```
cmder just deletes the `_` character and does not auto-complete to `a_1`, leaving me with this:
```
λ cd a
```
The same holds for the `a-1` path.

**Comment by chrisant996** [comment]
See https://github.com/chrisant996/clink/issues/129 for why, and what setting controls the behavior.

**Comment by carlodri** [comment]
`clink set match.ignore_case 0` did the trick! Thank you!
