### ISSUE TITLE
shortcuts for `ConEmu Here`

### ISSUE THREAD

**Issue by playgithub** [cmderdev/cmder#2566]
In `Settings/Keys & Macro`
Global shortcuts for `Activate ConEmu and ‘CD’ to last (top in Z-order) Explorer window path: PasteExplorerPath(1,1)`,
however it only works if there are activate existing ConEmu's. How to always create one, just like click `ConEmu Here` in the context menu?

**Comment by daxgames** [comment]
I am sorry but I do not understand the question.  Seems like a question better suited for the Conemu dev.

**Comment by playgithub** [comment]
> I am sorry but I do not understand the question. Seems like a question better suited for the Conemu dev since it is related to a Conemu setting.

OK, I'll ask there.
