### ISSUE TITLE
Can't Disable Single Instance Mode

### ISSUE THREAD

**Issue by leewp14** [cmderdev/cmder#2567]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

Version 1.3.18.1106

Windows 10 Enterprise 20H2
### Description of the issue

After disabling Single Instance Mode in settings and Save, reopen settings to check and the Single Instance Mode option is being ticked back. Launching cmder.exe will open a new tab (single instance). 
As per the tooltip suggests, one can use /nosingle. However, this option is missing from the executable, only /single is supported.

**Comment by leewp14** [comment]
Solved by switching off quake-style mode. Suggest not to allow untick Single Instance Mode when Quake-style slide down is enabled.

**Comment by chrisant996** [comment]
This is feedback about ConEmu. Please consider putting it in the ConEmu github repo so that the ConEmu team can consider it.
