### ISSUE TITLE
& was unexpected at this time

### ISSUE THREAD

**Issue by RT-Tap** [cmderdev/cmder#2570]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

Cmdr Version 1.13.18.1106  - extracted in C:\cmder 
ConEmu Version 21.3.4.0   - ConEmu.exe under ./vendor/conemu-maximus5/  right?

Windows 10 Home 64-bit (10.0, Build 19042)
### Description of the issue

I searched open/closed issues, the wiki and google and have not found anything so posting here.  
As the title says. every time I try to run Cmder.exe I just get 

```
& was unexpected at this time

Press Enter or Esc to exit....
```

This is my first time attempting to use cmdr and I cant seem to get it to work.  I have also set %CMDER_ROOT% to C:\cmder.

Any idea why?  
In all honesty I haven't tried much as I have no idea where to even start, hence searching the internet for the past 2 hours.  Although I thought MAYBE, but most likely not, having anaconda installed and putting a line to automatically start the base environment when starting Powershell in profile.ps1 under /Documents/WindowsPowerShell had something to do with it, so I commented it out, but obviously nothing changed, but that's the only thing I tried.

Thanks.

**Comment by daxgames** [comment]
If you download cmder and expand it to a new folder and run it it is not running powershell by default so it has nothing to do with anything in your profile.ps1.

Have you.modified the config in any way or is this a completly fresh unzipped archive?

**Comment by RT-Tap** [comment]
completely fresh but besides the point now
It was anaconda - I haven't used command prompt in so long I hadn't realized my command prompt would open flash up for a second and close, turns out anaconda was trying to run itself so I had to remove it from the registry bu removing `if exist & if exist "C:\Users\Artyt\anaconda3\condabin\conda_hook.bat" "C:\Users\Artyt\anaconda3\condabin\conda_hook.bat"` from `Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Command Processor` in the registry
