### ISSUE TITLE
cursor error when i edit ip

### ISSUE THREAD

**Issue by TotoroQwQ** [cmderdev/cmder#2574]
as the follow gif shows, i want to edit 192.168.0.252 to 192.168.0.25, 
when the cursor is behind '252', i press backspace,the char '2:' is deleted. 
but the follow message tell me ,just char ':' is deleted

then i reuse the last command,and add ':' between '252' and '9200', the char '9' is gone.

![1](https://user-images.githubusercontent.com/8982154/126621284-ebab3ccb-cf5b-4dbd-bfa7-c47980c8f7df.gif)

**Comment by chrisant996** [comment]
It looks like a mismatch between encoding and font, like in #2533.

**Comment by TotoroQwQ** [comment]
Yes, the solution is #2533
