### ISSUE TITLE
i cant add new aliases in the location

### ISSUE THREAD

**Issue by morpheuslord** [cmderdev/cmder#2576]
hello 
i wanted to add a new file to path using this command
portabletools="%CMDER_ROOT%\bin\brute-framework\start.exe" $*
but it is showing a lot of errors so how can we add new aliases

**Comment by daxgames** [comment]
Aliases for cmder shells are based on `doskey`.  You can search for doskey docs on google.  There is also some info about creating advanced doskey aliases in our wiki.

You can use the `alias` command.

```
alias /?
```

  If you want to maintain the `%` signs in the alias so the alias is pprtable.  The alias command args become more complicated as shown in the command line help and the wiki I mentioned.  It might be easier to edit the `%cmder_root%\config\user_aliases.cmd` file directly.

**Comment by morpheuslord** [comment]
i have checked but it was of no help

**Comment by daxgames** [comment]
Need more info.  I don't know what `"%CMDER_ROOT%\bin\brute-framework\start.exe"` is nor am I inclided to install it and find out.

I did the following based on the `alias /?` command line help:

```
alias portabletools="^%CMDER_ROOT^%\bin\brute-framework\start.bat" $*
vi "%CMDER_ROOT%\bin\brute-framework\start.bat"
```

and added this content:

```
@echo off

echo %*
```

typing:

```
portabletools This is extra args
```

yields the expected output:

![image](https://user-images.githubusercontent.com/7318053/127529722-677f47bf-e5e3-4343-b759-6d11e6f63b99.png)

**Comment by morpheuslord** [comment]
well i re did everything and now it is working fine thanks for the support
