### ISSUE TITLE
VirusTotal finds numerous viruses in cmder.exe running on Windows 10

### ISSUE THREAD

**Issue by pgmclean** [cmderdev/cmder#2578]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

**Comment by daxgames** [comment]
Its a false positive.

**Comment by pgmclean** [comment]
I ran a VirusTotal scan of cmder.exe running on Windows 10 and VirusTotal found numerous viruses are spawned when the cmder.exe image is executed. 
![Opera Snapshot_2021-07-30_105546_www virustotal com](https://user-images.githubusercontent.com/43798053/127583829-a0373976-e33c-4961-aeab-302c56b9131f.png)
![Opera Snapshot_2021-07-30_105457_www virustotal com](https://user-images.githubusercontent.com/43798053/127583833-88d3afe7-0c57-495c-a655-4740b6421179.png)

**Comment by pgmclean** [comment]
> Its a false positive.

I guess if most antivirus programs say there’s a problem, the file is probably malicious. If only a few antivirus programs have a problem with the file, it is more likely to be a false positive — this doesn’t guarantee the file is actually safe, it’s just a piece of evidence to consider. So I guess I will need to reply on my AVG Internet Security virus scanner which does not find any viruses in the complete cmder folder tree. Thank you for confirmation.
