### ISSUE TITLE
when I  am typing, miss keys

### ISSUE THREAD

**Issue by nouh** [cmderdev/cmder#258]
from time to time, when I type in the cmder , it will swallow some keys and not show them up. Is that a bug?

my OS is windows8.1

**Comment by cve** [comment]
I have the very similar problem and my system is Windows 8

**Comment by Jackbennett** [comment]
Does this behave the same for the powershell task as it does the cmd one? That will let us find out if its clink causing the problem.

**Comment by Riant** [comment]
It looks like the missing-letters bug happened (for example: typing "git status", but got "gt stats") sometimes when I switch the input-method as Chinese-Sougou. just switch to system English input-method to try to fix that.

For bug "cannot delete the first letter", exactly it has been deleted, but just visible.

Of course, it will be better if Cmder can do anything about that.

**Comment by kakkun61** [comment]
@Jackbennett
> when i use UP and DOWN to choose the command, i cannot delete the first letter of the command.

I have the same issue. Only on cmd with Clink it happens. On PowerShell it doesn't happen. After deleting &lt;cmder&gt;\vendor\clink it doesn't happen with cmd.

- Windows 8.1 Pro
- Cmder 1.2
- Clink 0.4.5

**Comment by Stanzilla** [comment]
Here you go then https://github.com/mridgers/clink/issues/new :)

**Comment by kakkun61** [comment]
Is this Clink's issue despite not happening on cmd & Clink without Cmder?

**Comment by PMExtra** [comment]
Still problems now...
