### ISSUE TITLE
Doesn't work with arm64 processor 

### ISSUE THREAD

**Issue by ibenzyk** [cmderdev/cmder#2580]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [ ] Question

### Version Information

Cmder Version 1.3.18.1106

Edition	Windows 10 Pro
Version	Dev
OS build	21354.1
Experience	Windows 10 Feature Experience Pack 321.7601.0.3

### Description of the issue

When I open Cmder it says:
`Press Enter or Esc to exit...`

**Comment by MartiUK** [comment]
By default we pull the x86_64 version of ConEmu and all other dependencies, from what I understand ConEmu does not support arm64 or at least produce arm64 builds. I found an issue for you: Maximus5/ConEmu#1488
