### ISSUE TITLE
cmder cant run with "running post-install".

### ISSUE THREAD

**Issue by Yuuichu** [cmderdev/cmder#2581]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Version Information

Version 1.3.18.1106

Windows 10 Pro 2004

### Description of the issue

I am a new user of cmder.
I downloaded "cmder.zip" version of cmder.
When I 2nd time I open it, and it stay on the page of 

"Running Git for Windows one time Post Install...."
"running post-install".

But when I use cmder-mini, this will not happen.

**Comment by Yuuichu** [comment]
![Uploading cmder.png…]()

**Comment by daxgames** [comment]
Cmder should run the git for windows one time post install the first tome you run it after install or update.

Cmder mini does not have git for windowa so this does not happen with mini.

**Comment by Yuuichu** [comment]
But it stuck on "running post-install" for a long time...
How I can do to solve it?

**Comment by daxgames** [comment]
I don't see that issue.  You can try:

1. To figure out what is wrong with your pre-cmder env that is causing this
2. You can prevent it from trying to run the post-install by renaming the `%cmder_root%\vendor\git-for -windows\post-install.bat`.
   - I am not sure what you lose by doing this as it is a part of Git for Windows portable setup that we do not write.

**Comment by Yuuichu** [comment]
ok,thank you so much

**Comment by aghbalu** [comment]
im facing the same problem with cmder .please can you help me

**Comment by daxgames** [comment]
Need more info.  The script runs and deletes itself. If it's stuck, what on your system is causing it to be stuck?

This is not a Cmder issue.  That script is a part of Git for Windows
