### ISSUE TITLE
Not getting the default cmder colorscheme and lamda in cmder (command prompt)

### ISSUE THREAD

**Issue by 17Swagat** [cmderdev/cmder#2582]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Version Information

1.3.18.1106

Windows 10 Pro  Version: 10.0.19043 Build 19043
### Description of the issue

I recently downloaded and installed cmder and my interface is as follows. Its nothing like the default cmder command prompt interface. How to change it to the default cmder color scheme / theme.
<img width="960" alt="cmder_now" src="https://user-images.githubusercontent.com/72545910/129040747-ef15f24d-7beb-4923-965c-4959b3b2b280.PNG">

How to change the interface to the expected default one of cmder
<img width="385" alt="cmder_expected" src="https://user-images.githubusercontent.com/72545910/129040838-3490bf25-86c4-4aeb-a9ff-0e3f83610838.PNG">

**Comment by chrisant996** [comment]
> ### Version Information
> 1.3.18.1106
>
> ### Description of the issue
> I recently downloaded and installed cmder and my interface is as follows. Its nothing like the default cmder command prompt interface.

You're not actually using Cmder 1.3.18.1106.

The screenshot shows "Clink v0.4.9", which is from an older version of Cmder.
Cmder 1.3.18.1106 uses Clink v1.1.45.

**Comment by 17Swagat** [comment]
> 
> 
> > ### Version Information
> > 1.3.18.1106
> > ### Description of the issue
> > I recently downloaded and installed cmder and my interface is as follows. Its nothing like the default cmder command prompt interface.
> 
> You're not actually using Cmder 1.3.18.1106.
> 
> The screenshot shows "Clink v0.4.9", which is from an older version of Cmder.
> Cmder 1.3.18.1106 uses Clink v1.1.45.

I uninstalled clink that I installed before installing cmder. Now cmder works fine. As it should normally do.

**Comment by 17Swagat** [comment]
Is there any way via which cmder's clink and clink that I installed for cmd terminal not interfere with each other.

**Comment by chrisant996** [comment]
> Is there any way via which cmder's clink and clink that I installed for cmd terminal not interfere with each other.

I think that you must have installed Clink 0.4.9 with the AutoRun option enabled.
The AutoRun option in Clink 0.4.9 was never compatible with Cmder.

Option 1 is install Clink 0.4.9 but do not use the AutoRun option.

But Clink 0.4.9 is very old (5+ years), and there is a better option:

Option 2 is install modern Clink versions from [chrisant996/clink](https://github.com/chrisant996/clink).
Modern Clink knows how to coexist with Cmder, even when AutoRun is used.
