### ISSUE TITLE
Change of root

### ISSUE THREAD

**Issue by morpheuslord** [cmderdev/cmder#2592]
Hello

I wanted to change the root like for example change %CMDER_ROOT% to %BRUTE_ROOT% and change the default name of cmder to my custom name how can I do that

**Comment by morpheuslord** [comment]
If I can't change the root how can I change the default icon of The default executable and tab

**Comment by daxgames** [comment]
The short answer:

1. Use search and replace.
2. Note: these types of changes will make staying in sync with us more difficult.

The long answer: 

1. Fork the github repo, I assume you intend to redistribute.  See the license and copyright contained in the repo.
2. Rename the repo.
3. See the short answer.
4. Figure out and setup a build and packaging CI process to build distributable archives.

Recomendation:  Don't do it, just include Cmder as is unless you want to COMPLETELY OWN all ongoing support of your fork but it is up to you.

**Comment by morpheuslord** [comment]
I tried to compile the launcher files but it was showing up errors

**Comment by daxgames** [comment]
Ok?

**Comment by morpheuslord** [comment]
So what else can I do with it 😶🤔

**Comment by daxgames** [comment]
I believe I already answered your questions with my recomendations above.  There is always [this](https://google.com).

**Comment by morpheuslord** [comment]
Thanks a lot for your support 😊👍

**Comment by daxgames** [comment]
@cmderdev/core @cmderdev/trusted-contributors 
@samvasko might want to look at this.  Not sure how to handle.

**Comment by Stanzilla** [comment]
Not much we can do with the information given by the reporter

**Comment by morpheuslord** [comment]
i found out i can do the changes i want by recompiling the cmder.exe launcher but when i ran a test build with the default one it was showing errors can you help in compiling the launcher i will take care of the rest.
