### ISSUE TITLE
[bug] Command group {cmd} not found

### ISSUE THREAD

**Issue by mrx23dot** [cmderdev/cmder#2597]
On win10/win7 when opening cmder from context menu with **default** command:
`{cmd} -cur_console:n`

it says:
Command group {cmd} not found! Choose your shell yes-no

this works:
`cmd -cur_console:n`

Version 1.3.18.1106

**Comment by mrx23dot** [comment]
this one also works:
{cmd::Cmder}

it also attaches to already open console (if single instance option is set), so I recommend this one for default parameter.

**Comment by mrx23dot** [comment]
Sorry, in settings/integration/Conemu here/Command the default field didn't work out of the box, which was: 
{cmd} -cur_console:n

I had to change it to: 
{cmd::Cmder}

to make it work.

**Comment by mrx23dot** [comment]
Shouldn't we change the default to make it work out of the box?

**Comment by daxgames** [comment]
It does work out of the box.  The default is shown below:

![image](https://user-images.githubusercontent.com/7318053/133776854-0b43bf53-7938-4aab-b26c-8a8c1c0a64cc.png)

The above is from a fresh download and extracted Cmder folder.

**Comment by mrx23dot** [comment]
Then it's only my PC, thanks!
