### ISSUE TITLE
Selecting+scrolling doesnt work together

### ISSUE THREAD

**Issue by mrx23dot** [cmderdev/cmder#2598]
Based on linux and windows consoles this should work:

- Press down left mouse button.
- Select a few lines, keep pressing mouse
- then scroll to select more lines which didn't fit the screen.

I expect to selection continue.

What happens is scrolling is blocked.

win7 + Version 1.3.18.1106

**Comment by daxgames** [comment]
You are asking for a feature in Conemu, the terminal emulator packaged with cmder.

Conemu is a separate package mainteined by others.
