### ISSUE TITLE
Links not underlined

### ISSUE THREAD

**Issue by mrx23dot** [cmderdev/cmder#2599]
In linux web links are automatically underlined indicating that they are clickable with CTRL.
![link](https://user-images.githubusercontent.com/4163396/132989120-ade1a9b1-3baa-4337-a341-ecd0dafce596.jpg)

But not in cmder Version 1.3.18.1106 + win7

**Comment by daxgames** [comment]
You are asking for a feature in Conemu, the terminal emulator packaged with cmder.

Conemu is a separate package mainteined by others.
