### ISSUE TITLE
Request: please update to last Conemu version: 210905

### ISSUE THREAD

**Issue by savbran** [cmderdev/cmder#2601]
https://github.com/Maximus5/ConEmu/releases

**Comment by viceice** [comment]
v210912 is also available

**Comment by vandre** [comment]
Related to this, the Cancel 'Skip This version' button does not work. Everytime I open Cmder I get prompted to update regardless if I click on the Cancel button.

**Comment by chrisant996** [comment]
If there is a "skip this version" dialog, a Cancel button in it would not mean "skip this version".

Cancel would mean "I'm not making a decision right now".

And then it would prompt next time.  Because no decision was made.

**Comment by daxgames** [comment]
Closing v1.3.19 has Conemu v210912
