### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by mrx23dot** [cmderdev/cmder#2602]
- When clicking cmder.exe it opens the window instantly
- but it takes 2seconds to load the lambda prompt.

There is no difference between cmder vs cmder-admin as startup task.
In settings/startup I reduced delay between console init to 10ms

Where is the delay coming from?
Is it the indexing of tab lookup commands?
~0.7s of it is the vendor\init.bat script, or at least it takes this much for the 2nd time.

system's cmd.exe loads instantly.

**env**
on i7 and samsung SSD
win10-x64 
Version 1.3.18.1106

**Comment by mrx23dot** [comment]
this is what displayed on title bar during 2secs of loading:
![lag](https://user-images.githubusercontent.com/4163396/133080971-2f2332e5-8932-47be-bff6-5c1dd9359cf7.jpg)

so looks like running it first time takes a lot of time.
These 2secs are always there for each launch via context menu, even if there is an already running instance.

**Comment by daxgames** [comment]
It takes longer becauae it is doing more than a standard `cmd.exe` session.

You can make startup a little faster by adding a `/f` after `.../init.bat" /f"`.  This turns off some functionality.

**Comment by mrx23dot** [comment]
/f helped 300ms, I didn't see any functionality loss. 
I created an init_small.bat keeping only CMDER_CLINK section.

Because win-git is already nicely integrated into cmd.exe so no extra step is needed for me.
