### ISSUE TITLE
Tab button doesn't list non-executable files

### ISSUE THREAD

**Issue by mrx23dot** [cmderdev/cmder#2605]
In cmd.exe and ConEmu 
1.  when I press TAB in a dir containing a_file.txt 
2.  it shows the file name
3.  and I can open it with enter.  

Which is very useful on a desktop OS.

I know that cmder adds an auto completion for executables (even double tab works great), 
but can we have both? 

So when nothing is entered an only tab is pressed once it could iterate over the files.
When partion text is entered it could simply do autocompletion (regardless if it's executable or not)

I know it's a deviation from unix console, but it's very useful, 
otherwise we have to change window, and find again with mouse. 
(even ConEmu kept this function)

v1.3.18
win10, win7

**Comment by chrisant996** [comment]
Refer to the Clink.html file in the `vendor\clink` directory under the Cmder directory.

The various Clink settings beginning with "`exec.`" control that.

`clink set exec.enable off` might be what you're looking for.

**Comment by mrx23dot** [comment]
Cheers, that partly worked, I open a ticket clink
https://github.com/mridgers/clink/issues/565

**Comment by mrx23dot** [comment]
Thanks for the heads up
https://github.com/chrisant996/clink/issues/166
