### ISSUE TITLE
Run batch scripts using alias

### ISSUE THREAD

**Issue by Servinjesus1** [cmderdev/cmder#2607]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Version Information

v210912 stable

win10

### Description of the issue

I am trying to run a batch script from an alias, and coming across what seems to be a weird interplay between bash-interpreted and windows-interpreted behavior. The alias I'd expect to write is:

    alias py='call C:\Users\fretwell2\Miniconda3\Scripts\activate.bat; jupyter-lab'

    λ py
    ''call' is not recognized as an internal or external command, operable program or batch file.

This `cmd.exe` flavor error is weird, given `call` is done for calling batch scripts in `cmd`. I've tried an array of other combinations, including `cmd <script>`, `bash <script>`, etc <sup>1</sup>. All result in the `"<command>" is not recognized...` error *unless* I don't include a command at all. Then I get a whole slew of other errors:

1. `<script>` works fine alone - not what I'm trying to achieve
2. `<script>; jupyter-lab` - not recognized error
3. `<script>\njupyter-lab` - (`cmd` flavor space engineering) `The directory name is invalid`
4. `'<script>'\njupyter-lab` - `The filename, directory name, or volume label syntax is incorrect.`
5. `'<script>'; jupyter-lab` - `The filename, directory name, or volume label syntax is incorrect.`

Ugh, I'm probably just a niche user trying to run jupyter easily from a command line in Windows in a convoluted way like a total scrub, but on the off chance this is relevant to improving how `cmder` aliasing is integrated into the tricky win(cmd+powershell)/unix(bash+...) clobbered ecosystem, I'd love some help.

---
<sup>1</sup> However, I think the script is written to be called from `cmd`, so it's important that `cmd` process it.

**Comment by daxgames** [comment]
You use call to 'call' a *.bat/*.cmd script from another *.bat/*.cmd script so that execution of the calling script continues when the called script is finished.

It is not used from the command line to run a *.bat/*.cmd.  Also `;` is not a valid command separator according to doskey documwntation which is what cmder cmd.exe aliases are based on use `$T` instead.

See: https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/doskey

**Comment by daxgames** [comment]
Also wrapping the alias in quotes is nkt required.

**Comment by Servinjesus1** [comment]
Ah, so `aliases` are run by `doskey`, not as batch scripts themselves or something akin to that! Thanks!

> Also wrapping the alias in quotes is not required.
In fact, it breaks the alias, which treats the trailing quote (single or double) as part of the `jupyter-lab` command. So, if the alias has spaces in it, **a trailing space** seems required before the quote...
