### ISSUE TITLE
"Default term" doesn't call init.bat

### ISSUE THREAD

**Issue by mrx23dot** [cmderdev/cmder#2608]
When I set cmder to override cmd.exe, and start cmd.exe it starts cmder (hook works), 
but it doesn't call init.bat to setup the lambda.
![2021-09-23 10_28_19-Window](https://user-images.githubusercontent.com/4163396/134484432-95e1b253-4876-4a51-854c-6e848ccb6a47.jpg)

After I manually call init.bat it looks correctly.
![2021-09-23 10_29_14-Window](https://user-images.githubusercontent.com/4163396/134484493-0373476f-710c-4ec7-80cb-eedb7c39e9b5.jpg)

Not sure if cmder or conemu related.
As I have seen the conemu doesn't have init.bat

win10
Version 1.3.18.1106

**Comment by daxgames** [comment]
The calling of `init.bat` in `cmd::cmder` sessions is configuration we add to Conemu.  If you remove it, you remove it.

So I dont understand why you think it 'should' work after you removed it.

**Comment by mrx23dot** [comment]
So I set this to override windows cmd.exe and click Apply:
![2021-09-24 09_22_19-Settings  xml  ConEmu 210304  64  {Preview}](https://user-images.githubusercontent.com/4163396/134642534-041688d9-a9b1-4d40-8c70-875e364ba3ae.jpg)

When I open cmd.exe it loads cmder (conemu) window, but doesn't load init.bat that turns conemu into cmder.

In another words there is a way to start cmder that doesn't apply the init script. Thus a hook is missing somewhere.
There isn't a session selection in "default term".
Even if I set session to be default it still doesnt work:
![2021-09-24 09_29_12-Settings  xml  ConEmu 210304  64  {Preview}](https://user-images.githubusercontent.com/4163396/134643465-10efb866-9a0e-4644-a006-7388bfcbc1cc.jpg)


If I simply run cmder.exe it works correctly with the cmd::cmder session. 
I didn't remove anything.

**Comment by daxgames** [comment]
Thanks for the additional info.  It always helps to know the full story.

You need to understand that the Cmder package is a collection of 4 different pieces of software tied together by configuration.

Cmder is that configuration with a custom launcher called `cmder.exe`.  It came about as a way to provide a better Windows terminal experience with minimal config required.

Each piece of software has its own features and settings that are not 100% aware of or compatible with each other.

This is not a Conemu or Cmder bug/issue it is just the way Conemu works.

You clicked a checkbox in Conemu that allows Conemu to take over for the windows cmd.exe.  Conemu knows nothing about Cmder config so it does what Conemu does.

There may be a way to do what you ask but I do not know how to do it.  I will look and see if I can figure it out and let you know.

**Comment by mrx23dot** [comment]
I will open an issue in conemu to be able to specify which session to start when taking over.
Then it will automatically configure cmder.

**Comment by mrx23dot** [comment]
https://github.com/Maximus5/ConEmu/issues/2375

**Comment by daxgames** [comment]
I looked and could jot figure out how maximus5 is overriding the cmd.exe so I am sorry I can't give you a way to get the behavior you ask for.

**Comment by chrisant996** [comment]
Well, I wrote a detailed reply explaining where in the code and why that would be a problem.  And I accidentally hit Ctrl+W, trying to select the current word (as though I were typing in my code editor), but Chrome interprets that as closing the window, so I lost it all.

Short version:
- A good spot in the relevant code is `CShellProc::PrepareExecuteParams` in src\ConEmuHk\ShellProcessor.cpp.
- I don't see a way for ConEmu to alter cmd.exe's command line.
- But it's not safe anyway to modify cmd.exe invocations to inject a call to init.bat in along with other parameters.  Can easily break other things.

**Comment by mrx23dot** [comment]
(CTRL+Z would restore the browser tab and typed text)

It can be simply chained together, 
`conemu.exe init.bat && 3rd_party_cmd`
but if we use precompiled ShellProcessor.cpp then our hands are tied. Let's see what conemu has to say.

My problem is that we loose good shortcuts like win+R cmd, win+X

**Comment by chrisant996** [comment]
> (CTRL+SHIFT+T would restore the browser tab and typed text)

Thank you - that's very handy!

> It can be simply chained together,
> `conemu.exe init.bat && 3rd_party_cmd`

Often, yes.
My point is that blind string manipulation is not a universally reliable transformation, and there will be weird breakages.
A quick and simple but strange example, to prove that particular transformation isn't universally safe:
- `cmd.exe > file` succeeds and produces a console that accepts commands but whose output is redirected.
- `cmd.exe init.bat && > file` produces a syntax error.

Maybe there's a different transformation that's universally safe, but I haven't been able to find one.

> but if we use precompiled ShellProcessor.cpp then our hands are tied. Let's see what conemu has to say.

You could make a prototype change in ConEmu and do some testing to look for ways to break it.

> My problem is that we loose good shortcuts like win+R cmd, win+X

With AutoHotkey (and also other ways) it's possible to make other shortcut keys that launch Cmder with specific tasks/tabs.
