### ISSUE TITLE
Cmder doesn't work unable to update ConEmu

### ISSUE THREAD

**Issue by Mohammed-Elashmoney** [cmderdev/cmder#2610]
I have downloaded cmder from the official site
and I putted it in [ C:\Users\'my user'\cmder ]
and I did add the PATH for cmder 
the problem is when I start the cmder as administrator the update for ConEmu show up 
![image](https://user-images.githubusercontent.com/43992621/135005293-03ec5bcb-2234-46dc-b063-dcb642a9cf8b.png)
and after I hit Download the counter stopped at 10% 
![image](https://user-images.githubusercontent.com/43992621/135005806-31900ab3-cec2-4ac2-8562-eb1041940e1e.png)
and this error occurred 
![image](https://user-images.githubusercontent.com/43992621/135005593-ccb82d77-da1f-411f-9051-bb45c7bf771e.png)
and if I hit retry this error show up again

**Comment by daxgames** [comment]
This is all conemu doing comenu updates using its own process.

**Comment by Mohammed-Elashmoney** [comment]
but the cmder doesn't work 
![image](https://user-images.githubusercontent.com/43992621/135007736-223c5e0c-2adf-4ac0-9f0b-ac16b2512db8.png)

**Comment by daxgames** [comment]
Download a new copy and refuse the update.

**Comment by daxgames** [comment]
I noticed you said you were starting cmder as admin.  What happens if you run cmder and a normal user?

**Comment by Mohammed-Elashmoney** [comment]
> Download a new copy and refuse the update.

I did that and it kind of work but the update pop up never updated always say retry idk why

**Comment by daxgames** [comment]
Did you try not running as administrator?  Is there a difference in behaviour?

**Comment by Mohammed-Elashmoney** [comment]
> Did you try not running as administrator? Is there a difference in behaviour?

Now the Update of the ConEmu 210304 Updated successfully Yesterday was never updated it always says retry 
But now it work finally

**Comment by Mohammed-Elashmoney** [comment]
I am sorry I was busy
cmder worked fine with a normal user
