### ISSUE TITLE
Cmder: init.bat has problems with Git

### ISSUE THREAD

**Issue by roblon** [cmderdev/cmder#2612]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information
Cmder version: 210304
Windows 10 x64

### Description of the issue
Freshly installed Cmder (with built-in git) git does not work at all.
![CmderPlain](https://user-images.githubusercontent.com/92030361/136360530-a35868b4-bbe8-472b-8a54-cfcfbb0230e5.PNG)

When set git from environment:

![Setting](https://user-images.githubusercontent.com/92030361/136360821-7410fe54-5622-4b0b-83c4-c266ec17f06a.PNG)

Cmder finds it and it configures correctly, git works and Cmder uses the passed git:

![CmderAfterEnvSet](https://user-images.githubusercontent.com/92030361/136361068-2ce50c1c-f8e0-4578-b483-73d8b171f7a5.PNG)

Unfortunately there must be a bug in the init.bat script which produces the error message: Syntaxerror; making impossible to profit about user_aliases and user_profile and also all default commands initialized after git setting.

![Errors](https://user-images.githubusercontent.com/92030361/136362100-ad05b1c4-8de4-497a-9405-26307f896be5.PNG)

LOGS:
`{PID=3240.TID=9476} [9476] [CDetourCreateProcess::Internal_CreateProcessInternalW] Either no blocking/elevation was needed or AM tried and failed. RealCreateProcessInteralW( ) called. Result: Success, Path: (null), Cmd Line: "C:\myPrograms\Cmder\vendor\conemu-maximus5\ConEmu\ConEmuC64.exe"  /OMITHOOKSWARN /CINMODE=600020 /AID=15860 /GID=3240 /GHWND=00041088 /BW=238 /BH=68 /BZ=1000 "/FN=Lucida Console" /FW=3 /FH=5 /TA=10100007 /HIDE /ROOT cmd /k ""%ConEmuDir%\..\init.bat" ", Error: 1008`

**Comment by daxgames** [comment]
That is not a pth we use so not sure where it is coming from.

**Comment by roblon** [comment]
@s-kocher thanks a lot, the variable `XDG_CONFIG_HOME` is nowhere set, if I set it as environment variable it changes the behaviour of the cmder start-up. In the case `XDG_CONFIG_HOME` I set, when I call `git` in cmder it search the config file into the right folder differently as when the variable is not set, however it does crashes throwing the same error maybe because it does not understand the quoting. Please have a look at the Picture.

![Variable](https://user-images.githubusercontent.com/92030361/139836306-24bac5c9-74dd-463e-ac46-e906e1da023d.PNG)

**Comment by daxgames** [comment]
Closing as this is not a Cmder issue and is most likely related to local config for Git.
