### ISSUE TITLE
Alias `gcmsg=git commit -m` not work properly

### ISSUE THREAD

**Issue by kktt007** [cmderdev/cmder#2615]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x ] Question

### Version Information

- Version 1.3.18.1106

### Description of the issue

Add lots of alias into user_aliases.cmd, 

Only find this alias **`gcmsg=git commit -m`** , `gcmsg` doesn't work properly. Below error message:

**"error: switch `m' requires a value"**

But it works if i put the file in Git "C:\Program Files\Git\etc\profile.d\aliases.sh" file.

**Comment by daxgames** [comment]
Add ` $*` after the `-m` in your alias.
