### ISSUE TITLE
this say that my windos is incompatible

### ISSUE THREAD

**Issue by Surita-pixel** [cmderdev/cmder#2616]
Esta versión de C:\Users\Equipo\Documents\cmder\vendor\git-for-windows\usr\bin\locale.exe no es compatible con la versión de Windows que está ejecutando. Compruebe la información de sistema del equipo y después póngase en contacto con el anunciante de software.
Running Git for Windows one time Post Install....
Esta versión de C:\Users\Equipo\Documents\cmder\vendor\git-for-windows\git-cmd.exe no es compatible con la versión de Windows que está ejecutando. Compruebe la información de sistema del equipo y después póngase en contacto con el anunciante de software.

eso me dice

**Comment by Surita-pixel** [comment]
i have windows 10 32 bits

**Comment by daxgames** [comment]
Cmder only supports 64 bit Windows
