### ISSUE TITLE
It is not work properly in windows 11

### ISSUE THREAD

**Issue by leo1217** [cmderdev/cmder#2619]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

Cmder 1.3.18
ConEmu 210912 [64] stable

Windows 11 Pro 22000.282

### Description of the issue

In windows11,Cmder doesn't work properly, and the highlighted syntax and syntax prompt are invalid.
![cmder_in_win11](https://user-images.githubusercontent.com/22098830/139570973-f1d55e6d-96e8-4990-800f-25a9b3de165e.png)

**Comment by chrisant996** [comment]
It might be anti virus blocking Clink from running.

See #2546 for troubleshooting.

Overview: copy the [latest clink](https://github.com/chrisant996/clink/releases) into the vendor\clink directory under the Cmder root. Then start Cmder, and share the clink.log file here (from the profile directory).

**Comment by leo1217** [comment]
```
1cf8 inject                    544 ---- 2021/11/04 21:17:53.261 -------------------------------------------------
1cf8 inject                    545 Injecting Clink...
1cf8 inject_dll                263 Version: 1.2.41.647c1b
1cf8 inject_dll                264 Arch: x64
1cf8 inject_dll                265 DLL: C:\Users\李标\AppData\Local\Temp\clink\dll_cache\1.2.41.647c1b_c637eb36\clink_dll_x64.dll
1cf8 inject_dll                267 Parent pid: 17392
1cf8 check_dll_version         153 *** ERROR ***
1cf8 check_dll_version         153 Unable to get DLL version for 'C:\Users\李标\AppData\Local\Temp\clink\dll_cache\1.2.41.647c1b_c637eb36\clink_dll_x64.dll'
1cf8 check_dll_version         153 (last error = 2)
1cf8 inject_dll                272 EXE version: 00010002 00000029

```
[clink.log](https://github.com/cmderdev/cmder/files/7475007/clink.log)

**Comment by leo1217** [comment]
> It might be anti virus blocking Clink from running.
> 
> See #2546 for troubleshooting.
> 
> Overview: download the latest clink ZIP file from [here](https://chrisant996.github.io/clink/), and extra the contents into Cmder's `vendor\clink` sub-directory. Then start Cmder, and share the `config\clink.log` file here (under Cmder's root directory).

**Comment by leo1217** [comment]
> It might be anti virus blocking Clink from running.
> 
> See #2546 for troubleshooting.
> 
> Overview: download the latest clink ZIP file from [here](https://chrisant996.github.io/clink/), and extra the contents into Cmder's `vendor\clink` sub-directory. Then start Cmder, and share the `config\clink.log` file here (under Cmder's root directory).

```
1cf8 inject                    544 ---- 2021/11/04 21:17:53.261 -------------------------------------------------
1cf8 inject                    545 Injecting Clink...
1cf8 inject_dll                263 Version: 1.2.41.647c1b
1cf8 inject_dll                264 Arch: x64
1cf8 inject_dll                265 DLL: C:\Users\李标\AppData\Local\Temp\clink\dll_cache\1.2.41.647c1b_c637eb36\clink_dll_x64.dll
1cf8 inject_dll                267 Parent pid: 17392
1cf8 check_dll_version         153 *** ERROR ***
1cf8 check_dll_version         153 Unable to get DLL version for 'C:\Users\李标\AppData\Local\Temp\clink\dll_cache\1.2.41.647c1b_c637eb36\clink_dll_x64.dll'
1cf8 check_dll_version         153 (last error = 2)
1cf8 inject_dll                272 EXE version: 00010002 00000029

```
[clink.log](https://github.com/cmderdev/cmder/files/7475016/clink.log)

**Comment by leo1217** [comment]
> It might be anti virus blocking Clink from running.
> 
> See #2546 for troubleshooting.
> 
> Overview: download the latest clink ZIP file from [here](https://chrisant996.github.io/clink/), and extra the contents into Cmder's `vendor\clink` sub-directory. Then start Cmder, and share the `config\clink.log` file here (under Cmder's root directory).

```
1cf8 inject                    544 ---- 2021/11/04 21:17:53.261 -------------------------------------------------
1cf8 inject                    545 Injecting Clink...
1cf8 inject_dll                263 Version: 1.2.41.647c1b
1cf8 inject_dll                264 Arch: x64
1cf8 inject_dll                265 DLL: C:\Users\李标\AppData\Local\Temp\clink\dll_cache\1.2.41.647c1b_c637eb36\clink_dll_x64.dll
1cf8 inject_dll                267 Parent pid: 17392
1cf8 check_dll_version         153 *** ERROR ***
1cf8 check_dll_version         153 Unable to get DLL version for 'C:\Users\李标\AppData\Local\Temp\clink\dll_cache\1.2.41.647c1b_c637eb36\clink_dll_x64.dll'
1cf8 check_dll_version         153 (last error = 2)
1cf8 inject_dll                272 EXE version: 00010002 00000029

```
[clink.log](https://github.com/cmderdev/cmder/files/7475021/clink.log)

**Comment by chrisant996** [comment]
Yup, looks like anti virus.

**Comment by leo1217** [comment]
> Yup, looks like anti virus.

I try to close anti virus software,it is still not work.

**Comment by daxgames** [comment]
Did you re-extract the archive after turning off the the antivirus?  The av usually removes the file.

**Comment by chrisant996** [comment]
The log shows that Clink successfully copied the `clink_dll_x64.dll` program file to the dll cache directory.
And then a moment later when Clink tries to access the DLL, the OS returns an error saying the file does not exist (error 2 is "file not found").

That's one of the typical interferences that anti virus suites can cause when they block Clink from running.
AV either removed the copy, or blocked access to the copy.

**Comment by leo1217** [comment]
> Right -- turning off AV won't fix the situation if AV already deleted the file. You'd need to restore the file, in addition to turning off AV.
> 
> Details:
> 
> The log shows that Clink successfully copied the `clink_dll_x64.dll` program file to the dll cache directory. And then a moment later when Clink tries to access the DLL, the OS returns an error saying the file does not exist (error 2 is "file not found").
> 
> That's one of the typical interferences that anti virus suites can cause when they block Clink from running. AV either removed the copy, or blocked access to the copy.
> 
> And if AV gets excited and also removes the original `clink_dll_x64.dll` file, then you'll be left in a stuck state even after turning off AV -- because AV either quarantined or permanently deleted the file. You'll have to restore the file. Re-extracting from the archive is one way to restore the file.
> 
> ### But please don't leave AV turned off:
> That puts your computer at very high risk of malware infection. Instead find a way to grant an exception for Clink in the AV software. All AV software I've ever seen has a way to add exceptions to avoid interfering with specific programs or specific folders.

I try again.
1. close antivirus
2. unzip cmder.7z ( it is new download)
3. right-click Cmder.exe , select Run as Administrator 
It is not work.
here is log.
![Snipaste_2021-11-05_01-25-17](https://user-images.githubusercontent.com/22098830/140389687-aa94aae8-7d5a-440b-9c33-b5fb248c87f1.png)

### clink.log:
```
3204 inject                    544 ---- 2021/11/05 01:10:35.885 -------------------------------------------------
3204 inject                    545 Injecting Clink...
3204 inject_dll                263 Version: 1.2.41.647c1b
3204 inject_dll                264 Arch: x64
3204 inject_dll                265 DLL: C:\Users\lee\AppData\Local\Temp\clink\dll_cache\1.2.41.647c1b_c637eb36\clink_dll_x64.dll
3204 inject_dll                267 Parent pid: 2176
3204 check_dll_version         153 *** ERROR ***
3204 check_dll_version         153 Unable to get DLL version for 'C:\Users\lee\AppData\Local\Temp\clink\dll_cache\1.2.41.647c1b_c637eb36\clink_dll_x64.dll'
3204 check_dll_version         153 (last error = 2)
3204 inject_dll                272 EXE version: 00010002 00000029

```


i wonder whether this problem is because win11 cmd has any change?

**Comment by leo1217** [comment]
I found this problem in 2 computers which had updated to windows 11.
and  another win10 with latest updated did not occur.

**Comment by chrisant996** [comment]
Win11 works fine with Clink.

All versions of Clink (even v0.4.9 and earlier) have periodically experienced interference from AV systems.  There is nothing Clink can do about that.

You need to examine anti virus system activity on your computers.
What you're experiencing is a known pattern of AV interference.
Also, someone reported that a recent Windows Defender signature update started giving false positives for Clink.

Are you using a third party anti virus system?  If so, has Windows Defender been disabled?  In other words, since Windows Defender is built into Windows maybe there is more than one AV system running, and you might need to add exceptions in multiple systems.  And/or report false positives to multiple AV software vendors.

**Comment by leo1217** [comment]
> Win11 works fine with Clink.
> 
> All versions of Clink (even v0.4.9 and earlier) have periodically experienced interference from AV systems. There is nothing Clink can do about that.
> 
> You need to examine anti virus system activity on your computers. What you're experiencing is a known pattern of AV interference. Also, someone reported that a recent Windows Defender signature update started giving false positives for Clink.
> 
> Are you using a third party anti virus system? If so, has Windows Defender been disabled? In other words, since Windows Defender is built into Windows maybe there is more than one AV system running, and you might need to add exceptions in multiple systems. And/or report false positives to multiple AV software vendors.

yes,i use  a third party anti virus,but that was closed before i re-unzip to install cmder.
Windows Defender was closed, too.
there was no any antivirus running.

i have no idea about this problem now.
i think maybe i should try in a totally new installed system, and than i  provide you with some logs?
now my 2 computer were updated win11 base on win10 directly.

**Comment by chrisant996** [comment]
Sorry, I don't know what to tell you.
I tested latest Clink with latest Win11 a few hours ago today.
No problems.

The clink.log clearly shows the DLL was copied successfully, and then a moment later it was not there anymore.

Also, just to double check:  What do you mean by "anti virus was closed"?

Maybe we're talking about the same thing, but "closed" is an unusual word choice.
It's necessary to "add exceptions" for files and folders, or it's necessary to "turn anti-virus off".
But "closing anti-virus" sounds like closing a window -- closing a window wouldn't have any effect because anti-virus suites are daemons that run in the background even when they aren't visibly "open".

**Comment by leo1217** [comment]
> Sorry, I don't know what to tell you. I tested latest Clink with latest Win11 a few hours ago today. No problems.
> 
> The clink.log clearly shows the DLL was copied successfully, and then a moment later it was not there anymore.
> 
> Also, just to double check: What do you mean by "anti virus was closed"?
> 
> Maybe we're talking about the same thing, but "closed" is an unusual word choice. It's necessary to "add exceptions" for files and folders, or it's necessary to "turn anti-virus off". But "closing anti-virus" sounds like closing a window -- closing a window wouldn't have any effect because anti-virus suites are daemons that run in the background even when they aren't visibly "open".

Oh sorry. 'closed' , I mean "turn anti-virus off".There is no anti virus software running.

**Comment by chrisant996** [comment]
Can you try deleting the `C:\Users\lee\AppData\Local\Temp\clink\dll_cache` directory (and all subdirectories)?
Then try starting Clink.

Also, can you successfully start Clink outside of Cmder?

**Comment by leo1217** [comment]
> Can you try deleting the `C:\Users\lee\AppData\Local\Temp\clink\dll_cache` directory (and all subdirectories)? Then try starting Clink.
> 
> Also, can you successfully start Clink outside of Cmder?

1. I can delete `C:\Users\lee\AppData\Local\Temp\clink\dll_cache`3

2. I can't open Click, below is an gif:( anti virus was turned off)

![clink](https://user-images.githubusercontent.com/22098830/140509687-16db6237-26fa-4f07-b2e5-4d6068461f74.gif)

**Comment by chrisant996** [comment]
That's not how to start Clink. Double clicking on it will flash a window for a moment and disappear.

1. Start a new `cmd.exe`
2. Run `d:\cmder\vendor\clink\clink.bat inject`

**Comment by leo1217** [comment]
> That's not how to start Clink. Double clicking on it will flash a window for a moment and disappear.
> 
> 1. Start a new `cmd.exe`
> 2. Run `d:\cmder\vendor\clink\clink.bat inject`

```
PS D:\cmder\vendor\clink> .\clink.bat inject
DLL version mismatch.
Unable to inject Clink.
See log file for details (C:\Users\lee\AppData\Local\clink\clink.log).
```

clink.log
```
4688 inject                    544 ---- 2021/11/06 00:41:42.864 -------------------------------------------------
4688 inject                    545 Injecting Clink...
4688 inject_dll                263 Version: 1.2.41.647c1b
4688 inject_dll                264 Arch: x64
4688 inject_dll                265 DLL: C:\Users\lee\AppData\Local\Temp\clink\dll_cache\1.2.41.647c1b_c637eb36\clink_dll_x64.dll
4688 inject_dll                267 Parent pid: 17060
4688 check_dll_version         153 *** ERROR ***
4688 check_dll_version         153 Unable to get DLL version for 'C:\Users\lee\AppData\Local\Temp\clink\dll_cache\1.2.41.647c1b_c637eb36\clink_dll_x64.dll'
4688 check_dll_version         153 (last error = 2)
4688 inject_dll                272 EXE version: 00010002 00000029

```

**Comment by chrisant996** [comment]
Does the file `C:\Users\lee\AppData\Local\Temp\clink\dll_cache\1.2.41.647c1b_c637eb36\clink_dll_x64.dll` exist?

If it exists, then the question is why does the OS tell Clink the file doesn't exist?

If it doesn't exist, then why did it disappear?  The OS told Clink that the file was successfully copied.  So why is it missing a moment later?

Either way, Clink can't do anything about this.

**Comment by leo1217** [comment]
> Does the file `C:\Users\lee\AppData\Local\Temp\clink\dll_cache\1.2.41.647c1b_c637eb36\clink_dll_x64.dll` exist?
> 
> If it exists, then the question is why does the OS tell Clink the file doesn't exist?
> 
> If it doesn't exist, then why did it disappear? The OS told Clink that the file was successfully copied. So why is it missing a moment later?
> 
> Either way, Clink can't do anything about this.

yes, it is very strange.
I can see `clink_dll_x64.dll` is in `C:\Users\lee\AppData\Local\Temp\clink\dll_cache\1.2.41.647c1b_c637eb36\`
![Snipaste_2021-11-06_12-06-45](https://user-images.githubusercontent.com/22098830/140597390-da8fe623-bbd4-41e5-8101-5288cfc1776f.png)

let me show you:
![clink exist](https://user-images.githubusercontent.com/22098830/140597543-f202f03f-ee68-4b73-b347-0db645e5eb21.gif)

```
3958 inject                    544 ---- 2021/11/06 12:12:07.606 -------------------------------------------------
3958 inject                    545 Injecting Clink...
3958 inject_dll                263 Version: 1.2.41.647c1b
3958 inject_dll                264 Arch: x64
3958 inject_dll                265 DLL: C:\Users\lee\AppData\Local\Temp\clink\dll_cache\1.2.41.647c1b_c637eb36\clink_dll_x64.dll
3958 inject_dll                267 Parent pid: 13948
3958 check_dll_version         153 *** ERROR ***
3958 check_dll_version         153 Unable to get DLL version for 'C:\Users\lee\AppData\Local\Temp\clink\dll_cache\1.2.41.647c1b_c637eb36\clink_dll_x64.dll'
3958 check_dll_version         153 (last error = 2)
3958 inject_dll                272 EXE version: 00010002 00000029

```

error message is `Unable to get DLL version`

**Comment by chrisant996** [comment]
`last error = 2` is the key information in the log.

2 = "file not found".

I don't know what to tell you.

The file is there, but the OS tells Clink it isn't there.

Maybe there is some other program interfering.

**Comment by leo1217** [comment]
> `last error = 2` is the key information in the log.
> 
> 2 = "file not found".
> 
> I don't know what to tell you.
> 
> The file is there, but the OS tells Clink it isn't there.
> 
> Maybe there is some other program interfering.

Will the path be affected by Chinese ？

**Comment by leo1217** [comment]
> `last error = 2` is the key information in the log.
> 
> 2 = "file not found".
> 
> I don't know what to tell you.
> 
> The file is there, but the OS tells Clink it isn't there.
> 
> Maybe there is some other program interfering.

Oh, i think i know why it no work.

my win11 user name is Chinese, not English

I try to create an new user with english name, and than cmder work normally.

**Comment by chrisant996** [comment]
> > `last error = 2` is the key information in the log.
> > 
> > 2 = "file not found".
> > 
> > I don't know what to tell you.
> > 
> > The file is there, but the OS tells Clink it isn't there.
> > 
> > Maybe there is some other program interfering.
> 
> Oh, i think i know why it no work.
> 
> my win11 user name is Chinese, not English
> 
> I try to create an new user with english name, and than cmder work normally.

In the log and information shared, the user account name seems to be "lee". Is that not the user name?

**Comment by leo1217** [comment]
> > > `last error = 2` is the key information in the log.
> > > 2 = "file not found".
> > > I don't know what to tell you.
> > > The file is there, but the OS tells Clink it isn't there.
> > > Maybe there is some other program interfering.
> > 
> > 
> > Oh, i think i know why it no work.
> > my win11 user name is Chinese, not English
> > I try to create an new user with english name, and than cmder work normally.
> 
> In the log and information shared, the user account name seems to be "lee". Is that not the user name?

Yep, I don't want to divulge personal information

**Comment by chrisant996** [comment]
That makes sense, but it would have been very helpful to know that the data shared was not accurate.

I'll look into the path handling. There must be a spot in the code where it isn't handling UTF8 correctly.

**Comment by leo1217** [comment]
> That makes sense, but it would have been very helpful to know that the data shared was not accurate.
> 
> I'll look into the path handling. There must be a spot in the code where it isn't handling UTF8 correctly.

Sorry, it is my my problem.
It worked in win10,so i ignore it.

anyway, thanks. and wait for your good news.

**Comment by chrisant996** [comment]
Are you saying on Win10 and Win11 the exact same user account name is used, and works on 10 but not on 11?

I think there must be more to the story.

But anyway, soon a new release should be available with a fix.

**Comment by leo1217** [comment]
> Are you saying on Win10 and Win11 the exact same user account name is used, and works on 10 but not on 11?
> 
> I think there must be more to the story.
> 
> But anyway, soon a new release should be available with a fix.

Yes,it works on win10.
I update win11 base on win10, account user name  was not change.
And after update, I found cmder not works .
As you see, yesterday i try to create a new user with english name, it works.

**Comment by chrisant996** [comment]
I think you must have set UTF8 as the system code page on Win10, but didn't set that up yet on Win11.

Clink is accidentally passing a UTF8 string to the system API that expects a string using the system code page. The only way that could be working on Win10 is if you set the system code page to be UTF8, which is not the default. And the Win11 computers must be using the default still, instead, thus it's not working on them.

Anyway, the next update of Clink will fix that.

Or you can set the Win11 computers to use UTF8, and that would also make it work without updating Clink.

**Comment by leo1217** [comment]
> I think you must have set UTF8 as the system code page on Win10, but didn't set that up yet on Win11.
> 
> Clink is accidentally passing a UTF8 string to the system API that expects a string using the system code page. The only way that could be working on Win10 is if you set the system code page to be UTF8, which is not the default. And the Win11 computers must be using the default still, instead, thus it's not working on them.
> 
> Anyway, the next update of Clink will fix that.
> 
> Or you can set the Win11 computers to use UTF8, and that would also make it work without updating Clink.

You are right !
I set it ,and it works now!

![Snipaste_2021-11-07_13-26-54](https://user-images.githubusercontent.com/22098830/140633551-8f3b5799-cbf8-4c6a-b08a-cf21949c5326.png)

![Snipaste_2021-11-07_13-25-11](https://user-images.githubusercontent.com/22098830/140633524-a6b0c60d-d330-4b51-ac78-e7ec9e03ce41.png)

**Comment by leo1217** [comment]
> I think you must have set UTF8 as the system code page on Win10, but didn't set that up yet on Win11.
> 
> Clink is accidentally passing a UTF8 string to the system API that expects a string using the system code page. The only way that could be working on Win10 is if you set the system code page to be UTF8, which is not the default. And the Win11 computers must be using the default still, instead, thus it's not working on them.
> 
> Anyway, the next update of Clink will fix that.
> 
> Or you can set the Win11 computers to use UTF8, and that would also make it work without updating Clink.

Now everything is normal

Thank you for your patience to help me solve the problem.

**Comment by chrisant996** [comment]
[Clink v1.2.42](https://github.com/chrisant996/clink/releases/) should fix the issue with non-ASCII account names even when the system code page is not UTF8.

**Comment by vcoppolecchia** [comment]
> chrisant996

Thank you, this solved the issue for me! :) 

For what it's worth I'm on Windows 11 Pro (version 21H2, build 22000.434).

**Comment by CassianoD2** [comment]
Who have the same problem, just active "Beta: UTF8", download de Clink below and replace all on the cmder/vendor/clink

> [Clink v1.2.42](https://github.com/chrisant996/clink/releases/) should fix the issue with non-ASCII account names even when the system code page is not UTF8.

**Comment by chrisant996** [comment]
> Who have the same problem, just active "Beta: UTF8", download de Clink below and replace all on the cmder/vendor/clink
> 
> > [Clink v1.2.42](https://github.com/chrisant996/clink/releases/) should fix the issue with non-ASCII account names even when the system code page is not UTF8.

Even better would be to update Clink.  The latest versions of Clink even include a built-in updater to make updating easy.

**Comment by abc-cassianomesquita** [comment]
> @CassianoD2
> 
> > Who have the same problem, just active "Beta: UTF8", download de Clink below and replace all on the cmder/vendor/clink
> > > [Clink v1.2.42](https://github.com/chrisant996/clink/releases/) should fix the issue with non-ASCII account names even when the system code page is not UTF8.
> 
> Even better would be to update Clink. The latest versions of Clink even include a built-in updater to make updating easy.

I made with the last version. Thank you for the info :D

**Comment by CassianoD2** [comment]
> @CassianoD2
> 
> > Who have the same problem, just active "Beta: UTF8", download de Clink below and replace all on the cmder/vendor/clink
> > > [Clink v1.2.42](https://github.com/chrisant996/clink/releases/) should fix the issue with non-ASCII account names even when the system code page is not UTF8.
> 
> Even better would be to update Clink. The latest versions of Clink even include a built-in updater to make updating easy.

Thank you for the information, i checked and i already downloaded the last verion. :D

**Comment by chrisant996** [comment]
@CassianoD2 are you saying that even after updating to the latest Clink, you were still encountering problems with non-ASCII paths?

If so, could you share specific information about what went wrong, so that I can fix the root cause of the problems?  If you must turn on "Beta: UTF8" for Clink to work, then that would mean there is a bug in Clink, and I would like to find and fix the bug.

As far as I could tell in my testing, v1.2.42 fixed the last of those kind of bugs in Clink.

Do be aware that turning on "Beta: UTF8" can work around bugs in some programs ... but it can also **_cause_** malfunctions in some programs (for various reasons, most of which are essentially pre-existing application bugs that were mostly hidden before UTF8 was possible as the system code page).
