### ISSUE TITLE
git alias doesn't work with vscode

### ISSUE THREAD

**Issue by kktt007** [cmderdev/cmder#2620]
Normally, cmder work perfectly with C:\tools\Cmder\config\user_aliases.cmd file.

I set gitbash path to `["C:\\tools\\Cmder\\vendor\\git-for-windows\\bin\\bash.exe"]` in vscode on windows, but when i open terminal and use alias, it doesn't work. I have also configure the same alias in C:\Users\Administrator\.gitconfig.

But alias still doesn't work. Like this

![img](https://images2.imgbox.com/e5/9b/GKzdTIYk_o.png)

Many thanks.

**Comment by daxgames** [comment]
`user_alias.cmd` configure aliases for `cmd` sessions they do not work in `bash` session.  This is normal behavior.

You should configure aliases for `bash` in `$CMDER_ROOT/config/profile.d/aliases.sh` or in `$CMDER_ROOT/config/user_profile.sh`

**Comment by kktt007** [comment]
> `user_alias.cmd` configure aliases for `cmd` sessions they do not work in `bash` session. This is normal behavior.
> 
> You should configure aliases for `bash` in `$CMDER_ROOT/config/profile.d/aliases.sh` or in `$CMDER_ROOT/config/user_profile.sh`

Thanks so much. As i don't know how to configure aliases.sh or user_profile.sh. Now I reference this wiki [Seamless VS Code Integration · cmderdev/cmder Wiki](https://github.com/cmderdev/cmder/wiki/Seamless-VS-Code-Integration) and it works well.
