### ISSUE TITLE
ssh-copy-id fails to create .ssh/authorized_keys

### ISSUE THREAD

**Issue by Blakoko** [cmderdev/cmder#2625]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

cmder v1.3.18
conemu 210304

Windows 10 Pro 19043
### Description of the issue

ssh-copy-id  fails to put pubkey in authorized_keys files
 it shows after trying ssh-copy-id  -i dummy_key.pub -p 1987 dummy@localhost

```log
/usr/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are prompted now it is to install the new keys
/usr/bin/ssh-copy-id: line 251: warning: here-document at line 251 delimited by end-of-file (wanted `EOF')
/usr/bin/ssh-copy-id: line 250: warning: here-document at line 250 delimited by end-of-file (wanted `EOF')
/usr/bin/ssh-copy-id: line 260: EOF: command not found
```

I Know the workaround but the shipped version of Cmder still got this issue
Actually the file in \vendor\git-for-windows\usr\bin\ssh-copy-id
got

```bash
  INSTALLKEYS_SH=$(tr '\t\n' ' ' <<-EOF)
        cd;
        umask 077;
        mkdir -p $(dirname "${AUTH_KEY_FILE}") &&
          { [ -z \`tail -1c ${AUTH_KEY_FILE} 2>/dev/null\` ] || echo >> ${AUTH_KEY_FILE}; } &&
          cat >> ${AUTH_KEY_FILE} ||
          exit 1;
        if type restorecon >/dev/null 2>&1; then
          restorecon -F .ssh ${AUTH_KEY_FILE};
        fi
EOF
```

But it should be

```shell
  INSTALLKEYS_SH=$(tr '\t\n' ' ' <<-EOF
        cd;
        umask 077;
        mkdir -p $(dirname "${AUTH_KEY_FILE}") &&
          { [ -z \`tail -1c ${AUTH_KEY_FILE} 2>/dev/null\` ] || echo >> ${AUTH_KEY_FILE}; } &&
          cat >> ${AUTH_KEY_FILE} ||
          exit 1;
        if type restorecon >/dev/null 2>&1; then
          restorecon -F .ssh ${AUTH_KEY_FILE};
        fi
EOF
)
```

Thanks.

**Comment by MartiUK** [comment]
Yeah I can confirm the bug, since this is something that has been inherited from the git-for-windows project, it likely won't be resolved until we release a new version. For the time being you are welcome to download a recent development build here: https://ci.appveyor.com/project/MartiUK/cmder/build/artifacts
