### ISSUE TITLE
[Possible enhancement] The download at releases are a bit strange: see https://github.com/cmderdev/cmder/releases [actually only cmder.zip is a bit strange]

### ISSUE THREAD

**Issue by rubyFeedback** [cmderdev/cmder#2626]
Hey cmder folks.

I recently downloaded this:

https://github.com/cmderdev/cmder/releases/download/v1.3.18/cmder.zip

Version 1.3.18.

However had I repackage it right now on Linux, so I can use it on my windows
box. And ... this is a bit strange:

If I look at the extracted directories' content I get:

    bin/
    Cmder.exe
    cmder.zip
    config/
    icons/
    LICENSE
    opt/
    vendor/
    Version_1.3.18.1106

What confuses me is that there is both an .exe file and a .zip file in
that extracted .zip file. So the .zip file contains ... another .zip file.

Perhaps there are reasons for this but ...

... when I repackage this tarball release, the .zip file, I showed above
via the https link, and put this into a .tar.xz archive on Linux, the
net result has a whooping size of **172 MB**.

Can this be correct? Because ... if I recall correctly the cmder was
quite small, only a few MB in the past. So my current assumption
is that there is too much content in the .zip file.

Just now I see the mini_cmder.zip so I think I should have used
that one. But is that big cmder.zip really needed? People who
want to push pull requests can git clone it anyway, right? Is
the huge .zip file necessary? It may confuse users perhaps.

Anyway, I just wanted to report this, feel free to disregard as-is.

**Comment by rubyFeedback** [comment]
I just downloaded mini_cmder.zip and repackaged it into
.tar.xz - it has a size of 17M but the download reports
a smaller size? The display is all a bit strange. Either
way I think this is the one I originally wanted to use. :D

**Comment by daxgames** [comment]
@rubyFeedback There is no cmder.zip inside the cmder full distribution.

**Comment by chrisant996** [comment]
> https://github.com/cmderdev/cmder/releases/download/v1.3.18/cmder.zip
> 
> Version 1.3.18.
> 
> However had I repackage it right now on Linux, so I can use it on my windows
> box. And ... this is a bit strange:

When you repackaged it, maybe you accidentally repackaged the original cmder.zip inside the new package.

It's not present in the original package.
