### ISSUE TITLE
Pasting long lines does not wrap the text correctly

### ISSUE THREAD

**Issue by hecerinc** [cmderdev/cmder#2636]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Versions

Cmder version: Version 1.3.15.1010
ConEmu build: 2021.9.12 x64
OS version: Windows 11 Enterprise 10.0.22000 Build 22000 x64
Used shell version (Far Manager, git-bash, cmd, powershell, cygwin, whatever): cmd

### Problem description

When I try to paste a long string in the text won't wrap correctly.

### Steps to reproduce

1. Open Cmder
2. Paste a text that exceeds the width of window

### Actual results

Text starts wrapping on same line

### Expected results

Text starts wrapping on new line

### Additional files

![cmderbug](https://user-images.githubusercontent.com/7988472/145514874-59cb1307-0db8-497c-90ae-2d5080727ff3.gif)

Originally opened this in the ConEmu project, but was referred here https://github.com/Maximus5/ConEmu/issues/2404

**Comment by chrisant996** [comment]
This has reported recently in another issue.  I'm on my phone right now, but please review recent issues to find it.

This does not appear to be a Clink issue.  I've added a reply in the linked ConEmu issue.

**Comment by chrisant996** [comment]
I will research further and share additional information when I can.

**Comment by chrisant996** [comment]
See https://github.com/Maximus5/ConEmu/issues/2404; a new pre-release build of Clink posted there has a setting that may improve the results, and allows overriding the behavior in case it isn't able to automatically work around the issue.

**Comment by chrisant996** [comment]
Detailed analysis is available in https://github.com/Maximus5/ConEmu/issues/2404.
This appears to be a change in Windows that has exposed a latent bug in ConEmu when a single character is printed at the end of a line.

(It is neither a Clink issue, nor a Cmder issue.)

**Comment by daxgames** [comment]
Closing because this is not Cmder.
