### ISSUE TITLE
Leading characters before λ

### ISSUE THREAD

**Issue by mohamedghry** [cmderdev/cmder#2637]
### Purpose Of The Issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information
Cmder                        1.3.18
ConEmu                     210912 stable
Windows 10 Home    19043.1348

### Description Of The Issue
In the latest version 1.3.18 the "λ" symbol is not displaying correctly when using the command prompt.

![image](https://user-images.githubusercontent.com/70846567/145692527-12745fdb-222a-497b-bc8e-934a0a2795d7.png)

### Attempted Fixes
- Replacing the vendor\profile.ps1 file with the same file from 1.3.15 release.
- Replacing λ in the vendor\profile.ps1 file with a unicode character and other characters.
- Replacing λ in the vendor\clink.lua with a unicode character and other characters.

All of the above fixes I tried didn't work.

**Comment by chrisant996** [comment]
It looks like there is a garbled escape code somewhere before the lambda.  `ESC[32m` would set the text color to green. The fact that `(32m` appears before the lambda looks as though maybe the prompt has been customized, and possibly incorrectly.

Also, since it sounds like it's happening in Powershell and Cmd, that makes it sound like a customization as well.

**Comment by mohamedghry** [comment]
> It looks like there is a garbled escape code somewhere before the lambda. `ESC[32m` would set the text color to green. The fact that `(32m` appears before the lambda looks as though maybe the prompt has been customized, and possibly incorrectly. Note the `[` vs `(`.
> 
> Also, since it sounds like it's happening in Powershell and Cmd, that makes it sound like a customization as well. I.e. it doesn't seem like it's an issue in Cmder or Powershell or Clink, but rather in a customization.

This issue didn't exist with Cmder v1.3.17 even though the same customization was there. It appeared after the Cmder folder was removed and replaced with the newest version.

As for the garbled escape code before the lambda, I think this is it, but I don't know how modify it:
```
local cmder_prompt = "\x1b[1;32;40m{cwd} {git}{hg}{svn} \n\x1b[1;39;40m{lamb} \x1b[0m"
```

**Comment by mohamedghry** [comment]
> It looks like there is a garbled escape code somewhere before the lambda. `ESC[32m` would set the text color to green. The fact that `(32m` appears before the lambda looks as though maybe the prompt has been customized, and possibly incorrectly. Note the `[` vs `(`.
> 
> Also, since it sounds like it's happening in Powershell and Cmd, that makes it sound like a customization as well. I.e. it doesn't seem like it's an issue in Cmder or Powershell or Clink, but rather in a customization.

It is solved, somehow the Environment variables were not set as before. The solution was to add `chcp utf-8` variable and the character is now normal again.
