### ISSUE TITLE
logs  unreadable code

### ISSUE THREAD

**Issue by nmydt** [cmderdev/cmder#2638]
![image](https://user-images.githubusercontent.com/62681228/145934034-9479b401-f6d1-42d6-a34b-b0dde82f7542.png)
![image](https://user-images.githubusercontent.com/62681228/145934054-c1736ef7-ac07-41a3-a07b-ae23a07033b1.png)
乱码该如何解决

**Comment by chrisant996** [comment]
That is the actual output.  The `ESC[...m` sequences are color codes.  Look up ANSI Escape Sequences to learn more about escape codes and color codes.

**Comment by nmydt** [comment]
@chrisant996  Is there any way to make the output log normal ? code with escape sequences is always unreadable.

**Comment by chrisant996** [comment]
I don't know. That is a question about the ConEmu program. Have you checked its documentation?

**Comment by daxgames** [comment]
THis is not a Cmder issue.  Closing.
