### ISSUE TITLE
bug when using up and down key

### ISSUE THREAD

**Issue by renzhn** [cmderdev/cmder#264]
Steps to reproduce this bug:
1. input `ipconfig` or any other command, `enter`
2. press `up` key, press `down` key
3. an `i` persists at beginning of line and cannot be deleted
4. press `up` key, there will be `iipconfig`

i'm using windows 8.1 x64 pro Chinese version

**Comment by Jackbennett** [comment]
Seems fixed, testing feedback on #506 please

**Comment by ilessy** [comment]
@naphelly24 thanks a lot. but the file path is now "cmder\vendor\clink.lua".

**Comment by jay763190097** [comment]
@naphelly24 how to solve the problem with the version 1.3.2?

**Comment by heweiwei** [comment]
I still encounter this issue on version 161206 stable

**Comment by jdhao** [comment]
@heweiwei , see [here](https://github.com/cmderdev/cmder/issues/506#issuecomment-438977819) for a solution.
