### ISSUE TITLE
Cmder terminal stuck when running adb command

### ISSUE THREAD

**Issue by ChairmanYSL** [cmderdev/cmder#2641]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

Cmder  v1.3.18.1106
ConEmu  v21.9.12.0
Clink   v1.3.0

Windows7 Pro 6.1.7601 Service Pack1
### Description of the issue

When I use adb in cmder, sometimes the terminal will suddenly stuck.
I saw a problem saying that cmder starts slowly, and the recommended solution is to update clink. I updated clink according to the given github address, but the problem is still not resolved.
Below is the log:
_________________________________________________________________________________
prompt filter failed:
E:\Cmder\vendor\clink.lua:290: Invalid argument
stack traceback:
        [C]: in function 'for iterator'
        E:\Cmder\vendor\clink.lua:290: in function 'get_git_status_setting'
        E:\Cmder\vendor\clink.lua:312: in function '?'
        ?: in function <?:153>
        ?: in function <?:37>
        [C]: in function 'xpcall'
        ?: in function <?:24>
        (...tail calls...)
____________________________________________________________________________________

**Comment by chrisant996** [comment]
It sounds like git is either not installed, or is not on the system PATH.

The function cited in the error is part of Cmder (not Clink), and reads as follows:

```lua
local function get_git_status_setting()
    gitStatusSetting = io.popen("git --no-pager config -l 2>nul")

    for line in gitStatusSetting:lines() do
```

The error is occurring on the `for` line.  Which means the `io.popen` line failed.  The implementation of that function in Cmder could avoid the error message if it included error handling, but either way the git integration would not work because errors are occurring when attempting to invoke git.

**Comment by ChairmanYSL** [comment]
Thanks for reply.
Follow your advice,I add git to the system `Path` ,but it still doesn't seem to work.
I am using `git-for-windos` that comes with `Cmder`.
Below is my `Path` content:
_______________________________________________________________________________________
%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;E:\svn\bin;E:\AndroidNdk\android-ndk-r10e;E:\WinSCP\;C:\Program Files\TortoiseGit\bin;E:\msys64\usr\bin;E:\msys64\mingw64\bin;E:\Cmder;E:\Cmder\vendor\git-for-windows;E:\Cmder\vendor\git-for-windows\bin
________________________________________________________________________________________

Could you please help me with that?

**Comment by chrisant996** [comment]
This is not a normal or common problem.  I would recommend to try reinstalling Cmder.

Something has gone wrong in the installation of Cmder and/or updating Clink.  Trying to figure out exactly what went wrong is probably a lot more expensive than just reinstalling.

Good luck!

**Comment by daxgames** [comment]
@ChairmanYSL if you are using git for windows embedded in cmder no need to modify the path to add git.  We handle that for you.

Are you in a git repository when you run `adb`?

If so:

Does it happen when you are not in a git repo?

What is the repo? Is it publicly available so we can try and recreate?

**Comment by ChairmanYSL** [comment]
@daxgames As you said,the problem occurs when i run `ADB` in a git repository but not when I am not in the git repository.

It usually happens when i run `adb push`，approximately 4 times for every 10 runs.

But sometimes it will also happen when i run `git` command.

I'm sorry, the repo is private and it involves trade secrets, so i can't provide to you.

Could it be related to too many files in the repo?

**Comment by daxgames** [comment]
I have never heard of an error being thrown due to too many files i  a git repo.  I HAVE heard of prompt slowness due to a git repo having  large number of files.  There are settings in cmder to improve performance in LARGE git repositories.

How can you run ADB in a git repository and not be in the git repository?  Or maybe I am misunderstanding 'the problem occurs when i run ADB in a git repository but not when I am not in the git repository'

**Comment by ChairmanYSL** [comment]
Could you please tell me how to set "disabling git prompt status"?

For example, when i run `adb devices` or `adb push xxx xxx` in the git repo, `Cmder` will suddenly stuck.Unless i press `Ctrl C` ,it will keep stuck there.
When I run `adb devices` or `adb push xxx xxx` in a directory without git repo,it will not happen.

**Comment by daxgames** [comment]
It in the `README.md`  look for Git Status Opt-Out

**Comment by daxgames** [comment]
Unreleased Cmder has the ability to do asynchronous vir prompt status.  Not sure that would resolve the issue and still allow you to have a git status aware prompt.  I guess it depends on the size of the repo.
