### ISSUE TITLE
[Question]about how to exec shell script by cmder?

### ISSUE THREAD

**Issue by color404** [cmderdev/cmder#2642]
## I hope mouse double click shell file  can run script,but it not work

![Dingtalk_20211221164746](https://user-images.githubusercontent.com/24849005/146899977-7f8b8281-8c97-4ba0-9376-b94af1a50328.jpg)
---
> **use cmder**
![动画](https://user-images.githubusercontent.com/24849005/146901086-a8a26416-3c4e-4866-af0e-1b7db316d578.gif)
---
>  **I use git for windows**
![11](https://user-images.githubusercontent.com/24849005/146901213-1409bfbf-3b31-42de-ba6f-6daee162b0b0.gif)
---
> test.sh content
```
#!/bin/bash

echo "hello world"

read -n 1
```

pls tell me how to configuration can work allright

**Comment by color404** [comment]
@daxgames  sir?

**Comment by daxgames** [comment]
Cmder is not a shell.  Cmder is a collection of software and configuration that provides an enhanced experience for cmd, powershell and bas shells.

What you ask for is not possible with Cmder.

**Comment by color404** [comment]
Thanks for the answer
