### ISSUE TITLE
Cmder error start Tomcat startup.bat

### ISSUE THREAD

**Issue by kayzzen01** [cmderdev/cmder#2649]
### Purpose of the issue
- [X] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information
Cmder Version 1.3.19.1181

Windows 10 Pro 21H2

### Description of the issue

When starting tomcat through the startup.bat script, the error message appears:

```
'C\Program' is not recognized as an internal or external command,
operable program or batch file.
```

I think it's breaking some script command when trying to open a new window. In Conemu or Command Prompt the command executed works normally.

To get around I'm starting tomcat by the command
`bin\catalina.bat run` that runs the service in the same window.

To reproduce the problem have Java and Tomcat installed and run the Tomcat startup script:

`bin\startup.bat`

I tried with Tomcat versions 9 and 10.

**Comment by daxgames** [comment]
Not really a Cmder issue other than Cmder default settings differ from ConEmu default settings.

Uncheck `Process 'start':

![image](https://user-images.githubusercontent.com/7318053/149826190-a3ae599d-37a5-4a57-8827-3d1fc62904b4.png)
