### ISSUE TITLE
setting codepage error

### ISSUE THREAD

**Issue by renzhn** [cmderdev/cmder#265]
C:\Users\renzhn
λ cp 65001
      0 [main] us 0 init_cheap: VirtualAlloc pointer is null, Win32 error 487
AllocationBase 0x0, BaseAddress 0x68570000, RegionSize 0x210000, State 0x10000
D:\Software\System\cmder\vendor\msysgit\bin\cp.exe: *** Couldn't reserve space for cygwin's heap, Win32 error 0

**Comment by Jackbennett** [comment]
I have no idea from this, if you can still get it to do it from the current or pre-build please open a new ticket.
