### ISSUE TITLE
shortcut commands dont work

### ISSUE THREAD

**Issue by yousefharley** [cmderdev/cmder#2653]
Commands dont work. i need help 
Commands like ls,cp,--help...etc
![Capture](https://user-images.githubusercontent.com/98108551/150370275-2a6bfcbd-bdd1-47ce-8a08-7047f91e2f3c.PNG)

**Comment by daxgames** [comment]
Are you using 32 bit windows.  Cmder is 64bit only.

**Comment by daxgames** [comment]
No response from OP Closing
