### ISSUE TITLE
prompt: missing space between path and scm state

### ISSUE THREAD

**Issue by geekrumper** [cmderdev/cmder#2654]
### Purpose of the issue
- [x ] Bug report (encountered problems/errors)

### Version Information
Version 1.3.19.1181

Windows 10 Enterprise (19042.1415)

### Description of the issue
The prompt is missing a space between folder and scm state.

Actual behavior:
`C:\work\projects\test(develop -> origin)`

Expected behavior:
`C:\work\projects\test (develop -> origin)`

I took the liberty to manually add a space in [clink.lua (169,63)](https://github.com/cmderdev/cmder/blob/master/vendor/clink.lua#L169), but I'm pretty sure that is not the right spot, since there were no changes in that file a while ago. After reading all about prompts, I was not able to fix this behavior via `config` and thus using `vendor` scripts.

**Comment by geekrumper** [comment]
Is this intentional? Can it be fixed somewhere else in the code? I was hesitant to create a pr with "fix".

**Comment by daxgames** [comment]
Probably intentional.  I did not go back and look to see if/when it might have changed.

**Comment by chrisant996** [comment]
The regression was introduced on Apr 16, 2021 by commit 0ef76ee2d3555d2fc967b5c61fdafda0933f50b3.

Before that commit, the prompt had space between `{cwd}` and `{git}...`:
```lua
    local cmder_prompt = "\x1b[1;32;40m{cwd} {git}{hg}{svn} \n\x1b[1;39;40m{lamb} \x1b[0m"
```

After that commit, the prompt no longer has a space there:
```lua
    prompt = uah_color .. "{uah}" .. cwd_color .. "{cwd}{git}{hg}{svn}" .. lamb_color .. cr .. "{lamb} \x1b[0m"
```

It was an accidental regression, and can be fixed by inserting a space immediately before `{git}` in this line:
```lua
    local version_control = prompt_includeVersionControl and "{git}{hg}{svn}" or ""
```

Finding it was very quick for me, but making a PR would take time that I don't have.
Someone else can make a PR with a fix, though.

**Comment by chrisant996** [comment]
> I took the liberty to manually add a space in [clink.lua (169,63)](https://github.com/cmderdev/cmder/blob/master/vendor/clink.lua#L169), but I'm pretty sure that is not the right spot, since there were no changes in that file a while ago. After reading all about prompts, I was not able to fix this behavior via `config` and thus using `vendor` scripts.

That is exactly the correct fix.  🙂

**Comment by geekrumper** [comment]
@chrisant996

pr #2661 is out. Thank you for this wonderful project. I've been using this since ages....
