### ISSUE TITLE
%PATH% is duplicated if running nested `cmders`

### ISSUE THREAD

**Issue by nguyenduy4321** [cmderdev/cmder#2655]
I created an alias `cmder=cmd.exe /k "%CMDER_ROOT%\vendor\init.bat"` to nest cmders (for personal use). Then I edit the `user_profile.cmd` file (in `config` folder), I do `set "PATH=mydrive\mypath\;%PATH%"` (set somepath).

When I try to run `cmder` in `cmder` (nested), I run the `set` command to check `%PATH%` it seems that `PATH` is duplicated what is set by `cmder`.

Maybe, `cmder` should avoid this duplication because it looks nice.

**Comment by daxgames** [comment]
Please provide detailed steps to receeate the issue then type:

`set path`

Provide the output please.

Cmder `init.bat` does actively try to avoid path duplication.

**Comment by nguyenduy4321** [comment]
Here:
1. I use `cmder` in `Windows Terminal` and add my plugins to `cmder` path, like below image
![image](https://user-images.githubusercontent.com/17503425/150822495-39d2446e-a2a0-4dcc-a66e-8a828fc7dd5c.png)
2. I alias `cmder=cmd.exe /k "%CMDER_ROOT%\vendor\init.bat"`
![image](https://user-images.githubusercontent.com/17503425/150823140-e8fc6474-2d15-42ab-af9c-d3e920154c58.png)
3. Type `set` to see `PATH`
![image](https://user-images.githubusercontent.com/17503425/150823455-f2e5d12e-1ca7-4dc3-80eb-c7d38f98f7b0.png)
4. Type `cmder` (have aliased), type `set` to see `PATH` again
![image](https://user-images.githubusercontent.com/17503425/150823705-07404894-940b-486e-9289-e780a7ef2f1f.png)

Sorry I didn't reply soon...

**Comment by daxgames** [comment]
This is not cmder doing this. It is your `user_profile.cmd`.  You can avoid this by using `%lib_path% enhance_path "D:\portapp\node"` the way `init.bat` does in `user_profile.cmd`

**Comment by nguyenduy4321** [comment]
Hummm… I think `cmder` wants me to modify `user_profile.cmd` to add `PATH` as the comments in this file.

Why do you let me to modify `init.bat`? I dont know the reason?

**Comment by daxgames** [comment]
I didnt tell yoy to edit `init.bat`, you never edit `init.bat`.  I told you to edit `user_profile.cmd` and use the same enhance_path method `init.bat` uses.

**Comment by daxgames** [comment]
`%lib_path% enhance_path [path]` tries to avoid duplication of paths but it is not 100% effective.  It could probably be made smarter. 

Can I ask WHY are you insist on nesting Cmder inside Cmder, it makes absolutely NO SENSE, just use another tab.

**Comment by daxgames** [comment]
I just tested it:

![image](https://user-images.githubusercontent.com/7318053/152453537-477c4a44-5ea7-42c8-bc61-b0dfee987846.png)

The `1093` is the number of characters in the path.  It does not appear to be growing or duplicating anything?

**Comment by daxgames** [comment]
If using `init.bat /f` the smarts of `%lib_path% enhance_path` are disabled thus allowing duplication.  See below:

![image](https://user-images.githubusercontent.com/7318053/152454631-707b361b-b9f7-4366-9704-df09b87cc055.png)
