### ISSUE TITLE
Can not run Tomcat server, the new openned tab shows error message

### ISSUE THREAD

**Issue by feralvarez95** [cmderdev/cmder#2656]
Me and some people of my team were using cmder as console for an application develpment that uses Tomcat. At first we were able to run the command to run the server, which open a new tab with the environment variables in it.

Then, in some moment (few months ago) when we run that command that runs the server in debug mode the message in the new tab is '"C:\Program" is not recognized as external or internal command'. 

Different configurations had been tested, as different installation folders, admin permissions, etc. but we can't run the server on cmder as we did it before (we have to use Windows terminal).

Have you seen this problem? Is there any solution for this?

Thanks!

**Comment by daxgames** [comment]
See #2649

**Comment by feralvarez95** [comment]
This is just what I need, thanks!
