### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by ThingsChange** [cmderdev/cmder#2657]
![image](https://user-images.githubusercontent.com/21259965/150902982-c1a497da-8315-42bc-8fb9-5049dad8b5c6.png)
当我启动时候，就会报这个错误，并且每当我运行命令的时候，命令可以正常执行，但是也会带上这个错误输出，即使我敲了一个回车命令依旧如此。v10.16.0 是我前几天在用的node版本。

**Comment by chrisant996** [comment]
Can you paste the text from the console, instead of a screenshot?

Text could be translated, but screenshots are much harder to translate.

**Comment by ThingsChange** [comment]
'v10.16.0"' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'DEFAULT' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
系统找不到指定的路径。

**Comment by ThingsChange** [comment]
@chrisant996 
'v10.16.0"' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'DEFAULT' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
系统找不到指定的路径。

**Comment by chrisant996** [comment]
I'm sorry, I tried to use Google Translate, but I don't know what you are reporting.  I also don't know why you mentioned me.

**Comment by ThingsChange** [comment]
> I'm sorry, I tried to use Google Translate, but I don't know what you are reporting.
> 
> ~I also don't know why you mentioned me.~ Update: Oh, you mentioned me because I suggested that pasting text might make it possible for someone to use a translator and attempt to help you.
> 
> I don't know what is happening on your computer, or what to suggest to do about the problem. The only thing I was able to do was remind that pasting screenshots makes it almost impossible for someone to help unless they know the language.

I pretend I can't see them now
