### ISSUE TITLE
vim unavailable

### ISSUE THREAD

**Issue by fxzbiz** [cmderdev/cmder#2658]
![image](https://user-images.githubusercontent.com/95843684/151324749-b738a9e8-4a49-4801-bbb4-096a9d0d3131.png)

**Comment by daxgames** [comment]
Works for me.

**Comment by daxgames** [comment]
Is this a fresh install?

Do you have  `~/.vimrc` or other valid vim config file.  If so rename it and see itmf that is the issue.

**Comment by ktyl** [comment]
I believe this is a reason: https://github.com/Maximus5/ConEmu/issues/2384
