### ISSUE TITLE
`hg_prompt_filter()` does not use `get_hg_branch()` which is specifically intended to get the Mercurial branch information

### ISSUE THREAD

**Issue by vsajip** [cmderdev/cmder#2659]
This code

https://github.com/cmderdev/cmder/blob/711fe2895e5331e183ee72c200a3f67349f1fa12/vendor/clink.lua#L525-L527

does not make use of the function specifically there for the purpose of getting the Mercurial branch information, which is at 
https://github.com/cmderdev/cmder/blob/711fe2895e5331e183ee72c200a3f67349f1fa12/vendor/clink.lua#L305-L321

It should do that, because it is better to encapsulate details of how the branch information is obtained/formatted. For example, I use the `prompt` extension for Mercurial to customise the information.

Earlier versions of cmder used `get_hg_branch()`, and it's not clear why that was changed.

**Comment by daxgames** [comment]
If you can fix it ease do and open a PR.
