### ISSUE TITLE
中文输入问题

### ISSUE THREAD

**Issue by cfzhangwl** [cmderdev/cmder#2667]
cmder 配置git 环境并启用，在两个相同符号间（如''，""），输入汉字“你好”后，光标会定位在中间某一位置，如下图
![image](https://user-images.githubusercontent.com/20165452/153526332-5da196e8-67fa-4c3c-ae47-a692011eafd9.png)
回车后 显示如下
![image](https://user-images.githubusercontent.com/20165452/153526387-44df2c1c-8f93-4d2b-9692-6234533d45e9.png)
再次输入“朋友”，点击“enter”后有这样啦
![image](https://user-images.githubusercontent.com/20165452/153526472-bd4cd6bb-deef-4e62-94a2-0973395abd80.png)

thanks!

**Comment by daxgames** [comment]
Translation: Configure the git environment and enable it, between two identical symbols (such as '', ""), enter the Chinese character "Hello", the cursor will be positioned somewhere in the middle, as shown in the following figure.

Even after translation I do not understand the issue.  The above screenshot is looks like it is from MINGW running in Comemu which is not Cmder.

**Comment by chrisant996** [comment]
It looks like an issue in bash, maybe.

It might be a UTF8 issue.

Very little information was provided, so  it's very difficult to offer any ideas without first asking 20 questions.
