### ISSUE TITLE
Replace CTRL+W Hotkey functionality

### ISSUE THREAD

**Issue by omiid-ad** [cmderdev/cmder#2668]
Hi, 
I used to use `ctrl+W` hotkey to delete the whole word before cursor location, but in `Cmder`, it closes current window.
How can i tweak that and replace it with the mentioned functionality?

**Comment by daxgames** [comment]
Configure it here:

![image](https://user-images.githubusercontent.com/7318053/154799515-41458bee-b360-46b9-9a7b-0bf2065f5de3.png)
