### ISSUE TITLE
If the "cmder" application path uses latin characters the "clink" library location is compromised.

### ISSUE THREAD

**Issue by VitorLuis2010** [cmderdev/cmder#2672]
I usually install applications in the "**Utilitários**" folder and that doesn't work.

Error log:

4240 inject                    545 ---- 2022/02/25 09:56:48.499 -------------------------------------------------
4240 inject                    546 Injecting Clink...
4240 copy_dll                  122 *** ERROR ***
4240 copy_dll                  122 Failed to copy DLL to 'C:\Users\vitor\AppData\Local\Temp\clink\dll_cache\1.2.46.69fc92_bf036c34\clink_dll_x64.dll'
4240 copy_dll                  122 (last error = 3)
4240 inject_dll                264 Version: 1.2.46.69fc92
4240 inject_dll                265 Arch: x64
4240 inject_dll                266 DLL: E:\**Utilit�rios**\cmder\vendor\clink\clink_dll_x64.dll
4240 inject_dll                268 Parent pid: 5824
4240 check_dll_version         154 *** ERROR ***
4240 check_dll_version         154 Unable to get DLL version for 'E:\**Utilit�rios**\cmder\vendor\clink\clink_dll_x64.dll'
4240 check_dll_version         154 (last error = 2)
4240 inject_dll                273 EXE version: 00010002 0000002e

**Comment by chrisant996** [comment]
That was a bug in Clink, which was fixed in v1.2.47, released on Nov 27, 2021.

The current version of Cmder includes Clink v1.2.46, which does not include that fix.

You can download the latest Clink `.zip` file from https://github.com/chrisant996/clink/releases and extract its contents into the `vendor\clink` directory under the Cmder install directory.

**Comment by daxgames** [comment]
@VitorLuis2010 See latest unreleased [build](https://ci.appveyor.com/project/MartiUK/cmder/build/artifacts)

**Comment by Snuupy** [comment]
> That was a bug in Clink, which was fixed in v1.2.47, released on Nov 27, 2021.
> 
> The current version of Cmder includes Clink v1.2.46, which does not include that fix.
> 
> You can download the latest Clink `.zip` file from https://github.com/chrisant996/clink/releases and extract its contents into the `vendor\clink` directory under the Cmder install directory.

This fixed my broken `%PATH`. Thanks. Not sure what in my path was breaking it before, but I used v1.3.38 of clink and my path was fixed in cmder.
