### ISSUE TITLE
添加新功能：标签增加一个重命名或者额外的信息，可以通过命令行启动参数时配置

### ISSUE THREAD

**Issue by jhalx** [cmderdev/cmder#2679]
举个例子
当我在一个窗体中启动了多个标签页，但是它们的标签显示的都是cmd.exe（当他们处于空闲状态时），我需要一个一个的去点击才能找到想要的窗口。
可以使用命令行创建时添加这个额外的自定义信息，我自己一般都是通过双击一个windows下的批处理文件通过命令来创建一个窗口，更方便快捷，所以我希望有命令行的参数来提供给这个功能。
提供三个形式，在标签显示的内容：
1、自定义信息+进程信息
2、只显示自定义信息
3、只显示进程信息
最好是能放在标签栏的设置里面可以用来配置相关的条目。

不知道是否能实现，只是一个想法，如果不能，请关闭这个条目。谢谢🌹

**Comment by chrisant996** [comment]
You can set the tab title a few different ways.  The ConEmu documentation has some useful information.  Also you can use a batch script when starting cmd tabs, and the batch script can use the cmd title command.  Good luck.
