### ISSUE TITLE
How to add ssh keys?

### ISSUE THREAD

**Issue by mikikuke** [cmderdev/cmder#2681]
I can find private and publish key in my cpanel...
so I need to add private key to my cmder?
How to do that?

I tried to run ssh username@domain 
as I always do but I got connection timeout error
I changed my computer...so probbaly that is the reason....

I know how to load ssh key into putty but I am not using putty

**Comment by daxgames** [comment]
Not sure I understand but I just create "%userprofile%\.ssh" folder and store and use my keys from there.

You can also use the `ssh-agent` provided by Git for Windows.  Just uncomment it in "%cmder_root%\config\user_profile.cmd" after placing the files as suggested above.

**Comment by mikikuke** [comment]
Can you please be more specific....how to create the folder...manually or with cmder command?
Basically, I have the public and private key from my host....and I don't know how to add them...
They send me instructions for putty but not for cmder....
I thought there is settings inside cmder to add keys but I can't find them.

I have gitbash installed and ssh does not connect there too.

I need to copy and paste private key to that folder?

**Comment by mikikuke** [comment]
I have .ssh folder already in my user folder...in WIN 11  
I have private key downloaded....if I put the file in there it does not work...do I have to copy the key from inside the file somehow?

**Comment by daxgames** [comment]
`ssh -i [path to private key] [user]@[host]`
