### ISSUE TITLE
Git: fatal: Unable to create '.git/index.lock':

### ISSUE THREAD

**Issue by Neerajsharma18** [cmderdev/cmder#2682]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [ ] Question

**Comment by Neerajsharma18** [comment]
fatal: Unable to create '/home/ec2-user/mumbai/.git/index.lock': Permission denied

**Comment by daxgames** [comment]
Are you ssh into an AWS EC2 instance?

How is this a Cmder issue?

**Comment by Neerajsharma18** [comment]
yes i am in AWS EC2 instance

**Comment by 296951** [comment]
Cmder has nothing to do with filesystem permissions preventing you from running Git commands in an nEC2 Instance this is not a Cmder issue.

**Comment by daxgames** [comment]
Cmder has nothing to do with filesystem permissions preventing you from running Git commands in an nEC2 Instance this is not a Cmder issue.

Closing.
