### ISSUE TITLE
how to split user_aliases.cmd which is too long

### ISSUE THREAD

**Issue by scil** [cmderdev/cmder#2683]
I'd like to split the long file user_aliases.cmd into multiple files.

Is there any way to achive it?

**Comment by chrisant996** [comment]
It sounds like you are unfamiliar with cmd scripts (batch scripts, shell scripts, etc).

So I would recommended to read about the [call](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/call) command.

**Comment by daxgames** [comment]
`user-aliases.cmd` is two things.  It is indeed a cmd file but it is also a self executing doskey macro store.

The lines at the top that are preceded by `;= ` are run as cmd code and line 3 uses doskey to load the `user-aliases.cmd` file as a doskey macro store that ignores the lines preceded by `;= `

Splitting thia file maybe possible by duplicating line 3 and pointing to the other alias files that include the same `;= ` lines in the current `user-aliases.cmd`.

Hopefully this makes sense

**Comment by scil** [comment]
> `user-aliases.cmd` is two things. It is indeed a cmd file but it is also a self executing doskey macro store.
> 
> The lines at the top that are preceded by `;= ` are run as cmd code and line 3 uses doskey to load the `user-aliases.cmd` file as a doskey macro store that ignores the lines preceded by `;= `
> 
> Splitting this file maybe possible by duplicating line 3 and pointing to the other alias files that include the same `;= ` lines in the current `user-aliases.cmd`.
> 
> I have not tried it but it might work and it might not.
> 
> Hopefully this makes sense

Thank you. It works!

This is my tree structure
```
user_aliases.cmd
my_aliases\
  sys-port.cmd
```

add a line into user_aliases.cmd
```

;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%~dp0%my_aliases/sys-port.cmd

;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%


```
