### ISSUE TITLE
enter is not a good copy and paste command

### ISSUE THREAD

**Issue by botao1995** [cmderdev/cmder#2685]
python3 -m paddle_serving_client.convert --dirname ./ch_PP-OCRv2_det_infer/ \
                                         --model_filename inference.pdmodel          \
                                         --params_filename inference.pdiparams       \
                                         --serving_server ./ppocrv2_det_serving/ \
                                         --serving_client ./ppocrv2_det_client/

![image](https://user-images.githubusercontent.com/47848566/161941247-c9ba73af-6171-4e79-9ff8-8f14af5397bb.png)
pasting multiple lines of text will send the Enter key to the console
can the problem be solved

**Comment by daxgames** [comment]
This is not an issue with Cmder.  The pasted dialog is from Conemu a third party component of Cmder that we do not control.
