### ISSUE TITLE
VSCode integration - console text is highlighted / has background of a different color

### ISSUE THREAD

**Issue by hyperrecursive** [cmderdev/cmder#2693]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Version Information

ConEmu 210912 [64]
Cmder 1.3.19

Microsoft Windows 11 Home 10.0.22000 Build 22000

### Description of the issue

The Cmder text is highlighted as shown in the screenshot below.

<img width="790" alt="image" src="https://user-images.githubusercontent.com/12224339/164547568-9baf3670-e971-4e77-a8b7-32a82c50b310.png">

This is run in the default console integrated in Visual Studio Code. As you can see, I'm starting cmder with `cmd /K vscode_init.cmd` directly with `cmd.exe`. I would appreciate any hints on how can I fix the background.

**Comment by daxgames** [comment]
Colors are configurable in the latest versions of Cmder.  It is ot super intuitive but if you search the issues you will probably find suggested solutions.

**Comment by daxgames** [comment]
Look for 'Changing Cmder Default cmd.exe Prompt Config File' in the README.md file.

**Comment by chrisant996** [comment]
See #2516.

**Comment by hyperrecursive** [comment]
I changed the file mentioned in the #2516 like so:
```
-- Prompt Element Colors
uah_color = "\x1b[1;33;49m" -- Green = uah = [user]@[hostname]
cwd_color = "\x1b[1;32;49m" -- Yellow cwd = Current Working Directory
lamb_color = "\x1b[1;30;49m" -- Light Grey = Lambda Color
clean_color = "\x1b[1;37;49m"
```
It worked. Thank you!
