### ISSUE TITLE
character display problem

### ISSUE THREAD

**Issue by jan-bar** [cmderdev/cmder#2694]
When I use a custom command in alias, or enter a command and press tab to complete it, the command will roll back a bit, causing problems with the display.

![GIF 2022-4-22-周五 15-21-54](https://user-images.githubusercontent.com/14202095/164627743-e61b9a1d-d08f-4d62-bfbb-c0f574c1e372.gif)

**Comment by jan-bar** [comment]
Change the prompt and it's ok.

![GIF 2022-4-26-周二 12-28-59](https://user-images.githubusercontent.com/14202095/165221362-0427f69d-febb-4905-bfb6-df1a5ee606ed.gif)

**Comment by chrisant996** [comment]
This type of thing has been reported in many issues.

It is a mismatch between font and the system code page.

Running `chcp 65001` or choosing a different font could be another way to resolve the issue.

Especially if you are currently using a CJK code page.

**Comment by jan-bar** [comment]
@chrisant996 Thanks for your reply, this worked. I'll look into it, thanks a lot
