### ISSUE TITLE
cd doesn't work with "~", but ls does

### ISSUE THREAD

**Issue by HeyItsJono** [cmderdev/cmder#2704]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information
Cmder v.1.3.19 via Windows Terminal Preview 1.14.1452.0.

### Description of the issue
For a period of time after updating to the most recent Cmder version, I was able to use `~` as a stand-in for `%HOME%` universally in all commands via the standard command prompt shell.
Unfortunately this has suddenly stopped working for commands like `cd` or `touch`, but oddly continues to work for `ls`.

For example, `cd ~` returns `The system cannot find the path specified.`, but `ls ~` will print the contents of my User directory as intended.
![image](https://user-images.githubusercontent.com/4620093/170811022-05037794-2a1d-40ad-8ce4-69e71c7ea73f.png)

If it makes a difference, my `cd` is aliased to `cd /d`, but even with this removed it doesn't work.

**Comment by chrisant996** [comment]
What shell are you using inside Cmder?  Cmd?  Bash?  Powershell?  Something else?

- Windows doesn't recognize `~` as a path component.
- `ls` is a *nix program ported to Windows, and the *nix emulation library (usually cygwin) emulates recognizing `~`.
- `cd` is a command built into cmd.exe, and it doesn't recognize `~`.
- `touch` must be some program you have, and apparently it doesn't recognize `~`.
- Clink can expand `~` when using filename completion, if `expand-tilde` is set `on` in the `.inputrc` file.

I don't know how `~` could have been working before, unless you were using Linux inside Cmder via the WSL.

**Comment by HeyItsJono** [comment]
Sorry, I thought I mentioned just standard CMD via Windows Terminal, with Cmder. No bash or anything. It's super odd but I updated to the latest Cmder version (and clink) about a week ago and since then ~ has inherently been working with all commands. Now it's suddenly stopped and I haven't changed anything. 

Setting `expand-tilde` to on sort of gets me there in that I can type `cd ~/directory` and press `Tab` and it will expand, then I can hit `Enter` to execute the command. Would there be any way to automatically expand `~` on hitting `Enter` to avoid needing to hit `Tab` first?

**Comment by chrisant996** [comment]
If tilde seemed to work as the home dir in Windows Cmd, I can't explain how. It shouldn't have been able to.

**Comment by chrisant996** [comment]
Also, see [Clink issue #289](https://github.com/chrisant996/clink/issues/289) for a discussion about a recent request for automatic tilde expansion.

If it's something you want to try to force, you can write a Lua script and use `clink.onfilterinput()` to postprocess the input line and replace tildes according to whatever rules you prefer.

**Comment by HeyItsJono** [comment]
Thanks for your advice! I wrote a small lua script to do exactly that and it works a treat. I've uploaded it [here](https://github.com/HeyItsJono/HomeClink) in case anyone wants a similar solution.

**Comment by chrisant996** [comment]
I'm glad it meets your needs.

The `rl.expandtilde()` function is part of the Readline library, and it's very simplistic.

For example, it doesn't pay any attention to quotes.  So the following (admittedly unlikely) example:
`program --open-document "c:\documents\~ important ~\taxes.doc"`

Becomes this:
`program --open-document "c:\documents\~ important C:\Users\You\taxes.doc"`

Which is a little unexpected, and not necessarily what one would expect.

However, here is an example where that _is_ what one would expect:
`powershell -Command "ls ~\Documents"`

Which is the whole problem with tilde expansion in Windows:  the only place that could _accurately_ do tilde expansion would be the file system itself.  And in Windows the file system doesn't recognize tilde.  So one must resort to parsing the command line input string, but there's no way to reliably accurately do that.

The script you've shared is a pretty good way to approximate it.
