### ISSUE TITLE
Multiple .dll files not found after repeated installations

### ISSUE THREAD

**Issue by AFarence** [cmderdev/cmder#2710]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

Latest Version: v1.3.19

Microsoft Windows 11 Home, version 10.0.22000 Build 22000

### Description of the issue

I've tried reinstalling CMDER multiple times. Each time, a series of .dll files are always missing (see sample screenshot). 

Also for whatever reason, Zone Identifier now flags a series of files when it previously didn't. I followed instructions and manually unblocked each one, but this problem still persisted. (Also I have to unblock them each time I try and run CMDER). I mention this because I'm not sure if these issues are related.

I'm trying to reinstall CMDER because my antivirus put (I think the .git file?) into quarantine and couldn't restore it. Any help would be much appreciated.

<img width="342" alt="image" src="https://user-images.githubusercontent.com/83982643/173159701-5a2aeb4e-ee33-415f-bfd2-e25a457830ce.png">

**Comment by daxgames** [comment]
There are zero dependencies on the .git folder.  This sounds like an Antivirus false positive issue quarantining files incorrectly.  Setup ann exclusion.
