### ISSUE TITLE
Ctrl+Backspace Causes Display Error when String Length > 5

### ISSUE THREAD

**Issue by madturtle84** [cmderdev/cmder#2713]
**Issue:**
Entering `123456` then `Ctrl+Backspace` leaves the first character "1" on the screen and can't be remove. 
Screen Record: https://user-images.githubusercontent.com/9062917/173731238-3dcc6d1d-5d4c-4521-b910-cca381e2dd8c.mp4

**Expected** 
`Ctrl+Backspace` should clear all characters of a word. 

**Detail**
The issue only happens when string length > 5.
The issue doesn't affect the execution of the command but the character in question persists in screen dump therefore confuses the users when reviewing.

**Comment by chrisant996** [comment]
That's a font vs codepage issue.

The lambda character is what's triggering the discrepancy.

Configure the prompt to not use a lambda character, or use a different codepage, or use a different codepage.

**Comment by chrisant996** [comment]
> That's a font vs codepage issue.
> 
> The lambda character is what's triggering the discrepancy.
> 
> Configure the prompt to not use a lambda character, or use a different codepage, or use a different codepage.

EDIT: or use a different font (I didn't mean to say codepage twice 😜).
