### ISSUE TITLE
Update request: Git/Gitbash embedded in Cmder is v.2.34.0 while we have Git 2.37.1

### ISSUE THREAD

**Issue by savbran** [cmderdev/cmder#2718]
Hi, the current (last) version of Cmder has still Git/Git bash embedded v.2.34.0.
Any possibility to update it to the last stable one: Git/Git bash 2.37.1 ?

Thanks in advance.

**Comment by daxgames** [comment]
Version is updated but build is failing for unrelated reason.  Closing.
