### ISSUE TITLE
Cmder not detecting local git configuration

### ISSUE THREAD

**Issue by Osolemio44** [cmderdev/cmder#2719]
## environment info:

ConEmu 210912 [64] Startup Info
OsVer: 10.0.19044.x64, Product: workstation, SP: 0.0, Suite: 0x100 (windows 10 X64)
Build: 2009, UBR: 1806, ReactOS: 0, Rsrv: 0, WINE: 0, PE: 0, R2: 0

## issue

I use cmder as the default terminal on my work computer. But it is not detecting the git configuration of the computer.
For example, today I did a git fetch and it gave me the following error:

![Code_GZZEhBeoH6](https://user-images.githubusercontent.com/55595063/178695771-87f35941-87f0-4d77-b6f0-d1ca34ffaa35.png)

but when i use git bash, i have no problem:

![Code_Y7rFkvRzZd](https://user-images.githubusercontent.com/55595063/178695873-73c95c93-03f4-4c55-9d4e-e19d01c0ab14.png)

In case it helps, this is my Environment Variables:

![SystemPropertiesAdvanced_dsZ1cQkgII](https://user-images.githubusercontent.com/55595063/178697058-39145962-48fe-408a-ae7a-d3b91d553307.png)

Is this a bug? How can i fix this?
thank you.

**Comment by daxgames** [comment]
I don't think this is a Cmder thing I think this is a git thing.

It would be nice to see the things you have obscurred to see if there is any important info there.

**Comment by Osolemio44** [comment]
the only thing i blurred was my full name.

**Comment by daxgames** [comment]
https://stackoverflow.com/questions/66629862/cannot-determine-the-organization-name-for-this-dev-azure-com-remote-url
https://itecnote.com/tecnote/r-cannot-determine-the-organization-name-for-this-dev-azure-com-remote-url/

**Comment by Osolemio44** [comment]
I've looked at the urls you gave me. They do not solve the problem I have.
I have done a `git config -l` in git terminal and cmder terminal. In both they give me different configurations. It is clear that it is not a Git or VSCode configuration problem , but that cmder is pointing to the Git that it has internally instead of correctly detecting the one that is installed on the system. How can i fix this?

**Comment by daxgames** [comment]
I got nothing given the current detaiks provided.

Need more detail.  There are `cmder_diag.[cmd|ps1|sh]` files you could run and post output.

You say cmder is pointing to a different `git`.   

Do you have git installed outside of Cmder you would rather use?  You say you run `git config` in a `bash` terminal are you starting `git-bash` from the Start Menu?

You say the git configs are different?  How are they different.

**Comment by Osolemio44** [comment]
this is what cmder_diag.cmd generated:
[cmder_diag_cmd.log](https://github.com/cmderdev/cmder/files/9168844/cmder_diag_cmd.log)
 
I have a local Git installation in my computer. And yes i would prefer to use the Git from the Computer instead the one from cmder. Ithought that cmder detect your local git and use it instead of the one bundled.

When i do git config -l from cmder i got this output:
```log
core.symlinks=false
core.autocrlf=true
core.fscache=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
help.format=html
diff.astextplain.textconv=astextplain
rebase.autosquash=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
credential.helper=!"C:/portables/cmder/vendor/git-for-windows/mingw64/libexec/git-core/git-credential-manager-core.exe"
credential.helperselector.selected=manager-core
user.name=********
user.email=********@********.com
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
merge.tool=kdiff3
mergetool.kdiff3.path=C:/Program Files/KDiff3/bin/kdiff3.exe
mergetool.kdiff3.trustexitcode=false
diff.guitool=kdiff3
difftool.kdiff3.path=C:/Program Files/KDiff3/bin/kdiff3.exe
difftool.kdiff3.trustexitcode=false
mergetool.keepbackup=false
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
core.hookspath=.husky
remote.origin.url=https://********/********/Core%20Platform%20Frontend/_git/web-b2c
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=origin
branch.main.merge=refs/heads/main
branch.develop.remote=origin
branch.develop.merge=refs/heads/develop
branch.feat/special-request-images.remote=origin
branch.feat/special-request-images.merge=refs/heads/feat/special-request-images
branch.feat/legal-text-on-card-saving.remote=origin
branch.feat/legal-text-on-card-saving.merge=refs/heads/feat/legal-text-on-card-saving
```

this is the the output og git config -l from gitbash from the local git installation: 
```log
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
credential.helperselector.selected=manager-core
user.name=*******
user.email=*******
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
merge.tool=kdiff3
mergetool.kdiff3.path=C:/Program Files/KDiff3/bin/kdiff3.exe       
mergetool.kdiff3.trustexitcode=false
diff.guitool=kdiff3
difftool.kdiff3.path=C:/Program Files/KDiff3/bin/kdiff3.exe        
difftool.kdiff3.trustexitcode=false
mergetool.keepbackup=false
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
core.hookspath=.husky
remote.origin.url=https://*******/*******/Core%20Platform%20Frontend/_git/web-b2c
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=origin
branch.main.merge=refs/heads/main
branch.develop.remote=origin
branch.develop.merge=refs/heads/develop
branch.feat/special-request-images.remote=origin
branch.feat/special-request-images.merge=refs/heads/feat/special-request-images
branch.feat/legal-text-on-card-saving.remote=origin
branch.feat/legal-text-on-card-saving.merge=refs/heads/feat/legal-text-on-card-saving
```

**Comment by chrisant996** [comment]
If you don't want to use Cmder's copy of git, why is the Full version of Cmder installed?  The Mini version is Cmder without git.  That's the difference.  The download instructions say if you already have git installed, then use Mini not Full.

**Comment by Osolemio44** [comment]
because I don't want to download several different versions of cmder in the first place.  and another reason is because cmder is indicated to try to detect the local git.
![Screenshot_20220722-183059_GitHub.png](https://user-images.githubusercontent.com/55595063/180484399-23b14aa3-4233-4aa2-96ea-162babbf56ce.png)

please, if you do not intend to contribute anything constructive or help, avoid commenting.

**Comment by chrisant996** [comment]
It was an honest question, and might have been a solution.  You didn't mention why you were using the Full version.  Please consider sharing more information, so that people can offer better help.

**Comment by chrisant996** [comment]
Three thoughts, observed by looking at Cmder's `init.bat` file:
- Have you tried setting the `%GIT_INSTALL_ROOT%` environment variable to tell Cmder where the local git is?
- Is Cmder configured to use `%fast_init%`?  If so, then that intentionally skips looking for a local git (because looking for a local git is slow).
- The way Cmder looks for a local git is by searching the system `%PATH%` by using `where.exe`.  If the local git isn't on the system path, or if the Cmder vendor git is on the system path earlier, then the local version won't be used.

One way to figure out what's happening could be to do some troubleshooting by editing the `init.bat` file to print information about what's happening while it's looking for where to find git.

**Comment by daxgames** [comment]
Based on the output from `cmder_diad.cmd` Cmder appears to be working properly.  The user installed git is older than Cmder embedded git.

```
GIT_VERSION_USER=2.32.0.windows.2 GIT_VERSION_VENDORED=2.34.0.windows.1
```

That is why it is using the embedded git.


If you want to use your git then upgrade it, use `Cmder Mini` or set `%GIT_INSTALL_ROOT%` before launching Cmder.

**Comment by Osolemio44** [comment]
It's my work computer and it's locked in many ways. One of them is that it won't let me update Git.
Setting the environment variable GIT_INSTALL_ROOT fixed the problem. So thank you very much.
