### ISSUE TITLE
cmder.net DNS down? Can I help?

### ISSUE THREAD

**Issue by zedshaw** [cmderdev/cmder#2721]
Not sure if this is the best way to report this, but the cmder.net DNS entries are not resolving.  If you're having trouble hosting the site I'd be _very_ interested in taking over your hosting for you for free.  Please let me know the best way to contact you and we can talk out how to get it back online.  Best is to email me at help@learnjsthehardway.com or DM me on Twitter @lzsthw to work out how I help with hosting.

Thanks!

**Comment by omgnuts** [comment]
Love this app, and happy to know if you need help with this too. Let me know, thanks @daxgames.

**Comment by daxgames** [comment]
Honestly I don't know who handles the DNS.  I know its not me. @cmderdev/core @cmderdev/trusted-contributors

**Comment by Stanzilla** [comment]
Not me :/

**Comment by MartiUK** [comment]
This would have been @samvasko. I am registering cmder.app and will host the site on cloudflare.
