### ISSUE TITLE
Cmder build is failing

### ISSUE THREAD

**Issue by daxgames** [cmderdev/cmder#2723]
@cmderdev/core @cmderdev/trusted-contributors anyone know how to fix this.

![image](https://user-images.githubusercontent.com/7318053/179559082-00cafabf-8225-4872-9e85-027a974cc15c.png)

**Comment by Stanzilla** [comment]
I would do exactly the same, yeah. Remove XP

**Comment by daxgames** [comment]
Thought about that but thought it may be fixable in Appveyor by whomever manages that for us.

**Comment by daxgames** [comment]
@MartiUK Did you ever get this to build in Appveyor.  I ask becasue I setup my fork in Appveyor and it does actually build PRs  and create artifacts.  The odd part is the artifacts have the wrong version file in them.  They build as `1.3.6-pre*`.

I know nothing about Appveyor and just setup a default project.  Are there additional settings you specified in yours?

**Comment by DRSDavidSoft** [comment]
@MartiUK There is something wrong with the current AppVeyor configuration.  We either need access to the configuration page to modify it, or access to admin settings of Cmder repo to change the CI to another account that have proper configurations.

**Comment by MartiUK** [comment]
Looks like it's building fine now, I re-ran with the latest commit
