### ISSUE TITLE
clink-completions update

### ISSUE THREAD

**Issue by chrisant996** [cmderdev/cmder#2727]
@daxgames Hi, Dax.  I have an update to the git support in clink-completions.  It is currently sitting as a PR in Vladimir's repo, but it's been a couple of weeks and Vladimir hasn't responded, so I wonder if he has abandoned the project.

I am looking at the possibility of promoting my fork as the new active repo for clink-completions.  I am also considering expanding the scope of what it includes.

The improvements are currently in this branch in my fork:
https://github.com/chrisant996/clink-completions/tree/clink_improvements

- It is still compatible with Clink v0.4.9 -- it uses new stuff only when running in a Clink that supports the new stuff, and it falls back to using v0.4.9 mechanisms when necessary.
- Fixes path parsing bugs, by using the new built-in Clink path parsing APIs when present.
- Fixes git repo search code when not in a git repo (it tried to walk up past the root dir and got confused).
- Improvements in `git` parser.
  - Displaying command completions includes descriptions of many commonly used commands.
  - For aliases, displaying command completions shows the aliased command as the description.
  - Completing stash names supports the `clink-select-complete` command.
  - Updated to use new Clink APIs, to make things work better.
  - Added support for more git commands.
  - Updated flags for all/most git commands.
  - Made aliased commands use the parser for the aliased command, so that completions work even when using aliased commands.
  - Uses new API for defining parsers, which makes it easy to add descriptions for completions for commands, arguments, or flags (and falls back to the old API when necessary).
- Various bug fixes.

P.S.  I've been using these enhancements for almost a year now, and I thought it was about time to share them.

**Comment by DRSDavidSoft** [comment]
If https://github.com/vladimir-kotikov/clink-completions/pull/149 is not merged, I appreciate Cmder using @chrisant996's fork for future updates.

**Comment by chrisant996** [comment]
A couple of days ago Vladimir made me an owner in his repo. I'm working on an update to include my PR and also several feature requests from the issues in the repo.

I'll post here again when the update is ready.

**Comment by DRSDavidSoft** [comment]
Thanks for letting me know, as I always I appreciate your updates to clink, so thanks! 😀

**Comment by chrisant996** [comment]
clink-completions v0.4.1 is available.

See [clink-completions/Releases](https://github.com/vladimir-kotikov/clink-completions/releases) page for download link and release notes.

I included a bunch of pending requests from the past few years, as well.

**Comment by DRSDavidSoft** [comment]
https://github.com/cmderdev/cmder/pull/2739 Just got merged, `v0.4.1` is now included with the new releases of Cmder.  Thanks @chrisant996!

**Comment by chrisant996** [comment]
I've got one more set of minor enhancements coming soon, which includes descriptions for single-character flags on common git commands.

I don't have any further plans for the near future for clink-completions.
