### ISSUE TITLE
cmder.net has expired.

### ISSUE THREAD

**Issue by bfleury-boul** [cmderdev/cmder#2728]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question

### Description of the issue

Not really an issue on the code itself, but `cmder.net has expired.`
Just wanted you to know about it =)

**Comment by MartiUK** [comment]
@bfleury-boul Now https://cmder.app managed by me.
