### ISSUE TITLE
Website is unavailable

### ISSUE THREAD

**Issue by AM-ops** [cmderdev/cmder#2730]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

Not Applicable (N/A)

### Description of the issue

The cmder.net/ website seems to be offline. Could be possible expiration of DNS. However when I checked the date it shows as:

Tuesday 11th of July 2023

**Comment by AM-ops** [comment]
Using the Wayback Machine the last snapshot taken was on: [12 July 2022](https://web.archive.org/web/20220712002720/cmder.net/)

Website was up at that time

**Comment by nero-0** [comment]
[cmder.app](https://cmder.app)
