### ISSUE TITLE
Hardcoded startup directory overwrites "Cmder here" on Windows

### ISSUE THREAD

**Issue by yomajo** [cmderdev/cmder#2731]
Using Windows.

I did `.\Cmder.exe /REGISTER ALL` as administrator in Cmder directory. as documentation instructs.
![image](https://user-images.githubusercontent.com/45366313/181892020-714f9e0d-98ec-4ac0-bea9-aad0c7766093.png)

However when I launch cmder from startup I want to set startup directory, so at task `cmd::Cmder` I have:

`cmd /k ""%ConEmuDir%\..\init.bat" " -new_console:d:C:\Coding `

When I launch from context, I expect working directory changed to the one Cmder being launched from.
![image](https://user-images.githubusercontent.com/45366313/181891558-2455b1d0-1175-4cd3-9131-69a7b128c03d.png)

How to set it up? Most questions-answers use older Cmder syntax and while editing task in the past I completely messed up my setup and had to delete and setup fresh.

**Comment by daxgames** [comment]
Don't hardcode a folder in the default task.  Hardcoding always wins.

Put the default task back to the default.

Create a shortcut to cmder.exe and add the folder path after cmder.exe in the shortcut.

Or

Create a new task and hardcode a folder there.  Create a shortcut and tell it to launch that task using `/task`

**Comment by yomajo** [comment]
Thank you Sir! Have a great rest of the weekend. Never would have thought shortcuts had options.

![Screen Shot 07-30-22 at 07 30 PM](https://user-images.githubusercontent.com/45366313/181928291-8afd4ff8-3fb2-4ae5-8bb2-2951c1c337d5.JPG)
