### ISSUE TITLE
Can't open Cygwin under cmder

### ISSUE THREAD

**Issue by ElvargThemSelf** [cmderdev/cmder#2732]
Whenever I try to open a new Cygwin window/tab on cmder I rather get this cryptic message instead on my **conemu-cyg-64** itself:

```bash
ConEmuC64: Process was not attached to the console. Is it GUI?

Current directory:
C:\Users\my_username

Command to be executed:
D:\path\to\conemu-cyg-cyg.exe C:\cygwin64\bin\bash.exe --login -i
```

I am at a complete loss here since cmder worked flawlessly a month ago. And I've also noticed python itself not opening as it should.

**Comment by daxgames** [comment]
Chances are this is a Conemu thing.  I'd look there.

ConEmu is the terminal emulator in Cmder.  If you are running Cygwin in Conemu then it has nothing to do with Cmder.
