### ISSUE TITLE
Startup is very slow, taking more than 30+ seconds

### ISSUE THREAD

**Issue by r8t0** [cmderdev/cmder#2733]
Translated from Google:
Hello, thank you for providing such a useful tool, but in the process of using it, I encountered a problem. 

The startup is very slow. Clicking "Cmder Here" in the right-click menu takes 36 seconds to start (00:01-00:37). 
Add the "/f" parameter according to this [issue,](https://github.com/cmderdev/cmder/issues/2602) and it takes 23 seconds to start (00:47-01: 10).
Press Enter directly without executing any command after startup, and it will be stuck for 1 second each time you enter (the last demonstration of the video)

video: 

https://user-images.githubusercontent.com/109657322/182510729-140a24a4-5d52-4ce1-927a-905e09a31c6c.mp4

![gif](https://user-images.githubusercontent.com/109657322/182553120-90174a6b-d5fa-4bc4-a137-7f06907736da.gif)

env:
i7-1165G7
16G
Windows10 21H2
Version 1.3.19.1181

**Comment by MM-UU** [comment]
Same here. Since the latest version it takes up to 6 minutes to start up on my laptop (i7-10510U/64Gb/Win10 21H2/ver 1.3.19.1181)

![image](https://user-images.githubusercontent.com/77098551/185341627-097a3eae-2625-4082-9dfd-b49d695f9dd8.png)

**Comment by r8t0** [comment]
> Same here. Since the latest version it takes up to 6 minutes to start up on my laptop (i7-10510U/64Gb/Win10 21H2/ver 1.3.19.1181)
> 
> Even with /f added for faster starting, it still takes the same time.
> 
> ![image](https://user-images.githubusercontent.com/77098551/185341627-097a3eae-2625-4082-9dfd-b49d695f9dd8.png)

By editing the init.bat, vender/lib/lib_base.cmd, and vender/clink.lua files, I removed many extended functions, such as git, svn environment detection, etc., and only retained the clink injection, history, and tag key command prompt functions. Startup now takes less than 7 seconds.

**Comment by chrisant996** [comment]
What is the `%PATH%` environment variable set to?

Are there any network paths in the `%PATH%` environment variable?

**Comment by daxgames** [comment]
The only time I have ever seen this kind of slowness is:

1. Corporate managed system with some software that inspects everything for data loss prevention. Most likeley cause in my experience.
2. Network paths as @chrisant996  mentioned.

**Comment by MM-UU** [comment]
> What is the `%PATH%` environment variable set to?
> 
> Are there any network paths in the `%PATH%` environment variable?

Unfortunately no network paths in the environment variable (both user and system variables)...

Somehow I had a good day yesterday (only 6 seconds), but today I had a long one (5 minutes +), a less long one (about 1.5 minute) and again some fast ones (only 6 seconds again and even 4 seconds)...

**Comment by daxgames** [comment]
@MM-UU If you go back to an older version does speed improve?

I still believe there is something on your systems causing this extreme(more than 5 seconds) .  I get the below times running on a circa 2016 intel Core i5 Linux laptop that has no SSD disk and 8GB RAM running an under powered Windows 10 Enterprise Virtualbox VM.

**Comment by MM-UU** [comment]
Just downloaded 1.3.17.1802, but it is still the same. Really weird because it started to get slow when I was using 1.3.18 (at first it was quick).

**Comment by daxgames** [comment]
@MM-UU is this on a personal system or a company managed system?  I have seen first hand the problem you describe and it is ALWAYS something on that system.

Have you tried another computer?

**Comment by daxgames** [comment]
@r8t0 thanks for the effort but these line times make no sense whatsoever.  Things that shold be very quick are not.

Same questions:

1. Is this on a personal system or a company managed system?  I have seen first hand the problem you describe and it is ALWAYS something on that system.

2. Have you tried another computer?

THERE IS SOMETHING ON YOUR SYSTEM CAUSING THIS!  :-)

**Comment by r8t0** [comment]
I got it. It's a system problem. This problem appears in a company managed system.Thank you

**Comment by daxgames** [comment]
@r8t0 check #2744 may help out your slowness.
