### ISSUE TITLE
Cmder failed to build with error on MSVC

### ISSUE THREAD

**Issue by fangzhouxia** [cmderdev/cmder#2734]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

the commit of Azerothcore_wotlk we use is 4846eff
windows server 2019
VS version: VS2019 (16.11.11)

### Description of the issue

Hi, all
Cmder fails to build on MSVC due to error "7z" Could you help look?

error message:
At F:\gitP\cmderdev\cmder\scripts\build.ps1:72 char:1
+ Ensure-Executable "7z"
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Ensure-Executable

Detailed log:
[build (1).log](https://github.com/cmderdev/cmder/files/9314012/build.1.log)

**Comment by daxgames** [comment]
Do you have 7zip installed and in the path?

**Comment by fangzhouxia** [comment]
Sorry for being late. We have 7zip, this problem can be avoided by specifying the absolute path of 7zip, but 7zip cannot be found in the programw6432 path, can you tell me what the programw6432 path is?

**Comment by daxgames** [comment]
`ProgramW6432 = C:\Program Files ` so we look for 7zip installed at `C:\Program Files\7-zip\7z.exe`
