### ISSUE TITLE
Backslash is added to files when tab completeing `git add`

### ISSUE THREAD

**Issue by mheden** [cmderdev/cmder#2743]
### Purpose of the issue
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information
cmder-full (scoop) 1.3.19
ConEmu 21.9.12.0

### Description of the issue
Thanks for a great program!

It seems like backslah is added to files when tab complete on `git add`:
![image](https://user-images.githubusercontent.com/8748209/189095201-66dd78ae-2fae-43eb-9368-321214cae6e3.png)

I tested with Clink v1.3.42.ef446e in an normal `cmd.exe` and it did not add the backslash.

If I try for example `notepad <tab>` it only adds backslashes to directories so it seem to be related to `git` somehow.

**Comment by mheden** [comment]
Now I saw that then testing clink in `cmd.exe` I uses `clink` from here https://chrisant996.github.io/clink which might be a different version that is bundled with cmder. However, the original issue remains.

**Comment by chrisant996** [comment]
That issue was fixed in Clink v1.3.40 (introduced in v1.2.7).

**Comment by chrisant996** [comment]
You can copy a newer Clink version into the Cmder vendor\clink\ directory.

**Comment by mheden** [comment]
Thanks, now it works fine! I guess it will be included in cmder sooner or later?

**Comment by daxgames** [comment]
Yes it will.
