### ISSUE TITLE
Crashes on Windows 11 arm64

### ISSUE THREAD

**Issue by rsmz** [cmderdev/cmder#2749]
Is there a dedicated build for arm64 or a workaround?

**Comment by daxgames** [comment]
No there is not an arm64 build.

**Comment by DRSDavidSoft** [comment]
Duplicate of #2633

**Comment by DRSDavidSoft** [comment]
This require core components (e.g. ConEmu, Clink and git-for-windows) to support ARM64 natively.

There is no ETA, but the support is in progress by the individual developers/authors of each project separately.

Once all the required dependencies have ARM support, we will release Cmder (ARM edition) for that platform.  Note that the older ARM32 (e.g. arm7l and older) are not supported, probably.

**Comment by chrisant996** [comment]
> This require core components (e.g. ConEmu, Clink and git-for-windows) to support ARM64 natively.

Yes.  Clink added ARM64 in v1.4.7.
