### ISSUE TITLE
Side effect from '&' at Cmder home folder name

### ISSUE THREAD

**Issue by fvoronin** [cmderdev/cmder#275]
When Cmder home folder name contain '&' symbol, it has side effect on start.

Exec `C:\A&B\Cmder.exe` and get in console

```
"C:\A" is not an internal or external command, operable program or batch file. 
The system can not find the path specified.

C:\Users\Batman>|
```

**Comment by Jackbennett** [comment]
Tested this with a downloaded mini 1.3.2

@cmderdev/trusted-contributors CMD task chokes on this, powershell is fine. will somebody who knows more that I on batch scripting fix this or add the wontfix label and close if it can't be done.

installed path: `C:\temp\cmder&mini\Cmder.exe`
```cmd
'C:\temp\cmder' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.

C:\Users\jbennett>%CMDER_ROOT%
'C:\temp\cmder' is not recognized as an internal or external command,
operable program or batch file.
'mini' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by daxgames** [comment]
& in batch is a reserved character and should not be used in folder or filenames. I am surprised it was even possie.

We can't fix this.
