### ISSUE TITLE
此应用无法在你的电脑上运行

### ISSUE THREAD

**Issue by chinassx** [cmderdev/cmder#2755]
![微信截图_20221016003209](https://user-images.githubusercontent.com/8578704/195997699-0f75be0a-9b48-4f34-97d9-af34c18a3017.png)

### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

**Comment by chrisant996** [comment]
Translates to "this app won't run on your PC".

**Comment by DRSDavidSoft** [comment]
@chinassx Sorry, but do you use an ARM64 based Windows 11, such as a Surface PC?

If so, please be aware that Cmder doesn't currently run on ARM.  You can check by clicking **This PC** → **Properties** or holding <kbd>Windows</kbd> + <kbd>Pause/Break</kbd> and checking **System type**.

The only platform that we currently support is Intel x86_64 or amd64, not 32-bit or ARM of any kind.

Other than that, maybe the .exe file somehow got corrupted.

**Comment by chinassx** [comment]
好的，谢谢~


| |
申少雄
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年10月17日 09:06 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [cmderdev/cmder] 此应用无法在你的电脑上运行 (Issue #2755) |

您是否使用基于 ARM64 的 Windows 11，例如 Surface PC？

如果是这样，请注意 Cmder 目前不在 ARM 上运行。您可以通过单击此 PC → 属性或按住 Windows + Pause/Break 并检查系统类型来检查。

我们目前支持的唯一平台是 Intel x86_64 或 amd64，而不是 32 位或任何类型的 ARM。

除此之外，也许 .exe 文件以某种方式损坏了。
