### ISSUE TITLE
`./build.ps1 -verbose` fails looking for `msbuild.exe`

### ISSUE THREAD

**Issue by daxgames** [cmderdev/cmder#2757]
### Purpose of the issue
- [X] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question

### Version Information

Cmder: master

### Description of the issue

`./build.ps1 -verbose` fails looking for `msbuild.exe` if running from a simple Powershell session that is not `msbuild` aware.  This should only happen if the `-compile` switch is also used.

**Comment by DRSDavidSoft** [comment]
@daxgames Thanks, PR #2758 will fix this issue.

**Comment by daxgames** [comment]
@DRSDavidSoft You are too fast.  🥇  Initially just documenting so I would not forget it but I was fixing after seeing the issue in the code.
