### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by AMANSAINI7144** [cmderdev/cmder#2768]
### Suggestion

Add Hacktoberfest2022 tag to your previous issues.

### Use case

Add Hacktoberfest2022 tag to your previous issues.

### Extra info/examples/attachments

Add Hacktoberfest2022 tag to your previous issues.

### Checklist

- [X] I have read the documentation and made sure this feature doesn't already exist.
- [X] I have searched for similar issues and found none that describe my feature request.

**Comment by DRSDavidSoft** [comment]
क्या तुम ठीक हो मेरे दोस्त?
