### ISSUE TITLE
[Feature request] Load scripts inside profile.d recursively

### ISSUE THREAD

**Issue by LucasOe** [cmderdev/cmder#2781]
### Suggestion

Currently only scripts inside the root profile.d directory get loaded on startup. I think it would be useful for scripts to be loaded recursively for more flexibility in sorting. For example powershell scripts could be loaded with
`Get-ChildItem -Path "$env:USERPROFILE\scripts\*.ps1" -Recurse | ForEach-Object {. $_.FullName)} | Out-Null`
for example.

### Use case

I have a powershell script with multiple other files as a dependency. The ability to have the script confined inside a it's own directory would help to make the directory structure more clean.

### Checklist

- [X] I have read the documentation and made sure this feature doesn't already exist.
- [X] I have searched for similar issues and found none that describe my feature request.

**Comment by chrisant996** [comment]
A reminder to watch out:  This would be a breaking change, and could cause existing scripts to suddenly start running when they would not otherwise have run.  This suggestion has potential for great harm to some exists users, if it were to be enabled by default.

**Comment by daxgames** [comment]
I am of the opinion that if you have scripts that need to load recursively you have the ability to do that yourself.

**Comment by chrisant996** [comment]
> I am of the opinion that if you have scripts that need to load recursively you have the ability to do that yourself.

Clink uses the same approach:  it loads Lua scripts from a well-known location.  If a user wants to load all scripts recursively, they can write a Lua script to do so and put it in the well-known location.  (However, doing so would break completions in Clink, since Clink expects that no Lua scripts in the completions\ folder will have been loaded.)

**Comment by LucasOe** [comment]
That's true, I didn't think about backwards compatibility when creating this issue. I'll use a script to load from subfolders then.
