### ISSUE TITLE
Question:  [Errno 2] Issue

### ISSUE THREAD

**Issue by MazzilloH** [cmderdev/cmder#2793]
### Question

Hi, I am really new at programming and I couldn't find a solution for this error, sorry if it the solution is too obvious

C:\Users\hyo11
λ cd PycharmProjects\pythonProject

C:\Users\hyo11\PycharmProjects\pythonProject
λ ls
'Conversor de Moneda 2.py'   convertidor.py   ex03_01/   main.py   venv/

C:\Users\hyo11\PycharmProjects\pythonProject
λ py Conversor de Moneda 2.py
C:\Users\hyo11\AppData\Local\Programs\Python\Python311\python.exe: can't open file 'C:\\Users\\hyo11\\PycharmProjects\\pythonProject\\Conversor': [Errno 2] No such file or directory

### Checklist

- [ ] I have read the documentation and made sure what I'm looking for isn't present, or is unclear.
- [ ] I have searched for similar issues, and either this question wasn't asked before, or I didn't find any that describe my question.

**Comment by DRSDavidSoft** [comment]
Sorry, this issue is related to Python programming language and not Cmder itself.  Please refer to other sources regarding help with coding in Python.

Happy programming! 😄

**Comment by MazzilloH** [comment]
Ok hahahaha thank you really because I am really new, so is sometimes
confuse some errors that appear
