### ISSUE TITLE
[Bug] Input string was not in a correct format.

### ISSUE THREAD

**Issue by bachig26** [cmderdev/cmder#2797]
### Version Information

```markdown
Cmder version: 1.3.21
Operating system: Windows 10
```

### Cmder Edition

Cmder Full (with Git)

### Description of the issue

```
Cannot convert value "1671444289,09065" to type "System.Int32". Error: "Input string was not in a
correct format."
At D:\cmder\vendor\profile.ps1:228 char:46
+ ... sed Time: $(get-Date) `($($CMDER_INIT_END - $CMDER_INIT_START) total` ...
+                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvalidCastFromStringToInteger
```

**_I don't why this error is occurring but it wasn't during my latest upgrades. and this error shows for the PowerShell only._**

### How to reproduce

After upgrading to the latest version 1.3.21 from 1.3.20

### Checklist

- [X] I have read the documentation.
- [X] I have searched for similar issues and found none that describe my issue.
- [X] I have reproduced the issue on the latest version of Cmder.
- [X] I am certain my issues are not related to ConEmu, Clink, or other third-party tools that Cmder uses.

**Comment by MartiUK** [comment]
Ah, yeah. I guess you're from a country that uses `,` for decimal places. I'll have a fix for you soon.

**Comment by MartiUK** [comment]
For now, you can delete that line from the profile.ps1 file, as it's only used for debugging.
