### ISSUE TITLE
[Bug] Show text weird when every time I opened a new cmder

### ISSUE THREAD

**Issue by MyDinnerIsReady** [cmderdev/cmder#2812]
### Version Information

```markdown
Cmder version: 1.3.20.151
Operating system: Windows 10 Education Version 21H2 OS build 19044.2364
```

### Cmder Edition

Cmder Mini

### Description of the issue

1. When I opened a new cmder and first input something and delete some characters, it will be like this:

https://user-images.githubusercontent.com/36349581/210470608-4e266794-c107-46a6-ad78-a48ddaac1060.mp4

2. When I texted ``git pull`` and it will be this. But if I run the command it will work correctly.

https://user-images.githubusercontent.com/36349581/210471488-edd7c499-ac88-406e-b59f-881095ac711e.mp4

### How to reproduce

Every time open a new cmder and it will be like this.
But It will be fine after I deleted them all and input again.

### Checklist

- [X] I have read the documentation.
- [X] I have searched for similar issues and found none that describe my issue.
- [X] I have reproduced the issue on the latest version of Cmder.
- [X] I am certain my issues are not related to ConEmu, Clink, or other third-party tools that Cmder uses.

**Comment by chrisant996** [comment]
There are many duplicate issues for this. Please read other similar issues for an explanation, and for ways to solve the problem.

**Comment by MyDinnerIsReady** [comment]
> There are many duplicate issues for this. Please read other similar issues for an explanation, and for ways to solve the problem.

Oh, I am really sorry but can you give me a URL with it?
I really did a lot of searches for it but I got nothing.
Thank you very much.

**Comment by chrisant996** [comment]
Do you know how to search Closed issues?

https://github.com/cmderdev/cmder/issues?q=is%3Aissue+is%3Aclosed

Many duplicates.  For example, the first one listed right now (2808) is the same issue.

**Comment by MyDinnerIsReady** [comment]
> Do you know how to search Closed issues?
> 
> https://github.com/cmderdev/cmder/issues?q=is%3Aissue+is%3Aclosed
> 
> Many duplicates. For example, the first one listed right now (2808) is the same issue.

Lol thanks, I know how to search but I don't know how to express the question, I tried such as 'cmder text issues', or 'cmder print exception' etc...
Really thanks for your answer.
I really like cmder but I really stuck with the issue.
Thanks a lot.

**Comment by chrisant996** [comment]
Clink v1.4.8 looks like it may have solved the width problems with the lambda character in the prompt.
