### ISSUE TITLE
Good News -- Clink v1.4.9 solves the lambda problems

### ISSUE THREAD

**Issue by chrisant996** [cmderdev/cmder#2813]
### Suggestion

This is not a feature request; it is a celebration/announcement about a fix in Clink v1.4.9 which affects Cmder significantly.

Yay!  Clink v1.4.9 fixes the Cmder lambda problems for CMD.exe (of course not for bash or powershell or etc, though).

The measurements for East Asian ambiguous width characters weren't always being used, and the combination of fixing that and rewriting the input line display should solve the lambda problems.

Caveat:  Due to the mismatch between the OS vs terminal program vs CJK codepage vs font, it is still possible that there may be some combinations of those where the measurement will still be incorrect.  But generally speaking, it should work seamlessly now for the majority of users in CJK locales.

### Checklist

- [X] I have read the documentation and made sure this feature doesn't already exist.
- [X] I have searched for similar issues and found none that describe my feature request.

**Comment by daxgames** [comment]
Awesome news @chrisant996 this is the most annoying reoccurring bug report we receive.  Fantastic work!

**Comment by jakitliang** [comment]
But ConEmu doesn’t support Asian languages with either `conemu-msys2` `conemu-cyg` and `conemu-msys`.

Using `msys2_shell.cmd` the envir may print some symbol that ConEmu can’t process and support, which will renderer bad output in some situation.

I don’t known why Windows Terminal does good, even though it borns after. And I see there is no updates and no response for many GitHub issue posts.

**Maybe Conemu is dead.** It didn’t finish support language features but dead.

I like `Clink` and it’s way to integrated nix-tools. Hope Conemu will be removed and replace with any other emulator.

**Comment by DRSDavidSoft** [comment]
@chrisant996 Thank you for your great contributions as always. 🎉 Users in v1.3.24 of Cmder will benefit from this!
