### ISSUE TITLE
[Bug] internal git get stuck when fetching

### ISSUE THREAD

**Issue by zorrohahaha** [cmderdev/cmder#2827]
### Version Information

```markdown
Cmder version:221218 stable
Operating system:Win10
```

### Cmder Edition

Cmder Full (with Git)

### Description of the issue

When typing "git fetch origin" in the bash ENV, sometimes the session get stuck and cannot quit.

### Checklist

- [X] I have read the documentation.
- [X] I have searched for similar issues and found none that describe my issue.
- [X] I have reproduced the issue on the latest version of Cmder.
- [X] I am certain my issues are not related to ConEmu, Clink, or other third-party tools that Cmder uses.

**Comment by zorrohahaha** [comment]
> Does it happen outside cmder in the same git repo running git bash?
> 
> The only thing Cmder changes in bash config is the prompt character so this is likely not Cmder issue.

I am using the git-bash directly from the "vendor/git-for-windows" and there is no such issue.
It seems the fetch was already done, but the bash prompt got stuck and cannot accept any new input. @daxgames 
And with some previous releases in 2021, there is no such issue either.

**Comment by daxgames** [comment]
Then I do not understand.

> When typing "git fetch origin" in the bash ENV,

And

> I am using the git-bash directly from the "vendor/git-for-windows" 

Are both git bash from `vendor\git-for-windows`p
