### ISSUE TITLE
Question: Running non-administrator command prompt inside an administrator Cmder console

### ISSUE THREAD

**Issue by holahapi** [cmderdev/cmder#2829]
### Question

How can I open a non-administrator command prompt inside an administrator Cmder console?

### Checklist

- [X] I have read the documentation and made sure what I'm looking for isn't present, or is unclear.
- [X] I have searched for similar issues, and either this question wasn't asked before, or I didn't find any that describe my question.

**Comment by daxgames** [comment]
Did you run cmder.exe as administrator?

**Comment by holahapi** [comment]
yes, I did.

I ran cmder.exe as administrator because some of my scripts require elevated privileges to run. To avoid being prompted by Windows every time I run them, I prefer to run cmder.exe with admin rights. However, for the scripts that don't require admin access, I'd like to run them in non-admin mode.

**Comment by daxgames** [comment]
Then I would suggest running Cmder.exe as a normal user and then a run `cmd::Cmder as Administrator` tab to do administrative tasks in because you can't de-elevate permissions if Cmder.exe is launched with elevated permissions.

**Comment by holahapi** [comment]
Thank you, I think I will just keep running Cmder.exe as a normal user as you suggested.
