### ISSUE TITLE
Question: why i got this message 'color.git.star' already exists

### ISSUE THREAD

**Issue by gostrafx** [cmderdev/cmder#2839]
### Question
![Screenshot.](https://i.ibb.co/Jk3HqQH/Capture.jpg)

C:\*\cmder\vendor\clink-completions\git.lua:17: setting 'color.git.star' already exists
C:\*\cmder\vendor\clink-completions\yarn.lua:86: setting 'color.yarn.module' already exists

### Checklist

- [X] I have read the documentation and made sure what I'm looking for isn't present, or is unclear.
- [X] I have searched for similar issues, and either this question wasn't asked before, or I didn't find any that describe my question.

**Comment by chrisant996** [comment]
Somehow you've got TWO copies of the Lua scripts that are being loaded.

`clink info` lists the locations where it loads scripts from. You've got multiple copies being loaded from multiple places.

**Comment by gostrafx** [comment]
@chrisant996 thank you
the problem is solved

clink uninstallscripts  C:\ProgramData\cmder\vendor\clink-completions
