### ISSUE TITLE
Moved Documents folder, running "ls" gives "ls: My Documents: No such file or directory"

### ISSUE THREAD

**Issue by qndev** [cmderdev/cmder#284]
I moved the location of the Documents folder to save space on my SSD.

When I run `ls` in my home directory, I get `ls: My Documents: No such file or directory`.
Moving the Documents folder back fixes this.

I've also moved the Downloads, Music, Pictures, and Videos folders to my HDD, but only the Documents folder gives this error.

I'm on Windows 8.1.

![cmder](https://cloud.githubusercontent.com/assets/5036244/4528790/220b2ab2-4d72-11e4-82b0-ae2a9e635b39.png)
![lib location](https://cloud.githubusercontent.com/assets/5036244/4528795/25aabcbe-4d72-11e4-866c-a076dbce2b72.png)

**Comment by Jackbennett** [comment]
Hopefully the newer tools included will fix this as we update cmder dependencies.
