### ISSUE TITLE
Question: PsGet should probably no longer be a standard module

### ISSUE THREAD

**Issue by schittli** [cmderdev/cmder#2841]
### Question

Good evening

I'm pretty sure, it's no longer wise to have PsGet embedded in Cmder:

- the PsGet GitHub Project: https://github.com/psget/psget is archived
- Because PsGet is no longer supported, it no longer gets (security) updates
- if you open the PsGet Homepage (listed on the archived GitHub Page): [psget.net](http://psget.net/) you will wonder about the result: 
![image](https://user-images.githubusercontent.com/8282673/232137895-d60d20da-2bae-4f6f-9131-f6750ece04c5.png)

- Commands like `Get-Help <psget command> -Online` opens the 'hijacked' psget.net website

Therefore, I don't think it's wise that Cmder deploys the no longer supported and no longer updated PowerShell module PsGet.

Thanks a lot, kind regards,
Thomas

### Checklist

- [X] I have read the documentation and made sure what I'm looking for isn't present, or is unclear.
- [X] I have searched for similar issues, and either this question wasn't asked before, or I didn't find any that describe my question.

**Comment by DRSDavidSoft** [comment]
CC'ing @cmderdev/trusted-contributors and @cmderdev/core 

If PsGet is not used by the community, we should definitely remove it.

Otherwise we should remove the link to the taken down domain (as the PsGet module's full code is present in the repo).

**Comment by daxgames** [comment]
I'm  all for removing it completely.

**Comment by MartiUK** [comment]
100% should be removed
