### ISSUE TITLE
[Bug] The command ‘node’ was not recognized by wox launch

### ISSUE THREAD

**Issue by lovelyJason** [cmderdev/cmder#2848]
### Version Information

```markdown
Cmder version: 1.3.21
Operating system: windows x64
```

### Cmder Edition

Cmder Full (with Git)

### Description of the issue

Look at this GIF：

![cmder](https://github.com/cmderdev/cmder/assets/50656459/e7c20097-bfd2-4209-a218-3c647fe5dbb9)

I installed the nodejs program.And then I open the cmder.exe program directly, enter the `node -v` command.It can smoothly output node version.

![image](https://github.com/cmderdev/cmder/assets/50656459/e8d7fe62-ef76-44a8-820e-53f3c7ca9e6a)

But If I open the 'cmder.exe' program through 'WOX', enter the enter the `node -v` command.It outputs below
![image](https://github.com/cmderdev/cmder/assets/50656459/a890067d-e276-49c1-9406-73e19a334005)

The above Startup Task is the '{bash::bash}' used.

If I change to '{cmd::Cmder}' task, it still performs so.It cannot recognize the `node` command through the `cmder` that is opened by WOX

### How to reproduce

1.startup task shell: {bash::bash} or any other available
2.start commands(default): 
```shell
-new_console:d:D:\ set "PATH=%ConEmuDir%\..\git-for-windows\usr\bin;%PATH%" & %ConEmuDir%\..\git-for-windows\git-cmd.exe --no-cd --command=%ConEmuBaseDirShort%\conemu-msys2-64.exe "%ConEmuDir%\..\git-for-windows\usr\bin\bash.exe" --login -i
3.open cmder through wox
```

### Checklist

- [X] I have read the documentation.
- [X] I have searched for similar issues and found none that describe my issue.
- [X] I have reproduced the issue on the latest version of Cmder.
- [X] I am certain my issues are not related to ConEmu, Clink, or other third-party tools that Cmder uses.

**Comment by daxgames** [comment]
@lovelyJason what is WOX and did you re-open it after installing node?

How did you install node?

Is node found in a normal windows cmd.exe window?

**Comment by daxgames** [comment]
@lovelyJason what is WOX and did you re-open it after installing node?  Cmder launced from WOX would share the path of WOX so if you have not relaunched WOX or rebooted after installing node WOX would have a path that did not include 'node.exe'

How did you install node?

Is node found in a normal windows cmd.exe window?

**Comment by lovelyJason** [comment]
- WOX is an efficient Windows promoter.Like spotlight on Macbook
- I do not re-open wox after installing node
- I install node by setup program on [https://nodejs.cn/](https://nodejs.cn/).This is a chinese official documentation website.
- there is no `node` command in windows cmd Seemingly

I try to re-open wox.That works!haha.
