### ISSUE TITLE
Question:  How to launch terminal-based programs outside cmder?

### ISSUE THREAD

**Issue by Pandaa-P** [cmderdev/cmder#2853]
### Question

How to launch terminal-based programs outside cmder?
For example  [Helix-Editor](https://github.com/helix-editor/helix) which is a terminal-based modal text editor can run on it's own dedicated terminal/textual window without the need for cmd/powershell or cmder. 

I have some issues when it run inside cmder, and found that when I run it as standalone, it perform far better and without the issues I encountered when it ran inside cmder. 
Issues like text rendering and text selections using the the mouse and some lagging while performing editing.

I'm seeking for some kind of `helix.exe code.py` or just `helix.exe` where execution the command launch `helix.exe` outside cmder terminal.

### Checklist

- [X] I have read the documentation and made sure what I'm looking for isn't present, or is unclear.
- [X] I have searched for similar issues, and either this question wasn't asked before, or I didn't find any that describe my question.

**Comment by daxgames** [comment]
Cmder is not the window but the configuration the Conemu window loads. If you have issues with console apps and display ininconsistencies with ConEmu Cmders terminal emulator report any issues there where it is supported.

As far as running terminal apps outside Conemu I would consult that apps documentation.
