### ISSUE TITLE
Question: How  to increase number of visible lines in cmder?

### ISSUE THREAD

**Issue by Harvey-2021** [cmderdev/cmder#2855]
### Question

how  to increase number of visible lines in cmder?
It has a limited number of lines and I can't see all the returned results

### Checklist

- [X] I have read the documentation and made sure what I'm looking for isn't present, or is unclear.
- [X] I have searched for similar issues, and either this question wasn't asked before, or I didn't find any that describe my question.

**Comment by daxgames** [comment]
Visible lines on a page or scrollback buffer?

You are asking more of a conemu question.  Conemu settings has a search feature try that.  I am not at a computer and do not know the answer off the top of my head.

**Comment by Harvey-2021** [comment]
my mean is scrollback buffer, 
thanks very much, I have found the answer from this site: https://conemu.github.io/en/SettingsSizePos.html
