### ISSUE TITLE
[Feature request] 

### ISSUE THREAD

**Issue by draftman9** [cmderdev/cmder#2868]
### Suggestion

I find the command `rename` installed on linux is much better than the one on win10. So is there any chances that add the linux-version `rename` to replace the one on win10? If so it would be great!

### Checklist

- [X] I have read the documentation and made sure this feature doesn't already exist.
- [X] I have searched for similar issues and found none that describe my feature request.

**Comment by daxgames** [comment]
Cmder's Linux like commands are from Git for Windows which is based on MSYS2.  I looked in the MSYS2 package repo and there is no package called `rename`.

if you could find a `rename.exe` that works like you like you can just copy it to `%cmder_rootZ%\bin`.
