### ISSUE TITLE
Question: How can I use agnoster in cmder?

### ISSUE THREAD

**Issue by moazam1** [cmderdev/cmder#2870]
### Question

Trying to figure out if there is any way to use [agnoster ](https://github.com/agnoster/agnoster-zsh-theme)in cmder? 

### Checklist

- [X] I have read the documentation and made sure what I'm looking for isn't present, or is unclear.
- [X] I have searched for similar issues, and either this question wasn't asked before, or I didn't find any that describe my question.

**Comment by DRSDavidSoft** [comment]
Hi there, I found some great articles which explain how to install ZSH on top of Git for Windows:
(Bear in mind, the full Cmder edition comes with Git, in which case you need to substitute the `C:\Program Files\Git` directory with `[cmder_root]\vendor\git-for-windows`)

- https://medium.com/@leomaurodesenv/setting-up-your-git-bash-zsh-terminals-on-windows-fa94871f440d
- https://dominikrys.com/posts/zsh-in-git-bash-on-windows/
- https://dev.to/equiman/zsh-on-windows-without-wsl-4ah9

Also install **oh-my-zsh** per the guides above, and configure the terminal of your choice to work with Cmder. (You can use the built-in ConEmu terminal in Cmder, or use [WindowsTerminal with Cmder](https://github.com/cmderdev/cmder/wiki/Seamless-Windows-Terminal-Integration) for example).

Then follow the guides below to configure **agnoster** on top of zsh:
- https://inspirnathan.com/posts/22-install-ohmyzsh-with-agnoster-theme/
- https://gabrieltanner.org/blog/customizing-terminal-using-ohmyzsh/

Please note, the guides above doesn't explicitly use Windows as the OS, so package mangers such as `brew` and `apt` are not available on Windows. Use alterative methods to install the required fonts, etc. However, after you enter the `zsh` shell, everything that comes after is identical between Windows and Linux/macOS as mentioned in the above guides.

Good luck, and post your progress here, if you need additional help and/or run into any issues.

**Comment by chrisant996** [comment]
@moazam1 it's unclear what you're asking.

- Are you asking how to run Linux on Windows, so that you can use the zsh shell, so that you can use a specific theme in zsh?
- Are you asking for pointers on how to convert themes from other shells (like zsh) to be usable with Clink with CMD.exe in Cmder?
- Are you asking literally just if the agnoster theme for zsh can be used as-is with things other than zsh?  No, it's designed for zsh.

**Comment by moazam1** [comment]
@DRSDavidSoft Thank you. I will check the above links.

@chrisant996 I am using cmder on windows. It was a long time ago when I installed a plugin (I don't recall the name) and it displayed the git branches like the below screenshot:

![image](https://github.com/cmderdev/cmder/assets/5168122/685479db-05b7-40f3-8ca6-b57295eb24d4)

I no longer have that cmder folder as my system got wiped down so trying to figure out what I used. May be agnoster or similar kind of a plugin?

**Comment by chrisant996** [comment]
@moazam1 Oh, you're looking for an alternative prompt style that can be used with Cmder and uses the Powerline styling that's used agnoster and many other prompt themes.

Probably you used one of these before:
- [Customize Windows Cmder Prompt](https://amreldib.com/blog/CustomizeWindowsCmderPrompt/) (which links to [AmrEldib/cmder-powerline-prompt](https://github.com/AmrEldib/cmder-powerline-prompt)).
- [fredjoseph/cmder-powerline-prompt](https://github.com/fredjoseph/cmder-powerline-prompt), which is an adaptation of AmrEldib's.

I had a fork of that as well, but I abandoned it and instead built this one which has more styles and capabilities and a configuration wizard:
- [clink-flex-prompt](https://github.com/chrisant996/clink-flex-prompt), similar to powerlevel10k for zsh.

Or you could use oh-my-posh or starship, which have various themes available to customize them further:
- [oh-my-posh](https://ohmyposh.dev/), with many [themes](https://ohmyposh.dev/docs/themes), including three inspired by agnoster for zsh (agnoster.minimal, agnoster, and agnosterplus).
- [starship](https://starship.rs/), which is powerful but takes more effort to configure.

**Comment by moazam1** [comment]
@chrisant996 thanks so much for the links. I absolutely love oh-my-posh. Took about 15 minutes to setup in cmder and now my terminal looks awesome!

**Comment by chrisant996** [comment]
This issue can be closed.
