### ISSUE TITLE
[Bug] loss of folder highlighting when calling "ls"

### ISSUE THREAD

**Issue by TNSaturday** [cmderdev/cmder#2873]
### Version Information

```markdown
Cmder version: 1.3.20.151
Operating system: Windows 11 22H2
```

### Cmder Edition

Cmder Full (with Git)

### Description of the issue

Prepend "ls -lah" command with a leading space and the output loses syntax highlighting (i.e. folders being shown in blue):
![image](https://github.com/cmderdev/cmder/assets/27682909/402a712c-df92-42ec-bd77-a780ae739e9d)

### How to reproduce

In any folder press space, then "ls -lah"

### Checklist

- [X] I have read the documentation.
- [X] I have searched for similar issues and found none that describe my issue.
- [X] I have reproduced the issue on the latest version of Cmder.
- [X] I am certain my issues are not related to ConEmu, Clink, or other third-party tools that Cmder uses.

**Comment by daxgames** [comment]
Then don't do that! 😉

**Comment by chrisant996** [comment]
It sounds like your `ls` is really a doskey macro that adds a flag to tell ls what colors to use.

Instead of using a doskey macro, try setting the `LS_COLORS` environment variable with the desired colors.
