### ISSUE TITLE
[Feature request] Ability to move between monitors while in quake-style mode

### ISSUE THREAD

**Issue by adamjoniec** [cmderdev/cmder#2874]
### Suggestion

Ability to move between monitors while in quake-style mode, or If that's impossible (or too difficult to implement) at least hot-key for switching quake-style on/off.

### Use case

Currently when cmder is in quake-mode it's windows can't be moved between monitors (either by mouse, or by Windows shortcut WIN+SHIFT+ARROW LEFT/RIGHT).

So to move cmder window between monitors I need to 
1) go to setting, disable quake-style
2) move cmder window to another monitor
3) enable quake-style from settings

Any improvement to that process would be great.

### Checklist

- [X] I have read the documentation and made sure this feature doesn't already exist.
- [X] I have searched for similar issues and found none that describe my feature request.

**Comment by daxgames** [comment]
This is not a Cmder feature to implement.  Request in the Conemu project on Github
