### ISSUE TITLE
How to enable 256 color?

### ISSUE THREAD

**Issue by jmcbee** [cmderdev/cmder#288]
Hi, very nice project. I love it. The problem I have right now is enabling 256 color support. I have the following startup:

```
-new_console:d:C:\Users\fbm "C:\Program Files (x86)\Git\bin\sh.exe" --login -i
```

Here's what happens when I ran the 256color perl script:

![](https://lh5.googleusercontent.com/-U7Q4Ls1iOAU/VDfBREldJ5I/AAAAAAAABYg/KdM61Rybs10/s0/2014-10-10_19-21-34.png)

**Comment by exhuma** [comment]
The link given above is dead. How do you enable 256 colors?

**Comment by Stanzilla** [comment]
https://conemu.github.io/en/Xterm256Colors.html

**Comment by marrik96** [comment]
I was looking into enabling 256 color from windows 10 when I SSH to linux hosts.  One option I found that seems a lot simpler and cleaner is to add putty as a new task.  You can find steps [here](https://www.thecrumb.com/2013/03/04/configuring-conemu-and-putty/)
