### ISSUE TITLE
[Bug] lost git branch highlighting when there are modified files

### ISSUE THREAD

**Issue by TNSaturday** [cmderdev/cmder#2883]
### Version Information

```markdown
Cmder version: 1.3.20.151
Operating system: Windows 11 22H2
```

### Cmder Edition

Cmder Full (with Git)

### Description of the issue

Previous to todays (October 18) clink update I had nice yellow git branch highlighting, when there are modified files. Now it's gone.

### How to reproduce

1. Create empty folder, run `git init` inside to initialize new git repository.
2. Run `echo something > test.txt` to create a file with come content in it.
3. Run `git add .`, `git commit -m "First commit"` to commit changes.
4. Modify test.txt file.
5. No yellow highlighting of the branch name
6. 

### Additional context

![image](https://github.com/cmderdev/cmder/assets/27682909/81c538b5-7470-4eaf-869e-fc88b664cde1)

1 - pending changes in test.txt
2 - no syntax highlighting

### Checklist

- [X] I have read the documentation.
- [X] I have searched for similar issues and found none that describe my issue.
- [X] I have reproduced the issue on the latest version of Cmder.
- [ ] I am certain my issues are not related to ConEmu, Clink, or other third-party tools that Cmder uses.

**Comment by chrisant996** [comment]
I'll see if I can reproduce this locally.

**Comment by chrisant996** [comment]
I can reproduce the issue.

**Comment by chrisant996** [comment]
This is not a Cmder issue.  It is a Clink bug introduced in v1.5.10.  A fix is coming.

**Comment by chrisant996** [comment]
Clink v1.5.11 has been published with the fix.

This issue can be closed.

**Comment by DRSDavidSoft** [comment]
Thanks for the fix, @chrisant996.

@TNSaturday please upgrade clink in your Cmder again.
