### ISSUE TITLE
[Bug] Multiple WindowSpace entries each time a new process is hooked with cmder

### ISSUE THREAD

**Issue by RaXorX** [cmderdev/cmder#2887]
### Version Information

```markdown
Cmder version: 230724 
Operating system: Windows 11 22631.2361
```

### Cmder Edition

Cmder Full (with Git)

### Description of the issue

![image](https://github.com/cmderdev/cmder/assets/44987810/b7e46e4b-8685-4495-8243-37a75961f945)
Whenever a new window is hooked to cmder, it shows multiple options for the WindowSpaces.
I'd like to disable this if it cannot be fixed per se for the moment. But the menu ends up being a bit too cluttered because of this.

### Checklist

- [X] I have read the documentation.
- [X] I have searched for similar issues and found none that describe my issue.
- [X] I have reproduced the issue on the latest version of Cmder.
- [ ] I am certain my issues are not related to ConEmu, Clink, or other third-party tools that Cmder uses.

**Comment by DRSDavidSoft** [comment]
Dear @RaXorX, this issue is related to the terminal windows, which is **ConEmu** and maintained by @Maximus5. Cmder uses ConEmu as the underlying terminal emulator to display your shells.

Please open a new issue over at the ConEmu repository and close this one, thank you.

**Comment by RaXorX** [comment]
Sorry for that, I used ConEmu for a little while and I didn't particularly see such an option in it, which made me think it was an issue from cmder. Will reopen on ConEmu's repo :)
