### ISSUE TITLE
[Bug] After idling Cmder for a while, ls takes long time to finish

### ISSUE THREAD

**Issue by rsirefelt** [cmderdev/cmder#2888]
### Version Information

```markdown
Cmder version: 1.3.24.236
Operating system: Windows 10
```

### Cmder Edition

Cmder Full (with Git)

### Description of the issue

Setup: Using Cmder in Windows Terminal

- After idling Cmder for a while, running the ls command takes a long time (~10 seconds) to finish
- When ls been run once it is instant afterwards until the terminal been idle again

### How to reproduce

See description

### Checklist

- [X] I have read the documentation.
- [X] I have searched for similar issues and found none that describe my issue.
- [X] I have reproduced the issue on the latest version of Cmder.
- [X] I am certain my issues are not related to ConEmu, Clink, or other third-party tools that Cmder uses.

**Comment by daxgames** [comment]
Cmder is configuration.  Running Cmder's `init.bat` in windows terminal simply sets environment variables and injects Clink to add Readline support.

If there is a bug it's probably not Cmder.

`ls` is from Git for Windows.

I use Cmder daily in Windows Terminal and have never noticed anything like this.

**Comment by rsirefelt** [comment]
Great! Thanks for the answer! Will continue digging in git for windows. Closing issue.
