### ISSUE TITLE
Question: is it possible to auto complete suggestion (grayed out suggestion)

### ISSUE THREAD

**Issue by basprins** [cmderdev/cmder#2893]
### Question

I recently updated to latest cmder and now have a fancy suggestion which often is exactly what I want to type. Is there a way to auto complete the entire suggestion?

![image](https://github.com/cmderdev/cmder/assets/14205998/714cc8e5-5f18-4cc9-8ead-22f74e03ecc9)

I tried to tab but it will complete the current word, but will stop on the first space or until there are more possibilities

### Checklist

- [X] I have read the documentation and made sure what I'm looking for isn't present, or is unclear.
- [X] I have searched for similar issues, and either this question wasn't asked before, or I didn't find any that describe my question.

**Comment by chrisant996** [comment]
Press <kbd>Right</kbd>.

More info [here] (https://chrisant996.github.io/clink/clink.html#features).  The feature is called "Auto-Suggestions".

**Comment by basprins** [comment]
OMG this is reaaaaallly fantastic!! haha so simple, I am in love. Thx!
