### ISSUE TITLE
运行总是提示：“此时不应有 D:\Program。”

### ISSUE THREAD

**Issue by SiaYung** [cmderdev/cmder#2903]
### Question

运行总是提示：“此时不应有 D:\Program。”
![snipaste_20231204_165237](https://github.com/cmderdev/cmder/assets/11502551/7f2e9997-16a7-4477-94e5-0fc0f7e01c12)

### Checklist

- [X] I have read the documentation and made sure what I'm looking for isn't present, or is unclear.
- [X] I have searched for similar issues, and either this question wasn't asked before, or I didn't find any that describe my question.

**Comment by chrisant996** [comment]
Google translator:

Language|Text
---|---
Simplified Chinese:|运行总是提示：“此时不应有 D:\Program。”
English:|Running always prompts: "There should be no D:Program at this point."

**Comment by SiaYung** [comment]
> @SiaYung 您可以在另一个文件夹中重新安装 Cmder 并再次报告吗？
> 
> ✅ C:\apps\Cmder ❌ D:\Program Files\Cmder


我的存放目录直接是  D:\cmder

**Comment by DOSforever** [comment]
这问题现在解决了吗？你有没有在 cmder 的有关启动 CMD 的任何自启动配置文件中写过自定义的 for 执行语句？

**Comment by frankpfan** [comment]
@SiaYung 看起来是因为哪里调用命令行时 D:/Program Files 没有用引号扩起来导致的。

我的 cmder 安装在 D:/Program Files/cmder 下，但没有此问题。大概是你额外的配置导致的问题。
