### ISSUE TITLE
Aliases not recognized + system can't find path specified

### ISSUE THREAD

**Issue by hesammoosapour** [cmderdev/cmder#2910]
### Version Information

```markdown
Cmder version:1.3.24.236
Operating system:Windows 11
```

### Cmder Edition

Cmder Mini

### Description of the issue

1) When I open a new bash console, it throws error, that system can't find path specified!

I deleted the Autorun in here:
Computer\HKEY_CURRENT_USER\Software\Microsoft\Command Processor
I also added CMDER_ROOT for my user and in path as well:

But it still shows the same error!

2)In addition source is not recognized as a command!!

Please tell me how to fix them.🙏

### Additional context

![image](https://github.com/cmderdev/cmder/assets/18083007/2c336f35-9166-44fe-8498-f8ff6653c7e6)

### Checklist

- [X] I have read the documentation.
- [X] I have searched for similar issues and found none that describe my issue.
- [X] I have reproduced the issue on the latest version of Cmder.
- [X] I am certain my issues are not related to ConEmu, Clink, or other third-party tools that Cmder uses.

**Comment by daxgames** [comment]
Th!re ia nit a lot to go on here.  I don't understand the screenshot you provided.  

1. You should remove `%cmder_root%` from the path as it is probably invalid unless you also set that envar to the actual path.

It is not required unless you want it in the path for some reason.

Can you provide a screenshot of the actual  error?

**Comment by daxgames** [comment]
I don't know what that is it looks like you're running something that you created that's throwing an error

**Comment by chrisant996** [comment]
Also, that error is not coming from bash.  But you said your intent was to start bash.  So it looks like something is wrong about your configuration, or about how you're starting bash (you haven't shared any information about _how_ you're trying to start bash, and those details can be very important).

So I wonder:  did you add some bash commands into a cmd startup script by mistake?  Cmd and bash are very different shells, and they can't be treated interchangably.

If you share more specific details about what you're doing, how you're doing it, and what configuration you've performed then that could enable to people to quickly help, without needing to spent a lot of their personal time trying to make guesses and ask questions.  The easier you make it for people to help, the more likely it is that they may try.

Here is an article that helped me learn how to make it easy for people to help me when I need help:
http://www.catb.org/~esr/faqs/smart-questions.html

**Comment by hesammoosapour** [comment]
This is newest version that I downloaded from cmder site.
https://hesammoosapour.ir/cmder.mp4

**Comment by chrisant996** [comment]
Are you using cmder mini?  Or cmder full?

**I think you must be using cmder mini, which does not include bash.**

The {bash::bash} task (and all the bash tasks) only work in cmder full.

Go to Settings > Startup > Tasks > {bash::bash}, and look in the bottom right text box.
It tries to run `%ConEmuDir%\..\git-for-windows\git-cmd.exe`, which only exists in cmder full.
```
set "PATH=%ConEmuDir%\..\git-for-windows\usr\bin;%PATH%" & %ConEmuDir%\..\git-for-windows\git-cmd.exe --no-cd --command=%ConEmuBaseDirShort%\conemu-msys2-64.exe "%ConEmuDir%\..\git-for-windows\usr\bin\bash.exe" --login -i
```

**Comment by daxgames** [comment]
Good catch - I didn't see it either.

**Comment by hesammoosapour** [comment]
This bash config doesn't work:
![image](https://github.com/cmderdev/cmder/assets/18083007/7c155670-adf2-4732-b3e4-c102160ff685)

This is currently the one that I can work with it :
![image](https://github.com/cmderdev/cmder/assets/18083007/1573e343-212e-4802-9624-70034ea8af42)
![image](https://github.com/cmderdev/cmder/assets/18083007/dbef2834-3a87-495b-92b6-7a3d5cb70fe3)

**Comment by hesammoosapour** [comment]
The problem is even when I am working with cmder full, I still get the same error:
![image](https://github.com/cmderdev/cmder/assets/18083007/5e550f6d-ae89-4fb7-8629-8daaa8550de7)

**Comment by hesammoosapour** [comment]
Also it doesn't recognizes commands like : source
![image](https://github.com/cmderdev/cmder/assets/18083007/a3e22181-8c4b-4f02-b477-105052b802fe)

**Comment by daxgames** [comment]
@hesammoosapour The screenshots you have shown of running consoles do not come from the screenshots of the Cmder `bash` tasks you have shown.  The running xonsoles are ALL `cmd.exe`.

The only Task that matches the running Console is the custom one you created and even it is not `bash` it is `cmd.exe` so commands like source would not work since `source` is a `bash` command.

**Comment by daxgames** [comment]
Do you have git installed oitside cmder?  If so how was it installed?  

Output of where git?

**Comment by hesammoosapour** [comment]
I installed the full version again, and now it is working awesomly.

Here are my snippets for my custom bash admin:

>* -cur_console:d:"F:\Old Drive C\xampp\htdocs\StockDesign" -cur_console:t:MainBelfi -cur_console:C:C:\cmder\icons\cmder.ico set "PATH=%ConEmuDir%\..\git-for-windows\usr\bin;%PATH%" & %ConEmuDir%\..\git-for-windows\git-cmd.exe --no-cd --command=%ConEmuBaseDirShort%\conemu-msys2-64.exe "%ConEmuDir%\..\git-for-windows\usr\bin\bash.exe" --login -i

Thanks to everyone specially @daxgames  🤗😍🙏

**Comment by daxgames** [comment]
Glad to hear it.
