### ISSUE TITLE
Question: How to update curl version in Bash console?

### ISSUE THREAD

**Issue by megatux123** [cmderdev/cmder#2922]
### Question

Hello I use Cmder 1.3.24 on Windows 10 Version 21H2 (OS Build 19044.1288)

It happens I have downloaded an updated version 8.6.0 of the curl program from `https://curl.haxx.se/windows` and installed it in a custom directory I included in the Windows OS PATH environment variable

With a CMD Cmder console this updated curl version checks when I use `curl --version` and is used over both the default Windows and Cmder standard curl versions

However my problem is in a BASH Cmder console `curl --version` shows an outdated version `curl 8.1.2` and the command `which curl` prints `/mingw64/bin/curl`

My question is what could be the official and fail-proof way to update the curl program to the last version for a BASH Cmder console ?

### Checklist

- [X] I have read the documentation and made sure what I'm looking for isn't present, or is unclear.
- [X] I have searched for similar issues, and either this question wasn't asked before, or I didn't find any that describe my question.

**Comment by daxgames** [comment]
Put the new `curl.exe` in `%cmder_root%/bin`

**Comment by megatux123** [comment]
This worked thank you I forgot about this option

Also sorry for the late reply but since I am not an advanced user I would like to ask what to do if the program exe has additional folders with libraries and files should I also copy them inside `%cmder_root%/bin` ?

For example the curl program full version download has this folder structure:

├───bin
├───dep
│   ├───brotli
│   ├───cacert
│   ├───libpsl
│   ├───libressl
│   ├───libssh2
│   │   └───docs
│   ├───nghttp2
│   ├───nghttp3
│   ├───ngtcp2
│   ├───zlib
│   └───zstd
├───docs
│   ├───examples
│   └───libcurl
├───include
│   ├───brotli
│   ├───curl
│   ├───nghttp2
│   ├───nghttp3
│   ├───ngtcp2
│   └───openssl
└───lib

with `curl.exe` in its own `bin` subfolder and at the same level what look like some important programming files in the `include` and `lib` folders

Should I copy all these curl folders to `%cmder_root%/bin` even if they will be now a level below curl.exe ?

Thanks again for the help

**Comment by daxgames** [comment]
there is no harm in what you have done but another approach might be to add an alias command to `user-profile.sh` and remove the path modification:

```
alias curl='$CMDER_ROOT/bin/curl/bin/curl'
```

Note: You would need to do the equivalent for other shell types Cmder supports to use this `curl` from `cmd` and `powershell`.

To add a persistent alias in `cmd::cmder` type:

```
alias curl=%CMDER_ROOT%/bin/curl/bin/curl
```

To add a persistent alias in `cmd::powershell` add to `user-profile.psi`:

```
set-alias curl = "$env:CMDER_ROOT/bin/curl/bin/curl
```

Adding aliases is my preferred approach and usually works but may not always work.

Sorry for any mistakes this was typed on my phone.

**Comment by daxgames** [comment]
I edited my last comment after I realized you were only trying to override curl path  in Cmder bash.
