### ISSUE TITLE
[Feature request] Update Clink version chrisant996 / v1.6.8

### ISSUE THREAD

**Issue by mattdkerr** [cmderdev/cmder#2928]
### Suggestion

Upgrade Clink to version chrisant996 / v1.6.8

### Use case

Update for fixes/features, but also to prevent clink update reminders, which don't work properly anyway

### Extra info/examples/attachments

https://github.com/chrisant996/clink

### Checklist

- [X] I have read the documentation and made sure this feature doesn't already exist.
- [X] I have searched for similar issues and found none that describe my feature request.

**Comment by chrisant996** [comment]
@mattdkerr can you share more about "Clink update reminders don't work properly"?  No one has reported anything like that in the Clink repo.  Please include as many details about what happens (or doesn't) and how to reproduce the problem.

**Comment by chrisant996** [comment]
@mattdkerr Can you share details about "Clink update reminders don't work properly"?

With more information, troubleshooting can happen, leading to a solution.

**Comment by mattdkerr** [comment]
I believe the built in clink update command (banner on shell open) installs to a system location instead of where cmder puts it.

**Comment by chrisant996** [comment]
> I believe the built in clink update command (banner on shell open) installs to a system location instead of where cmder puts it.

No:  `clink update` installs to the location of the Clink program files that get executed.

However, if you have also installed Clink separately from Cmder, and have configured Clink for AutoRun, then there's probably an edge case involved:

In that case, BOTH copies of Clink are actively trying to work together.  That would require updating BOTH copies of Clink.

What you should do to fix that complex configuration inter-dependency, is use `clink autorun uninstall`, and then use `clink autorun install` from inside Cmder.  Then the Cmder copy is the one that will always get injected first, and then updating from inside Cmder will work.

It's not exactly a Clink issue, it's more of an issue with how Cmder tries to override Clink using an undocumented debugging switch.

I'll try to think about what could be done about that.  Cmder does not expect you to install a second copy of Clink separately.

**Comment by chrisant996** [comment]
> I believe the built in clink update command (banner on shell open) installs to a system location instead of where cmder puts it.

@mattdkerr in addition to my previous reply, can you please share details about what you do and what goes wrong?  I appreciate the guess you shared, but to get to the bottom of what's really happening, it would help if interesting could be shared about what actually happens.  I can't see it for myself, so I need more information to do troubleshooting.

(And in case it wasn't clear, the reason I'm asking is that I'm the maintainer of Clink, and no one has reported anything that sounds like this before in the Clink repo or Cmder repo.)

**Comment by chrisant996** [comment]
> Please close this out, I'm not sure why it was happening but I can't repro it anymore

@mattdkerr If you run into it again, please open an issue and include (1) the output from `clink info` and (2) the contents from the `clink.log` file (the location of the file is listed in the `clink info` output).  Thanks!
