### ISSUE TITLE
Tab Close on CTRL-W

### ISSUE THREAD

**Issue by Joe1992w** [cmderdev/cmder#293]
Is there a way to remap the keyboard shortcut to close a window in cmder, When using 'Where Is' in nano (CTRL-W) cmder closes the windows as you would expect.

I've tried remapping the nano keyboard shortcut but muscle memory means I continue to accidentally close cmder windows instead of finding what I'm  trying to look for.

Thanks

**Comment by SkyLeach** [comment]
Everyone I've ever introduced to cmder runs into this default setting btw.  The simple fact is that ctrl+key combos are used in almost every console app and that use conflicts with windows interface defaults in most (the vast majority) of cases.

**Comment by Sysa** [comment]
In case someone looking for behavior with removing left forward word, you can assign action `Delete word leftforward to the cursor` to Ctrl+W combination (or LCtrl+W):

![2020-07-08 09_26_49-Settings  xml  ConEmu 191012  64  {Preview}](https://user-images.githubusercontent.com/5188118/86890529-ba1dde80-c0fd-11ea-8ad3-50bf5b551547.png)
