### ISSUE TITLE
Question: 

### ISSUE THREAD

**Issue by DrissBoumlik** [cmderdev/cmder#2960]
### Question
Hello 
I have this alias which worked before
`pamkallmdl=php artisan make:model $1/$2 -m -c -f $t php artisan make:seeder $2sSeeder`
so the Idea is type `pamkallmdl App/Person` to have "App" for $1 and "Person" for $2, but now it seems that $1 takes the whole string "App/Person" ( with the "/" )

### Checklist

- [X] I have read the documentation and made sure what I'm looking for isn't present, or is unclear.
- [X] I have searched for similar issues, and either this question wasn't asked before, or I didn't find any that describe my question.

**Comment by daxgames** [comment]
Args $1 and $2 need to be separated by spaces on the command line else it is $1.

Not sure how it ever worked if it did.

**Comment by DrissBoumlik** [comment]
never mind
my bad, I wasn't focused :/ , i forgot I used to do , `pamkallmdl App Person` no / just a space

**Comment by daxgames** [comment]
No problem, glad you got it working.
