### ISSUE TITLE
Question: Bad performance?

### ISSUE THREAD

**Issue by daze99** [cmderdev/cmder#2961]
### Question

I am not sure if this is a _cmder_, a _conemu_ or a _clink_ issue.

When I run `npm ci` in my project in _cmder_ it takes around 5 minutes to complete. Running the same command in _cmd_ only takes 3 minutes.

Is this a known issue? Is there a way to debug this to find out what is causing the performance loss?

### Checklist

- [X] I have read the documentation and made sure what I'm looking for isn't present, or is unclear.
- [X] I have searched for similar issues, and either this question wasn't asked before, or I didn't find any that describe my question.

**Comment by daxgames** [comment]
You could run `%cmder_root%\vendor\init.bat` in Windows `Cmd.exe` which would take conemu out of the mix.

There's also a way to run in the back that does not load clink but I can't remember what that is right now

**Comment by daze99** [comment]
Running it without _conemu_ solves the issue. I guess I will be using _Windows Terminal_ instead.

**Comment by daxgames** [comment]
we have an unreleased build that includes awindows aterminal and other enhancements.

**Comment by daze99** [comment]
I am really looking forward to that. Keep up the good work. Thanks
