### ISSUE TITLE
Question: how can i list dirictories

### ISSUE THREAD

**Issue by AHeleka** [cmderdev/cmder#2963]
### Question

 how can i list dirictories

### Checklist

- [X] I have read the documentation and made sure what I'm looking for isn't present, or is unclear.
- [X] I have searched for similar issues, and either this question wasn't asked before, or I didn't find any that describe my question.

**Comment by DRSDavidSoft** [comment]
Use the `ls` command. If you have downloaded the `mini` edition, that might not be available so use the `dir` command instead.

This is not the place to ask such questions. All standard Windows commands work in Cmder. And most UNIX/Linux commands work with it too, which includes the `ls` command.

Please read the documentation from external resources. If something doesn't work in Cmder (but works in other terminals) ask away here and we will be happy to help.
