### ISSUE TITLE
Autocomplete and accept suggestions keybinding

### ISSUE THREAD

**Issue by t1a2l** [cmderdev/cmder#2978]
### Question

I want tab to be used to both autocomplete and accept suggestion, the config key for that is nowhere to be found. How can i acheive that? currenlty tab for auto complete and right arrow to accept suggestion.

### Checklist

- [X] I have read the documentation and made sure what I'm looking for isn't present, or is unclear.
- [X] I have searched for similar issues, and either this question wasn't asked before, or I didn't find any that describe my question.

**Comment by DRSDavidSoft** [comment]
Pinging @chrisant996

**Comment by chrisant996** [comment]
Completions and Auto-Suggestions are very different systems.  Combining both of them into a single key means one of them would become unavailable.

[Read here](https://github.com/chrisant996/clink/issues/556) for more information.  There are several similar posts in the Clink forum, and I've tried to explain how and why that isn't possible to do without losing one of the features.  Read [How Completion Works](https://chrisant996.github.io/clink/clink.html#how-completion-works) and [Auto-Suggest](https://chrisant996.github.io/clink/clink.html#gettingstarted_autosuggest) to learn more about how each of the features works.

If you don't want to see the whole-line-auto-suggestions, then turn off that feature by running `clink set autosuggest.enable false`.
