### ISSUE TITLE
Xterm causing blank space in prompt after closing Vim

### ISSUE THREAD

**Issue by rmorrin** [cmderdev/cmder#302]
After editing a file and closing Vim, there is a large amount of 'blank space' between prompts (see screencap).

This doesn't happen with the standard vim configuration provided by msysgit, so I've been through my .vimrc and tracked it down to the `set term=xterm` option. Unfortunately this option seems to be necessary to allow most colour schemes to work correctly.

I'm still relatively new to Vim, so it's quite possible this can be resolved by some other configuration - If someone could point me in the right correction that would be great!

![Vim spacing issue](https://gist.githubusercontent.com/rmorrin/56f5944f23c934a0afb7/raw/55700c3068fd82b9e6da21103f4a9a6cdc7dee0f/Cap.png)

**Comment by Jayflux** [comment]
I have this too
Setting 256 colours didn't help
