### ISSUE TITLE
quotes not properly handled

### ISSUE THREAD

**Issue by gnychis** [cmderdev/cmder#305]
I am having the issue where quotes are not handled very traditionally.  

For example, in a traditional console:

```
$ echo "packages"
packages
```

In Cmder:

```
λ echo 'packages'
'packages'
λ echo "packages"
"packages"
```

This breaks more complex grammar, working in a traditional bash shell:

```
$ git filter-branch -f --index-filter 'git rm -r --cached --ignore-unmatch bin' --prune-empty --tag-name-filter cat -- --all
Rewrite 4b2293f4807bb3008d983d627423fe2b20cfd723 (2/2)
WARNING: Ref 'refs/heads/master' is unchanged
WARNING: Ref 'refs/remotes/origin/master' is unchanged
WARNING: Ref 'refs/remotes/origin/master' is unchanged
```

Failing due to the quotes in Cmder:

```
λ git filter-branch -f --index-filter 'git rm -r --cached --ignore-unmatch bin' --prune-empty --tag-name-filter cat -- --all
fatal: bad revision 'rm'
```

**Comment by NekR** [comment]
> There's another problem with msysgit which could be connected with this. 
git commit -m 'msg' will not work, and git commit -m "msg" will work. This make sense, but git commit -m "msg also works, which is very confusing for me. 

Same for me, very annoying.

**Comment by marcoflorian** [comment]
`echo "Something"  >> file.txt`

Prints at the end of the file:

`"Something"`

Any updates on this?

Is it safe to do it without quotes?

`echo Something  >> file.txt`

Seems to work fine:

`Something`

**Comment by JanSchulz** [comment]
I just tried this with https://github.com/cmderdev/cmder/pull/865 and this is the result:

```
C:\Users\jschulz
λ which bash
C:\Program Files\Git\bin\bash.exe
C:\Program Files\Git\usr\bin\bash.exe

C:\Users\jschulz
λ bash

jschulz@littlebottom MINGW64 ~
$ echo "hallo"
hallo
```

**Comment by mariotacke** [comment]
Just ran into the same issue. I started `bash` first, then ran the command in the shell and it worked.
