### ISSUE TITLE
Problems of context menu

### ISSUE THREAD

**Issue by JokerQyou** [cmderdev/cmder#309]
`Cmder.exe /REGISTER ALL` did work, but I found something unexpected. 
Right click in explorer and select the `Cmder here` menu item, and the Cmder window starts, but it hides itself right after that, so I have to click two more time to open that window.
And also, the `Cmder here` does not work with single instance option I set in the settings dialog. If `single instance` is on and there's already a cmder window, `Cmder here` does nothing but show the existing cmder window.

**Comment by rainyday** [comment]
The /single option does not appear to work in 1.3.0. It just opens a new tab in the same location as the original tab regardless of the path that is passed.

**Comment by Jackbennett** [comment]
@MartiUK I just tried 1.3.2 with `cmder.exe /SINGLE N:` and it just focuses the already open cmder with a new tab and doesn't change to the N drive. For clarity `cmder.exe n:` opened a new tab at n:\

**Comment by Jackbennett** [comment]
I think progress is focused the most in #420
