### ISSUE TITLE
Version update information is broken (not found)

### ISSUE THREAD

**Issue by brunowego** [cmderdev/cmder#310]
When start cmder I get this issue:

![untitled-1](https://cloud.githubusercontent.com/assets/441774/4876187/7494593c-62b9-11e4-9b4b-e7ca29698045.jpg)

Any idea how fix?

**Comment by fernandoPalaciosGit** [comment]
thank you so much, solved disabling the updater process on launch console.
![cmder-settings-bootstrap](https://cloud.githubusercontent.com/assets/4712282/15273223/67e2b0b6-1a92-11e6-9795-f0ff9c588e21.png)
