### ISSUE TITLE
output is ascii,not  UTF-8.

### ISSUE THREAD

**Issue by cnsinger** [cmderdev/cmder#316]
I can not set output is UTF-8,it is ascii.

![qq 20141113154605](https://cloud.githubusercontent.com/assets/6874457/5024885/353e0b34-6b4c-11e4-8ea2-556130461f30.png)

Some ascii code display is garbled.

**Comment by Jackbennett** [comment]
Needs testing again with a new version, I've seen some change mentioning utf8 support but I can't find what commit that was.
