### ISSUE TITLE
Error when using $() function call in another command

### ISSUE THREAD

**Issue by Aphax** [cmderdev/cmder#318]
I'm running that line in cmder so I can get the git archive of changed files only between two trees :
`git archive -o archive.zip HEAD^ $(git diff --name-only HEAD^ HEAD^^)`

But it result in : 
`error: unknown option`name-only'`

cmder thinks the option --name-only is called for the archive command, which is not. I tried in git bash to check if the syntax was right and it works fine, so I guess the problem comes from cmder ;)

**Comment by Jackbennett** [comment]
For future people, The reason that worked is `$()` to powershell means a [subexpression](http://ss64.com/ps/syntax-operators.html), basically "process this repl first and put the output here". Think of it as a whole new powershell.exe for that one line. It's different to `()` which would just run a single statement first like you would using in math equations. 

Just a fancy way of running one command and using that output for the next command with copy/paste or a variable. Which you need when you can't pipe things.

**Comment by yiang231** [comment]
for /f "delims=" %%i in ('git diff --name-only HEAD^ HEAD^^) do call set "DIFF=%%DIFF%% %%i"
git archive --format=zip -o archive.zip HEAD^^ %DIFF%

**Comment by TMODER** [comment]
> for /f "delims=" %%i in ('git diff --name-only HEAD^ HEAD^^) do call set "DIFF=%%DIFF%% %%i" git archive --format=zip -o archive.zip HEAD^^ %DIFF%
There is a ' sign missing, the correct CMD is:
 for /f "delims=" %%i in ('git diff --name-only HEAD^ HEAD^^') do call set "DIFF=%%DIFF%% %%i" git archive --format=zip -o archive.zip HEAD^^ %DIFF%

^-^
