### ISSUE TITLE
monokai colors?

### ISSUE THREAD

**Issue by Maximus5** [cmderdev/cmder#321]
I wonder, where have you taken "Monokai" palette?
I've found only base16 project (which describes many other palettes, also "Solarized"). But its palette does not match bundled with cmder. It has 8 colors and 8 monotones but not 12 colors and 4 monotones.

Here are some links:
http://chriskempson.github.io/base16/#monokai
https://github.com/chriskempson/base16

**Comment by Jackbennett** [comment]
I guess nobody knew :(
