### ISSUE TITLE
How can use (install) sshpass with cmder?

### ISSUE THREAD

**Issue by denisvolokh** [cmderdev/cmder#323]
Hi guys,

How can I use sshpass utility with cmder on windows? 
ssh is working fine but I have plumbub script that requires sshpass to be installed.

Thank you for the great tool.

**Comment by DanielGGordon** [comment]
@MartiUK I don't even see sshpass available on Cygwin

**Comment by MartiUK** [comment]
@DanielGGordon Looks like there is no native binary but it looks like you can compile it in Cygwin.

**Comment by MartiUK** [comment]
Either way it's up to @denisvolokh on how to proceed with his issue.
