### ISSUE TITLE
'awk' is not recognized

### ISSUE THREAD

**Issue by span** [cmderdev/cmder#330]
I saw this issue #23 which mentions that awk is not running. The issue is closed but since awk was not the main concern in the issue it was never treated.

I'm running Windows 7 64-bit and I have the awk binary in `vendor\msysgit\bin\` but when I try to run it in Cmder it is not recognized
```
λ awk
'awk' is not recognized as an internal or external command,
operable program or batch file.
```

I changed the filename to `awk.exe` and got this instead:
```
λ awk
This version of [my path]\vendor\msysgit\bin\awk.exe is not compatible 
with the version of Windows you're running. Check your computer's system 
information to see whether you need a x86 (32-bit) or x64 (64-bit) version of 
the program, and then contact the software publisher.
```
I'm not sure if this is supposed to work or not but I figured I'd post it here if you have any input or for anyone else looking for this.

**Comment by vohof** [comment]
I just added a new startup task with this command instead of an alias:

```
cmd /k "F:\ProgramFiles\CMDer\vendor\msysgit\bin\sh.exe --login" -new_console:d:%USERPROFILE%
```

**Comment by rmorrin** [comment]
@vohof Interesting, what are the benefits of using a startup task over an alias?

**Comment by vohof** [comment]
@rmorrin so I could use all the other msysgit binaries?

**Comment by valueforvalue** [comment]
A simple solution to this issue that works for Vista on up is just to use a symlink.
```
mklink awk.exe gawk.exe
```
Or you could create a batch file named awk.bat with the command:
```
gawk %1
```
Do note that I'm not sure how the arguments are passed as far as spaces go. Wrapping the "%1" in quotes doesn't work. So I think the cleanest solution is just to use a symlink.

**Comment by jasperandrew** [comment]
I just renamed `gawk.exe` to `awk.exe`, and then the `awk` command worked fine. I don't know whether or not that's stable or normal, though...
