### ISSUE TITLE
Registry storage

### ISSUE THREAD

**Issue by lifehome** [cmderdev/cmder#332]
Just wonder if cmder could use the registry as the storage path?
Currently I could only choose the /path/to/cmder/config/ConEmu.xml instead of multiple location, including the registry.

**Comment by Jackbennett** [comment]
Once you run `cmder /register all` to get the shortcuts and have cmder.exe available in your Path there's not much else to install.

>Just popping another question, that the ConEmu is now autorun on windows startsup, instead of Cmder, any idea it happens like this?

There's a conemu setting for this but we don't default it to on.
