### ISSUE TITLE
Exclamation mark cannot be escaped

### ISSUE THREAD

**Issue by borekb** [cmderdev/cmder#333]
I want to run something like:

```
echo "hello!"
```

However, that doesn't work in cmder, the output being:

```
History expansion: echo "hello"C:\Program Files (x86)\...
```

I have tried both

```
echo "hello^!"
echo "hello^^!"
```

but the history expansion still kicks in. How to escape the exclamation mark? Or, ideally, how to disable history expansion for exclamation marks?

**Comment by nhudacin** [comment]
+1 I hate history expansion in cmder.. Please let me know how to turn it off.

**Comment by Glaived** [comment]
I have the same problem with this command:
`browser-sync start --proxy localhost --files "**/*.php, **/*.html, \!**/vendor/**"`

On the *browser-sync* project by @shakyShane

**Comment by Stanzilla** [comment]
Works for me

**Comment by JanSchulz** [comment]
There is also this in `config/settings` (clink settings)

>history_expand_mode	
>The '!' character in an entered line can be interpreted to introduce words from the history. This can be enabled and disable by setting this value to 1 or 0. Values or 2, 3 or 4 will skip any ! character quoted in single, double, or both quotes respectively.

**Comment by VileTouch** [comment]
time for some ancient voodoo:

first, steal a coin from a poor widow

then replace **!** with `Alt+27`[33

then give back the coin to the widow along with another one of the same value from your own pocket.

obviously the coin part is the most important.
