### ISSUE TITLE
Alias with clear

### ISSUE THREAD

**Issue by Sparkdaemon** [cmderdev/cmder#341]
Bug desc:

When trying to create an alias with clear command ( alias cls=clear ) and use it, i get:
"cls isn't recognized as an internal or external command" !

This is not a big bug but.. :p

**Comment by Sparkdaemon** [comment]
Is there a file with aliases are stored?
thanks for your answers :+1:

**Comment by shaunidiot** [comment]
@Sparkdaemon this? https://github.com/bliker/cmder#aliases

**Comment by Sparkdaemon** [comment]
Oh.. *feels stupid* Thanks ^^
