### ISSUE TITLE
alt + backspace (delete word) broken

### ISSUE THREAD

**Issue by Ahtram** [cmderdev/cmder#343]
There's always one (fake) character left on my console when using alt + backspace.
![2014-12-07 14_43_24-cmder](https://cloud.githubusercontent.com/assets/1751201/5331862/46be3da4-7e78-11e4-9400-70987714fbdc.png)
![2014-12-07 14_43_38-cmder](https://cloud.githubusercontent.com/assets/1751201/5331865/482d8690-7e78-11e4-81a4-ca925c6a4a62.png)

**Comment by Peilun0912** [comment]
I have same problem, too. When I use up arrow key, the same bug also happen.

![cmder_bug](https://cloud.githubusercontent.com/assets/4880850/7651608/f7f98ff4-fb34-11e4-8b7c-8b1b8960e95b.gif)

**Comment by simsilver** [comment]
it seems caused by "@prompt xxx$_xxx" in init.bat

**Comment by simsilver** [comment]
or replace {lamb} with $G will works
