### ISSUE TITLE
invalid predicate `' when using find /v "" /c

### ISSUE THREAD

**Issue by ddcgm** [cmderdev/cmder#344]
dir | find /v "" /c
find: invalid predicate `'

find /v "" /c (that's two quote characters) is the same as wc -l in Unix.  It works in ConEmu so I'm not sure if this is a cmder issue or one of the other applications it uses.

**Comment by Jackbennett** [comment]
Cmder 1.3.2, seems a dependency got fixed in all this time.

```cmd
C:\Users\jbennett            
λ dir | wc -l                
29                           
                             
C:\Users\jbennett            
λ dir | find /v "" /c        
29                           
```
