### ISSUE TITLE
Using the context menu doesn't open a new tab in Single Instance Mode

### ISSUE THREAD

**Issue by alexilyaev** [cmderdev/cmder#356]
With `Appearance > Single Instance Mode` checked...
Using `Cmder Here` in the context menu opens correctly for the first time, but when trying again in another folder, it does not add a new tab to Cmder, it just focuses the existing tab.

Unchecking Single Instance Mode works as expected with new windows each time.

This worked ok with `ConEmu Here`.

I guess it's something that has to do with `init.bat` or the default `{cmd}` task, but I couldn't figure it out.

Tested on Win 7 and Win 8.1.

**Comment by 77cc33** [comment]
I have the same issue in quake mode & single instance on windows 7 x64 bit

some fix would be nice

**Comment by ticklemynausea** [comment]
I have the same issue. Could not fix it.

**Comment by stavfx** [comment]
Has anyone found a workaround? really missing this feature...

**Comment by TimNN** [comment]
I'm currently using the following workaround:

Create `workaround.bat` next to `Cmder.exe` with the contents:
```batch
@echo %1 > "%~dp0\CMDER_CD"
@"%~dp0\Cmder.exe" /SINGLE
```

Use `regedit` to edit the registered context menu entry (search for "Cmder") and replace "Cmder.exe" with "workaround.bat" in the entry of the command folder.
![sicpa-net_chl0112383_20150825_095454_tneumann_registry editor](https://cloud.githubusercontent.com/assets/1178249/9461491/67629ea6-4b0f-11e5-81f2-98757d756204.png)

Then add the following to `init.bat` in the `vendor` directory of your cmder installation:
```batch
@if not exist "%CMDER_ROOT%\CMDER_CD" (
    @goto ENDCD
)

@set /p CMDER_CD= < "%CMDER_ROOT%\CMDER_CD"
@del "%CMDER_ROOT%\CMDER_CD"

@cd /d %CMDER_CD%

:ENDCD
```
You'll notice a standard cmd window opening and closing when you "Cmder here" which you could workaround by replacing `workaround.bat` with a vbscript, put for me this is good enough.

Obviously, if you are using powershell, you'll need to port the part added to `init.bat` to you powershell initialization file.

**Comment by WangJi** [comment]
@TimNN 
I tried your way. It works. Thank you for sharing.
I'd wish DevTeam see this and fix it, though.

**Comment by MartiUK** [comment]
@WangJi We know about it, try the latest pre-release

**Comment by MadLittleMods** [comment]
:+1:

This doesn't seem to be working in the latest pre-release for me `v1.2.9` with `Appearance > Single Instance Mode` checked or `/single` parameter in shortcut.

Related to https://github.com/cmderdev/cmder/issues/525 and maybe https://github.com/cmderdev/cmder/issues/197

**Comment by MartiUK** [comment]
Strange, it's working for me...

My target for the shortcut is `[...]\cmder\Cmder.exe /single`

**Comment by TimNN** [comment]
@MadLittleMods I haven't used cmder in a while so I may be wrong, but I think you are misunderstanding something: The single options means that instead of opening a new window, a new tab is opened. This does not change cmder's behaviour of displaying separate previews for each tab, which I think it does anyway.

**Comment by MadLittleMods** [comment]
@TimNN I split out the stacking/preview disabling into a new issue: https://github.com/cmderdev/cmder/issues/758

**Comment by Ydiren** [comment]
I've vhanged the registry entry for "Cmder here" to `"C:\Cmder\Cmder.exe" /single "%V"` and each command prompt opens in a new tab. The only problem is that each tab is opened in the directory of the first tab, no matter which directory I select "Cmder here" in.

**Comment by agibson-fl** [comment]
>With Appearance > Single Instance Mode checked...
>Using Cmder Here in the context menu opens correctly for the first time, but when trying again in another folder, it does not add a new tab to Cmder, it just focuses the existing tab.

I'm having this same problem.

**Comment by MartiUK** [comment]
Working on it: #772

**Comment by Jackbennett** [comment]
@MartiUK  Looks like you've merged and closed things this references are you happy to close his too?

**Comment by MartiUK** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Yeah go for it.

On 25 May 2016 11:36:21 BST, Jack <notifications@github.com> wrote:
>@MartiUK  Looks like you've merged and closed things this references
>are you happy to close his too?
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/cmderdev/cmder/issues/356#issuecomment-221535812

- --
Sent from my Android device with K-9 Mail. Please excuse my brevity.
-----BEGIN PGP SIGNATURE-----

iQE+BAEBCgAoIRxNYXJ0aW4gS2VtcCA8bWFydGluQG1hcnRpbmtlLm1wPgUCV0WA
YAAKCRBxKFXOM3nEdc+DB/9OPqWkQj9g062hNAC5+r6ItADAzFbdZ05W/hUfnrbZ
X1eSRSGH1gYZ1soXIuQDt5aIhbuVXoQFdM6/G3uBTC84mXsHEQPTWLulTK2B9cng
tXNLUfWs/uHP2Woy9vPmwpedc3I/MfGWub8ahFPUUm9EKNhnq18QIfcUm19QAoBI
ufhLvm+Mu2lKSWo4e0A5Rt0ALiNOR9ZhR9GU9P4MgonBidya1YRmUHGkl/8eNahQ
hvGP7nz20nzkCc59wPXG/d5BFhZVZlqAGNaWqGKPfJtJw8EwHkR8UgIbM+/j5MXE
mJABtDIoXTz+gPhiqdjvfAc4WYAf7qZCkEp7a4Ki9MyH
=2O9d
-----END PGP SIGNATURE-----

**Comment by rainyday** [comment]
I don't think this is actually fixed? I'm having the exact same problem on 1.3.0.

**Comment by WangJi** [comment]
@rainyday No, it's not fixed.  Only the first tab can be opened in single instance mode.

**Comment by MrKuja** [comment]
Here my workaround, after registered "ConEmu here" :
  1. Open `regedit`, go to  _HKEY_CLASSES_ROOT > Directory > Background > shell > Cmder here > command_ (I named it "Cmder here" instead of the default "ConEmu here")
  2. Change the entry for `"[Path to Cmder]\Cmder.exe" /SINGLE "%V"`. It will open, at the first call, on the right current directory. However all "Cmder here" calls after will only have the same directory from the first tab, no mater from where you call it (as reported here).
  3. Change the default task in Cmder settings _Startup > Tasks_ to `cmd /U /K "set CMDER_START=%cd% & %ConEmuDir%\..\init.bat" -new_console:n` and check _"Default task for new console"_ setting.

As in the ini.bat, if we defined a _CMDER_START_ environment variable, it will cd on this directory (in where the click happens).
No need to modify files so the update will not replace them.

But this is a workaround, Cmder.exe should be fixed to have consistent behavior.

**Comment by Hugo-KTM** [comment]
I use 1.3.0 as a restricted user and the workaround by @MrKuja does not work for me.
I tried to pass CMDER_START to Cmder.exe via `cmd.exe /s /c set CMDER_START="%V" & Cmder.exe /SINGLE "%V"` but that did not work either.

**Comment by quericy** [comment]
@MrKuja  I use your solution at the version 1.3.1 , but it still only have the same directory from the first tab.

**Comment by Jackbennett** [comment]
rounding up another /single issue onto #420

**Comment by kofifus** [comment]
This is still not working for me,
I tried with both cmder 1.3.2 and by building the github head

- I tick Single instance mode 
- In the registry for Computer\HKEY_CLASSES_ROOT\Directory\Background\shell\Cmder\command I set "C:\cmder\Cmder.exe" /SINGLE "%V"
- I then try a directory right click -> Cmder here
- Also tested from a cmd.exe to do "c:\cmder\Cmder.exe /SINGLE "c:\Temp"

I get a new tab in the (single) window but **it does not** change directory

Any help ?

**Comment by jdhao** [comment]
I have also met this issue. I find that if you use quake-style slide down option, then when you use "cmder here", the new tab will be opened on current window instead of a new one.
![image](https://user-images.githubusercontent.com/16662357/49363419-94a84200-f71c-11e8-933a-9e1a748c98e7.png)

I am using the latest cmder.

**Comment by michidk** [comment]
Still does not work. Settings Quake style slide down to true, also didn't fix the issue.

**Comment by daxgames** [comment]
@michidk have you tried `cmder /register /single`?

**Comment by daxgames** [comment]
@michidk `/register all` does not honor `/single` unless you do `/register all /single` same thing for `/register user /single`.

I wrote this support so I know it worked on my system.  I will need to test it again.

**Comment by M-Younus** [comment]
> I have also met this issue. I find that if you use quake-style slide down option, then when you use "cmder here", the new tab will be opened on current window instead of a new one.
> ![image](https://user-images.githubusercontent.com/16662357/49363419-94a84200-f71c-11e8-933a-9e1a748c98e7.png)
> 
> I am using the latest cmder.

Works like a charm.Thanks man

**Comment by M-Younus** [comment]
> @michidk `/register all` does not honor `/single` unless you do `/register all /single` same thing for `/register user /single`.
> 
> I wrote this support so I know it worked on my system. I will need to test it again.

It works,Thanks.

**Comment by diablov** [comment]
`/register all /single`

works
