### ISSUE TITLE
Set Display location with multiple monitors

### ISSUE THREAD

**Issue by darKpoiSon** [cmderdev/cmder#360]
I have cmder installed on my Laptop, which is hooked up to a Display on my workstation.
I would like to be able to specify, that if the second Screen is connected to display cmder on that screen instead of my main laptop screen.
Would that be possible?

I have set the quake option and no borders so that I only see the console.

EDIT: when I move the Console to the second screen it automatically adjusts the position to -1920, but I can't manually change this setting because it only allows numbers in the input field

**Comment by MartiUK** [comment]
I don't think conemu has the option to open up on a second screen depending on what screens are attached. 

You can set "Auto save window size and position on exit" to true in "Size & Pos" in settings but I don't know what would happen if the window is saved on another screen and you don't have it connected.

**Comment by Maximus5** [comment]
@darKpoiSon You may try switch [-Monitor *id*](https://conemu.github.io/en/ConEmuArgs.html).

@MartiUK Also, It's rather strange that cmder in default config starts **between** monitors if they are small enough, and it do not save changed window position on exit.

**Comment by Stanzilla** [comment]
@Maximus5 uh that sounds bad, is that the `LastMonitor`setting or which one exactly?

**Comment by Maximus5** [comment]
@Stanzilla What do you mean? My note about "between monitors"? Values `ConWnd X` and `ConWnd Y` are way too large to fit desired console size in 1024x768 for example (may be even larger, can't recall now). May be this is not actual, it's look like cmder starts ConEmu maximized nowadays?

**Comment by Stanzilla** [comment]
@Maximus5 yeah that, and I will check the values. It should still start as a window though..

**Comment by Stanzilla** [comment]
We use 
```xml
<value name="ConWnd Width" type="dword" data="0000006f"/>
			<value name="ConWnd Height" type="dword" data="0000001a"/>
			<value name="Cascaded" type="hex" data="01"/>
			<value name="ConWnd X" type="dword" data="000000c5"/>
			<value name="ConWnd Y" type="dword" data="00000089"/>
```
