### ISSUE TITLE
Path ordering issue - wrong find.exe executes by default

### ISSUE THREAD

**Issue by mwagstaff** [cmderdev/cmder#37]
When I try running find, the find.exe from Windows\System32 is executed by default as the msysgit directories are only appended to the end of the path.

In other words, the "C:\Windows\System32" directory appears first in the path, whereas C:\cmder\vendor\msysgit\bin" appears later, towards the end. This means that when I try running the "find" command, I get the old (useless) Windows one, rather than the Unix version I was hoping for.

There are plenty of possible workarounds. In my case, I simply copied the Unix find.exe up to \cmder\vendor\conemu-maximus5\ConEmu, as the ConEmu directories are added to the beginning of the path.

Is there any way that you could add a config option so that the msysgit directory references can be added to the beginning of the path, rather than at the end?

**Comment by BobVul** [comment]
This was reverted by #994 and https://github.com/cmderdev/cmder/commit/2ccc06e63930ece3cf0df1313d48fb2a1847a5b9
