### ISSUE TITLE
No list of command-line options?

### ISSUE THREAD

**Issue by haunma** [cmderdev/cmder#370]
I hate to post such a dumb question as an "issue" but this is the only place I could find to potentially get some help.  I am trying to launch a cmder instance to act as a git bash prompt.  I know what I need to run, and it works fine if I type it in manually after starting cmder, but I cannot, for the life of me, figure out any way to supply a command+args on the cmder command line.  No matter what I try, all I get is an error dialog which says:

Cmder Launcher:  Unrecognized parameter.  Valid options:  /START /REGISTER /UNREGISTER

The main page suggests looking at the Conemu docs, but I cannot find a way to use any of the Conemu command-line switches on the cmder command line.  What am I missing?

(Before someone suggests it, I know there are ways to make cmder always run certain commands at startup.  I don't want that.  I want to create a desktop shortcut for git bash, another for windows command prompt, another for ssh, and so on.)

**Comment by suxonoff** [comment]
https://github.com/bliker/cmder/blob/master/launcher/src/CmderLauncher.cpp#L105

Unfortunately, they are hard-coded in launcher, I don't see any way to provide command-line argument for ConEmu process. This is sad, I want to customize something...

**Comment by haunma** [comment]
Well that is disheartening, for a tool that aims to be the ultimate *command terminal* tool :(

**Comment by blah238** [comment]
I agree, ConEmu has so many powerful command line arguments, for them to not be able to be passed in is a huge letdown.

**Comment by MartiUK** [comment]
Soon :tm:

**Comment by Lizard** [comment]
I would like to see this implemented as well, shame it's not supported yet - shouldn't be too complicated.

**Comment by Muzical84** [comment]
It'd be nice if GitHub had a feature request thing, because those AREN'T really "issues," and users could vote on them.

**Comment by olsonpm** [comment]
@Muzical84 - Most collaborators use the label feature to tag relevant issues as feature requests.  Users typically 'vote' on them by commenting.

**Comment by jolet** [comment]
+vote

**Comment by dbrimley** [comment]
+1

**Comment by Morkowski** [comment]
+1

**Comment by alevitsky** [comment]
+1

**Comment by JimAmuro** [comment]
+1
I hope to choose which task to open for the given directory. I can use ConEmu with arguments to achieve that, but it seems if I use ConEmu arguments for the default {PowerShell} task it just ignores the directory path argument. Hence I think it should be safer to open it with cmder.

**Comment by otravers** [comment]
This would be useful so that commands could be typed directly from a launcher such as Launchy, like illustrated below (obviously, this doesn't actually work right now):

![launchy-cmder](https://cloud.githubusercontent.com/assets/3731532/19493274/5bd29596-9550-11e6-88ae-cca2403438f7.png)

**Comment by thecere** [comment]
This works in my launchy setup. The auto.bat file is indexed with the default launchy mechanisms. The cmder.bat is located next to cmder.exe
![launchy](https://cloud.githubusercontent.com/assets/1588297/20642920/16dffa7e-b41c-11e6-8db0-3492eba0a1a8.png)


auto.bat:
@echo off
C:\apps\cmder\cmder.bat "d:\vls-trunk\env-win64\python27\python.exe -m auto.cli %*"

cmder.bat:
@echo off
set CMDER_ROOT=%~dp0
start %CMDER_ROOT%\vendor\conemu-maximus5\ConEmu.exe /icon "%CMDER_ROOT%\cmder.exe" /single /title Cmder /loadcfgfile "%CMDER_ROOT%\config\ConEmu.xml" /cmd cmd /k "%CMDER_ROOT%\vendor\init.bat cd %CD% && %~1"

**Comment by otravers** [comment]
Hi thecere, thanks for this but this returns "python/No module named auto".  I just installed Python and there's no auto.cli.

**Comment by thecere** [comment]
Hi otravers, forget the python specifics. The stuff in auto.bat is only an example for passing params around.

This one gives me the docker help if called with via launchy "auto > --help"
C:\apps\cmder\Cmder.bat "cmd /k docker %*"

**Comment by otravers** [comment]
Thanks a lot for clarifying, as you've seen I'm easily confused. I've created cli.bat with:

'@echo off
C:\Users\Olivier\OneDrive\PortableApps\Cmder\cmder.bat "%*"'

Now I can do _cli > whatever_ in Launchy, and _whatever_ gets executed in by _cmd.exe_ within Cmder, which is exactly what I was asking for. Thanks again!

**Comment by daxgames** [comment]
Added to Readme.md
