### ISSUE TITLE
Enable 256 colour support over SSH

### ISSUE THREAD

**Issue by rmorrin** [cmderdev/cmder#379]
I'm not sure if this is Cmder specific, but someone else might have solved this problem already.

When I SSH (using the ssh.exe provided by msysgit), I am seemingly unable to get 256 colour support in the terminal:

![cmder](https://cloud.githubusercontent.com/assets/2046187/5973604/48cdb106-a862-11e4-81ce-ec9bc7381dbc.png)

I'm fairly certain it's not a configuration problem, as running the same test-script in putty works without issue:

![putty](https://cloud.githubusercontent.com/assets/2046187/5973645/c099014a-a862-11e4-8cdd-34fd36fd565e.png)

Is this simply a limitation of the SSH client, or is there some workaround available?

Thanks!

**Comment by willemdh** [comment]
Hey,

I'm experiencing exact the same issue. 256 colors are not supported it seems by Cmder. I have a tool to display server information, which makes use of 256 color codes, which works perfectly when using mRemoteNG, Putty or Linux terminals, but not when I'm using Cmder.

This is the tool:
https://github.com/willemdh/generate_motd

It's made for CentOS. 

When i SSH to a server with this tool, every 256 color code formed like this \e[38;5;39m does not work and only outputs in grey.

Any advice to enable 256 color support in Cmder is welcome.

Thanks;

Willem

**Comment by teleivo** [comment]
Hello!

is there somebody who got this working? If so, it would be great if you could share your solution :)

Thanks a lot
ivo

**Comment by kthakore** [comment]
I am still having this issue.

**Comment by teleivo** [comment]
it would be extremely nice if someone who got this figured would share how he did it. thanks!!

**Comment by willemdh** [comment]
I have spent hours looking for a solution but didn't find any.

**Comment by Stanzilla** [comment]
You could use https://conemu.github.io/en/CygwinMsysConnector.html

**Comment by daxgames** [comment]
or you could use a mintty session in the development branch

**Comment by willemdh** [comment]
Yes but it would be nice if this became possible someday in Cmder

**Comment by Stanzilla** [comment]
We just gave you two ways it is possible in Cmder..

**Comment by daxgames** [comment]
Mintty is already a part of cmder in the development branch.

**Comment by daxgames** [comment]
@rmorrin it is not a limitation of ssh, rather it is because the Windows console so I that cmder uses for cmd and PowerShell shells is limited to 16 colors.  

As I said in earlier responses the development branch uses a newer Git for Windows that includes the xterm-256 capable mintty.   This in itself creates other issues.  See development branch readme.md where all of this is explained for more.

**Comment by willemdh** [comment]
Sorry misread. Confirmed to work perfectly with 256 colors in the development branch. Awesome! Now I can finally make a 256 color version of my generate_motd.sh script. THANKS a lot. :+1: 
This can be closed now I suppose.

**Comment by daxgames** [comment]
Output of 'echo $TERM'

**Comment by willemdh** [comment]
➜  generate_motd git:(master) ✗ echo $TERM
cygwin

**Comment by daxgames** [comment]
At you in a mintty session?  If so type 'export TERM=xterm-256color' and try again.

**Comment by willemdh** [comment]
@daxgames Thanks for the suggestion and sry for the late answer. I tried typing 'export TERM=xterm-256color', but it didn't help.

    echo $TERM
    cygwin
    export TERM=xterm-256color
    echo $TERM
    xterm-256color

Let me know if I'm doing something wrong or if you have any more suggestions.

**Comment by daxgames** [comment]
Then I am guessing you are not in a mintty session in under.  What are you choosing from the tasks menu to launch your session.  If cmder, powershell, or bash these do not support w56 color.  Note mintty sessions are only available in cmder development branch at this time so if you are running released cmder 1.2 you will not find it.

You can add Babun to released cmder tasks and it will use mintty and should work with 256 colors.

**Comment by DanielGGordon** [comment]
Cmder with Babun seems to work pretty well.

**Comment by willemdh** [comment]
When I go to setting, then Main, Update, and then click apply & check, I get "Your current ConEmu version is 151210 alpha. How can I find version of Cmder? I downloaded from GitHub, unzipped to 'cmder-development' and I'm running it from there with cmder.bat. 
I can see 'mintty' and 'mintty as admin' as a submenu from Bash. But when I open, I get:
```
The system cannot find the path specified.                                                                     
                                                                                                               
                                                                                                               
Current directory:                                                                                             
C:\Users\Willem                                                                                                
                                                                                                               
Command to be executed:                                                                                        
"C:\WINDOWS\system32\cmd.exe" /C C:\Users\Willem\Dropbox\Utilities\cmder-development\vendor\conemu-maximus5\..\
git-for-windows\usr\bin\mintty.exe /bin/bash -l                                                                
                                                                                                               
                                                                                                               
ConEmuC: Root process was alive less than 10 sec, ExitCode=1.                                                  
Press Enter or Esc to close console...                                                                         
```

When I look for mintty I can't find it "C:\Users\Willem\Dropbox\Utilities\cmder-development\vendor\conemu-maximus5" so I guess I'll have to install it over there? The path is truncated  however. I downloaded 1.1.3-cygwin17 Where should I put the mintty.exe?

**Comment by willemdh** [comment]
Ok managed to get it working in the dev version with link to Babun which was installed in my homedirectory. Thanks @daxgames @DanielGGordon for the help.

**Comment by daxgames** [comment]
@willemdh  Glad you got it working.  When you do an update via the ConEmu GUI you are updating the ConEmu portion of Cmder.

The error you posted above looks like you downloaded the Cmder source zip and not a Cmder distribution zip.  The difference being the distribution zip includes '[cmder_root]\vendor\conemu-maximus5\..\git-for-windows\usr\bin\mintty.exe" plus all the other bits Cmder requires but the source zip does not.

if you open a Powershell prompt outside Cmder and chenge to 'C:\Users\Willem\Dropbox\Utilities\cmder-development\scripts' and type '.\build.ps1 --verbose' it will download all the components missing from the source distribution.  This will fix 'mintty' from the Cmder tasks menu throwing the error and you will not need to add Babun to Cmder defeating one of the major features of Cmder, portability.

**Comment by DanielGGordon** [comment]
Yea Babun is too large to be portable, but it's a lot smaller and simpler than Cygwin. I like having both Cmder as a portable, and if the machine I have is using Babun, then I can use that with Cmder. I like Zsh a lot, which is not an option with cmd or Git Bash

**Comment by Daniel15** [comment]
I just tried out the msys connector mentioned earlier in this issue (https://conemu.github.io/en/CygwinMsysConnector.html). This appears to work fine for bash, but not for SSH. Using SSH results in what appears to be 16-colour mode:

![](http://ss.dan.cx/2016/04/ConEmu_25-18.26.10.png)

Without the connector, I get the output as shown by @rmorrin, so the connector is definitely doing *something*:
![](http://ss.dan.cx/2016/04/ConEmu_25-18.27.35.png)

I'm using ssh.exe bundled with Git for Windows.

**Comment by Daniel15** [comment]
Ah, I missed this part of the ConEmu docs:

> You need to ensure that buffer/scrolling is Off

You need to add `-cur_console:h0` to your task to disable buffering/scrolling in order for 256 colours to work.  ¯\\\_(ツ)\_/¯

![](http://ss.dan.cx/2016/04/ConEmu_25-21.06.50.png)

**Comment by rmorrin** [comment]
@Daniel15 Just to confirm, in your previous screenshots are you using bash (Git for Windows) as your shell?

**Comment by AugusDogus** [comment]
For those wondering, if you'd like to use the msys connector and have a default installation as I do the startup task is the following.

`set CHERE_INVOKING=1 & set "PATH=%ConEmuDir%\..\git-for-windows\usr\bin;%PATH%" & %ConEmuDir%\..\conemu-maximus5\ConEmu\conemu-msys2-64 %ConEmuDir%\..\git-for-windows\bin\bash --login -i`

This is for without scrolling. I notice that most of my colors now "work", but are inaccurate. That's good enough for me as I'd prefer to keep scrolling rather than give it up and have accurate colors. 

However, if you would like to make this compromise, one must simply add `-cur_console:h0` as @Daniel15 mentioned. 

`set CHERE_INVOKING=1 & set "PATH=%ConEmuDir%\..\git-for-windows\usr\bin;%PATH%" & %ConEmuDir%\..\conemu-maximus5\ConEmu\conemu-msys2-64 %ConEmuDir%\..\git-for-windows\bin\bash --login -i`

![image](https://user-images.githubusercontent.com/9794679/67131741-7976e180-f1cb-11e9-8e8b-21d5d7f41d93.png)
