### ISSUE TITLE
Complete aliases on tab

### ISSUE THREAD

**Issue by chodorowicz** [cmderdev/cmder#38]
I'd be great if `tab` would autocomplete aliases.

**Comment by vladimir-kotikov** [comment]
This can be resolved by setting clink's `exec_match_style` option default value to 1 or 2.
This relates to https://github.com/bliker/cmder/issues/280 and https://github.com/bliker/cmder/issues/218

**Comment by MartiUK** [comment]
This has been fixed since aa9cb38
