### ISSUE TITLE
extra character appears at the beginning,when used the arrow keys(up,down) navigate through the history 

### ISSUE THREAD

**Issue by xiaoyifang** [cmderdev/cmder#384]
extra character appears at the beginning of the command ,when used the arrow keys(up,down) to navigate through the history 

![image](https://cloud.githubusercontent.com/assets/105986/6033236/3cba43b2-ac4e-11e4-9ac8-6769e0fcd98d.png)

**Comment by lognbow** [comment]
I have the same issue. I guess this perhaps relates to the chinese character support when monoscope is disabled.

**Comment by Stanzilla** [comment]
Closing in favor of https://github.com/cmderdev/cmder/issues/553 which has more info
