### ISSUE TITLE
ConEmu auto attach with Cmder aliases

### ISSUE THREAD

**Issue by vitalybe** [cmderdev/cmder#388]
I've set Cmder (ConEmu) to auto-attach to new CMD processes and bring them into ConEmu main UI. That works great.

However, the opened cmd doesn't run the `init.bat` of cmder and thus I don't have any aliases, prompt, etc.

How can I make ConEmu auto run `init.bat` when auto-attaching opened prompts?

**Comment by Maximus5** [comment]
Why not to run ConEmu.exe instead of cmd.exe?

Anyway, ConEmu settings page ComSpec shows registry key where you may specify command that will be run on any cmd.exe console.

**Comment by rossipedia** [comment]
:+1: @Maximus5 thanks so much, was banging my head against this for hours this morning.
