### ISSUE TITLE
git-p4.py [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by rparolin** [cmderdev/cmder#392]
λ git p4
e:\install\python2.7\python.exe: can't open file 'C:/portable/cmder/vendor/msysgit/libexec/git-core/git-p4.py': [Errno 2] No such file or directory

---
The error is the drive where it is looking for git-p4.py.  My instance of cmder is actually installed to E:/portable/...

**Comment by MartiUK** [comment]
what happens when you run ```git-p4```?

**Comment by rparolin** [comment]
λ git-p4
'git-p4' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Jackbennett** [comment]
Just adding some test cases I did;
My clone of bliker:master is at `N:\cmder` with a full vendor build (i.e. includes msysgit)

```
C:\Users\jbennett
λ %CMDER_ROOT%
'N:\cmder' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\jbennett
λ git p4
fatal: git was built without support for git-core\git-p4 (NO_PYTHON=YesPlease).

C:\Users\jbennett
λ git-p4
'git-p4' is not recognized as an internal or external command,
operable program or batch file.
```

With deleting `/vendor/msysgit` to use my locally system installed msysgit;
```
C:\Users\jbennett.BHS.000
λ git p4
basename: too many arguments
Try `basename --help' for more information.
fatal: git was built without support for  (NO_PYTHON=YesPlease).
```
