### ISSUE TITLE
cant change start directory

### ISSUE THREAD

**Issue by hugomrdias** [cmderdev/cmder#4]
if i change the startup directory in the conemu settings the colors, hotkey etc stop working. 
im changing the {cmd} task.

and if i hit CTRL+T and change the startup directory the same happens. It shows a msg "The system cannot find the path specified".

**Comment by thebillkidy** [comment]
Maybe a bit late, but you can just set the CMDER_START environment variable to change the starting directory: "set CMDER_START=E:\Projects"
