### ISSUE TITLE
[question] encoding and supporting multi-lang

### ISSUE THREAD

**Issue by Guhnguk** [cmderdev/cmder#409]
this program is fancy and i'm falling lovin it. but I am struggling because of the Korean language. is there a supporting multi-language functionality or how to configure.

Show me!

**Comment by trapatsas** [comment]
Same issue here. I have a system with Windows 8.1 and Greek Display Language.

**Comment by vladimir-kotikov** [comment]
Try to play with font settings, especially 'Font charset'. Probably this could help.

![image](https://cloud.githubusercontent.com/assets/3857604/6523534/d4862876-c401-11e4-989e-2937ed13d15c.png)

Also there is a `CHCP` command which could help you to set up your console charset as well (try `CHCP 65001` to set up a Unicode code page)
