### ISSUE TITLE
~ alias home directory

### ISSUE THREAD

**Issue by Walther** [cmderdev/cmder#41]
It would be nice to have `~` to complete to home directory, in a similar fashion as in (most) Linux terminals. For example `cd ~`, `mv foo ~/bar/`, etc.

**Comment by mehdilamaaffar** [comment]
use this is work ** cd %home% **

**Comment by babhishek21** [comment]
The best way right now (without the possibility of breaking stuff) is to use this alias:
```
cd~= cd %homepath%
```
You could also use __%USERPROFILE%__ instead to get your own directory in case of multiple users.

**Comment by sergeyfarin** [comment]
PyCmd can do this.
![image](https://cloud.githubusercontent.com/assets/1467219/8450461/6ddd0d98-1fdb-11e5-8179-047dc285b6d9.png)

**Comment by MartiUK** [comment]
As per the initial request, this will never happen, unless `cmd` is open sourced (good luck) and the expansion rules changed. The recommended workaround is to stop using `cmd` and use `powershell`.

**Comment by wingy3181** [comment]
Bit old now..but I added `cd~=cd %HOME%$*`
At least so I can go `cd~ \Documents`

**Comment by dustinmichels** [comment]
> The best way right now (without the possibility of breaking stuff) is to use this alias:
> 
> ```
> cd~=cd %homepath%
> ```
> You could also use **%USERPROFILE%** instead to get your own directory in case of multiple users.

where are you entering this?

**Comment by peteraldous** [comment]
I was thrilled to find a sensible terminal emulator for WSL use. However, the ~ issue is still present. Interestingly, WSL's bash seems to use ~ just fine; e.g., `pushd ~`. On the other hand, gvim (I have a script in /usr/local/bin that launches the Windows-installed gvim executable) seems to think that %CMDER_HOME%\vonemu-maximus5\ConEmu\home\<username> is my home directory. As a result, it ignores my .gvimrc, can't see my spelling directory, and so on.

**Comment by peteraldous** [comment]
I was able to resolve my issue by adding

set HOME=C:\Users\<username>
set CMDER_START=C:\Users\<username>

to my startup environment. It's a little brittle but should work fine.
