### ISSUE TITLE
resize window not filled with content

### ISSUE THREAD

**Issue by tkmaxx** [cmderdev/cmder#413]
Apologies if this is not the right place to post this. If so, please direct me.

I'm starting vim in cmder. After I resize window, vim stays the same size as original window. Screen shots attached.
![before](https://cloud.githubusercontent.com/assets/10572546/6416101/7ce84bbe-be9b-11e4-9371-83561539ded4.png)
![after](https://cloud.githubusercontent.com/assets/10572546/6416103/81604bf6-be9b-11e4-84e5-817261d498bf.png)

**Comment by JorenJoestar** [comment]
Hey there!
Just make sure that in your Cmder options, under "Main->Size & Pos" the option "Auto size" is OFF.
If it's on ti will try to have the same number of console cells even if you resize the window, stretching in all possible ways.

**Comment by steph-ben** [comment]
I got the same issue, and I really don't understand how to fix it ?

As a quickfix, pressing ```CTRL+g``` on vim seems to resize

**Comment by daxgames** [comment]
Pressing enter also resizes vim.  Closing.
