### ISSUE TITLE
Vim help not working in cmder

### ISSUE THREAD

**Issue by z3t0** [cmderdev/cmder#415]
I can't access vim help texts from 'cmder' as cmd.exe.
Using it as powershell is not a problem, also using conemu directly doesn't cause any problems.
Basically it looks in the wrong place when using cmder. (check screenshot)

![image](https://cloud.githubusercontent.com/assets/9000061/6425084/141d405c-bedd-11e4-877f-c70f6f860f6f.png)

**Comment by z3t0** [comment]
**Workaround: for now I have set Cmder to use powershell instead of cmd as default and that works for me**

However this may be an easy fix so I'll leave the issue up here.

**Comment by gleenk** [comment]
How did you do this? (changing to Powershell)

**Comment by bahagiga** [comment]
@gleenk if are you asking how to change the default startup to Powershell, then you should be able to do that in Settings > Startup > Specified named task.

**Comment by z3t0** [comment]
powershell.exe from a cmd will work
