### ISSUE TITLE
Create files from cmder.

### ISSUE THREAD

**Issue by sunyoureyes** [cmderdev/cmder#417]
Can anyone help me, how can i create files from cmder? I want something like in Ubuntu terminal "toucn style.css" . 
Thank you, anywhere.

**Comment by Jackbennett** [comment]
If you've in powershell `new-item -type file exampleName`.
In cmd `type NUL > file.txt`.

I think in the dev build you can make an alias with spaces in so in the next release you can do `alias touch="type NUL > %1"`

**Comment by Jackbennett** [comment]
And if you are using powershell, put this in you file at $profile
```
function touch{
    Param(
        [Parameter(Mandatory=$true)]
        [string]$name
    )
    if(-not (test-path $name)){
        new-item -type file $name -force
    } else {
        Write-Warning "$name exists"
    }
}
```

We're working on making this like this much nicer.

**Comment by RyannosaurusRex** [comment]
Just using regular `touch test.txt` actually works for me and creates an empty file.  Is that what you're wanting?

**Comment by sunyoureyes** [comment]
Hmm. Now it works for me too) Something strange )

**Comment by SOSANA** [comment]
Hey all,

I recently did an update and now this touch option doesn't work anymore....anyone else having this issue?

**Comment by Aarchi-Ayoub** [comment]
npm install touch-cli -g
