### ISSUE TITLE
ssh keepalive

### ISSUE THREAD

**Issue by urza** [cmderdev/cmder#418]
Hi,
I instaled cmder (full, including unix tools) and I am using it as ssh client instead of putty (looks much better). I simply open cmder and write "ssh myserver" and log in.
However, in Putty I can set "keepalive" to keep mu connection active even when I dont send any commands for a while. Is there some way to do this in cmder and ssh command?
Thanks

**Comment by MartiUK** [comment]
The following will tell your ssh to send NOOP packets to the server, keeping any routers in-between thinking that you are still using the connection and keeping it open.

_All Hosts_

Add the following lines to the %HOME%/.ssh/config file (create if it doesn’t exist)

```
Host *
    ServerAliveInterval 60
```

Make sure you indent the second line.

_Per-Host_

If you only want to enable keep alive for a single server, you can add that into the %HOME%/.ssh/config file with the following syntax:

```
Host *hostname.com
   # ServerAliveInterval 60
```

**Comment by noelpuru** [comment]
It works for me if I use ``{bash::bash}`` instead of ``{cmd::Cmder}``.
