### ISSUE TITLE
Include Scoop as package manager

### ISSUE THREAD

**Issue by samvasko** [cmderdev/cmder#42]
[Scoop package manager](https://github.com/lukesampson/scoop) could be a great addition to **Cmder**. 
I really like the spirit of portability.

**Comment by DRSDavidSoft** [comment]
For future visitors: package-manager support is now coordinated centrally for the community.

Scoop has community manifests for `cmder` and `cmder-full` in `ScoopInstaller/Main`, and they point to official Cmder release assets. WinGet is not available yet, and Chocolatey packages exist but are not currently owned by `cmderdev`.

Master package-manager tracker: https://github.com/cmderdev/cmder/issues/3094
Wiki status page: https://github.com/cmderdev/cmder/wiki/Package-Manager-Status
