### ISSUE TITLE
Single mode does not set current directory

### ISSUE THREAD

**Issue by DoCode** [cmderdev/cmder#420]
When open cmder([cmder launcher exe](https://github.com/bliker/cmder/blob/development/launcher/src/CmderLauncher.cpp#L115) from development branch) in single mode from explorer context menu,
the `CMDER_START` environment variable is not overwritten when the second tab is started.

**Comment by MartiUK** [comment]
Just to be sure, are you running an exe you compiled yourself or the one included in the repo?

**Comment by DoCode** [comment]
I am running an self compiled exe from the current development branch who has the `/single` cli-switch.

**Comment by rainyday** [comment]
1.3.2 release notes claim this  issue was fixed but that does not appear to be the case. running `cmder /single C:\path` still does not set the path correctly in the new tab

**Comment by DoCode** [comment]
I don't know why me PR that resolve this issues with `/single` and `Cmder startup directory` is gone!?  
See it [here](https://github.com/cmderdev/cmder/pull/673).

**Comment by Stanzilla** [comment]
@DoCode that is weird? It shows in the history? https://github.com/cmderdev/cmder/commits/master/launcher/src/CmderLauncher.cpp

**Comment by Stanzilla** [comment]
no idea what happened, sorry :( Maybe @daxgames @MartiUK know. 

Care to redo the PR then?

**Comment by Starli0n** [comment]
I am facing the same issue here but only when I had launched an instance of Cmder before.

If I execute `Cmder.exe /SINGLE D:\` when there is no `Cmder` launched, it works and it will work it I run again this command.

However, if I had launched `Cmder` manually before the same command would not work and the default path would be my user path.

I tweaked the options of `Running As Admin` and tried all kind of combinations but I did not figure out how to solve the issue.

I do not know whether those issues are linked.

**Comment by DoCode** [comment]
@Starli0n please try my [PR](https://github.com/cmderdev/cmder/commit/a57c11e171f97eb8cc6a10b61053731d2940316a). This worked for me since Sep 4, 2015!

**Comment by DoCode** [comment]
@Stanzilla, how can we close this issue for all times? I use my [PR](https://github.com/cmderdev/cmder/commit/a57c11e171f97eb8cc6a10b61053731d2940316a) since Sep 4, 2015 and it works like a Charme with all updates from ConEmu...

**Comment by Starli0n** [comment]
@DoCode Thanks you, that's nice but I do not intend to compile my own version of Cmder (at least for now)

So please integrate his PR

**Comment by Starli0n** [comment]
For now, I use this walkaround:

**Terminal.cmd** _path_
```batch
@echo off

set ConEmuExe=ConEmu64.exe

rem Check if Cmder is already launched
tasklist /FI "IMAGENAME eq %ConEmuExe%" 2>NUL | C:\Windows\System32\find.exe /I /N "%ConEmuExe%">NUL
if "%ERRORLEVEL%"=="0" goto NEW_TAB

:OPEN_CMDER
%CMDER_ROOT%\Cmder.exe /SINGLE %~1
goto :EOF

:NEW_TAB
start %CMDER_ROOT%\vendor\conemu-maximus5\%ConEmuExe% /title Cmder /cmd cmd /k "%CMDER_ROOT%\vendor\init.bat && cd /d %~1"
```

But I do not have the right icon when I open a new tab.

It is really annoying.

**Comment by Stanzilla** [comment]
@DoCode like I said, please re-do the PR and it will get merged

**Comment by inwardmovement** [comment]
I have this issue too... when will it be fixed ?

**Comment by daxgames** [comment]
Fixed in current release
