### ISSUE TITLE
How to disable all shortcuts?

### ISSUE THREAD

**Issue by junkdog** [cmderdev/cmder#452]
Is it possible to disable all predefined shortcuts? I know I can individually unset each one - but it appears I have to do it on a per shortcut basis.

**Comment by Arrow7000** [comment]
You're a step ahead of me. How do you disable all shortcuts?

**Comment by junkdog** [comment]
Sorry, don't recall how, I only did a short detour into windows land because of a project.

**Comment by DonBeo** [comment]
Is there any update about this?
