### ISSUE TITLE
tmux in cygwin - open terminal failed: not a terminal

### ISSUE THREAD

**Issue by junkdog** [cmderdev/cmder#453]
It appears other have managed to get tmux working in cmder before (#56), but when I run it, I get

```
adrian@demonbook ~
$ echo $TERM
cygwin

adrian@demonbook ~
$ tmux
open terminal failed: not a terminal

adrian@demonbook ~
$ TERM=xterm tmux
open terminal failed: not a terminal
```

Is there a work-around to coax tmux into being happy again? As for cygwin, I followed the instructions on the [wiki](https://github.com/bliker/cmder/wiki/Integrating-Cygwin)

**Comment by kostrse** [comment]
Having the same problem.

**Comment by shkm** [comment]
+1

**Comment by MartiUK** [comment]
tmux doesn't exactly work in conemu, when using this method. Tmux is a bit finnicky with what terminal it wants, especially if it's on a non-Unix system.

Try setting up a new task except have it run
 ```C:\cygwin64\bin\mintty.exe -i /Cygwin-Terminal.ico -``` (If you installed it in the default location)

Where it should work.

If you don't want to do that, may I suggest GNU Screen?
