### ISSUE TITLE
PATH environment variable has space problem

### ISSUE THREAD

**Issue by deluxghost** [cmderdev/cmder#456]
at file "vendor\init.bat": line 32:
@set PATH=%CMDER_ROOT%\bin;%git_install_root%\bin;%git_install_root%\mingw\bin;%git_install_root%\cmd;%git_install_root%\share\vim\vim74;%CMDER_ROOT%;%PATH%

if my %PATH% has a space, this may cause some problem.
i think that is better:

@set "PATH=%CMDER_ROOT%\bin;%git_install_root%\bin;%git_install_root%\mingw\bin;%git_install_root%\cmd;%git_install_root%\share\vim\vim74;%CMDER_ROOT%;%PATH%"

the first quote is before "PATH=".

**Comment by MartiUK** [comment]
This should be fixed in the development branch.
