### ISSUE TITLE
Slide up doesn't restore focus

### ISSUE THREAD

**Issue by nilfric** [cmderdev/cmder#459]
1. App A has focus
2. Display and hide cmder using the slide down functionality
3. App A does not regain the focus

**Comment by Jackbennett** [comment]
I've been watching this issue open with conemu for ages. It's a strange behaviour of a combination of settings. My current laptop isn't doing what you describe but I've had it in the past.

[See](https://code.google.com/p/conemu-maximus5/issues/detail?id=1042) for some discussion.

The quickest work around i've found is to disable quake mode from the settings in conemu. But I have quakemode on and this doesn't happen so it's a bit odd.

**Comment by dw9** [comment]
Thanks, it works with quake mode set to off for me too. Btw. I'm using Windows 7.
