### ISSUE TITLE
unicode gets garbled

### ISSUE THREAD

**Issue by Pomax** [cmderdev/cmder#467]
A quick check on unicode support suggests cmder is making assumptions about glyph sizes in text that is not ASCII:

![screenshot 120](https://cloud.githubusercontent.com/assets/177243/7446666/3014c6b4-f195-11e4-8e3a-15d999b112cb.png)

The file in question is called 日本語.txt, but it looks like the CJK ideographs are assumed to be the same width as the monospace ASCII characters.

**Comment by afffsdd** [comment]
maybe because of conemus extended graphics thing

**Comment by MartiUK** [comment]
Try unchecking monospace see here https://github.com/bliker/cmder/issues/45

**Comment by Pomax** [comment]
that's more of a workaround instead of a real fix: the Japanese text (as well as the Chinese text in #45) *is monospaced*. It's just monospaced to a quad size twice that of ASCII, so with monospace on, this should definitely render properly. The fact that turning it off makes thing work means there's a good place for the maintainers to jump in and figure out how to solve the problem of the text rendering incorrectly.
