### ISSUE TITLE
Vim syntax highlighting doesn't work in cmder_full but in cmder_mini

### ISSUE THREAD

**Issue by s4wny** [cmderdev/cmder#468]
Vim syntax highlighting doesn't work in cmder_full but in cmder_mini (I'm using the latest version of cmder).

Any idea why?

**Comment by DanielGGordon** [comment]
I tried everything, and I also cannot get vim colors working in cmder_full. Oddly, when I ssh'd into a remote server, the colors did work - I played with my local .vimrc file and nothing helped.

**Comment by pbking** [comment]
Same happening to me.  JavaScript syntax highlighting works but not HTML or CSS or markdown.  Boo.  Works fine (with same vimrc) using ConEmu but not if using Cmder.

**Comment by afonsomatos** [comment]
Same here. It works fine if I open a new console with "vim", otherwise there are no colors.

**Comment by Stanzilla** [comment]
Probably because the _mini pack does not come with msysgit, and that includes vim?

**Comment by afonsomatos** [comment]
@Stanzilla I have vim installed from the official executable installer. I've added `vim.exe` to `PATH` and it launches great (w/syntax highlighting) from the normal command prompt. This doesn't seem to happen when using cmder.

**Comment by Stanzilla** [comment]
Alright, wrong suspicion then :)

**Comment by rmorrin** [comment]
It's possible that the vim used by the full installation doesn't search in the same place for your .vimrc file. Try running `:echo $MYVIMRC` inside vim and noting the output.

**Comment by JorenJoestar** [comment]
That command does not write anything :/
That would explain why I don't have any of my vimrc stuff working.

**Comment by pvonmoradi** [comment]
@JorenJoestar I'm having the same problem. Any ideas?
