### ISSUE TITLE
use alias in alias?

### ISSUE THREAD

**Issue by smeijer** [cmderdev/cmder#469]
Can we somehow use aliasses in an alias?

Let's say I wish to create a shortcut to edit my hosts file

```
subl="%CMDER_ROOT%\vendor\sublime-text\sublime_text.exe" $1 -new_console:s75V
edit-hosts={subl} "c:\Windows\system32\drivers\etc\hosts"
```

**Comment by glucas** [comment]
This is not supported for doskey macros, which are fairly limited: they can only be called as the first thing in the line, cannot be run from a batch program, etc.. 

See http://technet.microsoft.com/en-us/library/bb490894.aspx for details.

**Comment by daxgames** [comment]
Answered
