### ISSUE TITLE
How to add more commands beyond mysisgit?

### ISSUE THREAD

**Issue by raffian** [cmderdev/cmder#470]
Is it possible to expand cmder to support commands like top, iftop, , perhaps by swapping mysysgit with something like cygwin or similar Linux tools library?

Love cmder, just wish it had more Linux commands :-D

**Comment by MartiUK** [comment]
Drop executables into the bin folder, it'll be injected into your PATH at runtime.

For cygwin, I've made a guide, check it out in the wiki.

**Comment by raffian** [comment]
Nice, I'll try this out
