### ISSUE TITLE
CD'ing into a seperate drive

### ISSUE THREAD

**Issue by fhurtubise** [cmderdev/cmder#471]
I can pass a cd command to get to another drive, and tab completion works fine, but whenever I hit enter it just returns me to my home folder. I have tried with quotation marks and without, so either I am doing something or there is something wrong with cd'ing to another drive.

**Comment by vladimir-kotikov** [comment]
You have to pass `/d` option to cd command if you want to navigate to directory on another drive.

-----Исходное сообщение-----
От: "Francis Hurtubise" <notifications@github.com>
Отправлено: ‎06.‎05.‎2015 19:08
Кому: "bliker/cmder" <cmder@noreply.github.com>
Тема: [cmder] CD'ing into a seperate drive (#471)

I can pass a cd command to get to another drive, and tab completion works fine, but whenever I hit enter it just returns me to my home folder. I have tried with quotation marks and without, so either I am doing something or there is something wrong with cd'ing to another drive.

**Comment by richardfrost** [comment]
If anyone is interested in this, adding this line in my alias file took care of this:
```
cd=cd /d $*
```
Note: This behavior is default in PowerShell.
