### ISSUE TITLE
Cmder breaks when starting from non-system drive AND a path with spaces

### ISSUE THREAD

**Issue by superelitist** [cmderdev/cmder#474]
I have no idea where this is occurring:
If I start from `C:\cmder`, it works, if I start from `C:\spa ce\cmder` it works, if I start from `D:\cmder`, it works, **but** if I start it from `D:\spa ce\cmder`, the console opens, but I see the message:
`'D:\spa' is not recognized as an internal or external command, 
operable program or batch file.
The system cannot find the path specified.`

Additionally, the theme is not present, nor are the aliases. Otherwise it looks like a poor sad cmd.exe running in a cmder window.

I feel like the culprit might be init.bat, but I don't really understand what it could be doing wrong.

**Comment by mzvast** [comment]
Same problem~Any idea to solve this?

**Comment by Jackbennett** [comment]
Do you mind telling me if powershell does that too?
