### ISSUE TITLE
Text garbled when running VIM in a SSH'ed Powershell Session

### ISSUE THREAD

**Issue by thednaz** [cmderdev/cmder#476]
A bit of a corner case, but doesn't happen when running CMD, or running VIM in a native powershell session.

When VIM opens:
![vimgood](https://cloud.githubusercontent.com/assets/789072/7655988/95a41e6c-faf5-11e4-8655-4fc56c7d6063.png)

When pressing down arrow to end of file:
![vimbad](https://cloud.githubusercontent.com/assets/789072/7655992/9ebf381a-faf5-11e4-93e4-223604ed3f4b.png)

**Comment by razerwolf** [comment]
My bad, it's the same screenshot. The text obviously looks correct on open, but that image is the result of moving the cursor down to the last line.

**Comment by razerwolf** [comment]
Update: even with CMD it eventually garbles output, it just takes longer for it to happen. In fact, it seems that this usually happens after the command window is running for a bit of time. Thoughts?

**Comment by MartiUK** [comment]
What is $TERM set as when you ssh in? It should be xterm or similar.

Also, are you leaving the terminal alone (as in no input) for a while before it starts becoming garbled? Have a look at ssh keepalive in this case: https://sysadmincasts.com/episodes/39-cli-monday-how-to-keep-your-ssh-sessions-alive (Check the text below the video)
