### ISSUE TITLE
[REQ] Sudo (recommendation)

### ISSUE THREAD

**Issue by kronflux** [cmderdev/cmder#477]
I've been using this lovely tool to get around permission issues when doing maintenance on client units, it's called NSudo. It runs a command prompt as System, optionally with the TrustedInstaller flag.
I think it would be incredible if it were added to Cmder as "sudo <applicationname>", which could optionally launch an application as System or System with TrustedInstaller flag - OR run as "sudo su", which would relaunch(or simply apply permission to) Cmder so that the actual prompt has these permissions.

Here's the repository:
https://github.com/MouriNaruto/NSudo

Here's the downloadable executable thread:
http://forums.mydigitallife.info/threads/59268-Mouri_Naruto-NSudo-2-1

**Comment by vladimir-kotikov** [comment]
Try `csudo` script that already included in ConEmu and Cmder.

**Comment by kronflux** [comment]
I'm aware of csudo, but NSudo runs the prompt as System, not as Administrator. Useful for certain situations where system files need to be modified on the fly. It's the windows equivalent to actual sudo.

**Comment by daxgames** [comment]
I like this looking at it maybe to add.

**Comment by kronflux** [comment]
Just as a "FYI", this project has progressed quite a bit, and the latest works are located here:
https://github.com/M2Team/NSudo

**Comment by daxgames** [comment]
I did find the site you referrenced. I looked at it and my initial reaction is not to add it to cmder.  I had issues with it closing the cmder window.  Are you using it with cmder currently?

**Comment by kronflux** [comment]
at the moment I use the 64-bit executable renamed to "sudo.exe" in the cmder "bin" directory.
I use it as follows:
sudo -U:T -P:E <whateverIwanttodo.exe>

I had been using it at one point to launch cmder, but I since lost that configuration and never got around to setting it back up.
