### ISSUE TITLE
Windows 10 compatibility issues

### ISSUE THREAD

**Issue by flaiker** [cmderdev/cmder#478]
I am using cmder on several systems, on Windows 7 and 8.1 it is working fine, on 10 (10074) I got some problems. I am not sure if you are supporting Windows 10 as of yet as I did not see a system requirements section anywhere.

### Terminal is not fully functional
Using any git command that uses bash's diff I get this warning:
![image](https://cloud.githubusercontent.com/assets/5270359/7670184/365c7ae2-fc9b-11e4-9389-183590fa7408.png)
I can press enter and the command will execute normally.

I looked around this issue tracker and found quite a few issues related to this ( #50, #25 ). Using the suggested solution to set TERM=xterm did not resolve it though. I both set TERM in my systems environment variables and using the init.bat.
![image](https://cloud.githubusercontent.com/assets/5270359/7670248/f9e22d12-fc9c-11e4-9fdd-72435f8a88a1.png)

Git-Bash works fine by the way...
![image](https://cloud.githubusercontent.com/assets/5270359/7670260/948c9a50-fc9d-11e4-8f50-7888dc527e2c.png)

### Virtual console size
Another issue is that it seems as if the virtual scrolling lists (I don't know the actual term) do not know the size of the terminal. So if I am in a "scrollview" where I can normally scroll with arrow up/down and exit with q the content will just flicker for a moment and reset to the position before I pressed an arrow key. To me it seems as if the command thinks the console screen is large enough to display all the content, therefore scrolling is not allowed.
I can still scroll through it using Ctrl+Up/Down or the scroll wheel by using cmder's bufferscrolling and there I can see the full content is loaded into the buffer, not just what would be visible without scrolling.

This seems to be not limited to scrolling lists as you can see here running htop using ssh just freaks out.

**cmder Win10**
![image](https://cloud.githubusercontent.com/assets/5270359/7670291/639c3750-fc9f-11e4-800a-f2e2d330888c.png)
**cmder Win8.1**
![image](https://cloud.githubusercontent.com/assets/5270359/7670297/a2b32976-fc9f-11e4-9c1c-aa02241b0008.png)

I am using the same configuration on all three systems (I manage them using git) so that should not be a factor.

**Comment by MartiUK** [comment]
Are you having issues with the newest version?

**Comment by Flaiker** [comment]
I downloaded 1.2 from github releases.

First when I start it I get this (on Win10):
![image](https://cloud.githubusercontent.com/assets/5270359/7708387/8ec28ddc-fe55-11e4-9499-5584c66bd26f.png)

In the new default PowerShell I first of all don't have the ssh command available ("command ssh cannot be found"), which might just be me being to silly to use powershell. gl prints me the current path instead of doing git log --oneline --graph --... . Git log works (theres no "terminal is not fully functional" - message), though I still cannot scroll, If I try (on the ":" -prompt) it just says [K[B for down or [K[A for up arrow as I press the key.
I created a new cmd-tab, same issues there (except for gl and ssh working). Running htop over ssh stil has the same problem as mentioned in the op.

**Comment by ifeiteng** [comment]
i got the same issue

**Comment by sifex** [comment]
Build 10122 refuses to start entirely. Anyone else getting this?

**Comment by lossendae** [comment]
Nothing google can't solve, you have to install Visual C++ Redistributable for Visual Studio 2015 RC : https://www.microsoft.com/en-US/download/details.aspx?id=46881

**Comment by sifex** [comment]
Thanks for the assistance, since I wrote that my SSD has crapped out and it's no longer applicable.

**Comment by mwaa** [comment]
Still getting the same issue. Even after installing Visual C++ Redistributable for Visual Studio 2015 RC

**Comment by s4p0** [comment]
I found a description about powershell [here] (http://ss64.com/ps/syntax-run.html). [no expertise in this area]
> Before running any scripts on a new PowerShell installation, you must first set an appropriate __Execution Policy__, e.g. __Set-ExecutionPolicy RemoteSigned__

So, before execute __cmder__ on __Windows 10__ [worked for me], execute __PowerShell__ as __Administrator__ and execute __Set-ExecutionPolicy RemoteSigned__.

This will allows __cmder__ to execute __profile.ps1__.

**Comment by BrunoMoreno** [comment]
I made a remaster running on Windows 10:
https://github.com/BrunoMoreno/CmderRemaster

**Comment by anadin** [comment]
@BrunoMoreno thanks for this, perfect solution! :)

**Comment by BrandonG777** [comment]
@BrunoMoreno ssh and ls commands not working for me, new Windows 10 build maybe?

 0 [main] us 0 init_cheap: VirtualAlloc pointer is null, Win32 error 487
AllocationBase 0x0, BaseAddress 0x68570000, RegionSize 0x1D0000, State 0x10000
C:\Users\Brandon\Sync\Apps\cmder\vendor\msysgit\bin\ssh.exe: *** Couldn't reserve space for cygwin's heap, Win32 error 0

**Comment by mryongzhang** [comment]
when I run command [ls] on win10, then I got an error.
      0 [main] us 0 init_cheap: VirtualAlloc pointer is null, Win32 error 487
AllocationBase 0x0, BaseAddress 0x68570000, RegionSize 0x310000, State 0x10000
C:\Program Files (x86)\Git\bin\ls.exe: *** Couldn't reserve space for cygwin's heap, Win32 error 0
