### ISSUE TITLE
Missing DLL: MSVCP140.dll

### ISSUE THREAD

**Issue by UnNeill** [cmderdev/cmder#482]
Is this related to your new VS2015 update?
win 8.1 with vs2013

**Comment by jstevans** [comment]
It certainly seems that way. Go to the [Visual Studio 2015 RC Downloads page]; under "Additional Tools", there's "Microsoft VC++ Redistributable 2015 RC."

[Visual Studio 2015 RC Downloads page]:https://www.visualstudio.com/downloads/visual-studio-2015-downloads-vs

**Comment by wallacewinfrey** [comment]
Even after installing Microsoft VC++ Redistributable 2015 RC (and I can see msvcp140.dll in C:\Windows\System32) I still get the same message. If I copy the DLL to my cmder installation directory, the message I get is "The application was unable to start correctly (0xc000007b). Click OK to close the application."

**Comment by novacrazy** [comment]
Try installing the 32-bit version of the redistributable. That worked for me.

**Comment by Haprog** [comment]
Thanks @jstevans and @novacrazy !
I also had this problem today on Win 7 SP 1 (64-bit).
Fixed by installing 32-bit version of MS VC++ Redistributable 2015.

**Comment by CookieCrumb23** [comment]
Is there a quick, easy way to 'fix' this on a system on which I do not have administrator permissions?  
Because, obviously, installing the redistributable isn't an option.

**Comment by KanDisheng** [comment]
I have this problem too on Win 8.1 (64-bit).

**Comment by Stanzilla** [comment]
Install it on a system where you can and copy the dlls to cmder root.

**Comment by DoCode** [comment]
Same issue on Win 8.1 x64

**Comment by MartiUK** [comment]
I've just attached an archive with the dll in, could you try extracting that to your cmder directory?

**Comment by Jackbennett** [comment]
Win7SP1x64 here. Moved onto the `VCRUNTIME140.dll` is missing after extracting the attached msvcp140.7z/dll

**Comment by Blaok** [comment]
Yes after downloading `msvcp140.dll`, `VCRUNTIME140.dll` missing is popping up now... Win 8.1 x64.

**Comment by ouel92** [comment]
@MartiUK After extracting the `msvcp140.dll` , I get `api-ms-win-crt-runtime-I1-1-0.dll` missing. Windows 8.1 x64.

**Comment by ColCh** [comment]
Windows 8.1 x64 fixed with installation both 64-bit and 32-bit version of "Microsoft VC++ Redistributable 2015 RC". Thank you @jstevans and @novacrazy 

May be this info should be added to _README.md_ ?

**Comment by l1nxy** [comment]
me too.

**Comment by l1nxy** [comment]
thanks !
installing 64-bit version do not work. 
After installing 32-bit version of MS VC++ Redistributable 2015.
The problem fixed.
Win8.1 VS2013

**Comment by MartiUK** [comment]
c4873c6e5813e5c253ae32ba68123d2694b422ce I've reverted the VS2015 change.

**Comment by avimar** [comment]
I downloaded the full version from the webpage http://gooseberrycreative.com/cmder/ just now and I still had to download the Visual Studio 2015 RC... I had to search to find the error message here. Did you say you fixed it..?

**Comment by Stanzilla** [comment]
nah, he still needs to recompile

**Comment by MartiUK** [comment]
@avimar @Stanzilla It will be uploaded in a few hours, just testing it on a lot of VMs.

**Comment by DoCode** [comment]
What about new recompiled package?

**Comment by vrajanap** [comment]
I am still running into this issue with a package downloaded from http://gooseberrycreative.com/cmder/

**Comment by cflee** [comment]
Is this patched yet? I'm still running into the `api-ms-win-crt-runtime-l1-1-0.dll` issue with the current mini and full v1.2 downloads. (Windows 7 Pro x64 SP1)

**Comment by phpprobetter** [comment]
Are there any variants to install Apache 24 without Visual Studio 2015 RC ? may be copy some files from good working system?

**Comment by olsonpm** [comment]
Also running into this on a machine I do not have administrator permissions on.  Using the previous release.  Never used this program before - looks incredible :+1:

**Comment by phpprobetter** [comment]
who know russian - read [about this  problem here](http://fkn.ktu10.com/?q=node/6960)

**Comment by avindra** [comment]
Doing same as @olsonpm . Reverted to v1.1.4.1 until this is fixed.

**Comment by Stanzilla** [comment]
https://github.com/Stanzilla/cmder/releases/tag/v1.2.1
