### ISSUE TITLE
v1.2.0: Errors because of PowerShell execution policy

### ISSUE THREAD

**Issue by denisw** [cmderdev/cmder#483]
The first time I start Cmder 1.2.0, I get an error that a script cannot be executed because the PowerShell execution policy doesn't allow it. After I have run `Set-ExecutionPolicy Unrestricted` as administrator, the shell asks me every time on startup whether I really want to run the script.

**Comment by SkynetHopper** [comment]
I ran set-executionpolicy remotesigned but now it shows that the profile.ps1 file is not digitally signed at all.

![image](https://cloud.githubusercontent.com/assets/12433448/7678924/cd8f1792-fd60-11e4-87af-8de2bc16f01b.png)

**Comment by Jackbennett** [comment]
@skynetHopper if you run `get-executionPolicy -list` is it shown as remoteSigned?

Have you both tried either right-clicking the powershell file in question and clicking button "unblock file"

Or you can point the unblock-file command at the profile.ps1 file. If that works I'll have to look at doing that in a setup step.

You should be able to leave your executionPolicy as remotesigned.

**Comment by SkynetHopper** [comment]
Thanks Jack! Unblocking the .ps1 file worked! But its missing git support
and asks to install posh-git and restart.

Running get-executionPolicy -list does show it as remoteSigned.

**Comment by denisw** [comment]
I should stress that, while the problem might easily be fixa le by anyone with some PowerShell knowledge by themselves, it makes for a pretty bad user experience and first impression. It would be better if Cmder would set the execution policy itself if needed (and inform me about it), or if at least the docs would mention anything about the setup required.

**Comment by Jackbennett** [comment]
You are correct. We are trying to find a balance between what we really need and not just changing global settings for users.

**Comment by MartiUK** [comment]
@denisw There isn't much we can do unfortunately, overriding built in security protections isn't something I'm willing to do, even though I feel they're a bit heavy handed.

**Comment by denisw** [comment]
@MartiUK If it isn't possible to make it nice, perhaps cmd.exe would be a better default choice after all as it works out of the box. I think that together with docs to make PowerShell work well, this would make the initial experience as nice as the one in 1.1 again.

**Comment by Jackbennett** [comment]
I think there's a way around it, I'm making a new vm to test this stuff from scratch. The execution policy is more like a bad default and a not feature than it is for security.

What I don't want to is run the whole session in bypass.

**Comment by eliashdezr** [comment]
Running this as administrator did the trick for me.
´´´
Set-ExecutionPolicy -ExecutionPolicy Bypass
´´´

**Comment by OlsonDev** [comment]
So... the official solution is to open `LocalMachine` up to `Bypass` everything? Seems... bad.

**Comment by malobre** [comment]
If you don't want to use the `Set-ExecutionPolicy` or it didn't work (in my case the command didn't work) you can fix this by going into Settings > Startup > Tasks then select `{PowerShell}` or `{PowerShell as Admin}` and add `-ExecutionPolicy Bypass` to the command

**Comment by denisw** [comment]
Could we have cmd.exe as default again for v1.3 if this cannot be resolved automatically? At least that would work right away without error messages and configuration.

**Comment by malobre** [comment]
Or they could just add `-ExecutionPolicy Bypass` to the default powershell task

**Comment by OlsonDev** [comment]
I much prefer Process being set automatically. Thanks @malobre!

**Comment by denisw** [comment]
I second that the @malobre's approach would be the most elegant one!

**Comment by Jackbennett** [comment]
I just wish we could force to run our own init/profile script and drop back to `remoteSigned`

At least launching the process with -bypass is just for you cmder session and not anything that run on the computer. You wouldn't get any warning about running a script explicitly as `.\fromInternet.ps1`

I thought about signing our own script but we'd still have the same problem but with managing the key instead of the exec policy.

**Comment by isimmons** [comment]
Shouldn't cmd.exe be the default because it is always installed and in working order on all windows systems? 

How do I change this default task to use cmd.exe?

**Comment by LIGHTYEARS** [comment]
Thanks a lot!Unblocking the file profile.ps1 worked for me too.I navigate to the directory where contains the profile.ps1,then run command `Unblock-File .\profile.ps1` and it succeed.

**Comment by berryman13** [comment]
For those who are having trouble with this, this is what I did to fix on Win10.
Right click cmder, open it as admin. It may or may not show the error, probably will. Either way, it starts PowerShell by default, so as long as its ran as admin this command should do the trick:
`Set-ExecutionPolicy -ExecutionPolicy Bypass`

**Comment by sensui7** [comment]
For those who have scrolled down here and still don't know how to fix it.
You can either run the command in the above comment or edit the commands in the setting->startup->tasks> powershell and powershell as admin, add this "-ExecutionPolicy Bypass".

**Comment by DavidDeme** [comment]
Is it possible to change settings and make cmd.exe default when Cmder starts ? :(
It's so annoying when I have to close powershell.exe first and then start a new console :(

**Comment by benjamin79** [comment]
setting->startup->tasks>default shell

**Comment by simevidas** [comment]
Could someone please give clear instructions how to get rid this error message? I’ve tried to follow instructions mentioned in the comments above, but nothing has worked so far.

![capture](https://cloud.githubusercontent.com/assets/716405/10353655/db24a292-6d58-11e5-9767-04e28f370517.PNG)

**Comment by Stanzilla** [comment]
@simevidas https://github.com/Stanzilla/cmder/commit/20e4440d8cab2f797b6ab9d69fe36307fe51f046

**Comment by mflux** [comment]
I'm still having issues with this despite having updated to the latest version.

**Comment by MartiUK** [comment]
1.2.9?

**Comment by Jackbennett** [comment]
If you've not changed your execution policy you'll still get that with
powershell. The changes in later versions of cmder revert to using the old
cmd.exe instead to avoid it.

If you're a powershell user you need to set your execution policy as
described. I and MS recommend remotesigned.

So from an admin prompt, "Set-ExecutionPolicy RemoteSigned" then I think
you need to navigate into the cmder folder to run "unblock-file *"

**Comment by mcandre** [comment]
`Unrestricted` appears to be a more secure, `profile.ps1`-compatible setting than `Bypass`.

https://technet.microsoft.com/en-us/library/hh849812.aspx

**Comment by michael-wise** [comment]
https://github.com/cmderdev/cmder/issues/483#issuecomment-162931773
As of recent versions (when?), it seems Cmder prompts to Powershell Unblock-file itself on first run. I am unsure if it checks on ExecutionPolicy as I believe mine was already set.
