### ISSUE TITLE
cmder display error

### ISSUE THREAD

**Issue by YoannN2** [cmderdev/cmder#491]
# (laravel) php artisan tinker & cmder
Hi, I have a weird problem, whenever I use php artisan tinker, when I display an object within it I get the following :

![cmder and php artisan tinker](https://cloud.githubusercontent.com/assets/10013976/7701394/75584f36-fe72-11e4-81fd-653cca80d54f.jpg)

##Description :
Basically whenever tinker prints out an object, it dislays its class between &lt; and &gt; and somehow it then highlights everything in white.

My 'quick noob fix' once i'm done with tinker is to restart tinker ( starting it clears the white highlight) 
![cmder and php artisan tinker2](https://cloud.githubusercontent.com/assets/10013976/7701497/6357ba46-fe73-11e4-8a50-0e15667dc874.jpg)

and then i clear it...

It's a bit annoying. I'm not getting it with git bash or the good ol' cmd... And I do get it aswell with cmder as {cmd} or {PowerShell}
So far it's the only problem i've found with cmder, it's a life changer, it kicks asses !

##SYS INFO
Paths:
C:\Users\Yin\AppData\Roaming\Composer\vendor\bin;C:\Ruby22-x64\bin;C:\Users\Yin\AppData\Local\atom\bin;C:\Users\Yin\AppData\Roaming\npm

system : win8 64bit

**Comment by MartiUK** [comment]
That's really odd, I wonder if it's setting the background colour as well as the foreground color, I don't know my PHP but it looks like the offending code is here: https://github.com/bobthecow/psysh/blob/master/src/Psy/Output/ShellOutput.php#L198

Which uses symfony to set the colour: https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Console/Formatter/OutputFormatterStyle.php

Is there a default background colour it's assuming is there?

**Comment by YoannN2** [comment]
It might set the background color (of the text), when I do a `clear` I have those _highlights_ the whole screen becomes lighter but the padding of cmder's window doesn't change...

But then again through the **OutputFormatterStyle** class it's not passing a background, only a foreground...

in ShellOutput.php#L198 it calls **OutputFormatterStyle's constructor** with only a foreground as argument, which then calls setForeground **L86** ... and it doesn't touch the bg . at least as far as i can see. 

ref:
https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Console/Formatter/OutputFormatterStyle.php#L86-L131

Since the _highlight_ triggers AFTER the 'blue' as been called when he calls an object, i think somethign else is causing it...

I think the problem comes from git bash perhaps. i'll try later tmrw to uninstall it and see what happens.

Also i'm following a tutorial on Laravel, and they're using cmder (on mac) and not having that issue.

So the problem is on my end, i'll check later

**Comment by SrcFlux** [comment]
I'm experiencing this issue as well. A fix for it would be awesome!

**Comment by donkeycoder** [comment]
I'm also facing this problem .

**Comment by donkeycoder** [comment]
I have solved the issue . Change Schemes to ubuntu and it will work fine ...
![untitled](https://cloud.githubusercontent.com/assets/5843024/8509382/4cf04598-2254-11e5-9b27-856abeba1a72.png)

**Comment by YoannN2** [comment]
@donkeycoder this didn't fix it for me :/

**Comment by donkeycoder** [comment]
Make sure you are using latest version of Cmder ( Laragon 6.0).

**Comment by donkeycoder** [comment]
![untitled](https://cloud.githubusercontent.com/assets/5843024/8674905/c18c10be-29f5-11e5-80c1-bf7a37db924c.png)

I got the problem . Make sure your colour at 0 position and 8 position are same . 8th position is the selected colour if it is similar to background it won't show the selection , and make sure background is set to #2 . 

Tell me if it solved that

**Comment by YoannN2** [comment]
This fixed it ! Thank you :)

**Comment by babeuloula** [comment]
Hello, 

I have a similary problem with Symfony3. See below : 

![capture d ecran 2016-05-31 19 27 12](https://cloud.githubusercontent.com/assets/4849233/15684104/d12081e0-2765-11e6-8672-e1c9cf27c7f7.png)

![capture d ecran 2016-05-31 19 27 07](https://cloud.githubusercontent.com/assets/4849233/15684107/d38cb354-2765-11e6-95ed-521e18e4e25f.png)

Thanks
