### ISSUE TITLE
New console dialog shows incorrect options

### ISSUE THREAD

**Issue by SrcFlux** [cmderdev/cmder#495]
Whenever I create a new console inside Cmder the "Create new console" dialog shows two invalid options, one of them being:

```
PowerShell -NoLogo -NoProfile -NoExit -Command "Invoke-Expression '. ''%ConEmuDir%\..\profile.ps1'''"
```

and the other one seems to be the first part of my PATH variable:

```
;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\
```

![unbenannt](https://cloud.githubusercontent.com/assets/8874705/7714846/912d2348-fe82-11e4-8327-ec023539e8bd.png)

This issue does not seem to be related to my Cmder configuration, this happens on a minimum vanilla install as well.

I'm using Win 8.1 x64.

**Comment by MartiUK** [comment]
The PATH variable is actually in the config.xml, so I'll remove that, the Powershell one, I think references the last opened tab which in this case is the {PowerShell} task.

**Comment by glucas** [comment]
The PATH fragment can be removed by finding this in the ConEmu.xml:

    <value name="CmdLineHistory" type="multi"><line data=,,/></value>

and remove the line element, i.e.

    <value name="CmdLineHistory" type="multi"/>


The other one will show the full command for whatever console you last created. I don't see a way to turn that off -- personally I'd like to just not have the previous item there, but guess that would be a ConEmu feature.

**Comment by DanielGGordon** [comment]
I have a similar issues that shows 

`cmd /k "%ConEmuDir%\..\init.bat"`

As an option for a new console. When i go to the task settings, I only see `{cmd}` and `{CygWin bash}`, yet this other option shows up. I deleted the `<line>` element.

**Comment by PMExtra** [comment]
I have the same problem.

**Comment by daxgames** [comment]
Path was removed from conemu.xml other issue nis expected behavior closing
