### ISSUE TITLE
Switching to desktop screen using the Alt-Tab shortcut crashes cmder.

### ISSUE THREAD

**Issue by gmontalvoriv** [cmderdev/cmder#496]
This happens only when using the mini version. 

I'm using Windows 7 Premium Edition 64-bit

**Comment by MartiUK** [comment]
Have you changed any settings?

**Comment by gmontalvo5416** [comment]
I did make some changes (tabs on bottom, windows default theme, row highlighting), but that's about it. I didn't change anything regarding the console's startup settings and Keys either. However, after resetting all the changes back to default, there was no longer a problem with the alt-tab shortcut. I tried playing around with the settings again to see if I could find whatever caused it in the first place, but it all seems to be working fine now.
