### ISSUE TITLE
ncurses borders incorrectly displayed with ssh.exe

### ISSUE THREAD

**Issue by 0xicl33n** [cmderdev/cmder#499]
I read somewhere the ssh.exe that comes bundled with cmder is based off PUTTY ( i believe its kitty). 

which has the issue described here:

http://www.koerner.in/2011/08/ugly-borders-and-lines-in-curses-based-programs-using-putty/

Since the ssh that comes with cmder is bundled, is there any way to edit the settings to work like the above? I hate the AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA borders on my terminals.

**Comment by g105b** [comment]
Please can someone explain how this issue is resolved? I notice it is closed but upon recently switching to Windows and finding cmder, I'm experiencing this same issue.

**Comment by dzarda** [comment]
I must agree that ncurses continues to be broken under cmder

**Comment by 0xicl33n** [comment]
I have  switched to [windows terminal](microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) which works perfectly with curses :)
