### ISSUE TITLE
Aliases not loaded

### ISSUE THREAD

**Issue by sveggiani** [cmderdev/cmder#500]
When Cmder starts 1.2 none of the aliases defined in `config/aliases` file are available. No errors reported at all.

**Comment by PavleGit** [comment]
I also have this problem. Is there any solution to this yet?

**Comment by Lywel** [comment]
I also have this problem

**Comment by tournier** [comment]
Make sur the startup task is set, and kind of look like this:
http://i.imgur.com/jaIbwEu.png

Otherwise, providing screenshot or more informations about something you want to report may help.

**Comment by Lywel** [comment]
This is working now, thanks !

**Comment by PavleGit** [comment]
Thanks for reply, tournier!

Unfortunately I still cannot use my aliases (f.e. "subl" which is set as subl=C:\PROGRA~1\SUBLIM~1\sublime_text.exe $1 -new_console:s75V OR "e.").

I can however use aliases like "clear", "pwd" and so on. This is how my startup tasks are set (default):

![screenshot- 66](https://cloud.githubusercontent.com/assets/5628018/8031206/e8470c58-0dcc-11e5-89c0-a1074e90af36.jpg)

**Comment by darsain** [comment]
Since 1.2 cmder uses `{PowerShell}` instead of `{cmd}`. `{PowerShell}` uses `vendor/profile.ps1` to set up the environment, and there is nothing that would load or manage `config/aliases` in any way.

The 1.2 update effectively removed support for aliases. Instead we have `{PowerShell}` build in aliases, which are way less powerful and not persistent (any alias set via `Set-Alias` command gets deleted when you close the session).

**Comment by PavleGit** [comment]
Well then...those are unfortunate news. The ability to add custom aliases (like that) seemed really sweet.
Will try with PowerShell aliases and with [this](http://stackoverflow.com/questions/24914589/how-to-create-permanent-powershell-aliases) to make them permanent.

**Comment by darsain** [comment]
Yeah, I'm loading my own ps1 script with aliases myself. It's just not very user friendly, and those aliases are really dumb. AFAIK  there is no way how to make aliases that use parameters, or equivalent of `$*`.

**Comment by walkerdb** [comment]
It would be great to get aliases back

**Comment by darsain** [comment]
I solved this by switching cmder back to {cmd}. Using powershell was unbelievable pain due to tons of other issues anyway.

**Comment by jonasninja** [comment]
I also switched back to {cmd}. Not sure what the benefit of PowerShell is even supposed to be.

**Comment by DanielGGordon** [comment]
Powershell is great if you know how to use powershell commands. It's more native to Windows than any of the bash/linux emulators like Cygwin/Babun/git Bash. It uses completely different commands to allow you to interact with windows from command line. If you don't know how to use Powershell (like me), and you aren't going to learn powershell commands, then it's useless for you. Take a look here for a little explanation:

http://www.7tutorials.com/simple-questions-what-powershell-what-can-you-do-it

**Comment by howdoicomputer** [comment]
I switched back to cmd as well. I think a pull request is valid for updating the README.md to indicate that aliases are not supported under PowerShell. Also, I noticed the prompt is slightly different for git integration. I don't mind the change as long as I can have a pane with sublime running in it.
