### ISSUE TITLE
Git: fatal: Unable to find remote helper for 'https'

### ISSUE THREAD

**Issue by F21** [cmderdev/cmder#503]
I am unable to clone git repos over https:

```
λ git clone https://github.com/mesos/chronos.git
Cloning into 'chronos'...
fatal: Unable to find remote helper for 'https'
```

OS is Windows 8.1 64-bit.

**Comment by Alexhha** [comment]
The same issue on Win 7 x64
```
Caused by: hudson.plugins.git.GitException: Command "C:\cmder\vendor\msysgit\bin\git.exe -c core.askpass=true fetch --tags --progress https://github.com/justinjmoses/flexmojos-introduction/ +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: fatal: Unable to find remote helper for 'https'
```

**Comment by F21** [comment]
A temporary work around is to use `cmder_mini` and install the standalone msysgit package yourself. The downside of this is that this won't be portable if you want to bring cmder and tools on a usb stick.

**Comment by sifex** [comment]
Same Problem here. Win8.1 64-bit.

**Comment by anouarattn** [comment]
same problem, win 7 64-bit cmder v1.2

**Comment by anouarattn** [comment]
cmder-mini with standalone msysgit works fine thanks @F21

**Comment by sifex** [comment]
I find if you delete /vendor/msysgit and install git/msysgit independent it fixes the problem.
Temp solution though. Be nice for a proper fix

**Comment by glucas** [comment]
This may be the same issue as  #521.

**Comment by iki** [comment]
Temporary workaround for #503 and #521 is to download `PortableGit-1.9.5-preview20150319.7z` (or newer when available) from https://github.com/msysgit/msysgit/releases and extract it to `vendor\msysgit`.

```
cd cmder\vendor\msysgit
curl -k -L https://github.com/msysgit/msysgit/releases/download/Git-1.9.5-preview20150319/PortableGit-1.9.5-preview20150319.7z -o git.7z
7z x -aos git.7z
```
