### ISSUE TITLE
powershell read user profile

### ISSUE THREAD

**Issue by harkx** [cmderdev/cmder#505]
Using 150513 it seems cmder does not use the Powershell profile.
I have a function in that profile to connect to Ofice365, it would be great if launching cmder reads the powershell proflile.

In my case it's located in:

```
C:\Users\me\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1
```

You can query this location in Powershell with this command:

```
$Profile
```

**Comment by strig** [comment]
Go to `settings > startup > tasks` and remove the `--NoProfile` from the PowerShell command arguments.

**Comment by harkx** [comment]
Perfect! Thanks!

**Comment by nevion** [comment]
@strig why is this not default?

**Comment by Stanzilla** [comment]
I guess one could argue that to keep cmder properly portable it should ignore the local PS profile, not sure though

**Comment by JanSchulz** [comment]
Would it be a nice compromise to add someting like this into `user_profile.ps`:

```
# cmder runs the powershell with '--NoProfile', so $Profile isn't called on startup.
# If you want to use your $Profile, you can either uncomment the next lines or 
# change the startup to use $Profile (in cmder under settings > startup > tasks -> 
# the --NoProfile from the PowerShell command arguments).
#if (Test-Path $PROFILE) {
#    . $PROFILE
#} 
```

**Comment by Jackbennett** [comment]
What about a separate pre-configured task that doesn't have `--noProfile`. People can test with it and just move the default over if they choose.

**Comment by AlexHankins** [comment]
I was very puzzled why running PowerShell from the Start menu behaved differently from running it in Cmder.  This cost me some time and effort to research the issue.  Please fix.  Thank you.

**Comment by daxgames** [comment]
Add to the `%cmder_root%\user_profile.ps1`:

```
. $profile
```
