### ISSUE TITLE
Character persistence on cmder windows

### ISSUE THREAD

**Issue by ctexlive** [cmderdev/cmder#506]
Character persistence occurs when residual character of a previous command remains visible on the screen.
When press up-arrow key to view the last command, "mplayer" for example, the Command Window display is ok. See Fig1.
![cmder1](https://cloud.githubusercontent.com/assets/8100859/7805809/ac5f3fb0-03ab-11e5-974e-1bae1c05d661.png)

Subsequently press down-arrow key to change command history, some character remains visible on the CMDER windows.See Fig2.
![cmder2](https://cloud.githubusercontent.com/assets/8100859/7805811/b5482e34-03ab-11e5-87b4-d0ed99bc0c22.png)

It is very annoying. How to resolve the problem? Thanks.
It should be noted that the number of a command is less than or equal to 4,the phenomenon would not occur again.
Fig3 is font setting.
![font setting](https://cloud.githubusercontent.com/assets/8100859/7805815/bb5f1936-03ab-11e5-8719-63738194e4f2.png)

**Comment by ifeiteng** [comment]
me too

**Comment by henumohe** [comment]
me too

**Comment by denis-adobe** [comment]
This error is not replicable for me

**Comment by xgenvn** [comment]
Same here, struggling for at least 6 months, after windows 10 upgrade.
To reproduce this bug:
1. Type some long commands (>5 length of characters)
2. Ctrl-C
3. Arrow-Up
4. Arrow-Down
There's should be a first character of last command stay on screen.
I'm on latest version of cmder. Change the codepage to utf-8 wont help.
This bug is only happening on CMD. Under bash shell everything is fine.

**Comment by iainheng** [comment]
Having the same problem here in Windows 10

**Comment by xgenvn** [comment]
I have searched around again of any solution for this bug, and it's turned out that changing the {lambda} to proper ascii character will help (under cmder/config/cmder.lua). Check again #553.

**Comment by Jackbennett** [comment]
I can't reproduce this on my 1.3.0-pre can more people try it please.

**Comment by Oceangraves** [comment]
I'm still getting this error in the latest version.

**Comment by emmanuelnk** [comment]
Have this error on latest version 161206 ... My system locale is Chinese (Simplified).

**Comment by LexSong** [comment]
Same issue here

**Comment by Justsoos** [comment]
same problem, replace all, just two lamda "λ" in file \cmder\vendor\clink.lua with "$", solved.

`    if env == nil then
        lambda = "$"
    else
        lambda = "("..env..") $"
    end`

**Comment by hulucc** [comment]
Same issue, locale is Chinese simplified.

**Comment by jdhao** [comment]
I am using the latest version of cmder (version 1.3.8). It seems that this old issue still persists.  The `clink.lua` file have changed.  Find the line 

```
    local lambda = "λ"
```

and replace it with 
```
    local lambda = "$"
```

Restart cmder and the problem should disappear.

**Comment by Justsoos** [comment]
@jdhao 
the replace method was for version 1.3.4 older, like screenshot
![image](https://user-images.githubusercontent.com/3480043/48554935-b16e0880-e91a-11e8-8475-7d2c5667dcd2.png)
I tried cmd ver 1.3.8 and ComEmu ver 180626[64] just now, have not encontered this bug again. 
and no more running the environment: 
`set LANG=zh_CN.UTF8
`

**Comment by hulucc** [comment]
Still not working after updated 1.3.8

**Comment by Justsoos** [comment]
@hulucc  I tried ver1.3.8 as new installation, yes, the bug still there, my solution:
changing the "λ" with "$" at line 43.
![image](https://user-images.githubusercontent.com/3480043/48847069-9d734c80-eddb-11e8-8264-bad22028c3b2.png)

**Comment by daxgames** [comment]
You guys keep calling this a bug but I can't reproduce it.  If we can't reproduce it and you keep masking it by just changing it to `$` it will never get fixed as you guys seem to want based on the recent comments.

If someone can find a root cause and tell us how to reproduce it might be looked at but until that happens no one on the Cmder team is trying to 'fix' it.

**Comment by daxgames** [comment]
If you do want to just mask it there are better ways than changing the clink.lua because this file is overwritten on upgrade.

**Comment by Justsoos** [comment]
@daxgames  ha~ those bugs often met with Non-English Windows by chcp and UTF and font ... so many mixed mistakes, like:
https://github.com/cmderdev/cmder/issues/1339
https://github.com/cmderdev/cmder/issues/764
https://github.com/cmderdev/cmder/issues/1171

and "lambda" is not a normal ascii code, and most bugs from M$ Windows, not within capabilities of cmder.... so cmder run like a patch bbs of M$

**Comment by emmanuelnk** [comment]
@daxgames it's very easy to reproduce. Change the system locale of your system to something like Chinese Simplified. Then open cmder and white a bunch of commands. Then try to use the 'up' key to view previous commands. That should reproduce the issue. It's probably something to do with the byte  size of the lambda character in different encodings.

**Comment by jdhao** [comment]
I will try to elaborate my possibly-related settings for you to reproduce this bug.

I am using Windows 10 Pro, Version 1803 and OS build 17134.345. My region is set as `China` and my language is set `English (United States)`. 

I am using Cmder version 1.3.8 with ConEmu 180626.  My settings for `Startup -> Environment` is

```
set PATH=%ConEmuBaseDir%\Scripts;%PATH%
set LANG=en_US.utf8
chcp utf-8
set TERM=xterm-256color
```

Please let me know if you need any further info.

**Comment by jdhao** [comment]
@Justsoos , You have to type long command (some say the command length must be longer than four ) to actually trigger this bug. Have tried long commands?

**Comment by daxgames** [comment]
@justsoos are you using the up arrow to cycle through history as others have mentioned?

**Comment by Justsoos** [comment]
@daxgames  it is a complex story.... before update to 1.3.8, I run an 1.3.4 probably, have to `set LANG=zh_CN.UTF8` and chage the lambda to $ and several things else to avoid Chinese charactor errors, but this time, I delete the old cmder and extract 1.3.8 to the default install directory, have not to change them that mentioned, all works well.

**Comment by dorkbox** [comment]
An update on this issue, since I'm having it as well...
I think it's absolutely a rendering issue... since you cannot have arbitrary characters as the "lambda". For example -  the default is `λ` and if you *replace* it with `𝝺` (which is a different lambda) - the prompt is completely screwed up

![image](https://user-images.githubusercontent.com/5301521/77831348-da1d2980-712e-11ea-8bc3-5edfd3ea45ce.png)

For reference, I got that lambda from https://en.wikipedia.org/wiki/Lambda, and it is the `U+1D77A` lambda. I have UTF support enabled in windows.Only the first two lambda's work from that page.

**Comment by hamzahamidi** [comment]
I'm facing the same issue with v1.3.14

**Comment by dorkbox** [comment]
The only solution, sadly, is to change the character. `~` is what I use, and works without issues.

**Comment by jdhao** [comment]
It is year 2020. Sadly, this issue still persists. If this issue is hard to fix, why not just change the default prompt character from lambda to something purely ASCII, for example, `>` or `$` or whatever?

**Comment by daxgames** [comment]
@jdhao it's not up to me.  This is not my project I just help maintain it.  Changing the prompt is user configurable by adding lua code to the config folder.  You can change it to whatever you want one time and you will never have to change it again.

**Comment by AaronFeledy** [comment]
This issue has been plaguing me in my git-for-windows bash shell. If the last item in my history was longer than 4 characters, the first character would stick. I noticed that a fresh install was not having this issue, so I went digging.

I initially narrowed it down to my bash starting without the `--login` option. Removing the --login from a fresh install caused the problem to occur there. Adding the --login to my broken configuration fixed the issue for me. In digging through the various scripts that run for the login shell, I was able to determine that it was setting the `LANG` environment variable in the `/etc/profile.d/lang.sh` script.
```bash
export LANG=$(exec /usr/bin/locale -uU)
```
Manually running `export LANG=en_US.UTF-8` would immediately fix a problematic shell prompt for me.

I'm not sure how this translates to those experiencing the issue with cmd, but it likely has something to do with local options and perhaps something in `init.bat` that handles setting locale config.

**Comment by jackusay** [comment]
If you find out you can't change Prompt symbol (lambda λ), here is one possible solution.

v1.3.1

`C:\cmder\vendor\git-for-windows\etc\profile.d\git-prompt.sh`:

change
```
  PS1="$PS1"'λ '                 # prompt: always λ 
```
into
```
  PS1="$PS1"'$ '                 # prompt: always $ 
```

**Comment by chrisant996** [comment]
Or use UTF8 as the system code page.

The problem is that CJK locales define some Unicode characters to be different widths than the standard says they should be. And also some fonts define the characters with different widths than the standard or CJK widths expect.

Lambda happens to be one of the affected characters.
