### ISSUE TITLE
Autocomplete for non-executables not working

### ISSUE THREAD

**Issue by jarihu** [cmderdev/cmder#508]
The standard cmd.exe allows me to autocomplete and launch any file just by typing its name. 
Like for "foobar.txt" just by typing "foo" and hitting tab autocompletes the filename to "foobar.txt" and when I hit enter, it launches the file with default handler. Cmder doesn work like this. It seems to autocomplete only executables and dir names. Could this be changed?

**Comment by Jackbennett** [comment]
Clink handles the auto-complete for the cmd task. I think you want to append the following to the `%CMDER_ROOT%\config\settings` file.

```
# Autocomplete all files and by current folder as well as PATH
exec_match_style = -1
```

**Comment by aninda** [comment]
Thanks @Jackbennett !! That worked for me atlast.

**Comment by AlanTrudor** [comment]
Hey I am having this same problem but there is no settings file in v1.3.18.1106, could someone please help me resolve it :)

**Comment by bumbaras** [comment]
> Hey I am having this same problem but there is no settings file in v1.3.18.1106, could someone please help me resolve it :)
cmder doesn't support it, just forget and look for other replacement.
