### ISSUE TITLE
Cmder changes the height every time I open it

### ISSUE THREAD

**Issue by captainepoch** [cmderdev/cmder#511]
I'm in Windows 8.1 Pro x64 with Cmder (and ConEmu's latest version) in another path it's not C:. When I open it form an icon in the status bar, the height is modified with 1 unit less.

Is necessary that Cmder will be opened as admin?

Thank you very much! :+1:

**Comment by asabla** [comment]
I to experience this in windows 8.1 x64

**Comment by Maximus5** [comment]
"Latest" is ambiguous. Numbers please.

**Comment by MartiUK** [comment]
@Maximus5 Should be 150513

**Comment by adolphenom** [comment]
@Maximus5 @MartiUK It's 150513, actually.

**Comment by Maximus5** [comment]
Run ConEmu with `-log` switch, reproduce the problem (making screenshots of each step) and upload [LogFiles](http://conemu.github.io/en/LogFiles.html) to [DropBox](http://conemu.github.io/en/DropBox.html) or gist.

**Comment by adolphenom** [comment]
Here's my debug (no admin. exec, there's three tries): [See @ Dropbox](https://www.dropbox.com/sh/x86yzzn8qpw7lq3/AACU1KFzW9AhJNDlSxaM-2ETa?dl=0)

**Comment by dima-f1** [comment]
I also have this problem on Win 7

**Comment by Maximus5** [comment]
150513 is obsolete build. Update it and redo logs/screenshots.

**Comment by adolphenom** [comment]
I downloaded the latest release and installed dependencies 'cmder' needed. This bug is already fixed and it does not change the size of the window everytime I open cmder.

It can be closed. Thank you for your time :+1: :)
