### ISSUE TITLE
Permanent Tab name for specific processes

### ISSUE THREAD

**Issue by danielHalan** [cmderdev/cmder#512]
Would be nice if one could set a Permanent Tab name for specific Processes, that is a .exe including the file path. 

c:\ProjectA\Service.Host.exe
c:\ProjectB\Service.Host.exe

So one can differenciate the Tabs depending on which project is running.

The function could be included in "Rename Tab..." dialog, with an extra check-box when a process is running,
"Use always with currently active Process"

**Comment by daxgames** [comment]
Hey there,
Cmder uses ConEmu as terminal emulator, if you are experiencing a problem or want a new feature with that, please open a bug/feature request over at https://github.com/Maximus5/ConEmu

Thank you! :)
