### ISSUE TITLE
git not properly setup in v1.2

### ISSUE THREAD

**Issue by samuba** [cmderdev/cmder#513]
I just got cmder 1.2 on my fresh machine (no git preinstalled) and everytime I fire it up I get this:
"WARNING: Missing git support, install posh-git with 'Install-Module posh-git' and restart cmder."
Also "git" command is not recognized
This issue is not present in 1.1.4.1.

Also 1.1.4.1 was 249MB big, but 1.2 has only 102MB. Maybe thats a hint.

**Comment by danielHalan** [comment]
Experience the same issue, then the error stopped appearing but still no 'git' recognized, on Win8.1 x64

**Comment by gpakosz** [comment]
Same here, except issuing `Install-Module posh-git` doesn't bring `git` nor does make the warning disappear

**Comment by preyes323** [comment]
Experiencing the same issue.. after issuing the "Install-Module posh-git" command it get the following response ..
![capture](https://cloud.githubusercontent.com/assets/1038086/8001148/5df6a876-0b95-11e5-86cd-458ae4c3685d.PNG)

**Comment by MartiUK** [comment]
this is fixed: https://github.com/bliker/cmder/commit/29d1378d7afaa7bd8f78bf7cb72e524ef9556fe0

**Comment by danielHalan** [comment]
Nice, when is the next release planned?

**Comment by preyes323** [comment]
thanks! will check it out

**Comment by danielHalan** [comment]
Ah, missed that it was a PS script...

**Comment by preyes323** [comment]
It worked for me.

Thanks for the fix!

**Comment by tatoosh** [comment]
How to fix this? I got the same msg:
WARNUNG: Could not find git command. Please create a git alias or add %ProgramFiles%\Git\cmd to PATH.
Module posh-git was successfully installed.
WARNUNG: git command could not be found. Please create an alias or add it to your PATH.

**Comment by tatoosh** [comment]
Ok fixed it by replacing the profile.ps1 file. worked, thx!

**Comment by sigmap** [comment]
After updating profile.ps1 this error "WARNING: Missing git support, install posh-git with 'Install-Module posh-git' and restart cmder." still shows up.

**Comment by VKostenc** [comment]
Same thing... @sigmap

**Comment by bjornregnell** [comment]
Replaced the profile.ps1 with the fix https://github.com/bliker/cmder/commit/29d1378d7afaa7bd8f78bf7cb72e524ef9556fe0 but still gets 'WARNING: Missing git support, install posh-git with 'Install-Module posh-git' and restart cmder.' Any advice? (I have git  installed already in C:\Program Files (x86)\Git

**Comment by rfgamaral** [comment]
Same as everyone above...

**Comment by ToshioMagic** [comment]
Same. I successfully installed posh-git in cmder and restarted but it still tells me I don't have it. Attempts at reinstalling receives "WARNING: The module 'posh-git' was installed at more then one location."

**Comment by travisirby** [comment]
I was getting these errors. I installed Git For Windows from https://msysgit.github.io/ and it fixed them.

**Comment by omnus** [comment]
If git is working and you're just getting the annoying message every time you start up Cmder, you could just comment out the lines in `profile.ps1` (this is what I did for now)

```
#try {
#    Import-Module -Name "posh-git" -ErrorAction Stop >$null
#    $gitStatus = $true
#} catch {
#    Write-Warning "Missing git support, install posh-git with 'Install-Module posh-git' and restart cmder."
#    $gitStatus = $false
#}
```

**Comment by darkjstr** [comment]
I was able to remove the message by both ways: replacing profile.ps1, and installing Git for Windows.  It now states "WARNING: Enable-GitColors is Obsolete and will be removed in a future version of posh-git."

**Comment by guilhermemarconi** [comment]
Same here. I got this warning, but my `git` commands are working, even not showing me the branch I'm working on, for example.

I already have Git installed on my PC and I installed msysgit too but still not work.

**Comment by ayanamist** [comment]
Anyone install ps file but still experience the issue should notice that, the fixed version is from "development" branch but not "master" branch.

**Comment by dmxt** [comment]
I have same error. Any fix?

**Comment by podisto** [comment]
Hi you have to replace profile.ps1 and after execute the command "Install-Module posh-git" and it's ok. Thanks.
