### ISSUE TITLE
Incomplete git installation packaged with cmder v1.2 

### ISSUE THREAD

**Issue by glucas** [cmderdev/cmder#521]
Git is only partially functional from a clean installation of Cmder v1.2. Testing from a {cmd} shell, most git commands appear to work fine but `git pull` fails. 

    λ git --version
    git version 1.9.5.msysgit.1

    λ set git
    GIT_INSTALL_ROOT=C:\opt\cmder\vendor\msysgit

    λ where git
    C:\opt\cmder\vendor\msysgit\bin\git.exe

    λ git pull
    git: 'pull' is not a git command. See 'git --help'.

After a bit of experimentation (see comments on #419), my guess is that some of the files that were recently removed (004761b32f8aa47fad3929babf53e3f8972f33eb) from `vendor\msysgit\libexec\git-core` are still required.

**Comment by shytikov** [comment]
:+1: Can confirm this issue. Made new version of `cmder` useless.

**Comment by edclement** [comment]
:+1: Yeah, doing `git fetch` and then `git merge origin/BRANCH` is a pain.

**Comment by glucas** [comment]
`git svn` is another command that doesn't work.

**Comment by moloko** [comment]
Well this explains a lot of issues I was getting when I tried 1.2! I thought it was just something I had done wrong trying to remove my main install of msysgit so that only the one version bundled with cmder would be used, but I guess not

**Comment by gamer13** [comment]
I had the same problem, but 29d1378 seemed to fix it for me :)

**Comment by Morten242** [comment]
Adding back all the git-* files to ```vendor\msysgit\libexec\git-core``` restores git pull etc. So it seems like that is indeed it.

**Comment by Stanzilla** [comment]
https://github.com/bliker/cmder/commit/004761b32f8aa47fad3929babf53e3f8972f33eb was a silly change in general, why remove random exe files when you don't even know what they do? :-1:

**Comment by iki** [comment]
Temporary workaround for #503 and #521 is to download `PortableGit-1.9.5-preview20150319.7z` (or newer when available) from https://github.com/msysgit/msysgit/releases and extract it to `vendor\msysgit`.

```
cd cmder\vendor\msysgit
curl -k -L https://github.com/msysgit/msysgit/releases/download/Git-1.9.5-preview20150319/PortableGit-1.9.5-preview20150319.7z -o git.7z
7z x -aos git.7z
```

**Comment by NiklasRosenstein** [comment]
@iki Thanks, that worked!

**Comment by baxtheman** [comment]
@iki Yeah, it works, thank you

**Comment by shrayasr** [comment]
@iki: Still works, thanks :+1:

**Comment by svenluijten** [comment]
@iki Just ran into this issue, thanks for the clear solution! :smile:
