### ISSUE TITLE
Cmder crashes when AVG falsely flags it as a virus.

### ISSUE THREAD

**Issue by jontwo** [cmderdev/cmder#522]
Probably more of a problem with AVG antivirus, but if I try and pip install anything, AVG pops up with a virus warning. I add an exception, but too late, Cmder has crashed and I have to restart it.

The obvious answer is to uninstall AVG, but Cmder should be able to recover from this.

I'm on Windows 7 SP1 x64, cmder version 140707 preview.

**Comment by bondz** [comment]
I use AVG 2015 on Windows 8.1 and I have had AVG flag some programs for their "general behaviour" however Cmder does not crash before the app is added to exception. I recently upgraded to ``v1.2`` from ``1.1.4.2`` and haven't had any issues. Which version of Cmder are you running?

**Comment by MartiUK** [comment]
Have you asked AVG to add it to the global whitelist?

**Comment by jontwo** [comment]
Not sure about the global whitelist, but every time it happens, I click to add an exception. This seems to be ignored though. AVG doesn't seem to be blaming the exe though, it's more like %CONEMUDIR%\init.bat.

Anyway, I've uninstalled AVG and started using F-Secure instead. It all works fine now!

**Comment by onlineth** [comment]
Why was this closed? This is still an issue

**Comment by Stanzilla** [comment]
Because it's a false positive

**Comment by onlineth** [comment]
I understand, has anyone tried contacting AVG, though?

**Comment by MartiUK** [comment]
I'm sure they have.
