### ISSUE TITLE
Cmder Single Instance

### ISSUE THREAD

**Issue by bondz** [cmderdev/cmder#525]
When Cmder is set to single instance and tested as

```
Cmder.exe /single C:\Users
Cmder.exe /single C:\Users\Public
```

Cmder works properly opening a new tab for `C:\Users\Public` but the path of the console is set to `C:\Users\` and the variable `$env:CMDER_STATH` is also set to `C:\Users\`

Cmder works fine without the `/single` option set.

**Comment by blah238** [comment]
:+1: Also seeing this (mis)behavior.

**Comment by DoCode** [comment]
+1

**Comment by Hugo-KTM** [comment]
This issue also affects version 1.3.0
see also: #983

**Comment by Jackbennett** [comment]
Focussing comments on latest discussion in #420
