### ISSUE TITLE
storage in userprofile (instead of fixed config dir relative to the executable)

### ISSUE THREAD

**Issue by christian-korneck** [cmderdev/cmder#526]
hi,

first of all - thanks a lot for cmder - it's close to that dream of a modern Windows shell that wasn't there for ages. Thanks for making this real!

I wonder if there's any option to have one config storage per user (i.e. put the config dir in the user profile or use a per-user registry storage, like the original conemu.exe offers with the "/config" switch)?

For multi-user environments it would be very useful to only have only one read-only copy of the executables (i.e. in %programfiles%) and every user on the system can use it and have separate settings (i.e. with settings stored in the user profile or the HKCU part of the registry).

Best,
Christian

**Comment by ccoenen** [comment]
On windows, configuration belongs in the directory specified by the `%APPDATA%` variable. This is (windows 7 / 8) this directory: `C:\Users\<username>\AppData\Roaming` - but you should rather use the variable, in case the directory is mapped somewhere else.
