### ISSUE TITLE
Make cmder auto start with windows and auto minimize to the status bar.

### ISSUE THREAD

**Issue by amosbird** [cmderdev/cmder#532]
I'm using quake style slide down feature and find it very ergonomic. It will be convenient that cmder auto start and let me call it out by ctrl + `.

**Comment by glucas** [comment]
You can copy the cmder shortcut to your Windows startup folder. On Windows 8 that would be:
`C:\Users\<User Profile folder name>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`

**Comment by amosbird** [comment]
@glucas How to make it auto minimize to TSA?

**Comment by glucas** [comment]
Open the ConEmu Settings dialog (e.g. Win + Alt + P) and look for:

Main - Task Bar - Auto minimize to TSA

**Comment by glucas** [comment]
A workaround to run cmder minimized.

Create a Cmder.bat in your root cmder folder, based on this: https://github.com/bliker/cmder/blob/master/Cmder.bat

Add /MIN to the arguments passed to ConEmu:

start %~dp0/vendor/conemu-maximus5/ConEmu.exe /MIN /Icon .....

Then create a shortcut to your bat file and drop it in your startup folder. 

One downside of this approach is there is a cmd.exe window that flashes briefly when the script runs, but it does provide the behavior you want when combined with the 'Auto minimize to TSA' setting.

**Comment by aalvarado** [comment]
once you have your bat you can create a vbs script that will run it without a window:

```vb
Dim objShell
Set objShell = WScript.CreateObject( "WScript.Shell" )
objShell.Run "cmd /c cmder_start.bat", 0, True
Set objShell = Nothing
```

So no downsides now :)

**Comment by babhishek21** [comment]
Personally, I feel the best non-invasive way to achieve this is using the built-in **Windows Task Scheduler**. It provides a very easy to use interface to set up startup tasks, with customized parameters.

**Comment by kylemd** [comment]
Perfect fix for this issue is a combination of glucas and babhishek21's answers, for my purposes.

You see ConEmus icon flash up very briefly in the taskbar, but there are no other signs that it's started until you hit your hotkey.

I did exactly this in Task Scheduler (of course your paths may be different, my cmder root was C:\tools\cmder):

```
Run when user logs on
Run: C:\tools\cmder\vendor\conemu-maximus5\ConEmu.exe
Arguments: /Icon "C:\tools\cmder\icons\cmder.ico" /Title Cmder /LoadCfgFile "C:\tools\cmder\config\ConEmu.xml"
Start in: C:\Users\Kyle
```

**Comment by bllngr** [comment]
One addition, since I just stumbled over this: To start minimized with @kylemd's solution in https://github.com/cmderdev/cmder/issues/532#issuecomment-209477427, make sure to enable the option "Auto-hide on focus lose" on the Quake style page.

**Comment by sidian123** [comment]
Let me summarize what you're talking about and it work perfectly.

1. First, run Cmder by ConEmu with argument `/min`. 
    create file `Cmder.bat` in Cmder home
    ```bat
    cmd /c "vendor\conemu-maximus5\ConEmu64.exe /min /Icon icons\cmder.ico /Title Cmder  /LoadCfgFile config\user-ConEmu.xml"
    ```
2. to avoid console window opening, use vb script to disable it
    create file `Cmder.vbs` in Cmder home
    ```vbs
    Dim objShell
    Set objShell = WScript.CreateObject( "WScript.Shell" )
    objShell.Run "cmd /c Cmder.bat", 0, True
    Set objShell = Nothing
    ```
3. add **the shortcut** of `Cmder.vbs` to startup folder
    to open this folder, press `win+r`-->input `shell:startup`.

well, it's over~

**Comment by catalin560** [comment]
apparently you can do it right from the settings and don't need any bs workarounds...
Settings > Integration > Default term > check _Register on OS startup_
you can also do _Force ConEmu as default terminal_ and any time you open a cmd or powershell it will open it in cmder instead...

the only thing that bugs me is that at system startup it opens up to an empty window and you have to manually open a shell you like with CTRL + T or from the menu... I would like for it to auto open a bash window...

**Comment by brunomolteni** [comment]
I just found out you can also just edit the shortcut and add `/x -MinTSA` at the end, move this shortcut into `shell:startup` and you're golden, it starts without flashing, minimized and with a console already open :)

**Comment by Grim3ntrix** [comment]
***** "Laragon Cmder /or ConEmu Automation in Startup Guide" *****

Steps:
1 Create a batch file "Cmder.bat" in cmder home (C:\laragon\bin\cmder)
Copy this Script: 

`cmd /c "vendor\conemu-maximus5\ConEmu64.exe /min /Icon icons\cmder.ico /Title Cmder /LoadCfgFile config\user-ConEmu.xml"`

2. Create a vbs file "Cmder.vbs" in cmder home (C:\laragon\bin\cmder)
Copy this Script:

```
Dim objShell
Set objShell = WScript.CreateObject( "WScript.Shell" )
objShell.Run "cmd /c Cmder.bat", 0, True
Set objShell = Nothing
```

3. Create a shortcut of (Cmder.vbs) and Copy
4. Win + R and type "shell:startup"
5. Paste the "Cmder.vbs" in the startup folder

***** "To Start Cmder /or ConEmu minimize to TSA" *****

1. Open Cmder /or ConEmu Terminal
2. Go Over terminal Settings
3. Go to General > Task bar > Check the Auto hide to TSA > Save Settings
4. Restart PC

Done!

*********************************************************************************

"To add script in batch file and Execute NPM command"

1. Modify "Cmder.bat" file
Copy Script:

```
@echo off
cd /d "C:\laragon\www\Your-ProjectName-Here"
ConEmu64.exe /min /Icon icons\cmder.ico /Title Cmder /LoadCfgFile config\user-ConEmu.xml
npm run dev
```

2. Save and Restart PC

Done! This will work like a charm :)
