### ISSUE TITLE
Keyboard shortcuts like ctrl-a do not work anymore

### ISSUE THREAD

**Issue by ciryon** [cmderdev/cmder#533]
After installing Windows 10 tech preview Cmder seems to work great, but one very annoying issue is that Emacs-style keyboard shortcuts like ctrl-a (to move to beginning of line) no longer work. Instead ^A is displayed.

**Comment by saberone** [comment]
Same here. But I'm running on Windows 8.1

**Comment by epsitec** [comment]
I have rewired my brain to hit `Home` instead of `Ctrl+A`, however I am badly missing `Ctrl+K` which clears to the end of line. And I have not yet come up with an equivalent shortcut which does the same thing in _cmder_.
