### ISSUE TITLE
can we use Vundle to manage Cmder's vim plugins? Need some setup?

### ISSUE THREAD

**Issue by mintisan** [cmderdev/cmder#535]
1. firstly, I clone [vundle](https://github.com/gmarik/Vundle.vim) into `cmder\vendor\msysgit\share\vim\bundle`
2. then Launch `vim` and run :`PluginInstall`
3. at last, Cmder ouput `Not an editor command: PluginInstall`
![20150623195424](https://cloud.githubusercontent.com/assets/9136049/8305502/4ccf1a96-19e2-11e5-88e6-5402d9304bb7.png)

Does anyone encounter this problem?

**Comment by daxgames** [comment]
I use vundle with vim in cmder.  It works fine.

**Comment by daxgames** [comment]
I use this in Cmder using the bash shell.  It could probably work with Cmd based shell but currently that is not a requirement for me so i have not investigated it.  Its not portable at this time in that it is not a part of Cmder but I am thinking about trying to make it portable.  

My ~/.vim folder, the only thing I cloned there manually was 'Vundle.vim'

```
/c/Users/]username]/.vim/
▾ bundle/
  ▸ gundo.vim/
  ▸ lightline.vim/
  ▸ nerdtree/
  ▸ tabular/
  ▸ vim-fugitive/
  ▸ vim-ps1/
  ▸ Vundle.vim/
  ▸ YankRing.vim/
▸ colors/
▸ doc/
▸ plugin/
  colors.tar
  vundles.vim
```

In my ~/.vimrc file

```
" =============== Vundle Initialization ===============
" This loads all the plugins specified in ~/.vim/vundles.vim
" Use Vundle plugin to manage all other plugins
if filereadable(expand("~/.vim/vundles.vim"))
  source ~/.vim/vundles.vim
endif

```
In ~/.vim/vundles.vim

```
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo

Bundle 'tpope/vim-fugitive'
Bundle 'scrooloose/nerdtree'
Bundle "itchyny/lightline.vim"
Bundle "godlygeek/tabular"
Bundle "sjl/gundo.vim"
Bundle "skwp/YankRing.vim"
Bundle "PProvost/vim-ps1"

" All of your Plugins must be added before the following line
call vundle#end()            " required

filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
```

Hope this helps.

**Comment by mintisan** [comment]
@daxgames 
Very Thank you for your so detailed answer.
I know it works well in Linux as you sayed.

But what is `~` path stand for in Cmder? 

if my Cmder directory is `D:\Program Files\cmder`. And Vim directory is `D:\Program Files\cmder\vendor\git-for-windows\usr\share\vim\vim74` .

Thank you for taking the time to read this and hopefully responding.

**Comment by daxgames** [comment]
It is "%userprofile%" so "c:\users\[username]".

**Comment by daxgames** [comment]
Note vundle commands only work in com launched from a bash session.  I have been unable to make them work in com launched from cms.

**Comment by mintisan** [comment]
@daxgames It woks fine, Thanks again!

![20160105175811](https://cloud.githubusercontent.com/assets/9136049/12112200/013230c6-b3d6-11e5-8d4f-465f5cf8e29b.jpg)
