### ISSUE TITLE
How to make cmder open new tab with the current directory path 

### ISSUE THREAD

**Issue by lovedota** [cmderdev/cmder#536]
hi friends
I am newbie to cmder. How can I open new tab with Ctrl+T with current directory path. Thanks !

**Comment by kermage** [comment]
You can **_Right-Click_** on the **Tab** then select **`Duplicate root...`**

**Comment by lovedota** [comment]
@kermage It is not. Sorry for that !!!
![test](https://cloud.githubusercontent.com/assets/417914/10458940/73febf96-71f7-11e5-95fd-59fe13426137.gif)

**Comment by nevion** [comment]
for me, this really doesn't fit the bill - I want something more like control+[shift+] t on konsole/gnome terminal.  I want the new shells to start in the current directory by default.  The first shell should of course be home directory.

**Comment by sivilll** [comment]
@nevion Settings -> Keys & macro -> search for "duplicate" and bind Alt+R to what you usually have as "new tab". Ctrl+T for example, so every new tab is a duplicate.

**Comment by lovedota** [comment]
@sivilll  it works now

**Comment by sivilll** [comment]
:)

**Comment by RikkiGibson** [comment]
If there was a way to suppress the confirmation "do you to duplicate tab with root ..." that would be amazing :)

**Comment by ecampana** [comment]
@RikkiGibson Under **Settings** there is the **Confirm** field which is part of **Main** options then uncheck **Confirm tab duplicating (Duplicate root menu item)**. That should accomplish what you had in mind.

**Comment by RikkiGibson** [comment]
Thank you so much!

**Comment by svermeulen** [comment]
@Kietil's suggestions works well when using command prompt, but doesn't work for powershell, at least for me

**Comment by themindfulcoder** [comment]
Can this be done as a command?

# opens in htop in a new tab
htop &

**Comment by lioneltrebuchon** [comment]
Thanks for the nice thread! It's super nice to have so many useful suggestions in one thread.
I do not understand how to activate those settings. Let's pose that I changed:

- Keys & macro / `duplicate tab with current state...` -> `CTRL + T` (this only shows as `T` in the "Hotkey" section
- Changed the `Confirm actions` booleans to `false`

I woud like to activate that, `Save settings` doesn't, and logging out also doesn't.
Does it have to do with **where the ConEmu.xml is located**?

**Comment by 3N4N** [comment]
> @Kietil's suggestions works well when using command prompt, but doesn't work for powershell, at least for me

Same here. I guess we should look into how cmder is getting the root directory in the case of command prompt.
