### ISSUE TITLE
Use with Fish Shell

### ISSUE THREAD

**Issue by karlbateman** [cmderdev/cmder#537]
Any idea's how I might get this working with Fish Shell. I have this running with cygwin. Any pointers would be greatly appreciated.

Regards,
Karl

**Comment by jack71** [comment]
:+1:

**Comment by roy128** [comment]
:+1:

**Comment by catdad** [comment]
Oops. Wrong ref, ignore that. Can't delete it.

**Comment by umayr** [comment]
Is there any update regarding fishshell support? 

@karlbateman

**Comment by MartiUK** [comment]
@umayr Add cygwin as per wiki and install fish shell?

**Comment by rohitkrishna094** [comment]
does anyone know how to get fish working with cmder?
