### ISSUE TITLE
Enhancement / Feature request - when running as administrator first open window should run as admin. 

### ISSUE THREAD

**Issue by stefek99** [cmderdev/cmder#538]
Steps to reproduce:
- right-click on the icon
- run as administrator
- cmder is started
- the open console is not in admin mode (no protection shield next in the tab section)

For my project I need process to run with administrator rights, so right after opening new cmder I have to open a new tab. (which is not super-practical)

I think, that once I open cmder **as administator** the first opened console should be in admin mode.

**Comment by kermage** [comment]
Check #544.
