### ISSUE TITLE
Change the colors of 'ls'

### ISSUE THREAD

**Issue by oversky** [cmderdev/cmder#539]
How do I change the colors of the file types and folders when using ls?
The config file ".dircolors" in linux doesn't appear in cmder.

**Comment by italoayres** [comment]
I'm also having this issue. Actually, the output os 'ls' is similar to the windows 'dir', not like the linux 'ls'.

![image](https://cloud.githubusercontent.com/assets/759905/8634376/f2ce8bb4-27cc-11e5-8779-cdfd562b4be4.png)

**Comment by igorepst** [comment]
Not a complete answer, but may help. Use 'where ls' to discover where in the path the ls.exe is. It may look something like this:
C:\Program Files (x86)\Git\bin\ls.exe
c:\progs\Cygwin\bin\ls.exe
then investigate the usage of colors for the executable used.
Also note, there are aliases for cmder in config\aliases. And they work strangely:
the alias ls (=ls --show-control-chars -F --color $*) does print the colors
the alias la (=ls -al) does NOT
but running 'ls -al' directly on the command line results in colorful print
