### ISSUE TITLE
Context Menu "Cmder Here" Run as admin - Is this possible?

### ISSUE THREAD

**Issue by rustyd0g** [cmderdev/cmder#544]
I've been trying to get the right click context menu  "Cmder Here" to open at the current path with administrator privileges. Is this possible?

I've edited the cmd startup task by adding a \* as follows:

*cmd /k "%ConEmuDir%..\init.bat"  -new_console:d:%USERPROFILE%

However this opens the cmd menu in my home directory rather than at the current path. Any ideas?

**Comment by kmattimo** [comment]
My context menu works as administrator. I don't remember if running /REGISTER ALL after changing the startup task did anything, but try that. What I also did was adjust the properties->compatibility in Cmder.exe to 'run as administrator'. If you don't care too much about running as a standard user, that might fix it.

**Comment by blowsie** [comment]
Could someone share a working example (screenshot or code) of running cmder from context menu please?
I cant get it to work. :cry:

**Comment by kermage** [comment]
You can either:
* Change the **Cmder.exe** file privilege level in **`Properties` > `Compatibility` > `Run as administrator`**; or
* Prepend **`*`** to the default **`{cmd}`** task in **`Settings` > `Startup` > `Task`**. So it will be **`*cmd /k "%ConEmuDir%\..\init.bat" . . .`** after.

**Comment by camohub** [comment]
Click + btn > check checkbox "run as administrator" on the bottom.

**Comment by daxgames** [comment]
Won't fix. Closing.

**Comment by mikepeiman** [comment]
Having already set up Cmder to run in selected folder via context menu, I found in Settings => Startup => Tasks offered {cmd::Cmder as Admin} as an option, and selected this as "default task for new console" via checkbox. I've checked it and it works (my issue was that my new pipx and virtualenv commands were not recognized without admin privileges).

I also learned you can check your permission level with this command: ` echo %errorlevel%` where a result of `0` === admin.
