### ISSUE TITLE
compass not working with cmder ?

### ISSUE THREAD

**Issue by askbar** [cmderdev/cmder#546]
Hi

When I run `compass watch` I get a `compass : The term 'compass' is not recognized as the name of a cmdlet...` response. When I run the same command in windows power-shell it runs without any problems.... Any idea ?

**Comment by lossendae** [comment]
Is compass on windows path ?
Do you run cmder as administrator ?

**Comment by askbar** [comment]
It helps with compass in the windows path... And a restart. Thanx
