### ISSUE TITLE
not run  successfully 

### ISSUE THREAD

**Issue by assgod** [cmderdev/cmder#547]
after I installed vcredit2015 for lost dll. Another problem accured. I have use win7 utimate. from  
https://chocolatey.org/packages/cmder.portable/1.2-beta

Join-Path : Cannot bind argument to parameter 'Path' because it is null.
At G:\study-tool\chocolatey\bin\cmder\vendor\profile.ps1:2 char:29
+ $CmderModulePath = Join-path <<<<  $PSScriptRoot "psmodules/"
    + CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.Jo
   inPathCommand

WARNING: Missing git support, install posh-git with 'Install-Module posh-git' and restart cmder.

**Comment by assgod** [comment]
I think the developer should test it using win7/8/10 in vmware. we are not white rats. I hate you building such bug-king to waste me so much time. 
the alias config not work in 1.1.4 and 1.1.3

**Comment by assgod** [comment]
fuck you bug-king

**Comment by xyos** [comment]
you need to update powershell to 4.0:
https://www.microsoft.com/en-us/download/details.aspx?id=40855
