### ISSUE TITLE
Maximize single view/terminal/console to whole window

### ISSUE THREAD

**Issue by Nindaleth** [cmderdev/cmder#550]
I wonder if it is possible to temporary switch to "100% width 100% height" mode of one tab within cmder window. 

Suppose I split the window into 2×2 grid and suddenly one of the consoles needs my full attention. On Linux I can press a shortcut and the console switches to the whole window, the remaining ones are temporarily invisible until I switch back. See an example [here on YouTube] (https://youtu.be/N2h6XorbdKI?t=22s) - how he clicks on "Maximize terminal" and the one view maximizes over the remaining ones.

Is this possible in cmder? Or should I perhaps contact some of the upstream projects with this one?

**Comment by Stanzilla** [comment]
Yep, https://github.com/Maximus5/ConEmu please
