### ISSUE TITLE
ssh not working

### ISSUE THREAD

**Issue by LondonAppDev** [cmderdev/cmder#552]
With the new version of cmder (v1.2), I get this error every time I try to use 'ssh':

![image](https://cloud.githubusercontent.com/assets/4703936/8678104/91b33426-2a4a-11e5-9fba-ea962a5c6e70.png)

It works perfectly fine on the old version (v1.1.4.1)

**Comment by Kaotic** [comment]
I have too problem.

**Comment by Kaotic** [comment]
For resolve problem launch cmd.exe
View: 
powershell = http://img.kaotic.fr/6Uhx
ssh : http://img.kaotic.fr/XK5m

**Comment by LondonAppDev** [comment]
Thanks Kaotic. I am just launching Cmder.exe, is there somewhere in the config I can change it to use cmd.exe instead of powershell?

**Comment by doggy8088** [comment]
@LondonAppDev Try press the Win+Alt+P to open the Settings window.  Then check the following screenshot:
![image](https://cloud.githubusercontent.com/assets/88981/8702642/a33db278-2b4b-11e5-934a-3971cafecdf2.png)

**Comment by antoniobrandao** [comment]
@Kaotic the screenshot links are dead..

**Comment by LondonAppDev** [comment]
@doggy8088 thanks a lot!
