### ISSUE TITLE
First letter of command remains when iterating through history

### ISSUE THREAD

**Issue by louy2** [cmderdev/cmder#553]
The first letter of the first command longer than a threshold visited when iterating through history remains displayed, pushes subsequent iterations off one char, but does not affect the actual commands iterated.

Examples assume a clear prompt at the beginning.

Example:
1. First type `npm`
2. Use <kbd>↑</kbd> to iterate and see:
```shell
npm i webpack-dev-server --save-d
```
3. Use <kbd>↑</kbd> to iterate and see:
```shell
npm irun build
```
(should be `npm run build`)
4. Use <kbd>↑</kbd> to iterate and see:
```shell
nwebpack
```
(shoulde be `webpack`)
5. Use <kbd>↓</kbd> to iterate and see:
```shell
nnpm run build
```
(should be `npm run build`)
6. Use <kbd>↓</kbd> to get back to clear prompt and see:
```shell
n
```
(should be empty)

Strangely enough, the misdisplay doesn't affect the execution of the commands. The actual executed commands ignore the added letter. Short commands in the history such as `ls` and `npm` doesn't trigger this artifact.

**Comment by doggy8088** [comment]
I met the same problem also.

**Comment by louy2** [comment]
Went to test ConEmu, v150707 has no such issue. v140707 is used here, but no similar issue reports or related fix from 140707 onward discovered. Probably introduced by Cmder?

**Comment by zhaiyu-zhaiyu** [comment]
I've tested it more detailed and found that a command longer than 4 letters could trigger the problem. I do not know if you have exactly the same length of trigger one?

**Comment by zhfreal** [comment]
I got the same problem and replaced the ConEmu with the latest one(150707) and solved

**Comment by lognbow** [comment]
This is a duplicate issue: https://github.com/cmderdev/cmder/issues/506
I have the same problem. When a command larger than 4 character is displayed in the command history, the first letter will remain in the line, and kept pre-pended to other commands in the history.
I guess this has something to do with the system locale? I am using a windows 7 chinese version.

**Comment by Stanzilla** [comment]
@maximus5 ConEmu issue or clink issue?

**Comment by Maximus5** [comment]
ConEmu do not handle command line history. So that would be a clink issue, most probably.
Just get latest clink sources and build it to check if your binaries are obsolete.

Of course, you should check latest ConEmu builds.
There is no sense to report issues about [OLD BUILDS](https://conemu.github.io/en/OldBuild.html).!

**Comment by Stanzilla** [comment]
Yup indeed, guys, go test with https://github.com/Stanzilla/cmder/releases/tag/1.2.6 please.

**Comment by Stanzilla** [comment]
Just found https://github.com/cmderdev/cmder/issues/264, can you guys try this workaround, please?

**Comment by MartiUK** [comment]
@Stanzilla Would adding a space after the lambda solve this issue?

**Comment by Stanzilla** [comment]
Not sure, that would be 3 bits then, no?

**Comment by Stanzilla** [comment]
paging @mridgers for help :)

**Comment by mridgers** [comment]
It is quite possible that Clink is at fault here - I am suspicious that the lambda character is causing Readline to misbehave because it is a multi-byte character. Does the issue go away if the lambda is replaced with something ASCII-compatible like a `$`?

**Comment by Stanzilla** [comment]
Alright so just as I thought, @louy2 @doggy8088 can you test that for us? You'd have to replace the lambda character in `cmder\config\cmder.lua`

**Comment by suimong** [comment]
@Stanzilla The problem go away when I replace the lambda character with ">" or other ASCII characters.

**Comment by Stanzilla** [comment]
Thank you @suimong for confirming this. 

@mridgers any way you can fix this or do we have to change away from the lambda?

**Comment by mridgers** [comment]
I'll look into the issue and find a fix. There'is no reason at all why you should have to change from the lambda.

**Comment by Jackbennett** [comment]
Focus testing on #506
