### ISSUE TITLE
Run init.bat before any new scripts

### ISSUE THREAD

**Issue by blackpenny15** [cmderdev/cmder#554]
Hey all, apologies for asking this,
It's not a bug, and I my not be thinking about it in the right way, but I've used the Tasks to create a custom one that opens up about 7 tabs, mongodb, grunt, two node processes and a bash for each.

My question is how can I get init.bat to run before each one, I like tasty lamb :)
Also is there anyway to rather than execute something open a prompt and then execute, just because when I start and stop those processes I loose the tabs.

Thanks, apologies, couldn't find the answer anywhere.

**Comment by Maximus5** [comment]
Trivial answer hard to find? Copy your {cmd} task and append desired command after ` & `

**Comment by blackpenny15** [comment]
Thanks man, I'll give it a go in a moment.

Sent from my iPhone

On 22 Jul 2015, at 13:32, Maximus5 <notifications@github.com<mailto:notifications@github.com>> wrote:


Trivial answer hard to find? Copy your {cmd} task and append desired command after &

-

**Comment by blackpenny15** [comment]
Thanks man that worked perfectly, this can be closed.

**Comment by JanSchulz** [comment]
Close this?
