### ISSUE TITLE
ctrl + backspace doesn't work - delete word leftward to the cursor

### ISSUE THREAD

**Issue by mladenp** [cmderdev/cmder#555]
Currently when i press ctrl and backspace together nothing happens and i have **Delete word leftward to the cursor** checked
The thing is that it did work before but it somehow stopped, i didn't change anything.

**Comment by Maximus5** [comment]
Update your ConEmu

**Comment by myfairsyer** [comment]
I have the same issue on my new computer.

The checkbox is checked and the hotkey appears in the hotkeys list.

Cmder 1.3.5 (installed via chocolatey)
ConEmu 180206 [64] {Alpha}
Win 10 1803 (17134.228)
