### ISSUE TITLE
Can't get rid of "unrecognized parameter" error

### ISSUE THREAD

**Issue by Lomacar** [cmderdev/cmder#557]
At one point I changed CMDer to try to make it my default command line tool. But now whenever I try running batch script or even when installers try to run command line things I get this message popping up saying:

"Unrecognized parameter"
Valid options:
/START <path>
/REGISTER [USER/ALL]
/UNREGISTER [USER/ALL]

What the heck is that about? And how come no matter what I do that message persists? I tried going back to normal so things open in cmd.exe, but no luck. The only thing that I can do is delete or rename CMDer or the folder it is in, but then I will have to change settings in other programs that point to it, and besides, this is just wrong and needs to be fixed.

**Comment by kermage** [comment]
Check #561.
