### ISSUE TITLE
Tab names as directory names

### ISSUE THREAD

**Issue by justinmchase** [cmderdev/cmder#559]
Sometimes I have several console open at the same time, for different projects I'm working on. It would be nice if the tab names matched the name of the folder they are currently in. Something like this:

```
"%ProgramFiles%\Git\bin\sh.exe" --login -i -new_console:d:E:\code\example -new_console:t:{cwd}
```

Which would show the name `example` for the tab title. I'm manually editing them now.

**Comment by Maximus5** [comment]
Yep. Nobody reads docs.
http://conemu.github.io/en/ShellWorkDir.html

**Comment by edclement** [comment]
I left a comment (and quick fix) for this a few weeks ago:
https://github.com/bliker/cmder/issues/528

**Comment by kermage** [comment]
Use this in creating a new console or simply add as predefined task:
**`cmd /k prompt $p$e]9;3;"$p"$e\$g & title cmd`**
