### ISSUE TITLE
[Feature Suggestion] cmd.exe compatible switches

### ISSUE THREAD

**Issue by doggy8088** [cmderdev/cmder#561]
I tried to setup a cmd.exe replacement for cmder by referencing this article: [How to replace the 'cmd' alias in windows?](http://superuser.com/questions/810550/how-to-replace-the-cmd-alias-in-windows)

When I changed the value in the Windows Registry, I can run cmd.exe and Windows will launch cmder.exe instead.  

Here is the problem.  I'm using Windows 8.  When you open Windows Explorer and navigate to a folder (e.g. `G:\` ), then click on the File menu, then click the "Open command prompt" menu item.  It will fire "cmd.exe" with the following switches:

```
"Cmder.exe" /s /k pushd "G:\"
```

Then cmder.exe will launch the following error:

![image](https://cloud.githubusercontent.com/assets/88981/8906287/f8e8e97e-349f-11e5-93de-47f67203e95a.png)

As you can see, the `/k /s pushd` switches is used for cmd.exe.  So I'd like to suggest a feature that is cmder.exe could support cmd.exe compatible switches for launch cmder.exe.

Thanks!

**Comment by kermage** [comment]
Modify the **(Default)** String and add **` "%V"`** to the end.
So it will be **`C:\applications\cmder\cmder.exe "%V"`** after.

**Comment by doggy8088** [comment]
@kermage I tried many times.  This doesn't works.

**Comment by kermage** [comment]
Ok sorry, nvm that.

Actually, you can do this itself in **Cmder** but first you may want to revert the changes you made in registry earlier.

Here's how:
1. In **`Settings` > `Integration` > `Default term`**, enable **`Force ConEmu as default terminal for console applications`** and save the new setting.
2. Open the default **cmd** in any way *(under Start, in context menu, or in file menu)*. ConEmu fast configuration window should appear in the first run after save.
3. Choose ConEmu settings storage location. *I recommend anything except the registry option, for reasons:* **Portable mode and easy to copy default Cmder settings**.

>To use the default Cmder style and settings to the new ConEmu, copy ***%CMDER_ROOT%\config\ConEmu.xml*** to the ConEmu settings storage location chosen.

**Comment by doggy8088** [comment]
@kermage Thanks.  I have a further question.

Can I open `Cmder` instead of `ConEnu` by default?  I'd like to use Clink features in the Console.

**Comment by doggy8088** [comment]
@kermage Thanks.  It works. :+1: 

But I have a further question.  When I open the default **cmd**, how can I load a named task by default.  See screenshot below.  The `init.bat` file doesn't run before ConEmu start.  How can I do that?

![image](https://cloud.githubusercontent.com/assets/88981/9669453/cf840d60-52b9-11e5-89eb-b92009703d9d.png)

**Comment by jo2** [comment]
I ran into the same problem using docker quickstart terminal and found out that the path to bash.exe was invalid.

**Comment by daxgames** [comment]
`cmder.exe %1` or `cmder c:\windows` sould work with the latest version 1.3.6

**Comment by sebastianjung** [comment]
For me i had to point to the .bat file like so:

`C:\applications\cmder\cmder.bat`

**Comment by rorar** [comment]
If you found your way here, this might be your solution.
You might followed other (outdated) instructions with changing things in regedit and messed things a bit up

make sure you've correctly set up all variables correctly:
https://github.com/cmderdev/cmder/wiki/Setting-up-Environment-Variables
_Little Helper:_
Install cmder with...
System variables = cmder installed locally on your computer
User variables = Carry around cmder as portable app (for you usb flash drive)

run
**regedit.exe**
navigate to
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\cmd.exe

if the 
(Standard) key value is different from
C:\Windows\System32\cmd.exe
right click->Edit
copy and paste the above folder structure

Path key value is different from
C:\Windows\System32
right click->Edit
copy and paste the above folder structure

Fully reboot your PC with
run
shutdown /s /f /t 0

Turn on you PC...
Everythings should work as intended now.
