### ISSUE TITLE
Question/Suggestion: Could you add shift+left/right arrow support to select text?

### ISSUE THREAD

**Issue by zerodburn** [cmderdev/cmder#563]
Hi,

I am really enjoying cmder and the command line, especially typing a partial directory name then hitting tab and having cmder cycle through dir names for me!

I'm not even sure if this is possible, but it feels like it would be a very nice feature, seeing as you can do ctrl+v and ctrl+c in cmder at the moment.

Thanks

**Comment by kermage** [comment]
Tick/Enable the **Start selection with . . .**  option in **`Settings` > `Keys & Macro` > `Mark/Copy`**

**Comment by codemau5** [comment]
Why isnt this enabled by default?
