### ISSUE TITLE
Using .bashrc

### ISSUE THREAD

**Issue by ClementParis016** [cmderdev/cmder#565]
I am trying to install [thefuck](https://github.com/nvbn/thefuck) which [installation part](https://github.com/nvbn/thefuck#installation) asks to add a line in .bashrc (or equivalent).

I tried to create this ~/.bashrc file but it doesn't seem to work. Is there any way to make Cmder load the file or maybe there is another .bashrc equivalent specific to Cmder where I could put this command?

**Comment by Jayflux** [comment]
ive found that Cmder on its own doesn't read your bashrc.
If you run bash then it runs.

But yeah i would be interested in a solution too

**Comment by DanielGGordon** [comment]
Is there some sort of file that is read that is similar to /bashrc? For example if I wanted to create some new environment variable. 

What tells Cmder to user the aliases in `%CMDER_HOME%/config/aliases` ?

**Comment by rmorrin** [comment]
@DanielGGordon The `vendor/init.bat` file is what you are looking for, in particular: https://github.com/bliker/cmder/blob/master/vendor/init.bat#L50

This is ran each time cmder (or a new tab) launches so I'd avoid putting anything too complex in there, however.

**Comment by DanielGGordon** [comment]
Ok thanks that is exactly what I was looking for. Just wanted to set some path variables.

**Comment by daxgames** [comment]
%USERPROFILE%\.bashrc is now sourced in see #702

**Comment by thehackercat** [comment]
Can I add some Windows command like ```set http_proxy=http://10.178.0.84:3128``` in ```vendor/init.bat``` so I can set http proxy whenever I launch Cmder ?

**Comment by daxgames** [comment]
@thehackercat you don't want to do that because that file is replaced in update.  Create a proxy.bat file in %under_root%/config/profile.d with:

set http_proxy=http://10.178.0.84:3128
set https_proxy=http://10.178.0.84:3128
set no_proxy=127.0.0.1,localhost,.....

...... = whatever else you want to bypass proxy.

You can also do a proxy.sh that will be uses by bash

export http_proxy=http://10.178.0.84:3128
export https_proxy=http://10.178.0.84:3128
export no_proxy=127.0.0.1,localhost,.....

**Comment by thehackercat** [comment]
@daxgames Thanks, it works!

**Comment by jensenr30** [comment]
@jasonwilliams 

In order to make Cmder automatically read your .bashrc file, open Cmder.exe and go to:
Settings -> General ->Choose your startup task: {bash::bash}

This way, when cmder starts up, it automatically uses bash, which will read your .bashrc.
