### ISSUE TITLE
The term 'vim' is not recognized

### ISSUE THREAD

**Issue by spartan89** [cmderdev/cmder#566]
I am trying to create a readme file in my directory, I write: vim README
and I get this error.

<pre>λ vim README
vim : The term 'vim' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ vim README
+ ~~~
    + CategoryInfo          : ObjectNotFound: (vim:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

</pre>

**Comment by kermage** [comment]
You need the ***none*-mini** version to have all the UNIX commands, or install manually **msysgit**.

**Comment by springfieldking** [comment]
i have the same problem, but it happend only when i use powershell as startup a cmder, i work well on cmd

**Comment by Zundrium** [comment]
Having the same issue with a fresh <b><i>none</i>-mini</b> version 1.2, even when running it as an administrator or using the normal CMD instead of PowerShell on start-up.

**Comment by brentonklassen** [comment]
I'm having the same problem ever since I installed Windows 10. Now have no vim, and I can't run ls -lah.

**Comment by rmorrin** [comment]
@brentonklassen Did you install Git for Windows? If so, the issue is likely because the Unix tools have moved from Git's `bin` directory to `usr\bin`. You'll need to update your path to account for this.

Using my installation as an example: `C:\Program Files\Git\usr\bin` is required in my path.

**Comment by div-killer** [comment]
Hello guys, I have the same problem but I cannot find the solution.. Any possible ideas how to fix the error ? Im using windows 7 with git version 2.6.1.windows.1. Also does any of you can help with this following error "WARNING: Missing git support, install posh-git with 'Install-Module posh-git' and restart cmder." Using cmder. :@

**Comment by Stanzilla** [comment]
@div-killer please install the latest pre-release

**Comment by syampsijk** [comment]
hey i am having this issue.i cant use bashrc ,vim or any ,show error

**Comment by gianverab** [comment]
Once on the README, how can I save the changes and go back to the cmd?

**Comment by supreethbharadwajps** [comment]
having the same issue found anything yet?

**Comment by daxgames** [comment]
The latest cmder [here](https://github.com/cmderdev/cmder/releases) does not have this problem.

**Comment by jewelcse** [comment]
to resolve this problem you have to run vim database/database.sqlite in git bush terminal

**Comment by JonathanJRod** [comment]
To resolve this issue via PowerShell then I recommend getting Chocolatey Windows Package Manager, it's an amazing software management automation for Windows that wraps installers, executables, zips, and scripts into compiled packages. Once you have Chocolatey installed all you need to do to access Vim hassle-free is simply >choco install vim, and voila! I absolutely love Chocolatey! :)

**Comment by daxgames** [comment]
@JonathanJRod while you are correct this would install vim and make vim a runnable command it is not a valid solution in this thread.  Cmder Full includes Git for Windows which includes `vi`.  The best answer would be to create a Powershell alias for `vi` and call it `vim` which I believe the current version already does.
