### ISSUE TITLE
Setting cmder startup directory.

### ISSUE THREAD

**Issue by JPNaude** [cmderdev/cmder#57]
I'm trying to change the directory in which cmder starts up. To do this, I just added the following to the end of my init.bat file:

```
cd D:/work
d:
```

Its not very elegant but it works, and it prints some funny message as the first line of text:

![image](https://f.cloud.github.com/assets/1060109/1642878/aa8e10e2-58a5-11e3-89a9-9b2a25e14d3f.png)

Is there a better way to do this? Or at least get rid of the first line message?

**Comment by hmatijevic** [comment]
Instructions: Open Cmder -> Settings -> Tasks -> select {cmd::Cmder} (in my case). On the bottom (below textarea) you have button named "Startup dir...", and than select startup directory. Close cmder, and start again. That's it, enjoy

**Comment by thyme676** [comment]
While hmatijevic's tip was helpful, it took me a while to process as a Cmder noob. In the last step, replace %USERPROFILE% with N:\ where N:\ is the drive or location you wish to start in.

**Comment by zeakhold** [comment]
@hmatijevic very helpful,thanks!
**But** one thing must be noticed is that we should delete the default startup directory setting **before** clicking the "Startup dir..." bottom.

In my case,the default {cmd::Cmder} looks like this:
`cmd /k "%ConEmuDir%\..\init.bat"  -new_console:d:%USERPROFILE%`
Then,i change to this:
`cmd /k "%ConEmuDir%\..\init.bat"  -new_console:d:G:\myfoldername`

It works great **:)**

**Comment by tonyleeper** [comment]
Click Settings -> Startup -> Tasks
Select the first Predefined task, in my case {Shells::cmd}
On the right, under Task parameters, enter e.g.:
`/dir "c:\github"`

**Comment by akinhwan** [comment]
Interestingly enough    Under "Startup directory for new process:" it still says a different directory than what actually initiates in a new cmder tab...huh oh well

**Comment by Stanzilla** [comment]
@akinhwan can you try the latest master build and tell me if it is better now? https://ci.appveyor.com/project/MartiUK/cmder/build/1.0.521-master/artifacts

**Comment by marc-bertola** [comment]
@Stanzilla, in case you were still looking for feedback about your last post: I was running into this issue with 1.3.3, and 1.3.4, but the build you posted above works for me.

**Comment by cdtinney** [comment]
This doesn't seem to work for me:

`cmd /k "%ConEmuDir%\..\init.bat" -new_console:d:C:\foo`

It still opens in `%USER_PROFILE%`. Any suggestions?

**Comment by MalishenkoDV** [comment]
try this: for bash::Git bash :
1) changing program startup folder in settings —> task, choose btn "startup dir..." and placing necessary directory. You can place checkbox "Default task for new console" and put a hotkey. Using this hotkey -
 new "bash::Git bash" tab will be opened whis YOUR_PATH .

**Comment by essemario** [comment]
Edit the file:  \CMDER_DIRECTORY\config\user-profile.cmd
```
d:
cd Work
```

On bellow example, I've changed the directory and created a rotine to start homestead.


```
:: use this file to run your own startup commands
:: use  in front of the command to prevent printing the command

:: uncomment this to have the ssh agent load when cmder starts
:: call "%GIT_INSTALL_ROOT%/cmd/start-ssh-agent.cmd"

:: uncomment this next two lines to use pageant as the ssh authentication agent
:: SET SSH_AUTH_SOCK=/tmp/.ssh-pageant-auth-sock
:: call "%GIT_INSTALL_ROOT%/cmd/start-ssh-pageant.cmd"

:: you can add your plugins to the cmder path like so
:: set "PATH=%CMDER_ROOT%\vendor\whatever;%PATH%"

e:
cd ../../../../../Homestead

@echo off

:Ask
echo Would you like to start the Homestead?(Y/N)

set INPUT=
set /P INPUT=Yes(y) ou No(n): %=%
If /I "%INPUT%"=="y" goto yes 
If /I "%INPUT%"=="Y" goto yes 
If /I "%INPUT%"=="n" goto no

cls
echo Invalid option
echo - 
echo -
goto Ask

:yes
vagrant up
goto finalMessage

:no 
cls
goto finalMessage

:finalMessage
echo Your console is ready Mr. Chapela.
```

**Comment by bertoost** [comment]
> Instructions: Open Cmder -> Settings -> Tasks -> select {cmd::Cmder} (in my case). On the bottom (below textarea) you have button named "Startup dir...", and than select startup directory. Close cmder, and start again. That's it, enjoy

Too bad this is working, but then the "Open CMDer here" from the context menu (windows) isn't working anymore. It is forced to the startup directory all the time.
I would like to set a default directory to start when not using "Open CMDer here"

**Comment by daxgames** [comment]
@bertoost don't set that setting.  Cmder is a package of 4 different products each with its o own individual settings that sometimes conflict.  Cmder.exe will open in the current working directory or a directory you supply on the command line.  If you want cmder to launch from a shortcut in a certain folder every time configure the shortcut start directory instead.  `Cmder here` will continue to work as expected this way.

**Comment by GreatFireWall** [comment]
@daxgames Is there any solutions working both `Cmder here` and `set a default directory to start when not using "Open CMDer here"` ?

**Comment by daxgames** [comment]
Cnder.exe will open in the current 
working directory by default or you can 'cmder folder-name'

**Comment by GreatFireWall** [comment]
![image](https://user-images.githubusercontent.com/4510984/55630331-00440e00-57e8-11e9-9641-0b7097355a28.png)

I found a way.

**Comment by daxgames** [comment]
Yup that is correct

**Comment by TomatoToaster** [comment]
Wow, today I learned that Windows shortcuts let you choose where to run a program in them. Setting it to %USERPROFILE% did exactly what I wanted. Thanks!

**Comment by SteveLemire** [comment]
If you don't want to open a new console, you can do this:
- open cmder settings
- under Startup / Tasks, select you default task (_{cmd::Cmder}_)
- in the "Task parameters", add /dir with you cmder default path: `/dir "C:\CmderDirectory"`
- Save settings

![image](https://user-images.githubusercontent.com/18408683/83050855-2398d080-a01b-11ea-9e2d-05190f02b3ff.png)

**Comment by daxgames** [comment]
@SteveLemire that's a bit heavy handed as it will force that task to always open to that folder.  Maybe that's what you want but it limits some other functionality.

You could just launch Cmder using a command line argument like `cmder [folder path]` or use a Windows shortcut and specify a working directory.

**Comment by afcanop** [comment]
@SteveLemire  nice

**Comment by briansimiyuj** [comment]
> Instructions: Open Cmder -> Settings -> Tasks -> select {cmd::Cmder} (in my case). On the bottom (below textarea) you have button named "Startup dir...", and than select startup directory. Close cmder, and start again. That's it, enjoy

Thank you

**Comment by ashnur** [comment]
> Instructions: Open Cmder -> Settings -> Tasks -> select {cmd::Cmder} (in my case). On the bottom (below textarea) you have button named "Startup dir...", and than select startup directory. Close cmder, and start again. That's it, enjoy

It does say something about this issue that even after many years I still have to look this comment up to find that button.

**Comment by daxgames** [comment]
I'll say this again.   That's a bit heavy handed as it will force all tasks to always open to that folder.  Maybe that's what you want but it limits some other functionality.

You could just launch Cmder using a command line argument like `cmder [folder path]` or use a Windows shortcut and specify a working directory.

**Comment by rndph** [comment]
Now if I change the Startup Directory in the shortcut in my taskbar, Cmder will be shown twice and the actual pinned shortcut is never used.
How can I make it use the original shortcut?

![image](https://user-images.githubusercontent.com/30475702/102026674-63e55380-3d9f-11eb-8b40-c34eb63d100d.png)

**Comment by ashnur** [comment]
> I'll say this again. That's a bit heavy handed as it will force all tasks to always open to that folder. Maybe that's what you want but it limits some other functionality.

Is this some magic behind the curtains that will break without me noticing or is this something that I can correct once it occurs? Because so far I didn't notice anything.

> 
> You could just launch Cmder using a command line argument like `cmder [folder path]` or use a Windows shortcut and specify a working directory.

This doesn't help when I use ctrl+t to open a new tab, right?

**Comment by daxgames** [comment]
> Is this some magic behind the curtains that will break without me noticing or is this something that I can correct once it occurs? Because so far I didn't notice anything.

Cmder.exe will open a session in a folder passed on the command line.

It has nothing to do with new tabs or `ctrl+t`

**Comment by ashnur** [comment]
> > Is this some magic behind the curtains that will break without me noticing or is this something that I can correct once it occurs? Because so far I didn't notice anything.
> 
> Cmder.exe will open a session in a folder passed on the command line.
> 
> It has nothing to do with new tabs or `ctrl+t`

Cmder exe is already running, I press ctrl+c and it open in scoop directory where cmder is installed, every damn time. I understand that with arguments or with additional commands, or with a different operating system on a different planet with different problems this would be solved differently. I am not sure about
- your raising awareness comment about vague dangers of setting this setting, how dangerous it actually is, what I am breaking? Is there a place I could read up on this? I don't like to use issues as support mechanism.

- just opening a new tab with a shortcut that is predefined, how to add additional arguments and so forth to that?

**Comment by daxgames** [comment]
1. I don't understand or appreciate the hostility, I do this for free on my free time to help people that like Cmder.
2. I never said it was dangerous who said it was dangerous.
3. What it breaks:  Being able to open a cmder terminal in a designated folder using a command line option or a drive/folder `Open Cmder Here` context menu.
4. I just said it was heavy handed and could possibly limit other functionality, see #3, unless you really do want every session to open in a specific folder every time. 
5. Cmder opens, by default, in the `%cmder_root%` folder where the `cmder.exe` file is.  If cmder is installed in the scoop folder that explains why it opens to that path.
6. If its what you want do it.

Hopefully I have answered tou questions.  Let me know if not.

**Comment by ashnur** [comment]
I am sorry that you feel any kind of hostility, I want to assure you that was not my intent. Many thanks for the detailed answers, your analysis seems fully correct to me. It appears to me that picking any of the alternatives would be orders of magnitude much more work for something I don't use at the moment than what I do currently. I am also sorry about my first comment though, indeed the setting is not for what I thought it was. Should I edit my earlier comments to make this clear?

**Comment by daxgames** [comment]
No problem.  Whatever you want to do, I just wanted to makw syre you had answers to you queations.

**Comment by jhf** [comment]
I found this page, frustrated that cmder always suggests a scoop path after pressing ctrl+t.
Finally it dawned on me, that this is caused by how cmder is installed by scoop, and henceforth invoked.


By right clicking the Cmder icon itself, the settings there reveal a "Start in" that sets the folder to "C:\Users\$USER\scoop\apps\cmder\current".
Exiting Cmder fully, and then starting again, changes the default suggested startup directory.
![Skjermbilde 2023-11-03 173758](https://github.com/cmderdev/cmder/assets/18099/c353ae49-9050-4c88-9751-409de1fab3d8)
This is not the "Startup dir" in the task setting, but rather the starting directory for Cmder itself.
