### ISSUE TITLE
FIX: Incorrect startup directory.

### ISSUE THREAD

**Issue by kermage** [cmderdev/cmder#571]
> Creating a new console/tab defaults to the directory where the **Cmder** is *started*, *NOT* to desired directory set in **`Startup directory for new process:`**

Example:
- Start Cmder in `C:\Custom-Dir`
- Then create a new process/tab
- Set the startup dir to `C:\Another-Dir`

New tab opens in `C:\Custom-Dir` which is the first Cmder startup directory, where it should be in `C:\Another-Dir` or whatever is set in the new console creation

~~***I don't know if this is Cmder bug, or maybe i just broke something that cause this.***~~
**Found that this is not getting through [#L115](https://github.com/bliker/cmder/blob/master/launcher/src/CmderLauncher.cpp#L115)**.
--causing the initialization scripts to fail (*not moving to the wanted location*).

~~Anyway, if anyone else having this said issue, here's how I fix it:~~
Here's my quick fix:

- Comment out these lines in `%CMDER_ROOT%\vendor\init.bat` with **`::`**
```cmd
@if defined CMDER_START (
    @cd /d "%CMDER_START%"
) else (
    @if "%CD%\" == "%CMDER_ROOT%" (
        @cd /d "%HOME%"
    )
)
```
- Edit the default predefined task **`{cmd}`** in (**`Settings` > `Startup` > `Tasks`**) to
```
cmd /k "%ConEmuDir%\..\init.bat" -new_console:C:"%CMDER_ROOT%\cmder.exe"
```

**Update:** *Also for Powershell*

- Comment out these lines in `%CMDER_ROOT%\vendor\profile.ps1` with **`#`**
```cmd
if (Test-Path Env:\CMDER_START) {
    Set-Location -Path $Env:CMDER_START
} elseif ($Env:CMDER_ROOT -and $Env:CMDER_ROOT.StartsWith($pwd)) {
    Set-Location -Path $Env:USERPROFILE
}
```

- Edit the default predefined task **`{Powershell}`** in (**`Settings` > `Startup` > `Tasks`**) to
```
PowerShell -NoLogo -NoProfile -NoExit -Command "Invoke-Expression '. ''%ConEmuDir%\..\profile.ps1'''"
```

**Comment by w3cay** [comment]
Thank you !
