### ISSUE TITLE
windows 10 incompatibility

### ISSUE THREAD

**Issue by thigrand** [cmderdev/cmder#572]
". : File B:\Programy\cmder\vendor\profile.ps1 cannot be loaded because running scripts is disabled on this sys tem. For more information, see about_Execution_Policies at http://go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:3
+ . 'B:\Programy\cmder\vendor\conemu-maximus5\..\profile.ps1'
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
"

This is the welcome message when i turn cmder on windows 10.
Also i can't install bower. After install grunt he don't see the "grunt" at all. 
In cmd everything ok. I'm waiting for updates for windows 10:)

**Comment by r15ch13** [comment]
To fix that, run Powershell as Administrator und execute the command ```Set-ExecutionPolicy RemoteSigned```.
To change it back, execute: ```Set-ExecutionPolicy Restricted```

**Comment by pavelkouril** [comment]
RemoteSigned didn't work for me, I had to choose the "Bypass" execution policy.

**Comment by crisbeto** [comment]
I had it installed, before I moved to Windows 10, so after the upgrade was done everything works fine. My only issue is that the current git branch, isn't displayed, instead I get a `{git}`. The lamba sign is also replaced with `{lamb}`.

**Comment by r15ch13** [comment]
Update to v1.2 and overwrite the config files.

**Comment by thoroc** [comment]
I had the same thing as @crisbeto: Updated to Win10. So I installed from fresh, updated ConEmu from source and ran the command suggested by @r15ch13.

It is working find apart from the following warning, which is only a very minor annoyance.

> WARNING: Enable-GitColors is Obsolete and will be removed in a future version of posh-git.

**Comment by Ugarz** [comment]
Same as @crisbeto Updated to Win10 too, so I decided to delete all and start from fresh.
Same as @pavelkouril, "Bypass" saved me.
I still have an issue with zsh, but can't find out how to fix it, so if you have any advice / tips.
![150809143736](https://cloud.githubusercontent.com/assets/6050079/9154890/40dc0adc-3ea4-11e5-98e4-fc64b5a9afe2.png)

**Comment by crisbeto** [comment]
I actually fixed it by downloading again and pasting everything into the old folder. The only other issue I found is that `{hg}` gets added after the path., although I can live with that.

**Comment by Stanzilla** [comment]
that happens when you updated to 1.2 without deleting the old folder. Compare the files in the zip with what is in your folder and delete the ones that are extra.

**Comment by Ugarz** [comment]
My prompt color issue came from [posh-git](https://github.com/dahlbyk/posh-git/commit/4e778e2480f584e039b47f0db1c020a197ee9e8f) who enable colors by default now.
In [this commit](https://github.com/bliker/cmder/issues/568#issuecomment-126796913) eeree found and solved my issue with colors. :+1:

**Comment by Jayflux** [comment]
the "Bypass" execution policy worked for me

**Comment by npconfigit** [comment]
`Set-ExecutionPolicy RemoteSigned` in Windows 10 Enterprise worked for me when running powershell as Admin.
