### ISSUE TITLE
profile.ps1 doesn't have CMDER_START when duplicating tab in windows 10

### ISSUE THREAD

**Issue by drulia** [cmderdev/cmder#577]
I have installed windows and cmder, I haven't used this version on a previous windows setup, so cannot say if this is purely windows 10 problem.
Edit: previously I have only used cmd, as powershell wasn't supported the way it is now.

To the problem, when I duplicate current powershell tab, it opens in the default user location. Same happens if I execute `cmder /single /`. It does however work when I execute `cmder /start /`, then it open in the location I've passed.

I've added the line `Write-Host $Env:CMDER_START` in profile.ps1 file  just before it checks it and I see that when duplicating tab or creating in the same window a new tab, it doesn't have a `CMDER_START` and defaults to user profile location.

**Comment by kermage** [comment]
Try this. Goto (**`Settings` > `Startup` > `Tasks`**).
Remove the *`-new_console`* parameter in default predefined task **`{Powershell}`**.

```
PowerShell -NoLogo -NoProfile -NoExit -Command "Invoke-Expression '. ''%ConEmuDir%\..\profile.ps1'''"
```

**Comment by drulia** [comment]
This has one change that I can see, when executing command `cmder /single /`, it opens the new tab in the current directory rather than user profile, but it still ignores the directory I've passed. It is however a slightly more convenient behavior. It doesn't make any difference when duplicating a tab, tab opens in user profile. 

Thanks for trying to help.

**Comment by kermage** [comment]
If found this is not getting through...
https://github.com/bliker/cmder/blob/master/launcher/src/CmderLauncher.cpp#L115

**Comment by DoCode** [comment]
but CMDER_START is not set... why?

**Comment by MartiUK** [comment]
#772
