### ISSUE TITLE
Git hosts defined in .ssh/config not working in cmder

### ISSUE THREAD

**Issue by JPNaude** [cmderdev/cmder#58]
I have some git hosts defined in <HOME>/.ssh/config

Git operations in cmder does not seem to recognize these. For example, a push on a repository for which the host is defined in this config file is not working:

```
ssh: gitoffice: no address associated with name          
fatal: Could not read from remote repository.            

Please make sure you have the correct access rights      
and the repository exists.                               
```

Is there any way to get around this?

**Comment by NekR** [comment]
Why this issue is still closed? This problem persist even in new versions of cmder. cmder does not recognize already saved passwords/logins for git, and even if I re-type them again in cmder, it still did not saved credentionals.

**Comment by celorodovalho** [comment]
The same problem to me.

**Comment by crash21** [comment]
I have this as well

ssh my-server 

gives error: ssh: Could not resolve hostname my-server: no address associated with name

But if i do:

ssh -F C:/Users/user/.ssh/.config my-server

It works fine... So it takes wrong config file or what?

**Comment by klvbdmh** [comment]
The issue is still present in the latest cmder version.

**Comment by cmeza** [comment]
It seems ssh lost reference to my `/Users/MyUser/.ssh/config` (I never used `/c/Users/MyUser` path)  as well, but when starting cmder after a reboot, ssh-agent knows where my files are:

```Removing old ssh-agent sockets
Starting ssh-agent:  done
Enter passphrase for /c/Users/MyUser/.ssh/id_rsa:
Identity added: /c/Users/MyUser/.ssh/id_rsa (/c/Users/MyUser/.ssh/id_rsa)```

This just started recently. I never had problems with cmder for a long time using this setup.
