### ISSUE TITLE
start-ssh-agent not found

### ISSUE THREAD

**Issue by LondonAppDev** [cmderdev/cmder#580]
Hi,

Since downloading to the latest version of Cmder (v1.2), I am unable to run start-ssh-agent. I get the error: 
`'start-ssh-agent' is not recognized as an internal or external command,
operable program or batch file.`

Did this feature get removed?

Cheers,
Mark

**Comment by babhishek21** [comment]
I think starting **v1.2**, you simply call `agent`. It is located in the `bin` folder. To run SSH always at startup, you'll need to tinker with `/vendor/init.bat`. Look at the [Readme.md](https://github.com/bliker/cmder/blob/master/README.md) file for more information.
