### ISSUE TITLE
Mouse scrolling not responsive in console split mode.

### ISSUE THREAD

**Issue by flamestream** [cmderdev/cmder#581]
When creating a console windows with split views, only the first view will be scrollable with the mouse/touchpad.

As a side note, `ctrl` + `up`/`down` works.

**Comment by drulia** [comment]
I have noticed this issue as well. I have 3 horizontally split views and mouse scroll works fine on the top view, trying to scroll on the middle view actually scroll the bottom view and bottom view scroll is unresponsive.

`ctrl` + `up / down` does work.

P.S. running the latest versoin on windows 10.

**Comment by ktstowell** [comment]
Bump.

I have this issue as well.
