### ISSUE TITLE
Cmder Duplicate Root not work

### ISSUE THREAD

**Issue by lovedota** [cmderdev/cmder#582]
Hi guys
If I type directly the command line. It works

```
PowerShell -NoLogo -NoProfile -NoExit -Command "Invoke-Expression '. ''%ConEmuDir%\..\profile.ps1'''" -new_console
```

But if I add the new task with. When create new task, it does not work
![1](https://cloud.githubusercontent.com/assets/417914/9099859/00ee1322-3bff-11e5-9986-aec5c5a9598b.png)

**Comment by daxgames** [comment]
Works in the current version.
