### ISSUE TITLE
new console confirmation - with Ctrl-T

### ISSUE THREAD

**Issue by kcris** [cmderdev/cmder#583]
"Confirm creating new console" option is unchecked

when using the toolbar button to create new console, no confirmation is required, this is fine

but when pressing Ctrl-T to create a new console, the confirmation is requested - which is wrong

cmder version: 1.1.4.1 (140707 preview)

thanks

**Comment by Nektarios** [comment]
Hi - I wonder why this was closed? I'm having the exact same problem with cmder version 1.3.2 - no matter what options I toggle, I still get a confirmation when I open a new tab..

**Comment by Stanzilla** [comment]
Because it's an upstream issue, actually a setting you can change.

**Comment by immiao** [comment]
In Keys & Macros, Ctrl + T is bound to ``Create confirmation dialog``. I changed it to `Create new console or new window(check 'Multiple consoles in one ConEmu window`):Create()` then it works.

**Comment by mahhov** [comment]
tried binding (multiple key combinations) to `Create new console or new window(check 'Multiple consoles in one ConEmu window'):Create()`, it still prompts.

**Comment by dustintheweb** [comment]
thx @immiao, worked for me.
For anyone else trying to do this:
1. Settings > Keys & Macros > Find "Ctrl+T" and click it
2. in the "choose hotkey" filed, delete the T
3. in the top left drop down,  change to Macros
4. select one that isnt used
5. put "T" in "choose hotkey" and put `Create new console or new window(check 'Multiple consoles in one ConEmu window'):Create()` in the description

enjoy 😎

**Comment by immiao** [comment]
@mahhov I have to do both too. Thanks for adding.

**Comment by adam-ah** [comment]
I would recommend changing the default setting to the more sensible Create, instead of confirm.
Why is the default a confirm?
