### ISSUE TITLE
How to check version?

### ISSUE THREAD

**Issue by avindra** [cmderdev/cmder#587]
Is there a simple way to check the version of the tool? I've tried cmder --help, cmder -?, cmder /help, etc. None seem to work. Furthermore, is there a CLI way to use cmder itself?

**Comment by kermage** [comment]
@ `%CMDER_ROOT%` directory there is this file named **`Version v#.#`**

**Comment by avindra** [comment]
I see. Here's the problem: I switch versions by dropping files right over the directory. So, currently, I see:

```
$ ls -l Version* | awk '{print $9, $10}'
Version v1.1.4.1
Version v1.2
```

In linux it's easier to manage different versions with symlinks,  but in Windows it isn't as straightforward.

I think it would be more sensible to bake the version number into the launcher and add a command line switch to check the version with --version -v or -V. This is what most utilities do...

**Comment by Jackbennett** [comment]
You're right, the file is a cheap way of doing it. At least we can know the highest ver file wins.

I thought maybe some clever powershell way to get the checked out branch/tag and build and store that value to return but finding that, [wow](https://github.com/dahlbyk/posh-git/blob/master/GitUtils.ps1). Maybe we can make sure posh-git is on the build server then we can just use `(get-gitStatus).branch`, stick that and maybe some other info in a cmder.json and all the tools can reference this to describe themselves.

**Comment by Tset-Noitamotua** [comment]
Some news on that?

I would like to be able to do `cmder --version`

**Comment by Stanzilla** [comment]
Since cmder is not an application on its own, but a compilation of tools, this is not possible. We could create an alias like that that prints the name of the `Version`file in your cmder dir but eh, can just look at that file instead.

**Comment by Jackbennett** [comment]
Best you could do is `type $cmderRoot\version.txt` I'll make some alias
like version in the profile. It's not that useful to know though as cmder
made up if so many components. Might make it command more like`npm
outdated`.

**Comment by geekrumper** [comment]
I gave this a little thought and found the following to be the most useful one:

file: _%CMDER_ROOT%/config/user-aliases.cmd_
`version=ls %CMDER_ROOT% | grep Version*`

Just type `version` and you get `Version v1.3.5` back...
