### ISSUE TITLE
Powerline integration with cmder

### ISSUE THREAD

**Issue by Psidium** [cmderdev/cmder#590]
I'm a big fan of the Powerline on vim and on shells too, but I can't find a way to use it on cmder.
https://github.com/powerline/powerline
https://github.com/milkbikis/powerline-shell

I assume that, since cmder shows the git branch that I'm currently on and the lambda symbol, there must be some way to change the "PS1" (referencing the bash variable, not the powershell file, the place where it says the dir where I'm on). Could someone point me where to go? I'd love to make a new pull request or wiki entry on how to add powerline to cmder

PS.: I know it's possible to install on cygwin, but that's not what I want, I want cmd.exe running powerline

**Comment by glucas** [comment]
The prompt for a cmd.exe shell running under Cmder is configured by the script cmder\config\cmder.lua. 

Lua script configuration is a feature of clink (http://mridgers.github.io/clink/), which Cmder includes. I'm not sure powerline is possible here, since ultimately that lua script is just setting the Windows cmd.exe PROMPT variable. But you could ask over at the clink project, perhaps.

**Comment by Psidium** [comment]
Thanks! I'll sure look into it

Enviado do Outlook




On Wed, Aug 19, 2015 at 7:44 AM -0700, "Greg Lucas" <notifications@github.com> wrote:












The prompt for a cmd.exe shell running under Cmder is configured by the script cmder\config\cmder.lua. 



Lua script configuration is a feature of clink (http://mridgers.github.io/clink/), which Cmder includes. I'm not sure powerline is possible here, since ultimately that lua script is just setting the Windows cmd.exe PROMPT variable. But you could ask over at the clink project, perhaps.

**Comment by kaqqao** [comment]
Found these resources:

http://amreldib.com/blog/CustomizeWindowsCmderPrompt
http://codurance.com/2016/02/08/command-prompt-envy/

Haven't tried yet, but sounds promising.

**Comment by MadLittleMods** [comment]
With the recent Windows 10 update, you can now use bash and get `zsh`, [ `oh-my-zsh` ](https://github.com/robbyrussell/oh-my-zsh), and some Powerline fonts. I have [some notes in a gist](https://gist.github.com/MadLittleMods/0e38f03774fb16e8d698175e505f1f3e#cmder) on how I accomplished it.

![](http://i.imgur.com/VVivFYO.png)

**Comment by Psidium** [comment]
@MadLittleMods 

I'll be using [fish](fishshell.com) when this feature lands for everyone (currently only insiders get it).

As a note:

![a](http://turnoff.us/image/en/bash-on-windows.png)

**Comment by daxgames** [comment]
It was actually released this week and anyone can be an insider.  They just need to configure theire system to participate.

**Comment by daxgames** [comment]
True.  Was not thinking of Windows 10 for corporate use.

**Comment by lborg019** [comment]
I am currently working on my own hack.
I was able to do it with zsh using Microsoft's Unix Subsystem, but there really is no need for it.
check out this blogpost: https://amreldib.com/blog/CustomizeWindowsCmderPrompt
and gist: https://gist.github.com/AmrEldib/1d31cd54409a8ec612df

**Comment by hieudang9** [comment]
Hello there,
Any update here?  I want same thing as original post.
Thanks in advance.
