### ISSUE TITLE
Suggestion about transparency

### ISSUE THREAD

**Issue by yuntas** [cmderdev/cmder#591]
# The current cmder has a problem
- we can only do transparency as interlocking background and text...
- Therefore, If do transparency 40% ～ 70%, it is difficult to see text...

# To solve
- cmder should separate background from text

**Comment by Francisc** [comment]
I agree.

**Comment by babhishek21** [comment]
Transparency is actually handled by **ConEmu.** That kind of decoupling would be impossible IMHO.
