### ISSUE TITLE
"Inject ConEmuHk" settings slows git down considerably

### ISSUE THREAD

**Issue by ittayd** [cmderdev/cmder#592]
`git --version` works fast outside of cmder (native cmd, poweshell) but takes 2 seconds to return when the terminal is under cmder. Unchecking "Inject ConEmuHk" speeds it up

**Comment by ittayd** [comment]
It seems that after clearning this setting and working some time (with multiple reboots), console apps like 'less' and 'vim' (from the git distribution) don't work: I write 'less foo.txt' and hit enter and nothing happens.

**Comment by Maximus5** [comment]
Update your installation: https://github.com/Stanzilla/cmder/releases
Also: https://conemu.github.io/en/OldBuild.html

**Comment by ittayd** [comment]
I've downloaded the latest and have the same issue. 
In cmder:
```
C:\Users\idror> Measure-Command {git}


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 1
Milliseconds      : 511
Ticks             : 15111437
TotalDays         : 1.74900891203704E-05
TotalHours        : 0.000419762138888889
TotalMinutes      : 0.0251857283333333
TotalSeconds      : 1.5111437
TotalMilliseconds : 1511.1437
```
In the native powershell shell:
```
C:\Users\idror> measure-command {git}


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 99
Ticks             : 999033
TotalDays         : 1.15628819444444E-06
TotalHours        : 2.77509166666667E-05
TotalMinutes      : 0.001665055
TotalSeconds      : 0.0999033
TotalMilliseconds : 99.9033
```

**Comment by Maximus5** [comment]
There is no version "latest". Numbers please.

**Comment by ittayd** [comment]
1.2.6

**Comment by Maximus5** [comment]
There is no ConEmu version 1.2.6
https://conemu.github.io/en/OldBuild.html

**Comment by ittayd** [comment]
150913 alpha

**Comment by ittayd** [comment]
[Window Title]
ConEmu 150913 [32]

[Main Instruction]
No newer stable version is available

[Content]
Your current ConEmu version is 150913 alpha

Versions on server
http://conemu.github.io/version.ini
    120727c stable
    150813c preview
    151101 alpha (newer)


[OK] [Visit download page]

[Footer]
Whats new (project wiki page)

**Comment by Maximus5** [comment]
> 150913 alpha

> No newer stable version is available

> 151101 alpha (newer)

https://conemu.github.io/en/OldBuild.html

**Comment by ittayd** [comment]
and what should i do when using cmder? download the portable version?

**Comment by ittayd** [comment]
ok, downloaded the portable version, replaced in vendor, renamed, restarted cmder. Now it works fast. But, note the bug is for cmder, of which the latest version (1.2.6) is slow. I don't think it is appropriate to close it just because there is a way to manually update on of the components

**Comment by Maximus5** [comment]
Do you mind I need rewrite here the article contents which link I've posted three times?

**Comment by ittayd** [comment]
Not sure I understood. But:
The first time you wrote: "Update your installation: https://github.com/Stanzilla/cmder/releases", which I've done. It is true I didn't read the "Also" note, as well, it was not posted as the main step to take. 
You then posted the link a second time, together with reference for ConEmu, which just then made me realize you are talking about ConEmu, not cmder (which this bug is issued for), so I followed in the link, which said:"There is ConEmu internal updater. Just call it from...". I called the updater and it did nothing, which lead me to believe there's nothing to update. 
When you posted the link for the 3rd time, together with the bold '(newer)',  it was only then clear that the updater is not really an updater but a status checker.

**Comment by ittayd** [comment]
So, after downloading the latest ConEmu, the problem remains:
```
C:\Users\idror> measure-command {git}


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 1
Milliseconds      : 433
Ticks             : 14330530
TotalDays         : 1.65862615740741E-05
TotalHours        : 0.000398070277777778
TotalMinutes      : 0.0238842166666667
TotalSeconds      : 1.433053
TotalMilliseconds : 1433.053
```

**Comment by Stanzilla** [comment]
The latest release or pre-release is now always here: https://github.com/cmderdev/cmder/releases
