### ISSUE TITLE
SSH Visual Text Glitch

### ISSUE THREAD

**Issue by newtonianb** [cmderdev/cmder#594]
When I ssh into my VM from CMDER `vagrant ssh` I get an incredible glitchy text behavior. The cursor writes over old text, deleting lines in VM doesn't update the screen, just about everything that could go wrong visually with text goes wrong. Is this a known behavior?

**Comment by pavelkouril** [comment]
This happens also when I sometimes launch vim (bundled with Git for WIndows 2.5), do some git rebasing (that one uses vim), etc.

Not all the time tho, just most of the time. If this could get somehow isolated and fixed, it would be great!

**Comment by mtelesha** [comment]
I believe the issue is the terminal being communicated to the server.

My solution is with TERM


    export TERM=vt100

**Comment by extensibleseth** [comment]
I'm seeing this with vim too. It looks like it doesn't clear the screen when it's displaying a file and all blank chars are filled with whatever was on the screen before it opened.

@mtelesha How did you use export TERM=vt100 to resolve this?

**Comment by shengbinxu** [comment]
very good ! It has resolved my question.
