### ISSUE TITLE
Incompatibility with conemu 150716+ / double pinned icon on taskbar

### ISSUE THREAD

**Issue by asRIA** [cmderdev/cmder#599]
I assumed first that problem is related to conemu only, but seem that cmder is not compatible with latest implementation. 
Original ticket: https://github.com/Maximus5/ConEmu/issues/277

Steps to reproduce problem: 
* download cmder (portable version: https://github.com/bliker/cmder/releases/tag/v1.2 / cmder.7z)
* unpack to some folder 
* pin to taskbar by moving Cmder.exe onto window start bar
* run (by click on pinned link, or directly on program. Do not do auto update.
* // everything is OK, only one icon of cmder / conemu is available 
* replace content of folder vendor/conemu-maximus5 with conemu at least 150716
* run cmder by click on created link, or directly
* in taskbar you will see two icons. One belongs to cmder link, other is conemu process (with icon of cmder). Pinning newly created icon to taskbar will create direct link to conemu.exe. 

Before 150716: 
(conemu process will be under cmder icon)
![2015-08-18_22-20-58](https://cloud.githubusercontent.com/assets/4076929/9341838/896a4538-45f8-11e5-9a47-be3a03bb49be.gif)

After 150716:
(conemu will create new process (icon on taskbar) not related with cmder)
![2015-08-18_22-24-07](https://cloud.githubusercontent.com/assets/4076929/9341846/922ed9a4-45f8-11e5-9787-a9dea2bd8fcc.gif)

**Comment by asRIA** [comment]
Connected with: https://github.com/bliker/cmder/pull/600

**Comment by Stanzilla** [comment]
@asRIA can you test this and tell me if it works better? https://github.com/Stanzilla/cmder/releases/tag/1.2.5

**Comment by asRIA** [comment]
@Stanzilla  It works.

**Comment by Stanzilla** [comment]
Great to hear!

**Comment by wickles** [comment]
This issue is still happening for me in 1.3-pre. I haven't tried the previous versions but the release says it's fixed in this one?

**Comment by edgr-sanchez** [comment]
I'm also still experiencing this issue.

**Comment by promethe42** [comment]
Same issue here.

**Comment by PWalll** [comment]
Im still experiencing this issue.

**Comment by daxgames** [comment]
@PWalll what version of Cmder and Windows?  I am on the 1.3.14 and I do not see this issue.

**Comment by PWalll** [comment]
I checked other issues and got the double icon in task bar solved, thanks for caring anyway.

**Comment by daxgames** [comment]
@pwall glad you got it fixed.

Would you mind posting the fix you found or at least ref the other issues that pointed you to the solution so it helps the next person?

**Comment by PWalll** [comment]
@daxgames 
Run cmder.exe.
Pin the running program.
Right click on the pinned taskbar icon, then right click on the program name (should be "Console Emulator (x86)"), select "Property".
In the Property window, you may see that the target is "xxx\cmder\vendor\conemu-maximus5\ConEmu.exe". Change it into "xxx\cmder\Cmder.exe".
Done!
(The icon will be bugged just restart explorer.exe and it will be solved)

**Comment by daxgames** [comment]
@Pwalll Then I don't see a problem.  It's an artifact of how you did the pinning that the Cmder team has no control over.  Cmder.exe launches Conemu and exits so when you pin the running process you are indeed pinning Conemu.exe.  Changing the target to Cmder.exe causes the double pinning probably more a Windows issue than Cmder or Conemu issue.  We can't fix windows issues.  Restarting explorer is the solution to the problem

**Comment by PWalll** [comment]
I mean idk what it is but thats the only way it works... 
I hope its nothing foult of cmders team...

**Comment by daxgames** [comment]
Like I said nothing we can do about it.
