### ISSUE TITLE
Unable to `cd` to another drive

### ISSUE THREAD

**Issue by BeingTomGreen** [cmderdev/cmder#6]
I seem to be having some issues navigating to different drives. I keep C: for windows and keep all of my files on a second drive (D:)

If I attempt to navigate to `D:\Dropbox\Work\Repos\` nothing happens, yet if I run `ls D:\Dropbox\Work\Repos\` I am presented with the full contents of the folder.

Example:

```
C:\
λ cd D:\Dropbox\Work\Repos\

C:\
λ ls D:\Dropbox\Work\Repos\
!Misc              detail-admin-theme    dotfiles    ip-info            project-euler  runescape-feeds  simple-core-old  steam-api-old
Lua-intro          diablo-3-api          github-api  laravel-4-vagrant  recipies       sabstrap         simpleCMS        wardrobe
beingtomgreen.com  diablo-3-api-package  home        maths              runescape-api  simple-core      steam-api

C:\
λ cd D:\Dropbox\Work\Repos\maths
```

If I attempt to create a new tab with a startup location of `D:` I get:

```
The system cannot find the path specified.

D:\>ls
'ls' is not recognized as an internal or external command,
operable program or batch file.
```

And nothing seems to work, I assume this is at least partially related to #4.

In the mean time I have just modified the `init.bat` to initially `cd` into `D:`.

**Comment by Jayflux** [comment]
Was this ever fixed?
It doesn't work for me

**Comment by Jayflux** [comment]
ok fixed it
To change the drive you do not need to "cd d:" but "d:"

**Comment by keeprock** [comment]
@Jayflux Many thanks!

**Comment by thetypebeast** [comment]
The solution `cd /z` or `Z:` did not work for me. For both, I receive the message, "The system cannot find the drive specified." It works fine in command prompt.

![screen shot 2016-03-16 at 4 48 25 pm](https://cloud.githubusercontent.com/assets/5041699/13830052/647b044c-eb98-11e5-8443-cdf788e818be.png)

![screen shot 2016-03-16 at 4 58 06 pm](https://cloud.githubusercontent.com/assets/5041699/13830051/6478e8a6-eb98-11e5-9e0c-ab626d5868c9.png)

**Comment by Jayflux** [comment]
@thetypebeast try it against the latest alpha release and if it still doesn't work raise a new issue mentioning your OS version and alpha release version

latest alpha release here: https://ci.appveyor.com/project/MartiUK/cmder/build/artifacts

**Comment by thetypebeast** [comment]
It works in the alpha release using the command `Z:` but not `cd \z`. After changing the drive letter, I'm able to navigate the folder tree on that drive as normal with `cd`.

![screen shot 2016-03-17 at 10 47 00 am](https://cloud.githubusercontent.com/assets/5041699/13851919/f72ff8e8-ec2d-11e5-9f4f-ec8a1bea1083.png)

**Comment by teal-front** [comment]
i use D: is ok...

**Comment by avently** [comment]
Start new console in specified path on other drive doesn't work. Also Explorer's integration doesn't work with other drives (only with C:// no matter where cmder is located). 
ConEmu works as expected in all situations (cd, and new console, and integration).

Can you fix it?

**Comment by oussamasic** [comment]
use only D: and you will go to the D driver

**Comment by thetypebeast** [comment]
@teal-front & @oussamasic: I don't have access to the `D:` drive, nor do I have the authorization to map the network drive I wish to access to `D:` . As I stated on March 17, @Jayflux's solution worked for me. Thanks!

**Comment by oussamasic** [comment]
@thetypebeast for me it works you need only to write D: 
![cmder_2](https://cloud.githubusercontent.com/assets/12549631/21073278/bd667b56-bed1-11e6-81e4-d15f261682d7.jpg)

**Comment by MDJ2014** [comment]
cd d:

**Comment by daxgames** [comment]
@mdj2014 try 'd:' or 'cd /d d:'  your syntax is wrong and would fail in any cmd session not just cmder.

**Comment by MDJ2014** [comment]
It worked for me. That is why I posted it.

**Comment by johanguse** [comment]
Tks @MDJ2014

**Comment by DevWL** [comment]
This is not a cmder issue. If the "cd D:" is not working try
cd /D D:

**Comment by williamhowf** [comment]
thanks!

**Comment by Davidvd45** [comment]
awesome!

**Comment by masaab** [comment]
For me to change from H:\ to C I wrote Just C: and it  worked

**Comment by Darvesh696** [comment]
For changing the drive use `/d`.
`cd /d D:`
or 
`cd /d E:`

**Comment by gdev2018** [comment]
works for me to run cmdir with /START "V;/path"

**Comment by G33kNoob** [comment]
> ok fixed it
> To change the drive you do not need to "cd d:" but "d:"

thanks

**Comment by AkgunFatih** [comment]
> I am afraid this is not related to cmder in any way, but anyhow
> if you want to change to folder on another drive you should use `cd /d` or if you just want to change the drive use `D:` (just type that in, It is kinda weird)

lol it works soo strange

**Comment by Mansour-J** [comment]
On my PC it behaves very interestingly.... I manged to find it tho...

`C:` will take me to the drive C
`D:` will take me to the drive D


it interesting how all below combinations are not working....

```
cd D:
cd C:
cd D/
cd C/
cd C:\
cd C/
```

I was about to give up tho....

**Comment by solooo7** [comment]
@Mansour-J try
 cd /d D: 
or
 cd /d E:

**Comment by nico1988** [comment]
@BeingTomGreen you can use e: & cd /a/b/c
and use alias like this 
this is some alias demo
```
;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here
e.=explorer .
a.=cd C:\Users\Administrator
gl=git log --oneline --all --graph --decorate  $*
ls=ls --show-control-chars -F --color $*
pwd=cd
clear=cls
history=cat -n "%CMDER_ROOT%\config\.history"
unalias=alias /d $1
vi=vim $*
cmderr=cd /d "%CMDER_ROOT%"
cdxs=e: & cd \work\xsyx\
```

**Comment by nico1988** [comment]
![image](https://user-images.githubusercontent.com/19890788/74011374-a0e3fb00-49c2-11ea-8cdf-54d72b42fef1.png)

**Comment by daxgames** [comment]
@nico1988 you are making this too hard.  Windows cmd.exe `cd` supports this natively: `cd /d e:`
