### ISSUE TITLE
Git for Windows 2.5

### ISSUE THREAD

**Issue by sqrt** [cmderdev/cmder#602]
Git for Windows 2.5 [has been released](https://github.com/git-for-windows/git/releases/tag/v2.5.0.windows.1), essentially deprecating msysgit. Are there any plans to switch soon?

Edit: Just a little addition: There are a few [very nice features for power users](https://github.com/blog/2042-git-2-5-including-multiple-worktrees-and-triangular-workflows) in 2.5.

**Comment by SandHilt** [comment]
+1

**Comment by IlianYotov** [comment]
+1

**Comment by ccoenen** [comment]
+1

**Comment by doggy8088** [comment]
+1

**Comment by FlTr** [comment]
+1

**Comment by Stanzilla** [comment]
https://github.com/bliker/cmder/pull/605
