### ISSUE TITLE
api-ms-win-crt-runtime-l1-1-0.dll is missing error (Windows 8.1)

### ISSUE THREAD

**Issue by ruud00000** [cmderdev/cmder#604]
I get following error trying to install cmder full version from your site http://gooseberrycreative.com/cmder/ just now. Itried bith the .7z and the .zip version.

Program can't start because api-ms-win-crt-runtime-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem

Bug or can I fix this myself?

**Comment by Stanzilla** [comment]
Use this https://github.com/Stanzilla/cmder/releases/tag/v1.2.1

**Comment by ruud00000** [comment]
Tx!


Verstuurd door Outlook voor Android





On Sun, Aug 23, 2015 at 4:47 AM -0700, "Benjamin Staneck" <notifications@github.com> wrote:
Use this https://github.com/Stanzilla/cmder/releases/tag/v1.2.1

---

**Comment by DanielGGordon** [comment]
Stanzilla, why not make a pull request on the current master branch to apply this fix?

**Comment by Stanzilla** [comment]
@DanielGGordon The fix is already in the dev branch, not my call to move it to master.

**Comment by babhishek21** [comment]
Ref #501
