### ISSUE TITLE
Git autocomplete is not working as in git bash

### ISSUE THREAD

**Issue by ostap1010** [cmderdev/cmder#607]
Autocomplete function in git (when pressing TAB button) has some problem when "/" symbol is present in the branch name. For example, there is "feature/base1" and "feature/base2" branches in git repo. If to type "git checkout f"+TAB in cmder it produces: "git checkout feature". If to type same in git bash it produces "feature/base". It is better when autocompletion gives as much hint as possible.

**Comment by pc2459** [comment]
I've worked around it temporarily by grabbing an updated version of clink completions from https://github.com/vladimir-kotikov/clink-completions/releases/tag/0.2.0 and replacing what's in vendor > clink-completions

**Comment by vladimir-kotikov** [comment]
@Stanzilla, close please as `development` should contain [clink-completions@0.2.1](https://github.com/vladimir-kotikov/clink-completions/releases/tag/0.2.1) already
