### ISSUE TITLE
Crawling for executables in /bin

### ISSUE THREAD

**Issue by ghost** [cmderdev/cmder#61]
How do I get ruby running with this? I placed the `ruby-1.9.3-p484` folder into `/bin/`

Am I missing something here. Also - how (where) do I put binaries so I can use them. Like GIT, etc?

Also - when I've dropped in Ruby, do I have to start every command with the `ruby` prefix, or can I step into ruby?

Here's what I done. Excuse the noobness.

![...](http://f.cl.ly/items/0J2T3n3x0i2n370o3007/Image%202013-11-29%20at%205.46.14%20PM.png "...")

**Comment by GlassGruber** [comment]
Sorry to bump this up again but is this feature available atm? I've tried dropping a folder in `/bin` with an .exe file in it but cmder can't find it. 
Am I missing something? I've updated to the last 1.3.2 version

**Comment by daxgames** [comment]
Try this.  I have not done this but it should work.

1. Drop ruby folder in %cmder_root%\vendor
2. Edit %cmder_root%\config\user-profile.cmd
3. Add this on a new line 'set path=%cmder_root%\vendor\[ruby_folder]\bin;%path%' without the single quotes. Replace [ruby_folder] with the actual name of the ruby folder.

**Comment by GlassGruber** [comment]
Thank you @daxgames but this way I'm forced to list every single folder I'm interested instead of an automatic way to have every subfolder crawled, isn't it?

**Comment by daxgames** [comment]
Yes.  That's the way Windows and every other operating system works.  Not sure how you think it would work any other way.

**Comment by GlassGruber** [comment]
Yea ofc, what I mean is related to this #63 and #190 with a script to do this automatically. I guess I should have commented in the above mentioned issues, I thought this was more appropriate since the problem was first araised here.

**Comment by daxgames** [comment]
Understand.  I think since this is an old as well as a closed issue the dev team has decided not to pursue it.

It would have to be some sort of script that ran as a part of cmder startup that dynamically updated the path based on a directory containing exe, com, bat, and cmd files for the running session further slowing startup that is already a complaint of many cmder users.  I would not count on it geting added any time soon.

**Comment by GlassGruber** [comment]
I see, thank you!

**Comment by Jackbennett** [comment]
If you use the powershell console you can stick this in your profile to add the paths at the start of each console. But this is is only going to add each subdir. If you want to scan the path for subdirs fir `/bin` or `.exe` the I guess copy/modify our one that scans for `.git` [that's here](https://github.com/cmderdev/cmder/blob/61849dc7fd3e3d84ba14848abeaee1fac63a431e/vendor/profile.ps1#L63)

```powershell
$env:path.insert(0, ((ls ($env:CMDER_ROOT+'\bin') -Directory).fullname -join ';') + ';')
```

or, create a symbolic link to the exe in that bin folder but you need admin permissions for that.

**Comment by GlassGruber** [comment]
Interesting thank you! I'll give it a try, I use the normal cmd.exe tab but I was thinking about shifting to powershell lately. 

Also the symbolic link looks like a nice workaround!

**Comment by Jackbennett** [comment]
The latest w10 can symlink without admin rights otherwise Yeh it's a good
way.

**Comment by agaring** [comment]
So, not a perfect fix for everybody, but, while looking around for a solution to this problem myself I found that a commit back on 13 Mar 2018 (997e799138497dc30cff2d6b707f9096c81462d8) added the possibility to change the maximum recurse depth when adding in `%cmder_root%\bin` and `%cmder_user_bin%`. 

The argument to is called /max_depth and can go from 1 to 5, 1 being the default.

More detail: [Changing Cmder Default `cmd.exe` Shell Startup Behaviour Using Task Arguments](https://github.com/cmderdev/cmder/blob/master/README.md#changing-cmder-default-cmdexe-shell-startup-behaviour-using-task-arguments)
