### ISSUE TITLE
No Unix commands?

### ISSUE THREAD

**Issue by venatiodecorus** [cmderdev/cmder#610]
Hello,

I removed completely my old Cmder install and downloaded the latest version. Now I have no Unix commands such as git ls or ssh available to me. I just copy over files from the archive then run them and I get this behavior. I've confirmed there are no handles or running processes still using those files as well when I copy.

**Comment by rmorrin** [comment]
Unix commands come from git for windows. This can either be installed on your machine and included in your path, or is included as part of the 'cmder full' package.

If you do not have git installed on your machine,  It may be that you have replaced your older version with 'cmder mini' (a version which does NOT include git and the accompanying tools). I would check again which version you downloaded.

**Comment by venatiodecorus** [comment]
I made sure to download the full version.

**Comment by venatiodecorus** [comment]
I have Git for Windows installed as well but I figured Cmder was supposed to use the msysgit tools that it is distributed with. When I echo %PATH% within cmder, I don't see the msysgit directory listed.

**Comment by rmorrin** [comment]
Do you have Git installed in some non-default location? It's normally found in `C:\Program Files (x86)\Git` or similar.

Cmder [should check](https://github.com/bliker/cmder/blob/development/vendor/init.bat#L31) for an existing msysgit directory, and add it to the path if found.

If for some reason that check isn't happening, you could try to add it to your path manually.

**Comment by venatiodecorus** [comment]
Ok well I added the msysgit bin directory to my PATH manually and I guess that works. But also, cmder used to know that '~' corresponded to my user directory. Now when I do cd ~, it tells me The system cannot find the path specified. Am I crazy or did this used to work?

**Comment by JanSchulz** [comment]
I think the problem is that git for windows 2.5 does not add unix commands to the path:

```
λ path
PATH=C:\Users\...\Dropbox\Programme\cmder\bin;C:\Program Files\Git\bin;C:\Program Files\Git\share\vim\vim74;[...];C:\Program Files\Git\cmd;[...];

λ dir "C:\Program Files\Git\bin"
17.08.2015  15:19            32.256 bash.exe
17.08.2015  15:18           139.776 git.exe
17.08.2015  15:19            32.256 sh.exe

λ dir "C:\Program Files\Git\cmd"
17.08.2015  15:18           139.776 git-gui.exe
17.08.2015  15:18           139.776 git.exe
17.08.2015  15:18           139.776 gitk.exe
25.08.2015  12:07             3.031 start-ssh-agent.cmd
```

I installed the "make git available in cmd" version.

**Comment by steph-ben** [comment]
On my installation I needed to change this line to make it work:
https://github.com/cmderdev/cmder/blob/development/vendor/init.bat#L83

```
- set "PATH=%PATH%;%GIT_INSTALL_ROOT%\usr\bin;%GIT_INSTALL_ROOT%\usr\share\vim\vim74"
+ set "PATH=%PATH%;%GIT_INSTALL_ROOT%\bin;%GIT_INSTALL_ROOT%\usr\bin;%GIT_INSTALL_ROOT%\usr\share\vim\vim74"
```

```
λ git --version
git version 1.9.5.msysgit.0
```

**Comment by kavyarangaiah** [comment]
bc is not working for my cmder....it says bc is not recognised as internal or external command. what to do ??

**Comment by kavyarangaiah** [comment]
![screenshot 163](https://user-images.githubusercontent.com/38176965/38464819-45942028-3b31-11e8-855b-614dfd47ab4f.png)

**Comment by daxgames** [comment]
What is bc?

**Comment by kavyarangaiah** [comment]
Basic calculator...

On Apr 8, 2018 17:27, "Dax T Games" <notifications@github.com> wrote:

What is bc?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/cmderdev/cmder/issues/610#issuecomment-379544552>, or mute
the thread

**Comment by daxgames** [comment]
Did you try any other commands.  I doubt 'bc' is a part of git-for-windows.

On April 8, 2018 8:04:26 AM kavyarangaiah <notifications@github.com> wrote:
Basic calculator...

On Apr 8, 2018 17:27, "Dax T Games" <notifications@github.com> wrote:

What is bc?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/cmderdev/cmder/issues/610#issuecomment-379544552>, or mute
the thread

**Comment by kavyarangaiah** [comment]
Other than bc, what else I can try?? Please suggest me.....

**Comment by Stanzilla** [comment]
bc is not part of cmder, end of story :)

**Comment by kavyarangaiah** [comment]
Okkk.. Thanks
