### ISSUE TITLE
[ Solved ] How to I change to width of Split screen divider ( border ) line. 

### ISSUE THREAD

**Issue by snehesht** [cmderdev/cmder#613]
![screenshot](https://cloud.githubusercontent.com/assets/5787031/9485868/8b041bd6-4b8d-11e5-956e-60ff7c53afe1.png)

**Comment by jonnymaceachern** [comment]
See https://github.com/bliker/cmder/issues/596

**Comment by snehesht** [comment]
Hi, I think you misunderstood the question.  The Plane divider ( Green line in above pic ) is about 3px I want to reduce it to 1px. How do I do that ?

**Comment by snehesht** [comment]
After some trial and error on conemu config file I found the solution. I'm posting it here for others to see. 

Edit ConEmu.xml file and change the below 'data' value from 04 to 01 or 02.
<value name="Multi.SplitWidth" type="hex" data="04"/>
<value name="Multi.SplitHeight" type="hex" data="04"/>
