### ISSUE TITLE
how i can change the mysysgit folder

### ISSUE THREAD

**Issue by rockdrigo** [cmderdev/cmder#620]
i have  msysgit in the folder C:\DEV\Git  how i can use the aliases in cmd without install the full version of cmder?

**Comment by JanSchulz** [comment]
You could change the `vendor\init.bat` file to look at your git path:

```
:: Check if msysgit is installed
@if exist "%ProgramFiles%\Git" (
    set "GIT_INSTALL_ROOT=%ProgramFiles%\Git"
) else if exist "%ProgramFiles(x86)%\Git" (
    set "GIT_INSTALL_ROOT=%ProgramFiles(x86)%\Git"
) else if exist "%CMDER_ROOT%\vendor" (
    set "GIT_INSTALL_ROOT=%CMDER_ROOT%\vendor\msysgit"
)
```

-> replace `@if exist "%ProgramFiles%\Git` with `@if exist "c:\DEV\Git`

**Comment by JanSchulz** [comment]
The proper sulution would probably be to to change the default `init.bat` to run `where git.exe` and look at the results -> as long as git is in path this will work...
