### ISSUE TITLE
Cmder console remain unused text on screen

### ISSUE THREAD

**Issue by doggy8088** [cmderdev/cmder#623]
I met this problem for a couple of months.  It still doesn't fixed yet.  Here is the steps to reproduce this problem.

1. Open cmder window (Command prompt)
![image](https://cloud.githubusercontent.com/assets/88981/9657827/1932f4a0-5277-11e5-9921-378f9348a144.png)

2. Paste a text on it.  For example, `http://cmder.net/`
![image](https://cloud.githubusercontent.com/assets/88981/9657833/212dd526-5277-11e5-9c47-7630b569f3f8.png)

3. Then press Ctrl+Z undo changes.  You'll see "h" remain on window and the "h" can't be deleted unless you clear the screen by "Ctrl+L".
![image](https://cloud.githubusercontent.com/assets/88981/9657839/2f689810-5277-11e5-9757-d3c240277528.png)

4. If you just paste the same text again.  The screen will like the following screenshot.
![image](https://cloud.githubusercontent.com/assets/88981/9657844/420f9900-5277-11e5-93d7-eb4528e7f155.png)

I also recorded a short video to show this problem. See here: https://youtu.be/sQ5ZURcAi5Q

Also, I tried to use *cmd+clink* and there is no problem at this combination.  Only happen when using *cmder+clink*.

**Comment by doggy8088** [comment]
I find out the root cause finally.  The default "{lamb}" character cause this problem.

Here is my workaround:

1. Edit **%CMDER_ROOT%\vendor\init.bat** file
2. In the Line 12, I changed ```@prompt $E[1;32;40m$P$S{git}{hg}$S$_$E[1;30;40m{lamb}$S$E[0m``` instead of ```@prompt $E[1;32;40m$P$S{git}{hg}$S$_$E[1;30;40m$G$S$E[0m```

**Comment by fghhfg** [comment]
Where can I change it in the version 1.3.1 of cmder?

**Comment by jackusay** [comment]
ref https://github.com/cmderdev/cmder/issues/506#issuecomment-438977819
