### ISSUE TITLE
tail command not found

### ISSUE THREAD

**Issue by cjbrowne** [cmderdev/cmder#625]
λ tail
tail : The term 'tail' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ tail
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (tail:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

I have Cmder and Cmder\bin in the system path (not my user's path but that shouldn't matter), and the posh-git installation seemed to go fine (I get the git branch indicator at the end of the prompt, for example, and I can use 'git').

What could be wrong?

**Comment by Stanzilla** [comment]
The UNIX commands in cmder are actually the ones provided by msysgit (now: git for windows) if you don't have that installed, they will not work.

**Comment by cjbrowne** [comment]
I do have git for windows installed, and did have when I filed this issue.

I have solved the problem for myself by adding C:\Program Files (x86)\Git\bin to my system path, but I'm a tad worried about conflicts with builtin Windows utilities.  If I have problems, I'll revisit my solution.

**Comment by Stanzilla** [comment]
Ah great, I already fixed my fork of cmder regarding PATH and also updated to the latest version of Git for Windows, if you want to test it, you can find it here https://github.com/Stanzilla/cmder/releases/tag/1.2.5

**Comment by cjbrowne** [comment]
Nice :) I'll check it out later today if I get time.

**Comment by arnisjuraga** [comment]
In my case, `tail.exe` is located under `Git\usr\bin folder`.
Try both paths:

```
C:\Users\---username---\AppData\Local\Programs\Git\usr\bin                 <----tail.exe is here
C:\Users\---username---\AppData\Local\Programs\Git\mingw64\bin\
```
