### ISSUE TITLE
 msysGit has been superseded ,consider to switch to Git for Windows 2.x?

### ISSUE THREAD

**Issue by ihipop** [cmderdev/cmder#627]
as the msysGit  https://github.com/msysgit/msysgit said in commit https://github.com/msysgit/msysgit/commit/088d25f31e34544c90a3c3f7342ea424333f2805
>msysGit has been superseded by Git for Windows 2.x
https://git-for-windows.github.io/

Any consideration to switch to ```Git for Windows 2.x```?

**Comment by rmorrin** [comment]
This is already being discussed over at #605!
