### ISSUE TITLE
Strange Vim behaviour after Git for Windows upgrade

### ISSUE THREAD

**Issue by rmorrin** [cmderdev/cmder#628]
Upgrading the installed msysGit (1.9.5) to the newer Git for Windows (2.5.1) introduces a number of compatibility issues when the included Vim is used within Cmder.

*Before (msysGit 1.9.5):*
![msysGit 1.9.5](https://cloud.githubusercontent.com/assets/2046187/9758996/08ea0574-56e2-11e5-8395-b4d778694c3d.png)

*After (Git for Windows 2.5.1):*
![Git for Windows 2.5.1](https://cloud.githubusercontent.com/assets/2046187/9759056/6a405120-56e2-11e5-9ddc-802d78b6c14d.png)

A couple things I've picked up on so far:
* 256 colour themes don't seem to work. I use [vim-hybrid](https://github.com/w0ng/vim-hybrid) but in theory, any similar theme shows the same result.
* Occasional screen tearing/flickering when scrolling through files.
* Some files show garbage (whitespace?) characters, e.g: `^M` for Windows CRLF line-endings (I couldn't reproduce this consistently, though).
* The white background shown above remains in the prompt after quitting Vim.

I do use a somewhat customised .vimrc (plugins, etc). I've managed to simplify it while still reproducing the issue here: https://gist.github.com/rmorrin/bdd79a716a9079060732

It's worth mentioning this occurs in both Windows cmd, as well as Git's included bash (both in Cmder). When using the Mintty terminal included with Git for Windows everything works as expected. My guess is that there is some difference between the Vim versions included within each Git installation.

**Comment by Stanzilla** [comment]
Parts of this could be fixed by this https://github.com/git-for-windows/git/issues/364

**Comment by variab1e** [comment]
When I issue vim --help in the console the output is briefly displayed and then immediately suppressed.  Seems to be related.

**Comment by Stanzilla** [comment]
Can you guys try https://github.com/Stanzilla/cmder/releases/tag/1.2.6 please, it has updated Git and ConEmu versions which both claim to have vim fixes.

**Comment by rmorrin** [comment]
@Stanzilla After a little fiddling around (it seems the newer vim loads files from `.vim` a la *nix systems instead of `vimfiles`) I managed to get your build set up.

Unfortunately the situation has not improved: the same configuration works fine with the vim included in msysGit 1.9.5, but fails on Git for Windows' vim.

Curiously, I tried running vim from git-bash.exe (included in vendor\git-for-windows) which worked nicely:

![git-bash](https://cloud.githubusercontent.com/assets/2046187/10134762/27d0ac10-65e0-11e5-9a28-bfed1cccc0ae.png)

Could this mean that the problem lies somewhere within ConEmu/Cmder?

**Comment by variab1e** [comment]
Ah yes, it most certainly does. I never updated! Vim works perfectly fine (at least for me). When ConEmuHk.dll is not loaded. You can unload this by ensuring that it is unchecked under Settings > Features

**Comment by Stanzilla** [comment]
Nice investigation. Maybe @Maximus5 can chime in on this.

**Comment by Maximus5** [comment]
Vim in git-for-windows v2.x do not post any ANSI sequences to WinApi (and ConEmu therefore). All ANSI codes are processed by msys2 kernel (same as cygwin's one) and all bugs, I believe, must be addressed to their maintainers.
https://conemu.github.io/en/CygwinAnsi.html

**Comment by ValYouW** [comment]
Hi,

I have a strange behavior with vim also, after using vim the scrollbar disappear...
Before:
![image](https://cloud.githubusercontent.com/assets/4539636/10233091/279ee1be-6895-11e5-8121-2d1830b24bab.png)

After:
![image](https://cloud.githubusercontent.com/assets/4539636/10233098/30b39f24-6895-11e5-97ea-cb6f6139ac42.png)

Any ideas? thx.

**Comment by pavelkouril** [comment]
Another of the weird behavior (in PowerShell cmder) is after vim exits, it screws up the display of older entries and puts the input for new command at the top of terminal instead after last command (happens in like 80% of case).

**Comment by DanielGGordon** [comment]
I have this problem when using {cmd}, and I also had this problem before trying out version 1.26 (Stan's)

**Comment by variab1e** [comment]
Try the new conemu. It seems to have fixed everything for me at least.

**Comment by DanielGGordon** [comment]
@variab1e Which version? I am using the latest stable version. I am also having this problem when using my git bash task with the 1.4.1.1 build as well.

**Comment by Maximus5** [comment]
There is no "latest stable" version at all, so you can't have it.
http://www.fosshub.com/ConEmu.html

**Comment by DanielGGordon** [comment]
@Maximus5 you are right. So I tried using the most recent alpha version with cmder 1.1.4.1 and 1.26. Right now on 1.1.4.1 Cmder works just fine. However when I open Git Bash (Git 2.5 something) as one of my tasks, I still have the same problem.

Should I use the latest 'preview' version instead?

**Comment by rmorrin** [comment]
@variab1e Can you confirm what was fixed for yourself? Are you seeing the correct colours within vim now? I've tried with the latest ConEmu 'alpha' build and still have the same issue.

**Comment by variab1e** [comment]
The appear to be right. As well as --help properly printing and not destroying previous output. I'm on git version 2.5.2.windows.2

Also though I upgraded vim independently as well if I remember right:
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Sep 11 2015 14:42:15)

ConEmu 151006

I did a few other things too, but I don't think that would have changed anything past base. I can make a full dump of everything if you think it'd help.

**Comment by rmorrin** [comment]
@variab1e Do you have everything as a portable Cmder install? It'd be awesome if you could post a version somewhere so I can test with my own vim configuration.

If not, I am happy to wait until Cmder updates to new releases of the relevant tools :+1:

**Comment by MartiUK** [comment]
@rmorrin We're working on it, watch this space.

**Comment by DanielGGordon** [comment]
So are we simply waiting for a Git update to fix this VIM issues, or is there something can be changed in Cmder/Conemu?

**Comment by MartiUK** [comment]
@DanielGGordon See @Maximus5's comment: https://github.com/cmderdev/cmder/issues/628#issuecomment-143799317

**Comment by variab1e** [comment]
@rmorrin sorry for the delay, yep I am  [uploading my directory right now](https://github.com/variab1e/cmder) good idea anyways, because it took me about 2 weeks of tinkering to get it working the way I wanted it.

I re-wrote a bunch of the scripts around powershell and cmd.exe as well as ssh-agent. 

Plus you'll probably find a bunch of ridiculous comments and backup files in there, sorry! It wasn't cleaned for public consumption. But if it helps it was worth it.

**Comment by rmorrin** [comment]
@variab1e Unfortunately I was still seeing the same problem with your modified Cmder install.

However, I have noticed that replacing the vim executable in `vendor\git-for-windows\usr\bin` with the ['Win32 console executable'](http://www.vim.org/download.php#pc) from Vim's download page fixes the colours (but unfortunately introduces other issues). Presumably this is to do with the reason mentioned in [Maximus5's comment](https://github.com/cmderdev/cmder/issues/628#issuecomment-143799317).

**Comment by Maximus5** [comment]
> but unfortunately introduces other issues

What issues exactly?

**Comment by variab1e** [comment]
@rmorrin I would definitely recommend trying the updated repo I have, I've done 10-11 revisions since then. I believe I have that fixed pat.

**Comment by rmorrin** [comment]
@Maximus5 I only tested briefly, but noticed the following:

* Cursor not displaying in both normal and insert mode
* Ignoring syntax files in `~/vimfiles/syntax/` seems to be searching for them in the same folder as the executable (see below).
![Vim messages](https://cloud.githubusercontent.com/assets/2046187/11208596/0534f2d2-8d14-11e5-862a-2af6404ed653.png)

@variab1e Thanks, I'll be sure to try it out!

**Comment by Maximus5** [comment]
@rmorrin
Of course different builds of vim behaves differently. For example cygwin version requires \n as line delimiter, official one accepts \r\n. Paths and names of config files are affected to (.vimrc, _vimrc and so on).

As for cursor, show the [StatusBar](https://conemu.github.io/en/StatusBar.html) which cmder hides. (yeah, it takes so many space and user do not need to know what happens with their terminal, grrr).
StatusBar shows what happens with your cursor. I suppose, your vim is configured so the cursor is vanished from screen.

**Comment by variab1e** [comment]
@rmorrin Yes, I believe I have definitely fixed everything you are talking about. It is nothing with conemu - but rather settings and the associated suite of surrounding software.
