### ISSUE TITLE
Latest release : Windows 7 : Windows cannot find ".../vendor/conemu-maximus5/CpmE,u.exe"

### ISSUE THREAD

**Issue by don-dev** [cmderdev/cmder#629]
I have set cmder up on multiple win 7 environments, however the latest release on a windows 7 professional env. I have hit this error for the first time. I have seen this bug in your logs but they seem to be dated years ago and the fixes involve a release.

can you provide a fix? a workaround not dependent on a release?

**Comment by Stanzilla** [comment]
Can you try installing a recent release, for example https://github.com/Stanzilla/cmder/releases/tag/1.2.6 please?
