### ISSUE TITLE
Where is the hotkey binding stored?

### ISSUE THREAD

**Issue by doggy8088** [cmderdev/cmder#630]
I'd like to bind "Win+Delete" on "Close active console: Close(0)".  I just can't enter "Delete" key in the "Choose hotkey" field.

![image](https://cloud.githubusercontent.com/assets/88981/9771343/002250aa-5768-11e5-898d-1ed6c20ddef2.png)

I checked the config\ConEmu.xml file.  The hotkeys seems not registered here.  Does anyone know where it is?

**Comment by rmorrin** [comment]
They should be stored in the ConEmu.xml file, looks like the the particular hotkey you are looking for is under the 'Multi.Close' key.

There is an easier way to achieve what you want though; the dropdown next to the input allows you to select 'Delete' as one of the options, with the three on the far right allowing up to 3 modifier keys to be specified (one of which is the 'Win' key):

![capture](https://cloud.githubusercontent.com/assets/2046187/9809970/af07300c-5864-11e5-8f97-ab1c4d8df06d.png)
