### ISSUE TITLE
alias can not support pipeline symbol 

### ISSUE THREAD

**Issue by foxundermoon** [cmderdev/cmder#632]
eg:   alias.bat  gitpushall=git remote | xargs -L1 git push --all
if alias contain the  | symbol, it will faild.

**Comment by DanielGGordon** [comment]
What version are you using? The pipe seems to work fine for me

`ls | grep Desktop` will return only the folder named 'Desktop'. So it might be something else, like using xargs

**Comment by rmorrin** [comment]
I have an alias for almost the exact same thing which works fine. Looks to be an issue with the way alias.bat works.

As a workaround, you can edit the alias file directly, it can be found at `[CMDER PATH]\config\aliases`.

**Comment by foxundermoon** [comment]
@DanielGGordon 
my version is V1.2  compiled by my self. 
You can add the alias with pipeline by command?
can  you post your alia.bat content for me. thanks very much  .

**Comment by foxundermoon** [comment]
@rmorrin 
yeah, direct-to-edit the alias  config file is right.  
thanks

**Comment by glucas** [comment]
Cmd shell aliases are really doskey macros, and doskey has its own special characters for pipe, redirect, etc. See https://technet.microsoft.com/en-us/library/bb490894.aspx. 

To create an alias with a pipe, use $b instead. For example:

alias gitpushall=git remote $b  xargs -L1 git push --all
