### ISSUE TITLE
Extremely unresponsive behavior using Git for windows 2.5.x

### ISSUE THREAD

**Issue by avindra** [cmderdev/cmder#635]
Hi,

cmder just randomly locks up sometimes, which restarting cmder seems to fix.

You can reproduce this issue consistently by starting a git shell and spamming `CTRL+C` over and over. cmder will lock up and you won't get control back for a good minute. There are other times this happens, but this is the best way to reproduce the issue.

Here is how I launch my portable git install (extracted to `C:\App\git`):

```
call %WINDIR%\SysWOW64\cmd.exe /c  C:\App\git\bin\bash.exe --login -i  -new_console:d:%USERPROFILE%
```

Changing it to this:

```
C:\App\git\bin\bash.exe --login -i  -new_console:d:%USERPROFILE%
```

doesn't help either.

**Comment by Stanzilla** [comment]
https://github.com/git-for-windows/git/issues/227
