### ISSUE TITLE
Problem with install on window 7?

### ISSUE THREAD

**Issue by thearabbit** [cmderdev/cmder#637]
I have problem with window
`The program can't start because api-ms-win-crt-runtime-l1-1-0.dll is missing`.

**Comment by chaami** [comment]
Hi,
Installing the Visual c++ 2015 Resitributable (x64) fixed the issue for me.
You can download them from the Microsoft site directly.
Kind regards.

**Comment by babhishek21** [comment]
Refer #501

**Comment by neOnSHiFT** [comment]
@chaami I'm in x86 machine, I installed Visual C++ Redist 2013 and 2015 both x86 version but I that message still appear.
Do I have to install the x64 version too?

**Comment by chaami** [comment]
The x64 version is the one that you need...

**Comment by neOnSHiFT** [comment]
Nevermind I just downloaded cmder in @Stanzilla repo and it works

**Comment by thearabbit** [comment]
I tried to install `VC 64/86`.
But don't work
```js
The program can't start because api-ms-win-crt-runtime-l1-1-0.dll is missing...
```
Please help me.

**Comment by thearabbit** [comment]
And then I tried install `VC 2013-2015` both.
But still don't work.

**Comment by Stanzilla** [comment]
https://github.com/cmderdev/cmder/releases/tag/v1.2.9

**Comment by thearabbit** [comment]
Thanks, now it work fine.
