### ISSUE TITLE
Filenames with special characters e.g. ! are not handled correctly

### ISSUE THREAD

**Issue by gsbabil** [cmderdev/cmder#64]
Cmder has trouble handling filenames with special characters such as !. It doesn't make any difference if the name is quoted in single or double quotes.

e.g. both of the commands below would fail since !! gets expanded by the shell.

```
move "blah!!.mkv" "blah.mkv"
move 'blah!!.mkv' 'blah.mkv'
```

**Comment by Jackbennett** [comment]
This works now so long as the filename with special chars is in quotes or the special chars escaped

```
mv "blah!!.txt" blah.txt
mv 'blah!!.txt' blah.txt
mv blah^!^!.txt blah.txt
```
