### ISSUE TITLE
Having ls, cat, etc

### ISSUE THREAD

**Issue by kud** [cmderdev/cmder#641]
On the website, you say:

`Oooh yes! If you decide to use the slightly bigger msysgit version, you will have all Unix commands ready in PATH so that you can git init or cat instantly on every machine.`

But how to do it? For instance I don't have "ls" right with cmd.exe even if clink is installed...?

**Comment by Stanzilla** [comment]
Try this please https://github.com/Stanzilla/cmder/releases/tag/1.2.5

**Comment by kud** [comment]
Perfect, thanks. Plus you updated clink, great. :+1:

**Comment by leogout** [comment]
@Stanzilla thank you very much, i had a lot of issues from locked files or unset aliases, and ine one shot you resolved all my troubles !
