### ISSUE TITLE
Emoji support

### ISSUE THREAD

**Issue by lapin-b** [cmderdev/cmder#642]
Everything's in the title

**Comment by AlbertFM** [comment]
+1

**Comment by bhaveshgohel** [comment]
+1

**Comment by svenluijten** [comment]
+1

**Comment by arieljannai** [comment]
+1

**Comment by daxgames** [comment]
I don't get it.  What will emoji support be used for in a terminal/she'll app like Cmder/ConEmu.

Can someone explain to me what this means?

**Comment by lapin-b** [comment]
If you want another test printer for PHPUnit which prints emojis, it coule be useful. Except I don't have any other uses examples for the emojis support

**Comment by AlbertoFdzM** [comment]
Because they are useful. There are so many terninal tools that has started using them. Brew, some npm packages,  git for github, etc.

**Comment by Stanzilla** [comment]
useful how?

**Comment by AlbertoFdzM** [comment]
Cross and ticks to show list of process that has gone well and wrong, warning signal for the warning messages of a process,  the bug is usually used to identify bugs,  and a long long etc.

They are helpful providing a way to bring meaning with less words

**Comment by ticklemynausea** [comment]
Why all the questining of usefulness? If it's not useful to you, that's fine. But there's no good reason the best console for windows should not support something Linux and Mac OS  users already have had for quite a while.

**Comment by Stanzilla** [comment]
Still not our call, please make an issue over at ConEmu

**Comment by asternaut** [comment]
+1

**Comment by neolectron** [comment]
+1

**Comment by laurent22** [comment]
+1 I imagine it's difficult to support but that would definitely set ConEmu aside from other Windows terminal emulators, since none of them currently support Emojis.

**Comment by Stanzilla** [comment]
@laurent22 this is not the ConEmu bugtracker though.

**Comment by atefBB** [comment]
+1

**Comment by limpep** [comment]
+1

**Comment by daxgames** [comment]
You could all +1,000,000,000 this here and it will do no good.  This is not a feature for the cmder team to add.  If you want emoji support it would need to be added to ConEmu or maybe even Windows Console subsystem by Microsoft.  ConEmu is a component of Cmder and not developed by the Cmder Team.  I think you all know Microsoft.

Good Luck!

**Comment by DRSDavidSoft** [comment]
@daxgames Just as a perspective to where Emojis are used, [`Yarn`](https://yarnpkg.com) is a package manager for node that does this wonderfully:

<img src="https://cloud.githubusercontent.com/assets/5603632/19337371/0ef8e748-90eb-11e6-902a-1f671f37a779.png" width=300>

#### Related issues:
- https://github.com/yarnpkg/yarn/issues/960
- https://github.com/yarnpkg/yarn/issues/405

Here's [how this is displayed](https://github.com/yarnpkg/yarn/issues/405#issuecomment-248809161) in Cmder as of writing this:
<img src="https://cloud.githubusercontent.com/assets/4303/18737149/f18efcc8-8042-11e6-9de8-a2225486744e.png" width=450 />

I know it's not related related to Cmder and we should just wait for https://github.com/Maximus5/ConEmu/issues/554 but I thought it'd be a good idea to mention it here.

**Comment by daxgames** [comment]
@DRSDavidSoft Thanks for the good explanation.  I get it, it would be nice for tools that use them.  I just never associated the word emoji with this.

**Comment by omidkrad** [comment]
```javascript
const logger = {
  info: (msg) => console.info('📢i️nfo', msg),              
  warn: (msg) => console.warn('⚠️WARNING', msg),
  error: (msg) => console.info('❗❗ERROR❗❗', msg),         
  debug: (msg) => console.debug('🦟DEBUG:', msg),
};
```

**Comment by omidkrad** [comment]
Looks like the new Windows Terminal [supports](https://github.com/microsoft/terminal/issues/814) emojis! 🥳
