### ISSUE TITLE
As admin CMDER_ROOT not set in Powershell 

### ISSUE THREAD

**Issue by variab1e** [cmderdev/cmder#643]
Title says it all, the only place I see a mention of this is in `cmder/launcher/src/CmderLauncher.cpp` on line 114 & 115

	SetEnvironmentVariable(L"CMDER_ROOT", exeDir);
	SetEnvironmentVariable(L"CMDER_START", path.c_str());

I have a workaround currently of putting 

	# if CMDER_ROOT not set (for some reason in admin mode this doesn't happen)
	if( -not $env:CMDER_ROOT ){
		$env:CMDER_ROOT = Split-Path -Path $PSScriptRoot -Parent 
	}

into vendor/profile.ps1

**Comment by daxgames** [comment]
This is fixed in the development branch for all three shell types cmder, powershell and bash and can be closed. See #702
