### ISSUE TITLE
Using cmder inside Remote Desktop session is extremely slow

### ISSUE THREAD

**Issue by Blackbaud-DanHamlin** [cmderdev/cmder#644]
I have noticed that when i open Cmder inside of an RDP session that it is extremely slow.  I have tried connecting to Windows 7/8/10 machines with the same results and from Windows 8/10.

**Comment by mynkow** [comment]
I also have extremely slow cmder but only when I connect trough remote desktop. The host machine is Windows 7 enterprise. KBD input takes 4-5 seconds per character. Opening cmder takes more than 6 seconds. All other console windows (cmd, bash, PS) are OK

How can I help to fix this?

**Comment by bigbearzhu** [comment]
I had the same issue. However, after I turn off "Active Window Transparency" under Features -> Transparency -> Alpa transparency the responsiveness improved a lot.
