### ISSUE TITLE
Ignoring path value when running as admin.

### ISSUE THREAD

**Issue by cadillaclizard** [cmderdev/cmder#645]
When running cmder from registry by `"C:\cmder\Cmder.exe" /SINGLE "%V"` `%V` value is ignored when we open cmd.exe as an admin `cmd /k "%ConEmuDir%\..\init.bat"  -new_console:a` and cmd is opened in home directory.
(It works when we use `cmd /k "%ConEmuDir%\..\init.bat"  -new_console:d`)

**Comment by Memphizzz** [comment]
For me it actually looks like its the /single parameter which ignores the PATH.

**Comment by benallan** [comment]
For me, the path value seems to be ignored however I start cmder (with or without /SINGLE).
