### ISSUE TITLE
File /vendor/conemu-maximus5/ConEmu.exe not found.

### ISSUE THREAD

**Issue by AidanRB** [cmderdev/cmder#646]
When I run the program in Windows 7, I get "The system cannot find the file (root of program)\/vendor/conemu-maximus5/ConEmu.exe."

**Comment by Stanzilla** [comment]
Which version did you download and install?

**Comment by AidanRB** [comment]
The latest as of 3:00 9/25, I don't have it in front of me.

    --Aidan

**Comment by Stanzilla** [comment]
Can you try this one, please https://github.com/Stanzilla/cmder/releases/tag/1.2.6

**Comment by AidanRB** [comment]
Thanks, I downloaded it weird the first time.

**Comment by DanielGGordon** [comment]
Hey Stan what about your development branch: https://github.com/Stanzilla/cmder/tree/development
? Which one would you like people to test. I've pointed people (on https://gitter.im/bliker/cmder) to your link above.

**Comment by Stanzilla** [comment]
The releases I tag are from the development branch, the others (even master) are not really worth checking out as they either are feature branches for pull requests or a complete mess (master) :)
