### ISSUE TITLE
Is there any hotkey jump to "Search" box?

### ISSUE THREAD

**Issue by doggy8088** [cmderdev/cmder#647]
For the following screenshot, is there any hotkey that can jump cursor to "Search" box?

![image](https://cloud.githubusercontent.com/assets/88981/10124196/d3b107aa-6581-11e5-897a-2e8beb061237.png)

**Comment by glucas** [comment]
By default this is bound to Apps+F. 

You can change the binding via the Settings dialog. Go to 'Keys & Macro' and look for the row for 'Find text in active console'.

**Comment by Maximus5** [comment]
* https://conemu.github.io/en/SettingsHotkeys.html
* https://conemu.github.io/en/AppsKey.html

**Comment by doggy8088** [comment]
Thanks a lot! :+1:

**Comment by petrasl1976** [comment]
Hi,
I am using putty as terminal in ConEmu, but this "Find text in active console" (CTRL+F) does not work :( Any ideas how to look up for text in putty console? Any alternatives to this?
Thanks

**Comment by Maximus5** [comment]
@petrasl1976 How do you think ConEmu may search in the another [GUI application](https://conemu.github.io/en/ChildGui.html)? No sense.

**Comment by petrasl1976** [comment]
The same like it can search in CMD or POWERSHELL window buffers. It works well even CMD and POWERSHELL are "another GUI application". Why not PUTTY?

**Comment by Maximus5** [comment]
Read the link I've posted!
CMD and POWERSHELL are not GUI applications!!
