### ISSUE TITLE
Ctrl + D?

### ISSUE THREAD

**Issue by namanyayg** [cmderdev/cmder#648]
In a previous version, Ctrl + D duplicated the current tab. Now it closes Cmder.

Is there a way to restore Ctrl + D's functionality? Or if the shortcut has been re-assigned, what is the new shortcut?

Sorry for the noob question - I tried creating my own shortcut via ConEmu settings, but wasn't able to figure out how to do so.

**Comment by doggy8088** [comment]
Which version do you use?

I use Ctrl+D a lot too.  I don't like to change this default key binding.

**Comment by namanyayg** [comment]
@doggy8088 I recently upgraded to 1.2.6 from 1.1.3 (iirc) recently, where I found the keybindings changed. There is no default shortcut for 'duplicate' now, it seems.

**Comment by DanielGGordon** [comment]
I'm pretty sure I'm using 1.1.x, and CTRL + D actually closes my current window.

**Comment by ccoenen** [comment]
<kbd>Ctrl+D</kbd> on unix sends an `EOF` (end of file) character. Maybe this is what happens here? `EOF` would exit a bash, for example.

**Comment by ccoenen** [comment]
On 1.1, Ctrl+D does the following:

* Git Bash: Closes (consistent with [this StackOverflow answer](http://unix.stackexchange.com/questions/110240/why-does-ctrl-d-eof-exit-the-shell))
* Cmd.exe: Nothing at all
* Powershell: `^D` appears on the commandline

But in no case do i get another tab or window. Currently, there's no shortcut assigned for duplicate. But you can set any shortcut you want here: Click the icon in title bar, select "settings" (or use Win+Alt+P). This window comes up, where you can navigate to Keys&Macros

![cmder-settings-keyboard](https://cloud.githubusercontent.com/assets/124909/10234145/09396ec6-6893-11e5-9b27-d59cfe70d0c3.png)

**Comment by namanyayg** [comment]
@ccoenen I guess <kbd>Ctrl</kbd> + <kbd>D</kbd> being `EOF` is the correct reason for default behavior.

Nonetheless, I was successfully able to remap the combination to "Duplicate tab with current state of root process" from your screenshot. 

Thanks!

**Comment by RikkiGibson** [comment]
Bash and similar shells allow you to override the "ctrl+D to end session" behavior to basically do nothing. This is handy because ctrl+D is also the shortcut to go down a page in programs like `less`. If you're mashing that key to skim a file you don't want to accidentally hit that combo again outside of `less`.

When I open cmd.exe normally and just type ctrl+d it produces a `^D` character. Something cmder is doing on top of cmd.exe is making it so ctrl+D closes the tab. Is there any way I can configure this to have the same behavior as on a regular cmd.exe session?

**Comment by liquiddandruff** [comment]
Agree with above. Rebinding ^D causes cmder to eat the key combination and makes programs like `less` unusable. Leaving the ^D makes it easy to accidentally close the terminal. The usual instructions to set environment variables don't work since we're not in bash. Would like an answer for this.
