### ISSUE TITLE
Cannot switch to mapped network drive

### ISSUE THREAD

**Issue by akarienta** [cmderdev/cmder#649]
I have mapped network drive to letter `S:` in the system. 

I am using this command to mapping:
```
net use s: //server/folder/subfolder /user:username
```
The password is prompted.

In `cmd` I can do command `S:` to switch to this drive but it doesn't work in cmder. Getting this error:
```
S:
The System cannot find the Drive Specified.
```

**Comment by Maximus5** [comment]
What **shell** you are using in cmder??

**Comment by akarienta** [comment]
@Maximus5 Git Bash. But I have also enabled cmd commands, e.g. I can run `ls` as well as `dir`.

**Comment by akarienta** [comment]
I reinstalled cmder yesterday and problem is gone. I don't know what was wrong but I can't no longer reproduce this issue. Closing.
