### ISSUE TITLE
When exiting vim, cursor goes to first line of terminal instead of the end of it

### ISSUE THREAD

**Issue by pavelkouril** [cmderdev/cmder#656]
Seems to happen everytime when the terminal is "full". If there is space, it goes at the end, but when it's full, it goes to the beggining (as you can see in the screenshot) - instead of scrolling the terminal and placing it on the new line.

![image](https://cloud.githubusercontent.com/assets/636912/10428199/16d0a6fc-70f0-11e5-9a24-6be8541bbfac.png)

This is especially problemtic when doing `git rebase -i`, which fills the console window multiple times and result looks pretty messy. :(

Relevant technical info:

- Vim 7.4.872 (from Git for Windows)
- cmder 1.2 w/ PowerShell
- ConEmu 150513 [32]
- Windows 10 x64

The only "unusual" setting is I have the Quake-style console via ConEmu, but I'm not sure if that causes the issue or not.

**Comment by MartiUK** [comment]
Does the same issue happen when running the same commands with cmd?

**Comment by pavelkouril** [comment]
Ok, I just checked that and it does happen as well with cmd in cmder. Pure "cmd.exe" doesn't have this issue.

Also, I updated Git for Wndows to latest version (2.6.1), but it includes the same vim version and the error is still there.

**Comment by pavelkouril** [comment]
Another update: I tried disabling the "Quake style" console, and the issue persists even with the "classic" look.

**Comment by MartiUK** [comment]
Same issue as #628

**Comment by pavelkouril** [comment]
Is it really the same as #628? Sure, it is about vim, but that one is about weird colors, not about weird behavior after exiting?

**Comment by MartiUK** [comment]
@pavelkouril ANSI escape codes much like how colours are displayed do control the cursor position, if vim isn't reporting the codes correctly as in #628, then this would also be a similar issue.
