### ISSUE TITLE
Cmder do not run if username has spaces between

### ISSUE THREAD

**Issue by jorgevilaca82** [cmderdev/cmder#658]
Cmder do not run if username has spaces between

My username on windows is 'Jorge Luiz' and cmder show a error message saying 'c:\Users\Jorge' does not exist

**Comment by MartiUK** [comment]
Are you using cmd or powershell?

**Comment by jorgevilaca82** [comment]
cmd on win10

**Comment by jorgevilaca82** [comment]
please ignore, I download the source package, not the compiled one.

Sorry.
