### ISSUE TITLE
Stuff that should not be in the release zips

### ISSUE THREAD

**Issue by Stanzilla** [cmderdev/cmder#662]
* Icons  
  * [x] Which of those do we actually need to ship with the product? The psd probably not, are the other icon sizes used anywhere?
* Scripts
  * [x] I don't think users need those
* Vendor
  * [x] There is a tmp folder in there, is it used for something? Why do we ship it?

**Comment by MartiUK** [comment]
1. I believe only the .ico file is needed.
2. The tmp folder can be safely ignored, this is for building only.
