### ISSUE TITLE
Restart As Admin bug

### ISSUE THREAD

**Issue by danwellman** [cmderdev/cmder#669]
Using the full version of Cmder 1.1.4.1 on x64 Windows 10

When choosing Restart as Admin from right-clicking the tab, the tab restarts as admin, but I see a message at the top of the console:

> The system cannot find the path specified.
> File not found - C:\Program\config\aliases

Also, in a non-git folder I see {git} after the path and {lamb} before the prompt:

![image](https://cloud.githubusercontent.com/assets/373222/10558142/5a2025e2-74bd-11e5-9cdf-f75ba523a391.png)

**Comment by Stanzilla** [comment]
Please use the latest version and test again.

**Comment by danwellman** [comment]
I installed the latest version, and while 'Restart as Admin' works as expected, just launching Cmder defaults to Powershell, which throws a different error:

![image](https://cloud.githubusercontent.com/assets/373222/10561654/914415d8-752b-11e5-832a-d0952dd51fbb.png)

I've gone into settings, then Startup, and tried to set the Specified named task to {cmd}, but no matter which settings I change, the 'save settings' button stays grayed out and un-clickable.

**Comment by Stanzilla** [comment]
Please test with the latest pre-release

**Comment by danwellman** [comment]
I'm using 1.2, what is the latest pre-release?

**Comment by Stanzilla** [comment]
https://github.com/cmderdev/cmder/releases 1.2.9

**Comment by danwellman** [comment]
thanks, that works as expected :)
