### ISSUE TITLE
Ctrl+C no longer works as expected

### ISSUE THREAD

**Issue by Alxandr** [cmderdev/cmder#671]
Not sure if this is a bug, or an enhancement or simply something I need to change in the config, so if this is expected behavior and I'm just being stupid, I apologize in advanced ;).

I just installed the new 1.2.9 release. I've a newly formatted PC, so I just grabbed the latest release from github releases. In the previous version, when I pressed Ctrl+C, it would send the Ctrl+C to the underlying application. In the new version, I have to press enter first (or after). Otherwise it'll just display `^C` in the console.

Following are some images to illustrate, and reproduce steps:

![image](https://cloud.githubusercontent.com/assets/112334/10576253/2449d62e-7662-11e5-80ec-e0c281cc8d30.png)

Here, I've run `node`, and once the prompt is up I've hit `Ctrl+C` (nothing else). If I then hit enter, the following happens:

![image](https://cloud.githubusercontent.com/assets/112334/10576266/3f74fbd6-7662-11e5-978a-f911b6319b37.png)

It seems, both the `Ctrl+C`, and the `enter` is sent to the node process only after the first enter is pressed. However, if I reverse the order of things, and run `node` and press enter, everything works as expected.

![image](https://cloud.githubusercontent.com/assets/112334/10576281/6a693fc8-7662-11e5-8003-2435b9f307ca.png)

**Comment by DanielGGordon** [comment]
I'm pretty sure that's normal behavior for `node`. I logged onto my remote web server and just tried that, and I had the same response.

**Comment by DanielGGordon** [comment]
I am pretty sure this is expected behavior from `Node`. I tested this behavior on my remote web server and got the same thing. Not all programs handle `ctrl + C` the same way.

**Comment by MartiUK** [comment]
Thanks @DanielGGordon.

@Alxandr,
I'm not having this issue when running `node` under PS or cmd in an unmodified 1.2.9 build, `ctrl + C` is being sent straight away.

**Comment by devmckeon** [comment]
I'm having the same issue. I believe this is the desired behavior for cmder, but I don't see a simple setting to forward ctrl+__ to the shell and instead use ctrl+shift+__ for CUA bindings.

@DanielGGordon I think you are misunderstanding the issue. This behavior is certainly not normal for nodejs. The first screenshot displays the affected (not normal) behavior. The last screenshot shows the behavior one would expect if familiar with common shells.

**Comment by devmckeon** [comment]
This does not seem to be a node issue, but rather a cmd issue. I don't get this behavior in default cmder nor in linux, I do see it in "cmder here" as well as in plain cmd and ps.

**Comment by calclavia** [comment]
I'm running into the same issue when running Python programs

**Comment by Stanzilla** [comment]
@calclavia windows 10 insider build?
