### ISSUE TITLE
Restore last session with history on start

### ISSUE THREAD

**Issue by duncanawoods** [cmderdev/cmder#672]
The last session would include:
- each shell
- layout
- current directory
- history

Bonus - be able to save a session with a name and restore different sessions by name.

**Comment by MartiUK** [comment]
Is Settings > Startup > "Auto save/restore opened tabs" not enough?

**Comment by duncanawoods** [comment]
Ah, thanks.

I spent 20 minutes trying to find a way to do this. The settings and docs are... challenging. Having hierarchical settings and putting options on both parents and child nodes tripped me up here. IMHO easier for the user to only put options on child nodes and only use hierarchy for organisation. Windows 10 is good example - a simple list of sections down the LHS of a settings dialog is more usable.

**Comment by MartiUK** [comment]
Settings in ConEmu isn't up to me, opening an issue here: https://github.com/Maximus5/ConEmu could help.

We have our own wiki, but there isn't much there at the moment.

**Comment by gkalpak** [comment]
While tabs/layout/cwds are restored, command history doesn't (on Win10 at least).
Is per-tab history persistence working for anyone else?

**Comment by luisrudge** [comment]
@gkalpak it's not working for me

**Comment by saostad** [comment]
I have same problem.

**Comment by sebhewelt** [comment]
me too. Was this fixed?

**Comment by manu-m** [comment]
Per-tab history doesn't work for me, too

**Comment by fgrosbellet** [comment]
Same thing here.

**Comment by MinxiesDev** [comment]
Per-tab history doesn't work for me, either.

**Comment by daxgames** [comment]
Settings in ConEmu isn't something the Cmder team can fix, opening an issue here: https://github.com/Maximus5/ConEmu could help.
