### ISSUE TITLE
Removing cli color codes from outut

### ISSUE THREAD

**Issue by grafikkaos** [cmderdev/cmder#674]
Anyone have an idea of how I can fix the issue i am currently having as shown in the screenshot below?

![2015-10-20 19_52_25-search](https://cloud.githubusercontent.com/assets/124558/10617797/38f99656-7764-11e5-8713-31fb7e725980.png)

Thanks

**Comment by MartiUK** [comment]
What shell are you using?

**Comment by grafikkaos** [comment]
i am using cmd.exe.  In PowerShell, I am also getting the same issue

**Comment by gmsantosxl** [comment]
I've got this issue with PHP 7.0. Updade conemu solved this issue.

**Comment by Stanzilla** [comment]
I'm on ConEmu 151015 and it also works fine for me!

**Comment by MartiUK** [comment]
This has been fixed in the latest pre-release version.
