### ISSUE TITLE
msysgit commands not working

### ISSUE THREAD

**Issue by vintem** [cmderdev/cmder#675]
Hi, I have a new installation of Win10, I download the full version with msysgit, but when I open cmder the commands such as ls are not available. I keep receiving errors as the command is not recognized.

![2015-10-21 22_57_59-cmder](https://cloud.githubusercontent.com/assets/368734/10655908/4221e628-7847-11e5-94bc-e220e9aef3ff.png)

Is there anything special I have to do? 
Thanks

**Comment by Stanzilla** [comment]
Please download the latest pre-release from here https://github.com/cmderdev/cmder/releases

**Comment by vintem** [comment]
That fixed it. Thanks.
