### ISSUE TITLE
Question: Is integration with (portable) Python 3.2 possible?

### ISSUE THREAD

**Issue by TheAngryAvocado** [cmderdev/cmder#677]
I've successfully made an alias with sublime text 3, following the wiki's article.

I am a daily user of Python too, and I was wondering, is there a way to integrate portable Python like I did with sublime? If yes, I'd be happy if you told me the way to achieve it :)

The command would be "pythonp", to not conflict with existing commands.
(portable python download: http://portablepython.com/wiki/PortablePython3.2.5.1/ )

**Comment by DanielGGordon** [comment]
I like the idea, but I think we would want to keep it out of Cmder, which
we are trying to keep minimal. Wiki says uncompressed size is 65 MB, that
would almost double the size of the Cmder download and size on disk.

**Comment by JanSchulz** [comment]
I installed cmdr in my dropbox and added some dirs in vendor, which I then added to the path in `config/user_startup.cmd`:

```
@set "PATH=%PATH%;%CMDER_ROOT%\vendor\Aspell\bin"
@set "PATH=%PATH%;%CMDER_ROOT%\vendor\GnuPG\bin"
```

**Comment by JanSchulz** [comment]
Another way: I'm pretty sure that if you [install a new environment with conda](http://conda.pydata.org/docs/using/envs.html), the resulting dir is moveable. So you could add the complete dir into e.g. cmder/vendor and just set the path in the same way as would `activate.bat <env>`.
