### ISSUE TITLE
Error in NPM-Prompt

### ISSUE THREAD

**Issue by cee-kay** [cmderdev/cmder#678]
Hi Guys,

I guess i found a problem with the npm-prompt in cmder version 1.29
If the package.json file is missing the name and/or version property, the prompt will crash with
`cmder/vendor/clink-completions/npm_prompt.lua:11: attempt to concatenate local 'package) nil value`
and leaving current folder line like this:
 `C:\current\folder {git}{hg}`

Unfortunately I don't know LUA at the moment, so can someone reproduce this issue?

side note: you get this kind of package.json if you use the yeoman generator 'webapp' in the version 1.1.0. [Yeoman Webapp](https://github.com/yeoman/generator-webapp)

**Comment by vladimir-kotikov** [comment]
@Stanzilla, fixed in https://github.com/vladimir-kotikov/clink-completions/commit/1cea322bd6f579e8b8798381fcdd928a3869ce74

**Comment by Stanzilla** [comment]
Thanks!

**Comment by cee-kay** [comment]
Wow that was quick. Thx

**Comment by savovs** [comment]
This pops up when I try to acces my npm project: 
![conemu64_2016-11-16_17-39-41](https://cloud.githubusercontent.com/assets/1226564/20358448/b911dcd2-ac23-11e6-935d-f0fae6278388.png)

**Comment by dany-on-demand** [comment]
@savovs this happened to me when I had a merge conflict resulting in a non-valid package.json

a better error message would suffice
