### ISSUE TITLE
git: 'pull' is not a git command. See 'git --help'.

### ISSUE THREAD

**Issue by rparolin** [cmderdev/cmder#679]
1)  Downloaded binaries from the website.
2) navigate to existing git repro
3)  enter command 'git pull'

result)  git: 'pull' is not a git command. See 'git --help'.

**Comment by Stanzilla** [comment]
Please get the latest pre release from here https://github.com/cmderdev/cmder/releases

**Comment by rparolin** [comment]
Just noticed that now.  Please update the main page with a link to the latest binaries.
