### ISSUE TITLE
cyrillic characters problem

### ISSUE THREAD

**Issue by diimdeep** [cmderdev/cmder#68]
ls for example 
http://i.imgur.com/Nq3xCcs.png

chcp 
866

**Comment by zealotous** [comment]
```
bash
export LC_ALL=ru_RU.utf-8
```
Works fine for me.

**Comment by Safe-Mode** [comment]
> export LC_ALL=ru_RU.utf-8
Работает, спасибо!

**Comment by Safe-Mode** [comment]
После перезапуска консоли, опять нужно вводить, не знаете, как один раз ввести и все?

**Comment by ShoutingLime** [comment]
> После перезапуска консоли, опять нужно вводить, не знаете, как один раз ввести и все?
Строку
`export LC_ALL=ru_RU.utf-8`
нужно прописать в файле .bashrc.

**Comment by vovche** [comment]
А как добиться аналогичного эффекта, не запуская сеанс баш?
