### ISSUE TITLE
Don't work at my windows 7 (misiing api-ms-win-crt-runtime-l1-1-0.dll)

### ISSUE THREAD

**Issue by mifwarior** [cmderdev/cmder#682]
Just download cmder from http://cmder.net/ full version
Unpack to folder D:\Programms\Cmder
and run Cmder.exe
having popup error with misiing api-ms-win-crt-runtime-l1-1-0.dll

**Comment by Stanzilla** [comment]
Get the latest pre-release from https://github.com/cmderdev/cmder/releases
