### ISSUE TITLE
can u support the CHINESE OS ?the directory is like this ,see pic

### ISSUE THREAD

**Issue by dNEryno** [cmderdev/cmder#683]
http://i11.tietuku.com/f66bbb92c910d2b8.jpg

plz fix it ..
good work .
ty.

**Comment by shiroming** [comment]
没设置字体？我这边正常。

http://i13.tietuku.com/e0e5fa011a720771.png

**Comment by alesky** [comment]
Well. In my case it's not a bug at all.

You can just simply change your font to [WenQuanYi Micro Hei Mono](http://wenq.org/wqy2/index.cgi?MicroHei) （文泉驿等宽微米黑）.
