### ISSUE TITLE
Aliases with environment variables not working

### ISSUE THREAD

**Issue by glucas** [cmderdev/cmder#684]
I'm seeing an issue in v1.2.9 that I did not see in my previous 1.2 install. Aliases that refer to environment variables are failing. I can reproduce this with the built-in history alias:

    λ history
    cat: %CMDER_ROOT%\config\.history: No such file or directory
    λ set CMDER_ROOT
    CMDER_ROOT=C:\opt\cmder
    λ cat %CMDER_ROOT%\config\.history  
    ... works fine ...

Note that the variable is defined and the file exists. The error message indicates that CMDER_ROOT is not set, so it looks like the cat command is not inheriting the current shell environment. I see the same thing with a number of other aliases that I have. When I switch back to my older cmder installation everything works fine.

**Comment by glucas** [comment]
No one else seeing this? I'm on Window 8.1 and can reproduce directly after extracting cmder.7z, with no config changes:

    C:\Users\glucas
    λ history
    cat: %CMDER_ROOT%\config\.history: No such file or directory

    C:\Users\glucas
    λ cat %CMDER_ROOT%\config\.history
    cat: C:\Users\glucas\cmder\config\.history: No such file or directory

    C:\Users\glucas
    λ touch %CMDER_ROOT%\config\.history

    C:\Users\glucas
    λ history
    cat: %CMDER_ROOT%\config\.history: No such file or directory

**Comment by glucas** [comment]
Another test case. On plain old cmd.exe:

    C:\>doskey tryme=echo ^%HOME^%
    C:\>tryme
    C:\Users\glucas

On cmder.exe:

    λ ls %CMDER_ROOT% | grep Version
    Version v1.2.9
    λ doskey tryme=^%HOME^%
    λ tryme
    %HOME%

On my prior cmder.exe:

    λ ls %CMDER_ROOT% | grep Version
    Version v1.2
    λ doskey tryme=echo ^%HOME^%
    λ tryme
    C:\Users\glucas

**Comment by Stanzilla** [comment]
Yep, can reproduce, not yet sure what caused it though.

**Comment by glucas** [comment]
Thanks for confirming. I suppose it is most likely a Conemu change, I'll take a look through the issues over there.

**Comment by Stanzilla** [comment]
Did you test with clink 0.4.4?

**Comment by Stanzilla** [comment]
You can use this test build of clink to have the fix right now, we will make sure to include it in our next release: https://www.dropbox.com/sh/hqbrpkf0dpmmizq/AADIJ4G5gjJ59JfFmr-3-Qc0a/20150923_1abb57/clink_DEV.zip?dl=0

**Comment by glucas** [comment]
Great, thanks!

**Comment by gustavohenke** [comment]
:+1: Also using this dev build as a fix, thanks!
