### ISSUE TITLE
Running process, See Program App Folder / Root

### ISSUE THREAD

**Issue by danielHalan** [cmderdev/cmder#686]
Hi, 

Is it possible to view what the Active program home folder is? That is, if one starts 5 SomeApp.exe in five different folders, its not possible to distinguish them apart. 

Would be preferable to be able to enable this in Status-bar as it can be a lengthy path. (and preferable to cut the start, and show the ending part, if too long for text-view/label)

**Comment by MartiUK** [comment]
Settings > Main > Tab Bar then look at the Console settings and change it to how you want it to be.

**Comment by danielHalan** [comment]
I've tried the commands available in the hint, %d and %f, Unfortunately they show the Folder that the command was started, not the actual program folder. That is, if I'm inside a "Scripts" folder with bat-files, that does "start c:/zzzz/yyy/xxxx.exe" it will show "Scripts" path, for all of the processes.

Also the paths can be very long, so it would be great to be able to show full path in the "Status Bar"
