### ISSUE TITLE
The directory be duplicate displayed

### ISSUE THREAD

**Issue by leequangang** [cmderdev/cmder#689]
The directory would be duplicate displayed when change the window size or split it.

![1](https://cloud.githubusercontent.com/assets/4644874/10864245/04585a82-8023-11e5-9795-4afde9748839.png)

**Comment by defhook** [comment]
I also prompt it...
![cmder-issue](https://cloud.githubusercontent.com/assets/3256188/10875566/f24fb856-816e-11e5-8e0d-cc5b677b213d.gif)

**Comment by mwhitis** [comment]
I think what it's actually doing is running the last thing in the command buffer.  I'm seeing the same thing.  For example, I ran gl in my folder then resized the screen and it runs gl again instead of leaving me at the prompt

**Comment by MartiUK** [comment]
This has been fixed in clink 0.4.6, which is already part of cmder.
