### ISSUE TITLE
Tab-Complete paths not working [1.2.9]

### ISSUE THREAD

**Issue by reustonium** [cmderdev/cmder#691]
I'm running Cmder 1.2.9 and I've lost the ability to 'tab-complete' paths.

e.g.
I run `git status` and see that I have some unstaged changes.
So I run `git add t<tab>` to try to have Cmder auto-complete `test.md`, but the auto-complete never finds the file.
![image](https://cloud.githubusercontent.com/assets/1432186/10884811/05a96cca-8148-11e5-9ea7-5ecb347d9803.png)

Tab completion of paths works fine on the same system when running Cmder 1.1.4.1.

**Comment by Stanzilla** [comment]
Already fixed in dev, will be in the next release :)
