### ISSUE TITLE
Not getting git status in 1.2.9 prompt

### ISSUE THREAD

**Issue by mwhitis** [cmderdev/cmder#692]
I've been previously running the 1.1.4.1 version.  Tried upgrading to 1.2.9 and am no longer getting git status in the cmd prompt, just the directory and lambda.  Tried with both the included vendor git as well as an external copy of git that I've got already installed (2.5.1).  

Any thoughts?

**Comment by Stanzilla** [comment]
Can you try removing the old folders completely before updating, please?

**Comment by mwhitis** [comment]
@Stanzilla Yes, sorry, I did a clean install.  Upgrade was probably not the right word.  I deleted all the existing contents of my cmder folder, then extracted the contents of the 1.2.9 folder into it.

**Comment by mwhitis** [comment]
Ok, so I've been working with the cmder.lua, and have found the problem.  It must be something weird on my machine.  The issue is that the get_git_branch function is returning nothing.  Specifically, io.popen("git branch 2>nul") is coming back empty.  For some reason, that seems to be redirecting everything to nul instead of just stderr.  If I run it from a command prompt, the behavior is as expected, but when getting called from the lua script everything is redirected.  I've verified that the 1.1.4.1 git.lua uses the same code and is working properly.  Not sure if anything changed in the lua interpreter between the two versions, but I'm inclined to think it may just be me since no one else has reported it.

**Comment by Stanzilla** [comment]
Our Lua interpreter is clink, so you might get lucky and have it fixed by using a newer test build of that. You can get that from here https://www.dropbox.com/sh/hqbrpkf0dpmmizq/AADIJ4G5gjJ59JfFmr-3-Qc0a/20150923_1abb57/clink_DEV.zip?dl=0

**Comment by mwhitis** [comment]
I'm going to go ahead and close the issue.  The clink update didn't help, but if I change the lua code from:

io.popen("git branch 2>nul") 

to

io.popen("git branch") 

It's working as expected.

**Comment by Stanzilla** [comment]
@vladimir-kotikov any idea?

**Comment by vladimir-kotikov** [comment]
@Stanzilla, i saw this on one of my machines, but it doesn't repro right now. I updated ConEmu and git after that, so it might be an issue with one ot them.

@mwhitis, could you please post your git version and location (`git --version` and `where git` in console) and ConEmu version (`conemu /?`)
