### ISSUE TITLE
Cmder (cmd.exe) startup crashes at clink step

### ISSUE THREAD

**Issue by pilcru** [cmderdev/cmder#699]
Hi,

Today my installation of cmder stopped working, cmd.exe would crash when clink is run from /vendor/init.bat. Same thing with a fresh install of cmder. I do not have control over the windows updates on this computer so it might be because of something installed by my employer.

Here is the output in cmder, after I close the windows dialog saying that the "Windows command processor has stopped working":

```
C:\Users\pcuvil {git}{hg}
{lamb}

Current directory:
C:\Users\pcuvil

Command to be executed:
"C:\Windows\system32\cmd.exe" /k "C:\Users\pcuvil\Desktop\cmd\vendor\conemu-maximus5\..\init.bat"


ConEmuC: Root process was alive less than 10 sec, ExitCode=255.
Press Enter or Esc to close console...
```

The initial cmd prompt is not always there.

The clink log was not helpful at all, it stops before doing anything serious:

``` 
6008 do_inject                  185 System: ver=6.1 1.0 arch=9 cpus=8 cpu_type=8664 page_size=4096
6008 do_inject                  190 Version: 0.4.5
6008 do_inject                  191 DLL: C:\Program Files\cmder\vendor\clink\clink_dll_x64.dll
6008 do_inject                  193 Parent pid: 3496
6008 check_dll_version           52 DLL version: 00000004 000563f1
6008 do_inject_impl             283 Creating remote thread at 0000000077516590 with parameter 0000000000330000
```

To resolve the issue I had to overwrite _both_ clink and ConEmu with their latest versions (0.4.5 for clink, 151101 for ConEmu). Upgrading clink alone did not change anything, upgrading ConEmu alone allowed me to move past the crash but the command prompt showed {lamb}  and {git} instead of the nicer expected versions.

Not sure if anyone had this before, in any case you now have what worked for me!

--
Pierre

**Comment by Stanzilla** [comment]
When you say fresh install, which version did you download?

**Comment by pilcru** [comment]
I tried both v1.2 full version, and v1.2 full + overwritten with in the repo at 417051f.

**Comment by Stanzilla** [comment]
Can you try the latest pre-release at https://github.com/cmderdev/cmder/releases please?

**Comment by pilcru** [comment]
This one works, sorry I didn't see it before when I looked for new releases...

**Comment by Stanzilla** [comment]
No problem :)
