### ISSUE TITLE
npm_prompt.lua:11: attempt to concatenate local 'package_version' (a nil value)

### ISSUE THREAD

**Issue by shiroming** [cmderdev/cmder#700]
I use webstorm create a react starter kit project.

```
E:\code
-> cd react\

C:\cmder/vendor/clink-completions/npm_prompt.lua:11: attempt to concatenate local 'package_version' (a nil value)
E:\code\react {git}{hg}
{lamb}
```
![qq 20151109112951](https://cloud.githubusercontent.com/assets/3378984/11025394/6dc2e510-86d5-11e5-88c7-c6b7d74601d7.png)

**Comment by vladimir-kotikov** [comment]
@shiroming, this was fixed in upstream, the fix will be available in Cmder 1.3.0.

At this time you cant try to apply https://github.com/vladimir-kotikov/clink-completions/commit/1cea322bd6f579e8b8798381fcdd928a3869ce74 manually to your `npm_prompt.lua`

**Comment by shiroming** [comment]
got it。
THX

**Comment by vladimir-kotikov** [comment]
Yup, everything is correct. Your `package.json` is missing `name` and `version` attributes. (probably because it is a templete and you need to add them manually). See [package.json reference here](https://docs.npmjs.com/files/package.json#name)

**Comment by shiroming** [comment]
OK,I add "name" and "version" manually.

**Comment by vladimir-kotikov** [comment]
@MartiUK , @Stanzilla, this probably could be closed.

**Comment by adiachenko** [comment]
@vladimir-kotikov But what if I use npm just for pulling in dependencies with `private` property in package.json set to `true`? This new prompt is kind of obtrusive. You may consider replacing "<invalid_name>" and "<invalid_version>" with empty string in npm_prompt.lua.

**Comment by vladimir-kotikov** [comment]
@adiachenko, actually i'm inclining to replace `invalid_` -> `no_`. This would be more appropriate, than just empty strings (which would give you e.g. `@0.0.1` - looks kinda weird). Or, probably remove npm package badge at all if there is neither package name nor version specified.

**Comment by jpruiz114** [comment]
Hi. I'm a little lost here. Got the same issue with a Laravel project under PHPStorm.

Got this message:

C:\cmder/vendor/clink-completions/npm_prompt.lua:11: attempt to concatenate local 'package_version' )e

What approach did you use to solve it?

**Comment by vladimir-kotikov** [comment]
@jpruiz114, take a look at the 2nd comment on this thread and apply that change to your `C:\cmder/vendor/clink-completions/npm_prompt.lua`

**Comment by jpruiz114** [comment]
Hey @vladimir-kotikov thanks for your message. I'm a little confused here because there are two files:

npm.lua and npm_prompt.lua

In your fix from here:

https://github.com/vladimir-kotikov/clink-completions/commit/1cea322bd6f579e8b8798381fcdd928a3869ce74

... you were applying a patch to npm.lua including the function inside npm_prompt.lua

I tried adding the code to both files but still got the weird message:

![image](https://cloud.githubusercontent.com/assets/4614970/12988978/2e26f644-d0d1-11e5-9afb-772f043a24b8.png)

Thanks in advance for your help!

**Comment by Stanzilla** [comment]
check your `cmder\vendor` dir, the only lua file in there should be `clink.lua` if you have any extra, delete those and try again.

**Comment by vladimir-kotikov** [comment]
@Stanzilla, why clean `cmder/vendor`? I think we need to ask @jpruiz114, which version he use

@jpruiz114, you need to add changes to `npm_prompt.lua` only. In my patch i added them to `npm.lua` instead because at some point i decided to merge these two files into one. However latest public Cmder version (1.2.9) doesn't include this merge yet.

**Comment by Stanzilla** [comment]
@vladimir-kotikov because we changed around what is in there and when users upgrade by just copying the new files into the folder, some old stuff stays around and causes problems like the lambda not showing up because clink was called twice etc, that's why I like to make sure people only have the one lua file there that is actually used at the moment. But I guess it was not the case here.

**Comment by ghiscoding** [comment]
hey guys, just to let you know that I actually found another solution that worked from a [Chinese blog](http://blog.bflyer.com/2016/02/04/npm-prompt-lua-11-attempt-to-concatenate-local-package-version-a-nil-value/). 

I was getting this
```javascript
c:\cmder/vendor/clink-completions/npm_prompt.lua:11: attempt to concatenate local 'package_version' (a nil value)
```

The original `npm_prompt.lua` was (BEFORE FIX)
```javascript
...
local package_name = string.match(package_info, '"name"%s*:%s*"(%g-)"')
local package_version = string.match(package_info, '"version"%s*:%s*"(.-)"')
...
```
and the change is (AFTER FIX):
```javascript
...
local package_name = string.match(package_info, '"name"%s*:%s*"(%g-)"')
if package_name == nil then
	package_version = ''
end		
local package_version = string.match(package_info, '"version"%s*:%s*"(.-)"')
if package_version == nil then
	package_version = ''
end		
```

**Comment by PancakeTornado** [comment]
@ghiscoding The fix you found has a bug where it does not set `package_name`

The solution that worked for me was to edit the file:
`{YOUR_PATH}/cmder/vendor/clink-completions/npm_prompt.lua`
and overwrite the related lines to be this instead:

```bash
...
local package_name = string.match(package_info, '"name"%s*:%s*"(%g-)"')
if package_name == nil then
    package_name = ''
end     
local package_version = string.match(package_info, '"version"%s*:%s*"(.-)"')
if package_version == nil then
    package_version = ''
end
...
```

**Comment by eugenesvk** [comment]
I would suggest one additional change to get rid of the stray `@` character when there is no version present — adding an additional variable `package_version_separator` and making it blank `''` when there is no version
```
		local package_version_separator = '@'
		local package_name = string.match(package_info, '"name"%s*:%s*"(%g-)"')
		if package_name == nil then
			package_name = ''
		end
		local package_version = string.match(package_info, '"version"%s*:%s*"(.-)"')
		if package_version == nil then
			package_version = ''
			package_version_separator = ''
		end
		local package_string = color.color_text("("..package_name..package_version_separator..package_version..")", color.YELLOW)
```

**Comment by pantox** [comment]
Thanks all for your inspiration.

If you feel comfortable to have an automatic check for the right version and name field of your package.json leave it as it is. Otherwise for me it feels right when there is no package_name and package_version it shouldn't display anything.

This is my modification of `cmder\vendor\clink-completions\npm.lua` to get rid of all the empty brackets, symbols and stuff. 

	function npm_prompt_filter()
	    local package = io.open('package.json')
	    if package ~= nil then
	        local package_info = package:read('*a')
	        package:close()
	        local package_name = string.match(package_info, '"name"%s*:%s*"(.-)"')
	            or ""

	        local package_version = string.match(package_info, '"version"%s*:%s*"(.-)"')
	            or ""

	        if package_name == "" and package_version == "" then
	        	local package_string = ""
	        else
	        	local package_string = color.color_text("("..package_name.."@"..package_version..")", color.YELLOW)
	        	clink.prompt.value = clink.prompt.value:gsub('{git}', '{git} '..package_string)
	        end

	    end
	    return false
	end

Tested with cmder version v1.2.9 and also v1.3.0-pre

**Comment by danilobrinu** [comment]
npm_prompt.lua (v1.2.9)

```
local color = require('color')

function npm_prompt_filter()
    local package = io.open('package.json')
    if package ~= nil then
        local package_info = package:read('*a')
        package:close()
        local package_private = string.match(package_info, '"private"%s*:%s*true')
        if package_private == nil then
            local package_name = string.match(package_info, '"name"%s*:%s*"(%g-)"')
            local package_version = string.match(package_info, '"version"%s*:%s*"(.-)"')
            local package_string = color.color_text("("..package_name.."@"..package_version..")", color.YELLOW)
            clink.prompt.value = clink.prompt.value:gsub('{git}', '{git} '..package_string)
        end
    end
    return false
end

clink.prompt.register_filter(npm_prompt_filter, 40)
```

**Comment by danilobrinu** [comment]
If private, u don't need the name or version !!

**Comment by visualcookie** [comment]
Can confirm this issue is happening to me right now. Just upgraded to the latest version.

**Comment by iamfreee** [comment]
Yep me too!

@visualcookie did you fixed it?

**Comment by visualcookie** [comment]
@iamfreee Yeah, just copy and pasted @danilobrinu solution and now it works again.

**Comment by csmithersslc** [comment]
Hi, I am getting the same error now and the previous fixes seem to not work on this.  Do you have any suggestions?

**Comment by danilobrinu** [comment]
@csmithersslc what problems ?

**Comment by danilobrinu** [comment]
@csmithersslc i can help you, i fixed the previous version :)

**Comment by csmithersslc** [comment]
@danilobrinu Thank you!

**Comment by danilobrinu** [comment]
@csmithersslc tell me about your issues. Post prints and tag me.

**Comment by csmithersslc** [comment]
Sure @danilobrinu 

I cd'ed into a new directory and this was the output:
![capture](https://cloud.githubusercontent.com/assets/5580479/19843272/2dc09e88-9ee6-11e6-9a37-201b77b7dbc5.JPG)

The npm_prompt file reads as follows:
`local color = require('color')

function npm_prompt_filter()
    local package = io.open('package.json')
    if package ~= nil then
        local package_info = package:read('*a')
        package:close()
        local package_private = string.match(package_info, '"private"%s*:%s*true')
        if package_private == nil then
            local package_name = string.match(package_info, '"name"%s*:%s*"(%g-)"')
            local package_version = string.match(package_info, '"version"%s*:%s*"(.-)"')
            local package_string = color.color_text("("..package_name.."@"..package_version..")", color.YELLOW)
            clink.prompt.value = clink.prompt.value:gsub('{git}', '{git} '..package_string)
        end
    end
    return false
end

clink.prompt.register_filter(npm_prompt_filter, 40)`

And the npm one is as follows:
`function npm_prompt_filter()
    local package = io.open('package.json')
    if package ~= nil then
        local package_info = package:read('*a')
        package:close()
        local package_name = string.match(package_info, '"name"%s*:%s*"(.-)"')
            or ""

        local package_version = string.match(package_info, '"version"%s*:%s*"(.-)"')
            or ""

        if package_name == "" and package_version == "" then
            local package_string = ""
        else
            local package_string = color.color_text("("..package_name.."@"..package_version..")", color.YELLOW)
            clink.prompt.value = clink.prompt.value:gsub('{git}', '{git} '..package_string)
        end

    end
    return false
end`

**Comment by danilobrinu** [comment]
@csmithersslc what is your cmder version ?? u can use the previous comment with the code fixed

**Comment by csmithersslc** [comment]
Wow, that worked perfectly.  

I show it is version 161022 stable, the newest version.  

Thank you so much!

**Comment by danilobrinu** [comment]
@csmithersslc you can try this code ?

```lua
function npm_prompt_filter()
    local package_file = io.open('package.json')

    if package_file then
        local package_data = package_file:read('*a')
        local package = JSON:decode(package_data)

        if package then
             if not package.private then
                local package_name = package.name or "<no name>" 
                local package_version = package.version and "@"..package.version or ""
                local package_string = color.color_text("("..package_name..package_version..")", color.YELLOW)

                clink.prompt.value = clink.prompt.value:gsub('{git}', '{git} '..package_string)
            end
        end
    end

    package_file:close()

    return false
end
```

**Comment by csmithersslc** [comment]
I have tried it and it worked!  Thank you for your help.

**Comment by danilobrinu** [comment]
@csmithersslc the new version of cmder have fixed, update your cmder o download the latest version :)

**Comment by csmithersslc** [comment]
All done.  Everything looks good :)

**Comment by 6bytes** [comment]
Hi @danilobrinu 
I've been having the same issue for months now. I tried to paste the code you gave @csmithersslc but it didn't work for me :(
I get the following error:
![screenshot_12](https://cloud.githubusercontent.com/assets/844535/21008956/10247bdc-bd3c-11e6-8b3b-bc5df4937b4f.png)

My npm_prompt.lua file looks like this:

    local color = require('color')
    
    function npm_prompt_filter()
        local package = io.open('package.json')
        if package ~= nil then
            local package_info = package:read('*a')
            package:close()
            local package_name = string.match(package_info, '"name"%s*:%s*"(%g-)"')
            local package_version = string.match(package_info, '"version"%s*:%s*"(.-)"')
            local package_string = color.color_text("("..package_name.."@"..package_version..")", color.YELLOW)
            clink.prompt.value = clink.prompt.value:gsub('{git}', '{git} '..package_string)
        end
        return false
    end
    
    clink.prompt.register_filter(npm_prompt_filter, 40)

Just today updated cmder to version `161206 stable`.
How can I fix that?

**Comment by danilobrinu** [comment]
@6bytes download the lastest version of cmder, that issue is fixed. The version of cmder is 1.3.1 not 161206, 1061206 is the version of ConEmu i recommend not update the ConEmu why is probably not compatible with the lastest version of cmder. 

But u can try this code modifying file npm_prompt.lua:


```lua
function npm_prompt_filter()
    local package_file = io.open('package.json')

    if package_file then
        local package_data = package_file:read('*a')
        local package = JSON:decode(package_data)

        if package then
             if not package.private then
                local package_name = package.name or "<no name>" 
                local package_version = package.version and "@"..package.version or ""
                local package_string = color.color_text("("..package_name..package_version..")", color.YELLOW)

                clink.prompt.value = clink.prompt.value:gsub('{git}', '{git} '..package_string)
            end
        end
    end

    package_file:close()

    return false
end
```

**Comment by 6bytes** [comment]
Thank you @danilobrinu I just downloaded latest version and it's all working fine :)
