### ISSUE TITLE
Is cmder support scrolling with touch screen?

### ISSUE THREAD

**Issue by alesky** [cmderdev/cmder#706]
I'm using Surface without a type cover, and I found that is really hard to scroll using only touch screen.

Although I have a pen but i don't want to take it out from my bag...

**Comment by Jackbennett** [comment]
Apparently you just use two fingers to scroll: http://conemu.github.io/en/TabletPC.html

ConEmu is used to wrap the conhost that Cmder layers our settings on top of.

**Comment by alesky** [comment]
Thanks a lot!~

but..Russian... 
well, google translate also helps a lot LOL
