### ISSUE TITLE
Fullscreen window appears below taskbar in Windows 10

### ISSUE THREAD

**Issue by warpdesign** [cmderdev/cmder#707]
I'm using Windows 10 and when pressing Alt+Enter to switch to fullscreen, cmder appears below the taskbar:

![cmder](https://cloud.githubusercontent.com/assets/199648/11147918/c4f8715a-8a19-11e5-8b0b-085b945d31d3.png)

Enabling "always on top" option doesn't fix the problem.

**Comment by fr0zenone** [comment]
Same problem

**Comment by LVNCELOT** [comment]
+1

**Comment by jespardk** [comment]
+1
