### ISSUE TITLE
Profile.ps1 Question 

### ISSUE THREAD

**Issue by mehdroid** [cmderdev/cmder#708]
Can we add personal entries for aliases and modules without negatively affecting the cmder and conemu?

**Comment by daxgames** [comment]
Yes, the development version of vendor/profile.ps1 allows you to put user specific Powershell config in config/user-profile.ps1 without affecting the default user config.

**Comment by mehdroid** [comment]
Word! Thank you :)

**Comment by dengxiaozhen** [comment]
Hello, I opened the cmder after the emergence of such an error message, the system is x64 win10, how to solve it,thank you!
![cmder](http://7xon9l.com1.z0.glb.clouddn.com/QQ截图20151201101107.jpg)
