### ISSUE TITLE
"Cmder here" doesn't work if set start-up dir

### ISSUE THREAD

**Issue by nguymin4** [cmderdev/cmder#709]
Hi, I have the problem above for several months and I hope someone can help me with that.

OS: Windows 10
Cmder: 1.2.9
Git-for-Windows: 2.6.3

I set up startup dir for a default task with git-bash. However if I set startup dir then I cannot use the context menu `Cmder Here` anymore.

In addition, if I press `Ctrl+T` to create new session, then the new session will open the startup directory, not the current working directory.

**Comment by JanSchulz** [comment]
What does it mean that you "cannot use the context menu" anymore. Does it just start up in the wrong dir?

If it is the latter, it could be this line in `init.bat`:

```
@if defined CMDER_START (
    @cd /d "%CMDER_START%"
) else (
    @if "%CD%\" == "%CMDER_ROOT%" (
        @cd /d "%HOME%"
    )
)
```

**Comment by nguymin4** [comment]
@JanSchulz : I mean it always start with the startup-dir instead of the current working directory where I use `Cmder here` or where I press `Ctrl+T` (to create a new console)

Here is my default task
`%CMDER_ROOT%\..\Git\bin\sh.exe --login -i -new_console:d:D:\My_startup_dir`
So even I'm in a different directory, `Cmder here` always open my_startup_dir

Although, I think your solution is not gonna work, I did try it and it turned out I was right :(.
Thanks for you help anyway
