### ISSUE TITLE
Default paste all line command?

### ISSUE THREAD

**Issue by randy3k** [cmderdev/cmder#710]
[cmder.net](http://cmder.net) says <kbd>Ctrl + Shift + v</kbd> paste text, however, I think the default settings are:
<kbd>Ctrl + v</kbd>: paste first line
<kbd>Shift + Insert</kbd>: paste all lines,

I wonder if there is any intention to change the default <kbd>Shift + Insert</kbd> to <kbd>Ctrl + Shift + v</kbd> for pasting all lines? I think that <kbd>Ctrl + Shift + v</kbd> is way better than the default <kbd>Shift + Insert</kbd>.

**Comment by ccoenen** [comment]
I found this confusing, too, when i started using cmder. I wouldn't mind changing the default.

**Comment by DanielGGordon** [comment]
I'm currently using @daxgames fork (which has been merged into development already) - and `ctrl = shift + v` pastes all lines for me. 

`shift + insert` pastes all lines as separate lines, including the `enter` command. 

I get this result from the Cmder task. Is this issue in the Powershell task?

**Comment by jrzaurin** [comment]
Hi guys, I am late to the party, but...how one actually changes the default `paste all lines` command in Cmder? I have managed to uncheck, `Confirm keypress` and `Confirm pasting more than...`, but I can't find where to change that command. 

Thanks!
