### ISSUE TITLE
Can't register shortcut

### ISSUE THREAD

**Issue by DejanMarkovic91** [cmderdev/cmder#711]
When i updated Cmder to newest version, i am experiencing shortcut problem, when I try to use quake style, it says that it can't register shortcut because it is registered for other app (older version indeed). Does anyone know how to manually remove old shortcut entry? I also tried updating to beta version after screenshoting but problem persisted. I am using Win 10.

![capture](https://cloud.githubusercontent.com/assets/15866600/11176103/ed471ab8-8c39-11e5-9262-125a52ca4943.PNG)

**Comment by Stanzilla** [comment]
Something must have changed about that in the november update for Win10, I'm getting this error for ShareX, too.

**Comment by DejanMarkovic91** [comment]
Btw, I tried starting app as admin, but it did not work.

**Comment by chrismark** [comment]
Once can update the Hotkey in Settings (Win + Alt + P) > Keys & Macro. Quake Hot Key should be currently set to Ctrl + `. Select it, add an Alt (so it's Ctrl + Alt + `) by selecting Alt on 2nd dropdown on bottom right of dialog, then click Save Settings. Restart cmder and the popup should now be gone.

**Comment by dnutiu** [comment]
This popup is extremely annoying, it would be nice if the default values of Cmder wouldn't annoy users so much.
