### ISSUE TITLE
e. shortcut not working ?

### ISSUE THREAD

**Issue by warpdesign** [cmderdev/cmder#712]
Just downloaded Cmder (portable version) and it seems a lot of advertised goodies don't work out of the box:

 - 'e.' doesn't seem to be defined, I get "e. : The term 'e.' is not recognized as the name of a cmdlet, [...]" when typing that
 - ctrl+up does nothing

Is there something to do to activate default aliases & shortcuts ?

**Comment by MartiUK** [comment]
Download the latest pre-release from here: https://github.com/cmderdev/cmder/releases
