### ISSUE TITLE
Windows Defender on Windows 10 finds Trojan in extracted files

### ISSUE THREAD

**Issue by williamkray** [cmderdev/cmder#713]
after extracting the zip I downloaded, windows defender immediately tells me that there's a Trojan:Win32/Detplock in cmder\vendor\msysgit\bin\ssh.exe

now, i know that this sounds pretty legit since ssh obviously allows external command execution by design, but is there any way to not have it complain, or at least put a warning on the landing page if this is indeed a legitimate binary? seems like this could be offputting for new users.

apologies if this has already been discussed, i searched but didn't find any other issues related to this.

**Comment by MartiUK** [comment]
Only thing we can do is report that binary as legitimate to Microsoft, a lot more than just cmder uses msysgit.

**Comment by MartiUK** [comment]
Another thing you can do is use the latest pre-release as we use git-for-windows now rather than msysgit.

**Comment by bittin** [comment]
https://github.com/mridgers/clink/issues/381
