### ISSUE TITLE
Slow Atom 

### ISSUE THREAD

**Issue by pixie79** [cmderdev/cmder#714]
When running atom inside of cmder it's performance it's terrible. Running the same binary from the same location and using the same opening directory performance is fine for Atom standalone mode. 
Performance also appears better when run in its own window, but when sharing the window so it is at the top and you have two cygwin shells below it is unusable.

Regards

Mark

P.s otherwise cmder appears to be very useful

**Comment by MartiUK** [comment]
How does performance fluctuate, is it based on how you split the window or does it still grind to a crawl when atom is in it's own tab?

**Comment by pixie79** [comment]
Hi,

I think it seems to be related to the split window, If launched as part of its own window then speed is normal to using atom outside of cmder as far as I have seen so far.

Mark

**Comment by elcarim5efil** [comment]
Hi,
Could you please show me how to run atom inside of cmder? I have set the command line like `"%CMDER_ROOT%\vendor\atom\atom.exe" $1 -new_console:s70H`, but it just open a new window and run atom.
My cmder version is 1.3.1, and Atom version is 1.10.2.
Thanks.
