### ISSUE TITLE
cmder.exe detected as malware by BitDefender

### ISSUE THREAD

**Issue by oscar-b** [cmderdev/cmder#716]
BitDefender is flagging `cmder.exe` v1.2.9 as malware Gen:Variant.Kazy.767238.

![image](https://cloud.githubusercontent.com/assets/85102/11237517/bce5c984-8de0-11e5-8339-4a90c4e72b23.png)

![image](https://cloud.githubusercontent.com/assets/85102/11237542/e813c4ee-8de0-11e5-8b48-acff3780bc62.png)

**Comment by Stanzilla** [comment]
report it as false positive please
