### ISSUE TITLE
Antivirus deleting some files in cmder (reporting them as infected)

### ISSUE THREAD

**Issue by Harshdand** [cmderdev/cmder#724]
Hi,

Does cmder makes any changes to system files. My antivirus is reporting it as a virus Variant.kazy.

![capture](https://cloud.githubusercontent.com/assets/5079657/11318347/e7fb95b8-9074-11e5-8acb-ccb717c87d68.PNG)

**Comment by MartiUK** [comment]
False positive, report it to your anti-virus software vendor.
