### ISSUE TITLE
Launcher does not escape whitespace in set env variables.

### ISSUE THREAD

**Issue by MartiUK** [cmderdev/cmder#728]
This is a somewhat old bug IIRC, ideally we wouldn't want users sticking anything into their `Program Files` since Microsoft has taken considerable effort to lock it down; even for Administrator users (for good reason) but there will be other cases where someone will have a directory containing whitespace.

Can be reproduced by putting cmder into a directory with whitespace e.g. `C:\Program Files\`.

Since CMDER_ROOT et al are set in the launcher, this would be the best place to resolve it, but it probably could be fixed in the startup scripts instead.
#### Related Issues:
#727
#### Workarounds:

Don't put cmder in a directory containing whitespace

**Comment by Blasz** [comment]
This issue is still happening for bash tasks:
```
'C:\space' is not recognized as an internal or external command,
operable program or batch file.


Current directory:
C:\Users\Michael

Command to be executed:
"C:\Windows\system32\cmd.exe"  /c "C:\space folder\cmder\vendor\conemu-maximus5\..\git-for-windows\bin\bash --login -i"


ConEmuC: Root process was alive less than 10 sec, ExitCode=1.
Press Enter or Esc to close console...
```

**Comment by DanHarman** [comment]
Just hit this issue trying to change my bash task to use git for windows bash installed in the default location (C;\Program Files\Git\bin\bash". Is there a workaround?

**Comment by DanHarman** [comment]
Ok found the old standby of using Progra~1 works fine :)

**Comment by daxgames** [comment]
Works with current version.  Closing
