### ISSUE TITLE
F-Secure flags v1.2.9 as false positive

### ISSUE THREAD

**Issue by Kehet** [cmderdev/cmder#732]
I just noticed F-Secure SAFE flagged Cmder.exe (v1.2.9) as Gen:Variant.Kazy.767238. "Latest stable" v1.1.4.1 doesn't cause this issue.

**Comment by MartiUK** [comment]
We can't do anything about this, please report the false positive to your anti-virus vendor.

**Comment by Kehet** [comment]
well I really dont care either
