### ISSUE TITLE
consistent names for user profiles/startup files?

### ISSUE THREAD

**Issue by JanSchulz** [cmderdev/cmder#733]
According to https://github.com/cmderdev/cmder/pull/427#issuecomment-159416312, we have three different filenames for ps/bat/sh:

* Powershell = config/user-profile.ps1
* Cmder = config/user-startup.cmd
* Bash = config/user-cmder.sh

Could we use just one? E.g. `user-profile.{ps1|bat|sh}`?

**Comment by Stanzilla** [comment]
Yes pls

**Comment by kodybrown** [comment]
I ditto 'Yes pls' to using `user-profile.{ps1|bat|sh}`..

**Comment by MartiUK** [comment]
The code that looks for these should default to a standard profile if they're not found. Are you asking for a single file to do what they all do at once?

**Comment by kodybrown** [comment]
I understood it this way:

* Powershell = config/__user-profile__.ps1
* Cmder = config/__user-profile__.cmd
* Bash = config/__user-profile__.sh

**Comment by MartiUK** [comment]
Oh right yeah :confounded:

+1 to this.

**Comment by JanSchulz** [comment]
Closed by #737
