### ISSUE TITLE
cmder / ConEmu truncates stdout; bower installs don't work

### ISSUE THREAD

**Issue by chase-miller** [cmderdev/cmder#739]
# Version

150913 alpha 
# Steps to Reproduce
1. Launch cmder
2. Use git to clone https://github.com/johnpapa/ng-demos.git
3. With node / npm installed, run npm install -g bower gulp karma-cli nodemon
4. Navigate to ng-demo/modular
5. Run npm install
# Expected Results

npm executes and completes entirely.  All bower dependencies are resolved.
# Actual Results

npm fails saying that bower couldn't resolve a dependency.  
# Root Cause

ConEmu's ConEmuHk.dll has a bug in which it truncates stdout to 4096 characters.  This causes git/bower (and others I'm sure) to fail.  See https://github.com/bower/bower/issues/852#issuecomment-141724402 for more info.
# Workaround
1. Download the latest version of ConEmu (ConEmuPack.150813c at the time of this writing).
2. Copy and replace ConEmu/ConEmuHk.dll and ConEmu/ConEmuHk64.dll to cmder/vendor/conemu-maximus5/ConEmu

I don't know what other bugs may surface as a result of this workaround.
# Recommendation

Update cmder's distribution of ConEmu to the latest as it appears that this bug has been fixed.

**Comment by MartiUK** [comment]
The version of conemu you mention 150813c is behind what we are currently targeting in development, (151119 as of https://github.com/cmderdev/cmder/commit/a3e2d7546d19d5cead20cc4783c1c7fc42624454). I would suggest this be closed unless you can reproduce it with that version.

**Comment by chase-miller** [comment]
Agreed.
