### ISSUE TITLE
curl ntlm auth stopped working

### ISSUE THREAD

**Issue by educhana** [cmderdev/cmder#741]
The new msysgit curl binary provided in 1.2.9 misses SSPI feature. This causes NTLM authentication support to not work.

old curl -V
```bash
curl 7.30.0 (i386-pc-win32) libcurl/7.30.0 OpenSSL/0.9.8z zlib/1.2.7
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IPv6 Largefile NTLM SPNEGO SSL SSPI libz
```

new curl -V
```bash
λ curl -V
curl 7.44.0 (i686-pc-msys) libcurl/7.44.0 OpenSSL/1.0.2d zlib/1.2.8 libidn/1.32 libssh2/1.6.0
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: Debug IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets Metalink
```

**Comment by MartiUK** [comment]
Have you tried raising this issue on their project page? https://github.com/git-for-windows/git

**Comment by educhana** [comment]
Thanks. I was in doubt about which project owns the issue. I've dig a bit further and find the following:

There are two curl binaries in the distrib:
> ./vendor/git-for-windows/mingw32/bin/curl.exe
> ./vendor/git-for-windows/usr/bin/curl.exe

Its the one in /usr/bin that it's broken. If you use the other (mingw32 - that is compiled with SSPI feature) it works ok. Sadly it's out of the path by default.

In fact git is working with ntlm auth OK. Seems that it's using the mingw exe/dll

**Comment by MartiUK** [comment]
Try one of the builds here: https://ci.appveyor.com/project/MartiUK/cmder/build/1.0.117-development/artifacts This is built from the latest sources in the dev branch, and should include curl 7.45 from git-for-windows.

**Comment by educhana** [comment]
Has the same problem.

This is the command issued:

> curl -v --proxy-ntlm --proxy proxyserver:port **-U :** -L http://repo.continuum.io/pkgs/free/win-64/

BUT this works:

> curl -v --proxy-ntlm --proxy proxyserver:port **-U DOMAIN/user:password** -L http://repo.continuum.io/pkgs/free/win-64/

So, what you lose without SSPI is the ability to use you user credentials automatically from your login.

**Comment by MartiUK** [comment]
Yeah that's annoying, I suggest you open an issue on the git-for-windows page, curl needs to be compiled with SSPI.

https://github.com/git-for-windows/MSYS2-packages/blob/master/curl/PKGBUILD This file doesn't have the required switch enabled for it to be built with SSPI support.

**Comment by educhana** [comment]
OK. Thanks!

I've opened an [issue](https://github.com/git-for-windows/git/issues/555) to the git-for-windows team
