### ISSUE TITLE
Special Characters (such as Lambda) is not showing in Command Prompt

### ISSUE THREAD

**Issue by saggafarsyad** [cmderdev/cmder#742]
I mostly use PowerShell or Git-bash. When I open Command Prompt, I just noticed that the special characters is not showing. Here is what is like

![cmder-issues](https://cloud.githubusercontent.com/assets/7218502/11440077/26d3c69a-9532-11e5-9aa3-1372c666c94b.png)

I add 1 or 2 tasks to ConEmu (Git and Docker Terminal) and I don't think I misconfigured it

**Comment by sekai92id** [comment]
if you're already installed clinkz, you should remove clink from your system first.

**Comment by MartiUK** [comment]
As @sekai92id said, be sure to uninstall clink as we already include it.
