### ISSUE TITLE
ls from UnxUtils does not work

### ISSUE THREAD

**Issue by tfarina** [cmderdev/cmder#743]
λ ls
ls: unrecognized option `--show-control-chars'
Try `ls --help' for more information.

**Comment by MartiUK** [comment]
`ls` is aliased to `--show-control-chars` here : https://github.com/cmderdev/cmder/blob/development/vendor/aliases.example#L3

You should either delete that alias from $CMDER_ROOT/config/aliases or stop using unxutils.

**Comment by Ace-Who** [comment]
Or you can leave that alias and UnxUtils alone and add a space before "ls":
λ  ls

**Comment by Ace-Who** [comment]
Or you can leave that alias and UnxUtils alone and add a space before "ls":
λ <space>ls

**Comment by Ace-Who** [comment]
Or you can leave that alias and UnxUtils alone and add a space before "ls":
λ <additional space>ls

**Comment by Ace-Who** [comment]
Or you can leave that alias and UnxUtils alone and add a space before "ls":
λ <additional space>ls

**Comment by Ace-Who** [comment]
Or you can leave that alias and UnxUtils alone and add a space before "ls":
λ \<space\>ls

**Comment by Ace-Who** [comment]
Or you can leave that alias and UnxUtils alone and add a space before "ls":
λ \ ls

**Comment by NigelThorne** [comment]
If you type 'alias'  you get he list of aliases


> λ alias
> Use /? for help
> 
> clear=cls
> clink="D:\Program Files\cmder\vendor\clink/clink_x64.exe" --cfgdir "D:\Program Files\cmder\config" $*
> cmderr=cd /d "%CMDER_ROOT%"
> e.=explorer .
> gl=git log --oneline --all --graph --decorate  $*
> history=cat %CMDER_ROOT%\config\.history
> ls=ls --show-control-chars -F --color $*
> pwd=cd
> unalias=alias /d $1
> vi=vim $*

Then you can re-alias it without the "--show-control-chars"

> λ alias ls=ls -F --color $*
