### ISSUE TITLE
cmder.exe considered harmful by Bitdefender

### ISSUE THREAD

**Issue by halfpastfive** [cmderdev/cmder#744]
Hi, 

I downloaded the full version from your site today. 

EDIT : download URL  :https://github.com/cmderdev/cmder/releases/download/v1.2.9/cmder.zip

After unzip, the execution is blocked by my antivirus, stating that the app contains a malware Gen:Variant:Kazy (which seems to be an adware). 

Screenshot attached.
![malware](https://cloud.githubusercontent.com/assets/734678/11448315/c370ff0e-9555-11e5-9808-11e17eab4575.png)

**Comment by Stanzilla** [comment]
report it as a false positive please
