### ISSUE TITLE
extreme slowness in opening new tabs

### ISSUE THREAD

**Issue by aggieben** [cmderdev/cmder#752]
I'm experiencing an issue in which I open a new powershell tab and it takes a very long time to get to an interactive prompt.  I'm actually measuring everything happening in my `$profile`, and everything my profile does completes in less than 1 second total.  There's a long delay between the end of y `$profile` and the interactive prompt appearing.  

I don't use clink , I use PsReadline instead.

I realize I'm not giving you the technical info you would need to really debug, but I don't know what I don't know :-)

**Comment by tomasfejfar** [comment]
I actually have the same problem - and it seems to be caused by some node app running upon new tab creation. I suspect it's related to displaying git branch in prompt. I'd argue it might be the same issue here - not being an upstream issue. (see the tab title at the bottom - http://recordit.co/8LcoHlh1S8)

**Comment by aggieben** [comment]
I eventually wrote some profiling for my powershell profile, like this:

```PowerShell
# Measure-Command { Import-Module PsGet } |% { if ($PROFILE_PROFILE) { "$($_.ToString()) : import PsGet"}}
# Measure-Command { Import-Module pscx } |% { if ($PROFILE_PROFILE) { "$($_.ToString()) : import pscx"}}
# Measure-Command { Import-Module PsUrl } |% { if ($PROFILE_PROFILE) { "$($_.ToString()) : import PsUrl"}}
Measure-Command { Import-Module PsReadLine } |% { if ($PROFILE_PROFILE) { "$($_.ToString()) : import PsReadline"}}
```

et cetera.  This helped me narrow down where the time was going, and IIRC it was when it was loading posh-git (or one of its dependencies).  That, and maybe clink.  I can't remember the details now.

**Comment by tomasfejfar** [comment]
I've debugged it yesterday to clink-extensions (namely `Cmder\vendor\clink-completions\npm_prompt.lua`). So what I did was I picked some I felt are not necessary and renamed them to `*.lux`. Poof, problem gone.
