### ISSUE TITLE
Multiple location references when maximizing

### ISSUE THREAD

**Issue by twhitbeck** [cmderdev/cmder#753]
Running latest development branch: when I fullscreen (either by dragging titlebar to top of screen, using win+up kb shortcut, or clicking the maximize button) the current location line is duplicated 3 times or so. When minimizing, only one extra copy of the current location is added.

Before maximizing: 
![before](https://cloud.githubusercontent.com/assets/762471/11571692/9ffec784-99cb-11e5-8489-2ca124691797.PNG)

After maximizing: 
![after](https://cloud.githubusercontent.com/assets/762471/11571696/a6743810-99cb-11e5-96fc-63deb9b4457e.PNG)

**Comment by glucas** [comment]
+1 -- I'm seeing this as well.

**Comment by alanyee** [comment]
Sometimes, it seems to duplicate twice rather than three times.

**Comment by niwox** [comment]
+1

**Comment by MartiUK** [comment]
IIRC this is because there is no history for conemu to use, so it duplicates the prompt based on how you resize.

If you run some commands and try this again, you'll notice it'll use your history rather than repeating the prompt.

**Comment by MartiUK** [comment]
This has been fixed in clink 0.4.6, which is already part of cmder.
