### ISSUE TITLE
CTRL + Arrow key in integrated Sublime

### ISSUE THREAD

**Issue by tomm1996** [cmderdev/cmder#754]
Hello there,
I've integrated sublime into cmder at work, where I'm working with Windows 7.

So now I wanted to start doing this at home aswell, where I have Windows 10 (10.0.10240) installed, but when I press ctrl + any arrow key this menu appears and sublime loses focus.
![image](https://cloud.githubusercontent.com/assets/4152001/11574639/23080316-9a0d-11e5-9952-f8c3d8caf78e.jpg)

This is pretty annoying since I usually use this shortcut to jump before the word on the left side of my cursor position.

Any way to fix this?

**Comment by jakelucas** [comment]
I would also like to know if there is any solution to this problem.

I have tried customising key bindings and all kinds of settings in cmder, but nothing seems to change it.

For now I have changed my key bindings to use `alt` for commands that involve the arrow keys instead, but it isn't ideal.
