### ISSUE TITLE
I can't run de Cmder.exe

### ISSUE THREAD

**Issue by ffcc** [cmderdev/cmder#755]
I download the project as a zip, unzip and when I try to execute the Cmder.bat I have the following error: **Windows cannot find '<CMDER_UNZIP_FOLDER>/vendor/conemu-maximus5/ConEmu.exe'. Make sure...**

I look the vendor folder and eventually conemu-maximus5 doesn't exist. What I doing wrong? My OS is Windows 8 x64.

**Comment by Stanzilla** [comment]
You have to download from the releases page, not from the repo itself.  https://github.com/cmderdev/cmder/releases

**Comment by ffcc** [comment]
Thanks!
