### ISSUE TITLE
'ls' is no longer recognized command

### ISSUE THREAD

**Issue by dmxt** [cmderdev/cmder#757]
I'm using cmder version of cmd.exe and command `ls` used to work fine. I don't know what changed, but it's no longer recognized.

```
C:\Users\Dana
λ ls
'ls' is not recognized as an internal or external command,
operable program or batch file.
```

Does anyone know the solution to this problem?

**Comment by glucas** [comment]
The error indicates that `ls` is not on your PATH. Cmder includes an `ls` executable as part of the git distribution, which is added to the PATH by the default cmder\vendor\init.bat script.

From my shell I can see that `ls` is on the path:

    λ where ls
    C:\opt\cmder\vendor\git-for-windows\usr\bin\ls.exe

**Comment by dmxt** [comment]
@glucas How do I add ls to my PATH?

**Comment by MartiUK** [comment]
Have you tried installing the full version of cmder?

**Comment by dmxt** [comment]
@MartiUK I installed full version of cmder and it worked fine till few days ago and I have no idea what happened, it just stopped working on it own.

**Comment by glucas** [comment]
There are a couple things you should investigate:

What is currently on your cmder shell path? Use `set PATH` to see the semicolon-delimited list of path entries. Presumably there are entries there for cmder and some of its subdirectories. 

Have you installed some version of Git outside of cmder? 

Does your cmder installation include git as it should? I've installed v.1.2.9 of cmder, is that what you have or do you have something older? In my case git is installed here: 

    cmder/vendor/git-for-windows 

and the ls executable is 

    cmder/vendor/git-for-windows/usr/bin/ls.exe

Either something is wrong with your installation and you are missing those directories/files, or you have them but your PATH does not include the directory for some reason. If you do have the files you can try adding the directory containing ls.exe to your path from the shell, e.g. 

    set PATH=C:\cmder\vendor\git-for-windows\usr\bin;%PATH%

Then try `ls` and see if it works. If so, you can copy that same line to your cmder/config/user-startup.cmd file to make the change permanent. (If you're on an older version of cmder you may not have the file and would have to put this somewhere else).

**Comment by nmstoker** [comment]
I know this is old, but thought this might just be relevant to someone...

@dmxt not sure if it's the same root, but I had exactly this symptom on a brand new full version install of cmder and I eventually realised (thanks to @glucas's pointers above) that it was going wrong for me  because my version of Git for Windows was fairly old and it seems to have had no **/usr** directory.

Thus when cmder was identifying that I already had Git and adding to my PATH for that (see **init.bat** within **cmder\vendor\** ) it tried to look in **\Git\usr\bin\** for **ls.exe** and failed to find it (as there was no such directory).

Rather than edit **init.bat** (_and face it going wrong when I subsequently update cmder_) I simply installed the newest version of Git for Windows and on re-opening cmder all was fine :smile:

**Comment by sderrico** [comment]
@nmstoker Thank you! With your comment, it took me 2 minutes to solve this issue!

**Comment by nyangeta** [comment]
Hi 
I need help to resolve this problem .Spent 7 hrs without any lucky

'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

**Comment by nyangeta** [comment]
Hi 
I need help to resolve this problem .Spent 7 hrs without any lucky

'C:\Program' is not recognized as an internal or external command,
operable program or batch file

**Comment by nmstoker** [comment]
@nyangeta sorry, but you haven't given enough detail for anyone to work out your problem (even though I've a few guesses) As this may well be a completely separate cause from this issue, I'd suggest checking existing issues and possibly raise a new issue if you still draw a blank on here and Stackoverflow. Good luck!

**Comment by rogelio0805** [comment]
<img width="675" alt="ls issue" src="https://user-images.githubusercontent.com/39346760/49111372-e86ae500-f25d-11e8-9e1c-1b878d2707d7.png">
<img width="293" alt="ls issue 2" src="https://user-images.githubusercontent.com/39346760/49111437-21a35500-f25e-11e8-920a-8fcbeece61ad.png">
Every time I try to use the command ls (I have two ls.exe in my computer, how can i choose the right one  )

**Comment by glucas** [comment]
The 'where' command is showing you the results in the order they are in your PATH. So the ls.exe you don't want is being found first in your PATH. 

It seems like you have Z:\ as an entry in your PATH ahead of git. You could find where that is coming from and remove it, or you can add some commands to your cmder user_profile.cmd to make sure the git bin dir is added to the front of your PATH.
