### ISSUE TITLE
Option to disable preview stacking with multiple tabs

### ISSUE THREAD

**Issue by MadLittleMods** [cmderdev/cmder#758]
Add an option to only show a single instance in the task bar (no stacking). Similar to the [option for Internet Explorer](http://superuser.com/a/131150/130885).

This allows for easily getting to the desired tab via the Cmder UI versus the Windows preview from the task bar. The extra click to restore the currently open and active tab is not as nice for my workflow.

![](https://i.imgur.com/iW4no42.png)

https://github.com/cmderdev/cmder/issues/356#issuecomment-162509172

**Comment by MadLittleMods** [comment]
Associated issue on the ConEmu repo: https://github.com/Maximus5/ConEmu/issues/526

**Comment by MadLittleMods** [comment]
This option is already available in ConEmu under `Taskbar -> Taskbar buttons group -> Active console only` - Thanks to @Maximus5 for [pointing it out](https://github.com/Maximus5/ConEmu/issues/526#issuecomment-180085781)!

**Comment by kingRayhan** [comment]
@MadLittleMods thanks you so much. You saved lots of my time 😍

**Comment by andrasnyarai** [comment]
@kingRayhan  additionally you can use the 'global summon' - hotkey out of the box, instantly focusing cmder window. (ctrl + ö) in my setup, you can set it to not interfere with other hotkeys.
