### ISSUE TITLE
Cannot start a cmd file from shortcut/cli

### ISSUE THREAD

**Issue by thany** [cmderdev/cmder#760]
I'm trying to get cmder to run a cmd file when I launch it, by starting it from a shortcut. I can't seem to figure out how to do that, because no matter what I do, it never ever starts the cmd file.

Let's start from the commandline:

```
cmder /start my-commands.cmd
```

Starts a new cmder instance with the message `The directory name is invalid.` and then continues on like a default instance.

Perhaps it doesn't know what a cmd file is.

```
cmder /start cmd.exe /k my-commands.cmd
```

Same deal.

Perhaps it doesn't know where cmd.exe is.

```
cmder /start %ComSpec% /k my-commands.cmd
```

Same deal.

Maybe it just doesn't work or something. The cmd file honestly exists and it doesn't matter if I supply it with its full path or not. And then there's still the issue of specifying the working directory in a shortcut, which needs to be correct for my cmd files, but Cmder forces it to whatever has been set in the settings.

**Comment by MrRooks** [comment]
I'm trying to figure this out as well. But what I did figure out is that /start command is for setting the directory cmder starts in. So if you did cmder /start c:\ it would start a new cmder session in the c:\ directory. I can't get it to run anything from a commandline.

**Comment by thany** [comment]
Closed means fixed?

**Comment by MartiUK** [comment]
@thany Do you want to run the file every time or just the once?
