### ISSUE TITLE
How do confirm exe's are safe? md5? checksum?

### ISSUE THREAD

**Issue by born2net** [cmderdev/cmder#761]
I looked through the docs and I can't find anyway of telling is the cmder checksumed properly...
is the application safe? no Trojans etc?

tx

Sean

**Comment by actowolfy** [comment]
For cmder.zip
MD5: 4952E2AFAF3E036D955F7A7342C16057

CRC32: E90EC886

SHA1: 0C4F972142E6E55453C03AA3FE7B3FF01C336385

SHA256: 1893CBB9C0CBA30F668DFA2C57791B3D087C0FBF033878835B098C10A63630A5

SHA384: 53F44498E47CC321D286BAA2CC84C081123C19BC262AE0DEEC45FDD3F316BE1281B0EBE4D6743A38EF0DBB87750FE30D

SHA512: 
4732BCFDA4AA2D3F2A8E1E3087D60D92EE0BC863A9C36A0C2B6CAA4DCCF57F3BB11B536D36C0AAB6AD115E23118FAB35BEED2FAA584987602BF61E50343BE3DD
RIPEMD-160: E383FEBF049D4F979AFAE290555068B74722394E

**Comment by joaumg** [comment]
VirusTotal Scan: https://www.virustotal.com/en-gb/file/1893cbb9c0cba30f668dfa2c57791b3d087c0fbf033878835b098c10a63630a5/analysis/

**Comment by born2net** [comment]
so the viruses found are false positive?
I also have a question about ComEmu etc... since they are compiled to exe when we run them, how do we know there is no Trojans in any of that code... ?

tx

**Comment by actowolfy** [comment]
If you really have that big of problem with thinking there's malicious code then sift through the source code on here and build it yourself.
