### ISSUE TITLE
Security Warning - cmder\vendor\profile.ps1

### ISSUE THREAD

**Issue by nxion** [cmderdev/cmder#767]
I seem to be getting an error every time I run cmder and was wondering what I'm doing wrong. The result from `Get-ExecutionPolicy` states that I'm set to `Unrestricted`. The machine sis a WIndows 10 Pro. See the screenshot below

![capture](https://cloud.githubusercontent.com/assets/262779/11759626/db12f34c-a03b-11e5-9afc-9a8a0a5d9867.PNG)

**Comment by MartiUK** [comment]
You need to set your execution policy so you can run powershell scripts such as the profile script included with cmder.

**Comment by nxion** [comment]
I ran `set-executionpolicy unrestricted -s cu` to set it to unrestricted. Is that not the correct command?

**Comment by MartiUK** [comment]
Ah, sorry, run `Unblock-File Profile.ps1`. Windows sometimes blocks scripts downloaded from the internet.

**Comment by nxion** [comment]
Thanks. I will try that later. I do have to say, this is a fantastic project. I love the command line on Linux but have always found the Windows command line to be so cumbersome to use. Recently I have transitioned back to a Windows server admin and this has made my life MUCH easier. Feel like a Linux box :). Kudos!

**Comment by konius** [comment]
@MartiUK Thanks, that solved the problem
