### ISSUE TITLE
How to make Cmder stop displaying warning?

### ISSUE THREAD

**Issue by dmxt** [cmderdev/cmder#768]
Everytime I launch Cmder I receive this warning:

```
WARNING! The MacType's hooks are detected at 0x0000000180000000
         C:\Program Files (x86)\MacType\MacType64.dll
         Please add ConEmuC.exe and ConEmuC64.exe
         to the exclusion list to avoid crashes!
         http://conemu.github.io/en/Installation.html#mactype
```
I can't exclude these .exe on MacType because it's running in a registry. The solution work if you run MacType as a service or background app. But the thing is: it doesn't affect Cmder, so I'm not worried about the solution.

How can I make Cmder stop displaying this warning?

**Comment by Stanzilla** [comment]
That's more of a ConEmu issue, please file a ticket over there: https://github.com/Maximus5/ConEmu

**Comment by cocoZhong** [comment]
add "cls" in file /vendor/init.bat XD

**Comment by FateLight** [comment]
@cocoZhong add "cls" in file /vendor/init.bat XD？What should I do？thanks

**Comment by cocoZhong** [comment]
@FateLight add an clear screen command at the bottom of file init.bat.

**Comment by Obspogon** [comment]
do this https://github.com/Maximus5/ConEmu/issues/463
