### ISSUE TITLE
Startup Error: cmder\vendor\profile.ps1 cannot be loaded.

### ISSUE THREAD

**Issue by alanyee** [cmderdev/cmder#769]
Everytime I start up Cmder, I get
```
. : File C:\Users\Alan\Desktop\Dropbox\cmder\vendor\profile.ps1 cannot be loaded. The file
C:\Users\Alan\Desktop\Dropbox\cmder\vendor\profile.ps1 is not digitally signed. You cannot run this script on
the current system. For more information about running scripts and setting execution policy, see
about_Execution_Policies at http://go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:3
+ . 'C:\Users\Alan\Desktop\Dropbox\cmder\vendor\conemu-maximus5\..\prof ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```
How do I fix this problem?

**Comment by daxgames** [comment]
Open PowerShell. Type 'set-execution policy remotesigned' without the quotes.

**Comment by daxgames** [comment]
Needs to be PowerShell as admin

**Comment by alanyee** [comment]
Oh I just reinstalled cmder, and it worked. Anyways thanks for the help.

**Comment by ngocphamm** [comment]
For others having same issue, I don't know why but the command I have to put into PowerShell is `set-ExecutionPolicy remotesigned`. Thanks @daxgames for the hint!

**Comment by rowet** [comment]
I do not have privileges to set the execution policy at the Machine or User policy level, so the fix does not work.
Is there any other way to get around this annoying error? Perhaps generate a local signature? (I don't know how signing works.)
