### ISSUE TITLE
Can't change settings to default for fullscreen

### ISSUE THREAD

**Issue by alanyee** [cmderdev/cmder#770]
So far, cmder just opens with a minimal window with half it disappearing off the side of the screen. How do I edit where the screen shows since it does not obey the conventional layman way of remembering its window size and placement before I closed it? Also why do I have that window opening up in an odd place as default?

TLDR: How do I have cmder default to open in fullscreen?

**Comment by daxgames** [comment]
Mine opens using same screen position it had when I closed it.  Closing due to it seems to now work as requested and inactivity.
