### ISSUE TITLE
CMDER_START should always be set to USERPROFILE unless explicitly set through /START parameter

### ISSUE THREAD

**Issue by MartiUK** [cmderdev/cmder#772]
- [x] CmderLauncher.cpp: set CMDER_START to USERPROFILE unless set through /START param.
- [ ] Conemu.xml: Always use CMDER_START for new tasks.

**Comment by JanSchulz** [comment]
cmder is also registered as `"C:\Users\jschulz\Dropbox\Programme\cmder\Cmder.exe" "%V"` but the startup requires `/START` https://github.com/cmderdev/cmder/blob/development/launcher/src/CmderLauncher.cpp#L290

**Comment by JanSchulz** [comment]
Whatever, adding it also didn't make cmder start up in the directory I rightclicked.

**Comment by MartiUK** [comment]
I haven't made these changes yet, but it should fix most issues regarding `/START`.

**Comment by JanSchulz** [comment]
Ok, I think it's ok not to have /START in the context menu integration, but I think that the path argument is ignored in https://github.com/cmderdev/cmder/blob/development/launcher/src/CmderLauncher.cpp#L155 So in the moment it looks like the right click integration is broken? At least it doesn't work on my computer :-(

**Comment by MartiUK** [comment]
The problem with cmder_here stems from the fact that the tasks do not use CMDER_START as an initial directory to work with.

**Comment by JanSchulz** [comment]
What should the outcome be here? 

* `cmder /START <dir>` (right click "cmder here") -> should overwrite all settings?
* the tasks can specify it's own startup path 
* if a user sets `CMDER_START` -> not sure what priority that should have?

It seems for `PS`, the path gets applied to a registry key which is then used to set the `CWD`. For `cmd`, this registry key is ignored and `CMDER_START` env variable is used (which is not set by `cmder.exe`).  `shell` doesn't seem to change anything...

Unfortunately, the `init.bat` file always overwrites the current dir with the `"%HOME%"` if `CMDER_START` is not set.

IMO:
* if a path is set in `cmder /START <path>`, this path should overwrite everything
* if a user specifies a `CMDER_START` environment variable, it should be applied
* as a last measure, the set working dir (by the task) should be taken last.

* all tasks should set a working directory (which they do? `-new_console:d:%USERPROFILE%`)

IMO this could be done by letting `cmder.exe` setting/overwriting `CMDER_START` if  `path` is set. And get that implemented in all startup scripts.

**Comment by JanSchulz** [comment]
tried to make https://github.com/cmderdev/cmder/issues/772#issuecomment-170615849 happen in #798

**Comment by MartiUK** [comment]
@JanSchulz See #803 also.
