### ISSUE TITLE
cmder.exe does not exist

### ISSUE THREAD

**Issue by buckhorn-foxpert** [cmderdev/cmder#774]
I am following the instructions to add cmder to the shortcut menu and it says to run 
Execute  cmder.exe /REGISTER ALL
from the command window, but there is no cmder.exe in the download.  How are we supposed to install cmder?

**Comment by Stanzilla** [comment]
Where did you download which file exactly?

**Comment by buckhorn-foxpert** [comment]
I clicked the download zip button on this link https://github.com/cmderdev/cmder

**Comment by Stanzilla** [comment]
Ah, I see. Please use the packages provided here https://github.com/cmderdev/cmder/releases

What you downloaded is the source code only.

**Comment by buckhorn-foxpert** [comment]
Thank you
