### ISSUE TITLE
[Windows 8] vagrant.lua message

### ISSUE THREAD

**Issue by arcanedev-maroc** [cmderdev/cmder#779]
Everytime i open a new tab on cmder, i got this message :

`cmder/vendor/clink-completions/vagrant.lua:66: Additional arguments to new_parser() must be tables or strings`

How i can solve that (cmder v1.2.9) ??

**Comment by daxgames** [comment]
@vladimir-kotikov I have this too.  You know what it is and how to fix it.  I'm not a lua expert but since this came from your repo I hope you know how to fix it?

**Comment by daxgames** [comment]
Mine is an issue on WIndows 7.  Have not tried Windows 8.

**Comment by okoetter** [comment]
As a workaround you can comment line 66 in vagrant.lua by putting a double hyphen `--` at the beginning of the line. The error message does not appear after that. I don't know the consequences because I don't know lua but as the line seems to be syntactically wrong it won't work either way.

**Comment by vladimir-kotikov** [comment]
@arcanedev-maroc, @daxgames, This might happen because of outdated clink distribution. Mine is `v0.4.6 [git:82fc65]` and I don't see this problem. Could you please post your clink version here?

**Comment by vladimir-kotikov** [comment]
Also tried to upgrade to latest clink (`v0.4.7 [git:dfc95a]`) - no issues as well

**Comment by daxgames** [comment]
I updated to the latest clink but no fix.  it turned out that I had outdated lua bits in my config folder.

**Comment by arcanedev-maroc** [comment]
I solved it by downloading the latest artifact of cmder from AppVeyor: https://ci.appveyor.com/project/MartiUK/cmder

Hope this helps you.

**Comment by aaroncalderon** [comment]
Even though this issue is closed, I want to report I have same issue.

* cmder v.1.3.0-pre
* clink  v0.4.7 [git:dfc95a]
* OS. Windows 7 32bit

I do use Vagrant for some stuff. Fixing this issue will give me peace of mind just knowing I get to take advantage of all the features cmder offers. 

Thanks

**Comment by leppie** [comment]
I had `cmder.lua` hanging around. Deleting it solved the problem.

**Comment by aaroncalderon** [comment]
I updated to cmdr v1.3.0 and it fixed the issue.
