### ISSUE TITLE
How should i add a context menu entry?

### ISSUE THREAD

**Issue by Droyk** [cmderdev/cmder#780]
**You are about too read some bad english. and i am really sorry about it i am not a native english speaker**

Hey guys sorry if this is the not right way to ask this question 

So guys the developer of Cmder said that if you want to add Cmder  on your context menu then you should  do this Execute .\cmder.exe /REGISTER ALL
If you get a message "Access Denied" ensure you are executing the command in an Administrator prompt.

i am trying it but it always says this 
![screenshot_20151226113730](https://cloud.githubusercontent.com/assets/15848350/12005324/56d7a9c0-abc5-11e5-894f-8227ad4ee990.png)

plz help me gys and plz bear with i am just a normal kid so plz huh

**Comment by officialQP** [comment]
Open a CMD by searcing it in the search bar in windows, right click open as administrator and then type what he sent you maybe?

**Comment by Droyk** [comment]
[**@officialQP**](https://github.com/officialQP) commented on [Dec 26, 2015, 3:18 PM GMT+5:30](https://github.com/cmderdev/cmder/issues/780#issuecomment-167304826 "2015-12-26T09:48:31Z - Replied by Github Comment Enhancer"):
> Open a CMD by searcing it in the search bar in windows, right click open as administrator and then type what he sent you with out the . maybe?

**its not working it say's the same thing as cmder**

**Comment by Droyk** [comment]
[**@officialQP**](https://github.com/officialQP) commented on [Dec 26, 2015, 3:18 PM GMT+5:30](https://github.com/cmderdev/cmder/issues/780#issuecomment-167304826 "2015-12-26T09:48:31Z - Replied by Github Comment Enhancer"):
> Open a CMD by searcing it in the search bar in windows, right click open as administrator and then type what he sent you with out the . maybe?

I did it actually i have to do it without . & / and write it simple as this `cmder.exe /REGISTER ALL`

now i want to know how to get this option when you right click + shift click

**Comment by Vatsa774** [comment]
It's a part of the Wiki, guys..
https://github.com/cmderdev/cmder/wiki/%5BWindows%5D-%22Open-Cmder-Here%22-in-context-menu

**Comment by Droyk** [comment]
[**@Vatsa774**](https://github.com/Vatsa774) commented on [Dec 30, 2015, 11:25 PM GMT+5:30](https://github.com/cmderdev/cmder/issues/780#issuecomment-168045423 "2015-12-30T17:55:32Z - Replied by Github Comment Enhancer"):
> It's a part of the Wiki, guys..
> [https://github.com/cmderdev/cmder/wiki/%5BWindows%5D-%22Open-Cmder-Here%22-in-context-menu](https://github.com/cmderdev/cmder/wiki/%5BWindows%5D-%22Open-Cmder-Here%22-in-context-menu)  
> This adds it to the context menu, standard right click will suffice.

actually i did it with this method `cmder.exe /REGISTER ALL` and i tried your method too but 
what i really want is an entry when i press shift + right click . that's the only thing i want

**Comment by aedotj** [comment]
Add the string value "Extended" to [HKEY_CLASSES_ROOT\Directory\Background\shell\Cmder], so it looks like this:
![capture](https://cloud.githubusercontent.com/assets/7189784/12078530/2fa3c378-b216-11e5-8527-b2789a707d06.PNG)

**Comment by Droyk** [comment]
[**@aedotj**](https://github.com/aedotj) commented on [Jan 3, 2016, 5:03 PM GMT+5:30](https://github.com/cmderdev/cmder/issues/780#issuecomment-168490185 "2016-01-03T11:33:52Z - Replied by Github Comment Enhancer"):
> Add the string value "Extended" to [HKEY_CLASSES_ROOT\Directory\Background\shell\Cmder], so it looks like this:  
> 
> [![capture](https://cloud.githubusercontent.com/assets/7189784/12078530/2fa3c378-b216-11e5-8527-b2789a707d06.PNG)](https://cloud.githubusercontent.com/assets/7189784/12078530/2fa3c378-b216-11e5-8527-b2789a707d06.PNG)
> 
> If you want the .reg file to do it, it's pretty simple: (note that this is not my own .reg export, but the one from the [wiki](https://github.com/cmderdev/cmder/wiki/%5BWindows%5D-%22Open-Cmder-Here%22-in-context-menu)).
> 
>     Windows Registry Editor Version 5.00
> 
>     [HKEY_CLASSES_ROOT\Directory\Background\shell\Cmder]
>     @="Open Cmder Here"
>     "Extended"=""
> 
>     [HKEY_CLASSES_ROOT\Directory\Background\shell\Cmder\command]
>     @=hex(2):25,00,43,00,4d,00,44,00,45,00,52,00,5f,00,49,00,4e,00,\
>       53,00,54,00,41,00,4c,00,4c,00,5f,00,44,00,49,00,52,00,25,00,5c,00,43,00,6d,\
>       00,64,00,65,00,72,00,2e,00,65,00,78,00,65,00,20,00,2f,00,53,00,54,00,41,00,\
>       52,00,54,00,20,00,22,00,25,00,76,00,22,00,00,00
> 
> If you want mine instead (there's an icon, and you choose the directory without modifying your PATH, here it is:
> 
>     Windows Registry Editor Version 5.00
> 
>     [HKEY_CLASSES_ROOT\Directory\shell\cmder]
>     @="Open Cmder here"
>     "Icon"="\"C:\\Path\\To\\Cmder.exe\",0"
>     "Extended"=""
> 
>     [HKEY_CLASSES_ROOT\Directory\shell\cmder\command]
>     @="\"C:\\Path\\To\\Cmder.exe\" /start \"%V\""
> 
>     [HKEY_CLASSES_ROOT\Directory\background\shell\cmder]
>     @="Open Cmder here"
>     "Icon"="\"C:\\Path\\To\\Cmder.exe\",0"
>     "Extended"=""
> 
>     [HKEY_CLASSES_ROOT\Directory\background\shell\cmder\command]
>     @="\"C:\\Path\\To\\Cmder.exe\" /start \"%V\""
> 
> _Note: The first key (`HKEY_CLASSES_ROOT\Directory\shell\cmder`) adds "Open Cmder here" to the context menu when right-clicking on a folder, and the second key (`KEY_CLASSES_ROOT\Directory\background\shell\cmder`) adds "Open Cmder here" to the context menu when right-clicking on the background of the directory.  
> 
> You can simply delete `"Extended"=""` if you don't want to press SHIFT when right-clicking._

Really Thanxx about this and there is one more question i want to ask you is can this all be done via command for e.g. this command does everything `cmder.exe /REGISTER ALL` but the only thing is i want this in right click + shift mode .....so can this be done via command ............. i just want this function via shift + right click with the help of command can you plz help me with this thanxx.....

**Comment by aedotj** [comment]
@Droyk Not sure I understand. If you wanna register everything with a command (such as REG), yes you can, but it would be harder than just using a .reg file. Open up your console, and type `REG /?`.

This is, I believe, the best way to deal with the registry via the command line.

**Comment by Droyk** [comment]
[**@aedotj**](https://github.com/aedotj) commented on [Jan 6, 2016, 2:44 AM GMT+5:30](https://github.com/cmderdev/cmder/issues/780#issuecomment-169135706 "2016-01-05T21:14:06Z - Replied by Github Comment Enhancer"):
> [@Droyk](https://github.com/Droyk) Not sure I understand. If you wanna register everything with a command (such as REG), yes you can, but it would be harder than just using a .reg file. Open up your console, and type `REG /?`.
> 
> This is, I believe, the best way to deal with the registry via the command line.

actually i am not saying to deal with registry at all what i am saying is just to use command to hide the option in context menu and show the option when right click + shift ..........

for e.g. `cmder.exe /REGISTER ALL` if you paste this command in cmder it will show the option in the context menu. what i want is to enhance this command to hide when a user click right click and to show when a user press shift + right click .that's what i really want

**Comment by esphas** [comment]
Add the string value `Extended` via regedit mannually is enough to make command `Cmder Here` only appears in shift right click.

But if you are looking forward to a solution that solves the problem via command line, I have to say: **that's simply impossible yet**. As you can see, [the RegisterShellMenu won't register more in registry](https://github.com/cmderdev/cmder/blob/master/launcher/src/CmderLauncher.cpp#L167) (L189-L203). (Even the same in `release-1.3`: [L216-L230](https://github.com/cmderdev/cmder/blob/release-1.3/launcher/src/CmderLauncher.cpp#L194))

Maybe they will add that feature later on?

**Comment by Droyk** [comment]
[**@esphas**](https://github.com/esphas) commented on [Jan 6, 2016, 9:39 AM GMT+5:30](https://github.com/cmderdev/cmder/issues/780#issuecomment-169215446 "2016-01-06T04:09:22Z - Replied by Github Comment Enhancer"):
> But if you are looking forward to a solution that solves the problem via command line, I have to say: **that's simply impossible yet**. As you can see, [the RegisterShellMenu won't register more in registry](https://github.com/cmderdev/cmder/blob/master/launcher/src/CmderLauncher.cpp#L167) (L189-L203). (Even the same in `release-1.3`: [L216-L230](https://github.com/cmderdev/cmder/blob/release-1.3/launcher/src/CmderLauncher.cpp#L194))
> 
> Maybe they will add that feature later on?

but what about the simple windows CMD ?

I think windows cmd or powershell can help us on that

**Comment by esphas** [comment]
@Droyk Oh I thought you want to do it someway like `cmder.exe /register /ex all`...

Since you just need to run it via command line, that's simple: Run cmd or anything like that **as Administrator**, then:
```
reg add hkcr\directory\shell\cmder /v Extended
reg add hkcr\directory\background\shell\cmder /v Extended
```
This should work.

**Comment by Droyk** [comment]
[**@esphas**](https://github.com/esphas) commented on [Jan 6, 2016, 10:03 AM GMT+5:30](https://github.com/cmderdev/cmder/issues/780#issuecomment-169217513 "2016-01-06T04:33:46Z - Replied by Github Comment Enhancer"):
> [@Droyk](https://github.com/Droyk) Oh I thought you want to do it someway like `cmder.exe /register /ex all`...
> 
> Since you just need to run it via command line, that's simple: Run cmd or anything like that **as Administrator**, then:
> 
>     reg add hkcr\directory\shell\cmder /v Extended
>     reg add hkcr\directory\background\shell\cmder /v Extended
> 
> This should work.

thanxxx i knew it's possible but when i see other responses i was depressed and thought you can't just add that using the command line tool.....thanxxx.......for telling me

actually it is bit of my fault because of bad english. and i am really sorry about it i am not a native english speaker its only been 2 months since i started learning English and right-now i can only read and understand it properly but i can't write properly Poor me

**Comment by Droyk** [comment]
close

**Comment by Droyk** [comment]
[**@esphas**](https://github.com/esphas) commented on [Jan 6, 2016, 10:03 AM GMT+5:30](https://github.com/cmderdev/cmder/issues/780#issuecomment-169217513 "2016-01-06T04:33:46Z - Replied by Github Comment Enhancer"):
> [@Droyk](https://github.com/Droyk) Oh I thought you want to do it someway like `cmder.exe /register /ex all`...
> 
> Since you just need to run it via command line, that's simple: Run cmd or anything like that **as Administrator**, then:
> 
>     reg add hkcr\directory\shell\cmder /v Extended
>     reg add hkcr\directory\background\shell\cmder /v Extended
> 
> This should work.

thanxxx i knew it's possible but when i see other responses i was depressed and thought you can't just add that using the command line tool.....thanxxx.......for telling me

actually it is bit of my fault because of bad english. and i am really sorry about it i am not a native english speaker its only been 2 months since i started learning English and right-now i can only read and understand it properly but i can't write properly Poor me

**Comment by snowmaniowa** [comment]
Worked like a charm. Thank you!!
