### ISSUE TITLE
[v1.2.9] Can not alias with env. variables.

### ISSUE THREAD

**Issue by esphas** [cmderdev/cmder#784]
Env. variables in `config\aliases` will not work - they just display as is. But do alias in cmder works.
In `config\aliases`:
```
ppath=echo %PATH%
```
In cmder:
```
λ ppath
%PATH%
λ echo %PATH%
C:\WINDOWS\System32\...
λ alias ppath=echo %PATH%
λ ppath
C:\WINDOWS\System32\...
```
And, er..
In cmd:
```
> set CMDER_ROOT=e:\uts\cmder
> cd bin
> alias.bat /reload
Aliases reloaded
> ppath
C:\WINDOWS\System32\...
```
It might be related to the strange behavior of `doskey`:
In cmder:
```
λ doskey /macrofile=e:\uts\cmder\config\aliases
λ ppath
%PATH%
```
In cmd:
```
> doskey /macrofile=e:\uts\cmder\config\aliases
> ppath
C:\WINDOWS\System32\...
```
---
Edit:
Well, I found it reasonable why alias directly in cmder can use env. variables because the `bin\alias.bat` just got the real PATH as an argument instead of the string "%PATH%" - it just stored the value in `config\aliases` when exactly running.

But I still don't understand the problem itself - why `doskey` works wrong with cmder.

**Comment by okaufmann** [comment]
same problem here

**Comment by esphas** [comment]
I found another issue reports the same problem: #684 

It seems the dev build of clink can be used as a temporary fix. Anyway I thought this issue can be closed?
