### ISSUE TITLE
Git LFS support

### ISSUE THREAD

**Issue by Djabx** [cmderdev/cmder#785]
Hi,

I personally use the git included in cmder (and do not install anything else) but I would like to use the new and shiny large file support for git (cf: https://git-lfs.github.com/ ).
Do you think this could be included in cmder ?

BTW: if the external git is preffered (as proposed in #782 ), that would solve this "problem" .

**Comment by Jackbennett** [comment]
I had no idea git-lfs supported windows. I don't think we'll be pulling in git-lfs as portable install in the large cmder so I don't see how we can add this support. Instead we should prefer external git.

I see you can get git-lfs from `choco install git-lfs.install` so maybe it can be as simple as a startup command.
