### ISSUE TITLE
Change how we check for git directories in cmder.lua

### ISSUE THREAD

**Issue by MartiUK** [cmderdev/cmder#786]
See https://github.com/git/git/blob/master/contrib/completion/git-prompt.sh#L362

**Comment by vladimir-kotikov** [comment]
@MartiUK, you meant [this line](https://github.com/git/git/blob/master/contrib/completion/git-prompt.sh#L362)?

**Comment by MartiUK** [comment]
@vladimir-kotikov Yeah, should cut down on the time it takes to work up the directory tree to find a .git folder.

**Comment by JanSchulz** [comment]
Actually, the rebase hints and the info if I'm behind the remote are also nice... :-)

**Comment by vladimir-kotikov** [comment]
It would be great if this will improve perfomance, but i recall that we've been relying on git already at some moment before #438 and there were some performance issues... Unfortunately, git on Windows is not so super-fast as on Nix machines :(

**Comment by vladimir-kotikov** [comment]
Made some timings, and the results are not very promising:

 | Current | Using `git rev-parse`
------|-----------|--------------------------
Non-git directory | 0 | 0.22
Git repo | 0.30 | 0.55

So IMO it's better to keep the current approach. Personally for me it's not very comfortable to wait ~0.5 sec each time before thr prompt updates.

**Comment by JanSchulz** [comment]
@vladimir-kotikov Can you tell how you did the timing? That would make a nice test how to evaluate changes to this functions... :-)

**Comment by vladimir-kotikov** [comment]
Just printouts, exactly the same as in the gist
