### ISSUE TITLE
How to remove "Cmder Here" in the context menu after .\cmder.exe /REGISTER ALL?

### ISSUE THREAD

**Issue by ladder1984** [cmderdev/cmder#787]
How to remove "Cmder Here" in the context menu after .\cmder.exe /REGISTER ALL?

**Comment by Droyk** [comment]
first go to cmder and type this `cmder.exe /UNREGISTER ALL`
then 

Run regedit and go to HKEY_CLASSES_ROOT\Directory\Background\shell\
and delete cmder folder

and then go to HKEY_CLASSES_ROOT\Directory\shell
and delete cmder folder

and that's it you have done it voila :smile:

**Comment by esphas** [comment]
Actually you can head to `HKEY_CLASSES_ROOT\Directory` directly and delete item `Cmder`, and the same within `\backgrond`. No need to run `cmder.exe /UNREGISTER ALL`.

**Comment by Droyk** [comment]
[**@esphas**](https://github.com/esphas) commented on [Jan 6, 2016, 9:22 AM GMT+5:30](https://github.com/cmderdev/cmder/issues/787#issuecomment-169213935 "2016-01-06T03:52:40Z - Replied by Github Comment Enhancer"):
> Actually you can head to `HKEY_CLASSES_ROOT\Directory` directly and delete item `Cmder`, and the same within `\backgrond`. No need to run `cmder.exe /UNREGISTER ALL`.

ahh i knew it well **@ladder1984** now you can directly delete reg entries without initiating the command so be happy and close this issue

**Comment by ladder1984** [comment]
@esphas @Droyk  Thanks.

**Comment by 4AIS** [comment]
Cannot remove cmd. Error deleting partition. How can I solve this?

**Comment by daxgames** [comment]
`cmder.exe /UNREGISTER ALL` as Administrator.
`cmder.exe /UNREGISTER USER` as a specific user
