### ISSUE TITLE
How many day's more it will take to release a new updated version ?

### ISSUE THREAD

**Issue by Droyk** [cmderdev/cmder#788]
Note: You are about too read some bad english. and i am really sorry about it i am not a native english speaker

Hey guys i am just a newbee and it seems like cmder is not updated in months so when will it will be updated ? is there any developer version or any beta version are around ? plz tell me

**Comment by MartiUK** [comment]
I'm currently busy with work and other commitments to work on cmder every day, if I do find a chunk of time to work on it I'll be sure to have a pre-release available.
