### ISSUE TITLE
% variable expansion in config/alias

### ISSUE THREAD

**Issue by thecere** [cmderdev/cmder#791]
The % variable expansion in https://github.com/cmderdev/cmder/blob/master/config/aliases does not work for me (win 10):

    λ history
    cat: %CMDER_ROOT%\config\.history: No such file or directory
    λ which doskey
    /c/WINDOWS/system32/doskey

**Comment by JanSchulz** [comment]
IMO this error only means that `.history` is not yet created. AFAIK, this file is written when cmder is closed (and only has the commands available which were in the last closed cmder session.

**Comment by thecere** [comment]
Nope, .history is there. I've stumbled upon this by trying to append stuff to PATH with a custom alias. I've only used the history alias as an example, as it's already build-in.

**Comment by JanSchulz** [comment]
ok, I should have tested that first:

```
λ history
cat: %CMDER_ROOT%\config\.history: No such file or directory
```

Looks like https://github.com/mridgers/clink/issues/344?

**Comment by JanSchulz** [comment]
And duplicate of https://github.com/cmderdev/cmder/issues/684 -> should be fixed by a updated clink, which is included in one of the newer dev builds.

**Comment by JanSchulz** [comment]
Verified by installing the latest dev versions via appveyor: https://ci.appveyor.com/project/MartiUK/cmder/build/1.0.138-development/artifacts

**Comment by thecere** [comment]
Jep, thnx. Works for me now.
