### ISSUE TITLE
how to change the cmd line Icon ? 

### ISSUE THREAD

**Issue by woshichuanqilz** [cmderdev/cmder#796]
![2](https://cloud.githubusercontent.com/assets/11295355/12229507/76ec088a-b883-11e5-9bd4-1ac81b1eb096.png)
I want to change it to the `$` or `>`

**Comment by MartiUK** [comment]
Here: https://github.com/cmderdev/cmder/blob/development/vendor/cmder.lua#L2

**Comment by JanSchulz** [comment]
If you run the development branch, simple add a `whatever.lua` in `config/` with the following content:

´´´
function prompt_filter()
    clink.prompt.value = string.gsub(clink.prompt.value, "{lamb}", ">")
end

clink.prompt.register_filter(prompt_filter, 10)
```

**Comment by woshichuanqilz** [comment]
It worked, tnx a lot for your help~
