### ISSUE TITLE
Cmder doesn't properly utilize Windows Snap Assist

### ISSUE THREAD

**Issue by RDugan23** [cmderdev/cmder#799]
In Windows 10 you can snap other programs to different monitors (Win + Shift + arrow keys) or quadrants or even halves split vertically (Win + arrow keys). Cmder can move to other monitors using the firs method (as long as the Cmder window isn't maximized) but using the second method to snap Cmder to the desired corner or vertical half doesn't produce any results.

**Comment by kleinfreund** [comment]
I cannot confirm that *nothing* happens at all when pressing <kbd>Win</kbd>+<kbd>←</kbd>, etc. Rather, the behavior is broken.

For example when I open cmd.exe/PowerShell and let's say the console window is opened in the left half of the screen. Pressing <kbd>Win</kbd>+<kbd>→</kbd> will move the window to the right half.

When I do the same thing with the Cmder window, this does not happen. Rather the behavior is inversed. Pressing <kbd>Win</kbd>+<kbd>←</kbd> will move the window to the right half of the screen and vice-versa.

**Comment by RDugan23** [comment]
@Stanzilla: Pardon my ignorance, given that this is a ConEmu issue, does that mean that we will have to wait for ConEmu to solve this problem and then update our version of Cmder in order to get the fix? If so, is there anything I can or should do to help facilitate this? Thank you for all your effort and hard work. I thoroughly enjoy using Cmder everyday for development purposes.

**Comment by Stanzilla** [comment]
Yup, exactly, might also help filing a bug over there, too :)

**Comment by tomasorti** [comment]
> I cannot confirm that _nothing_ happens at all when pressing Win+←, etc. Rather, the behavior is broken.
> 
> For example when I open cmd.exe/PowerShell and let's say the console window is opened in the left half of the screen. Pressing Win+→ will move the window to the right half.
> 
> When I do the same thing with the Cmder window, this does not happen. Rather the behavior is inversed. Pressing Win+← will move the window to the right half of the screen and vice-versa.

Still happening this on **`Cmder Version 1.3.11.843`**, January 2019.
The behavior is broken...

**Comment by Stanzilla** [comment]
Still not a Cmder issue.

**Comment by tomasorti** [comment]
ConEmu, right?
Hope ConEmu will not blame Windows 10...

I am chasing this on ConEmu Issues like this one, which is closed:
[https://github.com/Maximus5/ConEmu/issues/284
](url)

**Comment by Stanzilla** [comment]
Yup

**Comment by tomasorti** [comment]
Ok, I have downloaded [ConEmu versions](https://github.com/Maximus5/ConEmu/releases):

- [190108](https://github.com/Maximus5/ConEmu/releases/tag/v19.01.08) (latest)
- [180626](https://github.com/Maximus5/ConEmu/releases/tag/v18.06.26) (the one shipped with Cmder Version 1.3.11.843)

and I can confirm this problem does **NOT** appear in ConEmu.
Snap with `Win+LeftArrow` & `Win+RighArrow` works fine in ConEmu.

But it does not in Cmder. So it must be **a issue of Cmder**.
