### ISSUE TITLE
Does not work with Julia

### ISSUE THREAD

**Issue by JobLeonard** [cmderdev/cmder#80]
Running julia.bat starts up the Julia shell, prints out the opening logo, then immediately quits.

```
c:\Julia\julia-05c6461b55                                                                   
λ julia.bat                                                                                 
               _                                                                            
   _       _ _(_)_     |  A fresh approach to technical computing                           
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org                          
   _ _   _| |_  __ _   |  Type "help()" to list help topics                                 
  | | | | | | |/ _` |  |                                                                    
  | | |_| | | | (_| |  |  Version 0.2.0 (2013-11-16 23:44 UTC)                              
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org release                             
|__/                   |  x86_64-w64-mingw32                                                


c:\Julia\julia-05c6461b55                                                                   
λ help()                                                                                    
This command is not supported by the help utility.  Try "() /?".
```

http://julialang.org/downloads/

**Comment by yanyu2015** [comment]
How can I config julia to cmder step by step?

**Comment by yanyu2015** [comment]
> Running julia.bat starts up the Julia shell, prints out the opening logo, then immediately quits.
> 
> ```
> c:\Julia\julia-05c6461b55                                                                   
> λ julia.bat                                                                                 
>                _                                                                            
>    _       _ _(_)_     |  A fresh approach to technical computing                           
>   (_)     | (_) (_)    |  Documentation: http://docs.julialang.org                          
>    _ _   _| |_  __ _   |  Type "help()" to list help topics                                 
>   | | | | | | |/ _` |  |                                                                    
>   | | |_| | | | (_| |  |  Version 0.2.0 (2013-11-16 23:44 UTC)                              
>  _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org release                             
> |__/                   |  x86_64-w64-mingw32                                                
> 
> 
> c:\Julia\julia-05c6461b55                                                                   
> λ help()                                                                                    
> This command is not supported by the help utility.  Try "() /?".
> ```
> 
> http://julialang.org/downloads/

How can I config julia to cmder step by step?

**Comment by daxgames** [comment]
Seems to work for me.

![image](https://user-images.githubusercontent.com/7318053/190877297-283740da-36fd-4121-aa0c-5a06b6815b79.png)

**Comment by chrisant996** [comment]
@daxgames you ran `julia.exe`.

The OP ran `julia.bat`.

Maybe there's a problem in julia.bat, or maybe it's the wrong thing to run?

**Comment by daxgames** [comment]
There is no `julia.bat` in the entire portable archive I downloaded.

![image](https://user-images.githubusercontent.com/7318053/190881522-306822ad-b9bf-4fe4-b8be-eead061a59b2.png)

![image](https://user-images.githubusercontent.com/7318053/190881556-550fecbe-a888-4375-9794-7bb59c84e225.png)

**Comment by chrisant996** [comment]
> How can I config julia to cmder step by step?

@yanyu2015  It seems there shouldn't really be any configuration needed for running Julia inside Cmder.  If you have encountered a problem, can you share what the problem is?

**Comment by yanyu2015** [comment]
@chrisant996 Sorry it can work well now.
At first, I don't have a  configuration of `path`, then I do it and restart cmder again and again, but it cannot work. Just a moment ago, it works. So it may be need to restart the computer system.
