### ISSUE TITLE
stray double quote using /Start

### ISSUE THREAD

**Issue by RTrescott** [cmderdev/cmder#801]
FSHARPINSTALLDIR=C:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0\
HOMEDRIVE=C:

C:>cmder /start "%fsharpinstalldir%"

... (cmder opens)
Set-Location : Illegal characters in path.  
At C:\Program Files (x86)\cmder\vendor\profile.ps1:60 char:5                                                  
-     Set-Location -Path $Env:CMDER_START  
-     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
  - CategoryInfo          : InvalidArgument: (C:\Program File...Framework\v4.0":String) [Set-Location], Arg 
    umentException  
  - FullyQualifiedErrorId : ItemExistsArgumentError,Microsoft.PowerShell.Commands.SetLocationCommand  

Set-Location : Cannot find path 'C:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0"' because it  
does not exist.  
At C:\Program Files (x86)\cmder\vendor\profile.ps1:60 char:5                                                  
-     Set-Location -Path $Env:CMDER_START  
-     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
  - CategoryInfo          : ObjectNotFound: (C:\Program File...Framework\v4.0":String) [Set-Location], Item 
    NotFoundException  
  - FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand  

C:\
λ "$Env:CMDER_START"  
C:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0"                                                  

... (note stray double quote at end.  Thanks!)

**Comment by daxgames** [comment]
works with current version, closing
