### ISSUE TITLE
how to set the start path of the cmder

### ISSUE THREAD

**Issue by woshichuanqilz** [cmderdev/cmder#802]
for example I want to start with the path "D:\"

I tried `cmder.exe /start "D:\"`
but it doesn't work.

**Comment by JanSchulz** [comment]
This should work in the latest dev version: #798

To get a recent verison of cmder, go to https://github.com/cmderdev/cmder/pull/771 and then click on the "details" link in the CI services box at the bottom of the page. From there, go to the "Artefacts" tab, where you find downloads of the latest version of cmder... 

Please report if that fixed your problem...

**Comment by woshichuanqilz** [comment]
tnx a lot  it worked !

**Comment by woshichuanqilz** [comment]
~~  it fine now, 
I don't know why. 
Tnx a lot . :+1:
