### ISSUE TITLE
how to start the cmder with a command 

### ISSUE THREAD

**Issue by woshichuanqilz** [cmderdev/cmder#805]
for example : 
`cmder /runcmd echo 'Hello World'` like this.

**Comment by Jackbennett** [comment]
If you want it to run every time it goes in your startup user-profile cmd/ps1 for the console host you're choosing. 

cmder.exe pretty much just lets you start at a target folder. 

@MartiUK  I swear I've seen an issue about updating the launcher to pass commands into cmder, I must be miss-remembering.

**Comment by thshdw** [comment]
This is mentioned here too https://github.com/cmderdev/cmder/issues/457

**Comment by Jackbennett** [comment]
Further discussion (if any) on 370 I think is appropriate. Consider 457 a good workaround.
