### ISSUE TITLE
Cmder - Warning: Missing git support 

### ISSUE THREAD

**Issue by AhmadAbdel-Halim** [cmderdev/cmder#806]
Whenever I use PowerShell with Cmder on windows 10 I get this error:
"WARNING: Missing git support, install posh-git with 'Install-Module posh-git' and restart cmder
So what's the problem here?

**Comment by MartiUK** [comment]
Have you tried running what it says to run?

**Comment by JamesSkemp** [comment]
For anyone coming to this later, don't lose hope. See issue #1345. Basically, try running `Update-Module posh-git` and then restart Cmder.

This issue was high in Google's results, but the linked issue was not.

**Comment by chrisxaustin** [comment]
It's an obnoxious message if I don't feel like installing that module.
It definitely doesn't need to be displayed on every line.

**Comment by daxgames** [comment]
@chrisxaustin This module is an integral part of Cmder Powershell sessions, if you don't like or want ot the don't run a Cmder Powershell session.

Just create a new Powershell task that does not use Cmder's `profile.ps1` to configure the session.

**Comment by benmed00** [comment]
The problem is still persistent for me

**Comment by daxgames** [comment]
@benmed00 - What problem?  This issue is closed and has been explained above.

**Comment by Gildedter** [comment]
> For anyone coming to this later, don't lose hope. See issue #1345. Basically, try running `Update-Module posh-git` and then restart Cmder.
> 
> This issue was high in Google's results, but the linked issue was not.

I did this, but now I get this error:
```
Update-Module: Module 'posh-git' was not updated because no valid module was found in the module directory. Verify that the module is located in the folder specified by $env:PSModulePath.
```

I installed via `scoop install cmder-full`, but I only get the warning message inside VsCode terminal instance of cmder ([this](https://github.com/cmderdev/cmder/wiki/Seamless-VS-Code-Integration#use-powershell-instead-of-cmdexe)), applying the same config for Windows Terminal doesn't give me the same warning. Is `posh-git` really needed, or can I just do away with it? I'm on version 1.3.19.

Windows Terminal config:
```
{
    "altGrAliasing": true,
    "antialiasingMode": "grayscale",
    "closeOnExit": "graceful",
    "colorScheme": "Monokai Cmder",
    "commandline": "pwsh.exe -ExecutionPolicy Bypass -NoLogo -NoProfile -NoExit -Command . '%cmder_root%/vendor/conemu-maximus5//..//profile.ps1'",
    "cursorShape": "bar",
    "font": 
    {
        "size": 12
    },
    "guid": "{d5f425c9-ae54-4345-87ed-c5f707f814a2}",
    "hidden": false,
    "historySize": 9001,
    "icon": "%cmder_root%/icons/cmder.ico",
    "name": "Cmder (pwsh)",
    "opacity": 100,
    "padding": "8, 8, 8, 8",
    "snapOnInput": true,
    "startingDirectory": "%USERPROFILE%",
    "useAcrylic": true
}
```
