### ISSUE TITLE
[Enhancement] Powershell and Babun (cygwin + zsh)

### ISSUE THREAD

**Issue by alazare619** [cmderdev/cmder#807]
Any chance to add powershell enviorment and Cygwin + zsh aka babun out of hte box see..http://babun.github.io/ for a idea of the babun enviorment

**Comment by DanielGGordon** [comment]
I personally have Babun configured as one of my tasks, and it works fairly well. However I might advise against bundling it with Cmder. Babun is still fairly large (> 200MB last time I checked).

**Comment by Stanzilla** [comment]
Babun comes with waaay too much stuff that we already use and include

**Comment by alazare619** [comment]
stanzilla and DanielGGordon I completely agree my idea is more just Cygwin / ZSH we dont need all of the extra dodads but just a basic cygwin enviorment and zsh for making it pretty a basic cygwin and zsh install is about 20 megs.

**Comment by Stanzilla** [comment]
Well we recently added bash/mintty, does that help?

**Comment by daxgames** [comment]
The recently added bash/mintty is based on msys2 not cygwin.  It is better 
that the old stuff but it's not not Babun/cygwin IMHO. :-)

Babun/Cygwin is much not more functional and very possibly overkill for the 
average cmder user.   It is so easy to add both if these to cmder if the 
user is a power user and a fringe use case so I see no reason to add it out 
or the box, also just my opinion.

I have a pull request out there, 
https://github.com/cmderdev/cmder/pull/740, that is just a simple script 
you can add to your externally installed *nix setup to incorporate cmders 
portable profile configs into it.  It is currently marked do not merge, not 
sure why.

Note in addition to adding this to your external external *nix 
/etc/profile.d you need to add a Cmder Task to actually launch the external 
session

**Comment by MartiUK** [comment]
Babun is too large to be included unfortunately, cmder is already over 100MB with just git-for-windows.

There is a wiki topic on adding cygwin, I assume it's fairly similar to add Babun.
