### ISSUE TITLE
how to use /? to get the help doc in the `cmder`

### ISSUE THREAD

**Issue by woshichuanqilz** [cmderdev/cmder#808]
it seems doesn't work in cmder. 

![01~20_16-30-12.png](http://7xpvdr.com1.z0.glb.clouddn.com/01~20_16-30-12.png)

**Comment by JanSchulz** [comment]
Try `find --help`. Find is coming from the git package and therefore as the unix style arguments, where `--help` is the one to ask for help and not `/?` which is used for windows commandline tools.

**Comment by woshichuanqilz** [comment]
tnx a lot :+1:
