### ISSUE TITLE
No longer shows git current branch

### ISSUE THREAD

**Issue by jmiazga** [cmderdev/cmder#809]
Cmder v1.2.9 no longer shows the current branch in git. Instead it shows the name and version from package.json.

![image](https://cloud.githubusercontent.com/assets/181441/12459594/9bf65350-bf7d-11e5-843a-1fd70c944c3e.png)

**Comment by MartiUK** [comment]
Calling @vladimir-kotikov

**Comment by vladimir-kotikov** [comment]
@jmiazga, does this happen only in this particular directory, or in every git repo?

Could you please paste the output of `git rev-parse --git-dir --is-inside-git-dir --is-bare-repository --is-inside-work-tree` (@MartiUK, this is still a nice way to debug :smile: )

**Comment by jmiazga** [comment]
It happens in every git repo. If there is no package.json nothing is displayed. I downloaded v1.2 and everything works as expected.

Output:
.git
false
false
true

**Comment by vladimir-kotikov** [comment]
Hm, that's strange. Just checked and the content of `config/cmder.lua` from 1.2.9 is strictly equal to the one from 1.2.0. So it seems the only reason is the different git versions.

**Comment by keathmilligan** [comment]
This seems to be a Windows environment issue. The redirect in the io.popen statement in the get_git_branch function in cmd.lua is causing the lines() function to return nothing in some cases.

One computer (that doesn't have the issue):

```
Lua 5.3.2  Copyright (C) 1994-2015 Lua.org, PUC-Rio
> for line in io.popen("git branch 2>nul"):lines() do print(line) end
* master
>
```

Another computer running the same LUA and git:

```
Lua 5.3.2  Copyright (C) 1994-2015 Lua.org, PUC-Rio
> for line in io.popen("git branch 2>nul"):lines() do print(line) end
>
```

You can remove the "2>nul" as work-around for now.
