### ISSUE TITLE
Netcat is missing

### ISSUE THREAD

**Issue by SunboX** [cmderdev/cmder#810]
I'm trying to tunnel SSH over Tor with Netcat, like explained here: https://en.wikibooks.org/wiki/OpenSSH/Cookbook/Proxies_and_Jump_Hosts#Tunneling_SSH_Over_Tor_with_Netcat

but I'm getting this exception message:
```bash
λ ssh -o ProxyCommand='nc --proxy-type socks5 --proxy localhost:9050 %h %p' pi@hfsaufz747hriw7674h.onion
/bin/sh: line 0: exec: nc: not found
ssh_exchange_identification: Connection closed by remote host
```

How can I fix this?

PS: Using Putty, it works so far.

**Comment by MartiUK** [comment]
Are you using cygwin or bash included with cmder?

**Comment by SunboX** [comment]
That's a good question. I didn't change it, how can I see what I'm using?

**Comment by JanSchulz** [comment]
I think the problem is that nc isn't available in git for windows (at least on my system, there is no nc.exe)

**Comment by MartiUK** [comment]
Ah okay, you're probably using the default cmd task.
Yes, netcat isn't included with git for windows.

I'd look at integrating cygwin https://github.com/cmderdev/cmder/wiki/%5BWindows%5D-Integrating-Cygwin and installing/using netcat. Plus it's closer to a posix environment.
