### ISSUE TITLE
When will the next version be available?

### ISSUE THREAD

**Issue by aayushkapoor206** [cmderdev/cmder#811]
When can we expect version 1.3? :smile:

**Comment by MartiUK** [comment]
I've set the milestone to be 31st Jan, so expect it on or around that time.

**Comment by Droyk** [comment]
[**@MartiUK**](https://github.com/MartiUK) commented on [Jan 21, 2016, 4:45 PM GMT+5:30](https://github.com/cmderdev/cmder/issues/811#issuecomment-173540942 "2016-01-21T11:15:49Z - Replied by Github Comment Enhancer"):
> I've set the milestone to be 31st Jan, so expect it on or around that time.

+1 thanxxx for the confirmation but can i expect some big speed booost
