### ISSUE TITLE
integrating Git for Windows vs. Git for Windows SDK?

### ISSUE THREAD

**Issue by mark-casey** [cmderdev/cmder#813]
So I'm just getting to mixed/alternate/better shells on Windows after being a long time PuTTY user since moving to Linux work; try and go easy on me :D

In any case, would it be fair to say that previously cmder integrated the build environment for Git for Windows 1.x (msysgit), but now integrates (or is moving to integrate) Git for Windows 2.x itself as opposed its build environment (i.e.: the Git for Windows SDK)?

If that is true, I was wondering if moving from integrating the build environment to integrating the thing being built itself has had any downsides?

I'm mainly interested because of the MinGW and MSys2 package builders that are somewhat integrated in the Git for Windows SDK (https://github.com/git-for-windows/build-extra#mingw-packages). Could I just unpack a bunch of cygwin's binaries into cmder's ./bin PATH addon if I don't want to have to integrate cygwin as a fully separate shell in cmder?

**Comment by Stanzilla** [comment]
We are integrating the finished product, not the build environment

**Comment by daxgames** [comment]
And always have, I believe.  

 

What is currently being bundled in the development branch is Git for Windows 2.x based on Msys2 versus what is currently bundled in released versions which is Git for Windows 1.9x based on Msys.

**Comment by mark-casey** [comment]
I guess the core of my question was that the change to 'vendor/sources.json' here (https://github.com/cmderdev/cmder/commit/3e06fcbf074721235c2d9fb2a99ca48a73b6c873) starting the move to git-for-windows changes the source url from 'https://github.com/msysgit/msysgit/releases/download/..' to 'https://github.com/git-for-windows/git/releases/download/..'

The repo for the new url is certainly the finished product, but the README of the repo used previously says it is not the finished product (and seems to have said that since at least 2012):

>**The relationship between msysGit and Git for Windows**
>-------------------------
>Git for Windows is the software package that installs a minimal environment to run Git on Windows. It comes with a Bash (a Unix-type shell), with a Perl interpreter and with the Git executable and its dependencies.
>
>On the other hand, msysGit is the software package installing the *build environment* that can build Git for Windows.

I had always thought msysgit and Git for WIndows were just two different ways to acquire git on Windows. This may just be a case of intended use cases in documentation vs. actual traditional use cases, but it made me wonder if there was an intentional shift to the "finished product" (git-for-windows) when the transition was started within cmder. And if not I wanted to point it out in case there were tools that used to be in msysgit intended for its "build environment" that are now only in the SDK (which, I believe the SDK only came into being recently).

**Comment by Stanzilla** [comment]
The whole thing has always been a mess but it is a bit better now with the new naming

**Comment by mark-casey** [comment]
Okay, so the confusion is normal I guess (and I agree, I find the new naming pretty straightforward). Thanks/closing
