### ISSUE TITLE
Cmder does not open in last open window position

### ISSUE THREAD

**Issue by wheelerlaw** [cmderdev/cmder#816]
I'm not sure if this is a bug with cmder, ConEmu, or windows, but basically cmder does not open in the position in which it was closed. In other words, it keeps opening half off the screen which is especially frustrating because I need to move it on screen every single time.

**Comment by MartiUK** [comment]
Settings > Main > Size & Pos > Check "Auto save window size and position on exit"

This should be set by default in the next version.

**Comment by MartiUK** [comment]
Settings > Main > Size & Pos > Check "Auto save window size and position on exit"

This should be set by default in the next version.
