### ISSUE TITLE
Launching 32bit version of ConEmu on Windows x64

### ISSUE THREAD

**Issue by MinchinWeb** [cmderdev/cmder#818]
Running Cmder 1.2.9 on Windows 10x64. When I go to setting of ConEmu, it tells me it's running the 32bit version. Should this not be the 64 bit version of ConEmu?

**Comment by Stanzilla** [comment]
https://github.com/cmderdev/cmder/pull/350

**Comment by vBm** [comment]
Fixed in 6a474dd6241f78e8df0d0af2b9df18a1ed048281
