### ISSUE TITLE
Git lau script fails with Git-Worktree

### ISSUE THREAD

**Issue by MinchinWeb** [cmderdev/cmder#819]
[Git Worktree](https://git-scm.com/docs/git-worktree) is a (wonderful! and) fairly new feature of Git that effectively lets you check out multiple branches of the same Git repo into separate directories. This is particularly handy if your `.git` folder grows large in size.

However, the lau script expects a `.git` folder, which doesn't exist in the root folders of the worktree checkouts. There is, however, a `.git` file. If the lau script looked for for this `.git` file as well (see [line 34-35](https://github.com/cmderdev/cmder/blob/master/config/cmder.lua#L34,L35)]?), the rest should still work.

**Comment by MinchinWeb** [comment]
I can confirm this is also an issue with the Git Powershell script, but I imagine that is probably a separate fix.

**Comment by fcharron** [comment]
+1

**Comment by fcharron** [comment]
https://github.com/vladimir-kotikov/clink-completions/issues/94

**Comment by fcharron** [comment]
linked to vladimir-kotikov/clink-completions#94

**Comment by fcharron** [comment]
This has just been fixed in vladimir-kotikov/clink-completions#95 (in master). It just needs to be integrated in cmder.
