### ISSUE TITLE
How to get this type of prompt?

### ISSUE THREAD

**Issue by devkhan** [cmderdev/cmder#822]
Please forgive me if this isn't the right place to ask this, but I don't if this is a feature of ConEmu, cmder or something else.

I can't find a setting or config to get this type of console prompt (the colored strip on the directory and branch). I've seen it in some places, but how do you get it?

![image](https://cloud.githubusercontent.com/assets/8049092/12719669/93ec418a-c91c-11e5-8e56-a47fb6ebb67c.png)

**Comment by DanielGGordon** [comment]
That's interesting, because I've never seen this with Powershell. 

Here is how it could work if you used something like Babun or Cygwin:

https://github.com/bhilburn/powerlevel9k

I have no idea how this could work with Powershell. I've only gotten something like this to work when running Babun (or on a non-Windows machine).

I would suggest asking questions like these on the gitter channel. https://gitter.im/cmderdev/cmder

**Comment by devkhan** [comment]
Actually, I got something similar ( background  and text span colors ) working but the character weren't properly shown. I guess that is because of some encoding problem. I tried the script found here:

https://github.com/chrisbenti/PS-Config/blob/master/Microsoft.PowerShell_profile.ps1

**Comment by DanielGGordon** [comment]
Would the Powerline patched fonts work? I use Deja Vu Sans Mono for Powerline to get some of those symbols (the important one is probably the filled triangle) working on Babun (but that uses the Mintty terminal).

**Comment by devkhan** [comment]
I don't know about that, but I took them from here: https://gist.github.com/qrush/1595572.

I'm closing this issue as this doesn't seem to be the right place for this discussion.

**Comment by datatypevoid** [comment]
I know  this has already been closed, but what the OP asked is possible with [Babun](https://babun.github.io). It utilizes `zsh`/`oh-my-zsh` and you can use custom themes such as [PowerLevel9k](https://github.com/bhilburn/powerlevel9k) which has colors similar to those requested.

**Comment by dcastro** [comment]
Try https://github.com/AmrEldib/cmder-powerline-prompt

Worked for me, very easy to install
