### ISSUE TITLE
Cannot save settings

### ISSUE THREAD

**Issue by strig** [cmderdev/cmder#828]
When trying to change the default startup shell to Powershell As Admin the "Save Settings" button is greyed out. Changing the default shell to something else does not activate it and it does not save automatically.

**Comment by MartiUK** [comment]
What version are you running?

**Comment by strig** [comment]
Most recent version - just updated it with the auto updater.

I was able to find a workaround by exporting a new settings file and
replacing the existing one with it. The save functionality is still not
working, however.

**Comment by Namfoodle** [comment]
I have the same problem.

**Comment by fatso83** [comment]
I am having the same problem. Installed using Chocolatey, so that might be a big part of it. After running
`choco install cmder` (or `cmder.portable`) and opening `cmder` from the Windows search menu I get an instance that in the settings section has its settings greyed out. The file name is `C:\tools\cmder\config\ConEmu.xml`. This is only writable by the admin, so if opening `cmder` with the admin user one can change the settings.

I am sorry if issue report belongs somewhere else, but the choco package had a [issue tracker pointing here](https://chocolatey.org/packages/cmder.portable/1.1.4.101).

**Comment by MartiUK** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

I don't support the chocolatey package, I can only recommend you download a build from github and extract it to a location that your user can write to (Desktop for example).

On 25 February 2016 19:11:41 GMT+00:00, Carl-Erik Kopseng <notifications@github.com> wrote:
>I am having the same problem. Installed using Chocolatey, so that might
>be a big part of it. After running
>`choco install cmder` (or `cmder.portable`) and opening `cmder` from
>the Windows search menu I get an instance that in the settings section
>has its settings greyed out. The file name is
>`C:\tools\cmder\config\ConEmu.xml`. This is only writable by the admin,
>so if opening `cmder` with the admin user one can change the settings.
>
>I am sorry if issue report belongs somewhere else, but the choco
>package had a [issue tracker pointing
>here](https://chocolatey.org/packages/cmder.portable/1.1.4.101).
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/cmderdev/cmder/issues/828#issuecomment-188935425

- --
Sent from my Android device with K-9 Mail. Please excuse my brevity.
-----BEGIN PGP SIGNATURE-----

iQE+BAEBCgAoIRxNYXJ0aW4gS2VtcCA8bWFydGluQG1hcnRpbmtlLm1wPgUCVs9U
eAAKCRBxKFXOM3nEdc+DCAC1UIOnznmDlLRq0UoA2AVJvLyPpZ18HwjGOt7iDBq8
ZzStLzTUxkolGdGPM9yT2EU8gJMN9/1Jb7MwfidhV5TpbsVCPAb/uArzV9jKA2wi
ze1gHf3bsU9WDrDcnjuzUBI7DxyJT/tNQtYtCe1LNtLoJGneFSaI3+n7XE5PJO2j
W6Ct2JMoJhEF1QAG6OA3JYGJ+Bp6MBwJpIRuKbYFyFCkBOn1wH9ggCn3IR62MhxQ
zBw9HNrqvx6myXlYSCfGI44fqbdEOJ3/WoPCAmbp8JNsHg39ev9KxWur2dSijKbF
SuD6mNXyYhCxM1kYp5sSqMpmWGpQ2K4cJIB2RbJcekRK
=O3yi
-----END PGP SIGNATURE-----

**Comment by fatso83** [comment]
OK, thanks for the reply and sorry about the noise. Will contact the package maintainers using their [Disqus forum](https://chocolatey.org/packages/cmder.portable/).

**Comment by bonsak** [comment]
I have the same problem.

**Comment by vdecree** [comment]
I too am having the same issues

**Comment by sittingpilgrim** [comment]
Try running cmder as administrator

**Comment by ilbonte** [comment]
Had the same problem. To fix this I opened cmder as admin, edited my settings and saved.
