### ISSUE TITLE
Git branch information is broken for submodules

### ISSUE THREAD

**Issue by gpakosz** [cmderdev/cmder#833]
When using Cmder with a `cmd.exe` session, Git branch information for submodules is broken.

This is directly related to `clink-completions`'s `get_git_dir()` not handling submodules correctly.

I believe once vladimir-kotikov/clink-completions/issues/46 is closed, `git_prompt_filter()` which uses `get_git_dir()` will report the proper branch information.

**Comment by gpakosz** [comment]
I thought the commit message would automatically close this issue.

**Comment by vladimir-kotikov** [comment]
It would when commit will appear in master branch. It has been merged into development yet.

**Comment by gpakosz** [comment]
I see. Thanks
