### ISSUE TITLE
switch to use master a the default development branch

### ISSUE THREAD

**Issue by JanSchulz** [cmderdev/cmder#836]
IMO this has two big pros:

* master it the default checkout and PRs are automatically opened against master and therefore most new contributors won't have to redo the change against development (rebase, do a new PR). In short: it's what almost every other github project uses...
* we could add a batch to the homepage to link to appveyor which shows the master branch and users can download pre releases without telling them to go to appveyor, check the build name, go to artefacts,...

**Comment by vladimir-kotikov** [comment]
:+1: And another one - we won't need anymore for these massive pre-release merges `dev -> master` :smile:

**Comment by MartiUK** [comment]
I'll look into it after the release.
