### ISSUE TITLE
Open with 4 console tabs..?

### ISSUE THREAD

**Issue by DealerOnClass** [cmderdev/cmder#839]
I was curious if there is a way to do this as it would be very helpful in my workflow. I know that once "cmder" is open, using "ctrl+t" I can open new tabs and do 50% top bottom etc, and ultimately I always setup a 4 console view. Is there a way to ensure it launches with that configuration? Your help greatly appreciated, thank you!

**Comment by MartiUK** [comment]
Set up your tabs as you want, then Settings > Tasks > `+` > Active Tabs

Rename the task to how you want, then Startup > Specified named task > `$your_task`
