### ISSUE TITLE
Cannot compatible with Ansicon

### ISSUE THREAD

**Issue by marslo** [cmderdev/cmder#84]
I'm using [Ansicon](http://adoxa.hostmyway.net/ansicon/) to make pretty prompt in my cmd:
![ansicon](https://f.cloud.github.com/assets/5822057/1724381/c6310462-626e-11e3-94cf-b751102d7423.png)

However, cmder doesn't compatible with it. Error shows: `the system cannot find the file: <ansicon.exe_path>. But this file does exists in that path:
![ansicon1](https://f.cloud.github.com/assets/5822057/1724479/4848d3de-6270-11e3-9894-56785052c84b.png)

Can you fix that?

**Comment by jjgh** [comment]
Got the same problem, is there a solution similar to what @xjlin0 suggests? Thanks.
