### ISSUE TITLE
Setting prompt in user startup file leaves blank line in terminal window

### ISSUE THREAD

**Issue by JonathanHolvey** [cmderdev/cmder#842]
I've noticed that when customising the prompt in `config\user-startup.cmd` the first prompt is presented after a blank line in the terminal window. This doesn't happen with a simple `echo "Hello world"` command.

I'm assuming this has something to do with the `call` from `vendor\init.bat`, since commands placed at the end of this file output on the first line as expected. I've experimented a little trying to work out what's going on, but I haven't found a solution as yet. It seems that you get the same behaviour using only `cmd.exe`, which can be replicated with the following:

Create two files `a.cmd` and `b.cmd`, containing `call b.cmd` and `prompt Test$S$G$S` respectively, then run `cmd /k a.cmd` from the location of the two files. You should see the prompt `Test >` printed on the _second_ line of the resulting window.

**Comment by JanSchulz** [comment]
I don't have a empty line:

```
Found ssh-agent at 1488
Found ssh-agent socket at /tmp/ssh-30Wurb96xHr8/agent.7040
C:\Users\jschulz
λ
```

But I do have such a line in the firts strup of a console:

```
Removing old ssh-agent sockets
Starting ssh-agent:  done
Enter passphrase for /c/Users/jschulz/.ssh/id_rsa:
Identity added: /c/Users/jschulz/.ssh/id_rsa (/c/Users/jschulz/.ssh/id_rsa)

C:\Users\jschulz
λ
```

-> In my case that looks related to the shs agent :-/

**Comment by JonathanHolvey** [comment]
The empty line I'm getting is immediately above the prompt when Cmder starts, like this: 
![screenshot_2016-03-12-09-45-54](https://cloud.githubusercontent.com/assets/10114731/13718620/711bc83a-e837-11e5-8853-7e06212baacf.png)

**Comment by luantu** [comment]
Also puzzled by the question
