### ISSUE TITLE
love love cmder, but dont like the icons... how can I change them?

### ISSUE THREAD

**Issue by born2net** [cmderdev/cmder#843]
love love cmder, but dont like the icons... can I change them?

if so how?

![capture](https://cloud.githubusercontent.com/assets/5090936/13101233/7d4bb5bc-d4f9-11e5-8c9e-b3034603be0d.PNG)

tx
Sean

**Comment by wqshen** [comment]
I also have this question. When i hide the title bar, the close button appeared on the new tab bar is very weird. Hope improve it.

**Comment by MartiUK** [comment]
Yeah, you can download the conemu source code, replace the icon files with the ones you want and compile it.
Looks like this file: https://github.com/Maximus5/ConEmu/blob/master/src/ConEmu/toolbar1.bmp

**Comment by edgr-sanchez** [comment]
The icons should definitely be improved. I'm sure they could find a pack of icons that is free to open source devs.

**Comment by born2net** [comment]
right now the icon DPI does not scale in high res screens

**Comment by karocksjoelee** [comment]
still looking forward to the UI improvement XD

**Comment by Oxicode** [comment]
+1

**Comment by catamphetamine** [comment]
So I guess this is the issue for `ConEmu` repo instead?
I could submit an icon or two if I knew who's willing to accept those icons.

**Comment by daxgames** [comment]
Specifically what icons? Cmder is a suite that uses conemu as a component but the main cmder icons are not pert of conemu.

**Comment by catamphetamine** [comment]
@daxgames I guess the ones that are showng in the original post.
Ok then, I'll contact ConEmu author.
