### ISSUE TITLE
Alias with multi-word git commit message not working

### ISSUE THREAD

**Issue by sinrise** [cmderdev/cmder#847]
As per the example in [this](https://github.com/cmderdev/cmder/issues/376) closed issue, I created an alias: 'gcam=git commit -m $*' but it does not work. It returns the following error:

λ gcam test commit message using cmder alias
error: pathspec 'commit' did not match any file(s) known to git.
error: pathspec 'message' did not match any file(s) known to git.
error: pathspec 'using' did not match any file(s) known to git.
error: pathspec 'cmder' did not match any file(s) known to git.
error: pathspec 'alias' did not match any file(s) known to git.

**Comment by sinrise** [comment]
Ok It does work if you add quotes around the message:
gcam "test commit message using cmder alias"
I'm not sure if you want to count this as even an issue if there is away around having to do quotes. It's not much of a shortcut otherwise but it technically works.

**Comment by daxgames** [comment]
Unaliased git even requires quotes so this is not an issue.
