### ISSUE TITLE
Cmder lists path on window resize.

### ISSUE THREAD

**Issue by elebumm** [cmderdev/cmder#851]
Hey guys, so I have been using cmder and it's working great but a minor bug is when i resize the window it will list the path again. Here is an example.

![1](https://cloud.githubusercontent.com/assets/6053155/13213684/9b1361b2-d918-11e5-9e55-e2d54abb4ae4.PNG)

After resizing multiple times...

![2](https://cloud.githubusercontent.com/assets/6053155/13213694/b3de27c2-d918-11e5-8b07-cb1e3d371ff2.PNG)

**Comment by Jameskmonger** [comment]
I am also experiencing this.

**Comment by Riant** [comment]
Yes, same issue I got.

**Comment by Riant** [comment]
I got same issue,

Any idea to fix that?

**Comment by akarel** [comment]
Check out issue #789 
You can get the portable clink here: [](https://mridgers.github.io/clink/)

**Comment by Jackbennett** [comment]
Oh the joys of clink. Needs updated as posted above.
