### ISSUE TITLE
path entry for <git>/cmd instead of <git>/bin? 

### ISSUE THREAD

**Issue by janschulz** [cmderdev/cmder#853]
The current git installer adds `C:\Program Files(x86)\Git\cmd` (and not `C:\Program Files(x86)\Git\bin`) to the path. IMO we should also change our path entry. `/cmd` would also make the `start-ssh-agent.cmd` script available in bash, which could then added (inactive...) to the default `config/user-profile.sh`.

On the other hand, `/bin` contains bash.exe, which might be good to have. So maybe add both?

Another thing I'm not a real an of is that `C:\Program Files\Git\usr\bin` is added at the start of the path, so things like windows `find` are shadowed by the git equivalent:

```cmd
λ where find
C:\Program Files\Git\usr\bin\find.exe
C:\Windows\System32\find.exe
c:\Rtools\bin\find.exe
```

I'm not sure if that was intentional (https://github.com/cmderdev/cmder/commit/fc85915b2c7b879daa371567467ef4921b22bbf6). 

So, IMO the path which is set if git is found should be:

```cmd
set "PATH=%GIT_INSTALL_ROOT%\cmd;%PATH%;%GIT_INSTALL_ROOT%\bin;%GIT_INSTALL_ROOT%\usr\bin;%GIT_INSTALL_ROOT%\usr\share\vim\vim74;"
```
[Or remove the `\usr\bin` entry and add that as an example to the generated `user-startup.cmd`]

And the same in the bash/ps startup scripts...

**Comment by JanSchulz** [comment]
Ok, I implemented that in https://github.com/cmderdev/cmder/pull/865

-> Unix commands are *always* added *to the end of the PATH*.

**Comment by Stanzilla** [comment]
Closed in favor of https://github.com/cmderdev/cmder/pull/865
