### ISSUE TITLE
Why not use @ECHO OFF?

### ISSUE THREAD

**Issue by daxgames** [cmderdev/cmder#868]
This is more of a question than an issue.

Why do we litter cmd and bat files with useless ```@``` signs to turn off command echo per line instead of just putting ```@echo off``` as the first line of the file?

**Comment by JanSchulz** [comment]
I tink mainly because using echo off would also set echo off in the following cmd session.

**Comment by daxgames** [comment]
I might try that and see.  Not sure that's true.

**Comment by daxgames** [comment]
Tested, verified safe, and implemented in #873.

**Comment by daxgames** [comment]
Fixed in #873

**Comment by glucas** [comment]
I like this pattern for bat files etc:

    @echo off
    @if not "%ECHO%"=="" echo %ECHO%

By default echo is off, but it makes debugging easy as you can temporarily 'set ECHO=on' in your shell.
