### ISSUE TITLE
Cmder Windows Pinning Issue [weird]

### ISSUE THREAD

**Issue by zQueal** [cmderdev/cmder#869]
Whenever I go to pin `Cmder` on the Windows taskbar it actually pins `Console Emulator` instead.

When I launch from the icon normally, it looks like this;

![y8jh9uz](https://cloud.githubusercontent.com/assets/239193/13482940/3f3bfbb2-e0be-11e5-86c5-0f2bc74af91f.png)

Which is expected and desirable. When launched from the now pinned icon it looks like this;

![r1hq2v5](https://cloud.githubusercontent.com/assets/239193/13482948/4bb7970c-e0be-11e5-8bd1-81c3a4470046.png)

which is very undesirable.

## Reproduce

1. Launch Cmder
2. Pin Cmder
3. Close Cmder
4. Launch from Pin
5. Suffer total agony and defeat

**Comment by MartiUK** [comment]
Try creating a shortcut to the cmder.exe and pinning that.

**Comment by zQueal** [comment]
Creating a shortcut failed on all fronts. Weirdly enough, when I pinned the application itself and restarted `explorer.exe` the path magically fixed itself and was operating like normal again.

Weird!

**Comment by philbritton** [comment]
Yea, I've had this issue for a while - I'd always pinned it from an already open instance.  I can confirm that pinning it from explorer by right clicking the .exe and selecting pin to taskbar is the solution.  Thanks for the fix.
