### ISSUE TITLE
Invalid macro definition at startup

### ISSUE THREAD

**Issue by tjnapster555** [cmderdev/cmder#875]
everytime i start cmder i get this error 
i am using the cmder with git v 1.2.9

also which theme is this ![theme name](https://camo.githubusercontent.com/812b2647d6cd216ecddfb3f0ec71639473717955/687474703a2f2f692e696d6775722e636f6d2f67316e4e6630492e706e67)

**Comment by Jackbennett** [comment]
theme, colours? Should be monokai.

Try 1.3.0-pre for s if you still have the macro error.

**Comment by jfpcarreira** [comment]
I also have this problem and I'm on git version 2.12.2.windows.2 and ConEmu 161022

**Comment by WyAtu** [comment]
I have the same problem. My cmder version is 1.3.4, and I set some aliases in the file named user-aliases.cmd

**Comment by mihaiconstantin** [comment]
> I have the same problem. My cmder version is 1.3.4, and I set some aliases in the file named user-aliases.cmd

What does your `user-alias.cmd` file look like?

**Comment by iSumitBanik** [comment]
Even I faced this issue. Later I realized that I had made mistakes in the `user-aliases.cmd` file

**Comment by DRSDavidSoft** [comment]
The default `user_aliases.cmd` file is located here, you can always compare yours with the default one to see if it needs adjustment:

https://github.com/cmderdev/cmder/blob/master/vendor/user_aliases.cmd.default

@chrisdel101 Your edits is **not** correct as you're essentially removing the `%CMDER_ROOT%` from your aliases. Consider using the default user aliases from the link provided above and make sure your environment variable for `CMDER_ROOT` is either unset or is pointing to the correct directory:

https://github.com/cmderdev/cmder/wiki/Setting-up-Environment-Variables

Once you've verified this, please edit your comment to remove the incorrect adjustments as it could confuse future visitors.

For example, the `cmderr` command is intended to bring you to the root directory of cmder, but now your edits alias it to `cd /d` which will just produce an error instead.
