### ISSUE TITLE
the {cmd} task

### ISSUE THREAD

**Issue by liongoodvery** [cmderdev/cmder#876]
I launched the console with the {cmd} task .I typed `ipconfig`  , then pressed the up key to get the former command, `ipconfig` , and the I pressed ESC key to clear the command in the prompt line .
The console did not delete the first char after the prompt sign . I the typed `ipconfig` the console displayed as `iipconfig`.The command correctly excuted .I used the mouse left key to copy the command and then copy in notepad.It is 'iipconfig' the 'i'  char is really there ,but the command executeed correctly  .For a deep explore,I found that when the command is no longer than 4 characters, such as `ls`,`tree`,works well,but `start` not

**Comment by Jackbennett** [comment]
This should be fixed in 1.3
