### ISSUE TITLE
Enconding ?

### ISSUE THREAD

**Issue by ouraios** [cmderdev/cmder#877]
Hi, i've a problem when i tried to use curl on wttr.in but cmder display some weird character :
![cmder](https://cloud.githubusercontent.com/assets/9526860/13637477/d7134c1c-e607-11e5-9281-2272125dac79.JPG)

How to correct this ?

**Comment by vladimir-kotikov** [comment]
Maybe `chcp 65001`

**Comment by ouraios** [comment]
Thanks it worked but when im connected thourgh ssh no-color are display, it's just grey how is it possible ?colour are enable in the remote machine (under debian)
