### ISSUE TITLE
ctrl+l with powershell in quake mode clears the first prompt line as well

### ISSUE THREAD

**Issue by spooky** [cmderdev/cmder#879]
When pressing ctrl+l to clear the output while using powershell, the first prompt line is cleared as well, so the only visible thing left is the lambda sign and the current path is not visible. This behavior is not visible when using cmd instead of powershell.

**Comment by MartiUK** [comment]
I see the problem, fix on the way

**Comment by spooky** [comment]
Worked like a charm. Thanks.
