### ISSUE TITLE
open new window with `ctrl+c` have a different view

### ISSUE THREAD

**Issue by iulo** [cmderdev/cmder#880]
like

![cmder](http://7xpdjc.com1.z0.glb.clouddn.com/cmder.gif)

How reset the new window as default ?

**Comment by MartiUK** [comment]
@cmderdev/owners @cmderdev/trusted-contributors 
I can't confirm this with the development builds, can some else confirm it has been fixed?

**Comment by Stanzilla** [comment]
wfm
