### ISSUE TITLE
Cmder opens off screen 

### ISSUE THREAD

**Issue by wheelerlaw** [cmderdev/cmder#881]
When I open cmder, it opens halfway off the screen on the right side of the screen. When I move it on screen, close it, then re-open it, it opens in the same half-off-screen position as last time, not remembering where it was previously closed.

**Comment by MartiUK** [comment]
This has been fixed already but for now you can go into the settings > Main > Size & Pos > Auto Save window size and position on exit.

**Comment by wheelerlaw** [comment]
That did it! Thanks!
