### ISSUE TITLE
mysql running on startup

### ISSUE THREAD

**Issue by swarajd** [cmderdev/cmder#882]
I freshly downloaded cmder mini, and when I run it it attempts to run mysql twice

![image](https://cloud.githubusercontent.com/assets/1250084/13679074/e1790bd4-e6bf-11e5-9164-abe5ab124cda.png)

I have been able to fix the error and add mysql to the path but then it prints out the generic man pages 

![image](https://cloud.githubusercontent.com/assets/1250084/13679143/4b48e552-e6c0-11e5-99fe-0c2c2f777968.png)

Is there any way to stop mysql from running at startup? I have tried searching through the entirety of the downloaded content for anything that contains mysql but I have only found my adding mysql to the path

**Comment by MartiUK** [comment]
Did you add the path or the path and the executable?

**Comment by sylram** [comment]
See issue https://github.com/cmderdev/cmder/issues/185
