### ISSUE TITLE
Line-wrapping breaks when using backspace key in a git repo with Cmder mini and Git for Windows.

### ISSUE THREAD

**Issue by JustHereForTheBugReport** [cmderdev/cmder#883]
The line wrapping behavior is not working correctly inside a git repo.

Demo: [http://i.imgur.com/2CNL7KH.gif](http://i.imgur.com/2CNL7KH.gif)

Steps to reproduce:

- navigate into a git repo
- enter a command that is long enough to wrap around
- backspace the characters on the second line

Expected result: The cursor returns to the first line

Actual result: The cursor returns to a blank line between the first and third.

I am running Cmder mini v1.2.9. I also have Git for Windows 2.6.3.windows.1.

**Comment by JanSchulz** [comment]
Can you try the latest prereleases (Link is in the readme), this should be fixed.

**Comment by JustHereForTheBugReport** [comment]
The latest prerelease I could find is v1.2.9 which is the version I'm currently using (https://github.com/cmderdev/cmder/releases)

**Comment by janschulz** [comment]
Get one here: https://ci.appveyor.com/project/MartiUK/cmder/branch/development/artifacts

**Comment by Stanzilla** [comment]
Yeah it's a bad situation again @MartiUK you wanted to do a new pre-release or release "soon"? Want me to just do a pre-release now?

**Comment by JustHereForTheBugReport** [comment]
Confirmed this is fixed in the latest build at https://ci.appveyor.com/project/MartiUK/cmder/branch/development/artifacts . Thank you.

I did notice that a couple of characters can become hidden behind the scrollbar, but I can make the scrollbar disappear by hovering over it briefly then moving the mouse away so not a big deal.
