### ISSUE TITLE
Invaid context menu entry after re-locating cmder folder

### ISSUE THREAD

**Issue by selrond** [cmderdev/cmder#884]
I have an invalid context menu entry in Windows - `Cmder Here` which says `Application could not be found`
Worked fine until I moved the cmder folder to another location on my pc - what am I supposed to do to make it work again?

**Comment by MartiUK** [comment]
You may need to unregister and then reregister the context menu.

**Comment by selrond** [comment]
Yeah but how - could you lend me a hand?

**Comment by MartiUK** [comment]
Try `cmder.exe /UNREGISTER ALL`

**Comment by selrond** [comment]
sorry for a dumb question, but what exactly should I do?

**Comment by MartiUK** [comment]
Run that command
