### ISSUE TITLE
Tab autocompetion for git is inconsistent (doesn't work with git add)

### ISSUE THREAD

**Issue by c33s** [cmderdev/cmder#885]
i testes `cmd.exe` with `clink`, there git autocompletion works as expected, tab completes the path after an `add`:
```
C:\test>git add
CHANGES             clink.lua           clink_x64.exe
LICENSE             clink_dll_x64.dll   clink_x86.exe
clink.bat           clink_dll_x86.dll   profile\
clink.html          clink_inputrc_base
C:\test>git add
CHANGES             clink.lua           clink_x64.exe
LICENSE             clink_dll_x64.dll   clink_x86.exe
clink.bat           clink_dll_x86.dll   profile\
clink.html          clink_inputrc_base
C:\test>git add clink
clink.bat           clink_dll_x64.dll   clink_x64.exe
clink.html          clink_dll_x86.dll   clink_x86.exe
clink.lua           clink_inputrc_base
C:\test>git add clink.
clink.bat   clink.html  clink.lua
C:\test>git add clink.bat
```

doing the same with cmder does not work. pressing tab does nothing with `git add`
```
C:\test
λ git add
```
`git apply` works as expected and completes the path
C:\test
λ git apply
CHANGES             clink.html          clink_dll_x86.dll   clink_x86.exe
LICENSE             clink.lua           clink_inputrc_base  profile\
clink.bat           clink_dll_x64.dll   clink_x64.exe
C:\test
λ git apply

changing the `C:\Program Files\Cmder\vendor\clink-completions\git.lua` from
```
--- snip ---
local git_parser = parser(
    {
        {alias},
        "add" .. parser({files},
            "-n", "--dry-run",
            "-v", "--verbose",
--- snip ---
```
to
```
--- snip ---
local git_parser = parser(
    {
        {alias},
        "add" .. parser(
            "-n", "--dry-run",
            "-v", "--verbose",
--- snip ---
```
make it work.

**Comment by joedrummer8993** [comment]
Thank you!  This has been bugging me for a while now!

**Comment by Stanzilla** [comment]
Nice find! If you don't mind, please file a bug over here, https://github.com/vladimir-kotikov/clink-completions that's the thing we are using in cmder.

**Comment by vladimir-kotikov** [comment]
This should be fixed in 0.2.2 which is a part of latest Cmder. Guys, could you please check the latest build before?

**Comment by vladimir-kotikov** [comment]
So, it works as expected with latest build?

**Comment by janschulz** [comment]
Maybe add an issue template which then includes a link to the Builds?

**Comment by c33s** [comment]
i tested it with the latest cmder from http://cmder.net/ which is [1.2.9][1]. this version of cmder ships with clink 0.4.5.
doing a manually upgrade of `C:\Program Files\Cmder\vendor\clink` to clink version 0.4.7
has not helped. missed to upgrade clink-completions.

as i mentioned above clink alone works for me, this was the reason i opened an issue here at the cmder repo. 

in my personal opinion this issue should not be closed. first a new cmder release should be deployed on cmder.net shipping the latest clink and clink-completions vendors.

vote for reopen. 

[1]: https://github.com/cmderdev/cmder/releases/download/v1.2.9/cmder.zip

**Comment by vladimir-kotikov** [comment]
@c33s, i meant this build https://ci.appveyor.com/project/MartiUK/cmder/build/artifacts which incledes completions@0.2.2 with the fix for `git add`

**Comment by c33s** [comment]
@vladimir-kotikov but i still think the version which is online on cmder.net is counting. 

from the user experience view, a user of this awesome software shouldn't be forced to dig for the right build. if i google for cmder http://www.cmder.net is the first page, this is the page where users download the program and there it is not fixed. so this issue apply. 

also just by opening the issue here i helped @joedrummer8993
