### ISSUE TITLE
Git Bash update breaks "Duplicate root" functionality

### ISSUE THREAD

**Issue by amirmohsen** [cmderdev/cmder#886]
First off, thanks for this amazing tool. It has massively helped streamline my development process.

Unfortunately, I'm having an issue after upgrading my git from 1.9.x (32bit) to 2.7.3 (64bit). Basically, the "Duplicate root" functionality doesn't work with the new Git Bash. It does open a new tab, but it stays in the default directory. My colleagues at work are having the same issue so it's not just me. I use Windows 10.

I'd appreciate it if you could investigate this further.

**Comment by MartiUK** [comment]
I can confirm this only works with the cmd task at this time, I'll look into resolving this over the next few weeks.

**Comment by amirmohsen** [comment]
Okay, thanks for looking into it.

**Comment by daxgames** [comment]
I think this might be an issue for ConEmu.  I see nothing in the environment that a script can trigger on after duplicating root.  Also if you look at the confirmation box from ConEmu it specifically mentions cmd.exe even when duplicating a bash session.

**Comment by Maximus5** [comment]
https://github.com/Maximus5/ConEmu/issues/761#issuecomment-230322320
