### ISSUE TITLE
Updating git-for-windows after installing the full cmder?

### ISSUE THREAD

**Issue by johanbove** [cmderdev/cmder#887]
Git was updated to version 2.7.4 recently. What are the correct steps in order to upgrade Git so **cmder** can still continue with it?

<img width="373" alt="snip_20160318151518" src="https://cloud.githubusercontent.com/assets/922765/13880376/43e06f4e-ed1c-11e5-8cc1-e17c9c7c5b3c.png">

**Comment by janschulz** [comment]
Install to default location and it will be added to the path by `init.bat` no matter what and the unix tools are also added.

**Comment by johanbove** [comment]
Thanks for the reply. So I stick with default "Use Git from the Windows Command Prompt" option here?

**Comment by Stanzilla** [comment]
You can also just download the portable version and extract it into the `vendor`dir

**Comment by johanbove** [comment]
Thanks for the suggestion @Stanzilla , but I already have Git For Windows installed and it is showing up in the installed software in Windows Configuration Screen. I don't want to have multiple version of Git on my machine. I want to make sure that if I install Git For Windows using the provided installer then it will be found by Cmder.
