### ISSUE TITLE
Add the download link of the Development Version to cmder.net

### ISSUE THREAD

**Issue by c33s** [cmderdev/cmder#888]
as mentioned in https://github.com/cmderdev/cmder/issues/885 the current release on cmder.net has outdated vendors which are updated in the actual builds of cmder 

please add a link "Download Nightly Build" to the this version next to the "Download minimal" "Download Full" Button on cmder.net

this would prevent opening already solved issues.

for the records or persons looking for the actual build. it can be found [here](https://ci.appveyor.com/project/MartiUK/cmder/build/artifacts)

**Comment by Stanzilla** [comment]
https://github.com/cmderdev/cmderdev.github.io

**Comment by c33s** [comment]
@Stanzilla should i recreate the issue there?

**Comment by Stanzilla** [comment]
Yes!
