### ISSUE TITLE
Adding FAR to cmder?

### ISSUE THREAD

**Issue by VileTouch** [cmderdev/cmder#889]
In my computer i use Conemu, with far, clink, gfw and babun, all installed separately, but i also have cmder in a flash drive for my console fix on the go... problem is, i really really miss far (and it's plugins!...) when i'm out and about. 

if i call far directly it works, but that means bypassing cmder almost entirely. so the question is how to do it seamlessly?

**Comment by janschulz** [comment]
I usually do this when I want something added to the path in a cmd task (assumes the latest build, NOT the latest release):

* add a new dir somewhere (I usually use `<CMDER_ROOT>\vendor\name_of_package`)
* edit  `<CMDER_ROOT>\config\user-profile.bat` and include a line ala `@set "PATH=%PATH%;%CMDER_ROOT%\vendor\heimdall"` (depends where the binaries are in that dir, a lot of times it's in a subdir `bin`
* restart cmder

I have cmder added to my dropbox, so this makes heimdal (android flasher) available on all my computers where I have access to my dropbox.
