### ISSUE TITLE
cmder is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Kurdym** [cmderdev/cmder#891]
Just downloaded the 1.3 prerelease, told Norton to trust the cmder.exe, and fired up.

Cmder came back with error message:
cmder is not recognized as an internal or external command, operable program or batch file.

Did a quick search on this error, but no solution seems to be solving it.

**Comment by janschulz** [comment]
With "fired up" you mean you double clicked on cmder.exe?

**Comment by Kurdym** [comment]
Yes. 
Also I tried to run the init.bat from the prompt then, and it gave the same error.

**Comment by Stanzilla** [comment]
Does it work if you disable Norton?

**Comment by Kurdym** [comment]
I disabled firewall and auto-protect on Norton, but still the same error.

**Comment by MartiUK** [comment]
Have you re-downloaded since disabling, as norton will have quarantined/deleted anything it deems a virus?

**Comment by Kurdym** [comment]
I redownloaded the.zip and extracted it to a folder, I told Norton to leave alone.
All goes fine. Doubleclick cmder, and a question from conemu5 pops up telling me it wants to download. I allow it and the terminal starts cmd, showing the error.
Opening a powershell tells me it created a profile and still another powershell goes without problems.

**Comment by MartiUK** [comment]
Have you aliased cmd -> cmder at any point?

**Comment by Kurdym** [comment]
Not that I know of. Where could that be?

**Comment by MartiUK** [comment]
Probably not, try deleting the `@echo off` at the top of init.bat and let me know how far it goes.

**Comment by Kurdym** [comment]
'F:\Standalone\_console\cmder' is not recognized as an internal or external command,
operable program or batch file.

I moved the folder from F:\Standalone\_console\cmder(1) to T:\cmder and restarted a few times.

Now it's fine. Only Norton really, really wants to delete git-bash.exe

**Comment by MartiUK** [comment]
The '(1)' is probably what caused your issues.

**Comment by Kurdym** [comment]
Yes, it was. 
Remainder of previous cmder.zip download. Opus renames newest to (1). Extracted it like that. 
Thanks for your extended help.
