### ISSUE TITLE
git stash

### ISSUE THREAD

**Issue by twiggler** [cmderdev/cmder#894]
I get the following error when running git stash:

λ git stash list
fatal: C:\tools\cmder\vendor\git-for-windows\mingw32/libexec/git-core\git-stash cannot be used without a working tree.

d:\Documents\SpaceFloepers  

d:\Documents\SpaceFloepers is my working directory, and contains the repository. Git stash works correctly when using git for windows bash prompt.

**Comment by molteber** [comment]
Been a problem for me a long time now. So frustrated that git stash won't work

**Comment by glucas** [comment]
This works just fine for me. Are you having problems with other git commands, or only stash? What output does this give you:

    git rev-parse --is-inside-work-tree

**Comment by tonyzzp** [comment]
I am meeting the same problem too.

"git submodule" throw the same error.

but it is ok when i use git bash or windows cmd.

**Comment by tonyzzp** [comment]
git rev-parse --is-inside-work-tree

this returns "true"

**Comment by twiggler** [comment]
λ git rev-parse --is-inside-work-tree
returns "true"

**Comment by tysonnero** [comment]
I too cannot execute "git stash" or "git submodule" and some other commands as well

**Comment by WRRB** [comment]
I'm having this issue as well.

**Comment by glucas** [comment]
In my git-for-windows install the string "cannot be used without a working tree" occurs in two places, in  the git-sh-setup script under cmder/vendor/(etc). It's either a result of calling

    git rev-parse --is-inside-work-tree 2>/dev/null

or 

    git rev-parse --is-bare-repository

Someone who can reproduce this problem could potentially narrow it down a bit further by changing one of those messages and seeing which specific case is failing.

**Comment by twiggler** [comment]
I can confirm the problem occurs in  require_work_tree when executing git stash.
The problem occurs with both cmd.exe and bash.

**Comment by chrisseroka** [comment]
The same happened on my machine. It turned out, that "git stash" worked while running in classic cmd.exe, so I disabled "ConEmu -> Settings -> Features -> Inject ConEmuHk". Now it works fine.

**Comment by raaaste** [comment]
Had this problem with `git mergetool` but @chrisseroka s solution fixed it.
