### ISSUE TITLE
PowerShell: tab completion not working with some modules

### ISSUE THREAD

**Issue by rauchmat** [cmderdev/cmder#895]
Modules that provide tab completion won't work with the default Powershell-Task of cmder. Expamples for affected modules are:
- https://github.com/tkellogg/Jump-Location
- https://github.com/cameronharp/Go-Shell

Interestingly tab completion works with posh-git.

**Comment by Jackbennett** [comment]
Are they installed to a path found in `$env:psmodulepath.split(';')` ?

**Comment by rauchmat** [comment]
Yes, they are. I just recognized that the issue is not reproducable any more with Version v1.1.4.1. Therefore I will close the ticket.
