### ISSUE TITLE
Feature Request: Send to all/group

### ISSUE THREAD

**Issue by DigiAngel** [cmderdev/cmder#896]
Would love to be able to group tabs/consoles and mirror commands and keyboard to all or those in a group.  Thank you for the great app!

**Comment by glucas** [comment]
This is already supported: you can split the window one or more times and send the same input to each split. 

I forget if this has a key binding by default. Go to Settings --> Keys & Macros and look for the command described "Group keyboard input for visible splits".

**Comment by glucas** [comment]
Looks like this is bound to the Apps+G hotkey by default.

**Comment by DigiAngel** [comment]
Well it sure is and does work great...I totally missed it.  Thank you.
