### ISSUE TITLE
Huge Cmder title bar when using on remote computer using Microsoft RDP

### ISSUE THREAD

**Issue by edgr-sanchez** [cmderdev/cmder#897]
Can anyone else reproduce this issue?

It happens when I use Microsoft's Remote Desktop app on OS X El Capitan to remote into a Surface Pro 4 running Windows 10.

Any time that I am connected, the title bar on Cmder looks like this:

![screenshot](http://i.imgur.com/wotw416.png)

**Comment by Daniel15** [comment]
I can repro this on a Lenovo X1 Yoga when using an external display. Cmder is fine on the laptop screen, but the title bar is giant when using it on the secondary monitor.

**Comment by mabdelfattah** [comment]
I'm also having this issue on Windows 10 + External screen, and I've restarted many times since I installed Cmder!

**Comment by dan-ionut-fechete** [comment]
Overriding high DPI scaling behavior should help

![image](https://user-images.githubusercontent.com/14959933/36126431-492a9284-100d-11e8-91ed-54d745eaad1b.png)
