### ISSUE TITLE
'clear' is not work in windows.

### ISSUE THREAD

**Issue by Tiny-Box** [cmderdev/cmder#898]
if I ssh to an virtualbox like vagrant, `clear` is not work. 
For example:
![image](https://cloud.githubusercontent.com/assets/7588395/14060474/e9360bd2-f39f-11e5-90a4-994741cb11cd.png)

**Comment by conradoojr** [comment]
@Tiny-Box in aliases file insert this **clear=cls**.

**Comment by born2net** [comment]
try Cont-L

**Comment by sekai92id** [comment]
use Ctrl+L

**Comment by Tiny-Box** [comment]
Ctrl+L is not work.

**Comment by bjohnso5** [comment]
I'm having this same issue when ssh'd to a remote (linux) host - invoking `clear` moves the cursor and current input line to the top of the window, but the previous output is not overdrawn with the background. Likewise to @Tiny-Box, `ctrl-l` has the same behaviour in this scenario.

**Comment by sekti92** [comment]
use Ctrl+L

**Comment by Carl-Foster** [comment]
To fix this for Windows, need to call this first thing: `export TERM=cygwin`

I'm unsure why this works while others don't, but it certainly works. Not sure what it will effect later though.

**Comment by shengbinxu** [comment]
https://github.com/cmderdev/cmder/issues/594

in remote mechine, add:
export TERM=vt100

I have solved my question。

**Comment by hailongs** [comment]
@shengbinxu 
 
这不是一个好办法吧？如果老是要操作一些线上的服务器怎么办啊

**Comment by shengbinxu** [comment]
@hailongs  是的。所以我现在就不用cmder了。问题太多，兼容性很差。还是xshell比较顺手。

**Comment by daxgames** [comment]
This has nothing to do with Cmder since it is on a remote machine.  Closing.
