### ISSUE TITLE
Cmder.exe recognized as a trojan/virus by 11/56 AV vendors

### ISSUE THREAD

**Issue by tskarman** [cmderdev/cmder#899]
See here: [https://www.virustotal.com/de/file/aa72f5fdb7433c1c1d16d4190c44744749c89a310d3fa2dafe281c94f2c08617/analysis/]

This occurs for the current [https://github.com/cmderdev/cmder/releases/tag/v1.3.0-pre] but happened with some AppVeyor build a few weeks ago, too.

This means that Cmder is currently not usable.

Thank you for this project,
regards,
Tobias

**Comment by HwapX** [comment]
+1

**Comment by Stanzilla** [comment]
Please report it as a false positive to your AV vendor.

**Comment by tskarman** [comment]
@Stanzilla The executable is categorized as a trojan/virus by at least 5 major vendors (see the virustotal link above).

Since I am not qualified to judge whether the executable actually is harmless, I won't be able to make such a report.

I just wanted to let you know that the executable is currently considered harmful by many AV vendors. Maybe you can tell which third-party component (if any) is causing this. It's the Cmder.exe that gets deleted by the AV software.

The virustotal link contains the name of the categorization (Razy).

**Comment by MartiUK** [comment]
IIRC it was clink this time around, only thing we can do is report the false positive and wait for the AV vendors to catch up.

**Comment by katio** [comment]
It's still an issue and it's a little scary for new users (3 / 57):
https://virustotal.com/es/file/477fb784b7b3f382f7de9cd40a4d46a86dc2286b8036e68ad188abebbaea4ad6/analysis/1496897221/

**Comment by zetnet** [comment]
After using cmder for a while, bitdefender just started blocking the application with the message "Potentially malitious application blocked.". Path [...]\vendor\conemu-maximus5\ConEmu\ConEmuC64.exe

**Comment by gabeio** [comment]
It isn't just an issue for new users. Corporate environments this will set off a lot of alarms.

**Comment by codecanoe** [comment]
Happening with Symantec Endpoint Protection Version 14.2. I've submitted a false positive report to them.

**Comment by idrissAbbou** [comment]
I reported this to Avast as false positive and I'm waiting for there answers

**Comment by idrissAbbou** [comment]
this is avast response :

 Hello,

Thank you for reporting this.

Our virus specialists have been working on this problem and the provided file has been whitelisted.

For future reference you might also find the following article to be useful: https://support.avast.com/en-us/article/228/

Best Regards,
Prokop
The Avast Support Team
