### ISSUE TITLE
Supporting "title" provided to start, in the Tab

### ISSUE THREAD

**Issue by danielHalan** [cmderdev/cmder#902]
Hi, 

When starting an application using **start "some title" d:/xxxxx** the title is not shown in the Tab, even when using the %s parameter which says "title" in the help.

**Comment by faouzzz** [comment]
![image](https://cloud.githubusercontent.com/assets/576894/14212294/7d7c4784-f832-11e5-9049-b8ae76abaae3.png)

**Comment by daxgames** [comment]
Closing to inactivity and it is really a Conemu question.
