### ISSUE TITLE
v1.3.0 antivirus

### ISSUE THREAD

**Issue by codesboy** [cmderdev/cmder#903]
v1.3.0   Blocked by antivirus software( jinshanduba) <img src="http://7xlaft.com1.z0.glb.clouddn.com/jietu/3.png">

**Comment by bappamungkas** [comment]
I got 10 warnings from avast when extracting v1.3.0 zip
for sure it was false positive right?
i ignored all the warnings.

**Comment by codesboy** [comment]
@bappamungkas You are too handsome

**Comment by Stanzilla** [comment]
Please report it as a false positive.
