### ISSUE TITLE
Hide Caption Always grayed out

### ISSUE THREAD

**Issue by sigmap** [cmderdev/cmder#906]
In my settings the option to "Hide Caption Always" is grayed out, unclickable, and checked. Forcing me to work inside a borderless window. I do not mind this, but I haven't been able to uncheck that and for the time being would prefer to correct this.

**Comment by Inveracity** [comment]
I ended up having to reset cmder to get it back, couldn't even configure the conemu.xml to sort it out :(

**Comment by adamsampson** [comment]
I just ran into this one myself, it is tied to the Transparency > User Screen Transparency setting.  When enabled, it forces "Hide Caption Always"

**Comment by sigmap** [comment]
Well, that answers that. Guess this matter is resolved/closed?

**Comment by YuZhengya90** [comment]
> I just ran into this one myself, it is tied to the Transparency > User Screen Transparency setting. When enabled, it forces "Hide Caption Always"

Thanks. It's helpful.
