### ISSUE TITLE
Unix commands not working in windows 10

### ISSUE THREAD

**Issue by srm-soumya** [cmderdev/cmder#908]
I updated my machine to windows 10, after that basic unix commands like ls, rm etc are not working in cmder.

Any work around for this?

**Comment by daxgames** [comment]
Output of 'git --version'?

**Comment by srm-soumya** [comment]
git --version: 
git version 2.8.1.windows.1

which git
'which' is not recognized as an internal or external command,
operable program or batch file.

**Comment by daxgames** [comment]
No idea.  I had an issue with git 2.8.0 but 2.8.1 fixed it.

Output of 'dir "%CMDER_ROOT%\vendor"' from inside CMDER?

**Comment by daxgames** [comment]
Output of 'ls'

**Comment by srm-soumya** [comment]
λ dir "%CMDER_ROOT%\vendor"
 Volume in drive C is Windows8_OS
 Volume Serial Number is A06A-CF28

 Directory of C:\Users\Gramener\Downloads\softwares\cmder\vendor

10/14/2015  08:45 AM    <DIR>          .
10/14/2015  08:45 AM    <DIR>          ..
10/14/2015  08:44 AM    <DIR>          clink
10/14/2015  08:45 AM    <DIR>          clink-completions
04/07/2016  11:11 AM    <DIR>          conemu-maximus5
10/14/2015  08:44 AM    <DIR>          git-for-windows
10/14/2015  08:24 AM             2,466 init.bat
10/12/2015  05:24 PM             1,910 profile.ps1
10/12/2015  04:30 PM    <DIR>          psmodules
10/12/2015  04:30 PM                52 Readme.md
10/12/2015  05:24 PM               737 sources.json
10/14/2015  08:45 AM    <DIR>          tmp
               4 File(s)          5,165 bytes
               8 Dir(s)  327,179,067,392 bytes free

λ ls
'ls' is not recognized as an internal or external command,
operable program or batch file.

**Comment by daxgames** [comment]
Output of 'echo %path%'?

Have you tried redowloading Cmder?

**Comment by srm-soumya** [comment]
λ echo %path%
C:\Users\Gramener\Downloads\softwares\cmder\bin;C:\Program Files\Git\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\share\vim\vim74;C:\Users\Gramener\Downloads\softwares\cmder\vendor\conemu-maximus5;C:\Users\Gramener\Downloads\softwares\cmder\vendor\conemu-maximus5\ConEmu;C:\Program Files (x86)\Lenovo\FusionEngine;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Common Files\lenovo\easyplussdk\bin;C:\Program Files (x86)\nodejs\;C:\Program Files\Git\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\Skype\Phone\;C:\HashiCorp\Vagrant\bin;C:\Program Files (x86)\Heroku\bin;C:\Program Files (x86)\git\cmd;C:\Android;C:\Windows\System32;C:\Users\Gramener\Anaconda3;C:\Users\Gramener\Anaconda3\Scripts;C:\Users\Gramener\Anaconda3\Library\bin;C:\Users\Gramener\AppData\Roaming\npm;C:\Program Files\Sublime Text 3;C:\Program Files\PostgreSQL\9.5\bin;;C:\Users\Gramener\Downloads\softwares\cmder

**Comment by srm-soumya** [comment]
Yes I tried to redownload it, still it doesn't work, Is there any other alternative like cmder?

**Comment by daxgames** [comment]
According to your path env var it looks like you have multiple copies of git installed both x64(C:\Program Files\git) and x86(C:\Program Files (x86)\git).  One of these is preferred by the cmder startup scripts, neither of which appears to have the larger set of *nix commands in the path.  This may be why it does not work.

Do you want to use cmders git or an externally installed git?  If cmders then uninstall the other two and make sure that are removed from the path env var.

**Comment by srm-soumya** [comment]
Thanks a lot for the support, it's working for me now.

**Comment by daxgames** [comment]
Glad to help.

**Comment by Jackbennett** [comment]
Thanks @daxgames for helping. @srm-soumya feel free to re-open or make new issues if it's not fixed.

**Comment by aarohmankad** [comment]
@daxgames what would be the solution if I don't want to use the cmder git but rather one that I installed?

**Comment by daxgames** [comment]
First step would be to use cmder_mini distribution OR if you already have cmder full installed just delete the %cmder_root%/vendor/git-for-windows folder.  Then start cmder.

**Comment by ameyzulkanthiwar** [comment]
Hey Soumya how did you fix this issue?
