### ISSUE TITLE
How to start in a given directory

### ISSUE THREAD

**Issue by hyperknot** [cmderdev/cmder#91]
I am trying to integrate cmder into TotalCommander.

I have been using cmd.exe and msysgit integration in with custom keys (F8, F9) to start them in the current directories from Total Commander.

I would like to do it with cmder, but every time it starts in the user's homedir. Is there any way to make cmder start in a given dir?

**Comment by kkorus** [comment]
to add:
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\Directory\shell\Console]
@="Cmder"

[HKEY_CLASSES_ROOT\Directory\shell\Console\command]
@="\"D:\\Apps\\cmder\\Cmder.exe\" /START \"%V\""


[HKEY_CLASSES_ROOT\Directory\Background\shell\Console]
@="Cmder"

[HKEY_CLASSES_ROOT\Directory\Background\shell\Console\command]
@="\"D:\\Apps\\cmder\\Cmder.exe\" /START \"%V\""

to remove:
Windows Registry Editor Version 5.00

[-HKEY_CLASSES_ROOT\Directory\shell\Console]

[-HKEY_CLASSES_ROOT\Directory\Background\shell\Console]

**Comment by JamoCA** [comment]
So what command line options to do add in order to launch cmder.exe and have it start in a specific path?  I'm using Total Commander too & added a link to the menu bar.  I want to open cmder in the currently selected directory and haven't had any success passing different "command" or "parameter" options.  Thanks.

**Comment by Sergej-Popov** [comment]
@JamoCA that command works for me, but only of cmder not already running. If instance of cmder is running it will refuse to open new tab in that location. This is annoying as ConEmu doesn't have that problem!

**Comment by JamoCA** [comment]
ok, I guess that makes sense, but it feels more like a limitation. I'm trying to keep cmder running in the tray. It'd be beneficial if there were a parameter to launch a specified path in a new cmder tab; kinda like clicking a URL opens a new tab in an already-running default browser.

**Comment by kkorus** [comment]
@JamoCA Hi, did you figure out how to open new folder as new tab? :)

**Comment by JamoCA** [comment]
Strange.  I removed the quotes from a simple path with no spaces (c:\) and it works, but "c:\" does not.

If I pass a path that has spaces in the directory name (c:\program files\), it won't work unless I specifically add quotes ("c:\program files\").

Is this a bug?  Paths should always work with quotes regardless of whether they have spaces or not, right?  Or do I path names need to be parsed to determine if there are spaces and then manually add quotes?

If I untoggle "Settings | Appearance | Single Instance Mode", individual cmder windows will open to the correct directories.  If I enable "single instance mode", any new "/start" commands fail... a new cmder tab w/the specified start directory is not opened.

If cmder is running in the tray with no tab open, using DOS to specify new start directory doesn't do anything... unless "single instance" is disabled.

QUESTION: Is it possible to execute cmder.exe with a unique start path and have it open up in a single instance with a new tab?

**Comment by kuncevich** [comment]
Trying to open a directory in new tab `cmder /single /start "path_to_my_dir"` not working. Only got new tab opened. Tried also with just simple paths like `cmder /single /start "c:"` or `cmder /single /dir "c:"` `cmder /single "c:"`  also without quotes doesn't matter. Could it be because I am using cygwin bash as default?

**Comment by JanSchulz** [comment]
Please try on of the latest dev builds (in appveyor -> artifacts)

**Comment by remcoros** [comment]
I just downloaded the latest appveyor build (mini). Completely removed 1.2.9 and started with a fresh install. 

I changed to 'single instance mode' in settings (and that's the ONLY setting I change).

Still not working properly for me :(

I tried:

Start the first instance using a shortcut on my taskbar (this opens in C:\Users\Remco).

Then (from Win-R):

- cmder.exe "C:\"
Gives focus to cmder, but nothing happens

- cmder.exe /start "C:\"
Gives focus to cmder, but nothing happens

- cmder.exe /single "C:\"
Gives focus to cmder, Opens a new tab, but doesn't change to "C:\" (it stays in C:\Users\Remco)

**Comment by kuncevich** [comment]
I figure out that in my case actually I had setting under `Settings/Startup/Tasks`: `d:%USERPROFILE%` that tells `cmder` to open my %USERPROFILE% directory on start. By removing that all working fine

**Comment by jakubsuchybio** [comment]
Thanks! Worked for me. When removed the %USERPROFILE% from Tasks in Settings of cmder. Then everytime I start cmder from Total Commander I am at current dir, which I started it from.

**Comment by pianoboysai** [comment]
this is my solution.
open init.bat, and delete this section
"
@if defined CMDER_START (
    @cd /d "%CMDER_START%"
) else (
    @if "%CD%\" == "%CMDER_ROOT%" (
        @cd /d "%HOME%"
    )
)
"

then set single instance for cmder,  finally, add register item: 
C:\yourpath\cmder.exe /single "%V"

**Comment by hmatijevic** [comment]
Instructions: Open Cmder -> Settings -> Tasks -> select {cmd::Cmder} (in my case). On the bottom (below textarea) you have button named "Startup dir...", and than select startup directory. Close cmder, and start again. That's it, enjoy

**Comment by eromoe** [comment]
thanks  @kuncevic
All bad is `%USERPROFILE%`  in task , remove that  make me open cmder in current directory.

**Comment by ravindrapalli33** [comment]
Another Method USING GUI
1. RUN cmder
![image](https://cloud.githubusercontent.com/assets/9862715/19747416/34ebe338-9bf9-11e6-8cbb-c8b4c16e91bf.png)
2. Right click on the tab bar and go to settings
3. Select Tasks under Start UP
4. On the right side -> select Predefined Tasks(anyone) -> In my case I'm using cmd: Cmder
5. After selecting click on Startup dir... at the bottom of the window.
6. Browse the directory and click OK
7. Save settings

**Comment by saeed3e** [comment]
Addition on @ravindrapalli33 comment:

And also make sure put/write file path after default cmder settings, as shown in attached image.
![cmder](https://cloud.githubusercontent.com/assets/3379401/21078794/cf0576b6-bfa1-11e6-8457-ff969fdc5486.PNG)

**Comment by Artaches** [comment]
Checkout my answer here: http://stackoverflow.com/questions/31933766/start-up-cmder-conemu-console-in-a-specific-folder/43836978#43836978

Basically, create a shortcut for ConEmu and change the "Start in:" attribute in the shortcut's properties.

**Comment by wujohns** [comment]
@saeed3e can‘t help anymore

**Comment by syon** [comment]
Here is my settings. This is for __["Cmder Here"](https://github.com/cmderdev/cmder#shortcut-to-open-cmder-in-a-chosen-folder)__, not for a fixed path.

Using `%CMDER_START%` instead of `%USERPROFILE%`.

- `*cmd /k "%ConEmuDir%\..\init.bat"  -new_console:d:%USERPROFILE%`  
  ↓
- `*cmd /k "%ConEmuDir%\..\init.bat"  -new_console:d:%CMDER_START%`

![cmder-settings-edit](https://user-images.githubusercontent.com/3148102/27644572-e12d0e44-5c5e-11e7-8190-e2c47d10edef.png)

In case of opening Cmder.exe from shortcuts, you can set the path in arg its property.

![cmder-property](https://user-images.githubusercontent.com/3148102/27644854-8e890214-5c5f-11e7-94b5-1639471dd76a.png)

Now it works for me, I hope this will help.

**Comment by froston** [comment]
This worked for me ...
in `/cmder/vendor/init.bat` change

 `pushd "%USERPROFILE%"` to `pushd "%CD%"`

**Comment by johnkors** [comment]
Thanks, @froston . Worked for me as well.

**Comment by Frankstar** [comment]
@froston THANK YOU! After changing that i can use the `-new_console:d:C:\path\to\dir `
in combination with the init script for Tasks!

Working Example: `cmd /k "%ConEmuDir%\..\init.bat"  -new_console:d:C:\choco-packages `

Pls fix this Upstream

**Comment by hub23** [comment]
I just added this to my init file:
```:: Start in User Home if CMDER_START is not defined.
if not defined CMDER_START (
    pushd "%USERPROFILE%"
)```

**Comment by taekout** [comment]
<STEPS>
1. Go to setting. (Right click on title bar of the window) --> Click Settings.
![image](https://user-images.githubusercontent.com/6590707/35933804-91fba564-0bf0-11e8-83a9-bba2d8acf9df.png)

2. Then in the setting window, on left panel, click [Startup>Environment] then add string in text box on the right.
set CMDER_START=C:\YOUR_PREFERRED_PATH
(See image below)
![image](https://user-images.githubusercontent.com/6590707/35933889-d6ad8cd6-0bf0-11e8-901f-e01d7b06bf34.png)

In my case, I use "set CMDER_START=%USERPROFILE%\cmder_script_folder

**Comment by BXMurphy** [comment]
Thank you, @taekout! That worked perfectly.

**Comment by arfmach** [comment]
The `/start` command-line option doesn't work for paths with spaces. I've tried to enclose the path in single-quotes and double-quotes, but neither worked.
Obs. I want to use it as "Cmder here" shortcut, so I can't escape spaces with backslash or caret.

**Comment by mhamri** [comment]
go to `vendors\init.bat` and add this line at top of the file after the `@echo off`

````CMD
set CMDER_START=%cd%
````

**Comment by daxgames** [comment]
@mhamri Why?  Current cmder will open in the current dir and a specified dir.  IF your tasks are not using legacy config from older versions.

**Comment by daxgames** [comment]
@arfmach what you say does not work works fine for me with current cmder versions IF your tasks are not using legacy config from older versions.

**Comment by sinancetinkaya** [comment]
> to add:
> Windows Registry Editor Version 5.00
> 
> [HKEY_CLASSES_ROOT\Directory\shell\Console]
> @="Cmder"
> 
> [HKEY_CLASSES_ROOT\Directory\shell\Console\command]
> @=""D:\Apps\cmder\Cmder.exe" /START "%V""
> 
> [HKEY_CLASSES_ROOT\Directory\Background\shell\Console]
> @="Cmder"
> 
> [HKEY_CLASSES_ROOT\Directory\Background\shell\Console\command]
> @=""D:\Apps\cmder\Cmder.exe" /START "%V""
> 
> to remove:
> Windows Registry Editor Version 5.00
> 
> [-HKEY_CLASSES_ROOT\Directory\shell\Console]
> 
> [-HKEY_CLASSES_ROOT\Directory\Background\shell\Console]

I had to add backslashes to get it to work

```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\Directory\Background\shell\Console]
@="Cmder"

[HKEY_CLASSES_ROOT\Directory\Background\shell\Console\command]
@="\"D:\\depo\\Sistem\\cmder_mini\\Cmder.exe\" /START \"%V\""

[HKEY_CLASSES_ROOT\Directory\shell\Console]
@="Cmder"

[HKEY_CLASSES_ROOT\Directory\shell\Console\command]
@="\"D:\\depo\\Sistem\\cmder_mini\\Cmder.exe\" /START \"%V\""

```

**Comment by lagivan** [comment]
CMDER_START variable is not available in the latest version. Has anyone succeeded with setting it up with the latest version to run cmder in the current folder, not the fixed one?

**Comment by daxgames** [comment]
Current Cmder will now open in the current folder or whatever folder you specify on the command line unless the task used to launch the session in Conemu specifies a folder to open in.  If `cmder c:\windows` does not open Cmder in the specified folder then check your task.

**Comment by NicolasZapata** [comment]
Hi!! the fix what I implement is it . . .
Open the cmder settings (shift+ctrl+p) and you going to ComSpec in Integration, and do this changes.
![image](https://user-images.githubusercontent.com/35777697/95697652-0e58c300-0c05-11eb-8183-883afcffca30.png)
In Used Command Processor check cmd, and check "Set ComSpect enviroment variable for child processes to selected value"
And that's it, I shared the screenshot for reference, any feedback in answer's section.

**Comment by daxgames** [comment]
Current cmder.exe will open in the current folder or whatever folder you specify on the command line assuming you have removed the old hard coded start folder in the Conemu task launching Cmder like current releases have.
