### ISSUE TITLE
Aliased commands: Syntax Highlighting Lost

### ISSUE THREAD

**Issue by TheRealBluebird** [cmderdev/cmder#912]
Hi,

I can't find any mention of this in previous issues.

I created an alias: "l=ls -la" (without the quotation marks)

This a fresh install of cmder on Windows 7.

The results of executing the full command and then the alias are show below. Why is the syntax highlighting lost and how can I fix it?

![untitled](https://cloud.githubusercontent.com/assets/18311528/14323933/a6cd80e4-fc1a-11e5-912d-109ce779ff85.png)

**Comment by daxgames** [comment]
alias l=ls -la --color

**Comment by daxgames** [comment]
The hi-lighting is lost because 'ls' is aliased to 'ls -ls --color' and 
doskey will not use an alias in other aliases.

**Comment by TheRealBluebird** [comment]
Thank you! @daxgames

**Comment by glucas** [comment]
A potentially useful tip here is to set an environment variable with your common options and use that in your alias variants. For example:

    ls=ls %LS_COMMON% $*
    ll= ls %LS_COMMON% -la $*

Then set the variable in your shell, e.g. in cmder/config/user-profile,cmd:

    set LS_COMMON=--color=auto -H
