### ISSUE TITLE
Arrow keys in Windows 10 Linux Subsystem

### ISSUE THREAD

**Issue by sargunster** [cmderdev/cmder#919]
Arrows keys don't work when using Linux programs using the new Linux Subsystem in the latest insider build of Windows. 

1. Get the latest Windows 10 Insider build
2. Enable Linux Subsystem
3. Open Cmder
4. Run command `bash`
5. In bash, use arrow keys for command history. Doesn't work

This works fine in the standard Windows command prompt terminal emulator.

**Comment by Stanzilla** [comment]
This? https://github.com/Microsoft/BashOnWindows/issues/111

**Comment by sargunster** [comment]
Yep, same thing. Sorry I didn't see that one.

**Comment by krisbulman** [comment]
Yeah, was able to get it working in cmder with ```cmd /k "C:\Windows\System32\bash.exe"  -new_console:d:%USERPROFILE%``` but arrow keys have ceased to function.
