### ISSUE TITLE
New admin tab - startup dir not working

### ISSUE THREAD

**Issue by thany** [cmderdev/cmder#920]
When I create a new console from an existing console window, and select "run as administrator", it _always_ starts in `C:\Users\[username]`.

It doesn't matter what directory is in the "startup directory" field, it's completely ignored. It also doesn't matter if I select "new window" or not. Other options are left default.

This is on version 1.2.9, on Windows 10.

**Comment by jojobyte** [comment]
Been having this same issue, been driving me crazy. Found a workaround that is functioning for now. 

When Cmder is open and right click it in the Taskbar, then right click Cmder in that context menu and select "Properties", then select the Compatibility tab (not the Shortcut tab) and check "Run this program as an administrator". The option under shortcut does not seem to work, but compatibility does for some reason.

Hope it works for you!

**Comment by Saturate** [comment]
I'm having the same issue on windows, with the newest version.

**Comment by thany** [comment]
@jojobyte I don't want to always start it with elevated privileges. Not nearly at all.
