### ISSUE TITLE
Single instance mode not working for default term

### ISSUE THREAD

**Issue by thany** [cmderdev/cmder#925]
When I go into the settings and enable single instance mode, it isn't saved even if I click "save settings" explicitly.

Steps to reproduce:
1. Make sure cmdr is the default term.
2. Start any batch/cmd file that runs long enough to keep the window open
3. Go into settings
4. Tick "single instance mode" checkbox
5. Save settings
6. Close the term
7. Reopen the term in the same way
8. Go into settings again -> "single instance mode" will be unticked again.

And indeed, starting any program that triggers the default term will open a new window - not a new tab in an existing window.

When I start cmdr from the start menu, said checkbox is saved perfectly fine. But even after that, starting a batch/cmd will not respect this setting, i.e. it unticks the setting again.

This is Cmdr 1.2.9 on Windows 10.

**Comment by jieverson** [comment]
Same problem here

**Comment by thany** [comment]
Even with the latest version? That's astonishing.

**Comment by daxgames** [comment]
Works with the latest version.  Closing
