### ISSUE TITLE
How do I use maven(a kind of tool for java compile package manager) in cmder?

### ISSUE THREAD

**Issue by caojinli** [cmderdev/cmder#927]
I got a issue about this as title, I don't know who met this and how to fix?

**Comment by busches** [comment]
The same way you would use Maven on the normal Windows command line. https://maven.apache.org/guides/getting-started/windows-prerequisites.html

**Comment by caojinli** [comment]
I can use mvn command at windows console, but I can not use mvn in **cmder **application.

**Comment by MartiUK** [comment]
https://maven.apache.org/guides/getting-started/windows-prerequisites.html

Look at the section "Maven in PATH."

**Comment by caojinli** [comment]
Thanks, MartiUK, I absolutely say that I had added it into my path which leads me could use maven command line in my DOS. but I can not use maven command line in Cmder.

**Comment by MartiUK** [comment]
Okay, what error are you getting, since 'I cannot use maven in cmder' isn't descriptive enough.

**Comment by MartiUK** [comment]
You could also try running mvn.bat in cmder, it should work just fine.

**Comment by caojinli** [comment]
Sorry, everything works well. I don't know how it can work this time.

**Comment by Madeyedexter** [comment]
Cmder appends its own path variables before the windows defined user path variables. If your path variable exceeds the 2048 character limit, it is truncated.
