### ISSUE TITLE
git (dirty) repository status not shown in promtp since 1.3.0pre

### ISSUE THREAD

**Issue by sveggiani** [cmderdev/cmder#928]
I'm not getting the indicator of a dirty repo in the prompt since I updated to 1.3.0pre.

The command I think it's getting executed is `git diff --quiet --ignore-submodules HEAD 2>nul` but in my current instalattion returns:

```
fatal: ambiguous argument '2': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

I'll try to obtain a command that works and commit it as a fix later.

**Comment by janschulz** [comment]
See https://github.com/cmderdev/cmder/pull/971
