### ISSUE TITLE
Full screen cmder behind taskbar

### ISSUE THREAD

**Issue by michaldudak** [cmderdev/cmder#929]
When I enter full-screen mode with alt-enter, the commander window is rendered behind the taskbar. I'd prefer to have the taskbar disappear completely (like in the case of standard Windows' cmd window). I'm using Windows 10 (build 10586)

![image](https://cloud.githubusercontent.com/assets/4696105/14743187/a0cb710a-08a0-11e6-8f0b-b392edfc9bfb.png)

**Comment by Jackbennett** [comment]
@Maximus5 any suggestions?
