### ISSUE TITLE
git directory error

### ISSUE THREAD

**Issue by dassio** [cmderdev/cmder#930]
whenever i was in a git cloned directory, and issue an command, cmder seems to run the `.git` directory as a batch file(the tab shortly changes to git.exe) and gives an error `ipinput`.

**Comment by Jackbennett** [comment]
The tab name is changing because there's a snippet of code that takes the `git status` info to print in your repl the branch/staging state every line.

If it's still doing it can you post more info about the git repo and the console output. possibly your own `git status` output.
