### ISSUE TITLE
How to add blank lines, when monitoring log file with "tail.exe"

### ISSUE THREAD

**Issue by arnisjuraga** [cmderdev/cmder#931]
Very similar to this one: [Inserting blank lines in powershell console](http://stackoverflow.com/questions/28338844/inserting-blank-lines-in-powershell-console)
If I use a command:

`tail -f some-logfile.log`

then its super handy to have ability to "mark" a space between previous and next log entries, while monitoring.

In Linux systems it's easy - just hit Enter, while monitoring file. 

In Windows - cmder does nothing, if I press Enter. 

Is it possible to "add blank lines" while following `tail -f` output?

**Comment by busches** [comment]
Tail is provided by git, `cmder\vendor\git-for-windows\usr\bin\tail.exe`. Can you do what you're asking in git bash? If not, the problem lies in the git package, not cmder.

**Comment by Jackbennett** [comment]
if the git tail.exe doesn't do it, the powershell way doesn't do it, then I suspect it's to do with how the windows console wants to eat input when there's a process running.

**Comment by arnisjuraga** [comment]
It does not "work" in Git Bash MINIGW**32**, but it works in MINIGW**64**.
Although - MINIGW64 "listens" to "ENTER" key and adds blank lines during `tail -f `, bu it's kind a "queuing" inputs and after `CTRL+C` it's executing these Enters.

Looks like this:
![image](https://cloud.githubusercontent.com/assets/2185289/15206516/70ca1a14-1828-11e6-9e31-f9e3a1bf97d3.png)

**Comment by rojagit** [comment]
why on earth Ctrl+C ?? It just killed the process.
