### ISSUE TITLE
git commit can't surport Chinese

### ISSUE THREAD

**Issue by codesboy** [cmderdev/cmder#932]
like this:
$ git commit -m "更新"
on github will Chinese garbled 
what i need do?

**Comment by Jackbennett** [comment]
Is this ok in any cmd.exe or powershell.exe console? Just to rule out git itself.

**Comment by codesboy** [comment]
It's ok in gitbash

**Comment by mrRosset** [comment]
Try #985

**Comment by codesboy** [comment]
#1070 this can fix the file path problem
