### ISSUE TITLE
Cmder minimizing when losing focus.

### ISSUE THREAD

**Issue by Tadimsky** [cmderdev/cmder#934]
In 1.3.0, when Cmder loses focus, it minimizes immediately. I'm seeing this on 4 different computers.
Is this a known issue? Going back to 1.2.9 fixes the issue.

This is on Windows 10 Insider builds.

**Comment by daxgames** [comment]
Nope have not seen this.

**Comment by Jackbennett** [comment]
In the ConEmu settings `win + alt+ P` under Main > Task bar there is a tick box "Minimize on focus lose (not in Quake Style)"

You don't have that ticked do you? I just downloaded the pre-release it's not a default of ours.

**Comment by Tadimsky** [comment]
Hey, I just deleted the whole cmder folder and downloaded it again and it's now working totally fine. 
Really not sure what happened - it seems likely that the option was set based on the behavior. I know I didn't set it though which is weird.
I'll close this issue :hamster:

**Comment by Stanzilla** [comment]
Great to hear!

**Comment by Mahdi-Hazrati** [comment]
> In the ConEmu settings `win + alt+ P` under Main > Task bar there is a tick box "Minimize on focus lose (not in Quake Style)"
> 
> You don't have that ticked do you? I just downloaded the pre-release it's not a default of ours.

Thank You it's work for me
