### ISSUE TITLE
init.bat fails and shows {lamb} and {git}

### ISSUE THREAD

**Issue by denisz1** [cmderdev/cmder#935]
For the latest pre release
The `init.bat` fails, and the prompt is all wrong

File fails here:

    if not exist "%CMDER_ROOT%\config\settings" (
        echo Generating clink initial settings in %CMDER_ROOT%\config\settings
        echo Additional *.lua files in %CMDER_ROOT%\config are loaded on startup.
    ) 

There is another location in the bat file with the same problem.

**Comment by janschulz** [comment]
What ist the error message?

**Comment by denisz1** [comment]
**UPDATE:**

I fixed it by adding _quotation marks_. Do the following:

Change this:

        echo Generating clink initial settings in %CMDER_ROOT%\config\settings
        echo Additional *.lua files in %CMDER_ROOT%\config are loaded on startup.

To this:

        echo Generating clink initial settings in "%CMDER_ROOT%\config\settings"
        echo Additional *.lua files in "%CMDER_ROOT%\config" are loaded on startup.

And change this:

        echo Creating intial aliases in %CMDER_ROOT%\config\aliases

To this:

        echo Creating intial aliases in "%CMDER_ROOT%\config\aliases"

Then it installs and runs as expected.

**Comment by janschulz** [comment]
Ok, can you please still post the error message and also the path where you installed cmder in? I suspect that it as something to do with spaces in your path, but actually can't really understand the problem because it is just a echoed variable and not something which is used programmatically (like the `if not exist "%CMDER_ROOT%\config\settings" (` line).

**Comment by denisz1** [comment]
There was no error. It didn't run far enough to install clink. So like others have reported, the prompt said {lamb} instead of the lambda sign, and the {git} substitutions were not made. And all paths were correct. It was a brand new install.

Others have reported that it was because of an old version of clink, but that's not it. It was not running clink, because the batch file failed at those lines. Makes no sense, btu there you go. 

Win10 x64 BTW.

**Comment by janschulz** [comment]
> There was no error. 

No error message at all when you opened a new cmder window? Also: what is the full path to your cmder install location (e.g. in my case: `C:\Users\jschulz\Dropbox\Programme\cmder\Cmder.exe`)?

**Comment by denisz1** [comment]
No, no error. But clink didn't run, so the macros were not expanded, and the shell was not "upgraded" in the cmder style.

`c:\Program Files (x86)\foo\bar\cmder\Cmder.exe`

**Comment by denisz1** [comment]
Obviously this is not just me, and obviously the fix works for others too, see @ElonLiu.
I'll leave this open until it's fixed and closed by one of the devs.

**Comment by janschulz** [comment]
Can you try this here: https://ci.appveyor.com/project/MartiUK/cmder/build/1.0.267-development/artifacts

**Comment by janschulz** [comment]
Could you also do me a favor and remove the `@echo off` at the start of the failing init.bat and report the output here? I can't reproduce in a `c:\temp\test test\` dir :-(

**Comment by denisz1** [comment]
I get the same as @ElonLiu:

    "\cmder\config\settings was unexpected at this time"

Also, for me its installed in a path with spaces: `...\Program Files (x86)\...`

**Comment by janschulz** [comment]
Ok, I think I found the problem: if the path has parentheses in it, it fails: `C:\temp\test (test)` does not work in the old version and in the current version, it still gives an error somewhere:

```
Enhancing PATH with unix commands from git [C:\Program Files\Git]
"\config\user-aliases.cmd" kann syntaktisch an dieser Stelle nicht verarbeitet werden.
```

**Comment by janschulz** [comment]
See https://github.com/cmderdev/cmder/pull/941 for more such changes...

**Comment by Stanzilla** [comment]
I'm not sure this helps at all, in addition it errors for every user alias in the user file:

```
Enhancing PATH with unix commands from git [C:\Users\Benjamin\AppData\Local\Atlassian\SourceTree\git_local]
'e.' is not recognized as an internal or external command,
operable program or batch file.
'gl' is not recognized as an internal or external command,
operable program or batch file.
ls: cannot access '=ls': No such file or directory
ls: cannot access '$*': No such file or directory
pwd: ignoring non-option arguments
/c/Users/Benjamin

'history' is not recognized as an internal or external command,
operable program or batch file.
'unalias' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by denisz1** [comment]
awesome :smiley:

**Comment by BrainCrumbz** [comment]
Hello there

we tried the 1.0.267 mini zip, and `{lamb}`, `{git}`, `{hg}`, `cmder\config\settings` issues disappeared. But now we see (translated from italian):

> INFORMATION: cannot find any file corresponding to indicated search criteria.
> \cmder\config\user-aliases.cmd unexpected.

Is there any newer CI build output we can try? Thanks for this great software!
