### ISSUE TITLE
"\cmder\config\settings was unexpected at this time" and {lamb} is shown instead of lambda symbol

### ISSUE THREAD

**Issue by ElonLiu** [cmderdev/cmder#937]
This happened since I downloaded the newest version and copied my old `aliases`, `ConEmu.xml` and `settings` file into the new config/ folder. I thought maybe I shouldn't have copied the `settings` file. But even though I deleted it, things are still the same.
Strangely, if I move the whole cmder to a different location, everything goes well. But it will not work in my previous location. Should I clean anything and where?

**Comment by ElonLiu** [comment]
Sorry. This issue seems similar to issue #935 and I fixed it according to @denisz1 

In addition to @denisz1's modifications, another modification may be as well needed: (Line 31)

Original:
`echo Additional *.lua files in %CMDER_ROOT%\config are loaded on startup.`

Should be:
`echo Additional *.lua files in "%CMDER_ROOT%\config" are loaded on startup.`

**Comment by janschulz** [comment]
Can you try this here: https://ci.appveyor.com/project/MartiUK/cmder/build/1.0.267-development/artifacts
