### ISSUE TITLE
How to update the SSL CA Bundle for cURL

### ISSUE THREAD

**Issue by predatorian3** [cmderdev/cmder#938]
I have a ca-bundle.crt that I downloaded with the latest trusts using the mk-ca-bundle.vbs script from a different version of cURL. That version works, however, when I drop that file into any directory in Cmder, the vendored version of cURL doesn't recognize it. Where should that file go, and is there a specific format it needs to be in?

**Comment by silverham** [comment]
I was able to get the custom zscaler certificate (base64 PEM formatted .crt file) recognized by openssl by:

1. Putting it into:
`C:\path\to\cmder\vendor\git-for-windows\etc\pki\ca-trust\source\anchors\zscaler-root.crt`

Note that i had to create `source` and `anchors` folders.

2. Run `update-ca-trust` (see [upstream source?](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-ca-certificates/update-ca-trust) but should be like [this one](https://github.com/msys2/MSYS2-packages/blob/master/ca-certificates/update-ca-trust) instead?)

3. Copy the updated files to the folder location trusted by `openssl`.

[in cmder/git-bash terminal]
`cp /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem  /usr/ssl/cert.pem`

and optionally:
```bash
cp /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem /usr/ssl/certs/ca-bundle.crt
cp /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt /usr/ssl/certs/ca-bundle.trust.crt
```

4, Then test:

`openssl s_client -showcerts -servername www.google.com -connect www.google.com:443 < /dev/null | head`

See output: (Note: "depth 3" is present  and no "unable to get local issuer certificate" error - yay!)

> depth=3 C = US, ST = California, L = San Jose, O = Zscaler Inc., OU = Zscaler Inc., CN = Zscaler Root CA, emailAddress = support@zscaler.com
> verify return:1
> depth=2 C = US, ST = California, O = Zscaler Inc., OU = Zscaler Inc., CN = Zscaler Intermediate Root CA (zscaler.net), emailAddress = support@zscaler.com
> verify return:1
> depth=1 C = US, ST = California, O = Zscaler Inc., OU = Zscaler Inc., CN = "Zscaler Intermediate Root CA (zscaler.net) (t) "
> verify return:1
> depth=0 CN = www.google.com, O = Zscaler Inc., OU = Zscaler Inc.
> verify return:1
> DONE
> CONNECTED(00000005)

If you had error, you would get:

> depth=2 C = US, ST = California, O = Zscaler Inc., OU = Zscaler Inc., CN = Zscaler Intermediate Root CA (zscaler.net), emailAddress = support@zscaler.com
> verify error:num=20:unable to get local issuer certificate
> DONE
> CONNECTED(00000005)

See also related issue: [openssl doesn't see updates from update-ca-trust #25088](https://github.com/msys2/MINGW-packages/issues/25088)


PS: I used Cmder Version 1.3.11.843
