### ISSUE TITLE
Highlight

### ISSUE THREAD

**Issue by davidcsi** [cmderdev/cmder#944]
This is NOT an issue, but I don't know where to ask for features :)
You already have "search" which highlights the word. But it would be AMAZING if it could highlight ALL words. I used this feature a lot when debugging log files (which is all the time :) )

Thanks

**Comment by vladimir-kotikov** [comment]
@davidcsi, this probably need to be implemented in ConEmu, similar to "search" feature, so you'd better ask @Maximus5 about that
