### ISSUE TITLE
Provide alternate icon colors

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [cmderdev/cmder#947]
Sample use case: I have a bunch of different environments at work, and it's super useful to have a different color-coded CMD window for each. Color-shifted versions of https://github.com/cmderdev/cmder/blob/master/icons/cmder.ico would be great.

*(I'll send a PR shortly)*

**Comment by Jackbennett** [comment]
discuss more in the PR

**Comment by babhishek21** [comment]
@JoshuaKGoldberg How do I go about using these icons?

**Comment by JoshuaKGoldberg** [comment]
I actually don't know where they're packaged with cmder; I just used my local copies. @Jackbennett ?

**Comment by babhishek21** [comment]
@JoshuaKGoldberg No. What I meant was that I know where the icons are (they are at `cmder/icons/.`), but ho do I use them for any tasks I may want to customize with an icon? 

I have a hunch it's done using the ConEmu settings page for Tasks.

![image](https://cloud.githubusercontent.com/assets/8472087/17706221/cfd4c0ec-63f8-11e6-951d-273cd16c7c5c.png)
