### ISSUE TITLE
Error when executing from a network location

### ISSUE THREAD

**Issue by alexisfcote** [cmderdev/cmder#949]
When extracting cmder to a network location and then running cmder.exe. 
There's the following error

```
U:\Programs\cmder/vendor/clink-completions/vagrant.lua:1: module 'matchers' not found:
        no field package.preload['matchers']
        no file 'C:\Windows\system32\lua\matchers.lua'
        no file 'C:\Windows\system32\lua\matchers\init.lua'
        no file 'C:\Windows\system32\matchers.lua'
        no file 'C:\Windows\system32\matchers\init.lua'
        no file '.\matchers.lua'
        no file 'C:\Windows\system32\matchers.dll'
        no file 'C:\Windows\system32\loadall.dll'
        no file '.\matchers.dll'
```

**Comment by mikeychan** [comment]
Just to add. There is a matchers.lua file under cmder\vendor\clink-completions\modules. No matter where I copy the lua files from this directory to other directories, it increases the number of modules not found messages and extends it to path.lua, tables.lua, etc.

**Comment by GitHubGeek** [comment]
I can confirm that running latest cmder 1.3.6 from a network drive still produces this error

![image](https://user-images.githubusercontent.com/265551/45278530-e02dc400-b510-11e8-99c1-da63a5cc6042.png)
