### ISSUE TITLE
Problems with latest release of intellij 2016.1.2

### ISSUE THREAD

**Issue by michaeljohnbennett** [cmderdev/cmder#953]
There was a security patch issues in the last few days which seems to break running cmder as the terminal.

Cmdline I'm using is: 

`cmd.exe /K "c:\dev\cmder\vendor\init.bat"`

Using doubled quotes is the same.

I get the following error:

java.io.IOException: Couldn't create PTY

**Comment by nach-o-man** [comment]
You should check [this](https://github.com/cmderdev/cmder/issues/282#issuecomment-219684282) thread.
