### ISSUE TITLE
proecss "ConEmu.exe" remains running after I exit cmder

### ISSUE THREAD

**Issue by THaGKI9** [cmderdev/cmder#956]
This case confuse me so much.
As i click the exit button in the top right corner, the cmder window disappear but process "ConEmu.exe"  is still running.
But sometimes process "ConEmu.exe" exits as cmder exits.

Additionally, if I start more than one cmder at the same time, and all processes "ConEmu.exe" won't exits even when I close all cmders.

**Comment by MartiUK** [comment]
What version of cmder are you running?
