### ISSUE TITLE
ConEmu Injecting hooks fail

### ISSUE THREAD

**Issue by huangzhiyang166** [cmderdev/cmder#958]
ConEmuC.W, PID=10156 Injecting hooks init PID=6924 FAILED, code=-732:0x00000005

**Comment by Jackbennett** [comment]
What have you got system-wize as well as anti-virus? Could something be trying to protect the process like EMET? What location are you running cmder from?

**Comment by huangzhiyang166** [comment]
my computer installed a anti-virus software, may be that the software to protect the process, and now I uninstall the anti-virus software and it work, thank you very much!!
