### ISSUE TITLE
Launcher is not recognized as a valid Win32 application on windows XP.

### ISSUE THREAD

**Issue by samvasko** [cmderdev/cmder#96]

**Comment by vfiset** [comment]
@secrettriangle same here, did you find any workaround?

**Comment by secrettriangle** [comment]
No :/

**Comment by vfiset** [comment]
Hi @bliker, I am experiencing the same issue with v1.1.4.1. Is there something I am missing?

**Comment by MartiUK** [comment]
@secrettriangle @vfiset Your problems should be fixed now: 5dbb84d78be695bf7630a09c68e5b3d93e805f01

**Comment by vfiset** [comment]
how can I build the dev branch? I am imcompetant when it comes to windows stuff. I don't see any hints in the doc.

**Comment by Jackbennett** [comment]
Run powershell.exe and cd into cmder/scripts and `get-help .\build.ps1 -full` should tell you plenty.

**Comment by Jackbennett** [comment]
or use `get-help .\build.ps1 -detailed` would be a more appropriate amount of output.
