### ISSUE TITLE
Cmder proxy Ubuntu Bash on Windows

### ISSUE THREAD

**Issue by leocavalcante** [cmderdev/cmder#964]
Cmder is a ConEmu shell that proxies cmd.exe or PowerShell, am I right?

If so... any tips on how to make it proxy Ubuntu Bash on Windows?
I have it already running, but its a very poor console, no Ctrl+V, no colors, no macros... I want to use Cmder with it, its possible?

**Comment by Jackbennett** [comment]
I've not run it myself but I suspect you just want to add another task to conEmu for it and what you desire should be injected. 

ConEmu settings -> Tasks -> Add it.

**Comment by leocavalcante** [comment]
Awesome! Thanks.
