### ISSUE TITLE
Error when right click "cmd here" in drive letter directory such as "D:/"

### ISSUE THREAD

**Issue by zxcbryanfury** [cmderdev/cmder#965]
Error msg below:

`Set-Location : Illegal characters in path.
At C:\Program Files\cmder_mini\vendor\profile.ps1:59 char:5
-     Set-Location -Path $Env:CMDER_START
-     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidArgument: (D:\":String) [Set-Location], ArgumentException
  - FullyQualifiedErrorId : ItemExistsArgumentError,Microsoft.PowerShell.Commands.SetLocationCommand

Set-Location : Cannot find path 'D:\"' because it does not exist.
At C:\Program Files\cmder_mini\vendor\profile.ps1:59 char:5
-     Set-Location -Path $Env:CMDER_START
-     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : ObjectNotFound: (D:\":String) [Set-Location], ItemNotFoundException
  - FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand`

**Comment by Jackbennett** [comment]
@MartiUK Does the `\` in at the end of the drive letter escape something stupid in the string in the launcher [here](https://github.com/cmderdev/cmder/blob/160fbad621f33fe3c2d1e61d86ef42097ba3dace/launcher/src/CmderLauncher.cpp#L160)? 
`$env:CMDER_START` is set as `U:"`
