### ISSUE TITLE
git checkout autocomplete is showing files

### ISSUE THREAD

**Issue by luisrudge** [cmderdev/cmder#966]
```
c:\git\oss\spectacle-editor (master) (spectacle-editor@0.0.1)
λ git checkout ma [TAB] [TAB]
main.development.js  master
```

`main.development.js` is a file, `master` is a branch. It should show only `master`

**Comment by vladimir-kotikov** [comment]
It works as intended - see https://git-scm.com/docs/git-checkout

> **git checkout [-p|--patch] [<tree-ish>] [--] <pathspec>…​**
When <paths> or --patch are given, git checkout does not switch branches. It updates the named paths in the working tree from the index file or from a named <tree-ish> (most often a commit).
