### ISSUE TITLE
After using up and down arrows, a 'c' leaves on the command line and cannot delete it.

### ISSUE THREAD

**Issue by Rushera** [cmderdev/cmder#968]
1. Extract and open cmder.exe for the first time.
2. Input `cd /d d:\workspace\`
3. Press up arrow, then down arrow.
4. Here comes the 'c' that I cannot delete.
5. Appears every time I use up and down arrow key.
![2016-05-30 00_10_29-cmder](https://cloud.githubusercontent.com/assets/9796128/15634675/36e83a24-25fc-11e6-976e-5b5052ac962e.png)

**Comment by Stanzilla** [comment]
https://github.com/mridgers/clink/issues/387
