### ISSUE TITLE
package.json removed - but Cmder still shows name and version from package.json

### ISSUE THREAD

**Issue by GeryS** [cmderdev/cmder#969]
The folder has not .git repo and has not package.json .... . Althought this Cmder shows name & version from package.json, which was deleted. Where Cmder found this data ?

**Comment by Jackbennett** [comment]
I've just tried this in 1.3.0-pre and as soon as I remove the package.json I lose the prompt message. 

Do you think you could give me some steps you've found to reproduce it?
