### ISSUE TITLE
Text color not honored upon restart

### ISSUE THREAD

**Issue by Piscean** [cmderdev/cmder#97]
Under Features/Colors, I've changed the value for Text to # 3, which is a greenish blue, and the value of Back to # 0, which is black.  The screen updates to greenish blue text on black.  Save settings.  Exit.  Restart cmder and the text is now white on black.  The value for Back is being honored, but the value for Text is not.

**Comment by Jackbennett** [comment]
Just tested @Piscean stepps from the current dev channel clone and build. Works as expected and the text color stays at # 3

**Comment by losandes** [comment]
There are two reasons that I am aware of that can cause this issue:

1. Your user account doesn't have permissions to the `%ConEmuBaseDir%\config\ConEmu.xml` file. 
    * For instance, if you install cmder with chocolatey (`choco install -y cmder`), it will be installed into `C:\tools\cmder`. Editing any file in that directory will require admin privileges. 
2. You can _apply_ some settings without _saving_ them. Make sure you click _Save Settings_ in the bottom right corner after making your changes.

To check if you have permissions to save your settings, open the _Settings_ dialog. Change the font size or something. If _Save Settings_ is still disabled, then you don't have access to save the ConEmu.xml file.

There are multiple ways to fix this. The simplest is just to export or copy the ConEmu.xml file to your desktop. Then copy it back to `%ConEmuBaseDir%\config\ConEmu.xml`. You will be prompted to use admin privileges when writing the file. After that, your user should be able to save settings.

> On a related side note - I think it would be better to have the apply and save buttons in the same vicinity. Because _apply_ is separated from the _Save Settings_ button by a fair distance, it's possible that many users will make the mistake of not saving but thinking that they have.
