### ISSUE TITLE
Can't use PSReadline's Ctrl+Alt+Shift+/ (Ctrl+Alt+?) in Cmder

### ISSUE THREAD

**Issue by dragon788** [cmderdev/cmder#970]
I don't have anything mapped to this and I'm running the default Powershell task in Cmder but it fails in Cmder and works in regular Powershell.

Looking at the Keys page I couldn't find anything exactly mapped to this, so I'm uncertain why this isn't working.

This also seems to be affecting my Ctrl+Space "autocomplete" enabled by PSReadline.

**Comment by Jackbennett** [comment]
Affecting ctrl+space how? That's working perfectly well for me. 

I'm just wondering if the rest is related to using ctrl+alt I think conemu might be eating it.
