### ISSUE TITLE
right click context menu open cmd without color

### ISSUE THREAD

**Issue by eromoe** [cmderdev/cmder#972]
I use `Integration -> ConEmu Here` to register context menu.
But it just open a cmd without color.

**Comment by Jackbennett** [comment]
Do you mean you have ran `.\cmder.exe /REGISTER USER` and now see "Cmder Here" with our icon in the right click menu, not shift+right click menu? That "cmder here" option just opens cmd.exe without any colours?

**Comment by eromoe** [comment]
`settings->Integration -> ConEmu Here `
Seems it just register `ConEmu `, not Cmder.  
Use .reg (wiki recommand) success

**Comment by Jackbennett** [comment]
Ah yeh that page is conemus own thing. there isn't a config we can set for that it seems to be generated from a default in its code if a registered menu item isn't already found. We had to make our own.
