### ISSUE TITLE
Automatically start a new console when restoring from the system tray

### ISSUE THREAD

**Issue by bdr99** [cmderdev/cmder#976]
I currently have cmder configured to automatically minimize to the system tray if the "X" is clicked. It also terminates all consoles. When I press Ctrl+` or click on the icon in the tray to restore cmder, there are no consoles running.

Is there a way to make cmder not terminate all consoles when the "X" is clicked, just go to the tray, leaving the consoles running? If this is not possible, then is it possible to, when cmder is restored the tray and no consoles are running, automatically start a new console? This would eliminate an extra step.

**Comment by Jackbennett** [comment]
I don't know how you are doing this.

From default all I can see to set is `Main > Task bar > Auto minimize to TSA` doing that and using minimize naturally just moves it to the system tray. If I click close `X` it closes the whole program.

To put cmder in the system tray and leave everything running you then click the minimize `_` button not close `X`

If you need further help, what other settings have you changed to get this behavior?

**Comment by bdr99** [comment]
Thank you for your reply. Here is a screenshot of my "task bar" settings section:

![cmder](https://cloud.githubusercontent.com/assets/2292715/15881987/dab3ee6a-2d08-11e6-842c-5c44c2f807ee.png)

I would like the minimize button to simply minimize cmder to the _task bar_, and the close button to minimize it to the system tray, without closing the console that I currently have open. This way, if I am actively using cmder, I can keep it open in my task bar, otherwise, I can minimize it to the system tray to get it out of the way, but still available when I need it. This is what I consider to be the normal purpose of the task bar and system tray in Windows. If I wanted to fully quit cmder, I would right click on the system tray icon and close it there. Many other applications behave this way (or can be configured to behave this way), such as Skype, TeamViewer, and KeePass.

**Comment by Jackbennett** [comment]
```
Settings > Main > Task Bar;
  Auto minimize to TSA = False
  Minimize on closing last tab = True
  Hide to the TSA = True
```

And you want to be right-clicking the closing X

- minimize  = cmder sits on task bar
- R-click X = cmder is minimized to TSA with currrent sessions open
- left click X = cmder will close all tabs and go to the TSA. 

Downside is when opening cmder from the TSA again you will have conemu with no tabs open as the X closed them all.

@Maximus5  Isn't there a way to have conemu always keep at least 1 certain tab task running. To auto open after close? Perhaps an option for X to close all but active as a shortcut.
