### ISSUE TITLE
ssh_config file is trying to locate into /etc/ssh/

### ISSUE THREAD

**Issue by ymoriaud** [cmderdev/cmder#978]
Hi everyone ! :)

I just get an issue with my _ssh_config_ file.
When I try to connect with ssh by specifying a hostname, it can't resolve it. So I enabled debug output and here is the debug line:

`debug1: Reading configuration data /etc/ssh/ssh_config`

My config file is located into my user folder `%USERPROFILE%\.ssh\ssh_config` and not into `/etc/ssh/ssh_config`. Besides I don't have any `/etc` folder but the default ssh folder into `%CMDER_ROOT%\vendor\git-for-windows\etc\ssh`

Is there something I'm doing wrong ?
How can I see why is it trying to locate it into `/etc` instead of `%USERPROFILE%`, `%HOME%` or `%CMDER_ROOT%\vendor\git-for-windows` ? And how can I change it ?

I'm using the Cmder pre-release 1.3.0. I also try with the previous version but with out any success.

Thank you !!

**Comment by ymoriaud** [comment]
Hi !

Does someone has any idea to help me to solve it ?
Do not hesitate if my explanation are not precise enough :)

Thank you !

**Comment by ntinkler** [comment]
Fairly late to the party, and I'm guessing you've resolved already, but by default cmder will look for the config file in 
/etc/ssh/ssh_config
and
%USERPROFILE%\.ssh\**config**

Note the lack of "ssh_" in front of the local config file.

**Comment by ymoriaud** [comment]
Never too late ! :D 

Thank you very much @ntinkler ! It works pretty well !
