### ISSUE TITLE
When cmder opened in visual studio code, there is wrong path

### ISSUE THREAD

**Issue by kaermorchen** [cmderdev/cmder#981]
Hello.

I work in Visual Studio Code and it's have external terminal. 
If press Ctrl + Shift + C, terminal had opened with the path project.
But when I have changed setting:
```
{
	"terminal.external.windowsExec": "Cmder"
}
```
Cmder has opened and it's has wrong path - C:\Users\Admin

**Comment by SimonCapewell** [comment]
I've got this working by dropping the _-new_console:d:%USERPROFILE%_ from the startup command for the default task. It now looks like _cmd /k "%ConEmuDir%\..\init.bat"_

**Comment by kaermorchen** [comment]
@SimonCapewell Thank you for help. It works.

![2016-08-16_19-59-18](https://cloud.githubusercontent.com/assets/11972062/17708061/ef9c957e-63eb-11e6-835a-fac38f3cbf82.png)

**Comment by tyler36** [comment]
This was working for in Visual Studio yesterday.
```
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
    "terminal.integrated.shellArgs.windows": [
        "/k",
        "%CMDER_ROOT%\\vendor\\init.bat"
    ],
```

Updated to latest CMDER v1.3.4 and now terminal always opens @ %userprofile%

**Comment by hudsonsilvaoliveira** [comment]
@tyler36 Just figured it out bro. Just use this:

```
"terminal.integrated.shell.windows": "C:\\cmder\\Cmder.exe",
"terminal.integrated.shellArgs.windows": ["/START", "%CWD%"],
```

**Comment by tyler36** [comment]
@hudsonsilvaoliveira  thanks for the update.
There was another issue I had (#1600) that lead to a fix that didn't require a change to my config.

Nice to know theres another option :)
