### ISSUE TITLE
default configuration does not support Chinese named file listing with ls

### ISSUE THREAD

**Issue by jimmy-yao** [cmderdev/cmder#985]
default configuration does not support Chinese named file listing with ls
OS:Windows10
Cmder:1.3.0-pre

![ls-dir-cmder](https://cloud.githubusercontent.com/assets/8335324/15884177/10f10b98-2d81-11e6-9217-4534b8705f96.jpg)

**Comment by Heier2013** [comment]
1. Press Win+Alt+p to open *settings*;
2. Search key worrd *Environment*;
3. Add the text `set LANG=zh_CN.UTF-8`.

I found this way by watching mingw64 *ENV* variables.

**Comment by lueo** [comment]
Work for me! Thanks @Heier2013

**Comment by codesboy** [comment]
I have set up a set of LANG = zh_CN. Utf-8，use **ls** can see normal file name, but the file path can't display properly.
Another problem is the first time open cmder client And switch the file path will go wrong

OS:win7 x64
cmder:1.3.0
@Heier2013

**Comment by Heier2013** [comment]
@codesboy 
1. In my case,i don't get any character encoding issues after set environment variables,you can try to uncheck the **Monospace** options;
2. I think you should view the error info first or reinstall *cmder*.

**Comment by jing2si** [comment]
@codesboy #1070 this can fix the file path problem

**Comment by codesboy** [comment]
perfect,It works.Thankyou.

**Comment by Michael728** [comment]
I have the same problem,and `Add the text set LANG=zh_CN.UTF-8.`,but it doesn't work

**Comment by codesboy** [comment]
@Michael728 You need this  #1070

**Comment by janschulz** [comment]
@codesboy I don't think so: `ls` is (usually) from the git-for-windows package. #1070 only fixes the garbled unicode letters in the current working dir (in the line before the lambda prompt -> the `D:\` in the above screenshot).

It would help to see where the error comes from:
* execute `where ls.exe` to get the full path to `ls.exe`
* open a normal cmd window, switch to the same dir and execute the full path to ls.exe

-> if the same error happens than ls.exe is the problem

Then try in the same cmd window `set LANG=zh_CN.UTF-8` and reexecute the `ls` call. If that works, then you can add the `set ...` call to `<cmder>\config\user-profile.cmd` or use https://github.com/cmderdev/cmder/issues/985#issuecomment-227387888 but do not use `set LANG=zh_CN.UTF-8` but only `LANG=zh_CN.UTF-8` (without the `set`)

**Comment by mbirth** [comment]
Just for the record, the locale `set LANG=en-GB.UTF-8` or `en-US.UTF-8` both didn't work for me as there don't seem to be any locales installed here. But `set LANG=C.UTF-8` brought the desired effect and made umlauts appear in e.g. the `ls` command.

**Comment by jdhao** [comment]
It works for me by using `set LANG=zh_CN.utf8`.

**Comment by chjiyun** [comment]
@jimmy-yao @mbirth @jdhao  the best way to solve this problem is to modify the file (\Cmder\vendor\conemu-maximus5\ConEmu) ,search the keyword "EnvironmentSet"  and add a new line:
```
<value name="EnvironmentSet" type="multi">
    <line data="set PATH=%ConEmuBaseDir%\Scripts;%PATH%"/>
    <line data="set LANG=zh_CN.UTF-8"/>
</value>
```
