### ISSUE TITLE
Clink completion failing

### ISSUE THREAD

**Issue by Naushi** [cmderdev/cmder#987]
I just found out that if clink was failing to show the correct strings for the prompt (`{git}, {lambda}` etc...) it was because it detected a package.json file in the folder I was accessing, and since this file didn't specify the version of the package (one freshly created with Yeoman), clink just gave up with a 
```
...gram Files\cmder/vendor/clink-completions/npm_prompt.lua:11: attempt to concatenate local 'package_version' (a nil value)
```
**Adding "version":"1.0" in the package.json file actually solved the issue but it would be cool if clink handled that better!**

I don't know if it depends on something cmder does or if I should contact the clink devs directly, sorry if it's not where I should post.

**Comment by pleverett** [comment]
You can also get rid of the error by opening the file "npm_prompt.lua" and replace line 11 with the following:

        local package_string = ''
        if package_version ~= nil then
          package_string = color.color_text("("..package_name.."@"..package_version..")", color.YELLOW)
        else
          package_string = color.color_text("("..package_name..")", color.YELLOW)
        end

**Comment by Stanzilla** [comment]
@vladimir-kotikov that's fixed already, right?

**Comment by vladimir-kotikov** [comment]
Yup, fixed in https://github.com/cmderdev/cmder/commit/75deb4f94544e299d2920b357bb5cbf0cf96c8ab
