### ISSUE TITLE
Lack of Proxy Setting

### ISSUE THREAD

**Issue by ykh** [cmderdev/cmder#989]
Hi
I need using cmder through proxy (because of some restriction on my network and failed to get some github libraries from repos)
I had lots of search, nothing found about proxy setting in cmder.
Any solution?
Tnx

**Comment by daxgames** [comment]
In cmder session:

Set http_proxy=http://[proxy]:[port]
Set https_proxy=http://[proxy]:[port]

In bash session:

export http_proxy=http://[proxy]:[port]
export https_proxy=http://[proxy]:[port]

In PowerShell session:

$eng:http_proxy=http://[proxy]:[port]
$eng:https_proxy=http://[proxy]:[port]

You can also add these commands to a proxy.cmd, proxy.sh, and proxy.ps1 
script in the [cmder]\config\profile.d folder to set the proxy on every 
session start.

**Comment by ykh** [comment]
It works. Tnx @daxgames :)
BTW I think cmder needs some interface about proxy settings.

**Comment by daxgames** [comment]
What I told you is it.  This is the way to use proxy in Windows and Linux consoles.

**Comment by kopf** [comment]
How does one best add exceptions (e.g. `localhost,127.0.0.1`) when the proxy is defined by environment variable like this?

**Comment by Jackbennett** [comment]
you would set `no_proxy` just like you commented

**Comment by digeomel** [comment]
With cmder 1.3.14, I have both `http_proxy` and `https_proxy` set as environment variables (not in the cmder command prompt or a batch file as suggested above), but it fails. The environment variables are there, you can see them in the command prompt (in all shells, including bash). Maybe it has something to do with self-signed certificates or missing certificate authorities?
