### ISSUE TITLE
After auto-update git/hg indication and lambda in prompt are broken

### ISSUE THREAD

**Issue by sanderkerel** [cmderdev/cmder#990]
After auto-update to ConEmu 160609 [32], the git/hg indication and lambda in prompt are broken. I only got {git}{hg} and {lamb}. I found an older issue (https://github.com/cmderdev/cmder/issues/279) that indicated a clink update might help.

In my cmder_mini\vendor\clink was clink v0.4.4. I upgraded that to a fresh clink v0.4.7

That fixed the issue, I got my git branch indication back, and my λ.

**Comment by raffian** [comment]
I concur with @sanderkerel, after last two auto-updates prompt went totally wacko; upgraded to clink 0.4.7, extracted to cmder/vendor/clink, restarted cmder, back in business LIKE A BOSS.

**Comment by n-s-k** [comment]
+1

**Comment by Stanzilla** [comment]
Good to know, guys! :)
