### ISSUE TITLE
{git}{hg} appearing in path print out rather than the values they represent

### ISSUE THREAD

**Issue by gunr2171** [cmderdev/cmder#995]
Just updated to ConEmu 160609 Stable.

![image](https://cloud.githubusercontent.com/assets/8290105/16013478/9262d4da-315b-11e6-9a8f-ce0dddd4736e.png)

Text version:

<pre>
C:\Users\hunterke {git}{hg}
{lamb} cd c:\code\Amber\amber-interface

c:\code\Amber\amber-interface {git}{hg}
{lamb} git branch
  deploy
* master
  phase-2
  sql-report
  v2
  v2-temp

c:\code\Amber\amber-interface {git}{hg}
{lamb} git status
On branch master
Your branch is up-to-date with 'gitlab/master'.
nothing to commit, working directory clean

c:\code\Amber\amber-interface {git}{hg}
{lamb}
</pre>

Is this a problem with cmder or the underlying ConEmu program?

**Comment by gunr2171** [comment]
Seems to be the same issue (or similar to) #178. PR #961 might fix this.

**Comment by Stanzilla** [comment]
@gunr2171 please update and post your clink version

**Comment by gunr2171** [comment]
Yep. Had 0.4.4. Upgraded to 0.4.7 and it's back to normal. Thanks for the quick help.

**Comment by jhonncerv** [comment]
why is this close ?? i have the same issue but i fix it creating a packege.json but i dont think this should be the proper solution

**Comment by gunr2171** [comment]
@jhonncerv I closed this issue because as soon as I manually updated my clink version the problem was solved.

**Comment by tonidy** [comment]
@Stanzilla this happened again on Clink 0.4.8. I've updated cmder to 1.3.0 and have similar issue.

![image](https://cloud.githubusercontent.com/assets/823034/16892722/3e643418-4b47-11e6-99a7-38da1b0d156c.png)
