### ISSUE TITLE
how to use clip command in the cmder? 

### ISSUE THREAD

**Issue by woshichuanqilz** [cmderdev/cmder#996]
clip command seem dosen't work in cmder? Is there a alternative? To copy content to the clipboard through the cmder command line ?

![06 14_19-46-05](https://cloud.githubusercontent.com/assets/11295355/16041627/09b8d26a-3269-11e6-9930-859309c3ef89.png)

**Comment by Stanzilla** [comment]
Works for me, which version of cmder are you using?

**Comment by mrRosset** [comment]
Not working for me either on 1.2.9 (with updated conemu and clink)

**Comment by Stanzilla** [comment]
Yeah it might be the path append/prepend change.

**Comment by woshichuanqilz** [comment]
I know how to fix it, 

copy the `clip.exe` file to the path `d:\ProgramFiles\cmder\vendor\git-for-windows\usr\bin\`

`cmder` is the folder where I install the cmder. It worked for me, you can have a try.

![06~15_08-27-46.bmp](http://7xpvdr.com1.z0.glb.clouddn.com/06~15_08-27-46.bmp)

**Comment by hmisko** [comment]
Generally it works, but `pwd | clip` doesn't. You can use `cd | clip` instead.

**Comment by heihachi88** [comment]
`pwd | clip.exe` works for me.

**Comment by dambo1993** [comment]
old topic - but for me (Windows7 64Bit):
pwd | clip -> fail
pwd | clip.exe -> fail
cd | clip -> OK!
cd | clip.exe -> OK!
So when I want to copy current path - I need to use windows CD "command".
