### ISSUE TITLE
Text cursor disappears when window resized

### ISSUE THREAD

**Issue by jakubsuchybio** [cmderdev/cmder#997]
Hi,
when I launch cmder Text Cursor looks fine and adjusting Settings works fine, but when I resize cmder window, then Text Cursor completely disappears and when I try to ```clear``` or Change settings of the cursor, nothing helps. Only closing and restarting cmder.

**Comment by Stanzilla** [comment]
Which version are you on?

**Comment by jakubsuchybio** [comment]
Near binaries I see file ```Version v1.2.9```.
Or is there another way to get version number?

**Comment by Stanzilla** [comment]
No, that's fine. Please upgrade to https://github.com/cmderdev/cmder/releases/tag/v1.3.0-pre

**Comment by jakubsuchybio** [comment]
Hm updating didn't help.
I am trying to filter out if different Win10 builds makes some difference. So far:
Win10 14366 hosted doesn't work.
Win10 10586.318 virtualized works.
Win10 14342 virtualized works.
Now I am trying to upgrade that 14342 to 14366 virtualized if it will work.

**Comment by Stanzilla** [comment]
Works for me https://gfycat.com/SneakyElasticBushsqueaker

**Comment by jakubsuchybio** [comment]
Well yeah when I run it it is fine. But when I resize the cmder window it disappears. I have issues updating that Win10 Fast VM, so I will report if that is the case later.
Here is recording from my host pc: https://gfycat.com/CreepyTestyFlyinglemur where it doesn't work.

**Comment by Stanzilla** [comment]
Uh i might be missing something, what is the problem in your vid?

**Comment by jakubsuchybio** [comment]
The blinking text cursor is visible at first start and after move, but after resizing of the window, the cursor disappears. And even after closing and starting again the cursor is gone. I wouldn't mind, but when you type some long command and you don't have that cursor and you want to make some changes, it is nearly impossible :)

**Comment by jakubsuchybio** [comment]
Ok, so my assessment about Win10 build influence regarding this issue:
build 10586.420 virtualized - no issue
build 14342.1000 virtualized - no issue
build 14366.0 virtualized - there is issue
build 14366.0 hosted (non-virtualized) - there is issue
So it seems, that new build 14366.0 has some breaking changes to cmder/conemu.

I will investigate deeper.
Ok I tried to replicate this issue in cmd.exe only and there is no issue.
So I am narrowing it to cmder/conemu.

Then I tried to start in cmder other consoles like poweshell and the issue is still there.

Now I will try this is clean conemu.
So clean portable ConEmu_160612 does not have the issue.

Ok last thing to check is version of ConEmu. 
Cmder uses version 160207.
So I also tried ConEmu_160207 and there is the same issue as in cmder!

Finally!!! So the problem is with old ConEmu used within cmder.
Could you please update cmder with newer ConEmu, so this issue would resolve?

As I tested, ConEmu_160612  doesn't have this issue, so if you could update ConEmu in cmder to 160612 it would be awesome. :)

Thanks

**Comment by Stanzilla** [comment]
Great to hear, already did that in the dev branch :)
