### ISSUE TITLE
Problems with v1.3.0-pre

### ISSUE THREAD

**Issue by rtpHarry** [cmderdev/cmder#998]
I saw in #993 the recommendation to update to the new pre-release version.

I had started getting these "new stable version" notifications all the time too so I thought that would fix things.

I deleted the folder, extracted the pre release version and ran it but now I have the same problems I used to have when I first upgrade to windows 10:

![image](https://cloud.githubusercontent.com/assets/1038062/16073347/64f43f42-32dd-11e6-8715-1701b6c79df3.png)

Left it yesterday to see if a reboot would fix it but just booted it up this morning and still getting the same problems.

I was using v1.2.9 before on Windows 10 and everything was working fine.

**Comment by rtpHarry** [comment]
I just updated my vagrant and git installs to rule that out but I'm still seeing the same `{placeholders}` throughout.

**Comment by Stanzilla** [comment]
Which clink version do you have? Just `clink`

**Comment by rtpHarry** [comment]
It's not finding it:

![image](https://cloud.githubusercontent.com/assets/1038062/16079887/aec1b986-32fd-11e6-9981-47485921e3b9.png)

I don't know what that first line means, "\cmder\config\settings was unexpected at this time.", maybe it's not getting its settings correctly. There isn't a config file tucked away outside of the main install directory is there that could be conflicting with the new install?

**Comment by Stanzilla** [comment]
All config is in the config dir, this is weird though. Haven't seen that error before.

**Comment by rtpHarry** [comment]
The're isnt a "settings" file, just these:

![image](https://cloud.githubusercontent.com/assets/1038062/16083778/2d47dc30-330e-11e6-8a47-e25574530970.png)

Which are fresh with this install. The only thing I kept from the last version was a custom .cmd in the `.\bin` but i just tried without that and still no improvement.

Could something in my path be messing it up?

Path=C:\Program Files (x86)\cmder\vendor\conemu-maximus5\ConEmu\Scripts;C:\Program Files (x86)\cmder\vendor\conemu-maximus5;C:\Program Files (x86)\cmder\vendor\conemu-maximus5\ConEmu;C:\Program Files\nodejs\;C:\Program Files\iis express\PHP\v7.0;C:\Program Files (x86)\iis express\PHP\v5.6;C:\ProgramData\Oracle\Java\javapath;C:\HashiCorp\Vagrant\embedded\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\GitExtensions\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\Microsof;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\HashiCorp\Vagrant\bin;C:\Users\rtpHarry\AppData\Local\Programs\Python\Python35-32\Scripts\;C:\Users\rtpHarry\AppData\Local\Programs\Python\Python35-32\;C:\Users\rtpHarry\.dnx\runtimes\dnx-coreclr-win-x64.1.0.0-beta4\bin;C:\Users\rtpHarry\AppData\Local\atom\bin;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\rtpHarry\AppData\Roaming\npm

**Comment by rtpHarry** [comment]
Should something be displayed when I type `clink` into the command line?

**Comment by Stanzilla** [comment]
Yeah, you have it in Program Files, that means, unless you run it as admin, it has no permission to generate the settings.

**Comment by Stanzilla** [comment]
So either move it out of there, or run cmder.exe as admin

**Comment by rtpHarry** [comment]
ah ok, each time it runs it says the "can I make changes to this computer" uac prompt and I say yes

**Comment by Stanzilla** [comment]
Well, try anyway. It might still bug out because of that. I suggest not having it on Program Files anyway.

**Comment by rtpHarry** [comment]
Woohoo :)

![image](https://cloud.githubusercontent.com/assets/1038062/16084099/578c9f48-330f-11e6-8480-9ccba63ea687.png)

I've always had it in program files since I started using it so something must have changed since the last release that stops it. 

I guess that might need to go in the release notes? Or maybe even code something in to detect that its inside `program files` and give a warning?

**Comment by rtpHarry** [comment]
Thanks for your help.

**Comment by Stanzilla** [comment]
Glad I could help and yeah we now generate the settings on the first start and that's not possible in Program Files, should probably note that somewhere

cc @MartiUK @daxgames
